### PR TITLE
[5.7] Add can() helper

### PR DESCRIPTION
**Pull request by hivokas**
This pull request adds the `can()` helper that acts similar to the `@can` blade directive.

### CODE REVIEW

**Comment by X-Coder264** [comment]
We should strive to decrease the amount of such helpers IMO, and this is doing the opposite.

**Comment by phannaly** [comment]
We already have a lot of helpers.

**Comment by antonkomarev** [comment]
@phannaly that doesn't mean that we need to keep adding them for every thing we want. They are global and this could lead to conflicts.

**Comment by phannaly** [comment]
@antonkomarev I mean we already have a lot of helpers and should not add any more unless it really useful than this.

**Comment by mfn** [comment]
No more global functions, please.

Rather: we should try to get rid of them.

**Pull request closed without merging**
