### PR TITLE
[5.7] Use container for Fire app callbacks.

### PR DESCRIPTION
**Pull request by imanghafoori1**
We can simply extend the ability of booting and booted methods to accept Class@method notation to be consistent with what the terminating callbacks can accept.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I think this would be better targetted at master.

**Comment by imanghafoori1** [comment]
Is it backward incompatible ? or it is related to versioning strategy ?!
@GrahamCampbell

**Comment by X-Coder264** [comment]
Well, you extended the method to do more than it did before so all other contract implementation will no longer be valid as they won't support `Class@method` notation so this is a breaking change and should target master.

**Comment by imanghafoori1** [comment]
@X-Coder264 Nice, Thanks for feedback.

**Pull request closed without merging**
