### PR TITLE
[5.4] Simplify built in auth

### PR DESCRIPTION
**Pull request by Kyslik**
- remove obscure ternary expression
 - method visibility change (it may show up in Laravel API doc)
 - update DocBloc (return type)

### CODE REVIEW

**Comment by taylorotwell** [comment]
I have no problem with ternary methods.

**Comment by Kyslik** [comment]
@taylorotwell neither do I.

What is this it is?
```
return a()?:b();
```
duh, its ternary operator... good question for an interview.

---

Jokes aside, anyone who implements their own `authenticated()` must know: it should return null or \Illuminate\Http\Response - to get this information you have to dig in AuthenticatesUsers.php because **API does not show** this information.

I proposed change:
 - IDE can pick up return type since `authenticated()` returns only \Illuminate\Http\Response
 - removes ternary operator (I have no problem with ternary operator, its just a bit obscure, without all of its parameters)
 - `authenticated()` is going to show up in Laravel API (as I understand)

Ultimately ternary operator should be replaced with `??` (PHP7+), at that point it is going to make sense in a first glance.

**Comment by JoostK** [comment]
This change makes sense to me, please reconsider.

**Comment by KKSzymanowski** [comment]
> method visibility change (it may show up in Laravel API doc)

Personally, I have never checked anything in the API docs, I find it a lot easier and more helpful to just `Jump to declaration`(if your're using PHPStorm) or read a chapter of the documentation.

This trait is used in a controller and in my opinion a public method on a controller suggests it handles an HTTP request. `authenticated` is a helper method, of sorts, therefore naturally it should be `protected`.

> IDE can pick up return type since authenticated() returns only \Illuminate\Http\Response

`authenticated` doesn't necessarily need to return `Illuminate\Http\Response`. It can be anything that can be cast to string(like a View instance). Because of that, it's correct to say it `@returns mixed`. You can override the docBlock in your controller and an IDE will recognize the return type correctly(at least PHPStorm does).

> remove obscure ternary expression

They become obscure when you nest them. This is perfectly fine in my opinion.
I use the `$foo = $bar ?: $baz;` syntax(omitting the second argument) all the time and I think it's much more readable than stating the returned value *explicite*. It also prevents possible code duplication and if the first argument is a method, it calls it only once.

> Ultimately ternary operator should be replaced with `??` (PHP7+), at that point it is going to make sense in a first glance.

I don't know why using `??` would make anything clearer than `?:` but the *null coalesce operator* may be more appropriate here, because `authenticated` could return `0` or `false` on purpose(don't know why though) and with the current implementation this would be ignored and the default `RedirectResponse` would be returned. But because Laravel still supports PHP 5 and also some of us still live in the dark ages where hostings don't provide PHP 7, we'll have no choice but to leave it as it is.

**Comment by Kyslik** [comment]
>Personally, I have never checked anything in the API docs, I find it a lot easier and more helpful to just Jump to declaration(if your're using PHPStorm) or read a chapter of the documentation.

I happen to use PHPStorm too, but I check (offline) [API](http://devdocs.io/laravel~5.3/api/5.3/illuminate/foundation/auth/authenticatesusers) on second display. Another use of API is when you don't have PHPStorm open and need to check XY (perhaps you are crafting an answer on stack-overflow or laracasts forum). 

>authenticated doesn't necessarily need to return `Illuminate\Http\Response`

Cool! Change "signature" of  [`sendLoginResponse(Request $request)`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L95) as well to `@return mixed` so its clear.

All the rest:  
yes, its clear if you write it with FUBAR pseudo variables but look at this:

```
return $this->authenticated($request, $this->guard()->user()) 
          ?: redirect()->intended($this->redirectPath());
```
it is not complicated to read but sure takes longer to absorb!

What I'have proposed is simple delegation of "forming the response" to `authenticated()` method which is IMHO better than code snippet above.

Cheers

**Pull request closed without merging**
