### PR TITLE
[5.6] __set_state exists in Carbon

### PR DESCRIPTION
**Pull request by kylekatarnls**
__set_state should not be overridden

### CODE REVIEW

**Comment by svenluijten** [comment]
If it shouldn't be overridden it should've been `final` or `private` to begin with. And a change in public API would normally warrant a major version bump (2.0.0) according to [semver](https://semver.org).

**Comment by olafnorge** [comment]
May we just fix it and discuss later?

**Comment by svenluijten** [comment]
@olafnorge sure, once the tests pass again.

**Comment by kylekatarnls** [comment]
Yes quick-revert here: https://github.com/laravel/framework/pull/23466

**Comment by kylekatarnls** [comment]
With Carbon version update the tests pass and so __set_state could be simply removed. So this PR is a better resolution in my opinion.

**Comment by torrancemiller** [comment]
Need this now. This brought down my dev environment. :(

**Comment by antonioribeiro** [comment]
@kylekatarnls is the usage of __set_state being tested?

**Comment by kylekatarnls** [comment]
__set_state in Carbon is exactly the same code as in Carbon and yes we tested it here: https://github.com/briannesbitt/Carbon/blob/master/tests/Carbon/InstanceTest.php#L61

**Comment by LukeTowers** [comment]
@kylekatarnls is that PR going to be backported to 5.5 LTS?

**Comment by kylekatarnls** [comment]
@LukeTowers > @taylorotwell did it.

What is the workflow for master/5.7, should it be this commit merged or should I submit an other PR?

**Comment by LukeTowers** [comment]
Awesome, thanks for the update!

**Comment by Kyslik** [comment]
This might have break something; see this [SO question](https://stackoverflow.com/q/49223434/1564365).

**Comment by GrahamCampbell** [comment]
Always submit PRs to the earliest branch on the framework. We regularly merge 5.5 -> 5.6 -> master. :)

**Comment by kylekatarnls** [comment]
@Kyslik 32bit problem, fixed in 1.24.2

**Pull request merged**
