### PR TITLE
[5.4] migrate to target

### PR DESCRIPTION
**Pull request by naugrimus**
Added an option to run migrations to a target.
This way migrations can be tested better.

it is not used to skip migrations.

```
php artisan migrate --target={target_migration}
```
other options and rollback still work as intended

### CODE REVIEW

**Comment by lk77** [comment]
i think a filter would be better that just a target.

**Comment by naugrimus** [comment]
if you use a filter, it would be possible to skip migrations. And that can never be right.

,NET and JAVA also have the target option

**Comment by tillkruss** [comment]
What's a target?

**Comment by naugrimus** [comment]
target is the migration up until you want to execute.

**Comment by tillkruss** [comment]
>target is the migration up until you want to execute.
Still don't get it. Can you explain that with an example?

**Comment by decadence** [comment]
@tillkruss You have 3 new migrations:
- table1.php
- table2.php
- table3.php

--target=table2.php will run table1.php and table2.php (until target2.php) but not table3.php as I understood.

**Comment by naugrimus** [comment]
let's say i have the following migrations:
2017_07_21_074058_create_user_table.php
2017_07_24_133039_user_level_id.php
2017_07_26_120731_user_status_log.php

during development there seems to be a problem in user_level_id.php, but it does not give errors

to test this, i wish to do a complete migration up until that point. and seed the data.
test that migration, maybe do a rollback and when everything is in order i can do a full migration run.

all i can do now is do a full run, and do a rollback. But the rollback only works when i use steps.
or maybe put the migrations i don't want to run in a different folder

**Comment by taylorotwell** [comment]
No plans to add this.

**Pull request closed without merging**
