### PR TITLE
Update Facade.php

### PR DESCRIPTION
**Pull request by draev**
Implementation with switch/case is limited for 4 parameters for static call..
As well, switch/case implementation does exact the same thing as call_user_func_array..

I propose to remove unnecessary code..

### CODE REVIEW

**Comment by lagbox** [comment]
I think this is done on purpose for performance reasons. The switch case should be faster than the `call_user_func_array`.

**Comment by barryvdh** [comment]
See https://gist.github.com/nikic/6390366

**Comment by barryvdh** [comment]
So perhaps this is better: https://github.com/laravel/framework/pull/12119

**Comment by draev** [comment]
@barryvdh fully agree with you ;)

**Pull request closed without merging**
