### PR TITLE
[11.x] Add find command

### PR DESCRIPTION
**Pull request by Muetze42**
In Laravel apps with many commands, I always have the problem that the list command is simply too long.
I therefore created a command to search the commands.

The name and description of the available commands are used for the search.

```shell
php artisan find
```

preview

With the `deep` option, the descriptions of the arguments and options are used in addition to the search.

```shell
php artisan find --deep
```

Aufzeichnung2024-05-10223329-ezgif com-video-to-gif-converter

After selecting a command that has been found, the help for the command is displayed and the following 3 options are available:
- Execute the command
- Search for another command
- Exit

The "Execute the command" option takes some getting used to for some commands. With the "make:model" command, for example, you have the option "all" and if you select this, the other options are still queried.

### CODE REVIEW

**Comment by antonkomarev** [comment]
Do we really need new extra command or we can add it to base artisan command?
`php artisan --find`

**Comment by rodrigopedra** [comment]
The `list` command accepts a namespace parameter. For example, this would liat only the `make` commands3

```bash
php artisan list make
```

Which is a much smaller list.

I do think this new command is useful, I just think it could be a third-party package.

**Comment by Muetze42** [comment]
@rodrigopedra 

The namespace arguement is known.

But if you have a lot of commands in the app namespace, it's still not very clear and you have to read a lot if you develop an app with a lot of commands.

I even developed the command as a 3rd party package for Laravel and Symfony.

Laravel actually covers almost all conceivable requirements without packages and I avoid installing packages. 
I would like to avoid having to install a package just because of a command.

If the command is integrated in Laravel, the package is for Laravel 10 and Symfony. Otherwise Laravel 11 as well.

**Comment by taylorotwell** [comment]
This could be a good package!

**Comment by Muetze42** [comment]
OK. The package was of course already prepared in parallel:

https://github.com/Muetze42/find-command

**Pull request closed without merging**
