### PR TITLE
[5.1] [Should be 5.0] Add whereNot to collection

### PR DESCRIPTION
**Pull request by lucasmichot**

### CODE REVIEW

**Comment by jaketoolson** [comment]
Interesting!  +1

**Comment by franzliedke** [comment]
How about calling these new ones `looseWhere()` and `looseWhereNot()` instead? 

@taylorotwell

**Comment by JosephSilber** [comment]
All 4 of these methods would could have been handled by [this single method](https://github.com/laravel/framework/pull/6502), and with a saner footprint if you ask me. Alas...

**Comment by GrahamCampbell** [comment]
Retargeted this to 5.0 for you. :)

**Pull request closed without merging**
