### PR TITLE
[5.6] Fire event when logger is resolved

### PR DESCRIPTION
**Pull request by mnabialek**
This will allow to easily attach additional data to logger creating LoggerResolved event listener. For example I often attach request url or artisan command and so on to get more information to track the potential problem.

### CODE REVIEW

**Comment by crynobone** [comment]
Is there any use case that that you experience not possible right now?

**Comment by mnabialek** [comment]
@crynobone I was not customizing logger in 5.6 yet (did it in previous releases) but for example how can I now add request url to all logger? I'm using `stack` as default logger and in channels I have set both `daily` and `slack` so I would like to have in both of them included request url.

**Comment by crynobone** [comment]
You can already listen to `Illuminate\Foundation\Http\Events\RequestHandled` or `Illuminate\Routing\Events\RouteMatched`.

**Comment by mnabialek** [comment]
And how does it help adding current request url to logger? In those events I don't have valid loggers instances I believe.

**Comment by crynobone** [comment]
> In those events I don't have valid loggers instances I believe.

Logger are resolved at very core of `Illuminate\Foundation\Application` construction, see <https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Application.php#L188>. While *creating logger instance* entirely depends on when it was first requested on your app which might be before or after request is resolved.

**Pull request closed without merging**
