### PR TITLE
[5.2] Replace array_except by Arr::except

### PR DESCRIPTION
**Pull request by lucasmichot**
Replace array_except by Arr::except

### CODE REVIEW

**Comment by lukasgeiter** [comment]
Is there a specific reason this isn't going into 5.1?

**Comment by lucasmichot** [comment]
@lukasgeiter, as of https://github.com/laravel/framework/pull/10069#issuecomment-135793232, seems NB changes should target 5.2

**Comment by lukasgeiter** [comment]
That's definitely not the case. I just think they didn't want to upgrade the major version of a dependency in 5.1 LTS. I don't see why these changes shouldn't be merged into 5.1.

**Comment by lucasmichot** [comment]
Waiting for @GrahamCampbell

**Comment by Sladewill** [comment]
Pretty sure @GrahamCampbell and @taylorotwell have said no Facades in the core framework in the past.

**Comment by lukasgeiter** [comment]
> no Facades in the core framework

Look again, that's no facade.

**Pull request closed without merging**
