### PR TITLE
[5.3] Fix null param issue for Http Request only method

### LINKED ISSUE #16203: Illuminate\Http\Request\Request $request->only() makes up missing attributes
- Laravel Version: v5.3.21
- PHP Version: 7.0.12
- Database Driver & Version: 10.1.18-MariaDB

### Description:
Assume the user passes the following request input:
```
[
     "name" => "Desk",
     "price" => 100,
]
```

When you execute: 
```php
$request->only(['name', 'price', 'count']);
```
you would get:
```
[
     "name" => "Desk",
     "price"  => 100,
     "count" => NULL,
]
```

However, if you do the following instead:
```php
array_only($request->all(), ['name', 'price', 'count'])
```

You now get:
```
[
     "name" => "Desk",
     "price" => 100,
]
```

For me, the second behavior makes much more sense when using it together with `$model->fill(...)`. Validation rules can tolerate not specifying attributes you don't want to edit (actually that works very well with `sometimes` filter) but it totally does not work when the attributes that are NOT in the original request now appear as `NULL`.

### Steps To Reproduce:
Above.

### PR DESCRIPTION
**Pull request by srmklive**
Fixes #16203.

### CODE REVIEW

**Comment by sisve** [comment]
This method is documented as "Get a subset containing the provided keys with values from the input data." This PR is a breaking change and the documentation will not longer be correct.

**Comment by srmklive** [comment]
@sisve This does exactly that, it only removes the keys that are not set in the request.

**Comment by GrahamCampbell** [comment]
I think the intersect method does what you want?

**Comment by srmklive** [comment]
@GrahamCampbell the issue is that when using `only` we are assuming that we will get only those parameters which we are specifying. This does get confusing sometimes that `$request->only` returns parameters which are not even available in the request.

**Pull request closed without merging**
