### PR TITLE
[5.7] Adding `RouteRegistrar` mixin to Router

### PR DESCRIPTION
**Pull request by arcanedev-maroc**

### CODE REVIEW

**Comment by taylorotwell** [comment]
I don't typically merge things without a description. What does this fix?

**Comment by arcanedev-maroc** [comment]
This is a *fix* for IDE when you're calling something `$this->middleware()` in `Illuminate\Foundation\Support\Providers\RouteServiceProvider` instead of using `Route::middleware()` (Facade).

routeserviceprovider

**Comment by arcanedev-maroc** [comment]
This is the second reason:

https://github.com/laravel/framework/blob/5.7/src/Illuminate/Routing/Router.php#L1250-L1262

cc @taylorotwell

**Comment by arcanedev-maroc** [comment]
Hi @taylorotwell, can you review this PR again ?

Thanks

**Comment by arcanedev-maroc** [comment]
OK @driesvints. Thanks :+1:

**Comment by driesvints** [comment]
@arcanedev-maroc when I said to resend it I actually meant with a clear description in the first comment. This way it's just gonna get closed again.

**Comment by arcanedev-maroc** [comment]
I've updated the description, let me know @driesvints if there is any missed info

**Pull request closed without merging**
