### PR TITLE
[6.x] Remove syncOriginal call from refresh method

### PR DESCRIPTION
**Pull request by ddzobov**
setRawAttributes method already accepts $sync argument - why not utilize it instead of implicit syncOriginal call?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What does this fix please?

**Comment by ddzobov** [comment]
> What does this fix please?

Just refactoring, nothing more :)

**Comment by GrahamCampbell** [comment]
Is the new code actually the same? Doesn't load modify attributes?

**Comment by ddzobov** [comment]
Same, syncOriginal will be called inside setRawAttributes after setting attributes

**Comment by taylorotwell** [comment]
I'm OK with current code.

**Comment by ddzobov** [comment]
> I'm OK with current code.

Why in all places this thing doing by passing true in second argument and only in this place - implicitly calling?

**Pull request closed without merging**
