### PR TITLE
[5.2] Simplify generated regex when both patterns match

### PR DESCRIPTION
**Pull request by martinlindhe**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
There might be other places where this is relevant too.

**Comment by martinlindhe** [comment]
Good point! I looked around a bit more by grepping on "pattern", but found only one obvious one in the same file as the initial commit, so I updated the pull request to include that, too.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. I think this would be better targetted at 5.1.

**Comment by taylorotwell** [comment]
Would be fine in 5.1.

**Comment by martinlindhe** [comment]
Okay, 5.1 rebase pull here https://github.com/laravel/framework/pull/10703

**Pull request closed without merging**
