### PR TITLE
[5.4] Moved tinker out to an external package

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by JosephSilber** [comment]
What's the motivation behind this?

**Comment by GrahamCampbell** [comment]
It's dependency heavy, and php-parser conflicts are becoming more and more of an issue for people these days.

**Comment by themsaid** [comment]
WHY? 😳

**Comment by GrahamCampbell** [comment]
The plan is to still have tinker in the default app structure, but it will be removable if people want.

**Comment by JosephSilber** [comment]
I can't imagine building a Laravel app without Tinker.

Maybe that's just me.

**Comment by GrahamCampbell** [comment]
> I can't imagine building a Laravel app without Tinker.

Yeh, the idea isn't to remove it from laravel, rather, just make it so that it can be removed, in order to install something else that conflicts with it. This also means that tinker can now be dropped into lumen. :D

**Comment by taylorotwell** [comment]
It would be in the default "require" so it would still ship out of the box. It would just be its own component.

**Comment by bobthecow** [comment]
>php-parser conflicts are becoming more and more of an issue for people these days.

Are they?

**Comment by bobthecow** [comment]
Oh, like #16773?

**Pull request merged**
