### PR TITLE
Fix shadowed import in RedirectResponse

### PR DESCRIPTION
**Pull request by thecrypticace**
See issue #12275

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Duplicate. Also, the import order there at the top was incorrect. Thanks anyway though.

**Comment by thecrypticace** [comment]
> Duplicate

Well, one issue and then this PR. But, I see you've fixed it. :+1: 

> Also, the import order there at the top was incorrect.

Is there a specific order here? Seemed to me like imports are by length of lines and then alphabetical in the framework.

**Comment by GrahamCampbell** [comment]
> Seemed to me like imports are by length of lines and then alphabetical in the framework.

Yes they are. That's why your order was incorrect.

**Comment by GrahamCampbell** [comment]
Alphabetical order by considering the entire string, not just the class name.

**Comment by thecrypticace** [comment]
Oh, ha, whoops. Thanks for the info.

**Pull request closed without merging**
