### PR TITLE
change the default and simple default pagination views. resolves #23254

### LINKED ISSUE #23254: Illuminate\Pagination\AbstractPaginator default view is set to bootstrap instead of default
Documentation states that by default `default.blade.php` is loaded as default pagination (https://laravel.com/docs/5.6/pagination#customizing-the-pagination-view), however `Illuminate\Pagination\AbstractPaginator` has both properties (for simple and length aware) set to:

```php
public static $defaultView = 'pagination::bootstrap-4';

public static $defaultSimpleView = 'pagination::simple-bootstrap-4';
```

### PR DESCRIPTION
**Pull request by wilburpowery**
If changing the default views was intentional, we should consider updating the documentation about the subject. 🤠

### CODE REVIEW

**Comment by wilburpowery** [comment]
Indeed it would. I think it would be good to have the contents of the bootstrap-4.blade.php file in default.blade.php. We could keep the bootstrap-4 file as a backup for anyone who changes the pagination styles and wants to go back to the default.

**Comment by wilburpowery** [comment]
Now it won't change anything for anyone. But, also now all you need to do is publish the views, edit the default file and you're ready to go. As of before, you would need to manually change the default view for the Pagination Class.

**Comment by taylorotwell** [comment]
Documentation should be updated.

**Comment by devcircus** [comment]
Maybe the "default" files should be removed now. It doesn't make sense to have files named "default" if they're not actually the default.

**Comment by wilburpowery** [comment]
I think maybe they could be renamed to custom.blade.php or something similar to serve as a template you can modify with your own styles.

**Pull request closed without merging**
