### PR TITLE
Add missing null check

### PR DESCRIPTION
**Pull request by ElfSundae**
Also may be merged into 5.4

### CODE REVIEW

**Comment by jmarcher** [comment]
I don't think that is the way __() should work

**Comment by ElfSundae** [comment]
@jmarcher Yeah, at first I think it should be:

```
 * @return string
 */
function __($key, 
```

**Comment by ElfSundae** [comment]
But the `__()` will attempt to use `trans()` if the JSON key is not found, and the code doc `@return \Illuminate\Contracts\Translation\Translator|string`, and the optional parameter `$key = null`, all these signs show that this function will return a Translator instance if the given $key is null.

ping @themsaid

**Comment by themsaid** [comment]
Docblock fixed: https://github.com/laravel/framework/commit/10c013c564b7e518640e42e97d9178f9e05ec7d9

**Pull request closed without merging**
