### PR TITLE
[9.x] Add prompt to optimize command in non-production environments

### PR DESCRIPTION
**Pull request by martinbean**
Various places in the Laravel docs say that the caching of routes etc should only be done as part of a deployment process. Yet various developers get tripped up after inadvertently running any of the `cache:*` or `optimize` commands and then wonder why things aren‘t working when they’re changing source files.

This PR adds a prompt when trying to run `php artisan optimize` in **non-production** environments. This means that any one running `php artisan optimize` during a deployment to their production environments shouldn’t be impacted (so long as they have set their `APP_ENV` value to `production`); but any one trying to run it in other environments (say `local`) will be prompted to actually confirm they want to run the command.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Couldn't this break applications deploying to staging environments where they actually do want `optimize` to run?

IMO this prompt should only display if the environment is *actually* `local`.

**Comment by martinbean** [comment]
> IMO this prompt should only display if the environment is _actually_ `local`.

Can certainly change the prompt callback to that case if you prefer as yeah, the prompt would be displayed if the environment was set to something like `staging`, `qa`, etc.

**Comment by taylorotwell** [comment]
Honestly I think I would just maybe add a comment to the output if the environment is not production - no prompt.

**Comment by MircoBabin** [comment]
I rebuild the cache a lot from scripting in my local environment. I know I have to do that when I change routes and when I introduce a new class. This additional confirmation message would only be annoying to me. At least it should be suppressable by a commandline switch.

So I agree with @taylorotwell that a message would be better.

**Comment by taylorotwell** [comment]
Yeah - I think just a comment would be sufficient.

**Comment by martinbean** [comment]
@taylorotwell Can you re-open this and I’ll change it to just an informational message instead?

**Comment by N30** [comment]
haha , I ended up here from here: https://didyoucacheyourconfig.com/ this is funny

**Pull request closed without merging**
