### PR TITLE
[5.8] Pass extra data to an API Resource

### PR DESCRIPTION
**Pull request by gdebrauwer**
## Explanation

API Resources are pretty powerful, but there's currently one thing not possible: passing extra data to a resource to alter the resource array.

This pull request adds a simple `using` function to API resources.

```php
UserResource::make($user)->using(['extra_value_key' => 'extra data that can be used to alter the array']);
UserResource::collection($user)->using(['extra_value_key' => 'it also works for a collection of an API resource']);

class UserResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'extra_data' => $this->extra['extra_value_key'],
        ];
    }
}
```

## Example

But why would you want to do that? Let me give an example.

Let's say you have an organization model, and each organization has multiple users. A user has a role within the organization, but also a global role within the application.
If you want to create a JSON response of an organization and its users, you probably want to return the organizational role of every user, not the global role.
With the added ‘extra data’ option, you can pass that extra information to the child resources. Those child resources can then use that information to change the array correctly.

```php
class OrganizationResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'users' => UserResource::collection($this->users)->using([
                'organization_id' => $this->id
            ]),
        ];
    }
}

class UserResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'role' => $this->roles->where('pivot.organization_id', $this->extra['organization_id'] ?? null)->first()->name,
        ];
    }
}
```

That's just one simple example. I think there's a lot of use cases for this. Sometimes a child resource may be influenced by a parent resource.

## Remarks

- The implementation is not breaking and completely optionally to use.
- Other people have already discussed such a feature in the past (https://github.com/laravel/framework/issues/23826), so I think it will be useful for quite a lot of people.
- I added some basic tests. Tell me if more should be added.
- I renamed existing tests and a test fixture to indicate that those are about extra metadata. I did this to avoid naming collision with the tests and test fixture that are added by this pull request.
- If (or hopefully when 😛) this gets merged, I will create a pull request to update the docs.

_(This is my first open source pull request so tell me if I did something wrong)_

### CODE REVIEW

**Comment by taylorotwell** [comment]
Pass it to the constructor of your resource.

**Comment by GuntherDebrauwer** [comment]
@taylorotwell  That's indeed the solution discussed in https://github.com/laravel/framework/issues/23826, but that won't work if you want to use the `::collection` method for example.

**Comment by arthurlauck** [comment]
@taylorotwell @GuntherDebrauwer Yeah, in static `collection` method it wouldn't work, this feature would be a nice way to do it.

**Comment by alkin** [comment]
@taylorotwell I am having the same issue here.

I can pass arguments to the Resource constructor with no problems, but i cant pass any arguments to the resources created with the `::collection` function. The only way to change the data from a ResourceCollection is to actually create the class and change inside, which is annoying when you have a lot of Resources.

This feature would allow us to keep using the static `::collection` method and pass arguments to the resources created.

**Comment by quangtran1357** [comment]
Hi @gdebrauwe, 
I have tried your way, it worked very well but it only worked when used in core JsonResource and ResourceCollection class files.
I didn't know if there was a way to use it without changing the two files above, I tried creating two new ResourceCollection and JsonResource files extend from those two files but couldn't use it.
Sorry for my bad english! 🙇

**Comment by gdebrauwer** [comment]
@quangtran1357 You have to extend and override all those classes if you want to use this. There's no other way sadly 🙁 (I think)

**Comment by quangtran1357** [comment]
@gdebrauwer thank you for reply, i understand!

**Comment by R-Kujawa** [comment]
I'm having the same issue with ::collection,` it would be great to have this functionality out of the box.

**Comment by ambroisehdn** [comment]
you can hack request
in controller you have that
`      
        request()->request->add([
            'extra_data' => [
                'foo' => 'foo-value',
                'other' => 'something',
            ],
        ]);
`
And in resource that 
`request()->get('extra_data')` or `$request->get('extra_data')`

**Comment by ignacio-dev** [comment]
This pull request was such a great idea. Why was it closed?

**Pull request closed without merging**
