### PR TITLE
[5.5] Support custom default views for error pages

### PR DESCRIPTION
**Pull request by nesk**
Laravel supports custom HTTP error pages. However, the ability to create a catch-all view would be pretty useful to display a default error page for unhandled HTTP status codes.

This PR allows developers to create a `resources/views/errors/default.blade.php` file which will be rendered if the status code of the HTTP exception has no dedicated view.

I will update the docs accordingly if this PR is merged.

### CODE REVIEW

**Comment by sisve** [comment]
This sounds problematic. How would we tell people that _some_ versions of 5.5 has these new catch-all pages, and some versions doesn't? I foresee a large amount of support issues that will be raised because they can't get it to work with their existing 5.5 installation. I would target 5.6 for this reason.

**Comment by ntzm** [comment]
@sisve New features should target the current branch, it's not a BC, it should target 5.5

**Comment by sisve** [comment]
@ntzm Do you see the problem where two people are both using Laravel 5.5, and only one of them can get the catch-all error page to work? Do you see the upcoming support questions this will create?

Just because something isn't breaking any backward compatibility doesn't mean it's a good idea to implement in the middle of a release lifecycle. This is a feature people will probably want to use, but we're very bad at communicating how they should be explicit in their composer.json files on which exact Laravel version they app requires. We tell them to use `5.5.*` after all, and it would be reasonable that all 5.5 releases would have the same features.

**Comment by deleugpn** [comment]
@sisve just like that?

**Comment by deleugpn** [comment]
@sisve that makes no sense in the Laravel release cycle. It's a silent way of saying you want semver in a framework that doesn't follow it. New features gets merged on point release all the time exactly because we advertise that breaking changes comes in the next minor release. If you look at the version as 5-5.29.0, this would make a new feature for 5-5.30.0.

**Comment by laurencei** [comment]
👎 - but for a different reason - it doesnt work intuiviely the way you think.

For example - if my errors folder in my application only contains `errors/default.blade.php` - then the `default` will *not* be used for a 500 error. That is because a default 500 page is included in the framework.

So people might think they can do just a single page to handle any issue - but the reality is you still need to provide a 404, 500, 419 and 503 page.

Sounds like a better option is just to override in your application and handle as required.

**Comment by nesk** [comment]
@laurencei Actually, the default view **will** be displayed for every exception, unless there is a more specific view (like a 419, 503, etc…). I don’t really see what you’re trying to say here.

If you want, I can create a bare repository to demonstrate how the default view handles exceptions. 🙂

**Comment by laurencei** [comment]
> unless there is a more specific view

I'm saying there is *always* a 404, 419, 500 and 503 error view - because the framework has them even if your application does not.

So default will only work for erorrs that are not any of the 4 above, which is not intuitive.

**Comment by laurencei** [comment]
Perhaps a different option is for 5.6 to remove the defaults from the framework - and place them into `laravel/laravel`. Then your `default/catch-all` option would work as expected.

**Comment by nesk** [comment]
Did you try to run Laravel with my PR? Creating your own default error page will override the 4 error views you’re talking about.

**Comment by laurencei** [comment]
@nesk - yes, clean install of Laravel 5.5 I still get the framework default `404` even with a `default.blade.php` file.

The reason is `view()->exists($view = "errors::{$status}") ` will always return `true` for `404` etc - because the view exists in the framework.

**Comment by laurencei** [comment]
@nesk - yes - clean install of Laravel 5.5.

Did you test this yourself? Because I honestly cant get it to work.

The problem is `view()->exists($view = "errors::{$status}")` will *always* return true for a `404` etc - because the view always exists (in the framework).

**Comment by GuidoHendriks** [comment]
I just tried this, I created a `errors/default.blade.php`. When I trigger a 404 it's using the built-in error page. So it does actually use the built-in ones over the default. So this PR won't allow a catch-all to be used for statuses like 404.

**Comment by devcircus** [comment]
Agree with @laurencei that this needs to be thought out more. It currently doesn't work as expected. I personally don't see the need, but everyone has different needs. So flesh it out and target 5.6.

**Comment by nesk** [comment]
@laurencei @GuidoHendriks My bad! I didn’t see that when testing today but now with your explanation its pretty clear. I will take a look on this tomorrow and rebase my commit if possible.

**Comment by GuidoHendriks** [comment]
@nesk What's the use case for this?

I would say I wouldn't really want to make any specific error pages besides the ones defined in Laravel. But in the case you get another one, locally you would get "Whoops" which is very helpful.

On production you get a generic "Whoops, looks like something went wrong." message in a red bar (see attached screenshot). That might be the only thing I'd want to change for my project, so that the generic error looks the same as the known errors on production.

screen shot 2018-01-17 at 02 10 19

**Comment by sisve** [comment]
> It's a silent way of saying you want semver in a framework that doesn't follow it.

@deleugpn In this case I'm not arguing about semver, but that adding a feature that we can expect many people to use will cause problems if only some 5.5 versions have it. How will we communicate to the users which versions has it? We would need a table somewhere that lists features and versions they were introduced. Such a table would also help package developers determine their minimum supported Laravel version.

Semver would have allowed this new feature (...ish). Sure, it would have incremented another number, but we're already incrementing numbers in our releases, so it isn't a big deal.

> New features gets merged on point release all the time exactly because we advertise that breaking changes comes in the next minor release.

And this touches another problem; we merge breaking changes _all the time_. I'm not talking about small new features, we actually merge changes to existing working code. An example is https://github.com/laravel/framework/pull/22554. These types of breaking changes, introduced in every ... (what do we call the third digit in the version number?) ... in the middle of the life of the release makes it hard to tell people that they should always upgrade to the latest version. We can't really say that, and when they run into problems say, "Yeah, we only meant that we do not introduce _large_ breaking changes. This was a small one. It didn't affect the guy that wrote the code."

But that moves the discussion back to semver (or communication), which wasn't my primary focus in my first comment.

**Comment by nesk** [comment]
@GuidoHendricks The goal is to allow the developer to customize **all** the error pages with only one Blade template, thus removing those “whoops” errors. That way, all the errors will be matching the project design.

The developer can still create more specific views for some errors, like 404.

**Comment by nesk** [comment]
@laurencei I've fixed the issues, you might want to have another look just in case. 🙂

**Comment by GuidoHendriks** [comment]
By default when a unhandled exception occurs, it will convert use a HTTP status 500 exception that will render the nice error page. But when an unhandled HTTP status code is handled, it will fallback to either `Whoops` (when available and in debug) or `SymfonyExceptionHandler`.

I would say that when not in debug, it should never fallback to `SymfonyExceptionHandler`. For unhandled HTTP exceptions I'd suggest a `unhandled.blade.php` - which is generic like the default `500.blade.php`. Could be `default.blade.php` as well, but I'd say that's more likely to cause confusion.

This way the errors shown in production are always handled consistently, and can easily be customised by creating your own `errors/layout.blade.php`, `errors/{status}.blade.php` and/or `errors/unhandled.blade.php`.

This is just a small difference from the original PR by @nesk:

```php
if (view()->exists($view = "errors::{$status}") || (! config('app.debug') && view()->exists($view = "errors::unhandled"))) {
    // ...
}
```

Besides that, a view (`unhandled.blade.php` in this case) could be created as well. But this could be up to the developer too?

**Comment by deleugpn** [comment]
I still like the concept, but implementation feels a little dirty.

**Comment by GuidoHendriks** [comment]
@nesk Not sure if my comment serves the same goal as yours after seeing your latest commit, I would say it does. If not, let me know and I'll create a separate PR for it.

**Comment by nesk** [comment]
@GuidoHendriks Not sure if you're talking about that, but in local environment, the `default` template will never be used except for HTTP exceptions. If you're in local environment and a (non-HTTP) exception is thrown, Whoop's UI page will be displayed, because the `config('app.debug')` check is already done [before running the `renderHttpException()` method](https://github.com/laravel/framework/blob/3f422993c69a053d7fd3094dd8a40f945b0b326d/src/Illuminate/Foundation/Exceptions/Handler.php#L284).

@deleugpn Could you explain what feels dirty to you?

**Comment by GuidoHendriks** [comment]
@nesk I think we agree. Unhandled non-HTTP exceptions are handled just fine, with debug on and off.

HTTP exceptions with an unhandled status code (no view), [currently fall back to either `Whoops` or `SymfonyExceptionHandler`](https://github.com/laravel/framework/blob/3f422993c69a053d7fd3094dd8a40f945b0b326d/src/Illuminate/Foundation/Exceptions/Handler.php#L312). Which is fine by me with debug on, but causes an inconsistent error for the users in production.

My proposal changes the fallback when debug is off to a `unhandled.blade.php` instead of the current `SymfonyExceptionHandler`.

**Comment by nesk** [comment]
@GuidoHendriks I had a hard time understanding what you were talking about but I think I've finally got it! I think it should be done in another PR because this is not especially related, you want to fix a behavior and I want to add a feature, these modifications should be separated.

**Comment by GuidoHendriks** [comment]
@nesk I would say what you're trying to achieve is already possible when all errors were shown consistently. Unless the point of your changes is to have a "catch-all" view for all of your errors. In that case I would probably just override `render()` in the `app/Exceptions/Handler.php`.

**Comment by devcircus** [comment]
IMO this seems like a good idea for a package. Not seeing the "improvements" to the current design. N

**Comment by taylorotwell** [comment]
Holding off on this for now.

**Pull request closed without merging**
