### PR TITLE
Allow string class names like dispatchFrom... methods.

### PR DESCRIPTION
**Pull request by danrichards**
It may be more appropriate to address this in Illuminate\Bus\Dispatcher. But this was a simpler.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This makes no sense. You have no way to pass in constructor arguments.

**Comment by danrichards** [comment]
Yes, you do. You just don't use a string.

**Comment by GrahamCampbell** [comment]
If you need to resolve dependencies from the ioc, then i'd recommend not using a self handling job, and instead, let laravel's dispatcher resolve your job handler from the container. That's how it was intended to be used.

**Comment by danrichards** [comment]
That is fine. I submitted this because the other methods allow you do pass a string and it seemed inconsistent that dispatch() could not do the same.

**Pull request closed without merging**
