### PR TITLE
[8.x] New sometimes if validation rule

### PR DESCRIPTION
**Pull request by alfonsobries**
I'm thinking that a "sometimes if" rule will be a handly addition, its a custom rule that I use a lot in my personals projects and I'm sure that is a very common problem we all have once in a while.

Use case: When we reuse a custom request class for editing and creating items

For example, let's say I'm storing a user where his name, email and password are required when storing but when editing we may only need one of the fields (lets say the user only edits the email), we can use that rule to not require the fields to be present when the user is being edited:

```
<?php

namespace App\Http\Requests;

use App\Rules\SometimesIf;
use Illuminate\Foundation\Http\FormRequest;

class UserRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            // The fields doesn't need to be present if we are editing ($this->user is
            // part of the request only when editing)
            'name' => ['required', 'string', new SometimesIf($this->user)],
            'email' => ['required', 'email', new SometimesIf($this->user)],
            'password' => ['required', 'min:6', new SometimesIf($this->user)],
        ];
    }
}
 ```

```
// So this request is valid only if updating
->putJson('users/99', ['email' => 'me@me.com'])  // Valid: Only the email will be affected

// And this one invalid since some data is missing:
->postJson('users', ['email' => 'me@me.com'])  // Invalid: Missing required data for creating
```

### CODE REVIEW

**Comment by johanrosenson** [comment]
Is this not something you could use the rule "required_if" for?

If that rule is used with a callback i think you get exactly what you are doing with your rule, correct me if i'm wrong.

https://laravel.com/docs/6.x/validation#rule-required-if

**Comment by GrahamCampbell** [comment]
Why 8.x instead of 7.x?

**Comment by alfonsobries** [comment]
@GrahamCampbell no special reason, just because is a new feature, so PR should be against 7?

**Comment by alfonsobries** [comment]
> Is this not something you could use the rule "required_if" for?
> 
> If that rule is used with a callback i think you get exactly what you are doing with your rule, correct me if i'm wrong.
> 
> https://laravel.com/docs/6.x/validation#rule-required-if

Required means that the value is not empty, that is different than a value that is not present, if we update a model with an empty value it will reset the values, actually in my example im using required & sometimes

**Comment by taylorotwell** [comment]
```php
/**
 * Get the validation rules that apply to the request.
 *
 * @return array
 */
public function rules()
{
    return array_filter([
        'name' => $this->user ? ['required', 'string'] : null,
        'email' => $this->user ? ['required', 'email', new SometimesIf($this->user)] : null,
        'password' => ['required', 'min:6', new SometimesIf($this->user)],
    ];
}
```

**Pull request closed without merging**
