### PR TITLE
[5.6] Idea for model type hinting improvements.

### PR DESCRIPTION
**Pull request by TBlindaruk**
This PR - Idea about type hinting improvements for models.

continuation of https://github.com/laravel/framework/pull/23686 

---

https://github.com/laravel/ideas/issues/284 - the issue of `idea project` about `Better type hints on magic methods`

---

If it will be ok, then I can add more method to this traits.

---

Please let me know what do you think.

### CODE REVIEW

**Comment by tillkruss** [comment]
I don't like the idea of having traits just for type hints that don't even work in all editors. Can't this be handled by an IDE plugin?

**Comment by koenhoeijmakers** [comment]
There are packages for this (`barryvdh/ide-helper` for instance), or you can just call `query()` first.

**Comment by deleugpn** [comment]
I like this idea more than the one used in Laravel-ide-helper package. This one doesn't create duplicate of files where PHPStorm complains about having the same filename twice and/or when you want to open a specific file, it finds two of it every time. 
I think it could be a cool package where you offers these traits and we use them in our base model. All models extends from our custom base model. Win-win.

**Comment by TBlindaruk** [comment]
@deleugpn ,

Ok, I will be creating an own package  - for the models `type hinting` purpose.

**Comment by TBlindaruk** [comment]
@deleugpn ,

https://github.com/TBlindaruk/laravel-idea-type-hinting

**Pull request closed without merging**
