### PR TITLE
[5.6] Update phpDoc for Broadcast Facade.

### PR DESCRIPTION
**Pull request by TBlindaruk**
- we have used `channel` method in Broadcast Facade in https://laravel.com/docs/5.6/broadcasting

### CODE REVIEW

**Comment by taylorotwell** [comment]
The PR traffic for this is getting a little crazy. It feels like it should just be auto-generated?

**Comment by TBlindaruk** [comment]
I just read the documentation of the Laravel and do improve for FW, when I see some mistake.

But I agree that it can be auto-generated. I will try to make a command for auto-generate this

**Comment by GrahamCampbell** [comment]
@TBlindaruk such a command already exists.

**Comment by GrahamCampbell** [comment]
https://github.com/barryvdh/laravel-ide-helper

**Comment by TBlindaruk** [comment]
ok, I will not do command and PR for Facades

**Pull request merged**
