### PR TITLE
[9.x] Split Conditionable into package

### PR DESCRIPTION
**Pull request by inxilpro**
This is a potential solution to #38389.

Realistically, anything that `illuminate/collections` depends on (that's also used elsewhere in the framework) is going to bump into this same issue. It's the same reason the `Macroable` trait had to be moved into its own package.

The other approach would be to just move `Conditionable` into the Collections package, but that just feels wrong to me. In the end, I decided to PR this as a solution. If you decide it's not worth breaking out another package, I'll happily re-submit the other solution.

### CODE REVIEW

**Comment by JosephSilber** [comment]
Where does it end though? The [HigherOrderCollectionProxy](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Collections/HigherOrderCollectionProxy.php) also doesn't really have anything to do with collections. It should really be called `HigherOrderProxy`, and accept any generic type.

Wouldn't it make more sense to have some catch-all package, like `Traits` or `Helpers` or whatnot, where we can store these lower level things? So `Macroable` and `Conditionable` and `HigherOrderProxy` and `HigherOrderWhenProxy` can all live in the same package together?

**Comment by GrahamCampbell** [comment]
illuminate/utils?

**Comment by inxilpro** [comment]
I like that. But at what point are  we just re-creating `illuminate/support`?

Would a better approach be to extract some things **out** of that package, and then make the collections package depend on it again? 

It feels like `illuminate/support` is exactly the right place for this kind of code.

**Comment by DarkGhostHunter** [comment]
I firmly believe `illuminate/support` should be a dependency for other packages. It's okay for `illuminate/collection` to require it.

**Comment by driesvints** [comment]
> It's okay for illuminate/collection to require it.

The entire point of illuminate/collection was that it didn't depend on illuminate/support. 

Honestly I'm beginning to think splitting illuminate/support was a mistake and we should just move everything back into one component.

**Comment by DarkGhostHunter** [comment]
At this point, for a code to have their own package, it should comply with the following:

1. Does not depend on `illuminate/support` functionality.
2. The dependent functionality can be replicated by just copy-pasting one or two methods.

For the case of `Conditionable`, if you replicate on `Collection` without the trait, it will break the trait check for conditions:

```php
if (in_array(Conditionable::class, class_uses_recursive($object)) {
    $object->when(true, ...);
}
```

In that case, you're bound to create a `Conditionable` contract. Seems very over-engineered to me.

Again, if a single part of the code requires `illuminate/support` to work, is no sin, as long is big enough (like Collections). `Conditionable` is merely a trait, not a class comprised of enough code that can't fit one screen. To me, `illuminate/support` is like a global toolbox for small utilities that can be dropped-in my project.

**Comment by taylorotwell** [comment]
@inxilpro can you resolve the conflicts on this?

**Comment by JosephSilber** [comment]
@taylorotwell what are your thoughts on this https://github.com/laravel/framework/pull/38457#issuecomment-902295865?

I would really like to eventually rename `HigherOrderCollectionProxy` to `HigherOrderProxy`. I've had many generic use-cases for it in the past.

**Comment by inxilpro** [comment]
I've resolved the conflicts. I think there are two viable paths:

1. Bring everything back into `illuminate/support`
2. Commit to "support" functionality getting split into smaller chunks over time. I don't think there's anything wrong with this, and it could be nice to have the option to just install `illuminate/proxies` and `illuminate/macroable` if that's the only "support" functionality that you need in your app.

After thinking about it a bit longer, it feels like moving away from a catch-all "support" package into more tightly scoped feature packages is a good thing. In fact, I think that in relationship to @JosephSilber's comment, it makes a lot of sense to introduce an `illuminate/proxies` package, too, that holds generic versions of various proxy objects (something like, `HigherOrderMethodProxy`, `HigherOrderObjectProxy`, `HigherOrderEnumerableProxy`, and `HigherOrderConditionableProxy`).

**Comment by taylorotwell** [comment]
Yeah I don't see what the big controversy is with splitting this out into a package.

**Comment by driesvints** [comment]
Thanks @inxilpro

**Pull request merged**
