### PR TITLE
[5.7] change doc blocks to be more descriptive

### PR DESCRIPTION
**Pull request by imanghafoori1**
Change doc blocks to be more descriptive
it now says it is an array of callables

### CODE REVIEW

**Comment by jmarcher** [comment]
I do not know if this is 100% right, event though `some_function_name` can be called using `call_user_func`, the type of the value is still `string`.

**Comment by X-Coder264** [comment]
@imanghafoori1 This should then also be changed on the Application contract.

**Comment by imanghafoori1** [comment]
@X-Coder264 Good point. thanks. I do it

**Comment by imanghafoori1** [comment]
@jmarcher those strings are considered to be php callables by is_callable() function

**Pull request merged**
