### PR TITLE
[9.x] Adds expected behavior to `where` function in query builder

### PR DESCRIPTION
**Pull request by dunhamjared**
_Coming at this with a different angle -- original: https://github.com/laravel/framework/pull/42432_

If you pass an array of values as the operator, I expect it to return rows that include those values. 

For example:

```
DB::table('users')->where('name', ['foo', 'bar']);
```

Would return users that have the name `foo` and `bar`. 

However, it only returns users that have the name `foo`.

### CODE REVIEW

**Comment by lk77** [comment]
Well it's the expected behaviour, that's how the sql where clause works

**Comment by lk77** [comment]
Well if you want you can use the equal sign :

```
DB::table('Customer')->where('City',  '=', 'Paris');
```

**Comment by dunhamjared** [comment]
@lk77 Yes, I understand that you can pass a comparison operator under the operator argument.

**Comment by lk77** [comment]
I don't like the idea of making too much assumptions on what the dev wants or does not wants,

like for example  :

```
DB::table('Customer')->where('City', $city);
```

is it a where or a where in ?

**Comment by taylorotwell** [comment]
Just call `whereIn`.

**Comment by lk77** [comment]
I understand your point of view, but your not gaining that much, you correct a potential mistake from new devs, and make the syntax a little bit shorter

**Comment by dunhamjared** [comment]
@lk77 A bunch of little gains add up. 

If we always live by "but your not gaining that much" to dismiss a change, then Laravel, and many other things in life, wouldn't be where it is today.

**Pull request closed without merging**
