### PR TITLE
[5.8] Fix doc block

### PR DESCRIPTION
**Pull request by mvdnbrk**
`$job` can be a string or an object.

### CODE REVIEW

**Comment by driesvints** [comment]
Couldn't we use `string|object` instead then if those are the two only possibilities?

**Comment by mvdnbrk** [comment]
@driesvints something like this?

```php
    /**
     * Create a payload string from the given job and data.
     *
     * @param  string|object  $job
     * @param  string  $queue
     * @param  mixed   $data
     * @return string
     *
     * @throws \Illuminate\Queue\InvalidPayloadException
     */
    protected function createPayload($job, $queue, $data = '')
    {
        ...
    }
```

```php
    /**
     * Create a payload array from the given job and data.
     *
     * @param  string|object  $job
     * @param  string  $queue
     * @param  mixed  $data
     * @return array
     */
    protected function createPayloadArray($job, $queue, $data = '')
    {
        ...
    }
```

```php
    /**
     * Create a payload for an object-based queue handler.
     *
     * @param  object  $job
     * @param  string  $queue
     * @return array
     */
    protected function createObjectPayload($job, $queue)
    {
        ...
    }
```

```php
    /**
     * Get the display name for the given job.
     *
     * @param  object  $job
     * @return string
     */
    protected function getDisplayName($job)
    {
        ...
    }
```

**Comment by GrahamCampbell** [comment]
👍

**Comment by mvdnbrk** [comment]
Will send in a new PR 😄

**Pull request merged**
