### PR TITLE
[5.6] Allow populating the collection by passing items as arguments (2)

### PR DESCRIPTION
**Pull request by pmatseykanets**
This is a continuation of #23510

### CODE REVIEW

**Comment by browner12** [comment]
is there a specific use case for this?

I'm trying to understand the justification for adding in this extra code, because I don't see a pain point in passing an array when one is asked for.

**Comment by taylorotwell** [comment]
No plans on adding right now.

**Comment by pmatseykanets** [comment]
@browner12 Thanks for a good and very valid question. I think the `Collection` class itself is a good answer, which in short is convenience. There are at least 10 other places where this particular pattern been already successfully applied without requiring any additional justification.

For instance one might wonder how hard it would be to pass an array of keys to [`has()`](https://github.com/laravel/framework/blob/3ed733fa0061a10cc5cfbfeefbc0170e58bbc276/src/Illuminate/Support/Collection.php#L780) or [`except()`](https://github.com/laravel/framework/blob/3ed733fa0061a10cc5cfbfeefbc0170e58bbc276/src/Illuminate/Support/Collection.php#L429) methods? And yet it's pretty convenient to be able to pass them simply as arguments in most cases (specifically when you have a handful of them). 

And that's just the `Collection`. There are literally hundreds of places in the framework where this specific pattern is used for years now.

**Comment by devcircus** [comment]
I believe this started as "why not?" on Twitter:

https://twitter.com/calebporzio/status/973301864962850817?s=21  

It makes sense to add the capability but you definitely want to make sure there is absolutely no changing behavior around this. Many things could break.

**Pull request closed without merging**
