### PR TITLE
[11.x] Add `Transactional` agnostic middleware

### PR DESCRIPTION
**Pull request by mabdullahsari**
This PR introduces a new middleware for the Queue component: `Transactional`.

## Why?

I have lost count how many times we had to create a similar middleware in the various projects I have worked on so far. We had to create another one just now, and decided to submit this to the framework core.

The middleware is very simple, but prevents possible disasters when the database operations fail in partial.

## Example

(Pseudocode with some complex Synchronization logic:)

```php
class SynchronizeCustomer implements ShouldQueue
{
    use Dispatchable;

    public function __construct(private CustomerChanged $event) {}

    public function handle(): void
    {
        if ($customer = Customer::tryFrom($this->event->customer)) {
            $this->update($customer, $this->event);
        } else {
            $this->create($this->event);
        }
    }

    protected function create(CustomerChanged $event): Customer
    {
        return Customer::factory()
            ->for($this->createAddress($event->address))
            ->for(...)
            ->for(...)
            ->for(...)
            ->for(...)
            ->has(...)
            ->has(...)
            ->has(...)
            ->hasAttached(...)
            ->create([
                'erp_id' => $event->customer,
                'name' => $event->name,
                'language' => $event->language,
            ]);
    }

    protected function update(Customer $customer, CustomerChanged $event): void
    {
        Pipeline::send(new PendingCustomerUpdate($customer, $event))->through([
            UpdateShippingAddresses::class,
            ReplaceRepresentativesIfChanged::class,
            UpdateCustomerDetails::class,
        ])->then(fn () => $customer->regenerateHashCodes());
    }

    private function createAddress(Address $address): AddressFactory
    {
        return AddressFactory::new([
            'street_prefix' => $address->additionalStreetPrefix,
            'street' => $address->street,
            'street_suffix' => $address->streetSuffix,
            'postal_code' => $address->postalCode,
            'city' => $address->city,
            'email' => $address->email,
            'phone' => $address->phone,
            'fax' => $address->fax,
        ])->for(Country::tryFrom($address->country->value));
    }

    public function middleware(): array
    {
        return [new Transactional()];
    }
}
```

## Remarks

I'm not 100% sure about the name, so suggestions welcome!

### CODE REVIEW

**Comment by mateusjatenee** [comment]
I do this all the time. Would love to see it in the core.

**Comment by taylorotwell** [comment]
I'm curious why it is in the queue component?

**Comment by mabdullahsari** [comment]
> I'm curious why it is in the queue component?

Database and Queue are like conjoined twins: the vast majority of jobs probably run a database operation in some way, shape or form. It would be nice to have some first-party middleware OOB providing resilience, fault-tolerance and transactional integrity. These important factors are often overlooked by many, and this exact placement would drastically improve its discoverability.

Moreover, Database is referenced through Support which is already a dependency of Queue, so technically there is no direct Database dependency.

I guess Foundation\Queue\Middleware is also an option though!

**Comment by taylorotwell** [comment]
If this exists it should 100% be in the database component. I don't understand why a middleware that specifically starts a database transaction as its only purpose wouldn't be in the database component.

**Comment by mabdullahsari** [comment]
> If this exists it should 100% be in the database component. I don't understand why a middleware that specifically starts a database transaction as its only purpose wouldn't be in the database component.

But this means that `Database` is technically going to have a dependency on `Queue` now, while `Queue` itself already has a dependency on `Database`.

What I also could do, is make the middleware "component agnostic" because this could also be used perfectly fine in an HTTP Pipeline or Command Bus Pipeline context. In that case, your suggestion and placement would make perfect sense.

**Comment by mabdullahsari** [comment]
@taylorotwell I've moved the middleware to the `Database` component, and have added more integration tests. 

LMK what you think! 🙏

**Comment by lkmadushan** [comment]
@mabdullahsari I was thinking about why we need this. We can add the DB transactions inside the handle method easily.

**Comment by mabdullahsari** [comment]
> @mabdullahsari I was thinking about why we need this. We can add the DB transactions inside the handle method easily.

I hear you, but this is a moot point since the same can be said for any middleware in existence. Laravel is renowned for its excellent DX, and I think this is going to be a indispensable addition! Moreover, it promotes composition of different pieces of functionality which is (almost) always a good thing. 👍

**Comment by marius-mcp** [comment]
@mabdullahsari nice approach.

This seems like a NOT in plain site solution that does not harm if not used (as opposed to many other happy flow rows of code included as overhead in laravel).

For me this would be much more clear and easy to spot:


    public function handle(): void
    {
        DB::transaction(function (): void {
         if ($customer = Customer::tryFrom($this->event->customer)) {
             $this->update($customer, $this->event);
         } else {
             $this->create($this->event);
         }
        });
    }


Question. The middleware is called before or after __construct?

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

**Pull request closed without merging**
