### PR TITLE
[5.8] Add support for schemas in SqlServer grammar

### PR DESCRIPTION
**Pull request by thijsvdanker**
### Benefit to end user

At this moment it is not get the column listing for a table in a schema different from the default schema. (e.g. *test.Users*)
It is also not possible to check if a table in a different schema exists.

Both the `compileTableExists()` and`compileColumnListing()` functions only check for object name and not for the schema.

### Contents of this pull request

This pull requests adds checks for the schema name in the `compileTableExists()` and
`compileColumnListing()` functions.
The available schemas can be defined in the database configuration.
This is all consistent with the PostgresGrammar and PostgresBuilder.

The default schema is gathered from the database by using
```
select SCHEMA_NAME()
```
Which is available since SQL Server 2008.
See https://docs.microsoft.com/en-us/sql/t-sql/functions/schema-name-transact-sql?view=sql-server-2017

### Breaking
This PR is breaking as it removes the `table` parameter from a public function:
```php
    public function compileColumnListing($table)
```

This is done for consistency reasons with the PostgresGrammar.

This PR could also be done in a non-breaking fashion by adding `$schema` as an optional parameter and either fetching the default schema there or checking for the schema if the parameter is not passed.

```php
    public function compileColumnListing($table, $schema = null)
    ...
```

### CODE REVIEW

**Comment by thijsvdanker** [comment]
Changed target branch to `master` as PR contains breaking changes.

**Comment by GrahamCampbell** [comment]
Corrected the target to 5.8.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by thijsvdanker** [comment]
@taylorotwell 

Consider checking for 2 table names that are the same but have a different schema:

```php
class CreateExistingFooTable extends Migration {
	public function up()
	{
		Schema::create('existing.Foo', function(Blueprint $table)
		{
			$table->string('foo', 50)->default('');
		});
	}
}
```

When checking for the existence of the Foo table on 2 different schemas, at this moment both schemas would return true.
```php
$schema = $this->getConnection()->getSchemaBuilder();

$existing = $schema->hasTable('existing.Foo'); // true
$nonExisting = $schema->hasTable('nonExisting.Foo'); // true
```


Which is a bug (if Laravel is supposed to support schemas), or a feature (if schemas are not supported).

Schemas are a basic functionality of SQL Server, so I'd vote for bug :)

**Comment by driesvints** [comment]
@thijsvdanker @GrahamCampbell please don't change the branch like this. There's currently a bug with changing base branches in Github: https://github.com/laravel/framework/pull/27099

**Pull request closed without merging**
