### PR TITLE
set JSON_UNESCAPED_UNICODE for default json_encode option

### PR DESCRIPTION
**Pull request by taoso**
Just make another try for #6526

### CODE REVIEW

**Comment by timgws** [comment]
@taylorotwell can we have another look at this? having `JSON_UNESCAPED_UNICODE` set by default does start to make sense, especially moving forward with 5.2.

**Comment by taylorotwell** [comment]
Are other large projects using this setting when converting to JSON? If so,
which ones?

**Comment by crynobone** [comment]
https://github.com/symfony/intl/blob/3.0/Data/Bundle/Writer/JsonBundleWriter.php seem to use it.

https://github.com/search?utf8=%E2%9C%93&q=JSON_UNESCAPED_UNICODE+user%3Afacebook+user%3Azendframework+user%3Asymfony+extension%3Aphp&type=Code&ref=searchresults

**Comment by lvht** [comment]
@taylorotwell ping

**Comment by seekcx** [comment]
This is a good pr!

**Comment by lvht** [comment]
You @seekcx may get more detail about why this PR was rejected at #6526

**Comment by lvht** [comment]
@taylorotwell just closed this PR without any additional reply about this discussion. This is the Laravel's style.

**Comment by timgws** [comment]
I still think we should set JSON_UNESCAPED_UNICODE by default.

**Comment by tonoslav** [comment]
@timgws is it at least possible to set by myself, I dont need default but I want to have it, always when datas are json_encoded into response or database I want it to be with option JSON_UNESCAPED_UNICODE
is it possible?

**Pull request closed without merging**
