### PR TITLE
[5.5] Always use handle function for commands.

### PR DESCRIPTION
**Pull request by lucasmichot**
In commands and command stubs, `fire` has been replaced by `handle` since 970836c5368642d975c56aa71f8aecafddcd3fd8 (version `5.0.30`)

### CODE REVIEW

**Comment by browner12** [comment]
should `Console/Command` be updated to reflect this change? if we're going to get rid of `fire` and make `handle` the standard, this would be the time to do it

**Comment by lucasmichot** [comment]
I think we should keep `Console/Command` as it so that console commands from your app still work with `fire`.

**Comment by browner12** [comment]
hmm... i guess I would lean towards removal.  if we target 5.5 we could make this breaking change, and include a note in the upgrade guide. 

this helps us keep a simpler code base (not by much in this case) and maintain a consistent interface.

**Comment by lucasmichot** [comment]
Yeah this would make sense @browner12 
Up to @taylorotwell

**Comment by sylarbg** [comment]
Generators for models and mails are broken
 "laravel/framework": "5.5.*"
  [Symfony\Component\Debug\Exception\FatalThrowableError]               
  Call to undefined method Illuminate\Console\GeneratorCommand::fire()

**Comment by lucasmichot** [comment]
Good catch @sylarbg , see https://github.com/laravel/framework/pull/19839

**Pull request merged**
