### PR TITLE
[5.1] 100x faster loading model mutators

### PR DESCRIPTION
**Pull request by prohalexey**
Implode all method's name with ';' and one preg_match significantly faster when foreach.
In project with more than 50 models and high load, it show good perfomance improvement;

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please fix the multiple issues.

**Comment by GrahamCampbell** [comment]
Are we 1000% sure this works? Maybe 5.2 or 5.3 is a safer place for this @taylorotwell?

**Comment by vlakoff** [comment]
* I was going to point out there is no `(;|^)` at the beginning (but maybe it is intentional?) and that you could use non-capturing groups for even better performance.

* But I have another suggestion (apparently twice as fast):

        preg_match_all('/;get([^;]+?)Attribute;/', ';'.implode(';', get_class_methods($class)).';', $matches)

* Finally, you don't need the `if` test. `$matches[1]` is guaranteed to exist as long as there is the capturing group; if there is no match it will be an empty array.

**Comment by GrahamCampbell** [comment]
We're open to PRs.

**Pull request merged**
