### PR TITLE
Add SES Session Token again to Symfony Mailer

### PR DESCRIPTION
**Pull request by Jubeki**
https://github.com/symfony/symfony/pull/42982 was merged into 5.4 of Symfony (still waiting to be merged into 6.0) which adds support for the temporary credentials of AWS.

Because in the ses section of the Laravel mail-config the `session_token` is named `token` we need to rename the config key while passing the options to the SES-Factory.

Another option would be to add this to the upgrade guide that the config entry needs to be renamed.

The SesFactory only respects the `session_token` and `region` option right now therefor I would recommend renaming the token to session_token in the config.

@driesvints what is your opinion on that?

### CODE REVIEW

**Comment by Jubeki** [comment]
And I don't know why the tests are failing 😅😂

**Comment by driesvints** [comment]
@Jubeki try rebasing with master and they'll pass again.

**Comment by driesvints** [comment]
@Jubeki let's keep the rename to avoid the breaking change

**Comment by driesvints** [comment]
@Jubeki ow sorry, I should have first rebased the symfony mailer PR and you should have rebased with that 🤦‍♂️

I've just merged master into symfony-mailer. Can you send this in anew? Sorry for the mess.

**Comment by Jubeki** [comment]
Yeah I will do that

**Pull request closed without merging**
