### PR TITLE
[5.6] Fix params order in Broadcast Manager.

### PR DESCRIPTION
**Pull request by jrojas28**
Fix intended to reorder the parameters in the Pusher Broadcaster to match the order expected by the latest Pusher constructor.

### CODE REVIEW

**Comment by sisve** [comment]
Could you reference what changes in the Pusher class you're referring to? I don't see the change in the Pusher class. https://github.com/pusher/pusher-http-php/blob/master/src/Pusher.php#L43

**Comment by devcircus** [comment]
Laravel suggests Pusher ~3.0 which matches the constructor parameters in the BroadcastManager class.

**Comment by GrahamCampbell** [comment]
This will unfortunately break for all existing users though.

**Comment by devcircus** [comment]
Here's the code from BroadcastManager:
```php
new Pusher($config['key'], $config['secret'],
            $config['app_id'], $config['options'] ?? [])
```

Here's the constructor from the latest Pusher:
```php 
public function __construct($auth_key, $secret, $app_id, $options = array(), $host = null, $port = null, $timeout = null)
```

The order is "key", "secret", "id", "options".

Links:
https://github.com/pusher/pusher-http-php/blob/master/src/Pusher.php#L43

https://github.com/laravel/framework/blob/5.6/src/Illuminate/Broadcasting/BroadcastManager.php#L213

**Comment by laurencei** [comment]
This PR is incorrect.

The root cause of the incorrect Pusher installation is described in this closed issue thread: https://github.com/laravel/framework/issues/23224 - @jrojas28 if you look at that, you'll see how to solve your problem.

Although that thread raising as interesting question why composer is installation a different branch. Maybe @GrahamCampbell can advise in that thread as an expert in that type of stuff?

**Comment by jrojas28** [comment]
@laurencei your shot was correct. The issue was on my end due to lacking `php-curl`. After installing it and retrying it pulled from the proper branch & installed correctly. 

I'm guessing the old branch is there & is pulled as back up because when lacking `php-curl`, Pusher relies on the HTTP Client features developed within that branch. Still, that's just a wild guess.

I'll leave this PR open for another hour or two in case @GrahamCampbell would like to provide some advices, but otherwise and as stated by @laurencei , this PR is wrong & will be closed.

**Comment by laurencei** [comment]
@GrahamCampbell - can we tighten the pusher composer requirements, so the other branch is not pulled, and instead composer fails?

**Pull request closed without merging**
