### PR TITLE
[5.7] Fixed DatabaseEloquentTimestampsTest.php

### PR DESCRIPTION
**Pull request by TBlindaruk**

### CODE REVIEW

**Comment by damiankloip** [comment]
Looks good - just saw this [here](https://travis-ci.org/laravel/framework/jobs/432622166)

**Comment by laurencei** [comment]
What exactly is this fixing? Your PR should give Taylor some basic idea of why it should be merged, because it's not immediately clear...

**Comment by damiankloip** [comment]
This is fixing random fails in `DatabaseEloquentTimestampsTest` due to now timestamps, see my comment above also. This is all over tests in the code base already.

**Comment by 36864** [comment]
Sometimes, these tests fail because the value of `Carbon::now()` is not the same between calling `$now = Carbon::now()` and creating the users (which implies a call to `Carbon::now()` to use for the timestamp field).

This change ensures `Carbon::now()` will return a fixed value for the duration of the test to avoid these sporadic failures.

**Comment by TBlindaruk** [comment]
@damiankloip , @36864 , Thanks!)

**Pull request merged**
