### PR TITLE
[5.2] update docblock for mailer 

### PR DESCRIPTION
**Pull request by nguyentienlong**
guzzle client should return `mixed` instead of return `void`

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Return void just means anything returned shouldn't be relied upon.

**Comment by nguyentienlong** [comment]
well, I was thought that return void return nothing: https://wiki.php.net/rfc/void_return_type

In Laravel Mailer class, `sendSwiftMessage` func call ` return $this->swift->send($message, $this->failedRecipients);`  https://github.com/laravel/framework/blob/5.1/src/Illuminate/Mail/Mailer.php#L395
which should return int (from parent class https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Mailer.php#L72)
In Mandrill, Mailgun Transport or etc ... which use guzzle as http client to call the API should return string (those apis response string).
So I think should return `int|string`. What do you think ?

**Comment by GrahamCampbell** [comment]
> well, I was thought that return void return nothing

It does currently, as of PHP 7.1, but that's not final yet.

**Comment by nguyentienlong** [comment]
so, what about @return `int|string` ?

**Comment by GrahamCampbell** [comment]
That doesn't mean the same. We're saying the return value is garbage. Use at your own risk.

**Comment by nguyentienlong** [comment]
I changed to int|string here nguyentienlong@556dc52
Reason: as I mentioned above comment

> In Laravel Mailer class, sendSwiftMessage func call return $this->swift->send($message, $this->failedRecipients); https://github.com/laravel/framework/blob/5.1/src/Illuminate/Mail/Mailer.php#L395
> which should return int (from parent class https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Mailer.php#L72)
> In Mandrill, Mailgun Transport or etc ... which use guzzle as http client to call the API should return string (those apis response string).
>

**Pull request closed without merging**
