### PR TITLE
[5.3] Use Macroable trait in Message Builder

### PR DESCRIPTION
**Pull request by rkgrep**
Allows to add additional features to notifications without rewriting native classes.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. I really don't like overusing these macros tbh, so I'd be :-1: here.

**Comment by rkgrep** [comment]
@GrahamCampbell Me too. But I really want this thing to be more flexible... At least to support additional drivers with custom features.

**Comment by taylorotwell** [comment]
What kinds of methods are you wanting to add with macros? Just to help me get a better idea of the use cases.

**Comment by rkgrep** [comment]
After my last PR was rejected, we have made custom database driver and `Channel\Notification` extension that supports additional features. However the message builder is used in base `Notification` which means that we have to extend at least 2 more classes to inject additional parameters into our custom driver.

I want to add methods for implementing payloads in database and attachments in e-mails, which can be ignored in other drivers.

**Pull request merged**
