### PR TITLE
Add validation keys for the new Password rule messages

### PR DESCRIPTION
**Pull request by pliasun**

### CODE REVIEW

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
This breaks the tests, and it also a major breaking change because the translations need to be updated in people's apps.

**Comment by driesvints** [comment]
This is a breaking change.

**Comment by bebetoalves** [comment]
> _No description provided._

I suggested a PR that would add this possibility of translation with keys without being breaking change and yet it was closed. I think people should give up on this and settle for using .json files to translate the Password messages into their languages.

**Comment by jnoordsij** [comment]
Can't this be done in v9 and then list it as breaking change? I think requiring an additional `<lang>.json` on top of the `validation.php` files to override messages is quite confusing to users and moreover isn't documented.

Also with the current setup any change to the default messages in `Password.php` in the future will be a breaking change for people using the `<lang>.json` files.

**Pull request closed without merging**
