### PR TITLE
[5.1] Have pagination presenters return an Expression from render

### PR DESCRIPTION
**Pull request by harrygr**
Have the `render()` methods from the pagination presenters return an instance of `Illuminate\View\Expression` instead of a string so they can be output in blade views using the normal `{{ }}` syntax rather than `{!! !!}`.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Breaking. Please send to 5.2 if it's not already there.

**Comment by harrygr** [comment]
It shouldn't be breaking as `Expression` has a `__toString()` method that should be backwards compatible. E.g. you can echo an `Expression` directly if not using blade tags. Correct me if I'm wrong.

**Comment by GrahamCampbell** [comment]
It is defintely breaking. You changed the contract so that any implementation that used to return a string is now wrrong.

**Comment by harrygr** [comment]
OK, fair enough. I've re-sent to master branch

**Pull request closed without merging**
