### PR TITLE
Make Application macroable

### PR DESCRIPTION
**Pull request by m1guelpf**
Making the Application macroable would allow, for example, things like https://github.com/laravel/framework/pull/21529#issuecomment-334206590.

### CODE REVIEW

**Comment by sisve** [comment]
No tests?

**Comment by m1guelpf** [comment]
@sisve The Macroable trait has its own tests, there's no need to add an specific Macroable test to every Macroable class.

**Comment by ConnorVG** [comment]
Why would you not also add this to the Console application?

**Comment by taylorotwell** [comment]
Going to hold off on this for now.

**Pull request closed without merging**
