### PR TITLE
[8.x] Add @count() to BladeEngine

### PR DESCRIPTION
**Pull request by faissaloux**
I frequently use @if ( count($array) ) like below, and sure a lot of devs do too.

```
@if ( count($array) )
//
@endif
```
 so I thought to simplify it by using @count
```
@count ( $array )
//
@endcount
```

### CODE REVIEW

**Comment by DarkGhostHunter** [comment]
Empty arrays are considered false. And you can use `blank()` and `filled()` helpers.

**Comment by faissaloux** [comment]
> Empty arrays are considered false. And you can use `blank()` and `filled()` helpers.

But still have to use it like @if ( filled($array) )

**Comment by dennisprudlo** [comment]
@faissaloux You don't need this helper.
> Empty arrays are considered false.

`@if ($array) ... @endif` works.

**Comment by faissaloux** [comment]
> @faissaloux You don't need this helper.
> 
> > Empty arrays are considered false.
> 
> `@if ($array) ... @endif` works.

No, we want to check the array length we need the count helper

**Comment by dennisprudlo** [comment]
Maybe I am missing something but you want the activate an if statement, if the array has values.
```php
count([]); // 0
count([1]); // 1
count([1, 2]); // 2
count([1, 2, 3]); // 3

(bool) []; // false
(bool) [1]; // true
(bool) [1, 2]; // true
(bool) [1, 2, 3]; // true
(bool) [0]; // true
(bool) [false]; // true
```

So `if (count($array))` and `if ($array)` will both evaluate to `false` if the array is empty and to `true` if the array is not empty. There's also `@empty(...)` to check if something is empty, but a variable not existing is also considered empty.

**Comment by faissaloux** [comment]
> Maybe I am missing something but you want the activate an if statement, if the array has values.
> 
> ```
> count([]); // 0
> count([1]); // 1
> count([1, 2]); // 2
> count([1, 2, 3]); // 3
> 
> (bool) []; // false
> (bool) [1]; // true
> (bool) [1, 2]; // true
> (bool) [1, 2, 3]; // true
> (bool) [0]; // true
> (bool) [false]; // true
> ```
> 
> So `if (count($array))` and `if ($array)` will both evaluate to `false` if the array is empty and to `true` if the array is not empty. There's also `@empty(...)` to check if something is empty, but a variable not existing is also considered empty.

Yes but for collections:
```
(bool) collect([]); // true
```

So here we need the count
```
(bool) count( collect([]) ); // false
```

To achieve this in blade we use
```
@if ( count( $collection ) )
  //
@endif
```

In this PR I simplified it using @count
```
@count( $collection )
  //
@endcount
```

**Comment by DarkGhostHunter** [comment]
`@if($collection->isEmpty())`

**Comment by faissaloux** [comment]
> `@if($collection->isEmpty())`
> 
> This PR is unnecessary IMO.

Yes this is correct but this PR is just to simplify this line of code.

Isn't @count( $collection ) better than @if( $collection->isEmpty() ) !!

**Comment by taylorotwell** [comment]
This has more downvotes than upvotes for now so going to hold off on merging this.

**Pull request closed without merging**
