### PR TITLE
[9.x] Adds password hash helper for Factories

### PR DESCRIPTION
**Pull request by DarkGhostHunter**
## What?

This small method will actually reuses the password hash to avoid creating it for each created model from the Factory. Should have major speedbumps when seeding 1.000+ models in a database. It uses `password` by default, and the application default hasher.

```php
public function definition()
{
    return [
        'name' => $this->faker->name,
        'password' => $this->password(), // "password"
        // ...
    ];
}
```

## How?

It saves the password (when called) into the Factory. This allows to hash a password only once when it makes/creates models.

## TODO?

The [`UserFactory.php` in laravel/laravel](https://github.com/laravel/laravel/blob/9.x/database/factories/UserFactory.php#L24) could be changed too to use the method instead of hard-coding the hash to _bcrypt_.

## BC?

Just adding a method and a property.

### CODE REVIEW

**Comment by driesvints** [comment]
How is this more performant than just using the hashed string like we do now?

**Comment by Krisell** [comment]
I also think the current implementation is better from a security perspective. Of course, this should not be used in production but the hardcoded bcrypt hash stands out very clearly, whereas a `password()` helper, even with a very bad default password, might be missed in reviews.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by DarkGhostHunter** [comment]
> How is this more performant than just using the hashed string like we do now?

For users or apps with different password requirements. For example, you may change `password` for `123asdAS#" or something if your app requires strong passwords with numbers or else.

Another way is to Artisan Tinker -> hash your new default password -> copy the hash, but feels less intuitive that using a password and saving the same hash in Factories.

I could have named it as `reuseHash('password')` tho.

**Pull request closed without merging**
