### PR TITLE
[10.x] Explicit nullable parameter declarations to fix PHP 8.4 deprecation

### LINKED ISSUE #50803: PHP 8.4: Implicitly nullable parameter declarations deprecated
### Laravel Version

any

### PHP Version

8.4.0

### Database Driver & Version

_No response_

### Description

As of PHP 8.4, implicitly nullable parameter declarations will be deprecated. See also https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated and https://wiki.php.net/rfc/deprecate-implicitly-nullable-types.

Currently, a large number of functions within this codebase still use this pattern; see also [a quick example](https://github.com/jnoordsij/laravel-framework/commit/051e98170550772c6dab28e690b2163766648b22) I made with [rector](https://github.com/rectorphp/rector). This should probably be adjusted.

Implementation suggestions:
- for maintenance reasons, it might be most fruitful to target any update at `10.x`, to also prevent lots of deprecations in the few months where v10 and PHP 8.4 are both supported;
- StyleCI has a [`nullable_type_declarations`](https://docs.styleci.io/fixers#nullable_type_declarations) fixer that can automatically fix and enforce this, which is probably the easiest way to automatically fix this;
- maybe for other people using StyleCI, adding this to the `laravel` preset might be a good way forward?

### Steps To Reproduce

N/A

### PR DESCRIPTION
**Pull request by Jubeki**
Closes #50803

_**Draft State**_

Let's run tests and get some opinions first, if this should be applied to Laravel 11 or Laravel 10. (I opted here for Laravel 10, not sure what this would imply when merging changes upstream)

Pint will be removed before the merge.

**_Description Taken from the provided issue:_**

As of PHP 8.4, implicitly nullable parameter declarations will be deprecated. See also https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated and https://wiki.php.net/rfc/deprecate-implicitly-nullable-types.

Currently, a large number of functions within this codebase still use this pattern; see also [a quick example](https://github.com/jnoordsij/laravel-framework/commit/051e98170550772c6dab28e690b2163766648b22) I made with [rector](https://github.com/rectorphp/rector). This should probably be adjusted.

Implementation suggestions:

- for maintenance reasons, it might be most fruitful to target any update at 10.x, to also prevent lots of deprecations in the few months where v10 and PHP 8.4 are both supported;
- StyleCI has a [nullable_type_declarations](https://docs.styleci.io/fixers#nullable_type_declarations) fixer that can automatically fix and enforce this, which is probably the easiest way to automatically fix this;
- maybe for other people using StyleCI, adding this to the laravel preset might be a good way forward?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Laravel 10 does not and will never support PHP 8.4, as far as I'm aware. This should target 11.x.

**Comment by GrahamCampbell** [comment]
Moreover, pint should not be installed here. The framework uses StyleCI to enforce code style.

**Comment by Jubeki** [comment]
Pint will be uninstalled after reviewing the changes, I left it there for now.

I just wanted to tag you @GrahamCampbell to discuss these changes.

And I will quote @driesvints from the issue: https://github.com/laravel/framework/issues/50803#issuecomment-2024756049
> It's highly unlikely we'll support PHP 8.4 on Laravel v10. But if it's not too much work and there aren't any breaking changes we can give it a go. I'll try to get a CI job up soon.

**Comment by driesvints** [comment]
@Jubeki @crynobone makes a good remark about the security releases only support. It might be better in the end to send this to 11.x instead. I appreciate the effort! 👍

**Pull request closed without merging**
