### PR TITLE
[5.3] Add Possibility to TokenAuth via header and not via GET param

### PR DESCRIPTION
**Pull request by LKaemmerling**
This PR makes it possible to Auth via Token with HTTP Header (api_token) instead of GET Parameter. The HTTP Header has an higher priority as the GET Parameter.

I think it is much cleaner to hide Auth Things for normal users when you do an HTTP Request

### CODE REVIEW

**Comment by themsaid** [comment]
You can use the `Authorization` header already:

`Authorization: Bearer 1duvRtIoy7wKfrMLgLsM`

**Comment by LKDevelopment** [comment]
@themsaid doesn't work for me when i wanted to use token based Authentification

**Comment by themsaid** [comment]
When you don't provide the `api_token` parameter, the guard will check your authorization header for a bearer token.

`Authorization: Bearer TOKEN_HERE` should work.

**Comment by taylorotwell** [comment]
Yes, this is already solved using Authorization header.

**Pull request closed without merging**
