### PR TITLE
[5.3] Recently updated state tracking

### PR DESCRIPTION
**Pull request by hosmelq**
I think this could be helpful in many scenarios.

### CODE REVIEW

**Comment by taylorotwell** [comment]
What's the use case for this?

**Comment by nathane** [comment]
Why not just listen to the `updated` model events fired?

**Comment by hosmelq** [comment]
I'm using `updateOrCreate` from a hasMany relationship, i need to check if the model was really updated but i don't have any way to do that, `isDirty` return false because the model was previously saved.

**Comment by taylorotwell** [comment]
I dunno. I'm personally not a fan of this syntax or wording.

**Pull request closed without merging**
