### PR TITLE
[8.x] Fulltext search for sql server

### PR DESCRIPTION
**Pull request by otilor**
This adds implementation of fulltext search for SQL server

### CODE REVIEW

**Comment by humaneguy** [comment]
@driesvints The test for SQL server is failing because I cannot, create full text indexes on `master` database which seems to be the database configured in the workflows

**Comment by Jubeki** [comment]
Maybe this resource for updating the workflow is helpful: https://github.community/t/ms-sql-service-with-full-text-search/137345

**Comment by driesvints** [comment]
Seems that the SQL Server tests indeed need a separate database to be set up to test this. I can look at that when I have some time, otherwise I'd appreciate if anyone could figure that out.

**Comment by driesvints** [comment]
@Jubeki from the error message it seems to me that it's possible to use full text search on the current image but that some databases aren't allowed to use it. If not, then the error message is misleading imo.

**Comment by humaneguy** [comment]
> @Jubeki from the error message it seems to me that it's possible to use full text search on the current image but that some databases aren't allowed to use it. If not, then the error message is misleading imo.

Yes. you can use the full text search on the image but on a different database aside `master, tempdb, or model database`

**Comment by humaneguy** [comment]
@driesvints I'm kind of in another issue here. I have to create a catalog before creating the index. Creating a catalog is another query entirely. Should I still include it in the where ```compileFulltext()``` method?

**Comment by driesvints** [comment]
I have no idea. I have no experience with SQL Server at all.

**Comment by driesvints** [comment]
@humaneguy if we don't have the knowledge to wrap up this PR it's best that we close it for now.

**Comment by humaneguy** [comment]
Yeah. I'd just close it.

**Pull request closed without merging**
