### PR TITLE
[6.x] Provide MiddlewareAware interface for Controllers / Request Handlers

### PR DESCRIPTION
**Pull request by deleugpn**
Instead of defining the middleware on the construct of a Controller, I like to write the `getMiddleware` method myself. This allows me to not have to extend the Base Controller offered by the framework. One thing my team noticed is that declaring it on the Request Handler causes less investigation on why something is happening. It's very common for people to forget to check the Route middleware for anything that's not standard Request / Response.
However, we also noticed that people get confused on why it works with the `getMiddleware` method at all. I believe an alternative to that head scratching moment is to actually offer an Interface for it.

I intend to write an interface for it on my own application and I'll be able to accomplish roughly the same behavior. I just thought that this maybe could be something offered by the framework itself without causing any hard at all.

### CODE REVIEW

**Comment by fragkp** [comment]
My thoughts on this: I didn't know about this feature (getMiddleware on Controllers). Its never mentioned in the documentation.

Let's deprecate this Feature in 6.x and remove it completely in 7.x.

**Comment by deleugpn** [comment]
[From the docs: ](https://laravel.com/docs/6.x/controllers#controller-middleware)

```
[...] However, it is more convenient to specify middleware within your controller's constructor. Using the middleware method from your controller's constructor, you may easily assign middleware to the controller's action.
```

**Comment by driesvints** [comment]
@deleugpn can you give a concrete example when this would be useful? All of this seems overkill to me tbh..

**Comment by deleugpn** [comment]
@driesvints it's nothing that doesn't already exists. The only difference is that
a) We never extend the base controller, so we don't have `$this->middleware()`
b) We always write Request Handlers (single action)
c) It's harder for newcomers / team members to understand that `getMiddleware` is a Laravel magic method on the Request Handler.

The introduction of an Interface would mitigate the _WTF_ moment when reviewing Pull Requests that people don't understand what's happening. But, as I said, I'm fine if the consensus is that this doesn't match with the framework core. I've just decided to create this interface on our own project to help with item **c)** and I thought I'd send a PR to see if it's something that could come from the core.

**Comment by driesvints** [comment]
Maybe it's better if we refactor the middleware methods and property to a trait instead so you can re-use it.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
