### PR TITLE
Update helpers.php

### PR DESCRIPTION
**Pull request by ghost**
debug don't die

exactly as it says does a dd() without dying. Very handy indeed in my opinion!

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This function already exists, provided by symfony.

**Comment by GrahamCampbell** [comment]
`dump`

**Comment by saulhudson** [comment]
well I still prefer ddd() :)

**Comment by paparent** [comment]
I'd love to see this kind of functionality especially for tests.. Any easy workaround (Sorry, new to Laravel!)

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L759-L775

(I'd like to see response, but continue the chain !)
cc @GrahamCampbell

**Pull request closed without merging**
