### PR TITLE
[11.x] Add Cast attribute for eloquent models

### PR DESCRIPTION
**Pull request by kontoulis**
### Proposal: Introduce a Cast attribute  to enhance model attributes type casting

<ins>**Summary**</ins>

I propose the introduction of a new `Cast` attribute for Eloquent models. This attribute allows us to specify type casting for model properties using PHP 8 attributes. The primary benefit is the ability to define casts in traits, thus reducing redundancy and improving code maintainability.

<ins>**Motivation**</ins>

Right now, defining casts in Eloquent models can get pretty repetitive, especially when you have to apply the same casts to multiple models. Using PHP 8 attributes gives us a more modern and straightforward way to handle type casting. It’s especially helpful with traits, since you won't have to keep adding the same casts to every model.

<ins>**Example usage**</ins>
Assuming that we have a basic `Price` value object which we need to use in our models (as seen in the unit tests) :
```php
#[Cast('price', Price::class)]
trait HasPrice {
    public function priceEquals(Price $other): bool
    {
        return $this->amount === $other->amount && $this->currency === $other->currency;
    }
}

#[Cast('normalModelAttribute', 'int')]
class EloquentModelWithAttributeCasts extends Model
{
    use HasPrice;
}
````

### CODE REVIEW

**Comment by driesvints** [comment]
Personal opinion but I don't feel we need yet another way to define casts besides the current API's...

**Comment by kontoulis** [comment]
@driesvints I understand that in general and it was my last resort :smile: . 
My motivation came from a need to cast value objects based on traits used by too many models (i.e. `Uuid` value objects) and this was the _cleaner_ way with the less side effects.

This functionality allows also 3rd party traits to be plug and play without requiring  to manually add any potential _cast_ they need.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

**Comment by calebdw** [comment]
Just wanted to say that this would help with help with statically detecting property casts: https://github.com/larastan/larastan/issues/2011

Larastan does not boot traits, so therefore it is impossible to detect casts that originate from traits using the public api (mergeCasts)

**Comment by kontoulis** [comment]
If anyone is still interested into this feature, I have published a new package for it  https://github.com/kontoulis/laravel-attribute-model-casting

**Pull request closed without merging**
