### PR TITLE
[5.4] Removed compiled class file generation

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Since Laravel 5.5 will be PHP 7.0+ it makes sense to remove this feature, since the best way to optimize performance in PHP 7 is just to correctly configure opcache to what's best for your server and websites.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I plan to remove this on 5.4.

**Comment by GrahamCampbell** [comment]
Easily fixed. :trollface: Just rename the PR.

**Comment by GrahamCampbell** [comment]
Done. :D

**Comment by arthurkirkosa** [comment]
This is causing some problems in the current 5.4 branch because it's not merged there as well

**Comment by GrahamCampbell** [comment]
This was merged to 5.4, because master was 5.4 at the time.

**Comment by arthurkirkosa** [comment]
For some reason I had to remove my `composer.lock` and `vendor` folder and reinstall all components and it worked. Thanks

**Pull request merged**
