### PR TITLE
[5.1] Routing : no need to get middlewares if they are skipped

### PR DESCRIPTION
**Pull request by lucasmichot**
No need to get middlewares if they are skipped.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I swear I've seen a PR like this before?

**Comment by it-can** [comment]
@Graham this one? https://github.com/laravel/framework/pull/11108

**Comment by GrahamCampbell** [comment]
No. Something much more similar.

**Comment by lucasmichot** [comment]
@GrahamCampbell 
It might be worth watching it again: http://www.imdb.com/title/tt0453467/

**Comment by GrahamCampbell** [comment]
Haha. Maybe I'm just going crazy(er).

**Comment by lucasmichot** [comment]
Acceptance is the key to start healing :+1:

**Comment by GrahamCampbell** [comment]
image

**Comment by crynobone** [comment]
https://github.com/laravel/framework/commit/2bd330f7cffc7ae8c59f588650e8d53190bc315b

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/pull/10385

**Pull request merged**
