### PR TITLE
[6.0] Update lang facade

### PR DESCRIPTION
**Pull request by oliverquynh**
Lang facade has to be updated because of the translator changes from https://github.com/laravel/framework/pull/29529

- Remove `trans` method signature.
- Rename `transChoice` to `choice`.

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks. Forgot this indeed. Damn DocBlocks.

**Review by driesvints — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
> Thanks. Forgot this indeed. Damn DocBlocks.

I'd still advocate to not have any duplicated docs across the facades within the framework for this reason of them getting out of date too easily, and instead using something like Barry's IDE helper locally.

**Comment by driesvints** [comment]
@GrahamCampbell unfortunately we'll need to keep then because otherwise static analysers can't analyse these classes anymore.

**Comment by GrahamCampbell** [comment]
Can we not just autogenerate stubs that can be given to static analyzers?

**Comment by driesvints** [comment]
@GrahamCampbell not sure if it's worth putting time into that ourselves.

**Pull request merged**
