### PR TITLE
Separate query bindings to fix their order

### PR DESCRIPTION
**Pull request by anlutro**
This is a new implementation of #884.

Currently it's near impossible to add a sub select, having or order by clause to a query builder as long as it has a binding - the order of the query binding gets completely messed up because all bindings are put into a single flat array. Therefore I propose this change which separates the bindings into 4 different categories.

It seems to pass all unit tests. The default `$type` value of 'where' on the various binding manipulation methods and the new `getBindings` method should ensure decent backwards compatibility. I had to modify one unrelated one, but it didn't make much sense to begin with - expecting the bindings to be `array('foo' => 'bar')` is stupid when we're using unnamed parameters (`?` as opposed to `:foo`). Nevertheless this is a pretty big change so I thought it best to target the master branch.

As an extension of this I would love to implement a selectSub and/or selectRaw method.

### CODE REVIEW

**Comment by SteveEdson** [comment]
I realise this is an old issue, however are binds supposed to work when used in query scopes? `setBindings` seem to wipe out previously set bindings. If I use `addBinding`, they are used in the wrong order. I am trying to combine two different scope queries.

**Comment by franzliedke** [comment]
@SteveEdson Why can't you add them with one of the query methods (`where` and the likes)?

**Comment by SteveEdson** [comment]
@franzliedke is there an example of this? I've not been able to get it to work. Also, is there a way to combine scope queries with a (`and` / `or`) that can change?

**Comment by franzliedke** [comment]
@SteveEdson Let's continue this discussion over there.

**Comment by franzliedke** [comment]
Uhm, sorry. Over there:  https://gist.github.com/franzliedke/e351e4a4d4f7d3d481a4

**Pull request merged**
