### PR TITLE
[5.8] use isBooted(), isDeferredService() for Application

### PR DESCRIPTION
**Pull request by fitv**
It will be better to use method.

### CODE REVIEW

**Review by oliverquynh — APPROVED** [review]

**Review by mpyw — APPROVED** [review]

**Comment by crynobone** [comment]
There no actual benefit since the instance have direct access to the property.

**Review by driesvints — APPROVED** [review]

**Comment by driesvints** [comment]
@crynobone I think in terms of readability this is a minor but nice change.

**Comment by crynobone** [comment]
>  I think in terms of readability this is a minor but nice change.

`$this->isBoot()` insteads of `$this->boot`? 

Is Laravel saying it recommend getter method compared to private/protected property directly? 

Because unless that's Laravel stand on the matter this is trivial and only open a floodgate to do the same thing all over the framework, https://github.com/laravel/framework/blob/5.8/src/Illuminate/Auth/Passwords/PasswordBroker.php (PR to convert to use `$this->getRepository()` instead of `$this->tokens`) for example.

If Laravel doesn't have a stand on this matter, anyone can come up with another PR and revert this changes tomorrow and some peoples may approved that as well.

**Comment by driesvints** [comment]
> $this->isBoot() insteads of $this->boot?

It's `isBooted` not `isBoot`

> Is Laravel saying it recommend getter method compared to private/protected property directly?

Not at all. For these boolean check it makes sense imo because the new implementation is more clear to me. For the example of the `PasswordBroker` I'd still use the properties directly.

**Comment by driesvints** [comment]
Also: the logic of `isset($this->deferredServices[$service])` is duplicated everywhere where these replacements were made. With this PR we keep the logic in one single place which is a good improvement imo.

**Pull request merged**
