### PR TITLE
Allow specifying connection on scheduled job

### PR DESCRIPTION
**Pull request by CmdrSharp**
Jobs can currently specify a queue to run on, but unlike normal job dispatching - jobs that are dispatched through the scheduler can not specify a connection. In fact, the ability to specify the queue is not documented either (which I will make another PR on).
This minor change allows specifying both a connection and a queue for scheduled jobs, which I'd deem to be important functionality as it's not at all uncommon to have more than one queue driver.

### CODE REVIEW

**Comment by ntzm** [comment]
This will need to target `master` as it is a breaking change

**Comment by CmdrSharp** [comment]
@ntzm With the latest commit, it should no longer be a breaking change.

**Comment by ntzm** [comment]
Changing the definition of a public method is always a breaking change, as any classes that extend it will break

**Comment by CmdrSharp** [comment]
@ntzm But of course you are correct! I'll close this out and create a new PR as changing the base didn't seem to work to well.

**Pull request closed without merging**
