### PR TITLE
[8.x] Update Bootstrap pagination style

### PR DESCRIPTION
**Pull request by JredLewis**
This PR updates Laravel's built-in Bootstrap pagination (```bootstrap-4.blade.php```) to be styled similarly to the built-in Tailwind pagination (```tailwind.blade.php```).

bootstrap-pagination

### CODE REVIEW

**Comment by driesvints** [comment]
This'll break the design for anyone currently using Bootstrap 3. This most likely would need to go into master.

**Comment by jrd-lewis** [comment]
> This'll break the design for anyone currently using Bootstrap 3. This most likely would need to go into master.

I checked with the ```Paginator::useBootstrapThree();``` and it seems to uses ```default.blade.php``

**Comment by GrahamCampbell** [comment]
This is still breaking, because people using the bootstrap 4 one will find their app suddenly looks different.

**Comment by driesvints** [comment]
Seems to have conflicts after switching branches. Can you please rebranch anew and send in a new pr?

**Pull request closed without merging**
