### PR TITLE
[5.3] Pass params from Route URL to FormRequest

### PR DESCRIPTION
**Pull request by actionm**

### CODE REVIEW

**Comment by shadoWalker89** [comment]
You can do `$request->route()->parameter('id')` or `$request->route('id')`

**Comment by actionm** [comment]
Yes, I can validate parameters in the Controller method, but this commit adds a validation in Request.

By default FormRequest checks only form (GET,POST,etc) parameters, but it can't validate parameters given from Route URL.  
```php
Route::get('/item/{id}', 'Controller@method');
Route::get('/item/{id1}www{id2}', 'Controller@method');
```

Now I can easily check parameters given from Route URL and reuse this validation in other methods to make code shorter.

```php
class TestRequest extends FormRequest

  public function rules()
  {
	return [
		'id1' => 'required|numeric|digits_between:1,10',
		'id2' => 'required|numeric|digits_between:1,10'
	];
  }
}
```
```php
class TestController extends Controller
{
  public function test1(TestRequest $request) {
      // params id1 id2 are validated
  }
}

  public function test2(TestRequest $request) {
      // params id1 id2 are validated
  }
}
```

**Comment by shadoWalker89** [comment]
You just need to override the `validationData()` on your `FormRequest` And return what ever you like.
In your case you can do

```php
protected function validationData()
{
    return array_merge($this->all(), $this->route()->parameters());
}
```

**Comment by taylorotwell** [comment]
No plans on adding this.

**Pull request closed without merging**
