### PR TITLE
[12.x] Add missing methods to the `Illuminate\Contracts\Container\Container` interface

### PR DESCRIPTION
**Pull request by subhamchbty**
1. `refresh($abstract, $target, $method)`
2. `rebinding($abstract, Closure $callback)`

# Proposed Changes
The changes have been made to the `src/Illuminate/Contracts/Container/Container.php` file, where the new methods have been added to the `Illuminate\Contracts\Container\Container` interface.

# Potential Impact
These changes are intended to be backward-compatible and should not break existing code that relies on the `Illuminate\Contracts\Container\Container` interface. They provide additional capabilities that can be optionally utilized by developers.

### CODE REVIEW

**Comment by Jubeki** [comment]
Hey, you can't make changes to an interface on a minor release, because there could be apps which implement the interface and would not be confronted with a breaking change.

These changes can only happen in major versions (master branch).

**Comment by subhamchbty** [comment]
@Jubeki Shall I change the base branch then? Or can you please suggest what I can do?

**Comment by Jubeki** [comment]
Yeah changing the base branch to master would be okay, because that would be the branch for the next major version 12.x

**Comment by subhamchbty** [comment]
Hi @Jubeki, I've create another PR as you suggested.

**Pull request closed without merging**
