### PR TITLE
[9.x] Generate table's columns as phpDoc properties for `make:model` command

### PR DESCRIPTION
**Pull request by sethsandaru**
Hi all,

This PR introduces a new option `--phpdoc` for the `php artisan make:model` command. 

It will generate the Model file **together** with the phpDoc's properties - the table's columns.

It would be a great helper for IDEs and for us to know the Models' columns. Makes the development process around Eloquent more enjoyable. Quite helpful for some tables that had a lot of columns since the beginning, we don't have to add the `@property` manually, takes time.

Usage:

```bash
php artisan make:model User --phpdoc
```

Without `--phpdoc` - same as today:

image

With `--phpdoc`:

image

Note: this feature requires `doctrine/dbal` package.

Cheers!

### Checklists
- [x] Implement feature
- [x] Unit testing
- [x] Test

### CODE REVIEW

**Comment by medilies** [comment]
Will it support refreshing the docs after changing the migration ?

**Comment by sethsandaru** [comment]
@medilies that's what I'm about to do next 😄

**Comment by foremtehan** [comment]
Wish this happen for Facades @method docblocks.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by sethsandaru** [comment]
Thanks for the information @taylorotwell . 

But I believe it is a small helper/nice-to-have feature and it wouldn't add a big burden for the `make:model` command, we also have unit testing, can we process? Thanks 😄

**Pull request closed without merging**
