### PR TITLE
[5.8] [WIP] Delete deprecated method

### PR DESCRIPTION
**Pull request by TBlindaruk**
I have deleted the deprecated method which was done in https://github.com/laravel/framework/pull/25567

Please notice, that in this PR I also merged 5.7 to master,  
So before merging this PR to master you should merge the 5.7 to master for see only my changes in PR

### CODE REVIEW

**Comment by jmarcher** [comment]
@TBlindaruk You need to rebase your branch

**Comment by GrahamCampbell** [comment]
Just forced GitHub to recompute the diff.

**Comment by GrahamCampbell** [comment]
Files changed still seems wrong. Could you rebase your branch please?

**Comment by TBlindaruk** [comment]
@GrahamCampbell , Ok I will do it after few hour

**Comment by GrahamCampbell** [comment]
Merged in https://github.com/laravel/framework/commit/d5f3e809890c5450c1cd4ef4d80ebbd7d16e17f3.

**Comment by TBlindaruk** [comment]
@GrahamCampbell , Thanks!

**Pull request closed without merging**
