### PR TITLE
[6.x] Add an `eager()` method to the lazy collection class

### PR DESCRIPTION
**Pull request by JosephSilber**
The `eager()` method enumerates all of the lazy collection's values, and constructs a new `LazyCollection` instance, which will now be backed by an array:

```php
$users = User::cursor();

$users = $users->eager();

$count = $users->count();

$users->each(function ($user) {
    //
});
```

The above will only fetch the users once. Without calling `eager` in between, the query would execute (and fetch all results) twice.

This is a pretty useless example, but is a clear illustration of what the `eager` method does.

### CODE REVIEW

**Comment by taylorotwell** [comment]
The naming of this and when to even use it are still very murky to me. 😄

**Comment by GrahamCampbell** [comment]
What about `strict()` as a method name?

**Comment by JosephSilber** [comment]
> when to even use it are still very murky to me

Do you understand when a user would want to call `lazy()` on a regular collection? You may want to run lazy operations even on a list that is already all in memory.

`cache` is functionally equivalent of `$lazyCollection()->collect()->lazy()`.

**Comment by BrandonSurowiec** [comment]
Would `snapshot()` be a better name?

**Comment by thecrypticace** [comment]
Yeah, I'm not a fan of the name `cache`. It feels too tied to actual persist able caching. Tbh, `snapshot()` isn't a bad name. It seems pretty descriptive to me. In my lazy collection implementation I called this method `eager()` (as you eagerly collect the values into the collection) which is another option.

**Comment by taylorotwell** [comment]
Definitely prefer `eager`.

**Comment by JosephSilber** [comment]
Updated.

**Pull request merged**
