### PR TITLE
[9.x] Support --ssl-ca on schema load and dump

### PR DESCRIPTION
**Pull request by DeepDiver1975**
When using SSL with MySql php artisan migrate will fail with 

```
In Process.php line 272:
                                                                               
  [Symfony\Component\Process\Exception\ProcessFailedException]                 
  The command "mysql  --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_L  
  OAD_PASSWORD}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}  
  " --database="${:LARAVEL_LOAD_DATABASE}" < "${:LARAVEL_LOAD_PATH}"" failed.  
                                                                               
  Exit Code: 5(Unknown error)

### CODE REVIEW

**Comment by driesvints** [comment]
Draft pr's aren't reviewed. Please mark as ready if you want a review, thanks.

**Comment by taylorotwell** [comment]
It doesn't complain if you pass an empty string?

**Comment by DeepDiver1975** [comment]
> It doesn't complain if you pass an empty string?

not with the mysql version I am using locally ....
Screenshot from 2022-02-22 10-19-13

**Comment by Brenneisen** [comment]
> It doesn't complain if you pass an empty string?

It does: https://github.com/laravel/framework/issues/41300

**Pull request merged**
