### PR TITLE
[5.7] Add ksort method to Collection

### PR DESCRIPTION
**Pull request by lupinitylabs**
To allow for sorting a collection by its keys, I suggest adding a ksort() method to the Collection class.
Currently, it is required to use constructs like:

```
$someArray = $someCollection->all();
ksort($someArray);
$someCollection = collect($someArray);
``` 

which is rather tedious, especially when there is a lot of chaining going on after the ksort(). The pull request would allow to simplify above code to:

```
$someCollection->ksort();
``` 

I leave it up to a framework aesthete to determine the final name of the method, as ksort() might be intuitive but probably not as expressive as the other method names, and also choosing the name of a PHP core function does not seem quite right (although there are already Collection methods like implode on the other hand...). However, since the ksort() method call has a different return value than the core ksort() function, it might be a good idea to name if differently.

### CODE REVIEW

**Comment by alberto-bottarini** [comment]
Please add some unit tests for this new method

**Comment by Dylan-DPC** [comment]
[ksort](http://php.net/manual/en/function.ksort.php) also accepts a defaulted `$SORT_REGULAR` parameter. So if you are adding it to the core, you might as well allow it to accept that parameter.

**Comment by GrahamCampbell** [comment]
5.5 is probably the best place for this?

**Comment by BrandonShar** [comment]
You can do this with `sortBy`, it passes both the key and value to the callback.

**Comment by DojoGeekRA** [comment]
Have you considered the method name `sortByKey`? 

Maybe there is no need to maintain the `k` abbreviation.

**Comment by taylorotwell** [comment]
Wrong branch. Should be 5.5 or 5.6. Also please name it `sortByKeys`.

**Comment by Lupinity** [comment]
Unit test added for new sort method.
Brandon has a point with using `sortBy`, however this would require using a closure for a relatively trivial task.

@taylorotwell ok, will rename the method and test to sortByKeys.

**Pull request closed without merging**
