### PR TITLE
[5.8] Updated the container for better PSR-11 ContainerInterface compliance

### PR DESCRIPTION
**Pull request by Shawty81**
@laurencei To be honest I did not run the HTTP tests because I wasn't able to configure PHPUnit properly. Tried for an hour or 2 but kept on getting hundreds of errors. By simply looking at the failed test I understand my changes cause it to fail. I can fix those, but as @deleugpn states this implementation might be a bit flawed...

After a quick test and checking the PHP docs, only abstract classes will cause a problem. class_exists will return false on interface and traits and they both have their own respective _exists methods. I've updated my code to check through the Reflection API if the identifier resolves to an instantiable class.

Then the only thing remaining is the comment made by @taylorotwell made here https://github.com/laravel/framework/pull/21327#issuecomment-331430213 :
> Just because a class is concrete doesn't mean the Laravel container can resolve it. What if it has an interface dependency that isn't configured?

To that my response is:
Why would you check if all the dependencies are resolvable for a unbound class if you don't do that for a bound class? I mean currently I can bind any class with unresolvable dependencies and the code would break just as hard.

### CODE REVIEW

**Comment by Shawty81** [comment]
Ok, I'm pretty sure I updated my PR but now it made a new one...

https://github.com/laravel/framework/pull/25678

**Comment by deleugpn** [comment]
Bringing the original PSR text here: 

```has($id) returning true does not mean that get($id) will not throw an exception. It does however mean that get($id) will not throw a NotFoundExceptionInterface
```

This is part of the original confusion and unfortunately PSR-11 was a little ambiguous here. According to the PSR editors, it's okay to `return true` on `has` for objects that we think we can resolve, even if we end up not resolving them after.
The previous implementation was, technically, valid as well, although it's up to Taylor to decide what is part of the container or not. The point of the PSR is that `has` must return anything that Laravel considers part of the container (implicitly bound or not).

**Comment by Shawty81** [comment]
Yes, I agree now by checking the links to the discussions you posted under the other pull request the current implementation is correct as well.

And I will totally have peace with agreeing to disagree if Taylor to decides to decline this PR as well :)

**Comment by taylorotwell** [comment]
This isn't correct either. I doubt it is actually possible to even implement this in the way you are wanting to without recursively spinning every dependency. You might as well just build the entire object for real at that point.

image

**Pull request closed without merging**
