### PR TITLE
Make Exceptions output a compressed JSON response

### PR DESCRIPTION
**Pull request by szepeviktor**
Maybe the average Laravel user needs pretty output :(

but I hope this will be merged.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Some CI jobs fail because of a non-related error.

**Comment by paras-malhotra** [comment]
This is a pretty big breaking change. Would mess up all log management tools in production that are used to a format. Probably best to target master.

**Comment by GrahamCampbell** [comment]
Please send to master. Tests will pass of you rebase.

**Comment by szepeviktor** [comment]
> Please send to master. Tests will pass of you rebase.

I thought sending to master will result in a merge 😢 

#35314

**Pull request closed without merging**
