### PR TITLE
[5.5] iv initialize in encrypt(): remove magic literal

### PR DESCRIPTION
**Pull request by Snawoot**

### CODE REVIEW

**Comment by tillkruss** [comment]
Why do you want to remove that?

**Comment by tillkruss** [comment]
Can you explain this change this in detail, please?

**Comment by fernandobandeira** [comment]
Basically this function will get the required iv length for each cipher, currently we support ``` AES-128-CBC ``` and ``` AES-256-CBC ```.

AES-128-CBC uses an iv with a length of 16
AES-256-CBC uses an iv with a length of 32

It does make sense to use this function instead of hardcoding 16 there since we will assure compatibility across multiple cipher methods...

**Comment by Snawoot** [comment]
Hello,

Sorry for too short comment. IV length varies for different ciphers. Currently Encrypter uses only AES and 16 bytes long IV is valid for both 128 and 256 variants it supports, but cipher whitelist may change in future. Actually, it should change because even if AES is  the best symmetric cipher ever, in some countries local regulations allows to use only locally certified ciphers for commercial applications.

This commit removes unneeded IV length hardcode. Probably in future Encrypted class should have extended cipher whitelist OR capability to accept custom whitelist.

**Comment by tillkruss** [comment]
@Snawoot: Is there any breaking change with this, or will everything that was encrypted in v5.4 be decryptable in v5.5?

**Comment by Snawoot** [comment]
@tillkruss no changes in data representation will occur, everything will be decryptable

**Pull request merged**
