### PR TITLE
[5.1] BelongsToMany: remove numerical id typecasting

### PR DESCRIPTION
**Pull request by alexgalletti**
Updated for 5.1, older PR #4480

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Can you include tests please?

**Comment by alexgalletti** [comment]
Ok, done.

**Comment by taylorotwell** [comment]
I still think this is a breaking change. Perhaps we should cast numeric values to int?

**Comment by xiphiaz** [comment]
It may actually be better to use the `$model->castAttribute` method, as I would expect that if the developer is expecting typecasted ids, then they would have defined them on `protected $casts = [];` in their model.

**Comment by alexgalletti** [comment]
Hmm... I'm not really seeing the breaking change but are you suggesting we change the code to reflect something like the following @taylorotwell 

```php
$changes['detached'] = (array) array_map(function ($v) { return is_numeric($v) ? (int) $v : (string) $v; }, $detach);
```

**Comment by taylorotwell** [comment]
Yes that's what I was suggesting.

**Pull request merged**
