### PR TITLE
[5.2] Add windows support for withoutOverlapping in scheduled tasks

### PR DESCRIPTION
**Pull request by auxide**
Fix for issue in windows when using withoutOverlapping().

Simply changed buildCommand() to return the windows equivalent when running in a windows environment.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
> sorry about that, ran php-cs-fixer and it didn't quite fix everything

**Comment by GrahamCampbell** [comment]
> sorry about that, ran php-cs-fixer and it didn't quite fix everything

Don't bother. StyleCI can merge the fixes after this PR gets merged by us.

**Comment by GrahamCampbell** [comment]
Please send a new PR without messing with all our phpdoc.

**Comment by auxide** [comment]
Sent a new PR (#12357) with docblock's restored

**Pull request closed without merging**
