### PR TITLE
[5.1] Simplify logic in Model::asDateTime()

### PR DESCRIPTION
**Pull request by vlakoff**
follow-up to #8469

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by KennedyTedesco** [comment]
:+1:

**Comment by taylorotwell** [comment]
Going to need much more explanation than this.

**Comment by vlakoff** [comment]
## Why is water wet? ##

Chemically speaking saying that water is wet has not much sense. We could however say that "Wetting process" is caused by the presence of a thin liquid particles layer over a material. In our specific case this depend from the chemistry of water and the chemistry of skin. So the main causes of the fact that water is wet, is its wetting properties determined by a force balance between adhesive and cohesive forces over the skin. Mercury although is a liquid will not "wet" you because it has strong cohesive force that don't permit to the molecules to get in touch with the sensory cells. When you touch water or a water wetted material part of the water molecules are transfer to your hands (an hydrophilic material) and so to the receptor cells giving the sensation of wet, this sensation can be caused however in some case of parasthesias even if there are no liquid particles. In fact there are no "wet receptor" over your skin but the sensation is due to the elaboration of different stimuli from tactile, pressure and temperature receptor present in you skin. Try to play with plasticine after a while handling it your hands will become hydrophobic you will no more fell the wet sensation when you wash them even if water is still "wet"!

#### References ####
* Marchioro, Giacomo (2014). "[Why is water wet?](http://chemistry.stackexchange.com/questions/7541/why-is-water-wet-and-fire-hot)".

**Comment by GrahamCampbell** [comment]
@taylorotwell Are you serious?

**Comment by taylorotwell** [comment]
Huh? They responded with some crazy post and you ask me if I'm serious? :)

If someone wants to explain it for real I will merge it.

**Comment by GrahamCampbell** [comment]
> If someone wants to explain it for real I will merge it.

Maybe you're not seeing it. The diff provided by github is pretty crap. Look at the whole function before and after, then it should become clear why this change makes so much sense. :)

**Comment by vlakoff** [comment]
I was going to split the PR in 2 commits, but in fact it is better to keep it as a whole, as it is the most straightforward.

@taylorotwell That's the best I can do:

marked

(I had forgotten how hard it is to [draw](https://www.youtube.com/watch?v=uQVXu7UMkjc) arrows by hand :p)

**Comment by vlakoff** [comment]
For the record, this change made it in #9408.

**Pull request closed without merging**
