### PR TITLE
[5.2] Add postLogout method to AuthenticatesUsers trait

### PR DESCRIPTION
**Pull request by dciancu**
Logging out should be a POST request, not GET.
http://stackoverflow.com/questions/3521290/logout-get-or-post

### CODE REVIEW

**Comment by JosephSilber** [comment]
> I'd like to thank my bank for making log off a GET request, and the Chrome team for handy URL prefetching.

- https://twitter.com/Nick_Craver/status/296281730984316928

**Comment by taylorotwell** [comment]
Can be defined in your own application.

**Comment by GrahamCampbell** [comment]
@taylorotwell I think we should consider changing the default from get to post for logging out in 5.3, since GET for logging out isn't really very safe.

**Comment by danieliancu** [comment]
I opened this PR mainly for the continuation of #13216 (where this discussion should take place), since I saw the API sticked with both methods of `getLogout` and `logout`.

**Pull request closed without merging**
