### PR TITLE
[5.4] If there is a withCount, Than also is withSum/withAvg/withMin/withMax

### PR DESCRIPTION
**Pull request by xuqihua**

### CODE REVIEW

**Comment by fernandobandeira** [comment]
This is actually a breaking change for the withCount method, you should assume that when no column is passed to withCount it should use ``` * ``` and not ``` id ``` also I don't think it's good to hard code ``` id ``` there, maybe you could try getting the primary key of the model?

This is breaking because count(column) will not count when the specific column has a null value also ppl my be using this on a model that doesn't have the ``` id ``` column...

**Comment by xuqihua** [comment]
@fernandobandeira 
Thank you.  I dont know there is old PR.
I have tested it in my project 😂

**Comment by taylorotwell** [comment]
If this is a breaking change we can not merge it into 5.4.

**Comment by Numline1** [comment]
@taylorotwell Any chance this would make it into 5.5?  What changes would be necessary, except the stated defaults (PK or * instead of "id")?

**Comment by decadence** [comment]
@xuqihua can you make it for 5.5?

**Comment by xuqihua** [comment]
@decadence 
Maybe, but I have used another way to solve such situation。
sub-query is a slow solution

**Comment by decadence** [comment]
@xuqihua
Yes but sometimes it's acceptable.
Give it a try for 5.5 please.

**Comment by xuqihua** [comment]
@decadence 
okay

**Pull request closed without merging**
