### PR TITLE
[6.0] Remove excess dependency illuminate/support from container

### PR DESCRIPTION
**Pull request by mixartemev**
thought from [this discussion](https://github.com/mixartemev/framework/pull/3#discussion_r306925644)

### CODE REVIEW

**Review by driesvints — APPROVED** [review]

**Review by antonkomarev — APPROVED** [review]

**Comment by staudenmeir** [comment]
If the value is never an object, we can replace `Arr::wrap($value)` with `(array) $value`.

**Comment by mixartemev** [comment]
@staudenmeir as I can see $concrete is never object, is only string or array, therefore your solution is great!:)

**Review by oliverquynh — APPROVED** [review]

**Comment by sisve** [comment]
What about the second place where it's documented as `* @param  \Closure|string  $implementation	`? Wouldn't that Closure be an object? Can it be cast to an array?

**Comment by mixartemev** [comment]
@sisve
Yes, Closure would be array wrapped in this case. But `$implementation` is other param. `$this->concrete` is array wrapped, not `$implementation`. And `$this->concrete` in this cace can be only string or array.

**Comment by taylorotwell** [comment]
(array) and Arr::wrap() are not the same thing. Please use the equivalent behavior.

**Comment by mixartemev** [comment]
@taylorotwell 
I don't see what might happen wrong with (array), but OK, here is exactly the same behavior #29420

**Pull request closed without merging**
