### PR TITLE
Modern Github badges using Shields.io

### PR DESCRIPTION
**Pull request by wouterds**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We tried those before, but Taylor reverted.

**Comment by GrahamCampbell** [comment]
Also, if we do use them, it'll probably be the flat style.

**Comment by WouterDS** [comment]
@GrahamCampbell what's wrong with the shields.io badges? Why not use them?

**Comment by GrahamCampbell** [comment]
We had issues with them before regarding if we use them we bust their api limit on github because of the traffic this repo gets.

**Pull request closed without merging**
