### PR TITLE
[5.2] Remove obsolete code from symfony/finder.

### PR DESCRIPTION
**Pull request by crynobone**
Based from symfony/symfony@be729e3

Signed-off-by: crynobone crynobone@gmail.com

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
What was it replaced with though?

**Comment by crynobone** [comment]
Not sure, but I remember you saying that the class we use is intelligent enough to load additional deps automatically. Right?

**Comment by GrahamCampbell** [comment]
Yes and no. We only load classes that php will actually force us to load. For example, if a class extends another class, we must load it, but if a class is just imported and not directly used, it will not get loaded.

**Comment by GrahamCampbell** [comment]
It might be cool, and somewhat easy to write some code that will just go through the imports and load them though. We'd have to be careful where imports might reference classes that don't exist, from optional dependencies and the like.

**Comment by crynobone** [comment]
<http://packanalyst.com/class?q=Symfony%5CComponent%5CFinder%5CExpression%5CExpression>

Seem like it an internal class, and we have already remove the related class before #10347

**Comment by GrahamCampbell** [comment]
Right. :)

**Pull request merged**
