### PR TITLE
[5.2] Upgraded to class preloader 2

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
@taylorotwell I wonder if we should just do this on 5.1?

**Comment by taylorotwell** [comment]
Sure. I guess the output is the same?

**Comment by GrahamCampbell** [comment]
Yeh, the output's totally identical. :)

**Comment by taylorotwell** [comment]
Yeah that's fine

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/pull/9446

**Pull request closed without merging**
