### PR TITLE
[10.x] Get foreign keys of a table

### PR DESCRIPTION
**Pull request by hafezdivandari**
This PR adds `Schema::getForeignKeys()` method to get foreign keys' info of the given table. 

## Usage
Just like `Schema::getColumns()` added on #48357 and `Schema::getIndexes()` added on #49204, the new `Schema::getForeignKeys()`method is to inspect the tables' foreign keys.

### `Schema::getForeignKeys()`
* `name` (`?string`): Name of the constraint (`null` on SQLite)
* `columns` (`string[]`): Array of local columns' names
* `foreign_schema` (`?string`):
  * SQLite: `null`
  * MySQL: Database name of the foreign table
  * PostgreSQL and SQL Server: Schema name of the foreign table
* `foreign_table` (`string`): Foreign table's name
* `foreign_columns` (`string[]`): Array of foreign columns' names
* `on_update` (`string`): Action rule on update (`cascade`, `set null`, `set default`, `restrict` (except SQL Server), `no action`)
* `on_delete` (`string`): Action rule on delete (`cascade`, `set null`, `set default`, `restrict` (except SQL Server), `no action`

### CODE REVIEW

**Comment by hafezdivandari** [comment]
Failing tests seem unrelated to this PR, but related to previously reported issue on #46165?

**Comment by iBotPeaches** [comment]
@hafezdivandari - I believe you are hitting this - https://github.com/shivammathur/setup-php/issues/798

Just hit our projects with same stack

**Comment by hafezdivandari** [comment]
Thanks for letting me know, I mark this PR as draft for now, will re-run the tests after `shivammathur/setup-php` issue resolved.

**Comment by mpyw** [comment]
@hafezdivandari  This also breaks compatibility with https://github.com/umbrellio/laravel-pg-extensions...
- https://github.com/umbrellio/laravel-pg-extensions/actions/runs/7287329915/job/19857806106

----

Related to:

- https://github.com/laravel/framework/pull/49231
- https://github.com/umbrellio/laravel-pg-extensions/pull/82

**Comment by hafezdivandari** [comment]
@mpyw ok, what can I do about this?

**Comment by mpyw** [comment]
@hafezdivandari I'll appreciate if you send a PR for umbrellio/laravel-pg-extensions that fixes argument type compatibility problem. 

- Remove native argument type constraint from newly overridden methods.

or

- Remove overridden methods, confirming it keeps the almost same behavior.

**Comment by mpyw** [comment]
@hafezdivandari Oh, please review https://github.com/umbrellio/laravel-pg-extensions/pull/83

**Pull request merged**
