### PR TITLE
[8.x] Fix distinct validation rule bug

### PR DESCRIPTION
**Pull request by amir9480**
This PR fixes issue #37257 .

### CODE REVIEW

**Comment by taylorotwell** [comment]
I don't think this is the right fix. IMO you should not be specifying `value.*` as distinct the rule should just be `'value' => 'array|distinct'` - but that doesn't work either at the moment. I'm not positive what the correct fix would be but I don't think th is it.

**Comment by taylorotwell** [comment]
Basically, I think you are using `distinct` in a way it was not intended to be used. Distinct is intended to be used with a payload like the following where you want to make sure no duplicate `id` fields are submitted:

```php
'users' => [
    [
         'id' => 1,
    ],
    [
         'id' => 2,
    ]
]
```

It is not designed to verify if a single array contains any duplicate values.

**Comment by amir9480** [comment]
@taylorotwell 
No, I'm 100% sure this was the problem,
If we put 'distinct' rule after array element rules It's gonna work as expected.

```php
$v = Validator::make(
    ['value' => [25, 25]], 
    [
        'value.0' => 'numeric|min:10|max:30', 
        'value.1' => 'numeric|min:20|max:40',
        'value.*' => 'distinct'
    ]
);
$v->errors()->all(); // The value.0 field has a duplicate value., The value.1 field has a duplicate value.
```

The bug only exists when we put a distinct rule before the array element rule.
```php
$v = Validator::make(
    ['value' => [25, 25]], 
    [
        'value.*' => 'distinct',
        'value.0' => 'numeric|min:10|max:30',
        'value.1' => 'numeric|min:20|max:40'
    ]
);
$v->errors()->all(); // []
```

This issue caused because this line ([ValidationRuleParser.php:67](https://github.com/amir9480/framework/blob/4eff7e2a1178c73069d36613b8deb11cff2187dd/src/Illuminate/Validation/ValidationRuleParser.php#L67)) changes the content of the `$rules` array but the `$rule` is the value before changing calling `explodeWildcardRules`.

**Comment by amir9480** [comment]
@taylorotwell 
I'm sure this was the problem,
If we put 'distinct' rule after array element rules It's gonna work as expected.

```php
$v = Validator::make(
    ['value' => [25, 25]], 
    [
        'value.0' => 'numeric|min:10|max:30', 
        'value.1' => 'numeric|min:20|max:40',
        'value.*' => 'distinct'
    ]
);
$v->errors()->all(); // The value.0 field has a duplicate value., The value.1 field has a duplicate value.
```

The bug only exists when we put a distinct rule before the array element rule.
```php
$v = Validator::make(
    ['value' => [25, 25]], 
    [
        'value.*' => 'distinct',
        'value.0' => 'numeric|min:10|max:30',
        'value.1' => 'numeric|min:20|max:40'
    ]
);
$v->errors()->all(); // []
```

This issue exists because this line ([ValidationRuleParser.php:67](https://github.com/amir9480/framework/blob/4eff7e2a1178c73069d36613b8deb11cff2187dd/src/Illuminate/Validation/ValidationRuleParser.php#L67)) changes the content of the `$rules` array but the `$rule` is the value before calling `explodeWildcardRules`.

**Pull request closed without merging**
