### PR TITLE
[5.6] Add allowed ip's or networks to Maintenance Mode

### PR DESCRIPTION
**Pull request by cesargb**
With this PR I can access to the App in maintenance mode from certain ip address or networks.

Example:
```bash
php artisan down --allow=127.0.0.1 --allow=192.168.0.0/16
```

### CODE REVIEW

**Comment by browner12** [comment]
Can you explain your use case? When is your App going into maintenance mode, and what do you need to see on your production app when it's in maintenance mode?

**Comment by m1kfb** [comment]
Fixing Data issues in production would be one use case, would be particularly useful for e-commerce instances changing promotional content.

**Comment by browner12** [comment]
ahh, so you're thinking like an https://apple.com shutting down its store when it adds new products?

**Comment by m1kfb** [comment]
Yeah, you and sort out product layouts, banners etc... without displaying to customers till it's ready. I don't currently require this functionality myself but could see it being useful.

**Comment by BrandonShar** [comment]
Nice idea. I always whitelist my own IP when I take a production site down. It's nice to be able to have a look around before turning everything back on.

**Pull request merged**
