### PR TITLE
[5.2] Changed controllers wildcards from static {one?}{two?}{three?}... to dynamic by ReflectionAPI

### PR DESCRIPTION
**Pull request by slavarazum**
Now we can correctly use route model bindings and pattern filters for controllers in **_RouteServiceProvider_**.
When we registered a controller:

``` php
Route::controller('some', 'SomeController');
```

with action:

``` php
public function getAction($foo, $bar, $baz = 'World!')
{
    return 'Hello ' . $baz;
}
```

Laravel will register _/some/action/{one?}/{two?}/{three?}/{four?}/{five?}_ route
Now it will look like **/some/action/{foo}/{bar}/{baz?}**
After we can use:

``` php
public function boot(Router $router)
{
    $router->pattern('foo', '[0-9]+');
    //or
    $router->model('bar', \App\User::class);
    //or
    $router->bind('baz', function ($value) {
            return strtoupper($value);
    });
    parent::boot($router);
}
```

If you want to use IoC conteiner to inject something like `Request $request` or `Guard $auth`, you can do this in any place of your method parameters.

``` php
public function getAction(Request $request, $foo, $bar, $baz = 'World!')
{
    return 'Hello ' . $baz;
}
```

or

``` php
public function getAction($foo, $bar, $baz = 'World!', Request $request)
{
    return 'Hello ' . $baz;
}
```

or

``` php
public function getAction($foo, $bar, Guard $auth, $baz = 'World!', Request $request)
{
    return 'Hello ' . $baz;
}
```

It won't affect your route parameters, it's still the same - **/some/action/{foo}/{bar}/{baz?}**

### CODE REVIEW

**Comment by taylorotwell** [comment]
What is all this $next logic supposed to be doing?

**Comment by darthmaim** [comment]
The `$next` logic loops through the remaining arguments and checks if any of those are required, because the current parameter can't be optional then. That handles cases like `public function getAction($optional='foo', $bar)` resulting in `{optional}/{bar}` instead of `{optional?}/{bar}`. Correct me if I'm wrong.

**Comment by taylorotwell** [comment]
Going to hold off on this. Too much to maintain and would prefer people just use explicit routes if they are concerned about parameter names.

**Comment by Lamp27** [comment]
@darthmaim 
Yes, you'r right! It works this way.
@taylorotwell 
Do you like this hardcode ? ```$uri.'/{one?}/{two?}/{three?}/{four?}/{five?}'```
When you type ```artisan route:list``` it's looks very funny.
And now we can't bind something on routes parameters or match some pattern on it, when we use controllers.
Also we can't define required route parameters in controller actions
Do you propose define all routes explicit?
For example:
```php
Route::get('cart/show/{user}', 'CartController@getIndex');
Route::post('cart/add/{user}/{product}', 'CartController@postAdd');
Route::put('cart/update/{user}/{product}', 'CartController@putUpdate');
Route::delete('cart/remove/{user}/{product}', 'CartController@deleteRemove');
```
With my proposition we can bind only
```php 
Route::controller('cart', 'CartController');
```
it's making routes more flexible. Why not?

**Comment by Anahkiasen** [comment]
You can use `Route::resource` though.

**Comment by Lamp27** [comment]
@Anahkiasen 
Really? resource for routes like this ```cart/update/{user}/{product}``` ?

**Comment by Anahkiasen** [comment]
Yes, it's called [nested resources](http://laravel.com/docs/master/controllers#restful-nested-resources)

**Comment by Lamp27** [comment]
You didn't understand what I'm talking about.

**Comment by igorsantos07** [comment]
I really can't understand how such "basic" feature like this was postponed with arguments like "use resources for what's not a resource" or "too much to maintain, I prefer to have developers hardcode their routes". See #10659 to understand how poisonous this kind of "weird behaviour" can be for new users.

Reflections are used in other frameworks to have a more meaningful and understandable API matching between methods and routes. It makes little to no sense to have five **hardcoded** arguments bound to actions. It makes even less sense to have to repeat some routes that should have query methods - as they're usually more meaningful - as they've been described before using the `Route::controller` call.

**Comment by igorsantos07** [comment]
I would even add here that this poses a real bug to application routing behaviour. As this is a search, it has optional arguments that must be sent over the URL - so the search results are shareable. This generates those two issues:
- everywhere I generate a shortcut link to a search result throughout the system, I'll have to remember the parameters order - or else, the search implementation will get screwed up
- if I create a search form (searchs are usually made through forms, right?), I'll actually have to find out my parameters in a different way, as they'll be named instead of indexed? WTF?

**Comment by Lamp27** [comment]
@igorsantos07 
That's exactly what I meant!
It's really absurdly. But as you can see, @taylorotwell doesn't hear community opinion, he says "Too much to maintain"... and left the dialog :D

**Pull request closed without merging**
