### PR TITLE
[5.2] Let the MySqlGrammar use the right JSON types instead of just strings

### PR DESCRIPTION
**Pull request by sebwas**
Supposed you have a column `attr` in your table. Supposed your table has these entries:

```
+------+--------------------------------------+
| name | attr                                 |
+------+--------------------------------------+
| a    | {"a": 1, "b": 3.1415926, "c": "foo"} |
| b    | {"a": 2, "b": 1.7182818, "c": "bar"} |
+------+--------------------------------------+
```

Now using Eloquent to get the row where the value of `a` is 1, you would have `DB::raw(1)` as the value in the call to `where` like this:

```
/* case #1 */ $model->where('attr->a', 1); // Does not work!
/* case #2 */ $model->where('attr->a', DB::raw(1));
```

With this fix, you can easily use it as you would expect (like in case 1).

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Could you add an integration test here please since your changes are largely untested (i think).

**Comment by sebwas** [comment]
It is tested as good as the "normal" MySQL JSON functionality.

Still want me to test it more thoroughly?

**Comment by GrahamCampbell** [comment]
Yes please. It also should make sure we don't break it later.

**Comment by themsaid** [comment]
So you remove '?' and replace them with the actual values instead of giving the task to PDO, why don't we just use the right binding via `PDOStatement::bindValue`?

**Comment by sebwas** [comment]
You are right.
Unfortunately, the query builder does not bind each param, but actually binds them all at once with the call to `PDOStatement::execute`. Also that would actually take all the flexibility you have by using the JSON column.

Your way is indeed cleaner, but that would require a rewrite of the whole query builder.

Strings are still bound using the `?`, the rest is type checked and is inserted accordingly.

**Comment by themsaid** [comment]
Well, a PR for that was already merged in 5.3: https://github.com/laravel/framework/pull/13066/files

Please let me know what do you think of it, also I believe in MySQL this change isn't breaking but I'm not sure about other engines supported by PDO.

**Comment by sebwas** [comment]
Yeah, I like that. That is a good way.
But a little problem is the little support of different types.

This does not really solve the problem I have with the JSON types though. Double is inserted as string, thus does not work (as expected). Boolean as well.
There might be more problems I can't think of right now.

**Comment by themsaid** [comment]
What about other DB engines, do you think this change is considered breaking?

**Comment by sebwas** [comment]
Well, since the PDO is the limiting element in the whole equation, I don't really see that.

Don't get me wrong, though, it's a good start, I think, but it's not the end. There's more to do.

**Comment by themsaid** [comment]
I think if we covered the rest of the types using PDO param types (`PDO::PARAM_BOOL`, 'PDO::PARAM_NULL') will provide a simpler implementation, also to cast double as integer.

**Comment by themsaid** [comment]
Actually the case with integers and strings, it can be handled by using the proper PDO parameter type, the thing with booleans is different though. `PDO::PARAM_BOOL` simply doesn't give the expected results. I believe the safest thing here is to mention that only integers & strings are to be used in a json field.

**Comment by sebwas** [comment]
Yeah, well, as I said, the PDO is the limit here ...

I don't think this should be where we stop. Either we make the PDO better, or we make our own version. Those are the possibilities imo.
JSON that only uses integers and strings doesn't work. Although these are probably the most used types, this is far from perfection.

**Comment by taylorotwell** [comment]
Making our own PDO isn't on the table, heh. Any improvements should come on PDO::bindParam on the 5.3 / master branch.

**Comment by sebwas** [comment]
PDO::bindParam won't fix the problems there are with the JSON data types that are not inserted correctly into the query, which this PR was about.

I see the possible security concerns, but since strings are still bound using the `?` placeholder and other types rely on the internal PHP type, I don't see an issue here.

Please re-consider merging this PR, as it would extend JSON support in Eloquent.

**Pull request closed without merging**
