### PR TITLE
[5.2] Fix SparkPost doesn't send attachments

### PR DESCRIPTION
**Pull request by billmn**
Fix issue #13546.

Here SparkPost's docs on attachments:
https://github.com/SparkPost/sparkpost-api-documentation/blob/master/services/transmissions_api.md#attachment-attributes

### CODE REVIEW

**Comment by TresErres** [comment]
Hi there,

After this fix, I'm getting:

Call to undefined method Swift_MimePart::getFileName()
vendor/laravel/framework/src/Illuminate/Mail/Transport/SparkPostTransport.php:68

**Comment by billmn** [comment]
Can you post your code?
I have used this code and it works fine:

```php
Mail::send('mail', [], function($mail) {
    $mail->to('email@address.ext')->subject('Sparkpost test');
});
```

Also my test has an empty "_children" array:
schermata 2016-05-26 alle 09 19 49

**Comment by TresErres** [comment]
Sure, here is:
```php
Route::get('/tm', function () {

    $message = 'Muy buenos días';

    $data = [
        'from_name' => 'rrr',
        'to_name' => 'rrr',
        'body' => $message,
    ];

    Mail::send([
        "emails.you-have-new-notification",
        "emails.you-have-new-notification-plain",
    ],
    $data,
    function ($message) {
        $message
            ->to('rrr@example.com', 'Ricardo')
            ->subject('Ricardo le ha enviado mensaje');
    });
});
```

**Comment by eleftrik** [comment]
I have the same issue reported by @TresErres

**Comment by billmn** [comment]
Ok thank you, I've found the problem ... I'm working on, soon a fix.

**Comment by billmn** [comment]
<blockquote>Call to undefined method Swift_MimePart::getFileName()</blockquote>

@TresErres This error because the message plain version is in getChildren() array. Soon a fix.

**Comment by kezkankrayon** [comment]
I have the same issue reported by @TresErres.

**Comment by taylorotwell** [comment]
Does anyone have a fix?






On Sat, May 28, 2016 at 6:00 AM -0700, "kezkankrayon" <notifications@github.com> wrote:












I have the same issue reported by @TresErres.

**Comment by billmn** [comment]
@taylorotwell Yes but I'm testing the fix in different cases: https://github.com/billmn/framework/commit/fea984df2de3b826a3cf0f68216bdc2f17582700

**Pull request merged**
