### PR TITLE
[5.8] Rename cached schema to cached scheme

### PR DESCRIPTION
**Pull request by TBlindaruk**
Rename `cachedSchema` to `cachedScheme` , since `cachedSchema` is deprecated from 
 https://github.com/laravel/framework/pull/26640 

P/S: please merge 5.7 br into master before merge this PR

### CODE REVIEW

**Comment by taylorotwell** [comment]
Looks like there is a lot of other commits in this PR. Can you send again?

**Comment by TBlindaruk** [comment]
@taylorotwell ,

It is happening since of 5.7 br is not in the master ;)

Could you merge 5.7 into master, please?

**Comment by driesvints** [comment]
@TBlindaruk if you want to add something to the next release (5.8) you can simply branch of the master branch. This will prevent commits from 5.7 to also be included.

**Comment by TBlindaruk** [comment]
@driesvints , I know this.

But in this PR I have delete of some code which was added only to the 5.7 and not merged to the master yet.

**Comment by driesvints** [comment]
@TBlindaruk ah okay! I see @GrahamCampbell just merged 5.7 into 5.8 so you should be able to resend it now :)

**Pull request closed without merging**
