### PR TITLE
Add deleteOrCreate Method to Eloquent Builder

### PR DESCRIPTION
**Pull request by codezardasht**
### Introduction

This PR introduces a new method `deleteOrCreate` to the `Eloquent\Builder` class. This method allows developers to either delete an existing record based on specified attributes or create a new one if the record does not exist.

### Motivation

In many scenarios, developers need a convenient way to delete a record if it exists or create a new one if it doesn't. This functionality is similar to the existing `updateOrCreate` method but focuses on deletion and creation. This method simplifies the logic and reduces boilerplate code for such operations.

### Scenario: User Hearting a Gift
Consider a scenario where a user can react to a gift with a "heart". If the user has already reacted to the gift with a heart, this reaction should be deleted. If the user hasn't reacted yet, a new reaction should be created.

### Implementation

The `deleteOrCreate` method attempts to find the first record matching the given attributes using `firstOrNew`. If the record exists, it is deleted. If the record does not exist, a new one is created with the specified attributes and values.

### Method Signature

```php
public function deleteOrCreate(array $attributes, array $values = [])
{
    return tap($this->firstOrNew($attributes), function ($instance) use ($attributes, $values) {
        if ($instance->exists) {
            $instance->delete();
        } else {
            $instance->fill(array_merge($attributes, $values))->save();
        }
    });
}


###Conclusion
This method enhances the Eloquent ORM by providing a straightforward way to handle delete-or-create operations, making the code more concise and readable.

### CODE REVIEW

**Comment by hamoshwani** [comment]
Thank you for the contribution! The deleteOrCreate method is a valuable addition to Eloquent Builder, simplifying workflows by combining delete and create operations.

**Comment by GrahamCampbell** [comment]
This seems pretty edge-casey to me. I'm not sure this belongs in the framework core. I note also you both work for the same company.

**Comment by codezardasht** [comment]
> This seems pretty edge-casey to me. I'm not sure this belongs in the framework core. I note also you both work for the same company.

Your note is correct, we both are co-founder of Technobase company

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
