### PR TITLE
[5.8] Arr:getFirst($array $keys...) | Get the first element in an array based on key where value is set

### PR DESCRIPTION
**Pull request by martinhschei**
In a project i needed to get the values from a array passed down to a function where either value X,Y or Z was set.

```
$a = [
 'email' => '',
 'phone' => '',
 'mobile' => '12345678',
];
```

I wanted to pass this on to some other function in the same class with using the same structure ( 'mobile' => '12345678') not only the value. To both figure out which of the values is set and grab the whole $key => $value structure i created a helper as in this PR.

Also if there is a prioritized order of the values it will pick the first one. Let's say you are identifing a user by email, phone (office, home, etc.) or mobile, but you prefer email, can do it with phone, and it barely is sufficient with mobile, you could easily prioritize it like this and get the one which is set.

```
if ($identifier = Arr::getFirst($array, 'email', 'phone', 'mobile')) {
   // buisness..
}

```

Since this is a new function is does not break any existing projects. It is useful in the use case described above and it probably exists some other similar use case where it also can clean up code and be useful.

I really enjoy working with Laravel, it's a great framework!

### CODE REVIEW

**Comment by ahinkle** [comment]
How is this different from `Arr::first()`?

**Comment by ahinkle** [comment]
Looks very close to `Arr::first()` -- might be too confusing on the differentiation.
 
I imagine you can accomplish the same with tweaking `Arr::only()` a bit.. e.g: `Arr::only($a, ['nested']`.

**Comment by mfn** [comment]
Implementation aside, having `Arr::first` and `Arr::getFirst` is confusing

**Comment by martinhschei** [comment]
@ahinkle i agree. maybe a better route to take is to adjust some existing method.

@mfn i see your point, but i have not managed to find a short, unique and descriptive name - suggestions? maybe adjusting ::first insted of creating a new method?

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
