### PR TITLE
[10.x] Update Kernel::load() to use same `classFromFile` logic as events

### LINKED ISSUE #47312: Cannot auto-register commands in non-default namespace with multiple namespaces
### Laravel Version

9.52.7

### PHP Version

8.1.10

### Database Driver & Version

Postgres 14

### Description

Hello!

The `App\Console\Kernel::console()` does not register commands that are outside of the default namespace---this is due to a bug in the class name parsing algorithm which assumes commands are always in the `App` namespace and produces a 'class' that looks like:
```
"App\<namespace_path>\Support\Commands\EventReminders"
```

This can be fixed by replacing the logic in `Kernel::load()`:
https://github.com/laravel/framework/blob/c60191f33a88f91685634b157b4dc515381fccd1/src/Illuminate/Foundation/Console/Kernel.php#L337-L341
with the logic from `DiscoverEvents::classFromFile()`:
https://github.com/laravel/framework/blob/c60191f33a88f91685634b157b4dc515381fccd1/src/Illuminate/Foundation/Events/DiscoverEvents.php#L88-L97
which the `EventServiceProvider` uses to auto-register listeners (and does work with listeners in non-default namespaces).

Thanks!

### Steps To Reproduce

1. Register 2 different namespace in application
2. Place command in non-default namespace
3. Attempt to auto-register command in Kernel

### PR DESCRIPTION
**Pull request by calebdw**
Closes #47312

Replaces the logic the `Console\Kernel` uses to parse classes from files with the same logic used by Events in `DiscoverEvents::classFromFile()`---this allows commands outside the `App` namespace to be auto-registered if desired.

Thanks!

### CODE REVIEW

**Comment by driesvints** [comment]
I don't feel we should do this. I don't think we should encourage people to move these files outside the default `app` directory.

**Comment by CalebDW** [comment]
Why not? I work on a large application and we follow a DDD approach inside another namespace, there's no reason for an artificial restriction that all commands must be inside the `app` directory.

I just updated the logic to be consistent with the logic already being used when auto-registered Listeners

**Comment by CalebDW** [comment]
Note that this was just a quick, in-place edit, but longer term it might be a good idea to move this logic to a `DiscoverCommands` class similar to `DiscoverEvents` (possibly with the common logic abstracted to a `DiscoverClasses` class that both of them extend)

**Comment by taylorotwell** [comment]
Reverted: https://github.com/laravel/framework/issues/47377

**Comment by devlob** [comment]
I agree, I'm also using Laravel as my Infrastructure on a project that I use DDD and I was shocked that the commands for autoloading would be hardcoded to `app`, I want the freedom to change that as a developer.

**Pull request merged**
