### PR TITLE
[5.1] Fixing scheduler switch user with withoutOverlapping together not working

### LINKED ISSUE #13332: Laravel schedule switch 'user' combined with 'withoutOverlapping' not working
Tested this on Laravel 5.1 and Lumen 5.1

My command is set to run every minute, change user and without overlapping:

```php
$schedule->command('command')
    ->user('vagrant')
    ->withoutOverlapping();
```

I'm getting the following error when running it as root:

```
$ php artisan schedule:run
Running scheduled command: sudo -u vagrant (touch /web/storage/framework/schedule-2d4441595514912ce98d904112cb2c13; '/usr/bin/php5' 'artisan' command; rm /web/storage/framework/schedule-2d4441595514912ce98d904112cb2c13) > '/dev/null' 2>&1 &
sh: 1: Syntax error: "(" unexpected
```

Thanks in advance.

### PR DESCRIPTION
**Pull request by pulkitjalan**
Fixes #13332

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What about windows support?

**Comment by pulkitjalan** [comment]
Ah... Sorry didn't test Windows.

Does `sudo -u` work on Windows anyway?

Also what terminal on Windows, the native one?

**Comment by GrahamCampbell** [comment]
We need to get it to ignore the user flag on windows.

**Comment by pulkitjalan** [comment]
ok, so this be ok? or do you think there should also be a check in the user() function for if windows throw exception?

```
if (windows_os()) {
    return $command;
}

return $this->user ? 'sudo -u '.$this->user.' -- sh -c \''.$command.'\'' : $command;
```

**Comment by GrahamCampbell** [comment]
I was just thinking: `return $this->user && ! windows_os() ? 'sudo -u '.$this->user.' -- sh -c \''.$command.'\'' : $command;`

**Comment by pulkitjalan** [comment]
Cool, done that. Thanks.

**Pull request merged**
