### PR TITLE
fix single line @php statements to not be parsed as php blocks

### LINKED ISSUE #45330: Blade renderer breaks when mixing 2 @php-syntaxes in the same view
- Laravel Version: 9.43.0
- PHP Version: 8.1.13
- Database Driver & Version: n/a

### Description:

When mixing `@php(..)` and `@php`/`@endphp` later in the view the renderer breaks and gives preference to the @php/endphp pair above the parentheses.

Same issue as just posted, but tested in V9. @driesvints your excuse of "don't use it" is from my perspective not really an excuse. If you have a view of 400+ lines add `@php/@endphp` somewhere in the bottom and you didn't notice that someone else added `@php(..)` somewhere higher up in that same file you pull your hair out on why it doesn't work. Because the errors get quite weird when mixing things with other directives in between.

### Steps To Reproduce:

See https://github.com/rikvdh/laravel-broken-blade-view/blob/v9/resources/views/welcome.blade.php

You expect 'goodbye' as output. But this breaks.

The rendered view:
```php
<?php($hello = 'welcome')
@php
    $hello = 'goodbye';
?>

<?php echo e($hello); ?>

<?php /**PATH /Users/rikvdh/tmp/broken-view/resources/views/welcome.blade.php ENDPATH**/ ?>%                  
```

### PR DESCRIPTION
**Pull request by rikvdh**
when @endphp is also in the same file, + unit test, fixes #45330

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks!

**Comment by rikvdh** [comment]
🙂

@taylorotwell Do I need to create this for 10.x as well? Or gets this merged automatically into there?

**Comment by driesvints** [comment]
@rikvdh fixes for 9.x get merged in master 👍

**Comment by taylorotwell** [comment]
Reverted due to breaking changes:

https://github.com/laravel/framework/issues/45388

**Pull request merged**
