### PR TITLE
[11.x] Requires Guzzle on `laravel/framework`

### PR DESCRIPTION
**Pull request by nunomaduro**
Due to the high usage of this dependency in the core, it probably makes sense to actually move this dependency to `laravel/framework` instead of having 99% of the skeletons include this dependency in their `composer.json` file. It's probably easier for us to simply manage this ourselves.

Here is the companion PR on the skeleton: https://github.com/laravel/laravel/pull/6324.

### CODE REVIEW

**Comment by antonkomarev** [comment]
@nunomaduro What about start moving to depency on psr/http-client in framework to let people not be tied to exact version of the concrete client?

**Comment by driesvints** [comment]
@antonkomarev not sure I follow. Could you give some concrete examples?

**Comment by GrahamCampbell** [comment]
I don't see the point in doing that. It was not possible before, even before guzzle was moved to the require block.

**Comment by antonkomarev** [comment]
I don't mean that we should do it right now, it will require to rewrite all http client integrations. I'm talking about future possibilities to not strictly stick to concrete Guzzle versions.

I frequently faced situations when projects are using Guzzle major version X and packages required major version Y. Using the HTTP Client interface we could use any version of Guzzle, as well as another one HTTP client without conflicts.

**Pull request merged**
