### PR TITLE
[5.2] Cache Command - Option to remove tagged items

### PR DESCRIPTION
**Pull request by KennedyTedesco**
To entirely remove the default store:

```
php artisan cache:clear
```

Optionally you can set up the store name to be removed:

```
php artisan cache:clear myFooStore
```

But, if you would like just remove some tagged items:

```
php artisan cache:clear --tags=foo
```

Or items of many tags:

```
php artisan cache:clear --tags=foo,bar
```

To my applications this is very useful.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Probably best going to 5.3 IMO.

**Comment by KennedyTedesco** [comment]
@GrahamCampbell Are you sure? This works fine on 5.2.

**Comment by GrahamCampbell** [comment]
Don't retarget please. It's just a comment for Taylor.

**Comment by KennedyTedesco** [comment]
Got it.

**Pull request merged**
