### PR TITLE
[8.x] Fix SqlServerGrammar::compileDropDefaultConstraint: remove hardcode schema in sql command

### LINKED ISSUE #37419: Migrate failed to drop default constrains in an mssql databases
Hi,

if you work in a MSSQL database not in the default schema dbo, then faild to delete default constraint via "php artisan migrate".
The problem is in the function compileDropDefaultConstraint in class Illuminate\Database\Schema\Grammars\SqlServerGrammar . In the function the dbo schema is hard coded. 

in Illuminate\Database\Schema\Grammars\SqlServerGrammar.php
```
    /**
     * Compile a drop default constraint command.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileDropDefaultConstraint(Blueprint $blueprint, Fluent $command)
    {
        $columns = "'".implode("','", $command->columns)."'";

        $tableName = $this->getTablePrefix().$blueprint->getTable();

        $sql = "DECLARE @sql NVARCHAR(MAX) = '';";
        $sql .= "SELECT @sql += 'ALTER TABLE [dbo].[{$tableName}] DROP CONSTRAINT ' + OBJECT_NAME([default_object_id]) + ';' ";
        $sql .= 'FROM SYS.COLUMNS ';
        $sql .= "WHERE [object_id] = OBJECT_ID('[dbo].[{$tableName}]') AND [name] in ({$columns}) AND [default_object_id] <> 0;";
        $sql .= 'EXEC(@sql)';

        return $sql;
    }
```
On version "Laravel Framework 8.42.0"

### PR DESCRIPTION
**Pull request by MichaelGottschlich**
PR to fix #37419

### CODE REVIEW

**Comment by taylorotwell** [comment]
What if this breaks other applications?

**Comment by MichaelGottschlich** [comment]
by leaving out the schema no problem should occur. Since if no schema is specified, the user's default schema is used. Which is otherwise also the case.

**Comment by gmutinel** [comment]
I think this COULD break things, if someone has a dbo schema but not setted as default (could be done for security reasons), this will break what was previously working. I think this should go to the database configuration with 'dbo' as default

**Comment by MichaelGottschlich** [comment]
it should not break anything, since the new create tables, view and constraints is always created in default schema of the user. 

If you want to do it right you need a setting for it.

If you now create a new table with constraints and the DB user is assigned e.g. mySchema as default schema. You can't delete the constraints anymore.

**Comment by taylorotwell** [comment]
No plans to implement this atm.

**Comment by MichaelGottschlich** [comment]
this is the only function where the dbo scheme is hard coded. 
If this is to be a security issue, then over all the scheme must be hard coded.

**Comment by gmutinel** [comment]
What I meant is that a DB could be built with more than one Schema and what you're targeting is NOT the default one (for security reasons dbo could not be writable by the non-admin users).
But yes, you're correct, it should be handled in all SQL Server related functions as a setting, the same as connection (so a default one in the DB settings and an override in the Model). As a trick you should be able to hardcode it into the $table variabile in the model, but it's an hack imho.

**Comment by MichaelGottschlich** [comment]
How so I need to use the dbo schema in my database?

For example, if I want to run several applications in one database. Then I can assign a schema to each application. Give the data users the appropriate permissions on the respective schema.

I could also use a table prefix but I can't just set the permissions over the schema but have to authorize each table individually.

Security issues only arise if the permissions are not set correctly.

**Comment by MichaelGottschlich** [comment]
if you to write with schema than can use sql function SCHEMA_NAME(). SCHEMA_NAME() get current schema.



> As a trick you should be able to hardcode it into the $table variabile in the model, but it's an hack imho.
The trick with the table name does not work, because the table name is in [].

**Pull request closed without merging**
