### PR TITLE
[5.8] Add translation to EnsureEmailIsVerified Middleware

### PR DESCRIPTION
**Pull request by cbaconnier**
This pull request change the raw string 'Your email address is not verified.' to be translatable

Hopefully I did it correctly

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
@taylorotwell  This will break the component because the `__` function doesn't exist outside of foundation.

**Comment by cbaconnier** [comment]
@GrahamCampbell Is `Lang::getFromJson()` would work then?

**Comment by driesvints** [comment]
@cbaconnier `abort` messages shouldn't displayed to the end user. They're converted to HttpExceptions which are RuntimeExceptions. In a Laravel app you typically make templates for these codes and put any message you have in there.

**Comment by cbaconnier** [comment]
@driesvints I understand that `__()` needs to be reverted . But it took make longer to understand your answer.

It made sense when I realised that the [message is translated in the view](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Exceptions/views/403.blade.php#L5).

I'm so sorry for having make lose your time! 🙇🙇🙇

**Comment by driesvints** [comment]
No problem 👍

**Pull request merged**
