### PR TITLE
[9.x] Add a separate Rate Limiting Service Provider (Deferrable)

### PR DESCRIPTION
**Pull request by paras-malhotra**
With expanding the scope of RateLimiters to jobs as well (https://github.com/laravel/framework/pull/34829), it might be the right time to introduce a `RateLimitingServiceProvider` in 9.x. This can be where users can register all their rate limiters so that there's a dedicated provider to do so (instead of using `AppServiceProvider` for jobs and `RouteServiceProvider` for routes). 

Also, this should improve performance slightly as it is a deferrable provider, so the named rate limiter registrations would only trigger when the app resolves the `RateLimiter`.

This is a breaking change because I'm extracting out the `RateLimiter` singleton registration to a separate provider. That's why this PR targets master.

If this PR is accepted, I'll send across a PR to the Laravel skeleton repo for a `RateLimiterServiceProvider` in the `app/Providers` directory that extends the base provider in this PR and registers the named rate limiters in the `boot` method.

### CODE REVIEW

**Comment by Shizzen83** [comment]
I encountered this issue but I simply used the `resolving` method of the container to lazily setup the rate limiter

```php
$this->app->resolving(RateLimiter::class, function (RateLimiter $rateLimiter, $app) {
            $rateLimiter->for('api', function (Request $request) {
                return Limit::perMinute(60);
            });
        });
```

By this way, you don't need an additional service provider (you may for clarity of course, but no need for a deferrable one).

**Comment by paras-malhotra** [comment]
Yep, that's a good workaround for performance. I just think it may make sense to have it as a service provider for both convenience (one class for both route and job rate limiters vs job limiters in AppServiceProvider and route limiters in RouteServiceProvider) and performance (without the workaround you suggested).

**Comment by GrahamCampbell** [comment]
> $this->app->resolving(RateLimiter::class, function (RateLimiter $rateLimiter, $app) {

This is absolutely the correct way to do this, and is not a "workaround". It is just the correct way to do it, if you want the best performance. Similar to registering blade stuff.

**Comment by paras-malhotra** [comment]
You're probably right but I would have appreciated some more insights into when to create a ServiceProvider rather than a resolving callback.

**Pull request closed without merging**
