### PR TITLE
[5.5] Backport PHP 7.3 and 7.4 Support

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by driesvints** [comment]
5.5 has ended though.

**Comment by GrahamCampbell** [comment]
This isn't going to work because of PHPUnit.

**Comment by majuansari** [comment]
@GrahamCampbell @driesvints Any chance to get PHP 7.4 support for Laravel 5.5?

**Comment by driesvints** [comment]
@majuansari 5.5 is EoL

**Pull request closed without merging**
