### PR TITLE
[12.x] use promoted properties

### PR DESCRIPTION
**Pull request by browner12**
this new feature helps reduce a lot of boilerplate code.

resubmission of #53807 

I had originally started the original PR against master, but then was concerned if there were changes prior to the v12 release, we might run into some annoying merge conflicts. as long as we're not concerned about that too much, then this master targeted PR should be good.

### CODE REVIEW

**Comment by mnabialek** [comment]
My only concern here is that comments for properties that contains some more info are not there anymore.

**Comment by Rike-cz** [comment]
Sorry, but this is really not good pattern.
1. part of properties get shrink into constructor and lost full comment,
2. part of properties stay on top as usual.
Together it brings worse readability because both types of declaration have different "rhythm".

**Comment by rodrigopedra** [comment]
Can't we keep the properties comments in the constructor docblock?

**Review by JurianArie — COMMENTED** [review]
~Type hinting the callables as `\Closure` might be a breaking change for some people. Before this change callable instances were also accepted~

@donnysim you are right, I only looked at the properties but did not check the constructor.

**Comment by donnysim** [comment]
@JurianArie i don't see any type hints being changed here tho 🤔 they all were and still are Closure type.

**Comment by taylorotwell** [comment]
I do think I'll just leave this off for now since we lose information from docblocks.

**Pull request closed without merging**
