### PR TITLE
[5.7] Expose readStream and writeStream to allow cross-filesystem actions

### PR DESCRIPTION
**Pull request by tomlankhorst**
This allows easy reading/writing of files across filesystems and to response-streams. 

Across filesystems:
```php
Storage::disk('s3')
  ->writeStream(
    'remote-file.zip',
    Storage::disk('local')->readStream('local-file.zip')
  );
```

To response-streams:
```php
return response()
  ->stream( function() {
    fpassthru( Storage::disk('s3')->readStream('file.zip') );
  });
```

### CODE REVIEW

**Comment by sisve** [comment]
Would it make sense to have readStream throw an exception on failures instead of returning null? A null value cannot provide much debugging information into _what_ failed.

**Comment by taylorotwell** [comment]
Why are we inventing new exception types. Just let Flysystem throw whatever exception it throws.

**Comment by tomlankhorst** [comment]
@taylorotwell Such that I can specify what exceptions the implementation of the Filesystem contract might throw. On the other hand, these exceptions can be avoided in the first place so I might remove them as well.

**Comment by tomlankhorst** [comment]
@sisve Sure, currently this is a relic of Flysystem which returns null on failure. Could throw an exception on `null` return.

**Pull request merged**
