### PR TITLE
Add required if size validations

### PR DESCRIPTION
**Pull request by aligulzar729**
This PR adds the ability to make a field required if the size of the given field is equal to, less than (max) or greater that (min) the given size. This is quiet convenient, readable, shorter and doesn't need importing Rule class.
Also, I'm currently working on the same thing for exclude if validation.
carbon.

### CODE REVIEW

**Comment by igorgaming** [comment]
Why not just use [sometimes](https://laravel.com/docs/9.x/validation#validating-when-present)?

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by igorgaming** [comment]
> > Why not just use [sometimes](https://laravel.com/docs/9.x/validation#validating-when-present)?
> 
> Because it's just a different story. Consider this scenario you want to validate attachments only when there are more than 2 attachment element in attachments array. How do you write the validation rule for this scenario? Is it doable with sometimes?

It sounds weird, do you have a real-life example?

**Comment by agulzar-netlinks** [comment]
> > > Why not just use [sometimes](https://laravel.com/docs/9.x/validation#validating-when-present)?
> > 
> > 
> > Because it's just a different story. Consider this scenario you want to validate attachments only when there are more than 2 attachment element in attachments array. How do you write the validation rule for this scenario? Is it doable with sometimes?
> 
> It sounds weird, do you have a real-life example?

```php
  'attachments' => [
      'array',
      Rule::requiredIf(count(request('attachments', [])) > 0),
  ],
  'attachments.*' => [
      'required_with:attachments',
      'integer',
      'exists:attachments,id'
  ],
```

**Pull request closed without merging**
