### PR TITLE
[11.x] Implements route description

### PR DESCRIPTION
**Pull request by juanparati**
Routes currently supports name actions, that are very handy for call routes using some kind of canonical name, however the names are not very descriptive, so I decided to implement optional description for routes.

Some examples of route description usage are:

```PHP
    Route::get('account/view/{id}', 'BankAccountController@viewAccount')
        ->name('account:view:account')
        ->description('View the bank account for customer %s');

    Route::post('user/secret', 'UserController@storePin')
        ->name('user:set:secret')
        ->description('Set user secret PIN'); 

    Route::post('user/secret', 'TranslationEsController@store')
        ->name('store:spanish:translation')
        ->description([
              'language' => 'spanish',
              'operation' => 'store translation'
              'only' => 'admin'
         ]);
```

The benefits for this feature are:
- Descriptions can be used for log semantic description of an action into a log, user activity, journal, etc.
- Descriptions can be show to end-user in order to help with interaction (Ex: "You cannot set user secret PIN" instead "Unable to perform operation user:set:secret").
- Descriptions accept mixed values like arrays so it can be used in order to pass data directly to the controller.

The implementation of the description is totally innocuous and it doesn't modify the default "Routing" behavior. It's just a getter and setter implementation.

This feature can be easily implemented using macros, so it may have not sense to overload more the framework with extra features. If your feel that this feature is very trivial please close this PR without answer.

Example of this feature implementation using macros:

```PHP
        Route::macro('description', function (string $desc) {
            $this->desc = $desc;
            return $this;
        });

        Route::macro('getDescription', function () {
           return $this->desc ?? null;
        });
```

### CODE REVIEW

**Comment by cosmastech** [comment]
This could be useful if the Laravel team ever decides to support generating OpenAPI docs as first-class concern of the framework.

**Comment by donnysim** [comment]
I'd personally prefer if it supported callbacks, I don't want to allocate a bunch of memory for text that will mostly never be used outside of console and it would also allow translating them.

**Comment by rojtjo** [comment]
> I'd personally prefer if it supported callbacks, I don't want to allocate a bunch of memory for text that will mostly never be used outside of console and it would also allow translating them.

A callback actually uses a lot more memory than a simple string: https://3v4l.org/UuRot

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

**Comment by donnysim** [comment]
@rojtjo that depends on the string, I doubt the descriptions will be as simple as "Some description". Also just adding "Some description" to array does not allocate new strings as PHP caches all string occurrences and reuses them so it would be more appropriate to add something like `'Some description ' . $i`, which would still be smaller in this case than functions, but we're still using unrealistically short text if we're thinking about using it for generating some API documentation.

**Comment by rojtjo** [comment]
You are totally right! I jumped to conclusions too quickly here.

**Pull request closed without merging**
