### PR TITLE
[11.x] Add `Dumpable` trait to Uri

### PR DESCRIPTION
**Pull request by nuernbergerA**
This adds the ability to the new `Uri` class to call `dd()` and `dump()`

### CODE REVIEW

**Comment by filipac** [comment]
I think that Dumpable is not ideal in this class, I would like to see something like `dd($this->value());` not the whole object.

**Comment by nuernbergerA** [comment]
> I think that Dumpable is not ideal in this class, I would like to see something like `dd($this->value());` not the whole object.

I started with the simplest way and see what Taylor thinks and will override `dump` if he thinks that just the string should be dumped

**Comment by nuernbergerA** [comment]
> You probably should add a test case for https://github.com/laravel/framework/blob/11.x/tests/Support/SupportUriTest.php too.
> 
> (I am thinking of at least something like a reflection that checks for traits to be on the class)

all other classes in the code base that use the dumpable trait don't have such tests.

**Comment by adaliszk** [comment]
> all other classes in the code base that use the dumpable trait don't have such tests.

Oh wow, that does not sound too great; now that I think about it, a test to expect a class pattern to include the trait would be much more useful. That way one generic test would be able to force all classes to include it as an architecture test.
Anyway, you know the code and its testing requirements better; only my gut feeling was commenting.

**Pull request closed without merging**
