### PR TITLE
[5.3] Backup offset/limit properties when running pagination/chunk queries

### PR DESCRIPTION
**Pull request by vlakoff**
Still preparing the field for https://github.com/laravel/internals/issues/103.

Sample code that would be failing currently:
```php
// get a paginator
$paginator = $query->paginate(...);

// leftover offset/limit clauses are unexpectedly applied here:
$topMovies = $query->where('rating', '>=', '9')->get();
```

Sadly tests can't be added for this, `forPage` being mocked.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Couldn't you add an integration test for it?

**Comment by vlakoff** [comment]
I have added integration tests for `paginate` and `chunk` methods, for Eloquent and Query Builder.

But I noticed the code currently doesn't work for `chunkById`, as it's using `forPageAfterId`.

**Comment by vlakoff** [comment]
I have fixed `chunkById`, though it's becoming a bit bloated…

Also there remains `simplePaginate` to be verified.

**Comment by taylorotwell** [comment]
All of this stuff is getting ridiculous. What are we doing?

**Comment by taylorotwell** [comment]
I don't understand how Laravel has existed for 5 years without these ridiculous things?

**Comment by vlakoff** [comment]
I understand your position, the code is more complicated than I was expecting. It's really a "gains vs. code complexity" situation. So, shall we just accept that paginate/chunk methods "pollute" the builder instance, and the instance is not reusable after?

**Comment by taylorotwell** [comment]
I would. Re-using the query builder in general is bad practice IMO even though I believe the core does it once for getting the count and then running the pagination query. In general though it should never be done and I don't feel like polluting everything up just to accomodate it.

**Pull request closed without merging**
