### PR TITLE
[8.x] Trim Japan space full width character "　"

### PR DESCRIPTION
**Pull request by SocolaDaiCa**
I use Japan language. It has space full with "　".
when I type into input with only space full with "　"  and submit, middleware TrimStrings cant trim It and required validate rule will not work correct.

I had modify middleware TrimStrings and create test case for It. Please help to verify It.

image

image

@taylorotwell

### CODE REVIEW

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Comment by SocolaDaiCa** [comment]
Hi @taylorotwell ,
I Had update description. Please help to verify It

**Comment by deleugpn** [comment]
You need to open a new PR to get this evaluated if you made enough changes to the explanation. As someone that has been  bitter  by the Japanese character it may be a valid change. Just try again!

**Comment by SocolaDaiCa** [comment]
@deleugpn  https://github.com/laravel/framework/pull/37947 I create new PR, but it closed,

I Think, next time,  I will create method cover all unicode space https://markushedlund.com/dev/trim-unicodeutf-8-whitespace-in-php/

But I dont know how to write all unicode space for testing

**Pull request closed without merging**
