### PR TITLE
[5.4] Implement Every X Minutes

### PR DESCRIPTION
**Pull request by alexbowers**
Implements the ability to specify cron frequencies.

### CODE REVIEW

**Comment by alexbowers** [comment]
Ignore this. I realised that i've messed up. Will fix.

**Comment by alexbowers** [comment]
If approved, I'd like to refactor a couple of existing methods:

- everyFiveMinutes
- everyTenMinutes
- everyThirtyMinutes

I'd also like to propose the ability to do the same with hours, days, months etc.

**Comment by jakesyl** [comment]
@alexbowers additionally, you might even considering asking @taylorotwell  to remove those methods, or at least deprecate them and flag them for removal in a later version

**Comment by alexbowers** [comment]
I was thinking that keeping them as "helper" methods would be useful, but that they would utilise this method.

**Comment by sisve** [comment]
Does this work for larger values than one hour, like `->everyXMinutes(90)`?

**Comment by alexbowers** [comment]
Honestly not sure what would happen in those circumstances. Best bet is
probably tjrow an out of range exception for <= 1 and >60

**Comment by taylorotwell** [comment]
I think I'm going to hold off on this to be honest. Maybe it would be better to make this macroable or something?

**Comment by alexbowers** [comment]
@taylorotwell Would you mind sharing why you don't want this in? It makes it much more readable for doing things like `everyXMinutes(20)`, etc. Which currently would require a custom `cron()` call, which is harder to parse / read.

**Pull request closed without merging**
