### PR TITLE
[11.x] Fix the edge case of `.php` extension chopping in make commands

### PR DESCRIPTION
**Pull request by osbre**
As pointed by @jasonmccreary in this comment: https://github.com/laravel/framework/pull/51843#issuecomment-2190232393

Update: dependent on https://github.com/laravel/framework/pull/51924

### CODE REVIEW

**Comment by timacdonald** [comment]
This is not the same functionality as the origin is also problematic.

`rtrim` will trim characters, not the given string as a whole.

```php
php artisan make:model Foo.php

// Foo

php artisan make:model Sponsorship

// Sponsorshi

php artisan make:model Photograph

// Photogra
```

**Comment by osbre** [comment]
Good catch. Seems like a good case for introducing `Str::chop` 😅 will send a PR shortly

**Comment by timacdonald** [comment]
@osbre, I have just created a PR to fix the make command and introduce a helper function for this type of string manipulation.

**Comment by osbre** [comment]
@timacdonald  Good job! That was fast lol. I was deciding between `chop` and `chopEnd` and you've already done it 😂

**Pull request closed without merging**
