### PR TITLE
[5.1] fix doctrine/inflector version to pull 1.1.0

### PR DESCRIPTION
**Pull request by janhartigan**
This is a clone of #20227 for the 5.1 branch.

### CODE REVIEW

**Comment by gmsantos** [comment]
I guess composer will stop on 1.1 with the current constraint

**Comment by janhartigan** [comment]
^1.0 will take you all the way up to <2.0.0

**Comment by gmsantos** [comment]
Only if all constraints is satisfied... In a system with PHP 5.6 the version will be 1.1... In PHP 7.0 the version will be 1.2 and finally in PHP 7.2 the version will be 1.3 (or newer)

**Comment by janhartigan** [comment]
Interesting...any documentation on that? I just ran into this problem in a local environment running php7.0 and laravel 5.2. The specific issue was:

```
[Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - Installation request for laravel/framework 5.2.* -> satisfiable by laravel/framework[5.2.x-dev].
      - laravel/framework 5.2.x-dev requires doctrine/inflector ~1.0 -> no matching package found.
  ].
```

Maybe I'm just reading the error wrong?

**Comment by janhartigan** [comment]
Could it be that it's based on the php version in the `require` block rather than the local environment php version?

**Comment by gmsantos** [comment]
I ran a test on this (travis build)[https://travis-ci.org/gmsantos/inflector/builds/257074965?utm_source=github_status&utm_medium=notification]

See the output for each PHP version:

image

image

image

**Comment by janhartigan** [comment]
Yeah ok I think this is my problem. I just ran a bare-bones test on 5.1 and got the same results as you. Thanks for helping me poke around @gmsantos

**Pull request closed without merging**
