### PR TITLE
[9.x] Add price directive for blade

### PR DESCRIPTION
**Pull request by milwad-dev**
Convert number format to directive blade

### CODE REVIEW

**Comment by ankurk91** [comment]
Lets call it money or currency

**Comment by milwad-dev** [comment]
@ankurk91 
ok

**Comment by milwad-dev** [comment]
{{ number_format(5000000) }}
@money(5000000)

**Comment by driesvints** [comment]
I wouldn't do this. This is a pretty domain specific keyword that could be used in lots of apps where the expected implementation would be different (different library like MoneyPHP, decimal handling, etc). This is best defined in userland.

**Comment by milwad-dev** [comment]
@driesvints 
Sometimes can use directive to use php function!

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
