### PR TITLE
[5.7] Move Notifiable trait to "Authenticatable"

### PR DESCRIPTION
**Pull request by Byorun**
move Notifiable trait to "Authenticatable" base class for default laravel user model since the CanResetPassword trait used there depends on $this->notify(). After that we can delete the Notifiable trait from the user model shipped by the default laravel installation. This should make it clearer that the Notifiable trait is needed in order for the default password reset function to work properly.

### CODE REVIEW

**Comment by morloderex** [comment]
So what happens right now if someone where to remove the trait from the user model? does it break the resets password functionallity?

**Comment by Byorun** [comment]
right now you would get:
BadMethodCallException with message 'Call to undefined method Illuminate\Database\Query\Builder::notify()

**Comment by taylorotwell** [comment]
Will just keep it on there to be explicit.

**Comment by Byorun** [comment]
then maybe a hint about breaking default password reset if removed could be helpful. Since removing it would not immediately affect your laravel installation

**Pull request closed without merging**
