### PR TITLE
[9.x] Throw Exception if a query expression is defined in `order by` for cursor pagination

### PR DESCRIPTION
**Pull request by maximepvrt**
Add check for non-aliased expression in order by clause in cursorPaginate() method

This change adds a check to ensure that expressions used in the order by clause are aliased and also included in the select clause. If a non-aliased expression is used, a RuntimeException will be thrown with an appropriate message.

This change ensures that cursorPaginate() method works correctly with expressions used in the order by clause, and prevents potential issues with non-aliased expressions.

> Query expressions in "order by" clauses are supported only if they are aliased and added to the "select" clause as well.
[https://laravel.com/docs/9.x/pagination#cursor-vs-offset-pagination](https://laravel.com/docs/9.x/pagination#cursor-vs-offset-pagination)

Additionally, I attempted to write a test case that would trigger the RuntimeException when a non-aliased expression is used in the order by clause, but was not able to do so.

Thanks for considering this merge request!

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by maximepvrt** [comment]
Hi @taylorotwell, currently without this explicit error, the error returned is "can only flip string and integer values" from this line https://github.com/laravel/framework/blob/9.x/src/Illuminate/Pagination/AbstractCursorPaginator.php#L208. I think it would be good to add explicit errors to encourage adoption of cursor pagination.

**Comment by maximepvrt** [comment]
@taylorotwell, have you seen my last message ?

**Comment by maximepvrt** [comment]
@driesvints 😇

**Comment by driesvints** [comment]
Looks like Taylor doesn't wants to merge this one sorry.

**Pull request closed without merging**
