### PR TITLE
[5.2] Declare missing abstract render method

### PR DESCRIPTION
**Pull request by lucasmichot**
Declare missing abstract `render` method.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Maybe this belongs on 5.3?

**Comment by lucasmichot** [comment]
Well it's a bug in fact - so I am a bit wondering
Thought on which branch I shall target @taylorotwell ?

**Comment by lucasmichot** [comment]
A workaround could also be:
```php
public function __toString()
{
    if (! method_exists($this, 'render')) {
        return;
    }

    return (string) $this->render();
}
```

**Comment by taylorotwell** [comment]
Holding off on this. Doesn't even appear to match the signature on the other classes.

**Pull request closed without merging**
