### PR TITLE
[7.x] Refactor duplicated logic in Component

### PR DESCRIPTION
**Pull request by imanghafoori1**
It refactors a little bit of duplicated logic into a method with a readable name.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmm, the tests are failing now. The only "change" I did was correct the type of the method cache to be an array as documented, instead of a collection...

**Comment by imanghafoori1** [comment]
@GrahamCampbell I review it now

**Comment by imanghafoori1** [comment]
@GrahamCampbell The problem is the `->all()` method.

line 116:  static::$propertyCache[$class] = $this->getNames($publicProperties)->all();

remove it

**Comment by driesvints** [comment]
Feel free to attempt again with passing tests

**Comment by GrahamCampbell** [comment]
No it's not? I think you are looking at an old copy of the diff?

**Comment by GrahamCampbell** [comment]
@imanghafoori1 I can re-open this PR once the tests are fixed.

**Comment by imanghafoori1** [comment]
The failure is interesting, I'll check the root cause of it

**Comment by imanghafoori1** [comment]
@GrahamCampbell The ignoring aspect does not work now.

**Pull request closed without merging**
