### PR TITLE
[8.x] Update the badges to use shields.io

### PR DESCRIPTION
**Pull request by pataar**
Shields.io works a lot better than the old pugx.org.

### CODE REVIEW

**Review by driesvints — APPROVED** [review]
Agreed. We should roll these out on all repos. They're much more reliable.

**Comment by pataar** [comment]
@driesvints I can upgrade the rest of the badges in other repositories too if you like?

**Comment by driesvints** [comment]
@pataar that would be fantastic. Thank you 👍

**Comment by pataar** [comment]
There you go!

**Comment by driesvints** [comment]
Thank you!

**Pull request merged**
