### PR TITLE
[9.x] Default address methods

### PR DESCRIPTION
**Pull request by jasonmccreary**
Upon using these two methods for the first time recently, my expectation was they would automatically set the column name for me given their specific method names.

I addressed this tiny paper-cut by defaulting the column name inline with Laravel's naming convention (snake case) for both the `ipAddress` and `macAddress` methods.

**Before**
```php
$table->ipAddress('ip_address');
$table->macAddress('mac_address');
```

**After equivalent**
```php
$table->ipAddress();
$table->macAddress();
```

_**Note:** I considered this a breaking change since it updates the method signatures. However, this could be defaulted in another way to merge into Laravel 8.x if desired._

### CODE REVIEW

**Comment by jasonmccreary** [comment]
The failure seems unrelated. However, let me know if this somehow affected those tests.

**Comment by GrahamCampbell** [comment]
Yep, we're aware master is failing, due to pending upstream (testbench) changes. Should be sort out soon. :)

**Comment by GrahamCampbell** [comment]
Hmmm, I don't think I like these defaults.

**Comment by jasonmccreary** [comment]
@GrahamCampbell I felt there were sensible/predictable given Laravel's naming convention and the current method names. I'm open to whatever. These were really just for convenience. One can always pass the argument.

**Pull request merged**
