### PR TITLE
[10.x] Revert UUID v7 changes

### PR DESCRIPTION
**Pull request by driesvints**

### CODE REVIEW

**Comment by Bosphoramus** [comment]
so no UUID v7 support? 👀

**Comment by driesvints** [comment]
@Bosphoramus You can easily opt into it yourself.

**Comment by Bosphoramus** [comment]
oh i see @driesvints, so this pr only changes the default UUID version back to 4 but still allows v7 to be used?
how can we opt to use v7? will this be documented on the docs? 
Thank you!

**Comment by driesvints** [comment]
Here's the docs on that: https://laravel.com/docs/9.x/eloquent#uuid-and-ulid-keys

**Pull request merged**
