### PR TITLE
[5.7] Set relation on parent for HasOne and HasMany

### PR DESCRIPTION
**Pull request by avrahamappel**
When you create a parent - child relationship from the child end, the relationship is set on the child:

```
$comment = new Comment;

var_export($comment->post); // --> NULL

$comment->post()->associate(Post::create())->save();

var_export($comment->post instanceof Post); // --> true
```

However, when you create the relationship from the parent end, this is currently not the case:

```
$post = Post::create();

var_export($post->comments->isEmpty()); // --> true

$post->comments()->save(new Comment());

var_export($post->comments->first() instanceof Comment); // false
```

I don't see why we shouldn't have the same behavior in both cases. This pull request adds a line to the `HasOneOrMany::save` method that makes this possible.

Seems that this idea was referenced way back in '13 in Issue #731, but nothing ever came of it.

### CODE REVIEW

**Comment by staudenmeir** [comment]
This doesn't work properly when the relationship hasn't been loaded yet:

```php
$post = Post::create();
$post->comments()->save(new Comment());
dump($post->comments);
```

In this case, `$post->comments` contains the new comment twice. `save()` also executes an additional query to load the relationship that wouldn't be necessary for many/most of the users.

If the relationship has been loaded, the result is still not ideal because it doesn't respect a potential `orderBy()` clause the relationship might have.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by avrahamappel** [comment]
@staudenmeir I understand the first issue, which is easily solved. 

For the second issue, I guess there's no way around it without the existing Collection keeping track of how its items are grouped, which definitely seems like overkill at this point. In practice though, I think I would expect the new comment to be automatically added to the comments property more than I would be bothered by the fact that it isn't sorted.

I still feel like there is value in this feature; tell me what you think.

**Comment by staudenmeir** [comment]
I agree that the potentially incorrect order is a minor issue.

But personally, I don't think this feature justifies such a big change.

**Comment by avrahamappel** [comment]
I hear you.

**Comment by ChristopheB** [comment]
I agree that this feels a bit strange, especially when serializing just after.

With belongsTo, it works as expected:
```php
<?php

$comment = new Comment;
$comment->post()->associate(Post::create());
$comment->save();

// OK, the serialized comment contains the post
dump(isset($comment->toArray()['post'])); // => true
```

But on the hasMany side, the $relations property is indeed not updated:
```php
<?php

$post = Post::create();
$post->comments()->save(new Comment);

// The serialization of $post does not contain any comment
dump(isset($post->toArray()['comments'])); // => false

$post->fresh();
$post->refresh();

// Fresh and refresh don't help
dump(isset($post->toArray()['comments'])); // => false
```

I might be missing something, but I don't even know how to get a fresh set of relations, without explicitly calling ``$post->comments`` or ``$post->load('comments')``. Even though, when serializing this post I would expect to have its comments appended.

Any chance this could be reconsidered?

**Pull request closed without merging**
