### PR TITLE
[7.x] Update ramsey/uuid lib

### PR DESCRIPTION
**Pull request by caiquecastro**
Update ramsey/uuid library

### CODE REVIEW

**Comment by driesvints** [comment]
Think we might be able to do this on 6.x as well?

**Comment by GrahamCampbell** [comment]
Please update the suggested text for `moontoast/math` to say that it is only needed if you are using the uuids v3 package, on both places where it occurs as a suggestion.

**Comment by taylorotwell** [comment]
Why allow multiple versions of things?

**Comment by driesvints** [comment]
@taylorotwell the amount of libraries still requiring v3 is enourmous. This way we they can upgrade in the meantime while we can drop v3 in a future major version.

**Comment by shez1983** [comment]
@taylorotwell  this has caused a clash with vapour btw.. as i suspect we add in 4.0 but vapour is asking/requiring 3.9 so is not installing.. so i had to manually for now remove 4.0

**Comment by GrahamCampbell** [comment]
Not a clash. This allows BOTH versions. If you add vapour manually to your composer json, then run composer update, it will install properly. The `composer require` command is a bit thick.

**Pull request merged**
