### PR TITLE
[5.4] Test predis and phpredis together

### PR DESCRIPTION
**Pull request by halaei**
reopen for https://github.com/laravel/framework/pull/17853

### CODE REVIEW

**Comment by tillkruss** [comment]
@taylorotwell: Should we make sure PhpRedis supports `WITHSCORES` as well for compatibility?

**Comment by taylorotwell** [comment]
Yes, the whole point is for them to be basically 100% compatibility so you can switch without noticing. If we can't hit that goal then PhpRedis would just need to be removed.

**Comment by taylorotwell** [comment]
This breaks my tests locally unless I have PHPRedis installed. How can we skip those tests if it is not installed? It's impossible for me to test Laravel locally now. :(

**Comment by halaei** [comment]
@tay

On Feb 13, 2017 5:13 PM, "Taylor Otwell" <notifications@github.com> wrote:

This breaks my tests locally unless I have PHPRedis installed. How can we
skip those tests if it is not installed? It's impossible for me to test
Laravel locally now. :(

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/laravel/framework/pull/17882#issuecomment-279395563>,
or mute the thread

**Comment by halaei** [comment]
Adding some logic to tell dataprovider function don't  put ['phpredis'] in
the returned array will be good.
Having said that, it is not that hard to install phpredis? In ubuntu sudo
apt-get install php-redis does that.

**Comment by tay** [comment]
@halaei I think you meant to tag @taylorotwell instead of me 👋

**Comment by halaei** [comment]
@tillkruss @taylorotwell I think phpredis support should have been added to `predis` package not laravel. What are we doing here after all?

**Pull request merged**
