### PR TITLE
[10.x] Add multiple exceptions support for the `rescue` helper function

### PR DESCRIPTION
**Pull request by jeffrey-kroonen**
Sometimes you have a case where more than one exception can be thrown and you want to perform a certain action for each case. Currently it is not possible to do this with the `rescue` function.

For example you wan't to perform a simple action.

```php
try {
    $user = User::query()->findByEmail($email);
} catch (ModelNotFoundException $e) {
    // Do something when model is not found.
} catch (UnauthorizedException $e){
    // Do something when the current user is unauthorized.
}
```

With the added implementation to support multiple exceptions we can now do this to with rescue!

```php
$user = rescue(
    fn () => User::query()->findByEmail($email),
    [
        ModelNotFoundException::class => function (Throwable $e) {
            // Do something when model is not found.
        },
        UnauthorizedException::class => function (Throwable $e) {
            // Do something when the current user is unauthorized.
        },
        function () {
            // This block of code will be executed when non of the above exceptions match.
        }
    ]
);
```

As you can see we have added a third array item without a key. This will be executed as our last resort. This is not mandatory and can be omitted if desired.

### CODE REVIEW

**Comment by rojtjo** [comment]
Can't you just solve this by handeling it in the rescue callback?

```php
$user = rescue(
    fn () => User::query()->findByEmail($email),
    fn (Throwable $e) => match ($e::class) {
        ModelNotFoundException::class => "User not found: $email",
        UnauthorizedException::class => 'Unauthorized',
        default => 'Something went wrong',
    },
);
```

**Comment by jeffrey-kroonen** [comment]
@rojtjo Thank you for your comment. This wouldn't solve the problem for the case when you want to use a callback as value.

 ```php
rescue(
    fn () => User::query()->findByEmail($email),
    fn (Throwable $e) => match ($e::class) {
        ModelNotFoundException::class => function () use ($email) {
            // Do something when model is not found.

            return "User not found: $email";
        },
        default => 'Something went wrong',
    },
);
```

**Comment by rojtjo** [comment]
You could solve that by wrapping the `match` expression in a `value` call.

```php
rescue(
    fn () => User::query()->findByEmail($email),
    fn (Throwable $e) => value(match ($e::class) {
        ModelNotFoundException::class => function () use ($email) {
            // Do something when model is not found.

            return "User not found: $email";
        },
        default => 'Something went wrong',
    }),
);
```

Also, I just realised this might be a breaking change since you can't really know if the passed array is a map of exception handlers or an actual fallback value:

```php
rescue(
    fn () => throw new Exception('Foo'),
    ['username' => 'guest'],
);
```

Result before change: `['username' => 'guest']`
Result after change: `null`

**Comment by nunomaduro** [comment]
Thank you for trying to contribute to Laravel. It's a good idea. However, it's a breaking change:

```
$value = rescue(function () {
    throw Exception('Foo');
}, [1, 2, 3]);

// Before: [1, 2, 3]...
// After: 1
```

**Pull request closed without merging**
