### PR TITLE
[5.1] using less memory in getExtension

### PR DESCRIPTION
**Pull request by pouya-parsa**
By remove one useless variable,we will use less memory.

### CODE REVIEW

**Comment by reshadman** [comment]
Based on [this](http://www.phpinternalsbook.com/zvals/memory_management.html) PHP does not exactly copy the array until it is modified.

**Comment by GrahamCampbell** [comment]
The performance using php 5.5 should be the same before and after.

**Comment by pouya-parsa** [comment]
@GrahamCampbell But what about the result memory_get_usage() shows about using less memory ?
I trusted it :disappointed:

**Comment by GrahamCampbell** [comment]
What php version?

**Comment by pouya-parsa** [comment]
5.5.11

**Pull request closed without merging**
