### PR TITLE
[5.8] Fixed circular dependency - fix #28165

### LINKED ISSUE #28163: [5.7] Maximum function nesting level on Queue::fake()
- Laravel Version: 5.7.*
- PHP Version: 7.2

### Description:
So, refactoring some code i've found a circular dependency in the Queue mock:
If you try to call a undefined method in the Queue mock you will see a `Error : Maximum function nesting level of '256' reached, aborting!`

Obviously you can just use an existing function, but it can be an inconvenient with any method naming change.

### Steps To Reproduce:
- Create a new test.

```php
\Queue::fake();
\Queue::undefinedMethod();
```

### LINKED ISSUE #28165: [5.8] Maximum function nesting level on Queue::fake()
Laravel Version: 5.8.*
PHP Version: 7.2

Description:
So, refactoring some code i've found a circular dependency in the Queue mock:
If you try to call a undefined method in the Queue mock you will see a Error : Maximum function nesting level of '256' reached, aborting!

Obviously you can just use an existing function, but it can be an inconvenient with any method naming change.

Steps To Reproduce:
Create a new test.
\Queue::fake();
\Queue::undefinedMethod();

### PR DESCRIPTION
**Pull request by kauanslr**
This PR fix the issue opened by me (#28165).

Basically, this code override the `QueueManager::__call` magic method when the Queue is mocked to prevend a circular dependency when calling a undefined method in the mock.

To prevent any break of existing feature i've made a simple test.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Tests fail?

**Comment by kauanslr** [comment]
> Tests fail?

Yes, i'm looking this.

Two memcached tests failed with PHP7.1, i'm trying to reproduce locally.

**Comment by kauanslr** [comment]
Done.

But the Travis is crazy.

**Comment by antoniopaisfernandes** [comment]
I've got a failing test when updating to 5.8.12

```
There was 1 error:

1) Tests\Feature\Claims\ArrivingAtTheWarehouseTest::dri_cores_are_split_by_UK_and_PL
BadMethodCallException: Call to undefined method Illuminate\Support\Testing\Fakes\QueueFake::assertPushedTimes()
```

**Comment by kauanslr** [comment]
We'll, looks like there many `protected` asserts. As @chantmich  mentioned, we cold just make these methods public.

**Comment by kauanslr** [comment]
> I've got a failing test when updating to 5.8.12
> 
> ```
> There was 1 error:
> 
> 1) Tests\Feature\Claims\ArrivingAtTheWarehouseTest::dri_cores_are_split_by_UK_and_PL
> BadMethodCallException: Call to undefined method Illuminate\Support\Testing\Fakes\QueueFake::assertPushedTimes()
> ```

Maybe, a alternative is to use `assertPushed` and pass `times` in `callback` parameter.

**Comment by antoniopaisfernandes** [comment]
@kauanslr I've, since, done that.

```
Queue::assertPushed(PrintAndEmail::class, 2);
```

I just viewed assertPushedTimes as a more verbose way of testing what I intended.

Thanks anyway.

**Pull request merged**
