### PR TITLE
[5.8] Add Env class

### PR DESCRIPTION
**Pull request by kawax**
https://github.com/laravel/ideas/issues/1580

Still no breaking change.
This is for users who do not want to use env().

```php
<?php

use Illuminate\Support\Env;

return [
    'name' => Env::get('APP_NAME', 'Laravel'),
];
```

future plan
- Replace all env()
- Deprecate env() and move to `laravel/helpers`

### CODE REVIEW

**Comment by jmarcher** [comment]
Why? What is the problem with env() ? Why would someone not use env() but somehow Env::get()?

**Comment by kawax** [comment]
env() is likely to conflict with other packages. 
Same function, but a slightly different spec.

**Comment by taylorotwell** [comment]
Maybe for 5.9.

**Comment by mfn** [comment]
@kawax FWIW, I support your basic idea, thanks 👍 

I personally have been bitten by this, integrating legacy code with Laravel which also used a `env()` global function which however worked differently 💥

**Comment by driesvints** [comment]
@mfn this got added on master: https://github.com/laravel/framework/pull/28073

**Pull request closed without merging**
