### PR TITLE
[5.2] Use the method() wrapper method instead of getMethod().

### PR DESCRIPTION
**Pull request by risan**
Use the wrapper method of method() instead of getMethod() for retrieving HTTP method.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why?

**Comment by risan** [comment]
@GrahamCampbell in case in the future we are no longer subclassing from Symfony Http Request class, which provide the getMethod() class.

**Comment by GrahamCampbell** [comment]
> in case in the future we are no longer subclassing from Symfony Http Request class, which provide the getMethod() class.

That will never happen.

**Comment by GrahamCampbell** [comment]
Even if it did for some reason, we'd still have the getMethod method there.

**Pull request closed without merging**
