### PR TITLE
[5.5] Add Tests Demonstrating and Fixes for Error on Retrieving a User By Token With a Bad Identifier

### PR DESCRIPTION
**Pull request by mcordingley**
This addresses the issue that @SebastianS90 pointed out and adds tests to demonstrate it.

### CODE REVIEW

**Comment by SebastianS90** [comment]
Looks good to me, thanks!

**Comment by taylorotwell** [comment]
How many more PRs do we need on this?

**Comment by mcordingley** [comment]
Always at least one more. 😱

**Comment by taylorotwell** [comment]
It's just getting really wearisome. We've gone through about 4-5 Laravel patch releases with this simple fix.

**Comment by mcordingley** [comment]
I know. It's ridiculous. This one should end it. I've been throwing on tests with these last two pulls to block regressions from happening.

**Pull request merged**
