### PR TITLE
Use argument unpacking in PHP5.6

### PR DESCRIPTION
**Pull request by barryvdh**
See https://wiki.php.net/rfc/argument_unpacking and https://gist.github.com/barryvdh/c88c87b41afd0d88d13b

Even with the PHP check, is does seem to run twice as fast in my setup. Does need some more people testing perhaps.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Just send this to master since we've dropped php 5.5 support there.

**Comment by GrahamCampbell** [comment]
Though, actually, i already have a local branch for the master branch that uses this sort of syntax everywhere, but Taylor and I are a bit sceptical about if changing it worth it.

**Comment by GrahamCampbell** [comment]
That is, in general, not this isolated case. ;)

**Comment by barryvdh** [comment]
Well, even if it's not for performance, it's prettier than the switch statements ;)

**Comment by vlakoff** [comment]
Agree, it's much more pleasant to read. And the performance gain might be appreciable too.

@GrahamCampbell Would a PR making the change to arguments unpacking be accepted?

**Pull request closed without merging**
