### PR TITLE
[5.6] Add callback support to "optional"

### PR DESCRIPTION
**Pull request by JosephSilber**
Lets you pipe the value into an outside function, with the guarantee that you're not passing it `null`:

```php
return optional($modelOrNull, function ($definitelyTheModel) {
    return doSomethingWithTheModel($definitelyTheModel);
});
```

### CODE REVIEW

**Comment by BrandonShar** [comment]
how is this better than a ternary or an if statement? 

I love the optional helper, but I think it's getting stretched a bit far lately.

**Comment by JosephSilber** [comment]
A ternary is insufficient when the value comes from a function/expression.

**Comment by BrandonShar** [comment]
Ah ok, so this would be for cases where you might have a result of one function that you want to pass as an argument to another function. I don't think that's a common pattern for me, but that may be because I haven't been looking for it. It would probably be helpful to update the example since the current one would be more succinct as a ternary. 

There was another PR recently where a contributor wanted to add similar functionality to `tap` and I thought creating a `when` helper might be a better idea. Maybe that would be the same case here?

Personally, I like keeping optional as nothing more than a PHP version of Ruby's `&` operator, so I have a bit of a bias.

**Comment by derekmd** [comment]
`transform()` used internally by API resources can do this: https://laravel.com/docs/5.6/helpers#method-transform.

It will call the `Closure` when the value passes `filled()`.

https://github.com/laravel/framework/blob/5.6/src/Illuminate/Support/helpers.php#L1121-L1142

**Comment by crynobone** [comment]
I find it odd that `optional()` may now not return `Illuminate\Support\Optional`.

```php
optional($user, function ($user) {
    return $user->sendResetPassword();
})->getInvalidProperty->dump;
```

It now would throws exception.

**Comment by garygreen** [comment]
> I love the optional helper, but I think it's getting stretched a bit far lately.

Do a PR to remove the Optional helper. I'd +1 it. tap tap tap tap dat all day 😄

**Comment by JosephSilber** [comment]
@derekmd the `transform` helper checks for `filled`, as you've noted. Not `null`.

@crynobone I don't see that confusing at all. These are two different uses of the `optional` helper. Think of it as an overloaded method with a different return type.

**Pull request merged**
