### PR TITLE
[5.2] Add root url to elixir

### PR DESCRIPTION
**Pull request by JosephSilber**

### CODE REVIEW

**Comment by ibrasho** [comment]
Thanks :+1:

**Comment by mscharl** [comment]
:+1:

**Comment by badconker** [comment]
Hi,
This PR has disappeared from master branch : https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/helpers.php#L303

Is it normal ?

**Comment by JosephSilber** [comment]
It seems it's also gone from 5.2 :cry: 

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/helpers.php#L303

**Pull request merged**
