### PR TITLE
[5.8] Use PHP's configured default character set when outputting from "e" helper function

### PR DESCRIPTION
**Pull request by maaarghk**
Rationale is in #25689

Re-post of #25690 - against master this time because it is a potential breaking change.

### CODE REVIEW

**Comment by browner12** [comment]
I don't fully understand this, so this may be an ignorant question, but would this be better served as an env/config value?

I also feel like we need a default value, since `ini_get()` has the potential to return empty strings or `FALSE`.

```php
return htmlspecialchars($value, ENT_QUOTES, ini_get('default_charset') ?? 'UTF-8', $doubleEncode);
```

**Comment by maaarghk** [comment]
Hmmm. While I can't really think of a convincing reason why not, it doesn't really feel right. The conversation is kinda old but reading #6891 I don't think an application would be doing the right thing by calling ini_set('default_charset') with a configuration value - and using a different value here than ini_get('default_charset') is wrong, so letting them set the charset without then putting it in config would be strange.

As for defaulting to 'UTF-8' if they leave it blank, not sure either, PHP docs only say: `Setting default_charset to an empty value is not recommended.` but don't specify what behaviour to expect if you do that. [The docs](http://php.net/htmlentities) state `ini_get('default_charset')` is the default for `$encoding` anyway so I don't think we are doing anything that wouldn't happen if the user called `htmlentities` directly.

**Comment by taylorotwell** [comment]
I kinda agree this should either not change or should be configurable?

**Comment by maaarghk** [comment]
It _is_ configurable, which is actually the whole point. 

ATM it is hard coded as 'UTF-8', so not configurable. This MR makes it configurable via htmlspecialchars as the default is `ini_get('default_charset')`. So you can configure by changing php.ini.

**Pull request closed without merging**
