### PR TITLE
[5.5] Resolve bug Call to a member function onQueue() on string

### PR DESCRIPTION
**Pull request by Shegl**
Method onQueue() should be applied on ShouldQueue, not on Dispatcher.

### CODE REVIEW

**Comment by taylorotwell** [comment]
dispatch returns PendingDispatch which has an onQueue method.

**Comment by Shegl** [comment]
It can be reproduced on lumen:
$schedule->job(new SomeJob())->hourly();

It cause error: Call to a member function onQueue() on string

On updated to current version Lumen 5.5

**Comment by Shegl** [comment]
Please check this out @taylorotwell, dunno why but every "php artisan schedule:run" fails, should I create Issue than ?

**Comment by devcircus** [comment]
Maybe try to get some feedback on larachat slack. There's always someone there answering questions. At this point it doesn't seems like an issue with Laravel. If you can spin up a sample repository on github, that recreates the issue and share it there, someone can probably help. 

I use onQueue often and have never had a problem.

**Comment by piotrek-lifeinmobile** [comment]
I also found this problem in my project.

\vendor\illuminate\queue\SyncQueue.php
return 0 not a PendingDispatch
```
public function push($job, $data = '', $queue = null)
{
	$queueJob = $this->resolveJob($this->createPayload($job, $data), $queue);

	try {
		$this->raiseBeforeJobEvent($queueJob);

		$queueJob->fire();

		$this->raiseAfterJobEvent($queueJob);
	} catch (Exception $e) {
		$this->handleException($queueJob, $e);
	} catch (Throwable $e) {
		$this->handleException($queueJob, new FatalThrowableError($e));
	}

	return 0;
}
```

\vendor\illuminate\queue\RedisQueue.php
return NULL or String not a PendingDispatch
```
public function push($job, $data = '', $queue = null)
{
	return $this->pushRaw($this->createPayload($job, $data), $queue);
}
public function pushRaw($payload, $queue = null, array $options = [])
{
	$this->getConnection()->rpush($this->getQueue($queue), $payload);

	return json_decode($payload, true)['id'] ?? null;
}

```

**So this can't work in this scenario :
dispatch($job)->onQueue($queue);** 

from :
\vendor\illuminate\console\Scheduling\Schedule.php

```
    public function job($job, $queue = null)
    {
        return $this->call(function () use ($job, $queue) {
            $job = is_string($job) ? resolve($job) : $job;

            if ($job instanceof ShouldQueue) {
                dispatch($job)->onQueue($queue); <-- THIS CAN"T work in this scenario
            } else {
                dispatch_now($job);
            }
        })->name(is_string($job) ? $job : get_class($job));
    }

```

FIX from @Shegl helped mi

```
FROM : dispatch($job)->onQueue($queue);
TO: dispatch($job->onQueue($queue));

```

**Pull request closed without merging**
