### PR TITLE
[5.7] rollback `error pages` changes;

### PR DESCRIPTION
**Pull request by TBlindaruk**
In the https://github.com/laravel/framework/commit/83ca9a7706a8091de9da17cb687a0852c9ef1960 commit was introduced the new layout for the error pages. <strike> Also, messages are changed for all error pages. </strike>

I think will be better to change the message in the 5.8v.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I agree tbh. Test failing?

**Comment by TBlindaruk** [comment]
@GrahamCampbell ,  fixed

**Comment by GrahamCampbell** [comment]
👍

**Comment by TBlindaruk** [comment]
@GrahamCampbell , I have done revert for all things which are changed in the commit =_=

**Comment by TBlindaruk** [comment]
But it will change not only the message. It will change the full layout. So, images will not show anymore with this changes

**Pull request merged**
