### PR TITLE
[5.2] Convert eloquent empty attribute to null

### PR DESCRIPTION
**Pull request by guilhermegonzaga**

### CODE REVIEW

**Comment by garygreen** [comment]
Why? What if you want to set an attribute as an empty string as you don't use nulls for string fields in db?

**Comment by Sladewill** [comment]
:+1: sounds good when ever should you ever store empty strings instead of null, but it is a breaking change so maybe 5.3 because people would need to update migrations?

**Comment by garygreen** [comment]
@Sladewill That's a personal preference and Laravel shouldn't force you into a particular storage schema. Nothing in Laravel automatically converts empty strings to null. It should be left up to your app to fill your models with suitable values for your database. :-1:

**Comment by acasar** [comment]
:-1: From me too. If you want to store empty strings you should be able to do so.

**Comment by GrahamCampbell** [comment]
Empty string is not the same as null, and should not be treated as such.

**Comment by garygreen** [comment]
@GrahamCampbell worryingly all tests passed with this PR but this could have broken a lot of apps if it got thru...

**Comment by GrahamCampbell** [comment]
We'd accept a PR to add tests to assert the current behaviour so it doesn't get changed by mistake in the future. ;)

**Comment by guilhermegonzaga** [comment]
This would facilitate use:

```php
// $request ['name' => 'my name', 'field' => '']
// setted 'field' to null because there is no reason to store an empty string in the database
$model->create($request->all());
```

But I admit it could break some applications, especially if the field is not set to null in their migration.
Is there any way to convert an empty string to null in an easy way?

**Comment by acasar** [comment]
There is:

```php
$model->create(array_filter($request->all()));
```

**Comment by GrahamCampbell** [comment]
Or, do some proper validation on the data first. Also, it's not "breaking" applications if the database throws an error if it correct to do so?

**Comment by guilhermegonzaga** [comment]
Thank you.
Im not too sure about that.

- Enviada via iPhone

**Pull request closed without merging**
