### PR TITLE
[5.6] LogManager driver capable of producing logger with any Monolog handler

### PR DESCRIPTION
**Pull request by ralphschindler**
The provided driver allows a configuration centric approach to creating Logger instances (channels) where the handler can be any of the [built-in Monolog handlers](https://github.com/Seldaek/monolog/tree/master/src/Monolog/Handler) without needing to write custom factories (code).

By using `Container::build()` it is capable of matching any named constructor values from any Handler that are provided in the `handler_params` configuration option.  For non-monolog provided handlers, it is capable of accepting an option `handler_class` where it will use the full class name to instantiate/build.

Example of creating a `php://stderr` non-bubbling StreamHandler based logger:

```
    'channels' => [
        'nonbubblingstream' => [
            'driver' => 'monolog',
            'handler_type' => 'stream',
            'handler_params' => [
                'stream' => 'php://stderr',
                'bubble' => false
            ]
        ],
    //...
```

Example of a LogEntries based channel logger:

```
    'channels' => [
        'logentries' => [
            'driver' => 'monolog',
            'handler_type' => 'LogEntries',
            'handler_params' => [
                'token' => '123456789'
            ]
        ],
    //...
```

This feature is completely backwards compatible and opt-in.  If accepted, I will document it's usage in the manual.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Instead of binding contextual parameters into the container, is it possible to use `makeWith`?

**Comment by ralphschindler** [comment]
Yes! I didn't realize that make would create instances of arbitrary (non-registered) types. This is much better, it's more clear and concise. (Used `make` over `makeWith` since the latter is listed as an alias.)

**Comment by taylorotwell** [comment]
Tweaked things a hair... just went with `handler` configuration option that must be the class name. Figured people can just use Handler::class and import the handler at the top of the configuration file.

Renamed `handler_params` to `with` since it kinda matches the container argument.

Thanks!

**Comment by ralphschindler** [comment]
I dig the changes. Thanks!

**Pull request merged**
