### PR TITLE
[5.1] Escape square brackets in string which is used as a CSS ID selector

### PR DESCRIPTION
**Pull request by rairlie**
In my test I had an issue trying to interact with a form containing an input array, e.g:

```
HTML:
<input name="foo[]">
```

```
Test:
function testType {
    $this->type('value', 'foo[]');
}
```

When running PHPUnit you will see something like:

```
Symfony\Component\CssSelector\Exception\SyntaxErrorException: Expected identifier or "*", but <delimiter "]" at 6> found
```

The issue is that the field name 'foo[]' is being used to build a CSS selector:

```
{$element}#{$name}, {$element}[name='{$name}']
```

which in this case results in:

```
*#foo[], *[name='foo[]']
```

As you can see `*#foo[]` is not a valid ID selector, it should be escaped as `*#foo\[\]`. Ref: https://mathiasbynens.be/notes/css-escapes

Ideally all characters that are valid in CSS selectors should be correctly escaped,
though that seems outwith the scope of this function. Probably best to have a utility class that can build W3C-compliant CSS selectors, though I'm not aware of one for PHP?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please resolve the merge conflicts otherwise we can't accept this.

**Comment by rairlie** [comment]
Thanks - now done.

**Comment by GrahamCampbell** [comment]
We also can't merge with merge commits. Can you please rebase and force push so there is only one commit.

**Comment by taylorotwell** [comment]
I tried to fix the conflicts myself but am having trouble getting the tests to pass.

**Comment by GrahamCampbell** [comment]
Seem to be passing on travis.

**Pull request merged**
