### PR TITLE
[5.3] Add names to password routes

### PR DESCRIPTION
**Pull request by laurencei**
Add names to password routes, in a similar way to `login` and `logout`

### CODE REVIEW

**Comment by JosephSilber** [comment]
`password.request` does not properly describe what this route does.

**Comment by lioannou** [comment]
@JosephSilber - I'm open to a better name

...it is used to request a new password?

**Comment by GrahamCampbell** [comment]
Probably best to send to 5.4, not 5.3.

**Comment by taylorotwell** [comment]
Please send to 5.4.

**Pull request closed without merging**
