### PR TITLE
[5.1] Allow "message" key as mail parameter

### PR DESCRIPTION
**Pull request by billmn**
Fix https://github.com/laravel/framework/issues/11236

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Breaking change.

**Comment by GrahamCampbell** [comment]
This also doesn't actally work.

**Comment by GrahamCampbell** [comment]
You broke the addContent method.

**Comment by GrahamCampbell** [comment]
Please send to 5.2.

**Comment by billmn** [comment]
Ok I'll send to 5.2.
Can you show me where is the breaking change?

**Comment by GrahamCampbell** [comment]
The fact the variable is renamed.

**Comment by GrahamCampbell** [comment]
We're passing it through so that people can use it.

**Comment by GrahamCampbell** [comment]
TBH, I'm :-1: on the change.

**Comment by billmn** [comment]
Make sense.
Do you still want that I send the PR to 5.2?

**Comment by GrahamCampbell** [comment]
Not really up to me if this gets merged ultimately. I'm :-1: on the change going in anywhere.

**Pull request closed without merging**
