### PR TITLE
[5.5] Apply custom pivot model attribute casting on arrays

### PR DESCRIPTION
**Pull request by themsaid**
Currently attaching/syncing multiple records doesn't trigger the attribute casting on the custom pivot model:

```
$project->collaborators()->attach([
            [$user->id => ['permissions' => ['foo' => 'bar']]],
            [$user2->id => ['permissions' => ['baz' => 'bar']]],
        ]);
```

```

class CustomPivotModel extends Pivot
{
    protected $casts = [
        'permissions' => 'json',
    ];
}

```

### CODE REVIEW

**Comment by chelout** [comment]
Try this case:
```php
    public function test_casts_are_respected_on_sync_array()
    {
        $user = CustomPivotCastTestUser::forceCreate([
            'email' => 'taylor@laravel.com',
        ]);

        $user2 = CustomPivotCastTestUser::forceCreate([
            'email' => 'mohamed@laravel.com',
        ]);

        $project = CustomPivotCastTestProject::forceCreate([
            'name' => 'Test Project',
        ]);

        $project->collaborators()->attach([
            $user->id => ['permissions' => ['foo' => 'bar']],
            $user2->id => ['permissions' => ['baz' => 'bar']],
        ]);
        $project->collaborators()->sync([
            $user->id => ['permissions' => ['foo1' => 'bar1']],
            $user2->id => ['permissions' => ['baz2' => 'bar2']],
        ]);
        $project = $project->fresh();

        $this->assertEquals(['foo' => 'bar'], $project->collaborators[0]->pivot->permissions);
        $this->assertEquals(['baz' => 'bar'], $project->collaborators[1]->pivot->permissions);
    }
```

**Comment by themsaid** [comment]
@chelout if course it does, sync re-creates the records, your assertions are invalid.

**Comment by chelout** [comment]
Sorry, was in a hurry. Test throws error:

>Illuminate\Tests\Integration\Database\EloquentCustomPivotCastTest::test_casts_are_respected_on_sync_array
>ErrorException: Array to string conversion

Right assertions:

```php
    public function test_casts_are_respected_on_sync_array()
    {
        $user = CustomPivotCastTestUser::forceCreate([
            'email' => 'taylor@laravel.com',
        ]);

        $user2 = CustomPivotCastTestUser::forceCreate([
            'email' => 'mohamed@laravel.com',
        ]);

        $project = CustomPivotCastTestProject::forceCreate([
            'name' => 'Test Project',
        ]);

        $project->collaborators()->attach([
            $user->id => ['permissions' => ['foo' => 'bar']],
            $user2->id => ['permissions' => ['baz' => 'bar']],
        ]);
        $project->collaborators()->sync([
            $user->id => ['permissions' => ['foo1' => 'bar1']],
            $user2->id => ['permissions' => ['baz2' => 'bar2']],
        ]);
        $project = $project->fresh();

        $this->assertEquals(['foo1' => 'bar1'], $project->collaborators[0]->pivot->permissions);
        $this->assertEquals(['baz2' => 'bar2'], $project->collaborators[1]->pivot->permissions);
    }
```

**Comment by themsaid** [comment]
@chelout ah thanks, check now.

**Comment by chelout** [comment]
Seems fine. Thanks a lot!

**Pull request merged**
