### PR TITLE
Use installed.json for extra discovery

### PR DESCRIPTION
**Pull request by barryvdh**
As suggested @naderman in https://github.com/laravel/framework/commit/cb6474742f7f8bad649d295909fe0840520bcfa9#commitcomment-22370108 this uses `vendor/composer/installed.json`, instead of looping through al package dirs.

Renamed the test to reflect the class, and cleaned up the packages.php file before running the test, to make sure it's fresh.

One note is that the order might change, but I'm not sure if we should assume it always just random?

### CODE REVIEW

**Comment by naderman** [comment]
Hah I wasn't even looking at the right file oh well ;-)

**Comment by barryvdh** [comment]
Taylor rewrote it a few commits later :) https://github.com/laravel/framework/commit/a5a0f3e7b82a1a4dc00037c5463a31d42c94903a

Hmm, tests are failing because the installed.json is not present. @naderman Should the file always be present, or is that a recent change?

**Comment by naderman** [comment]
@barryvdh it's been there since at least 2012: https://github.com/composer/composer/commit/15ab5868a339bd523de739929fdb0f89a01a6a88

**Comment by driesvints** [comment]
Sweet!

**Pull request merged**
