### PR TITLE
[5.1] Model : allows to update with $options

### PR DESCRIPTION
**Pull request by lucasmichot**
So that we can update a model without necessary updating its timestamps:

``` php
$model->update(['foo' => 'bar'], ['timestamps' => false]);
```

### CODE REVIEW

**Comment by lukasgeiter** [comment]
:+1:

**Comment by proshanto** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Please send to 5.2.

**Comment by RomainLanz** [comment]
Why this is not added to 5.1?

**Comment by GrahamCampbell** [comment]
Because it's potentially a breaking change.

**Comment by GrahamCampbell** [comment]
For people that extend that method.

**Comment by RomainLanz** [comment]
You've got eagle eyes about breaking change :eyes:

**Pull request closed without merging**
