### PR TITLE
[5.8] Bump min Symfony version to 4.2

### PR DESCRIPTION
**Pull request by X-Coder264**
This PR bumps the minimum Symfony version to 4.2 for Laravel 5.8.

### CODE REVIEW

**Comment by driesvints** [comment]
Why though? What's the reason?

**Comment by taylorotwell** [comment]
We typically bump the Symfony minor versions on each Laravel minor version upgrade.

**Comment by driesvints** [comment]
Ok sounds good!

**Comment by GrahamCampbell** [comment]
There's various places that this PR has accidentally missed out.

**Comment by X-Coder264** [comment]
@GrahamCampbell About what places are you talking about? This PR updated it in all of them as far as I can see.

**Comment by GrahamCampbell** [comment]
For example: https://github.com/laravel/framework/blob/master/composer.json#L90, https://github.com/laravel/framework/blob/master/composer.json#L134.

**Comment by X-Coder264** [comment]
Oh sorry, I don't know how I've missed those. I see @TBlindaruk already created a PR for that :)

**Pull request merged**
