### PR TITLE
[9.x] Improve type hints in ModelNotFoundException

### PR DESCRIPTION
**Pull request by spawnia**
I am using this class in my unit tests to build up an exception I expect
to be thrown in the code under test. My model is using string keys, so
both my IDE and static analysis tooling complain about passing its ID.

Additional work on this could be done by:
- introducing generic types for both the model and its ID
- using strong type hints
I kept it light and simple for now and only changed the type hints.

### CODE REVIEW

**Comment by nunomaduro** [comment]
@spawnia Can you add tests for this? On the folder `types`.

**Comment by spawnia** [comment]
I thought about it, but did not since there are no generics or other advanced type shenanigans involved. If you still think it is necessary, I can add some.

**Comment by nunomaduro** [comment]
Yes, thanks.

**Comment by nunomaduro** [comment]
Replaced by https://github.com/laravel/framework/pull/41082. I've added you as co-author.

**Comment by zachfraizer** [comment]
On Thursday, February 17, 2022, 05:44:44 AM CST, Nuno Maduro ***@***.***> wrote:
 
 
 


@spawnia Can you add tests for this? On the folder types.

**Pull request closed without merging**
