### PR TITLE
[5.5] Properly handle boolean casting for “true” and “false” strings

### PR DESCRIPTION
**Pull request by jkmassel**
Resubmitting to master due to potentially breaking changes from: https://github.com/laravel/framework/pull/20142 per @m1guelpf

### CODE REVIEW

**Comment by taylorotwell** [comment]
This also doesn't seem totally correct. filter_var will return `null` for random strings like "foobar" in this case.

**Comment by BrandonSurowiec** [comment]
@jkmassel  Why not just do something simple like:

```
return $value === 'false' ? false : (bool) $value;
```

**Comment by jkmassel** [comment]
If we're going for one-liners, the change in 79781de change I think is _slightly_ more readable. I'm happy to take direction and update the PR tonight if necessary.

Also - definitely not a problem to be solved in this Pull Request, but it seems like if you want to be super strict, `null` is the right value for trying to cast something to a type into which it it doesn't fit. Silently turning it into `false` seems like it could have unexpected results. Obviously no way this can be changed now without massive problems, but perhaps something worth some consideration. Either way, I learned something new to watch out for with casts!

**Comment by laurencei** [comment]
👎 from me.

I feel this is the wrong solution to the wrong question. The real question is why are you storing "false" in your database to represent `false`. They are fundamentally different and should not be interchanged.

If you have this type of issue, then the real solution is to migrate your database and do a change in the column to `bool` and have the database handle this.

Further - if you went ahead with this change, you actually cause a logic problem - because when you validate a `boolean` rule Laravel explicitly and intentionally does not accept "false" as `false` in that validation - they are **not** the same thing and will lead to strange application problems.

**Comment by taylorotwell** [comment]
Will hold off on this for now.

**Pull request closed without merging**
