### PR TITLE
[9.x] Modify `mergeCasts` to return `$this`

### PR DESCRIPTION
**Pull request by finagin**
This change helpful to use the method in pipeline like this:
```php
    public function initializeUsesUuid()
    {
        $this
            ->setKeyName('uuid')
            ->setKeyType('string')
            ->setIncrementing(false)
            ->mergeCasts([$this->getKeyName() => $this->getKeyType()])
            ->mergeGuarded([$this->getKeyName()]);
    }
```

### CODE REVIEW

**Comment by dinhquochan** [comment]
@taylorotwell Can merge this into 8.x? Because It's not breaking changes (not much).

```php
// before
public function initializeUsesUuid()
{
        $this->setKeyType('string')
            ->setIncrementing(false);
        $this->mergeCasts([$this->getKeyName() => $this->getKeyType()]);
}

// after
public function initializeUsesUuid()
{
        $this->setKeyType('string')
            ->setIncrementing(false)
            ->mergeCasts([$this->getKeyName() => $this->getKeyType()]);
}
```

**Comment by driesvints** [comment]
@dinhquochan feel free to pr

**Comment by finagin** [comment]
@driesvints, hey, I create this PR to 8.x (#35676), but it's rejected

**Comment by driesvints** [comment]
@finagin that PR shouldn't have been closed. Feel free to resubmit it.

**Comment by finagin** [comment]
@driesvints I can't reopen #35676 but open new PR #35683

**Pull request merged**
