### PR TITLE
[5.5] Use Null Coalesce Operator

### PR DESCRIPTION
**Pull request by carusogabriel**

### CODE REVIEW

**Comment by sisve** [comment]
I see no reason to rewrite existing code that already works just to use a new PHP7.0 feature. Can you describe what bugs this actually fixes?

**Comment by carusogabriel** [comment]
It doesn't fix any bugs, it's just for a shorter solution :disappointed:

**Comment by Kyslik** [comment]
I wonder if `??` is any "faster" than `isset() ? :` or its really just a sugar.

**Comment by carusogabriel** [comment]
@Kyslik [Here is it's RFC](https://wiki.php.net/rfc/isset_ternary). Apparently, no.

**Comment by mputkowski** [comment]
You should change this in whole code (if you really want to change it), not in single case like in this PR.

**Comment by deleugpn** [comment]
@mputkowski larger PRs = harder to review.

**Comment by Dylan-DPC** [comment]
Having a single or lesser number of PRs with all changes makes it easier to maintain consistency. Say suppose you want to revert this change in future, you will have to revert each PR or go around making the changes manually.  Makes it easier to reference in the future as well.

**Comment by carusogabriel** [comment]
@mputkowski I've searched the whole code, and this was the last occurrence of ternary comparisons that could be changed.

**Pull request merged**
