### PR TITLE
[5.1] Make DatabaseEloquentMorphTest not dependent on another test

### LINKED ISSUE #10860: Test isolation for Eloquent morph
When I run: `phpunit --filter DatabaseEloquentMo`, tests pass.

But when I run: `phpunit --filter DatabaseEloquentMorph` (same tests as above, except for `DatabaseEloquentModelTest`), I get this:

    There was 1 error:

    1) DatabaseEloquentMorphTest::testCreateFunctionOnNamespacedMorph
    Argument 2 passed to Illuminate\Database\Eloquent\Relations\MorphOneOrMany::__construct()
    must be an instance of Illuminate\Database\Eloquent\Model, instance of
    Mockery_2__Foo_Bar_EloquentModelNamespacedStub given, called in
    C:\laravel\tests\Database\DatabaseEloquentMorphTest.php on line 229 and defined

    C:\laravel\src\Illuminate\Database\Eloquent\Relations\MorphOneOrMany.php:34
    C:\laravel\tests\Database\DatabaseEloquentMorphTest.php:229
    C:\laravel\tests\Database\DatabaseEloquentMorphTest.php:173

    FAILURES!
    Tests: 23, Assertions: 15, Errors: 1.

So I guess `DatabaseEloquentMorphTest` is relying on some set up made in `DatabaseEloquentModelTest`, which isn't ideal. I couldn't figure it out yet. Anyone?

### PR DESCRIPTION
**Pull request by vlakoff**
Fixes #10860.

Kudos @jairovsky for pointing out the cause.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please rebase.

**Comment by vlakoff** [comment]
Rebased.

**Comment by taylorotwell** [comment]
The tests fail?

**Comment by taylorotwell** [comment]
Looks like some kind of Travis problem with php 7.

**Pull request merged**
