### PR TITLE
[5.7] Add $model->loadCount()

### PR DESCRIPTION
**Pull request by hulkur**
Companion to `load` like `with`/`withCount`

[Ideas#869](https://github.com/laravel/ideas/issues/869)

### CODE REVIEW

**Comment by taylorotwell** [comment]
Is this actually giving a performance benefit vs $model->relation()->count()?

**Comment by hulkur** [comment]
Can't give any numbers on performance. My use-case is loading multiple relations, so it depends on how it is built deeper.

```
$model->loadCount(['some', 'other']);
```
vs
```
$model->some()->count();
$model->other()->count();
```

**Comment by staudenmeir** [comment]
For me, the main advantage is that the value is stored and can be accessed multiple times.

So it's the short version of this:

```php
$posts->comments_count = $post->comments()->count();
```

**Comment by taylorotwell** [comment]
I would prefer something like this go on master branch. Reason being is because model's contain a lot of user defined methods, and if they have defined a method called "loadCount"... this would be a breaking change for them.

**Pull request closed without merging**
