### PR TITLE
[5.9] Corrected test for support optional

### PR DESCRIPTION
**Pull request by MammutAlex**
Added assertions for isset value

- If target is **array** and isset like for **object**
- If target is **null** get isset

### CODE REVIEW

**Comment by MammutAlex** [comment]
So
Again failed test for Redis
I did not touch the functional or the test of those who failed
Here was also a fail https://travis-ci.org/laravel/framework/builds/510270439

**Comment by xuanquynh** [comment]
I think these tests can be sent to "5.8" branch.

**Comment by MammutAlex** [comment]
> I think these tests can be sent to "5.8" branch.

You're right

**Comment by MammutAlex** [comment]
@xuanquynh Do you understand what the problem with tests is?https://github.com/laravel/framework/pull/28001#issuecomment-476079765

**Pull request closed without merging**
