### PR TITLE
[11.x] Fix issue with missing 'js/' directory in broadcasting installation command

### PR DESCRIPTION
**Pull request by alnahian2003**
### Issue

After installing a fresh Laravel app with the Breeze 'api' stack, the `install:broadcasting` command to enable broadcasting throws an error:

```bash
> php artisan install:broadcast 

  INFO Published 'broadcasting' configuration file.  

  INFO Published 'channels' route file.  


  ErrorException 

 copy(laravel-app\resources\js/echo.js): Failed to open stream: No such file or directory

 at vendor\laravel\framework\src\Illuminate\Foundation\Console\BroadcastingInstallCommand.php:56
   52▕     $this->enableBroadcastServiceProvider();
   53▕
   54▕     // Install bootstrapping...
   55▕     if (! file_exists($echoScriptPath = $this->laravel->resourcePath('js/echo.js'))) {
 ➜ 56▕       copy(__DIR__.'/stubs/echo-js.stub', $echoScriptPath);
   57▕     }
   58▕
   59▕     if (file_exists($bootstrapScriptPath = $this->laravel->resourcePath('js/bootstrap.js'))) {
   60▕       $bootstrapScript = file_get_contents(

 1  vendor\laravel\framework\src\Illuminate\Foundation\Console\BroadcastingInstallCommand.php:56

 2  vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
   Illuminate\Foundation\Console\BroadcastingInstallCommand::handle()
```

### Solution

The error is occurring because the 'js/' directory in the resource path doesn't exist yet. This can be fixed by creating the directory before copying `echo.js` inside it. This PR addresses the issue.

### CODE REVIEW

**Comment by driesvints** [comment]
Not sure what you did to make the tests fail but can't seem to get them passing anymore on this PR. Try recreating the PR anew with passing tests.

**Comment by driesvints** [comment]
Sorry, seems this is more widespread. I don't have any clue why this is happening for pull requests but not for our base 11.x branch.

**Comment by alnahian2003** [comment]
Uh oh! I deleted my old fork and created a new one for a new PR. Should I wait though?

**Comment by driesvints** [comment]
Reverted something. Can you try again?

**Comment by alnahian2003** [comment]
Sure! Let me give it a try

**Comment by alnahian2003** [comment]
Hey, resubmitted this PR #50657 

Hope the checks pass this time 🤞

**Pull request closed without merging**
