### PR TITLE
[10.x] add user() helper function to reduce the need to write guard()->user()

### PR DESCRIPTION
**Pull request by MouhcineMAHFOUD**
During development, I find my self and my team writing every time auth()->user() to access the currently authenticated user, we use this so much that for almost all projects we add this function as a helper function, so I suggest to add it to the framework, in the hope that it will be very helpful for other people as well.

### CODE REVIEW

**Comment by ankurk91** [comment]
No more global function please.

Your function does not support multiple guards

**Comment by MouhcineMAHFOUD** [comment]
Hello @ankurk91 
You're right,  in most cases I would avoid adding more global functions, however, in this case it's being used a lot, that's why I think it will be useful to the framework.

I have added support for multiple guards.

**Comment by antonkomarev** [comment]
Can't you get it from the request?

`$request->user()`

**Comment by donnysim** [comment]
I, and I can see many others, already create this helper to type it to specific class instead of interface and to shorten the writing, so this most definitely will be a breaking change for some and would kind of still remove the benefit of typing the return type.

**Comment by milwad-dev** [comment]
You can use this helper in you own application!

**Pull request closed without merging**
