### PR TITLE
[5.7] Enable OPcache optimization for \is_array function.

### PR DESCRIPTION
**Pull request by TBlindaruk**
- FQN for some function is faster, more information you can see in https://github.com/Roave/FunctionFQNReplacer

In case if this PR will be merged then I can add FQN for other functions.

### CODE REVIEW

**Comment by sisve** [comment]
Are you _sure_ this isn't a breaking change? What if someone has a namespaced is_array function, wouldn't this stop calling that function?

**Comment by TBlindaruk** [comment]
hmm, I will change the target to 5.8

**Comment by GrahamCampbell** [comment]
I think 5.7 is the best place for this. It can be assumed that people aren't overloading this function. That'd be very odd, and not something I think laravel needs to care about not breaking.

**Comment by TBlindaruk** [comment]
@GrahamCampbell , I have changed again target

**Comment by taylorotwell** [comment]
Please re-submit with before / after benchmark comparisons with a real application.

**Comment by deleugpn** [comment]
I have tried to benchmark this before in the collection class (using FQN in all function calls on Collection and Arr) and couldn't get any benefit out of it.

**Comment by TBlindaruk** [comment]
@deleugpn ,
I have tried to do like:

```PHP
<?php
declare(strict_types = 1);

use Illuminate\Support\Arr;

require_once __DIR__ . '/vendor/autoload.php';

$start = microtime(true);

for ($i = 0; $i < 1000000; ++$i) {
    Arr::accessible(rand(0, 100));
    Arr::add([], 'asd', rand(0, 100));
}
var_dump(microtime(true) - $start);

$start = microtime(true);
for ($i = 0; $i < 1000000; ++$i) {
    Arr::accessibleFQN(rand(0, 100));
    Arr::addFQN([], 'asda', rand(0, 100));
}
var_dump(microtime(true) - $start);
```

and I got result like:
```
---------------------
float(0.77622103691101)
float(0.76661992073059)
---------------------
float(0.78784203529358)
float(0.77640986442566)
---------------------
float(0.81309294700623)
float(0.74442887306213)
---------------------
float(0.77926397323608)
float(0.74646091461182)
---------------------
float(0.75503921508789)
float(0.73970913887024)
---------------------
float(0.83547401428223)
float(0.74301886558533)
---------------------
float(0.91685009002686)
float(0.73422002792358)
---------------------
float(0.74081707000732)
float(0.7497980594635)
---------------------
float(0.76737809181213)
float(0.76085305213928)
---------------------
float(0.72502994537354)
float(0.74334406852722)
---------------------
float(0.7718071937561)
float(0.7372260093689)
---------------------
float(0.7352180480957)
float(0.74284410476685)
---------------------
float(0.79143404960632)
float(0.71761989593506)
---------------------
float(0.7347137928009)
float(0.76255178451538)
---------------------
float(0.79634022712708)
float(0.77007293701172)
---------------------
float(0.83311700820923)
float(0.75413298606873)

```
PHP Version: PHP 7.1.16-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:47:00) ( NTS )

**Pull request closed without merging**
