### PR TITLE
[5.1] Cast the resolved current page to an integer

### PR DESCRIPTION
**Pull request by AdenFraser**
I believe this is an adequate fix for #11241, can implement test to confirm.

Afaik there is no reason not to cast the value here? 

If so, will add tests... but not confident this is deemed an acceptable fix (even though it works :wink:)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
As in the comment I posted, this fix is not sufficient.

**Comment by GrahamCampbell** [comment]
The behaviour of casting to an int is not consistent on different php versions.

**Comment by AdenFraser** [comment]
It's consistently 0 or below though, so should be treated as invalid by `isValidPageNumber()`?

**Comment by GrahamCampbell** [comment]
But, in casting to an int, you're letting through invalid page numbers, like `foo`.

**Comment by AdenFraser** [comment]
Do we not do that already? 

https://laracasts.com/discuss?page=foo would currently resolve the current page as 0, but casted as an int it would still resolve as 0.

https://laracasts.com/discuss?page=4foo would currently resolve the page as 4, but casted it would still remain as 4.

As a side note, if you see the appended 4foo parameter above, the paginated page is page 4... however the pagination links remain at page 1. Not that I'd expect them to work if we are providing a string, but it seems inconsistent that the query builder resolves a different current page to the paginator.

**Comment by taylorotwell** [comment]
Fixed.

**Pull request closed without merging**
