### PR TITLE
[10.x] ReadLine

### PR DESCRIPTION
**Pull request by Noorani-MM**
### Request type :question:

- [ ] :bug: Bug ( fixed or found bug )
- [x] :new: New feature ( make new feather or add some things new in project )
- [ ] :star2: Config ( change config files or install )
- [ ] :rocket: Performance ( when you do something that can improve performance )
- [ ] :books: Document ( when code has documentation or document change )

### Description :books:

Get every line of text and set as array, Then you can change or improve text line by line.

### How to use ⚒️ 

```php

$lines = \Illuminate\Support\Str::readLines($text);

```

Then you can 

```php
foreach ($lines as $line) { 
   // code
}
```

### CODE REVIEW

**Comment by henzeb** [comment]
I'd rename the method to split or explode and allow the developer to choose it's own character for splitting. Also, allow nullable string, because otherwise the 'empty' check is not needed.

**Comment by Noorani-MM** [comment]
> I'd rename the method to split or explode and allow the developer to choose it's own character for splitting. Also, allow nullable string, because otherwise the 'empty' check is not needed.

What is your suggest for method name?

**Review by milwad-dev — COMMENTED** [review]
I don't think need to loop or convert string into an array, also you can add this to your own package!

**Comment by henzeb** [comment]
> > I'd rename the method to split or explode and allow the developer to choose it's own character for splitting. Also, allow nullable string, because otherwise the 'empty' check is not needed.
> 
> What is your suggest for method name? readLines Inspired by C# chosen to be specific for reading lines

This has no chance of making it. Especially because you don't do anything special and do not use PHP_EOL. But a method dat splits/explodes anything and deals with null might.

**Comment by Noorani-MM** [comment]
> I don't think need to loop or convert string into an array, also you can add this to your own package!

I already working on a project that I need to add \t in lines. We will certainly have many projects of this style in the future. I think this is better to we have kind of this method instead of writing that for every project

**Comment by Noorani-MM** [comment]
> This has no chance of making it. Especially because you don't do anything special and do not use PHP_EOL. But a method dat splits/explodes anything and deals with null might.

Maybe 🤔. So I have to change it to something like this

```php

public static function explode(string $separator, string $text) : array
{
    return explode($separator, $text);
}

public static function readLine(string $text, $separator = "\n") : array
{
     return empty($text) ? [ ] : self::explode($separator, $text);
}

```
Now you can separate the lines from the text both logically and arbitrarily

**Comment by milwad-dev** [comment]
> > I don't think need to loop or convert string into an array, also you can add this to your own package!
> 
> I already working on a project that I need to add \t in lines. We will certainly have many projects of this style in the future. I think this is better to we have kind of this method instead of writing that for every project

But is not need to add it into a framework.
Framework is sensitive and not every method can be added, but the methods that are used a lot should be added.

Of course now Laravel have a lot of method that no need it.

**Comment by Noorani-MM** [comment]
> > > I don't think need to loop or convert string into an array, also you can add this to your own package!
> > 
> > 
> > I already working on a project that I need to add \t in lines. We will certainly have many projects of this style in the future. I think this is better to we have kind of this method instead of writing that for every project
> 
> But is not need to add it into a framework. Framework is sensitive and not every method can be added, but the methods that are used a lot should be added.
> 
> Of course now Laravel have a lot of method that no need it.

Yes I agree with that, But as I said `readLine` inspired by C# .net Framework . So why we don't add a good method that used by another Framework ?

**Comment by williamtrevisan** [comment]
So, if I'm not wrong, a method like this already exists. Here it is: https://laravel.com/docs/10.x/helpers#method-fluent-str-split. Maybe we can improve this one to have the same experience that have in your "readLines", because I think that the `split` method doesn't split string when we pass "\" as a parameter. Also, the `split` returns a collection, what, in laravel context, IMO, is better than returns an array, and we can improve to call him with Str facade directly as well. What do you thing about it?

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
