### PR TITLE
[5.5] Add 'pasta' and 'veggies' to $uncountable

### PR DESCRIPTION
**Pull request by hipsterjazzbo**
No points for guess what kind of app I'm making 😛

### CODE REVIEW

**Comment by BrandonShar** [comment]
`pastas` is a valid pluralization. If these are models, you can overwrite the table name on the model class or just add them to the pluralizer array in a service provider.

**Comment by lagbox** [comment]
"We have X pasta(s) on the menu."
`{$itemCount} {str_plural($name, $itemCount)}`

Current behavior:

"We have 0 pastas on the menu."
"We have 1 pasta on the menu."
"We have 4 pastas on the menu."

>"pasta (countable and uncountable, plural pastas)" - [Wiktionary - pasta - noun](https://en.wiktionary.org/wiki/pasta#Noun)

>“There's a choice of three pastas, spaghetti, gnocchi, and fettuccini ..." - [Wiktionary - Citations - pasta](https://en.wiktionary.org/wiki/Citations:pasta#Noun:_a_type_of_pasta)

**Comment by BrandonSurowiec** [comment]
`veggies` is also the plural of `veggie` ;)

**Comment by patlecat** [comment]
Why is "fish" not in the list?

**Comment by jmarcher** [comment]
@patlecat It is in the list indeed

**Comment by patlecat** [comment]
@jmarcher Ah yes it was folded, so I didn't see it. Thanks.

**Pull request closed without merging**
