### PR TITLE
[10.x] Accept `minecraft` protocol in URL validation

### PR DESCRIPTION
**Pull request by MrMicky-FR**
This adds support for the `minecraft` protocol in `Str::isUrl` and the `url` validation rule. This protocol is a valid URL protocol used by the Minecraft game to join a Minecraft server (same idea as the `steam` protocol, which is already in the list).

I had submitted a PR to be able to specify new protocols without having to modify this insane protocols list (#47381) but unfortunately it was closed and my [latest comment](https://github.com/laravel/framework/pull/47381) is still unanswered after one month 😕

### CODE REVIEW

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
👎 We should not diverge from the Symfony list. If we need something adding, it should be added to Symfony first.

**Comment by MrMicky-FR** [comment]
> 👎 We should not diverge from the Symfony list. If we need something adding, it should be added to Symfony first.

@GrahamCampbell From what I can tell, Symfony doesn't include this list: https://github.com/symfony/symfony/blob/68f27ef75cf90dc177f87806af3ce3c407f23e3f/src/Symfony/Component/Validator/Constraints/UrlValidator.php#L25

And the default protocols only contains `http` and `https`:
https://github.com/symfony/symfony/blob/68f27ef75cf90dc177f87806af3ce3c407f23e3f/src/Symfony/Component/Validator/Constraints/Url.php#L38

**Comment by MrMicky-FR** [comment]
> As it may very well be that I need it to be https, but some idiot passed Minecraft url and now my app breaks if I do not add a regex to validate it starts with http...

As Taylor Otwell suggested, you can use `url|starts_with:http,https`, but I also think the best solution would be to completly remove this list.

> Then we need a way to add protocols the application accepts, instead of adding protocols to laravel as we go.

I agree with you, especially as many protocols in this list doesn't make sense. I would be happy to do a new PR for a different approach to solve this, I'm just not sure how to do it, as my last attempt (#47381) was closed.

**Comment by henriquecm** [comment]
I think the best approach would be having a short list with the most commonly used protocols ex: http,https, ftp, ssh, mailto, tel, blob, etc.

And a configuration for other accepted protocol at application level, similar to how you can configure default string size for migrations `Schema::defaultStringLength()`.
```php
$default = Str::$defaultAcceptedProtocols;
Str::defaultAcceptedProtocols([...$default, 'minecraft']);
```

And a optional argument on `Str::isUrl` that is merged with the default list.

**Comment by henzeb** [comment]
> I think the best approach would be having a short list with the most commonly used protocols ex: http,https, ftp, ssh, mailto, tel, blob, etc.
> 
> And a configuration for other accepted protocol at application level, similar to how you can configure default string size for migrations `Schema::defaultStringLength()`.
> 
> ```
Still no. I think we need something that allows you to specify the protocols your application accepts for that specific field. I can't think of a common use case where an url can be any of those, as your application, frontend or backend, needs to be able to handle them. Most of the time you want to register the website of a user. The user wants a Minecraft url, he is probably not planning to allow mailto or tel there. Simply http/https would be a default situation. anything else is for specific use cases.

**Comment by MrMicky-FR** [comment]
> @MrMicky-FR let's actually just revisit your original PR: #47381
> 
> Can you reopen it?

Seems like I can’t reopen a PR that I haven’t closed myself

**Pull request closed without merging**
