### PR TITLE
[4.2] Fix file locking issue with Laravel file sessions

### PR DESCRIPTION
**Pull request by avi123**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Is anyone able to test this please and confirm that this does work? If we can't get this 100% clear, then this will have to be retargeted to 5.0. Once the psr-2 changes go into laravel 5.0, laravel 4.2 will become locked for all improvements or edge cases fixes like this.

**Comment by GrahamCampbell** [comment]
Also note, for anyone coming to this and reading my last comment here, Laravel 5 never moved to PSR-2, and there are no plans to in the near future.

**Comment by wiseloren** [comment]
I'm assuming this never got worked into anything.  I've just run into this issue and am in need of getting it fixed.  I've put together a sample repository here: https://github.com/wiseloren/laravel-race  That shows the problem.  I've only tested with the file driver since I didn't have a database handy for the test project.  I'm willing to work on the code, though, I'm guessing I'll need to find and fix the correct files in 5.0 instead of 4.2.

**Comment by wiseloren** [comment]
I can confirm that this fix fixes the issues in the laravel race repository causing everything to properly be incremented.

**Comment by cedricve** [comment]
Nice, fixes my issue!

**Comment by cedricve** [comment]
@loren138 I know this has been a while, but I've create a ServiceProvider:

https://github.com/cedricve/lockfile

**Pull request closed without merging**
