### PR TITLE
[5.6] Required If Rule based on a clousure or boolean value

### PR DESCRIPTION
**Pull request by alfonsobries**
This PR will allow me to create a `required` rule-based in a user closure or a boolean value, the same behavior could be achieved with a custom closure but I think this provides a cleaner way to add some custom condition to require a value

Examples:

```
$this->validate($request->all(), [
   'role_id' => Rule::requiredIf(function () use ($request) {
   		return $request->user()->is_admin
   		   && $some_other_complicated_condition; 
    })
})
```

```
$this->validate($request->all(), [
   'role_id' => Rule::requiredIf($request->user()->is_admin)
})
```

### CODE REVIEW

**Comment by alfonsobries** [comment]
The main idea is to avoid this type of conditions:
`'role_id' => (auth()->user()->is_admin ? 'required' : '') . '|integer'`

Better: 
`'role_id' => [Rule::requiredIf(auth()->user()->is_admin), 'integer']`

**Comment by alfonsobries** [comment]
Wondering if the __toString method should return ‘required_if:true’ or ’required_if:false’ to be more consistent ?

**Comment by garygreen** [comment]
Surprised this got merged. It's just syntax sugar and yet another thing to maintain. Related to #25103

```php
'role_id' => (auth()->user()->is_admin ? 'required' : '') . '|integer'
```

Better:

```php
'role_id' => [Rule::requiredIf(auth()->user()->is_admin), 'integer']
```

Why is it better? Meh.

**Comment by garygreen** [comment]
Also this opens up a whole new door of PRs. Can we also add:

```php
requiredWithout
requiredIfNot
...
```

This only makes sense to me if we converted all the existing rules into first class citizens, without the need to serialize the rules to a string again. But the way Laravel works at the moment is it essentially just creates a rule-based string, so there's no real benefit from just creating that string yourself. In fact it just slows down your validation.

**Pull request merged**
