### PR TITLE
[5.0] Make use of new resolvingType method

### PR DESCRIPTION
**Pull request by hannesvdvreken**
Follow-up PR of #6724

Includes
- More method documentation for new methods
- Methods now also added to the `Container` contract
- Made use of the new `$container->resolvingType` method to clean up `ValidationServiceProvider` and `FormRequestServiceProvider`.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Rebase?

**Comment by hannesvdvreken** [comment]
@taylorotwell rebased

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by hannesvdvreken** [comment]
Ping

**Comment by taylorotwell** [comment]
Is this needed after merging that other PR?

**Comment by hannesvdvreken** [comment]
Nope

**Pull request closed without merging**
