### PR TITLE
[5.1] Change default schema of UrlGenerator@[asset,assetFrom]

### PR DESCRIPTION
**Pull request by xujif**
change default schema of UrlGenerator
so that assets can auto load from https or http even behind reserve proxies (which u can not change settings).

### CODE REVIEW

**Comment by xujif** [comment]
@taylorotwell

**Comment by GrahamCampbell** [comment]
Please don't ping after 2 hours...

**Comment by GrahamCampbell** [comment]
Taylor does have to sleep. ;)

**Comment by GrahamCampbell** [comment]
Also, this is a breaking change IMO :-1: from me.

**Pull request closed without merging**
