### PR TITLE
[5.2] Fix for wrong return value from getOriginal

### PR DESCRIPTION
**Pull request by egeriis**
This is the fix for the issue mentioned in #12945.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Isn't this something that should be fixed in Arr::get? @GrahamCampbell

**Comment by taylorotwell** [comment]
Also this change wouldn't really make since if you passed a key... if the key isn't there you want an empty array back? That doesn't make sense to me.

**Comment by egeriis** [comment]
Considering that the documentation states that the return value should always be null, I assumed that was the expected behavior: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L3085

If `getOriginal` is not supposed to always return an array, it lack documentation.

**Comment by taylorotwell** [comment]
I think the doc-block is just wrong. The $key param was probably added later and the doc block never updated.

**Comment by mark86092** [comment]
The [Arr.php#L255](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Support/Arr.php#L255) is doing the same thing as Taylor said

**Comment by vlakoff** [comment]
I know. It would be simply to not rely on the `Arr::get` handling of null keys.

**Comment by mark86092** [comment]
@vlakoff I'm sorry, but the code is not for you. A reference for egeriis

**Comment by vlakoff** [comment]
Ah, got it. `Arr::get` and `Arr::has` aren't documented (nor tested) for null keys, while these null keys are "supported", and actually used, just like here for instance...

**Comment by vlakoff** [comment]
I think we should:
* add my "proactive measure" above
* add tests for null keys
* leave phpdocs as they are

**Comment by vlakoff** [comment]
edit: just update `@return` for getOriginal

**Comment by vlakoff** [comment]
Submited #12958 about the various point I raised above.

You may still want to suggest adding tests for `getOriginal`.

**Comment by taylorotwell** [comment]
Closing this because of @vlakoff's PR to address issue.

**Comment by egeriis** [comment]
Great job @vlakoff

**Pull request closed without merging**
