### PR TITLE
[10.x] Fix the issue of `$wrap` collection resource attribute 💼

### PR DESCRIPTION
**Pull request by mahmoudmohamedramadan**
## In The Old Pull Request Version

I intended to use the **Data Wrapping** feature but, there was a glitch in the response where the wrapper was not affected by whatever changes in the `$wrap` attribute when I used the `collection` method, so, I debugged the code and found out that Laravel not accessing this attribute inside that method therefore, I did it and the response was correct back! 🎉

## In The New Pull Request Version

Mr. **Taylor Otwell** told me to update the code to access that attribute anonymously to fade away any issue in the future so, I worked on the code again and resolved the issue. Moreover, I found the new way is more efficient and works without restrictions! 🥳

> [!NOTE]
> In the old version, I was forced to put the testing method at the end of the file because when I changed the `$wrap` attribute value affected the successor testing methods and the wrapper value changed from `data` to `posts` and made them fail **(This the restriction that I mean in the new version)**.

### CODE REVIEW

**Comment by mahmoudmohamedramadan** [comment]
@driesvints I have fixed the issue of the Test in #50256 please, take a look over this pull request!

**Comment by taylorotwell** [comment]
I'm pretty worried about this static state interfering with later or nested resource serialization. Ideally this would be instance state on the anonymous resource collection. Is that possible?

**Comment by mahmoudmohamedramadan** [comment]
@taylorotwell I have accomplished the task where I make a condition in case the coming resource is an instance of `AnonymousResourceCollection`, update the wrapped value from the `collects` attribute 🚀

**Comment by taylorotwell** [comment]
Undocumented this entire feature. Not sure it's worthwhile to even have around.

**Comment by mahmoudmohamedramadan** [comment]
@taylorotwell Yup, it's not documented but is just a scenario I have faced and I found that is a real issue that may be faced by another Laravel developer so, I made this PR.

**Pull request closed without merging**
