### PR TITLE
Route Middleware Auto-Register

### PR DESCRIPTION
**Pull request by tzsk**
Auto-Register Route Middlewares with a name property in the middleware class itself.

Have to add a register method in the `App\Http\Kernel` class. Like so: 

```php
    /**
	 * Automatically register middlewares.
	 *
	 * @return void
	 */
	public function register() {
		$this->load(__DIR__.'/Middleware');
    }
```

**Note:**  It will not re-register existing middlewares inside `$middlewares` and `$middlewareGroups`. It will only add the middleware if the middleware is not present in the Existing List. You can create a middleware and add it in the Kernel and this PR won't add that middleware again.

### Usage:

Create middleware like you normally would: `php artisan make:middleware Subscribed`. In the created Middlewear file you will find a name property.
Choose whatever name you like ex. `subscribed`. Then use the middleware in routes like following:

```php
Route::middleware('subscribed')->get(...);
```

### CODE REVIEW

**Comment by a-komarev** [comment]
Is there is a way to ignore autoloading somehow?

**Comment by tzsk** [comment]
> Is there is a way to ignore autoloading somehow?

@a-komarev - Yes. By default it won't register any Middlewares and act like normal Laravel 5.5 Middleware until the `load()` method is called inside `App\Http\Kernel` class. We can remove the `register()` method in there completely to revert the behavior to normal Laravel 5.5 Middleware.

**Comment by taylorotwell** [comment]
Too slow for every web requests. Console is fine because speed is not as high of a priority.

**Comment by tzsk** [comment]
@taylorotwell - If it turns out to be major hit in performance for someone then it can easily be disabled by simply removing the `register()` method inside `App\Http\Kernel` or just comment out `$this->load(__DIR__.'/Middleware');`. By doing that its as good as Fresh Laravel. 

OR, it can be shipped with already commented `$this->load(__DIR__.'/Middleware');` whoever requires auto-register they can simply un-comment the line and they are good to go.

By commenting out that `load()` method it will have zero impact on existing flow.

**Pull request closed without merging**
