### PR TITLE
issue #17439: Fixed a flaw in str::is() function.

### PR DESCRIPTION
**Pull request by alpha-hawk**
There is small flaw in the function. As we are dealing with strings there we should do a strict check (===) instead of (==).

### CODE REVIEW

**Comment by ellisio** [comment]
I don't think this a good implementation unless the method is changed to the following; but it wont happen until the minimum PHP version is bumped.

```php
public static function is(string $pattern, string $value)
```

The reason being is because if a developer calls `Str::is(1000, '1000')` it would return false.

**Comment by ellisio** [comment]
Without actually testing anything, I feel like this change would actually cause performance issues. Say a developer calls:

```php
if (Str::is(1000, '1000')) {
    echo "success";
} else {
    echo "error";
}
```

Your change would bypass the `===` check and fall into the slower `preg_match` comparison.

**Comment by alpha-hawk** [comment]
Yes. I am totally agree with you here as usage varies according to requirements.

But if the check is placed in an automated environment or in a general utility function to compare two different values, it can cause problems. 

When a int 0 is inserted it destroys the purpose of the function and returns always true.
 
But yes we can always implement a work around. Its better to fix the call instead of implementation.

**Comment by alpha-hawk** [comment]
What if we typecast the parameters before comparison?

**Comment by GrahamCampbell** [comment]
The function only takes string inputs, as specified in the phpdoc.

**Comment by alpha-hawk** [comment]
If the function deals only takes string inputs, shouldn't there be a strict check then.

**Comment by ellisio** [comment]
@GrahamCampbell -- He has a point there. If the docs state this function only accepts strings as arguments, and to support `>= 5.6.4`, shouldn't there be something like the following to start the function:

```php
if (! is_string($pattern) || ! is_string($value)) {
    throw new InvalidArgumentException('Only strings are allowed.');
}
```

**Comment by GrahamCampbell** [comment]
The function is officially undefined for anything that's not a string. We don't have to throw an exception if the argument is not a string. There are thousands of other function across the framework that are in a similar boat.

**Comment by GrahamCampbell** [comment]
> Then when, if ever, Laravel requires >= 7.0.0, it would be changed to:

Don't think that will ever happen actually.

**Comment by ellisio** [comment]
You're saying 5.5, .... even 6 (someday, right?) won't drop support for `< 7`? What happens with PHP 5.x reaches EOL? ;)

**Comment by ellisio** [comment]
http://php.net/supported-versions.php

Seeing as how PHP 5.6 will be officially unsupported as of 2019. :)

**Comment by GrahamCampbell** [comment]
Laravel 5.5 is dropping support for PHP 5.6, but it's not using scalar type hints.

**Comment by ellisio** [comment]
Ah, why not? If you're supporting the minimum needed version why would you want to skip out on the power of that? A good example is this function with saying it requires strings.

Personally, I think it would help developers become better developers and to encourage them to stop using methods in the wrong fashion.

**Comment by GrahamCampbell** [comment]
Well, if we already wanted to enforce typing, we could have just thrown invalid argument exceptions in our methods. The fact that php 7 has type hints isn't any different really. PHP does no compile time type checking (the only type checking it actually does is with the void return type, it ensures return nodes in the AST have no body), so the execution strategy is essentially the same as having an is_string check in the code.

**Comment by ellisio** [comment]
I agree, but having InvalidArgumentExceptions all over the code makes the method body a mess (more complexity do to more lines of code in the method).

Use scalar type hints removes that complexity, but enforces better implementation practices.

Using this method as a good example, `Str::is(1000, '1000')` should be discouraged because you are comparing an `int` to a `string`; but the helper is for `string`-types. By using the scalar type hints available, and since the framework will require PHP 7+, you would be encouraging Jr Developers to write better code.

**Comment by NeoXtreme** [comment]
If are going to avoid safety checks just because something is said in documents,  we can drop the whole notion of basic validation. Can't believe Laravel is so dependent on phpdoc for argument validation.

**Comment by alpha-hawk** [comment]
I understand that, but if due to some unfortunate incident on part of the programmer once a zero has been placed inside the array, all permissions will just collapse. 
As we are dealing with the site permissions here, I think we should handle these kind of issues. It is very easy to place a zero inside the array but it should not affect the whole permissions. 
If you don't find that important please feel free to close the issue.

**Pull request closed without merging**
