### PR TITLE
[5.2] Throw an exception when can't json encode in eloquent

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Replaces #11139.

### CODE REVIEW

**Comment by lucasmichot** [comment]
@GrahamCampbell I like a lot the idea of this, but I think that:
* we could have a `JsonEncodingException`
* this should apply to all classes that implement `\Illuminate\Contracts\Support\Jsonable`

**Comment by GrahamCampbell** [comment]
:-1: for adding an extra exception. We already throw a few generic exceptions in eloquent.

**Comment by GrahamCampbell** [comment]
> this should apply to all classes that implement \Illuminate\Contracts\Support\Jsonable

I suggested this to Taylor before and he didn't seem to like the idea.

**Comment by lucasmichot** [comment]
> I suggested this to Taylor before and he didn't seem to like the idea.

OK, but in this case, if this applies to `\Illuminate\Database\Eloquent\Model`, this should at minima also apply to `\Illuminate\Database\Eloquent\Collection` too, no ?

**Comment by taylorotwell** [comment]
I don't even think this is necessary at all. If this is going to make you wrap it in a try / catch, what's the difference from the current situation where you can just do if (! $user = $user->toJson()) { json_last_error() }

**Comment by GrahamCampbell** [comment]
Sure. :)

**Pull request closed without merging**
