### PR TITLE
[8.x] Allow jobs to define which queue they run on when inside a batch

### PR DESCRIPTION
**Pull request by Krunch**
As mentioned in #34296 we cannot execute jobs on a different queue than the one the batch is running. This small improvement I am proposing will allow developers to pick which queues they want their batched jobs to run on while also limiting the number of calls to the queue system to a minimum. In the best case scenario, the number of queue system calls will be the same (if jobs just go to the same queue as the batch). When, multiple different queues are specific in a single batch then the number of queue system calls is equal to the number of distinct queues present in all jobs.

This will allow more use cases to be supported by the new batch job system that was added in Laravel 8. This new batch job system is very useful in the case where you need to trigger a specific action when all jobs are executed. In some cases like mine (described in #34296) not all jobs are known in advance and are dictated by a job within an existing batch dynamically adding new jobs to the same batch. Those new jobs may need to go on a different queue because they are different unit of work (pull/push system), but still need to be tracked within the same batch. In our case, a batch is considered to be the pull job + all push jobs created, and tracking them within the batch makes it very convenient to trigger a completion action once all pull+push jobs are done.

This does not break anything and simply allows jobs to control the queue they need to run on. The default behavior is still the same (run on the same queue as the batch if a job does not specify a queue).

I hope this can be added to the framework as I am sure many other developers might find this addition very useful in the future. If there are any concerns or changes that need to be done please do tell, this is the first time I make a pull request here.

If this change is accepted I can add/modify the relevant tests.

### CODE REVIEW

**Comment by paras-malhotra** [comment]
It's still a breaking change imo - if people have $queue set on their jobs, this would change the behaviour.

**Comment by Krunch** [comment]
> It's still a breaking change imo - if people have $queue set on their jobs, this would change the behaviour.

Would this be a better alternative then?

```PHP
$this->options['queue'] ?? $queue ?? null
```

**Comment by taylorotwell** [comment]
@paras-malhotra can you elaborate?

**Comment by paras-malhotra** [comment]
> @paras-malhotra can you elaborate?

Let's say `$queue` is set in a `SampleJob` class like so: `public $queue = 'some-queue'` and the SampleJob is dispatched using `Bus::batch([new SampleJob(...), ..])->onQueue('another-queue')->dispatch()`, the earlier behaviour (prior to this PR) would be that the SampleJob is dispatched on `another-queue` but after this PR, it would be dispatched on `some-queue`.

I don't see anything wrong with it, just saying that we should probably target master/9.x and not 8.x

**Comment by taylorotwell** [comment]
Yeah I think @paras-malhotra is correct that this would be a breaking change. I also can't decide if I even like this particular feature.

**Comment by mrmonat** [comment]
I can think of a scenario where this would be very useful:

Queue Setup:
- default queue
- long running queue (extra queue config with high timeout specified)

A number of "long running" jobs get dispatched in a batch and fetch data (this can take a while, longer than the default 60s queue timeout).
Each of this "long running" jobs can add jobs to the batch, but on the "default" queue, because these jobs don't exceed the 60s queue timeout.

All these "long running" and "default running" jobs share the same batch to track the total progress.

**Comment by ehben83** [comment]
Agree with @mrmonat and @Krunch  - would be nice to have this. 
I also currently have the need for such a behavior : tracking total progress + dispatching on different queues due to the nature of the different jobs running in it.

**Comment by jasonlfunk** [comment]
I'll add my use-case here too. I have a batched job that adds additional jobs to it. Some of these jobs are high priority and some are low priority. I need all the high priority ones to be handled prior to the low priority (but I still need to know when all of these jobs are finished.) This use-case cannot be done with the current implementation as all job as FIFO in a batch.

**Comment by Krunch** [comment]
@taylorotwell any chance you can reconsider this feature? Thank you.

**Pull request closed without merging**
