### PR TITLE
Update helpers.php for is_empty and if_isset

### PR DESCRIPTION
**Pull request by vinodraut**
We are using these function & think that these will be a very useful for laravel community if its directly available through laravel.

is_empty - Added is_empty function which nearly works on any variables including but not limited to Collection, Paginator , LengthAwarePaginator, Eloquent Collection

if_issset - Added if_issset its like isset but 2nd and 3rd parameters will work for if item isset or not.

### CODE REVIEW

**Comment by a-komarev** [comment]
`if_issset` should be named as `if_isset`.

**Comment by a-komarev** [comment]
`is_empty ` seems interesting and readable for me `if (is_empty($something))` but `if_isset` looks a bit strange `if (if_isset($something))`. And I don't see any use cases for second helper.
I'm upvoting first helper and downvoting second one.

**Comment by vinodraut** [comment]
@a-komarev 
if_isset has other 2 parameters which are helps to do some operation based on if_isset result.

**Comment by a-komarev** [comment]
Can you provide usage examples?

**Comment by vinodraut** [comment]
@a-komarev 

example uses of if_isset

`$result = if_isset($this->accessStages['xyz'], function() {
                return array_pull($this->accessStages['xyz'], '__result');
            }, null);`

**Comment by taylorotwell** [comment]
No plans on adding these for now.

**Comment by vinodraut** [comment]
Thats fine!! if someone feels this useful can use it as package at https://packagist.org/packages/livelyworks/laraware
https://github.com/livelyworks/Laraware

**Pull request closed without merging**
