### PR TITLE
[7.x] Make parsedown swappable

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This PR introduces the "illuminate/markdown" component. It should "just work". No configuration needed. As long as some markdown package is installed, it should find it, and use it.

This design is super easy to configure now. Previosuly it was impossible to configure the parsedown renderer, or use a different markdown implementation. Now it is super easy to do. Simply bind to the Markdown interface, and you're done!

By default, we support `league/commonmark`, `erusev/parsedown`, `michelf/php-markdown`, out of the box, and we search for them in that order.

---

I think there are two sane choices for the default parser. Either we:

1. stay with parsedown (https://github.com/laravel/laravel/pull/5192),
2. or we switch to commonmark (https://github.com/laravel/laravel/pull/5193).

We do this simply by means of what we include by default in new apps - the framework itself has no preference, other than the order it looks for parsers out of the box.

---

So, we're now super flexible, and everything still works without needing to install extra dependencies on apps based from laravel/laravel due to us including a parser in "require".

### CODE REVIEW

**Comment by taylorotwell** [comment]
What was some of the reasoning for this? Is Parsedown not a very good default?

**Comment by driesvints** [comment]
Isn't also the point of a specification like Markdown that you don't need to support multiple drivers because they all do the same basically?

**Comment by GrahamCampbell** [comment]
> Isn't also the point of a specification like Markdown that you don't need to support multiple drivers because they all do the same basically?

Unfortunately, markdown is not a specification. It's the name given to a family of languages. For example, GitHub flavoured markdown was historically popular, until the CommonMark specification was developed. Only the league CommonMark library is actually following this specification. Parsedown has no specification, and seems to make breaking changes to parsing in minor releases.

> Is Parsedown not a very good default?

So, yeh, as I said above, Parsedown doesn't actually have a spec, and is not stable between versions.

> What was some of the reasoning for this?

The main reasoning for this is that it's totally impossible (without replacing the framework's view files) to customize the markdown parser. After this PR, it's now super easy to do this, since we resolve the markdown contract from the ioc container.

I think the league CommonMark package is the best default, and it's actually more used that Parsedown. This is because most of Parsedown's downloads are coming from laravel/framework or illuminate/mail downloads. There were 2156952 downloads of laravel/framework or illuminate/mail 5.4, 5.5, 5.6, 5.7, 5.8 and 6.x in the last 30 days, and 2165578 parsedown downloads. This means only 8626 people intentionally downloaded Parsedown in the last 30 days, compared to league's commonmark, which had 96691 downloads in the last 30 days.

Note also that my graham-campbell/markdown package had 39048 downloads in the last 30 days, and it brings commonmark into laravel, and makes it easy to customize, so that shows that there is demand for it. 11x as many people downloaded commonmark for laravel (using my package alone) than those downloading parsedown to use outside of laravel!

---

Finer details for calculating the laravel downloads over the last 30 days:

Laravel 5.4: 98410  + 3813
Laravel 5.5: 221912 + 7482
Laravel 5.6: 143645 + 5988
Laravel 5.7: 237423 + 9959
Laravel 5.8: 553445 + 14515
Laravel 6.x: 851005 + 9355

**Comment by GrahamCampbell** [comment]
Customising markdown parsers is totally a common thing to do, I should add. One could view parsedown extra as doing that. The CommonMark package has an extension system for doing this, and there are many extentions. For example, if people wanted to have twitter handles parsed and links, they'd need to customize the parser to do that. Something they can't do easily without this PR.

**Comment by GrahamCampbell** [comment]
I'm wondering if I should remove the locator class, and just move the content of create within the closure in the service provider?

**Comment by mfn** [comment]
Can you given an example how I would use a custom markdown implementation, I mean specifically where exactly would I specify it to replace the existing one?

**Comment by GrahamCampbell** [comment]
Yeh. If you want a totally custom implementation, just bind the "Markdown" contract in your app service provider. Laravel will then just use it.

If you are not overriding that, and want to customise the commonmark instance used, just rebind the commonmark interface, then Laravel will get that from the container when it looks to see if it can use commonmark, rather than creating the default commonmark setup.

**Comment by mfn** [comment]
Got it!

So there seems to reason to have the locator for further customization and I think your suggestion for the closure makes sense 👍

**Comment by GrahamCampbell** [comment]
> So there seems to reason to have the locator for further customization and I think your suggestion for the closure makes sense

I'm going to delete the locator class, since I actually didn't intend for anyone to ever call it.

Here are my two examples more clarified:

# Example 1

Suppose you want to totally replace the markdown renderer the framework will use. Simply bind the thing you wanna use in your app service provider:

```php
$this->app->singleton(\Illuminate\Contracts\Markdown\Markdown::class, function ($app) {
    return new ...
});
```

# Example 2

Suppose you have installed commonmark in your app's composer.json instead of parsedown, and you wanna install a commonmark extension. No need to rebind the markdown contract. Just bind the commonmark environment in your app service provider:

```php
$this->app->singleton(\League\CommonMark\EnvironmentInterface::class, function ($app) {
        $environment = \League\CommonMark\Environment::createCommonMarkEnvironment();

        $environment->addExtension(...);

        return $environment;
});
```

**Comment by GrahamCampbell** [comment]
Added a test to demonstrate using a custom commonmark environment:

```php
    public function testResolvesCustomCommonMarkEnv()
    {
        $app = new Application();
        $app->register(new MarkdownServiceProvider($app));

        $app->singleton(EnvironmentInterface::class, function () {
            $environment = Environment::createCommonMarkEnvironment();

            $environment->addExtension(new class implements ExtensionInterface {
                public function register(ConfigurableEnvironmentInterface $environment)
                {
                    throw new Exception('Ext was resolved!');
                }
            });

            return $environment;
        });

        $markdown = $app->make(Markdown::class);

        $this->expectException(Exception::class);
        $this->expectExceptionMessage('Ext was resolved!');

        $markdown->render('foo');
    }
```

It shows that laravel automatically used the environment I had bound, since when I asked it to render, it involved the extension I had added.

**Comment by driesvints** [comment]
Can we instead of creating a new component move the Markdown stuff into the Support or View component? I'm not sure is a new component is needed for this.

**Comment by GrahamCampbell** [comment]
I'm not really sure where it fits. Laravel does already have quite small components for some things, like cookie and hash. There would certainly be an argument for moving hash into support or cookie into http, if those components were being created today.

**Comment by GrahamCampbell** [comment]
Same with the pipeline component, which could have easily been put in support.

**Comment by taylorotwell** [comment]
I don't think we should make this swappable. I think we should use one good default. If a better default is now CommonMark I am fine switching to that. I think original I used Parsedown for the table support possibly. But, I see there is an official table extension for CommonMark. I am fine with switching to that if we want to do a smaller PR for that.

**Pull request closed without merging**
