### PR TITLE
[5.1] SQL server exists fix

### PR DESCRIPTION
**Pull request by acasar**
Possible fix for https://github.com/laravel/framework/issues/10580

### CODE REVIEW

**Comment by taylorotwell** [comment]
@HipsterJazzbo your PR broke something

**Comment by taylorotwell** [comment]
Closing since issue reports this is still broken even with this PR applied.

**Comment by taylorotwell** [comment]
Ping @HipsterJazzbo. We still have a broken feature from your PR that we will revert if is not fixed soon.

**Comment by vlakoff** [comment]
It took me a bit of time to track back to the relevant PR, so here it is:  #10373.

**Pull request closed without merging**
