### PR TITLE
[11.x] `Fluent::scope/collect` methods

### PR DESCRIPTION
**Pull request by stevebauman**
## Description

> This PR is a rehash of https://github.com/laravel/framework/pull/49054, but targeting `Fluent`.

The `Support\Fluent` instance is underpowered imo, and I think it can provide a ton of value to developers like the `Collection` class does. While collection instances provide utilities to _arrays of items_, fluent instances could provide utilities to _arrays of attributes_.

Having the ability to access deeply nested attributes via dot-notation on a framework level class instance, that can also convert to collections, makes Fluent instances incredibly powerful.

Imagine getting a response from an HTTP request for products, mapping them into `Fluent` instances. This provides you great utility methods for accessing their deeply nested associative array data:

```php
// $product = Http::get('api/products')->collect()->mapInto(Fluent::class)->first();

$product = new Fluent([
    'name' => 'Smartphone',
    'brand' => 'Apple',
    'details' => [
        'price' => 499.99,
        'operatingSystem' => 'OS 8.1',
        'colors' => ['black', 'white', 'blue'],
        'features' => [
            'screen' => '6.5 inch OLED',
            'battery' => '4500mAh',
            'camera' => [
                'front' => '12 MP',
                'rear' => [
                    'wide' => '12 MP',
                    'ultrawide' => '16 MP',
                    'zoom' => '10 MP'
                ]
            ],
        ],
    ],
]);

// Dot-notation access
$product->get('details.features.camera');

// Collection transformation
$product->collect();

// Scope to Collection transformation
$product->scope('details.colors')->collect()->sort();
```

## Breaking Changes

Since `Fluent` now uses `Arr::get` on the underlying `$attributes` array to support dot-notation, existing arrays containing dots in their array keys won't function correctly when accessing them via `get`.

If we don't want to break BC, we can place `Arr::get` in the `scope` method specifically, or provide another utility method for providing dot-notation access to the Fluent instance. Maybe something like `value`, etc.

```php
$fluent = new Fluent(['...']);

$fluent->value('foo.bar.baz');
```

---

Let me know your thoughts! Thanks so much for your time. No hard feelings on closure ❤️

### CODE REVIEW

**Comment by simonhamp** [comment]
@stevebauman Could the `toCollection` method take a collection class name as a parameter so that it's possible to create a subclass of `Illuminate\Support\Collection`, and not just the default built-in Collection class?

**Comment by stevebauman** [comment]
@simonhamp Yea for sure, though I'm not sure if the method name would be properly suitable anymore, unless we verify the instance type before hand? Ex:

```php
public function toCollection($class = Collection::class)
{
    return new $class($this->attributes);
}

// ...

$fluent->toCollection(stdClass::class);
```

**Comment by woodspire** [comment]
> @simonhamp Yea for sure, though I'm not sure if the method name would be properly suitable anymore, unless we verify the instance type before hand? Ex:
> 
> ```
> public function toCollection($class = Collection::class)
> {
>     return new $class($this->attributes);
> }
> 
> // ...
> 
> $fluent->toCollection(stdClass::class); // Incorrect usage
> ```
simply add a check: if (! $ class instanceOf BaseCollection) { throw new error }

**Comment by stevebauman** [comment]
@woodspire `instanceof` doesn't work with string based class references:

```php
$data = collect();

$class = Collect::class;

$data instanceof $class; // false
```

**Comment by taylorotwell** [comment]
This PR is triggering all sorts of weird test failures for me. Wondering if it needs to be rebased or something?

**Comment by simonhamp** [comment]
@stevebauman you may be able to use [`is_a()`](https://www.php.net/manual/en/function.is-a.php) to accept the string variant through

**Comment by stevebauman** [comment]
@taylorotwell Hmm seems to be attributed to `data_get` vs `Arr::get` in the `Fluent::get` method.

The same tests in GitHub actions fail locally with `data_get`, but pass with `Arr::get`, going to debug 👍

**Comment by stevebauman** [comment]
Ok fixed. It was due to the `config` container instance being created as `Fluent` inside the test environment, and it containing array keys with dots (see below).

I've update the PR to use the new `value` method for the `offsetGet` and `__get` methods. Let me know your thoughts!

```

Illuminate\Container\Container {#1034▶
  #resolved: []
  #bindings: []
  #methodBindings: []
  #instances: array:1 [▶
    "config" => Illuminate\Support\Fluent {#1030▶
      #attributes: array:2 [▶
        "database.fetch" => 5
        "database.default" => "default"
      ]
    }
  ]
  #scopedInstances: []
  #aliases: []
  #abstractAliases: []
  #extenders: []
  #tags: []
  #buildStack: []
  #with: []
  +contextual: []
  #reboundCallbacks: []
  #globalBeforeResolvingCallbacks: []
  #globalResolvingCallbacks: []
  #globalAfterResolvingCallbacks: []
  #beforeResolvingCallbacks: []
  #resolvingCallbacks: []
  #afterResolvingCallbacks: []
}
```

**Pull request merged**
