### PR TITLE
[7.x] Add until Collection method

### PR DESCRIPTION
**Pull request by jasonmccreary**
This introduces a new `until` Collection method. It is similar to the `take_while` method in Ruby.

While this functionality may be achieved using combinations of the existing Collection methods or with custom logic, the code clarity provided by this single method brings value.

For example:

```php
[$before, $after] = $primes->partition(function ($item) {
    return $item < 11;
});
$before->dump();
```

May simply be written as:

```php
$primes->until(11)->dump();
```

This would be useful as a _higher order_ method as well.

### CODE REVIEW

**Comment by jasonmccreary** [comment]
If this is acceptable, I'd be glad to follow-up with the Higher Order Proxy for `until` as well as the update to the Docs.

**Comment by taylorotwell** [comment]
Curious to see some application examples of when this might be helpful in a typical Laravel app...

**Comment by taylorotwell** [comment]
Interesting. Can you share that snippet of code?

**Comment by GrahamCampbell** [comment]
We probably want this on lazy collections too?

**Comment by jasonmccreary** [comment]
@taylorotwell, unfortunately, it was just a quick script to rebuild some lost order data. So I didn't keep it. However, I ended up doing a `foreach` just because the finding the right combination of `filter` or short-circuiting `each` felt more verbose.

Glad to sit on it until I come across another need.

@GrahamCampbell, yeah, I think it'd be pretty nice as a Higher Order Proxy too. That way it's easier to pass custom logic.

```php
$prs->until->unapproved();
```

Glad to add it to whatever. Just want to make sure it's _merge-worthy_ first.

**Comment by taylorotwell** [comment]
I'm pretty good with it. Do you think there is merit to naming it `takeWhile` just so it has parity with the existing Ruby method people might already be familiar with?

**Comment by jasonmccreary** [comment]
Your call. I only changed it to have the nice single word method name.

Also, this stops _when_ the condition is met, whereas `takeWhile` might imply a different logic.

**Review by rbuzzibarrios — APPROVED** [review]

**Comment by taylorotwell** [comment]
OK, that's fine. Let's go ahead and wrap this up then with the HigherOrder support and LazyCollection support.

**Comment by taylorotwell** [comment]
@jasonmccreary ping me when you are done with this

**Pull request merged**
