### PR TITLE
[5.5] simplify currentPageResolver

### PR DESCRIPTION
**Pull request by huglester**

### CODE REVIEW

**Comment by ludo237** [comment]
> the difference is that a cast to int will always get you an int, which may or may not be the original value. E.g. (int)'foobar' results in the int 0. This makes it safe for most SQL purposes, but has nothing to do with the original value, and you won't even know it.
filter_var with FILTER_VALIDATE_INT tells you whether the value is an int, based on which you can make the decision to use it in an SQL query or display an error message to the user.


From this [SO](https://stackoverflow.com/questions/4789624/php-security-int-vs-filter-validate-int#4789649)

**Comment by huglester** [comment]
I understand that, FILTER_VALIDATE_INT it will tell you if it's integer or not, but why bother here?

The problem here is that in this situation we do not throw an exception if it's not an integer, anyway we always return the integer.

so why bother checking for 'is it integer'?

**Comment by jmarcher** [comment]
Well, it changes the behaviour, if, for example, you have something like:
```
$page="2a";
```
With your changes, the code returns 2 whereas the original one returns 1.

**Comment by huglester** [comment]
thanks @jmarcher .
never spotted, that '2a' would return 2 when casting to int

**Pull request closed without merging**
