### PR TITLE
[8.x] Batch jobs

### PR DESCRIPTION
**Pull request by themsaid**
This PR allows the following:

```php
$batchId = (new Batch([
    new ProcessRows(1,1000),
    new ProcessRows(1001, 2000),
]))->then(function () {
     // Do something after the 2 jobs has ran.
})->otherwise(function () {
    // Do something if any job fails.
})->dispatch();
```

If any of the jobs fail, the whole batch will be considered failed and will be deleted from storage. 

However, people can use `allowFailure()` and the batch will continue running even if any/all jobs fail.

```php
(new Batch([
    new ProcessRows(1,1000),
    new ProcessRows(1001, 2000),
]))->then(function () {
     // Do something after the batch is done.
})->allowFailure()
   ->dispatch();
```

Inside each job user must check if the batch still exists or not before running the job so they don't process jobs of a batch that has already failed. To check if the batch is still running:

```php
// Inside the job class.
public function handle()
{
    if (! $this->batchIsActive()){
        return;
    }

    // Run the job logic.
}
```

You can also add more jobs to a batch:

```php
public function handle()
    {
        if (! $this->batchIsActive()) {
            return;
        }

        $this->batch()->add([
            new TestJob(),
            new TestJob(),
        ]);
    }
```

You can gather information about a batch:

```php
$batch = Batch::find($id);

$batch->size();
$batch->pending();
$batch->processed();
$batch->failures();
$batch->isRunning();
$batch->hasFailed();
$batch->hasFinished();
```

### CODE REVIEW

**Comment by lucadegasperi** [comment]
This looks awesome!
When a batch is created can I query it for how many jobs are into it?
What about firing an event every time the batch counter is decremented or changed?
Can the batch counter be incremented while it's running by adding new jobs to it or sub-jobs?

**Comment by DarkGhostHunter** [comment]
* It would be cool to have a way for the Batch to capture the exception and allow the callback to handle it. 
* Also, to know some basic statistics about the Batch itself, assuming the Batch is some kind of expensive logic. I think the time when it started and finished should be enough.

```php
Batch::process(
    new ProcessRows(1,1000),
    new ProcessRows(1001, 2000),
)->then(function (Batch $batch) {
    User::find(3)->notify(new BatchCompleted($batch->startedAt(), $batch->finishedAt()));
})->otherwise(function (Batch $batch) {
    User::find(3)->notify(new BatchFailed($batch->getException()->getMessage()));
})->dispatch();
```

**Comment by hailwood** [comment]
@themsaid so one of the things I did recently was importing from a couple of CSVs,
These had +200,000 rows each, so I wanted to batch them, the catch was that the 

unfortunately the best I could do was 

Import the first CSV as a single job,
Then queue the second larger CSV as individual jobs (processing 1000 rows each).

So... 
I'm thinking this proposal would allow something like this proposal allow something like the following correct?

```php
// $arrayOfFirstJobs;
// $arrayOfSecondJobs;

Batch::process($arrayOfFirstJobs)
    ->then(fn(Batch $firstBatch) => Batch::process($arrayOfSecondJobs)->dispatch()
        ->then(fn(Batch $secondBatch) => User::find(3)->notify(new BatchCompleted(
            $firstBatch->startedAt(),
            $secondBatch->finishedAt()
        )))
        ->otherwise(fn(Batch $batch) => User::find(3)->notify(new BatchFailed(
            $batch->getException()->getMessage()
        )))
    )
    ->otherwise(fn(Batch $batch) => User::find(3)->notify(new BatchFailed(
        $batch->getException()->getMessage()
    )))
    ->dispatch();
```

Would it be possible to add more jobs to the batch later and also can we use multiple then/otherwises?

E.g.

```php
Batch::process($arrayOfFirstJobs)
    ->then(fn (Batch $batch) => $batch->process($arrayOfSecondJobs))
    ->then(fn (Batch $batch) => User::find(3)->notify(new BatchCompleted(
        $batch->startedAt(), 
        $batch->finishedAt()
    )))
    ->otherwise(fn (Batch $batch) => User::find(3)->notify(new BatchFailed(
        $batch->getException()->getMessage()
    )))
    ->dispatch();
```

In the above the assumption is that if the previous `then` returns a batch to be processed, it's
a) Auto dispatched
b) subsequent `then`s are delayed until the new batch has completed.

Can we have self handling batches?

E.g.

```php
class CsvBatch extends BatchProcessor
{

    public User $user;

    public $run = 1;

    public function __construct(User $user)
    {
        $this->user = $user;
    }

    public function finished(CsvBatch $batch)
    {
            if($this->run === 1) {
                $this->run = 2;
                return $this->process(...get_more_jobs());
            } else {
                $this->user->notify(new BatchCompleted(
                    $batch->startedAt(), 
                    $batch->finishedAt()
                ));
            }
    }

    public function failed(CsvBatch $batch)
    {
            $this->user->notify(new BatchFailed(
                $batch->getException()->getMessage()
            ));
    }
}
```

```php
(new CsvBatch(User::find(3)))->process(...$jobs)->dispatch();
```

**Comment by anouarabdsslm** [comment]
thanks @themsaid  for this feature. Can we have the the `job` that make the batch fails to be passed to the otherwise closure ??

**Comment by netpok** [comment]
I'm not sure about storing the batch in cache:
- It has an hour timeout: what if a job takes more time or just the queue is very long
- Cache could be emptied for example by a `cache:clear` in a deploy script

Maybe it would be better to store in the cache driver (I know that not all supports it) or a definable store.

**Comment by taylorotwell** [comment]
Closed pending https://github.com/laravel/framework/pull/32830

**Pull request closed without merging**
