### PR TITLE
Changed "/" to DIRECTORY_SEPARATOR

### PR DESCRIPTION
**Pull request by Garbee**
Makes path helpers usable in Windows servers. Fixes issue #8913.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1: from me.

**Comment by GrahamCampbell** [comment]
> Makes path helpers usable in Windows servers.

If you're doing this, all you're doing is breaking your code that used to work on linux.

**Comment by GrahamCampbell** [comment]
If you're doing the things that were described in that other issue.

**Comment by Garbee** [comment]
> If you're doing this, all you're doing is breaking your code that used to work on linux.

Please support with some examples/facts.

You can thumb-down it all you want, it doesn't create any problems on Linux and Taylor has already acknowledged the issue is an actual issue. So let's focus on getting the issue fixed, not outright rejecting everything you don't see as fit.

**Comment by nicholasruunu** [comment]
`DIRECTORY_SEPARATOR` in linux env will evaluate to / so I don't see how this would change anything on linux.

**Comment by Garbee** [comment]
Also, let's be clear with what can happen now. On Windows environments you can easily `explode()` the output returned by the helpers, before you would need to explode, then do it again to the parts for the other separator.

This change allows for far better coding to be done. Any challenges to it should be met with facts/test cases. That way they can be addressed and solved. Plenty of facts exist as to why this constant should be used, none as to why "/" should be other than "it works in most situations most of the time so it isn't a problem." Which is nothing but complete horse shit.

**Comment by Garbee** [comment]
On the note of storing paths being an edge-case, it really depends on how people have built their systems. A lot of the time, things like image/file attachment to models will store some path in the DB. If they store the path pulled from one of these helpers as a starting point and are under Windows, then there would be a problem.

That is the most likely point of concern (other than temp caching of paths in redis or something.) But, once again, all *Windows* focused which is already a small subset of users, especially in production.

**Comment by daftspunk** [comment]
:-1: from me, because @Garbee. Just kidding mate :-)

**Comment by Garbee** [comment]
Dude stop sounding like Flyn. It will only bring pain and anguish.

**Comment by Flynsarmy** [comment]
:thumbsdown:

**Comment by GrahamCampbell** [comment]
This stuff isn't changing again, while I don't really like it either, that's what we have now.

**Comment by Garbee** [comment]
@GrahamCampbell Why don't you like it exactly? It seems odd a framework that prides itself on consistency and ease of use has a collaborator who evangelizes things that make it inconsistent and harder to use.

You also never supported your claims on it breaking code that worked on Linux boxes. So if you could revisit that as well it would be great. I'd love to know how it would break things, yet has been released to stable and we haven't heard a word of it.

**Comment by GrahamCampbell** [comment]
> It seems odd a framework that prides itself on consistency and ease of use has a collaborator who evangelizes things that make it inconsistent and harder to use.

I think it's more consistent to always use linux style separators.

**Comment by robclancy** [comment]
I think it is more consistent to always use the constants PHP provides for a reason.

/imbackbitches

**Comment by GrahamCampbell** [comment]
Hi Rob. :0

**Comment by GrahamCampbell** [comment]
Hi Rob. :)

**Pull request merged**
