### PR TITLE
[5.5] No need to use a collection for that

### PR DESCRIPTION
**Pull request by lucasmichot**
No need to use a collection for that

### CODE REVIEW

**Comment by browner12** [comment]
is there a performance difference here?

**Comment by lucasmichot** [comment]
Yes @browner12 , it's much faster. You don't need to create a useless collection.
Check `\Illuminate\Support\Collection::first`, it's only calling `\Illuminate\Support\Arr::first`

**Comment by garygreen** [comment]
I'm really not sure why Laravel is so obsessed with Collections so much lately, or closures. Is it for readability? Is it an avoidance of a loop at all costs? Because personally I find the second one to be simpler and more readable, it's also less "visual debt" to me.

```php
return ! is_null(Arr::first($dontReport, function ($type) use ($e) {
    return $e instanceof $type;
}));
```

```php
foreach ($dontReport as $type) {
	if ($e instanceof $type) {
		return true;
	}
}

return false;
```

**Comment by lucasmichot** [comment]
Yeah @garygreen, but sometimes a function name (`first` in this case) is also a good indicator about what we are trying to achieve.

At the end anyone can code it the way one wants in any app, but within the framework we should avoid to create useless objects, which is the case here

**Comment by vlakoff** [comment]
Agree with @garygreen. Its second snippet is **much** more readable. Not to mention it's also much faster.

**Pull request merged**
