### PR TITLE
Improve has for nested relations

### PR DESCRIPTION
**Pull request by jarektkaczyk**
The same as https://github.com/laravel/framework/pull/4237 only greatly simplified ;)

### CODE REVIEW

**Comment by RSully** [comment]
Has this been fixed since? I am having trouble using whereHas on same-table relations in a 4.1 application.

**Comment by lukasgeiter** [comment]
@RSully It has been fixed, but probably not for 4.1. You'll have to update.

**Comment by RSully** [comment]
@lukasgeiter I updated to 4.2 and didn't seem to fix my problem.

**Comment by RSully** [comment]
Looking through the comments I think the issue I am having is the same as @te11ur, which is unrelated to this pull request. (Also, this was merged in as #6726.)

**Pull request closed without merging**
