### PR TITLE
[5.5] Add Query Builder method "if"

### PR DESCRIPTION
**Pull request by damonto**
In some scenes the "when" method don't fit right, so I wrote an if method to solve this problem.

Before:
```
User::when(true, function ($query) {
    $query->where('email', 'xxx@xxx.com');
});
```

After:
```
User::if(true, 'email', 'xxx@xxx.com')
```

### CODE REVIEW

**Comment by papac** [comment]
Note that the @param attribute is followed by two spaces, the argument type, two more spaces, and finally the variable name.

**Comment by alexbowers** [comment]
If this is replacing `when` could it not just act as an alias?

**Comment by alexbowers** [comment]
Oh, I see. It is not just an alias, it is a `when where` combination?

Neat.

**Comment by leongpeng** [comment]
@alexbowers Yes. it's a `when where` combination.

If you are using `when` your code looks like this:

```
User::when(request->has('xxx'), function ($query) {
     $query->where('xxx', 'xxxx')
})
->when(request->has('yyy'), function ($query) {
    $query->where('yyy', 'yyyy');
})
```

But now i can use `if` instead of `when`

```
User::if(request->has('xxx'), 'xxx', 'xxxx')
      ->if(request->has('yyy'), 'yyy', 'yyyy')
```

**Comment by amochohan** [comment]
I think to be more useful, the second argument could be checked to see if it is callable, so that I could still perform more complex conditions such as:

```php
User::if(true, function ($query) {
     $query->whereHas('somerelationship', function ($q) {
          $q->where('attribute', 'value');
     })
})
```

**Comment by kamui545** [comment]
amochohan Just use the `when` method? Or am I missing something? lol

**Comment by n7olkachev** [comment]
It is so unclear. I'd never guess that `if` method calls `where` internally.

**Comment by taylorotwell** [comment]
No plans to add this right now.

**Pull request closed without merging**
