### PR TITLE
str_before and str_after bug fix

### PR DESCRIPTION
**Pull request by JacobBennett**
Will fail if passing "0" for the `$search`

Sorry @taylorotwell 

image

### CODE REVIEW

**Comment by browner12** [comment]
I think you may actually need a strict comparison here.

```php
return $search === "" ? $subject : array_reverse(explode($search, $subject, 2))[0];
```
If the user passes in an integer for `$search` (I don't know why, but it probably will happen), an integer `0` will evaluate `true` without the strict comparison and simply return the `$subject`.

Example:

```php
str_after('there are 0 bananas', 0);
```

Without the strict comparison:  'there are 0 bananas'

With the strict comparison: ' bananas'

**Comment by browner12** [comment]
ping @JacobBennett

**Comment by JacobBennett** [comment]
Thanks for the fix on this @browner12 https://github.com/laravel/framework/commit/1e4f1899903215aaac41bc6a0855a0c88e8b8b2b

**Comment by Hendrikto** [comment]
Wow... the new code is considerably less readable than the one it replaced.

You should just revert everything back. With all the changes this "one-liner" is garbage.

**Comment by devcircus** [comment]
A very common pattern in string manipulation. 
Reads very clearly to me.

**Pull request merged**
