### PR TITLE
[5.6] Use Inflector array of uncountable words

### PR DESCRIPTION
**Pull request by carusogabriel**
Inflector [has an array of uncountable words](https://github.com/doctrine/inflector/blob/master/lib/Doctrine/Common/Inflector/Inflector.php#L233). So, why not use it? :smile:

### CODE REVIEW

**Comment by taylorotwell** [comment]
If we do this, why have this protected uncountable method at all? Just let it plural every time and it's the same, fine.

**Comment by GrahamCampbell** [comment]
> If we do this, why have this protected uncountable method at all? Just let it plural every time and it's the same, fine.

Being uncountable implies that the plural is the same BUT, the plural being the same does not imply uncountable, so this change is wrong.

For example, Aircraft is countable, but the plural form is the same as the singular.

**Comment by taylorotwell** [comment]
Hmm, I guess I'm missing something. What situation is now broken after this change?

**Comment by rs-sliske** [comment]
Inflector::pluralize's list of things which are uncountable (if it has one, to be honest i havent looked yet) is wrong

`collect(Pluralizer::$uncountable)->filter(function($value){return Inflector::pluralize($value) !== $value;})->mapWithKeys(function($value){ return [$value => Inflector::pluralize($value)];})->toArray()`

**Comment by taylorotwell** [comment]
Sigh, guess I'll revert this (manually).

**Pull request merged**
