### PR TITLE
[10.x] Revert PR 50403

### PR DESCRIPTION
**Pull request by driesvints**
Reverts https://github.com/laravel/framework/pull/50403

### CODE REVIEW

**Comment by devajmeireles** [comment]
@driesvints , we don't need a PR like that to the `11.x`?

**Comment by driesvints** [comment]
@devajmeireles yes I'm merging this into upstream.

**Comment by steve-junker** [comment]
@driesvints, what has to be done to update the subtree split https://github.com/illuminate/view/blob/v10.48.2/Compilers/ComponentTagCompiler.php#L261 and the packagist package https://packagist.org/packages/illuminate/view#v10.48.2?

**Comment by driesvints** [comment]
Tried tagging v10.48.3 and that seems to have done the trick.

**Pull request merged**
