### PR TITLE
[5.4] Allow setting a factory's attribute to a factory instance

### PR DESCRIPTION
**Pull request by JosephSilber**
The factory will then create the model and use its primary key.

---

So instead of this:

```php
$factory->define(Post::class, function ($faker) {
    return [
        'user_id' => function () {
            return factory(User::class)->create();
        },
   ];
});
```

You can now use this:

```php
$factory->define(Post::class, function ($faker) {
    return [
        'user_id' => factory(User::class),
   ];
});
```

After this there's no need for `lazy` anymore, so it's been removed.

### CODE REVIEW

**Comment by taylorotwell** [comment]
How do you pass custom attributes to it?

**Comment by JosephSilber** [comment]
Custom attributes in this case are usually not needed.

You can always use a closure if you need to.

**Comment by taylorotwell** [comment]
Hmm then I think `lazy` should be left in there.

**Comment by taylorotwell** [comment]
I think using `lazy` is fine here.

**Pull request closed without merging**
