### PR TITLE
Update DatabaseRule.php

### PR DESCRIPTION
**Pull request by zhitoo**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What does this fix?

**Comment by GrahamCampbell** [comment]
Class names are defined only with backslashes. Forward slashes are incorrect.

**Comment by hshafiei374** [comment]
'App/Models/Users'

**Comment by hshafiei374** [comment]
App\Models\Users::class

**Comment by GrahamCampbell** [comment]
Only the bottom one is allowed input. The first example you give is not supported.

**Pull request closed without merging**
