### PR TITLE
Add override to redirect url

### PR DESCRIPTION
**Pull request by kubacode**
Adding an optional property to override the default validation redirect URL.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm curious, why would you need this?

**Comment by taylorotwell** [comment]
I don't think this would be very common. Just override the method if needed.

**Comment by kubacode** [comment]
In my use case, I have a Register form on my sites index. If there are validation errors, I want to redirect do a dedicated Register page rather than back to the index. As far as I am aware, you can't override using the AuthenticatesAndRegistersUsers trait? Please correct me if I am wrong!

**Comment by taylorotwell** [comment]
Yeah you should just be able to override the method.

**Pull request closed without merging**
