### PR TITLE
[6.x] URL encode $path in FilesystemAdapter->getLocalUrl()

### PR DESCRIPTION
**Pull request by LukeTowers**
Fixes https://github.com/laravel/framework/issues/34199

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Doesn't this risk double encoding paths?

**Comment by LukeTowers** [comment]
@GrahamCampbell only if someone is encoding the results of `$disk->url()` then yes, it would, but I would argue that they shouldn't be doing that, and if they are then they should be doing the same `rawurlencode(rawurldecode($disk->url($path)))` that we're doing in October to protect against this change, given that the `url()` method is assumed to be returning valid URLs.

**Comment by driesvints** [comment]
@LukeTowers what stops you from doing this in userland?

**Comment by taylorotwell** [comment]
We could perhaps consider this for 9.x but I don't think we can technically release it on 6.x and up because of semantic versioning and it being a breaking change.

**Comment by driesvints** [comment]
> Is master the branch that I should target for inclusion in 9.x?

Yeah, although I must say that I'm a bit hesitant to say that we should merge this. It's been the current behavior since years already without any reports on it.

**Comment by LukeTowers** [comment]
@driesvints fair enough, although I would still recommend adding a disclaimer to the docs, one would expect the url() method to return an actual valid URL.

**Comment by driesvints** [comment]
@LukeTowers good point. Can you maybe send in a PR for that?

**Comment by LukeTowers** [comment]
@driesvints done: https://github.com/laravel/docs/pull/6359

**Pull request closed without merging**
