### PR TITLE
[5.2] Stabilized table aliases for self joins by adding count

### LINKED ISSUE #13353: Self join prevents DB query cache
It occurred to me, that any query using a self join is never to be cached by a database because, although the query parameters remain equal, the query isn't the same every time it's executed. This is because Eloquent generates a table alias based on the microtime ([BelongsToMany](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L377), [BelongsTo](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php#L126), [HasOneOrMany](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php#L100)).

Do you think it would be possible to generate the table alias based on something that doesn't change a much? Like an md5 of the table name, for example. This would allow for the query to be cached by the database itself.

I'd be happy to make a pull request, but I can't oversee all implications of what I'm suggesting; it might have some side effects or break BC, I don't know. Therefore, I thought it'd be a good thing to submit an issue first.

### PR DESCRIPTION
**Pull request by JeroenVanOort**
In order to improve query cacheability.

---

Fixes #13353.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
No need to hash that value?

**Comment by JeroenVanOort** [comment]
The only reason to hash is in case someone has tables like 'self_1', 'self_2', etc.

**Comment by GrahamCampbell** [comment]
how is the hash anymore resistant?

**Comment by GrahamCampbell** [comment]
maybe just call it laravel_reserved_1

**Comment by JeroenVanOort** [comment]
I think it's less likely for someone to have a table like 'self_c4ca4238a0b923820dcc509a6f75849b' than 'self_1'. The same reason why it was used in the first place, I assume; I just left it in.

Sure, the prefix could be changed to 'laravel_reserved_' to avoid this all together.

**Comment by taylorotwell** [comment]
Holding off on this.

**Comment by GrahamCampbell** [comment]
@taylorotwell What about for 5.3?

**Comment by JeroenVanOort** [comment]
@taylorotwell So what do I do now? I'd really like to have this merged in some shape or form. I guess you want to have a good look at this before merging and I get that, but closing the PR isn't very motivating for me.

**Comment by JeroenVanOort** [comment]
@GrahamCampbell Could we please look at this once more?

**Comment by taylorotwell** [comment]
Will re-open for reconsideration.

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell Could we please look at this once more?

Not upto me. Upto @taylorotwell. ;)

**Comment by JeroenVanOort** [comment]
Benchmarks for this request are difficult in the sense that this change has it's largest effects on long, more complicated queries on data that doesn't change by the second (in which case caching isn't helpful anyway), which I can't easily replicate in code I can share.

The most simple scenario is making a list of children that have a parent: in the current situation the generated table alias is different every time the query is executed and thus can't be cached. In the situation requested the alias will be the same every time, so it can be cached by the database system itself. On these simple queries, I've seen the query time halved, but they didn't take very much time to run anyway.

What you'll have to take my word for, is that I observed the time taken to execute a longer query drop from about 350ms to 1.1ms by simply executing the same thing twice (on a MySQL server that is set up to support caching, Homestead doesn't by default). For one project I'm working on, the page load time (as reported by the debug bar) goes down from ~500ms to just ~160ms, after the query has been cache by the first page load.

As far as I know, this change doesn't break anything; it just enables the database engine do it's caching job.

**Pull request merged**
