### PR TITLE
[5.1] Use ellipsis character (&hellip;) instead of three dots (...)

### PR DESCRIPTION
**Pull request by jufy**
Use ellipsis character (&hellip;) instead of three dots (...) in str_limit() function.

This helps with HTML validation.

### CODE REVIEW

**Comment by willrowe** [comment]
`str_limit` isn't always used in HTML output, it could be used for JSON or plain text. This wouldn't work in those cases.

**Comment by GrahamCampbell** [comment]
This is breaking, and is also wrong. This function isn't just used within the context of html.

**Comment by jufy** [comment]
Then three dots "..." can be replaced with "…". This is although valid for HTML, supported by JSON and plain text formats

**Comment by GrahamCampbell** [comment]
You can do what ever you like in your own app, that's why this is a configurable paramater.

**Pull request closed without merging**
