### PR TITLE
[7.x] Guzzle-like request body summary added to HttpClient RequestException

### PR DESCRIPTION
**Pull request by Salmondx**
Small addition to PR https://github.com/laravel/framework/pull/31720

`Illuminate\Http\Client\RequestException` now contains a short truncated summary of failed response body content.

The code is similar to how Guzzle handles exceptions (e.g. `GuzzleHttp\Exception\RequestException`).

It may be useful in debugging or log collecting purposes (in Sentry for example). In current iteration of this exception the only way to understand why request failed is to reproduce it manually.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. but my feeling is that this is overkill. This component is meant to be a simple API for the 95% of the use cases. It is intended that everyone else simply should just use Guzzle.

**Comment by Salmondx** [comment]
Hm, I didn't change the component logic and its API, just made it simpler to trace errors for 95% of use cases 😄

I replaced Guzzle almost everywhere in my projects so you did a great job. That's probably the only missing feature that I face almost daily.

**Comment by igorsgm** [comment]
I think that what @Salmondx wrote for the `Illuminate\Http\Client\RequestException` in this pull-request is a good improvement to handle the Http exceptions.

Currently, in most cases, the class just returns 401 or 403 in logs without any deeper explanation or trace that would help the developers to reproduce the bug.
And in my opinion, add the Guzzle package just to have a simpler debug experience wouldn't be such an elegant use case, once the built-in `HttpClient` solves most api requests scenarios

**Comment by taylorotwell** [comment]
Why did you not use Guzzle's `\GuzzleHttp\Psr7\get_message_body_summary($response);` function directly?

**Comment by Salmondx** [comment]
> Why did you not use Guzzle's `\GuzzleHttp\Psr7\get_message_body_summary($response);` function directly instead of duplicating the code?

As I saw laravel have only dev dependency on guzzle and in general as I understand you prefer not to use Guzzle dependencies whenever it is possible. If it is not true and I can use Guzzle functions - will be glad to update 👍

**Comment by taylorotwell** [comment]
It's impossible to use the Laravel HttpClient without installing Guzzle so I think it's safe to use it here.

**Comment by Salmondx** [comment]
Does anybody have any ideas why this change fails on php 7.2-lowest? I don't see any special requirements to php env in guzzle package, may be its some test environment misconfiguration?

**Comment by driesvints** [comment]
@Salmondx guess that function didn't exist for that guzzle version? In which version was it introduced? We might need to bump the minimum version.

**Comment by Salmondx** [comment]
@driesvints  As I can see, this function was added to `guzzle/psr7` in version 1.5.0: https://github.com/guzzle/psr7/releases/tag/1.5.0

Looks that guzzle 6.4.0 should be safe to use: https://github.com/guzzle/guzzle/blob/6.4.0/composer.json

Should I update it in `composer.json` from `"guzzlehttp/guzzle": "^6.3.1|^7.0"` to `"guzzlehttp/guzzle": "^6.4.0|^7.0"`?

**Comment by GrahamCampbell** [comment]
Please don't change the Guzzle version constraint. You need to add the PSR7 Guzzle package to the composer.json, actually.

**Comment by Salmondx** [comment]
@GrahamCampbell hm, currently guzzle dependencies are in `require-dev`. If I add explicit dependency on `guzzle/psr7` in `require-dev` section it will fix broken tests, but can affect someone in "production", don't you think?

**Comment by GrahamCampbell** [comment]
> but can affect someone in "production", don't you think?

No.

**Comment by Salmondx** [comment]
Looks that it should be good now, thanks for advises.

**Comment by taylorotwell** [comment]
So if someone has 6.3.1 of Guzzle installed this will break?

**Comment by Salmondx** [comment]
Looks like it will, but as I understand Graham thinks that it is not the problem? As I can see we should either update minimum guzzle version or copy paste code from guzzle?

**Comment by taylorotwell** [comment]
@GrahamCampbell was there a big reason you didn't want to up the constraint to 6.4.0?

**Comment by driesvints** [comment]
I don't think we can make use of that function on a stable release. Like Taylor said, people on a lower Guzzle version will see their apps break and we can't enforce them to upgrade since Guzzle isn't a dependency in "require". This will need to be done on master for 8.0

**Comment by taylorotwell** [comment]
Yeah, I think probably best to resend this to `master` branch. Sorry.

**Pull request closed without merging**
