### PR TITLE
[9.x] Use `str_contains` instead of `strpos`

### PR DESCRIPTION
**Pull request by selcukcukur**

### CODE REVIEW

**Comment by dinhquochan** [comment]
👎  this PR because Laravel 8.x required `7.3` that version does not have `str_contains()` function.

**Comment by selcukcukur** [comment]
> 👎 this PR because Laravel 8.x required `7.3` that version does not have `str_contains()` function.


It can be used with the `symfony/polyfill-php80` package. The `str_contains` method on php 7.x.

**Comment by GrahamCampbell** [comment]
This PR is not for Laravel 8. It's for Laravel 9, which is PHP 8.0.2+ only.

**Comment by dammy001** [comment]
Exactly @GrahamCampbell

**Pull request merged**
