### PR TITLE
[6.0] DomCrawler and CssSelector are actually browser-kit deps

### PR DESCRIPTION
**Pull request by crynobone**
Unless you require https://github.com/laravel/browser-kit-testing this is not needed by any developer to use the Framework.

### CODE REVIEW

**Comment by driesvints** [comment]
Can we maybe get rid of the dependencies in `require-dev` as well?

**Comment by crynobone** [comment]
@driesvints 

Should be possible, can't find any code referring both namespace.

https://github.com/laravel/framework/search?q=CssSelector&unscoped_q=CssSelector
https://github.com/laravel/framework/search?q=DomCrawler&unscoped_q=DomCrawler

**Comment by driesvints** [comment]
@crynobone I hijacked your PR 😬

**Comment by driesvints** [comment]
That's odd. It didn't re-trigger the build.

**Comment by crynobone** [comment]
> I  hijacked your PR

No problem

> That's odd. It didn't re-trigger the build.

Travis running the build at the moment <https://travis-ci.org/laravel/framework/builds/575089816>

**Review by driesvints — APPROVED** [review]

**Pull request merged**
