### PR TITLE
Fix HtmlString

### PR DESCRIPTION
**Pull request by mvdnbrk**
See #32286, #32285

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
As I said before, the constructor insists on you passing a string. If you do not pass a string, then the behaviour is formally undefined.

**Comment by GrahamCampbell** [comment]
You can use static analysis tooling to make sure you are not calling this incorrectly. Laravel does not perform a typecheck at runtime here for performance reasons.

**Comment by mvdnbrk** [comment]
@GrahamCampbell Converting to string is done in several places, ie:

https://github.com/laravel/framework/blob/ff1a13ecf09d978575148c5095b87fa66187aad6/src/Illuminate/View/ComponentAttributeBag.php#L147-L166

**Comment by GrahamCampbell** [comment]
That is totally different. That is getting the string representation of an htmlstring.

**Comment by mvdnbrk** [comment]
It is not that class implements the `Illuminate\Contracts\Support\Htmlable` contract just like `HtmlString` does and it needs to return a string in all circumstances.

**Comment by GrahamCampbell** [comment]
Only in the circumstances where it is constructed correctly. Otherwise it has undefined behaviour.

**Comment by mvdnbrk** [comment]
Secondly see this part of code of the `Illuminate\Support\Stringable` class

https://github.com/laravel/framework/blob/ff1a13ecf09d978575148c5095b87fa66187aad6/src/Illuminate/Support/Stringable.php#L25-L28

It accepts a default value of an empty string. It casts `$value` to string.

**Comment by mvdnbrk** [comment]
> Only in the circumstances where it is constructed correctly. Otherwise it has undefined behaviour.

You dont know if it is constructed correctly.
The way it is implemented now allows you ta pass in *any* value you like, a string, an intege, an object whatever.

**Comment by GrahamCampbell** [comment]
You are not allowed top pass any value. This is always the convention when code does not have type checks. The implementer trusts that you call it correctly.

**Comment by mvdnbrk** [comment]
You should have type checks in my opinion, that's another debate ;-)

**Pull request closed without merging**
