### PR TITLE
PHP Short Array Syntax

### PR DESCRIPTION
**Pull request by philsturgeon**
I thought I'd give https://github.com/thomasbachem/php-short-array-syntax-converter a try and it works incredibly well. This only took a few minutes, but hey, now Laravel is a few bytes smaller.

I don't actually really even know if this is a troll or not. I'm in too deep.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Lol, we've closed like 20 of these in the last 6 months.

**Comment by taylorotwell** [comment]
Ha that's pretty cool, maybe closer to actual release date though.

**Comment by philsturgeon** [comment]
Sweet. Give that thing a try when you're ready.

**Comment by Anahkiasen** [comment]
Doesn't PHP CS fixer already do that? With the `short_array_syntax` fixer?

**Comment by GrahamCampbell** [comment]
> Doesn't PHP CS fixer already do that? With the short_array_syntax fixer?

Yes, it does. That's not the point though.

**Comment by GrahamCampbell** [comment]
It's also possible that we might end up using https://styleci.io/.

**Pull request closed without merging**
