### PR TITLE
[5.7] Pass route to custom URL formatters

### PR DESCRIPTION
**Pull request by imbrish**
Pass route for which URL is currently generated to the custom host and path formatters.

---

This is a part of a series of pull requests simplifying localization of URLs, more details here https://github.com/laravel/framework/pull/24048.

### CODE REVIEW

**Comment by sisve** [comment]
Could you add another test case for this functionality instead of modifying the existing one?

**Comment by imbrish** [comment]
Sure thing! However it was exactly when writing tests that I discovered this issue https://github.com/laravel/framework/issues/24047. Thus I want to wait first for https://github.com/laravel/framework/pull/24051 to make it's way to 5.7, then rebase and add separate tests. Or should I add them already?

**Comment by sisve** [comment]
I'm not sure what you're asking. Are you saying that you cannot write tests until another 5.6 PR is ported to 5.7? If so, why not?

**Comment by imbrish** [comment]
Somehow I overlooked the fact, that I don't need to test for the relative route after all.

**Pull request merged**
