### PR TITLE
[5.3] Access collection items as its properties

### PR DESCRIPTION
**Pull request by gcamrit**
``` php
$collection = collect([
  'id'   => 23,
  'name' => 'Amrit'
  'age'  => 23
]);

// with this pr you can access items key as collection properties

$collection->id // 23
$collection->name // Amrit

```

### CODE REVIEW

**Comment by geshan** [comment]
+1

**Comment by mainalikishan** [comment]
+1

**Comment by yajra** [comment]
👎  I think you can just use fluent for this case.

```php
$fluent = new \Illuminate\Support\Fluent([
        'id'   => 23,
        'name' => 'Amrit',
        'age'  => 23,
    ]);

    dd($fluent->name);
```

**Comment by Amrit01** [comment]
yes you can but you can't manipulate data as collection does

**Comment by amritms** [comment]
+1

**Comment by crynobone** [comment]
What wrong with just using `$collect->get('id');`. Using the magic method would only works on some scenarios, not with numeric arrays as an example.

**Comment by rkgrep** [comment]
👎 Collections are not supposed to handle such data.

**Comment by taylorotwell** [comment]
Indeed collcetions are not supposed to serve as single object things.

**Pull request closed without merging**
