### PR TITLE
[5.1] Swap Carbon dependency for Date

### PR DESCRIPTION
**Pull request by Evertt**
Because Date does everything Carbon does, plus localization.

### CODE REVIEW

**Comment by crynobone** [comment]
Oh yes, let break everyone's project that actually directly use `Carbon` with Laravel.

**Comment by Evertt** [comment]
Whoops, yes, damn...
And how about doing this for 5.2? Or doesn't this fit in a minor release update?

**Comment by crynobone** [comment]
Made some update to the first comment. ^

Need to be with what the advantage. Doesn't feel it has any advantage, or what can't be done with Carbon exactly at the moment.

**Comment by arrilot** [comment]
I would recommend you to resend to master. There are no chances this will be merged into 5.1 from my point of view.

**Comment by Evertt** [comment]
@crynobone from the [docs](https://github.com/jenssegers/date#usage):

> Methods such as parse and createFromFormat also support "reverse translations". When calling these methods with translated input, it will try to translate it to English before passing it to DateTime:

> ```php
$date = Date::createFromFormat('D d F Y', 'zaterdag 21 maart 2015');
```

**Pull request closed without merging**
