### PR TITLE
[5.6] Added custom default host and port.

### PR DESCRIPTION
**Pull request by mcmc4519**
Added custom default host and port for php artisan serve.

### CODE REVIEW

**Comment by laurencei** [comment]
You cant use `env()` here. You need to use `config()` otherwise this will break for people using `config:cache`

**Comment by GrahamCampbell** [comment]
I don't see why we'd need this set by env?

**Comment by GrahamCampbell** [comment]
You could just alias the command?

**Comment by mcmc4519** [comment]
Yes! 
Thank you!

I close pull request.

**Pull request closed without merging**
