### PR TITLE
[7.x] Route trailing slash bug

### PR DESCRIPTION
**Pull request by driesvints**
Replaces https://github.com/laravel/framework/pull/32031

Alternative approach to cloning the request. I deliberately removed the instanceof check in the createFromBase method because otherwise this wouldn't be possible.

### CODE REVIEW

**Comment by kohlerdominik** [comment]
Hi Dries

Thanks very much for the quick addressing of this fix. We have an unfortunate additional use-case:
our route is not only `/foo/bar/`, but `/foo/bar/?param=baz`.
This worked fine before 7.x (or in 7.x without route-caching), but is still broken in this branch.

**Comment by driesvints** [comment]
@kohlerdominik that request perfectly works for me in 7.x

**Comment by driesvints** [comment]
@kohlerdominik pushed a commit that'll fix this.

**Comment by kohlerdominik** [comment]
Yes, works now perfect for me. Very much appreciate your work. 
Looking forward for this to be released (our production environment is currently online without route caching :( )

**Comment by driesvints** [comment]
@kohlerdominik should be tagged now

**Pull request merged**
