### PR TITLE
[5.4] Helper function: now

### PR DESCRIPTION
**Pull request by jbruni**
Get Carbon instance for current date/time.

### CODE REVIEW

**Comment by jbruni** [comment]
Nothing special. It's just that I've been using this in so many projects...

**Comment by m1guelpf** [comment]
@jbruni Taylor normally doesn't like helpers not used in the framework, but I have a feeling with this :wink:

**Comment by devcircus** [comment]
See #19984

**Comment by jbruni** [comment]
Hmmm... how interesting... the very same suggestion, only 12 days before. I haven't seen it before (sorry). The guy there took the time and chose nice words to justify the PR.

No problem. I do create my own helper functions file with specific helpers, related to the project.

I just came here and posted the PR because, as I said, I've been adding and using this simple/handy `now()` function in all projects since some time ago.

It looks like I am not the only one!

**Comment by jbruni** [comment]
Nice to see that it has been added:
- https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/helpers.php#L587-L598
- https://laravel.com/docs/5.5/helpers#method-now

**Pull request closed without merging**
