### PR TITLE
[5.1] key:generate command: support spaces around "=" in .env file

### PR DESCRIPTION
**Pull request by vlakoff**
- Improves handling in case user have formatted their `.env` file.
- Adds support for https://github.com/laravel/laravel/pull/3490.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by vlakoff** [comment]
Would you reconsider this if bundled with some tests for this command? Currently there are none…

**Comment by GrahamCampbell** [comment]
It's not up to me - that's why I've not closed it. I'm just giving my opinion.

Taylor will consider this in due course.

**Comment by GrahamCampbell** [comment]
I'd say don't write any tests until Taylor gives the goahead, if he does.

**Comment by vlakoff** [comment]
Ah… I was just going to also suggest this:

Provide feedback if there is a .env file but for any reason the replacement in it didn't occur. Currently the console would print "Application key set successfully.", which is wrong I think.

**Comment by vlakoff** [comment]
@taylorotwell 

I'd really like to see this implemented, as I think it's a useful yet simple change.

If I make changes so that the command is testable (currently it's not) and rock-solid, would you reconsider your position? As stated in my comment above, if the replace fails it still displays a success message…

**Pull request closed without merging**
