### PR TITLE
[5.2] Switched to symfony 3.0

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Do things seem to work I guess?

**Comment by GrahamCampbell** [comment]
I've had no issues so far, and all our tests pass. :)

**Comment by GrahamCampbell** [comment]
We've still got time to fix anything that comes up. Anyway, both symfony 2.8 and 3.0 are still moving targets atm. :)

**Comment by stof** [comment]
Why not allowing both 2.8 and 3.0 at the same time ? This should work fine (as all new APIs are introduced in 2.8), and would allow to use libraries depending on a Symfony 2.x API.

**Comment by barryvdh** [comment]
If that's true, it would probably be a lot easier to upgrade, due to not all packages being updated yet..

**Comment by GrahamCampbell** [comment]
The idea was to have 5.2 make a hard break. 5.1 is there for that purpose. It's LTS.

**Comment by stof** [comment]
@GrahamCampbell this means that you require all PHP libraries to switch to Symfony 3.0 APIs to be usable with Laravel, even if your code is actually compatible with 2.8.
See https://github.com/tijsverkoyen/CssToInlineStyles/issues/107 for such an issue being opened on a library which has nothing to do with Laravel because of this change (even though supporting Symfony 3.0 in this library is actually a good idea of course).
This change means it makes the upgrade to Laravel 5.2 harder than necessary (unless you don't depend on other libraries using Symfony components of course).
Even Symfony 3.0 components are allowing 2.8 versions of other components

**Comment by GrahamCampbell** [comment]
Yes, we do require upgrading to 3.x. If you don't want to, that's fine, use L5.1.

**Comment by GrahamCampbell** [comment]
Unlocking, but note that our issues are NOT for communication with Taylor. They are only there for the community to discuss bugs with each other - see the contribution guide lines.

**Comment by taylorotwell** [comment]
So 3.0 is totally compatible with 2.8? I guess 3.1 will be the first break with 2.x?

**Comment by GrahamCampbell** [comment]
Yes and no. 3.0 was where all the breaks happened, but 2.8 was meant to get any non breaking new stuff that 3.0 got.

**Comment by barryvdh** [comment]
If I understand correctly, all new features are introduced in 2.8. 3.0 just removes the BC layer for all the deprecated stuff. http://symfony.com/blog/transition-from-symfony-2-7-to-3-0-symfony-2-8-on-its-way

**Comment by stof** [comment]
3.0 is compatible with a project running on Symfony 2.8 without using any of the deprecated APIs. The breaks between 2.x and 3.0 are that all BC layers are gone.

this means that code compatible with 3.0 is compatible with 2.8, but the opposite is not always true.

**Comment by taylorotwell** [comment]
So, as one of the maintainers of Symfony, your suggestion is for us to allow both 2.8 and 3.0 with Laravel 5.2?

**Comment by stof** [comment]
yes, it is.

And my recommendation would also be to allow ``~2.7`` rather than ``2.7.*`` in 5.1, so that people wanting to use a new feature added in 2.8 will be able to do it. Our BC policy means that your code written for 2.7 will work for 2.8 too (some APIs may be deprecated, but they will continue working until 3.0). And if something breaks, it will be considered as a regression and fixed quickly (but regression are as likely to happen in 2.8.0 than in 2.7.next, as they are mistakes in both cases)

**Comment by taylorotwell** [comment]
OK Let's allow 3.0 and 2.8 on 5.2. then.

**Comment by stof** [comment]
The exception to this rule is the case where you use an API tagged as ``@internal`` yourselves btw. But for this case, even ``2.7.*`` is unsafe, as we do not guarantee any BC for APIs we declared as being purely internal (and if you have such usage, there is a strong need to stop using it).

**Pull request merged**
