### PR TITLE
[5.2] Add --no-timestamps and --soft-deletes options to make:migration and make:model Artisan command

### PR DESCRIPTION
**Pull request by yappkahowe**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What's the use case for this?

**Comment by charlesyapp** [comment]
It is for convenience purpose. Save some time and effort from adding $table->softDeletes(), removing $table->timestamps(), adding SoftDeletes trait, and setting date mutators.

**Comment by GrahamCampbell** [comment]
I was meaning what's the use case of actually needing those?

**Comment by charlesyapp** [comment]
Most of the time I use `make:model -m` to create models and migrations so that for every model created, I am sure there is a migration file for that model. But then I have to manually remove `$table->timestamps()` and add `$table->softDeletes()` in some of the migrations created. Then I need to add `$timestamps = false` and `use SoftDeletes` trait to the respective models. This becomes problematic when I have many models and migrations in my project. I might have added soft-deletes in some migrations, but missed to add `SoftDeletes` trait to their models. 

So this PR allows me to type a command e.g. `php artisan make:model User -m --no-timestamps --soft-deletes` to create a User model with `SoftDeletes` trait and `$timestamps = false`, and a create_users_table migration file with `$table->softDeletes()` without `$table->timestamps()`.

**Comment by JosephSilber** [comment]
Is it really that hard to manually edit the migrations file to your liking?

**Comment by charlesyapp** [comment]
It is not that hard but manually edit them creates possibility of inconsistencies. If I have 50 tables to create, then I have to edit up to 100 files, then cross-check the 100 files again for consistencies. If I missed one of them and only realize in later stage of development, I have to go back and fix it again. It is tedious, error-prone, and time-consuming.

**Comment by taylorotwell** [comment]
No plans on adding this at the current time.

**Pull request closed without merging**
