### PR TITLE
[5.8] Unit tests - Fix caching user on request when request changes

### PR DESCRIPTION
**Pull request by joelharkes**
Removes cached user when request changes (fixes unit test with global application using different users).

---
Currently you cannot call 2 api calls in 1 unit test with different user authentication. because the user gets cached globally and not refreshed with a new api call.

This problem also exists when you globalize the createApplication process. (for performance/memory issues)

I targeted the problem to a very simple solution (see changes).

### CODE REVIEW

**Comment by mfn** [comment]
Would be nice a test is included to show off that .. well, the tests work 🤷‍♀️

No production side-effects due to this? Just asking because this is code not related to tests.

**Comment by shadoWalker89** [comment]
@taylorotwell Could this be added in 5.7 as well ? cuz it's still a little bit of time until 5.8 is out

**Comment by joelharkes** [comment]
@shadoWalker89 the fix is relative simple to add to your project by subclassing: `PassportServiceProvider` and using this one instead in your kernel.

```
<?php

use Illuminate\Support\Facades\Auth;

class FixedPassportServiceProvider extends Laravel\Passport\PassportServiceProvider
{
    protected function makeGuard(array $config)
    {
        return new RequestGuard(function ($request) use ($config) {
            return (new Laravel\Passport\Guards\TokenGuard(
                $this->app->make(League\OAuth2\Server\ResourceServer::class),
                Auth::createUserProvider($config['provider']),
                $this->app->make(Laravel\Passport\TokenRepository::class),
                $this->app->make(Laravel\Passport\ClientRepository::class),
                $this->app->make('encrypter')
            ))->user($request);
        }, $this->app['request']);
    }
}

class RequestGuard extends \Illuminate\Auth\RequestGuard
{
    public function setRequest(Illuminate\Http\Request $request)
    {
        if ($this->request !== $request) {
            $this->user = null; // disgusting fix to make unit tests work with single application.
        }
        $this->request = $request;

        return $this;
    }
}

```

**Comment by joelharkes** [comment]
@mfn im relative new to laravel (love digging in source code). i could see if i can make some test later. 

Currently my work flow is to change the framework code locally in the vendors folder, to test, then send a PR here, than make an overwrite function/class to fix it in my code.

ill see if I can make some time to add my contributions properly. 

some functionality i added locally is:
* Make the factory class also be able to create any kind of classes (not just eloquent classes).
* Allow * for scopes in client authentication and also return allowed scopes in http response.

**Comment by shadoWalker89** [comment]
@joelharkes I'm not using passeport :D

**Comment by mnabialek** [comment]
Just in case it seems to be reverted - https://github.com/laravel/framework/commit/970c9ed70b053aec7d69487a825577ed6f0329d1

**Comment by joelharkes** [comment]
@taylorotwel your commit is not descriptive at all... What did it break?

**Pull request merged**
