### PR TITLE
[5.6] Remove JsonSerializable implementation now implemented in Carbon

### PR DESCRIPTION
**Pull request by kylekatarnls**
- As it's a strict duplicate the JsonSerializable can be removed safely.
- The "1.25.*" change need to be reverted as it prevent users for getting new methods, will conflicted with custom requirement (such as `"nesbot/carbon": "dev-master"`) and users will think they get the last 1.x version and will wrongly rely on the documentation, but it will not be accurate for them.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Doesn't this still leave the macroable problem?

**Comment by kylekatarnls** [comment]
Carbon\Carbon^1.26.2 has no conflict with Illuminate\Support\Carbon as we simply changed the variable name, so and in this PR the `use Macroable;` is kept untouched. So Laravel macros methods replace Carbon macros methods and recorded macros are separated.

**Comment by 36864** [comment]
Why are we forcing ^1.26.4 when the conflict was resolved in ^1.26.2?

Could we just revert this to (^1.24.2) and add "!=1.26.0 !=1.26.1" to avoid the incompatible versions?

**Comment by kylekatarnls** [comment]
Thanks @36864 it is perfectly relevant, I will fix that.

**Comment by kylekatarnls** [comment]
@taylorotwell if you need more time to consider this change, can I submit the composer version upgrade alone. Users are still locked in 1.25 for the moment.

**Comment by GrahamCampbell** [comment]
> Users are still locked in 1.25 for the moment.

I think that's fine. What's the rush to upgrade?

**Comment by kylekatarnls** [comment]
Meanwhile, the new features present in the documentation miss. And because of situations like this one: https://github.com/laravel/framework/issues/23893#issuecomment-383719046

Also to mention: when 5.6.17 was released, 1.26.2 was yet released too and fixed the conflict. Users who updated between both can now work with laravel 5.6.16 and carbon 1.26.2 and can now use 1.26+ methods and on next update, Carbon will downgrade to 1.25 and their code will break with some method not found exceptions.

That's why when if there is no special rush, it could be bad to wait too long.

**Comment by GrahamCampbell** [comment]
> So there is no special rush but it could be bad to wait too long.

Would it? Carbon 1.25 seems pretty stable. I don't see a good reason for Laravel 5.5 and 5.6 to just stick on 1.25, and Laravel 5.7 to pin to the the latest minor release available at time of release.

**Comment by kylekatarnls** [comment]
Stability is not the point. What I explained was:

5.6.16 allowed 1.24.2 to 1.26.2 (minimal requirement to last release before 5.6.17)
5.6.17 cause either a Carbon upgrade (not a problem) either a downgrade (force 1.26.2 to downgrade to 1.25) and this is bad because users can still have used 1.26 features, so the update will work for them but it will break their code.
(5.7 is not a concern, it's only related to 5.6.)

And users will expect to have the last Carbon version and will rely to the documentation but even if they run `composer update`, they won't get the last version. I think they won't figure out why.

Last, if users want to use new features, they need to hack composer dependencies (https://github.com/laravel/framework/issues/23893#issuecomment-383719046) and those kind of hack are not a long term solution.

5.5 and 5.7 are both ^1.24, why 5.6 would be the lonely version to enforce 1.25 ?

I can add, 1.x releases will slow down in favor 2.x efforts. Macros and JSON won't be changed again in 1.x, the purpose of these changes was to align Carbon on Illuminate\Support\Carbon, avoiding the override need in Laravel and so provide a complete documentation accurate for Laravel users too ; this goal was reached in 1.26.2. That's one more reason why forcing an outdated version of Carbon seems a terrible idea to me.

**Comment by nbolender** [comment]
@GrahamCampbell Just yesterday I was referring to the Carbon docs while working on my Laravel 5.6.16 project and used some of the functionality introduced in Carbon 1.26 (setToDate()).

I ran composer update and suddenly that method was not available because of the new Carbon version pinning.

If the incompatibilities can be resolved quickly, I think it would be best to do so to avoid user confusion.

**Comment by taylorotwell** [comment]
I'm not touching anything Carbon related for 5.6 branch. Also changes would need to be discussed for 5.7 (master) branch.

**Comment by kylekatarnls** [comment]
@taylorotwell But you do not provide any solution as alternative. Do you have a chat place to discuss further?

**Pull request closed without merging**
