### PR TITLE
[5.4] Convert zRangeByScore syntax for PhpRedis

### PR DESCRIPTION
**Pull request by tillkruss**
This converts Predis':
```php
['WITHSCORES' => true, 'LIMIT' => [$offset, $count]
```

To PhpRedis:

```php
['withscores' => true, 'limit' => [$offset, $count]
```

### CODE REVIEW

**Comment by nrk** [comment]
Just a related note: Predis doesn't really care about which casing style is used for command modifiers keywords as it [converts them to uppercase internally](https://github.com/nrk/predis/blob/v1.1.1/src/Command/ZSetRangeByScore.php#L34), so you can pass them as `WITHSCORES` or `withscores` or even `WiThScORES` and it won't make any difference. The use of uppercase-by-default in Predis, in docs or code, is just for consistency with the Redis documentation.

**Comment by tillkruss** [comment]
@nrk: Yeah, we use Predis as the standard and just make sure the syntax is converted when PhpRedis is used. What would really help us is a full documentation of all Predis methods and their supported signatures. I noticed that some methods can be called in 2-3 different ways.

**Comment by taylorotwell** [comment]
Do we actually need this if the case doesn't matter?

**Comment by tillkruss** [comment]
Yes, Predis doesn't care, PhpRedis does 😐

**Comment by nrk** [comment]
@tillkruss having proper documentation for Predis would be awesome but unfortunately I don't have enough free time for it and nobody seems motivated enough to submit contributions in this area. I know the test suite shouldn't really be used as a reference, but test units for each command cover all of their supported signatures.

**Comment by tillkruss** [comment]
@nrk: Okay, thanks, I'll have a look!

**Pull request merged**
