### PR TITLE
[5.3] Target Current PHP Releases

### PR DESCRIPTION
**Pull request by GrahamCampbell**
When Laravel 5.3 ships, PHP 5.5 will be EOL.

### CODE REVIEW

**Comment by vlakoff** [comment]
I know this request is likely to be rejected, but please reconsider this. Many hosting providers just don't offer PHP 5.6. It's a shame, but it's what it is. Other people are just getting tired having to migrate everything every six months.

If Laravel doesn't require PHP 5.6, don't require it for the sake of requiring it.
There are breaches in older PHP versions? It's not your responsibility, let the user assume it.

**Comment by GrahamCampbell** [comment]
By doing this we're pressuring them to upgrade. The minimum version anyone should be using today is PHP 5.6. It's unacceptable not to support it.

However, if you do really want PHP 5.5, you can still use Laravel 5.1 LTS.

We also plan to bump again to PHP 7.0 as soon as 2 more releases down the line.

**Comment by vlakoff** [comment]
Real question: is it your responsibility to tell people what PHP version they have to use?

**Comment by GrahamCampbell** [comment]
> Real question: is it your responsibility to tell people what PHP version they have to use?

Yes.

**Comment by GrahamCampbell** [comment]
We're not bumping it for a laugh. We're actually using PHP 5.6 features in Laravel 5.3, and we don't want to support PHP versions that are EOL. PHP 5.5 will be EOL when L5.3 ships.

**Comment by vlakoff** [comment]
If I want to pee without holding it and splash everywhere, I don't want anyone to forbid me doing it because it's bad for me (and my bathroom), because this is FREEDOM.

**Comment by vlakoff** [comment]
Pun apart, could you please point to parts which are requiring PHP 5.6?

**Comment by GrahamCampbell** [comment]
With respect, we have the right to do what we want, just like very other PHP project out there, and if we want to start using new stuff, we will.

**Comment by GrahamCampbell** [comment]
There's nothing to discuss here. We're not rolling back all the changes.

**Pull request merged**
