### PR TITLE
[11.x] Use qualify class method

### PR DESCRIPTION
**Pull request by iamgergo**
This is a followup of #52924. There is already a dedicated method to create FQCN.

### CODE REVIEW

**Comment by iamgergo** [comment]
It looks some composer dependecies cannot be downloaded for the tests.

**Comment by szepeviktor** [comment]
> There is already a dedicated method to create FQCN.

Will it insert `Exceptions\` into the FQCN?

**Comment by iamgergo** [comment]
Yes.

**Comment by taylorotwell** [comment]
I don't want to change anything if it's not broken. 👍

**Pull request closed without merging**
