### PR TITLE
[11.x] feat: introduce perWeek and perMonth Limit option

### PR DESCRIPTION
**Pull request by sts-ryan-holton**
Hi :wave:

This is my first PR submission to the Laravel community :rocket:

Recently in a project I've found myself needing a "weeks" and "months" option for the rate limiting options. I've got quite s specific use case here for this and so found that Laravel offers `perMinute`, day, etc. I suggested in a recent [discussion](https://github.com/laravel/framework/discussions/53001#discussioncomment-10808568) which suggested to open a PR for this, so here we go!

The `perWeek` implementation here is pretty straightforward, but I appriciate some users may want some configuration over the `perMonth` option.

I've retained backwards compatible function args here so it's familiar for people!

Hoping someone can help me get this merged as I think it's quite low risk!

### CODE REVIEW

**Comment by taylorotwell** [comment]
How did you land on the days in month value?

**Comment by taylorotwell** [comment]
The month one feels a bit weak to me. Not sure I'm going to merge this one atm.

**Comment by henzeb** [comment]
I agree with Taylor here. I suggest creating a PR instead that allows people to add Macros to Limit and/or RateLimiter using Macroable.

**Comment by sts-ryan-holton** [comment]
@taylorotwell Would you be open to me adding a new PR with just the `perWeek` option?

**Pull request closed without merging**
