### PR TITLE
support 'deleting' event

### PR DESCRIPTION
**Pull request by terranc**
example:

```php
	public static function boot()
    {
        parent::boot();
        static::deleting(function ($model) {
                $model->deleted_by = Auth::id();
        });
    }
```

### CODE REVIEW

**Comment by ludo237** [comment]
I don't get this, the `Deleting` event exists in Eloquent Events Pool

**Comment by terranc** [comment]
Sorry, This is for soft delete

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Comment by terranc** [comment]
OK,Thanks!

**Pull request closed without merging**
