### PR TITLE
[9.x] Use array_key_first

### PR DESCRIPTION
**Pull request by iamgergo**
Since PHP 7.3 there is a native function for retreiving the first key of the given array: https://www.php.net/manual/en/function.array-key-first.php

So a small refactoring can be done here. The behavior is exactly the same, actually the polyfill for this function is the current implementation.

Related PRs: #35147 and #32550. 

I don't think this has any feelable affect on the performance in real Laravel applications, as it was discussed. My point of view is just, why not to use native stuff where we can.

### CODE REVIEW

**Comment by iamgergo** [comment]
The tests were failing (not only here, for the PRs submetted before this one as well). The reason was because the tests were not checking for the default `timeout => 30` option, also the `assertSame` is sensitive for the keys I belive, so I've updated the order as well, just to make the tests passing.

**Comment by crynobone** [comment]
> The tests were failing (not only here, for the PRs submetted before this one as well)

Probably should create a separate PR for that?

**Comment by iamgergo** [comment]
I thought about that, but since this is a very small change, I thought it's okay.

Let me know if I still should submit a separate PR.

**Comment by iamgergo** [comment]
I created a separate PR for the tests, since this PR might not be merged. https://github.com/laravel/framework/pull/40995

**Comment by alecpl** [comment]
firstCredentialKey() method should probably be removed as it is used in one place only.

**Comment by iamgergo** [comment]
I think it can be useful, if I want to extend the class and override that method. I would not remove it, however it's true, it's used only once.

**Comment by driesvints** [comment]
Hi, I've fixed the tests on 9.x so please rebase your PR and mark your PR as ready when tests pass. Thanks

**Pull request merged**
