### PR TITLE
[9.x] Stay consistant and use collect()

### PR DESCRIPTION
**Pull request by lucasmichot**
Stay consistant and use `collect()` instead of `Collection::make` and `new Collection`

### CODE REVIEW

**Comment by lucasmichot** [comment]
Seems like a flaky test : https://github.com/laravel/framework/runs/5055118245?check_suite_focus=true

**Comment by rodrigopedra** [comment]
Missing spots:

## `new Collection`

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Database/Eloquent/Factories/Factory.php#L132-L136

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Database/Eloquent/Casts/AsEncryptedCollection.php#L25

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Database/Eloquent/Casts/AsCollection.php#L23

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Database/Eloquent/Model.php#L1436

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Database/Concerns/ExplainsQueries.php#L22

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Collections/Traits/EnumeratesValues.php#L243

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Collections/Traits/EnumeratesValues.php#L858

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Collections/LazyCollection.php#L1248

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Collections/LazyCollection.php#L1260

## `Collection::make(...)`

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Database/Query/Builder.php#L2353

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Database/Migrations/Migrator.php#L126

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Database/Migrations/Migrator.php#L508

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Database/Eloquent/Relations/MorphTo.php#L90

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Database/Concerns/BuildsQueries.php#L72

https://github.com/laravel/framework/blob/2667e69aee70c114e6e465b3ffcff329935eccd9/src/Illuminate/Collections/LazyCollection.php#L1518

**Comment by driesvints** [comment]
I don't think we should rely on a helper and should use the actual class instead.

**Comment by GrahamCampbell** [comment]
> I don't think we should rely on a helper and should use the actual class instead.

Agreed.

**Comment by rodrigopedra** [comment]
On one hand I agree with @driesvints , I prefer relying on the actual class, specially as it is not long to type.

On the other hand I agree with @lucasmichot  that there should be consistency. But there are 200+ spots where the `collect(...)` helper is used, so it would be a bigger change.

**Comment by GrahamCampbell** [comment]
We could do nothing, also.

**Pull request closed without merging**
