### PR TITLE
[11.x] Ability to generate URL's with query params

### PR DESCRIPTION
**Pull request by stevebauman**
This PR adds the ability to generate URL's with query parameters via a new `query()` method on the `UrlGenerator`.

Currently, URLs cannot be generated with query parameters using the `UrlGenerator`.

Example:

```php
// http://localhost/products?sort=-name
url()->query('products', ['sort' => '-name']);

// http://localhost/products?columns[0]=name&columns[1]=price&columns[2]=quantity
url()->query('products', ['columns' => ['name', 'price', 'quantity']]);
```

Existing query parameters in the given path may also be overridden:

```php
// http://localhost/products?sort=-price
url()->query('products?sort=-name', ['sort' => '-price']);
```

They may also be appended onto:

```php
// http://localhost/products?sort=-name&search=samsung
url()->query('products?sort=-name', ['search' => 'samsung']);
```

### CODE REVIEW

**Comment by mrShibli** [comment]
where I write it? in model or blade file or controller or route??? where??? give me a example

**Comment by onlime** [comment]
@mrShibli 
> where I write it? in model or blade file or controller or route??? where??? give me a example

everywhere! That's what such helpers like [`url()`](https://laravel.com/docs/11.x/helpers#method-url) are for, to be used in a controller, in a middleware, in blade, in wherever you wish.
You can also use `url('https://example.com/foo?some=name')->query('', ['search' => 'bar'])` to merge query params into an existing URL with/without query params. Look at the `RoutingUrlGeneratorTest` examples in this PR!

**Comment by taylorotwell** [comment]
@stevebauman could you send a laravel/docs PR for this one?

**Comment by stevebauman** [comment]
@taylorotwell Yea absolutely!

**Pull request merged**
