### PR TITLE
Exists property is set to false on soft deleted eloquent model

### PR DESCRIPTION
**Pull request by HolgerW1**
If you soft delete a model the property _exists_ is set to false which may lead to problems.

Try the following code as a test:

```
$model->delete();
$model->forceDelete();
```

Surprisingly the model won't be hard deleted because the first _delete_ call will set the _exists_ property to _false_ thus the second call of _forceDelete_ won't perform anything and the model remains in the DB.

Soft deleting a model should prevent setting the _exists_ property to _false_ because otherwise the model object is in an inconsistent state and any logic relying on this property to check if a model was deleted will fail.

### CODE REVIEW

**Comment by HolgerW1** [comment]
Dunno why the pull request went haywire. Please close it.

**Comment by HolgerW1** [comment]
Actual patch can be found here 77f8b4d8e72cc1a630b00dedb4d7b7472f9bb49c, feel free to open a new pull request if you're interested.

**Comment by GrahamCampbell** [comment]
Can you re-open at 5.1 please @HolgerW1.

**Comment by GrahamCampbell** [comment]
You sent to 5.0 instead of 5.1.

**Comment by HolgerW1** [comment]
I see, sorry for the mess. Don't know why hub used 5.0 as a base instead of 5.1, never had the 5.0 branch active.
New pull request added #9806, please rename it to whatever fits best.

**Pull request closed without merging**
