### PR TITLE
[10.x] Ignore MSSQL exception about PDO::ATTR_STRINGIFY_FETCHES

### LINKED ISSUE #47937: laravel PDO invalid attribute exception with PHP 8.2.9/8.1.22
### Laravel Version

10.17

### PHP Version

8.2.9

### Database Driver & Version

php_pdo_sqlsrv_82_ts_x64 5.11, Microsoft sql server 2019

### Description

PHP just released a new minor version 8.1.22 / 8.2.9.
There are some changes related to PDO.

My applications work fine with php 8 early minor versions.

With 8.1.22 (laravel 9.*) /8.2.9 (laravel 10.*), have a connection to a ms sql server 2019, with official MS pdo driver,

I got
`
Illuminate \ Database \ QueryException
SQLSTATE[IMSSP]: An invalid attribute was designated on the PDO object.
`

for any queries in laravel.

I have also tested with raw php, pdo seems working fine.

### Steps To Reproduce

- with php 8.1.22/8.2.9 and Microsoft pdo driver, either windows or linux, 
- connecting to a Microsoft sql server
- do a query in laravel.

### PR DESCRIPTION
**Pull request by tonysm**
### Fixed

- Ignores the MSSQL exception about `PDO::ATTR_STRINGIFY_FETCHES`. Something changed in the extension and this attribute now triggers an exception. This wasn't the case before, so I think we can ignore the exception when setting that attribute until there's a release/hotfix.

---

Here's the [comment](https://github.com/laravel/framework/pull/48144#issuecomment-1690199914) I left in another PR for context:

> I found [this reference from Drupal](https://www.drupal.org/project/sqlsrv/issues/3379887), where they are using a try/catch when setting the PDO attributes. It looks like something changed in the SQL Server extension. Some other references from https://github.com/php/php-src/issues/11587 and a https://github.com/laravel/framework/issues/47937. A PR was merged already in the https://github.com/microsoft/msphpsql/pull/1468, but I still see the issue. It looks like they are arranging a https://github.com/microsoft/msphpsql/pull/1468#issuecomment-1683158076. In the meantime, the solution described in the package referenced in https://github.com/microsoft/msphpsql/pull/1468#issuecomment-1688901365 seems to be similar to what the Drupal folks did.

An alternative solution would be to remove that attribute from the list of `$options` in the `SqlServerConnector` class.

Hat tip to @SakiTakamachi for the [implementation here](https://github.com/SakiTakamachi/laravel-sqlsrv-err-avoid).

### CODE REVIEW

**Comment by tonysm** [comment]
I just noticed there's a [draft PR](https://github.com/laravel/framework/pull/48157) from @crynobone to ignore the MSSQL suite temporarily. That might be a better approach than changing the connector code here...

**Comment by crynobone** [comment]
It better to let @taylorotwell decide on this. The pros and cons with both solutions

**Comment by taylorotwell** [comment]
Can someone explain the pros / cons? 😅 Mark as ready for review when done.

**Comment by SakiTakamachi** [comment]
Hi.

I'm probably one of the most knowledgeable on this subject.

First, let me explain how this issue came about.

Last month I made a modification in php-src, including PDO Core, to fix mysql behavior.

As for the C language, the change was to pass the `PDO::ATTR_STRINGIFY_FETCHES` setting to the `set_attr()` of the PDO drivers from Core.

The PDO driver just returns false on failure of `set_attr()`, such as when an unsupported attribute is passed, so this shouldn't be a problem.

However, only PDO SQLSRV, managed outside of php-src, was implemented with its own design that instead throws an exception when it should return false.

Of the 16 PDO drivers provided by PECL, only SQLSRV causes problems.

I submitted a monchy patch to PDO SQLSRV and it was merged into the development branch.

But the PDO SQLSRV lead didn't want to solve this problem on the PDO SQLSRV side.

We are currently urging Microsoft to release the hotfix as soon as possible, but the lead has not yet responded and there is no change in the situation.

**Comment by SakiTakamachi** [comment]
Now let's talk technically about the problem.

The error is on the driver side of SQLSRV.

After the PDO core accepts the attribute value, it passes it to the SQLSRV driver. The SQLSRV driver should have returned false, but it throws an error.

This error is triggered by receiving an unsupported attribute value, so you can safely ignore it by swallowing it with a try catch.

Alternatively, you can set PDO's error mode to silent mode just before calling `set_attribute()`, and change it back after calling one.

**Comment by tonysm** [comment]
Thanks for the context @SakiTakamachi. Marking this as ready for review so @taylorotwell can check it again.

**Comment by SakiTakamachi** [comment]
For your reference.

Changes of PDO Core:
https://github.com/php/php-src/blob/3e0e7e3f9016e9c09c484cf7050a960be20da860/ext/pdo/pdo_dbh.c#L799

Where the exception occurs in PDO SQLSRV:
https://github.com/microsoft/msphpsql/blob/f6f76d4ac116411b6c53ce482c16da73a0652292/source/pdo_sqlsrv/pdo_dbh.cpp#L1367

At first glance, it looks like the exception is caught, but actually this code is executed before that and the exception is raised:
https://github.com/microsoft/msphpsql/blob/f6f76d4ac116411b6c53ce482c16da73a0652292/source/pdo_sqlsrv/pdo_util.cpp#L519

**Comment by SakiTakamachi** [comment]
Originally, I planned to submit a PR to Laravel for the contents of this Laravel library.

https://github.com/SakiTakamachi/laravel-sqlsrv-err-avoid

However, since the content is nothing more than a temporary adhesive bandage, there is a history of providing it as a library.

**Comment by SakiTakamachi** [comment]
I wrote a lot of long sentences, but that's it.

**Comment by tonysm** [comment]
@SakiTakamachi when the MSSQL PDO driver releases the hotfix, we should be able to remove the changes here, no? Or do you mean we may need to keep the changes if we want to support the affected versions of `pdo_sqlsrv`? Not sure if it's worth keeping it. Either way, even if we keep it, it won't break anything.

**Comment by SakiTakamachi** [comment]
If there is a third option, it is to provide functions like my library as a separate repository/package like `laravel-sail`.
If it is a Laravel official package, it will be easy to incorporate it into composer's dependencies.
And I think it's easier to convey that it's a band-aid rather than modifying the main body.

However, I don't know much about Laravel's policy, so I'm sorry if this is an irrelevant suggestion.

**Comment by tonysm** [comment]
Yeah, I understand what you mean. I don't usually add external packages to fix core issues. In this case, the problem is at the extension level, which is odd. I don't think we should merge this anymore. At this point, I'd recommend folks patching their apps internally until the fix is released at the extension. The `mssql` integration suite has been disabled for now already, so we should be able to bring it back when the fix is released.

I am closing this PR for now. But feel free to re-open it and merge if y'all think it's worth it.

**Comment by SakiTakamachi** [comment]
Hi.

I would like to inform you that a hotfix has been released!

**Comment by tonysm** [comment]
@SakiTakamachi Thank you for the heads up. Not sure why, but the tests are still failing. Maybe the GitHub action doesn't have the hotfix yet? https://github.com/laravel/framework/pull/48343

**Comment by SakiTakamachi** [comment]
@tonysm 

Looking at the execution log of github actions, it seems that it's using PDO SQLSRV `5.10.1`.

The one it should use is `5.11.1`.

The `setup-php` definition may be outdated.

**Comment by GrahamCampbell** [comment]
https://github.com/shivammathur/setup-php/pull/766 should fix that.

**Comment by GrahamCampbell** [comment]
setup-php v2.26.0 now loads the latests version of the extension on supported PHP versions.

**Pull request closed without merging**
