### PR TITLE
[9.x] fix paginator footer text

### PR DESCRIPTION
**Pull request by mertasan**
Edit: I created a new PR. #37540

### CODE REVIEW

**Comment by jrmajor** [comment]
Wouldn't it be a breaking change for existing applications which don't publish pagination view?

**Comment by driesvints** [comment]
This is indeed a breaking change. Probably best to send this to master.

**Comment by mertasan** [comment]
@driesvints @jrmajor 
Yes you are right. I thought about it and couldn't find a way. I changed the target to master.

**Comment by mertasan** [comment]
@driesvints  @jrmajor  I created a new PR because the file history changed when I changed the target branch. #37540

**Pull request closed without merging**
