### PR TITLE
[5.8] allowing injecting method result into Blade

### PR DESCRIPTION
**Pull request by browner12**
currently we can inject a class into blade with

```php
@inject('metrics', 'App\Services\MetricsService')
```

this change allows us to inject the result of a method from that class

```php
@inject('metrics', 'App\Services\MetricsService@monthlyRevenue')
```

please **do not** merge yet.  needs tests.  looking for some feedback.

### CODE REVIEW

**Comment by ManojKiranA** [comment]
its looks cool but you can change your blade directive to more specific such as

 `@injectMethod('metrics', 'App\Services\MetricsService@monthlyRevenue')`

**Comment by browner12** [comment]
hmm... it doesn't seem worth adding an entire other Blade directive for this.

**Comment by X-Coder264** [comment]
The `inject` directive is IMO a big code smell which nobody should use (there should be no calls to services inside the views/presentation layer, all needed data should already be passed from the controller/view composer/whatever renders the view) and if it were up to me I'd delete it from the framework so I'm against a similar new directive being added in.

**Comment by mfn** [comment]
Same as @X-Coder264

**Comment by browner12** [comment]
I agree, we should not add a new directive for this. But this is a PR to edit the current one, so let's discuss that.

However, removing the `@inject` directive is another discussion.  You guys who don't like it (and I would tend to agree) how do you solve this then? View composers?

**Comment by taylorotwell** [comment]
I'll probably hold off on this for now. People aren't ready for it. 😆

**Pull request closed without merging**
