### PR TITLE
[5.0] Fix Windows path for nested config folders

### PR DESCRIPTION
**Pull request by RomainLanz**
Fix 9aed416700bc8e9082e8fb17c4a2b1579d3c3942

Thanks to @portonefive

### CODE REVIEW

**Comment by uibar** [comment]
Thank you.

**Comment by taylorotwell** [comment]
Sigh this broke Laravel entirely.

**Comment by taylorotwell** [comment]
Reverted since this literally broke the entire framework.

**Comment by ValsiS** [comment]
ty , in 5.0.10 :) it works fine

**Comment by RomainLanz** [comment]
Mmmmh strange. So there are still a bug elsewhere.

https://github.com/laravel/framework/issues/7629

https://laracasts.com/discuss/channels/general-discussion/laravel-5-composer-update-error-on-fresh-installation

https://laracasts.com/discuss/channels/general-discussion/l5-date-default-timezone-error-on-clear-compiled

**Comment by taylorotwell** [comment]
That bug is unrelated.

**Comment by RomainLanz** [comment]
Same again here https://laracasts.com/discuss/channels/general-discussion/problem-with-installation-laravel5

**Comment by taylorotwell** [comment]
Yeah, it's broken on Windows. You can stop posting links. I don't have a Windows machine can't help you. You're fix broke it on Linux.

**Comment by taylorotwell** [comment]
I'll probably just rip out this feature entirely unless someone is able to get a fix soon.

**Comment by RomainLanz** [comment]
I'll try to find a fix, how many time can you wait?

**Comment by taylorotwell** [comment]
I don't know. Looking at the code I can't even figure out the problem, so...

**Comment by portonefive** [comment]
Hate to see features get ripped out.. The paths just need to be standardized. When I posted the first fix I knew it needed to be opposite. This will standardize Windows paths to Linux. Please PR it @RomainLanz 
```
if ($tree = trim(str_replace(str_replace('\\', '/', config_path()), '', str_replace('\\', '/', $directory)), DIRECTORY_SEPARATOR))
```

**Comment by taylorotwell** [comment]
I don't even understand why any of that is necessary. Can someone please for the love of all that is holy explain it to me? We are using DIRECTORY_SEPARATOR.

**Comment by taylorotwell** [comment]
Tagged that fix. All good?

**Comment by ValsiS** [comment]
5.0.12 no error message ...

**Comment by portonefive** [comment]
@taylorotwell 

config_path() string (27) "C:\Development\boise/config"
$directory string (27) "C:\Development\boise\config"

You can see how the str_replace on line 91 would be ineffective due to the strings not being equal. Using directory separator 

DIRECTORY_SEPARATOR is all fine (and preferred even), but you would need to use it where you define the paths. 

Illuminate\Foundation\Application: Line #279 - configPath() would need to be:
```php
return $this->basePath. DIRECTORY_SEPARATOR . 'config';
```

Ideally you would want to replace all references of '/' with DIRECTORY_SEPARATOR in that file. I will submit a PR when I get home later if you haven't done so by then.

**Comment by taylorotwell** [comment]
Gotcha. Thanks for explanation.

**Comment by portonefive** [comment]
@taylorotwell You can revert the fix that was posted in this thread and merge #7635 if you'd like. Just changes out the hard-coded separators for the constant.

**Comment by taylorotwell** [comment]
OK I merged #7635. Is anyone actually testing this stuff? I'm not tagging another release until someone posts a screenshot of this working or submits a unit tests (perferrably)

**Comment by taylorotwell** [comment]
With #7635 merged, those str_replaces are needed anymore so I removed it back to how it was. Can someone set minimum-stability to "dev" and make sure this is working on Windows?

**Comment by portonefive** [comment]
@taylorotwell I am currently running with minimum-stability at dev, and on Windows, and the above is working. The only fix that is needed is #7635 so you can surely revert the str_replace changes.

**Comment by taylorotwell** [comment]
So with latest commit hash on laravel/framework it is working for you and loading config directories that are nested?

**Comment by portonefive** [comment]
That's correct. I am running (dev-master eab95a8) on Windows, with the following config:

**config/test/foo.php**
```php
<?php

return [
    'bar' => 'baz'
];
```
Result: 
config('test.foo.bar') string (3) "baz"

All seems well.

**Pull request merged**
