### PR TITLE
[5.2] Add method Application::bootstrapPath()

### PR DESCRIPTION
**Pull request by vlakoff**
Bootstrap directory is currently hardcoded, hence this PR allowing to relocate it just like others paths.

### CODE REVIEW

**Comment by taylorotwell** [comment]
What was your use case for re-locating it?

**Comment by vlakoff** [comment]
I'm working on a project for some car manufacturer named volkswagen. Under some circumstances they want the application to perform better (faster cloud servers, less ads, etc.). The best approach is to bootstrap to a different application which use the same codebase except for ahem, just a few tweaks.

**Comment by vlakoff** [comment]
@taylorotwell Would you accept a backport of this addition to 5.1? It's 100% backward-compatible and would help me for some projects. Thanks in advance for considering this.

**Comment by GrahamCampbell** [comment]
We strictly only backport bug fixes.

**Comment by vlakoff** [comment]
I know, but I just saw [this change](https://github.com/laravel/laravel/commit/2c834ad59c63535ea6e22c659ede67c0ddce1874) and I thought, maybe... Would be appreciated still.

**Comment by GrahamCampbell** [comment]
That was a minor fix to allow us to make the laravel preset on StyleCI contain all the PSR-2 fixers out of the box. The key thing, is that it was a fix. This PR is a feature, and is potentially breaking too, so I don't see it getting backported, sorry.

**Comment by vlakoff** [comment]
No worries. Although this PR can't be breaking, I understand your points.

I guess we'll have to update to 5.2, then soon 5.3...

**Comment by GrahamCampbell** [comment]
Would symlinking the bootstrap folder to your actual location work in the short term?

**Comment by vlakoff** [comment]
Symlinks are hell, avoiding them the most possible. The goal is simplification, not the reverse ;)

**Pull request merged**
