### PR TITLE
Update Container.php

### PR DESCRIPTION
**Pull request by Ken-vdE**
When building a singleton instance, all of its dependencies could be singleton instances too.
When forgetting a stored singleton instance, it could be desirable to dynamically forget all its stored dependencies too.

I based these new methods on the existing `resolve()`, `build()` and `resolveDependencies()`, which I reversed to 'destruct' them, if you will.

### CODE REVIEW

**Comment by driesvints** [comment]
We're probably not going to be merging this at this time, sorry.

**Comment by Ken-vdE** [comment]
> We're probably not going to be merging this at this time, sorry.

May I ask why not?

**Comment by driesvints** [comment]
I don't think these methods will be useful to a majority of people. Feel free to release this as a package if you wish.

**Comment by Ken-vdE** [comment]
Understandable. Thank you for replying so quickly.

**Pull request closed without merging**
