### PR TITLE
[5.4] Sanitize inputs before the validation

### PR DESCRIPTION
**Pull request by arcanedev-maroc**
This feature allows us to sanitize the inputs before the validation.

## Example :

```php
    // CreatePostFormRequest

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => "required",
            'slug' => "required|unique:posts,slug",
        ];
    }

    /**
     * Sanitize the inputs.
     *
     * @return array
     */
    protected function sanitize()
    {
        return [
            'slug' => str_slug($this->get('slug', $this->get('title', ''))),
        ];
    }
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I don't think this is necessary to put in the core tbh. Less to remember if people just implement this small bit of code themselves, rather than having to remember how this works, even if it's not much, it all adds up.

**Comment by arcanedev-maroc** [comment]
It's very simple to use and i don't think it's gonna be hard to remember it.

And it's very, very useful for sanitizing the inputs before the validation like:

```php
    /**
     * Sanitize the inputs.
     *
     * @return array
     */
    protected function sanitize()
    {
        return [
            'email' => strtolower(trim($this->get('email', ''))),
        ];
    }
```

**Comment by jerguslejko** [comment]
+1

**Comment by a-komarev** [comment]
The latest PR about sanitizers https://github.com/laravel/framework/pull/15920 was moved to https://github.com/laravel/internals/issues/42 internal discussion.

**Comment by arcanedev-maroc** [comment]
This is feature doesn't add any sanitizes methods @a-komarev.

But it allows you to integrate your sanitizer helper (or 3rd party packages) with an *eloquent* way.

```php
    protected function sanitize()
    {
        return [
            'email' => SanitizerHelper::sanitizeEmail($this->get('email', '')),
        ];
    }
```

**Comment by a-komarev** [comment]
This could be solved by using recently introduced method:

```php
/**
 * Prepare the data for validation.
 *
 * @return void
 */
protected function prepareForValidation()
{
    // no default action
}
```

**Comment by taylorotwell** [comment]
See above comment.

**Pull request closed without merging**
