### PR TITLE
[7.x] Add isNotFilled() method to Request

### PR DESCRIPTION
**Pull request by KennedyTedesco**
Very often, I use `! $request->filled()`, and it's ok, I can live with it. But I would love to have an `empty()` method. So, instead of:

```php
if (! $request->filled('recaptcha')) {
    // TODO
}
```

Would be possible to use:

```php
if ($request->empty('recaptcha')) {
    // TODO
}
```

The `empty()` method here is just the opposite of `filled()` (in the sense of behavior) to maintain the cognitive consistency when using one or another.

About the name, if `empty()` isn't that good, we can choose another one, but I prefer the first one.

Ps: I know I can use a macro if this gets rejected. :grin:

### CODE REVIEW

**Comment by derekmd** [comment]
In other parts of the framework, "blank" is used as the opposite of filled: https://laravel.com/docs/7.x/helpers#method-blank

PHP's `empty()` function returns `true` for undefined symbols or falsey values so:

```php
empty('0');
// true

request()->replace(['foo' => '0'])->empty('foo');
// false
```

Since `empty()` behavior differs from the opposite of `filled()`, `blank()` is used instead.

(Ruby on Rails also uses blank: https://api.rubyonrails.org/classes/Object.html#method-i-blank-3F)

**Comment by GrahamCampbell** [comment]
> PHP's empty() function returns true for undefined symbols or falsey values so:

I don't think we should try to emulate PHP's empty function. That behaviour is usually not what people intended.

**Comment by KennedyTedesco** [comment]
We already don't emulate !empty() in the filled() function. I've kept the same behavior. 

About the name, I'm open to change it, if requested. My suggestions are: empty() or notFilled().

**Comment by shalvah** [comment]
@GrahamCampbell I think @derekmd was suggesting w use the name `blank()`, not that we emulate `empty()`'s behaviour. He was just giving some backstory into the reason for the name.

**Comment by taylorotwell** [comment]
If we rename to `blank` there will be a subtle difference between the `blank` helper and this method. Namely, empty arrays are considered blank by the `blank` helper but would not be considered blank by this method.

**Comment by KennedyTedesco** [comment]
The same way, `filled()` considers empty arrays as true:

```php
request()->replace(['foo' => []])->filled('foo'); // true
```

My goal here is to find a way to negate the `filled()`.

**Comment by taylorotwell** [comment]
So far I'm just not happy with the naming options. We could use `isNotFilled` to be super explicit. Similar to Collection's `isNotEmpty`.

**Comment by KennedyTedesco** [comment]
`isNotFilled()` looks pretty good to me, super explicit. I've changed the method name.

**Pull request merged**
