### PR TITLE
[6.x] Only prepend scheme to PhpRedis host when necessary

### PR DESCRIPTION
**Pull request by ryzr**
Please see https://github.com/laravel/framework/pull/34016

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
So I suppose the question is whether we want to support this. Do we take the position that you including the scheme in the host file is invalid syntax?

**Comment by ryzr** [comment]
> So I suppose the question is whether we want to support this. Do we take the position that you including the scheme in the host file is invalid syntax?

Good point. I'm actually prepending the tls:// scheme to env vars in Terraform config to get this working in the first place. It makes sense to me to specify host and scheme distinctively. 

For me, upgrading from v7.25.0 to v7.26.0 was a breaking change (hence the PR), but curious how common this configuration was, if it wasn't what was intended anyway.

**Comment by sebdesign** [comment]
@ryzr I understand that in your config you have set the `scheme` to `tls` and also the `host` prefixed with `tls://`. In previous versions the `scheme` key did not do anything with the `phpredis` connector, but now it does prepend the `tls://` in front of the `host`.

@driesvints I'm fine with this PR, as it addresses cases like this, which users have defined the `scheme` AND prepended the scheme in the `host` for the `phpredis` driver.

But configuring redis like this is not really correct, and it would certainly not work with the `predis` driver: you need to configure either the `scheme` or prefix the scheme in front of the `host`, but not both.

If folks need to use different connectors between environments, they could use the `REDIS_URL` or the `REDIS_HOST`, or even introduce a `REDIS_SCHEME` variable.

**Comment by driesvints** [comment]
Maybe it's best that we fix this for 6.x & 7.x and then revert it again for 8.x?

@taylorotwell what are your thoughts?

**Comment by sebdesign** [comment]
@driesvints I agree with this, let's merge this but we should be more clear about the correct configuration in the docs. I'll submit a PR to the `laravel/docs`.

**Comment by taylorotwell** [comment]
I see no huge need to revert this after merging as long as our docs is correct.

**Comment by robclancy** [comment]
This just caused us to have downtime because we were manually including the scheme since Laravel didn't handle it. So now I assume I'm getting a double scheme. This wasn't a backwards compatible change, especially since digital ocean docs have suggestions to add the scheme yourself. 
https://www.digitalocean.com/community/questions/how-to-setup-laravel-with-digitalocean-managed-redis-cluster (also saw this in other places, this was just the first googled result I found... added a comment to see if the author can correct it).

**Pull request merged**
