### PR TITLE
[7.x] Fix not being able to set component attributes from inside class

### LINKED ISSUE #31653: Can't set component view attributes from component class.
- Laravel Version: 7.x-dev
- PHP Version: PHP 7.3.11
- Database Driver & Version: N/A

### Description:
I'm not 100% sure if this is a bug or intended behavior, but I'm not able to set default attributes from the component class.

### Steps To Reproduce:

```php
<?php 
use Illuminate\View\Component;
use Illuminate\View\ComponentAttributeBag;

// App\View\Components\Button
class Button extends Component
{

    public function __construct()
    {
        $this->withAttributes(['class' => 'foobar', 'type' => 'button']); 
    }

}
```

```php
<?php 
// resources/views/components/button.blade.php
dd($attributes);
?>
```

```
Illuminate\View\ComponentAttributeBag {#284 ▼
  #attributes: []
}
```

### PR DESCRIPTION
**Pull request by ryangjchandler**
This pull request should fix #31653 . There were a couple of routes that could have been taken which I detailed in the issue, but I chose to go down the merging route, instead of conditional setting.

There is a very simple test provided too, not sure if this could be expanded.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Totally broke attributes on 7x. release. Reverting.

**Comment by taylorotwell** [comment]
Please make sure all PRs actually work on a real component.

**Comment by ryangjchandler** [comment]
Apologies @taylorotwell. Strange since I made the changes directly in a new Laravel project and then moved to framework branch.

**Comment by ryangjchandler** [comment]
I've identified the problem. I'll make a second PR with some better tests too.

**Pull request merged**
