### PR TITLE
[5.4] Low-hanging optimization in Eloquent model

### PR DESCRIPTION
**Pull request by fernandobandeira**
Re-submit of #17656

Changed just ``` getAttributeFromArray ``` so we keep the current behavior...

```php
function foo() {
    $data = ['key' => null];
    if (array_key_exists('key', $data)) {
        // return $data['key'], which is null
    }
}

function bar() {
    $data = ['key' => null];
    if (isset($data['key'])) {
        // not reached
    }
    // return implicit null
}
```

We are saving around 5% with this change...

props @silwerclaw 
also ping @vlakoff

### CODE REVIEW

**Comment by browner12** [comment]
In the case of an attribute being `null`, do we need an explicit `return null` at the end, or is that implied?

**Comment by fernandobandeira** [comment]
Thats implied

**Comment by GrahamCampbell** [comment]
> In the case of an attribute being null, do we need an explicit return null at the end, or is that implied?

Yeh, that's not needed. The introduction of the `void` return type is just a confusion, since returning nothing is treated as `null`.

**Comment by browner12** [comment]
thanks guys. looks like the behavior is identical then.

i can't speak to the speed savings, though.

**Comment by fernandobandeira** [comment]
Here's a gist that vlakoff did to benchmark it:

https://gist.github.com/vlakoff/2569a9de8b33b05a203f6993ec39e69b

**Comment by taylorotwell** [comment]
Can you provide before and after benchmarks?

**Comment by fernandobandeira** [comment]
Running the benchmark on PHP7.0

Code that was executed:

```php
User.php

protected function getAttributeFromArray($key)
    {
        global $BENCHMARK_1;
        if (! empty($BENCHMARK_1)) {
            if (isset($this->attributes[$key])) {
                return $this->attributes[$key];
            }
        } else {
            if (array_key_exists($key, $this->attributes)) {
                return $this->attributes[$key];
            }
        }
    }

benchmark.php
        global $BENCHMARK_1, $BENCHMARK_2;
        $nb = 1000;
        $user = \App\User::first();        
        $t1 = microtime(true);
        $BENCHMARK_1 = false;
        $BENCHMARK_2 = false;
        for ($i = $nb; $i--; ) {
            $user->id;
        }
        $t2 = microtime(true);
        $BENCHMARK_1 = true;
        $BENCHMARK_2 = true;
        for ($i = $nb; $i--; ) {
            $user->id;
        }
        $t3 = microtime(true);
        echo $t2 - $t1;
        echo PHP_SAPI == 'cli' ? "\n" : '<br>';
        echo $t3 - $t2;
        echo PHP_SAPI == 'cli' ? "\n\n" : '<br><br>';
        echo $t2 - $t1 == 0 ? 'N/A' : ($t3 - $t2) * 100 / ($t2 - $t1);
        exit;
```

**Results:**
0.033835172653198
0.032655954360962

96.514815206285 Around **3.5%** difference in AVG.

**Pull request merged**
