### PR TITLE
[6.x] limit expected bindings v3

### PR DESCRIPTION
**Pull request by nfangxu**
I prefer my way. @mpyw 

#35865 
#35972

### CODE REVIEW

**Comment by u01jmg3** [comment]
What about `whereBetween()`, `whereJsonLength()` and `having()`?

**Comment by KaneCohen** [comment]
This is more elegant, however it might have an issue with input like that:

```
[[], [12, 30]
```

Array flattening disregards empty array since technically there's no values inside while `head()` function will return `false`.

**Comment by nfangxu** [comment]
> This is more elegant, however it might have an issue with input like that:
> 
> ```
> [[], [12, 30]
> ```
> 
> Array flattening disregards empty array since technically there's no values inside while `head()` function will return `false`.

If this is the case, returning a false is also OK

**Comment by nfangxu** [comment]
> What about `whereBetween()`, `whereJsonLength()` and `having()`?

`whereJsonLength()` directly (int) limit

`whereBetween()` and `having()` has been added

**Comment by limingxinleo** [comment]
M

**Comment by taylorotwell** [comment]
Saying "I prefer my way" with no explanation isn't going to get anything merged.

**Pull request closed without merging**
