### PR TITLE
[7.x] Implemented security measure for external links

### PR DESCRIPTION
**Pull request by CaddyDz**
References:

* https://web.dev/external-anchors-use-rel-noopener/

* https://twitter.com/addyosmani/status/1234055782896979968

Signed-off-by: CaddyDz <caddydz4@gmail.com>

### CODE REVIEW

**Comment by taylorotwell** [comment]
Promotion is removed in 7.x... please remove that file.

**Comment by CaddyDz** [comment]
Done!

**Comment by GrahamCampbell** [comment]
Hmmm, something looks odd with this diff. Could you rebase? `git pull --rebase upstream 7.x` and then `git push --force`.

**Comment by CaddyDz** [comment]
this looks good? @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Excellent. Yes. 👍

**Review by GrahamCampbell — APPROVED** [review]

**Pull request merged**
