### PR TITLE
Properly terminate Route Middlewares that implement TerminableMiddleware

### PR DESCRIPTION
**Pull request by winglian**
Might be a bug, but Route Middlewares that implement TerminableMiddleware do not have their terminate method called on shutdown. One example of this not happening is when the Session middleware is used as a route middleware.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I think the route middleware should be terminated first.

**Comment by winglian** [comment]
Should we simply do an `array_reverse` so that routes are terminated in reverse order of the middleware stack? My initial logic was to follow the current convention where they are terminated in order of the stack.

**Comment by taylorotwell** [comment]
I was mainly thinking just swap the arguments to the array_merge.

**Comment by GrahamCampbell** [comment]
> I was mainly thinking just swap the arguments to the array_merge.

:+1:

We should be careful using array_reverse all over functions that are executed in every request. Can be costly.

**Comment by winglian** [comment]
if the reasoning is performance issues with `array_reverse` we could use `foreach($idx=count($allMiddlewares)-1;$idx>=0;$idx--)`. My personal feeling is only to terminate them consistently in the same order they are in the pipeline, whether forward or reverse.

**Pull request merged**
