### PR TITLE
[8.x] Improvement in the `Arr::query()` method

### PR DESCRIPTION
**Pull request by selcukcukur**
- Before :
```php
Arr::query(['foo' => 'bar', 'baz' => ['bam' => 'baz', 'first' => 'two']]);
// Result : foo=bar&baz%5Bbam%5D=baz&baz%5Bfirst%5D=two
```
- After :
```php
Arr::query(['foo' => 'bar', 'baz' => ['bam' => 'baz', 'first' => 'two']]);
// Result : foo=bar&baz[bam]=baz&baz[first]=two
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is a major breaking change, and will definitely break apps.

**Comment by selcukcukur** [comment]
> This is a major breaking change, and will definitely break apps.

Normally, it is stated that the output should be obtained in this way in the documents for [8.x] version. So I targeted the 8.x version.

See: https://laravel.com/docs/8.x/helpers#method-array-query

**Comment by bert-w** [comment]
Shouldnt url's strictly speaking use the encoded version, i.e.  `%5D` and `%5B`?

StackOverflow answer https://stackoverflow.com/a/13227416/1346367, pointing to the RFC https://www.ietf.org/rfc/rfc3986.txt . It denotes square brackets as "gen-delims", indicating that they should be encoded.

I notice my Firefox browser automatically *visually* converts a percent-encoded address to a non-encoded address containing `[` and `]`, however the devtools still show the request as sending a `%`-encoded string.

Note that you can also use `urldecode($arrQueryResult)` if you need the decoded version.

**Comment by selcukcukur** [comment]
> Shouldnt url's strictly speaking use the encoded version, i.e. `%5D` and `%5B`?
> 
> StackOverflow answer https://stackoverflow.com/a/13227416/1346367, pointing to the RFC https://www.ietf.org/rfc/rfc3986.txt . It denotes square brackets as "gen-delims", indicating that they should be encoded.
> 
> I notice my Firefox browser automatically _visually_ converts a percent-encoded address to a non-encoded address containing `[` and `]`, however the devtools still show the request as sending a `%`-encoded string.
> 
> Note that you can also use `urldecode($arrQueryResult)` if you need the decoded version.

You are right about this, I sent this withdrawal request because I saw in the documents that the output should be sent that way ...

Otherwise, it must be used as '%' of course.

**Comment by taylorotwell** [comment]
Breaking change.

**Pull request closed without merging**
