### PR TITLE
[5.2] Fix a bug seeIsSelected() can't check select tag with multiple values

### PR DESCRIPTION
**Pull request by shadoWalker89**

### CODE REVIEW

**Comment by shadoWalker89** [comment]
There is an enhancement that i would like to add if you agree.
In the seeIsSelected() the second argument could be an array. This is very useful when dealing with a select tag that can have multiple values.

```php
$this->seeIsSelected('roles[]', ['user', 'reviewer']);
```

**Comment by shadoWalker89** [comment]
Will you please guide me how to fix the StyleCI problem.

**Comment by GrahamCampbell** [comment]
>

**Comment by GrahamCampbell** [comment]
> Will you please guide me how to fix the StyleCI problem.

Don't worry about it. StyleCI will merge the fixes itself after this PR is merged.

**Comment by GrahamCampbell** [comment]
In terms of fixing StyleCI in general, you can just download the diff it gives you, and apply it using `git apply`.

**Comment by taylorotwell** [comment]
@sileence does this look ok to you?

**Comment by sileence** [comment]
@taylorotwell yes, it looks fine! I didn't take select multiple into consideration when I wrote the original method, so nice fix @shadoWalker89

**Pull request merged**
