### PR TITLE
[11.x] Make floating-point types consistent

### PR DESCRIPTION
**Pull request by hafezdivandari**
Fixes #3151, #7298, #9089, #9103, #13258, #18776, #21032, #21827, #42308 Related to https://github.com/laravel/ideas/issues/1527 and #47080

This PR makes `float` and `double` column types consistent across all databases and also removes `unsignedDecimal`, `unsignedDouble`, and `unsignedFloat` column types.

## Why?

Almost all databases have 4-bytes single-precision and 8-bytes double-precision storage types when declaring floating-point types (approximate numeric data values). Current syntax is inconsistent on Laravel and there is no way to declare precision value.

* As of MySQL 8.0.17, the nonstandard `FLOAT(M,D)` and `DOUBLE(M,D)` syntax is deprecated and you should expect support for it to be removed in a future version of MySQL. [Source](https://dev.mysql.com/doc/refman/8.0/en/floating-point-types.html#:~:text=As%20of%20MySQL%208.0.17%2C%20the%20nonstandard%20FLOAT(M%2CD)%20and%20DOUBLE(M%2CD)%20syntax%20is%20deprecated%20and%20you%20should%20expect%20support%20for%20it%20to%20be%20removed%20in%20a%20future%20version%20of%20MySQL.)
* As of MySQL 8.0.17, the `UNSIGNED` attribute is deprecated for columns of type `FLOAT`, `DOUBLE`, and `DECIMAL` (and any synonyms); you should expect support for it to be removed in a future version of MySQL. [Source](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html#:~:text=As%20of%20MySQL%208.0.17%2C%20the%20UNSIGNED%20attribute%20is%20deprecated%20for%20columns%20of%20type%20FLOAT%2C%20DOUBLE%2C%20and%20DECIMAL%20(and%20any%20synonyms)%3B%20you%20should%20expect%20support%20for%20it%20to%20be%20removed%20in%20a%20future%20version%20of%20MySQL.%20Consider%20using%20a%20simple%20CHECK%20constraint%20instead%20for%20such%20columns.)

## Changes

* Changes `$blueprint->float($column, $total = 8, $places = 2, $unsigned = false)` to `$blueprint->float($column, $precision = 53)`
* Changes `$blueprint->double($column, $total = 8, $places = 2, $unsigned = false)` to `$blueprint->double($column)`
* Changes `$blueprint->decimal($column, $total = 8, $places = 2, $unsigned = false)` to `$blueprint->decimal($column, $total = 8, $places = 2)`
* Removes  `$blueprint->unsignedFloat()`
* Removes `$blueprint->unsignedDouble()`
* Removes `$blueprint->unsignedDecimal()`

### Before this PR

| Syntax | MySQL | PostgreSQL | SQL Server | SQLite |
| --- | --- | --- | --- | --- |
| `$table->float('foo')`                    | `double(8, 2)` | `double precision` | `float` | `float` |
| `$table->float('foo', 9)`                | `double(9, 2)` | `double precision` | `float` | `float` |
| `$table->float('foo', 9, 3)`             | `double(9, 3)` | `double precision` | `float` | `float` |
| `$table->float('foo', 9, null)`         | `double`       | `double precision` | `float` | `float` |
| `$table->float('foo', null, null)`     | `double`       | `double precision` | `float` | `float` |
| `$table->double('foo')`                 | `double(8, 2)` | `double precision` | `float` | `float` |
| `$table->double('foo', 9)`             | `double(9, 2)` | `double precision` | `float` | `float` |
| `$table->double('foo', 9, 3)`         | `double(9, 3)` | `double precision` | `float` | `float` |
| `$table->double('foo', 9, null)`     | `double`       | `double precision` | `float` | `float` |
| `$table->double('foo', null, null)` | `double`       | `double precision` | `float` | `float` |

### After this PR

| Syntax | [MySQL](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html#:~:text=A%20floating%2Dpoint,in%20this%20section.) | [PostgreSQL](https://www.postgresql.org/docs/11/datatype-numeric.html#:~:text=PostgreSQL%20also%20supports%20the,mean%20double%20precision.) | [SQL Server](https://learn.microsoft.com/en-us/sql/t-sql/data-types/float-and-real-transact-sql?view=sql-server-2017#:~:text=float%20%5B%20(n)%20%5D%20Where%20n%20is%20the%20number%20of%20bits%20that%20are%20used%20to%20store%20the%20mantissa%20of%20the%20float%20number%20in%20scientific%20notation%20and%2C%20therefore%2C%20dictates%20the%20precision%20and%20storage%20size.%20If%20n%20is%20specified%2C%20it%20must%20be%20a%20value%20between%201%20and%2053.%20The%20default%20value%20of%20n%20is%2053.) | [SQLite](https://www.sqlite.org/datatype3.html#:~:text=REAL.%20The%20value%20is%20a%20floating%20point%20value%2C%20stored%20as%20an%208%2Dbyte%20IEEE%20floating%20point%20number.) |
| --- | --- | --- | --- | --- |
| `$table->float('foo')`      | `float(53)` | `float(53)`        | `float(53)`        | `float`  |
| `$table->float('foo', 24)`    | `float(24)` | `float(24)`        | `float(24)`        | `float`  |
| `$table->float('foo', null)`  | `float`     | `float`            | `float`            | `float`  |
| `$table->double('foo')`     | `double`    | `double precision` | `double precision` | `double` |

## Comparison of Floating-Point Types on Different DBs

| Syntax | [MySQL](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html#:~:text=FLOAT%5B,than%20DOUBLE.) | [PostgreSQL](https://www.postgresql.org/docs/11/datatype-numeric.html#:~:text=The%20assumption%20that%20real%20and%20double%20precision%20have%20exactly%2024%20and%2053%20bits%20in%20the%20mantissa%20respectively%20is%20correct%20for%20IEEE%2Dstandard%20floating%20point%20implementations.%20On%20non%2DIEEE%20platforms%20it%20might%20be%20off%20a%20little%2C%20but%20for%20simplicity%20the%20same%20ranges%20of%20p%20are%20used%20on%20all%20platforms.) | [SQL Server](https://learn.microsoft.com/en-us/sql/t-sql/data-types/float-and-real-transact-sql?view=sql-server-2017#:~:text=SQL%20Server%20treats,float(53).) | [SQLite](https://www.sqlite.org/datatype3.html#:~:text=If%20the%20declared%20type%20for%20a%20column%20contains%20any%20of%20the%20strings%20%22REAL%22%2C%20%22FLOA%22%2C%20or%20%22DOUB%22%20then%20the%20column%20has%20REAL%20affinity.) |
| --- | --- | --- | --- | --- |
| `FLOAT(M, D)`      | Deprecated        | _N/A_                       | _N/A_                | Double (`REAL`) |
| `DOUBLE(M, D)`     | Deprecated        | _N/A_                       | _N/A_                | Double (`REAL`) |
| `FLOAT(1 to 24)`   | Single (`FLOAT`)  | Single (`real`)             | Single (`float(24)`) | Double (`REAL`) |
| `FLOAT(25 to 53)`  | Double (`DOUBLE`) | Double (`double precision`) | Double (`float(53)`) | Double (`REAL`) |
| `FLOAT`            | Single (`FLOAT`)  | Double (`double precision`) | Double (`float(53)`) | Double (`REAL`) |
| `DOUBLE`           | Double (`DOUBLE`) | _N/A_                       | _N/A_                | Double (`REAL`) |
| `DOUBLE PRECISION` | Double (`DOUBLE`) | Double (`double precision`) | Double (`float(53)`) | Double (`REAL`) |
| `REAL`             | Double (`DOUBLE`) | Single (`real`)             | Single (`float(24)`) | Double (`REAL`) |

## Upgrade guide
The `double` and `float` column types of database migrations have been rewritten to make these types consistent across all databases:
* The `double` column type now creates a `DOUBLE` equivalent column without total digits and places (digits after decimal point), which is the standard syntax in SQL. Therefore, you may remove the arguments for `$total` and `$places`:

  ```diff
  - $table->double('amount', $total = 8, $places = 2, $unsigned = false);
  // `DOUBLE(8, 2)` on MySQL, `DOUBLE PRECISION` on PostgreSQL, and `FLOAT` on SQLite and SQL Server
  + $table->double('amount');
  // `DOUBLE` on MySQL and SQLite, `DOUBLE PRECISION` on PostgreSQL and SQL Server
  ```

* The `float` column type now creates a `FLOAT` equivalent column without total digits and places (digits after decimal point), but with an optional `$precision` specification to determine storage size as a 4-byte single-precision column or an 8-byte double-precision column. Therefore, you may remove the arguments for `$total` and `$places` and specify the optional `$precision` to your desired value and according to your database's documentation. The default `$precision` is set to 53 that would result in 8-byte double-precision column on all database drivers:

  ```diff
  - $table->float('amount', $total = 8, $places = 2, $unsigned = false);
  // `DOUBLE(8, 2)` on MySQL, `DOUBLE PRECISION` on PostgreSQL, and `FLOAT` on SQLite and SQL Server
  + $table->float('amount', $precision = 53);
  // `FLOAT(53)` on MySQL, PostgreSQL, and SQL Server. `FLOAT` on SQLite
  ```

* The `$unsigned` parameter of the `$table->decimal()`, `$table->double()`, and `$table->float()` methods has been removed. Actually, this were only supported on MySQL. However, You may force deprecated `UNSIGNED` attribute using `->unsigned()` modifier:

  ```diff
  - $table->decimal('foo', $total = 8, $places = 2, $unsigned = true);
  - $table->double('bar', $total = 8, $places = 2, $unsigned = true);
  - $table->float('baz', $total = 8, $places = 2, $unsigned = true);
  + $table->decimal('foo', $total = 8, $places = 2)->unsigned();
  + $table->double('bar')->unsigned();
  + $table->float('baz', $precision = 53)->unsigned();
  ```

* The `unsignedDecimal`, `unsignedDouble`, and `unsignedFloat` column types have been removed. Therefore, you may use equivalent column types and forcing deprecated `UNSIGNED` attribute using `->unsigned()` modifier. Actually, this were only supported on MySQL:

  ```diff
  - $table->unsignedDecimal('foo', $total = 8, $places = 2);
  - $table->unsignedDouble('bar', $total = 8, $places = 2);
  - $table->unsignedFloat('baz', $total = 8, $places = 2)
  + $table->decimal('foo', $total = 8, $places = 2)->unsigned();
  + $table->double('bar')->unsigned();
  + $table->float('baz', $precision = 53)->unsigned();
  ```

### CODE REVIEW

**Comment by bluedreamer** [comment]
Why was the unsigned removed from decimal()? Who made the decision to merge this. I use this and am having issues upgrading to 11. 1 database out of them all deprecating a feature doesn't mean it should be removed. Mariadb still has it and mysql hasn't got rid of it yet. What a stupid decision to allow the removal of the unsigned attribute on decimal()

**Comment by hafezdivandari** [comment]
@bluedreamer just use `decimal()->unsigned()` as explained on the [upgrade guide](https://laravel.com/docs/11.x/upgrade#:~:text=However%2C%20if%20you,the%20column%27s%20definition).

**Comment by bluedreamer** [comment]
But why was a breaking public API change allowed for what amounts to a cosmetic reason? Why wasn't the param deprecated in documentation only? Wasted my time.

**Comment by devajmeireles** [comment]
Regardless of anything, the PRs that @hafezdivandari  delivers are always of a high standard of description, incredible!

**Comment by Vimiso** [comment]
Laravel: `^11.9`
MySQL: `8.4.2`

Heads up, your documentation specifies before your PR `$table->float('foo')` will create a `double`, and after a `float`. 

This is not the case.

`$table->float('foo')`  with no precision argument will continue to create a double.

I have found having to set the precision explicitly to `null`, eg. `$table->float('proximity', precision: null)` then indeed sets the data type to float.

**Comment by hafezdivandari** [comment]
@Vimiso I've explained that the default `precisions` is 53:

`$table->float('foo')` => `FLOAT(53)` => `DOUBLE` on MySQL

**Comment by Vimiso** [comment]
Ah got you, my bad!

**Pull request merged**
