### PR TITLE
[11.x] Defer registering schedule registered using `ApplicationBuilder::withSchedule()`

### LINKED ISSUE #51354: Schedule gets registered with every artisan call
### Laravel Version

11.7.0

### PHP Version

8.3.6

### Database Driver & Version

_No response_

### Description

When running any `artisan` command (just `php artisan` does the same), the code inside `console.php` route file and/or `->withSchedule()` bootstrap method gets executed. Usually this wouldn't be a big deal, because the code should only register cron events. However, sometimes dynamic scheduling might involve database queries which can inflict unwanted performance penalty or in worst case scenario fail in CI setup.

We noticed this in our CI while upgrading from Laravel 10 to Laravel 11 (with slimmed down app structure). Our scheduler needs to be dynamic and it makes a DB query for that reason. When CI is setting up the application it runs `composer install` which then runs `php artisan package:discover --ansi` as a composer `post-autoload-dump` script. This is standard in every Laravel project. Since `package:discover` is an artisan command it boots up the scheduler as well. At this stage in CI database is not yet available thus we get a `QueryException: SQLSTATE[HY000] [2002] Connection refused`.

I have checked and this wasn't the case with Laravel 10. I'm not sure if this is now intended or not, but I would expect scheduler code to only execute when calling `php artisan schedule:run` and `php artisan schedule:work`.

### Steps To Reproduce

* Set up new Laravel 11 project.
* Add `dd();` inside `console.php` route file or inside `->withSchedule()` app bootstrap method.
* Run `php artisan` and observe the command to fail.

### PR DESCRIPTION
**Pull request by crynobone**
fixes #51354

### CODE REVIEW

**Comment by Plytas** [comment]
Thanks for your input @crynobone, but this doesn't solve the full problem. The problem still exists if you use just `console.php` route file.

This change introduces a new issue where you cannot use both `->withSchedule()` on app bootstrap AND `console.php` route file. You can observe this by having a task scheduled in both places and running `php artisan schedule:list`.

Note: `inspire` is scheduled inside `console.php` (comes by default in new install) and `test` is scheduled inside bootstrap.

Before this change:
image

After this change:
image

**Comment by crynobone** [comment]
You should defer resolving code dedicated for Schedule if `console.php`. The file itself needs to be loaded for all artisam requests.

**Comment by Plytas** [comment]
You are correct, I forgot the fact that `console.php` is used for more than just schedule.

So the only issue I see now is that both methods cannot be used simultaneously while it could have been before.

**Comment by crynobone** [comment]
> So the only issue I see now is that both methods cannot be used simultaneously while it could have been before.

As in Laravel 10? It should only be possible to register Schedule within `App\Console\Kernel::schedule()`. So this should make `withScheduling()` behave similar to the old method.

**Comment by Plytas** [comment]
As in Laravel 11 before this change. I'll re-itterate my previous message.

This change introduces a new issue where you cannot schedule commands in both `->withSchedule()` on app bootstrap AND `console.php` route file. You can observe this by having a task scheduled in both places and running php artisan schedule:list.

Note: `inspire` is scheduled inside console.php (comes by default in new install) and `test` is scheduled inside bootstrap.

Before this change:
image

After this change:
image

With this change `->withSchedule()` is only resolved when `console.php` route file is empty, otherwise it only lists (and processes) schedule from `console.php` and ignores `->withSchedule()`.

**Comment by taylorotwell** [comment]
I'm pretty concerned about this breaking other applications.

**Comment by crynobone** [comment]
The only possible breaking change is when someone uses `withScheduling()` to add and schedule command, but that's never how it was intended to be used:

```php
return Application::configure(basePath: dirname(__DIR__))
    ->withScheduling(function ($schedule) {
        Artisan::command('go', fn () => $this->comment('Done!'))->hourly();
    })->create();
```

With this PR, `go` command is only loaded via `schedule:list` and `schedule:run` and cannot be called directly via `artisan`.

**Comment by crynobone** [comment]
Add additional tests to cover the limitation when adding new artisan commands within `withSchedule()`

**Comment by taylorotwell** [comment]
I dunno, I'm not comfortable merging this without much more community feedback and input.

**Pull request closed without merging**
