### PR TITLE
[5.3] delete @ parent feature from blade

### PR DESCRIPTION
**Pull request by halaei**
`@parent` feature is a bug, and it is there even for those who don't use it. I only can try to remove it. So here you are.

### CODE REVIEW

**Comment by halaei** [comment]
#10068

**Comment by abhimanyusharma003** [comment]
I think it should be fixed not removed.

**Comment by taylorotwell** [comment]
Should be fixed, not removed.

**Comment by halaei** [comment]
Thanks then ;)

**Pull request closed without merging**
