### PR TITLE
[8.x] Add new feature `validated` function in `Request`

### PR DESCRIPTION
**Pull request by michaelnabil230**
`Illuminate\Http\Request` has been improved and `validated()` has been added to it and `safe()` has also been added and I have also modified `Illuminate\Foundation\Http\FormRequest` so that it does not have duplicate lines

Before :

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TestController extends Controller
{
    public function __invoke(Request $request)
    {
        $validated = $request->validate([
            'name' => ['required'],
            'phone' => ['required'],
        ]);
    }
}
```

Now : 

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TestController extends Controller
{
    public function __invoke(Request $request)
    {
        $request->validate([
            'name' => ['required'],
            'phone' => ['required'],
        ]);
        
        // Retrieve the validated input data...
        $validated = $request->validated();

        // Retrieve a portion of the validated input data...
        $validated = $request->safe()->only(['name', 'phone']);
        $validated = $request->safe()->except(['name', 'phone']);
    }
}
```

### CODE REVIEW

**Comment by michaelnabil230** [comment]
I just want to organize the code more

**Comment by michaelnabil230** [comment]
I hope to be a contributor I have a lot of ideas but I can't implement them alone

**Comment by yoeriboven** [comment]
The `validate` method returns the validated fields.

```php
$validated = $request->validate([
    'name' => ['required'],
    'phone' => ['required'],
]);
```

**Comment by michaelnabil230** [comment]
> The `validate` method returns the validated fields.
> 
> 
> 
> ```php
> 
> $validated = $request->validate([
> 
>     'name' => ['required'],
> 
>     'phone' => ['required'],
> 
> ]);
> 
> ```

It's a new feature that I just added and basically it's like a shortcut

**Comment by michaelnabil230** [comment]
Hi @taylorotwell 
It's not a problem solution or a bug correction 
It's just new features that can be added to the framework and some code shortcuts

**Comment by michaelnabil230** [comment]
Can the withdrawal request be reopened ?

**Comment by michaelnabil230** [comment]
@taylorotwell Can the withdrawal request be reopened?

**Pull request closed without merging**
