### PR TITLE
[5.6] Bumps nesbot/carbon to 1.29.*

### PR DESCRIPTION
**Pull request by SolStis86**
This version introduced new utility CarbonPeriod which is a nice interface for generating date periods into arrays / collectons and plays nicely with current Carbon\Carbon / DateTime objects

### CODE REVIEW

**Comment by SolStis86** [comment]
The failures here are interesting... 

```
1) Illuminate\Tests\Database\DatabaseEloquentIntegrationTest::testTimestampsUsingDefaultDateFormat
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2017-11-14 08:23:19.000000'
+'2017-11-14 08:23:19.290111'
/home/travis/build/laravel/framework/tests/Database/DatabaseEloquentIntegrationTest.php:1184
2) Illuminate\Tests\Database\DatabaseEloquentIntegrationTest::testTimestampsUsingOldSqlServerDateFormat
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2017-11-14 08:23:19.000000'
+'2017-11-14 08:23:19.290111'
/home/travis/build/laravel/framework/tests/Database/DatabaseEloquentIntegrationTest.php:1228
```

How are the created_at / updated_at timestamps generated? If through carbon, is its default accuracy now to the millisecond?

**Comment by GrahamCampbell** [comment]
Thanks. This would need to happen on master though. ;)

**Comment by 36864** [comment]
Also, Carbon is up to 1.31 now, is there any reason you'd want to specifically update to 1.29?

**Comment by SolStis86** [comment]
The reason for 1.29 is that it introduced Carbon\CarbonPeriod... a fluent implementation of dealing with DatePeriods analogous to http://php.net/manual/en/class.dateperiod.php. The reason its not compatible seems to be beyond even the great Taylors intelect at present (which im fucking humbled by) .  Id like to say force the tests, however i know their in no way rollerent to the reqirements of the framework.... https://soundcloud.com/hardcore-messiah/dougal-b2b-gammer-slammin-vinyl-nye-2007

**Comment by SolStis86** [comment]
Its a nice to have so no biggy

**Pull request closed without merging**
