### PR TITLE
[6.x] fix sqlserver drop column

### PR DESCRIPTION
**Pull request by joelharkes**
Answer for sql server dropColumn migrations not working because of default constraints:

Now default constraints get deleted first:

Read here the whole issue: https://github.com/laravel/framework/issues/4402

### CODE REVIEW

**Comment by joelharkes** [comment]
i can fix the tests, please let me know if you like the style of the code?

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, **tests**, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Comment by joelharkes** [comment]
The thorough explanation is in the GitHub issue..

It doesn't feel very welcoming to instantly close my PR, instead of guiding me to a good PR.. this happens every PR I post. 

I guess that is why there is no developer community on laravel except the core developers who are allowed to do anything?

**Comment by driesvints** [comment]
Hey @joelharkes. The PR template for our repos has the following note:

> Pull requests without a descriptive title, thorough description, or tests will be closed.

https://github.com/laravel/framework/blame/6.x/.github/PULL_REQUEST_TEMPLATE.md

This is clearly displayed on any PR that is opened. It's very hard for us to keep up with every PR as it is (we're maintaining lots of repos) so if we also had to dig through every issue which is linked in a PR we would be doing nothing else besides that. Please always add a thorough (but concise) description to your PR what you're solving or proposing so we can review it within the PR itself. Taylor also noted that this PR lacks tests which is probably party of the reason why he closed it.

Please don't take this personal. Maintaining such a large amount of repositories is quite a task. Feel free to try again with the above things in mind.

**Pull request closed without merging**
