### PR TITLE
[5.2] Fix issue #11815

### LINKED ISSUE #11815: Timestamps are not prefixed when updating many-to-many relationship
I have a many-to-many relationship of Users and Notices set up in Eloquent. The pivot table has timestamps and a 'read' field (so each user can mark a notice as read independently). Here are the relevant model definitions:

    class Notice extends Model
    {
        public function users()
        {
            return $this->belongsToMany('App\Entities\User', 'notice_user_map')
                ->withPivot('read')
                ->withTimestamps();
        }
    }

    class User extends Model implements AuthenticatableContract, AuthorizableContract, CanResetPasswordContract
    {
        public function notices()
        {
            return $this->belongsToMany('App\Entities\Notice', 'notice_user_map')
                ->withPivot('read')
                ->withTimestamps();
        }
    }

However, when I try to mark all notices for a user as read I get an error. The code I'm using is

    $user->notices()->wherePivot('read', 0)->update(['read' => 1]);

The error is

> Integrity constraint violation: 1052 Column 'updated_at' in field list is ambiguous (SQL: update \`notices\` inner join \`notice_user_map\` on \`notices\`.\`id\` = \`notice_user_map\`.\`notice_id\` set \`read\` = 1, \`updated_at\` = 2016-01-06 23:49:45 where \`notice_user_map\`.\`user_id\` = 2904708423 and \`notice_user_map\`.\`read\` = 0)

The columns that are set should have the table prefix, i.e. `notice_user_map.read` and `notice_user_map.updated_at`

Also the date isn't quoted, not sure if that's the exact query that was trying to be run or if that's just how Laravel is displaying it.

Laravel 5.1, PHP 5.5, MySQL 5.6

### PR DESCRIPTION
**Pull request by samrap**
Timestamps are not prefixed when updating many-to-many relationship

This issue is caused by the Eloquent Builder's `addUpdatedAtColumn` method, which
does not account for relationships when retrieving the "updated at" column. Unlike
the `SoftDeletes` trait, which knows to get the qualified "deleted at" column
when deleting relationships, the Eloquent Builder's `addUpdatedAtColumn` method
simply calls the model's `getUpdatedAtColumn` method, which returns the static
constant who's value is "updated_at".

The fix for this is implementing the same methods for deleting relationships when
updated them. The `Illuminate\Database\Eloquent\Model` class receives a new
`getQualifiedUpdatedAtColumn`, which simply concatenates the model's table name
with the model's "updated at" column name. Meanwhile, the `Illuminate\Database\Eloquent\Builder`
`addUpdatedAtColumn` method checks to see if the current query has any joins. If
the query does have joins, it will call the model's `getQualifiedUpdatedAtColumn`,
otherwise it will do what it has always done, call the `getUpdatedAtColumn` method.

This finally gives us the proper "updated at" query whether we have joins or not.
However, the method returns a merged array using the `Illuminate\Support\Arr`
class, which merges the existing values with the new "updated at" column, but
due to the nature of the `Arr::set` method, breaks the join query from `table.updated_at`
to `[table => updated_at]`, breaking the subsequent query.There are two solutions
I found to this issue. The first is to modify the Query Builder `update` method to
call `Arr::dot` on the on the values passed to the method. This is not ideal, as
it reverses the `Arr::set` method which causes an unnecessary latency in time and
could also have unforseen affects. The second solution goes back to the Eloquent
Builder `update` method. Instead of using the `Arr::add` method to add the
"updated at" column, we will perform a simple `array_merge`, which does exactly
what the `Arr::add` method did when updating, but doesn't break the merge when
adding a relationship to the "updated at" column.

**When using the `Arr::add` method:**  `update `bug` inner join `bug_laravel` on `bug`.`id` = `bug_laravel`.`bug_id` set `bug`.`deleted_at` = ?, `bug` = ? where `bug_laravel`.`laravel_id` = ? and `bug`.`deleted_at` is null`
**When using `array_merge` function:** `update `bug` inner join `bug_laravel` on `bug`.`id` = `bug_laravel`.`bug_id` set `bug`.`deleted_at` = ?, `bug`.`updated_at` = ? where `bug_laravel`.`laravel_id` = ? and `bug`.`deleted_at` is null`

The first query fails, because the values returned from `Arr::add` are as follows:

```
array:2 [
  "bug.deleted_at" => "2016-05-11 18:08:12"
  "bug" => array:1 [
    "updated_at" => "2016-05-11 18:08:12"
  ]
]
```

But, using `array_merge`:

```
array:2 [
  "course.deleted_at" => "2016-05-11 18:09:39"
  "course.updated_at" => "2016-05-11 18:09:39"
]
```

This fix passes all tests, and has been tested on a working application I am currently developing.

---

Closes #11815.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Could you add a couple of tests to cover this please?

**Comment by samrap** [comment]
Sure, I'm not familiar with the extent of the framework's testing, so this might take a while.

**Comment by samrap** [comment]
Been busy at work, finishing those tests is still a top priority for me, looking into it tonight.

**Comment by tillkruss** [comment]
Any updates on the tests?

**Comment by taylorotwell** [comment]
Breaks things: https://github.com/laravel/framework/issues/13707

Reverted. :(

**Comment by samrap** [comment]
Bummer. Can you elaborate more on the breakage? I still plan on finding a fully functional solution to this bug.

**Comment by samrap** [comment]
@taylorotwell bummer. Will look further.

**Comment by taylorotwell** [comment]
The thread I linked has some details. The OP of that might be able to give more insight.

**Comment by samrap** [comment]
Got it. It's pretty apparent what's going on. Just need to find a way to use the qualified column on the join part of the query only. Easier said than done ;)

**Pull request merged**
