### PR TITLE
Completes eloquent builder find or fail return phpDoc

### PR DESCRIPTION
**Pull request by vladkucherov**

### CODE REVIEW

**Comment by vladkucherov** [comment]
Am i missing something? why is it closed?

**Comment by taylorotwell** [comment]
How does this method ever return an array of Eloquent query builders? (static[])

**Comment by vladkucherov** [comment]
It returns the `find` method which does return `static` and `static[]`

```
public function findOrFail($id, $columns = ['*'])
    {
        $result = $this->find($id, $columns);

        if (is_array($id)) {
            if (count($result) == count(array_unique($id))) {
                return $result;
            }
        } elseif (! is_null($result)) {
            return $result;
        }

        throw (new ModelNotFoundException)->setModel(get_class($this->model));
    }
```

Find:
```
/**
     * Find a model by its primary key.
     *
     * @param  mixed  $id
     * @param  array  $columns
     * @return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection|static[]|static|null
     */
    public function find($id, $columns = ['*'])
```

**Comment by GrahamCampbell** [comment]
Looks like phpdoc on find is wrong.

**Comment by vladkucherov** [comment]
Looks so

**Pull request closed without merging**
