### PR TITLE
[5.7] Changed 403 to `Response::HTTP_FORBIDDEN`

### PR DESCRIPTION
**Pull request by TBlindaruk**

### CODE REVIEW

**Comment by carusogabriel** [comment]
@TBlindaruk Maybe we can expand this patch to change all other codes across this codebase to constants?

**Comment by devcircus** [comment]
Maybe he's changed his mind over the years but similar PRs have always been rejected.

**Comment by TBlindaruk** [comment]
@carusogabriel , in case, if this PR will be accepted then I will create another PR for change all codes.

**Comment by taylorotwell** [comment]
403 is shorter and is not changing anytime soon.

**Pull request closed without merging**
