### PR TITLE
[5.8] Don't add page query string param for the first page of pagination to avoid SEO duplicate content issues

### PR DESCRIPTION
**Pull request by benathomeofchampions**
Paginator will currently return the page query string parameter for the first page of pagination (?page=1), when on proceeding pages.

This introduces a potential SEO duplicate content issue, as the page now has 2 URLs, which a site owner would need to address via canonical links.

This PR changes the url() method of AbstractPaginator to only return the paging query string param for pages > 1.

### CODE REVIEW

**Comment by bonzai** [comment]
#27920

**Comment by SjorsO** [comment]
Isn't it a best practice to always set a canonical url in the head tag? Something like this would solve this problem:
```html
<link rel="canonical" href="{{ URL::current() }}" />
```

**Comment by benathomeofchampions** [comment]
> Isn't it a best practice to always set a canonical url in the head tag? Something like this would solve this problem:
> 
> ```
> <link rel="canonical" href="{{ URL::current() }}" />
> ```

Yes, that's correct, but you would still need to account for subsequent pages. `URL::current()` will return the URL with path, minus paging, for pages 2, 3 and so on.

The point of the PR is simply to avoid a site owner introducing duplicate content issues by implementing Paginator, in case they had not considered correct use of canonical tags.

**Comment by laurencei** [comment]
Based upon the previous PR for 5.8 that Taylor explicitly said he wouldnt do for this release, your best bet is to re-target this PR to `master` - and target the change for 5.9

**Comment by GrahamCampbell** [comment]
Please target master. GitHub couldn't correctly change the target because of commits existing on 5.8 not yet merged into 5.9.

**Comment by benathomeofchampions** [comment]
Thanks, both. I'll submit a new PR to master!

**Pull request closed without merging**
