### PR TITLE
[11.x] Always set connect timeout, timeout and enforce TLS 1.2 or higher when using Guzzle

### PR DESCRIPTION
**Pull request by GrahamCampbell**
1. All browsers that I know of already set TLS 1.2 as the minimum supported version, more than a year ago, some more than 3 years ago. The Symfony HTTP client in 6.3.0 will default to only allowing TLS 1.2 or higher. I have not made this change in Guzzle because I feel it would be a breaking change, and may actually impact Guzzle users, because outside of newer versions of Laravel, Guzzle users tend to run on very old systems.
2. The Laravel HTTP client already enforced a connect timeout and a timeout, but this was missing from Pusher. I've enforced the same good configuration options there.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Yeh. I'll look into this in a bit. I'll also be a nice performance improvement to not be re-creating the client over and over, so we can re-use the same TCP connection behind the scenes if people are hitting the same endpoint.

**Comment by daniser** [comment]
@GrahamCampbell @taylorotwell This change should be mentioned in upgrade guide. It just downed my production due to outdated version of Curl.

**Comment by driesvints** [comment]
@daniser can you send in a PR to the docs?

**Comment by daniser** [comment]
@driesvints Right, I'll get to it.

**Pull request merged**
