### PR TITLE
[10.x] Add possibility to set backoff method in broadcast event

### PR DESCRIPTION
**Pull request by dammy001**

### CODE REVIEW

**Comment by jmarcher** [comment]
This will break a lot of things

**Comment by dammy001** [comment]
@jmarcher @driesvints at which will this cause a breaking change?

**Comment by driesvints** [comment]
You're no longer setting the backoff property at object initialization time.

**Comment by dammy001** [comment]
Yeah but if you check pushOn method inside the queue class, the backoff checks for property or method been provided by the job/event passed.

**Comment by jmarcher** [comment]
What Dries and I meant is that if you create a new BroadcastEvent class the property is no longer there.

**Comment by dammy001** [comment]
@jmarcher @driesvints check the below lines because I'm not sure there's any breaking change

https://github.com/laravel/framework/blob/997218b35f5a7f2d5cb7c640e690a5af03499658/src/Illuminate/Broadcasting/BroadcastManager.php#L171

https://github.com/laravel/framework/blob/997218b35f5a7f2d5cb7c640e690a5af03499658/src/Illuminate/Broadcasting/BroadcastManager.php#L183

https://github.com/laravel/framework/blob/997218b35f5a7f2d5cb7c640e690a5af03499658/src/Illuminate/Queue/Queue.php#L147

https://github.com/laravel/framework/blob/997218b35f5a7f2d5cb7c640e690a5af03499658/src/Illuminate/Queue/Queue.php#L192

**Comment by jmarcher** [comment]
I know what you are thinking, but if I create the class and want to access the backoff property directly, this is no longer initialized as before, your change makes the value of the backoff property depend on another class

**Comment by dammy001** [comment]
@jmarcher i guess I'll add the at the constructor level then

**Pull request closed without merging**
