### PR TITLE
[5.1] Removed unused statement

### PR DESCRIPTION
**Pull request by proshanto**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is not unused.

**Comment by proshanto** [comment]
I would like to disagree.

```
$this->laravel['config']
$this->laravel['config']
```

is used instead of $app['config'] which is consistent to other commands. Correct me if i'm wrong.

**Comment by brunogaspar** [comment]
@proshanto It's used on the file that's being required.

**Comment by proshanto** [comment]
I see now. Thanks @brunogaspar 

In config file `$this->laravel['path.base']` could be written and phpstorm won't complain.

**Comment by GrahamCampbell** [comment]
We're already been there in the other duplicates. This way is faster.

**Pull request closed without merging**
