### PR TITLE
[5.7] Revert of Illuminate/Database/Schema/ForeignKeyDefinition.php

### PR DESCRIPTION
**Pull request by TBlindaruk**
- the main difference between `ForeignKeyDefinition` and `ColumnDefinition`,
 that `ColumnDefinition` is actually created https://github.com/laravel/framework/pull/24444/files#diff-0a0682dbb89567dbcd7c4f50d4d1ece5R1260

 So, as for me it is not ok, that we will have return type, which never will be returned.

 cc: @staudenmeir

UPD: reverted part of https://github.com/laravel/framework/pull/26554

### CODE REVIEW

**Comment by staudenmeir** [comment]
That was a conscious decision to make the change less "intrusive". An IDE can recognize it without us returning the actual type.

**Comment by GrahamCampbell** [comment]
This should perhaps be targetted at 5.8 rather than 5.7.

**Comment by TBlindaruk** [comment]
Yes, IDE can recognize it, but 

on the documentation, we will have that this method also can return class which will never will be returned https://laravel.com/api/5.7/Illuminate/Database/Schema/Blueprint.html#method_foreign

**Comment by TBlindaruk** [comment]
@GrahamCampbell PR were was added this class not released yet

**Comment by staudenmeir** [comment]
There a lots of cases in the framework where we have IDE hints like this:
https://laravel.com/api/5.7/Illuminate/Database/Eloquent/Model.html#method_with

**Comment by TBlindaruk** [comment]
@standaniels , but in this case, we do not create a class, just for IDE

**Comment by staudenmeir** [comment]
I don't see the difference.

**Comment by deleugpn** [comment]
That's a shame. I was looking forward to this.

**Comment by driesvints** [comment]
I agree with @TBlindaruk. It's a bit different with the example you mentioned @staudenmeir. In the example you mention the classes are actually used behind the scenes but the class from the PR here is never used.

**Pull request merged**
