### PR TITLE
[8.x] Set anonymous migration

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by crynobone** [comment]
See https://github.com/laravel/laravel/pull/5585#issuecomment-819066305

**Comment by lloricode** [comment]
> See [laravel/laravel#5585 (comment)](https://github.com/laravel/laravel/pull/5585#issuecomment-819066305)

thanks

**Comment by lloricode** [comment]
Hi @crynobone 

did you check this? https://github.com/laravel/laravel/pull/5590

**Comment by crynobone** [comment]
> did you check this? laravel/laravel#5590

That's targeting Laravel 9, and you are targeting Laravel 8.

**Comment by lloricode** [comment]
> > did you check this? [laravel/laravel#5590](https://github.com/laravel/laravel/pull/5590)
> 
> That's targeting Laravel 9, and you are targeting Laravel 8.

i see, just reading around, will place it to master, thank you

**Pull request closed without merging**
