### PR TITLE
[5.1] Make attributes argument optional for relations

### PR DESCRIPTION
**Pull request by valeryq**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What's your use case?

**Comment by valeryq** [comment]
For example:
I can create model: `User::create();` without attributes, but why I cannot create relation in this style???
That's for uniform style code and similar use methods.

For model changes was at the [commit](https://github.com/laravel/framework/commit/b8ce95b859ebc532f19c78fcc6d5396fc3e014f0)

**Comment by taylorotwell** [comment]
I assume this would only be for updating timestamps. In that case, you should use the `touch` method.

**Comment by valeryq** [comment]
@taylorotwell yes, I agree with you. But why it needed in `Model.php`? I mean create with attributes argument by default.

Thank you for answer!

**Pull request closed without merging**
