### PR TITLE
[5.8] Fix issue while committing transaction 

### PR DESCRIPTION
**Pull request by aman00323**
As the bug is mention here https://github.com/laravel/framework/issues/29505, i have try to fix code as per need.

### CODE REVIEW

**Comment by driesvints** [comment]
@aman00323 it's best that you provide a thorough explanation instead of linking to an issue.

**Comment by aman00323** [comment]
> @aman00323 it's best that you provide a thorough explanation instead of linking to an issue.

@driesvints I have added condition where if the `$this->transaction` is set to `0` then it will throw error.

The earlier code will be as it is in `else` like this 
```
$this->transactions` = max(0, $this->transactions - 1);
$this->fireConnectionEvent('committed');
```

the only `else if` condition i have added which check `$this->transaction` is `0` or not, if it is then will throws error.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by aman00323** [comment]
@taylorotwell and @driesvints 

This pull request has the solution to bug **User commit when there is no transaction started**
The current code never notify user that transaction is not started and they are trying to commit.

**Current 5.8 Code**
```
        if ($this->transactions == 1) {
            $this->getPdo()->commit();
        }
        $this->transactions = max(0, $this->transactions - 1);
        $this->fireConnectionEvent('committed');
```

As the current code never going to notify user that the **transaction was not started** so user should notify that transaction they are trying to commit that is not active.

**Changes done to code**
```
        if ($this->transactions == 1) {
            $this->getPdo()->commit();
        } elseif ($this->transactions == 0) {
            throw new TransactionException;
        } else {
            $this->transactions = max(0, $this->transactions - 1);
            $this->fireConnectionEvent('committed');
        }
```

So this code will throw error if the transaction is not started. this code is placed here https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Concerns/ManagesTransactions.php#L154-L163

**Comment by mfn** [comment]
This can't go into 5.8 because it's a breaking change.

People could have unknowingly this behaviour and, while buggy, it would break their application in a minor update.

**Comment by digilist** [comment]
@mfn yes, it might break their application. But that's a good think!

Think about the current behavior:

1. An app does some stuff and commits all the changes to the database (by accident too early), even though the processing is not finished yet and there are further update statements to come
2. One of the following statements after the commit fails
3. The database is in an inconsistent state (maybe even unrecoverable)

Fixing bugs that prevent serious issues should have a higher priority than keeping BC.

But if you want to postpone this change, at least some log message with level `critical` must be emitted for the moment.

**Comment by aman00323** [comment]
I agree with @digilist current user might be facing this issue, and they never know what's  happening from laravel side, @taylorotwell please give your review to this issue.

**Comment by driesvints** [comment]
@aman00323 @digilist this is why I said to submit the pr with a thorough explanation (as it says in the pr template). If you give enough info, code examples and reasoning why this is needed then Taylor might reconsider. Feel free to resubmit with a thorough explanation.

**Comment by aman00323** [comment]
@driesvints can you re-open this PR as i have fully described [here](https://github.com/laravel/framework/pull/29649#issuecomment-523311134) why this PR is important, with detailed description.

**Pull request closed without merging**
