### PR TITLE
[5.6] Added assertUri method to TestReponse

### PR DESCRIPTION
**Pull request by gsingh1**
This PR is to add a simple helper to facilitate the checking of the TestResponse URI to ensure that in a test, when doing a request, the `TestResponse` correctly goes to an expectant URI.

Example:
`$response->assertUri($uri);`
instead of
`$response->assertHeader('Location', $uri);`

### CODE REVIEW

**Comment by gsingh1** [comment]
This would be great to have in the `5.5` branch too. How can I request this?
@taylorotwell 
Thanks

**Comment by a-komarev** [comment]
Maybe it was better to name it `assertLocation`?

**Comment by gsingh1** [comment]
Already done - [see here ](https://github.com/laravel/framework/commit/6ceca14d25783733cd3755996df86de1019ca91e)

**Comment by a-komarev** [comment]
Great, thanks. It will be much more clear now.

**Pull request merged**
