### PR TITLE
[5.7] Ability to disable register route

### PR DESCRIPTION
**Pull request by Cannonb4ll**
Sometimes you will want to disable registering in a application, this PR makes it possible to easily disable those routes.

```
Auth::routes(['register' => false]);
```

### CODE REVIEW

**Comment by JeroenBoesten** [comment]
I feel this should've been added a long time ago, needed this more than once, and it seems like a viable option since email verification now works in the same way.

**Comment by sisve** [comment]
This sounds like something that should have tests. It sounds like a security problem if a dev sets up a site, disable registering, and we accidentally include the register routes again.

On a separate note, should the password reset also have this type of toggle?

**Comment by devcircus** [comment]
Never understood why you would hide routes behind a method anyway. Your routes file should be explicit. Quicker to do it manually than to use this new option, if you know how to use your editor.

**Comment by browner12** [comment]
yah, I personally would prefer we got rid of `Auth::routes()`, but I don't think that's happening anytime soon.

**Comment by yajra** [comment]
Thanks @Cannonb4ll, sent a related PR #19452 but failed. Glad this went through! Less codes with clean implementation at least for me. No more if to toggle register. :)

```php
Auth::routes([
    'verify'   => config('site.email_verification', false),
    'register' => config('site.registration', true),
]);
```

**Pull request merged**
