### PR TITLE
[5.2] Ability to recursively replace parameters in array of Language Lines

### PR DESCRIPTION
**Pull request by AdenFraser**
I think this could be quite helpful (certainly would be for a project I'm working on at the moment), so if this is seen as useful and a worthy addition, I will create some tests for the functionality to ensure it's working correctly. 

Recursively cycles through all lines returned, and if the line is a string the makeReplacements() method is used to make replacements else the recursion continues. No parameter replacements are done on keys, since that would open up the possibility of overriding values etc.

Thoughts?

### CODE REVIEW

**Comment by AdenFraser** [comment]
Tests are failing, I shall investigate.

**Comment by taylorotwell** [comment]
Can you provide the use case with example language files?

**Comment by AdenFraser** [comment]
Of course! Where would you like them?

**Comment by taylorotwell** [comment]
here

**Comment by AdenFraser** [comment]
As a comment I presume, not in the commit?

**Comment by taylorotwell** [comment]
yes, comment

**Comment by AdenFraser** [comment]
An example based on legal document pages in different languages, purely hypothetical as this isn't what I had in mine for a use case.

```
<?php

return [

    'conditions' => [

        'allow_inquiries' => 'To allow all inquiries, solicitations, interviews, and meetings with a seller to go through the Broker first, and to not pursue any brokers elsewhere during the allotted timeframe',

        'provide_relevant_info' => 'To provide all relevant personal and financial information to the broker for the purpose of leasing property',

        'retainer_fee' => 'To pay the retainer fee of :amount which :isnotswitch refundable in the case of :circumstance.',

        'broker_fee' => 'To pay the Broker fee of :amount on the :whenswitch of an agreed-upon property.',

        'compensatory_fee' => 'To pay the compensatory fee of :amount if, having entered into an agreement, the Buyer then defaults upon the agreed-upon terms.',

        'compensatory_fee_buyer_grants' => 'To pay the compensatory fee of :amount if the Buyer grants the right of exclusive representation to another broker or enters a lease with a seller introduced by the Broker within :time after the termination of this agreement'

    ],

];
```


Loading out all individual strings:

```
<p>
    @lang('file.conditions.allow_inquiries', [])
    or
    {{ trans('file.conditions.allow_inquiries', []) }}
</p>
<p>
    @lang('file.conditions.provide_relevant_info', [])
    or
    {{ trans('file.conditions.provide_relevant_info', []) }}
</p>
<p>
    @lang('file.conditions.retainer_fee', ['isnotswitch' => 'is not', 'circumstance' => 'some things happening'])
    or
    {{ trans('file.conditions.retainer_fee', ['isnotswitch' => 'is not', 'circumstance' => 'some things happening']) }}
</p>
<p>
    @lang('file.conditions.broker_fee', ['amount' => '£15000', 'whenswitch' => 'closing'])
    or
    {{ trans('file.conditions.broker_fee', ['amount' => '£15000', 'whenswitch' => 'closing']) }}
</p>
<p>
    @lang('file.conditions.compensatory_fee', ['amount' => '£15000'])
    or
    {{ trans('file.conditions.compensatory_fee', ['amount' => '£15000']) }}
</p>
<p>
    @lang('file.conditions.compensatory_fee_buyer_grants', ['amount' => '£15000'])
    or
    {{ trans('file.conditions.compensatory_fee_buyer_grants', ['amount' => '£15000']) }}
</p>
```


Loading out as an array of strings and looping through:

```
@foreach(trans('file.conditions', ['isnotswitch' => 'is not', 'circumstance' => 'some things happening', 'amount' => '£15000', 'whenswitch' => 'closing']) as $k => $pagagraph)

    <p>
        {{ $paragraph }}
    </p>

@endforeach
````


Obviously that's still not the cleanest code above. However it's far simpler to output a number of language strings when some or all will receive replacements (potentially from a variable provided by the controller).



There are certainly a lot of other usage scenarios but this was the easiest to come up with on the fly without going into a lot of detail as to what i'm currently attempting to achieve on the project I thought this would be suitable for.

**Comment by AdenFraser** [comment]
Comment edittted*

**Comment by taylorotwell** [comment]
Hmm, I'm not sure if that is a very common use case. It seems like you could probably write a little helper function yourself to do this as well? Thanks for the suggestion!

**Pull request closed without merging**
