### PR TITLE
[5.9] Remove Mandrill and SparkPost mail drivers

### PR DESCRIPTION
**Pull request by driesvints**
We're removing these drivers because we feel that general interest in these is declining and these aren't used by any of Laravel's core services themselves. We're encouraging the community to release packages for these if there's any interest in continued use of them.

### CODE REVIEW

**Comment by CyrilMazur** [comment]
Ok, why not. But from what I see of `Illuminate\Mail\TransportManager` the list of available drivers is hard coded and there is no method to register new ones. How do you recommend someone makes a package to add extra drivers then? Extend the `TransportManager` class?

**Comment by driesvints** [comment]
@CyrilMazur: it extends `Illuminate\Support\Manager` which basically allows you to extend with any driver you wish to create.

**Comment by CyrilMazur** [comment]
@driesvints  ok thanks found it https://github.com/laravel/framework/blob/5.8/src/Illuminate/Support/Manager.php#L87-L89

This would deserve to be mentioned in the doc, apparently it was long time ago (https://laravel.com/docs/5.0/extending) and then deleted 😶

**Comment by driesvints** [comment]
@cyrilmazur feel free to send in a pr!

**Comment by b00f** [comment]
MailGun is not a transparent service. They banned their service for some countries like Iran. Sad to hear that you have removed SparkPost which is more transparent and dedicated to FOSS principle.

**Comment by gcphost** [comment]
This is disappointing. None of the mail services are actually used by the framework, why not remove them all? Stick them in a @laravelmail type repo and open that up for PRs?

I'm not a fan of installing a 40 line 8 star github package to my app, we'll likely have to make a mandrill plugin on our own to avoid this. Community drivers dont often get the scrutiny official drivers do, dont update as fast, get patched with security fixes, etc.

I also wonder how you measured that interest was declining in these drivers? We're not sending analytics back to Laravel are we? 

Thanks.

**Pull request merged**
