### PR TITLE
Adding support for CockroachDB

### PR DESCRIPTION
**Pull request by centerorbit**
Ported changes from:
https://github.com/illuminate/database/compare/v5.7.11...centerorbit:cockroach

To support Feature/Idea: https://github.com/laravel/ideas/issues/1378

### CODE REVIEW

**Comment by sisve** [comment]
Adding a database implementation without any tests at all? That's a risky move.

1. Which versions of cockroachdb does this support? 1.1? 2.0? 2.1?
2. Have this been tested with all the different database-backed drivers we already have? Things like the database-backed queue, sessions, cache, etc.

Adding this into the framework means we also take on the responsibility to document which versions we support, which we doesn't support, and limitations in the implementation.

**Comment by centerorbit** [comment]
Thanks for the feedback @sisve! The Laravel Contribution page was a little lacking in what to do in situations like these, so I appreciate the guidance. I've used Laravel for various projects for years now, but this is my first contrib back to core. Getting to know the community, if you will.

I'll look into how the Postgres tests are written and see if I can get some test coverage too.

To answer your questions:
1. I've tested this with v2.1.0 (aka latest) of Cockroach
2. This is a very good point. I actually built-out this using a side-project based on Lumen, so many of these more advance Laravel drivers are not included, I'll have to look into creating myself a Laravel instance.

Your point about taking on the documentation responsibility, etc. is very valid. But I'd also like to back it up with some reasoning why it'd be a good move:
* All currently supported databases are of the Primary/Replica nature (as traditional databases are), whereas Cockroach doesn't have a "Primary" the cluster is designed to auto-replicate out-of-the-box.
* It's incredibly easy to get a CockroachDB instance running, and I've seen their community working towards supporting other PHP platforms, such as Drupal.

**Comment by centerorbit** [comment]
@sisve I've added GrammarTest, that's the major difference in my change from what Postgres had already.

This did point out two primary differences between Postgres and Cockroach that I'd like to bring up:

Timestamp precision:
* [Postgres supports a "precision" value on time, timestamp, and interval.](https://www.postgresql.org/docs/9.1/static/datatype-datetime.html)
* Cockroach does not.

Time time zones:
* Postgres supports `time with time zone` on the Time datatype
* [Cockroach does not](https://www.cockroachlabs.com/docs/stable/time.html)

[Excerpt from Postgresql.org:](https://www.postgresql.org/docs/9.1/static/datatype-datetime.html)
`The type time with time zone is defined by the SQL standard, but the definition exhibits properties which lead to questionable usefulness.`

So, I think this is fine for most cases. Thoughts?

**Comment by taylorotwell** [comment]
Sounds like a great package.

**Comment by centerorbit** [comment]
Hey @bytewoopy and @leenooks since this PR was closed, I've been using my own fork that supports Cockroach. 

I'm using this with `"laravel/lumen-framework": "5.7.*",`

Here's what I do:

Add the following to your composer.json (where `...` is where you merge with whatever else you have).
```
"require": {
            ...
            "illuminate/database": "dev-cockroach as 5.7.11",
},
...
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/centerorbit/database.git"
        }
]
```

Then, once installed, edit your `.env` to have:
`DB_CONNECTION=cockroach`

... followed by whatever connection and auth settings that you desire.

**Comment by gnanakeethan** [comment]
Is there any idea to merge this into main source?

**Comment by centerorbit** [comment]
@gnanakeethan I don't think there is enough active interest in CockroachDB at this moment to entice the core maintainers to take on the burden of maintaining this relatively new Database. I've had success in maintaining my fork of it, and updating it along with the new Laravel versions, and I've appreciated the relative ease of compatibility between Postgres and Cockroach.

**Comment by gnanakeethan** [comment]
@centerorbit I am looking at this plugin on top of existing Laravel framework. https://github.com/nbj/cockroachdb-laravel

It seems not maintained for at least a year now.

**Comment by centerorbit** [comment]
@gnanakeethan I'm not familiar with the library you posted... I was using mine for a side-project, the nice thing about it was that it was near identical to how the built-in Postgres was handled, since Cockroach tries hard to mimic Postrges as closely as possible. I think the few differences I made were to how timezones are handled? (but as you see it's been 2 years).

When I was using it, it was very easy to update to the latest version of Laravel because that section of Laravel's core code did not change often.

One thing to note though, my version is not a plugin, but rather a fork of Laravels DB innards "illuminate/database". Had this MR gotten brought back it would have just been built in, but to use this you'll have have to likely fork what I have and update with the latests to make sure it doesn't break anything.

**Comment by Elycin** [comment]
For what it's worth, Cockroach is starting to gain serious traction since this issue was opened.

As a database engine that Laravel could utilize, with new features such as Octane around the corner getting ready to handle more concurrency and parallel processing, it seems foolish to not have a database engine that could allow the framework to scale even further.

With in regards to my experience in managing a high availability percona/galerae cluster, it is extremely hard to have a resilient configuration when you are dealing with multiple millions of rows in regards to cluster information that can withstand nodes of either master or slave type going down. If you could imagine bringing down parts of your infrastructure without compromise to fix something, this is what's available out there at google-scale.

Cockroach would be a godsend, and just to incentivize that, the following companies are listed on its website as testimonials:
- Comcast
    - "Comcast delivers customized service recommendations with CockroachDB." 
- SpaceX
    - "CockroachDB handles all of SpaceX's operational data for the largest constellation of satellites in the world"
- Doordash
    - "DoorDash, the leading delivery service in the U.S. stores all their delivery order data in CockroachDB"
- LUSH
    - "With CockroachDB, we can pick and choose where data is stored, satisfying both data sovereignty concerns and the need to have a global view of data. This is really powerful for us because it allows us to be smarter about how we handle stock. And that’s going to be a very large data set." 
    - 950 Stores, 49 Countries, 165K transactions per day
    - Case Study: https://resources.cockroachlabs.com/case-study/lush-case-study

Full list of customer success stories: https://resources.cockroachlabs.com/customers 

@taylorotwell forgive me for the tag, but I hope that this could be on the horizon for the future of the Laravel project. I'm excited as a developer to see what you've done, and I hope you find this worth considering, perhaps within your own native implementation.

**Comment by Elycin** [comment]
Chiming in further to now say that Netflix is now using CockroachDB.

image

https://netflixtechblog.com/towards-a-reliable-device-management-platform-4f86230ca623?gi=386877bfebeb

**Comment by GrahamCampbell** [comment]
Most people don't operate at Netflix scale, so what they are doing is largely not relevant.

**Comment by xwiz** [comment]
@GrahamCampbell I have considered cockroackdb several times to be honest and I kinda agree with what @Elycin said to some extent -- being that galera cluster configurations tend to be highly sensitive though quite reliable, bringing unsynchronized nodes up to speed can easily take from seconds to hours. It would be great to create a laravel variant built for just scalability and have CI setup for load testing and such, ideas and stuff like this can go in there first before adopted into the main core and enthusiasts like me can check it out and make contributions that will eventually make the framework better. Currently Laravel can do a lot better in terms of counts, pagination, bootstrap configurations, and app singletons management, [model resources](https://github.com/laravel/framework/discussions/38322) and probably more stuff (I noticed the ideas don't really get attention, maybe it's a small political hub).

**Comment by Elycin** [comment]
@GrahamCampbell scale is only one reason out of many, the other reasonings mentioned above are still vastly relevant. It doesn't make sense to exile that demographic of developers who are invested in your framework because one justification isn't relevant, does it?

**Comment by dennisprudlo** [comment]
@Elycin I think what he meant with "most people don't [...]" is not that Laravel shouldn't support it, but rather that it's debatable whether this needs to be in the core. Taylor said this would make a great package. But including it into core would mean the team at Laravel would have to maintain it.

**Comment by corsair** [comment]
> Most people don't operate at Netflix scale, so what they are doing is largely not relevant.

This perception and attitude are entirely problematic. @taylorotwell 

The point isn't that there aren't enough Laravel developers operating at the Netflix level; it's that teams will entirely overlook and disregard your platform, Laravel, as viable if it isn't immediately apparent that you provide resources and options for scalability.

Building to scale is vital for consideration, whether you're a medium or large operation. Companies will typically prefer to not spend resources where they don't need to. Thus, the prospect of having to develop a package will be the last resort before any other options if a framework already supports this within its core.

In addition to now including Netflix, let's also consider the remaining companies who have publicly stated they utilize CockroachDB:

- Comcast ($103.6B in revenue annually)
- eBay ($10.3B annually)
- Bose ($3.6B annually)
- Doordash ($2.9B annually)
- SpaceX ($2B annually)
- Shipd ($1B annually)
- Nubank ($1B annually)
- Lush ($535M annually)

If you're okay with the official sentiment of Laravel to be solely focused on "**the people who don't operate at Netflix level**", then that's _fine_. However, when developers communicate their frustrations of this, whether for their own projects or when representing a team/company interested in giving Laravel a try, you need to accept this will drive those developers away.

I've been using Laravel since 2.0 and it has made working with PHP elegant and wonderful, but it is the aforementioned mindset that unfortunately makes considering Laravel for larger projects or startups less of an option for myself and clearly many others.

**Comment by leenooks** [comment]
So I've just forked nbj/cockroachdb-laravel and merged updates that I've found and implemented myself. I'm using Cockroach in a project, so as I find more issues I'll aim to keep my fork up to date [leenooks/cockroachdb-laravel](https://github.com/leenooks/cockroachdb-laravel). I'm currently working with Laravel 8.

(For the record, I had a bunch of migrations that used for postgresql before I switch out the DB to cockroach. Those migrations failed, and while I didnt look into why, after I forked and fixed up [leenooks/cockroachdb-laravel](https://github.com/leenooks/cockroachdb-laravel), they then worked without needing to be changed.)

**Pull request closed without merging**
