### PR TITLE
[5.5] Added dd_if helper

### PR DESCRIPTION
**Pull request by Grummfy**
Sometimes you want to debug some value but under some condition. So instead of writing

```
if ($test) {
    dd($value1, $value2, ...);
}
```

you can now write

```
dd_if($test, $value1, $value2, ...);
```

### CODE REVIEW

**Comment by GuidoHendriks** [comment]
Implementation debugs if the `$boolean` is false. 😕

**Comment by Grummfy** [comment]
oups, fixed.

**Comment by GrahamCampbell** [comment]
I think this is a bad idea tbh, because it encourages leaving dd statements in the code.

**Comment by Grummfy** [comment]
Why it encourage leaving dd in the code? It's jsut a big helper like dd is but with a bit of fancy.

**Comment by concept-core** [comment]
Please don't add this. I can only imagine how many people will keep it in there on mistake.

I don't think this should be a feature of the framework at all since it already has lots of helpers.

Would love to see that the trend for adding helpers to laravel would stop finally and focus on good features.

**Comment by sisve** [comment]
1. We clearly need the matching `dump_if` helper to accompany this PR.
2. Where are the tests?

**Comment by ConnorVG** [comment]
From what I can tell, this means that you're willingly (currently) *committing* `dd` calls into your live projects whilst wrapping them in `if` calls. I **strongly** advise against this. You *should* never be, even with `if` checks, running code in production that could print out any sort of debug. Not only would it be very jarring for a user who accidentally bumps into this but it's also a huge security flaw... Depending on what is being dumped.

You need to not look at debug functions (like `dump` or `dd`) in the same perspective as the non-debug functions that have `_if` variants (like `abort`). They are **not** the same.

This has a big 👎 from me, though it is a good example to use when describing what "debug" functions actually are and where and when you should be using them.

**Comment by Grummfy** [comment]
Thanks for your feedback.
In my day to day life as developer I find it useful, as useful as the dd is. I never use dd in production, none as dd_if, the purpose is an help.

@ConnorVG thanks for the big feedback.

I really understand how it can be badly use, but as my day to day developer I see a need for this.

**Comment by 36864** [comment]
It's fairly easy to add your own helpers to your projects. If you find it that useful, you could even make a package for it.

Doesn't belong in the core though.

**Pull request closed without merging**
