### PR TITLE
refactor collection

### PR DESCRIPTION
**Pull request by lawsonjt**

### CODE REVIEW

**Comment by jmarcher** [comment]
Why? And just leave an `use` there...

**Comment by lawsonjt** [comment]
Whoops on the 'use'.  The reason for the PR is because I first learned about Collection::make() through this file when I was learning the basics and poking around.  It wasn't until later that I learned you can just do collect().  Shorter, and no namespace needed.

**Comment by jmarcher** [comment]
This change makes no sense.

**Comment by 36864** [comment]
We should be striving to use less helpers, not more.

**Comment by jmarcher** [comment]
@36864 I would not say that using helpers is bad, but this change does not solve any issue is just a matter of taste.

**Comment by driesvints** [comment]
This is fine as it is. Please don't send in PRs without an explanation.

**Pull request closed without merging**
