### PR TITLE
[7.x] TableExists, ColumnListing, DropIfExists are updated

### PR DESCRIPTION
**Pull request by urlportal**
Hi. Sorry for my English.
Schema::dropIfExists method works incorrectly if schema contains in the table name. For example `Schema::dropIfExists('some_schema.some_table')` will create a request: 
```if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'some_schema.some_table') drop table "some_schema"."some_table"```
but in table `INFORMATION_SCHEMA.TABLES` there is no record with `TABLE_NAME = 'some_schema.some_table` but isset record with `TABLE_NAME = 'some_table' AND SCHEMA_NAME = 'some_schema'`. As a result, the table is not removed, but the migration is performed successfully.
I corrected the mistake localy, but later found in the branch [8.x] the best solution using `object_id`

### CODE REVIEW

**Comment by urlportal** [comment]
@taylorotwell please tell me what I did wrong? DropIfExists not working correctly. 7 version still supported. Unfortunately the company in which I work is not planning update Laravel up to 8 yet.

**Comment by Jubeki** [comment]
@urlportal Laravel 7 is no longer supported:
https://laravel.com/docs/8.x/releases#support-policy
Security Fixes only went until March 3rd, 2021

**Comment by Jubeki** [comment]
Maybe your company should give https://laravelshift.com a try for upgrading.

**Comment by urlportal** [comment]
> @urlportal Laravel 7 is no longer supported:
> https://laravel.com/docs/8.x/releases#support-policy
> Security Fixes only went until March 3rd, 2021

Thank you!

**Pull request closed without merging**
