### PR TITLE
[5.3] Add redirect helper to router

### PR DESCRIPTION
**Pull request by brayniverse**
As proposed on [this internals thread](https://github.com/laravel/internals/issues/172), this PR adds a redirect helper to the Router for those occasions when you want to redirect from an old route to a new route.

Route caching still works because the redirection is handled by an internal controller.

### CODE REVIEW

**Comment by mul14** [comment]
I love `Route::redirect()` idea. But, I curious. Why you don't use `Route::macro()` instead?

```php
Route::macro('redirect', function ($previous, $destination, $status = 301) 
{
    return app('router')->any($previous, function() use ($destination, $status) 
    {
        return redirect($destination, $status);
    });
});

// Usage
Route::redirect('/about_us', '/about');
```

The behaviour is exactly same.

**Comment by garygreen** [comment]
@mul14 macros break route caching. Imo macro ability should be removed from the router entirely for that reason.

**Comment by brayniverse** [comment]
@mul14 can you use route caching if you are using macros?

**Comment by mul14** [comment]
Aha, thank you for pointing me out.

**Comment by taylorotwell** [comment]
I suggest making this a package.

**Comment by brayniverse** [comment]
Ah that's a shame. Thanks for considering.

**Comment by garygreen** [comment]
@taylorotwell please could you reconsider this PR? I'm coming across more and more websites that need to redirect existing urls but there's no nice way of doing this currently. With this PR, it supports caching the routes file as well.

**Comment by brayniverse** [comment]
I did end up making this into a package if anybody was interested.

https://github.com/brayniverse/laravel-redirect-helper

**Comment by garygreen** [comment]
@bryannielsen nice. Route caching still works I assume? 😄

**Comment by brayniverse** [comment]
@garygreen yup, there is a `RedirectController` the package is using to handle the redirect, so caching still works.

https://github.com/brayniverse/laravel-redirect-helper/blob/master/src/RedirectController.php

**Comment by garygreen** [comment]
That's cool. I usually do redirects at the nginx/apache level but having it built into the app is much better as everything stays version controlled, and can even use the package to pull redirects from the database that get added thru the admin panel or something. Good job 👍

**Comment by brayniverse** [comment]
@garygreen thank you :) let me know if you have any feedback; on the [repo's issues](https://github.com/brayniverse/laravel-redirect-helper) of course, don't want to spam this thread.

**Pull request closed without merging**
