### PR TITLE
[5.5] [WIP] Allow custom string passwords in Encrypter class

### PR DESCRIPTION
**Pull request by Jameron**
My last request was closed with comment: "No need for any of this. All you need to do is:

> $encrypter = new Encrypter('key', 'cipher');"

The goal is to allow custom passwords when encrypting data, the code I provided allows for this by converting a password string into an acceptable key to match with the cipher. e.g.

`        $iterations = 1000;
        $salt = $this->key;
        $key = hash_pbkdf2('sha256', $password, $salt, $iterations, 32);
`

As suggested, if I were to instantiate the Encrypter class with a string password that doesn't match the cipher, then an exception is raised.

`$string` = 'secret message';`
`$pass = 'swordfish';`

`$encrypter = new Encrypter($pass, 'AES-128-CBC');`

`The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.`

Please reconsider or provide a better explanation.

### CODE REVIEW

**Comment by sisve** [comment]
History: https://github.com/laravel/framework/pull/18068 https://github.com/laravel/framework/pull/18090 https://github.com/laravel/framework/pull/18091

Your current implementation of encryptWithPassword makes assumptions on the parameters to hash_pbkdf2. What if the user wants to use another algorithm, or another number of iterations? What about generating another key length for another cipher? Did you know that the salt parameter is documented as "This value should be generated randomly"?

 Calling `encrypt($payload, true, $user->symmetricKey)` gives a result that decrypt cannot decrypt because the later will do a hash_pbkdf2 on the key I send in.

Many of previously mentioned issues is still present; what happens if I call `encrypt($payload, true, $user->symmetricKey)` and symmetricKey is null? That is clearly an error in my application code, but the framework will not tell me about it at all, instead defaulting to another key. Imagine this happening for thousands of users that now share a common key, instead of the per-user key I thought it used...

**Comment by Jameron** [comment]
Thanks for your feedback, are you suggesting I revise the pull request to address your issues, or just trash this idea altogether?

I feel strongly that unique password encryption should be available to users. I am willing to do the work necessary to make this feature possible, and merge into Laravel.

**Comment by sisve** [comment]
I think that the `$encrypter = new Encrypter('key', 'cipher');` is enough to do what you want; you can specify a cipher and a per-user key and you get the requested functionality. The current cipher can be read from the config, and the key can be generated by hash_pbkdf2 as you've shown earlier.

**Comment by Jameron** [comment]
I see, so add this logic to application rather than do the work to get into the framework. My only question now is, when is it necessary to add functionality to a framework and when to place directly into application? My thoughts were this would be useful to Laravel users and promote encryption.

**Pull request closed without merging**
