### PR TITLE
[5.5] Simplify static variables initialization

### PR DESCRIPTION
**Pull request by vlakoff**

### CODE REVIEW

**Comment by jmarcher** [comment]
No description provided.

I think that the code before is fine, it prevents unnecessary re-initializations of static variables.

**Comment by vlakoff** [comment]
@jmarcher Such initialization is executed only on first function call.

(and no description because "title says it all")

**Comment by vlakoff** [comment]
@taylorotwell Could you reconsider it, please?

(by the way, yes, caching the array using a static variable is clearly worth it)

**Comment by sisve** [comment]
These things are copy/pasted from https://github.com/danielstjules/Stringy/blob/f9c2e0ae36b613e7c82688f308778bd081eccc85/src/Stringy.php#L1859. There's no need to change it at our end, it would only make it harder to update the code with new rules.

**Comment by vlakoff** [comment]
Actually, this function already has been modified on the laravel end. My changes don't make the manual updating easier nor harder.

(maybe slightly easier, in fact)

**Pull request closed without merging**
