### PR TITLE
[7.x] Add set message to validation exception

### PR DESCRIPTION
**Pull request by MammutAlex**
This is a compromise for adding a custom message to a validation error
Previous PRs (#26798,#22045,#28246,#21863, #22823) have added a translator to `ValidationException`

Now you can customize your message (localization or just your message)
```
public function render($request, Throwable $exception)
{
    if ($exception instanceof ValidationException) {
        $exception->setMessage(__('Lang error message'));
    }
    return parent::render($request, $exception);
}
```

### CODE REVIEW

**Comment by driesvints** [comment]
I really don't understand why people keep on wanting to translate this. This is an internal exception message that shouldn't bubble up to the end user.

**Comment by MammutAlex** [comment]
@driesvints in my case
when rendering exception to JSON the message field is passed
on the frontend, I display the message field in the notification

**Comment by taylorotwell** [comment]
But you aren't supposed to. You are supposed to display the actual validation messages that are translatable.

**Comment by infostreams** [comment]
@taylorotwell @driesvints The reason why people want to translate this is because

a) it's in the JSON coming from the API
b) everything else in that response is translated

I don't understand why you don't want to translate it ("this sentence is an internal sentence!" is the answer?), but if you insist it's not for public consumption perhaps you could turn it into something like INVALID_DATA or VALIDATION_FAILED instead of "The given data was invalid."? That way at least the intent is communicated. I don't think I see the use case of this part of the response otherwise. Are we supposed to just ignore it (then why is it there)? Log it to our error trackers? I'm stumped.

**Comment by r-kujawa** [comment]
@infostreams I totally agree with you. It would be great to at least be able to modify the message string from inside the FormRequest class, that way the message could be specific to an actual action. For example, if creating a new user, you could set that error to 'Could not create new user.'

Without this option I don't see the point of returning the default message either.

I am willing to submit a PR that makes this happen from inside the FormRequest, but don't want to waste my time on this if it will be denied.

Currently I'm checking if error's exist and defining the main error message on the front end, but would be nice to have the error message coming from the FormRequest itself, in case I want to use the same message in different parts of my application.

**Comment by driesvints** [comment]
We've already said multiple times on various other issues and prs that we won't be changing this. We think this should be done in userland. Sorry.

**Comment by infostreams** [comment]
I understand that you don't want to change it, I just don't understand why you're sending it to the end user in the first place.

**Pull request closed without merging**
