### PR TITLE
[11.x] Allow list of rate limiters without requiring unique keys

### LINKED ISSUE #53157: the RateLimiter `Limit::perSecond` not working as expected for the queue jobs
### Laravel Version

11.27.2

### PHP Version

9.3.12

### Database Driver & Version

_No response_

### Description

I tried to use the new Laravel jobs per second rate limiter as described by @timacdonald in #48498. 
we are using a third-party web service with the following rate limits:
* 1 request/second
* 30 requests/minute 

I used the following config for the rate limit:
```php
RateLimiter::for('webservice_api', fn () => [
    Limit::perMinute(30),
    Limit::perSecond(1),
]);
```

Expected output:
Limit job 1/second and 30/minute.

Actual output:
The job is always rate-limited and does not execute at all.

### Steps To Reproduce

1. Create a fresh Laravel app and add  the following rate limiting config to `AppServiceProvider`:
```php
public function boot(): void
{
    RateLimiter::for('webservice_api', fn () => [
        Limit::perMinute(30),
        Limit::perSecond(1),
    ]);
}
```

2. Create a new job with the following code:
```php
<?php

namespace App\Jobs;

use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use Illuminate\Queue\Middleware\RateLimited;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class SendToWebService implements ShouldQueue
{
    use Queueable;

    public function handle(): void
    {
        Http::post('https://httpbin.org/post');
        Log::debug('Done');
    }


    public function middleware(): array
    {
        return [new RateLimited('webservice_api')];
    }
}
```

3. Dispatch the job multiple times:
```php
for ($i = 0; $i < 10; $i++) {
    dispatch(new \App\Jobs\SendToWebService());
}
```

4. And, run the `php artisan queue:work`

Expected behavior:
Execute one job per second.

Actual behavior:
Not executing at all and always rate limited.

### PR DESCRIPTION
**Pull request by timacdonald**
This PR ensures that rate limiters specifying multiple limits will always have unique keys.

## The issue.

```php
RateLimiter::for('limiter-name', fn () => [
    Limit::perSecond(1),
    Limit::perMinute(30),
]);
```

This rate limiter will always fail. No request would ever get through. Zero. Nada.

 This is because both limits share the same key. The docs specify that _If you're assigning multiple rate limits segmented by identical by values, you should ensure that each by value is unique_

Screenshot 2024-10-16 at 09 52 04

This is fine, but also can be something easily forgotten; bit of a footgun.

## The improvement

This PR attempts to improve the situation by ensuring that when a list of limits has duplicate keys they are modified to be unique.

```php
RateLimiter::for('limiter-name', fn () => [
    Limit::perSecond(1),
    Limit::perMinute(30)->by(Auth::user()),
    Limit::perDay(500),
]);
```

In this above example, the first and the last limits would have their key modified to be unique.

Although this is a breaking change, it only breaks in already broken situations, so I see this as an overall improvement.

I don't feel like we need to update the docs. This is just a fallback fix for those rare times it is held wrong.

---
fixes https://github.com/laravel/framework/issues/53157

### CODE REVIEW

**Comment by NickSdot** [comment]
@gcg wasn't this PR all about that you no longer need to give unique names?

**Comment by gcg** [comment]
> @gcg wasn't this PR all about that you no longer need to give unique names?

Still did not test ALL possible combinations but I was using the exact same example w/out giving unique names and after this PR, those 2 limiters that returns multiple limits in an array w/out unique names started failing all requests. 

I will share more information but giving unique key names manually seems to be working and it's clearly documented so I am in the blame here :) I am reporting live here just in case it happens to someone else.

**Comment by timacdonald** [comment]
Thanks for letting us know, @gcg.

Please let us know what you find out. My gut feeling is that your previous set up, sharing the same keys, was likely not working as expected even if it seemed to be working.

Keep me posted.

**Comment by timacdonald** [comment]
And sorry for the troubles!

**Comment by gcg** [comment]
> Please let us know what you find out. My gut feeling is that your previous set up, sharing the same keys, was likely not working as expected even if it seemed to be working.

yeah, you are probably right. I had 2 limiters that returns list limits, one of them is so rarely use and the other route has it's own custom rate limits built in predating laravel mw, even if the ratelimiter didn't work before for that case, I probably didn't notice and only noticed once we started failing requests. 

> Keep me posted.

I redeployed rate limiters after uniquely naming everything and now it's back to normal. 

> And sorry for the troubles!

It's not your fault that I missed the warning in the documentation, as u stated, it wasn't probably working as it should from the beginning.

**Pull request merged**
