### PR TITLE
[5.5] Modify find eloquent collection method to accept collection

### PR DESCRIPTION
**Pull request by amaelftah**
this **PR** will allows eloquent collection **find()** method to accept **collection**

```php

$users = User::get()->find(collect([20,40,30]))

```

### CODE REVIEW

**Comment by a-komarev** [comment]
Maybe it will be better to check for ``?

```php
if ($key instanceof \Illuminate\Contracts\Support\Arrayable) {
    $key = $key->toArray();
}
```

**Comment by Te7a-Houdini** [comment]
@a-komarev thanks

**Comment by carusogabriel** [comment]
@Te7a-Houdini Do you have a use case better than `collect([1, 2, 3])`?

You are duplicating and complicating some unnecessary work :sweat_smile:

**Comment by denaje** [comment]
@carusogabriel 

```php
$collection = collect();

// Complicated logic

$users = User::get()->find($collection);
```

**Pull request merged**
