### PR TITLE
[10.x] Added many-to-many relation trough set collumn

### PR DESCRIPTION
**Pull request by Daniel-H123**
### _**Note: This is my first contribution to the laravel framework**_
 
I recently worked on a project, where I came across a many-to-many relation with the keys in a set collumn. I couldn't find any 'good' solution to add the relation so I thought, why not add it, since they can be usefull in my opinion. Please note that i'm not experienced in modifying the laravel framework code, since this is my first pr, so any feedback is dearly appreciated.

### Summary:
The ~~`hasManyInSet`~~ `belongsToManySet` relation allows you to define a many-to-many relation between two tables, using a set collumn, so without having to use a pivot table. While a pivot table is recommended, it is still usefull to use the many-to-many relation in this form.

### Situation:

Users:
| id | username | groups |
|--------|--------|--------|
| 1 | User1 | 1,2,5 |
| 2 | User2 | 3 |
| 3 | User3 | | 

Groups:
| id | name |
|--------|--------|
| 1 | Group1 |
| 2 | Group2 |
| 3 | Group3 |
| 4 | Group4 |
| 5 | Group5 |

### Example: 

You can setup the relation for the user in this example in the model with `belongsToManySet()`.

```php
<?php // Model

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    public function groups() 
    {
        return $this->belongsToManySet(Group::class, 'groups', 'id');
    }
}
``` 

You can call the relation just like any other relation in Laravel.

```php
<?php // Controller

namespace App\Http\Controllers;

use Illuminate\Database\Eloquent\Model;

class UserController extends Controller
{
    public function getUsersWithGroups() 
    {
        $users = User::select('*')->with('groups')->get();
        return response()->json($users);
    }

    public function getUserGroups($user) 
    {
        $users = User::find($user->id)->groups;
        return response()->json($users);
    }

}
```

### CODE REVIEW

**Comment by Daniel-H123** [comment]
After further thought it should be something like `belongsToManySet`, but that just doesn't sound right.

**Comment by Rizky92** [comment]
I'm not sure how it'll go. I personally don't see this type of database structure in the wild, but _who knows_?

Anyway, this looks like a new definition of relation rather than extension of existing `BelongsToMany`, since `BelongsToMany` requires explicit intermediate table. You'll also need to figure out how to do this:

```php
Group::first()
    ->users()
    ->createMany([
        // ...
    ])

**Comment by Daniel-H123** [comment]
I agree. I'm currently rewriting the relation extending the relation class directly. It currently does not work both ways, so that is also a problem that needs to be solved.

**Comment by akr4m** [comment]
The `belongsToManySet` relation offers a unique and streamlined approach to many-to-many relationships in Laravel. With further refinement, it has potential to be a valuable addition for specific use-cases I think.

**Comment by AndrewMast** [comment]
Correct me if I am wrong, but wouldn't this relation only work when on a MYSQL connection because `FIND_IN_SET` is exclusively a MYSQL function? Several [PRs](https://github.com/search?q=repo%3Alaravel%2Fframework+find_in_set&type=pullrequests) and [issues](https://github.com/search?q=repo%3Alaravel%2Fframework+find_in_set&type=issues) over the years have gone nowhere and have been closed because of this. I am all for making the SQL grammar work on other connections by using other [sql functions](https://stackoverflow.com/questions/6979813/alternative-to-find-in-set-in-sqlite/6980615#6980615), but I think it would be best for this to be a standalone package. Honestly, if this was a package, I would have used it in several of my projects already.

**Comment by Daniel-H123** [comment]
Thanks for your message @AndrewMast 

> Correct me if I am wrong, but wouldn't this relation only work when on a MYSQL connection because `FIND_IN_SET` is exclusively a MYSQL function?

This is true, and something I am working on at the moment. I'm looking to extend laravel with a custom whereInSet function, but I think it would be difficult to make it efficiënt (with using indices)  and usable with all db engines.

I'll try to make it work, but if it doesn't, it would be inpractical adding it in laravel itself, so i'll just publish it as a package as you suggested.

**Comment by Daniel-H123** [comment]
I added a new whereInSet() function to the Laravel builder, so it uses the like boolean instead of the MySQL-only FIND_IN_SET function. It should work now with all other supported Laravel database engines. I'm still figuring out if there are things that I could have made more efficient, and there is also some logic that needs to be added, for example, adding and removing items from a set. However, I would appreciate any feedback on the quality or usefulness of the current revision of my code.

**Comment by driesvints** [comment]
@Daniel-H123 are you still working on this? Draft prs aren't looked at.

**Comment by Daniel-H123** [comment]
> It will be better if the `whereInSet` method generates sql something like this:
> 
> ```sql
> SELECT * 
> FROM `users` 
> WHERE  `groups` REGEXP '(^1$|,1,|,1$|^1,)';
> ```
> 
> I think it would be faster for performance.

Thanks for your suggestion. I think `REGEXP` is a mysql specific function right? If it works, i'm happy to add it, but i'm trying to avoid creating it specificly for one DB engine.

**Comment by driesvints** [comment]
Gonna close this one now. Feel free to resend it if you want.

**Pull request closed without merging**
