### PR TITLE
[5.2] Validation test

### PR DESCRIPTION
**Pull request by arrilot**
To prevent #11426 in the future

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please send to 5.1.

**Comment by GrahamCampbell** [comment]
We want to make sure it stays correct on there too, right?

**Comment by arrilot** [comment]
Hmm, makes sense

**Comment by GrahamCampbell** [comment]
Laravel 5.1 is LTS, so all bug fixes will be going there for at least 2 more years.

**Pull request closed without merging**
