### PR TITLE
[5.5] Reset Response content-type.

### PR DESCRIPTION
**Pull request by lucasmichot**
Reset Response content-type.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why?

**Comment by lucasmichot** [comment]
Because you would find yourself with the original content-type, matching the content passed in the constructor.

```php
$response = new \Illuminate\Http\Response(['foo' => 'bar']);
$response->setContent('foobar');
echo $response->headers->get('Content-Type') . PHP_EOL;
// application/json
```

This PR fixes that.

**Comment by taylorotwell** [comment]
I still don't get it. You will have to provide a more thorough and detailed explanation before I can merge this.

**Comment by lucasmichot** [comment]
```php
// 1. you create a Response and pass an array in the constructor, you response will be interpreted as a JSON response and the Content-Type header will be set to application/json
$response = new \Illuminate\Http\Response(['foo' => 'bar']);
// 2. if you change the content of this response, passing a simple string, the content-type should not be application/json anymore
$response->setContent('foobar');
// 3. At the moment if we change the content of a Response, after setting it with an array (or arrayable, jsonable..etc..), the content-type stays application/json forever and do not take into consideration the new content
echo $response->headers->get('Content-Type') . PHP_EOL;
```

**Comment by GrahamCampbell** [comment]
Doesn't work.

```
$response = new \Illuminate\Http\Response('{"foo": "bar"}', 200, ['Content-Type' => 'application/json']);
```

Will not work, which means json responses that get converted to illuminate responses in the exception handler get broken.

**Pull request merged**
