### PR TITLE
[5.5] Return an array, not a collection

### PR DESCRIPTION
**Pull request by lucasmichot**
Return an array, not a collection.

### CODE REVIEW

**Comment by laurencei** [comment]
Why?

I dont see the negative of using the collection here?

**Comment by lucasmichot** [comment]
Both are fine, but docblocks indicate that we are supposed to return array

**Comment by laurencei** [comment]
Can we change the docblock then?

It's a public function - so changing it just creates comparability issues for no real gain here?

**Comment by lucasmichot** [comment]
Well te result is actually used as an array and not as a collection, and only by  \Illuminate\Console\Scheduling\ScheduleRunCommand::handle

Up to @taylorotwell , either apply this PR, either change the return docblock to `\Illuminate\Support\Collection`

**Comment by laurencei** [comment]
> What about people extending Schdule then?

But if they are *already* extending it - then they are currently getting a collection and are used to it (regardless of the docblock). If they are compensating and converting it to an array it might now break?

**Comment by lucasmichot** [comment]
Actually you cannot extend a class if the docblock is different. But you can still use a Collection as an array.

There is an error here, either the docblock, either the return
I let @taylorotwell make his choice

**Comment by browner12** [comment]
@lucasmichot can you explain this?

> Actually you cannot extend a class if the docblock is different. 

I don't think that's actually true. Docblocks won't cause errors if they are different.

**Comment by taylorotwell** [comment]
Just change the doc block.

**Comment by lucasmichot** [comment]
See https://github.com/laravel/framework/pull/20104

**Pull request closed without merging**
