### PR TITLE
[11.x] Added `for` method to Eloquent models

### PR DESCRIPTION
**Pull request by ash-jc-allen**
Hey!

This PR proposes a new `for` method that helps set foreign keys on models. It's a fresh (and simplified!) take on my past attempt from a couple of years ago: https://github.com/laravel/framework/pull/42467

I think a major drawback of the previous approach was that it wasn't obvious whether `for` would be used in queries, or for setting fields on models. So it got a bit confusing!

In this approach, I've completely ditched the Builder side of things. Although on the surface, it looks like it would have been nice, I think it would have caused more issues than it solved! So, instead, the `for` method only exists on the Model classes.

So you can call it like so:

```php
use App\Models\Comment;
use App\Models\Post;
use App\Models\User;

// Imagine these are from a request or something instead.
$post = Post::first(); // ID: 123
$user = User::first(); // ID: 456



// Before:
$comment = Comment::create([
    'comment' => 'hello',
    'post_id' => $post->id,
    'user_id' => $user->id,
]);



// After (using the "for" method):
$comment = Comment::make(['comment' => 'hello'])
    ->for($post)
    ->for($user);

$comment->save();
```

Assuming there is a `posts` and `users` relationship, the comment will now have the following data set:

```text
'comment' => 'hello'
'post_id' => 123,
'user_id' => 456,
```

There's also the ability to specify the relationship name if needed:

```php
Comment::make(['comment' => 'hello'])
    ->for($post, 'blogPost')
    ->for($user)
    ->save();
```

I also quite like how it almost reads like a human-readable sentence when it's written like this too:

```php
new Comment()
    ->for($post)
    ->for($user)
    ->fill(['comment' => 'hello'])
    ->save();
```

Hopefully this is something that other devs would also find useful. Although it's a relatively small change, I like the way that it can reduce the likelihood of typos and also uses a similar syntax to model factories. 

But I completely understand if it's not something worth merging in. I'd kick myself if I didn't try and scratch the itch though haha!

If it's something you might consider merging, please let me know if there's anything you might want me to change 😄

### CODE REVIEW

**Comment by Bosphoramus** [comment]
Yes, please! 🤩🤩

**Comment by caendesilva** [comment]
I love it. The implementation looks simple and easy to maintain, whilst the feature is very useful.

**Comment by ahinkle** [comment]
I can see the benefit, but it feels a bit ambiguous and might raise questions if I came across it while browsing the code—or for juniors who might struggle to decide which approach to use. The existing methods are a bit more explicit in their intent.

Cool idea though!

**Comment by ericwoelki** [comment]
> Wouldn't it be better if this was powered by actual relationship method assignments? So
> 
> ```
> $store->owner()->assign($user);
> ```
> 
> If I recall correctly

You already can do `$model->relation()->associate($related)` for cases like this. [Docs](https://laravel.com/docs/11.x/eloquent-relationships#updating-belongs-to-relationships)

**Comment by ericwoelki** [comment]
@osbre Fair, I was pointing out that the method is `associate()` rather than `assign()`. I agree with you that deferring to it behind the scenes for the proposed `for` could simply its implementation and also has the benefit of populating the relation.

**Comment by Mejvas** [comment]
This change makes sense because building relations in this way is already implemented in `Illuminate\Database\Eloquent\Factories\Factory`.

**Comment by morloderex** [comment]
It doesn't look like this will work for all relations specifically i am thinking of ManyToMany relations and Morphed relations.

**Comment by taylorotwell** [comment]
I think I will hold off on this one for now. A bit worried such a short, common word could already exist in applications and cause breaking changes. I also wonder if you could just use factories.

**Comment by ash-jc-allen** [comment]
Hey @taylorotwell, that's totally cool! I'm glad I got a chance to try and scratch an itch. I'd have only kicked myself if I hadn't tried contributing it 😄

**Pull request closed without merging**
