### PR TITLE
[7.x] Correct grammar

### PR DESCRIPTION
**Pull request by LeoNguyenHQ**

### CODE REVIEW

**Comment by browner12** [comment]
all of your "a" to "an" changes look good, but some of the other changes are unnecessary, or a matter of preference.

For example:

```php
/**
  * Adds a where condition using row values.
  *
```

is fine.  I guess technically it is not a complete sentence, but neither is "Add a where condition using row values."

**Comment by laristine** [comment]
@browner12 Thank you for the comment! I certainly see third-person verbs (like `Adds`) can be a matter of preference, and this is mostly about consistency. The [file you quoted](https://github.com/laravel/framework/pull/33815/files#diff-cc3d43e01028390141596ae0da939930) has 148 functions, almost all of which already use imperative mood (like `Add`) in PHPDoc. While correcting grammar in the file, I moved the remaining 5 to the imperative mood camp. In fact, `Add a where condition using row values.` is a complete sentence.

I haven't found an official stance on this yet. Laravel's [Contribution Guide](https://laravel.com/docs/7.x/contributions#phpdoc) has this valid PHPDoc example below, so I suppose it's a signal that it's okay to move toward this style?

```php
/**
 * Register a binding with the container.
 *
 * @param  string|array  $abstract
 * @param  \Closure|string|null  $concrete
 * @param  bool  $shared
 * @return void
```

That said, I'm totally okay with reverting these tense changes.

**Comment by browner12** [comment]
I think you'll have more luck if you keep the PRs super simple and 1 dimensional.  I would recommend opening a new PR with ***just*** the "a" to "an" and "an" to "a" fixes.   Makes it really simple for the team to review.

**Comment by laristine** [comment]
Duly noted. I appreciate your advice, @browner12. :)

**Pull request closed without merging**
