### PR TITLE
[5.8] Add json extension to composer requirements

### PR DESCRIPTION
**Pull request by browner12**
retargeting master for #25831

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
@browner12 Could you also add this to the individual illuminate package composer.json files in the cases where those modules depend on the extension too please?

**Comment by browner12** [comment]
doesn't Taylor have some script that splits the stuff up automatically? or are you saying within this repo in each of the `src` folders?

**Comment by GrahamCampbell** [comment]
I'm meaning within this repo. There are multiple composer.json files that need updating. :)

**Comment by GrahamCampbell** [comment]
Like, for example https://github.com/laravel/framework/blob/master/src/Illuminate/Http/composer.json.

**Comment by browner12** [comment]
gotcha, sure thing.

**Pull request merged**
