### PR TITLE
[5.4] fix: stop worker if a database disconnection occured

### PR DESCRIPTION
**Pull request by Broutard**
fix issue #19072

### CODE REVIEW

**Comment by tillkruss** [comment]
Title please.

**Comment by taylorotwell** [comment]
I don't think we need a shouldStop and a shouldQuit.

**Comment by Broutard** [comment]
@taylorotwell the previous valid commit #96b465e only stop() the worker.

**Comment by Broutard** [comment]
Maybe a simple reconnect should do the trick...

**Comment by taylorotwell** [comment]
Why not just use the existing shouldQuit variable? Why did you need to make a new one?

**Comment by Broutard** [comment]
The shouldQuit variable do a kill() and do not fire any event.
The truth is that I did not understand the difference between kill () and stop ()

**Pull request merged**
