### PR TITLE
[5.3] Add flag for select type of create controller

### PR DESCRIPTION
**Pull request by eskrano**
Add flag for select type of create controller (resource controller or no).

### CODE REVIEW

**Comment by browner12** [comment]
and here is the slippery slope we go down with that commit of mine.

**Comment by GrahamCampbell** [comment]
Please implement my review comments.

**Comment by browner12** [comment]
i guess my personal opinion on this is to not merge.  my argument in the initial commit is we are going after 90% of the use cases. The 10% can use the dedicated command for their need.

The problem if we implement this is, now do we go and add options for the `--table` and `--path` options for making a migration?

You can see how this quickly becomes a tangle of code.

my 2 cents. thanks.

**Comment by taylorotwell** [comment]
If I was going to have this flag I would just call it something like -r not -c_r

**Comment by taylorotwell** [comment]
Though I do think this command has the potential to seriously bloat as noted.

**Comment by eskrano** [comment]
@taylorotwell update . set -r flag

**Pull request merged**
