### PR TITLE
[5.3] Move the fire of the NotificationSent event after the actual sending

### PR DESCRIPTION
**Pull request by gregoriohc**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I think the event was fired first so that if sending throws an exception, the event still made it out into the wild?

**Comment by gregoriohc** [comment]
But if it throws an exception, the NotificationSent event doesn't makes sense, isn't it?

**Comment by GrahamCampbell** [comment]
I guess. :)

**Comment by GrahamCampbell** [comment]
I'm just trying to explore the reasons for and against. This PR probably is fine. 👍

**Pull request merged**
