### PR TITLE
[8.x] Add beforeQuery to base query builder

### PR DESCRIPTION
**Pull request by cbl**
## Background

Currently there is no way to change subselect-builder whereby the changes are applied to the parent query builder as well. This is because the subselect query is rendered when applied.

## The Solution

Preserve query modifications that are applied when the builder gets rendered.

This pr adds a `beforeQuery` method to the base query builder. The preserved closures will be called before the query gets rendered. This allows keeping sub query builders alive and modifying the sub query after applying it to the parent builder:

```php
// 1. Add the subquery
$builder->beforeQuery(function($query) use($subQuery){
    $query->joinSub($subQuery, ...);
});

// 2. Add constraints to the subquery
$subQuery->where('foo', 'bar');

// 3. Render the subquery, the constraints from 2. are applied
$builder->get();
```

The preserved closures will be executed in the following builder methods:

- `toSql`
- `exists`
- `insert`
- `insertOrIgnore`
- `insertGetId`
- `insertUsing`
- `update`
- `upsert`
- `delete`
- `truncate`

## Usage

If wanted the preserved modifiers can be applied using `applyBeforeQueryCallbacks`

```php
$builder->applyBeforeQueryCallbacks();
```

The preserved modifiers may be passed to other builders

```php
$otherBuilder->beforeQueryCallbacks = $builder->beforeQueryCallbacks;
```

## Where This Is Usefull

This is particularly useful for the new one-of-many feature, where performance can be improved for tables with millions of entries by limiting the groups inside the sub-queries during eager loading.

### CODE REVIEW

**Comment by driesvints** [comment]
Oof, this seems like a very complex feature to maintain. I can already see this being mis-used or new methods forgetting to be added. This seems better off as a feature in user land?

**Comment by cbl** [comment]
I could really need this to get eager loading for `one-of-many` relationships with more than million entries to < 2ms. 😅

**Comment by taylorotwell** [comment]
Hey @cbl - can you provide more detail on what changes this will allow you to make to One Of Many relationships to improve performance?

**Comment by taylorotwell** [comment]
Can you show the entire change that will need to be made to the CanBeOneOfMany trait? Is it literally just those few lines you showed?

**Comment by cbl** [comment]
@taylorotwell This is the full diff of the `CanBeOneOfMany` trait for the performance improvement: [cbl:one-of-many_performance](https://github.com/cbl/framework/commit/80b229548bf569dcce0969238b05d0e8b8914436#diff-fe30107a56ebbb0693e45ad4228a00e6f949a1b98c8f59ab275f1cc7d122c3df). The commit also contains all changes to apply constraints to the subquery where it can improve the performance.

**Comment by taylorotwell** [comment]
@cbl Do you have a big problem with me renaming this method to `$query->beforeQuery(fn)`?

**Comment by cbl** [comment]
@taylorotwell No, this probably gives users a quicker idea of what the function does.

**Comment by cbl** [comment]
@taylorotwell looks good, ready to be merged from my side 👍

**Pull request merged**
