### PR TITLE
Forward all collection methods to underlying collection

### PR DESCRIPTION
**Pull request by shaedrich**
Forward all collection methods to underlying collection

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

**Comment by shaedrich** [comment]
> What is the use case here?

DRY. Why reinventing the wheel?

**Comment by GrahamCampbell** [comment]
This doesn't work because you can't use __call to implement an interface.

**Comment by shaedrich** [comment]
I created the PR too early, but you can see in the branch itself that I removed the interfaces, because they are already implemented on the underlying collection

**Pull request closed without merging**
