### PR TITLE
[5.2] Allow the shuffle() method to be seeded

### PR DESCRIPTION
**Pull request by JayBizzle**
We often need to display items in a random order, but only random on a daily basis i.e. the order is static for a day, then the following day, the order changes.

This PR adds the ability to seed the `shuffle()` method.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why not just use the `random_int` function. It has better performance than `mt_rand`.

**Comment by JayBizzle** [comment]
`random_int` isn't seedable is it?

**Comment by GrahamCampbell** [comment]
> random_int isn't seedable is it?

Why is that needed?

**Comment by GrahamCampbell** [comment]
Oh, sorry. I get what you're doing now! Looks fine. :)

**Pull request merged**
