### PR TITLE
[5.4] Add includeWhen directive

### PR DESCRIPTION
**Pull request by jbrooksuk**
This is a directive that shortens:

```blade
@if ($user->ownsPost($post)
@include('posts.edit-controls', ['post' => $post])
@endif
```

to...

```blade
@includeWhen($user->ownsPost($post), 'posts.edit-controls', ['post' => $post])
```

### CODE REVIEW

**Review by pjona — APPROVED** [review]

**Comment by taylorotwell** [comment]
This was merged. Not sure why it's not detecting.

**Comment by driesvints** [comment]
@taylorotwell commit hash got changed when you rebased. That's probably the reason.

**Comment by driesvints** [comment]
Not that commit authors are still kept as is. You're just now indicated as the comitter.

**Comment by seanthebean** [comment]
Found the commit that added this into the 5.4 branch, just for traceability: 5fe39aa3bac01f49ffaf5d44bf03688690106dbe

**Pull request closed without merging**
