### PR TITLE
[9.x] Add whereBelongsToById to EloquentBuilder

### PR DESCRIPTION
**Pull request by ioan-cristea**
We need this in case we want to find by relationship id, withouth query the model to reduce mysql queries.
Like filtering the model by relationship in controller from FormRequest, in most efficient way.

This will help also in filtering by relationship when we have only the id, without **query the model** or **use the column name of the relationship**

### CODE REVIEW

**Comment by driesvints** [comment]
Please undo all styling changes in this PR.

**Comment by GrahamCampbell** [comment]
Why is this targeting Laravle 9?

**Comment by ioan-cristea** [comment]
Now, I use v9.x, and will be helpful for me, but if is needed I will contribute also on v10.x, with a optimised for PHP8.1

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
