### PR TITLE
[5.8] Add Config Facade methods hints

### PR DESCRIPTION
**Pull request by antonkomarev**
Continue of #28788

This PR adds bunch of missing methods to Config Facade and adds missing type-hints for existing ones.

### CODE REVIEW

**Comment by X-Coder264** [comment]
I wouldn't add methods to the docblock that aren't on the interface that the facade "points" to. This comment also applies to all other facade docblock PRs that you've opened.

**Comment by antonkomarev** [comment]
There are a lot of Facades which proxies concrete implementations without interfaces at all.

**Comment by X-Coder264** [comment]
Yeah, my point/comment was only for the facades that proxy to classes that have an interface like this one.

**Comment by taylorotwell** [comment]
I dunno if I want to keep shouldering this maintenance burden of such PR traffic around facade comments. Doesn't Barry's package already handle all this for you?

**Comment by antonkomarev** [comment]
@taylorotwell I understand your point, but since we've already got a lot of methods described in facades and not all of them are up to date we can't just ignore the changes. If you want I can continue this as single commit, but it might be harder to review it.

**Pull request closed without merging**
