### PR TITLE
Remove individual files instead of whole directory in artisan fresh

### PR DESCRIPTION
**Pull request by shamiao**
A few days ago, I run `./artisan fresh` on a developing application and it ruined all of my own `App\Services\*` classes, and `resources/assets/less/app.less` stylesheets. (relax - my own code has been recovered with git :grinning:)

On a user modified laravel application, `fresh` command should remove scaffolding safely, or refuses to run. Either is better than destroying user code. 

I changed `fresh` commands to remove individual class/stylesheet/asset files instead of whole directory to avoid this program.

### CODE REVIEW

**Comment by shamiao** [comment]
This solution is better but still far from perfect. A really safe scaffolding removal command should: 

1. Check which scaffolding files has been changed after installation. 
2. Untouch any changed php class file, and prompt user to remove scaffolding by his own. 
3. If any frontend file (php blade & stylesheets & assets) has changed, untouch ALL frontend files, and prompt user to edit frontend code by his own.  
    (since frontend files are deeply coupled, it's not safe to delete individual file even unchanged)

I hope me or anyone else come out with an really safe implementation.

**Comment by taiyaei** [comment]
`fresh` is really only meant to be used immediately after install.

Also, this doesn't delete the directories, so it's not really a "fresh" install.

**Comment by shamiao** [comment]
@taiyaei There is no excuse for destroying user code. If `fresh` is designed only for a new installation, it should just refuses to run on a modified one. 

Not deleting directories is an issue, thank you for pointing this out. I am adding some `deleteEmptyDirectory` (same as `rmdir` behavior) to solve this.

**Comment by GrahamCampbell** [comment]
The fresh command is only meant to be used on a new laravel install, not on one that's been changed already.

**Pull request closed without merging**
