### PR TITLE
[4.2] Cache : ensure the number of minutes is not < 1 for Redis setex

### PR DESCRIPTION
**Pull request by lucasmichot**
Fix https://github.com/laravel/framework/issues/5806
Related to https://github.com/laravel/framework/pull/5823

### CODE REVIEW

**Comment by halaei** [comment]
This is a bog itself. Here is the right way:

```php
    public function put($key, $value, $minutes)
    {
        $value = is_numeric($value) ? $value : serialize($value);

        $this->connection()->setex($this->prefix.$key, max(1, $minutes * 60), $value);
    }

```

**Comment by GrahamCampbell** [comment]
We only allow passing through integers, not floats. You cannot use 0.1, or wheatever.

**Comment by halaei** [comment]
There is a need to have less than one minute input, and every cache store supports it except RedisStore. It is a bug.

**Comment by GrahamCampbell** [comment]
Our phpdoc says only int is allowed.

**Comment by GrahamCampbell** [comment]
The behaviour for anything else is undefined.

**Comment by halaei** [comment]
Fix the phpdoc then and make the behavior defined! Which one has an undefined behavior? I see `* 60` everywhere in the code.
There is real need for supporting a fraction of a minute. RateLimiter is an example.

**Comment by GrahamCampbell** [comment]
> Fix the phpdoc

The phpdoc is not incorrect? You may not pass a float through. We could change this in L5.3, if you are willing to send a PR.

**Comment by halaei** [comment]
Isn't the change I mentioned for 5.2 is reasonable as well?

**Comment by GrahamCampbell** [comment]
No, because it involves making a breaking change to our contracts, which forces third party implementations to suddenly accept floats.

**Comment by lucasmichot** [comment]
> @lucasmichot IMHO, this limitation is not reasonable. I need to cache things for less than 1 min. If you don't want to cache for less than one min, then don't pass a minute less than 1 min.

#5806 was a bug fix, not a decision about a new behaviour.

> This is a bog itself. Here is the right way:

Check http://redis.io/commands/SETEX, the duration is in seconds. Not milliseconds

> Fix the phpdoc then and make the behavior defined! 

_Can you/could we_ or _please_ never hurt

**Comment by halaei** [comment]
@lucasmichot Sorry for the used language of the first message. But I still disagree. If there is a need to make sure setex is not receiving float, which I am not sure is a must, there could be a code like this:

```php
        (int) max(1, $minutes * 60)
```

**Comment by halaei** [comment]
In the current status of the framework code, you still can pass 1.5 as minutes and it works!

**Comment by GrahamCampbell** [comment]
> In the current status of the framework code, you still can pass 1.5 as minutes and it works!

You are technically not allowed to do that though. You must only pass an integer. The fact that works is a happy coincidence, if you will.

**Comment by lucasmichot** [comment]
> In the current status of the framework code, you still can pass 1.5 as minutes and it works!

Because this is actually casted to int

And SETEX does not accept float

```sh
lucas@air:~/Gits/laravel/framework | 5.2 ✔                                                                                                                                                                                  [4d7eb59]  14:36
> redis-cli
127.0.0.1:6379> setex foo bar 1.5
(error) ERR value is not an integer or out of range
```

**Comment by halaei** [comment]
@lucasmichot 1.5 min = 90 seconds, already an integer.

**Comment by halaei** [comment]
@lucasmichot I think predis handles the casting to int as well. Don't know who! I am var_dumping minutes and float is the result of that.

**Comment by halaei** [comment]
Here is a code in \Illuminate\Cache\Repository that do a casting, only if the given value is string:

```php
    protected function getMinutes($duration)
    {
        ...
        return is_string($duration) ? (int) $duration : $duration;
    }
```

**Comment by halaei** [comment]
I think there is room for improvement. If you agree, I can start a pull request for [5.3], but may need help. I know nothing about cache drivers except Redis. Do you guys support it?

**Pull request merged**
