### PR TITLE
add .idea to .gitignore for PhpStorm IDE

### PR DESCRIPTION
**Pull request by Runrioter**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This belongs in your global git config.

**Comment by Runrioter** [comment]
@GrahamCampbell You are right.

**Comment by iboved** [comment]
How to add it to global git config? Thanks.

**Comment by driesvints** [comment]
@iboved https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/

**Comment by fylzero** [comment]
@driesvints Does this point not also apply to .DS_Store files?  Shouldn't that arguably be in a global .gitignore and not project files as well?

**Comment by octoper** [comment]
@fylzero .DS_Store files are Mac OS specific files instead of .idea or .vscode that are program specific. (e.g. they can be used by a team wants to have the same editor workspace for all team members)

**Pull request closed without merging**
