### PR TITLE
[5.6] PHPDoc to prevent use of Request::get() the most we can

### PR DESCRIPTION
**Pull request by vlakoff**
See #24689 and https://github.com/laravel/ideas/issues/114.

### CODE REVIEW

**Comment by crynobone** [comment]
While this never been used in Laravel before I'm more leaning forward to adding [trigger_error()](http://php.net/manual/en/function.trigger-error.php) here.

**Comment by Alymosul** [comment]
I'm with anything that makes people aware to avoid this method.

**Comment by deleugpn** [comment]
I've been using  `$request->get()` since forever and never had a problem with it. From what I've seen the issue seem to only present itself if you use the same name in different containers of data in your http request, which is something questionable on it's own.

**Comment by devcircus** [comment]
Same here. I  se it in every project. Confused by this.

**Comment by deleugpn** [comment]
I read those topics and understood exactly what you're saying. But since I always write the full feature (since request until response), I never put the same name in two different containers of data. If URL is using that name, why should the post request use it for a different data, anyway?
I don't know the reason Laravel chose a different order and now it's just pointless to keep it consistent with Symfony, but I still think there is no problem with using `get` because you shouldn't use the same name for different data in a single request on different containers.

**Comment by taylorotwell** [comment]
I made the wording a little softer.

image

**Pull request merged**
