### PR TITLE
[5.3] Divide authentification routes

### PR DESCRIPTION
**Pull request by dersvenhesse**
I recently stumbled upon some applications where users are allowed to login but aren't allowed to register themselves. So it might be neat to easily add routes for login and logout without the registration routes. 

I simply divided the function `auth` in three methods. These methods can be called from `routes.php` to add these routes separately.

### CODE REVIEW

**Comment by JosephSilber** [comment]
`Route::register()` is extremely unintuitive.

**Comment by dersvenhesse** [comment]
@JosephSilber I agree, the method names could be improved. I oriented these on the given paths. Do you have a better proposal?

**Comment by JosephSilber** [comment]
I personally don't think there's a need for any of this.

**Comment by GrahamCampbell** [comment]
I'm :-1: too.

**Comment by srmklive** [comment]
There is absolutely no need for this ...

**Comment by dersvenhesse** [comment]
Apparently I'm the only one who'd like that. I withdraw the request.

**Pull request closed without merging**
