### PR TITLE
[5.2] Use Instance query instead of cloned parent query

### PR DESCRIPTION
**Pull request by tiran133**
This fixes https://github.com/laravel/framework/issues/13762

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This breaks our tests?

**Comment by tiran133** [comment]
Yes wasn't aware of that. Haven't tested it locally sorry for that.
But the test actually don't test if the morphed model don't use the SoftDeletes trait.

This problem still exists #13762 it will fail if you don't use the SoftDeletes trait on a morphed Model.

 I have a closer look. But some help would be nice.

**Comment by acasar** [comment]
@tiran133 Can you just PR a test case that currently doesn't work?

ping @phroggyy

**Comment by acasar** [comment]
@GrahamCampbell Replaced by https://github.com/laravel/framework/pull/13806

**Pull request closed without merging**
