### PR TITLE
[5.7] Query Builder Contract

### PR DESCRIPTION
**Pull request by inxilpro**
This is based on a [conversations in the `ideas` repo](https://github.com/laravel/ideas/issues/987) around adding a builder contract for easier type hinting across projects (without always having to keep track of which kind of builder you're working with).

This PR is backwards-incompatible because it breaks the ability to override underlying query builder calls via macros. This practice seems pretty dangerous to me, so I don't imagine a ton of people are doing it, but I may be wrong.

Right now, more tests would need to be refactored to account for the fact that many function calls are no longer going through `__call()`. I'm willing to start updating tests, but I want to find out if this is something you'd be interested in pursuing first, or if anyone else has comments about using macros to override query builder calls.

The main upside here is that you could now do:

```php
<?php

use Illuminate\Contracts\Database\Builder;

class WorksWithDatabase
{
  protected $builder;

  public function __construct(Builder $builder)
  {
    $this->builder = $builder;
  }

  public function run()
  {
    $this->builder->each(function($row) {
      // I don't need to know if this is an Eloquent query or a base query
    });
  }
}
```

### CODE REVIEW

**Comment by jmarcher** [comment]
For me this is way too risky, 2400 lines added is a hell lot to review, and 30 errors and 17 failures are still present in the tests.

Can you name more advantages in favour of this change?

**Comment by inxilpro** [comment]
Oops. I must’ve screwed up which branch I was working from. It’s only 7 or so files changed. I’ll fix shortly.

**Comment by taylorotwell** [comment]
I'm not sure the benefits really outweigh the amount of changes in this PR?

**Comment by deleugpn** [comment]
Too bad. Some interfaces around Eloquent would have been pretty neat.

**Comment by inxilpro** [comment]
It's only 8 files… most of those changed lines amount to duplicated docblocks. It's really not that *major* of a change… it's explicitly calling the internal `$query` object instead of using `__call()` for everything.

**Comment by Calytic** [comment]
This is a fantastic PR @inxilpro.  The changes here are fundamental and while I absolutely acknowledge the burden of testing it on the many platforms that Laravel supports and how substantial an effort such a change might entail in the long run, I'm disappointed to see it rejected nonetheless.

IMHO, The level of consistency in this approach among the various abstractions would make Eloquent unparalleled as a DBAL.  While the interface only addresses edge-cases, it does eliminate a substantial number of them, not to mention making Eloquent more extensible in general.  I sincerely hope that despite being rejected, this PR and similar ones has started a conversation that will eventually lead to an accepted implementation that fulfills the spirit of this work.

**Comment by maciejfikus** [comment]
In my opinion benefits DOES outweigh the amount of changes needed to solve this issue. 

Right now, we have to either guess / track what builder we are using at the time (which is not too comfortable nor practical) or ignore type hinting, which is just wrong. Moreover, even official docs still recommends going without type hints while working with Query Builder make the code more and more legacy :/.

**Pull request closed without merging**
