### PR TITLE
[9.x] Pluralizer applies improvements.

### PR DESCRIPTION
**Pull request by selcukcukur**

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks but it's now impossible to see what changed here?

**Comment by foremtehan** [comment]
@driesvints https://github.com/laravel/framework/blob/0ba82df367e90f38bbebc54d13548640d5854c87/src/Illuminate/Translation/MessageSelector.php

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks **sufficient explanation**, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Comment by foremtehan** [comment]
@taylorotwell the switch function replaced with `match`, 299 lined remove +18 inserted

**Pull request closed without merging**
