### PR TITLE
[11.x] Fixing incompatible errors

### PR DESCRIPTION
**Pull request by hans-thomas**
It fixes incompatible errors in Laravel after upgrading to Symfony:7.0. 
There are still 20 errors in the tests. Can I help to fix the errors?

### CODE REVIEW

**Comment by driesvints** [comment]
Hi there, thanks but we already have a PR up and are planning to tackle this internally.

https://github.com/laravel/framework/pull/48403

**Comment by driesvints** [comment]
@hans-thomas if you want, you can PR the pr above

**Comment by hans-thomas** [comment]
> @hans-thomas if you want, you can PR the pr above

@driesvints I love to but I don't get it 😅 what do you mean by that?

**Comment by Jubeki** [comment]
@hans-thomas I think you did the right thing as you are already targeting the symfony7 branch with this PR.

Maybe @driesvints can check this PR again. (Though symfony7 will probably be rebased against master first, to fix some other tests)

**Comment by driesvints** [comment]
@Jubeki think the branch was changed after I closed the PR because it was first targetting master.

**Comment by driesvints** [comment]
Thanks @hans-thomas. Right now I don't have the time to look into this PR to see if everything seems in order. I'll leave this open to review at a later moment.

**Comment by hans-thomas** [comment]
Too late to review. It's already done in `symfony7` branch.

**Pull request closed without merging**
