### PR TITLE
[5.6] Swap the index order of morph type and id

### PR DESCRIPTION
**Pull request by eddiclin**
It can be utilize the index when query the type by using "WHERE type = ?",
also "WHERE type IN (?)"

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
This is a breaking change.

**Comment by eddiclin** [comment]
@Dylan-DPC Please point it out, I don't know it will break what.

**Comment by Dylan-DPC** [comment]
Your order of indexing is different so it is a tough one whether it is breaking or not

**Comment by eddiclin** [comment]
It just speed up the sql which query by morph type. Sometimes we will query many rows with one type or some types, sql server can speed up it by this index.

**Comment by themsaid** [comment]
Problem here is that the new index name will be difference since the order changed, so if I have a migration with a `down()` method removing the key by old name, this migration will now error on rollback since the name has changed, it's an edge case but trying to make sure no breaking changes.
 
Also won't this make it do a slower lookup by ID? Your changes will make the following queries faster:

- by type
- by type and ID

But will make this slower

- by ID only

**Comment by a-komarev** [comment]
Search by ID only is pretty rare case for morph tables. Because it's useless to find all entities with ID of 3 without defining exact type.

**Comment by themsaid** [comment]
@a-komarev makes sense, only the breaking part I mentioned is a concern then.

**Comment by a-komarev** [comment]
Temporary clone of `dropIndex` method with old behavior is not a great idea, but I don't see any other ways to deal with it.

**Comment by dwightwatson** [comment]
Do you have to re-order the columns as well though? I know it's only a visual thing, but I've always thought having the ID before the type looked better. That wouldn't affect the performance of the index would it?

**Comment by eddiclin** [comment]
@dwightwatson Yes, that wouldn't affect the performance of the index.
As @a-komarev said, " it's useless to find all entities with ID of 3 without defining exact type". I think that put the type before the morph ID looked better.

**Comment by taylorotwell** [comment]
If it doesn't affect the performance than what are we doing?

**Comment by eddiclin** [comment]
@taylorotwell What I'm talking about with @dwightwatson is the order of columns, not the order of indexes.

**Pull request merged**
