### PR TITLE
[11.x] Fix handling empty values passed to `enum_value()` function instead of only empty string

### LINKED ISSUE #53180: Bug where empty arrays `[]` are treated as `null` when running the following assertion in PEST. It seems like the `enum_value` function is internally calling a `transform` function which then converts the `[]` value to `null`.
Just updated to Laravel 11.28. After running some tests in my application I noticed that this PR introduces an issue where empty arrays `[]` are treated as `null` when running the following assertion in PEST. It seems like the `enum_value` function is internally calling a `transform` function which then converts the `[]` value to `null`.

```php
use Illuminate\Testing\Fluent\AssertableJson;

->assertJson(fn (AssertableJson $json) => $json->whereType('id', 'string')
    ->where('object', 'menu')
    ->where('name', 'Primary')
    ->where('handle', 'primary')
    ->has('items', 2)
    ->has('items.0', fn (AssertableJson $json) => $json->whereType('id', 'string')
        ->where('object', 'menu_item')
        ->where('label', 'Home')
        ->where('url', '/')
        ->where('active', true)
        ->where('opens_new_tab', false)
        ->where('items', []) // Issue occurs here
        ->where('order', 0)
        ->etc()
    )
    ->has('items.1.items.0', fn (AssertableJson $json) => $json->whereType('id', 'string')
        ->where('object', 'menu_item')
        ->where('label', 'Payments')
        ->where('url', '/payments')
        ->where('active', true)
        ->where('opens_new_tab', false)
        ->where('items', []) // Issue occurs here
        ->where('order', 0)
        ->etc()
    )
    ->etc()
);
```

This check will return the following error:

```
Property [items.0.items] does not match the expected value.
Failed asserting that Array &0 [] is identical to null.
```

_Originally posted by @jayan-blutui in https://github.com/laravel/framework/issues/53096#issuecomment-2415215533_

### PR DESCRIPTION
**Pull request by crynobone**
fixes #53180

### CODE REVIEW

**Comment by devajmeireles** [comment]
@crynobone Do you believe it will fix `Js::from` function?

11.27
`Illuminate\Support\Js::from([]) => []`

11.28
`Illuminate\Support\Js::from([]) => null`

**Comment by crynobone** [comment]
@devajmeireles did you check the tests in this PR? Feel free to add more if you see it missing anything

**Comment by devajmeireles** [comment]
> @devajmeireles did you check the tests in this PR? Feel free to add more if you see it missing anything

I'm so sorry! I didn't see the `Js::from` test.

**Comment by PHLAK** [comment]
This is still broken when an empty collection is passed into `Js::from()`.

```php
Js::from(Collection::make()); // null
```

This is specifically affecting eloquent query results for me.

**Pull request merged**
