### PR TITLE
[5.7] Support custom user provider names in generator commands

### PR DESCRIPTION
**Pull request by markwalet**
The generator commands only worked when the `auth.providers.user` configuration was used. When you change this to something else, the user model wouldn't be replaced correctly.

I refactored the retrieval of the authentication model to a seperate method called `userProviderModel()`. Then I searched and replaced all occurrences of `config('auth.providers.users.model')`. 

I don't know if this is the way you'd like to implement this method. But it fixes the bug. I'll keep the PR open for feedback and edits.

### CODE REVIEW

**Comment by jmarcher** [comment]
This could use some tests.

**Comment by markwalet** [comment]
I know. I searched for some example tests for the commands but I couldn't find any. So I didn't know how you want these tests to look.

**Comment by markwalet** [comment]
I can't even run all tests. I get a memory exception. Is there a way to run all tests in chunks or something? Without increasing my memory limit.

**Comment by jmarcher** [comment]
You can run test per Class, Method, Group, etc. but you still need to run all the tests at least once to make sure your changes do not break other parts of the system.

**Comment by markwalet** [comment]
Yeah I don't feel like running through every testclass manually. There should be a way to do this automatically.

Besides that, I know that this change will not break anything. Because all tests get executed with CI.

I do want to write some tests for this change, but I need someone who can tell me where to start. Especially because I cannot find any tests for the `artisan:make` commands.

**Comment by jmarcher** [comment]
I meant that your tests YOUR tests per class/method or group.

**Comment by markwalet** [comment]
Ah yeah, that's possible.

Do you know why there aren't any existing tests for the commands?

**Comment by lucasmichot** [comment]
Duplicate #24501

**Comment by markwalet** [comment]
Anyone who can help me?

**Pull request merged**
