### PR TITLE
[5.7] Adds clear() method to Collection

### PR DESCRIPTION
**Pull request by hivokas**
This pull request adds the `clear()` method to the `Collection` class.
I think that this method may be useful in some cases.

### CODE REVIEW

**Comment by deleugpn** [comment]
Wouldn't it be better to make it immutable and return a new empty collection?

**Comment by hivokas** [comment]
From my point of view, it shouldn't be immutable.

**Comment by hivokas** [comment]
But I may be wrong :)

**Comment by mfn** [comment]
For the most part, the `Collection` is immutable. On top of my head, these are the "mutable" methods so far:
- `prepend`
- `transform`
- `offsetSet` (aka `ArrayAccess` interface)

I'm not a fan of adding mutable methods, but collection inherently **are not** mutable so there's hardly an argument against it.

But since collection have existed for such a long time no need for this 😄 I would rather see this (mutable method) not added…

**Comment by 36864** [comment]
Can you provide an example use case for this?

**Comment by taylorotwell** [comment]
I would just use `collect()` to get a new collection entirely.

**Pull request closed without merging**
