### PR TITLE
[6.x] Fix for Blueprints executing dropForeign commands in the wrong order.

### PR DESCRIPTION
**Pull request by Bradez**
## The Bug

Sometimes, when writing migrations, you need to alter a column that has a foreign key relationship. Due to database limitations, you're unable to alter a column that has a foreign key defined. Therefore, logically, you would write something like the following in order to drop the foreign key first and then make the relevant changes:
```php
Schema::table('users', function (Blueprint $table) {
	$table->dropForeign('foo');

	$table->boolean('foo')->default(false)->change();

	// (optionally) recreate the foreign key either now or later.
});
```

Due to a bug with with how Laravel constructs the command priorities (within the `addImpliedCommands` method), the commands for any changed columns will be executed first. That, inning of itself, is correct and a good thing.

However, in this case, a `dropForeign` should always be prioritized over any changes / additions. Otherwise, you will receive an SQL error indicating that you're unable to modify a column that has a foreign key relationship. Thus, the current workaround is to do something like so:

```php
Schema::table('users', function (Blueprint $table) {
	$table->dropForeign('foo');
});

Schema::table('users', function (Blueprint $table) {
	$table->boolean('foo')->default(false)->change();
});
```

Needless to say, the workaround is unnecessarily more "clunky," just to overcome this bug (and that's after you've identified the problem isn't with your migration itself but rather Laravel's handling of command priorities.)

## The Resolution

The solution is straight forward. We need to extract any commands that should be "prioritized" and ensure they're placed at the front of the `$this->commands` array so that when we convert `$this->commands` to SQL, the `dropForeign` keys take the priority.

There may be other scenarios where commands need to be prioritized and therefore I've defined an array of `$prioritizedCommands` in the new `filterPrioritizedCommands()` method so those can be added. The method will ensure the commands retain that priority, so that we can bundle the same type of commands together.

For example, if `dropForeign` is the first value of `$prioritizedCommands` (as is the case now) then all commands that are `dropForeign` will appear at the first in the SQL query and so on and so forth.

This just helps to ensure consistency, rather than randomly scattering these "prioritized commands" at the front of the `$this->commands` array based on how the user has set it up in their migration.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Is this issue present in 6.x? If so, please close this PR and submit a fresh PR to the 6.x branch.

**Comment by Bradez** [comment]
> Is this issue present in 6.x? If so, please close this PR and submit a fresh PR to the 6.x branch.

You're absolutely right, @GrahamCampbell, it is present in 6.x.
I've gone ahead and swapped that over to `6.x` now. 👍

**Comment by taylorotwell** [comment]
Rather than making all these changes on a LTS release and risk introducing more breaking changes for users - just use the workaround.

**Comment by Bradez** [comment]
@taylorotwell, that's the reason for assigning it to 8.x (rather than 6.x initially).

**Pull request closed without merging**
