### PR TITLE
Update phpDoc adding some throws tag

### PR DESCRIPTION
**Pull request by JCarlosR**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Some of these methods don't throw the exceptions you listed.

**Comment by JCarlosR** [comment]
Is it not necessary to add the `throws` tag if it's already added on a called method inside the same class?

```
/**
 * @throws UnexpectedValueException
 */
function foo(string $s) : void {
  if ($s === null) { throw new UnexpectedValueException("bad"); }
}

/**
 * @throws UnexpectedValueException <-- not necessary (?)
 */
function bar() {
    foo("hello");
}
```

In this case I was following PhpStorm's suggestions.

**Comment by Furgas** [comment]
@taylorotwell They are not thrown directly by them, but indirectly by the methods that are called inside and not caught. The caller should be aware of what to expect without the need to analyze the whole call graph.
However, in this particular case I would count container exceptions as global and fatal (the same as `\Exception` or `\Throwable`) and not include them in indirect `@throws` annotations.

**Comment by driesvints** [comment]
@JCarlosR @Furgas it isn't feasible to add cascading throws tags throughout the entire codebase because we'd be maintaining more DocBlocks then anything else. It'd just be too much. Also: where does this stop? Do we also implement throws tags for every exception third party libraries throw? 

Just adding them to the actual method that throws them is enough.

**Comment by Furgas** [comment]
Ideally, you should deal with them as early as possible - by addressing them or rethrowing a new exception (with inner exception set) between layer/library boundaries. That is better then pretending to the final consumer that he would only have to deal with some `MyAppException` when in reality he will be hit with some random exceptions from deep layers of the framework or libraries unknown to him.

Being strict with `@throws` tags will then signal you if you have a problem with your architecture and program flow when you find that you need to add them in multiple places, up to the outer layer.

**Pull request closed without merging**
