### PR TITLE
[9.x] Adds `redirectName` method

### PR DESCRIPTION
**Pull request by mahmoudmohamedramadan**
This PR allows us to use a new awesome form of the `redirect` method by passing the route name source and route name destination instead using URI, let's examine the next scenario for more illumination.

## BEFORE this PR gets merged

```PHP
Route::get('users', [UserController::class, 'index']);
Route::get('posts', [PostController::class, 'index']);

Route::redirect('/users', '/posts');
```

But, what if the URI was too long, it will be difficult to write and remember, so let's say hello to the new redirect method 🎉

## AFTER this PR gets merged

```PHP
Route::get('users', [UserController::class, 'index'])->name('users.index');
Route::get('posts', [PostController::class, 'index'])->name('posts.index');

Route::redirectName('users.index', 'posts.index');
```

### CODE REVIEW

**Comment by ankurk91** [comment]
I can see a flood of similar PRs in future. Laravel team should strictly prohibit such bloat PRs 

Here are some more PR ideas to earn GitHub badges

```php
Route::redirectAction
Route::redirectController
Route::redirectDomain
```

**Comment by driesvints** [comment]
@ankurk91 we appreciate you helping our on PRs and with the PRs you've sent in in the past but I often see you posting on PRs while being a bit harsh towards other community members. We'd appreciate it if you refrained from doing that in the future. You can always give your opinion but we respectfully ask that you do that in a kind and supportive manner.

**Comment by ankurk91** [comment]
Thanks Dries for the feedback.
I will take care of it.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
