### PR TITLE
Correct return type for Contracts\Validation\ValidationException::errors()

### PR DESCRIPTION
**Pull request by tobyzerner**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Not correct. What is returned here DOES implement that contract, and that's what we want to get across here. This means we COULD change the actual object we return here in the future and it technically wouldn't be breaking.

**Comment by tobscure** [comment]
Are you sure? The errors() method which I've changed the docblock for is returning the value of getMessageBag() called on the provider. If you look at \Illuminate\Contracts\Support\MessageProvider, the return value of getMessageBag() is documented as \Illuminate\Support\MessageBag.

**Comment by tobscure** [comment]
I see what you're saying though. This PR returns the concrete which is wrong. Just to make it clear:

Class::method | Current return value | Correct return value |
------ | -------- | ------
\Illuminate\Contracts\Validation\ValidationException::errors() | \Illuminate\Contracts\Support\Message***Provider*** | \Illuminate\Contracts\Support\Message***Bag***
\Illuminate\Contracts\Support\MessageProvider::getMessageBag() | \Illuminate\Support\MessageBag | \Illuminate***\Contracts***\Support\MessageBag

Should I do another PR?

**Comment by GrahamCampbell** [comment]
Sure. :)

**Pull request closed without merging**
