### PR TITLE
Removed useless else after return

### PR DESCRIPTION
**Pull request by alexmanno**
As a title, I removed the useless else after returns.

(Without changing the logic)

### CODE REVIEW

**Comment by lagbox** [comment]
These are the valueless changes that people have been complaining about.

**Comment by alexmanno** [comment]
@lagbox That's very welcoming.

**Comment by lagbox** [comment]
@taylorotwell is this restyling of the framework actually happening or not as this type of stuff seems very inconsistent in what is merged and what isn't?

**Comment by browner12** [comment]
these PRs are not being accepted. we have had a discussion about improving our Contribution Guide to go over style stuff like this so we can bring more consistency to the framework.  I had intended to take this on, but have been swamped lately.

**Comment by alexmanno** [comment]
Many thanks for explanations @browner12 :)

**Comment by lagbox** [comment]
@alexmanno Sorry, that was more of a note in general not quite for you, sorry about the tone.
Not valueless as in we don't value the contribution; valueless as in it doesn't actually add any value to the code, its just a term.

There has been an inconsistency with this particular issue over the last couple of months which is why I had thrown that out.

There was a reason (preference and explicit nature of them) for them being kept. Just wanted to know the final position on these.

@browner12 Thanks, I didn't know that was on you.

**Comment by browner12** [comment]
I had brought it up and volunteered, but if someone wants to go for it, more power to them.

Like I said, I'm swamped at work now, so it's not going to get done soon if it's on me.

**Comment by lagbox** [comment]
@browner12 maybe we can figure something out, im always on freenode[irc] (lagbox)

**Pull request closed without merging**
