### PR TITLE
[5.5] Fix conflicts on ModelMakeCommand

### PR DESCRIPTION
**Pull request by brunogaspar**
I've renamed the shortcut for the factory, otherwise it would throw an error saying that 2 shortcuts with the same name exist.

### CODE REVIEW

**Comment by browner12** [comment]
was this a 5.5 only thing? didn't notice it on 5.4

**Comment by brunogaspar** [comment]
The conflict was introduced [here](https://github.com/laravel/framework/commit/5ac005a0fb7d9f2520172869024ea57c03c383e4#diff-3640f65f6a067bdd9aa9a69b33f8a741).

**Comment by devcircus** [comment]
That was the first thing that crossed my mind when I saw that pr submitted. Didn't have time to check the code though.

**Comment by olivM** [comment]
is it just me or there's still a problem with this file  ?https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Console/ModelMakeCommand.php

**Comment by brunogaspar** [comment]
> is it just me or there's still a problem with this file ?

@olivM How so?

> how can it pass CI ?

@olivM No idea why it's passing on Travis, maybe the tests are not really touching this file, but StyleCI itself complained about it.

**Pull request merged**
