### PR TITLE
[5.4] Add file() method to response factory contact.

### PR DESCRIPTION
**Pull request by mosinve**
Add missing file() method in ResponseFactory contract to allow using this method according manual https://laravel.com/docs/5.4/responses#file-responses, shoud fix #20473

### CODE REVIEW

**Comment by ntzm** [comment]
Adding to contracts breaks BC, you should target 5.5 / master.

**Comment by mosinve** [comment]
it not breaks anything))) It fixes ;)

**Comment by ntzm** [comment]
It's a breaking change because anyone creating their own implementation that doesn't have a `file` method will break.

**Comment by mosinve** [comment]
Ah, yep, you right, I don't think such way ;)

**Pull request closed without merging**
