### PR TITLE
[5.5] No need to use collect() helper.

### PR DESCRIPTION
**Pull request by lucasmichot**
In some cases, using `collect()` helper or calling `Collection::make` is useless.

### CODE REVIEW

**Comment by mathieutu** [comment]
Hi @lucasmichot! 
What is the purpose of this kind of PR? The betterment?
(no troll, real question)
Is it really about performance, code style, "visual debt"..?

**Comment by lucasmichot** [comment]
@mathieutu It's about performance.
`collect()` and `Collection::make` are both calling `new Collection`.
These intermediary steps are useless. Why calling a function that just call another function?

**Comment by browner12** [comment]
could we foresee the `collect` helper doing something more in the future other than just instantiating the class? or the name or namespace of the `Collection` changing?  I think that could be the one benefit we get from the helper.

mostly just playing devil's advocate here. don't code for things you only think you might need, right?

**Comment by mathieutu** [comment]
Yeah,  I agree it's really playing devil's advocate.

But it's also one of the main Laravel's principle: add some functions to simplify the development, and clear the code style.

>Why calling a function that just call another function?
By following that, you can remove the ` collect` helper and also lots of Laravel most used stuff! 😋

**Comment by taylorotwell** [comment]
I think it's fine.

**Pull request closed without merging**
