### PR TITLE
[5.6] Adds ability to generate single action controller

### PR DESCRIPTION
**Pull request by hivokas**
This pull request adds ability to generate single action controller by specifying `--action` flag like this:

```
php artisan make:controller ShowProfile --action
```

### CODE REVIEW

**Comment by sisve** [comment]
The `--action` parameter is ambiguous to me. Aren't all controllers containing actions? And a `--single-action` is also weird, that makes it sound like the user need to know how many actions their controllers will contain up-front.

Would it make sense to extend it to allow the user to automatically create actions? `make:controller --actions=showThis,doThat,invokeSomething`, which would allow them to `make:controller --actions=__invoke`?

Or perhaps a `make:controller --only-a-invoke-method-as-single-action`?

**Comment by deleugpn** [comment]
You might be better off calling it a Handler instead of a Controller.

**Comment by hivokas** [comment]
@taylorotwell it's `--invokable` now

**Comment by devcircus** [comment]
@ogunkarakus 
```php
Route::post('/comment', 'StoreCommentController')->name('comment.store');
```

**Comment by gofish543** [comment]
Why would you want to generate a single action controller vs a regular controller?
What is the different between the two?
What is the net gain?

**Comment by deleugpn** [comment]
Relevant: https://jenssegers.com/85/goodbye-controllers-hello-request-handlers

**Comment by devcircus** [comment]
IMO single action controllers are very much a part of modern web development. No one is making a controller something it's not. It's simply a controller with a single action that handles one specific purpose instead of a controller with 7 actions and 7 different purposes. 
I have my own package that handles this, but glad to see it baked in.

**Comment by hivokas** [comment]
@taylorotwell added information about `--invokable` flag to docs in this PR: https://github.com/laravel/docs/pull/4389

**Comment by ModernArtisan** [comment]
@hivokas Nice idea :)
@taylorotwell I have a question. What's wrong with my previous PR? - https://github.com/laravel/framework/pull/17821
Looks demotivating for me...

**Pull request merged**
