### PR TITLE
[5.4] Add O(n) `median` and `nthOrder` implementations to `Arr` class.

### PR DESCRIPTION
**Pull request by mcordingley**
This pull adds the Quickselect algorithm for finding arbitrary order statistics in linear time with the `nthOrder` function on `Arr`. It also adds a `median` function, which amounts to sugar on top of `nthOrder`. Laravel's current way of finding medians takes O(n lg n) time, so this is an order-of-magnitude speedup to the process. The pull also updates `Collection` to use this new implementation.

For purposes of generality, the methods return the _element_ with the nth order statistic, not just the value off of that element with the nth order statistic. A user interested in just the value should easily be able to pull it off of the element. In the case of an array of scalars, the element and value are one and the same.

The methods can search not just for numeric values, but arbitrary comparable values. This means, for instance, that the median date can be found. Since the methods can take a comparison callback, the median of any complex, arbitrary ordering can be found. The drawback to generalizing beyond numbers is that it is no longer possible to average a split median. Instead, the lower median is selected, per convention. For numeric contexts in which the numbers follow a non-linear pattern, averaging a split median would still lead to incorrect results, so switching to the lower median should be no worse than averaging, if not better.

The second commit switches the internal implementation of `median` on `Collection` to use this logic. The function retains the same signature: it returns the median value, not element, and takes an optional string argument to pluck a field off of the collection. The differences are that it benefits from the speed-up, gains the ability to take the median of non-numeric fields, which consequently means that it now uses the lower median, where applicable.

I would switch `Collection` to make use of the callable callback, but that would also entail switching it to return the matched element, not the matched value. While I think this preferable, it would significantly change the signature of an established method.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
> Add O(n)

Quick select actually has worst case complexity `O(n^2)`. Average case is `O(n)`. Just didn't want the description to be misleading.

**Comment by mcordingley** [comment]
Point. In the worst case, it is O(n^2). The expected running time is O(n). However, the theoretical worst case is extraordinarily unlikely to happen. Since it's a randomized algorithm, there is no specific input that would elicit the worst case. Wikipedia describes it as running in "almost certain linear time." The RNG would need to pick a specific bad pivot point with each split to have that happen.

There is another algorithm that runs in worst-case linear time by spending additional work locating optimal pivot points. However, it's considerably more complicated to implement and takes longer to run in practice. The literature suggests that this implementation is broadly preferable for these reasons.

For what it's all worth.

**Comment by GrahamCampbell** [comment]
Yes, I agree that quickselect is a good choice, though, it was worth noting that is not an algorithm which is guaranteed to be linear time, though, due to the randomized pivot, is is linear time, with high probability. On a side note, `random_int` is actually faster than `mt_rand`

**Comment by mcordingley** [comment]
Gotcha. I've noticed that people get weird sometimes where performance is concerned, so I wanted to clarify that even though the worst case is technically O(n^2), it basically doesn't happen.

**Comment by mcordingley** [comment]
Thanks for the tip on `random_int`, by the way. I just switched it over to that. 👍  It sounds almost like `random_int` dominates `mt_rand`. Do you know if that's the case?

**Comment by mcordingley** [comment]
I don't know if there's interest in this, but this pull also opens the way to pulling the top m items from a collection of size n in O(n) time. Grabbing them and then sorting them would then be O(n + m lg m). If that's desired, then I'd be more than happy to build it.

**Comment by GrahamCampbell** [comment]
Probably hold off on making any further changes for now until we establish if this change is actually wanted in the core, then we can discuss any modifications if needed, at that point. :)

**Comment by taylorotwell** [comment]
I don't have any plans to add these functions to the core right now. Arr is macroable.

**Pull request closed without merging**
