### PR TITLE
Remove execution bits on all files

### PR DESCRIPTION
**Pull request by szepeviktor**
Next up: check this in Travis

### CODE REVIEW

**Comment by szepeviktor** [comment]
I hope everyone will be glad to setup his git client to turn off execute bits.

**Comment by taylorotwell** [comment]
I have no idea what you are talking about.

**Comment by szepeviktor** [comment]
@taylorotwell This is something modified by the `chmod` command.

> The execute permission grants the ability to execute a file. This permission must be set for executable programs, including shell scripts, in order to allow the operating system to run them. When set for a directory, the execute permission is interpreted as the search permission: it grants the ability to access file contents and meta-information if its name is known, but not list files inside the directory, unless read is set also.

https://en.wikipedia.org/wiki/File_system_permissions#Permissions

**Comment by browner12** [comment]
we know what execution bits are. can you explain ***why*** this change is necessary?

**Comment by szepeviktor** [comment]
@browner12 If you want to keep a server with a POSIX filesystem clean, a part of this process is having files with 0664 permissions.

**Comment by szepeviktor** [comment]
Of course scripts and binaries should have execute bit turned on.

**Comment by szepeviktor** [comment]
By default git does not set execute bit on Windows. Someone may had special settings.

**Comment by szepeviktor** [comment]
@taylorotwell @browner12 Any chance we switch to 0644 of all files in the project?

**Comment by browner12** [comment]
FYI, Taylor rarely looks at closed PRs. If you truly want this to go through I would open another one, and provide a much more thorough explanation this time, and why we need it / why it is better.

**Pull request closed without merging**
