### PR TITLE
[8.x] Add assertNotAllowed to TestResponse

### PR DESCRIPTION
**Pull request by fheider**
add a new shortcut function for testing the response status 405, if a method isnt allowed.

### CODE REVIEW

**Comment by SjorsO** [comment]
I think `assertMethodNotAllowed` is a better name. The 405 status code means the HTTP method is not allowed. The current name makes it feel like it has to do with not being authorized (401) or forbidden (403).

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
Should be named `assertMethodNotAllowed`

**Comment by taylorotwell** [comment]
It seems shorter to just type `$response->assertStatus(405)`?

**Comment by fheider** [comment]
> It seems shorter to just type `$response->assertStatus(405)`?

but it isnt readable. you have to know what 405 is.
to make it save, it could be `$response->assertStatus(Response::HTTP_METHOD_NOT_ALLOWED);`

but `$response->assertMethodNotAllowed()` looks cleaner

**Pull request closed without merging**
