### PR TITLE
[5.3] --force works for daemon workers

### PR DESCRIPTION
**Pull request by halaei**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Don't really want to add this right now.

**Comment by GrahamCampbell** [comment]
Aw. I liked this.

**Comment by taylorotwell** [comment]
Ha. I’ll look at it again.

**Comment by vlakoff** [comment]
This command argument should be described, otherwise you have to look at `Worker::daemonShouldRun` code to understand what it does.

**Pull request closed without merging**
