### PR TITLE
[9.x] Remove reduceWithKeys and merge the functionality with reduce

### PR DESCRIPTION
**Pull request by mokhosh**
This moves `reduce` out of `Collection` and `LazyCollection` and puts it into `EnumeratesValues` as suggested by @JosephSilber.

The existing test for `reduce` has be adapted to contain asserts for both situations, with and without `$key`.

I've also moved `tap` one method down to be alphabetically correct.

@JosephSilber while I was checking the code in `EnumeratesValues` I got an idea. Can we make `reduce` higher proxy-able as well? I don't know how to do that now, but I'm willing to do it if you give me a little guidance.

### CODE REVIEW

**Comment by driesvints** [comment]
@JosephSilber you didn't get pinged by GitHub yet because we haven't merged the CODEOWNER changes yet into master so pinging you manually here.

**Comment by driesvints** [comment]
@mokhosh there's a merge commit in this commit history. Can you rewrite the history so it's clean?

**Comment by mokhosh** [comment]
Sure

**Comment by JosephSilber** [comment]
> This moves reduce out of `Collection` and `LazyCollection` and puts it into `EnumeratesValues`

This was just done for 8.x, which is periodically merged with master. No need to do it here separately.

> Can we make reduce higher proxy-able as well?

We can't. Higher order proxies work by calling a method on each item, and returning its values. Since `reduce` needs an additional parameter (the `$carry`), I believe it can't ever work with higher order proxies.

**Comment by mokhosh** [comment]
> This was just done for 8.x, which is periodically merged with master. No need to do it here separately.

There's no diff there actually with the 8.x PR.
I should just say "this removes reduceWithKeys", I thought people who see this now might be in a 8.x mindset so I explained a bit more.

> Should probably go in a separate PR.

I think it's already merged in the 8.x PR, so should we just leave it? I'll keep this in mind for the future contributions.

> We can't. Higher order proxies work by calling a method on each item, and returning its values. Since reduce needs an additional parameter (the $carry), I believe it can't ever work with higher order proxies.

You're right. Thanks.

**Comment by mokhosh** [comment]
@driesvints I'm not sure why `git rebase` isn't showing me the merge commit so I can squash it. I red and watched a dozen tutorials on rebase, but they all worked on simple examples with one branch and no merge commits.

Can you please guide me through this?

**Comment by gocanto** [comment]
> @driesvints I'm not sure why `git rebase` isn't showing me the merge commit so I can squash it. I red and watched a dozen tutorials on rebase, but they all worked on simple examples with one branch and no merge commits.
> 
> Can you please guide me through this?

@mokhosh 
You could this from your `CLI`

git checkout `master`
git pull
git checkout `mokhosh:master`
git rebase master -i

```
pick `add foo`
s `merge commit to be removeb`
pick testReduce`
```

then, you can choose the commit message you fancy better for those changes. 👍🏻

**Comment by mokhosh** [comment]
@gocanto Thanks for your reply. The third command gave me this error:
```
error: pathspec 'mokhosh:master' did not match any file(s) known to git
```

**Comment by gocanto** [comment]
> @gocanto Thanks for your reply. The third command gave me this error:
> 
> ```
> error: pathspec 'mokhosh:master' did not match any file(s) known to git
> ```

`mokhosh:master` should be your master branch reference. Whatever the name or source that might be! :)

**Comment by driesvints** [comment]
@mokhosh I'd just check out a new branch and do the code changes anew as the current timeline is a bit messed up now. Then force push to your branch here.

**Comment by mokhosh** [comment]
@driesvints Thank you, and sorry for the trouble. I'll be cleaner next time.

**Pull request merged**
