### PR TITLE
[5.4] Some SensioInsight Fixes 

### PR DESCRIPTION
**Pull request by ousamabenyounes**
[5.4] Files should not be executable  : 

Project contains files with permissive permissions. In order to avoid opening a security breach, you should restrict execution rights on following files:

src/Illuminate/Auth/AuthManager.php
src/Illuminate/Auth/AuthServiceProvider.php
src/Illuminate/Auth/DatabaseUserProvider.php
src/Illuminate/Auth/EloquentUserProvider.php
src/Illuminate/Auth/GenericUser.php
src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php
src/Illuminate/Auth/Passwords/PasswordBroker.php
src/Illuminate/Auth/Passwords/PasswordResetServiceProvider.php
src/Illuminate/Auth/Passwords/TokenRepositoryInterface.php
src/Illuminate/Cache/ApcStore.php
src/Illuminate/Cache/ApcWrapper.php
src/Illuminate/Cache/CacheManager.php
src/Illuminate/Cache/CacheServiceProvider.php
src/Illuminate/Cache/Console/ClearCommand.php
src/Illuminate/Cache/Console/ForgetCommand.php
src/Illuminate/Cache/DatabaseStore.php
src/Illuminate/Cache/FileStore.php
src/Illuminate/Cache/MemcachedConnector.php
src/Illuminate/Cache/MemcachedStore.php
src/Illuminate/Cache/NullStore.php
src/Illuminate/Cache/RedisStore.php
src/Illuminate/Cache/Repository.php
src/Illuminate/Cache/composer.json
src/Illuminate/Config/composer.json
src/Illuminate/Console/Application.php
src/Illuminate/Console/Command.php
src/Illuminate/Console/composer.json
src/Illuminate/Container/Container.php
src/Illuminate/Container/composer.json
src/Illuminate/Contracts/Support/Arrayable.php
src/Illuminate/Contracts/Support/Jsonable.php
src/Illuminate/Contracts/Support/MessageProvider.php
src/Illuminate/Contracts/Support/Renderable.php
src/Illuminate/Cookie/CookieJar.php
src/Illuminate/Cookie/CookieServiceProvider.php
src/Illuminate/Cookie/composer.json
src/Illuminate/Database/Capsule/Manager.php
src/Illuminate/Database/Connection.php
src/Illuminate/Database/ConnectionInterface.php
src/Illuminate/Database/ConnectionResolver.php
src/Illuminate/Database/ConnectionResolverInterface.php
src/Illuminate/Database/Connectors/ConnectionFactory.php
src/Illuminate/Database/Connectors/Connector.php
src/Illuminate/Database/Connectors/ConnectorInterface.php
src/Illuminate/Database/Connectors/MySqlConnector.php
src/Illuminate/Database/Connectors/PostgresConnector.php
src/Illuminate/Database/Connectors/SQLiteConnector.php
src/Illuminate/Database/Connectors/SqlServerConnector.php
src/Illuminate/Database/Console/Migrations/BaseCommand.php
src/Illuminate/Database/Console/Migrations/InstallCommand.php
src/Illuminate/Database/Console/Migrations/MigrateCommand.php
src/Illuminate/Database/Console/Migrations/RefreshCommand.php
src/Illuminate/Database/Console/Migrations/ResetCommand.php
src/Illuminate/Database/Console/Migrations/RollbackCommand.php
src/Illuminate/Database/DatabaseManager.php
src/Illuminate/Database/DatabaseServiceProvider.php
src/Illuminate/Database/Eloquent/Builder.php
src/Illuminate/Database/Eloquent/Collection.php
src/Illuminate/Database/Eloquent/MassAssignmentException.php
src/Illuminate/Database/Eloquent/ModelNotFoundException.php
src/Illuminate/Database/Eloquent/RelationNotFoundException.php
src/Illuminate/Database/Eloquent/Relations/BelongsTo.php
src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php
src/Illuminate/Database/Eloquent/Relations/HasMany.php
src/Illuminate/Database/Eloquent/Relations/HasOne.php
src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php
src/Illuminate/Database/Eloquent/Relations/MorphMany.php
src/Illuminate/Database/Eloquent/Relations/MorphOne.php
src/Illuminate/Database/Eloquent/Relations/MorphOneOrMany.php
src/Illuminate/Database/Eloquent/Relations/Pivot.php
src/Illuminate/Database/Eloquent/Relations/Relation.php
src/Illuminate/Database/Grammar.php
src/Illuminate/Database/MigrationServiceProvider.php
src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php
src/Illuminate/Database/Migrations/Migration.php
src/Illuminate/Database/Migrations/MigrationCreator.php
src/Illuminate/Database/Migrations/MigrationRepositoryInterface.php
src/Illuminate/Database/Migrations/Migrator.php
src/Illuminate/Database/MySqlConnection.php
src/Illuminate/Database/PostgresConnection.php
src/Illuminate/Database/Query/Builder.php
src/Illuminate/Database/Query/Expression.php
src/Illuminate/Database/Query/Grammars/Grammar.php
src/Illuminate/Database/Query/Grammars/MySqlGrammar.php
src/Illuminate/Database/Query/Grammars/PostgresGrammar.php
src/Illuminate/Database/Query/Grammars/SQLiteGrammar.php
src/Illuminate/Database/Query/Grammars/SqlServerGrammar.php
src/Illuminate/Database/Query/JoinClause.php
src/Illuminate/Database/Query/Processors/PostgresProcessor.php
src/Illuminate/Database/Query/Processors/Processor.php
src/Illuminate/Database/Query/Processors/SqlServerProcessor.php
src/Illuminate/Database/README.md
src/Illuminate/Database/SQLiteConnection.php
src/Illuminate/Database/Schema/Blueprint.php
src/Illuminate/Database/Schema/Builder.php
src/Illuminate/Database/Schema/Grammars/Grammar.php
src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php
src/Illuminate/Database/Schema/Grammars/PostgresGrammar.php
src/Illuminate/Database/Schema/Grammars/SQLiteGrammar.php
src/Illuminate/Database/Schema/Grammars/SqlServerGrammar.php
src/Illuminate/Database/Schema/MySqlBuilder.php
src/Illuminate/Database/Schema/PostgresBuilder.php
src/Illuminate/Database/Seeder.php
src/Illuminate/Database/SqlServerConnection.php
src/Illuminate/Encryption/Encrypter.php
src/Illuminate/Encryption/EncryptionServiceProvider.php
src/Illuminate/Events/Dispatcher.php
src/Illuminate/Events/EventServiceProvider.php
src/Illuminate/Events/composer.json
src/Illuminate/Foundation/AliasLoader.php
src/Illuminate/Foundation/Application.php
src/Illuminate/Foundation/ProviderRepository.php
src/Illuminate/Foundation/Providers/ArtisanServiceProvider.php
src/Illuminate/Foundation/Providers/ComposerServiceProvider.php
src/Illuminate/Foundation/Testing/TestCase.php
src/Illuminate/Hashing/BcryptHasher.php
src/Illuminate/Hashing/HashServiceProvider.php
src/Illuminate/Hashing/composer.json
src/Illuminate/Http/JsonResponse.php
src/Illuminate/Http/RedirectResponse.php
src/Illuminate/Http/Response.php
src/Illuminate/Http/composer.json
src/Illuminate/Log/Writer.php
src/Illuminate/Log/composer.json
src/Illuminate/Mail/MailServiceProvider.php
src/Illuminate/Mail/Mailer.php
src/Illuminate/Mail/Message.php
src/Illuminate/Mail/composer.json
src/Illuminate/Pagination/PaginationServiceProvider.php
src/Illuminate/Pagination/composer.json
src/Illuminate/Queue/BeanstalkdQueue.php
src/Illuminate/Queue/Connectors/BeanstalkdConnector.php
src/Illuminate/Queue/Connectors/ConnectorInterface.php
src/Illuminate/Queue/Connectors/SqsConnector.php
src/Illuminate/Queue/Connectors/SyncConnector.php
src/Illuminate/Queue/Console/ListenCommand.php
src/Illuminate/Queue/Jobs/BeanstalkdJob.php
src/Illuminate/Queue/Jobs/Job.php
src/Illuminate/Queue/Jobs/SqsJob.php
src/Illuminate/Queue/Jobs/SyncJob.php
src/Illuminate/Queue/Listener.php
src/Illuminate/Queue/Queue.php
src/Illuminate/Queue/QueueManager.php
src/Illuminate/Queue/QueueServiceProvider.php
src/Illuminate/Queue/SqsQueue.php
src/Illuminate/Queue/SyncQueue.php
src/Illuminate/Redis/RedisServiceProvider.php
src/Illuminate/Redis/composer.json
src/Illuminate/Routing/Console/ControllerMakeCommand.php
src/Illuminate/Routing/Redirector.php
src/Illuminate/Routing/Route.php
src/Illuminate/Routing/RoutingServiceProvider.php
src/Illuminate/Routing/UrlGenerator.php
src/Illuminate/Session/CacheBasedSessionHandler.php
src/Illuminate/Session/CookieSessionHandler.php
src/Illuminate/Session/SessionManager.php
src/Illuminate/Session/SessionServiceProvider.php
src/Illuminate/Session/Store.php
src/Illuminate/Session/TokenMismatchException.php
src/Illuminate/Session/composer.json
src/Illuminate/Support/Arr.php
src/Illuminate/Support/Facades/App.php
src/Illuminate/Support/Facades/Artisan.php
src/Illuminate/Support/Facades/Auth.php
src/Illuminate/Support/Facades/Blade.php
src/Illuminate/Support/Facades/Cache.php
src/Illuminate/Support/Facades/Config.php
src/Illuminate/Support/Facades/Cookie.php
src/Illuminate/Support/Facades/Crypt.php
src/Illuminate/Support/Facades/DB.php
src/Illuminate/Support/Facades/Event.php
src/Illuminate/Support/Facades/Facade.php
src/Illuminate/Support/Facades/File.php
src/Illuminate/Support/Facades/Hash.php
src/Illuminate/Support/Facades/Input.php
src/Illuminate/Support/Facades/Lang.php
src/Illuminate/Support/Facades/Log.php
src/Illuminate/Support/Facades/Mail.php
src/Illuminate/Support/Facades/Password.php
src/Illuminate/Support/Facades/Queue.php
src/Illuminate/Support/Facades/Redirect.php
src/Illuminate/Support/Facades/Redis.php
src/Illuminate/Support/Facades/Request.php
src/Illuminate/Support/Facades/Response.php
src/Illuminate/Support/Facades/Route.php
src/Illuminate/Support/Facades/Schema.php
src/Illuminate/Support/Facades/Session.php
src/Illuminate/Support/Facades/URL.php
src/Illuminate/Support/Facades/Validator.php
src/Illuminate/Support/Facades/View.php
src/Illuminate/Support/Fluent.php
src/Illuminate/Support/Manager.php
src/Illuminate/Support/MessageBag.php
src/Illuminate/Support/NamespacedItemResolver.php
src/Illuminate/Support/Pluralizer.php
src/Illuminate/Support/ServiceProvider.php
src/Illuminate/Support/helpers.php
src/Illuminate/Translation/FileLoader.php
src/Illuminate/Translation/LoaderInterface.php
src/Illuminate/Translation/MessageSelector.php
src/Illuminate/Translation/TranslationServiceProvider.php
src/Illuminate/Translation/Translator.php
src/Illuminate/Translation/composer.json
src/Illuminate/Validation/DatabasePresenceVerifier.php
src/Illuminate/Validation/Factory.php
src/Illuminate/Validation/PresenceVerifierInterface.php
src/Illuminate/Validation/ValidationServiceProvider.php
src/Illuminate/Validation/Validator.php
src/Illuminate/Validation/composer.json
src/Illuminate/View/Compilers/Compiler.php
src/Illuminate/View/Compilers/CompilerInterface.php
src/Illuminate/View/Engines/CompilerEngine.php
src/Illuminate/View/Engines/Engine.php
src/Illuminate/View/Engines/EngineInterface.php
src/Illuminate/View/Engines/EngineResolver.php
src/Illuminate/View/Engines/PhpEngine.php
src/Illuminate/View/Factory.php
src/Illuminate/View/FileViewFinder.php
src/Illuminate/View/View.php
src/Illuminate/View/ViewFinderInterface.php
src/Illuminate/View/ViewServiceProvider.php

### CODE REVIEW

**Comment by ousamabenyounes** [comment]
[5.4] User specific files should not appear in .gitignore    

.DS_Store is user-specific and should not appear in a project .gitignore. Consider adding it to the user global .gitignore instead.

**Comment by ousamabenyounes** [comment]
[5.4] User specific files should not appear in .gitignore :

.DS_Store is user-specific and should not appear in a project .gitignore. Consider adding it to the user global .gitignore instead.

**Comment by ousamabenyounes** [comment]
[5.4] Logical operators should be avoided :  

The and operator does not have the same precedence as &&. This could lead to unexpected behavior, use && instead.

**Comment by taylorotwell** [comment]
I don't like huge, robotic changes like this.

**Comment by ousamabenyounes** [comment]
Sorry, I was just trying to apply SensioInsight recommandations:  
https://insight.sensiolabs.com/projects/ecb13104-12ee-41de-914e-e9be98319394/analyses/6  

I really like Insight project and try to fix quality/security/performances issues with it.  

Really sorry about this too big pull request, I will split this pull request to make it more readable...  

Regards.

**Pull request closed without merging**
