### PR TITLE
Remove dead code (stubs) in test classes

### PR DESCRIPTION
**Pull request by alexandre-butynski**
There were a lot of unused stubs in the bottom of test classes. This pull request removes them :)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Any reason why this wasn't sent to 5.0?

**Comment by GrahamCampbell** [comment]
@taylorotwell I was just conscious that the master branch is behind the 5.0 branch atm, so the next 5.0->master merge might break if the tests were using these stubs in 5.0.

**Comment by alexandre-butynski** [comment]
I have sent this to master because refactoring is made for developers and developers work more on master than on 5.0. I bet there is less dead code in the 5.0 branch (tests should have been modified/deleted since) then this refactoring would have been less effective.

**Comment by GrahamCampbell** [comment]
@alexandre-butynski Yeh, that's fine. Thank you for your contribution. :)

**Pull request merged**
