### PR TITLE
[5.5] Model date and date time casting

### PR DESCRIPTION
**Pull request by themsaid**
```php
class Person extends Model
{
    public $dateTimeFormat = 'Y-m-d H:i:s';
    
    public $dateFormat = 'Y-m-d';

    public $casts = [
        'birthdate' => 'date',
        'registered_at' => 'datetime'
    ];
}
```

Previously when casting this model into array/json the `birthdate` value will become `1989-10-01 00:00:00`, this PR gives the developer control over a `date` field format, so in this example the value is going to be `1989-10-01`.

- Model's `dateFormat` was renamed to `dateTimeFormat`
- New `dateFormat` attribute is used to set the format for a date only fields

### CODE REVIEW

**Comment by laurencei** [comment]
Is it too hard/worth it to do:

    public $timeFormat = 'H:i:s';
    
    public $dateFormat = 'Y-m-d';

    public $casts = [
        'birthdate' => 'date',
        'start' => 'time',
        'registered_at' => 'datetime'
    ];

Then datetime is a combination of time and date formats?

**Comment by taylorotwell** [comment]
I would like to try to avoid such a big breaking change.

**Comment by laurencei** [comment]
What about

    public $casts = [
        'birthdate' => 'date:Y-m-d',
        'registered_at' => 'datetime:Y-m-d H:i:s'
    ];

So the cast has the format itself?

**Comment by themsaid** [comment]
Well the change needed is to replace `dateFormat` to `dateTimeFormat` in their model class, also to use `$model->setDateTimeFormat()` instead of `$model->setDateFormat()`.

Also if they cast an attribute as date, it'll result in `2017-10-10` instead of `2017-10-10 00:00:00`.

**Comment by lucasmichot** [comment]
Seems related : https://github.com/laravel/internals/issues/669

**Comment by stevendesu** [comment]
There are a few things I like about this solution and a few things I don't like...

 1. Using two formats (date and datetime) could improve consistency in formatting across your app. However, just as problems arose from only having a single format, I could foresee problems arising from only having two formats. There may be legitimate use cases for three or more date formats.
 2. This changes the meaning of `date` and `dateFormat`, and so it would require people to update their apps if they previously depended on those definitions. It also changes the meaning of the `getDateFormat()` function. This could basically break a lot of apps, as it is
 3. When you start adding new types ("date" versus "datetime") you get into a _**really**_ deep rabbit hole. Should we add an "isodate" type which is always returned in UTC? What about a "timestamp" type that's always displayed as seconds since epoch? What about types for different timezones? Laravel has one type for all time-related data: `\Carbon\Carbon`

I would recommend an option that allows you to specify the format per-field. Either my own recommendation in https://github.com/laravel/internals/issues/719 or the recommendation in https://github.com/laravel/internals/issues/669

Alternatively, a third option may exist that utilizes object-oriented programming and abstractions. Create a date formatting service which is passed as a dependency to Eloquent models. In this way people could build add-ons for Laravel that modify the date format.

**Comment by djh101** [comment]
What about adding dateTime as the new name and deprecating date in 5.6, waiting until 5.7 to remove/replace completely? Even if only one date format is used, I think dateTime is a more sensible name given that that's what it is (then if a date format is still desired in the future there isn't an issue of the name already being in use).

**Comment by taylorotwell** [comment]
I don't think I'll merge this for now. I don't want to make the breaking change.

**Pull request closed without merging**
