### PR TITLE
[10.x] Add prefix support to rate limit key

### PR DESCRIPTION
**Pull request by erfsober**
Related issues and PRs: https://github.com/laravel/framework/issues/28323 https://github.com/laravel/framework/issues/16786 https://github.com/laravel/framework/pull/28339 https://github.com/laravel/framework/pull/28856

The same issue, which was resolved in https://github.com/laravel/framework/pull/28856 for inline throttle definition in middleware.

Example:

```php
// User can send 1000 requests of any kind in an hour.
Route::prefix('pane')->middleware('auth', 'throttle:1000,60')->group(function() {
    // User can download 10 times a minute, but not more than 100 times an hour.
    Route::post('/download', 'Ctrl@create')->middleware('throttle:10,1,minute_download', 'throttle:100,60,hour_download');
    // User can email 5 times an hour
    Route::post('/email', 'Ctrl@email')->middleware('throttle:5,60,email');
    // User can search 100 times an hour
    Route::get('/search', 'Ctrl@search')->middleware('throttle:100,60,search');
});
```

This pull request adds prefix support to the by() method of the rate limiter. The by() method is used to set the key of the rate limit. With this change, you can now specify a prefix string that will be added to the key, allowing you to easily differentiate between different rate limits that use the same key.

The updated method signature now includes an additional parameter $prefix which is an optional string. If a prefix is provided, it will be concatenated with the $key parameter, and the resulting string will be used as the rate limit key.

This change provides greater flexibility and control over rate limiting in Laravel applications, particularly in cases where multiple rate limits may need to be applied to the same key.

I've tested this change thoroughly and it has been working as expected in my local environment.

Thank you for considering this pull request.

Example:
```php
protected function configureRateLimiting(): void {
	$unique_identifier = 1;
	RateLimiter::for('verify-code', function (Request $request) use ( $unique_identifier ) {
    		$phone = $request->input('phone');
    		return [
    			Limit::perMinute(config('rate-limits.verify-code.every-minute'))->by($phone, $unique_identifier++),
    			Limit::perMinutes(5, config('rate-limits.verify-code.every-5-minutes'))->by($phone, $unique_identifier++),
    			Limit::perMinutes(30, config('rate-limits.verify-code.every-30-minutes'))->by($phone , $unique_identifier++),
    			Limit::perHour(config('rate-limits.verify-code.every-1-hour'))->by($phone, $unique_identifier++),
    			Limit::perMinutes(360, config('rate-limits.verify-code.every-6-hours'))->by($phone, $unique_identifier++),
    			Limit::perDay(config('rate-limits.verify-code.every-day'))->by($phone, $unique_identifier++),
    		];
		});
	}

```

### CODE REVIEW

**Comment by rezaDstras** [comment]
It seems pretty fine.

**Comment by LordVersA** [comment]
I had a problem in rate limiter, and it doesn't work on multiple rate limiter fine, it can fix that issue.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by taylorotwell** [comment]
Just pass the prefix to `by` directly.

**Comment by erfaansabouri** [comment]
As @taylorotwell mentioned here is the solution:

Handle rate limit in RouteServiceProvider.php

```php

RateLimiter::for('get-sms', function (Request $request) {
			$ip = $request->header('x-real-ip') ?? $request->ip();
			return [
				Limit::perMinute(config('rate-limits.get-sms.every-minute.value'))->by($ip . config('rate-limits.get-sms.every-minute.key')),
				Limit::perDay(config('rate-limits.get-sms.every-day.value'))->by($ip . config('rate-limits.get-sms.every-day.key')),
			];
		});
```
Sample route: 
```php
Route::get('/getSms', [ V1::class , 'getSms'])->middleware(['throttle:get-sms']);
```

-----------------
Or handle rate limit in api.php ( inline mode ):

```php

Route::any('/getSms', [ V1::class , 'getSms'])->middleware('throttle:10,1,get-sms-per-minute-limit', 'throttle:100,86400,get-sms-per-day-limit');



```

**Pull request closed without merging**
