### PR TITLE
[5.3] Adds an Intersect Method on the Request Class

### PR DESCRIPTION
**Pull request by AdenFraser**
Allows intersection of request input with provided array of input keys or method arguments.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Is this different than `$request->only($keys)`?

**Comment by AdenFraser** [comment]
`$request->only($keys)` returns null for $keys which are not provided by the form (either due to the inputs not existing, checkbox not being filled, disabled or whatever other reason).

Returning null for values which shouldn't be updated isn't particularly helpful on update methods as the existing value is then nulled.

**Comment by taylorotwell** [comment]
So could the implement of intersect under the hood simply be:

```
return array_filter($this->only($keys));
```

**Comment by AdenFraser** [comment]
That's a lot cleaner actually!

**Comment by GrahamCampbell** [comment]
Please send to 5.2. ;)

**Comment by AdenFraser** [comment]
There you go - #13167

**Comment by GrahamCampbell** [comment]
Keeping this open incase Taylor wants this on 5.3 only.

**Comment by athahersirnaik** [comment]
Great PR. Had done this in base DB repository of my codebase.

**Pull request closed without merging**
