### PR TITLE
[9.x] Added new email validation rule messages

### PR DESCRIPTION
**Pull request by SuperDJ**
Added Email validation rule. This makes it possible to give different error messages for different errors.

Using the following e-mailadress: `Кириfoö()@example.com`.
**Current behavior**
With the current email validation:
```php
'email' => 'email:rfc,strict,dns,spoof,filter'
```
When it fails it will only return
>The :attribute must be a valid email address.

**New behavior**
With the new email validation:
```php
'email' => [Email::rfc()->strict()->dns()->spoof()->filter()]
```
When it fails it wil return:
```php
[
       'The email must be a valid email address.',
       'The email does not have a valid domain.',
       'The email appears to be spoofed.',
       'The email must pass the filter.',
]
```

The behavior is taken from the [Password rule](https://laravel.com/docs/9.x/validation#validating-passwords).

### CODE REVIEW

**Comment by SjorsO** [comment]
I think someone who fills in `Кириfoö()@example.com` as their email probably doesn't need a specific explanation to figure out why their email isn't considered valid.

**Comment by driesvints** [comment]
I also think a generic message is probably enough. Also, there's now quite a bit of duplication between the new functionality and the validation trait.

**Comment by SuperDJ** [comment]
@driesvints I agree that the functionality is the same. In the validation trait I wasn't able to find a way of adding multiple validation messages for the same validation rule. 

My main reason for this PR is not add a new validation rule but to have specific validation messages for each email validation rule option (rfc, strict, dns etc.). I would like this to give better validation information to our end users.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by tbalint1995** [comment]
@SuperDJ 
Where is the Email class located in Laravel 9, as I understand there is no such class and methods like that?

**Pull request closed without merging**
