### PR TITLE
[6.x] Add response time assertion

### PR DESCRIPTION
**Pull request by zendraxl**
Add response time assertion.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm not sure this would be particularly useful since it's very dependent on the spec of the machine running the test.

**Comment by zendraxl** [comment]
@taylorotwell you are absolutely right, but CI should be pretty consistent?

**Comment by GrahamCampbell** [comment]
I think the point is that we want the framework core to be designed in such a way that tests work the same on everyone's local machines, as on any CI setup.

**Comment by GrahamCampbell** [comment]
You are free of course to release this code as a package.

**Comment by zendraxl** [comment]
What is the best way to hook into that with package?

**Pull request closed without merging**
