### PR TITLE
[5.3] Add optional compression for redis store

### PR DESCRIPTION
**Pull request by ethanhann**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why only the redis store. It's nothing unique to redis. It would make sense to have this for every implementation, if we're going to have it at all. A better place to implement this would be the cache repository layer.

**Comment by ethanhann** [comment]
@GrahamCampbell Thanks for the feedback. I thought about that, but there is implementation specific logic in each store that prevents having the compress/uncompress method calls in Illuminate\Cache\Repository. For example, in RedisStore->get() unserialize() is called on the value. If unserialize() is called in that method on the compressed string, and then gzuncompress is called in Repository->get() the wrong value will be returned. Basically, gzcompress/gzuncompress need to be called in a a certain order, depending on the store-specific logic.

I can implement this feature for the other stores, but I wanted to get some feedback first.

**Comment by GrahamCampbell** [comment]
Ok, makes sense!. Though, before making any more changes to the PR, I think we should wait for Taylor to say if he likes the idea at all first. I'm not sure it'd get widely used tbh.

**Comment by ethanhann** [comment]
It might not be a widely used feature, but for high traffic applications it is absolutely critical. For example, if you are caching a model with a few other related eager-loaded models you might have a cached value that is 100kb. That isn't much storage-wise, but at scale you might have 1000 cached items each being requested 100 times per second. That adds up to a lot of data transfer. If you are using a distributed cache service you are going to spend a truck load of money on it if your data is not compressed.

Even if you don't have high traffic, compressing the data means a smaller tier of your storage back-end can be used. Dropping even one AWS Elasticache tier would cut operational costs by a lot.

**Comment by taylorotwell** [comment]
No plans to add this.

**Comment by ethanhann** [comment]
Created this instead: https://github.com/ethanhann/Laravel-RedisStore

**Pull request closed without merging**
