### PR TITLE
[8.x] Add support for everyOddMinute, everyEvenMinute, everyOddHour, everyEvenMinute

### PR DESCRIPTION
**Pull request by yazeed**
Added support for **everyOddMinute**, **everyEvenMinute**, **everyOddHour**, and **everyEvenMinute** on ManageFrequencies under console.

Targeted 8.x as it's a fully backward compatible minor feature.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I don't think many people will use this? Those that want to can just use the custom syntax they have available to them.

**Comment by yazeed** [comment]
> I don't think many people will use this? Those that want to can just use the custom syntax they have available to them.

Not sure how many people would use it, but I needed it and thought it might be useful for others as well, and I never tried using the custom syntax. :-)

**Comment by GrahamCampbell** [comment]
The syntax would be what you have in your PR. `->spliceIntoPosition(1, '1-59/2');`

**Comment by taylorotwell** [comment]
I dunno, seems like `everyTwoMinutes` would be sufficient?

**Pull request closed without merging**
