### PR TITLE
[9.x] Add `even` and `odd` method to collection

### PR DESCRIPTION
**Pull request by Nothehi**
Receiving values that are in the even or odd position is one of those tasks that are very widely used, and I think it is better to create semantic functions for them.

example:
```php
collect(['a', 'b', 'c', 'd', 'e', 'f', 'g'])->even()
// output: b, d, f

collect(['a', 'b', 'c', 'd', 'e', 'f', 'g'])->odd()
//output: a, c, e, g
```

### CODE REVIEW

**Comment by JayBizzle** [comment]
Naming might be confusing.

```php
collect([1, 3, 5, 7, 9])->even();

// Should it return empty, or the even keys?
```

**Comment by Nothehi** [comment]
It actually returns items that are in even or odd position, and it doesn't matter what key or value the items have, the only thing that matters is the item's position in the collection.

It will return:
```
// 3, 7
```

But I agree with you might be confusing, Have you any suggestion?

**Review by mahmoudmohamedramadan — COMMENTED** [review]
```PHP
/**
 * Get the values that are in even positions.
 *
 * @return static
 */
public function even()
{
   return $this->nth(2, 1);
}
```

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
