### PR TITLE
[5.1] Fixes code syntax in Guard::attempt method

### PR DESCRIPTION
**Pull request by ryun**

### CODE REVIEW

**Comment by lukasgeiter** [comment]
This changes the logic of the method. If `$this->hasValidCredentials($user, $credentials)` is true, the method should always return `true` (not only if `$login` is true as well)

**Comment by ryun** [comment]
Point taken, but this can't be what we want:
```
if ($login) {
    $this->login($user, $remember);
}
{
    return true;
}
```

**Comment by lukasgeiter** [comment]
I agree it is missleading... It should be:

    if ($login) {
        $this->login($user, $remember);
    }
    return true;

**Comment by GrahamCampbell** [comment]
Yes, only with a blank line before the `return true;`

**Pull request closed without merging**
