### PR TITLE
[6.x] Type annotation fix: in `newPivot(.. , string)` string should be Pivot

### PR DESCRIPTION
**Pull request by HenkPoley**
6.x version of the master branch patch: https://github.com/laravel/framework/pull/34485

### CODE REVIEW

**Comment by taylorotwell** [comment]
It can definitely be a string.

**Comment by lk77** [comment]
it's always a string, it's the FQCN of the model to use, there is no reason for it to be a pivot instance it make no sense

**Comment by HenkPoley** [comment]
So `$using::fromRawAttributes()` will work because PHP will call the variable-variable object?

**Comment by HenkPoley** [comment]
So I did misunderstand the code, but since it can return a string, should that be added to `@return` ?

**Comment by HenkPoley** [comment]
Ah, I think I misread `return $using ? .. : ..`

**Comment by lk77** [comment]
```
$class = Test::class;
dump($class);
dump($class::$STATIC_PROPERTY);
 ```

```
"App\Models\Test"
"property_value"
```
the same thing apply for methods

**Comment by HenkPoley** [comment]
I guess `@psalm-var class-string $using` could be annotation. Iff psalm is used to statically check consistency.

**Pull request closed without merging**
