### PR TITLE
[8.x] Added HasFactory to DatabaseNotification class

### PR DESCRIPTION
**Pull request by foremtehan**
Allow to use factory for `Illuminate\Notifications\DatabaseNotification`

### CODE REVIEW

**Comment by driesvints** [comment]
Maybe we should ship a factory as well?

**Comment by foremtehan** [comment]
more than `HasFactory` ? This is my first PR and i'm not familiar with framework code base sorry 😅I just want to use factory in that class in my app.

**Comment by driesvints** [comment]
I realized this isn't really possible since the notifications table is polymorphic and we can't know up front which model type to provide.

**Comment by foremtehan** [comment]
I used this in laravel 7 like:

```php
$factory->define(\Illuminate\Notifications\DatabaseNotification::class, function (Faker $faker) {
    return [
        'id'              => \Ramsey\Uuid\Uuid::uuid4()->toString(),
        'type'            => 'App\Notification\ThreadNotification',
        'notifiable_id'   => factory(\App\User::class),
        'notifiable_type' => 'User',
        'data'            => ['foor' => 'bar'],
    ];
});
```

So if it not possible should get rid of all my tests?

**Comment by driesvints** [comment]
@foremtehan what I meant is that we can't ship it with Laravel itself because we don't know what `notifiable_type` will be.

**Comment by taylorotwell** [comment]
I'm not sure this is necessary or even makes sense. You can already define a factory for this model and then set the class name of the model in the factory and use the factory directly.

**Pull request closed without merging**
