### PR TITLE
[7.x] Revert bad change in view service provider

### PR DESCRIPTION
**Pull request by GrahamCampbell**
// cc @taylorotwell @kylekatarnls @browner12

### CODE REVIEW

**Comment by browner12** [comment]
do you want to remove that trailing comma as well in this PR?

**Comment by browner12** [comment]
https://github.com/laravel/framework/commit/e1fb7b1507947911f408ffdbc1fd95d02507a9c7

**Comment by taylorotwell** [comment]
My bad.

**Comment by GrahamCampbell** [comment]
The comma was already fixed before this PR.

**Pull request merged**
