### PR TITLE
[5.2] Add random() function to query builder

### PR DESCRIPTION
**Pull request by hamedmehryar**
This function adds sql statements to query to get a number of random
records.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Does this work with all drivers?

**Comment by hamedmehryar** [comment]
Unfortunately no.
I'm going to implement this in different Grammars.

**Comment by hamedmehryar** [comment]
Implemented in Grammars.

**Comment by GrahamCampbell** [comment]
Thanks, but sqlite is still missing.

**Comment by hamedmehryar** [comment]
I've tested this for sqlite and `... order by RANDOM() LIMIT 1;` worked and returned a random row.
Only SqlServer and MySql have different implementations.

**Comment by GrahamCampbell** [comment]
Ah, ok, Great.

**Comment by JayBizzle** [comment]
In my opinion, this method should _NOT_ do both order by rand _AND_ also limit.

As it is possible to seed the RAND() MySQL function, i would expect this method to look like this...

```php
public function random($seed = '')
{
    return $this->orderByRaw('RAND('.$seed.')');
}
```
if this was the case, i would suggest the method be named `orderByRand()` which would make Eloquent statments more readable i.e. `Users::orderByRand()->limit(20)->get();`


...or at an absolute, it could be like this push...
```php
public function random($limit = 1, $seed = '')
{
    return $this->orderByRaw('RAND('.$seed.')')->limit($limit);
}
```

Not sure how this translates to other drivers though

**Comment by hamedmehryar** [comment]
Thanks @JayBizzle, I will do some further research on it.

**Comment by hamedmehryar** [comment]
Well, I split this function into two functions:
`orderByRand($seed = '')`
and
`random($value = 1, $seed = '')`

This Allows one to use:
`$query->orderByRand()` only to sort the results randomly.
or to use:
`$query->random()->get()` to get one or many random records the same as `$collection->random()`

**Comment by taylorotwell** [comment]
Why not just use $collection->shuffle()?

**Comment by barryvdh** [comment]
That's not helpful if you have many items, but only want to load a few (so combined with a limit)

**Comment by GrahamCampbell** [comment]
> Why not just use $collection->shuffle()?

Yeh, that won't be possible if there's millions of rows.

**Comment by taylorotwell** [comment]
But it’s more feasible to return millions of rows via Eloquent?

**Comment by barryvdh** [comment]
The use-case is not to get ALL millions rows, but just X random rows from those million. With shuffle(), you would load all rows, but with random SQL, you only get the X rows (although random supposedly isn't very efficient either in MySQL either, but assume better then loading all rows in a collection)

**Comment by taylorotwell** [comment]
But why would you get all million? Just use a where clause and LIMIT then call shuffle?

$query->where(‘foo’, ‘bar’)->limit(50)->get()->shuffle()?

**Comment by barryvdh** [comment]
Because you would always get the same 50 results, never the next 50.

Simple example; you have a database with jokes (say 1000), and on the frontpage, you want to show a random one. So: `$query->orderByRand()->first()` will get a random one using SQL. `$query->limit(50)->get()->shuffle()->first()` would always load 50 same ones, `$query->get()->shuffle()->first()` would load all?

**Comment by taylorotwell** [comment]
Gotcha

**Comment by barryvdh** [comment]
But the `random()` with `limit()` is a bit much imho, just `orderByRand()` would probably suffice.

**Comment by vlakoff** [comment]
Same story… #5223, #5435.

**Comment by vlakoff** [comment]
Also you don't have to add two methods. You can do:

    ->orderByRandom(); // all rows

    ->orderByRandom()->limit(10); // 10 random rows

**Comment by taylorotwell** [comment]
Changed this to just a single method: `inRandomOrder`...

```
App\User::inRandomOrder()->take(10)->get();
```

**Comment by barryvdh** [comment]
Isn't `orderByRandom()` (or `orderRandom()`) more clear, that it's actually a `ORDER BY` statement? (In case there are multiple etc)

**Comment by JayBizzle** [comment]
Agree with @barryvdh 

Also reads better IMO

**Comment by taylorotwell** [comment]
If someone asked me "how should I sort X?" I would respond with "in random order".

**Comment by KennedyTedesco** [comment]
To me `orderByRand()` or `orderByRandom()` it's a bit more clear, since we already have a `orderBy()` method.

**Comment by athahersirnaik** [comment]
Yes, orderByRandom() is bit clear

**Comment by taylorotwell** [comment]
I’m not changing it. Sorry. :/

**Comment by neowill2013** [comment]
orderByRandom would be better

**Comment by taylorotwell** [comment]
Sorry locking this because I'm not going to be spammed all day on my inbox.

**Pull request merged**
