### PR TITLE
[9.x] Allow to fillJsonAttribute with encrypted fields

### PR DESCRIPTION
**Pull request by dkulyk**
This PR allow to use fillJsonAttribute with encrypted fields.

```php
public $casts = [
        'secret_json' => 'encrypted:json',
        'secret' => 'encrypted',
];

$model->setAttribute('secret_json->key', 'value');
$model->fill([
  'secret->id' => 'id',
  'secret->key' => 'key'
]);
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Any reason this can't target 8.x?

**Comment by dkulyk** [comment]
> Any reason this can't target 8.x?

https://github.com/laravel/framework/pull/36025

**Comment by taylorotwell** [comment]
Isn't this a breaking change?

**Comment by dkulyk** [comment]
When `$model->fill([ 'secret->id' => 'id'])` store to attributes decrypted value when `secret` has encrypted cast  - this is a bug.

**Pull request closed without merging**
