### PR TITLE
[5.8] Changed description for `authenticate` method

### PR DESCRIPTION
**Pull request by TBlindaruk**
- Changed description for `authenticate` method, since `check` method has the same description.

### CODE REVIEW

**Comment by lagbox** [comment]
How about something like "returns the current authenticated user or ..." since it isn't returning a bool (checking).

**Comment by TBlindaruk** [comment]
@lagbox changed

**Comment by taylorotwell** [comment]
The original description was better?

**Comment by TBlindaruk** [comment]
@taylorotwell , original description the same as for `check` method ;(

At the first, I have changed to `Determine if the current user is authenticated, in other case throw the error.`

Should I create a new PR with this?

**Comment by devcircus** [comment]
Just drop the "s" from "Returns" and we're good. It should match "throw".

**Pull request closed without merging**
