### PR TITLE
[10.x] Custom RateLimiter increase

### PR DESCRIPTION
**Pull request by khepin**
# Context

Sometimes a rate limit doesn't map directly to an increase of 1 at a time. Some examples would be:
- a limit on bandwidth used 
- a limit on # of updates across batch calls where each call could mean multiple "hits"
- a limit on time spent on some operations

For such rate limits today, the only available options via the `RateLimiter` class would be to loop and call `->hit` for as many times as we want to increment.
This becomes impractical when the number we want to increment by increases since each `hit` requires updating a cache server.

## Where do we use this?

At Square, we use a mechanism in queued jobs where we give higher / lower priority to certain users depending how much compute they've used across multiple jobs.
That is decided by counting the time spent across all queue workers up to a given limit over time. So rate limiting based not on each 1 job counting for 1 but instead counting for how many milliseconds were spent on the job.

So for a job running in 250ms, it would be easier to increment the number of attempts by 250 directly.

# Proposal

Introduce additional `increment` public method on the `RateLimiter` class to enable incrementing by a custom amount.

### CODE REVIEW

**Comment by ahinkle** [comment]
I see the need here, but is method names like `hit()` and `increment()` ambiguous for developers?

**Comment by khepin** [comment]
Do you have a suggestion you think is clearer? 
I'm struggling to come up with something else

**Comment by Anton5360** [comment]
> Do you have a suggestion you think is clearer? I'm struggling to come up with something else

I would suggest `hitTimes` naming.

 This way we don`t have two ambiguous method names but just kind of "expand" the existing one

**Comment by christophrumpel** [comment]
Ok, thanks, I thought so, too, since this was the only way I made it work. Still great work 👍

**Pull request merged**
