### PR TITLE
[5.3] Email is not available in Request anyway

### PR DESCRIPTION
**Pull request by gauravmak**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What does this do please?

**Comment by gauravmak** [comment]
Removes unnecessary code I believe. When I implemented forgot password in one of my application recently, I thought I was missing something in my implementation because I wasn't getting `$email` in reset password blade view file. Later found that, its not being fetched by code at all. This change might change someone's time in future as well as keep code clean.

**Comment by morloderex** [comment]
This prevents errors from people just going through to the reset-password directly.

**Comment by srmklive** [comment]
I don't there is any need to change how it currently is right now. @themsaid what do you think regarding this PR?

**Comment by taylorotwell** [comment]
It is if you sent it to query string.

**Comment by Rhincodon** [comment]
@taylorotwell By default generated in notification link does not contain email query string parameter. https://github.com/laravel/framework/blob/4df539c76353ff1931b0441f0d8f3f07bbf7b342/src/Illuminate/Auth/Notifications/ResetPassword.php#L49

**Pull request closed without merging**
