### PR TITLE
[9.x] Added `whenIsJson` to Stringable.

### PR DESCRIPTION
**Pull request by michaelnabil230**
This PR is to add the method `whenIsJson` in the stringable class

Ex:

```php
str('[1,2,3]')->whenIsJson(function () {
    // Your code
});
```

### CODE REVIEW

**Comment by ankurk91** [comment]
Please stop adding such methods, you already do like

```php
Str::of($string)->when(function ($str) {
  //
})->value()
```

**Comment by michaelnabil230** [comment]
> Please stop adding such methods, you already do like
> 
> 
> 
> ```php
> 
> Str::of($string)->when(function ($str) {
> 
>   //
> 
> })->value()
> 
> ```

‏I think it will be the last added.

**Comment by michaelnabil230** [comment]
@ankurk91 ‏I think it will be the last added.

**Comment by dinhquochan** [comment]
Don't add such methods. I prefer using `when()` to do this.

:-1: this PR.

**Pull request closed without merging**
