### PR TITLE
[7.x] Allow disabling of global middleware

### PR DESCRIPTION
**Pull request by nmokkenstorm**
This PR aims to fix issue [#32384](https://github.com/laravel/framework/issues/32384), and is supplementary to PR [#32347](https://github.com/laravel/framework/pull/32347) by @dsazup , after discussion with @driesvints.

At time of writing global middleware doesn't support access to routes, because the route matching process is done after the global middleware stack has run. As a result, accessing the current route on `Illuminate\Foundation\Http\Kernel` works for terminable (global) middleware, but not for regular middleware.

I've moved the global middleware stack check to its own method, and manually match there now, but obviously there's a performance consideration there. The obvious solution is marking the `findRoute` method of `Illuminate\Routing\Router` as public and caching the actual lookup, but that'd be a breaking change in the contract. I'm open for thoughts on this.

### CODE REVIEW

**Comment by nmokkenstorm** [comment]
@GrahamCampbell should be the correct branch now, I keep doing this wrong every time 😅

**Comment by taylorotwell** [comment]
I don't think matching the request twice per app lifecycle is going to be a feasible solution.

**Comment by nmokkenstorm** [comment]
> I don't think matching the request twice per app lifecycle is going to be a feasible solution.

Agreed, hence the proposed caching option. If you're able to match a route for a given RouteCollection once, I don't see that change between calls. Do you have thoughts on that?

Alternatively the matching part could be moved up a bit in the cycle, but that's a bigger architectural change. I know that that is generally frowned upon as it might have a lot more side effects, but I'm willing to look into it if you feel the caching thing won't work out to your liking.

**Comment by taylorotwell** [comment]
Personally my hunch at the current time would be that withoutMiddleware simply does not work with global middleware and we move on. If you want it to work with a global middleware, make that global middleware a route level middleware.

**Pull request closed without merging**
