### PR TITLE
[5.9] Remove deprecated helpers

### PR DESCRIPTION
**Pull request by driesvints**
Remove helpers which were deprecated in https://github.com/laravel/framework/pull/26898

### CODE REVIEW

**Comment by sisve** [comment]
Is there a discussion behind these changes? I know that there has been talk about removing the global helpers for a long time, but why only these and not all of them?

**Comment by mfn** [comment]
Only helpers which map 1:1 to the respective class static method are removed, because they don't bring anything to the table.

The functions left are the ones with an original implementation.

**Comment by driesvints** [comment]
@sisve the reasons @mfn stated above are the main reasoning behind this.

**Comment by driesvints** [comment]
Also see https://github.com/laravel/framework/pull/26898

**Comment by taylorotwell** [comment]
Let's put together a `laravel/helpers` package which includes these helpers before we do this.

**Comment by driesvints** [comment]
Sure thing 👍

**Comment by driesvints** [comment]
Package created: https://github.com/laravel/helpers

**Pull request merged**
