### PR TITLE
[8.x] Fix blade compiler regex issue

### LINKED ISSUE #36815: Components: The ")" character, this may cause an error
- Laravel Version: 8.34.0
- PHP Version: 7.4.16
- Database Driver & Version: -

### Description:
If you use the ")" character in a declared attribute of a component, this will result in an error:
_ParseError
syntax error, unexpected .._

### Steps To Reproduce:
**Declare an attribute on a component:**
`public function __construct($title = '')`

**Run from any .blade.php:**
`<x-forms.input title="test test )"/>`

### PR DESCRIPTION
**Pull request by driesvints**
Draft PR with failing test for a current issue with Blade components where a single `)` is passed as a string argument. I've tracked it down to the regex below that doesn't seems to quite parse things correctly. Every attempt I made so far to fix it broke something else in the compiler.

https://github.com/laravel/framework/blob/d8a53a068c4b16187a9933ec5c5c9db33ff4e9c6/src/Illuminate/View/Compilers/BladeCompiler.php#L420

Update: thanks to @jasonmccreary for fixing this 🥳 

Fixes https://github.com/laravel/framework/issues/36815

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm scared but we'll give it a shot. 😅

**Comment by jasonmccreary** [comment]
Agreed. The idea is to handle any quoted strings separately. This is a bit naive to all the various ways one may quote strings in PHP. But it should solve the immediate issue with the current Regex approach. Supporting more complex syntax will likely require a more complex approach.

**Comment by selcukcukur** [comment]
https://regexr.com/5psod Too many regex syntax errors.

**Comment by jasonmccreary** [comment]
@selcukcukur PHP uses PCRE.

**Comment by selcukcukur** [comment]
@jasonmccreary I skipped that part, sorry 😅

**Comment by shaffe-fr** [comment]
Hi @driesvints, this PR caused an exception for the following case:
```
@php($label = new HtmlString(__( 'forms.terms', [ 'link' => 'I don\'t'])))
<x-input-checkbox name="terms" :label="$label" required/>
```
The new regex seems to have issues with escaping (escaped apostrophe `\'` in my example).

**Comment by jasonmccreary** [comment]
@shaffe-fr, it's currently a rather naive check for quoted strings. I'll see if I can adjust it to account for basic escaping. But I do worry we're pushing the limits of what this regex can do in a single pass.

**Comment by taylorotwell** [comment]
@shaffe-fr just do `<?php your code ?>` 😓

**Comment by shaffe-fr** [comment]
I understand that I can do this differently, I just wanted to indicate a small regression. Sorry for the inconvenience.

**Comment by driesvints** [comment]
@shaffe-fr thanks for notifying us. For now please use Taylor's suggestion.

**Comment by selcukcukur** [comment]
The last PR pushes the boundaries very much, I think this should not be applied.

**Pull request merged**
