### PR TITLE
remove return void

### PR DESCRIPTION
**Pull request by babininja**
remove @return void

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR, but the code is already correct.

**Comment by 36864** [comment]
That's exactly what `@return void` means.

**Comment by babininja** [comment]
but Constructors don't get return values and there is no need to @return void

**Comment by GrahamCampbell** [comment]
> but Constructors don't get return values

And so their return type is `void`.

> and there is no need to @return void

The framework's code style is to always have return annotations, so we can distinguish between "does not return a value", and "does not have documentation".

**Pull request closed without merging**
