### PR TITLE
[5.5] Default 404 and 500 error pages

### PR DESCRIPTION
**Pull request by laurencei**
There is currently a nice "pretty" default 503 maintenance page included in the framework.

This PR adds similar "pretty" default 404 and 500 error pages (still can be easily overridden as required).

**404s:**

**500s (when not in debug mode):**

### CODE REVIEW

**Comment by dwightwatson** [comment]
I wonder if it might be better to shorten the messages as much as possible, as this length of text won't look great on mobile devices. Maybe something like "Page not found" and "Something went wrong".

In addition, it might be beneficial to add a link back, or to the root URL. It's fair not to have that on a 503 page as one would expect the entire site to be unavailable, but with a 404 or a 500 you'll probably want to get the user back on the right track.

**Comment by ankurk91** [comment]
What about having a fallback ```error.blade.php``` which can be loaded if corresponding view not found.

This way we will not have to create a separate view to each http error, it would be good if framework comes with this feature, later developers can override it.

**Comment by lioannou** [comment]
@dwightwatson - I added some small padding. This is what they look like on a small mobile:

image

In regards to links etc - obviously it is up to Taylor - but if you want links to your pages etc - that is where people can override and place what they like in their app. Otherwise there is always the "back" button on a browser 😄

**Comment by taylorotwell** [comment]
If we're gonna have smaller font sizes on these pages we should change the 503 page to match.

**Comment by lioannou** [comment]
Ok - all font sizes now the same.

desktop


mobile

**Comment by JosephSilber** [comment]
Why isn't there a single layout file that they all extend?

**Comment by lioannou** [comment]
What happens if I make a layout file called `errors.blade.php` - and someone has the same layout file in their app? Might lead to unexpected behavior if you call a layout file you were not expecting?

I was trying to keep this simple - and let people override as they need...

**Comment by JosephSilber** [comment]
@lioannou this would be in the errors directory, not a global layout file. So it won't clash with anything the user has elsewhere.

**Comment by lioannou** [comment]
@JosephSilber - as discussed on Slack - I cant get the view files to call a layout inside the framework - it only wants to load the extended view file from the App folder.

If you can come up with a solution I'm happy to modify the PR - otherwise we'll have to leave it as is.

**Comment by lioannou** [comment]
@JosephSilber - ok - I've done a refactor into a layout file.

**Comment by taylorotwell** [comment]
just call it errors::layout ... not errors:frameworkerror

**Comment by lioannou** [comment]
@taylorotwell - ok done.

**Comment by fernandobandeira** [comment]
Would it be possible to ``` trans() ``` these errors?
Just asking since we're changing them...

Personally I'll overwrite these pages however that might be usefull for the community...

**Pull request merged**
