### PR TITLE
[5.4] Allow for dev-providers

### PR DESCRIPTION
**Pull request by alexbowers**
https://github.com/laravel/internals/issues/308

### CODE REVIEW

**Comment by tomschlick** [comment]
Any opinions on splitting provider registration to a new providers.php config entirely? As apps grow and make use of more and more providers that list can get pretty long...

**Comment by alexbowers** [comment]
I'd prefer that, but currently this is a less drastic change

**Comment by garygreen** [comment]
-1 to this. I don't see how this is any different to just doing the below in your `AppServiceProvider`:

```php
if ($this->app->environment('local')) {
   $this->register('....');
}
````

The `app.php` config file shouldn't care about dev dependencies, only production ones imo. Also if you included your dev ones in there, they would get cached with the config on production which is another waste.

**Comment by taylorotwell** [comment]
@garygreen once difference would be perhaps that of performance. If you have a non-deferred provider that is mainly used in development, you still have to perform the file IO of loading that provider even in production environments.

**Comment by garygreen** [comment]
@taylorotwell 

> you still have to perform the file IO of loading that provider even in production environments.

Well not if you dynamically load your dev providers in your `AppServiceProvider` via `$this->app->register(....)`

I guess it makes sense to have at least a consistent way of registering dev service providers, so people can update their packages to say "add to providers" or "add to dev_providers". I don't think it should cache the dev providers in the cache:config though. 

Another option could be to promote a `DevServiceProvider` with an array of providers to load / special config for local / dev environment. 

```php
<?php namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class DevServiceProvider extends ServiceProvider
{
    /**
     * Development service providers to register.
     *
     * @type {array}
     */
    protected $providers = [
        //
    ];

    /**
     * Boot.
     */
    protected function boot()
    {
        // Setup any special configs for development here, etc.
    }
}
```

**Comment by garygreen** [comment]
Also what about facades? Do you also then add one for `dev_facades` ? You could keep going with this.... 😕

**Comment by rsdev000** [comment]
What about middlewares ?

**Comment by alexbowers** [comment]
> I guess it makes sense to have at least a consistent way of registering dev service providers, so people can update their packages to say "add to providers" or "add to dev_providers". 

Thats my main motivation for this. 

>  I don't think it should cache the dev providers in the cache:config though.

I haven't looked at how its cached, but would it not be cached based on whats called by `ProviderRepository`.

In that case, these wouldn't be cached on production, since that would never be called.

> DevServiceProvider

I'm not really keen on this idea, because it separates out a way to do it from what people are used to, and as far as I can see provides no additional benefit to having it simply in an array in the `app.php` file.

Is there a benefit to having it within its own service provider?

To me, that would mean that the `DevServiceProvider` is required to be called in production, and then somewhere it decides whether to register everything inside of the `providers` array, probably with the same logic (if app_env) anyway, so does separating this out to a new class give any benefit?

> what about facades

Thats something that could be considered, but is separate in scope to this PR.

**Comment by alexbowers** [comment]
@rsdev000 nothing would change with how middleware works.

**Comment by garygreen** [comment]
@alexbowers 

> Is there a benefit to having it within its own service provider?
> To me, that would mean that the DevServiceProvider is required to be called in production, and then somewhere it decides whether to register everything inside of the providers array, probably with the same logic (if app_env) anyway, so does separating this out to a new class give any benefit?

The `DevServiceProvider` wouldn't be registered / loaded if the environment isn't local. The benefit of doing all this stuff in a single provider is that all your development registering of providers, facades, configs, middleware, etc, all happens in one place. The provider won't even be touched in production. Mixing dev / environment specific stuff in `app.php` just doesn't feel right to me imo.

**Comment by alexbowers** [comment]
@garygreen So where would the `DevServiceProvider` be registered?

**Comment by garygreen** [comment]
@alexbowers 

It would probably go into `laravel/laravel` and be registered in [`AppServiceProvider`](https://github.com/laravel/laravel/blob/master/app/Providers/AppServiceProvider.php)

I mean what your essentially re-creating here (in some ways) is the cascading configs which Laravel 4 had and it was all stripped out for the configs to become environment agnostic. To re-add that back in (in a very basic sense by prefixing some with `dev_`) just feels weird.

**Comment by taylorotwell** [comment]
Hmm, I dunno. It seems like there is quite a bit of contention here. For now, I would suggest just dynamically register dev providers in your AppServiceProvider would be a fairly good option. If you have a package, you could include the code to copy and paste within your installation instructions.

**Pull request closed without merging**
