### PR TITLE
[5.2] fix docblock of Routing

### PR DESCRIPTION
**Pull request by mark86092**
It is strange that StyleCI didn't fix that before

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why should StyleCI fix this? It's not a static analysis tool, it just fixes code style.

**Comment by GrahamCampbell** [comment]
In terms of fixing the 2 spaces thing, we plan to add that later on, and fix all that across the entire framework.

**Comment by mark86092** [comment]
OK, let me revise the PR, and fix the docblock but not the space problem.

BTW, @GrahamCampbell is it a good idea to refactor some function of Routing to new file?

**Comment by GrahamCampbell** [comment]
> BTW, @GrahamCampbell is it a good idea to refactor some function of Routing to new file?

I don't think so?

**Pull request merged**
