### PR TITLE
[5.0] Safe cache write and validation on read

### PR DESCRIPTION
**Pull request by texnikru**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You haven't made any of the cs changes I asked for?

**Comment by texnikru** [comment]
No, here is no new changes.
Just copied files from old branch and back them in new branch. In all other cases pull request was have several commits instead of one. Possible this can be done with another way but I dont know.

**Comment by taiyaei** [comment]
You should read about [git rebase](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) or [git reset](http://stackoverflow.com/a/5201642) to squash commits so you don't have to make multiple PRs in the future

**Comment by texnikru** [comment]
Thx

**Comment by texnikru** [comment]
Changes above is final with all required changes.
Here is my misunderstand above.

**Comment by CurosMJ** [comment]
Why did you define `is_serialized()` as an helper?
That should have been defined as a protected or private method.

**Comment by texnikru** [comment]
is_serialized() - missed function in php, this is useful for all.

**Comment by GrahamCampbell** [comment]
Please make the cs fixes I asked for.

**Comment by taylorotwell** [comment]
If you are having this problem just use a better cache like Memcached which is actually suited for these types of situations. The file driver is mainly for low volume / development.

**Pull request closed without merging**
