### PR TITLE
Added that subqueries related to another database work

### PR DESCRIPTION
**Pull request by maguilar92**
**Related to pull request #23032** 

**I would like to apologize for the insistence of adding this compatibility but I think it can be very useful for several users, including a project that I am developing with multiple databases.**

**I changed the last pull request code by changing the database separator used and using interface CanCrossDatabaseShazaamInterface to implement it**

Added cross database compatibility in subqueries including database name in subquery when query connection and subquery connection are different and connection implements CanCrossDatabaseShazaamInterface.

# COMPATIBILITY

- MySQL (Compatible)
- PostgreSQL (Compatible)
- SQLite (Not compatible) **will work as it works now**
- SQL Server (Compatible)

This will not break any existing features because user no need to modify existing code. 
Only the subqueries with table in another database incorporate the database name to the left of the table name.

# BENEFITS
Users can use the methods has, whereHas, doesntHave and whereDoesntHave in Eloquent when the relation is in another database.

For example:

`Provider::whereHas('orders')`

### NOW GENERATES

````select * from `hvp_providers` where exists (select * from `hvp_products` where `hvp_providers`.`id` = `hvp_products`.`provider_id` and `hvp_products`.`deleted_at` is null) and `hvp_providers`.`deleted_at` is null````

**Sql error:** 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'global.hvp_products' doesn't exist

### WITH THIS PULL REQUEST GENERATES

````select * from `hvp_providers` where exists (select * from `shop`.`hvp_products` where `hvp_providers`.`id` = `hvp_products`.`provider_id` and `hvp_products`.`deleted_at` is null) and `hvp_providers`.`deleted_at` is null````

### CODE REVIEW

**Comment by taylorotwell** [comment]
No plans on adding. Sorry.

**Comment by deleugpn** [comment]
It's a little cumbersome, so it's not a surprise it didn't make into the core of the framework. Personally I wouldn't recommend cross database joins. But if your mind is set on this, perhaps you should consider writing a package for Laravel that introduce this.

**Comment by maguilar92** [comment]
I have package created locally. I will publish it today!!

In my case I need it because I have a global database and then each driving school has its own

Thanks for all.

**Comment by maguilar92** [comment]
Package is now available:

[https://github.com/hoyvoy/laravel-cross-database-subqueries](url)

**Pull request closed without merging**
