### PR TITLE
[5.4] schedule:list

### PR DESCRIPTION
**Pull request by decadence**
Make command that lists Schedule events and their next run date considering when / skip callbacks.
Unfortunately I don't quite understand how to test it within framework without `artisan` script. I could only test it within 5.4.27 Laravel Application.

### CODE REVIEW

**Comment by tillkruss** [comment]
Could you post a screenshot of the output?

**Comment by decadence** [comment]
screenshot_1
@tillkruss

**Comment by taylorotwell** [comment]
No plans to add this for now.

**Comment by JayBizzle** [comment]
@decadence How did you get your output to look so tidy? I just tried this command in my own application and get the following output

screen shot 2017-06-29 at 22 10 46

**Comment by decadence** [comment]
@JayBizzle use `description` method on `Event`

**Pull request closed without merging**
