### PR TITLE
[5.3] Let disconnect but don't try again inside transaction

### PR DESCRIPTION
**Pull request by halaei**
Regarding https://github.com/laravel/framework/issues/15865

Not sure if I considered everything. So I am not fixing tests for now.

### CODE REVIEW

**Comment by halaei** [comment]
How about this PR @taylorotwell @themsaid?

**Comment by GrahamCampbell** [comment]
Was this changed in 5.1? Perhaps we need to fix this there?

**Comment by halaei** [comment]
It is present in 4.2 as well. It being old makes me have doubts about the PR.

**Comment by GrahamCampbell** [comment]
We don't need to care about 4.2 - only security issues. Only 5.1 LTS will get other types of bug fixes.

**Comment by taylorotwell** [comment]
Is this supposed to replace your other PR?

**Comment by halaei** [comment]
@taylorotwell Yes, this if accepted can apply to 5.1 too. No need for the other PR.
I can close this too and send PR for 5.1 (probably 2 separate PR).

**Pull request closed without merging**
