### PR TITLE
[5.4] Higher Order Array or Object Bug Fix

### PR DESCRIPTION
**Pull request by alexbowers**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Personally I would suggest just checking for is_array. It will be much faster than data_get in this situation.

**Comment by alexbowers** [comment]
Feel free to modify as you see fit.

I assume you mean to do `return is_array($value) ? $value[$key] : $value->{$key};` ?

**Comment by taylorotwell** [comment]
yes.

**Comment by alexbowers** [comment]
@taylorotwell This change has been made.

**Comment by franzliedke** [comment]
I highly advise against this. There's already enough magic involved.

If you're dealing with arrays, accessing them should work like this:
~~~
$collection->map['field']
~~~

We can do this by implementing `offsetGet` on the proxy class. I'll send a PR.

**Comment by alexbowers** [comment]
I'm happy for this to be altered if it improves the code / expectations of the code; however I would say a common API is preferential to it throwing an error if you try to access the collection as shown in the examples, and it happens to be an array.

Offtopic: @franzliedke I have sent you a message on larachat, if you get the chance to check it out, i'd be grateful :)

**Comment by franzliedke** [comment]
Collection items don't just happen to be arrays, though. You should know what you're dealing with when you are accessing a whole collection through the proxy.

That's the point of this feature: accessing all items in a collection just like you would access one object, which you can do because they all have the same type/interface. I want this to be as expectable as possible.

I've seen your message, I will get to it. ;)

**Pull request merged**
