### PR TITLE
[6.x] Composer fix monolog version range

### PR DESCRIPTION
**Pull request by dmitryuk**
Replaces deprecated composer's logical Or from "|" to "||", because official composer's documentation claims that only that should be used.
https://getcomposer.org/doc/articles/versions.md#version-range
`A double pipe (||) will be treated as a logical OR`
Double pipe is Or operator, but single pipe is logical Xor.
Official issue on composer [github](https://github.com/composer/composer/issues/6755)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please update all `composer.json` files in the repo that ref monolog.

**Comment by dmitryuk** [comment]
Ok, i will do it some later, thank you

**Comment by driesvints** [comment]
I took the liberty to revert this. The single pipe is still supported and won't be removed as @stof mentions here: https://github.com/composer/composer/issues/6755

At the moment all of the Laravel libraries use the single pipe formatting and to stay consistent it's best that we just leave things be. There's no harm in keeping the current formatting. 

Also reverted https://github.com/laravel/framework/pull/30637

**Comment by X-Coder264** [comment]
I don't see why we should revert this and remain on a deprecated solution. IMO we should do the exact opposite and fix this in all composer.json files.

**Comment by GrahamCampbell** [comment]
The old syntax gives maximum compatibility with old composer versions.

**Comment by stof** [comment]
Well, composer versions not supporting it are not relevant anymore. They won't be able to use Packagist anymore, since they don't support the composer repositories splitting metadata into separate files (Packagist kept the older format for a while to give time to upgrade composer, but at some point, it dropped the old format which was insane for performance)

**Comment by GrahamCampbell** [comment]
Ah, right. :P

**Pull request merged**
