### PR TITLE
[5.6] Fix "addSelect" to add any columns to a BelongsToMany relationship

### PR DESCRIPTION
**Pull request by tpavlek**
This is a bug that caught me in production code, so I replicated it with a (fairly contrived) unit test.

Naturally the "correct" solution for this unit test is to not have a separate table for post approvals, but it demonstrates the failing that is applicable elsewhere.

The problem, it seems, is that the `get()` method on `BelongsToMany` will not select anything if there are existing columns on the builder. But this seems to contrast with the expected behaviour of `addSelect()`. I expect `addSelect()` to _add_ a column to the current selection, not completely replace it.

I'm willing to contribute code to fix this if it is accepted as a bug.

### CODE REVIEW

**Comment by staudenmeir** [comment]
The `HasManyThrough` relationship has the same problem.

**Comment by tpavlek** [comment]
I think it's necessary because if you call `select()` instead of `addSelect()` you _do_ want that overwriting (which is accomplished in the same manner).

I think the best solution here is that `BelongsToMany` (or `HasManyThrough`) sets up a default select of `related.*` when it's instantiated, and then `addSelect` will properly merge that in.

**Comment by taylorotwell** [comment]
You're not selecting the columns needed to complete the relationship.

**Comment by taylorotwell** [comment]
I agree though it could probably be fixed if you want to submit a patch.

**Pull request closed without merging**
