### PR TITLE
[5.1] Make $this->validate() also accept array

### PR DESCRIPTION
**Pull request by mul14**
This PR will make `$this->validate()`
have same behaviour like `Validator::make($array)`

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1: breaking change

**Comment by mul14** [comment]
I don't think so. Anyone can still use the `Request` object. So it doesn't break their current application.

**Comment by GrahamCampbell** [comment]
You've made a breaking change to the function definition of a public method.

**Comment by mul14** [comment]
Understood. Should I resend this PR to 5.2/master branch?

**Comment by taylorotwell** [comment]
Indeed this would need to be done on 5.2. Graham is correct.

**Comment by GrahamCampbell** [comment]
Maybe we should rename the variable in 5.2 too since "request" isn't so correct if we modify the method in this way.

**Pull request closed without merging**
