### PR TITLE
Allow for auth routes without registration

### PR DESCRIPTION
**Pull request by amosmos**
Without breaking anything of course

### CODE REVIEW

**Comment by m1guelpf** [comment]
Have been doing this manually since I can remember... hope this gets merged :smile:

**Comment by taylorotwell** [comment]
I prefer people to just copy the routes they want and paste them in.

**Comment by amosmos** [comment]
I see. It's just so useful. 90% of our (100+) projects needs this, and I saw online so many others who use this. So I thought this can help so many people by saving them the time to copy and paste and change `$this->` to `Route::`. I agree it's not so much work but it is still something I thought you would love to be able to offer Laravel users.

Is there a way to extend the Router class in my own project somehow and add a function to it?

Thanks!

**Comment by decadence** [comment]
Use `macro` method.

**Comment by RikSomers** [comment]
@amosmos If it this common for your projects to only need login routes, why don't you create a skeleton project that only includes these routes?

The reason these routes and views are even added in the first place are to help people (new to Laravel) quickly scaffold the registration and login process. If you need anything beyond that, your best bet is to just create something yourself.

**Comment by amosmos** [comment]
@decadence thanks for the idea, I'll check it.

@RikSomers - I want something *less* then that, not beyond that. Feels weird to make an entire skeleton projects just so I will have a function that returns less routes then what laravel already does. I just know that it is a very very common use case for laravel developers, arguably more common then original routes function use case, so I suggest to add it to the framework, without breaking anything. Bottom line it's just 1 more function with 1 more line of code.

But I totally respect @taylorotwell decision to not accept this, although I'm sure one day he will see how beneficial this is to the framework :-)

**Comment by RikSomers** [comment]
@amosmos To be honest, it feels weird for me to even have the scaffolding baked into the framework in the first place. Would be much better suited in a seperate package if you'd ask me.

**Pull request closed without merging**
