### PR TITLE
[11.x] Add initial typings for QueryBuilder and some relationships

### PR DESCRIPTION
**Pull request by joelharkes**
_Added to 'master' as it could be quite a big change for static analyzers such as larastan._

This PR adds generic typings to query builder and some of the relationships (willing to put to work to make it 100% if i get a go, not wanting to waste a days of work if you do not like this idea)..

Benefits:
* Complete type system for queries and relationships (at least for 95% use cases)
* Static analyzers will be able to understand code much better and need less hoops.
* IDE will be happy with the improvements

## Benefits Query builder

Proper typing for Query build model:
image

Results:
image
image

Get results as well:
image

Proper typings for relationships:

image

Results
image

### Static analyzers

Larastan and psalm will be able to do much better and in depth analyses of correctness of the code.

### Draw backs

PHPStorm still has some problems with generics, it dies after on second level of generics:
* https://youtrack.jetbrains.com/issue/WI-71011/this-and-static-return-type-do-not-work-as-Generi-in-phpdoc-this
* https://youtrack.jetbrains.com/issue/WI-47158/Generics-support-with-template
* https://youtrack.jetbrains.com/issue/WI-63722

Which means calling the builder from a Model and getting the results without explicit type casts loses type control :-(
this is why I considered putting this on master branch and hope PHPStorm would solve this by the time this lands.

 
image

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'll need to wait for @nunomaduro to review this.

**Comment by AAllport** [comment]
Avid generics fan here! Great to see this PR come through.

@nunomaduro, do you see any way this could go into L10?
It would be a fantastic addition alongside the changes in #44545

**Comment by nunomaduro** [comment]
Thank you for your contribution to the Laravel community! We appreciate your efforts in adding types to Eloquent. Unfortunately, at this time, we cannot merge this pull request as it requires full support for generics in PHPStorm. Once PHPStorm fully supports generics, we will re-evaluate this pull request and consider merging it. Thank you for your understanding.

**Comment by joelharkes** [comment]
@nunomaduro  can i re-open the PR when PHP storm supports this?

**Comment by joelharkes** [comment]
@nunomaduro  and others please upvote on this youtrack item for support: https://youtrack.jetbrains.com/issue/WI-71011/this-and-static-return-type-do-not-work-as-Generi-in-phpdoc-this

**Comment by brendt** [comment]
FYI https://youtrack.jetbrains.com/issue/WI-63722 will be fixed in PhpStorm 2023.2 👍

**Pull request closed without merging**
