### PR TITLE
[5.4] Improvements in withoutOverlapping function.

### PR DESCRIPTION
**Pull request by Litiano**
It is now possible to enter the mutex deadline.
Correct some PHPDoc

### CODE REVIEW

**Comment by themsaid** [comment]
> It is now possible to enter the mutex deadline

I wonder why this might be useful?

**Comment by Litiano** [comment]
If the task is interrupted abruptly the mutex file is not removed, and waiting a day for it to be cleared from the cache can be very much.

**Comment by taylorotwell** [comment]
Let's not call it "mutexDeadline". Why not just "expiresAt" or something?

**Comment by Litiano** [comment]
expiresAt property could be added in Event, or left in CallbackEvent?

**Comment by taylorotwell** [comment]
Tests fail.

**Pull request closed without merging**
