### PR TITLE
[11.x] Improvements for the ServeCommand (add more loves & elevate DX)

### PR DESCRIPTION
**Pull request by sethsandaru**
Hi guys,

As a person who really loves the `php artisan serve` and jumps into the development immediately, I'd like to add some improvements and hopefully, it would help other developers too

1. Print out a better request time, for requests that take less than 1 second, `~0s` doesn't seem so helpful at all.
2. Show the request's route instead of "........." 

Thanks all.

## Before

before

## After

after

### CODE REVIEW

**Comment by chu121su12** [comment]
Any chance displaying the request method and response status code?

**Comment by sethsandaru** [comment]
> Any chance displaying the request method and response status code?

that'd be something I'll try to improve next 😄

**Comment by seriquynh** [comment]
Your improvement looks great. Hope it'll be accepted soon.

**Review by nunomaduro — APPROVED** [review]
All the changes look generally fine to me; however, I've found this particular command's code a little bit problematic when we change code on it. So, we may have to revert this pull request if we find out that it causes problems.

**Pull request merged**
