### PR TITLE
[5.4] Add a "getDot" method to Collections

### PR DESCRIPTION
**Pull request by andrey-helldar**
Get an item from the collection by dotted key.
Example:
$d = collect(['a' => ['b' => ['c' => 'hello']]]);
echo $d->getDot('a.b.c');
// hello

### CODE REVIEW

**Comment by a-komarev** [comment]
Dont like name of method, as for me it's better to extend `get` method but it will be breaking changes then :(

**Comment by andrey-helldar** [comment]
I agree, the method name is poorly. Fantasy was not enough. 😔

**Comment by taylorotwell** [comment]
No plans to add this method.

**Comment by andrey-helldar** [comment]
Why not?
I often have to use a construction:
`$d = collect(['a' => ['b' => ['c' => 'hello']]]);`
`echo $d->get('a.b.c');`

**Comment by joshmanders** [comment]
@andrey-helldar collections are macroable, write a macro that does this for you.

**Pull request closed without merging**
