### PR TITLE
Change Composer hasPackage to public

### PR DESCRIPTION
**Pull request by buihanh2304**
This method is not used in Composer class, and cannot access from outside.
So, I change it's visibility to public.

### CODE REVIEW

**Comment by buismaarten** [comment]
May be a breaking change when someone is using the method in their application.

**Comment by buihanh2304** [comment]
@buismaarten How can they use the method without create a new class extends `Illuminate\Support\Composer`, and then call to the method in that class?

**Comment by rodrigopedra** [comment]
> How can they use the method without create a new class extends Illuminate\Support\Composer, and then call to the method in that class?

That is how. And if, for some reason, they are overriding that method, changing its visibility from protected to public would make their subclass crash.

I agree that is very unlikely, and would be a very niche use case. But with the new year approaching, and thus a new Laravel version approaching, I guess it is safer to send this PR to master instead.

**Comment by buihanh2304** [comment]
@rodrigopedra 

I understood. I will change target branch to master.

**Pull request merged**
