### PR TITLE
[10.x] Fix custom themes not reseting on Markdown renderer

### PR DESCRIPTION
**Pull request by AEM5299**
This fixes the issue described in #46179. It should reset the theme to `'default'` on the Markdown renderer object if no `$theme` is set on the `Mailable` object. I've also added a test for this. This PR does not introduce any breaking changes.

There's a small inconsistency between `Mailable` and `Markdown` classes, the `Mailable` class has a default `$theme` value of `null` (implicitly the default theme), however `Markdown` has a default theme value of `'default'` ([here](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Mail/Mailable.php#L166) and [here](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Mail/Markdown.php#L28)). But fixing this inconsistency _might_ be a breaking change, so not sure if you'd want to fix it.

### CODE REVIEW

**Comment by pikseli** [comment]
Seems like it's setting the theme always to `default` unless it's explicitly defined in the `Mailable` class thus making the `markdown.theme` option in `config/mail.php` configuration file being ignored.

**Comment by driesvints** [comment]
@AEM5299 we'll need to fix that. Can you provide a follow up PR?

**Comment by AEM5299** [comment]
Opened PR #46317.

**Comment by driesvints** [comment]
We've decided to revert this PR for now.

**Pull request merged**
