### PR TITLE
Split the AuthenticatesAndRegisterUsers into two

### PR DESCRIPTION
**Pull request by madslundholmdk**
After some projects i have made in Laravel 5, I found out it not allways necessary to have a registration page.
Therefore I have split it up to two traits: AuthenticatesUsers and RegistersUsers.
Redirect functions are moved to an new trait, called RedirectPaths.
The original trait is removed.

These changes must also be changed in the laravel/laravel repo.

### CODE REVIEW

**Comment by MadsLundholmDk** [comment]
Pull request for laravel/laravel: https://github.com/laravel/laravel/pull/3305

**Comment by MaartenStaa** [comment]
There was a similar pull request before, but I hope it gets accepted this time. I can see how this can be a relatively common scenario.

**Comment by RomainLanz** [comment]
Use tabs and not space.

**Comment by JoostK** [comment]
There was indeed a previous PR to do this and it was rejected. I liked that one better as it was not breaking BC, this one does (and must therefore be targeted against the master branch). I wouldn't go ahead with retargeting this though, as this is not very likely to be merged anyway.

**Pull request closed without merging**
