### PR TITLE
[5.3] Added release notes for v5.3.1

### PR DESCRIPTION
**Pull request by tillkruss**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Wonder if we should adopt the same changelog format as symfony. There will be another 5.2 release coming soon you see.

**Comment by tillkruss** [comment]
I'm cool either way. @taylorotwell?

**Comment by taylorotwell** [comment]
Yeah I could see that being useful.

**Comment by tillkruss** [comment]
I'll split them up with the next 5.2 and 5.3 release.

**Pull request merged**
