### PR TITLE
[9.x] Improve pop method in Collection

### PR DESCRIPTION
**Pull request by moharami**
when we use pop with count zero or negative, doesn't remove items correctly. I fix that and add some tests for this purpose.

### CODE REVIEW

**Comment by taylorotwell** [comment]
What was the previous behavior?

**Comment by ankurk91** [comment]
This statement should already take care of negative count

`min($count, $collectionCount)`

**Comment by moharami** [comment]
**Previous Behavior**
    
    $c = collect(['foo', ' bar', 'baz']);
    $c->pop(0); //["baz", " bar"]
    $c->all(); //["foo"]


    $c = collect(['foo', ' bar', 'baz']);
    $c->pop(-1); //["baz", " bar", "foo"]
    $c->all(); //[]


    $c = collect(['foo', ' bar', 'baz']);
    $c->pop(-5); //["baz", " bar", "foo", null, null, null, null]
    $c->all(); //[]



**Explain Behavior Case 1:**

  for example, when we put -5 in count in pop methods, it goes here

     $collectionCount = $this->count();

        foreach (range(1, min($count, $collectionCount)) as $item) {
            array_push($results, array_pop($this->items));
        }

        return new static($results);

and it behaviour like this

        min($count, $collectionCount) // min(-5 , 3)  = -5
        range(1, min($count, $collectionCount) // range(1, -5) = [1, 0,-1,-2,-3,-4,-5]

and array_pop iterate 7 time, and it removes 7 item from collection(that has just 3 item)

**Explain Behavior Case 2:**
when we put zero

    min($count, $collectionCount) // min(0 , 3)  = 0
    range(1, min($count, $collectionCount) // range(1, 0) = [1, 0]

and array_pop remove 2 item from collection

**Comment by taylorotwell** [comment]
I don't know if I really want to mess with this on a patch release.

**Pull request closed without merging**
