### PR TITLE
[7.x] Make attributes available within render method

### PR DESCRIPTION
**Pull request by taylorotwell**
Currently `$this->attributes` is `null` within a component's `render` method. This solves that by allowing components to return a `Closure` from `render` to defer the template building... which allows you to do some pretty funky stuff.

```php
public function render()
{
    return function ($data) {
        // return $data['attributes'];
        // return $this->attributes;
    };
}
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
Eh, this has a breaking change that $this->foo set in `render` will not be available in the template.

**Comment by Pennywise96** [comment]
Hello,
how can I get this to work?

If I put the ```return function ($data) ``` in my component render function, I get this error:
```syntax error, unexpected '}', expecting ';' ```


Did I forget something there?

**Comment by driesvints** [comment]
@Pennywise96 this hasn't been released yet. Next Tuesday it will be.

**Comment by Pennywise96** [comment]
@driesvints I have now updated to version 7.14.0, but I still get the same error.
Did I forgot something?

**Comment by mennovanhout** [comment]
> @driesvints I have now updated to version 7.14.0, but I still get the same error.
> Did I forgot something?

As your error states. You're just using it wrong it seems. Probably you made a syntax error, But your snippet is to small to give any more details.

**Comment by Pennywise96** [comment]
This is the code of the component:

```
<?php

namespace App\View\Components\wg\tmpl;

use App\Models\Page;
use Illuminate\View\Component;

class Navigation extends Component
{
	
	public $nodes;
	public $type;
	
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($nodes="0", $type="0")
    {
        $this->nodes = $nodes;
        $this->type = $type ?? 'full';
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
	{
	    return function ($data) {
	        $data['attributes'];
	    }
	}
}
```

and this is the error message:

```
Facade\Ignition\Exceptions\ViewException
syntax error, unexpected '}', expecting ';' (View: /Applications/XAMPP/xamppfiles/htdocs/cms2/public/templates/index.blade.php)
```

**Comment by BrandonSurowiec** [comment]
Looks like you missed a semi-colon:

```
    public function render()
	{
	    return function ($data) {
	        $data['attributes'];
	    }; // <-- right here
	}
```

**Pull request merged**
