### PR TITLE
[5.8] Add Model::saveAttributes() to save only certain attributes of a model

### PR DESCRIPTION
**Pull request by cmorbitzer**
This adds a new method `saveAttributes()` to models that only saves the given attributes of the model instead of all changed attributes.

For example, if I change the `name` and `email` attributes of my `User` instance `$user`, and then call `$user->saveAttributes(['name'])`, only the name will be saved. The email will remain changed on the instance, but will not be updated in the database. The tests added for this provide additional examples.

This is useful for cases where attributes of a model need to be changed and those changes persisted in the database, but it is not known if other attributes have already been modified on the instance without intention of immediately being saved. In those cases, using `save()` could introduce an unintended side effect of altering data where it is not obvious.

Consider a contrived example:
```php
$user = User::find(1);
$user->email = $request->input('email');
$user->emailService()->activateService();
// Do other logic...
$user->save();

class User {
    public function emailService() {
        return new EmailService($this);
    }
}

class EmailService
{
    protected $user;

    public function __construct(User $user) {
        $this->user = $user;
    }

    public function activate()
    {
        $token = $this->httpClient->post('https://external.api');
        $this->user->service_token = $token;
        // Since the external service is activated, save the token
        // instead of hoping future developers using this method
        // remember that step.
        $this->user->saveAttributes(['token']);
        // Perhaps more logic here...
    }
}
```

In this case, if `activateService()` used `save()`, all attributes that had been changed on the User model would be saved even ones that the service is not aware of. If it uses `User::find(1)->update()`, then the corresponding model events are not fired. This solution allows a developer to safely save only the attributes that are meant to be saved and still fire the model events, without disrupting whatever else might be happening with the model instance.

Open to discussion/suggestions.

### CODE REVIEW

**Comment by mfn** [comment]
Adding a method on Eloquents Model can't be done a point release as it might break with existing users codebases who might have added such a method.

I re-read your use cases multiple times but still don't fully understand _why_ this is truly useful.

> In this case, if `activateService()` used `save()`, all attributes that had been changed on the User model would be saved even ones that the service is not aware of

In your example, the service also sets the token.

You mean if something outside/before the service already mutated the user?

But isn't that rather a architecture problem, that then the user shouldn't be saved by the service but somewhere else?

**Comment by driesvints** [comment]
> Adding a method on Eloquents Model can't be done a point release as it might break with existing users codebases who might have added such a method.

Sure it can. Extending the public api without breaking changes is a valid thing to do. We can't account for every scenario where people "might" have implemented a method themselves. This isn't a breaking change.

**Comment by mfn** [comment]
What?

Of course it is. Especially given that people _are very likely_ to add any kind of code to models (even they shouldn't).

**Comment by driesvints** [comment]
@mfn it isn't. From the SemVer documentation (https://semver.org/#spec-item-7):

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API.

You can't possible account for every override that *could* be made.

(I know Laravel atm isn't semver but that's besides the point now).

**Comment by taylorotwell** [comment]
I don't think I'm going to add this to the core right now but should work perfectly fine if you add it to a base Eloquent model in your application that all of your other models extend.

**Pull request closed without merging**
