### PR TITLE
[9.x] Add contains[Any|All|None] in Collection 

### PR DESCRIPTION
**Pull request by michaelnabil230**
This PR to add `containsAll`,`containsAny` and `containsNone` in to Collection.
These functions allow checking the presence of any, none, or all values.

ِExamples for use:
```php

use Illuminate\Http\Request;

class UserController
{
    public function __invoke(Request $request)
    {
        $request->validate([
            'names' => ['required', 'array'],
        ]);

        $names = $request->collect('names');

        if ($names->containsAll(['Taylor', 'Michael'])) {
            # code...
        }

        if ($names->containsAny(['Taylor Otwell', 'Michael Nabil', 'Khaled Ahmed'])) {
            # code...
        }

        if ($names->containsNone(['Marian', 'Ahmed', 'Menna'])) {
            # code...
        }
    }
}
```

Another example:
```php 

use Illuminate\Http\Request;

class BookController
{
    public function __invoke(Request $request)
    {
        $books = ['book1', 'book2', 'book3'];
        
        if (collect($books)->containsAll(['book1', 'book2'])) {
            # code...
        }

        if (collect($books)->containsAny(['book1', 'book2', 'book5', 'book6'])) {
            # code...
        }

        if (collect($books)->containsNone(['book4', 'book5'])) {
            # code...
        }
    }
}


```

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by michaelnabil230** [comment]
@taylorotwell I’m very sad whenever I try to develop in framework, you refuse, I don’t know where the problem is.

**Comment by rennokki** [comment]
@michaelnabil230 I had about 10 PRs rejected before having some meaningful ones. It gets some time understanding the needs of the framework in order to come up with solutions.

For your case, I think you might want to try [Spatie's Collection Macros](https://github.com/spatie/laravel-collection-macros) or do it yourself with the macros: https://laravel.com/docs/9.x/collections#extending-collections

**Comment by michaelnabil230** [comment]
@rennokki You have a right to talk about you, but how can I know that? There is no place where developers talk about anything related to the updates they already need.

**Comment by rennokki** [comment]
@michaelnabil230 https://github.com/laravel/framework/discussions

**Comment by michaelnabil230** [comment]
@rennokki ‏I just created this pull request, but it's rejected as normal.

https://github.com/laravel/framework/pull/42699

**Comment by rennokki** [comment]
@michaelnabil230 There are things that can be done using macros, validations have too. If they were to accept each PR like this, the Framework would be bloated quickly. It was a purpose behind macros. Some features might help only you, and having it built-in would increase the size and complexity of the framework for everyone else.

**Comment by michaelnabil230** [comment]
‏I understand you well.

**Comment by michaelnabil230** [comment]
‏I understand you well.

**Comment by michaelnabil230** [comment]
‏I understand you well.

**Pull request closed without merging**
