### PR TITLE
[5.1] Make URL generator macroable

### PR DESCRIPTION
**Pull request by vlakoff**
Currently to extend `URL` I have to do very shameful things.

Two-liner. Just amazing cost-benefit ratio.
Also notice `Route` is already macroable.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I'm :-1: for adding static states everywhere.

**Comment by vlakoff** [comment]
All I want is to add a method to `URL`. It should be simple to extend, but actually it isn't at all.

What do you propose?

**Comment by taylorotwell** [comment]
What method did you want to add?

**Comment by vlakoff** [comment]
I tweaked a bit the `RoutingServiceProvider`, [here are the changes](https://github.com/laravel/framework/compare/5.1...vlakoff:registerUrlGenerator), split in several commits for clarity.

The main change is isolating the `UrlGenerator` instanciation, so a different class can easily be used by extending the service provider.

**Comment by taylorotwell** [comment]
Still curious what method you wanted to add

**Comment by vlakoff** [comment]
Two close examples:
* Disabling the "session fallback" mechanism in `previous()` as I really disagree with it.
* Adding `previousOr($fallback)` to let choose the fallback URL.

Refs notably #10229.

**Pull request merged**
