### PR TITLE
Fix bug in \Illuminate\Database\Query\Builder

### PR DESCRIPTION
**Pull request by palicao**
Fixes a bug in the query builder where, when an empty or invalid
operator was provided, the value was swapped with the operator itself.

### CODE REVIEW

**Comment by staudenmeir** [comment]
As the failed tests show, this causes other problems. The fix would have to look something like this:

````php
if (func_num_args() === 3 && $this->invalidOperator($operator)) {
    list($value, $operator) = [$value, '='];
}
````

**Comment by staudenmeir** [comment]
You should also target the 5.6 branch, not 5.5.

**Comment by taylorotwell** [comment]
Pass a valid operator.

**Comment by palicao** [comment]
@taylorotwell what's invalid in "="?

**Comment by staudenmeir** [comment]
He is referring to the test query: `where('foo', '', 'bar')`

**Comment by palicao** [comment]
Yeah but then the (buggy) code that tries to fix an invalid operator should be removed as well. Just a suggestion, I won't spend any more time trying to contribute where contribution is not welcome!

**Pull request closed without merging**
