### PR TITLE
Adds composer for foundation

### PR DESCRIPTION
**Pull request by jmverges**

### CODE REVIEW

**Comment by jmverges** [comment]
I was just thinking, why not? I don't know if you already had this discussion. Please, let me know.

**Comment by jmarcher** [comment]
I do not think this is necessary read more here: https://github.com/laravel/framework/pull/21734#issuecomment-337695848

**Comment by jmverges** [comment]
Thank you @jmarcher. 

However, is this a political reason or code wise reason? It's for my understanding. 

In my opinion, for doing experiments for others developers, could be neat to have all of them in separate repositories and foundation too. In this way you could have different foundations if you are doing projects that only need parts of the framework. 

This could be good for other frameworks or cms's. I know about the possibility of having just a package of the framework and I know I could create my own Foundation copy pasting the framework one, but to keep track of the changes between versions would be more complex.

@taylorotwell "political/strategical" reason or code wise? Thank you in advance 👍

**Comment by devcircus** [comment]
Not sure what you mean by political / strategical but Foundation would have to basically require the entire framework. All of the code in Foundation is specific to Laravel and serves no purpose in any other context.

**Comment by taylorotwell** [comment]
This isn't a thing.

**Comment by jmverges** [comment]
@devcircus @taylorotwell if foundation requires everything, but everything else could be decoupled in other repositories (as they are read-only at the moment) then, wouldn't make any sense to require Foundation (as isolated package) and this package require everything else (as isolated packages) instead of require Framework and don't use half of it? I really would like to understand the reason, please.

**Comment by jmverges** [comment]
in fact: https://packagist.org/packages/illuminate/foundation ?

**Comment by jmverges** [comment]
#21770

**Comment by browner12** [comment]
AFAIK, doing things as dependencies vs doing them as subtrees has tradeoffs both ways.  There's no clear winner, so this how it's done, and there's no real reason to change to a purely dependency setup.

**Comment by jmverges** [comment]
@browner12 imo subtress is more confortable to work in you machine if you work only on the project lets say. however if you want to experiment or create "things" based on the framework dependencies get more confortable. However, I'll open in internals some ticket, but I see, in general,  there is not interest at all, so I will shut up. Thanks anyway 👍

**Pull request closed without merging**
