### PR TITLE
[4.2] Expand on PHP7 compatiblity with __isset() fix from 5.3 branch

### PR DESCRIPTION
**Pull request by GenPage**
I was unable to cherry-pick the commit since so much has changed from 4 -> 5, so I applied the fix manually. 

Reference commit: https://github.com/laravel/framework/commit/8fb89c61c24af905b0b9db4d645d68a2c4a133b9
Conversation: https://github.com/laravel/framework/pull/13509#issuecomment-256683363

### CODE REVIEW

**Comment by FelipeeDev** [comment]
This change is too crucial to putting it in the 4.2 branch. I think that it should be moved to 4.3. It casue few bugs with undefied fields and relations. For example... now... all the unset fields/attributes are checked with camelCase - methods, with can give a different result then a relation. I think it's a bug now (for 4.2).

**Comment by GrahamCampbell** [comment]
There is no 4.3, but I see your point about this bug being the expected behaviour in 4.2.

**Comment by FelipeeDev** [comment]
Yes, I know that there's no 4.3. But I'm not sure does this change should be merge here...

**Comment by drecken** [comment]
Seems like this just broke our App in production :/

Relationship method must return an object of type Illuminate\Database\Eloquent\Relations\Relation

**Comment by taylorotwell** [comment]
Reverted.

**Comment by sjoerdloeve** [comment]
Is there a better fix for this problem? We are running into the same problem after upgrading to PHP 7.0 on Laravel 4.2. Off course upgrading to Laravel 5.5 is the best choice, but at this time we do not have time for that. 

Changing `__isset()` and `offsetExists()` as is on Laravel 5.5 fixes our problem.
But as you are reverting that solution: Can you help with the correct solution? 

Main problem:
`empty(User::first(['name'])->name)` provided true now, also when it is filled with a value.

**Comment by sjoerdloeve** [comment]
**Update on situation**
The problem only appears on relations with case conversion. The relation will be converted to snake_case on the output, but with `empty` and `isset` you won't be able to check on snake_case property. When you use the camelCase it works fine.. 

Example on PHP 7.0:
```
$user = User::with('testRelation')->first();
dd( empty($user->test_relation->name), empty($user->testRelation->name) );
// Result:  true, false

Example on PHP 5.6:
dd( empty($user->test_relation->name), empty($user->testRelation->name) );
// Result:  false, false

**Pull request merged**
