### PR TITLE
[5.5] Add the ability to handle nested levels in collection.

### PR DESCRIPTION
**Pull request by mathieutu**
Hi,
With this PR, we can now manage nested arrays and traversables in collection.
Before, only the first level of an array was converted to a collection, it can be painful when you're trying to chain many operations on many levels.

I had the problem myself, and I've seen many posts about that in forums like laracast or stackoverflow, so I think this should be handled in the core.

Thank you for your time and your work.

### Example:
```php
$nestedArray = [
    '1stLevel' => [
        '2ndLevel' => [
            '3rdLevel' => [
                'value'
            ]
        ]
    ]
];
```
#### Before : 
```php
$c = collect($nestedArray);
$c->get('1stLevel'); // array

$c->each(function ($value, $key) {
    dump($key, gettype($value)); // '1stLevel', array
    return (new Collection($value))->each(function ($value, $key) {
        dump($key, gettype($value)); // '2ndLevel', array
        (new Collection($value))->each(function ($value, $key) {
            dump($key, gettype($value)); // '3rdLevel', array
            (new Collection($value))->each(function ($value) {
                dump(gettype($value)); // string
            });
        });
    });
});
```

#### After:
```php
$c = collect($nestedArray)->parseNested();
$c->get('1stLevel'); // Collection

$c->each(function ($value, $key) {
    dump($key, get_class($value)); // '1stLevel', Collection
    return $value->each(function ($value, $key) {
        dump($key, get_class($value)); // '2ndLevel', Collection
        $value->each(function ($value, $key) {
            dump($key, get_class($value)); // '3rdLevel', Collection
            $value->each(function ($value) {
                dump(gettype($value)); // string
            });
        });
    });
});
```

### Bonus:
You can also declare a `$nested` boolean when you create the collection:
```php
(new Collection($nestedArray))->get('1stLevel'); // array
(new Collection($nestedArray, true))->get('1stLevel'); // Collection
```
I wondered about this: this can be cool, but if you think we shouldn't change the constructor, no problem I can edit and leave only the `parseNested` method.

### CODE REVIEW

**Comment by taylorotwell** [comment]
No plans to add this.

**Comment by mathieutu** [comment]
@freekmurze Interested by that for your package ?

**Comment by freekmurze** [comment]
@mathieutu thanks for the offer, but since if haven't got a need for this functionality myself, I'm going to pass on this.

**Comment by mathieutu** [comment]
ok, too bad!

**Pull request closed without merging**
