### PR TITLE
[9.x] Fix original is equivalent

### PR DESCRIPTION
**Pull request by tntsoft**
Relationships seem to be spilling over as attributes. They are being picked up as `dirty` always and then the framework is attempting an Update statement on them. The columns don't exist in the specified tables, thus it errors out.

Assuming that Relationships have no reason to be in attributes in the first place, this does not fix the root cause of the issue, but patches the problem.

This PR is made to bring this to your attention, I'm not sure how to replicate the problem in a separate repository.

Please let me know what I can do to shed some light on this issue so we can get this resolved.

Screenshot 2022-05-07 at 20 16 16
Screenshot 2022-05-07 at 20 16 03
Screenshot 2022-05-07 at 20 15 40

### CODE REVIEW

**Comment by tntsoft** [comment]
To further elaborate, this is the error that I'm getting.

**Exception**
```SQLSTATE[42S22]: Column not found: 1054 Unknown column 'currency' in 'field list' (SQL: update `users` set `currency` = {"id":2,"name":"CAD","code":"CAD","description":"Canadian Dollar","created_at":"2022-05-06T19:05:34.000000Z","updated_at":"2022-05-06T19:05:34.000000Z"}, `can` = {"view_reports":false,"approve_awards":false}, `users`.`updated_at` = 2022-05-08 05:50:27 where `id` = 5)```


**Stacktrace**
```

/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Database/Connection.php:702
--
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Database/Connection.php:559
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Database/Connection.php:492
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3256
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:994
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1104
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1019
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1055
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:30
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1056
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:905
/opt/homebrew/var/www/PHP8.0/rr-core/app/Http/Controllers/LanguageController.php:31
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Routing/Route.php:261
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Routing/Route.php:204
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Routing/Router.php:725
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/inertiajs/inertia-laravel/src/Middleware.php:88
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/app/Http/Middleware/Translation.php:34
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:50
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:44
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:121
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:64
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:116
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Routing/Router.php:726
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Routing/Router.php:703
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Routing/Router.php:667
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Routing/Router.php:656
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:167
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:67
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php:31
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php:40
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php:86
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/fruitcake/laravel-cors/src/HandleCors.php:52
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php:39
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:116
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:142
/opt/homebrew/var/www/PHP8.0/rr-core/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:111
/opt/homebrew/var/www/PHP8.0/rr-core/public/index.php:52

```

**Screenshot**

query

**Comment by bert-w** [comment]
I think there is some bug in your code. Relations shouldnt become part of the `attributes` property of an Eloquent model.

**Comment by DarkGhostHunter** [comment]
> Models seem to have Relationships as attributes in some cases. 

> Relations shouldn't become part of the attributes property of an Eloquent model.

This ☝

If you set a relation as an attribute, Eloquent will think it belongs to a column table, hence the error. Relations are loaded into their own separate property array, so this problem never happens.

You should refactor your Model and code to never do that.

**Comment by tntsoft** [comment]
Nobody set any relationships as attributes, the problem only appears when the `Auth::user()` facade is invoked.

We are an organization and this is an enterprise project, multiple developers have reviewed the code and structure.

As you can see in my screenshot, alongside our `currencies` relationship, Spatie Permissions `can` gate has also spilled through into attributes.

I am happy to share the entire repository privately with a Laravel employee and even demo the problem on a call.

Have patched the issue temporarily by not calling `update` on the `Auth::user()` instance, and finding the user in the DB instead.

**Comment by tntsoft** [comment]
> > Models seem to have Relationships as attributes in some cases. 
> 
> 
> 
> > Relations shouldn't become part of the attributes property of an Eloquent model.
> 
> 
> 
> This ☝
> 
> 
> 
> If you set a relation as an attribute, Eloquent will think it belongs to a column table, hence the error. Relations are loaded into their own separate property array, so this problem never happens.
> 
> 
> 
> You should refactor your Model and code to never do that.

In the shared screenshot you can see that `currencies` is a relationship and not an attribute.

What you are implying is probably something like `getCurrenciesAttribute` and returning a relationship - which we would never do.

**Comment by tntsoft** [comment]
I believe we might have caught the issue and it appears to somehow be `Sanctum` related.

We were attempting a language update on the `Auth::user()` using the `auth` middleware, but we're actually authenticated via Sanctum spa. 
Screenshot 2022-05-09 at 07 08 09

Once we moved the route to `auth:sanctum`, everything's right again.
Screenshot 2022-05-09 at 07 08 21

The relationship isn't spilling into attributes anymore.
Screenshot 2022-05-09 at 07 13 14

**Comment by DarkGhostHunter** [comment]
You may need to replicate that on [Sanctum](https://github.com/laravel/sanctum) instead if that's the culprit.

**Comment by driesvints** [comment]
There's commits on this PR that don't belong here. Please resend this.

**Comment by driesvints** [comment]
Just read the details of this. Please try a support channel as well as I also think this is a bug with your app, not with Laravel.

**Pull request closed without merging**
