### PR TITLE
[5.2] Add where time support query

### PR DESCRIPTION
**Pull request by johnpaulmedina**
Added the ability to query with whereTime support for MySQL
#14364

### CODE REVIEW

**Comment by johnpaulmedina** [comment]
If this works well how can we push this to 5.3 release?

**Comment by fernandobandeira** [comment]
5.3 receive merges from the whole 5.2 branch, also 5.2 receives from 5.1 then eventually if this get into 5.2 it will go to 5.3 too...

**Comment by jmarcher** [comment]
I think that you need to make a few tests to ensure everything works properly

**Comment by tillkruss** [comment]
@johnpaulmedina Could you provide 1-2 tests?

**Comment by johnpaulmedina** [comment]
It was already merged in. I actually use this on production myself and shared it. I will keep in mind to provide the tests with it next time.

I use it for statistics and metrics on agents in a call center between date x and date y BUT only between time x and time y of each of those dates in the range.

I didn't really write this code. It technically already exist in laravel framework for whereDay whereYear whereMonth whereDay... all I did was duplicate one of those and change the MySQL function it calls to time().

**Pull request merged**
