### PR TITLE
[5.8] Replace deprecated phpunit <7.5.0 methods

### PR DESCRIPTION
**Pull request by imanghafoori1**
replace deprecated phpunit methods with new ones

see this link : 

https://github.com/sebastianbergmann/phpunit/issues/3368

Note that the composer.json file now requires phpunit 7.5 or more
--

image

### CODE REVIEW

**Comment by imanghafoori1** [comment]
I don't know whether I should make the same PR for 5.7 or not...

**Comment by imanghafoori1** [comment]
This tests fail in the `env:lowest` config.
because in that case phpunit version is 7.0.0

**Comment by devcircus** [comment]
Is there anything stopping us from bumping the minimum requirement for phpunit in 5.8 to 7.5?

**Comment by GrahamCampbell** [comment]
Please send this to the 5.7 branch, since all these changes only affect the tests, so we can safely bumb the minimum version of phpunit, without it being a breaking change, since it is with respect to testing the framework itself.

**Pull request closed without merging**
