### PR TITLE
[7.x] Times helper method

### PR DESCRIPTION
**Pull request by RedFernLiam**
Current ugly ways to loop a set number of times...

```php
foreach (range(1, 5) as $i) { // }
```

```php
for ($i = 0; $i < 5; $i++) { // }
```

```php
collect(range(1, 5))->each(function ($i) { // })
```

Proposed way with helper method...

```php
times(5)->each(function ($i) { // }
```

Open for suggestion for the name of this method as it could be misinterpreted that the method is mathematical and the parameter is being multiplied?

### CODE REVIEW

**Comment by browner12** [comment]
that is literally why the `for` loop exists in PHP.

you're gonna need a stronger argument than "it's ugly".

**Comment by RedFernLiam** [comment]
@browner12 A helper is a helper. You could say the same for the `last` helper in core which is just php for `end`.

**Comment by derekmd** [comment]
This is already supported by https://laravel.com/docs/7.x/collections#method-times

```php
collect()->times(5, function ($i) {
    // $i starts at 1
});
```

**Comment by RedFernLiam** [comment]
Thanks @derekmd I must have missed that. I will close this PR because it open the argument to having all collection methods as helpers which is dumb.

**Comment by decadence** [comment]
No need to call times after collect helper. times is static method on Collection class.

**Pull request closed without merging**
