### PR TITLE
Add paginate method to Collection class

### PR DESCRIPTION
**Pull request by simonhamp**
See (#3463) and https://gist.github.com/simonhamp/549e8821946e2c40a617c85d2cf5af5e

### CODE REVIEW

**Comment by ntzm** [comment]
I believe this should be done via a macro in a service provider, because `illuminate/support` doesn't depend on `illuminate/pagination`

**Comment by taylorotwell** [comment]
No plans to add.

**Comment by simonhamp** [comment]
I thought the reliance would be an issue. Shame

**Comment by tylerwiegand** [comment]
I'm curious to know WHY this wasn't added -- when I need to sort through and filter out many models and combine collections to get a desired result it is rather annoying that I can't just ->paginate(12) like I can with the query builder. Spent 2 days on this issue, only to find it has been solved and rejected. I'm sure there IS a reason, but I want to know it.

**Comment by LMCom** [comment]
I have an index page with paginated results. There is one particular filter, that the user can choose, that only can be applied after getting the result from the database, since it depends on the model rather than the database table. That is one example of a use case, where a paginate method for Collection is indispensable. Adding @simonhamp's solution as a macro appears to be the only way to fulfill the requirements.

**Comment by kasperhartwich** [comment]
This makes so much sense to work out of the box.. Sad to see it being rejected. :-(

**Comment by Jofairden** [comment]
I was looking for this feature. Sad that it still isn't even considered as of 2020, it's clearly very useful and the denial has plenty of downvotes. You should reconsider.

**Comment by felix2056** [comment]
Seriously this is getting annoying. I spent 2 whole days trying to get around this and had to write spaghetti to finally get it to work until I found this.
It has become a requirement to have this functionality on bigger applications. Such a shame it's still not on 7.0

**Pull request closed without merging**
