### PR TITLE
[5.3] Add isNotEmpty to Collection

### PR DESCRIPTION
**Pull request by bobbybouwmann**
Just a minor improvement for more readabililty and less `!` in code

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR.

**Comment by ntzm** [comment]
Don't really see the point in this to be honest

**Comment by GrahamCampbell** [comment]
Best leave to Taylor to decide. :)

**Comment by taylorotwell** [comment]
Probably will hold off on this for now.

**Comment by bobbybouwmann** [comment]
Fine with me, thank you for reviewing ;)

**Comment by holtkamp** [comment]
my 2 cents: "it *is* a Support package, right?". So helper functions to spice up life ought to be welcome...

**Pull request closed without merging**
