### PR TITLE
[5.8] Add default parameter to value method.

### PR DESCRIPTION
**Pull request by lucasmichot**
Add default parameter to `value` method.

### CODE REVIEW

**Comment by mfn** [comment]
What does it fix?

And why only to `Eloquent\Builder`, what about `Query\Builder`?

**Comment by lucasmichot** [comment]
> What does it fix?

It does not fix anything, it's feature that avoid doing `->value('field') ?: 'default value'`

I don't know if this PR will be merged. If it is, I'll make another one

**Comment by sisve** [comment]
Those two statements are not identical. This change would be a default value in case there's no matching row, while `?: 'default value'` would cover both missing rows or false-ish values.

**Comment by lucasmichot** [comment]
I've added this to a builder macro, I am not sure this is of interest

**Pull request closed without merging**
