### PR TITLE
[9.x] Improve `Support\LazyCollection` type definitions

### PR DESCRIPTION
**Pull request by sebdesign**
Similarly to #38538, this PR makes the `LazyCollection` generic.

I haven't tested this with PHPStorm or Psalm, but in VSCode + PHPStan extension it works great.

Also:

- Fixed some minor issues with the `Support\Collection` types
- Added missing tests for some methods

There are still a few issues with the constructors and the `make()` method of the collections:
- The `Support\LazyCollection` needs to widen the type of items it accepts, because it accepts `callable`s that return `Generator`s, but the `Support\Collection` does not accept that. I have extended the `make` method and it works as expected.

- For some reason `new Eloquent\Collection([new User()])` returns `Eloquent\Collection<(int|string), Eloquent\Model>` instead of `Eloquent\Collection<int, User>`. If I extend the constructor it works (but I haven't included this).

### CODE REVIEW

**Comment by driesvints** [comment]
Seems like tests are failing here. Feel free to markt his as ready when tests are passing.

**Comment by sebdesign** [comment]
All good now! Maybe @nunomaduro would like to review this?

**Comment by driesvints** [comment]
Ping @JosephSilber

**Comment by sebdesign** [comment]
Also, @JosephSilber I think there is an issue with the internal types the `LazyCollection`: The `makeIterator` returns a `Traversable` but it is used as if it's an `Iterator`.

**Pull request merged**
