### PR TITLE
[5.3] Add not_before and not_after rules

### PR DESCRIPTION
**Pull request by mnabialek**
Added to 2 date rules that I always miss:

**not_before** - same date or after
**not_after** - same date or before

A bit of code has been refactored, so if approved someone more experienced should probably also look at this to make sure nothing won't be broken

### CODE REVIEW

**Comment by themsaid** [comment]
What's the difference between `not_before` and the current `after`?

**Comment by mnabialek** [comment]
`after` accepts only date after date given not including given date and `not_before` accepts given date and date after it, so `not_before` is `after` + given date. Same with `not_after` rule.

For example, now when I want to set `paid_at` field that should be today or future I have to use `before:tomorrow` and it would be much obvious to use `not_after:today` but it will be even more helpful when I have 2 dates and day might equal or second should be after the first. Using current rules `after` or `before` won't work because they won't handle case when dates are same.

**Comment by themsaid** [comment]
I think `before:tomorrow` serves the purpose, it means today or any day in the past is valid which is what you want to have, right?

**Comment by mnabialek** [comment]
Yes, this case yes, it can be do this way, but if have 2 date fields: `start` and `end` and we want `end` >= `start` as far as I know there's now way to validate it using predefined validation rules, `after` rule will fail `end` = `start`

**Comment by themsaid** [comment]
You can do the following:

```
"end" => "after:".Carbon::createFromFormat("Y-m-d H:i:s", input('start'))->yesterday()
```

**Comment by mnabialek** [comment]
Yes, of course this can be done this way. I can calculate any date and type in, but as you see syntax would be much cleaner if such rules could be used. If you look at http://stackoverflow.com/questions/27018045/how-to-make-an-input-date-field-greater-than-or-equal-to-another-date-field-usin you will see that other people also are looking for after and before that use >= or <= operator

**Pull request closed without merging**
