### PR TITLE
refactored make:migration to make its options more customizable

### PR DESCRIPTION
**Pull request by mxts**
refactored `make:migration` to make its options more customizable via `getOptions()`

### CODE REVIEW

**Comment by mxts** [comment]
Sorry, I can't quite make out which test is failing. Help? Thank you.

**Comment by mxts** [comment]
I created another branch just to test at my repo and all passed... https://github.com/avexsoft/framework/actions/runs/1062530946
GitHub issue?

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by mxts** [comment]
@taylorotwell 

Thanks for getting back. This is not a bug per se, but in the way `make:migration` is currently written that makes it not extendable, or at least, I don't know another way of extending it.

If we look at `make:model` , `make:controller`, `make:factory` and a few other commands, they are declared using `protected $name` and becomes extendable by creating a singleton in a package which overrides `getOptions()` and `getArguments()`.

https://github.com/laravel/framework/blob/709714d3d296b1557038e362b9405b9d65528572/src/Illuminate/Foundation/Console/ModelMakeCommand.php#L16

https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Routing/Console/ControllerMakeCommand.php#L16

https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Database/Console/Factories/FactoryMakeCommand.php#L16

In contrast, `make:migration` is defined using `protected $signature`

https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Database/Console/Migrations/MigrateMakeCommand.php#L16-L21

So what I was trying to do was to extend `make:migration` for in one of my packages, however, it just wouldn't work due to the use of `protected $signature`.

This is where commands are processed differently if not declared using `$signature`.
https://github.com/laravel/framework/blob/306208394bf05f9acebce3663c3cfb7e3b1ac21c/src/Illuminate/Console/Command.php#L84-L86
https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Console/Concerns/HasParameters.php#L15-L33

My PR refactors `make:migration`'s `$signature` into `$name` + `getOptions()` + `getArguments()` while retaining the original behavior. 

Hope my explanation makes sense. Thank you.

**Pull request closed without merging**
