### PR TITLE
[9.x] Dispatch jobs with the ShouldBeUnique interface only once after response

### PR DESCRIPTION
**Pull request by redelschaap**
When using the `dispatchAfterResponse` function on a job that implements the `ShouldBeUnique` interface, I would expect it to be dispatched only once after response. Instead, these jobs are dispatched as many times as you call the function.

Dispatching them only once is very useful when you have more than one reason to dispatch a job, but you need it to be actually running one time.

This PR offers a solution, just not sure if this would be considered a breaking change.

### CODE REVIEW

**Comment by ankurk91** [comment]
It should rather check the lock key.

How does it work with Octane?

**Comment by redelschaap** [comment]
Let me see if I can make this work using a lock key.

Never worked with Octane myself. Let me also see if I can try that out.

**Comment by redelschaap** [comment]
Lock key is now implemented.

I'm afraid I don't have the ability to set up and test with Octane now. Is there "an easy way" to test this or could someone else test this on Octane?

**Comment by ankurk91** [comment]
Since you are no longer storing the keys within class, there is no concerns with Octane now

**Comment by redelschaap** [comment]
Good to know!

**Comment by taylorotwell** [comment]
Please provide examples for how to recreate the broken situation now so we can see what you are referring to.

**Comment by redelschaap** [comment]
In the following situation, the job will be executed thrice:

```php
JobImplementingTheShouldBeUniqueInterface::dispatchAfterResponse();
JobImplementingTheShouldBeUniqueInterface::dispatchAfterResponse();
JobImplementingTheShouldBeUniqueInterface::dispatchAfterResponse();
```

For example, I use the `dispatchAfterResponse()` method on jobs that needs to run for different types of a specific model, while looping through them. Let's say I have 10 records with in total 3 different model types, I need this job to be dispatched 3 times. Instead, the job will be dispatched and executed 10 times.

However, because they implement the `ShouldBeUnique` interface, I would expect the job only to be executed 3 times (assuming the uniqueId is set up correctly). Especially because all (unique) jobs will do the same work and thus are being run unnecessarily.

**Comment by taylorotwell** [comment]
I don't find the behavior that unexpected. Or, at least, it seems undefined to me. Telling the job to dispatch after the response doesn't seem compatible with being "unique". You are telling the job to run synchronously within the current process - not on the queue.

**Comment by redelschaap** [comment]
@taylorotwell Well maybe the thing is that it is undefined. But I guess the job is synchronously, so it should run multiple times. On the other hand, what's the value of running the same job multiple times at the end of a process?

Another thought... Should a job that implements the `ShouldQueue` interface be actually queued when using the `afterResponse` methods (instead of being executed)? That would make more sense to me.

If not, would a `dispatchOnceAfterResponse` method be a good addition to the framework?

Queueing the job is just not enough in some situations, because a worker can already executed it before the process that wants to queue it is fully finished.

**Pull request closed without merging**
