### PR TITLE
[9.x] Add `htmlContains` and `textContains` to `Mailable` class

### PR DESCRIPTION
**Pull request by xiCO2k**
This PR adds `htmlContains` and `textContains` to the `Mailable` class.

This way the user can check with the `Mail::assertSent` method:

## Example:

```php
Mail::fake();

Mail::assertSent(NewUserMail::class, fn ($mail) =>
    $mail->hasTo('john@doe.com') &&
    $mail->hasSubject('Login Information') &&
    $mail->htmlContains($password) &&
    $mail->textContains($password)
);
```

I also notice that are methods like the `assertSeeInHtml` but that does not work well with the `Mail::fake()`.

We can also rename it to be called like `->seeInHtml` and `->seeInText` if you think that is better.

Hope this is a cool addition,
Thanks,
Francisco

### CODE REVIEW

**Comment by taylorotwell** [comment]
I kinda prefer people test content of mailables under certain circumstances separate from sending with given arguments:

https://laravel.com/docs/9.x/mail#testing-mailables

Thoughts?

**Comment by xiCO2k** [comment]
I think both ways are good to have.

This is really useful for this feature tests like this example:

```php
it('allows an admin to create a new user', function () {
    Mail::fake();
    signInAsAdmin();

    $this->post(route('users.store'), [
        'name' => $name = 'John Doe',
        'email' => $email = 'john.doe@example.com',
        'password' => $password = 'SomePasswordOverEightChars12345@',
    ])->assertRedirect(route('users.index'));

    $user = User::whereEmail($email)->first();

    expect($user)
        ->name->toEqual($name)
        ->password->not->toBeEmpty();

    Mail::assertSent(NewUserMail::class, fn ($mail) =>
        $mail->hasTo($email) && 
        $mail->hasSubject('Login Information') &&
        $mail->htmlContains($password)
    );
});
```

**Comment by GC-Mark** [comment]
I agree these can be useful to have, but not having these methods kinda forced us in our company to test the _entire_ email HTML under varying circumstances, with help from https://github.com/spatie/phpunit-snapshot-assertions which I think gives a more solid test and proves your email will render correctly as well as having the correct content.

It was initially surprising that you couldn't already easily do what this PR is proposing, so I think it is a 'nice to have' 👍

**Comment by taylorotwell** [comment]
What about when locales are used? Note `render` method.

CleanShot 2022-04-06 at 10 16 02@2x

**Comment by JayBizzle** [comment]
@xiCO2k I don't think draft PRs get reviewed, so if this is ready, you need to remove the `Draft` status 👍

**Comment by xiCO2k** [comment]
Thanks @JayBizzle, I'm aware, is not ready to be reviewed, I will need to add a test and figure one issue that I found.

**Comment by xiCO2k** [comment]
Hey @taylorotwell sorry for the delay

Found one issue that probably invalidates this PR.

If the user uses the `->view('name')` method, the `buildView` does not contain the html, and it only contains the view name `string`, for that is needed to run the:

```php
return Container::getInstance()->make('mailer')->render(
    $this->buildView(), $this->buildViewData()
);
```

And that does not work with the `Mail::fake()`.

I guess that may invalidate this PR, but will leave it here, if you have any ideas.

Thanks.

**Comment by taylorotwell** [comment]
Will close for now.

**Pull request closed without merging**
