### PR TITLE
[5.6] Ability to set mail message ID right hand side using a config value

### PR DESCRIPTION
**Pull request by themsaid**
screen shot 2018-02-15 at 9 26 21 pm

This PR adds the ability to set the right hand side of the Message-id header to a specific domain.

To do this, you need to set the `mail.domain` config value to a valid domain.

### CODE REVIEW

**Comment by sisve** [comment]
No tests?

**Comment by taylorotwell** [comment]
We can probably move this into the singleton registration for the mailer, so we don't load this until it's needed?

**Comment by themsaid** [comment]
@taylorotwell moved it into the singleton and also added a condition to only run it a config value was set.

**Comment by tillkruss** [comment]
@themsaid: This should probably be either mentioned in the docs, or maybe even be added to `config/mail.php`.

**Pull request merged**
