### PR TITLE
[5.7] Allow TransportManager to create log driver with any Psr\Log\LoggerInterface instance

### PR DESCRIPTION
**Pull request by sebdesign**
Addresses #26833

### CODE REVIEW

**Comment by sebdesign** [comment]
@driesvints would it be better to wrap the conditional in an `if` statement and fetch the channel from configuration in there? Because now this call is useless if there is no `LogManager` bound.

**Comment by driesvints** [comment]
@sebdesign yeah I agree.

**Comment by driesvints** [comment]
@sebdesign I also think it's best to explain in your main comment why you're sending this in. It helps Taylor to understand clearly why this change is needed.

**Comment by driesvints** [comment]
Could also use a failing test for the problem at hand.

**Comment by sebdesign** [comment]
@driesvints When I implemented this feature I had a test that asserted the TransportManager would have the default log channel, but Taylor removed it, so I thought it would be useless to add a similar test again.

But I can definitely add a failing test. Should I push it here since this PR has already been merged? I'm sorry for the poor commit message though.

**Comment by driesvints** [comment]
@sebdesign you can send in a new PR for that :)

**Pull request merged**
