### PR TITLE
Bug!!:connections return unexpected.

### PR DESCRIPTION
**Pull request by xujif**
this is a bug when two connection uses same driver :
//connections: A and B (B is default)
```
\DB::connection(‘A’); //will return "A" connection
\DB::connection(‘B’); //will also return "A" connection

### CODE REVIEW

**Comment by xujif** [comment]
#17090

**Comment by GrahamCampbell** [comment]
Are you sure? It looks like the new details are getting passed through. Did you bind these things as a singleton, or not? What version of Laravel are you using?

**Comment by taylorotwell** [comment]
I feel fairly confident this is user error.

**Comment by xujif** [comment]
@GrahamCampbell 
@taylorotwell 
sorry. the problem is in a third party library:   "Did you bind these things as a singleton, or not? " It bind it as  a singleton.

**Pull request closed without merging**
