### PR TITLE
Add ability to hidden Eloquent Model 

### PR DESCRIPTION
**Pull request by milwad-dev**
Sometimes you like to remove some attributes from query.
Actually you add hidden in model but with this method you can remove attributes like this :
```
$users = User::query()->latest()->get();
$users->hidden(['email', 'name']);
```

is very easy :)

### CODE REVIEW

**Comment by ankurk91** [comment]
https://laravel.com/docs/9.x/eloquent-serialization#temporarily-modifying-attribute-visibility

**Comment by milwad-dev** [comment]
@ankurk91 
Sometimes you can write like this:
```
$users = User::query()->with('roles')->get();
```
But write like this:
```
$users = User::query()->get();
$users->load('roles');
```

Sometimes need to hidden.

**Comment by igorgaming** [comment]
Try use this https://laravel.com/docs/9.x/eloquent-collections#method-makeHidden

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
