### PR TITLE
[5.2] Update make:auth generated views

### PR DESCRIPTION
**Pull request by cyrodjohn**
Use Blade ‘first’ method instead of ternary condition to render the error class.

### CODE REVIEW

**Comment by cyrodjohn** [comment]
From a [tweet](https://twitter.com/adamwathan/status/756584833741185024) of Adam Wathan

**Comment by taylorotwell** [comment]
Since 5.3 is so close to release maybe we should do it there? :smile:

**Comment by cyrodjohn** [comment]
@taylorotwell Created a new PR for 5.3 https://github.com/laravel/framework/pull/14475

**Comment by vlakoff** [comment]
Am I the only one to think a simple conditional is much easier to understand?

**Pull request closed without merging**
