### PR TITLE
[5.7] Add repeat() helper

### PR DESCRIPTION
**Pull request by martinbean**
Adds a `repeat()` helper function, a function that simply executes the given callback a number of times. Includes test.

Usage:

```php
repeat(10, function () {
    // Does this 10 times
});
```

### CODE REVIEW

**Comment by jmarcher** [comment]
I do not think we need more global helpers.

And I do not mean to be rude but this seems useless. What is the problem with:
```php
for($i = 0; $i < 10; ++$i){
    // Does this 10 times
}
```

**Comment by martinbean** [comment]
@jmarcher It’s more expressive. Which is what the framework’s about.

**Comment by driesvints** [comment]
If this is gonna be accepted at all I'd suggest to add this to the support helpers instead.

**Comment by martinbean** [comment]
> If this is gonna be accepted at all I'd suggest to add this to the support helpers instead.

@driesvints I did try and work out which namespace to put it in. What are the difference between the “Support” and “Foundation” helpers? What should be where? I went with Foundation because the function isn’t found in one of the Support classes.

**Comment by driesvints** [comment]
>  I went with Foundation because the function isn’t found in one of the Support classes.

What do you mean? This is a new function?

Support = a variety of functions and helpers which can be used on various PHP projects.
Foundation = functions and helpers which are directly related to the framework.

**Comment by martinbean** [comment]
> What do you mean? This is a new function?

@driesvints Yes. It’s proposing adding a new `repeat()` helper function, as it would have been helpful on a couple of Laravel-based projects I’ve worked on now.

> Support = a variety of functions and helpers which can be used on various PHP projects.
Foundation = functions and helpers which are directly related to the framework.

I can move this to the `Support` namespace in that case if preferred?

**Comment by driesvints** [comment]
> I can move this to the Support namespace in that case if preferred?

Yes please.

**Comment by jmarcher** [comment]
> @jmarcher It’s more expressive. Which is what the framework’s about.

Here I have to disagree. Any newcomers in your codebase or even in the framework will need to understand what the repeat() helper does.

I believe any developer knows that this loop will be executed 10 times: `for($i = 0; $i < 10; ++$i){ }`, this because `for`  loops are everywhere and they work.

**Comment by martinbean** [comment]
@driesvints Done! 🙂

---

> Any newcomers in your codebase or even in the framework will need to understand what the repeat() helper does.

@jmarcher Do you really believe that? How many people do you think use Laravel (or any web framework) without first diving into its source code? How many developers have built Laravel projects without knowing exactly what every framework-provider function and method did?

I get you’re not a fan of this suggestion. That’s fine. I mentioned it would have been helpful for me on a couple of projects now, and I imagine it has a generic enough use case to be useful to others, too.

**Comment by jmarcher** [comment]
@martinbean I do, I really believe that.

I mean the helper you introduced, even needs extra error handling where in some cases a `for` loop will still work. 
Cases in which a for loop still works (They are not pretty but still):
```php
for($i = 0; $i < '10'; ++$i){
    // Does this 10 times
}
```
```php
for($i = 0; $i < '10a'; ++$i){
    // Does this 10 times
}
```

**Comment by taylorotwell** [comment]
Hmm, I like the sentiment but do think I'll hold off on it for now, mainly because this is is already possible and quite similar:

```php
collect(range(1, 10))->each(function () {
    var_dump('foo');
});
```

**Comment by martinbean** [comment]
@taylorotwell No problem. Thanks for the feedback.

**Comment by derekmd** [comment]
`Collection::times()` is a similar existing function accessible through the `collect()` global helper:

```php
collect()->times(10, function ($i) {
    return $i * 2;
})
// [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
```

**Pull request closed without merging**
