### PR TITLE
[5.5] Switch to PHPUnit 6

### PR DESCRIPTION
**Pull request by tillkruss**
Switch PHPUnit from 5.7 to 6.0.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Looks like lots of namespace related stuff will have to be fixed.

**Comment by tillkruss** [comment]
Yeah, working on that now.

**Comment by GrahamCampbell** [comment]
All the changes made to the `src` folder should go to Laravel 5.4, so it can be used with the new version of phpunit too.

**Comment by GrahamCampbell** [comment]
Infact, specifically, the changes also need to be updated to work with the old version too.

**Comment by tillkruss** [comment]
How would you do that?

- PHPUnit 5.6 uses `PHPUnit_Framework_Error_Notice`.
- PHPUnit 6.0 uses `PHPUnit\Framework\Error\Notice`.

**Comment by GrahamCampbell** [comment]
Those things don't matter in our own test suite since we're only using phpunit 6, but changes in our src matter. You'll have to add class exists checks.

**Comment by tillkruss** [comment]
Sorry, I still don't get it. You mean make the `extends XXX` conditional with a `class_exists()` check?

Feel free to edit the PR.

**Comment by GrahamCampbell** [comment]
Gah, we should revert the other phpunit changes we made on 5.4 then, and say we only support phpunit 5 on there.

**Comment by taylorotwell** [comment]
Someone will have to coherently summarize the actual issue before I can comment.

**Comment by tillkruss** [comment]
I'm not aware of any issues, but Graham probably know this better than me.

PHPUnit is PHP7+ only and we already switched from `PHPUnit_Framework_TestCase` to `PHPUnit\Framework\TestCase` in Laravel 5.4.

**Comment by crynobone** [comment]
> Gah, we should revert the other phpunit changes we made on 5.4 then, and say we only support phpunit 5 on there.

to late for that, Laravel 5.4 (Testing) technically only works with PHPUnit 5.7

**Comment by gmsantos** [comment]
PHPUnit 6 is not backward compatible with PHPUnit 5.*

What we have in PHPUnit 5.7 is some [foward compatibility layer](https://github.com/sebastianbergmann/phpunit/tree/5.7/src/ForwardCompatibility) to ease the migration to PHPUnit 6 (that was implemented on #17058)

No need to revert nothing in Laravel 5.4, it will continue to work with PHPUnit 5.7. But the upgrade for PHPUnit 6 is only for Laravel 5.5.

**Comment by GrahamCampbell** [comment]
> No need to revert nothing in Laravel 5.4, it will continue to work with PHPUnit 5.7.

On laravel 5.4 we've killed phpunit 4 support for no reason.

**Comment by crynobone** [comment]
> On laravel 5.4 we've killed phpunit 4 support for no reason.

If you don't have any intention to maintain and check that it's properly working with lower PHPUnit (have different metric on Travis CI to test against 4.8) why even bother. Last I test against lowest, anything lower than 4.8 doesn't work with even earlier version of Laravel.

**Comment by GrahamCampbell** [comment]
@crynobone No, I'm referring to people using the framework test classes, NOT what version of phpunit the framework uses to test itself.

**Comment by crynobone** [comment]
> No, I'm referring to people using the framework test classes, NOT what version of phpunit the framework uses to test itself.

*I AM TALKING** about this, I do run Testbench and even I can't really guarantee with Laravel 5.3 would work with other PHPUnit `~4.8` and `~5.4` regardless of what I put in the suggestion.

**Comment by GrahamCampbell** [comment]
> I do maintain Testbench and even I can't really guarantee with Laravel 5.3 Testing Classes would work with other PHPUnit ~4.8 and ~5.4 regardless of what I put in the suggestion.

Lol, well, just because your package doesn't work with phpunit 4.8, it doesn't mean most of laravel's core testing classes don't work with it. Infact, I'm pretty sure they do work fine.

Anyway, that got savage quickly. :trollface:

**Comment by crynobone** [comment]
> Lol, well, just because your package doesn't work with phpunit 4.8.

with other than* PHPUnit `~4.8` and `~5.4`. It does work with 4.8, but nothing less. 

> Anyway, that got savage quickly.

Yes, master @GrahamCampbell, boss always win.

**Comment by taylorotwell** [comment]
So what's the answer here? Just let Laravel 5.4 ride on PHPUnit 5.7 and then bring in PHPUnit 6 with Laravel 5.5?

**Comment by GrahamCampbell** [comment]
> So what's the answer here? Just let Laravel 5.4 ride on PHPUnit 5.7 and then bring in PHPUnit 6 with Laravel 5.5? I'm fine with that if so.

Yeh, sounds fine. 👍

**Comment by tillkruss** [comment]
Thanks for all the input guys!

**Comment by tillkruss** [comment]
Eh, why was this closed? The PR was targeted to 5.5.

**Comment by GrahamCampbell** [comment]
Not sure.

**Pull request merged**
