### PR TITLE
[5.3] Soft limit 120

### PR DESCRIPTION
**Pull request by petar-dambovaliev**
Soft limit implies it won't give an error but it's still recommended to follow it.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I fixed the validator one but think I will leave the other.

**Comment by PetarDambovaliev** [comment]
@taylorotwell PSR-2 states if the arguments are split into multiple lines there should be 1 argument per line.
Your commit has 3 arguments on 1 line.

**Comment by GrahamCampbell** [comment]
We follow our own coding style. This may not be identical to psr-2 in every way, however it's very close.

**Comment by PetarDambovaliev** [comment]
@GrahamCampbell Sorry, i just assumed that was the right way since that what it said on the contribution page at laravel.com .
Since it's not, i wouldn't bother you with psr stuff, cheers.

**Comment by GrahamCampbell** [comment]
We do follow psr-2, just with very tiny differences. This is one of them.

**Pull request closed without merging**
