### PR TITLE
[5.2] New Artisan command: "config:view"

### PR DESCRIPTION
**Pull request by erunion**
This adds a new Artisan command, `config:view`, that lets you inspect the compiled config that's running in your environment. This is helpful to quickly determine settings that are being used without having to switch between your `.env` or `config/<section>.php` files.

It lets you do cool things like:
1. View your entire config

```
$ php artisan config:view
Configuration: app
+----------+----------+-------------------------------------+
| aliases  |          |                                     |
|          | App      | Illuminate\Support\Facades\App      |
|          | Artisan  | Illuminate\Support\Facades\Artisan  |
…
+----------+----------+-------------------------------------+
Configuration: auth
+----------+----------+-----------------+
| driver   | eloquent |                 |
| model    | App\User |                 |
| password |          |                 |
|          | email    | emails.password |
|          | expire   | 60              |
|          | table    | password_resets |
| table    | users    |                 |
+----------+----------+-----------------+
…
Configuration: view
+----------+----------------------------------------+--------------------------------+
| compiled | /home/site/web/storage/framework/views |                                |
| paths    |                                        |                                |
|          | 0                                      | /home/site/web/resources/views |
+----------+----------------------------------------+--------------------------------+
```
1. Your `app` config

```
$ php artisan config:view app
Configuration: app
+----------------------+------------------------------------+---------------------------------------------------------------+
| aliases              |                                    |                                                               |
|                      | App                                | Illuminate\Support\Facades\App                                |
|                      | Artisan                            | Illuminate\Support\Facades\Artisan                            |
|                      | Auth                               | Illuminate\Support\Facades\Auth                               |
|                      | Blade                              | Illuminate\Support\Facades\Blade                              |
…
|                      | Schema                             | Illuminate\Support\Facades\Schema                             |
|                      | Session                            | Illuminate\Support\Facades\Session                            |
|                      | Storage                            | Illuminate\Support\Facades\Storage                            |
|                      | URL                                | Illuminate\Support\Facades\URL                                |
|                      | Validator                          | Illuminate\Support\Facades\Validator                          |
|                      | View                               | Illuminate\Support\Facades\View                               |
| cipher               | rijndael-128                       |                                                               |
| cookie_domain        | localhost                          |                                                               |
| debug                | true                               |                                                               |
| fallback_locale      | en                                 |                                                               |
| key                  | W4ZQxqTlGycvzKYZFyGi8WJa4ki1bhNO   |                                                               |
| locale               | en                                 |                                                               |
| log                  | daily                              |                                                               |
| name                 | My Site!                           |                                                               |
| providers            |                                    |                                                               |
|                      | 0                                  | Illuminate\Foundation\Providers\ArtisanServiceProvider        |
|                      | 1                                  | Illuminate\Auth\AuthServiceProvider                           |
…
|                      | 16                                 | Illuminate\Translation\TranslationServiceProvider             |
|                      | 17                                 | Illuminate\Validation\ValidationServiceProvider               |
|                      | 18                                 | Illuminate\View\ViewServiceProvider                           |
| timezone             | America/New_York                   |                                                               |
| url                  | http://localhost                   |                                                               |
+----------------------+------------------------------------+---------------------------------------------------------------+
```
1. Or a single config like `app.timezone`:

```
$ php artisan config:view app.timezone
America/New_York
```

### CODE REVIEW

**Comment by JosephSilber** [comment]
Instead of having the keys split into multiple columns, wouldn't it make more sense to show the full key path (with its dots) in a single key column?

**Comment by erunion** [comment]
@JosephSilber I think it's a lot easier to read with them split up.

**Comment by JosephSilber** [comment]
> I think it's a lot easier to read with them split up.

Really? You have a single column (the 2nd one) that shows both keys and values interchangeably. That's not very clear.

**Comment by erunion** [comment]
I should've tested this under the latest 5.2 before creating the PR as the new Config\Repository stuff is breaking this.

@JosephSilber I think in this case, a little bit of whitespace with splitting them up into columns really goes a long way. Example of how it'd look like in a single column:

```
$ php artisan config:view app
Configuration: app
+----------------------+------------------------------------+---------------------------+
| app.aliases.App          | Illuminate\Support\Facades\App                             |
| app.aliases.Artisan      | Illuminate\Support\Facades\Artisan                         |
| app.aliases.Auth         | Illuminate\Support\Facades\Auth                            |
| app.aliases.Blade        | Illuminate\Support\Facades\Blade                           |
…
| app.aliases.Schema       | Illuminate\Support\Facades\Schema                          |
| app.aliases.Session      | Illuminate\Support\Facades\Session                         |
| app.aliases.Storage      | Illuminate\Support\Facades\Storage                         |
| app.aliases.URL          | Illuminate\Support\Facades\URL                             |
| app.aliases.Validator    | Illuminate\Support\Facades\Validator                       |
| app.aliases.View         | Illuminate\Support\Facades\View                            |
| app.cipher               | rijndael-128                                               |                                                               |
| app.cookie_domain        | localhost                                                  |                                                               |
| app.debug                | true                                                       |                                                               |
| app.fallback_locale      | en                                                         |                                                               |
| app.key                  | W4ZQxqTlGycvzKYZFyGi8WJa4ki1bhNO                           |                                                               |
| app.locale               | en                                                         |                                                               |
| app.log                  | daily                                                      |                                                               |
| app.name                 | My Site!                                                   |                                                               |
| app.providers.0          | Illuminate\Foundation\Providers\ArtisanServiceProvider     |
| app.providers.1          | Illuminate\Auth\AuthServiceProvider                        |
…
| app.providers.16         | Illuminate\Translation\TranslationServiceProvider          |
| app.providers.17         | Illuminate\Validation\ValidationServiceProvider            |
| app.providers.18         | Illuminate\View\ViewServiceProvider                        |
| app.timezone             | America/New_York                                           |                                                               |
| app.url                  | http://localhost                                           |                                                               |
+----------------------+------------------------------------+---------------------------+
```

That'll just be a complete mountain of text in a terminal, and IMO is really difficult to quickly scan.

I'l re-open this PR when it's working again under 5.2.

**Comment by morloderex** [comment]
Maybe add a option to the command to signal one or 2 columns to be used, since I think the number of columns is personal preference.

**Comment by erunion** [comment]
Reopened to #12648.

**Pull request closed without merging**
