### PR TITLE
[5.1] Use ::class notation

### PR DESCRIPTION
**Pull request by lucasmichot**
Since the introduction of `Gate`, classes are resolved using the `::class` notation.
This PR aims to put some consistency for class resolution. 

_Note_ :
FQN are left unchanged on purpose in `\Illuminate\Foundation\Application::registerCoreContainerAliases()`.

### CODE REVIEW

**Comment by JosephSilber** [comment]
I've been shot down before #8962

**Comment by Sladewill** [comment]
It would be nice to have this done as it provides consistency within the framework as they get updated to this way and also less prone to get unnoticed errors.

**Comment by lucasmichot** [comment]
Indeed @JosephSilber , didn't see yours.
If this PR is closed, this changes can be passed slowly in lighter PRs

**Comment by lucasmichot** [comment]
Nothing broken to fix

**Comment by rkgrep** [comment]
I guess this will be done by Tailor himself as it was done before with arrays syntax.

**Comment by lucasmichot** [comment]
No clue

**Comment by GrahamCampbell** [comment]
This will not be made on 5.2 if not on 5.1 because 5.1 is LTS, so 5.1->5.2 merges still need to happen.

**Pull request closed without merging**
