### PR TITLE
[7.x] Replace Zend to Laminas

### PR DESCRIPTION
**Pull request by kawax**
`laminas-diactoros` will be released soon.
https://github.com/laminas/laminas-diactoros

### CODE REVIEW

**Comment by jmarcher** [comment]
Can you explain why should we do the change?

**Comment by kawax** [comment]
`zend-diactoros` is abandoned
https://packagist.org/packages/zendframework/zend-diactoros

**Comment by mfn** [comment]
That package actually uses also a new namespace, doesn't it? E.g. https://github.com/laminas/laminas-diactoros/blob/master/src/Response.php#L11 shows
image

I wonder though why it works, is there a shim somehow? 🤷‍♀️

**Comment by GrahamCampbell** [comment]
Thanks for the PR. Could you please:

1. Update the "suggest" blocks of the two composer.json files that suggest the zend dependecy to suggest **both** the zend package, and the new one.
2. Can you update the code to check if the new class exists, and use it first, otherwise, use the zend class.
3. Could you send this to 6.x, since this is now not a breaking change, and we need to keep 6.x using maintained code, since it's LTS.

**Comment by GrahamCampbell** [comment]
> I wonder though why it works, is there a shim somehow? 🤷‍♀️

No, just the current stable release of that package has the old namespaces, since it's the same code.

**Comment by mfn** [comment]
Holy 💥 Sounds pretty smart at first… thx.

**Comment by driesvints** [comment]
> No, just the current stable release of that package has the old namespaces, since it's the same code.

It doesn't? I see the new namespace on the latest release: https://github.com/laminas/laminas-diactoros/commit/064f0b20e832bb232d0311f915c7422fef1b1857

**Comment by driesvints** [comment]
@kawax please send this to 6.x

**Comment by GrahamCampbell** [comment]
> It doesn't? I see the new namespace on the latest release: laminas/laminas-diactoros@064f0b2

Oh, I was looking at https://github.com/laminas/laminas-diactoros/compare/2.2.1...master. It looks like they forgot to update the docs, and I assumed that src was updated there too. I guess not. :P

**Pull request closed without merging**
