### PR TITLE
[5.6] Allow notification routing to depend on notification being sent

### PR DESCRIPTION
**Pull request by freekmurze**
This PR makes notification routing a bit more flexible by passing the notification to the `routeNotificationForXXX`

If this would be accepted, this would become possible:

```php
// on a Notifiable

public function routeNotificationForSlack($notification)
{
    if ($notification instanceof MySpecialSnowflakeNotification) {
        return $this->alternative_slack_webhook;
    }
    return $this->slack_webhook;
}
```

Didn't yet figure out how the new behaviour can be tested properly.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Couldn't this be considered breaking because you changed the signature of a public and protected functions that may have some effect?

**Comment by taylorotwell** [comment]
Merged into 5.6. One question I do have is when would the notification ever be `null` in `RoutesNotifications`. I see you made the parameter optional there.

**Comment by freekmurze** [comment]
The notification will never be `null`. It was handy to have that parameter as optional while developing the PR. Forgot to make it required when sending the PR.

**Comment by Modelizer** [comment]
Change log is pointing to 5.5. :/ 
Also title need to be updated to [5.6]

**Comment by aaronhuisinga** [comment]
@freekmurze I was just about to open a PR for the same exact thing. Found your Laracasts thread, and found you'd already done it! Thanks!

**Pull request merged**
