### PR TITLE
[8.x] Fix iterator for createMany

### PR DESCRIPTION
**Pull request by zablondawit**
Fixed iterator provided for `createMany()` function inside Factory class, replaced using EloquentCollection transform function.

```php
    // Before
    public function createMany(iterable $records)
    {
        return new EloquentCollection(
            array_map(function ($record) {
                return $this->state($record)->create();
            }, $records)
        );
    }
    // After
    public function createMany(iterable $records)
    {
        return (new EloquentCollection($records))->transform(function ($record) {
            return $this->state($record)->create();
        });
    }
```

### CODE REVIEW

**Comment by driesvints** [comment]
@theZetrax what does this fixes? Can you provide a test?

**Comment by netpok** [comment]
The createMany method accepts an `iterable` but the `array_map` only supports arrays.

**Comment by theZetrax** [comment]
Ok, I'll check with a test. My logic is [array_map](https://www.php.net/manual/en/function.array-map.php) supports arrays but the `createMany()` function requires arrays as input. @driesvints

**Comment by netpok** [comment]
@theZetrax For easiest test I sugest you copy [this line](https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/tests/Database/DatabaseEloquentFactoryTest.php#L109) and wrap the input array in `collect`. That should do the trick.

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Pull request closed without merging**
