### PR TITLE
[5.6] Store and restore system locale in Queue Job

### PR DESCRIPTION
**Pull request by everestmx**
Store and restore locale in Queue Jobs.

The PR solves the problem when sending e-mails in correct locale with trait Queueable in queue-service.

### CODE REVIEW

**Comment by wielski** [comment]
Good solution

**Comment by sisve** [comment]
This sounds related to https://github.com/laravel/ideas/issues/394.

1. There's no test in this PR. This sounds like something that could use tests.
2. Putting the logic in SerializesModels is weird; shouldn't the locale be persisted even if my job never serializes models?

**Comment by laurencei** [comment]
What happens to jobs that are queued before this PR, and run after? It will set the `locale` to `null`?

Might need to be a 5.7 feature. Or if no locale is set, it reverts to the app locale?

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Pull request closed without merging**
