### PR TITLE
[8.x] Add insensitive mode to contains method

### PR DESCRIPTION
**Pull request by reziamini**
Somebody just needs to check there is a needle in a haystack with insensitive mode and there was no way before that.

### CODE REVIEW

**Comment by rodrigopedra** [comment]
A parameter list change for a public method is a breaking change. As such I guess you should send this PR to the master branch.

In meanwhile, `\Illuminate\Support\Str` is macroable, which means you can dynamically add a custom method to it.

In the docs there is an example on adding a macro to the `\Illuminate\Support\Collection` class:

https://laravel.com/docs/8.x/collections#extending-collections

Which should work similarly to adding a macro to `\Illuminate\Support\Str`.

I also think it might be better to add another method for case insensitive `contains` instead of adding a boolean flag. But that is my personal preference, maybe the maintainers would be fine with the current approach.

**Comment by rezaamini-ir** [comment]
I think It is not a breaking change 
Old tests was passed and the third param is an optional parameter and everything has written before will work without any problem.
And why should we add method which has defined with a bit different.
An optional param i think is a best way..

**Comment by rodrigopedra** [comment]
> I think It is not a breaking change

If a developer is extending that class their app will break due to mismatch method signature.

Regarding the boolean flag, as I said it is my personal preference, due to increased expressiveness, after sometime it might not be clear what `false` changes in this line `$this->assertFalse(Str::contains('taylor', 'Tay', false));` (from the tests in your PR).

I don't consider it to be "best" or "worst" than using a flag, it is just my preference.

**Comment by anubisthejackle** [comment]
I have the same feeling around boolean flags. They make code harder to read. My personal rule of thumb is, if I can't understand a method call in Notepad without having to dig up either documentation or the original class, it isn't clear enough.

**Comment by rezaamini-ir** [comment]
I think it's better to wait for what will maintainers decide.

**Comment by driesvints** [comment]
Feel free to resubmit this without the breaking change or to master, thanks

**Comment by rezaamini-ir** [comment]
@driesvints What do you think about extracting insensitive mode in a new method call `containsInsensitive` ?

**Comment by driesvints** [comment]
@rezaamini-ir just feel free to submit whatever you think is best. I don't review PR's myself (except for code styling and breaking changes). Taylor does the reviewing.

**Pull request closed without merging**
