### PR TITLE
[5.7] Add make:class command to artisan

### PR DESCRIPTION
**Pull request by joecampo**
Sometimes I just need to create a plain class from artisan. Often I just make a model and back out Eloquent. (Apologies if this has been rejected/submitted before - I didn't find anything when searching).

### CODE REVIEW

**Comment by stephan-v** [comment]
I don't see the value in adding something which should be done by your IDE. If you have properly set up your IDE then most IDE's can automatically define your namespace and class name for you.

**Comment by ankurk91** [comment]
https://www.youtube.com/watch?v=dfgtKb-VpRk
See how Adam Wathan is creating new php Class files.

**Comment by deleugpn** [comment]
Doesn't feel that useful to me either.

**Comment by taylorotwell** [comment]
I've thought about this before but opens up more commands like make:interface, make:trait, etc

**Pull request closed without merging**
