### PR TITLE
[5.4] Add Contributor Covenant Code of Conduct

### PR DESCRIPTION
**Pull request by DanielCoulbourne**
While there are no major issues currently outstanding in the Laravel community, having an established Code of Conduct would allow the core team to have concrete guidelines to point to in the event that harassment, or other inappropriate behavior by contributors or commenters becomes an issue.

This code of conduct is a slight modification of the [Contributor Covenant Code of Conduct](http://contributor-covenant.org/) which is used by many prominent open source communities including Ruby on Rails, Elixir, Vue.js, and Yarn.

Currently I have included the suggestion to email Taylor directly for abuse questions, but in the instance that Taylor doesn't want the drama, we could set up an abuse@laravel.com or similar email address to forward to trusted community members.

### CODE REVIEW

**Comment by tillkruss** [comment]
Nice! Should this maybe also go somewhere on the website?

**Comment by lsmith77** [comment]
FYI .. we are considering to adopt the same CoC for Symfony https://github.com/symfony/symfony/pull/24896

Generally I feel it would be a good idea to ensure that the entire eco-system gets a CoC and more importantly gets a board to look over enforcement that isn’t tied to one entity. I am not quite sure how the selection process should be, but Laravel is certainly part of the Symfony eco-system, so I would be happy to collaborate on this topic.

**Comment by GrahamCampbell** [comment]
NB this was changed in https://github.com/laravel/framework/blob/5.5/CODE_OF_CONDUCT.md.

**Comment by lsmith77** [comment]
ah thx for the info .. didn’t think of checking the current state :)

**Pull request merged**
