### PR TITLE
[5.7] Add JSON SELECT support for MariaDB

### PR DESCRIPTION
**Pull request by ybr-nx**
Adds JSON select suuport for MariaDB. I just added new driver called **mariadb** that just extends MySQL and overwrites some query strings.

All features are migrated from my package:
https://github.com/ybr-nx/laravel-mariadb
It is **major** as driver name may conflict in case that package is already in use. It has over 11k installs on packagist.

### CODE REVIEW

**Comment by staudenmeir** [comment]
If #24542 gets merged, we could just replace MySQL's arrow operator with the equivalent `JSON_EXTRACT()`. This would add support for MariaDB without a separate grammar.

**Comment by sisve** [comment]
Can we do a version check and throw a clear error message in case an older version of mariadb is in use that doesn't support whatever needs to be supported?

**Comment by ybr-nx** [comment]
@staudenmeir 
Throwing exception would be nice but I think it's not related to this pull-request as there's no such feature for MySQL (or any other?) also.

@sisve 
Replacing JSON_EXTRACT() would be also one way as it's standard function instead of using MySQL json path alias. It would be bigger change as column name in the query result is different. MySQL and MariaDB are getting more and more incompatible, so different driver is the only way in the future ( that doesn't mean **right now**)

**Comment by staudenmeir** [comment]
Good point about the column name.

https://github.com/laravel/ideas/issues/870 is also relevant here.

**Comment by taylorotwell** [comment]
This may need to be evaluated after merging of #24542

**Comment by SquareBeard** [comment]
Why was this closed ? Any plan to merge this ?

**Comment by ragingdave** [comment]
@ybr-nx Any plans to resubmit with #24542 now having been merged?

**Pull request closed without merging**
