### PR TITLE
Add validateUsername method

### PR DESCRIPTION
**Pull request by hootlex**
Add username validation rule.

The field under validation may have alpha-numeric latin characters, as
well as dashes, underscores, apostrophes and periods.

Username field rules: https://support.google.com/a/answer/33386?hl=en

### CODE REVIEW

**Comment by lukasgeiter** [comment]
That's just Googles (and your) idea of a username. Someone else might not want apostrophes in there etc etc. Meaning this is not really a validation rule that is the same for every application therefore it doesn't make sense to have it in the core.

**Comment by GrahamCampbell** [comment]
Please fix your identation.

**Comment by GrahamCampbell** [comment]
I'm also not sure this belongs in the framework core. As already observed, people have different ideas about what should or should not be allowed.

**Comment by Sladewill** [comment]
Think its a matter of using regex rule for these kinda of things.

**Comment by kyrenator** [comment]
I know its just a regex rule but I think username validation rule is useful to be available by default.

**Comment by Sladewill** [comment]
As @GrahamCampbell stated everyone has a different opinion and stance of what are valid characters in a username, and because of that the nicest way to handle that is to just use the regex.

**Comment by kyrenator** [comment]
@Sladewill I believe most people will be satisfied with alphanum, dashes, underscores and periods.

**Comment by overtrue** [comment]
:-1:

**Pull request closed without merging**
