### PR TITLE
[5.0] withCookies

### PR DESCRIPTION
**Pull request by lucasmichot**
Move `withCookies` to `ResponseTrait` and get rid of the loop in `AddQueuedCookiesToResponse`

### CODE REVIEW

**Comment by TheShiftExchange** [comment]
What is the benefit of this?

Plus, you've completely removed a public method from a class - so this is potentially a breaking change (if someone is calling that in their code somewhere) - so it cant go against the 5.0 branch.

**Comment by lucasmichot** [comment]
Benefits : no loop in AddQueuedCookiesToResponse, plus we can add many cookies with this method instead of calling withCookie several times.
It's the same method but in ResponseTrait, so accessible for Response, and not only from RedirectResponse.

> so this is potentially a breaking change (if someone is calling that in their code somewhere

AFAIK, a class function will always override a trait function

**Comment by TheShiftExchange** [comment]
Ok yeah - your right - the function will still be available - so it shouldnt break existing apps.

**Comment by lucasmichot** [comment]
Anyway @TheShiftExchange , your comment is good: I make sure sur `withCookie` is not using `withCookies` (`withCookies` could be overridden in the class), see https://github.com/laravel/framework/commit/08d8df94f4c1afb89ce98d6b84f841c9c72c8438

**Pull request merged**
