### PR TITLE
[5.1] Fire saved event when updating touched relations

### PR DESCRIPTION
**Pull request by mendicm**
Fire saved event also when updating touched *Many relations.

### CODE REVIEW

**Comment by mendicm** [comment]
Please see #11400 and #11198. This pull request completes the mentioned issue.

**Comment by taylorotwell** [comment]
I can't start firing new events on a LTS release. People may be listening for those events and not expecting them in this situation.

**Comment by mendicm** [comment]
Maybe on 5.2+? I think that the actual functionality isn't coherent.

**Comment by IllyaMoskvin** [comment]
I might be misunderstanding, but this PR might be more of a bug-fix than a feature.

Are these meant to be functionally equivalent?

```
\App\Models\Foo::find('1')->bars()->touch();
\App\Models\Foo::find('1')->bars()->each( function( $bar ) { $bar->touch(); } );
```

If so, the latter works correctly, but the first one does not. This PR would fix that, but maybe there's a better way to do it.

For context, I'm trying to get `$touches` to trigger `saved` to run `searchable` from Scout.

**Pull request closed without merging**
