### PR TITLE
[5.2] Make extending RateLimiter easy

### PR DESCRIPTION
**Pull request by dciancu**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Better to make a rate limiter contract?

**Comment by danieliancu** [comment]
Yes, that would be better. I'll go ahead and do it.

Should I push another commit or close the PR, delete the branch and open a new one?

**Comment by lucasmichot** [comment]
> Better to make a rate limiter contract?

:+1:

**Comment by taylorotwell** [comment]
Graham is correct.

**Pull request closed without merging**
