### PR TITLE
[5.4] Added HasOne Through and BelongsTo Through

### PR DESCRIPTION
**Pull request by pdscopes**
I have created a HasOneThrough and BelongsToThrough Eloquent relationships.

This was originally made in https://github.com/laravel/framework/pull/16599 then improved upon in https://github.com/laravel/framework/pull/16719. Linked to https://github.com/laravel/framework/issues/8721.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please rebase and squash.

**Comment by taylorotwell** [comment]
There is extra stuff on the results that is not on the account history table (supplier_id) when using hasOneThrough:

http://d.pr/i/cqHS

**Comment by taylorotwell** [comment]
Closing pending inactivity.

**Comment by danielboendergaard** [comment]
The extra colum which is included in the result is needed for eager loading since there is no information about the result's relation to the original table in the original result. The same information is included when using the `hasManyThrough` relation so it shouldn't be an issue.

You can see it being included in the result for `hasManyThrough` here: https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Relations/HasManyThrough.php#L396

**Pull request closed without merging**
