### PR TITLE
Update toIlluminateResponse method in Handler.php

### PR DESCRIPTION
**Pull request by itbdw**
replace `$response->headers->all()` with `$response->headers->allPreserveCase()` to use original header capitalizations.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why does it matter?

**Comment by itbdw** [comment]
Just keep custom header originally. That's what `Response` class do in `Symfony`.

And custom header works fun in `Laravel` except in `abort()` method. It just use the lower case for response. Makes me uncomfortable ...

Is there any reason using the lower case on purpose?

**Comment by taylorotwell** [comment]
Header names are not case sensitive.

**Comment by itbdw** [comment]
OK, I knew it. I will change it myself on my code then.

**Pull request closed without merging**
