### PR TITLE
6.x

### PR DESCRIPTION
**Pull request by TBlindaruk**

### CODE REVIEW

**Comment by driesvints** [comment]
Think something went wrong here. You're trying to merged 6.x into 7.x

**Comment by TBlindaruk** [comment]
yep ) It just to get actual 6.x changelog in 7.x br) All okay

**Comment by driesvints** [comment]
@TBlindaruk it's best that you handle 6.x -> 7.x merges locally. Otherwise we run the risk that someone accidentally hits the "delete branch" button when the pr is merged or closed.

**Comment by TBlindaruk** [comment]
ok )

**Comment by GrahamCampbell** [comment]
We should probably make all the permanent branches protected tbh, so they can't be deleted or force pushed to.

**Pull request closed without merging**
