### PR TITLE
[5.0] Adjusting Model::touchOwners to not touch on creation

### LINKED ISSUE #6386: $touches causes fatal error if no ManyToMany relations exist
You can set up a pair of Eloquent models like this:

    class Product extends \Eloquent {
        public function assets() {
            return $this->belongsToMany('Asset');
        }
    }

    class Asset extends \Eloquent {
        protected $touches = [ 'products' ];

        public function products() {
            return $this->belongsToMany('Product');
        }
    }

By doing this, you can call

    Product::find( $validProductId )->assets()->attach( $validAssetId );

the `Asset` will go and update the `updated_at` field on every related `Product` to indicate that its relations have changed.

However, if you make a new `Asset`, or take an `Asset` which has no related `Product`s yet, you'll get a fatal error as the `Model::touchOwners` method only checks if `$this->relation` isn't null:

	public function touchOwners()
	{
		foreach ($this->touches as $relation)
		{
			$this->$relation()->touch();

			if ( ! is_null($this->$relation)) // this is the problem
			{
				$this->$relation->touchOwners();
			}
		}
	}

I have a tentative fix in place locally (for now) by just adding in a check for `&& ! $this->$relation->isEmpty()`, but that may affect other relations, I'm not sure:

	public function touchOwners()
	{
		foreach ($this->touches as $relation)
		{
			$this->$relation()->touch();

			if ( ! is_null($this->$relation) && ! $this->$relation->isEmpty())
			{
				$this->$relation->touchOwners();
			}
		}
	}

### PR DESCRIPTION
**Pull request by impleri**
Fixes #6386 in 5.0. Re-post of #8128 after testing several scenarios.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Leave the ! is_null check in there as well.

**Comment by taylorotwell** [comment]
What if the relation is a single model. Would count() work?

**Comment by impleri** [comment]
I've returned the !is_null check. The test files I'm using is: https://gist.github.com/impleri/838490c5b99cc00250db

**Comment by jarektkaczyk** [comment]
It doesn't solve the problem. There is still no `touchOwners` method on the collection, so it will break for x-m relation.

This one does it well #8360, however @taylorotwell in my opinion `touchOwners` belongs to the `Eloquent\Collection` instead. Why didn't you want it there?

**Pull request closed without merging**
