### PR TITLE
[11.x] Display number of flushed failed jobs

### PR DESCRIPTION
**Pull request by iamgergo**
It would be nice to see how many failed jobs have been flushed when using `queue:flush` command, like when using the `queue:clear` command.

----

This PR:

- Changes the `FailedJobProviderInterface::flush` method's return type.
- Unifies and reworks the `flush` method's logic based on the `FileFailedJobProvider` class.
- Refactors the `DatabaseUuidFailedJobProvider` class, now it extends the original `DatabaseFailedJobProvider`, instead of duplicating a huge chunk of code.
- Changes the output of the `queue:flush` command.

### CODE REVIEW

**Comment by iamgergo** [comment]
I think the failing tests are not related to the codechage.

**Comment by driesvints** [comment]
@iamgergo I fixed the tests on master. Can you rebase?

**Comment by iamgergo** [comment]
Thanks!

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
