### PR TITLE
[11.x] add ability to disable relationships in factories

### PR DESCRIPTION
**Pull request by browner12**
sometimes when `make`ing or `create`ing a model, we don't actually care about the relationships. this new property and method allow us to turn them all off at once. when disabled, any attribute that is assigned a factory will instead return `null`.

imagine an `Organization` and `User` models.  the `organizations` table is:

- id
- name

and the `users` table is:

- id
- name
- age
- organization_id

When we define the `UserFactory` we setup the relationship with a factory:

```php
public function definition(): array
{
    return [
        'name'            => fake()->name(),
        'age'             => rand(1, 100),
        'organization_id' => Organization::factory(),
    ];
}
```

This is great for when we seed and when we run feature tests, because it will automatically create the `Organization`s for us.

However, this is not always desired, often when you're writing Unit tests. Imagine my user model has an `isAdult()` function:

```php
class User
{
    public function isAdult()
    {
        return $this->age >= 18;
    }
}
```

To write a Unit test for this I would `make` a User:

```php
public function test_can_determine_adult()
{
    $user1 = User::factory()->make(['age' => 17]);
    $user2 = User::factory()->make(['age' => 18]);
    $user3 = User::factory()->make(['age' => 19]);

    $this->assertFalse($user1->isAdult());
    $this->assertTrue($user2->isAdult());
    $this->assertTrue($user3->isAdult());
}
```

Unfortunately, this would try storing Organizations in a database, even though we don't care about that. It would also fail if you didn't have `RefreshDatabase` or something similar on your test. 

With this PR, you could easily disable **all** relationships defined in your factories and make this test work:

```php
public function test_can_determine_adult()
{
    $user1 = User::factory()->disableRelationships()->make(['age' => 17]);
    $user2 = User::factory()->disableRelationships()->make(['age' => 18]);
    $user3 = User::factory()->disableRelationships()->make(['age' => 19]);

    $this->assertFalse($user1->isAdult());
    $this->assertTrue($user2->isAdult());
    $this->assertTrue($user3->isAdult());
}
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
Would the state of this property be lost if you called a method like `afterMaking` which creates a new factory instance?

**Comment by browner12** [comment]
that name change seems fine to me.

do you want the property adjusted as well to `withoutRelationships`, and then invert the logic?

I'm not positive, but you're probably right that anything that builds a new object probably would lose this state. the whole factory is a little bit of a mess of static vs object. not sure how you would want to handle this.  I believe I had a PR a long time ago that got rid of the whole static new object paradigm but it was closed.

**Comment by taylorotwell** [comment]
Hey @browner12 - sorry about the immutable stuff... was it really that bad? It looks like you just had to pass the property through the constructor? 😅

**Comment by browner12** [comment]
@taylorotwell it's definitely doable. what I'm struggling with though is I don't see the value of immutability on the factories. maybe I don't fully understand how everyone uses them, so I'd like to gain perspective on that. but if not, I think there'd be value in refactoring the immutability out, and simplifying the factories greatly.

**Comment by christophrumpel** [comment]
@browner12 was this released? I thought so but can't find it anymore.

**Comment by christophrumpel** [comment]
Ah I see it was renamed later to: withoutParents 👍

**Comment by browner12** [comment]
@christophrumpel was it really? lol

**Pull request merged**
