### PR TITLE
[5.5] Removed optimize command

### LINKED ISSUE #20767: [5.5] Optimize command deprecation
Since the `php artisan optimize` command is deprecated (the file is pretty much empty and does nothing), shouldn't it be deleted permanently?

https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Console/OptimizeCommand.php

### PR DESCRIPTION
**Pull request by DCzajkowski**
Removed optimize command, since it was left empty anyway. Closes #20767

### CODE REVIEW

**Comment by sisve** [comment]
It is being deprecated for one release, according to https://github.com/laravel/internals/issues/383

**Comment by DCzajkowski** [comment]
It is not a breaking change (since it won't destroy any codebase) and it isn't really deprecated. It is softly removed currently, which makes no sense whatsoever.

**Comment by taylorotwell** [comment]
We'll remove it in 5.6 and note in the upgrade guide for 5.5. It can break deployment scripts that are calling it if we remove it without warning.

**Comment by DCzajkowski** [comment]
What about making it write to the console?:
```
[Warning] Deprecated ...
```

**Comment by decadence** [comment]
Can somebody explain why this was deprecated and what is alternative?

**Comment by timacdonald** [comment]
@decadence i think I remember Taylor maybe saying on a podcast that due to performance improvements in PHP itself (OPCache and whatnot) the command didn't really have any benifit anymore. Don't quote me on that...

**Comment by decadence** [comment]
@timacdonald thanks

**Comment by josegus** [comment]
so.. should we still using config:cache, route: cache.. ?

**Comment by josegus** [comment]
I've just created a new laravel 8.1 through laravel installer, and "artisan optimize" is in the command list

**Comment by me-shaon** [comment]
@josegus The optimize command was again added later through this PR: https://github.com/laravel/framework/pull/23468

**Pull request closed without merging**
