### PR TITLE
[5.1] Cleanup route function

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This was triggered by https://github.com/laravel/lumen-framework/issues/119.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can you explain the problem and what this fixes.

**Comment by GrahamCampbell** [comment]
It doesn't fix anything code wise. It just makes it way clearer and provides readable phpdoc.

**Comment by yaede7** [comment]
I am seeing that a code fix is necessary. Lumen returns an array as the route and Laravel ruturns an Object (Illuminate\Routing\Route). 

In Lumen - \Laravel\Lumen\Application line 643  - setRouteResolver returns $this->currentRoute

```php
    protected function registerRequestBindings()
    {
        $this->singleton('Illuminate\Http\Request', function () {
            return Request::capture()->setUserResolver(function () {
                return $this->make('auth')->user();
            })->setRouteResolver(function () {
                return $this->currentRoute;
            });
        });
    }
```
$this->currentRoute returns an array and is documented as such in that same class (Laravel\Lumen\Applications) line 115

```php
    /**
     * The current route being dispatched.
     *
     * @var array
     */
    protected $currentRoute;
```
So in Illuminate\Http\Request the function route() returns the array in Lumen. If you pass a parameter on route() then it is trying to access the parameter function on an array which can't be done.

So something like this would work
```php
    /**
     * Get the route handling the request.
     *
     * @param null|string $param
     * @return mixed
     */
    public function route($param = null)
    {
        // is either an array (Lumen) or an instance of \Illuminate\Routing\Route (Laravel)
        $route = call_user_func($this->getRouteResolver());

        if (is_null($route) || is_null($param)) {
            return $route;
        } else if(is_array($route)) {
            return $route[2][$param];
        } else {
            return $route->parameter($param);
        }
    }
```
Now from Illuminate\Http\Request is can call route($param) in both laravel and lumen and get my route parameter back as a string.  Hope that makes sense.

I can submit a pull request if needed.

**Comment by GrahamCampbell** [comment]
So we basically need to add

```
        } elseif (is_array($route)) {
            return $route[2][$param];
```

**Comment by taylorotwell** [comment]
Laravel and Lumen use different routing engines. Nothing was broken in
Laravel so I'm tempted to revert al this

**Comment by yaede7** [comment]
Yeah adding the elseif would be all that needs to be added.

**Comment by taylorotwell** [comment]
WHAT ARE WE FIXING?!

**Comment by GrahamCampbell** [comment]
> Laravel so I'm tempted to revert al this

There's nothing to revert yet. No commit has been pushed to laravel to fix any lumen specific issue.

**Comment by GrahamCampbell** [comment]
The only commit there was a fix for readability and to remove recursion.

**Comment by yaede7** [comment]
Yeah just discussing a possible solution to two different routers sharing one the same request class.  The only functionality that breaks in lumen is in the route() function when a parameter is passed because it wants the laravel router when a param is passed not the lumen. Not a urgent fix or anything. Just something I found.

**Comment by alexw23** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
This commit was NOT meant fix that lumen issue.

**Comment by killermonk** [comment]
Roughly 2 years ago I submitted a PR to add something like that routing ability to Laravel and it was rejected for the reasons listed above. I then subclassed the affected Laravel routing components for Lumen, added the functionality there, and submitted a PR to Lumen to fix the routing issue. That PR was subsequently rejected because it was too big of a change to put in mid-release, or some such. My requests for assistance/guidance as to how to get a "correct" PR in to fix the issue were met with silence.

So, when it really comes down to it, I get the impression that it isn't a high priority to get feature-complete routing functionality in Lumen. Even after 2 years since the original bugs and PRs were filed.

The Lumen issue is a blocker for people's projects. I follow the bug and I get notified every few months when someone makes another comment on it. My project was young enough, and the Lumen bug was a critical blocker, that I ended up moving my Lumen project to another framework rather than run a private fork of Lumen that fixed the actual issue.

**Pull request merged**
