### PR TITLE
[5.1] Deprecated push queues

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Push queues are not all of IronMQ, just the marshal, subscribe stuff and related logic.

**Comment by GrahamCampbell** [comment]
IronMQ only supports push queues though?

**Comment by GrahamCampbell** [comment]
Oh right. My bad. :)

**Comment by franzliedke** [comment]
What's the reason for depreciating them, by the way?

**Comment by taylorotwell** [comment]
I think Push Queues made more sense when queues where quite new to the PHP
scene and it was meant as a introduction to queues without being too
intimidating. Now that people are more accustomed to queues in general and
we have easy ways to set them up (Forge, etc.), I think it makes sense to
remove this special feature.

**Comment by franzliedke** [comment]
Cool, thanks for explaining!

**Comment by bspringston** [comment]
so @taylorotwell, is your recommendation then to use the database queue setting and configure Supervisor (via forge or directly) so that jobs are queued and run asynchronously without going through a 3rd party?

**Comment by taylorotwell** [comment]
That would be my recommendation, yes.

**Pull request merged**
