### PR TITLE
[5.6] Extract common method to AuthenticatesBroadcast trait

### PR DESCRIPTION
**Pull request by mnabialek**

### CODE REVIEW

**Comment by taylorotwell** [comment]
We don't always have to extract common code into traits.

**Comment by mnabialek** [comment]
@taylorotwell  But isn't it violation of DRY? Now there are multiple places where piece of codes are repeated - for example this PR, https://github.com/laravel/framework/pull/22603 and https://github.com/laravel/framework/pull/22607 - shouldn't we target in most cases to have only one version of same code instead of 3 or 4?

**Comment by GrahamCampbell** [comment]
> But isn't it violation of DRY?

Don't treat the recommendations so literally. Everything has pay-offs. :)

**Comment by decadence** [comment]
Copy-and-Paste-Driven Development :)

**Pull request closed without merging**
