### PR TITLE
In the illuminate/support MessageBag helper class add method I added …

### PR DESCRIPTION
**Pull request by thadbryson**
…the sprintf() function. This way when you add a message to the MessageBag you can use sprintf() to format it. It makes it much easier to add messages that look nicer. I just added variadic arguments which are optional in the method call and in the sprintf() function. All tests pass in the tests/Support directory.

### CODE REVIEW

**Comment by thadbryson** [comment]
This is just more convenient than adding another function call. It's cleaner syntax without adding much more complexity.

**Comment by taylorotwell** [comment]
No plans on adding this. @ntzm suggestion was good.

**Comment by thadbryson** [comment]
Thank you.

**Comment by thadbryson** [comment]
I did just notice something. My code passed all the tests but the change to ->add() didn't break the interface in Illuminate\Contracts\Support\MessageBag. I didn't change that file to have the ->add() match. the tests should probably be updated. Just FYI.

**Pull request closed without merging**
