### PR TITLE
[5.1] Add 5.3 exception handler changes

### PR DESCRIPTION
**Pull request by DuckThom**
As suggested in https://github.com/laravel/framework/issues/14009, the changes would be breaking for 5.2 and 5.1. Unless I'm missing something and more changes were made outside of this file, they don't seem to be breaking for me.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This a major breaking change for anyone extending this class. You can actually fix this on your own app though, without upgrading, and without breaking all existing apps.

**Comment by GrahamCampbell** [comment]
Leaving for Taylor to merge if he really wants to. This will break my package for sure though, and my apps.

**Comment by taylorotwell** [comment]
You need to use app() to resolve it within the constructor without it being a breaking change.

**Comment by GrahamCampbell** [comment]
It is still breaking because it no longer uses the logger passed to the constructor.

**Comment by DuckThom** [comment]
Aah, now I see why it would break stuff.

@GrahamCampbell 
I'm wondering, why you're doing `parent::__construct($container->make(LoggerInterface::class))` in your exceptions package as the default handler in `app\Exceptions\Handler.php` uses the default constructor. Where does it get the LoggerInterface from? If it get's instantiated (?) automatically, is `$container->make(LoggerInterface::class)` necessary?

**Comment by taylorotwell** [comment]
Holding off because breaking.

**Pull request closed without merging**
