### PR TITLE
Bugfix: domain routing for subfolder

### PR DESCRIPTION
**Pull request by benubird**
Previously, if laravel was installed to a subfolder, when attempting
to generate a route url for a route associated with a domain, the
subfolder is not included. This corrects that problem.

For more details, see request #3911

### CODE REVIEW

**Comment by kirashi3** [comment]
What about those of us running servers who do not wish to have a separate domain or subdomain just for a Laravel installation?
Call me old fashioned, but some servers and clients I work with *prefer* subdirectories.
How would one setup Laravel to operate out of a subdirectory?

**Comment by OskarD** [comment]
@taylorotwell Why would it hurt to allow it? Like @kirashi3 says, sometimes there is no other choice. My company requires me to work on a subdirectory level because setting up new proxies and domain names is time consuming and cannot be done instantly by the developer, which would give me long delays in deployment. I worked around this by forcing the root url in my AppServiceProvider class, but I feel like Laravel should offer the option out of the box as a modern framework.

It seems like a fairly non-intrusive modification to the code to me. Am I missing something?

(I came here through an [SO question](http://stackoverflow.com/questions/25750604/laravel-artisan-gives-wrong-base-url/29838413?noredirect=1#comment53836473_29838413))

**Comment by thomas83** [comment]
I think this is needed often times.  With companies, they often have a domain installing various different types of applications:

http://www.company.com/app-1-using-laravel/
http://www.company.com/app-2-using-codeigniter/
http://www.company.com/app-2-using-symfony/

etc.

This is a very common real-life scenario actually.  Would be great if this flexibility could be made.  CI and Symfony is able to do this too.  Laravel is great everywhere, but seems to be stuck in this problem of forcing users to install the app in a root.

**Comment by taylorotwell** [comment]
If someone sends a PR to comprehensively fix it I will merge it.

**Comment by JoelGross** [comment]
@taylorotwell I just did a hacky fix on my own site to make this work for coalitiontechnologies.com/jobs. What I did was to update \vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Request.php and added a line after line 1221. Line 1221 + my new code is:

$host = strtolower(preg_replace('/:\d+$/', '', trim($host)));

        $host = $host.'/jobs';

Then I had to comment out the line throwing an exception on this - 
            //throw new \UnexpectedValueException(sprintf('Invalid Host "%s"', $host));

I've never worked on an open source project before, but I'd be happy to try to figure out a more comprehensive fix for you. My concern is that I am pretty new to coding and might screw something else up outside of what I'm trying to do. If you think my hacky fix above is the right idea though I'd be happy to try to figure out a more comprehensive way of implementing it?

**Pull request closed without merging**
