### PR TITLE
[5.1] `lists` method should be consistent

### PR DESCRIPTION
**Pull request by OzanKurt**
When calling `lists` method on a collection it returns a new collection.
It would be great if they both return a `new Collection` and be
consistent.

### CODE REVIEW

**Comment by OzanKurt** [comment]
How did the tests about `lists` method pass?

**Comment by OzanKurt** [comment]
And of course they didn't :D

**Comment by GrahamCampbell** [comment]
We need to be sure this hasn't broken things in places where our tests don't cover too.

**Comment by OzanKurt** [comment]
I edited the current tests anyway. Currently checking the other methods which uses `lists` method if there are any.

**Comment by JosephSilber** [comment]
Why was this only done for the Eloquent Builder? Shouldn't the Query Builder also return a collection?

Furthermore, as I've been nagging @taylorotwell for forever, the query builder should also return its results as a collection!

**Comment by taylorotwell** [comment]
No. Eloquent returns collections. Query bolder returns arrays.

**Pull request merged**
