### PR TITLE
[8.x] Typo fixes

### PR DESCRIPTION
**Pull request by nexxai**
Got bored tonight and went on a typo hunt

### CODE REVIEW

**Comment by driesvints** [comment]
Sweet, thanks!

**Comment by nexxai** [comment]
@driesvints I also wanted to confirm - for the changelog, there were a few, but I figured those were being pulled directly from the PR titles, so I wasn't sure if I should fix them or not.  Can you let me know if those should be fixed or not?  I can see arguments both for and against updating it so I'll leave it up to you and your team to decide.

**Comment by driesvints** [comment]
Nah, it's okay to leave those.

**Comment by nexxai** [comment]
Sounds good.  Thanks for confirming!

**Pull request merged**
