### PR TITLE
[5.2] Avoid unexpected removal of items with null key.

### PR DESCRIPTION
**Pull request by anteriovieira**
This pull request prevent unexpected removal of items with null key and avoid unnecessary call functions.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please rebase to fix StyleCI. ;)

**Comment by anteriovieira** [comment]
:+1:  Done!

**Comment by taylorotwell** [comment]
Need more explanation on how this solves the issue.

**Comment by anteriovieira** [comment]
Thank @taylorotwell , I had committed a mistake.

... If we do not find the item in the array, we should proceed to the next item to be removed.

This can be avoided:
```php
    $parts = [];
    // ...
    unset($array[array_shift($parts)]);
```

**Comment by taylorotwell** [comment]
Is this a breaking change? I still don't even understand what is going on here? :/

**Comment by anteriovieira** [comment]
The tests passed, have any other way to ensure that will not break ? What is happening is that when the item is not found in the array the variable ```$parts``` gets an empty array then it is passed as a parameter to function ```array_shift()``` resulting in null value.  Without this change the method ```unset()``` and ```àrray_shift()``` is called unnecessarily and to top it removes an item with null key.

**Comment by anteriovieira** [comment]
@taylorotwell  you use ```$parts = []``` to exit the while block? because after it is passed to function ```array_shift()``` returns null.

**Comment by taylorotwell** [comment]
Can you give me sample code to paste into current Laravel to re-create problem?

**Comment by anteriovieira** [comment]
This is an example:

```php
    
    $array = ['products' => ['desk' => ['price' => 50], null => 'something']];
    Arr::forget($array, ['products.amount.all', 'products.desk.price']);

    // ['products' => ['desk' => []]]

```
The item with null key has been removed. But I would like you to give special attention to the function call ```unset()``` and ```àrray_shift()``` after receiving ```$parts = []```.

**Comment by anteriovieira** [comment]
@GrahamCampbell what is your opinion about it?

**Comment by taylorotwell** [comment]
I dunno, I'm a little nervous about this breaking certain situations.

**Comment by anteriovieira** [comment]
Yeah, sure, I understand you. I would like to take and suggest the following:

```php
//...
$keys = (array) $keys;

if (count($keys) >  0) {
	$original = &$array;
	
	foreach ($keys as $key) {
		//...
	}
}
//...
```
Thus we maintain the void return. or:
```php
    /**
     * ...
     * @return false|void
     */
    public static function forget(&$array, $keys)
    {
    //...
```
This second change does not make sense to me.

**Comment by GrahamCampbell** [comment]
> false|void

No such thing as that. `void` means the return value is garbage.

**Comment by anteriovieira** [comment]
I understand, then we keep like this?

**Comment by leidison** [comment]
Interesting the first suggestion of Mr. @anteriovieira. Place the code within the ```if (count ($ keys)> 0)``` instead of using ```return;``` it is more consistent because you do not need a return to the function.

**Pull request merged**
