### PR TITLE
[5.1] Mass-update formatting to PSR2 (cosmetic only)

### PR DESCRIPTION
**Pull request by NFarrington**
Updates all code to be PSR-2 compliant, per the new guidelines for Laravel 5.1. Changes are purely cosmetic.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Some of these changes arn't PSR-2, AND you've made some breaking changes to our methods by removing optional parameters. Not sure why you did that?

**Comment by NFarrington** [comment]
@GrahamCampbell There was a single instance in src/Illuminate/Queue/IronQueue.php where the optional parameter was followed by a required parameter - you can't have an optional parameter before a required parameter, because by definition to provide the required parameter, you also need to provide the optional parameter.

Are you able to provide (just a few, not all) examples regarding which of these changes you believe not to be PSR-2?

**Comment by GrahamCampbell** [comment]
Changing the array stuff isn't PSR-2. Please don't send another PR. We deal with CS on our own internally.

**Comment by NFarrington** [comment]
> array stuff

There's a lot of 'array stuff' in PHP code - do you have a specific file/line? I'd like to be able to justify any changes you feel are unwarranted. 

> We deal with CS on our own internally.

Given the amount of code that is not PSR-2 compliant (as demonstrated by the PR), this really doesn't seem to be the case. There's even indentation with 3 spaces instead of 4, that was resolved in this PR.

I'm not trying to cause a fuss, or saying this PR should be accepted, but it does demonstrate that a significant amount of code is not PSR-2 compliant - perhaps this might be better listed as an issue, for you to deal with internally at a later date?

**Comment by GrahamCampbell** [comment]
Could you send the indentation fixes please?

**Comment by GrahamCampbell** [comment]
> perhaps this might be better listed as an issue, for you to deal with internally at a later date?

It's fine - I'm keeping track of this in my head.

**Comment by GrahamCampbell** [comment]
:)

**Comment by NFarrington** [comment]
Thanks for the response/acknowledgement :)

Indentation fixes submitted as PR https://github.com/laravel/framework/pull/9671

**Pull request closed without merging**
