### PR TITLE
[5.5] Remove unnecessary else

### PR DESCRIPTION
**Pull request by mnabialek**

### CODE REVIEW

**Review by tillkruss — COMMENTED** [review]
You could collapse the if statement as well, no?

**Comment by mnabialek** [comment]
Yes, it could be something like this:

```
return isset($matches[1]) ? $matches[1] : ($payload['job'] ?? null);
```

but I think it would make code harder to read

**Comment by tillkruss** [comment]
The 2nd example of course 🙂

**Comment by GrahamCampbell** [comment]
I think it's most readable in this PR's current state. Multiple ternaries are not as readable I think. :)

**Comment by joshmanders** [comment]
I'd have to side with Graham. Ternaries shouldn't be multiples. Gets confusing.

**Comment by deleugpn** [comment]
I would side with @tillkruss on this one. Pure ternary is, indeed, a little over-the-edge

Complicated
```
return isset($matches[1]) ? $matches[1] : (isset($payload['job'])  ? $payload['job']: null);
```

Simple
```
return $matches[1] ?? $payload['job'] ?? null;
```

with `??` you know that it's either the value checked itself or the next.

**Pull request merged**
