### PR TITLE
[5.9] Remove AppNameCommand

### PR DESCRIPTION
**Pull request by driesvints**
The AppNameCommand isn't really serving much purpose after initial usage. Besides that you generally don't want to change your App namespace. Having a customized namespace is more something you'd do for a package and not an application. Removing this will encourage more people to use the default App namespace.

Make commands can still be used as they are now because they guess the namespace of the app themselves.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Agree. Can be released as a package and maintained by the community if anyone needs this feature.

**Comment by ralphschindler** [comment]
@driesvints: Now that this is leaving the default artisan, what do you think about making the `make:command XXXCommand` (for instance) prefix the actual cli commands with `app:` so that it is initially expected to be executed like `artisan app:xxx`?

This would effectively, by default, group all the custom/app-specific commands together in the app "namespace" for the artisan cli.

**Comment by driesvints** [comment]
@ralphschindler can you explain a bit more? I have no idea what you mean.

**Comment by isluewell** [comment]
**I created a gist, in case anyone else needs it.**

https://gist.github.com/isluewell/b824c0aef32f5007170fcd0d8498b657

First we create the command with

``` php
php artisan make:command AppName
```

Then we replace the content created in the file `app/Console/Commands/AppName.php` with the content of the gist.

and then use it in the usual way, changing `Luewell` for the name of your application.

``` php
php artisan app:name Luewell
```

**Comment by andrey-helldar** [comment]
If anyone needs this command and removed `str_` and `arr_` helpers, you can install this package: https://github.com/andrey-helldar/laravel-helpers

**Comment by andrey-helldar** [comment]
Changing the namespace in the application is like combing your hair in the morning. When you got up disheveled and picked up a comb ... ah, well, yes ...

**Comment by crynobone** [comment]
Screenshot_20190913-162631

**Comment by andrey-helldar** [comment]
Hm...

**Comment by Jossnaz** [comment]
@driesvints why do you generally not want to change the namespace of your app?

**Comment by browner12** [comment]
there is no value to doing it, and it causes other complications that aren't worth the headache.

**Comment by Jossnaz** [comment]
@browner12 complications like what? been a while I used it, but I remember one had problems with generator packages that assumed that the namespace is App... is it that for example? do you have different examples? 

there is value doing it actually... namely, I feel at home. I dont feel comfortable not living in my namespace. Yes yes, "whatever" right? well, I see your point, and I'm not gonna change it now as probably indeed it has headache. But I think it's important to make a strong case, not just "there is no point" because people already started side stepping this and hacking it out themselves. Just because nobody explained why. You didn't either.

It's generally a bad idea not saying "why". Like "dont inflate your life vests in the airplane" well, it is well known that people do that when the plane is about to crash, they inflate them in the airplane. If you would tell people that they won't be able to escape the airplane as soon as water enters and they have the life vests inflated, causing them to be trapped at the roof unable to escape and drown, they wouldnt inflate them trust me.

**Comment by timothykimemia** [comment]
@driesvints @taylorotwell its wasnt really about namespace but clearing all configuration from one-line command, has anyone created a package ... please share
Capture 1

**Comment by Jossnaz** [comment]
@timothykimemia no, clearing cache must be something difficult in laravel! there cannot be just one command to do it, you have to google and then execute like 8 different commands in order.... 
I think in your screenshot the queue worker wasnt restarted, so that seems incomplete as well.

**Comment by timothykimemia** [comment]
I still retain version 5.8 because of this command when developing enterprise systems using laravel @Jossnaz (try it), imagine every new feature or module while coding -> cache:clear && route:clear && config:clear when all I have to do is `php artisan app:name Commerce` ... again, if anyone has a package that can clear laravel cached files like v.5.8, please share

**Comment by timothykimemia** [comment]
@Jossnaz my bad, went through the code snippet: all its doing is call `optimize:clear`
:/5.8/src/Illuminate/Foundation/Console/AppNameCommand.php

**Comment by Jossnaz** [comment]
@timothykimemia if you on linux you can add this alias to your ~/.bashrc file at the bottom:
```
alias artcache='composer dump-autoload && php artisan optimize && php artisan clear-compiled && php artisan cache:clear && php artisan view:clear && php artisan route:cache ; php artisan queue:restart'
```
notice: this does not clear the cache of the config file, you'd have to manually add it as well. Notice as well that route:cache throws an error to me because of closures, so the following `;` makes it so that the next command executes even if there was an error

is inspired by https://stackoverflow.com/questions/47435222/clear-laravel-queue-cache-without-restarting/55857091#55857091

**Comment by markdwhite** [comment]
Just to note that changing the app namespace causes problems with the new approach to Model Factories due to a hard-coded expectation in Factory::resolveFactoryName() that app namespaces are always 'App':

`$resolver = static::$factoryNameResolver ?: function (string $modelName) {
            $modelName = Str::startsWith($modelName, 'App\\Models\\')
                ? Str::after($modelName, 'App\\Models\\')
                : Str::after($modelName, 'App\\');

            return static::$namespace.$modelName.'Factory';
        };
`

This is breaking change affecting those that have changed namespace in the past, and it is not warned about on the upgrade docs. I'm creating an issue relating to that now, but I suspect the response will be to change the app namespace back to 'App'.

**Pull request merged**
