### PR TITLE
[Routing] Fix phpdoc return

### PR DESCRIPTION
**Pull request by pespantelis**
An example..

``` php
Route::bind('user', function($value)
{
    return User::where('name', $value)->first();
});

Route::bind('post', function($value, Router $route)
{
    // now the $route->parameter('user') should return an instance of the User's class
    return $route->parameter('user')->posts()->where('slug', $value)->first();
});

Route::get('{user}/{post}', function($user, $post)
{
    ...
});
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Should be `string|object` then. `mixed` should be avoided at all costs. It's totally useless.

**Comment by pespantelis** [comment]
@GrahamCampbell Should we change this to `string|object` or leave it as is?

**Comment by GrahamCampbell** [comment]
I'll sort it.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/pull/8183

**Comment by pespantelis** [comment]
:+1:

**Pull request closed without merging**
