### PR TITLE
[11.x] Prompts user to run migrations on `install:api` Artisan command

### PR DESCRIPTION
**Pull request by nunomaduro**
This pull request prompts user to run migrations on `install:api` Artisan command:

Screenshot 2024-02-29 at 14 59 33

### CODE REVIEW

**Comment by hafezdivandari** [comment]
Would you please consider adding `--passport` option to install Laravel Passport?

**Comment by driesvints** [comment]
@hafezdivandari I don't think we should do that at this point. Otherwise we'll be adding flags for every other package as well.

**Comment by hafezdivandari** [comment]
But we have 2 first-party packages for API auth?
Having an option to choose between Sanctum or Passport when running `install:api` improves DX.

**Comment by driesvints** [comment]
@hafezdivandari the packages are two very different things. One does PAT and the other OAuth 2. We don't recommend using the PAT from passport any longer.

**Comment by hafezdivandari** [comment]
@driesvints I know the difference, but both of them have api guard, and we are talking about `install:api` command.

**Pull request merged**
