### PR TITLE
[5.2] URL Generator - Some minor performance tweaks

### PR DESCRIPTION
**Pull request by KennedyTedesco**
Specially the change of `preg_replace()` to `str_replace()`. Even with the changes the readability wasn't affected, I guess.

### CODE REVIEW

**Comment by ArjanSchouten** [comment]
:-1: This affects the readability of the code.

You change the behavior too!

1. ```Str::contains``` has some extra checking.
2. ```preg_replace()``` is set with a limit. You forgot to set the limit on ```str_replace```!

**Comment by KennedyTedesco** [comment]
1 - Don't need of extra checking for this behaviour in particular.
2 - A root URL is something like `http://domain.com/` (That means, `schema` + `baseUrl`). The replace happens just once anyway.

**Comment by KennedyTedesco** [comment]
Yesterday I made a benchmarking. Has gain (60% ~ 80%). But it's no big deal to be honest. As i've said, it's just a micro tweak.

That's it. Just a proposal. I'm ok if we decide to close this. Optimisations on Routing brings more practise results.

**Comment by ArjanSchouten** [comment]
Probably only this rule can be changed:
```php
return str_replace($start, $scheme, $root, 1);
```

**Comment by KennedyTedesco** [comment]
In reality that fourth argument of `str_replace()` doesn't limit. It just receive a variable by reference to set the number of replacements performed.

**Comment by ArjanSchouten** [comment]
You're right :smile:

**Pull request closed without merging**
