### PR TITLE
[5.7] fixed doc block for handleQueryException;

### PR DESCRIPTION
**Pull request by TBlindaruk**
- changed first argument from `\Exception` to `\Illuminate\Database\QueryException` since we called `tryAgainIfCausedByLostConnection` with `\Illuminate\Database\QueryException`

### CODE REVIEW

**Comment by sisve** [comment]
This is a breaking change; anyone can call handleQueryException to handle any type of exception that have occurred during querying, or perhaps wrap the exception in another exception of another type. There are no guarantees that all derived implementations always work with QueryException here.

**Comment by TBlindaruk** [comment]
@sisve , in case, if someone calls this method with other exception then they got a fatal error.

Because `handleQueryException` is called `tryAgainIfCausedByLostConnection`,

tryAgainIfCausedByLostConnection is :


```PHP
    /**
     * Handle a query exception that occurred during query execution.
     *
     * @param  \Illuminate\Database\QueryException  $e
     * @param  string    $query
     * @param  array     $bindings
     * @param  \Closure  $callback
     * @return mixed
     *
     * @throws \Illuminate\Database\QueryException
     */
    protected function tryAgainIfCausedByLostConnection(QueryException $e, $query, $bindings, Closure $callback)
    {
        if ($this->causedByLostConnection($e->getPrevious())) {
            $this->reconnect();

            return $this->runQueryCallback($query, $bindings, $callback);
        }

        throw $e;
    }
```

**Comment by sisve** [comment]
Not if I have overridden the handleQueryException method to accept other exceptions, and handle them accordingly.

**Comment by TBlindaruk** [comment]
@sisve , than you will override the phpDoc also

**Comment by sisve** [comment]
1. Do you accept that phpdocs are part of the method signature?
2. If it says that it `@return string`, and you change it to `@return int`, do you agree that you've changed the method signature?
3. And do you agree that changing method signatures are breaking changes?

Do you consider this a acceptable special case just because it calls tryAgainIfCausedByLostConnection?

**Comment by sisve** [comment]
I understand what you're getting at, but it highlights another problem. The implementation (content of the method) does not match the contract (the method signature). The method signature states that we allow any types of exceptions, but this is obviously a lie. This is something that would have been seen in tests if we had tests that invoked the method with the parameters it claims to accept and support.

I am agreeing with you on these changes; the method's name indicates that it should only accept a QueryException. I would love to see more php7 typehints instead of phpdocs, but that is besides the point.

I am only saying that these things, changing a method signature, is a breaking change. It makes sense to do these changes in the 5.7 release, since it is highly improbable (but not impossible) that someone has override with a different exception support while still conforming to the contract. But everyone that has their own implementation of the code need to update the contract/phpdocs accordingly, and in worst-case, stop calling the method with non-QueryException exceptions.

**Comment by taylorotwell** [comment]
Sorry, I don't really see a point in changing this one.

**Pull request closed without merging**
