### PR TITLE
[4.2] Adds Form::tel()

### PR DESCRIPTION
**Pull request by GiamPy5**
Adds support for telephone input field which is a nice touch for users browsing Laravel websites on their phone!

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The form component is not maintained anymore.

**Comment by GiampaoloFalqui** [comment]
Does that mean no more ```Form::open()``` or ```Form::[...]``` in L5?

**Comment by GrahamCampbell** [comment]
No, you can still have them if you require `"illuminate/html": "~5.0"`. They're just not maintained anymore.

**Comment by RomainLanz** [comment]
When L5 will be released can we maintain this repository https://github.com/illuminate/html or it will still be READ ONLY?

**Comment by GrahamCampbell** [comment]
@RomainLanz. No it will not be maintained. High priority fixes may be merged, and the repo will continue receiving tags, but it will not be maintained.

**Comment by RomainLanz** [comment]
I can't understand why you don't want to maintain this package. It's very usefull and necessary.

You just need to authorize PR, the community will maintain the package for you. If you don't do that, I think that another guy will fork the repo and maintain the pacakge, that just ridiculous IMO.

**Comment by GrahamCampbell** [comment]
The idea is that people just find a new package. It's fine if someone from the community wishes to maintain a package. The decision was taken because the html package was taking way more time that it was worth to maintain.

**Pull request closed without merging**
