### PR TITLE
[5.2] Make Collection unique method to use strict check when comparing keys

### PR DESCRIPTION
**Pull request by mnabialek**
This was raised in https://github.com/laravel/framework/issues/14449 - in fact I think it should use strict checking in this case by default

### CODE REVIEW

**Comment by fernandobandeira** [comment]
This is probably a breakable change tbh the best solution would probably be to pass a parameter to the function to decide if the in_array will use strict mode. Or merge this on another branch...

**Comment by mnabialek** [comment]
After reconsideration I've added `$strict` parameter with default to `false` to not to break existing code, however I would consider to change this parameter to `true` by default for example in 5.3 branch

**Comment by fernandobandeira** [comment]
IMO we should always avoid to change the default behavior of functions on existing releases, i deleted my previous comment on this PR because i thought that probably there's no one expecting this to not be strict mode however better safe than sorry.

Question:
Should this go to 5.1 instead since it's a LTS release?

**Comment by taylorotwell** [comment]
Please send PR for `uniqueStrict` method to 5.3 branch.

**Pull request closed without merging**
