### PR TITLE
[5.7] Enable passing options to custom presets

### PR DESCRIPTION
**Pull request by connectkushal**
The ability to create our own presets is very convenient. But currently it is not possible to have customization in the user made preset commands by passing options to it. For example if i am making a preset for tachyon css and want the dev to choose a js framework from either vue or react along with the choice of creating auth pages or not, its not possible with `php artisan preset tachyon` alone.

This pr enables passing of multiple values to the custom presets through `--option=`, which can be used as ...
`php artisan preset tachyon --option=vue --option=cdn --option=version:4.0` or 
`php artisan preset tachyon --option=react --option=auth`
.
This opens many possibilities for creating presets which will simplify and make frontend dev much faster.

This is a non breaking change and works as intended without affecting the default presets.

---
The array of values passed can be accessed in the following way.

```
PresetCommand::macro('tachyon', function($command){
    $options =  $command->option('option'), 
    ....
    ....
});
```

---

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why not just something like `option`?

**Comment by connectkushal** [comment]
Honestly, wasn't sure of using `--pass` either but all look the same to me. Had picked it up randomly after considering `--extra` (from ansible) and also `--option` initially. Im cool with anything.

**Comment by connectkushal** [comment]
If you want me to change the name, i'll also update the example in the description above.

**Comment by taylorotwell** [comment]
I would prefer option over pass.

**Comment by connectkushal** [comment]
@taylorotwell done :)

**Pull request merged**
