### PR TITLE
[11.x] Fix inconsistent database parsing on PostgreSQL

### PR DESCRIPTION
**Pull request by hafezdivandari**
As explained on #49020, `Schema::hasTable()` uses `Schema::getTables()` on all database drivers except PostgreSQL, because `Schema::hasTable()` on PostgreSQL is the only function on the schema/grammar/builder that accepts 3-parts references like `Schema::hasTable('database.schema.table')`. This is an inconsistent behavior, as other functions and non of the other database drivers support this syntax.

This PR fixes this by throwing an exception if 3-parts reference is mistakenly passed to `Schema::hasTable()` and also changes `Schema::hasTables()` on PostgreSQL to use `Schema::getTables()` just like other databases.

Note: Passing 2-parts reference or just table name to these functions on PostgreSQL works as expected as before:

```php
Schema::hasTable('schema.table');
Schema::getColumns('schema.table');
Schema::getIndexes('schema.table');
Schema::getForeignKeys('schema.table');
Schema::hasTable('table'); // uses default schema
Schema::getColumns('table'); // uses default schema
Schema::getIndexes('table'); // uses default schema
Schema::getForeignKeys('table'); // uses default schema
```

#### Likelihood Of Impact: Very Low

The `Schema::hasTable()` on PostgreSQL database doesn't accept declaring database name by passing a 3-parts reference anymore and will throw an exception. Therefore, if you were using 3-parts reference on these methods you may use `connection()` to declare the database instead:

```diff
- Schema::hasTable('database.schema.table');
+ Schema::connection('database')->hasTable('schema.table');
```

### CODE REVIEW

**Comment by driesvints** [comment]
@hafezdivandari are you still working on this?

**Comment by hafezdivandari** [comment]
@driesvints yes, I'm wating for #49264 to be merged:

https://github.com/laravel/framework/pull/49264/files#diff-9fc77e1263d98fe08a38be1f5d172d2497320915fa8b8148e1823052eb33f403R231

**Comment by hafezdivandari** [comment]
@driesvints would you please merge '10.x' into master?

**Comment by hafezdivandari** [comment]
@driesvints would you please merge '10.x' into master? cc @taylorotwell

**Comment by hafezdivandari** [comment]
@driesvints would you please merge '10.x' into master? cc @crynobone

**Comment by driesvints** [comment]
@hafezdivandari will do as soon as all of the fixes PRs that are open are merged.

**Comment by driesvints** [comment]
@hafezdivandari done now

**Pull request merged**
