### PR TITLE
[11.x] fix: allows injection using multiple interfaces with the same concrete implementation

### LINKED ISSUE #53110: Multiple interfaces injection fails if they have the same concrete class
### Laravel Version

11.26.0

### PHP Version

8.3.12

### Database Driver & Version

_No response_

### Description
If two independent interfaces are implemented by the same concrete class and used in a method binding only the first interface gets resolved.

### Probable Cause
Following the issue in debug, it appears to be related to the interaction and logic behind `alreadyInParameters` and `resolveMethodDependencies`. 

The method  `alreadyInParameters` prevents the multiple injection of objects with the same class but compares the class name against the `instanceof` of the previous parameters **after they have been resolved** instead of the **requested** type of the parameters.

### Steps To Reproduce

given the following classes:

```php
interface IInterfaceA
{
    public function doSomethingA();
}
```

```php
interface IInterfaceB
{
    public function doSomethingB();
}
```

```php
class ConcreteClass implements IInterfaceA, IInterfaceB
{
    public function doSomethingA()
    {
        // Implementation for doSomethingA
    }

    public function doSomethingB()
    {
        // Implementation for doSomethingB
    }
}
```

and registered with:
```php
$this->app->singleton(\App\Services\ConcreteClass::class, function (Application $app) {
            return new ConcreteClass();
        });
$this->app->bind(\App\Interfaces\IInterfaceA::class,\App\Services\ConcreteClass::class);
$this->app->bind(\App\Interfaces\IInterfaceB::class,\App\Services\ConcreteClass::class);
````

the route pointing to the following controller raise an `ArgumentCountError`

```php
class SampleController extends Controller
{
	public function executeRequest(Request $request,IInterfaceA interfaceA, IInterfaceB interfaceB)
	{
	}
}
````

### PR DESCRIPTION
**Pull request by jamiethorpe**
Fixes [issue 53110](https://github.com/laravel/framework/issues/53110)

This allows multiple interfaces to be injected when they use the same concrete implementation. This change also prevents injecting the same interface twice, but I'm not sure if that's necessary.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Seems like we would want a test for this new behavior I think.

**Comment by jamiethorpe** [comment]
Should be good now. I wasn't 100% sure if the test fit into any of the existing test files, so I added a new one.

**Comment by taylorotwell** [comment]
Sorry for delay - thanks. 👍

**Comment by jasonvarga** [comment]
This caused an issue with route model binding. See: https://github.com/laravel/framework/issues/53952

@jamiethorpe since you authored this PR, maybe you could give some insight? It would be appreciated! 🙏

**Comment by taylorotwell** [comment]
Reverting for now.

**Comment by jasonvarga** [comment]
Thank you

**Comment by jamiethorpe** [comment]
@jasonvarga This looks like an oversight on my part. I probably won't get to it until after the holidays, but I'll take another stab at it and and tests to make sure the refactor doesn't break the same functionality. Thanks for finding that 😬

**Pull request merged**
