### PR TITLE
Added @section('scripts') and @section('styles') for extend

### PR DESCRIPTION
**Pull request by tutkun**
Added @section('scripts') and @section('styles') for extend

### CODE REVIEW

**Comment by fernandobandeira** [comment]
If we're adding this I would personally prefer using ``` @stack ``` and ``` @push ``` as it seems more apropriate for this...

**Comment by calebporzio** [comment]
Either way - I thought this exact thing today - hope this gets pulled in.

**Comment by taylorotwell** [comment]
You can add this to your own application as needed.

**Comment by tutkun** [comment]
Yes, i did it. But, I was think can be added as global. Thanks.

**Pull request closed without merging**
