### PR TITLE
[5.4] Add a make:composer command to generate view composers

### PR DESCRIPTION
**Pull request by vpratfr**
This is a PR to add a generator for view composers [as discussed in that proposal](https://github.com/laravel/internals/issues/430).

As stub, I took the sample code that was in the documentation and the default namespace as described there too. Kindly note that this namespace will be configurable with my other PR #18203.

The command will also accept a `--provider` switch which will trigger creation of the service provider as described in the documentation. 

I had to provide an extra parameter to the `make:provider` command in order to be able to use a different stub than the default one for providers.

This should complement nicely all the current generators for this kind of concept.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I don't particularly want to add a generator for this.

**Comment by vpratfr** [comment]
Just curious, why would you want a generator for middleware, event or command? ViewComposers have just about the same complexity and just as useful. You got me slighly puzzled here.

**Comment by joshmanders** [comment]
Honestly I think the artisan command help is getting out of control with all the stuff in it. A lot of these generators should be pulled out into a independent package that can be required in, like `tinker` is.

**Comment by vpratfr** [comment]
I would tend to agree with you Josh. That could be an external official dev-only dependency. 

Either way I fail to understand why there would not be a make command for each of the framework's concepts/entities.

Depending on the project, one could be well having many more composers than commands or events for instance.

**Pull request closed without merging**
