### PR TITLE
[5.7] Normalize view paths within FileViewFinder

### PR DESCRIPTION
**Pull request by fkulakov**
Normalize view paths within FileViewFinder

Please see https://github.com/laravel/framework/issues/26357 for more details

### CODE REVIEW

**Comment by sisve** [comment]
Could the normalizePath strip away the application directory? I will compile the views on my Jenkins machine (where they are somewhere in /var/lib/jenkins/workspace/master-HASH/) but deploy them to other absolute paths in production.

This is slightly relevant: https://github.com/laravel/ideas/issues/488

**Comment by fkulakov** [comment]
If I understand you correctly, it not change current application behavior. View files has compilied by another logic and those changes try to make it compatible.

Those changes just remove unnecessary '../' and similar segments from the view paths when you try to render it.

**Comment by taylorotwell** [comment]
Tests fail on my machine.

**Comment by taylorotwell** [comment]
5) Illuminate\Tests\View\ViewFileViewFinderTest::testNormalizedPaths with data set #4 ('/var/log/../../var', '/var')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'/var'
+'/private/var'

/Users/taylor/Documents/Code/Repositories/laravel-framework/tests/View/ViewFileViewFinderTest.php:168

**Comment by fkulakov** [comment]
@taylorotwell ok, it exactly my mistake. But it is actually realpath on your machine, yes? I am not mind about mac, sorry. I think I can leave only check for incorrect path: only this  is important for backward compatibility. realpath() function is not need a additional tests. Its ok?

**Pull request closed without merging**
