### PR TITLE
[9.x] Revert "[9.x] Update psr/log version" and fix properly

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Reverts laravel/framework#38852. Supports psr log v1, v2 and v3.

### CODE REVIEW

**Comment by X-Coder264** [comment]
What does removing the `string|Stringable` types fix?

**Comment by GrahamCampbell** [comment]
Lots of libs still only support v1 and breaking v1 support is silly. When we can easily support everything, we should.

**Comment by GrahamCampbell** [comment]
We can also clearly see most people still use v1:

image

**Comment by GrahamCampbell** [comment]
image

**Comment by X-Coder264** [comment]
Fair enough, even though I'm more on the "let's push the community forward" line of thinking (by making Laravel 9 support psr log v2 and v3 instead of all three major versions). For v1 there's still Laravel <=8.

**Comment by GrahamCampbell** [comment]
I don't agree that's a good approach here. We can certainly recommend people v3, but until everyone gets caught up, we just needlessly stopping people from upgrading. Maybe once v3 is up to 30% of the downloads, we could reconsider, maybe for Laravel 10.

**Comment by kylekatarnls** [comment]
For me scarifying the type strictness to allow backward compatibility with v1 and v2 is fine, but I proposed this change because I got interface incompatibility PHP errors when using PHP 8.1 and psr/log 3, I will check if it's now working but if you just revert the previous change we likely have the incompatibility again.

**Comment by GrahamCampbell** [comment]
This is not a straight up revert. It fixes compatibility with v3, without breaking v1 and v2.

**Comment by kylekatarnls** [comment]
Oh I see you reverted the param type but not the return type so it's both covariant and contravariant.

Impressed

**Comment by GrahamCampbell** [comment]
Yeh. :)

**Pull request merged**
