### PR TITLE
[7.x] Add select method to Collection

### PR DESCRIPTION
**Pull request by ecrmnn**
The `select` method will return a collection with the specified keys.

After considering different names for this method I decided to go with `select` since it's also used in the query builder to select columns.

Explained in detail on this discussion https://github.com/laravel/framework/discussions/32991

```php
$people = collect([
    [
        'first' => 'John',
        'last' => 'Doe',
        'name' => 'John Doe',
        'email' => 'john.doe@gmail.com',
    ],
    [
        'first' => 'Jane',
        'last' => 'Doe',
        'name' => 'Jane Doe',
        'email' => 'jane.doe@gmail.com',
    ],
]);

$people->select(['first', 'last', 'email'])->all();
// or ...
$people->select('first', 'last', 'email')->all();

//=> [
//=>     [
//=>         'first' => 'John',
//=>         'last' => 'Doe',
//=>         'email' => 'john.doe@gmail.com',
//=>     ],
//=>     [
//=>         'first' => 'Jane',
//=>         'last' => 'Doe',
//=>         'email' => 'jane.doe@gmail.com',
//=>     ],
//=> ]
```

### CODE REVIEW

**Comment by adiletmaks** [comment]
Looks good, but what about `only()` method ?

**Comment by ecrmnn** [comment]
@adiletmaks Explained in detail on this discussion #32991

> I've previously made a [PR](https://github.com/laravel/framework/pull/29055), but it was a breaking change when extending the functionality of the `only` method. I'm sure this is a great addition to Collection, but I want to discuss the naming of the method.

**Comment by taylorotwell** [comment]
Seems to only work if the items in the collection are arrays?

**Comment by ecrmnn** [comment]
@taylorotwell You're right, I missed that unfortunately. 

I've implemented this for Eloquent objects and its working great. 
This PR isn't automatically updating since its closed. Should I open a new PR? 

Link to commit if you're interested https://github.com/ecrmnn/framework/commit/f4c49433442adbe2a5930893b4c1c3a6dc20f39f

**Pull request closed without merging**
