### PR TITLE
Change typehinting in Bladecompiler to extend via __invoke

### PR DESCRIPTION
**Pull request by bastiankoetsier**
With this change you can extend Blade with classes that implement `__invoke` in addition to anonymous functions

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Send to 5.1 please, and also use tabs for indentation, and don't change the spacing in the docblock. It was 2 spaces for a reason.

**Comment by bastiankoetsier** [comment]
Wow, that was quick :-) Just to be sure: With 5.1 you mean ```master``` ? I thought, i should send it to 5.0 because of:
"Minor features that are fully backwards compatible with the current Laravel release may be sent to the latest stable branch."

**Comment by GrahamCampbell** [comment]
This is a breaking change to the method signature of a public method.

**Comment by bastiankoetsier** [comment]
Sorry to bother you again :-( 
I don´t really see, where this change ist "breaking" ? I´m with you, that the method signature changes with this commit. But it is still possible to extend Blade with an anonymous function like before (see https://gist.github.com/bastiankoetsier/a49e4d28bf36f29a8161). Additionally you are able to pass a class to the ```extend```method, that implements ```__invoke```, so basically more flexibility. 
After this is clear, i´m going to send this PR to every branch you like :-)

**Comment by GrahamCampbell** [comment]
It's breaking for class extention.

**Comment by bastiankoetsier** [comment]
Thanks for clarification !
PR incoming in ```master``` :-)

**Comment by GrahamCampbell** [comment]
It's possible Taylor will disagree with me and want this on 5.0, but we'll see. Thanks anyway.

**Pull request closed without merging**
