### PR TITLE
[5.0] Fix Doctrine Column Types

### LINKED ISSUE #7560: v5.0.6 Doesn't Register 'bigInteger' Column Type with Doctrine?
After updating to v5.0.6, I'm getting the following error when running migrations which reference 'bigInteger' columns. v5.0.5 does not seem to have this issue.

[Doctrine\DBAL\DBALException]                                                                                        
  Unknown column type "bigInteger" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL  
  \Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If  
   this error occurs during database introspection then you might have forgot to register all database types for a Do  
  ctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedD  
  atabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping informatio  
  n.

### PR DESCRIPTION
**Pull request by GrahamCampbell**
@jakecarlson, @rilut, does this actually fix this for you?

I don't use doctrine myself, so I'm not certain this is actually correct.

---

Closes #7560.

### CODE REVIEW

**Comment by rilut** [comment]
@GrahamCampbell It works, I've tried your fix for a `dateTime` column (yes, `datetime` in doctrine)

**Comment by taylorotwell** [comment]
How do we know this doesn't recreate other bugs? We have no tests here.

**Comment by GrahamCampbell** [comment]
@taylorotwell The trouble is, that if I wrote tests cases, we could just be asserting an incorrect behaviour. I need more information for someone who actually knows what they're doing with doctrine. Then I'd be happy to add some test cases.

**Comment by GrahamCampbell** [comment]
@jakecarlson Has just confirmed this works for him too. I'll write some tests soon, since it looks like this implementation is indeed, correct.

**Pull request merged**
