### PR TITLE
Pass basic authentication field parameter to the auth.basic middleware

### PR DESCRIPTION
**Pull request by Omranic**
This is fully backward compatible.
Allow customizing the authentication field easily:
```php
$this->middleware('auth.basic:guardians,username')
```

### CODE REVIEW

**Comment by jmarcher** [comment]
You can easily achieve the same by extending the middleware itself, I do not see this as part of the core, to be honest.

**Comment by Omranic** [comment]
Yes, it's possible to extend or override the middleware, but the question is why should we do so when this is a core feature, and could be passed as an optional parameter, with full backward compatibility.

It's the same case as for the guard parameter I believe.

**Comment by taylorotwell** [comment]
Breaking change if extending the middleware already.

**Comment by taylorotwell** [comment]
Resubmit to master.

**Pull request closed without merging**
