### PR TITLE
[5.6] Optional can be converted into string

### PR DESCRIPTION
**Pull request by TheDeadCode**
Fix for #23303

### CODE REVIEW

**Comment by taylorotwell** [comment]
Do you have a real-world use case?

**Comment by TheDeadCode** [comment]
My own --

I use an external library and it uses a direct cast on the objects in a list, to populate different fields. It either takes `null`, three different types of objects, or a string to get the value.

We only implement those types of objects in a few places, but we use `__toString` everywhere else. `optional()` was perfect for us due to that, except that it lacked the ability to cast.

It can also potentially break the code if someone were to move from the instance of a specific object, to `Optional`, and direct cast it to a string, either in his own code or in an external library.

**Comment by BrandonShar** [comment]
Based on the test, I don't think I understand the use case. An optional, after having a method called on it, is going to return either the expected result or swallow it and return nothing. Casting `(string) optional($var)` with your change doesn't seem to have any benefit for using the optional, at the end of the day you're just running `(string) $var`.

**Comment by TheDeadCode** [comment]
The goal was to make the optional class as much compatible as possible with the underlying object.

**Comment by BrandonShar** [comment]
Yes, but optional is used when you don't know if your variable contains an object or not. With your use case, optional doesn't actually do anything because the behavior is the same whether it's passed an object or null. 

With your code:
```php
$x = null;

(string) optional($x); // ""
(string) $x; // ""
```

Why even use optional here?

The normal usage is when you're doing something like calling a method `optional($x)->someMethod()` where having null would cause an error.

**Comment by 36864** [comment]
@BrandonShar You only tested the null case. This is to fix the non-null case of casting optional to string.
```
>>>$user = App\User::find(1);
=> App\User {#878} //collapsed for brevity
>>> (string) optional($user);
PHP Recoverable fatal error:  Object of class Illuminate\Support\Optional could not be converted to string on line 1
```

**Comment by TheDeadCode** [comment]
Exactly what @36864 said. This *is to make optional compatible with the underlying object*, like I have said *multiple times* now.

When you can null to a string, you get “”, which is the expected behaviour. 

If you do not feel like making optional compatible with the underlying object as much as possible, then simply close this PR.

**Comment by BrandonShar** [comment]
I must not be being clear...

Here's what you want to change optional to do:

```php
$x = null;
(string) optional($x) // ""
$x = User::find(1);
(string) optional($x) // {"id": 1, ...}
```

And here's what happens if you *don't use optional at all*

```php
$x = null;
(string) $x // ""
$x = User::find(1);
(string) $x // {"id": 1, ...}
```

So why are you using `optional` at all?

**Comment by 36864** [comment]
Consistency, mostly? 

```
$x = optional($model);
$x->maybeDoSomething();
$service->print($x);
```

I'd also like to point out this PR, which is essentially the same type of addition (making optional work in a case where it wouldn't be needed at all): https://github.com/laravel/framework/pull/22417

**Comment by BrandonShar** [comment]
I wouldn't have merged #22417 either :wink: 

I understand your example now, I wasn't thinking of a situation like that. I would discourage storing `optional` values and keeping them, though; I don't think this is the only situation where it would behave strangely.

I didn't write the original optional code, but I've always assumed it was based on the `&` operator in ruby and have used it as such: just use it to swallow potential method call on null errors and don't actually hang on to the result long term.

**Comment by taylorotwell** [comment]
@TheDeadCode can you share the actual code snippet demonstrating how you want to use this?

**Comment by taylorotwell** [comment]
I'm still just confused on why you are echoing an optional result directly. Usually when optional is used it is to access some other property or method on the given value, not echo the optional itself.

**Comment by GrahamCampbell** [comment]
NB, in most other languages, to string is not directly proxied in an optional. They usually wrap the string up so you know you printed an optional.

**Comment by taylorotwell** [comment]
Closing pending inactivity. Feel free to re-open with more examples of how this would be used.

**Comment by hsntngr** [comment]
@taylorotwell I'm having same issue with 5.7 

Error: `Object of class Illuminate\Support\Optional could not be converted to string`

Code

```php
getImage("gpu:originals", optional($post->featured->first())->path)

function getImage($type, $path = null)
{
    return \ImageHandler::getPublicPath($type, $path);
}

   public function getPublicPath($opts, $image = null)
    {
        # parse image options
        $options = $this->parseOptions($opts);

        # if image is null, return fb image
        if (!$image) {
            return $this->fallbackImage($options);
        }
        # check image image exists on storage
        $exists = Storage::disk("local")
            ->exists($options["size"] . "/" . $image);

        # if image does not exists, return fallback image
        if (!$exists) {
            return $this->fallbackImage($options);
        }

        # return public image path
        return asset("storage/" . $options["size"] . "/" . $image);
    }
```

**Pull request closed without merging**
