### PR TITLE
[10.x] `naturalLanguageList` string helper

### PR DESCRIPTION
**Pull request by hungthai1401**
This PR ships `naturalLanguateList` string helper.

Example:
```php
['one', 'two', 'three'] => 'one, two and three'
```

### CODE REVIEW

**Comment by nexxai** [comment]
There's a few things here that I think are going to generate some discussion:

1. Are the methods supposed to be spelled using 'languate' rather than 'language'?
2. Will there be support for the Oxford comma?
3. And finally, the most important: what problem does this solve?

**Comment by hungthai1401** [comment]
@nexxai Thanks
1. This is my typo. I will fix it
2. No, it's not support Oxford comma.
3. The purpose of this helper is `forming natural language`

**Comment by chu121su12** [comment]
This already exists as another form in Arr
https://github.com/laravel/framework/blob/5c93d2795c393b462481179ce42dedfb30cc19b5/src/Illuminate/Collections/Arr.php#L437

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by hungthai1401** [comment]
@chu121su12 thanks

**Pull request closed without merging**
