### PR TITLE
[5.2] Deleting unused method.

### PR DESCRIPTION
**Pull request by ghost**
Reading the code, I've noticed a method which is not used, or not being used as it should.

So... I think I've fixed it.

### CODE REVIEW

**Comment by gmsantos** [comment]
Bad idea. Removing a public method probability leads to BC changes. 

How can you assure that no one is using it?

**Comment by IlyaBakhlin** [comment]
I've checked with PhpStorm there're no uses of the public method.

Also the tests are passing.

**Comment by gmsantos** [comment]
It's a public method... you can't guarantee that every single project with Laravel on the entire world is not using this specific method...

**Comment by SuryaElite** [comment]
I'm using this method in one of my internal projects.

**Comment by IlyaBakhlin** [comment]
Well... In my opinion, if you're using it, you're doing bad, just because the code design is awful. The `$methods` property is returned by the `methods` method, and this last one is returned by the `getMethods` method. Am I the only one who notices a duplicated and useless code?

The best practice is to use the `getMethods` method which should return the `$methods` property.

**Comment by danieliancu** [comment]
@IlyaBakhlin I agree with what you say, but this should be targeted at `5.3` because it is a breaking change.

**Comment by IlyaBakhlin** [comment]
@danieliancu, done. :v:

**Comment by GrahamCampbell** [comment]
Public methods are not "unused" by definition.

**Comment by GrahamCampbell** [comment]
Laravel intentionally added this method for ease of use.

**Comment by danieliancu** [comment]
@IlyaBakhlin I mean to submit your PR to the master branch.
https://laravel.com/docs/5.2/contributions#which-branch

**Comment by IlyaBakhlin** [comment]
@GrahamCampbell, really? Well that creation is another stupid as fuck addition by Laravel, hahaha! The first one I've noticed is putting the Authentication routes to the `vendor` directory, duplicating the code if you want to custom them.

Any way, fuck it; keep destroying the programming good practices with you "beautiful" code. :kiss:

**Comment by lagbox** [comment]
"Yea, well, you know, that's just, like, your opinion, man." - The Dude

**Pull request closed without merging**
