### PR TITLE
[5.7] Modifies Route::redirect to use 302 as the default status code instead of a 301

### PR DESCRIPTION
**Pull request by shrink**
A [301 status](https://httpstatuses.com/301) is a permanent redirect from one location to another, these redirects are cached by browsers, which is the expected behaviour:

>  A 301 response is cacheable by default; i.e., unless otherwise indicated by the method definition or explicit cache controls.

Laravel defaults to using a `301` in the `Route::redirect` method. This is unfortunately quite dangerous: if a developer does not know that a `301` is going to be used, and that it is going to be cached with no expiry, their users will be permanently redirected with no way for the developer to undo the redirect.

Laravel does not default to a `301` anywhere else, for example the [`redirect` helper](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/helpers.php#L680) defaults to a `302`.

I have performed a [search of GitHub for open source Laravel projects using the `Route::redirect` method](https://github.com/search?q=%22Route%3A%3Aredirect%22+extension%3Aphp+path%3Aroutes&type=Code) and found the following:

1. Many developers are explicitly defining their status code as `301`
2. Some developers are using the `redirect` method within conditionals without specifying a `302`

This indicates to me the following things are true:

1. Developers expect that the default is not `301`
2. Developers who wish to use a `301` are explicitly defining it 
3. Developers are shipping applications that will perform in unintended ways because they do not realise that by default all redirects are permanently cached by their user's browsers

Therefore I propose that the default be changed to a safe `302`. Due to the permanent nature of a `301` it should only be used when explicitly defined by a developer. 

Edit to add: this [Super User post](https://superuser.com/questions/304589/how-can-i-make-chrome-stop-caching-redirects) where people discuss accidentally using 301s and trying to deal with the cached result has over 230,000 views, which indicates that there are a lot of developers uninformed about the result of using a 301.

Thanks!

### CODE REVIEW

**Comment by 36864** [comment]
I would argue that the reason most people explicitly pass 301 as the status code is because that's what the example in the documentation does.

A better approach to this would be to change the documentation, to clarify that 301 is the default status code and that means redirections are permanent.

Redirect routes are most useful for migrating old URLs to new ones (which is generally a permanent change), or to alias common typos (i.e.: redirect '/user/1' to '/users/1', also a permanent thing). Using redirect routes for temporary redirects should be the exception, not the rule.

Instead of forcing everyone who knows what a permanent redirect is, and actually bothered to look at a method signature before using it, to go back and change all their routes files to explicitly add a 301 status codes, could we just make a better effort to educate new users?

**Comment by citricsquid** [comment]
There are many different use cases for the `redirect` method. A permanent redirect from a legacy route is one of them, but there are many more that don't involve permanency, such as conditional redirects and upcoming-feature "coming soon" page.

The documentation would need to read something like:

>  ⚠This method uses a `301` status code by default, which is a **permanent redirect**. A permanent redirect is cached by the user's browser with no expiry, meaning that once the redirect has been followed by a user you will not be able to change that redirect for that user until their cache expires (which can take months, or years). This should only be used when you are absolutely sure that you will not need to use this route again. If you do not wish to permanently redirect this route, pass a `302` status code as the third parameter. 

When a warning like that is neccessary, why not change the default behaviour to be safe and require explicit opt-in to the dangerous behaviour? There are no breaking changes with this change, all of your redirects (without an explicit status code) will continue to redirect, and if you wish for them to be cached permanently by your user's browser then you can add the `301` parameter -- which should take a couple of seconds even with hundreds of redirects.

The framework should be consistent and safe by default. A `302` is used for all other redirects (by virtue of using the `redirect` helper) -- it doesn't make sense to deviate from this for one class of redirect, and thus require a warning in the documentation. A user, like yourself, who understand the behaviour of a `301` and *wants* the behaviour of a `301` should opt-in.

**Comment by taylorotwell** [comment]
I'm going to revert this. I don't think the `Route::redirect` and `redirect` helpers necessarily need to be consistent. They serve different purposes. If I am hard-coding a redirect right into my route's file like `Route::redirect` allows, I think the more common use case is that is a permanent redirect.

**Comment by citricsquid** [comment]
@taylorotwell my concern isn't that Laravel should be consistent for the sake of being consistent, Laravel exists to make developers lives easier and inconsistency is sometimes a part of that: my concern is that a 301 has severe side effects and so unlike, say, arguments about `needle, haystack` vs. `haystack, needle`, this isn't just a "whoops, I made an error in my code, I'll fix it and run my tests again / deploy the new version" it's a problem that can't be easily debugged or fixed because the damage lives on in user's caches indefinitely.

There are many ways to use redirect routes and certainly a permanent redirect is one of them and the most common, but in that case given the consequences associated with a 301 it should be up to the developer to actively decide that they want the redirect to live on in their user's cache forever by opting in to a 301.

If a 301 didn't have these side effects then I'd absolutely agree that it makes complete sense to be inconsistent here. I also understand that the api for `redirect` is pretty ugly when including a 301 if you *do* want a permanent redirect and it probably feels unnecessary, especially for someone who understands what a 301 is and the consequences of it, but for a developer who doesn't have that knowledge and ships an application with a 301 they don't know about, it's going to be a nightmare to debug the consequences and rectify them.

If making the `redirect` methods api cleaner is more important than ensuring developers don't shoot themselves in the foot, then I think at the very least the documentation should include a warning about the consequences of a 301 as it's quite common for developers not to be aware of them. I'm happy to update the documentation with that warning if this is reverted.

Thanks!

**Pull request merged**
