### PR TITLE
[5.1] Improve each method

### PR DESCRIPTION
**Pull request by srobati**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Needs description.

**Comment by GrahamCampbell** [comment]
@taylorotwell This is basically just a miro-optimisation. We're saving significantly on memory because the `(array)` cast causes php to copy the entire array on every iteration, so moving it outside the outer loops stops that happening.

**Comment by JoostK** [comment]
@GrahamCampbell That is not entirely true. Yes, the cast will be run every iteration of the inner loop, *however* every cast of a variable that is already of the intended type has no further side effects or copies or something, simply nothing happens then (except for having to execute an additional opline). See https://github.com/php/php-src/blob/f58ebb36094e6c59d4e87bfba2a0504858adbec9/Zend/zend_operators.c#L580-L581 for the main implementation of the array cast operator (called from the VM when interpreting the `ZEND_CAST` opcode).

**Comment by GrahamCampbell** [comment]
@JoostK Are you sure that's the case in php 5.5?

**Comment by GrahamCampbell** [comment]
@JoostK Just checked. You are correct. :)

**Comment by GrahamCampbell** [comment]
> If you meant the variable is not already an array, then yes each iteration will create a new array.

Yeh. :)

**Comment by srobati** [comment]
guys you're right,thanks @JoostK . but however `(array) $rules` take some steps for casting.

**Comment by lukasgeiter** [comment]
I think this should be merged. It might not make a big difference, but still makes sense. And I don't see any disadvantages with it.

**Comment by Sladewill** [comment]
It's usually regarded as best practice in any programming language to not call things like this so I agree its just so it matches general standards.

**Pull request closed without merging**
