### PR TITLE
[5.7] Extract Nexmo and Slack drivers to own package

### PR DESCRIPTION
**Pull request by themsaid**
The channels were extracted to:

https://github.com/laravel/slack-notification-channel
https://github.com/laravel/nexmo-notification-channel

### CODE REVIEW

**Comment by koenhoeijmakers** [comment]
Why not in https://github.com/laravel-notification-channels as the docs still reference to as a sort of "collection of all notification channels"?

**Comment by devcircus** [comment]
That’s a “community” driven repo. These are official Laravel packages.

**Comment by koenhoeijmakers** [comment]
Can totally get behind that. 

It's just that `laravel-notification-channels` doesn't seem that active in the form of adding new channels as the oldest new channel PR dates from `Sep 6, 2016` and that this might have been a point to pick that up again.

**Comment by laurencei** [comment]
Seems strange to be doing this on a point release (even if its not breaking). Why not leave the whole change until 5.8 entirely?

**Comment by themsaid** [comment]
@taylorotwell added to the framework's composer.json file.

**Comment by laurencei** [comment]
@themsaid - Travis is failing with "Your requirements could not be resolved to an installable set of packages"

**Comment by themsaid** [comment]
@laurencei  yes, for now. We'll need to publish the libraries on packagist first.

**Comment by taylorotwell** [comment]
Are we going to move the tests the repos?

**Comment by taylorotwell** [comment]
Both packages have been added to Composer.

**Comment by themsaid** [comment]
@taylorotwell build is passing now.

**Comment by taylorotwell** [comment]
@mfn @laurencei do you have a reason why we shouldn't? It's not a breaking change in any way?

**Comment by laurencei** [comment]
It felt strange initially - and then I considered the fact that the framework is essentially a bunch of packages, and so in that respect it makes sense. I agree there is no breaking change that I can think of either.

**Comment by taylorotwell** [comment]
@themsaid do you want to tag 1.0.0 of both of the packages?

**Comment by TBlindaruk** [comment]
@taylorotwell , @themsaid , @driesvints ,

Maybe will be better to move this packages with git history?

http://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/

**Comment by driesvints** [comment]
@TBlindaruk it's a bit to late for that since we already tagged versions. Didn't know about this. Thanks for sharing! :)

**Comment by TBlindaruk** [comment]
@driesvints we still can do it in the separate branch)))

Like:
1. delete files from the package 
2. moved files with the history

;)

**Comment by driesvints** [comment]
@stevebauman please see https://github.com/laravel/framework/issues/26766 & https://github.com/laravel/nexmo-notification-channel/issues/2

**Comment by stevebauman** [comment]
Thanks @driesvints, that was indeed the issue. To resolve I had to manually delete `app/bootstrap/cache/config.php` as artisan wouldn't boot properly with this issue.

**Comment by fitztrev** [comment]
@mfn It could be a breaking change. Now, the `nexmo/client` package and all its dependencies are installed in my app, when before it was just a "suggested" package left for me to decide if I want to use that driver. The `nexmo/client` package has a number of outdated dependencies:

```
Package                      Installed  Latest   Description
============================================================================
php-http/guzzle6-adapter     v1.1.1     v2.0.0   Guzzle 6 HTTP Adapter
php-http/httplug             v1.1.0     v2.0.0   HTTPlug, the HTTP client abstraction for PHP
ralouphie/getallheaders       2.0.5      3.0.1   A polyfill for getallheaders.
zendframework/zend-diactoros  1.8.6      2.0.1   PSR HTTP Message implementations
```

I don't already use any of those but if I did, and had the latest version of any of them installed, it would cause issues.

I noticed on the master branch these have been removed: 88b9fd6b62c0a01ed6adc65d089c94813c2f1762

**Comment by TBlindaruk** [comment]
@driesvints

**Comment by driesvints** [comment]
@fitztrev At the moment we're not getting any issues about this so I wouldn't revert.

**Comment by Kyslik** [comment]
Isn't this breaking change? I can not update above 5.7.15 without:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Container.php line 960:

  Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in cla
  ss Illuminate\Support\Manager
```

**Comment by stevebauman** [comment]
Hi @Kyslik, are you sure you cleared the `boostrap/cache/config.php` file? I literally had the exact same error as you:

https://github.com/laravel/framework/pull/26689#issuecomment-445289646

You'll have to delete the files manually since artisan will try to auto-load your providers which will generate the same exception.

**Comment by Kyslik** [comment]
@stevebauman  As I mentioned I did `git clone...` (on brand new machine) && `composer update` so I did not have the `bootstrap/cache/config.php` present.

It's solved for me with disabling the auto-discover for those two packages.

**Comment by stevebauman** [comment]
I understand @Kyslik. Did you add the `NotificationServiceProvider` to your `config/app.php` file?

**Comment by Kyslik** [comment]
@stevebauman no I did not; I am sure that the app I am talking about worked on L5.7.15 (on server its still running like that) I tried to update to latest L5.7.17 on my local machine and got the error about `Illuminate\Support\Manager`.

**Comment by stevebauman** [comment]
You will need to add that service provider to get back up and running. Give it a shot and let me know if it works.

**Comment by Kyslik** [comment]
@stevebauman yes that works as well.

```
...
\Illuminate\Notifications\NotificationServiceProvider::class,
```

and removed `dont-discover` from composer.json

And it works as expected:

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/nexmo-notification-channel
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
```

Thank you :). I still think the change should be in L5.8 instead.

**Comment by stevebauman** [comment]
@Kyslik Great to hear! And I also agree, but it's already been pushed into a release so oh well 🙁 

I don't even use these notification channels so it's somewhat disappointing that we're forced to download these into our projects.

**Pull request merged**
