### PR TITLE
Support listening on abstract classes

### PR DESCRIPTION
**Pull request by paulschwarz**
Event Dispatcher supports listening on abstract classes in addition to concrete classes and interfaces.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please send this to 5.4 since it's a major breaking change.

**Comment by GrahamCampbell** [comment]
I'm also concerned over how much slower this now is.

**Comment by paulschwarz** [comment]
Thanks for the feedback. Where do we see performance metrics?

**Comment by markkarimov** [comment]
Where do you see the breaking change? If anything, it only completes the functionality. Would be nice to see it in 5.3.

**Pull request closed without merging**
