### PR TITLE
[v11] Spark is not a framework dependency, middleware does not exist

### PR DESCRIPTION
**Pull request by pxpm**
I was bugged with https://github.com/laravel/framework/issues/50298

I think closing the issue was an overlook, as I still think this does not belong here. 

I should have created the PR at first to better illustrate the issue, sorry for that 🙏 

Cheers

### CODE REVIEW

**Comment by browner12** [comment]
Are you manually attaching that middleware to some routes? Or is this on a clean install?

**Comment by pxpm** [comment]
> Are you manually attaching that middleware to some routes? Or is this on a clean install?

I am not touching that middleware in any place. 

I am pushing other middlewares in the ServiceProvider with `Router::pushMiddlewareToGroup()`, not sure if that can be anything related here. Those middlewares are not the spark one, or I am not trying to set another `subscribed` middleware.

**Comment by pxpm** [comment]
Ok, I was able to find what was logging that into my app logs. 

My editor static analyser was the culprit. I was able to reproduce the issue by forcing it to re-index the project files. 

Whenever it reindexes that class the error is thrown, because "technically" the class should exists as `subscribed` is a perfectly valid key from that array. One should know before hand that to use "subscribed" alias you must first install the spark package, but what's the point ? 
Can't that alias be registered by spark package ? 

Feel free to close if you think it's ok as it is, but from my POV, even if I found this "by chance" and shouldn't be getting this error unless "i try to use the alias without installing the package", it makes more sense that this package alias to be registered by the package itself. 

Cheers

**Comment by taylorotwell** [comment]
Sorry, how do I recreate this issue on a fresh Laravel 11 application. We are registering that alias for convenience for Spark users. I don't see how just listing that in the aliases array would cause any issue? What do I need to type into a fresh Laravel 11 routes file to trigger an error?

**Comment by taylorotwell** [comment]
Closing for now.

**Pull request closed without merging**
