### PR TITLE
[10.x] Feature Fluents Methods Arrays

### PR DESCRIPTION
**Pull request by rmunate**
Hello Engineer Taylor,

I feel comfortable sending you this proposal as I believe it would greatly enhance the handling of arrays in our Laravel systems. I say this because working with fluid methods where we can chain them together to achieve the expected result is more convenient and elegant than nesting instances within instances of `Arr::method(Arr::method())`.

With this proposal, I aim to achieve two things. Firstly, to introduce functionality similar to how `Str::of()` currently works with the proposed method `Arr::of()`. Secondly, I would like to separate the "Arrays" section, similar to how the "Strings" section was separated, leaving only helper functions in the helpers section that do not require a class instance.

The behavior of the different methods would be as follows:

```php

// Arr::accessible()
Arr::of(['a' => 1, 'b' => 2])->accessible(); 
// true

// Arr::add()
Arr::of(['name' => 'Desk'])->add('price', 100)->add('quantity', 50);
// ['name' => 'Desk', 'price' => 100, 'quantity' => 50]

// Arr::collapse()
Arr::of([[1, 2, 3], [4, 5, 6]])->collapse([[7, 8, 9]]);
// [1, 2, 3, 4, 5, 6, 7, 8, 9]

// Arr::crossJoin()
Arr::of([1, 2])->crossJoin(['a', 'b']);
/*
    [
        [1, 'a'],
        [1, 'b'],
        [2, 'a'],
        [2, 'b'],
    ]
*/

// Arr::divide()
[$keys, $values] = Arr::of(['name' => 'Desk'])->divide();
// $keys: [0 => "name"]
// $values: [0 => "Desk"]

// Arr::dot()
Arr::of(['products' => ['desk' => ['price' => 100]]])->dot();
// ['products.desk.price' => 100]

// Arr::except()
Arr::of(['name' => 'Desk', 'price' => 100])->except('price');
// ['name' => 'Desk']

// Arr::exists()
Arr::of(['name' => 'John Doe', 'age' => 17])->exists('name');
// true

// Arr::first()
Arr::of([100, 200, 300])->first(function (int $value, int $key) {
    return $value >= 150;
});
// 200

//... And within the same context, 100% of the methods available from the `Arr::class`.
```

Methods that return arrays will return a static instance of the `Illuminate\Support\Arrayable` class, allowing other methods available in the class to be chained. Only methods that return something other than an array won't support chaining, just like how `Str::of()` works. If you do not wish to access additional methods, the magic method `__get()` is also available for you to use (->value) to access the corresponding value.

Engineer Taylor, if you find this feasible, I look forward to your feedback. I would work on the tests as well as the corresponding documentation.

I remain attentive to your comments.

### CODE REVIEW

**Comment by henzeb** [comment]
We have Collections for that....

**Comment by rmunate** [comment]
Hello @henzeb,

What you're mentioning is absolutely correct. Collections are a great way to work with data. I anticipated that situations like these might be raised by the Laravel team and other contributors. Therefore, I wanted to present this feature request early on to initiate a discussion and receive valuable feedback. Please believe me when I say that there will still be instances where arrays are the most suitable solution for different situations in our code. Just as the `Str` class has become an incredibly convenient way to work with strings, we can aim to provide similar ease of use for arrays. Thank you for considering this proposal.

**Comment by henzeb** [comment]
You don't understand. your Arrayable implementation is a primitive version of Collection, as in, Collection is also an array internally stored in a value, but also allows all kinds of iterable stuff to be put into it. Yours will never return an scalar array, just like Collection, both have the need to call toArray once done.

And i am not sure what your are trying to do with __get, but Collections also have a good implementation of higher order functions.

If you need chaining, Collections are perfectly fine for that. At the end you need the array, value() or toArray() doesn't matter. it's the all the same.

**Comment by CalebDW** [comment]
What if `Arr::of` returned a `Fluent` object and then all of the `Arrayable` methods were placed on the `Fluent` class instead? The `Fluent` already uses an internal array and allows for both array and object access---the only thing it's missing in my opinion are the nice helper methods to operate on it like `map`, `each`, etc.

**Comment by henzeb** [comment]
> What if `Arr::of` returned a `Fluent` object and then all of the `Arrayable` methods were placed on the `Fluent` class instead? The `Fluent` already uses an internal array and allows for both array and object access---the only thing it's missing in my opinion are the nice helper methods to operate on it like `map`, `each`, etc.

What would make this any different than a Collection? I might be missing something, but I believe making an Arr::of implementation that allows chaining is basically reïnventing Collections.

**Comment by Rizky92** [comment]
There was an [attempt](https://github.com/laravel/framework/pull/45752) in the past to make fluent array helper. If you're working with complex array manipulation, you should use `Collection`.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
