### PR TITLE
[5.3] XSRF-TOKEN cookie can be set as httpOnly

### PR DESCRIPTION
**Pull request by ametad**
see: https://github.com/laravel/framework/issues/16191

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
NB Related to https://github.com/laravel/framework/pull/11346.

**Comment by taylorotwell** [comment]
I think the whole point of this token is to be JavaScript accessible because it's designed to work with frameworks like Angular or HTTP libraries like Axios that use this cookie as a convention to copy it over into a header for you automatically.

**Comment by ametad** [comment]
Okay I see.. It's not as 'bad' as I thought then :)

**Comment by Frondor** [comment]
> I think the whole point of this token is to be JavaScript accessible because it's designed to work with frameworks like Angular or HTTP libraries like Axios that use this cookie as a convention to copy it over into a header for you automatically.

And that way, you're trading off a good security design over specific front-end libraries support. Why would I want the `XSRF-TOKEN` cookie to be exposed and facilitate XSS attacks? Even if I don't use any of those libraries, that should be configurable in my opinion, and then update the middleware to also take it from the cookie in
https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L138 
like `$token = $request->input('_token') ?: ($request->cookie('XSRF-TOKEN') ?: $request->header('X-CSRF-TOKEN'));`

Read more about this on : https://stackoverflow.com/questions/21357182/csrf-token-necessary-when-using-stateless-sessionless-authentication#comment53246664_25198454

**Comment by sisve** [comment]
It's really weird that you highjack a year old issue to argue your point, and then link the issue on the framework/internals repo to this issue. Let's move the discussion of your suggestion to the internals issue.

**Comment by simonschaufi** [comment]
> I think the whole point of this token is to be JavaScript accessible because it's designed to work with frameworks like Angular or HTTP libraries like Axios that use this cookie as a convention to copy it over into a header for you automatically.

Does that mean that if I set a cookie as HTTP only, that JavaScript can't access it anymore?

I have a Web Application Scan Tool running on my application and it complains about the insecure XSRF-TOKEN cookie with this link: https://cwe.mitre.org/data/definitions/1004.html as reference

**Pull request closed without merging**
