### PR TITLE
[5.6] Add @dump blade helper

### PR DESCRIPTION
**Pull request by gilbitron**
Adds a `@dump($data)` help to Blade. Works similar to `@dd()` but doesn't "die".

screen shot 2018-03-02 at 2 12 18 pm

### CODE REVIEW

**Comment by jmarcher** [comment]
This was rejected several times:
https://github.com/laravel/framework/pull/22294
https://github.com/laravel/framework/pull/20043
https://github.com/laravel/framework/pull/19543

**Comment by gilbitron** [comment]
@jmarcher Despite it being an obviously popular request.

**Comment by taylorotwell** [comment]
I give up heh

**Comment by vinterskogen** [comment]
Well, it looks like I had foreseen this will be merged a couple months ago in my PR.   https://github.com/laravel/framework/pull/22294#issuecomment-348839196 Personally I do not think adding an optional debugging helper like this into blade will impact Laravel in any case. Thumbs up on the message above are confirming this opinion eloquently. :)

**Pull request merged**
