### PR TITLE
Check parent class for method dependency injection

### PR DESCRIPTION
**Pull request by GMiLL5**
This should fix issue #7938

### CODE REVIEW

**Comment by JoostK** [comment]
Couldn't we just do `return $value instanceof $class;` (the `instanceof` operator returns false for non-objects)

**Comment by GrahamCampbell** [comment]
Yeh

**Comment by GrahamCampbell** [comment]
Either @GMiLL5 or @JoostK, could you please send a pull with a good solution.

@JoostK - your suggested one looked pretty solid. :)

**Comment by GMiLL5** [comment]
`$class` is passed through as a string so `$value instanceof $class` throws a syntax error

**Comment by JoostK** [comment]
@GMiLL5 According to [the documentation](http://php.net/manual/en/language.operators.type.php) it should work just fine with strings.

To be pedantic: the runtime type of a variable can never be the cause of a syntax error, as parsing happens long before the runtime evaluation. A syntax error occurs when the parser cannot match the input text against the language rules.

**Pull request closed without merging**
