### PR TITLE
[11.x] Adds anonymous broadcasting

### PR DESCRIPTION
**Pull request by joedixon**
Sometimes you may wish to broadcast an ad-hoc event.

An ad-hoc event is one where you don't need to hook into it anywhere else in your application. You just want to notify the frontend of something.

For this, you don't want to go to the trouble of creating a brand new event, you just want to fire off a message.

For this, we can use an anonymous broadcast using the `Broadcast` facade, which can be as simple as:

```php
Broadcast::on('my-channel')->send();
```

_Results in..._

```json
{
    "event":"AnonymousBroadcastable",
    "data":"[]",
    "channel":"my-channel"
}
```

You may dispatch to multiple channels at the same time:

```php
Broadcast::on(['my-channel', new PrivateChannel('my-channel'), 'presence-my-channel')->send();
```

You may also configure the name, payload, broadcasting connections and whether or not it should only be dispatched to others:

```php
Broadcast::on('my-channel')
    ->as('my-event-name')
    ->with(['some' => 'array', 'of' => 'data'])
    ->via('reverb')
    ->toOthers()
    ->send();
```

_Results in..._

```json
{
    "event":"my-event-name",
    "data":"{\"some\":\"array\",\"of\":\"data\"}",
    "channel":"test-channel"
}
```

**Edit:**

After feedback from @lukeraymonddowning, the following conveniences were added:

```php
Broadcast::private('my-channel')->send();

Broadcast::presence('my-channel')->send();
```

### CODE REVIEW

**Comment by lukeraymonddowning** [comment]
Would it be worth having a `Broadcast::private` method as a little convenience helper?

```php
Broadcast::private('my-channel')
    ->as('my-event-name')
    ->with(['some' => 'array', 'of' => 'data'])
    ->via('reverb')
    ->toOthers()
    ->send();
```

**Comment by joedixon** [comment]
> Would it be worth having a `Broadcast::private` method as a little convenience helper?
> 
> ```
> Broadcast::private('my-channel')
>     ->as('my-event-name')
>     ->with(['some' => 'array', 'of' => 'data'])
>     ->via('reverb')
>     ->toOthers()
>     ->send();
> ```

Consider it done 🚀

**Comment by devajmeireles** [comment]
Awesome! Will be a very good addition. I'd like to suggest an interesting addition in my opinion.

As we know Broadcast has two ways of being dispatched, `ShouldBroadcast` and `ShouldBroadcastNow`. 

From what I can understand, this will always be dispatched using `ShouldBroadcast`, which requires queues.

So, it might be interesting to think about something like:

```php
Broadcast::on('my-channel')->send();
```

```php
Broadcast::on('my-channel')->sendNow();
```

Or simply:

```php
Broadcast::on('my-channel')->send(queueable: false);
```

An easy way to achieve this result would be to change the implementation of `send` by making it consume two possible Broadcast classes. One implementing `ShouldBroadcast` and the other implementing `ShouldBroadcastNow`.

**Comment by taylorotwell** [comment]
@devajmeireles implemented.

**Comment by antonkomarev** [comment]
@joedixon Cool feature. But is there is a way to broadcast after db commit as we can do with events by implementing interface `ShouldDispatchAfterCommit`?

**Pull request merged**
