### PR TITLE
[8.x] `@checked` Blade directive

### PR DESCRIPTION
**Pull request by ash-jc-allen**
Hi! This PR's only a small one, but something that I thought might be useful. It adds a new `@checked` Blade directive that can be used in views.

In almost every project I've worked on, I always see this type of approach used for determining whether 'checked' should be placed on a radio button or checkbox:

```blade
<input type="radio" name="active" value="1" {{ old('active', $user->active)) ? 'checked' : '' }}/>

<input type="radio" name="active" value="0" {{ old('active', $user->active)) ? '' : 'checked' }}/>
```

With `@checked`, you could pass the condition straight to the directive and let it handle it for you. As a quick example, say you had the following Blade in a form that you can use to update a user model:

```blade
<input type="radio" name="active" value="1" @checked(old('active', $user->active))/>

<input type="radio" name="active" value="0" @checked(!old('active', $user->active))/>
```

If the condition resolved as a truthy result, `checked` would be added to the input field (making the radio button checked as a result). But, if it's a falsey result, nothing will be output.

Of course, this isn't exactly adding any new functionality, but I thought it could be some pretty nice syntactic sugar to neaten up our views.

If it's anything you'd consider merging, please let me know if any changes need making to it 😄

### CODE REVIEW

**Comment by JayBizzle** [comment]
If this was accepted, would it also be sensible to add `@selected` for `<select>` elements?

**Comment by ash-jc-allen** [comment]
@JayBizzle I had the same idea and was thinking of pitching that, but wanted to see how `@checked` would do first. That'll be next on my list to PR if Taylor's open to it :)

**Comment by chuckrincon** [comment]
> If this was accepted, would it also be sensible to add `@selected` for `<select>` elements?

An [attempt](https://github.com/laravel/framework/pull/19622) to introduce this directive has been made some time ago, but it was rejected.

**Comment by taylorotwell** [comment]
I've ported this over to Laravel 9 in case people were already defining this as a macro or something. Thanks! ❤️

**Comment by ash-jc-allen** [comment]
@taylorotwell Sweet! It hadn't actually crossed my mind about anyone who might already be defining it themselves. If it's not already been done, I'll try and get a PR over today to add the `@checked` and `@selected` to the docs 😄

**Pull request closed without merging**
