### PR TITLE
[5.8] Broadcasting channels guards

### PR DESCRIPTION
**Pull request by willypuzzle**
This PR allows using multiple guards on broadcast channels with private and presence channels.

# How it works ?

We added the possibility to specify some options on broadcast channels as a second parameter to the ```channel``` method.
Only ```guards``` option is supported for now.

```php
Broadcast::channel('channel', function() {
	...
}, ['guards' => ['web', 'console']])
```

This second parameter is optional to ensure backward compatibility. If no guards are specified, the system will use the default user resolver like in current version.

# Why this PR ?

Actually, you can't easily use a specific guard on a broadcast channel without protecting the route used for broadcasting authentication. (which is not protected by default) By default, the user resolver used for broadcasting is the default one. As far as we know, it can't be changed to use a specific guard.
Furthermore, 2 users authenticated by 2 different guards can't communicate on the same channel.

# Use case

By adding this feature, we were able to authenticate 2 types of users on different channels. We were also able to allow communication between these 2 types of users on the same channel.

This can be used to make private chats between users and admins when 2 guards are used for authentication.

# Tests

We have done our best to make unit tests for current and new features.

---

We hope this can be useful to someone else. Feel free to suggest improvements, modifications, or to suggest better solutions. You are welcome !

### CODE REVIEW

**Comment by sisve** [comment]
There are a few method signature changes in this PR. Those are usually breaking changes. Are you sure this shouldn't target the 5.8 release?

**Comment by zedentox** [comment]
We are adding an optional `options` parameter to the `channel` method. Do you think it can break something ?
We added 5.7 in the title because it was the next version of the framework when we made these changes but of course we can target the 5.8, it's not a problem.

**Comment by sisve** [comment]
Adding an optional parameter is okay for callers, but not for those that have derived from the class and overridden the method.

    Warning: Declaration of DerivedBroadcaster::channel($channel, $callback) should be compatible
    with Broadcaster::channel($channel, $callback, $options = Array)

Example: https://3v4l.org/TRTq8

**Comment by zedentox** [comment]
Oh, I forgot this use case. @willypuzzle will change the targeted version.

Again, thank you ! 👍

**Comment by taylorotwell** [comment]
I feel like there are changes here unrelated to the feature you are trying to make. For example, `channelNameMatchPattern` method? Am I wrong and that change is actually needed. I would prefer all code stay the same except only the changes that need to be made to make this feature work.

**Comment by willypuzzle** [comment]
@taylorotwell that code was added in order to avoid to repeat the same portion of code more than one time. Without that function the same code was replied in verifyUserCanAccessChannel and in retrieveChannelOptions for example. In according to the not-repeat-yourself principle.

**Pull request merged**
