### PR TITLE
[7.x] Add "subquery value" where statement support to the query builder

### PR DESCRIPTION
**Pull request by reinink**
This PR adds the ability to add "where subquery value" clauses to the query builder.

Here's a simple (somewhat contrived) example. Let's say you had an olympics app that tracked all the athletes and their medals. Let's say you wanted to find all the athletes whose *latest* medal was a gold medal. Here's how you could do that using this new feature:

```php
$athletes = Athlete::where(function ($query) {
    $query->select('type')
        ->from('medals')
        ->whereColumn('athlete_id', 'athletes.id')
        ->orderByDesc('awarded_date')
        ->limit(1);
}, 'Gold')->get();
```

I've used this in my own apps (via a macro) to find all the users whose most recent membership is of a certain type.

```php
$users = User::where(function ($query) {
    $query->select('type')
        ->from('membership')
        ->whereColumn('user_id', 'users.id')
        ->orderByDesc('start_date')
        ->limit(1);
}, 'Pro')->get();
```

Currently when the `where()` method receives a subquery, it treats it as a nested where statement. I was able to maintain that behaviour and still add this new functionality by simply checking if the second argument is `null`. If it's `null`, then it treats it as a nested where statement. If it's not null, it treats it as a "where subquery value" statement.

### CODE REVIEW

**Comment by reinink** [comment]
Ping @staudenmeir for review. ❤️

**Comment by ManojKiranA** [comment]
Does this PR Support following Syntax

Get all the Users **Where not Gold Medalist**
```
$users = User::where(function ($query) {
        $query->select('type')
            ->from('membership')
            ->whereColumn('user_id', 'users.id')
            ->orderByDesc('start_date')
            ->limit(1);
    }, '!=',' Gold')->get();
```

**Comment by deleugpn** [comment]
What's the difference between this and a whereExists?

**Comment by BrandonSurowiec** [comment]
@deleugpn `whereExists` would include any user who _ever_ got a Gold medal. With the `where` it checks only the user's _last_ medal to see if it was "Gold."

**Comment by reinink** [comment]
@ManojKiranA Yes, this works with any operator (`=`, `<`, `>`, `<=`, `>=`, `<>`, `!=`, `like`, `not like`, etc).

**Pull request merged**
