### PR TITLE
[6.x] added broadcastAs method to BroadcastNotificationCreated

### PR DESCRIPTION
**Pull request by pkarczmarczyk94**
This PR relates to issue #30599. It allows changing notification event name on broadcast.

### CODE REVIEW

**Comment by taylorotwell** [comment]
IMO there is no strong reason to change or customize this.

**Comment by pkarczmarczyk94** [comment]
@taylorotwell  Now channel subscriber has to react to event called `\Illuminate\Notifications\Events\BroadcastNotificationCreated` and every notification's event is called the same. So subscriber has to react to every notification as he doesn't know which one is this. Second thing is that event's name is a namespace of event's class and you can modify custom event's names but not this one, also this functionality was implemented previously (before it was changed by commit I've mentioned in the issue  #30599)

**Comment by graemlourens** [comment]
We have also tried to override this default naming, as we do not want the UI (SPA Angular App) to have anything to know about our class structure naming, either of our code or of the framework we use. We would love such a change to make its way to a future release.

In nearly all places where broadcasts can be triggered, these events can be defined, however not in notifications, and we currently don't see a logical reason why this should not be customisable.

**Comment by graemlourens** [comment]
@taylorotwell Would it be possible to get a clarification on your end why this seems not a good idea to you or how this would damage the strategy of notification broadcasting? Please refer also to my previous comment why customising this is essential for clean separation of backend and UI.

Summary/enhancement of my previous comment: If in any **future laravel releases** the naming of 'BroadcastNotificationCreated' **class name/namespace would change**, this would immediately **break our Interface** for receiving notification broadcasts (as UI would be listening for an broadcast-event that is never fired anymore). In this case we would like to define broadcastAs to something that we have control over changing if needed and coordinate with whatever JS-App is listening.

**Comment by mukarramkhalid** [comment]
This issue has been haunting us for a while now. I hope @taylorotwell sees the problem here.

I had to manually override `BroadcastNotificationCreated` using composer in my app. Kinda hackish but "Desperate Times Call for Desperate Measures".

`"autoload": {
    "exclude-from-classmap": [
        "vendor/laravel/framework/src/Illuminate/Notifications/BroadcastNotificationCreated.php"
    ],
    "files": [
        "app/Overrides/BroadcastNotificationCreated.php"
    ]
}`

**Comment by graemlourens** [comment]
Just to clarify (more for other stumbling upon this, as for me initially this was very confusing):

It IS possible to define the broadcast TYPE (adding method broadcastType() returning a string to your notification class). This however manipulates/defines the type that is **injected into the payload** of the broadcast message (along with socket & id).

Is is possible in this way for the listener to be able to **determine what notification he received** and act accordingly based on the 'type' in the payload - default its the class name of the notification.

This issue is about being able to override/define the **event name** that a subscriber has to listen to **that is always the same for all notifications** (default Illuminate\Notifications\Events\BroadcastNotificationCreated)

**Comment by Kyoss79** [comment]
@mukarramkhalid it seems your solution in composer.json does not work anymore with composer2 and psr-4 autoloading.

I tried to get this working by binding the class to something else, but to no avail. Maybe someone else has an idea.

In the AppServiceProvider i put:
`$this->app->bind(\Illuminate\Notifications\Events\BroadcastNotificationCreated::class, \App\Events\BroadcastNotificationCreated::class);`

**Comment by mukarramkhalid** [comment]
> @mukarramkhalid it seems your solution in composer.json does not work anymore with composer2 and psr-4 autoloading.
> 
> I tried to get this working by binding the class to something else, but to no avail. Maybe someone else has an idea.
> 
> In the AppServiceProvider i put: `$this->app->bind(\Illuminate\Notifications\Events\BroadcastNotificationCreated::class, \App\Events\BroadcastNotificationCreated::class);`

@Kyoss79 

It should work with composer 2. It's a simple class exclusion and autoloading a file of your choice. Composer 2 fully supports this. 

Please note that this requires a `composer dump-autoload` once you make the change. Maybe that's what you're missing?

**Pull request closed without merging**
