### PR TITLE
[5.8] Accept underscores in the URL validator, as the URL will load

### PR DESCRIPTION
**Pull request by sgilberg**
We came across an issue in one of our Laravel apps (currently using 5.8) in which a valid URL was being treated as invalid by the 'url' validation rule, due to the presence of an underscore in the domain name (which, while unconventional, still works). Laravel's validateUrl() method documentation states that it is based on Symfony's UrlValidator. Symfony recently released a fix for this same issue here: https://github.com/symfony/symfony/commit/ad89564ebfaac0367449e8625eac3538d5eecdab (see related discussion here: https://github.com/symfony/symfony/issues/32506). 

I copied the pattern update into Laravel's validateUrl() method and updated the corresponding tests accordingly.

(I realize we are _just_ out of the published window for bug fixes on 5.8, but I'm hoping we can squeeze in one this small anyway, as it is compatible with the current release. I can resubmit to the 6.x branch if necessary.)

### CODE REVIEW

**Comment by taylorotwell** [comment]
Hello!

Could you send this to 6.x branch as well?

**Comment by sgilberg** [comment]
Gladly! https://github.com/laravel/framework/pull/30418 Thanks so much @taylorotwell appreciate all the good work you do

**Comment by sgilberg** [comment]
Would it be possible to include this in a 5.8.36 release?

**Comment by driesvints** [comment]
@sgilberg 5.8 isn't supported anymore unfortunately.

**Pull request merged**
