### PR TITLE
[5.3] Allow multiple folders for migrations

### PR DESCRIPTION
**Pull request by alexbowers**
Currently the tests are broken. Most should be simple to fix, I'll get onto this tomorrow.

### CODE REVIEW

**Comment by alexbowers** [comment]
Currently seeking feedback on the code structure. Will make all tests pass afterwards.

**Comment by philbates35** [comment]
From the looks of it this allows you to run something like `php artisan migrate --path=some/path --path=some/other/path`, but running `php artisan migrate` will only ever run migrations from the default path. I'd that right? In laravel/internals#68 the idea of being able for a "module" to register it's own migrations, meaning that `php artisan migrate` would run the migrations from multiple locations (for all registered modules) without you having to pass the additional parameters. IMO that would be even better.

**Comment by alexbowers** [comment]
@philbates35 You have this the wrong way around, the way it works is the way you would expect it to work.

Passing in `--path=..` will make it run _only_ that path, leaving path off, it will run all registered paths (by default, `database/migrations`). To register a new path, you would run something like `app('migrator')->path('/var/www/sites/laravel/vendor/alexbowers/module/database/migrations')`, and then the commands will all recognise the new set of migration files contained within the folder.

`migrate:status`, `migrate`, `migrate:rollback`, `migrate:reset` all work as expected in this regard, with no changes having been made at all to how the `--path` option works, other than to make the value an array so that the functions continue to work.

**Comment by philbates35** [comment]
Ah in that case this sounds excellent and gets a +1 from me

**Comment by thomasruiz** [comment]
This looks great. I'd suggest `Migrator` still accepts a single string as a path (convert it to an array if it's a string) to ensure backward compatibility.

**Comment by alexbowers** [comment]
I believe it still does, though I'll test it when I get back to my machine.
Can you see something I can't in my changes?

**Comment by alexbowers** [comment]
Ah sorry @thomasruiz I understand what you mean now. I'll look into doing that.

**Comment by alexbowers** [comment]
@taylorotwell Assistance with the remaining tests is required I think. Thanks.

**Comment by taylorotwell** [comment]
Is the main use case of this to break your own application's migrations up into multiple folders or to allow packages to expose migrations without exporting them?

**Comment by alexbowers** [comment]
I think both would be valid use cases, but my use case is the latter.

I am setting up a system where there will be a core system, and then modules can add into it. The usecase for me is that migrations can be exposed and ran without having be leave the modules directory.

It also makes maintainence a little easier, since when updating the module, I don't have to worry about which migrations may be new, and exporting them, I just have to run `migrate` and it'll work

**Comment by alexbowers** [comment]
Force-pushed current state squashed.

**Comment by Modelizer** [comment]
Can we do aliasing of a path? example `artisan migrate users` which will go to user module and run those migration in it.

**Comment by Modelizer** [comment]
@philbates35 @alexbowers idea is good but we need to right this code somewhere in our code `app('migrator')->path('/var/www/sites/laravel/vendor/alexbowers/module/database/migrations')` Cant we handle it from CLI? My idea is can we do aliasing of a path? example `artisan migrate --module=users` which will go to user module and run those migration in it.

**Comment by alexbowers** [comment]
@Modelizer With this current PR, you would have to have it defined somewhere in your code. For me, I put these inside of a service provider (ModulesServiceProvider). This would then work in the CLI as is.

```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class ModulesServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        app('migrator')->path('/path/to/migrations');
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}

```

I think in its current state, it would be better for the CLI interaction to be a separate feature / PR. What you want is more 'tagging' than modules.

@taylorotwell Thoughts?

**Comment by Modelizer** [comment]
@alexbowers Yes when we create a ServiceProvider we can also pass migration path as an option so that we don't need to add it manually. 

And yes i also agree CLI things should be push to another PR.

**Pull request merged**
