### PR TITLE
[8.0] Added reverse helper function to illuminate\Support\Stringable class

### PR DESCRIPTION
**Pull request by roni-estein**
This simply adds the reverse function to the Stringable class. I just assumed it was on there when reaching for it today, and it wasn't. It's my first time having a chance to contribute to the laravel framework, and this seemed like a small enough section to approach with confidence. The function itself is just a convenience function that wraps an existing php function that has a weird name.

### CODE REVIEW

**Comment by roni-estein** [comment]
not an assumption that this will be merged, just a question. It has a failing test, it looks like my IDE leaves indents on blank rows when hitting enter. Is that something that I would have to pull out and resubmit? Or does styleCI deal with that on its own.

Thanks!

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
Please update this to work with mbstrings.

**Comment by rodrigopedra** [comment]
For reference:

https://www.php.net/manual/en/function.strrev.php#125301

**Comment by roni-estein** [comment]
Thanks for the reference, I found it this morning, I was thinking of going with this. I was going to speed tests it first to see which solution was actually faster. But here are some tests to make sure everything worked with situations people had listed they had problems with in other situations.
```
collect([
  'foo/qux? foo/bar?',
  '火车票',
  '日、に、本、ほん、語、ご',
  'Hallöle',
  'Weiße Rosen sind nicht grün!'
])->map(function($item){
	return [$item => implode(array_reverse(preg_split('//u', $item , null, PREG_SPLIT_NO_EMPTY)))];
});
```

**Comment by roni-estein** [comment]
Yikes 10x slower! Just goes to show you perhaps don't believe what you see:

```
$time = -hrtime(true);
collect([
  'foo/qux? foo/bar?',
  '火车票',
  '日、に、本、ほん、語、ご',
  'Hallöle',
  'Weiße Rosen sind nicht grün!'
])->map(function($item){
	return [$item => implode(array_reverse(preg_split('//u', $item , null, PREG_SPLIT_NO_EMPTY)))];
})->dump();
$time += hrtime(true);
dump($time);


$time2 = -hrtime(true);
collect([
  'foo/qux? foo/bar?',
  '火车票',
  '日、に、本、ほん、語、ご',
  'Hallöle',
  'Weiße Rosen sind nicht grün!'
])->map(function($item){
  	$r = '';
    for ($i = mb_strlen($item); $i>=0; $i--) {
        $r .= mb_substr($item, $i, 1);
    }
    return [$item => $r];
})->dump();
$time2 += hrtime(true);
dump($time2);
```

timing:
```
Illuminate\Support\Collection {#1201
  #items: array:5 [
    0 => array:1 [
      "foo/qux? foo/bar?" => "?rab/oof ?xuq/oof"
    ]
    1 => array:1 [
      "火车票" => "票车火"
    ]
    2 => array:1 [
      "日、に、本、ほん、語、ご" => "ご、語、んほ、本、に、日"
    ]
    3 => array:1 [
      "Hallöle" => "elöllaH"
    ]
    4 => array:1 [
      "Weiße Rosen sind nicht grün!" => "!nürg thcin dnis nesoR eßieW"
    ]
  ]
}
4610453
Illuminate\Support\Collection {#1194
  #items: array:5 [
    0 => array:1 [
      "foo/qux? foo/bar?" => "?rab/oof ?xuq/oof"
    ]
    1 => array:1 [
      "火车票" => "票车火"
    ]
    2 => array:1 [
      "日、に、本、ほん、語、ご" => "ご、語、んほ、本、に、日"
    ]
    3 => array:1 [
      "Hallöle" => "elöllaH"
    ]
    4 => array:1 [
      "Weiße Rosen sind nicht grün!" => "!nürg thcin dnis nesoR eßieW"
    ]
  ]
}
477714
=> 477714
```
ran about 100x always seems the same.

**Comment by rodrigopedra** [comment]
Hi @roni-estein thanks for considering the reference I sent. 

From your benchmark code I noticed you didn't use the code from the linked difference.

On the comment I linked it used `mb_str_split` instead of `preg_split`, so I tested using a modified version from your benchmark:

~~~php
<?php
// ./routes/console.php

use Illuminate\Support\Facades\Artisan;

Artisan::command('app:reverse', function () {
    $test_preg_split = function ($string) {
        return \implode(\array_reverse(\preg_split('//u', $string, null, PREG_SPLIT_NO_EMPTY)));
    };

    $test_for = function ($string) {
        $reversed = '';

        for ($i = \mb_strlen($string); $i >= 0; $i--) {
            $reversed .= \mb_substr($string, $i, 1);
        }

        return $reversed;
    };

    $test_mb_str_split = function ($string) {
        $chars = \mb_str_split($string, 1, \mb_internal_encoding());

        return \implode('', \array_reverse($chars));
    };

    $inputs = [
        'foo/qux? foo/bar?',
        '火车票',
        '日、に、本、ほん、語、ご',
        'Hallöle',
        'Weiße Rosen sind nicht grün!',
    ];

    $tests = [$test_preg_split, $test_for, $test_mb_str_split];

    foreach ($tests as $test) {
        $output = [];
        $time = -\hrtime(true);

        foreach ($inputs as $input) {
            $output[] = $test($input);
        }

        $time += \hrtime(true);
        \dump($output, $time);
    }
});
~~~

The result:

~~~bash
$ php artisan app:reverse
36917
array:5 [
  0 => "?rab/oof ?xuq/oof"
  1 => "票车火"
  2 => "ご、語、んほ、本、に、日"
  3 => "elöllaH"
  4 => "!nürg thcin dnis nesoR eßieW"
]
15290
array:5 [
  0 => "?rab/oof ?xuq/oof"
  1 => "票车火"
  2 => "ご、語、んほ、本、に、日"
  3 => "elöllaH"
  4 => "!nürg thcin dnis nesoR eßieW"
]
7232
array:5 [
  0 => "?rab/oof ?xuq/oof"
  1 => "票车火"
  2 => "ご、語、んほ、本、に、日"
  3 => "elöllaH"
  4 => "!nürg thcin dnis nesoR eßieW"
]
~~~

The reason I modified your benchmark code was that at first I forgot to return a key/value pair from the `map` callback, and the `mb_str_split` results were a lot faster.

But I noticed the output was different and then I changed to return a key/value pair and it got worse than the `for`.

So I decided to test all of them returning the reversed string from the `callback` and the `mb_str_split` was faster again.

In my opinion, the chosen implementation might be the easier to maintain, so maybe the `for` approach wins at that criterion. 

Someone won't be reversing lots and lots of strings, so the difference in execution time should not be the "choice" reason. (sorry, could not find the word I want in English, hope that is clear).

If one person needs to squeeze performance for reversing lots and lots of strings, they can always write a custom function and use the most performant approach, which might be some other we are not considering here.

I like the `mb_str_split` approach better not because it seems to be the fastest one (in my machine at least), but because it could use a different encoding than the default. For example, the implementation from the link I sent accepts an optional encoding parameter:

~~~php
// https://www.php.net/manual/en/function.strrev.php#125301
function mb_strrev(string $string, string $encoding = null): string
{
    $chars = mb_str_split($string, 1, $encoding ?: mb_internal_encoding());
    return implode('', array_reverse($chars));
}
~~~

So the helper function could accept an `$encoding` parameter to take advantage of it. But as most of the helper methods from `Illuminate\Suppor\Str` doesn't take the encoding as a parameter, and as most people use `UTF-8` for web anyway, I don't think that should be a reason to choose that over the `for` which is a simpler and straightforward solution.

(By the way, the `Illuminate\Suppor\Str@length` method accepts an optional `encoding` parameter, but that is the only one in that class).

**Comment by roni-estein** [comment]
Hi @rodrigopedra, I opted to not use `mb_str_split`, which would certainly have been easier because it requires php 7.4. I wasn't sure, but in composer.json laravel 8 supports php 7.3 . As such on a standard install we wouldn't have access to that function. As for the speed test I wanted them to be equivalent, but also something you could throw into tinker or tinkerwell for quick visual verification. Contributing to a large project like this is new to me and I'm happy to learn and I appreciate your patience. I look forward to finding out how I could improve this, and make further contributions in the future.

**Comment by roni-estein** [comment]
Also that artisan command was a great idea! I'll use that going forward for new functionality tests. Thanks!

**Comment by sisve** [comment]
Keep in mind that the mbstring package works with code points, not characters, and there are issues if you start to move codepoints around. The [grapheme](https://www.php.net/manual/en/ref.intl.grapheme.php) functions work with characters, which is what people usually want when they are using the mbstring package. I realize that the Str functionality is already using mbstring, so this is more of an information message than an attempt to change this implementation.

Ref: How many characters is an Ö? https://3v4l.org/DUmSn

**Comment by rodrigopedra** [comment]
@roni-estein I didn't know it wasn't available before php 7.4, so maybe the `for` approach is the way to go.

@sisve didn't know about those functions, thanks for the heads up. I needed this a couple of weeks ago, ended up normalizing ( https://www.php.net/manual/en/normalizer.normalize.php ) the input before processing it. It is from the same the same extension (`intl`) I should have read the whole function index from that extension...

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by roni-estein** [comment]
@taylorotwell just a question, this is certainly not required functionality, and adds a maintenance burden. Is the structure of the pull request acceptable? Or is there a reference of a well structured pull request that we can refer to not the feature per se but the structure?

Thanks for your time.

**Comment by driesvints** [comment]
@roni-estein I'm guessing Taylor doesn't wants to maintain it at this time.

**Comment by roni-estein** [comment]
Hi dries I was only asking about the quality of the pr if it’s missing something or it was fine. If it wasn’t was there a reference. But I’ll look up some of the merged ones.   
  

  
  

  
  
>

**Pull request closed without merging**
