### PR TITLE
[5.7] Wrap a message of ValidationException with __()

### PR DESCRIPTION
**Pull request by hivokas**

### CODE REVIEW

**Comment by bonzai** [comment]
#21863
#22045
#23802

**Comment by hivokas** [comment]
Now it will work without foundation, but I'm not sure if it is the best solution.

**Comment by bonzai** [comment]
It's not.

If you really want to translate the exception message, you can make it in:

- `App\Exceptions\Handler\invalid()`
- `App\Exceptions\Handler\invalidJson()`

**Comment by taylorotwell** [comment]
Eh, no plans on adding this right now.

**Pull request closed without merging**
