### PR TITLE
[5.3] allow return full word in str_limit

### PR DESCRIPTION
**Pull request by emtudo**
$string='The PHP framework for web artisans.';

str_limit($string, 10, ''); //Result: The PHP fr
str_limit($string, 10, '', true); //Reuslt: The PHP

### CODE REVIEW

**Comment by lemesdaniel** [comment]
change mb_strpos to mb_strrpos it would be better

 $newLimit = mb_strpos($sentese, ' ', $limit);

So also respect the limit

**Comment by emtudo** [comment]
I think it wouldn't be better, because:
with mb_strrpos

$string='The PHP framework for web artisans.';

str_limit($string, 10, ''); //Result: The PHP fr
str_limit($string, 10, '', true); //Reuslt: The PHP framework for web

**Comment by emtudo** [comment]
I think it wouldn't be better, because:

with mb_strrpos($value, ' ', $limit);

$string='The PHP framework for web artisans.';

str_limit($string, 10, ''); //Result: The PHP fr
str_limit($string, 10, '', true); //Reuslt: The PHP fr
or
with mb_strrpos($sentence, ' ', $limit)
str_limit($string, 10, ''); //Result: The PHP fr
str_limit($string, 10, '', true); //Reuslt: The PHP framework for web

**Comment by emtudo** [comment]
now respect limit!

thanks @lemesdaniel

**Comment by emtudo** [comment]
now respect limit!

thanks @lemesdaniel

**Comment by taylorotwell** [comment]
You can write your own help if you need this functionality.

**Pull request closed without merging**
