### PR TITLE
[5.0] Automatically Resolve Migrations Dependencies

### PR DESCRIPTION
**Pull request by antonioribeiro**
This one is to automatically resolve:

```
class CreateUsersTable extends Migration {

    public function __construct(ClasName $class)
    {
        $this->class = $class;
    }

    ...
}
```

@GrahamCampbell, before you say anything, there was a bunch of spaces before Filesystem:

```
public function __construct(MigrationRepositoryInterface $repository,
                            Container $container,
                            Resolver $resolver,
                            Filesystem $files)
```

So I replaced them all with tabs.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I've kind of always avoided this as people can just use App::make from within a migration if they need anything from the container, and because one wouldn't typically unit test a migration.

**Comment by GrahamCampbell** [comment]
:( I really liked this idea. I hate using App::make in constructors. Feels really hacky.

**Comment by antonioribeiro** [comment]
Also, in my opinion, it's kind of confusing to see classes being autoresolved in some parts of Laravel and not in others. Newcomers might hit a wall until they understand some features aren't supposed to work everywhere.

**Comment by taylorotwell** [comment]
I just don't understand the point of dependency injecting migrations? Are
you ever really going to inject a mock into a migration?

**Comment by antonioribeiro** [comment]
People might need to inject classes to help their migrations to happen. Something that happened to me was a simple group of columns I needed in two different tables, so I did:

I have two (very similar) of those:

    <?php

    use PragmaRX\Support\Migration;
    use Illuminate\Database\Schema\Blueprint;
    use ConsultorioDigital\Services\Events\Database\Migrations\EventColumns;

    class CreateEventsLogTable extends Migration {

        /**
         * @var EventColumns
         */
        private $eventColumns;

        public function __construct(EventColumns $eventColumns)
        {
            $this->eventColumns = $eventColumns;
        }

        /**
         * Run the migrations.
         *
         * @return void
         */
        public function migrateUp()
        {
            Schema::create('events_log', function(Blueprint $table)
            {
                $table->string('id', 64)->primary();
                $table->string('original_event_id', 64)->index()->nullable();

                $this->eventColumns->create($table);
            });
        }

        /**
         * Reverse the migrations.
         *
         * @return void
         */
        public function migrateDown()
        {
            $this->drop('events_log');
        }

    }

and this is the common columns generator:

    <?php

    namespace ConsultorioDigital\Services\Events\Database\Migrations;

    use Illuminate\Database\Schema\Blueprint;

    class EventColumns {

        public function create(Blueprint $table)
        {
            $table->string('office_room_id', 64)->nullable();
            $table->timestamp('start')->index();
            $table->timestamp('end')->index();
            $table->boolean('all_day')->default(false);
            $table->string('title')->nullable();
            $table->text('description')->nullable();
            $table->string('user_id', 64)->nullable()->index();
            $table->string('client_id', 64)->nullable()->index();
            $table->string('frequency_id', 64)->nullable();
            $table->string('authorizer_id', 64)->nullable();
            $table->timestamp('authorized_at')->nullable()->index();
            $table->timestamp('completed_at')->nullable()->index();
            $table->string('completed_by_id', 64)->nullable();
            $table->string('room_financial_id', 64)->nullable()->index();
            $table->string('user_financial_id', 64)->nullable()->index();

            $table->timestamps();
        }

    }

Of course I could use inheritance or traits, but mind just went first with a common Laravel solution and it didn't worked.

**Comment by Anahkiasen** [comment]
Also something I often do is injecting migrations in other migrations. Say you add a new table that replaces an other one, in the new migration's down method I just call the old migration's up method to avoid to have to repeat the old structure's fields twice.

**Comment by franzliedke** [comment]
If I understand Taylor correctly, he's saying we don't need constructor injection here because that's only necessary if you want to unit test your classes - and you probably don't do so for migrations.

Since we already have te `Schema` facade in the migrations anyway, why not just use `App::make()` for locating your dependencies in the constructor. It's not quite that clean, but totally enough.

**Comment by antonioribeiro** [comment]
So if I'm understanding well, reversing your logic, one who doesn't unit test is not supposed to use constructor injection, and the new method injection, they are off limits? Sounds depressing, because those are fantastic Laravel features and everyone should be a allowed to use it. If you are trying to teach by example, it might not be the best didactic. 

I personally do not have a problem with this, every time I hit a wall I just extend the service and add what I need. I had to extend migrations to use transactions and rollback failed migrations (on PosgtreSQL), and also to be able to namespace, separate migrations per service and selectively enable them. But, when you expect people to have aha moments like "of course this feature is not supposed to work here, we don't inject mocks into migrations!", I fear exclusion and, in the future, docs may have to change a bit:

"PHP THAT DOESN'T HURT PROS"

**Comment by GrahamCampbell** [comment]
I agree. I inject dependencies even when I don't bother writing tests for
things.

**Comment by hannesvdvreken** [comment]
I believe you can always use `App::call` and `App::make`. It is not necessary to add a dependency on `illuminate/container` to every other Illuminate component just for the sake of having auto dependency injection everywhere. One can always use the facade and `App::wrap` to bring those features to every part of the application within the Laravel framework.

Wrote a blog post on this a couple of days ago. It's not finished but feedback is welcome. https://gist.github.com/hannesvdvreken/421784b60745bfa0cf03

**Comment by hannesvdvreken** [comment]
Also @GrahamCampbell, I love this comment:

    I really think laravel should just take the jump and move to PSR-2, and symfony style docblocks.

**Comment by mysteryos** [comment]
Just hit that bump. Went the typical DI fashion in migrations, ended with `App::make`.

It would create consistency within the laravel application to have DI supported in all app classes.

**Pull request closed without merging**
