### PR TITLE
[10.x] Vite custom cdn support

### PR DESCRIPTION
**Pull request by AmirHossein**
assetsUrl added to be able to pass custom cdn.
```blade
@vite('resources/sass/app.scss', assetsUrl: 'https://cdn.domain/assets')
```
to have output like this:
```html
<link rel="preload" as="style" href="https://cdn.domain/assets/app.c3369b22.css" />
<link rel="stylesheet" href="https://cdn.domain/assets/app.c3369b22.css" />
```

### CODE REVIEW

**Comment by timacdonald** [comment]
@AmirHossein can you not set the `ASSET_URL` environment variable? That is what the variable does already and it's intention.

**Comment by AmirHossein** [comment]
in my case, asset url is not static and resources are distributed to different servers. so it would be great to support such cases...

**Comment by ChrisB-TL** [comment]
This would be handy for multi tenant apps where the asset URL is determined dynamically.

**Comment by timacdonald** [comment]
Would you just do the following in your tenant "setup" to achieve this?

```php
Config::set('app.asset_url', '...some dynamic URL here based on the tenant...');
```

The `app.asset_url` config is not just used by Vite, so you would want that set property for all assets, right?

**Comment by ChrisB-TL** [comment]
> Would you just do the following in your tenant "setup" to achieve this?
> 
> ```
> Config::set('app.asset_url', '...some dynamic URL here based on the tenant...');
> ```
> 
> The `app.asset_url` config is not just used by Vite, so you would want that set property for all assets, right?

Ah, sorry, left out a key bit of info. We do the above for tenant subdomain assets. However, we serve bundles from our root domain.

We currently do this by registering a modified Illuminate\Foundation\Vite with assetPath() overriden - so this would just be a nice to have from an upgradability perspective rather than necessary for our use case.

**Comment by timacdonald** [comment]
Hey folks,

Would something like the following work for your needs?

```blade
<head>
    <!-- ... -->
    {{
        Vite::withEntryPoints(['resources/js/app.js'])
            ->createAssetUrlsUsing(function ($path) {
                // Custom logic here.
            });
    }}
</head>
```

I'm not sure the current proposed solution is how we want to handle this.

But could one of you also provide a bit more detail on why the feature is needed with the other things I've mentioned.

Still not quite sure I get the setup that actually requires this change. Thanks!

**Comment by ChrisB-TL** [comment]
That would work for our use case. 

For us, any assets unique to a tenant are served from the tenant's domain using the asset_url config. Vite bundles are on the root domain only (and are the only thing on the root domain), which we use a CDN for. So we only override the Vite asset path.

Amir's use case sounds different, though.

**Comment by AmirHossein** [comment]
Hi,
In my case, assets are managed in different level and provided via function in apps. So it is not static value.

We currently override assetPath method but asked for support officially.

As `$path` passed to the function i think `createAssetUrlsUsing` is enough.
Somethinbg like below:
```php
Vite::createAssetUrlsUsing(function ($path) {
    // Custom logic here.
})
```

**Comment by timacdonald** [comment]
Hey folks, I've created https://github.com/laravel/framework/pull/49437

Could you confirm this solves your problems. Note that it does not allow you to customize the "hot" path generation, i.e., when the dev server is running, only the built asset paths.

Let me know your thoughts.

**Pull request closed without merging**
