### PR TITLE
[5.5] bcrypt changed to Hash::make and renamed to str_hash :D

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Small change as requested in https://github.com/laravel/internals/issues/695

### CODE REVIEW

**Comment by m1guelpf** [comment]
@Dylan-DPC Maybe you should close this in favour of https://github.com/laravel/framework/pull/20155?

**Comment by Dylan-DPC** [comment]
no i could merge your changes in this PR?

**Comment by m1guelpf** [comment]
@Dylan-DPC Go ahead... or I can PR your PR :D

**Comment by fernandobandeira** [comment]
Maybe ``` hash_make ``` could be used instead? It would be closer to the ``` Hash::make ``` syntax so it could help ppl remember about it...

**Comment by m1guelpf** [comment]
@fernandobandeira Well, `str_hash()` is consistent with other str_* functions. I like it :smile:

**Comment by fernandobandeira** [comment]
Yep i get it just a suggestion...

**Comment by devcircus** [comment]
If the "str_hash" function is going to happen, why not add it alongside bcrypt for now, and change any core references to the new wording. 

This way users will be able to continue using bcrypt, but know it is deprecated. 

Personally don't see any reason to change at all just because something may be changing in 7.2.

**Comment by m1guelpf** [comment]
@devcircus I'd say that's Taylor decision. It has been suggested lots of times to trigger `E_DEPRECATED_ERROR` errors and deprecate instaed of remove, but as far as I know, it hasn't been done yet.

**Comment by devcircus** [comment]
Definitely Taylor's call. Just would be good to avoid needlessly breaking apps due to some possible future change.

**Comment by koenhoeijmakers** [comment]
Should just put a `@depricated` docblock by the `bcrypt()` helper and create `str_hash()` alongside it to prevent breaking applications i suppose?

**Comment by m1guelpf** [comment]
@koenhoeijmakers See [my comment above](https://github.com/laravel/framework/pull/20152#issuecomment-316420730).

**Comment by koenhoeijmakers** [comment]
Also, i'd suggest calling it `hasher()`, since any hasher class should implement the `HasherContract`, but thats my opinion.

@m1guelpf yea i just noticed :)

**Comment by joshmanders** [comment]
Lets give it some uniqueness and call it `hashbrowns($str)` because they are tasty.

**Comment by taylorotwell** [comment]
Don't remove the bcrypt method. I would just add the new method for now and we'll remove bcrypt helper in a later release.

**Comment by Dylan-DPC** [comment]
@taylorotwell fine i will add the bcrypt method again. Reopen? or create a new PR?

**Comment by m1guelpf** [comment]
@Dylan-DPC New PR.

**Comment by m1guelpf** [comment]
@taylorotwell How about deprecating bcrypt()?

**Pull request closed without merging**
