### PR TITLE
[9.x] Apply scopes for updateFrom

### PR DESCRIPTION
**Pull request by driesvints**
This PR implements updateFrom which got re-introduced in https://github.com/laravel/framework/pull/39151 in a similar way on the Eloquent Builder. This way, any global scope will be applied.

See https://github.com/laravel/framework/issues/44380

### CODE REVIEW

**Comment by peanutsmcgee** [comment]
I've run into an issue with bindings being incorrectly ordered here, using the following test case.
```
public function testUpdateFromMethodWithSubJoinsOnPostgres()
{
	$builder = $this->getPostgresBuilder();
	$builder->getConnection()->shouldReceive('update')->once()->with('update "users" set "email" = ?, "name" = ? from (select * from "orders" where "orders"."id" = 1) as "sub" where "name" = ? and "users"."id" = "sub"."user_id"', [1, 'foo', 'bar', 'baz'])->andReturn(1);
	$result = $builder->from('users')
		->joinSub(function ($q) {
			$q->from('orders')
				->where('orders.id', 1);
		}, 'sub', 'users.id', '=', 'sub.user_id')
		->where('name', 'baz')
		->updateFrom(['email' => 'foo', 'name' => 'bar']);
	$this->assertEquals(1, $result);
}
```



based off of `testUpdateFromMethodWithJoinsOnPostgres()` and `testJoinSub()` in `Illuminate\Tests\Database\DatabaseQueryBuilderTest.php`

The test is returning the bindings in the order `['foo', 'bar', 'baz', 1]` (notice the placement of the "1").

**Comment by driesvints** [comment]
Ow, I think I remember that we specifically didn't want global queries to apply here. I'm sorry but this isn't supported.

**Comment by peanutsmcgee** [comment]
@driesvints I've found a solution that's been working for what I need, using an overwritten `PostgresGrammar.php` file. I'm not sure if it's good enough for a PR, but I figured I'd share just in case it's useful to others.

In short, instead of re-ordering the bindings, we can re-order the `where` statements.
```
// this bit from your commit
public function updateFrom(array $values)
{
	return $this->toBase()->updateFrom($this->addUpdatedAtColumn($values));
}


// no longer needs the re-ordering of bindings, which makes it identical to prepareBindingsForUpdate()
// I could also just change the method updateFrom() in Builder.php, but it's convenient for me to keep my changes to a single file
public function prepareBindingsForUpdateFrom(array $bindings, array $values)
{
        return $this->prepareBindingsForUpdate($bindings, $values);
}


// same general idea as the original function, but places $joinWheres before $baseWheres
protected function compileUpdateWheres(Builder $query)
{
	$baseWheres = $this->compileWheresToArray($query); // method from Grammar.php

	$joinWheres = $this->compileUpdateJoinWheresToArray($query); // new method (alternative to compileUpdateJoinWheres())

	$allWheres = array_merge($joinWheres, $baseWheres);

	return $this->concatenateWhereClauses($query, $allWheres); // method from Grammar.php
}

// replacement method for compileUpdateJoinWheres()
// basically the same, just without imploding the results
protected function compileUpdateJoinWheresToArray(Builder $query)
{
	$joinWheres = [];

	foreach ($query->joins as $join) {
		foreach ($join->wheres as $where) {
			$method = "where{$where['type']}";

			$joinWheres[] = $where['boolean'] . ' ' . $this->$method($query, $where);
		}
	}

	return $joinWheres;
}

```

**Comment by driesvints** [comment]
Maybe yeah. I just remember a lot of apps broke last time we modified this method.

**Pull request closed without merging**
