### PR TITLE
[10.x] MySQL Grammar and Blueprint binary column fix

### PR DESCRIPTION
**Pull request by julesgraus**
The [Blueprint](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Schema/Blueprint.php) class has a ```binary``` method that creates a blob column in your database. 

I added a method called ```blob``` that creates a **blob** field in the database, and I did modify the ```binary``` method to create a **binary** field instead. 

I've also modified the ```typeBinary``` method in the [MySQLGrammar](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php) class so it returns **'binary'** instead of **'blob'** and added a ```typeBlob``` method that returns **'blob'**

As a finishing touch I've modified the ```testAddingBinary``` in [DatabaseMySqlSchemaGrammarTest.php](https://github.com/laravel/framework/blob/10.x/tests/Database/DatabaseMySqlSchemaGrammarTest.php) and added the ```testAddingBinary``` methods to ensure the quality.

### CODE REVIEW

**Comment by julesgraus** [comment]
Some background info on WHY I do want to fix this.

I am experimenting with EventSauce. An event sourcing package. It requires you to add [specific binary fields to your database table](https://eventsauce.io/docs/message-storage/repository-table-schema/). When I did use the binary method on the blueprint class, I was surprised I did get a blob field instead.

Of course one can fix this by executing raw statements, but I think this is less confusing if we solve it like this.

**Comment by hafezdivandari** [comment]
This is a breaking change. You may try this instead:

```php
Schema::table('test', function (Blueprint $table) {
    $table->char('binary_column', 16)->collation('binary');       // binary(16)
    $table->string('varbinary_column', 16)->collation('binary');  // varbinary(16)
    $table->tinyText('tinyblob_column')->collation('binary');     // tinyblob
    $table->text('blob_column')->collation('binary');             // blob
    $table->mediumText('mediumblob_column')->collation('binary'); // mediumblob
    $table->longText('longblob_column')->collation('binary');     // longblob
});
```

**Comment by crynobone** [comment]
@hafezdivandari 

Wouldn't it be useful if we can have `asBinary()` as a helper method? 

```diff
-$table->char('binary_column', 16)->collation('binary');
+$table->char('binary_column' 16)->asBinary();
```

**Comment by hafezdivandari** [comment]
@crynobone it would be MySQL / MariaDB specific modifier then. Alternatively, we can add `length` and `fixed` to `binary` on Laravel 11.x, it works for MYSQL, MariaDB and SQL Server that have `binary(n)` and `varbanary(n)`.

on `MySqlGrammar`

```php
/**
 * Create the column definition for a binary type.
 *
 * @param  \Illuminate\Support\Fluent  $column
 * @return string
 */
protected function typeBinary(Fluent $column)
{
    if ($column->length) {
        return $column->fixed ? "binary({$column->length})" : "varbinary({$column->length})";
    }

    return 'blob';
}
```

on `SqlServerGrammar`:

```php
/**
 * Create the column definition for a binary type.
 *
 * @param  \Illuminate\Support\Fluent  $column
 * @return string
 */
protected function typeBinary(Fluent $column)
{
    if ($column->length) {
        return $column->fixed ? "binary({$column->length})" : "varbinary({$column->length})";
    }

    return 'varbinary(max)';
}
```

**Comment by julesgraus** [comment]
Appending something to char would not be as easy as for example like adding a text column.

And you could see this as a breaking change, but this functionality in my point of view was broken anyway. Simply because calling the binary method, does not add a binary field to your database. Therefore I consider it a bug. And it only could break users websites after they migrate. Upgrading would not be good enough to break your site right?

**Comment by taylorotwell** [comment]
Not going to take any action on L10 with L11 so close to release (this week or next).

**Comment by julesgraus** [comment]
Ok. I will create the same kind of PR for Laravel 11.

**Pull request closed without merging**
