### PR TITLE
[9.x] Add equals methods to Collection

### PR DESCRIPTION
**Pull request by wimski**
I've created some helper methods for comparing Collections using the already present diff methods.

It's basically a short-hand for converting this...
```php
if (
    $collectionA->diff($collectionB)->isEmpty()
    && $collectionB->diff($collectionA)->isEmpty()
) {
    // do something if both collections contain the same values
}
```

...into this.
```php
if ($collectionA->equals($collectionB)) {
    // do something if both collections contain the same values
}
```

### CODE REVIEW

**Comment by wimski** [comment]
Why do the tests fail with PHP 8.2 on a test that is completely unrelated to my changes? :astonished:

**Comment by marcovo** [comment]
I suspect this implementation would falsely regard the arrays `['a', 'a', 'b']` and `['a', 'b', 'b']` to be equal. This points to an underlying fundamental problem: your implementation using `diff()`s is probably correct if the arrays represent two `Set`s, but for other data structures like lists or hashmaps, there will be different rules for what it means to be 'equal'; e.g. for lists you may expect the ordering within the arrays to be the same, for hashmaps you may want to ensure the same key/value pairs are present.

**Comment by wimski** [comment]
> I suspect this implementation would falsely regard the arrays `['a', 'a', 'b']` and `['a', 'b', 'b']` to be equal.

Ah yes, I totally missed that 🙈 

 > [...] for hashmaps you may want to ensure the same key/value pairs are present.

Isn't that what the 'assoc' version is for?

> While I think `equals()` methods could be useful, I think these nuances should be addressed first, and probably there are other edge cases as well that should be carefully examined.

You're quite right. I was too hasty with my implementation. Thanks for the review!

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
