### PR TITLE
[6.x] High Memory Use Fixes

### PR DESCRIPTION
**Pull request by ghost**
Related issue: https://github.com/laravel/framework/issues/31159

Can make a solution for output buffering disabling on downloading file?

### CODE REVIEW

**Comment by sebsel** [comment]
Oops, didn't look at it till after work and someone else fixed it already :D

I can confirm that the `ob_end_flush()` solution also solves the issue for me. Yaay for the tests.

**Comment by GrahamCampbell** [comment]
Thanks for the PR, but there's no way we can merge this fix because it ends the output buffer...

**Comment by GrahamCampbell** [comment]
This totally breaks Laravel's view system, and all other code that relies on output buffering.

**Comment by GrahamCampbell** [comment]
As you observed, your changes broke the tests, for the exact reason I just described.

**Comment by driesvints** [comment]
@GrahamCampbell do you have any ideas on how to solve the related issue?

**Comment by sebsel** [comment]
I was reading this wrong: I thought the solution I suggested, with `while` was breaking the changes. But it is the other way around it seems.

I can post my suggestion myself and see how that goes?

**Comment by driesvints** [comment]
@sebsel sure

**Comment by voyula** [comment]
@sebsel "while" is will not work because output buffering is active and output buffering will import all download data in memory before send to response.

@GrahamCampbell output buffering disabling for a download file, the one way to solve.

**Comment by sebsel** [comment]
FWIW just finished creating #31163.

@voyula How did you conclude `while` will not work? I have tested it, it solved the problem for me, and the test pass too. What test did you do that make `while` break?

**Pull request closed without merging**
