### PR TITLE
[5.1] Updated PsySH

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by rkgrep** [comment]
:+1: Finally it will work in 5.2

**Comment by GrahamCampbell** [comment]
Actually, 0.5 should already work since laravel 5.2 was changed to allow symfony 2.8 too.

**Comment by rkgrep** [comment]
It does, bu requires to implicitly add 2.8 dependency to composer.

**Comment by GrahamCampbell** [comment]
What?

**Comment by GrahamCampbell** [comment]
It should work out of the box.

**Comment by rkgrep** [comment]
That's why i opened issue in psysh before - symfony 3.0 is allowed in 0.5.2, but not supported. And during laravel installation 3.0 is installed by default as highest available version.

**Comment by GrahamCampbell** [comment]
> That's why I opened issue in psysh before

We've changed things since you opened that issue.

**Comment by GrahamCampbell** [comment]
You don't need symfony 3 anymore to use laravel 5.2.

**Pull request merged**
