### PR TITLE
[4.2] Correctly identify the end of a custom blade function

### PR DESCRIPTION
**Pull request by lonnylot**
The current regex returned from `BladeCompiler::createMatcher` finds the last `)` in the file. It should find the first one so we know when the function call ends.

### CODE REVIEW

**Comment by taylorotwell** [comment]
This will need a lot more tests to be merged. Things like this have been tried before and found broken later.

**Comment by lonnylot** [comment]
What types of things are you looking for their to be tests for? Things like new line characters?

**Comment by GrahamCampbell** [comment]
Perhaps 5.0 would be a better place for this? Surely people hitting this issues have fixed it some other way on 4.2, so might get their code broken by this change in behaviour.

**Comment by lonnylot** [comment]
Yesterday in IRC @taylorotwell gave the example of:
`@fiz(@biz(@bar('foo')))`

Given that example and knowledge of the current functionality I no longer think changing the regex is a good solution. I think that we would need some sort of parser. I'm going to close this PR for now and hopefully come up w/ an idea of what that might look like and ping you guys on laravel-dev to discuss it further.

**Pull request closed without merging**
