### PR TITLE
[5.1] Add missing dependency

### PR DESCRIPTION
**Pull request by lucasmichot**
We use Str:: functions in the Parser

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Maybe it should be a "suggest" instead?

**Comment by lucasmichot** [comment]
If we use the `illuminate/console` package out of a Laravel project, it will not work.
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Console/Parser.php#L5
I think `require` makes more sense

**Comment by GrahamCampbell** [comment]
The parser is only used if you're using commands with a signature, and most core commands don't.

**Comment by lucasmichot** [comment]
It would be confusing. Developer will refer to http://laravel.com/docs/5.1/artisan#writing-commands to use `illuminate/console`. Only the `$signature` part is documented, not the `getOptions` and `getArguments` functions

**Comment by GrahamCampbell** [comment]
Well it's not confusing if we litterally put in the suggest "Needed to parse command signatures.".

**Comment by GrahamCampbell** [comment]
Anyway, up to Taylor to decide. :)

**Comment by lucasmichot** [comment]
Indeed

**Pull request merged**
