### PR TITLE
[5.5] Add firstOrDefault Method

### PR DESCRIPTION
**Pull request by ahmed-aliraqi**
Add `firstOrDefault` method to eloquent builder

### CODE REVIEW

**Comment by decadence** [comment]
But for what? It's just wrapper.

**Comment by ahmed-aliraqi** [comment]
To avoid `Trying to get property of non-object` error exeption 

for example : 

```
User::whereId(555555)->first()->name 
```
will return error exeption 

-----
```
User::whereId(555555)->firstOrDefault()->name
```
will return null

**Comment by decadence** [comment]
I mean firstOrNew already handles that. Why do you need similar method with other name?

**Comment by ahmed-aliraqi** [comment]
If I use firstOrNew I must add an empty array to the first parameter

**Comment by a-komarev** [comment]
Maybe there is a need to change API of the `firstOrNew` method then instead of making another one method?

**Pull request closed without merging**
