### PR TITLE
[5.3] Add full width character forms to ascii table

### PR DESCRIPTION
**Pull request by fgambino**
Reference: http://www.fileformat.info/info/unicode/block/halfwidth_and_fullwidth_forms/list.htm

### CODE REVIEW

**Comment by fgambino** [comment]
Should the symbol characters be added too?

**Comment by GrahamCampbell** [comment]
Please send a PR to the stringy library. We don't accept changes to this in the framework. We just sync up with them.

**Comment by fgambino** [comment]
Ah okay, sorry about that

**Comment by GrahamCampbell** [comment]
np :)

**Pull request closed without merging**
