### PR TITLE
[8.x] @aware blade directive

### PR DESCRIPTION
**Pull request by inxilpro**
This is a re-submit of #39080 that makes the data from any components that are actively being rendered as well as parent components that haven't yet been rendered available to child components via the `@consume` directive:

```blade
{{-- menu.blade.php --}}
@props(['color'])
<ul>
  <x-menu-item color="orange">A</x-menu-item>
  <x-menu-item>B</x-menu-item>
  {{ $slot }}
</ul>

{{-- menu-item.blade.php --}}
@consume(['color' => 'red'])
<li>slot={{ $slot }}, color={{ $color }}</li>

{{-- Without setting color attribute, colors will be: orange, red, blue, red --}}
<x-menu>
  <x-menu-item color="blue">C</x-menu-item>
  <x-menu-item>D</x-menu-item>
</x-menu>

{{-- With setting color attribute, colors will be: orange, pink, blue, pink --}}
<x-menu color="pink">
  <x-menu-item color="blue">C</x-menu-item>
  <x-menu-item>D</x-menu-item>
</x-menu>
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
Heh, didn't know you were working on this again and actually just submitted a PR with another approach. 

Let me know what you think: https://github.com/laravel/framework/pull/39102/files

**Comment by inxilpro** [comment]
Hm. What do you expect the output of my tests to be? With your implementation, I'm expecting:

```html
<ul>
<li>slot=Inline child 1, color=orange</li>
<li>slot=Inline child 2, color=pink</li>
<li>slot=Default item 1, color=blue</li>
<li>slot=Default item 2, color=pink</li>
</ul>
```

But actually getting:

```html
<ul>
<li>slot=Inline child 1, color=orange</li>
<li>slot=Inline child 2, color=orange</li>
<li>slot=Default item 1, color=blue</li>
<li>slot=Default item 2, color=blue</li>
</ul>
```

It feels like you should be able to explicitly override consumed data. A use case may be:


```blade
<x-menu style="muted">
  <x-menu.item>About</x-menu.item>
  <x-menu.item>Contact</x-menu.item>
  <x-menu.item style="danger">Log Out</x-menu.item>
</x-menu>
```

**Comment by inxilpro** [comment]
@taylorotwell I just updated the tests. I tried to merge yours and mine together so that they covered all the possible cases. Let me know if you have an issue with that. I'll pull in the `flushComponent` bit shortly.

**Comment by inxilpro** [comment]
(I can't really think of any reasonable way to get around the `@props` issue. The parent's view **can't** be evaluated until its children are.)

**Comment by taylorotwell** [comment]
@inxilpro I don't think those are major issues. I personally would not add an `$aware` property at the moment. The `@props` default issue we will just have to document.

**Comment by driftingly** [comment]
@inxilpro are you able to update the name/description of this PR to match the `@consume` => `@aware` rename?

**Comment by thewebartisan7** [comment]
With component class you still use @aware directive in view right?

**Pull request merged**
