### PR TITLE
Fix pluck method in Eloquent Builder to support additional columns for mutations

### PR DESCRIPTION
**Pull request by niyazvpp**
This pull request fixes the issue where additional columns in the database come under mutations in the `pluck` method of a model. The changes include:

- Updated the `pluck` method to support specifying additional columns useful for mutations.
- Added new methods (All methods are partially/completely taken from `Illuminate\Database\Query\Builder`):
  - `stripTableForPluck`: Strips off the table name or alias from a column identifier.
  - `pluckFromObjectColumn`: Retrieves column values from rows represented as objects.
  - `pluckFromArrayColumn`: Retrieves column values from rows represented as arrays.

These changes ensure that the `pluck` method can handle additional columns correctly, maintaining the integrity of data when mutations are applied.

### Example Usage:

1. **Basic Usage Without Additional Columns:**

    ```php
    // Retrieve values from the 'name' column
    $results = Model::query()->pluck('name');

    // Output: Collection of values from the 'name' column
    ```

2. **Using a Key Without Additional Columns:**

    ```php
    // Retrieve 'name' values with 'id' as the key
    $results = Model::query()->pluck('name', 'id');

    // Output: Collection of 'name' values keyed by 'id'
    ```

3. **Using Additional Columns for Mutations:**

    ```php
    // Retrieve 'name' values with additional 'age' and 'status' columns
    $results = Model::query()->pluck('name', null, ['age', 'status']);

    // Output: Collection of 'name' values with mutations based on 'age' and 'status' columns
    ```

4. **Combining a Key with Additional Columns:**

    ```php
    // Retrieve 'name' values keyed by 'id', with additional 'age' column
    $results = Model::query()->pluck('name', 'id', 'age');

    // Output: Collection of 'name' values keyed by 'id' with mutations based on 'age' column
    ```

These examples demonstrate the flexibility of the enhanced `pluck` method, whether you're working with or without additional columns or keys. The enhancement ensures that the `pluck` method can handle complex scenarios involving mutations effectively.

### CODE REVIEW

**Comment by henzeb** [comment]
does the eloquent collection not support "[only](https://laravel.com/docs/11.x/collections#method-only)" ?

**Comment by niyazvpp** [comment]
@henzeb `pluck` retrieves specific columns directly from the database as key-value pair, while `only` filters attributes from an already-loaded collection. They serve different purposes.

**Comment by henzeb** [comment]
Ah, yeah, I saw pluck, I forgot to read "eloquent **builder**" my bad. but still, pluck on the collection is also on an already loaded collection, there is no only on the Builder.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

**Comment by niyazvpp** [comment]
> Thanks for your pull request to Laravel!
> 
> Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include.
> 
> If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

@taylorotwell Thanks for the reply. But,

1. I don't think there is enough code to justify a new package. Also, since `macro()` doesn't support overriding existing methods, I can't even overwrite it in my own project.

2. The current `pluck` method in Eloquent Builder already utilizes the `pluck` method from the base query builder, so it already includes the methods I added. I have streamlined some additional processes and checks related to mutations. We could consider creating a common trait for these methods if needed.

3. There's still no good, simple, and optimal solution for using `pluck` with columns that have mutations, even with collections. For example, consider situations where we need to use table names in a query due to joins directly or for relations:
   ```php
   $client_options = $user->clients()->pluck('clients.name', 'clients.id');
   // works without mutations
   
   $client_options = $user->clients->pluck('name', 'id');
   // (collection method) does work but selects all columns while querying, so not optimal.

   $client_options = $user->clients()
                          ->get(['clients.name', 'clients.display_name', 'clients.id'])
                          ->pluck('clients.name', 'clients.id');
   // Won't work because of table names in pluck
   // So, a simple `Builder::macro('pluckWithMutation', ...)` won't work.

   $client_options = $user->clients()
                          ->get([
                            'clients.name',
                            'clients.display_name', // mutation dependent
                            'clients.id'
                          ])
                          ->pluck('name', 'id');
   // Does work, but the developer has to manually remove table names

So, there's no good solution for cases where `pluck` needs additional columns for mutation purposes. That's where this PR is relevant.

**Pull request closed without merging**
