### PR TITLE
[5.4] Schedule on Weekends

### PR DESCRIPTION
**Pull request by alexbowers**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What's your use case for this please?

**Comment by alexbowers** [comment]
I have image processing that I only want to run weekend early mornings (to lessen the load on the servers).

So something like this may be used by me. (This isn't exactly what I do, but an example).

```php
$this->event->between('02:00', '06:00')->weekdays()->getExpression()
```

**Comment by GrahamCampbell** [comment]
As long as you have a use case that's fine. I was just guarding against adding it for the sake of it. :)

**Comment by alexbowers** [comment]
I currently do it in a somewhat messy way, so it is possible without this addition, but it requires the use of the `cron` method, and manually adding the `0,6` which is not ideal. Much less readable, and since we already have the `weekdays` figured `weekends` is the way it should be done. :)

**Comment by dani3l** [comment]
I've created a patch for carbon that deals with weekends on different countries
https://github.com/briannesbitt/Carbon/pull/380

Maybe you can implement something like that as well since weekends might not only be saturdays and sundays

**Pull request merged**
