### PR TITLE
[5.1] Use Str class instead of string helper functions

### PR DESCRIPTION
**Pull request by lucasmichot**
Avoid useless calls to an helper function which will call the Str function

---

Also related to #9273, #9310 and #9011

### CODE REVIEW

**Comment by a-komarev** [comment]
What is the best use case of helpers, in blade templates? Or it's better to avoid them at all?

**Comment by lucasmichot** [comment]
You can use them anywhere you want in your Laravel project.
But the framework itself should rely on the functions called by the helper, for performance reasons

**Comment by edenreich** [comment]
I agree @lucasmichot , although there are many places in the framework code that the functions are based on the helper function

**Comment by lucasmichot** [comment]
Well not in laravel/framework 5.4 anymore, only the `collect()` function is directly called

**Pull request merged**
