### PR TITLE
[5.0] Remove find method from the model class

### PR DESCRIPTION
**Pull request by JosephSilber**
It will defer to the builder class, like all other static methods.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Is this a bc break? What happens if someone calls parent::find? How does php deal with that?

**Comment by JosephSilber** [comment]
@GrahamCampbell I don't see how this could be a breaking change.

http://ideone.com/n8s2ob

**Comment by GrahamCampbell** [comment]
> I don't see how this could be a breaking change.

That's fine. I was just checking. Wanted to be 100% sure. :)

**Comment by mpociot** [comment]
Yes - this does brake a LOT of code!

**Comment by sschlein** [comment]
Unfortunately this is going break all my current Laravel 5 production applications (4) - I don't see any benefit in this change. Only work... :-1: 

At the moment, I'm not able to deploy code without breaking the production apps..

**Comment by JoostK** [comment]
This is interesting, as a [minimum example](http://3v4l.org/fNrk3) does not show such issues. I'm not saying we shouldn't revert, but I'd like to know what is happening differently for it not to work.

**Comment by taylorotwell** [comment]
Looks like we will have to revert this. Not surprised.

**Comment by taylorotwell** [comment]
Reverted in 5.0.16.

**Comment by JosephSilber** [comment]
@mreschke as shown by @JoostK's [simple example](http://3v4l.org/fNrk3), calling `parent::find` should send it through `__callStatic`.

How could it "cause infinite recursion"?

Can you share with us the exact error you get?

**Comment by JosephSilber** [comment]
@mpociot, @sschlein did you actually get an error, or you're basing it on @mreschke's experience?

**Comment by mpociot** [comment]
@JosephSilber Yes, I also got infinite recursion error.

In my case, I'm using the 3rd party package Ardent, which is extending the Eloquent Model and is calling `parent::find`, resulting in an infinite loop.

https://github.com/bart/ardent/blob/master/src/LaravelBook/Ardent/Ardent.php#L876

**Comment by JosephSilber** [comment]
@mpociot can you paste (or provide a screenshot) of the actual error you're getting?

**Comment by mreschke** [comment]
All of my models simply extend Illuminate\Database\Eloquent\Model as usual.  I always override find() to add caching, just like this

use Cache;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	public static function find($id, $columns = array('*'))
	{
		return Cache::remember(strtolower(get_class()).":$id", function() use($id, $columns) {
			return parent::find($id, $columns);
		});		
	}
}

I use nginx so my error is a 502 Bad Gateway.  If you add a simple dump('test'); just inside that find() function you will see your browser fill up with a million 'test' dumps then crash, so yes it is definitely calling itself.  I don't know why it isn't finding the other find() commands you moved around.

The quick fix for me was to change parent::find($id, $columns) to 
return parent::query()->find($id, $columns);

Which of course does call a (new static)...

**Comment by JosephSilber** [comment]
OK. Figured it out.

The call actually does get sent to `__callStatic`. Within `__callStatic` a new instance is created and we call *its* `find` method. Since the child class has a `find` method, it doesn't hit the `__call` method, which then just circles back to `__callStatic`.

Turns out @GrahamCampbell was right.

Sorry about this :disappointed:

**Comment by mreschke** [comment]
This quick response is dedication is one of the many reasons why me and my development team absolutely love laravel!  Thanks to guys!

**Comment by GrahamCampbell** [comment]
> Turns out @GrahamCampbell was right. Sorry about this :disappointed:

Really, lol.

**Pull request merged**
