### PR TITLE
[5.2] Add an `is` method to the Arr class

### PR DESCRIPTION
**Pull request by JosephSilber**
``` php
Arr::is(User::all()); // true
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Being ArrayAccess doesn't make something behave like an array.

I'd say it has to be both ArrayAccess and Traversable.

**Comment by JosephSilber** [comment]
> Being ArrayAccess doesn't make something behave like an array.

No, but it's close enough.

**Comment by GrahamCampbell** [comment]
I think it's a bit odd personally.

**Comment by taylorotwell** [comment]
Renamed to `accessible`.

**Pull request merged**
