### PR TITLE
[5.0] Removed Some Unused Imports

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by RomainLanz** [comment]
Maybe better to wait for PSR-2? `php-cs-fixer` will automatically remove unused imports.

**Comment by GrahamCampbell** [comment]
@RomainLanz I am actually using php-cs-fixer with https://styleci.io.

**Comment by GrahamCampbell** [comment]
> It's the same for the final dot.

I know - I actually wrote that fixer. :)

**Comment by GrahamCampbell** [comment]
I'll also be doing the PSR-2 migration. I've been working on this for a long while now, lol. PHP-CS-FIXER has ~10 new fixers that I've written to help us including https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/887.

**Comment by GrahamCampbell** [comment]
Also, if you're interested, the fixers Laravel will be using are here: https://github.com/StyleCI/Config/blob/0ffe60da8835558f00b999e896c5aee27121e8ee/src/Config.php#L219. NB, this list is still subject to change.

**Comment by RomainLanz** [comment]
Wow, very nice!

Thanks @GrahamCampbell!

**Comment by overtrue** [comment]
:+1: nice!

**Pull request merged**
