### PR TITLE
[5.1] Remove unused alias

### PR DESCRIPTION
**Pull request by KennedyTedesco**

### CODE REVIEW

**Comment by lukasgeiter** [comment]
Maybe I'm missing something but isn't this a BC break? What if someone uses `app('paginator')` in their code?

**Comment by franzliedke** [comment]
True.

**Comment by GrahamCampbell** [comment]
The Factory class doesn't exist anyway though.

**Comment by lukasgeiter** [comment]
>The Factory class doesn't exist anyway though.

Nice one. So people using `app('paginator')` would have gotten a class not found exception, right?

**Comment by GrahamCampbell** [comment]
Something like that, yeh.

**Pull request merged**
