### PR TITLE
Return 0 from average when the collection is empty

### PR DESCRIPTION
**Pull request by JosephSilber**
Seems more logical to me.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by taylorotwell** [comment]
Eh, it doesn't seem more logical to me. Now I have on way to differentiate that the collection was empty from the average actually being zero.

**Comment by GrahamCampbell** [comment]
Or maybe we should just divide by zero if it's empty...

**Comment by GrahamCampbell** [comment]
And let people deal with the error from php.

**Comment by GrahamCampbell** [comment]
Since you can't take an average of an empty set.

**Comment by JosephSilber** [comment]
@taylorotwell the average of no items *is* 0.

If you want to know whether the collection is empty, call `isEmpty` yourself.

**Comment by taylorotwell** [comment]
Disagree.

**Comment by taylorotwell** [comment]
Or do I. Damn.

**Comment by taylorotwell** [comment]
SQL AVG() on no results returns null.

**Comment by GrahamCampbell** [comment]
lol - maybe sleep on it ;)

**Comment by JosephSilber** [comment]
I'm thinking of it from a use-case perspective. I can't think of a reason you'd ever *not* want a predictable float/int returned.

**Comment by HipsterJazzbo** [comment]
FWIW, I had it return 0 in the first iteration, and someone convinced me to change it. I'm wishy-washy.

**Pull request closed without merging**
