### PR TITLE
[5.1] Let collection handles Jsonable items

### PR DESCRIPTION
**Pull request by lucasmichot**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please avoid mixed.

**Comment by GrahamCampbell** [comment]
Just add `Jsonable` to the list of allowed types.

**Comment by lucasmichot** [comment]
I think this is the typical use case where `mixed` should be used as these function accepts any kind of argument, as at the very end this argument will be converted to an array.

**Comment by GrahamCampbell** [comment]
Hmmm, that's true.

**Pull request merged**
