### PR TITLE
[5.7] Add Schedulable Feature

### PR DESCRIPTION
**Pull request by davidpiesse**
After requiring a model that needs to be individually scheduled (think Basecamp Check-in) I built a trait that uses existing Laravel logic.

This extends this into a core trait, a new Schedule Event class (similar to CallbackEvent) and one additional method on Schedule 'use'.

A Schedulable model/class can now be added to the schedule with
```php
$schedule->use(Checkin::class);
```
Behind the scenes it create a schedule event that runs every time and checks if anything needs to be run.

I have held off a significant refactoring of the Schedule Event system as it works great as is except for in this instance.

### CODE REVIEW

**Comment by davidpiesse** [comment]
Relates to laravel/internals#1024

**Comment by sisve** [comment]
There's some formatting changes in the Schedule.php file that aren't wrong, but shows up as changes in the PR. These changes does not seem to be necessary for the functionality. Perhaps remove them so the PR only contains relevant changes?

**Comment by davidpiesse** [comment]
Blame my parents code formatter!
I have a pending commit to reverse these!
Thanks,
David

**Comment by taylorotwell** [comment]
Can you provide some more examples of how this used. The one code example doesn't give very much information on what this is doing. Thanks.

**Comment by davidpiesse** [comment]
Doh! Forgot the link to the article (if at all interested) [Link](https://medium.com/@piesse/laravel-user-defined-scheduling-%EF%B8%8F-9775e861a034)
The use cases would be whenever a user / custom schedule is required for each object in a collection (i.e. item in a model array) such as:
- Basecamp Checkin Notification (user defines the schedule) (I got the idea from your and Adam's recent Twitter posts)
- User Custom Timezones - consistent schedule but where each user's timezone differs
- Differing Frequencies (Oh Dear app user defined interval)

Effectively it replaces the following common use case code
```php
$schedule->call(function () {
    Checkin::all()->each(function($checkin){
        if($checkin->isDue()){
            $checkin->doSomething();
        }
    });
})->everyMinute();
```
Note: isDue() is considered to be equivalent to that use in [Schedule\Event](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Console/Scheduling/Event.php#L270).

**Comment by laurencei** [comment]
It kind of feels that your pushing the scheduling logic into the model, and abstracting it out of the scheduler itself. The whole reason we have the scheduler file currently - it is very obvious and clear what is scheduled and when.

But my concern is about the mutuxes. You've pushed them into the trait, so each model has it's own mutex. But how does that work with the custom frequencies and single description? I think there might be issues, but I need to play around with it.

@taylorotwell - if your going to consider merging this - can I at least have the weekend to test it? I'm super busy today and tomorrow - but I can play around with it over the weekend and test.

> User Custom Timezones - consistent schedule but where each user's timezone differs

This is *really* going to end in unexpected behavior. The use of scheduling inside timezones that have day light savings always triggers strange behavior when those daylight savings start/end. i.e. some jobs will run twice as often, and some will never run. The optimal behavior is always schedule in UTC (perhaps with an "offset" to determine if you want it to run at a specific time of day).

**Comment by davidpiesse** [comment]
Hey @laurencei, 
Totally agree that it moves scheduling logic away from the scheduler into models/classes- but that is essential in these use cases (and why it differs from the current method).

This approach allows you to consistently define schedules (cron expressions) for a class rather than custom implementations. As a bonus you get the ManagesFrequencies methods 

RE: Mutex's - It works exactly the same as a Callback event, including mutex's (to the point where there maybe should be a class that Callback Event, this and the Job method all extend from).
There is only one mutex per Class that is added (used) rather than per individual model.
It is in essence a wrapper of a predefined callback, that rather than taking a callback takes a class instead.

As for timezones - offsets are imo usually bad idea - and timezones a better implementation for overall consistency. Offsets are easy to store and understand but they are affected by daylight saving in so many ways they fail to be correct for some periods of a year.
For example CST in the US is currently UTC-6 but in a couple of weeks it turns to UTC-5. Ideally you set it to a sub-defined tz such as America/Chicago (auto changes).

**Comment by taylorotwell** [comment]
I think the idea is pretty neat but going to hold off on including it in the core of the framework for now.

**Comment by davidpiesse** [comment]
Ok! Thanks.

**Comment by laurencei** [comment]
> For example CST in the US is currently UTC-6 but in a couple of weeks it turns to UTC-5

And when you schedule a daily task to run at CST of 02:30 - and the daylight savings changes, this process is run twice in a hour (when the clocks go back an hour), or not at all (when the clocks go forward an hour and skip). Hence the problems :)

**Comment by davidpiesse** [comment]
CST will not change with daylight saving - it just has a UTC offset (-6).
If you want to employ daylight savings you must use a locale based timezone
(America/Chicago) which will auto change to daylight savings. You are right
you might get double notifications in those two hours a years (one at each
end) BUT you do use daylight saving correctly.

**Comment by WebMedic-X** [comment]
Hello, hope all is well!

Found this from @davidpiesse article and not sure if it was ever added to Laravel?

**Pull request closed without merging**
