### PR TITLE
[5.4] Blade parenthesis parse fix

### LINKED ISSUE #18317: Blade parenthesis parse issue
- Laravel Version: 5.4.12
- PHP Version: 7.0.15
- Database Driver & Version:

### Description:

in my template i use

```
@section('title', 'Hello :)')
```

which results in error:

```
Parse error: syntax error, unexpected '?'
```

### PR DESCRIPTION
**Pull request by andkom**
fix blade expression parsing like: 

```
@section('content', '\'test\' ":)"')
```
#18317

### CODE REVIEW

**Comment by tillkruss** [comment]
Did you by any chance compare the regexp speed before and after your change?

**Comment by andkom** [comment]
Quick test showed that new regexp is about 2 times slower than old. Is that critical?

**Comment by ConnorVG** [comment]
Two times slower? That's unreal.

**Comment by taylorotwell** [comment]
It's impossible to correctly cover all cases of this kind of parsing with regex. This has been covered in many other GitHub threads.

**Pull request closed without merging**
