### PR TITLE
[9.x] Prettify the event:list command

### PR DESCRIPTION
**Pull request by imanghafoori1**
The current form of printing a table for showing events/listeners is very sensitive to the width of the command line. In this form, we can survive much smaller screens.
- It also indicates which listener implements the `ShouldQueue` and `ShouldBroadcast` interface.

image

The new output is responsive to the width of the terminal window and trims the long lines.

image

You may change the text and color to your liking.

-----------------

- This is the before, which has problems when an event has more than one listener:

image

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is a breaking change, no?

**Comment by imanghafoori1** [comment]
- Yeah, to some level, the `protected` method may be overridden, but that is very unlikely.
- We can change it to be fully backward compatible if needed.

**Comment by GrahamCampbell** [comment]
I also meant the fact that the output was changing.

**Comment by driesvints** [comment]
@GrahamCampbell I personally don't consider that part of the public API but let's see what Taylor says.

**Comment by taylorotwell** [comment]
Personally I'd like to see the formatting be a bit more in line with `route:list` in terms of how listeners are displayed below the events, etc. so it feels consistent. Maybe @xiCO2k would be willing to help?

**Comment by xiCO2k** [comment]
Actually I did start a PR for that, will find the time to finish it

**Comment by xiCO2k** [comment]
Also @imanghafoori1 let me know if you want to match the look with route:list on this PR.

**Comment by imanghafoori1** [comment]
no problem, I will try to make it consistent to night,

**Comment by xiCO2k** [comment]
Awesome @imanghafoori1, if you need any help, let me know ;)

**Comment by imanghafoori1** [comment]
@xiCO2k Thank you very much, currently working on it, and I will push the results an hour or so.

**Comment by imanghafoori1** [comment]
With the push of the second commit, I am done.  \\(^_^)/

**Comment by taylorotwell** [comment]
@xiCO2k can you share what your version looked like?

**Comment by xiCO2k** [comment]
I was trying 3 different looks

First:
Screen Shot 2022-04-20 at 19 40 24

Second:
Screen Shot 2022-04-20 at 19 44 55

Thrid:
Screen Shot 2022-04-20 at 19 47 23

I think what fits the best is the first one, but not sure how it should look when there is more than 1 listener.

Let me know what you guys think.

**Comment by taylorotwell** [comment]
Personally I like the third one best... with an empty line added in between new events to give it a bit more breathing room. 👍

**Comment by xiCO2k** [comment]
I can PR that style change, and then @imanghafoori1 after the merge can PR those cool additions to show `ShouldQueue` and stuff like that.

What do you guys think? 
@taylorotwell @imanghafoori1

**Comment by imanghafoori1** [comment]
@xiCO2k I have no idea, actually.

**Comment by taylorotwell** [comment]
@xiCO2k sure go ahead and send over your style change.

**Pull request closed without merging**
