### PR TITLE
Add Persian characters in Str::charsArray()

### PR DESCRIPTION
**Pull request by behzadsh**
Add Persian characters and missing Arabic characters to Str::charsArray()

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please send this to the stringy library. I will periodicity sync us up with them.

**Comment by behzadsh** [comment]
I also create a [pull request](https://github.com/danielstjules/Stringy/pull/115) for stringy.
I don't understand why you reject this, when you don not use that library directly

**Comment by crynobone** [comment]
Yeah, should just wait for Stringy to merge this and then do the same here. It's still is @behzadsh contribution.

**Comment by GrahamCampbell** [comment]
Not going to happen since we're already out of sync with stringy.

**Comment by ahmadina** [comment]
@behzadsh +1

**Comment by GrahamCampbell** [comment]
The next time stringy does a release, I'll sync up with it.

**Comment by ra3oul** [comment]
@GrahamCampbell  come on men why you are trying to be hero gozo khan

**Comment by ahmadina** [comment]
@GrahamCampbell I agree with @ra3oul, you are not a laravel hero for us, don't try!

**Comment by jafaripur** [comment]
@GrahamCampbell Your work and speaking is not acceptable for merging policy in open source world!

**Comment by GrahamCampbell** [comment]
I'm a bit confused what you're talking about? This PR will only make it into the core when it goes into stringy, in the same way that code only goes into our 5.2 by automatic merge from 5.1.

**Comment by GrahamCampbell** [comment]
I'll retain the commit authors when possible, in the same way I cherry-pick changes when merging PRs targeted to the wrong branch. No further discussion is required here.

Consider this code to be read only, like all our illuminate components.

**Comment by mhndev** [comment]
it should be clear who has committed.
it's not true just get the code and commit yourself.
it's about being selfish.

**Comment by GrahamCampbell** [comment]
@mhndev At no point did I say I would be doing that!

**Comment by jafaripur** [comment]
@ahmadina Laravel is cheap framework and person is not hero, the framework should be hero.

**Comment by GrahamCampbell** [comment]
Locking this because the conversation has strayed away from the PR. When stringy releases, laravel will sync up. Commit authors WILL be retained.

**Comment by GrahamCampbell** [comment]
@behzadsh Thank you for your contribution, it's much appreciated. It's a shame your PR got hijacked.

**Comment by GrahamCampbell** [comment]
This PR is also impossible to merge into laravel as is due to merge conflicts with https://github.com/danielstjules/Stringy/commit/b85a84d0b91e6940edaa183b2f73714998450a51.

**Pull request closed without merging**
