### PR TITLE
[5.1] Guard : remove useless curly brackets

### PR DESCRIPTION
**Pull request by lucasmichot**
Remove useless curly brackets

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
These are not useless.

**Comment by GrahamCampbell** [comment]
Oh right, this is a mess because the if statement is missing braces. Could you put all braces in please?

**Comment by lucasmichot** [comment]
sure @GrahamCampbell

**Comment by lukasgeiter** [comment]
@GrahamCampbell You mean like #8805?

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by taylorotwell** [comment]
If it's not broken, don't fix it.

**Pull request closed without merging**
