### PR TITLE
[5.3] Resolve the current path by default for the LengthAwarePaginator

### PR DESCRIPTION
**Pull request by themsaid**
If no path provided to the paginator we'll resolve it from the request by default.

In reference to: https://github.com/laravel/framework/issues/15562

### CODE REVIEW

**Comment by taylorotwell** [comment]
Looks like tests are failing here

**Comment by GrahamCampbell** [comment]
Test need updating. :)

**Comment by garygreen** [comment]
Just a few things, I think `resolveCurrentPath` should always be called with the user-supplied path, or default one.

```php
    /**
     * Resolve the current request path or return the default value.
     *
     * @param  string  $default
     * @return string
     */
    public static function resolveCurrentPath($default = '/')
    {
        if (isset(static::$currentPathResolver)) {
            return call_user_func(static::$currentPathResolver);
        }

        return $default != '/' ? rtrim($default, '/') : $default;
    }
``

Then it can become:

```php
        $this->path = $this->resolveCurrentPath($this->path);
```

**Comment by garygreen** [comment]
Also the same needs to happen to `Paginator.php`

**Comment by garygreen** [comment]
Can also then remove supplying the path from the query builder paginate. `Paginator::resolveCurrentPath()` from [`Database\Eloquent\Builder`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Builder.php#L484)

**Comment by themsaid** [comment]
`$this->resolveCurrentPath($this->path)` will always return the resolved path and neglect user provided one since there's always a resolver added by the pagination service provider.

For the paginator change I think yes it needs to be changed as well.

**Comment by garygreen** [comment]
Maybe it could become:

```php
    /**
     * Resolve the current request path or return the default value.
     *
     * @param  string|null  $default
     * @return string
     */
    public static function resolveCurrentPath($default = null)
    {        
        if (is_null($default) && isset(static::$currentPathResolver)) {
            return call_user_func(static::$currentPathResolver);
        }

        if (is_null($default)) {
            $default = '/';
        }

        return $default != '/' ? rtrim($default, '/') : $default;
    }
```

That way the custom resolver is only called if a path wasn't explicitly supplied.

**Comment by garygreen** [comment]
```$default = '/';`` maybe should be ```$default = $this->page``` but thought that looked a bit weird.

**Comment by themsaid** [comment]
@garygreen that might be a breaking change :)

**Comment by garygreen** [comment]
@themsaid yeah it maybe, it's nice though 😄 

Your current version has a slightly different behavouir for `/` at the moment. Imo it should be:

```php
$this->path = is_null($this->path) ?
    $this->resolveCurrentPath() :
    ($this->path != '/' ? rtrim($this->path, '/') : $this->path);
```

**Comment by garygreen** [comment]
Hmm no forget that, your version does make sense. Though what if you wanted to force it to use `/` without calling the custom resolver? At the moment not possible...?

**Comment by taylorotwell** [comment]
This is really a breaking change since now you can no longer pass `/` explicitly. @garygreen i suggest just manually passing in the path you want in the options to the paginator. If needed we can update the documentation to make this clearer.

**Comment by garygreen** [comment]
It is breaking yeah so should go in 5.4. The paginator is very inconsistent with the paths at the moment imo. You shouldn't need to specify the path resolver, it should call internally itself if no path was given.

**Pull request closed without merging**
