### PR TITLE
Added ability to use Redis Sentinel configuration

### PR DESCRIPTION
**Pull request by mingalevme**
These changes make it possible to use Redis Sentinel with Laravel/Lumen and Predis, configuration example:
```
return [
   // ...
    'redis' => [
        'client' => 'predis',
        'sentinel' => [
            'tcp://10.24.5.136:26379?timeout=0.100',
            'tcp://10.24.5.137:26379?timeout=0.100',
            'tcp://10.24.5.138:26379?timeout=0.100',
            'options' => [
                'replication' => 'sentinel',
                'service' => env('REDIS_SENTINEL_SERVICE', 'mymaster'),
                'parameters' => [
                    'password' => env('REDIS_PASSWORD', null),
                    'database' => 0,
                ],
            ],
        ],
    ],
];
```
It's very important to call Arr::pull($config, 'options', []) before passing it to Client.

### CODE REVIEW

**Comment by s-hamid** [comment]
> These changes make it possible to use Redis Sentinel with Laravel/Lumen and Predis, configuration example:
> 
> ```
> return [
>    // ...
>     'redis' => [
>         'client' => 'predis',
>         'sentinel' => [
>             'tcp://10.24.5.136:26379?timeout=0.100',
>             'tcp://10.24.5.137:26379?timeout=0.100',
>             'tcp://10.24.5.138:26379?timeout=0.100',
>             'options' => [
>                 'replication' => 'sentinel',
>                 'service' => env('REDIS_SENTINEL_SERVICE', 'mymaster'),
>                 'parameters' => [
>                     'password' => env('REDIS_PASSWORD', null),
>                     'database' => 0,
>                 ],
>             ],
>         ],
>     ],
> ];
> ```
> 
> It's very important to call Arr::pull($config, 'options', []) before passing it to Client.

What will be the default key settings?

**Comment by CharlesBilbo** [comment]
In case anyone is visiting this in 2021 this is the appropriate config to get redis sentinel working with your application

Additionally at this time you need to use the dev-master branch of predis and not the current version (1.1.7) as this version hard sets the password to null.

`'redis' => [

        'client' => env('REDIS_CLIENT', 'predis'),

        'default' => [
            'tcp://127.0.0.1:26379?timeout=0.1',
            'tcp://127.0.0.1:26379?timeout=0.1',
            'tcp://127.0.0.1:26379?timeout=0.1',
        ],

        'options' => [
            'replication' => 'sentinel',
            'service' => 'mymaster',
            'parameters' => [
                'password' => env('REDIS_PASSWORD'),
                'database' => 0,
            ],
        ],
    ];`

**Comment by skiat** [comment]
Let me conribute with another working config (running in 2022 with laravel 8.x)

This includes "private" options that allows to choose different database id and prefix, which is very important in case of shared redis instances.

_config/database.php_
```php
<?php

return [
//...
   'redis' => [
       'client' => 'predis',

       'default' => [
             'tcp://' . env('REDIS_HOST') . ':' . env('REDIS_PORT') . '?timeout=0.1',
             'tcp://' . env('REDIS_HOST_n') . ':' . env('REDIS_PORT') . '?timeout=0.1',
             'options' => [
                  'replication' => 'sentinel',
                  'service' => 'mymaster',
                  'parameters' => [
                       'password' => env('REDIS_PASSWORD'),
                       'database' => env('REDIS_DB', 0)],
                       'prefix' => 'myapp:',
       ],

       'cache' => [
             'tcp://' . env('REDIS_HOST') . ':' . env('REDIS_PORT') . '?timeout=0.1',
             'tcp://' . env('REDIS_HOST_n') . ':' . env('REDIS_PORT') . '?timeout=0.1',
             'options' => [
                  'replication' => 'sentinel',
                  'service' => 'mymaster',
                  'parameters' => [
                       'password' => env('REDIS_PASSWORD'),
                       'database' => env('REDIS_CACHE_DB', 1)
                       'prefix' => 'myappcache:',
                  ],
             ]
        ],
   ],
];
```

**Comment by DreadfulCode** [comment]
Thanks @skiat  but your example appears to be broken. Was this tested locally first? and is there a closing bracket missing?

**Comment by CharlesBilbo** [comment]
@DreadfulCode Yeah seems like there is a closing bracket missing @Olayiwola72 Each TCP address in that array is a different redis sentential server. instance they way sentinel works is their one main server and 2 observers.

**Comment by skiat** [comment]
> Thanks @skiat but your example appears to be broken. Is there a closing bracket missing for 'default.parameters'?

Thanks, yes, I fixed my comment.
Cheers

**Comment by LyKos4** [comment]
Does it work with phpredis too? Also can we use it for default, cache and others that are using different redis databases so that all use sentinel?

**Comment by skiat** [comment]
> Does it work with phpredis too? Also can we use it for default, cache and others that are using different redis databases so that all use sentinel?

Hi LyKos4
unfortunately not. And also this with predis is no more applicable since laravel 10.
see https://github.com/monospice/laravel-redis-sentinel-drivers as replacement

**Comment by LyKos4** [comment]
> > Does it work with phpredis too? Also can we use it for default, cache and others that are using different redis databases so that all use sentinel?
> 
> Hi LyKos4 unfortunately not. And also this with predis is no more applicable since laravel 10. see https://github.com/monospice/laravel-redis-sentinel-drivers as replacement

So from version 10, laravel doesn't support sentinel usage without additional packages, right?
Unfortunately monospice has below limitation:
"For instance, if we wish to use Redis behind Sentinel for both the cache and session in Laravel's API, we cannot set separate Redis databases for for both types of data like we can in a standard, single-server Redis setup without Sentinel. This causes issues when we need to clear the cache, because Laravel erases stored session information as well. "

**Pull request merged**
