### PR TITLE
[9.x ] Updated Mailable to prevent duplicated recipients

### LINKED ISSUE #45042: Duplicate replyTo when running render() prior to send
- Laravel Version: 9.40.1
- PHP Version: 8.1.10
- Database Driver & Version: not relevant

### Description:
If you run `render()` prior to sending the email, it will double `replyTo`.
A bit related to #30857

### Steps To Reproduce:

The below example will add `info@example.com` 2 times to the reply_to field.
```
use App\Mail\Question;

$mailTemplate = new Question( 'Hello, I have a question' );
$mail = $mailTemplate->render();
// ...store $mail in the database

Mail::to( config( 'mail.from.address' ) )
    ->locale( 'nl' )
    ->send( $mailTemplate );
```

```
<?php
namespace App\Mail\Patient;

use App\Models\Patient;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class Question extends Mailable implements shouldQueue
{
    use Queueable, SerializesModels;

    /**
     * Create a new message instance.
     *
     * @param Patient $patient
     * @param string  $question
     */
    public function __construct( public string $question )
    {
        $this->queue = config( 'config.queue-email' );
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->from( [
            'address' => config( 'mail.from.address' ),
            'name'    => config( 'mail.from.name' ),
        ] )
                    ->replyTo( 'info@example.com' )
                    ->subject( 'someone has a question' )
                    ->view( 'mail.question' );
    }
}
```

### PR DESCRIPTION
**Pull request by WendellAdriel**
As discussed on #45042 these changes prevent the use of duplicated recipients in the `to`, `from`, `cc`, `bcc` and `replyTo` properties of the mailable.

### CODE REVIEW

**Review by driesvints — APPROVED** [review]
This *looks* okay to me. At least worth a try.

**Comment by WendellAdriel** [comment]
Thank you so much @driesvints!!!

**Comment by taylorotwell** [comment]
But now these tests no longer check that two "to" addresses can actually be added.

**Comment by WendellAdriel** [comment]
That’s true @taylorotwell, sorry!
I’ll update the tests and the PR ASAP

**Comment by AAllport** [comment]
It looks like this may have introduced a bug/breaking change...

If you have the following: `Mail::to($recipient)->send(new FooMail($recipient))`
You can no longer set the "name" of the recipient in the build method when calling `->to($reciepent->mail, $recipient->full_name)`

It looks like the call to `->unique()` is removing the instance of the address with the name.

Was this intended behaviour?
It feels like if you are calling `->to()`, then the most recent addition should take priority.

**Pull request merged**
