### PR TITLE
[5.6] Paginators should be built from Contracts

### PR DESCRIPTION
**Pull request by grashoper20**
Follow up to #19328, paginators should not only be built of the container, they should use the interface. This is more correct and gives developers more flexibility in their implementation.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
You have broken the tests

**Comment by tillkruss** [comment]
I've changed the branch to 5.6. You need to rebase and fix the tests.

**Comment by taylorotwell** [comment]
There are other commits in the PR.

**Comment by paulofreitas** [comment]
@grashoper20 Try resubmitting this to the `master` branch instead. Don't forget to fix the tests, you should probably change `Illuminate\Pagination\PaginationServiceProvider` to resolve these contracts within container. 👍

**Pull request closed without merging**
