### PR TITLE
Close all connections after test has finished

### PR DESCRIPTION
**Pull request by wins1908**

### CODE REVIEW

**Comment by taylorotwell** [comment]
This should not be necessary. Under normal circumstances Laravel will just use the same connection each time. Perhaps there is some other problem in your code causing this error to occur.

**Comment by wins1908** [comment]
@taylorotwell I haven't seen anywhere which will call \Illuminate\Database\DatabaseManager::disconnect() in laravel framework.
I assume that database is going to close the unused connections itself, after $this->app = null in \Illuminate\Foundation\Testing\TestCase::tearDown().
Could you pls check again? 
It seems that many people have the same issue with me.

**Comment by weburnit** [comment]
ab780f50dec964a4d77d5c3415cf4712
We have more than 500 Tests, and it runs quite fast
Therefore previous connections can not be released. This commit has fixed this issue quite well.
@taylorotwell would you plz consider it one more?
b1c1dccbd9efc3679b44b326977cbc15

**Comment by deleugpn** [comment]
I think Taylor's point here was that if this is happening, we should investigate why Laravel is not reusing the same connection instead of throwing the towel at it by disconnecting and reconnecting each test.

**Comment by wins1908** [comment]
@deleugpn @taylorotwell at vendor/laravel/lumen-framework/src/Testing/TestCase.php:116, the application was removed after each test has finished, that's why database connection cannot be reused among tests.

**Comment by deleugpn** [comment]
@wins1908 The application being teared down should be enough condition for the connection to be destroyed as well, no? That is, building a new application for the next test should either pick up the connection from PHP's connection pool or use a new one because the old one got picked up by GC. Either cases, not exactly a Laravel problem. 

I guess it's a good work-around to merge this, but the fact that there's an underlying problem still persists.

**Comment by weburnit** [comment]
if we run test without Code-coverage, error encounters for sure!
In case, code-coverage is enable, Test env will slow down a bit and everything is fine.
P/s: I'm using Postrgresql

**Comment by RobvH** [comment]
@taylorotwell We were running into exactly the same problem in one of our lumen services' test suites -- I was prepping a PR when I found @wins1908.

It is definitely not reusing the connections; at least not with Postgres. 

The Lumen service where we had the issue has 3 db connections active and in transactions; we reached the point where any new test case would cause the error. Subclassing DatabaseTransactions and adding `$database->connection($name)->disconnect();` after the rollback solved it entirely.

**Comment by mfn** [comment]
I believe this was fixed (for Laravel) in 5.5 and at least backported to 5.4 (or it was introduced in 5.4, don't remember); I know this issue well because I had the same problem in the past.

It's all connected to this trait `\Illuminate\Foundation\Testing\DatabaseTransactions`.

See the code in 5.3:
```php
    public function beginDatabaseTransaction()
    {
        $database = $this->app->make('db');

        foreach ($this->connectionsToTransact() as $name) {
            $database->connection($name)->beginTransaction();
        }

        $this->beforeApplicationDestroyed(function () use ($database) {
            foreach ($this->connectionsToTransact() as $name) {
                $database->connection($name)->rollBack();
            }
        });
    }
```

Now compare it to 5.4/5.5
```php
    public function beginDatabaseTransaction()
    {
        $database = $this->app->make('db');

        foreach ($this->connectionsToTransact() as $name) {
            $database->connection($name)->beginTransaction();
        }

        $this->beforeApplicationDestroyed(function () use ($database) {
            foreach ($this->connectionsToTransact() as $name) {
                $connection = $database->connection($name);

                $connection->rollBack();
                $connection->disconnect();
            }
        });
    }
```
This contains the needed `->disconect()` call.

It works for us (we've >2k tests, lots of them using this trait) and before this fix I basically had a copy of the trait doing exactly this and could remove it once we upgraded to 5.4/5.5

**Pull request closed without merging**
