### PR TITLE
[8.x] Support returning an instance of a caster

### PR DESCRIPTION
**Pull request by brendt**
See https://github.com/laravel/framework/pull/32213#issuecomment-608438683

---

With the addition of the `Castable` interface (https://github.com/laravel/docs/pull/5934), it makes sense to allow direct instantiation from within a `Castable::castUsing` implementation. A common usecase could be something like this:

```php
class EloquentDataTransferObject extends DataTransferObject implements Castable
{
    public static function castUsing()
    {
        return new DataTransferObjectCaster(static::class);
    }
}
```

Which allows a kind of "generic" cast. All classes extending `EloquentDataTransferObject` can now directly be used as a cast type, and will be casted to the correct implementation of `EloquentDataTransferObject`.

Eg.

```php
class MyData extends EloquentDataTransferObject {
    public int $property = 1;
}

class ModelX extends Model
{
    protected $casts = [
        'data' => MyData::class,
    ];
}
```

### CODE REVIEW

**Comment by brendt** [comment]
@taylorotwell I suppose this means it'll be added in 8.x?

**Comment by mfn** [comment]
Would be great to have this in 7.x … it's backwards compatible, no?

**Comment by driesvints** [comment]
@brendt correct.

@mfn Taylor asked to send this to master instead.

**Comment by taylorotwell** [comment]
OK then send back to 7.x ... haha... I'll just merge it forward. Sorry for the inconvenience of making you send again. 😬

**Comment by brendt** [comment]
No problem, here it is: https://github.com/laravel/framework/pull/32225

**Pull request closed without merging**
