### PR TITLE
[5.8] Add 'index' => 'viewAny' to resourceAbilityMap

### PR DESCRIPTION
**Pull request by jcqtc**
Automatically bind the `viewAny` method to the `index` controller action

### CODE REVIEW

**Comment by tvbeek** [comment]
First of all I think this is a nice addition.
But it breaks if you don't have a viewAny on your policy and use $this->authorizeResource(Model::class, 'model');
That result in that I'm not sure that this isn't a backward compatibility break.

Maybe it is an idea for the next time to add it more clear to the releasenotes.

**Comment by danijelk** [comment]
FYI it is a breaking change. We tried to add it last year but got rejected https://github.com/laravel/framework/pull/26078 but glad it got through this time...

**Comment by clement-jacquet** [comment]
What if we check if the gate exists before actually adding it as a middleware ?

**Comment by driesvints** [comment]
@danijelk new functionality which doesn't breaks the public api isn't considered a breaking change.

**Pull request merged**
