### PR TITLE
[5.5] Fix NotificationFake interfaces and return fake object.

### PR DESCRIPTION
**Pull request by mathieutu**
Hi,
This PR:

- adds the missing Dispatcher contract on NotificationFake: it failed when injected, and it's supposed to replace the ChannelMannager in the container, which has this contract. ([1st commit](https://github.com/laravel/framework/commit/9926672301cb43dbc32825019b093a57c2f65c4a))
- return the created Fake object when Notification::fake() method is called. It permits to use it directly in tests. Tests was added for that. ([2nd commit](https://github.com/laravel/framework/commit/4e81435772c6a751c375f5c2fb8db0b3b9aa2fbe))

Thanks.
Matt'

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
This is a breaking change for those who don't expect it to return a faked object.

**Comment by taylorotwell** [comment]
So how do we recreate the problem this created?

**Comment by mathieutu** [comment]
Using Dependency Injection instead of facade:

```php
public function store(Dispatcher $notifications)
{
        // (...)

        $notifications->send(
            $users,
            new FooNotification()
        );
}
```

And it's even not only about "what failed". In my opinion this is just an *oversight*. The other interface of ChannelManager, is already implemented, the methods from the interface are implemented, and **the container already resolves `app(Dispatcher::class)` as `NotificationFake`**...

**Comment by taylorotwell** [comment]
If you are using dependency injection, why would you use the `fake` method at all? You would just make the dispatcher directly?

**Comment by mathieutu** [comment]
hum ? Didn't understand your point..
The missing interface hasn't any link with the `fake` method, it's just a missing interface!
As `BusFake` implements the `Bus/Dispatcher`, `NotificationFake` must implements the `Notification/Dispatcher`. It must because it's a fake. It's supposed to implement the same method, and simulate the same behavior. You already use the same methods, and it's binding in its usage, so it's really just an oversight.


And btw the `fake` is not just only for the Facade but for all the ways to access to the container. If you use `$notifiable->notify()` it will be exactly the same, because it's just `app(Dispatcher::class)` behind the scene.

This is just a little PR with two different things around the same topic : 
- 1st commit is just fixing a bug by implementing a missing interface.
- 2nd is simply about returning the fake from the Facade `fake` method. It doesn't change anything to the actual usage, it just permits to use it directly afterwards.

**Pull request merged**
