### PR TITLE
[8.x] Update Builder.php, fixing null column with cursorPaginate

### PR DESCRIPTION
**Pull request by MostafaRabia**
Change to make `cursorPaginate` work with nullable column in `orderBy`.

The `cursorPaginate` send where like this `column > null`, and error fires `Illegal operator and value combination.`.

This is solution for this case, I don't know if there is way to make it better, but i don't think there is one to do `->where('column','>',null)`, if there so this would help him :)

### CODE REVIEW

**Comment by taylorotwell** [comment]
Ping @paras-malhotra

**Comment by MostafaRabia** [comment]
@paras-malhotra 
You are right, sorry i didn't test it efficiently, and with my last PR it's good to orderBy column that will be null with id or anything unique.
But i'm facing now `Only arrays and objects are supported when cursor paginating items.` in `Illuminate/Pagination/AbstractCursorPaginator.php:201` and i don't know why, The code is same nearly, and everything is good as i see, so what is it?
I debuged `$item` that `getParametersForItem` take, it's null, why?

And very thanks to you.

**Comment by paras-malhotra** [comment]
@MostafaRabia, not sure about that. Would be great if you could open an issue with some steps to replicate. I'll look into it.

**Comment by MostafaRabia** [comment]
I will.

**Pull request closed without merging**
