### PR TITLE
[8.x] Translate the pagination messages

### PR DESCRIPTION
**Pull request by dmouse**
The messages in `Pagination/resources/views/tailwind.blade.php` are not translatable correctly, in some languages we need to define first the numbers and then text.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Export the pagination views using `vendor:publish`. Customize them as you see fit.

**Comment by dmouse** [comment]
@taylorotwell but what's the idea, 5 lines after is in use `pagination.previous`. Why not translate all?

**Comment by rodrigopedra** [comment]
@dmouse all the strings you changed in the PR are already localize-able.

For example, in this code `{{ __('Pagination Navigation') }}` the string `"Pagination Navigation"` is being passed as an argument to the `__(...)` helper, which will localize it according to the current locale.

The catch here is that Laravel supports 2 methods of providing localization strings, one is the PHP based you tried to introduce with your PR and the other is a JSON based that is documented here:

https://laravel.com/docs/8.x/localization#using-translation-strings-as-keys

So to translate that sample string to Portuguese, for example, you can create a `./resources/lang/pt.json` with this content:

~~~json
{
    "Pagination Navigation": "Navegação da paginação"
}
~~~

And when the app's locale is set to `pt` (Portuguese) it will use translation.

Of course you can also export the views and customize them however you like to.

===

Note: I chose Portuguese as the example as it is my native language.

**Comment by dmouse** [comment]
Thank you @rodrigopedra.

I just tried to use the same syntax in all the file to translate the string in the same `pagination.php` file and when I saw the `previous` and `next` keys. I thought it would be a good idea if all the strings in the file were defined in the same way.

But anyway, thank you for your time @rodrigopedra ++

**Comment by rodrigopedra** [comment]
You're welcome @dmouse

**Pull request closed without merging**
