### PR TITLE
workaround for bug in is_writable

### PR DESCRIPTION
**Pull request by efinder2**
If you create a new Laravel application on windows on a mounted Linux drive whith ACL, this exception will be thrown:
```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
In PackageManifest.php line 179:
  The R:\path\to\laravel\bootstrap\cache directory must be present and writable.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```
Problem is the `is_writable` function returns false although the cache directory is present and writable. The `fileperms` function resolves the permissions as `40777`. It is possible to create files in the user/group constellation in php.

To be sure whether the directory is writable you have to write in it. If it is successful you may proceed. Because I'm not sure where to put the equivalent of the [wordpress ](https://developer.wordpress.org/reference/functions/win_is_writable/) function I'd add it to the same function where I had the problem.

I'm open to alternatives.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by efinder2** [comment]
@taylorotwell I understand your concerns and know my proposal is not finished for merging yet. Problem is, even if I write a package with the fixed is_writable function, there is, as far as I know,  no possibility to replace the usage of the function in class Illuminate\Foundation\PackageManifest. The class self could also not be replaced in a package.

Alternatively to my proposal, it may be better to replace the is_writeable function in the Illuminate/Filesystem/Filesystem class. So the change is easier to maintain. Only the few usages of the class in the system need to replaced. Problem here is if the directories wich are checked for is writable have automated processes. The creation of a file for testing would trigger those processes. A check whether the system runs on windows would make the automated testing of the function more complex. So I suggest to create a alternative function wich could be activated if needed.

If there is a possibility to override this function I'm complete ok with that and will create an option for me. But I'm quite new to laravel and don'ts see a possibility.

**Comment by efinder2** [comment]
@taylorotwell what status of this point? I don't see a possibility to override the PackageManifest class. The use of the class is not configurable. Because it is used in central locations. I don't see a way without extending many classes so it isn't fully compatible anymore.

**Comment by moxuanyuan** [comment]
I have the same problem

**Pull request closed without merging**
