### PR TITLE
[8.x] Added getAuthIdentifierForBroadcasting method

### PR DESCRIPTION
**Pull request by yousuf-hossain-shanto**
I am working on a project where doctor can chat with patients. Doctor and Patient are two different auth guard and different model also. I am using pusher and Laravel echo for real-time chat.

Everything is fine when doctor and patient id is different. But facing issue when doctor and patient id is same. But, doctor and patient id can be same because of they are from different model and different database table.

Currently Laravel is sending **getAuthIdentifier** method value to broadcaster (pusher, redis) and those broadcaster is identifying users by this value. It can be resolved by modifying **getAuthIdentifier** method into relevant authenticatable model. But, **getAuthIdentifier** method is a common used method by various packages and libraries. They expect id from using it. So, it is risky to modify it.

I have added a new method named **getAuthIdentifierForBroadcasting** to resolve it.

Thanks in advance

### CODE REVIEW

**Comment by morloderex** [comment]
Another way of solving this is having to different guards e.g `doctors` and `patients`.

Then you could define your channels like this which signal's the broadcaster to use both guards:

```php
Broadcast::channel('some-doctor-patient-channel-name', function ($user, $id) {
   // determine if the channel is accessible for a given user model here
}, ['guard' => 'doctor', 'patient']);
```

You do unfortunetly need to define this guard configuration for every channel you have currently there is no way of doing this on a global level e.g for all channels as far as i can see from the source code.

Based on this information i do not think your suggestion is necessary needed as one could just define which guard(s) a specific channel should use instead.

**Comment by yousuf-hossain-shanto** [comment]
> Another way of solving this is having to different guards e.g `doctors` and `patients`.
> 
> Then you could define your channels like this which signal's the broadcaster to use both guards:
> 
> ```
> Broadcast::channel('some-doctor-patient-channel-name', function ($user, $id) {
>    // determine if the channel is accessible for a given user model here
> }, ['guard' => 'doctor', 'patient']);
> ```
> 
> You do unfortunetly need to define this guard configuration for every channel you have currently there is no way of doing this on a global level e.g for all channels as far as i can see from the source code.
> 
> Based on this information i do not think your suggestion is necessary needed as one could just define which guard(s) a specific channel should use instead.

I already authenticate my channel using this way but that issue is happening after authentication. I debug on pusher and see that,
1. Doctor (id 1) joined to a channel chat
2. Patients (id 1) joined to the same channel

and after that, pusher/redis identify the last user joined at that channel because of their same id (Laravel sent as user_id)

**Comment by morloderex** [comment]
Ah, i get your point now, my bad for not understanding completly what you mean.

Adding this method might be useful then, however would a sensible default value be `modelclass:model_identifier`. This way  it should work by default when using mutiple guards?

**Comment by yousuf-hossain-shanto** [comment]
@morloderex Thanks for your suggestion. I just added a different method with previous return value (model id). If one need to prefix model identifier with something, then he/she can change it as he/she want. Otherwise default value will be used

**Comment by taylorotwell** [comment]
For this to not be breaking we may need to ensure that the new method exists on the model before calling it. Some people may not be using the Authenticatable trait and may be implementing the getAuthIdentifier method themselves.

**Comment by taylorotwell** [comment]
Please revert all those spacing changes.

**Comment by yousuf-hossain-shanto** [comment]
Now it will use default getAuthIdentifier method as a fallback

**Pull request merged**
