### PR TITLE
[5.5] Make seeders chainable

### PR DESCRIPTION
**Pull request by freekmurze**
Right now you must call seeders in `DatabaseSeeder` like this:

```php
$this->call(SeederA::class);
$this->call(SeederB::class);
$this->call(SeederC::class);
```

The changes in this PR will enable to do the above like this

```php
$this
   ->call(SeederA::class);
   ->call(SeederB::class);
   ->call(SeederC::class);
```

### CODE REVIEW

**Comment by a-komarev** [comment]
What is the profit from it? Wouldn't it be better to make:
```php
$this->call([
    SeederA::class,
    SeederB::class,
    SeederC::class,
]);
```

**Comment by laurencei** [comment]
@freekmurze wouldnt the new syntax be this?

```
$this
   ->call(SeederA::class)
   ->call(SeederB::class)
   ->call(SeederC::class);
```

**Comment by devcircus** [comment]
Can't you already do 
```
$this->call([
    SeederA::class,
    SeederB::class,
]);
```

**Comment by browner12** [comment]
@devcircus yes you can.  I'm not really seeing the benefit of chaining, but oh well, it's already in.

**Comment by lbm-trentm** [comment]
if no one can really see the benefit to this, why bloat the software?

**Comment by nachofassini** [comment]
what @a-komarev  proposes its already implemented [docs](https://laravel.com/docs/5.5/seeding#calling-additional-seeders)

**Comment by deleugpn** [comment]
@lbm-trentm The PR creator, people liking the PR and Taylor seem to disagree with your premise.

**Comment by a-komarev** [comment]
@deleugpn nobody said that we are disagree with this PR. Question of reason was raised and this behavior was available already, as @nachofassini pointed to docs.

One minor notice that in first comment bad example is provided. It should be:

```php
$this
   ->call(SeederA::class)
   ->call(SeederB::class)
   ->call(SeederC::class);
```

**Comment by connectkushal** [comment]
to those grumbling about bloating the software without any benefit, this pr adds just 2 extra words to the actual code, `return $this`

**Comment by browner12** [comment]
Lingchi - Death by 1000 cuts. 

Mostly trolling, but our initial point was this was a solution to a problem that already had a solution.

It's in now, so /shrug

**Pull request merged**
