### PR TITLE
[5.4] Add an unsignedDecimal method to Laravel Schema Blueprint

### PR DESCRIPTION
**Pull request by phpguru**
… along with a unit test for it. Improves solution offered to [Issue 875](https://github.com/laravel/framework/issues/875).

### CODE REVIEW

**Comment by tillkruss** [comment]
Did you test that on MySQL, PostgreSQL and SqlServer?

**Comment by sisve** [comment]
It will not work on PostgreSQL and SQL Server because they follow the sql standard, and there's no such thing as unsigned numerics. If you want to force non-negative values you use constraints, not data types.

> Exact numeric types hold numeric values without digits after the decimal or with a firm number of digits after the decimal. All exact numeric types are signed.

Source: https://en.wikibooks.org/wiki/Structured_Query_Language/Data_Types#Exact_Numeric

> Approximate numeric types hold numeric values with an implementation defined precision (after the decimal). All approximate numeric types are signed. Their primary use cases are scientific computations.

Source: https://en.wikibooks.org/wiki/Structured_Query_Language/Data_Types#Approximate_Numeric

All the data types in [PostgreSQL: Documentation: 9.5: Data Types](https://www.postgresql.org/docs/9.5/static/datatype.html) are signed,
 there are no unsigned versions. 

On the other hand, this PR makes sense to bring consistency to the schema builder api even if the underlying database doesn't support the result.

**Comment by phpguru** [comment]
>  Did you test that on MySQL, PostgreSQL and SqlServer?

I did not test on PostgreSQL nor SqlServer, however I did test with provided additional PHPunit test and verified it passes the test and the code works against MySQL. 

> to bring consistency to the schema builder api even if the underlying database 
> doesn't support the result.

The "unsigned[NumericType]" methods are convenience wrappers. I've merely added one that seemed oddly missing.

**Comment by tillkruss** [comment]
@sisve thanks.

**Comment by ziming** [comment]
In MySQL 8.0.17

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-17.html

"The UNSIGNED attribute is deprecated for columns of type FLOAT, DOUBLE, and DECIMAL (and any synonyms) and support for it will be removed in a future MySQL version. Consider using a simple CHECK constraint instead for such columns."

**Pull request merged**
