### PR TITLE
[5.6] Fix double firing of resolving callback

### PR DESCRIPTION
**Pull request by slavarazum**
When we bind something with IoC container like this:
```php
app()->bind(Some::class, SomeAwesome::class);
```
And register resolving callback
```php
app()->resolving(Some::class, function ($some) {
    dump('Resolving Some');
});
```
After resolve this class by `resolve(Some::class)` resolving callback will fire twice. Because 1st step will be - resolve `Some::class` and 2nd step will be resolve `SomeAwesome::class` as condition in `getCallbacksForType` method is:
```php
if ($type === $abstract || $object instanceof $type) {
    $results = array_merge($results, $callbacks);
}
```
`$object instanceof $type` matches `Some` interface and also `SomeAwesome` class, because `SomeAwesome` is instanceof `Some`.
I think we should exclude cases when resolving callback registered to interface fires for class.
```php
 if ($type === $abstract ||
    $object instanceof $type &&
    (class_exists($abstract) || ! interface_exists($abstract)) &&
    ! interface_exists($type)) {
    $results = array_merge($results, $callbacks);
}
```

### CODE REVIEW

**Comment by sisve** [comment]
The suggested if-statement looks like a mess and there's no tests in this PR.

There's still two resolving events trigger if Some is an class.

**Comment by ModernArtisan** [comment]
@sisve Do you have any other suggestions how to resolve this issue?

**Comment by tillkruss** [comment]
Extract parts of the condition into a method, or at least a temporary variable.

**Comment by ModernArtisan** [comment]
@tillkruss It's clear, but I think maybe there is a better solution for this issue. I have investigated how IoC Container works and I haven't found any solution without making large-scale changes yet.

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Comment by tomlankhorst** [comment]
Btw, a 'hack' is to make the concrete class in a closure without invoking the service container: 

```php
app()->bind(Some::class, function(){
  return new SomeAwesome;
});
```

**Pull request closed without merging**
