### PR TITLE
[5.2] Made sure missing keys are not returned with null from Request->only()

### PR DESCRIPTION
**Pull request by OskarD**
https://github.com/laravel/framework/issues/14734

### CODE REVIEW

**Comment by OskarD** [comment]
I didn't take the subarrays into account, will need to dig deeper into the code to complete this PR

**Comment by GrahamCampbell** [comment]
Thanks, but we intentionally have null values here. We have a different method for if you don't want them.

**Comment by GrahamCampbell** [comment]
`intersect`

**Comment by OskarD** [comment]
Ok, thank you

**Pull request closed without merging**
