### PR TITLE
[5.7] Bumped versions

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Bumped min symfony version to 4.1, and use the caret operator globally.

### CODE REVIEW

**Comment by browner12** [comment]
i'm definitely all for consistency here, but can you explain why we are going with carets over tildes?

**Comment by deleugpn** [comment]
^

**Comment by X-Coder264** [comment]
Because the caret operator sticks closer to semantic versioning, eg.

 `^1.1.1` is equivalent to `>=1.1.1 <2.0.0`
while
 `~1.1.1 ` is equivalent to  `>=1.1.1 <1.2.0 `

**Comment by browner12** [comment]
true, but what you see in this PR are requirements like

`~1.12` going to `^1.12`

which are equivalent.

I would say they both stick to semantic versioning, one is just a little more conservative than the other.

Again, I'm okay either way as long as we're consistent. And I don't want to draw out this issue since it's all functionally the same. Was more so just curious if anyone had a reason other than what it says in the Composer manual.

**Comment by GrahamCampbell** [comment]
Yeh, just going for the semver operators, and keeping it consistent where it's the same as the tilde.

**Pull request merged**
