### PR TITLE
Add everyXDays and everyXDaysAt scheduling frequency helpers

### PR DESCRIPTION
**Pull request by sowrensen**
This PR adds some helpers for scheduling frequencies to run jobs every X days. With `everyXDays()` and `everyXDaysAt()` the following helpers are also added:

- `everyTwoDays()`
- `everyFiveDays()`
- `everyTenDays()`

### CODE REVIEW

**Comment by SjorsO** [comment]
Something similar was proposed and rejected before: https://github.com/laravel/framework/pull/33380

The problem with these methods is that they don't actually run every X days. For example: if a month has 31 days, `everyTwoDays` will run two days in a row, on the 31st and the 1st. The other proposed methods have the same kind of problem problem.

**Comment by sowrensen** [comment]
@SjorsO You are right. I didn't think of it. I had to do something similar for my work, run a job each 3 days. Doing so using `cron()` was a bit tedious, as you mentioned on a comment. I thought to add some helpers to make it easier.

However, running two consecutive days for a 31-day month is still an issue even if we use `cron('0 0 */2 * *')`. I feel that is more of an issue with cron itself. I cannot think of any solution right now, but I would like to hear any suggestion and implement it.

**Comment by dennisprudlo** [comment]
You could write into the cache when the last execution of the job/command was the schedule it daily and check if the last execution was 2 days ago.

As you said it's more of a cron thing because `0 0 */2 * *` actually means "every other day **per month**"

**Comment by sowrensen** [comment]
> You could write into the cache when the last execution of the job/command

That's a great idea.

> `0 0 */2 * *` actually means "every other day **per month**"

Now, you see the dilemma here. Since it explicitly mentions "per month", changing this **intended behavior** might confuse users. I would rather keep things as close as possible to the original. Besides, people will be unaware of this checking unless it is mentioned on the doc or they dig into the source code. 😒

**Comment by taylorotwell** [comment]
Jobs like this are pretty better handled by telling the scheduler to run them `daily` then combining that with a `when` callback to have more robust opportunities for determining if the job can run within PHP:

```php
$this->command(...)->daily()->when(fn () => something);
```

**Pull request closed without merging**
