### PR TITLE
[5.4] Correction of casting with overflow.

### PR DESCRIPTION
**Pull request by Arekusei**
See #19035

### CODE REVIEW

**Comment by tillkruss** [comment]
What happens if the primary key is a UUID?

**Comment by taylorotwell** [comment]
I don't see how this changes the code? Also, we need steps to reproduce if possible. On your original issue you said "I don't know". If we can't re-produce it how do we fix it?

**Comment by Arekusei** [comment]
@taylorotwell This is reproduced on any model with an auto-critical value greater than the maximum INT value. I ran into this problem on the x86 version of PHP.
That's what I meant and gave the sample code in that issue that behaves incorrectly.

PS. Sorry for the bad english.

**Comment by Arekusei** [comment]
@tillkruss 
```cmd
php -r "$posNum = '123e4567-e89b-12d3-a456-426655440000'; var_dump(filter_var($posNum, FILTER_VALIDATE_INT) !== false ? (int)$posNum : $posNum);"
string(36) "123e4567-e89b-12d3-a456-426655440000"
```

**Pull request closed without merging**
