### PR TITLE
[9.x] Remove redundant types on mixed

### PR DESCRIPTION
**Pull request by PerryvanderMeer**
This PR removes redundant types on `mixed` types, [since `mixed` already accepts these types](https://www.php.net/manual/en/language.types.mixed.php).

### CODE REVIEW

**Comment by PerryvanderMeer** [comment]
Something different i came across while updating these docblocks. For nullable types, `string|null` and `?string` are used through eachother. For example:

https://github.com/laravel/framework/blob/37bbb8c299b51195fc38f845dae847726d982522/src/Illuminate/Auth/Access/HandlesAuthorization.php#L22

https://github.com/laravel/framework/blob/37bbb8c299b51195fc38f845dae847726d982522/src/Illuminate/Auth/Access/HandlesAuthorization.php#L35

I'm not sure if we want these internal inconsistencies. I'd prefer `?string` for variables with a single type, since it improves readability.

**Comment by bert-w** [comment]
`array|mixed` could indicate that it's generally supposed to be an array, but other types are possible. I think we lose some clarity by making everything`mixed` only.

I think in a lot of cases it probably isn't really correct to define something as `mixed` since it probably only accepts a subset like `string|null|boolean|float|integer`, which for simplicity's sake is defined as `mixed`. So there are definitely some improvements to be made.

**Comment by jmarcher** [comment]
I think it is more clear the way it is now.

**Comment by PerryvanderMeer** [comment]
I agree with you both, `mixed` types would need more improvements for clarifying.
How about the [internal inconsistencies](https://github.com/laravel/framework/pull/45175#issuecomment-1336134424) for `string|null` and `?string`?

/cc @taylorotwell

**Pull request closed without merging**
