### PR TITLE
[5.6] Fix issue with artisan make: commands alreadyExists method to ensure …

### PR DESCRIPTION
**Pull request by JamesAnelay**
As discussed in #24125 Fixes issue with make:event + make:listener not actually checking the correct file location.

Note this reverts the fix changes for 3079175 but I don't think those didn't really worked in the first place. Would need to know more about that issue to be able to incorporate it into this pull request.

Also defaulted ExceptionMakeCommand::alreadyExists back to the parent as from what I can see there is no difference.

### CODE REVIEW

**Comment by tillkruss** [comment]
Could you add tests?

**Comment by devcircus** [comment]
Isn't this the same as #21600 that was closed?

**Comment by JamesAnelay** [comment]
@devcircus Indeed it looks similar. I guess my question would be

"This breaks some framework behaviour such as not generating events for framework events." What exactly does that mean, it's not clear to me.

There are about 405 declared classes at this point that "class_exists" is checking against such as "ParseError" or "BadFunctionCallException" or "Illuminate\Cache\CacheManager"

Note that the newly generated Listener or Event never makes it into the declared class list and therefor never returns true on class_exists given the new classes go in App\Listeners namesapce I can't see the issue, but maybe i'm missing something.

**Comment by tillkruss** [comment]
Can we check for file existence instead?

**Comment by JamesAnelay** [comment]
Ok so it seems to me that the easy solution is to check class_exists + also check if the file already exists. That keeps your fix in place for the event: generate command but also stops the command overwriting files that already have been created..

Something like:
```
    protected function alreadyExists($rawName)
    {
        return class_exists($rawName) || $this->files->exists($this->getPath($this->qualifyClass($rawName)));
    }
```

**Pull request closed without merging**
