### PR TITLE
[5.5] Add ->post() method to Request

### PR DESCRIPTION
**Pull request by svenluijten**
The `->post()` method will get all data from the request body (POST body), or when given a `$key`, it'll get that specific value. Using Symfony's public `$request` property on the `Request` object: https://github.com/symfony/http-foundation/blob/master/Request.php#L76-L81

### CODE REVIEW

**Comment by taylorotwell** [comment]
When would you actually use this?

**Comment by svenluijten** [comment]
Given you're on `/foo?page=1`, with a form that looks like this:

```html
<form action="" method="POST">
    <input name="page" type="text">
    <input type="submit" value="Submit">
</form>
```

In this case, `$request->get('page')` would only contain one of the values (either `1` from the query string, or the data you submitted via the form). 

With this PR merged, you can safely assume all the data you retrieved with `$request->post('page');` is always equal to what was submitted via the form. Maybe `post` isn't the right word to use here though, since it gets values from the request body (also on `PUT`, `PATCH`, etc.). Maybe `->body();`?

**Comment by dbpolito** [comment]
I like this, i already had to workaround with something like this before.

**Comment by a-komarev** [comment]
@svenluijten Why this so important for you to get exactly post data? Wouldn't `$request->input('page')` prefer $_POST over the $_GET params?

**Comment by cwhite92** [comment]
I needed this because I wanted to log certain properties of the request, like any query strings that were passed, any POSTed data, the URL etc. But the query strings and POST data needed to be logged separately.

If I used `->input()` to get the POST data, it would also include query params. `->all()` would also include any query params on the request. There doesn't seem to be a convenient method to retrieve JUST the POSTed data from the request, without merging the query params as well.

**Comment by a-komarev** [comment]
@cwhite92 that make sense

**Comment by devcircus** [comment]
$request->request return $_POST parameters only

**Comment by cwhite92** [comment]
Yeah, that's what this PR implements.

**Comment by devcircus** [comment]
So ```$request->post()``` instead of 
```$request->request```

and 
```$request->post('title')``` instead of 
```$request->get('title)``` ?

**Comment by svenluijten** [comment]
@devcircus No, `$request->post();` instead of `$request->request->all();`, and `$request->post('title');` instead of `$request->request->get('title');`.

`$request->get('title');` will include results from the query string, which is not what we want.

**Comment by devcircus** [comment]
Yeah just seems like the functionality is already there. Lots of PRs lately that simply save a few keystrokes. 

Then again, I've never had the same parameters in POST and GET at the same time, so never had the need for separating it like this, maybe it'll come in handy.

**Comment by garygreen** [comment]
I think this makes a lot of sense. I mean we already have `->query()` which get's the query parameters, why not `->post()` which get's the post's parameters.

**Comment by decadence** [comment]
+1 for this. I don't like that we can't take input only from POST.
But this and `query` don't support dot key.

**Comment by sisve** [comment]
What would ->post() return for GET requests? Isn't [Request.php#L353](https://github.com/laravel/framework/blob/5f71c09c2a079e865ec8420e2abe52633d57d310/src/Illuminate/Http/Request.php#L353) replacing the container you presume to contain post-data with the query string, or perhaps even parsed json data?

**Pull request merged**
