### PR TITLE
[5.2] Do not call scope twice

### PR DESCRIPTION
**Pull request by vlakoff**
One step closer to ZONDA.

### CODE REVIEW

**Comment by vlakoff** [comment]
Introduced in https://github.com/laravel/framework/commit/23adaa4068ad91fd934b58b6f60cef06135a76e3.

**Comment by GrahamCampbell** [comment]
?

**Comment by mark86092** [comment]
@vlakoff, in my test, the `?:` won't run call_user_func_array([$this->model, $scope], $parameters) twice.

```
$default = null;
function test() {
        echo "Test";
        return true;
}
$result = test() ?: $default;  // only 1 "Test" printed
```

**Comment by vlakoff** [comment]
I just realized the mistake, but you have been faster than me :) Sorry for the inconvenience.

**Pull request closed without merging**
