### PR TITLE
[5.8] Database migration - ForeignKeyDefinition as a return

### PR DESCRIPTION
**Pull request by TullariS**
Based on the comments from @TBlindaruk, an instance of ForeignKeyDefinition will be returned from the foreign() method, rather than simply being set in the PHPDoc.

Also, since foreign() would need to generate the same Fluent parameters as indexCommand(), to avoid repeating the code, I have created indexCommandParameters() to handle parameters for both indexes and foreign keys.

### CODE REVIEW

**Comment by taylorotwell** [comment]
If it works with PHPDoc only why do we need a code change?

**Comment by TullariS** [comment]
> If it works with PHPDoc only why do we need a code change?

@taylorotwell True, but the idea was that it also followed how ColumnDefinition works. If ColumnDefinition is an actual return, makes sense that ForeignKeyDefinition should be the same.

Could also be useful in future (maybe) if the developers need to define column-only or index-only methods outside of fluent. They could add them to those classes.

**Comment by TullariS** [comment]
@taylorotwell , @deleugpn please look at #24444.

ColumnDefinition was created. It is simply a wrapper for Fluent, doesn't really do anything other than provide code assist for IDEs.

So, if it is only for IDE, then all Blueprint needs is to have its @return updated from Fluent to ColumnDefinition, but for some reason addColumn() now returns ColumnDefinition and not Fluent.

https://github.com/laravel/framework/pull/24444/files#diff-0a0682dbb89567dbcd7c4f50d4d1ece5R1260

How is this not also a case of 

> If it works with PHPDoc only why do we need a code change?

This PR is not trying to change things. Its trying to make them the same, otherwise #28387 would work just fine.

**Comment by deleugpn** [comment]
I understand what you're saying, but I don't agree with Tetiana's point. I don't care that it's never going to return an actual instance of ForeignKeyDefinition, the docblock is enough to help IDE and has no downside whatsoever.

**Comment by TullariS** [comment]
@deleugpn I don't care either actually (its only for IDE), but it would make sense that the class would be introduced to the code in the same way as ColumnDefinition.

Actually the bottom line is that in the end it doesn't matter if #28435 or #28387 since the class doesn't really do anything.

**Pull request closed without merging**
