### PR TITLE
[5.6] Updating Travis CI config file

### PR DESCRIPTION
**Pull request by arcanedev-maroc**
Run tests with PHP 7.1.3 instead of the latest version of PHP 7.1

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm not sure this is necessary?

**Comment by arcanedev-maroc** [comment]
This PR make sure that the min PHP version is tested and maintained.

**Question:** Why in the `composer.json` file the php version is `^7.1.3` and not `^7.1` ?

**Comment by X-Coder264** [comment]
@arcanedev-maroc It's ```^7.1.3``` because that is the minimal version that Symfony 4 requires. As to why that specific version, it's because of this bug (https://bugs.php.net/bug.php?id=73989) which was causing segfaults.

**Comment by arcanedev-maroc** [comment]
OK i see now, thanks @X-Coder264 👍

**Pull request closed without merging**
