### PR TITLE
[8.x] Unification of paginator translation keys

### PR DESCRIPTION
**Pull request by andrey-helldar**
I made an appeal to the translations of the paginator keys, since this file contained an appeal to both the pagination.php file and the json file.
Has brought the code to a single form.

I also sent a PR to the https://github.com/laravel/laravel/pull/5426

### CODE REVIEW

**Comment by taylorotwell** [comment]
No plans to change this for now, especially on a minor release.

**Comment by andrey-helldar** [comment]
> No plans to change this for now, especially on a minor release.

Now in [one file](https://github.com/illuminate/pagination/blob/master/resources/views/tailwind.blade.php) there (lines 6, 10, 16, 20, 28, 30, 32, 34 and 74) is a call to the translation of json and pagination.php file.
I think this is wrong. It is necessary to unify the treatment. Do either everything in json or everything in pagination.php.

It is incorrect to upload changes to the patch. I agree.
This is a minor change for a major update, given the original access error. That is why I suggested changes to the minor version.

If, nevertheless, you think that this should be placed in the major version, then I can send a PR to it.
Should I submit a PR to the `master` branch?

**Comment by andrey-helldar** [comment]
It's not clear what to do from the current answer 😯
I'm not looking forward to talking. Just a short answer.

**Comment by driesvints** [comment]
@andrey-helldar given Taylor's answer we probably won't be changing this, sorry.

**Pull request closed without merging**
