### PR TITLE
[5.2] Update SessionGuard.php

### PR DESCRIPTION
**Pull request by larschinkel**
Refresh the remember token only if it exists.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Failing tests?

**Comment by larschinkel** [comment]
Yep. The Travis CI build failed. But I don't know why.

**Comment by larschinkel** [comment]
I'll come back later. Have to do deeper checks.

**Comment by mark86092** [comment]
You can check the travis log, seems something to do with `getRememberToken`

**Comment by larschinkel** [comment]
Yep, it says that `getRememberToken() does not exist on this mock object` which I don't understand yet. 
I thought that this Method is available if its injected in the refreshRememberToken() Method: 

```php
    /**
     * Refresh the "remember me" token for the user.
     *
     * @param  \Illuminate\Contracts\Auth\Authenticatable  $user
     * @return void
     */
    protected function refreshRememberToken(AuthenticatableContract $user)
    {
        if (! empty($user->getRememberToken())) {
            $user->setRememberToken($token = Str::random(60));

            $this->provider->updateRememberToken($user, $token);            
        }
    }
```

**Pull request closed without merging**
