### PR TITLE
[5.2] Fix double json_encode on pivot model

### PR DESCRIPTION
**Pull request by PhiloNL**
I'm not 100% sure if this is the best way to fix https://github.com/laravel/framework/issues/10533 but this works and no failing tests.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Could you add a test that failed before, and passes now please.

**Comment by PhiloNL** [comment]
@GrahamCampbell done!

**Comment by GrahamCampbell** [comment]
Thanks. Taylor will review this soon. ;)

**Comment by PhiloNL** [comment]
Thanks! 

There is one issue remaining related to casting attributes on the pivot model.

```php
$model->sync([
    1 => ['data' => ['foo' => 'bar']]
]);
```

This still results in:

> ErrorException in helpers.php line 748:
> preg_replace(): Parameter mismatch, pattern is a string while replacement is an array

I've been trying to fix this and have found a solution (which would replace this pull request), but can't find a way to achieve this without breaking a few tests. Should I do a separate pull request to compare?

**Comment by taylorotwell** [comment]
OK taking a slightly different approach here and have pushed a fix. We need the constructor to accept values and mutate them so it behaves more expected during tests. For example if you do `new CustomPivot($model, $attributes) in test you want to be able to pass it an array.

So I've added a new `fromRawAttributes` static method to the base pivot class so you can now do:

```
public function newPivot(Model $parent, array $attributes, $table, $exists)
{
    return Custom::fromRawAttributes($parent, $attributes, $table, $exists);
}
```

https://github.com/laravel/framework/commit/f356419fa6f6b6fbc3322ca587b0bc1e075ba8d2

**Comment by PhiloNL** [comment]
@taylorotwell thanks! Do you have any idea how to fix casting attributes when attaching/syncing?
Since `sync` and `attach` don't touch the pivot model there is no way to use `$casts` or mutators like `setDataAttribute()`.

**Comment by taylorotwell** [comment]
Will make a note to check on that

**Comment by EspadaV8** [comment]
@taylorotwell this is still an issue in 5.1. Can it be backported at all?

**Pull request closed without merging**
