### PR TITLE
[5.2] make:event command no longer overwrites existing events

### PR DESCRIPTION
**Pull request by arthurkirkosa**

### CODE REVIEW

**Comment by taylorotwell** [comment]
I don't think this will work for core events. What if the $rawName is `Illuminate\Database\Events\BeganTransaction` because that's what I have in my `$listen` property on my EventServiceProvider?

**Comment by arthurkirkosa** [comment]
This is the ```make:event          Create a new event class``` command, not the ```event:generate``` one.

**Comment by arthurkirkosa** [comment]
Will this be replaced with another fix?

**Comment by taylorotwell** [comment]
Sure, feel free to send over another PR if you can. I need an example also
of how I can recreate the bug.

**Comment by arthurkirkosa** [comment]
Example:

```
php artisan make:event SomeEvent

// modify the class

php artisan make:event SomeEvent

// see the class overwriten
```

**Pull request closed without merging**
