### PR TITLE
[5.6] Allow the use of component('alias') as mentioned in the documentation

### PR DESCRIPTION
**Pull request by sileence**
The documentation says that after using `Blade::component('components.alert', 'alert')` you can call the component like: `@component('alert')`. That wasn't working for me, this is a possible fix.

Although I'm not happy with using the `View` facade in BladeCompiler (or maybe it doesn't matter?), especially because that made the tests more complicated. Other than that this might be fine.

### CODE REVIEW

**Comment by sisve** [comment]
Did you ever figure out _why_ it wasn't working for you?

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Comment by taylorotwell** [comment]
@sebastiandedeyne any idea why this wouldn't be working?

**Comment by sebastiandedeyne** [comment]
Oh wait a minute, some confusion here. After seeing the snippet in this issue I double checked the realse notes, and apparently the example isn't what my PR was... It was never intended to alias a component path, just register a directive.

Release notes state that this is possible:

```
@component('alert')
```

Only `@alert` was added (with the option to add extra parameters, `@alert(['type' => 'success'])`.

See the example in the original PR: https://github.com/laravel/framework/pull/22796

**Comment by sileence** [comment]
@sebastiandedeyne that's what I noticed, that the alias functionality wasn't in the code. But if it was never intended I think the documentation can be changed and that's basically it.

**Pull request closed without merging**
