### PR TITLE
[9.x] Remove unnecessary returns

### PR DESCRIPTION
**Pull request by daftspunk**
These don't do anything and are not exposed anywhere.

### CODE REVIEW

**Comment by imanghafoori1** [comment]
The class can be extended and the method can be called in the subclasses. So we can not say that no one needs the returned result.

**Comment by daftspunk** [comment]
Doubtful since the base class already returns void for the same operation: https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Model.php#L1445

Relying on this result would be unreliable as it stands. This looks more like an uncorrected oversight...

**Comment by driesvints** [comment]
This will allow the process to continue past the if statement which wasn't the case before.

**Comment by daftspunk** [comment]
Yes apologies missed an empty return inside the if statement. So long as you are aware of this. Thanks

**Pull request closed without merging**
