### PR TITLE
[5.1] Encryption: Extract key length validation

### PR DESCRIPTION
**Pull request by franzliedke**
This keeps the logic for determining and validating correct key lengths for a given cipher in one place.

> Keep things together that change for similar reasons.

Since encryption is so important, I thought it would be a nice idea.

### CODE REVIEW

**Comment by KennedyTedesco** [comment]
I liked this approach.

**Comment by override-chaos** [comment]
:+1: Must better approach !

**Comment by ibrasho** [comment]
This seems quite laravelish!

**Comment by GrahamCampbell** [comment]
This is overkill IMO.

**Comment by taylorotwell** [comment]
Really I thought the previous way was fine.

**Pull request closed without merging**
