### PR TITLE
[5.1] Run Scrutinizer checks for PSR-2

### PR DESCRIPTION
**Pull request by martinssipenko**

### CODE REVIEW

**Comment by martinssipenko** [comment]
Another alternative would be to add `"squizlabs/php_codesniffer": "~2.0"` to `require-dev` and run `phpcs` on travis-ci.

**Comment by taylorotwell** [comment]
It hasn't been converted yet.

**Comment by RomainLanz** [comment]
@taylorotwell Do you know the date of conversion?

**Comment by GrahamCampbell** [comment]
Yes. It'll be the end of May this hear.

**Pull request closed without merging**
