### PR TITLE
Add short trans variant

### PR DESCRIPTION
**Pull request by eskrano**
Add short trans variant

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but I don't think we need an alias for an alias tbh.

**Comment by ConnorVG** [comment]
I reckon this is a bit too complex, we should cover forward compatibility without the requirement of multiple location changes by the result of simplistic code duplication. I recommend instead that we go this route:

```if (! function_exists('t')) {
    /**
     * Short function trans() .
     *
     * @return \Symfony\Component\Translation\TranslatorInterface|string
     *
     * @see trans
     */
    function t()
    {
        return call_user_func_array('trans', func_get_args());
    }
}```

**Comment by eskrano** [comment]
@GrahamCampbell its good for templates .

**Comment by GrahamCampbell** [comment]
You do release that suggestion there was just :trollface:?

**Comment by ConnorVG** [comment]
To be fair, though, @eskrano... You could have this in your application and use it yourself rather than have it added to the base framework.

Composer:
```json
"autoload": {
    "files": ['bootstrap/helpers.php'],
}
```

Place it in `bootstrap/helpers.php`, `composer dump-autoload`.

**Comment by taylorotwell** [comment]
No plans to add to core.

**Pull request closed without merging**
