### PR TITLE
[5.2] Add loadIfNeeded function to Model.php

### PR DESCRIPTION
**Pull request by yalexyu**
Note: Moved from #12261 

`loadIfNeeded` is a utility function that reduces boilerplate required in loading relations if they aren't already loaded. 

Example:

```
$user = User::query()->find(1);
if (!$user->relationLoaded('someRelation')) {
    $user->load('someRelation');
}
if (!$user->relationLoaded('someOtherRelation')) {
    $user->load('someOtherRelation');
}
```

With `loadIfNeeded`:

```
$user = User::query()->find(1);
$user->loadIfNeeded(['someRelation', 'someOtherRelation]);
```

### CODE REVIEW

**Comment by KnutHelland** [comment]
It probably needs a test as well?

**Comment by yalexyu** [comment]
@KnutHelland I've added a test. Please let me know if it's sufficient and/or if I should do anything else.

**Comment by acasar** [comment]
Hmm these tests are not actually testing anything since you duplicated the entire logic in tests.

**Comment by KnutHelland** [comment]
Very good point from acasar. Maybe you can rewrite your test to something more like this? 

```
    public function testLoadIfNeeded()
    {
        $model = m::mock('EloquentModelStub');
        $model->shouldReceive('load')->once()->with(['foo'])->andReturn($model);
        $model->shouldReceive('relationLoaded')->once()->with(['foo', 'bar'])->andReturn(['foo']);
        $model->loadIfNeeded($model);
        // ... and so on
    }
```
Don't think it should be necessary to create one more stub in the bottom of the file just to test this simple function. Mocker will do the trick.

Also, someone should probably tell if `loadIfNeeded` is a good name for this function? I'm not that into Laravel (and should probably not involve in this discussion at all). But there is already one method in `Model` with a similar behaviour named `bootIfNotBooted`, so if that's the naming convention, then this one should be `loadIfNotLoaded`.

And I think that is a more descriptive name as well, if it was up to me. Because that is exactly what it does. The name `loadIfNeeded` is more vague. When is it needed to load? Oh, it is when it is not loaded.

**Comment by JosephSilber** [comment]
You should squash those 7 (!) commits into one.

**Comment by yalexyu** [comment]
Thanks for the feedback, everyone! I'll create a new PR with the necessary changes.

**Pull request closed without merging**
