### PR TITLE
[11.x] Fix ratio validation for high ratio images

### PR DESCRIPTION
**Pull request by ahmedbally**
When uploading images with resolution of 1366x768 which has ratio 16/9 validation fails
so i go with solution to solve the issue provided with test case of the 16/9 ratio
its also increase the precise for other ratios

### CODE REVIEW

**Comment by vlakoff** [comment]
I have a bit of trouble to understand this change, and to determine if it is really correct.

To summarize, you have replaced:
`max($width, $height)`
with:
`max(($width + $height) / 2, $height)`

(and the larger the result is, the lowest the precision (i.e. tolerance) is, and it turn the "stricter" the aspect ratio validation is)

The points I have trouble with:
* You are discarding `$width`. That seems to introduce a bias. Previously, `$width` and `$height` had the same "importance". My point is that 16/9 (1366x768 image) and 9/16 (768x1366 image) should validate exactly the same. Your code changed handling of the former, but changed nothing with the latter.
* Considering a 1366x768 image, `($width + $height) / 2` gives 1067. So this value 1067 is the new max, whereas previously it was 1366. I have just a bit of trouble to understand the rational behind this calculated value.

Provided that the value of `($width + $height) / 2` is correct to consider, I think the proper fix would not be `max(($width + $height) / 2, $height)`, but just `($width + $height) / 2`.

**Comment by vlakoff** [comment]
I'm thinking of the following approach:

```php
$desiredRatio = $numerator / $denominator;

$actualRatio = $width / $height;

$otherRatio1 = ($width + 1) / $height;
$otherRatio2 = ($width - 1) / $height;
$otherRatio3 = $width / ($height + 1);
$otherRatio4 = $width / ($height - 1); // TODO: avoid division by 0 if $height === 1

$success = abs($desiredRatio - $actualRatio) === min(
	abs($desiredRatio - $actualRatio),
	abs($desiredRatio - $otherRatio1),
	abs($desiredRatio - $otherRatio2),
	abs($desiredRatio - $otherRatio3),
	abs($desiredRatio - $otherRatio4),
);
```

We test if the ratio of the image is the closest possible to the desired ratio. We try with width or height changed by 1, and if we were the closest possible, these other 4 cases will have ratios that are further to the desired ratio.

This approach seems to be correct, but I hope there is some way to simplify the code.

**Comment by vlakoff** [comment]
The above snippet fails with a 1366x768 image, because 1365x768 would be actually closer to the desired 16/9 ratio.

So, I tried another approach: providing the actual width, or the height, calculate the other dimension using the desired ratio, and test if the result matches the actual other dimension. For instance:

Desiring a 16/9 ratio:
* an image with a 1366 px width should have a 768.375 px height (calculated by $width * denominator / $numerator), which is then rounded to 768 px.
* an image with a 768 px height should have a 1365.333 px width (calculated by $height * numerator / $denominator), which is then rounded to 1365 px.

Though, note how our 1366x768 image succeeds using the former calculation, but fails using the latter!

Also, as we calculating using floats, there is some "imprecision" due to the nature of floats. Executing the latter calculation, I got results such as float(1366) or even float(1366.01), whereas the proper result is 1365.333…

A solution could be, when the other dimension is between two integers (i.e. the image can't perfectly achieve the desired ratio), to accept both the lower and the upper integer. But this would allow for too much imprecision with small images, for instance, desiring the 16/9 with an image of 5 px width, we should really have a 3 px height, not 2 px.

**Comment by vlakoff** [comment]
(still thinking of loud, hope it doesn't bother you)

Considering the pitfalls I exposed in my above post, I figured out this approach:

```php
$calculatedHeight = round($width * $denominator / $numerator);
$calculatedWidth = round($height * $numerator / $denominator);

if ($height === $calculatedHeight || $width === $calculatedWidth) {
    // Pass
}
```

If at least one of the two calculations matches, we're good. As shown previously, a correct image could have only one calculation that matches. Of course, it is possible that both calculations match. And contrarily, if no calculation matches, we are certain there exists a more appropriate width/height pair.

Nervertheless, I figured out another issue: if a calculated width/height has a ".5" decimal (e.g. 42.5), there is no particular reason to round it up, i.e. it should be equally acceptable to round it down. Sadly, supporting that case leads to a more complicated code:

```php
$calculatedHeight = $width * $denominator / $numerator;
$calculatedWidth = $height * $numerator / $denominator;

if (
    $height === round($calculatedHeight, 0, PHP_ROUND_HALF_UP)
    || $height === round($calculatedHeight, 0, PHP_ROUND_HALF_DOWN)
    || $width === round($calculatedWidth, 0, PHP_ROUND_HALF_UP)
    || $width === round($calculatedWidth, 0, PHP_ROUND_HALF_DOWN)
) {
    // Pass
}
```

**Comment by ahmedbally** [comment]
I see your concern but i tried to find an equation to solve almost of ratios, without breaking changes
I thinks of almost all these cases of small images and large images
Your solution may need more tests in some images there is over 4 pixel for difference
You can create pull request with your solution

**Pull request merged**
