### PR TITLE
[5.2] Force the relation to have the connection of the parent

### PR DESCRIPTION
**Pull request by zaherg**
Some times when you have many connections defined and you need to change the connection for one of the Models, but if this Model has a relations with other Model it will not work, the relations will not work at all.

This small change, make sure that the connection to the child model will be the same as the parent model.

It may not be something everyone needs, but I found it useful in my case.

Cheers

### CODE REVIEW

**Comment by tomschlick** [comment]
Huge 👍  from me. This has been a big PITA of using multiple databases for a multi-tenant app. The workaround is that you don't eager load models that "cross the databases" but thats not fun at all.

**Comment by themsaid** [comment]
I think we shouldn't force same connection, cause sometimes you might have a model whose table is in a different database. Maybe we can make it optional, as a second parameter of the `on()` method for example.

**Comment by tomschlick** [comment]
Ah I just read this wrong, I thought it was getting the connection FROM the child model not from the parent. Disregard the 👍  then.

**Comment by taylorotwell** [comment]
Holding off on this for now then.

**Comment by linuxjuggler** [comment]
I agree that `on` function should have something like that, but if we look at the current [code](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L607)  we will see that `on` function do nothing except creating a new instance and set the connection for the parent not the child nor vice versa.

another suggestion that I have is to add the forceConnection parameter to all the relations functions so that they will be able to either force the connection to that relation, and since you will be able to define many functions for the relation you can have one with forced connection and the other one depending on the model connection, what do you think @taylorotwell  & @themsaid .

**Comment by linuxjuggler** [comment]
@tomschlick in this changes, the parent is the one who initiate the connection for example if you want to get the `user posts` then the user here is the parent, and it will use the user connection, but if the relation were from the posts to the users, then the posts is the parent here.

**Pull request closed without merging**
