### PR TITLE
[5.1] Inject the database connection into the migration classes

### PR DESCRIPTION
**Pull request by rayrutjes**
Automatically inject the database connection into the migration up and down methods.

### CODE REVIEW

**Comment by taylorotwell** [comment]
You can use the `DB` facade to execute something against the database.

**Comment by RayRutjes** [comment]
The originally idea was to avoid having to use the Facades, for example when using Lumen, please take a look here:https://github.com/laravel/framework/pull/8634
This is just a way to make those migration decoupled from the facades. People could still use facades, but could also use the connection directly.

**Comment by DsXack** [comment]
:+1:

**Comment by DsXack** [comment]
We like not use facades

**Comment by DsXack** [comment]
@taylorotwell why we should use https://github.com/barryvdh/laravel-ide-helper for syntax highlight and use autocompletion even in the lumen?

**Comment by taylorotwell** [comment]
Not using facades in migrations is just borderline superstitious and I
really don't want to cater to that. Sorry.

**Comment by sebastiaanluca** [comment]
@RayRutjes @DsXack Was also looking for a way to prevent using facades in Lumen (nothing to do with being superstitious btw, just a more unified approach as I don't use facades anywhere).

Anyway, just ended up creating a BaseMigration:

```php
<?php

use Illuminate\Contracts\Foundation\Application;
use Illuminate\Database\Migrations\Migration;

class BaseMigration extends Migration {
    
    /**
     * @var Application
     */
    protected $app;
    
    /**
     * @var \Illuminate\Database\Schema\Blueprint
     */
    protected $schema;
    
    public function __construct()
    {
        $this->app = app();
        $this->schema = $this->app['db']->connection()->getSchemaBuilder();
    }
    
}
```

Works like a charm with `$this->schema->…` if that's what you're looking for.

**Comment by DsXack** [comment]
@sebastiaanluca, you use global `app()` function. This like facades. I can not use a static functional because it does not allow two or more instances of applications within a single request. Besides - the facades do not provide any IDE tips and autocompletion. I understood I did not do it in laravel. It can be used in zf2 and simfony.

**Comment by GrahamCampbell** [comment]
> you use global app() function

That's just as bad as using facades for those that don't like facades. Infact, imo, it's worse.

**Comment by DsXack** [comment]
I think that this issue (about facades) has been discussed many times. I was just hoping that will provide an opportunity not to use the facades. But it's not.

**Comment by petrgrishin** [comment]
:+1:

**Comment by DsXack** [comment]
@taylorotwell, I agree that it suevereie when we use laravel. But in the lumen have the option ["not to use the facades"](https://github.com/laravel/lumen/blob/master/bootstrap/app.php#L22). What it is, if for any reason it will still have to include?

**Comment by crynobone** [comment]
Lumen will always include/enable facades for console regardless of `bootstrap/app.php`.

**Pull request closed without merging**
