### PR TITLE
[5.6] Serialize relationships

### PR DESCRIPTION
**Pull request by browner12**
resubmission of #21191 to master branch due to breaking changes.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I was able to completely comment out the following code with no tests failures, indicating it is not tested currently:

screen shot 2017-09-21 at 9 32 12 am

**Comment by browner12** [comment]
well then... i'll take another stab at that 😑

**Comment by taylorotwell** [comment]
Added a test for that.

**Comment by browner12** [comment]
thanks @taylorotwell

**Pull request merged**
