### PR TITLE
[5.6] Change handling of domain names by validateUrl regex

### PR DESCRIPTION
**Pull request by ColinBohn**
### Issue
The current validateUrl regex returns false negatives for local domains ending in a number, such as:
- http://localdomain1
- http://2018-19

Additionally the current validateUrl regex returns false positives for domain names with invalid symbols, such as:
- http://-google.com
- http://google-.com
- http://goo^gle.com

### Solution
This pull request changes the domain portion of the validateUrl regex to a more generalized pattern.

The first group matches zero or more of:
- a single unicode letter or number; followed by a dot OR
- a single unicode letter or number; followed by zero or more letters, numbers, or minuses; followed by a single letter or number; followed by a dot

The second group matches once:
- a single unicode letter or number OR
- a single unicode letter or number; followed by zero or more letters, numbers, or minuses; followed by a single letter or number

This pattern passes all existing test cases, as well as a few more added in to test for the issue to be fixed by this PR.

### CODE REVIEW

**Comment by mnabialek** [comment]
So after this change `https://localdomain1` will be considered really as valid url ? I wouldn't like real users to use urls like this.

**Comment by ColinBohn** [comment]
@mnabialek The current validateUrl tests would imply that it is intended to return true for local network domains such as http://localhost, as can be seen in the below entries in **validUrls**:
https://github.com/laravel/framework/blob/9a912d6f7da4d15144d73afc9213a5ef0f8db3e2/tests/Validation/ValidationValidatorTest.php#L2051
https://github.com/laravel/framework/blob/9a912d6f7da4d15144d73afc9213a5ef0f8db3e2/tests/Validation/ValidationValidatorTest.php#L2057

The issue raised in this PR is that because of a bug in the current pattern for validateUrl, adding a number to the end of a local domain (e.g. http://localhost1) causes the validator to return false, while that should actually be valid.

**Comment by devcircus** [comment]
IMO before changing this regex, maybe it would be good to open an issue on the ideas repo and discuss it first. It's a large regex taken from symfony and shouldn't be changed without careful consideration from not only the community but the core maintainers as well. It looks like it has changed a little over on the symfony repo too, so maybe those changes should be considered also? Just a thought.

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Pull request closed without merging**
