### PR TITLE
[8.x] Avoid renaming collections and macroable

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Laravel 8 introduces new (almost) stand-alone `illuminate/collections` and `illuminate/macroable` packages, however this unfortunately came with renaming the existing classes. The solution to try and mitigate this is sub-standard IMO, and I think it's best we simply don't rename the classes at all.

Why was the old compatibility solution bad? Consider the following code:

```
function f(Illuminate\Support\Collection $c) {}

f(new Illuminate\Collections\Collection);
```

This will crash! That is, existing code that uses the old collection names cannot handle the new class names. This is really no good, and in particular means packages will struggle to support both Laravel 6 LTS and Laravel 8 together, for example. The same goes for apps: in practice one would really have to changes all code to use the new classes.

So, why not just **not rename the classes**. Problem solved. Easy upgrading for everyone! 🚀

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Test failure is unrelated. All branches are failing with the same error.

**Comment by jmarcher** [comment]
What happens if someone requires only `illuminate/database` (illuminate/database itself requires `illuminate/support` but this wont include the collections) won't this be a problem for those people not using the entire framework?

**Comment by GrahamCampbell** [comment]
> but this wont include the collections

Yes, it will include the collections. The support package depends on the collections package. :)

**Comment by GrahamCampbell** [comment]
Also, note that this PR is not about splitting out a separate collections package. That has already been done. This PR is addressing the namespacing of the classes.

**Comment by helori** [comment]
Couldn’t we use a custom namespace in composer psr-4 so that old classnames point to the new renamed ones ? I usually don’t like this kind of hack but it would temporarily solve packages compatibility and would allow upgrades at low cost, before having to rename everything 🤔

**Comment by deleugpn** [comment]
Since `illuminate\support` requires `illuminate\collections`, wouldn't it be better to add classes to the Support class that extends the original classes, but tag them as deprecated? You get the benefit of not breaking people's apps, the original code was pushed upwards to the collections package and Laravel 9 or 10 can remove the dummy class.

**Comment by GrahamCampbell** [comment]
> Since illuminate\support requires illuminate\collections, it might be worth considering an option to add classes to the Support class that extends the original classes

This was already done, but that option is no good for the reason I explained in the OP.

**Comment by deleugpn** [comment]
Oh sorry I didn't understand that. Now that understand it better, I'd say it would be even better to `class_alias(Illuminate\Collections\Collection::class, '\Illuminate\Support\Collection');`.
This would force PHP to treat the Collection class as both variants and prevent the issue raised?

**Comment by gocanto** [comment]
wouldn't it better if we keep the `Support` namespace in those packages?

**Comment by driesvints** [comment]
@gocanto that's exactly what this PR does.

**Comment by gocanto** [comment]
We are just renaming the namespace through composer, right? - Unless, I missed something

**Comment by GrahamCampbell** [comment]
🥳

**Pull request merged**
