### PR TITLE
[9.x] Improves `serve` Artisan command

### PR DESCRIPTION
**Pull request by nunomaduro**
This pull request improves Laravel's `serve` artisan command. Here is the difference:

Screenshot 2022-07-22 at 18 32 56

So, the output got improved. The "time" is the only information highlighted, as is the only thing that actually changes. And we got to see a "rounded" duration of the request.

Note that, because we are using PHP's built-in server using a file such as "server.php", we don't have information regarding the Method, Uri, Response Code, etc.

In addition, unexpected output such as port already in use, or `.env` got changed, is displayed this way:

Screenshot 2022-07-22 at 18 00 50

Screenshot 2022-07-22 at 18 01 53

### CODE REVIEW

**Comment by antonkomarev** [comment]
@nunomaduro new implementation missing PHP version. Not sure it's really important, but may be useful in some edge cases.

**Comment by nunomaduro** [comment]
It's intentional.

**Comment by RosiersRobin** [comment]
Is there a reason why I'm getting an error serving from specific port and host?

```
ErrorException 

  Undefined array key 1313

  at \vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:250
    246▕                 $this->requestsPool[$matches[1]][1] = trim(explode('[200]: GET', $line)[1]);
    247▕             } elseif (str($line)->contains(' Closing')) {
    248▕                 preg_match('/\:(\d+)/', $parts[1], $matches);
    249▕
  ➜ 250▕                 $request = $this->requestsPool[$matches[1]];
    251▕
    252▕                 [$startDate, $file] = $request;
    253▕                 $formattedStartedAt = $startDate->format('Y-m-d H:i:s');
    254▕

  1   \vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:250
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Undefined array key 1313", "\vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php")

  2   \vendor\laravel\framework\src\Illuminate\Collections\Traits\EnumeratesValues.php:264
      Illuminate\Foundation\Console\ServeCommand::Illuminate\Foundation\Console\{closure}("[Tue Jul 26 17:26:27 2022] 127.0.0.1:1313 Closing
")
```

This occures when running serve this way: `php artisan serve --port 80 --host 0.0.0.0`

and accessing the served site via `http://development.docker/`.

**Comment by ankurk91** [comment]
Rather than showing `~0` seconds, can we show milliseconds?

**Comment by nunomaduro** [comment]
@ankurk91 It's not possible due PHP Built-in server limitations.

**Comment by netomarchiori** [comment]
@nunomaduro looks great! what needs to be changed in the project to get this new version? I'm able to see the new version only on newly created projects, but not on the ones that were update to v9.x. thanks!

**Pull request merged**
