### PR TITLE
Method is declared as void and shouldn't return anything

### PR DESCRIPTION
**Pull request by Whyounes**

### CODE REVIEW

**Comment by TheShiftExchange** [comment]
You should just change the description in the docblock.

If you change the actually `return` - you might cause unintended consequences - i.e. someone might have a function that actually relies on the return you've removed...

**Comment by GrahamCampbell** [comment]
This is totally pointless anyway.

**Comment by Whyounes** [comment]
I made a PR to understand the difference in the return value.
@GrahamCampbell You're really polite as always :)

**Comment by franzliedke** [comment]
Something like this was recently merged, so I wouldn't quite call it pointless, either...

**Comment by GrahamCampbell** [comment]
> so I wouldn't quite call it pointless

I would. This makes zero difference to the code. `void` really means, "don't rely on the output", so you can assume it not to return anything. Anyway, returning another function marked as void is fine anyway. If it ain't broke, don't fix it, and that's coming from me!

===
*Disclaimer:*
My opinions and comments are not the official view from Laravel or Taylor, they are solely my opinion.

**Comment by Whyounes** [comment]
@GrahamCampbell Most of your contributions are fixing `spaces`, `line feed`, etc. which can be called pointless using your arguments.
Just a small advice: please fix your attitude, you should be nice to people.

**Comment by GrahamCampbell** [comment]
@Whyounes I do not see coding style as totally pointless, or indeed compliance with standards. Your proposed changes do not fall into that category. One could make small changes like this for ever with no gain. There needs to be a point where we take a step back and look at why it is we're actually making changes. Taylor took the decision to close this, and I totally agree with him.

**Comment by GrahamCampbell** [comment]
I think we're done here really.

**Pull request closed without merging**
