### PR TITLE
[5.5] Allow to compare model with 'null'

### PR DESCRIPTION
**Pull request by bohdan-shulha**
This merge request will allow to compare models in situations like we have a user and an order may/may not have a person.

In pseudocode:
```
class Order extends Model
{
   public $manager = null;
}
```

```
public function myAction(Order $order)
{
    if (! Auth::user()->is($order->manager)) {
        throw new IllegalAccessException();
    }
}
```

### CODE REVIEW

**Comment by bohdan-shulha** [comment]
BTW, there might be compability issues with optional argument. Is it possible to remove type hinting and add `instanceof` chek?

**Comment by jmarcher** [comment]
This limits the Framework to only work in PHP 7.1

**Comment by GrahamCampbell** [comment]
This won't work. We can allow `null` by simply updating the code to have a default value. Please update this PR.

**Comment by taylorotwell** [comment]
Just remove the entire type-hint.

**Comment by bohdan-shulha** [comment]
I've fixed issue guided by @taylorotwell answer. Should I create a new pull request? Can it be merged at all? I have a little misunderstanding with PR approval process, so many status changes in such little period of time confused me a bit :(

**Pull request closed without merging**
