### PR TITLE
expected behavior like works in laravel 5.1

### PR DESCRIPTION
**Pull request by mmeshkatian**
See this example :
Model::where([‘a’=>’b’,’c’=>’d’])->orwhere([‘a’=>’b’,’c’=>’d’])

Expected use “and” between orwhere array but “or” used its not true logically

### CODE REVIEW

**Comment by mmeshkatian** [comment]
src/Illuminate/Database/Query/Builder.php

**Review by MohammadHemmati — APPROVED** [review]
yes it's cool and i have same problem

**Comment by jmarcher** [comment]
Provide a description of why this is needed.

Tests should also be provided.

**Comment by ayaka209** [comment]
https://github.com/laravel/framework/issues/24755#issuecomment-402731369

really strange behavior, maybe need to document it.

**Pull request closed without merging**
