### PR TITLE
[10.x]: Add Blade @use directive

### PR DESCRIPTION
**Pull request by simonhamp**
This is a variation on #49177 as I talked myself into a slightly better approach.

This is only an addition, so shouldn't cause any trouble or disturbance - unless someone has create a custom Blade directive called `@use`.

A minor addition for convenience when trying to use classes/enums in your Blade templates.

### Benefits
- 1 line instead of 3 🔥
- Less code to type ⏱️
- Makes templates look cleaner 🧹
- Better than abusing `@inject` just for enums 😅

### Example
```blade
{{-- Before --}}
@php
use \App\Enums\WidgetStatusEnum as Status;
@endphp

{{-- After --}}
@use('App\Enums\WidgetStatusEnum', 'Status')

@use('App\Models\Bar')

{{ Status::Foo }}

{{ Bar::first() }}
```

### Caveats
IDE support won't be there initially for folks, so there will be squigglies.

### CODE REVIEW

**Comment by PerryvanderMeer** [comment]
Would it be possible to make the second parameter optional and use the class name by default?

```php
@use('App\Enum\StatusEnum')

{{ EnumStatus::Foo }}
```

**Comment by simonhamp** [comment]
@PerryvanderMeer great suggestion! Added

**Comment by lazer-hybiz** [comment]
would `@use(App\Models\Bar::class)` work? (or even better `@use(App\Models\Bar)`)

**Comment by simonhamp** [comment]
@lazer-hybiz `@use(App\Models\Bar)` will work. `@use(App\Models\Bar::class)` _won't_, because you wouldn't write that in a normal `use` statement.

**Comment by taylorotwell** [comment]
> Would it be possible to make the second parameter optional and use the class name by default?
> 
> ```
> @use('App\Enum\StatusEnum')
> 
> {{ EnumStatus::Foo }}
> ```

I actually don't think you can make this assumption. You can import a namespace without importing a class.

```php
use App\Repositories;

Repositories\UserRepository::all();
```

**Comment by dillingham** [comment]
Could you replace ::class with nothing when compiling or would that not actually help IDE support

**Comment by simonhamp** [comment]
@dillingham could do... but why write those extra characters when you don't need to?

**Comment by inxilpro** [comment]
We've actually had this in our app for ~6 months, and at least with PhpStorm it's quite easy to add IDE support by just configuring a new blade directive. It works great!

**Comment by liamkeily** [comment]
> We've actually had this in our app for ~6 months, and at least with PhpStorm it's quite easy to add IDE support by just configuring a new blade directive. It works great!

Please could you share the PHPStorm settings for this new blade directive. I attempted this myself but the class being defined with a string seems to make it tricky to configure perfectly.

This is what i tried:

image

This is how it's displaying in my IDE:

image

vs how it displays without the new directive:

image

**Pull request merged**
