### PR TITLE
[5.5] Clean elses

### PR DESCRIPTION
**Pull request by carusogabriel**
I've removed the `else`s when we have already returned something :put_litter_in_its_place:

### CODE REVIEW

**Comment by lagbox** [comment]
good luck

**Comment by sisve** [comment]
@carusogabriel What bugs does this fix? What problems does it resolve? Does this simplify anything for our users?

**Comment by carusogabriel** [comment]
@sisve Is a mantra that I learned and follow :pray:: 
> There is no else!

We can simplify ways (I don't know if it is the correct word here) in our code, instead of two, just one. If we've already exited the code, nothing else will be executed, soo, why `else`? If it exited the code, continue to execute, no enter in else statement.

**Comment by deleugpn** [comment]
Relevant: https://github.com/laravel/framework/pull/21862, https://github.com/laravel/framework/pull/21767, https://github.com/laravel/framework/pull/20900

**Comment by carusogabriel** [comment]
I just can't get why he doesn't merge it. It's cleaner, reduce complexity and other stuff :disappointed:

**Comment by sisve** [comment]
> It's cleaner, [...]

That's your personal opinion.

> [...] reduce complexity [...]

That's your personal opinion.

> [...] and other stuff

That's slightly vague...

**Comment by carusogabriel** [comment]
@sisve About reducing complexity: https://www.slideshare.net/guilhermeblanco/php-for-adults-clean-code-and-object-calisthenics (slide 33 and beyond)

**Comment by sisve** [comment]
The slideshow has 15 slides with code changes, and on slide 48 claims that some of the changes has reduced the cyclomatic complexity. However, the presence of an else-clause does not affect cyclomatic complexity at all. So the argument about reduced cyclomatic complexity is not about the else-clauses, but the other changes he does over the 15 slides.

**Comment by sisve** [comment]
To be clear; I am not saying that your suggestions will make the world a worse place. I'm just pointing out that these things are primarily opinion-based, and as such, may not conform to the mind of The Merger.

One would imagine that having some kind of coding guidelines for these things would help in the future...

**Comment by carusogabriel** [comment]
No problem, opinions and points something diverges :sweat_smile: 

About `Coding Guidelines`: very interesting :thinking:

**Comment by taylorotwell** [comment]
Don't typically merge these. Only merging this one because it has only 1 small merge conflict against master. Thanks 😅

**Comment by Stretsh** [comment]
Nice... Now others with PRs get to do extra work, because of some personal preferences...

**Comment by cbj4074** [comment]
And furthermore, code-folding is no longer possible. Enjoy.

no-more-code-folding

@taylorotwell In my humble opinion, these syntactical preferences should either be ignored (as you have done in the past) or articulated in a standard that is posted clearly to https://laravel.com/docs/master/contributions#coding-style . These are frivolous changes that waste peoples' time and create unnecessary merge conflicts (as can be seen in this specific instance).

**Comment by jleonardolemos** [comment]
Yeah these changes may seem to be useless, but they help us undertand the framework, thanks @carusogabriel

**Comment by 36864** [comment]
Why is a function more difficult to understand when you have code paths clearly defined?

If I want to determine what happens when an if statement fails, it's easier to scan for an else statement than to scan for braces, especially in nested code blocks.

Previously, if I wanted to know what a function returns, all I had to do was scan backwards for a return statement and check if it was in an if/else block. Now I need to scan the entire function for returns that may or may not be in conditional blocks.

Making code less obvious, less pedantic or less explicit does not make it cleaner or more readable, it does the exact opposite.

The next logical step here is to just use ternary statements for all of these methods like ` return $condition ? $success :  $failure;`. That's less code, so it has to be better, right? It's also a lot more readable because you only have one return statement instead of having multiple statements and having to figure out when each of them is executed.

**Comment by cbj4074** [comment]
*This!!!* ^ Very well stated, @36864 :clap:

**Comment by Stretsh** [comment]
This PR was submitted following a mantra that @carusogabriel learned and follows: "There is no else". I know of a lot of devs who would consider this mantra dangerous. It is "using something that is supposed to be relative (case by case) as absolute and then forcing others to adhere to it".

@36864 said:
> Making code less obvious, less pedantic or less explicit does not make it cleaner or more readable, it does the exact opposite.

A thought that Laravel was proud to be written in clean, readable code, since that is the mantra of folks close to the framework. Hence my failure to understand why @taylorotwell finally caved in, after ignoring such requests for a while.

**Comment by piiih** [comment]
@Stretsh 
```
Nice... Now others with PRs get to do extra work, because of some personal preferences...
```
What do you mean with 'extra work'?

**Comment by 36864** [comment]
@a-komarev 
I'm on board with guard clauses to prevent nested conditionals. This is not what's being done here. An else statement is not a nested conditional.

Ultimately, I'm okay with either style being used. What I'm not okay with is the style being changed for no reason other than someone thinking it's "more readable", and making the code inconsistent. 

Inconsistency is what really annoys me here. If early returns are the holy grail and `else` clauses are the devil, why were `elseif` statements kept? 
Either choose early returns with no else statements, or proper code path blocks with else statements. Going at it half-assed and leaving the job half-finished is just a waste of everybody's time.

**Comment by a-komarev** [comment]
@36864 I think because it's much harder to remove `elseif` statements. It's really complex work to refactor all the stuff at once and more harder to review such PRs. If you are so mad on this inconsistency and `elseif` statements not being touched - you could make PR which do the next step to better code.

**Comment by 36864** [comment]
>much harder to remove `elseif` statements

What? Let's look at a real example from this PR: (comments removed for brevity)
```
 protected function getDsn(array $config) 
{
  if (in_array('dblib', $this->getAvailableDrivers())) {
    return $this->getDblibDsn($config);
  } elseif ($this->prefersOdbc($config)) {
     return $this->getOdbcDsn($config);
  } else { 	
    return $this->getSqlSrvDsn($config); 	
  }
}
```
This was refactored to just remove the final else statement. Removing the elseif statement would have required the following additional changes:
 - delete the letters [e, l, s, e] from `elseif`

If I were to make a PR regarding this, it would be to revert the changes made. 
Guard statements are useful for two things: Preventing excessive conditional block nesting and short-circuiting execution when invalid data or an invalid application state is detected. 
Another tool that's quite useful for preventing nested conditionals is the elseif statement. You get all the joy of having separate conditions without the indentation hell of multiple if/else blocks. Whether guard statements are more readable than chained elseif blocks is a matter of opinion.

The only file where removing the else block can make sense, under the guise of "we don't need it because guard statements" in this entire PR is Migrator.php since the if statement is handling what could be interpreted as an error (attempting to rollback migrations when there are no migrations to rollback).

**Comment by a-komarev** [comment]
@36864 Good catch. You are right, in this example its pretty clear. I was talked about making changes in all framework code where `elseif` is met.
Want to try your luck and check if this change will be merged? :rofl:

**Comment by cbj4074** [comment]
The next thing you know, we'll be arguing about tabs vs. spaces! Oh, wait... The only sensible argument in this thread is that this preference needs to be standardized, one way or another (and so far, only three people, myself excluded, have advocated for as much). I care a lot more about making useful contributions to the code-base than reverting each other's work. This one's on you, Taylor. You set a precedent with this one, and it smacks of favoritism.

**Pull request merged**
