### PR TITLE
[5.7] Backport #27610

### PR DESCRIPTION
**Pull request by CupOfTea696**
A backport of #27610 for 5.7

### CODE REVIEW

**Comment by laurencei** [comment]
The PR you listed says

> Sent to 5.8 because of the breaking changes on the `Composer` class.

So that is why it is not in 5.7?

**Comment by devcircus** [comment]
Doesn't breaking changes go to master?

**Comment by sisve** [comment]
This does indeed sound wrong. If the original PR couldn't target 5.7 a few days ago for reasons regarding breaking changes, why would it be acceptable now? (The answer is probably a vague "it's probably not acceptable now".)

**Comment by driesvints** [comment]
I'm going to leave this to Taylor to decide upon but if anyone is using the Composer class then this will definitely cause some breakages.

**Comment by daylaborers** [comment]
What is the Workaround, we can't deploy and horizon crash's when we use some stuff

**Comment by driesvints** [comment]
@daylaborers upgrade to 5.8

**Comment by daylaborers** [comment]
This is not a workaround :D Thats a lot of work to test our Application

**Pull request closed without merging**
