### PR TITLE
[5.6] Allow callable array syntax in route definition

### PR DESCRIPTION
**Pull request by hulkur**
This PR will allow defining route actions as arrays

`Route::get('smth', [SomeController::class, 'methodName']);`

This has no direct benefit code-wise, but enables better navigation in IDE-s.

`is_callable` validates that specified class and method exist and only `is_array` check is needed.

### CODE REVIEW

**Comment by hulkur** [comment]
yes, navigating to correct controller from string is bothersome

**Comment by RikSomers** [comment]
Can't you just do that already tho, with about the same number of characters?

`Route::get('smth', SomeController::class . '@methodName');`

**Comment by hulkur** [comment]
i guess you can, but in php array is one of the callable syntaxes so I added that

**Comment by devcircus** [comment]
Nice addition. I've hacked this in for years.

**Comment by rentalhost** [comment]
It should works with code like `\Route::get('x', [ 'uses' => [ A::class, 'b' ] ])`?

**Comment by hulkur** [comment]
It does not currently.

**Comment by rentalhost** [comment]
Can you implement that? Seems that it could be done on line 47. It will make me very happy, once that I commonly use with `uses`. 😄

**Comment by hagabaka** [comment]
I think there are two problems with this implementation:

1. it doesn't honor the `Router`'s group namespace. By default (set in RouteServiceProvider), routes will look up controllers in the `App\Http\Controllers` namespace, so using the traditional syntax the controller name does not need to have that namespace prepended, including things like `Route::resource('users', UserController::class)`. But the array syntax requires the full class name.
2. It doesn't work with magic controller methods using `__call()`, Whereas using `Controller@method` works when the Controller does not have that method but handles it through `__call`.

I think these problems as well as lack of support of `['uses' => [Controller::class, 'method']]` can be fixed by changing [`Router::actionReferencesController`](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Routing/Router.php#L489) and [`Router::convertToControllerAction`](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Routing/Router.php#L504), which normalize the route action into the `['uses' => ...]` form and applies the group namespace.

**Comment by williamdes** [comment]
I would just add that you can not do :
```php
Route::get('/hello-world/{userId}', [
    'as'   => 'call_hello_world_please',
    'uses' => [ Hello::class, 'world' ],
]);
```
So you need to fallback to the string syntax ... :skull: 
```
Symfony\Component\Debug\Exception\FatalThrowableError: ReflectionFunction::__construct() expects parameter 1 to be string, array given in file /var/www/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php on line 22
Stack trace:
  1. Symfony\Component\Debug\Exception\FatalThrowableError-&gt;() /var/www/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php:22
  2. ReflectionFunction-&gt;__construct() /var/www/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php:22
  3. Illuminate\Routing\RouteSignatureParameters-&gt;fromAction() /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php:471
  4. Illuminate\Routing\Route-&gt;signatureParameters() /var/www/vendor/laravel/framework/src/Illuminate/Routing/ImplicitRouteBinding.php:24
  5. Illuminate\Routing\ImplicitRouteBinding-&gt;resolveForRoute() /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php:787
  6. Illuminate\Routing\Router-&gt;substituteImplicitBindings() /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:39
  7. Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle() /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
  8. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
  9. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
 10. Illuminate\Auth\Middleware\Authenticate-&gt;handle() /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 11. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 12. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php:58
 13. Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle() /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
 14. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 15. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
```

**Comment by hulkur** [comment]
This was rejected in https://github.com/laravel/framework/pull/24589

**Pull request merged**
