### PR TITLE
feat(enum): add http status enum

### PR DESCRIPTION
**Pull request by christophstockinger**
More info in pull request #47333

### CODE REVIEW

**Comment by rodrigopedra** [comment]
I've been using enums a lot, but in this particular case, in the meanwhile, the `Illuminate\Http\Response` class has all HTTP statuses as public constants. It inherits from its `Symfony\Component\HttpFoundation\Response` base class.

I don't think there is a great advantage, right now, over using these constants already provided. As actually I guess the sample code you have on #47333 will end being like:

```php
public function index(Request $request) {
     // ... some databse logic ... 
    return response()->json(['some data'], HttpStatus::OK->value)
}

public function store($data, Request $request) {
    // ... some databse logic ... 
    return response()->json(['created data'], HttpStatus::CREATED->value)
}
```

As I believe, Backed Enums does not automatically "unboxes" its value. 

So these helper functions would need to change to account for that. Did you try a helper like `response()->json()` works with your proposed enum?

Also, one could expect the `Request@status()` method to return an Enum instance to ease comparison, which would be a breaking change. *(in this case adding a complimentary `Request@hasStatus(...$statuses)` which accepts a variadic enum value list could be an option)*

**Comment by joelbutcher** [comment]
I personally think this PR would be better suited in a new major symfony version, instead of Laravel - but in such a way as to avoid breaking BC...

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by christophstockinger** [comment]
@rodrigopedra 
> Also, one could expect the Request@status() method to return an Enum instance to ease comparison, which would be a breaking change. (in this case, adding a complimentary Request@hasStatus(...$statuses) which accepts a variadic enum value list could be an option)

Can you explain that? I'm not sure what you mean? After all, in the whole context we are not talking about Request but Responses.

**Comment by rodrigopedra** [comment]
@christophstockinger 

You are correct, I meant to write `Response@status()` as when checking in a middleware. Thanks for the heads-up.

Nonetheless, an integer (current return value) would be different from an enum instance.

Sample code:

```php
public function hanlde($request, $next) {
    $response = $next($request);

    if ($response->status() === HttpStatus::NOT_ACCEPTABLE) {
        // will never get into here, as an integer will never equal an enum instance
    }

    return $response;
}
```

**Pull request closed without merging**
