### PR TITLE
Builder toggle function

### PR DESCRIPTION
**Pull request by justinasit**
A quick and painless function to toggle boolean column's value from true to false and vise versa. Equivalent to this example SQL code:

```
Update `posts` set `active` = !`active`;
```

This function prevents the need to loop through records and update them one by one. So instead of writing this:

```
foreach (Posts::all() as $post) {
  $post->active = !$post->active;
}
```

We can write this:

```
Posts::toggle('active');
```

### CODE REVIEW

**Comment by deleugpn** [comment]
Would you mind writing tests for this?

**Comment by staudenmeir** [comment]
This only works on MySQL. `"not $wrapped"` also works on PostgreSQL and SQLite. SQL Server requires `"$wrapped ^ 1"`.

I suggest a `Grammar::compileToggle()` method that you override in `SqlServerGrammar`.

**Comment by justinasit** [comment]
Thanks for the feedback guys, I'll do both of those things.

**Comment by phanan** [comment]
:/ IMHO such a feature is not universal i.e. not applicable for non-boolean columns, and hence should belong in userland.

**Comment by taylorotwell** [comment]
No plans to add this in its current form.

**Pull request closed without merging**
