### PR TITLE
Possibility to use where for where in clause with tests

### PR DESCRIPTION
**Pull request by evsign**
Just a way to use `where` for building `where in` sql clause)
How to use: 

``` php
$builder->where('id', [1,2,3]);
$builder->where('id', 'in', [1,2,3]);
$builder->where('id', '=', [1,2,3]);
```

All of these callings will be transformed in `select * from table where "id" in (?, ?, ?)`

### CODE REVIEW

**Comment by taylorotwell** [comment]
Prefer people just explicitly call whereIn.

**Comment by evsign** [comment]
@taylorotwell I too, but i thought its not about what we prefer, but about what people could use) I thought only about ease of use and intuitively behavior for people, and this not forcing using one method against another. 
Thanks)

**Comment by crynobone** [comment]
> I thought only about ease of use and intuitively behavior for people, and this not forcing using one method against another. 

```php
User::where('id', '!=', [1, 2, 3])->get();
```

Intuitively, you would expect this to output `SELECT * FROM `users` WHERE id NOT IN (1, 2, 3)`.

What happen when you use `<`, `>`, `>=`, or `<=`? Simply parsing it as `WHERE id IN (1, 2, 3)` would be confusing for many people, as this is an unexpected behaviour.

**Comment by evsign** [comment]
@crynobone Thanks. I reworked this issue and now:
```php
$builder->where('id', [1,2,3]);
$builder->where('id', 'in', [1,2,3]);
$builder->where('id', '=', [1,2,3]);
```
will produce `select * from table where "id" in (?, ?, ?)`
and
```php
$builder->where('id', '!=', [1,2,3]);
$builder->where('id', 'not in', [1,2,3]);
```
will produce `select * from table where "id" not in (?, ?, ?)`

All another callings will be with default behavior.

@taylorotwell may i send pr again with fixes for this feature? or this already not under consideration?)

**Pull request closed without merging**
