### PR TITLE
[5.4] [WIP] Make validator less monolithic structure

### PR DESCRIPTION
**Pull request by Skysplit**
This PR relates to laravel/internals#156 and is still work in progress

TODO:
- [ ]  Database validators
  - [ ]  `exists`
  - [ ]  `unique`
- [ ] `required_*` validators (required itself is done)
- [ ] `Validator::extend()`
- [ ] `sometimes()`
- [ ] `after()`
- [ ] Adding error messages translation
- [ ] Allow mapping parameters for non-builtin validators
- [ ] Mapping parameters for translator
- [ ] Remove obsolete tests that no longer match validator's API
- [ ] Add new tests for that API
- [ ] Review fix tests that are not passing
- [ ] Code refactor
- [ ] Write/polish documentation for validator and rules
- [ ] Document new possibilities for defining validation rules

Sorry for putting it in one large commit. I was playing with this validator for quite a long time and wasn't sure if methods remain the same or there will be need to change them.

### CODE REVIEW

**Comment by taylorotwell** [comment]
This would need a real thorough explanation of how this would benefit users with good examples of each benefit.

**Comment by KennedyTedesco** [comment]
The only thing that come to my mind is that this structure is a bit better to maintain. To the users, nothing of substantial. Correct me if I'm wrong.

**Comment by Skysplit** [comment]
The main goal is indeed maintenance of the code.

However, from my experience with current validator, the module translation implementation is inconsistent across validator. The thing I have on my mind is `Validator::replacer()`, which handles parameters replacement. In my opinion it should be handled by translation module (which, by the way, does not support languages other than english properly).

Also, there are few tweaks that current validator can handle:

Extended rules syntax
```php
$this->validate($request, [
    'foo.*.bar.*' => 'required|in:a,b,c',
    'foo.*.baz.*' => [
        ['min', 3],
        'numeric',
        'required',
        'in' => [1, 2 ,3]
    ],
    'foo.*.foo.*' => [
        \App\Validators\MyValidator::class => [
            'parameter_a' => 'value1',
            'parameter_b' => 'value2'
        ]
    ]
]);
```

Defining own rules
```php

class MyRule extends \Illuminate\Validation\Rule
{
    public function passes($attribute, $value, $parameters, $validator)
    {
        return true;
    }
}

Validator::extend('foo', MyRule::class);
```

Currently existing methods are supported as well
```php
Validator::extend('foo', function ($attribute, $value, $parameters, $validator) {
    return true;
});
Validator::extend('foo', 'MyClass@myMethod');
Validator::extend('foo', 'MyClass');
```

**Comment by fernandobandeira** [comment]
Seems good for maintenance since we could add these files to a folder like Rules and even create an artisan command like ``` php artisan make:rule NameRule ``` to create new rules.

**Comment by taylorotwell** [comment]
I'm not interested in the maintenance argument because currently validator is not that hard to maintain. I'm only interested in actual benefits to end users.

**Comment by Skysplit** [comment]
The main goal was to separate validation rules from actual validator for better readability and code maintenance, however while investigating current validator (even before I had rewriting it in my mind) I found that some part of validator uses translation messages for passing parameters, and other part uses replacers. So this became second goal of my PR - allow user to name parameters more easily and pass them to validator without calling replacers. This helps overriding laravel's translation package if one wants to (Currently you have to override Tranlsation AND Validation with it, because of this behavior).

Another benefit is possibility to reuse validation rules. Now we can reuse any validation rule in our custom validators .

**Comment by taylorotwell** [comment]
I really feel like it's going to be unlikely I merge this. The validator isn't that hard for us to maintain and I'm not sure we have any use case to benefit end-users that is really grabbing me. I would rather not split it into 50+ classes with no amazing benefit to end-users.

**Comment by Siprah** [comment]
http://www.portal2sounds.com/659#q%3Dkidding%2520me

**Comment by Skysplit** [comment]
@taylorotwell Laravel validator has translation/parameters module implemented really wrong way. I've been looking at validator code for a long time and there is no way one can easily override custom laravel translator with his, because you have to override validator as well. I do not think that's how it should work.

Also, offtoping a little bit, you may ask what is wrong with translations. As I said before, It does not support languages other than english well. I'm Polish, and if I'd want to build laravel app with proper translations, I am unable to, because Polish(and Russia, Arabic and many more) plural rules are much more complicated than just ranges `0 = plural`, `1 = singular`, `2-infinity = plural`.

**Comment by taylorotwell** [comment]
Perhaps there is a way to solve your problem without defining 50+ files though.

**Comment by Skysplit** [comment]
@taylorotwell To be fair, I do not see anything wrong with defining 50 files, each for own validation rule. You said, that validation class isn't hard for you to maintain. How come 3000+ lines file is not a problem to maintain and better solution that 50 files? With all respect, I just cannot agree with your approach.

**Comment by Skysplit** [comment]
Also, to support my arguments, this is how it looks in other frameworks:

Symfony: https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Validator/Constraints  
ZendFramework: https://github.com/zendframework/zend-validator/tree/master/src  
Yii2: https://github.com/yiisoft/yii2/tree/master/framework/validators

**Comment by fernandobandeira** [comment]
Some of them like Yii2 seems to group the validations by types they have Integer, Min , Max, etc in one file named NumberValidator, for example.

Not sure if a similar approach is viable but would reduce the number of files significantly.

**Comment by KennedyTedesco** [comment]
Personally I don't see any problems to have a lot of files, that's a natural consequence of object oriented programming.

On the other hand, the current implementation of the Validator looks good enough for now.

**Comment by Skysplit** [comment]
@fernandobandeira Indeed I find yii2 validator very well designed and easy to use. I kept 50 rules seperate, because I wanted to keep as much backwards compatibility as possible, and *yii2-way* would change how we could define rules. I think that it would be possible to rewirte current PR to work smilliarly to yii2 one. I'm calling @taylorotwell because I'd like to know his opinion on that approach.

@KennedyTedesco Overall it looks good, but details like `Validator::replacer()` make it really awful to me, and incredibly hard to extend (please see my previous comments).

**Pull request closed without merging**
