### PR TITLE
[5.1] Backport of using Str::studly to resolve driver method

### PR DESCRIPTION
**Pull request by arcanedev-maroc**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Sorry, 5.1 is closed for new features.

**Comment by arcanedev-maroc** [comment]
This is not a feature, it's a bug fix: https://travis-ci.org/ARCANEDEV/Units/builds/154271896

**Comment by arcanedev-maroc** [comment]
@taylorotwell can you tell us what you think about this ?

**Comment by GrahamCampbell** [comment]
It just means that package was relying on a feature only introduced in a later version.

**Pull request closed without merging**
