### PR TITLE
[5.1] Changed file permissions to 644

### PR DESCRIPTION
**Pull request by taoso**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This was proposed before and rejcted. Not sure how you still feel about this @taylorotwell.

**Comment by GrahamCampbell** [comment]
Ping @lucasmichot, @JosephSilber, @franzliedke, @crynobone. What do you guys make of this?

**Comment by crynobone** [comment]
1. What the potential security risk by not doing this?
2. What the affect on all unmerged PR?
3. Is there a way to avoid new file to be added as `755` in the future?

**Comment by lucasmichot** [comment]
@crynobone 1) No risk AFAIK, 2) but unmerged PRs will overwrite this new rights.
3) There is no way to simply enforce
This could be done only locally by Taylor (http://stackoverflow.com/questions/10783678/git-shell-script-execute-permissions-enforced) or with a build script

**Pull request closed without merging**
