### PR TITLE
[5.6] Route::viewDir() Method

### PR DESCRIPTION
**Pull request by imliam**
This helper method mimics the functionality offered by the relatively new `Route::view()` method (added in Laravel 5.5) but extends it by rerouting requested the URI at any number of sub-levels to match a view directory in the code base.

This makes it possible to create views with static content and not need to worry about updating routes to match them or using a CMS-style solution to manage them.

For an example, to see how it works, let’s imagine the following route definition:

```php
Route::viewDir('/pages', 'pages');
```

And the following directory structure for the views:

```
views/
├── auth/
├── errors/
├── layouts/
├── pages/
│   ├── about-us.blade.php
│   ├── faq.blade.php
│   ├── privacy-policy.blade.php
│   ├── team/
│   │   ├── developers.blade.php
│   │   ├── index.blade.php
│   │   ├── management.blade.php
│   │   └── marketing.blade.php
│   └── terms-of-service.blade.php
└── partials/
```

The following routes will be generated to match each of the views in the given directory:

```
/pages/about-us
/pages/faq
/pages/privacy-policy
/pages/team
/pages/team/developers
/pages/team/management
/pages/team/marketing
/pages/terms-of-service
```

I am aware this could probably be improved by moving the closure logic to the ViewController that Route::view(...) uses and to remove the use of helper functions, if need-be.

### CODE REVIEW

**Comment by sisve** [comment]
Why would this be better than creating static php files in the public directory? You're just adding lots of overhead (framework boot, routing, database connections, etc) for static files.

**Comment by ImLiam** [comment]
The same reason as `Route::view(...)` - you get the full benefit of having the framework loaded. You can gate it behind middleware, make use of all of the things Blade has to offer, helper functions (such as passing auth data through to a Vue component prop) etc.

**Comment by 36864** [comment]
If I understand this correctly, this would work like a controller that parses a wildcard route url to find a view? Essentially the same as:
```
//routes file
Route::get('/pages/{page?}', 'PageController@getPage');
//controller code
functino getPage($request, $page)
{
  $view = $this->parse_url($page);
 if(View::exists($view)) {
     return view($view);
  }
 abort(404);
}
```

I can see some uses for it, specifically adding a temporary page to a website without having to rebuild the route cache,

I can also see this functionality leading to developers just sticking all their views under a viewDir() route and skipping controller code entirely for most pages. I haven't decided if that would be an overall good or bad thing yet.

**Comment by taylorotwell** [comment]
No plans on adding to core. Could be a good package candidate.

**Pull request closed without merging**
