### PR TITLE
[5.5] Add datetime to scheduler

### PR DESCRIPTION
**Pull request by iwex**
This one needs for better logging understanding

### CODE REVIEW

**Comment by laurencei** [comment]
Wouldnt the log be timestamped? Why does the output here affect it?

**Comment by iwex** [comment]
@laurencei This lines will appear in supervisor logfile, in docker I track this file

**Comment by laurencei** [comment]
Why is it in the supervisor logfile? This is for the scheduler, not for queue daemons?

**Comment by iwex** [comment]
@laurencei oh, sorry, I push command's output to some logfile

**Comment by iwex** [comment]
@taylorotwell ?

**Pull request closed without merging**
