### PR TITLE
#17642 - Reset day parameter when using Y-m

### LINKED ISSUE #17642: [5.4] Validation Rule: date_format bug
As the title says, I may be missing something. The scenario is provided below.

# Versions used
> Laravel Version: 5.4.3
> PHP Version: 7.0.15
> Database Driver & Version: MariaDB 10.1.20

# Problem
> The Laravel 'date_format' validation rule on Requests fail on the date '2017-02'. It fails on non leap years when using the month '02' (February).

# Test Data
**Working on the following dates [Validation is successful]**
> 2016-01
> 2016-02
> 2020-02
> 2024-02

**Not working on the following dates [Validation does not match the format Y-m]**
> 2013-02
> 2017-02
> 2021-02

# Steps to Reproduce

**Create a request with the following rule**
> `return ['testDate' => ['bail', required, 'date_format:Y-m']];`

**Next steps**
> Create a sample input form, route, and controller that uses the request created.
> Input the test data provided above.
> Input test data '2017-02'. Expected: Validation Passed, Actual: Does not match the format Y-m

# Other notes
> The validation rule 'date' works properly even on non leap years when using the month '02' (February).
> Tested on Laravel 5.3, same error.

### PR DESCRIPTION
**Pull request by BramRoets**
This should fix #17642 

Note: this bug only happens when the computers date is set to 31/xx/xxx (or any date not existing in february)

### CODE REVIEW

**Comment by arjasco** [comment]
@taylorotwell @BramRoets  Unfortunately. This still doesn't fix the problem, it's making the assumption your format will be `Y-m` when the problem occurs. Thats not the case because when using `m-Y` or `Y/m` or whatever takes your fancy, it will still occur.

My pull request back in January https://github.com/laravel/framework/pull/17693 did solve the problem but got closed :(

```php
$date = DateTime::createFromFormat('!' . $parameters[0], $value);
```

Thats all it takes, I'm not sure why we can't just go with this, remove the extra test and thats the problem solved.

**Comment by rtheunissen** [comment]
@taylorotwell this bug is causing our app to crash badly today. It's the 31st of August today, which means that any month that doesn't have 31 days fails validation. The format we're using is `F Y`, but `June 2017` fails because `createFromFormat` returns `July 2017`.

The solution to prefix `!` works as far as I can tell. The [PHP documentation](http://php.net/manual/en/datetime.createfromformat.php) says:

> Without !, all fields will be set to the current date and time.

It's ridiculous to have to prepend the `!` ourselves.

@arjasco was on point here and his closed PR should be merged asap.

**Comment by rtheunissen** [comment]
It's also very difficult to override existing validation rules, unless I'm simply not seeing how this should happen?

**Comment by rtheunissen** [comment]
We're currently using this as an interim solution. 

Is it necessary to check that the date equals the value? Surely if it could be resolved at all should be sufficient?

```php
$validator->extend('hotfix_date_format', function ($attribute, $value, $parameters, $validator) {
            return (is_string($value) || is_numeric($value))
                && (DateTime::createFromFormat($parameters[0], $value) !== false);
        });
```

**Pull request merged**
