### PR TITLE
[9.x] add filename in output that is generated by generator commands

### PR DESCRIPTION
**Pull request by hAz5**
add filename in input that is generated by generator commands

before

before

after
after

### CODE REVIEW

**Comment by timacdonald** [comment]
If we consider this PR, please see this comment (https://github.com/laravel/framework/pull/33368#issuecomment-656995736) for reasoning and why it might be good to actually output the entire path, not just the filename.

**Comment by hAz5** [comment]
@timacdonald thank you for making me aware

this is the result of my last changes:

after2

@nunomaduro @timacdonald  Please If there is an issue, please let me know.

**Comment by driesvints** [comment]
I don't think we should add a warning there... It also feels weird the migration doesn't have a full path but the other ones do.

**Comment by hAz5** [comment]
> 

the migration command has --fullpath option but others don't have

can you tell me which tag I can use?

**Comment by nunomaduro** [comment]
Feel free to re-submit this pull request. Yet, the output should be consistent with other commands, and affect all the `make:*` commands. As such, would be cool something like the following:

If single file created:
```

[ INFO ] Model [app/Models/Foo.php] created successfully.

```

If multiple files created:

```

[ INFO ] Model and Factory created successfully.

    ⇂ app/Models/Foo.php
    ⇂ database/Factories/FooFactory.php

```

**Pull request closed without merging**
