### PR TITLE
[WIP] Better interface mocking

### PR DESCRIPTION
**Pull request by SamMousa**
Example of how interface should be mocked to prevent implicit requirements on concrete implementations.
See #11732

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but we just need to add a method_exists check really.

**Comment by SamMousa** [comment]
@GrahamCampbell you are unbelievable. Stop closing issues that are clearly too complicated for you to grasp.

**Comment by GrahamCampbell** [comment]
I understand what you are saying that this is technically incorrect without the method on the interface. I understand that just fine, but, this is not the only place where this occurs, and Taylor intentionally missed out some methods.

**Comment by SamMousa** [comment]
Ah so if you make errors consistently it's okay? 
If you require methods not in a contract don't typehint against the contract... It totally defeats the purpose of the contract. By closing these issues it cannot be discussed; there is no harm in leaving it open for more developers to chime in.

Basically what you are suggesting is that if Laravel requires me to implement an interface I should also go through the whole source code to see if there are any undocumented requirements on my implementation..

**Comment by GrahamCampbell** [comment]
They've already been previously discussed, as you can imagine.

**Comment by GrahamCampbell** [comment]
I'm also not stopping people from further discussion, it's just not a bug.

**Comment by SamMousa** [comment]
If they have been previously discussed how about linking to that discussion and documenting the decision somewhere? 
I am really curious to hear arguments in favor of calling functions on objects without any valid motivation for assuming the function exists...

I am also really curious to hear arguments in favor of making your tests always pass because they are not really testing what they are supposed to...

**Pull request closed without merging**
