### PR TITLE
[5.2] Added validation rule for unique values in an array

### PR DESCRIPTION
**Pull request by themsaid**
This validation rule will ensure a value is unique among other set of values in the array.

``` php
// This will fail
Validator::make(
   ['foo' => ['foo', 'foo']], 
   ['foo.*' => 'no_duplicates']
);
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
Hmm, I would have expected it to look like:

```
`foo' => `no_duplicates'
```

**Comment by themsaid** [comment]
@taylorotwell I've modified the code and made the validation method find the raw attribute (with asterisks) using a class property and use it with `Str::is` to check the other values.

**Comment by taylorotwell** [comment]
Hmm, my original comment was dumb I think. Not sure what I was thinking there. What was the original implementation of this PR like?

**Comment by themsaid** [comment]
```
Validator::make(
   ['foo' => ['foo', 'foo']], 
   ['foo.*' => 'no_duplicates:foo.*']
);
```

It was originally that way, the validator was having a single parameter `foo.*` which is the key it should look for duplicates at. The main purpose I made it accept a parameter is that I wasn't able to get the raw attribute name (with asterisk) from inside my `Validator::validateNoDuplicates` method, and then thought having the attribute manually input by the developer will make it more flexibility, maybe he wants to check against another set of records.

```php
    protected function validateNoDuplicates($attribute, $value, $parameters)
    {
        $data = array_filter(Arr::dot($this->data), function ($key) use ($attribute, $parameters) {
            return $key != $attribute && Str::is($parameters[0], $key);
        }, ARRAY_FILTER_USE_KEY);

        return ! in_array($value, array_values($data));
    }
```

After the edit the Validator will try to get the raw attribute name automatically instead of asking the developer to provide it.

**Comment by taylorotwell** [comment]
Oh OK I see.

**Comment by taylorotwell** [comment]
So my original comment was OK I guess :smile:

**Comment by themsaid** [comment]
Yup, I just edited the description after making the edits maybe that's what caused confusion :smile:

**Comment by taylorotwell** [comment]
Ah ok :)

**Comment by taylorotwell** [comment]
Renamed this to `distinct` instead of `no_duplicates`.

**Comment by taylorotwell** [comment]
:+1:

**Comment by danieliancu** [comment]
:+1: Nice job!

**Comment by themsaid** [comment]
`distinct ` is better, Nice :+1:

**Pull request merged**
