### PR TITLE
[5.5] Add queue assertions for chained jobs

### PR DESCRIPTION
**Pull request by TitasGailius**
Add additional assertions against chained jobs.
---
`assertChained($job, $callback = null)`
`assertNotChained($job, $callback = null)`
`assertNothingChained()`

`assertChained($job, $callback = null)`
```php
Queue::fake();

$order = factory('App\Order')->create();

FirstJob::withChain([
    new SecondJob($order),
])->dispatch($order);


Queue::assertChained(SecondJob::class);
Queue::assertChained(SecondJob::class, function ($job) use ($order) {
    return $job->order->id === $order->id;
});

```
---
`assertChained($job, 1)`
```php
Queue::fake();

FirstJob::withChain([
    new SecondJob,
    new ThirdJob,
    new ThirdJob,
])->dispatch();

Queue::assertChained(SecondJob::class, 1);
Queue::assertChained(ThidJob::class, 2);

```
---
`assertNothingChained()`
```php
Queue::fake();

$order = factory('App\Order')->create();
FirstJob::dispatch($order);

Queue::assertNothingChained();
```
---
`assertNotChained($job, $callback = null)`
```php
Queue::fake();

[$order1, $order2] = factory('App\Order', 2)->create();

FirstJob::withChain([
    new SecondJob($order1),
])->dispatch();

Queue::assertNotChained(FirstJob::class);
Queue::assertNotChained(SecondJob::class, function ($job) use ($order2) {
    return $job->order->id === $order2->id;
});
```

### CODE REVIEW

**Comment by sisve** [comment]
The syntax `Queue::assertChainedTimes(SecondJob::class);` looks weird. I suggest that the default value is removed to force people to say how many times they expect it to be chained.

**Comment by TitasGailius** [comment]
@sisve Wrong example.You can't actually use `assertChainedTimes($job, $times = 1);` because it's a protected method. You can pass a numeric value as a second argument to `assertChainedTimes($job, 2);` instead.
It's the same as using current implementation `Queue::assertPushed($job, 2);`

**Comment by mateusjatenee** [comment]
Looks great!

**Comment by taylorotwell** [comment]
I'm not sure I really like this approach. How do I assert something was chained in relation to the first job? Doesn't this just test it was chained "somewhere"?

**Comment by TitasGailius** [comment]
@taylorotwell 
Good point, I was thinking to pass something like `$parentJob` to the callback or to check if  second parameter is a string in `assertChained` method and compare against that as well.
```php
Queue::assertChained(SecondJob::class, function ($job, $parentJob) {
    // do whatever you want with $parentJob
});
// or
Queue::assertChained(SecondJob::class, FistJob::class);
```
I decided to skip this because I didn't really think of any good real life examples where this might be applicable. Although I can easily update the PR to match these needs if you want.

**Comment by taylorotwell** [comment]
I think I'm going to hold off on this for now.

**Pull request closed without merging**
