### PR TITLE
[6.x] Restore phpunit 7 support

### LINKED ISSUE #31101: Declaration of ArraySubset::evaluate incompatible with PHPUnit 7.5
- Laravel Version: 6.10.1
- PHP Version: 7.3
- PHPUnit: 7.5.20

### Description:

@GrahamCampbell 

I'm getting a very similar issue to #28827 on Laravel 6.10.1 in combination with PHPUnit 7.5.20

_ErrorException : Declaration of Illuminate\Foundation\Testing\Constraints\ArraySubset::evaluate($other, string $description = '', bool $returnResult = false) should be compatible with PHPUnit\Framework\Constraint\Constraint::evaluate($other, $description = '', $returnResult = false)_

This type signature was not updated in PHPUnit, but it has been changed 11 days ago in Laravel Framework with the release of 6.10.x

https://github.com/sebastianbergmann/phpunit/blob/7.5.20/src/Framework/Constraint/Constraint.php#L47

https://github.com/laravel/framework/blame/02a326ce5641b741fafb017f3d02b8917ba5e563/src/Illuminate/Foundation/Testing/Constraints/ArraySubset.php#L58

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Closes #31101.

### CODE REVIEW

**Comment by spawnia** [comment]
Thank you. I really dislike the direction that PHPUnit has been going in lately with locking down classes/methods to be impossible to extend.

**Comment by GrahamCampbell** [comment]
PHPUnit 7 support will be removed in Laravel 7, however.

1. Laravel 5.8 supports PHPUnit 7 and 8.
2. Laravel 6 supports PHPUnit 7, 8 and 9 (we are treating it as a bug that support for PHPUnit 7 is currently not present in Laravel 6, and this PR will restore it)
3. Laravel 7 will support only PHPUnit 8 and 9, when it is released in a few weeks.

The reason for saying Laravel 6 will support PHPUnit 9, even though it's not out yet, is because Laravel 6 is an LTS release, and so needs to work on PHP 8.0 and 8.1 when they come out. There's a good chance PHPUnit 7 or 8 won't work properly on PHP 8, but PHPUnit 9 will likely get any fixes backported to it from PHPUnit 10.

**Comment by driesvints** [comment]
@GrahamCampbell any chance we can get the tests fixed so we can get this merged? I think there's just a copy/paste gone wrong. The Assert class seems to be placed twice inside the same if statement.

**Comment by lukasjuhas** [comment]
Thank you for this!

**Comment by GrahamCampbell** [comment]
Added that missing line. Looks like the tests were broken on PHPUnit 7, since the exception assertion stuff isn't present.

**Pull request merged**
