### PR TITLE
[5.5] remove unused parameter

### PR DESCRIPTION
**Pull request by ngocnv-0940**

### CODE REVIEW

**Comment by sisve** [comment]
Changing a method signature in the middle of 5.5? Blasphemy!

Do I need to point out the problems or will just you retract this change?

**Comment by lagbox** [comment]
So if I had extended this class and bound my version to the container I will have to deal with PHP warnings?

**Comment by sisve** [comment]
Okay. So I can be more clear than that.

The method is unused in our implementation. However, we're a framework and people can extend our rate limiters and overridden that method. Changing that method from our end will cause php warnings about mismatching method signatures.

**Comment by sisve** [comment]
Highly relevant: https://github.com/laravel/framework/pull/22202

**Pull request closed without merging**
