### PR TITLE
[5.4] Use translator for replacing validator message parameters

### PR DESCRIPTION
**Pull request by Skysplit**
This PR provides some consistency across validator, as it uses translator for replacing parameters.

I'm not very familliar with mockery, so I wasn't able to fix all translator tests, but I managed to fix few of them.

Any thoughts, help or advice would be appreciated.

### CODE REVIEW

**Comment by themsaid** [comment]
I don't think it's a valid PR unless all tests pass, please fix.

**Comment by garygreen** [comment]
How come you renamed everything from replacer to mapper?

**Comment by Skysplit** [comment]
@garygreen I just found that `replacer` name does not fit behavior of this method, as it actually does not replace anything, but maps validator parameters to proper translation parameters.

**Comment by taylorotwell** [comment]
Holding off on this for now.

**Comment by Skysplit** [comment]
@taylorotwell any chances that this kind of changes could be merged in future? I'm really curious, as this PR does not break much (not in translator at least), yet provides consistent behavior when it comes down to translating error messages. If one would like to replace translator, current validator makes message formatting really inconsistent :/

**Comment by garygreen** [comment]
@Skysplit I think the problem is that it's not too obvious what you mean by keeping things consistent, what does the PR actually do? Also your changed waaaaay too much with the replacer -> mapper stuff which seemed completely unrelated to the PR itself.

**Comment by Skysplit** [comment]
@garygreen Currently when you're using `trans(':foo', ['foo' => 'bar'])` it's the translator job to replace parameters in string with proper values. Currently in validator this behaviour is partially done by translator, partially by validator replacers.

In my PR, validator only provides values for parameters, which then are passed to translator, which makes it easier for developers to change translator with keeping consistent message formatting.

For example:  
Laravel message for `size.numeric` looks like `The :attribute must be :size kilobytes.` where `:attrbute` and `:size` are validation parameters.

Currently only `attribute` parameter is replaced by translator, and `size` is replaced by validator.

When you would like to implement your own translator, for example based on php [MessageFormatter](https://secure.php.net/manual/en/class.messageformatter.php), you would have to write your validation message like this: 
`The {attribute} must be :size kilobytes.` - that's the incosistency I'm talking about.

**Comment by garygreen** [comment]
Well that does clear it up, sounds like a worthwhile PR to me. Maybe open another PR but with a clear explanation and also try and change as little as possible (no replace -> mapper stuff) that way it'll more likely get accepted.

**Comment by Skysplit** [comment]
@garygreen Thanks for feedback! However, I think that **replace -> map** stuf is pretty much required, as `replace` just does not fit behaviour of the method. It does not replace anything, it provides array with parameters.  In that case `replace{RuleName}` and `Validator::replace()` names are bit misleading.

**Comment by garygreen** [comment]
Well it's been named that since 4.2, as far as I remember. Changing the name of it doesn't really add much value or fix anything, it only makes the upgrade step into 5.4 more complicated than it needs to be.

**Comment by Skysplit** [comment]
@garygreen Sounds good. Once again, thanks for feedback.

I'd like to hear @taylorotwell opinion on this before submitting another PR.

**Comment by Skysplit** [comment]
I just had an idea. What about keeping both `Validator::replace` and adding `Validator::map` as well? This would allow both new and old apporach to work.

**Comment by garygreen** [comment]
Why are you obsessed with `map` - just leave it as it is! Lol

**Pull request closed without merging**
