### PR TITLE
[8.x] Support for closure-based routes caching

### PR DESCRIPTION
**Pull request by jarektkaczyk**
Introducing closure-based routes caching.

In order to cache the routes we're extending IoC so it supports `calling` serialized closures.
Implementation aims to be as simple as possible with `@` callable syntax on top of `Opis\Closure\SerializableClosure` which we already use in the `queue` component.

Example cached route:

```php
...
'serialized-route' => 
array (
  'methods' => array (
    0 => 'GET',
    1 => 'HEAD',
  ),
  'uri' => 'genie',
  'action' => array (
    'uses' => 'Illuminate\\Container\\SerializedClosure@C:32:"Opis\\Closure\\SerializableClosure":970:{@IFD1EnJFrI3ZYePnRGDKf6yrbATMCi8bZTCZQeRiU8o=.a:5:{s:3:"use";a:0:{}s:8:"function";s:800:"function (\\Illuminate\\Http\\Request $request) { ... }";s:5:"scope";N;s:4:"this";N;s:4:"self";s:32:"0000000045201a3c000000001cce6179";}}',
    'as' => 'serialized-route',
  ),
  'fallback' => false,
  'defaults' => array (),
  'wheres' => array (),
  'bindingFields' => array (),
  'lockSeconds' => NULL,
  'waitSeconds' => NULL,
),
```

---

The PR introduces new functionality, doesn't change existing behavior except for unhandled path throwing error in the past, and thus is fully backward-compatible.
Should be good to merge to `7.x`, however targeting master as we know that... 😂

image

### CODE REVIEW

**Comment by netpok** [comment]
Does this have any noticeable performance increase over the classical non-cached routes? I mean serializing and deserializing is not a fast task.

Also how is this affecting the other routes, is the deserialization only happens when one tries to access the route or on every request?

**Comment by mbardelmeijer** [comment]
How about adding opis/closure to the suggest key in the container, and adding the dependency to illuminate/foundation?

**Comment by driesvints** [comment]
Ping @frankdejonge. Does this look like anything you were up to?

**Comment by anouarabdsslm** [comment]
@jarektkaczyk can you provide where route closure caching will be beneficial, as @netpok mentioned serializing and deserializing not a fast task.

**Comment by jarektkaczyk** [comment]
@mbardelmeijer @anouarabdsslm thanks for comments and questions, much appreciated!

First things first:
- it does not have **any** negative effects in performance in current setup
- it does not have significant performance effect even when using such routes, for 2 reasons:
  - serialization of all closures defined in your routes (should you have any) happens **only** during `artisan route:cache` call, so does not affect runtime of your app
  - deserialization happens **only** for the specific route that is being looked up - that is to say likely 99.9% of cases in normal flow. It can affect some fancy work with the routes that one might manually perform, which wouldn't be good anyway


The reason for having this feature is the following:
- you can define closure routes, but then you cannot benefit from caching
- you can potentially break your production env (seen it many times) if you use non-artifact deployment (ie. bunch of commands in the server, whether automated or not) and do not happen to have `route:cache` in your CI setup AND you leave a closure route somewhere, whether by mistake or not being aware of the possible issue.

@mbardelmeijer @netpok good point on dependency, will add

**Comment by frankdejonge** [comment]
Hi @driesvints,

My approach was a little different. In my approach, the caching would store the index of entry of the closure and the `prod` implementation would still load routes, although in a simplified way. It would only really handle the closures and use when dispatched, it would use the resolved index to look up the closure. That way there's no need to serialize the closure.

In more detail: The order of routes loaded is always the same, this means if you increment an integer to provide an index, it'll be stable. So when you cache the routes, the route loader can use this index to store which closure it should load. This approach would require the route loader to be an explicit thing, or at least that would make it easier and I don't know if that's the case now. 

Perhaps it's a fun exercise to try and make that work and see if the performance is any better/worse compared to this approach. We could pair on it if you fancy a sessions with a beer.

**Comment by netpok** [comment]
The encryption package just makes sure the key is set, it does not actively depends on it. The queue package has it as "real" dependency.

I'm pretty sure that a new dependency for the container is a no go, so it should suggest the package. If it is not present it just breaks like many other places in the framework.

Also if this is not affecting the performance than I have no more problems with the PR, but a notification about the negative impact would be nice on the `route:cache`.

**Comment by driesvints** [comment]
@frankdejonge thanks! Gonna wait to see what Taylor says first.

**Comment by taylorotwell** [comment]
Since the cached routes are stored in the bootstrap directory locally, I'm not entirely sure the encryption key is super relevant here. Anyone can already modify the cached controller callbacks to point to any class and method they want if they needed to. They would also likely have access to the encryption key environment variable if they have access to the server.

The encryption key feels more relevant when queueing Closures to a third party system such as SQS or even a database.

**Comment by netpok** [comment]
@taylorotwell  You're right but the main concern IMO is that this allows executing serialized closures in general so there will be at least a few people who will try to use it for serializing things they aren't completely understanding.

**Comment by taylorotwell** [comment]
I think I will just hold off on this for now.

**Pull request closed without merging**
