### PR TITLE
[7.x] SQL select exists support

### PR DESCRIPTION
**Pull request by royduin**
See: https://github.com/laravel/ideas/issues/2231

### CODE REVIEW

**Comment by taylorotwell** [comment]
It's unclear to me why it wouldn't be simpler to write your original idea query as a simple count.

**Comment by royduin** [comment]
Because I want a bool instead of an integer and it's faster. The `SELECT *` will be ignored in `EXISTS()`.

**Comment by desaintflorent** [comment]
I agree that a selectExists method or similar would be really helpful !
In my case I needed to add a boolean if a relation exist on the model.
Here what I currently use :

```
public function scopeWithRelationExistBool($query)
{
		$query->withCount(['relation as someboolname' => function ($q) {
			return $q->where('something', 'anotherthing');
		}])->withCasts(['someboolname' => 'boolean']);
}
```
So If count is equal or more than 1 it will be true.

**Comment by desaintflorent** [comment]
But in this the case if we want to order by someboolname in mysql it will be ordered by count value not by boolean... So I'm back to selectRaw :/

**Pull request closed without merging**
