### PR TITLE
[10.x] Add `list` rule

### PR DESCRIPTION
**Pull request by medilies**
When I want my API to receive a JSON array, the current `array` rule allows both JSON arrays and JSON objects. With this `list` rule, I can be sure I will receive `[1, 2, 3]` instead of `{"a": 1, "b": 2, "c": 3}`.

### CODE REVIEW

**Comment by medilies** [comment]
I forgot to this `'list' => 'The :attribute field must be a list.',` to `src\Illuminate\Translation\lang\en\validation.php`

**Comment by fragkp** [comment]
> I forgot to this `'list' => 'The :attribute field must be a list.',` to `src\Illuminate\Translation\lang\en\validation.php` and I'm a afraid a new commit from me will rerun the actions.

It will trigger a rerun, but thats totally fine.

**Comment by diegogit03** [comment]
Maybe this rule can receive a datatype something like `list:number` or `list:string`

**Comment by medilies** [comment]
That's a good point @diegogit03 but I didn't try to handle that in this rule because the developer can use something like `['field' => 'list', 'field.*' => 'number']`.

**Pull request closed without merging**
