### PR TITLE
[5.5] If applied, this commit adds the timer() helper function

### PR DESCRIPTION
**Pull request by introwit**
**Why timer()**
- Because multiple approaches are available to achieve the same output, the better execution time plays a decisive role. So it ends up to `start the timer, subtract and echo the results` loop.

**Uses**
- Can be called without any arguments, to echo the execution time from `LARAVEL_START` till that point.
- A callback or the code can be passed as an argument to include its execution in the result time as well.

**Credits**
- Never thought to make this as a PR until I saw @calebporzio and many other also play around with this idea.
- The code and conditional check of closure is also from Caleb's knowledge base and is taken from his [gist](https://gist.github.com/calebporzio/52cc47ccd8ef75eff33cb45d56b4874b) , so pass all the :kissing_heart: to @calebporzio :smile:  

**Example**

```php
Route::get('/', function () {
    timer(define('TEST', 3)); // echos 0.010795831680298 seconds

    echo "using timer at multiple places to break and measure the difference"; 

    timer(); // echos 0.010809898376465 seconds
    return view('welcome');
});
```

### CODE REVIEW

**Comment by calebporzio** [comment]
@introwit thanks for the cred. Oddly enough I didn't PR it because I'm actually not sure it belongs in the framework especially because it echos instead of returning an int.

Also, I like your implementation using LARAVEL_START, just not sure that is the expected functionality when I pass in an expression. Like I would want the time of the expression in isolation from the rest of the app running time - nah mean?

**Comment by introwit** [comment]
@calebporzio most of my use cases were measuring the differences as shown in the example, your tweet pumped me and I made the PR. 

- I agree that many (almost all) would be in the favor of returning an int > echoing a string in this case. I thought putting up a PR would be the best place where the community can guide me what should be the correct practice instead of echoing and I can learn a thing or two from you guys :smile: 

- > Like I would want the time of the expression in isolation from the rest of the app running time.

Maybe we can use a second parameter to dictate how the calculation should be done? Not sure, your thoughts would be helpful :)

**Comment by taylorotwell** [comment]
No plans to add.

**Comment by introwit** [comment]
No problem Taylor :smile:

**Pull request closed without merging**
