### PR TITLE
Add Optional Auto-Registration of Seeder Class in DatabaseSeeder

### PR DESCRIPTION
**Pull request by sarahelsagheir**
This pull request allows developers to optionally auto-register the generated seeder class in DatabaseSeeder.php using the --auto-register (-r) flag.

**command example**: php artisan make:seeder -r

When the -r or --auto-register flag is used, the generated seeder class is automatically appended to the $this->call([]) array in DatabaseSeeder.php, streamlining the workflow by eliminating the need for manual registration.

**Key Features:**

1. Optional Auto-Registration:
   * Use the --auto-register flag to append the new seeder class to the $this->call([]) array in DatabaseSeeder.
2. Prevents Duplicates:
   * Checks if the seeder is already registered before adding it to avoid duplicate entries.
3. Backward Compatible:
   * The feature is completely optional, preserving existing behavior when the flag is not used.
4. Developer Feedback:
   * Provides clear messages to inform developers if the seeder was successfully registered or already present.

### CODE REVIEW

**Comment by shaedrich** [comment]
I feel like there should be auto-**discovery** instead of auto-**registration** (that would probably have to be targeted at `12.x`)

**Comment by shaedrich** [comment]
> 1. Seeder Exclusion Challenge

Yep, I thought about that. This could be mitigated by introducing a new directory (e.g. `database/AutoSeeders`) for that purpose—not ideal, but this would ensure backwards compatibility

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

**Comment by shaedrich** [comment]
@taylorotwell Would you be more open to exploring the idea of auto-**discovery** for `12.x`?

**Pull request closed without merging**
