### PR TITLE
[5.2] Inaccurate Chinese character length problem

### PR DESCRIPTION
**Pull request by seekcx**
mb_strlen second parameter to add utf-8 support Chinese string length calculations.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is a breaking change?

**Comment by Abel94** [comment]
sorry,I do not understand your development process, but I hope this issue can be resolved.

**Comment by taylorotwell** [comment]
I think you can set the default multibyte encoding http://php.net/manual/en/function.mb-internal-encoding.php

**Comment by Abel94** [comment]
But other mb_ function you specify the encoding, why the need to manually set it?

**Pull request closed without merging**
