### PR TITLE
Added `files()` function to helpers list.

### PR DESCRIPTION
**Pull request by maherelgamil**

### CODE REVIEW

**Comment by JuanDMeGon** [comment]
Be aware that on lines 802 and 805, the $path can still being null

**Comment by maherelgamil** [comment]
Thanks for you @JuanDMeGon , I fixed it now.

**Comment by JuanDMeGon** [comment]
You know what? I think that I get confused on my first comment. Basically, if the path is null it will always return `app('files')`.
It seems like your original code was correct and the latest commit does not need the additional condition, because `! is_null($path)` is going to be `true` always after the first if statement.

Very sorry for the confusion here.

**Comment by maherelgamil** [comment]
@JuanDMeGon No problem, I reverted it now.

**Comment by maherelgamil** [comment]
@taylorotwell why?  😥

**Pull request closed without merging**
