### PR TITLE
[5.5] Enhance Mailable queueing

### PR DESCRIPTION
**Pull request by aleksandrlat**
It is impossible to enhance or change queue job in Mailable now. 

For example it would be nice to add [failed](https://laravel.com/docs/5.5/queues#dealing-with-failed-jobs) method to Job to handle job failures. But it is impossible now.

With job factory method we can use any custom Job for Mailables. It will be possible to add [failed](https://laravel.com/docs/5.5/queues#dealing-with-failed-jobs) method.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I would rather just support `failed` in Mailables and Notifications, etc. 

@themsaid is it not possible already?

**Comment by aleksandrlat** [comment]
`failed` is one of use cases. There maybe other probably.
Having `failed` in Mailables and Notifications would be nice.

**Comment by taylorotwell** [comment]
I would rather do that than hack this in. @themsaid

**Comment by themsaid** [comment]
@taylorotwell Here's a PR to support `failed()` in mailable and notifictaions: https://github.com/laravel/framework/pull/21585

@aleksandrlat what else do you think should be supported?

**Comment by aleksandrlat** [comment]
I just thought about other potential tasks. I don't have something concrete in mind.

**Pull request closed without merging**
