### PR TITLE
[11.x] Add support for enums in `whereIn` route constraints

### PR DESCRIPTION
**Pull request by osbre**
Currently, passing an array of enum cases results in an exception:

```php
Route::get('/posts/{type}')->whereIn('type', PostType::cases());

// Error: Object of class Illuminate\Tests\Routing\CategoryBackedEnum could not be converted to string
```

This change fixes it, allowing us to pass array of enums into `whereIn`.

Probably interchangeable with https://github.com/laravel/framework/pull/51104

### CODE REVIEW

**Comment by taylorotwell** [comment]
Fine with merging this, but not you could just type hint the Enum in your route parameter and you wouldn't need this `whereIn` call at all. 😅

**Comment by vanodevium** [comment]
@taylorotwell 

It's undocumented feature

**Comment by taylorotwell** [comment]
@vanodevium https://laravel.com/docs/11.x/routing#implicit-enum-binding ?

**Comment by osbre** [comment]
@taylorotwell Unfortunately, it's not the same in some cases. Perhaps later I can send a test update to further demonstrate why.

**Comment by vanodevium** [comment]
@taylorotwell 

I'm sorry that I'm just now writing my comment.

I will try to explain my vision of the problem to you as simply as possible.

Let's imagine that we have the following routing configuration:

> Category enum is taken from the documentation, values: [fruits, people]

```php
Route::get('/{category}', function (Category $category) {
    dd("This is case without unpacking enum values into RegEx");
});

Route::get('/news', function () {
    dd("This is NEWS page");
});
```

According to the documentation, for this configuration I will never get to the **news** page, because the request will always fall into the **first route**, but enum does not have a **news** value, so it will be raise 404. Everything is as written in the documentation, I completely understand. 
> Of course, I can push the news to the top and everything will work as it should.

But the question is: **why such behavior**? 
It's simple: because enum is not unpacked into a regular expression at the matching step, so anything gets into the resolver and shows a 404.

Ok, how to fix it?. Very easy:

```php
Route::get('/{category}', function (Category $category) {
    dd("This is case with unpacking enum values into RegEx");
})->whereIn('category', Category::cases());

Route::get('/news', function () {
    dd("This is NEWS page");
});
```

In this version, everything that is not suitable for the enum will not get into the **first route**.
And I'll be happy to see news page as I want.

--- 

So maybe **->whereEnum('name', Enum::class)** helper with automatic unpacking into regex is no so bad idea?

**Pull request merged**
