### PR TITLE
[5.2] Add Mailjet.com Mail Provider

### PR DESCRIPTION
**Pull request by ghost**
This adds support for https://www.mailjet.com/ as a mail provider.

`.env`

```
MAIL_DRIVER=mailjet
MAILJET_PUBLIC=public_key
MAILJET_PRIVATE=private_key
```

`config/services.php`

``` php
'mailjet' => [
    'public' => env('MAILJET_PUBLIC'),
    'private' => env('MAILJET_PRIVATE'),
],
```

### CODE REVIEW

**Comment by ellisio** [comment]
I feel like this should be made into it's own package and included with a ServiceProvider.

**Comment by GrahamCampbell** [comment]
Thanks, but we don't plan to accept any more mail drivers into the core at this point.

**Comment by DraperStudio** [comment]
How would I register a new Mail Driver via a ServiceProvider then? Can't find any details about that anywhere since the `TransportManager` is used to register the drivers.

**Comment by ellisio** [comment]
@DraperStudio This may help you: https://github.com/sboo/laravel5-mailjet

**Comment by GrahamCampbell** [comment]
That library doesn't look very good. It is not necessary to override so much. You can easily register custom drivers to a manager class using the extend method.

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Support/Manager.php#L111

**Comment by DraperStudio** [comment]
Is really that much work required to register a new mail driver? Seems kinda overkill.

**Comment by GrahamCampbell** [comment]
You should not finding yourself needing custom facades or managers.

**Comment by ellisio** [comment]
@GrahamCampbell's is indeed the preferred way. I've only had to really extend the framework a once or twice because Laravel's core had to change for some of our business rules.

Didn't look too far into that library, my bad :)

**Comment by ellisio** [comment]
https://laravel.com/docs/5.2/cache#adding-custom-cache-drivers -- This is for extending the Cache driver. But you can follow the same concept for a Mail driver.

**Comment by DraperStudio** [comment]
Solved it like this for now. Is there anything I could call instead of `app('swift.transport')` to extend the mail drivers?

```php
app('swift.transport')->extend('mailjet', function() {
    $config = $this->app['config']->get('services.mailjet', []);

    return new MailjetTransport(
        new HttpClient(Arr::get($config, 'guzzle', [])),
        $config['public'], $config['private']
    );
})
```

**Pull request closed without merging**
