### PR TITLE
[8.x] Code optimization: Make Closures static

### PR DESCRIPTION
**Pull request by simonschaufi**
[PHP Inpections](https://plugins.jetbrains.com/plugin/7622-php-inspections-ea-extended-) suggested to make closures static that don't depend on `$this`. The only place where this is not possible is in Macros. Those are excluded from the optimization.

The optimization is based on this PR: https://github.com/Ocramius/GeneratedHydrator/pull/83

I ran a couple of framework unit tests on my local Ubuntu with PHP 7.4 and this is the result:

```
before:
Time: 00:41.122, Memory: 236.50 MB
Time: 00:40.884, Memory: 236.50 MB
Time: 00:41.165, Memory: 236.50 MB

after (with static):
Time: 00:42.184, Memory: 234.50 MB
Time: 00:41.700, Memory: 234.50 MB
Time: 00:41.686, Memory: 234.50 MB
```

Concerning the time there is no difference but we save 2 MB by this micro optimization!

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I think some cases have been missed, for example, in service providers. `$this->app` can be replaced with `$app`, the first param to the callback.

**Comment by simonschaufi** [comment]
Could you point me to an example file with line number?

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/1ae3e0bb30e57e6400f83feb89f4a4f052e4d86c/src/Illuminate/View/ViewServiceProvider.php#L121-L126

Could be:

```php
    public function registerFileEngine($resolver)
    {
        $resolver->register('file', static function ($app) {
            return new FileEngine($app['files']);
        });
    }
```

**Comment by simonschaufi** [comment]
ah ok, I didn't want to mix refactoring and "code optimization" within one PR.

**Comment by simonschaufi** [comment]
How should a test scenario in a real world app look like? Make some HTTP requests and compare the time and memory? Run phpunit tests? I don't have any experience in benchmarking

**Comment by SjorsO** [comment]
The benchmark you posted shows that this change makes the tests run 1.95% slower, but saves 0.85% memory. Doesn't seem like a good trade :smile:

**Comment by simonschaufi** [comment]
Well, [this](https://github.com/Ocramius/GeneratedHydrator/pull/83#issuecomment-469396606) should actually be the result but they don't say anything under which PHP version they tested.

**Comment by taylorotwell** [comment]
Closing since real-world performance / memory savings seem to be negligible.

**Comment by simonschaufi** [comment]
This is a micro optimization, of course you can't expect saving plenty of seconds and a couple of MB of RAM. I was asking for benchmarks from other people but nobody responded to that which makes me sad. I spend so much time in preparing this PR.

**Comment by driesvints** [comment]
@simonschaufi thank you for your pr but it's indeed always best that you try to discuss this with others first before putting in all the work.

**Comment by simonschaufi** [comment]
I did that actually even personally with Taylor in Discord in the #internals channel. See https://discordapp.com/channels/297040613688475649/486650494790402061/710437616591568917

**Comment by simonschaufi** [comment]
@SjorsO could you do a benchmark test yourself please?

**Comment by SjorsO** [comment]
> @SjorsO could you do a benchmark test yourself please?

I don't believe this PR would make a meaningful difference in performance, so I don't want to invest any time in it.

**Pull request closed without merging**
