### PR TITLE
[5.2] originalIsNumericallyEquivalent float bug fix

### PR DESCRIPTION
**Pull request by erhankr**
not working for floats because of
(string)'1.00' === '1.00'
(string)1.00  === '1'

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This breaks things for large integers though?

**Comment by vlakoff** [comment]
* Looks like it gives same results with large integers, it goes to scientific notation the same.
* Refs #2904 and #3392.
* A simple `==` would do, instead of the `strcmp() == 0`.

**Comment by GrahamCampbell** [comment]
> Looks like it gives same results with large integers, it goes to scientific notation the same.

No? For integers that aren;t large enough to be approximated as floating point numbers, the act of casting them to floating point causes data loss.

**Comment by GrahamCampbell** [comment]
@vlakoff See the issue: https://3v4l.org/n5los. These two integers are not equal...

**Comment by GrahamCampbell** [comment]
Without the cast: https://3v4l.org/5npCv.

**Comment by GrahamCampbell** [comment]
Just to prove they're not approxumated by php without the cast: https://3v4l.org/beSpI.,

**Comment by vlakoff** [comment]
Good catch, I overlooked this.
So the lesser evil is probably to leave as is?

**Comment by taylorotwell** [comment]
Will hold off for now.

**Pull request closed without merging**
