### PR TITLE
[5.4] Execute queries with lock only in write database

### PR DESCRIPTION
**Pull request by SebastianBerc**
As we know, in Laravel we can use two instances of a database, first for read and second for write.

When we use $query->lockForUpdate() or $query->lock(true), PDO for write will be used, but when we use $query->sharedLock() or $query->lock(false), we will still use PDO for read.

In Postgres case when we call lock with false as an argument, grammar will compile it to 'for share' in PDO for read. Finally, when we call lock with 'for share' - grammar will return the same result, but builder this time will use PDO for write.

If we use any lock on the read-only database, we'll get the query exception: "SQLSTATE[25006]: Read only sql transaction: 7 ERROR:  cannot execute SELECT FOR SHARE in a read-only transaction", so queries with a lock should always be executed on the write database to avoid the exception.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Please share the exact query builder calls you are making in your application.

**Comment by SebastianBerc** [comment]
```php
Category::query()->orderBy('rgt', 'DESC')->take(1)->sharedLock()->first();
```

**Comment by taylorotwell** [comment]
So your query is already using the write PDO connection, correct? What is the issue?

**Comment by SebastianBerc** [comment]
No, this builder will use read PDO, because `sharedLock()` calls `lock(false)` and:

```php
    public function lock($value = true)
    {
        $this->lock = $value;

        if ($this->lock) {
            $this->useWritePdo();
        }

        return $this;
    }
```

**Comment by taylorotwell** [comment]
Please send to the 5.4 branch.

**Comment by JoostK** [comment]
This seems incorrect to me. The isset check now always passes?

**Comment by SebastianBerc** [comment]
Yeah - except `null` ofc, and nothing wrong with that. Why it seems to be incorrect?

`true` - lock for update in write PDO, `false` - lock for share in write PDO, any kind of string as any other lock in write PDO and finally `null` doing nothing at all ;).

**Comment by JoostK** [comment]
@SebastianBerc ah, I see now. The naming of `$this->lock` and it being a boolean is not intuitive at all though for the behavior you describe. Furthermore, I would prefer an `is_null` check instead of using `isset`, which is functionally equivalent but expresses more clearly the intent.

**Comment by GrahamCampbell** [comment]
👍

**Pull request merged**
