### PR TITLE
Added 'string' validation rule

### PR DESCRIPTION
**Pull request by garygreen**

### CODE REVIEW

**Comment by garygreen** [comment]
@taylorotwell Please can you re-consider this request. On the validator the `min` `max` rule validate both strings and arrays. If your validating a text `notes` like `required|min:1`  -- if a malicious user posted a array against this validation rule it would pass. Using something like `alpha` isn't suitable as it has limited support the full range of characters. There should be an option in core to validate if the input is a string.

**Comment by RomainLanz** [comment]
:+1:

**Comment by juukie14** [comment]
I can see myself using this rule in some cases.

**Comment by garygreen** [comment]
Thanks so much for this Taylor (and Graham!). I've added it to the docs PR laravel/docs#1044

**Pull request merged**
