### PR TITLE
[5.9] Remove primitive type-hint

### PR DESCRIPTION
**Pull request by oliverquynh**
The framework doesn't currently accept primitive type-hint.

### CODE REVIEW

**Comment by devcircus** [comment]
The framework doesn't use them everywhere but IMO there are situations where they can play an important role. I believe this is a good use-case.

**Comment by xuanquynh** [comment]
There are many related issues like this. Accepting primitive type-hints is an important and breaking change that effects to a lot of interfaces. And Taylor still wants to keep the current source code synchronized. If he change his opinion, the Laravel community will help to do. For example, creating issue that is similar to the Symfony [add type-hints issue](https://github.com/symfony/symfony/issues/32179)

**Comment by dinhquochan** [comment]
Some files have `bool` and `array` type-hints like this. Why Taylor does not remove all of them? I don't think it should be removed.

**Comment by xuanquynh** [comment]
I don't know those cases. He may not want to manage some situations if they aren't important.

**Pull request closed without merging**
