### PR TITLE
[5.4] Auth route options

### PR DESCRIPTION
**Pull request by whatsupmike**
Now Route::auth() takes array as a parameter. Now works ’only’ and ’except’ for creating
auth routes.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Any reason you targeted 5.4 please?

**Comment by GrahamCampbell** [comment]
It is still about 7 months off being released.

**Comment by taylorotwell** [comment]
If you want to customize Route::auth I recommend registering your routes manually.

**Comment by whatsupmike** [comment]
Sorry for the wrony target. It was my first pull request. Thanks for the advice.

**Pull request closed without merging**
