### PR TITLE
[7.x] Multiple Mailers Per App

### PR DESCRIPTION
**Pull request by taylorotwell**
This PR provides support for multiple different mailer configurations within a single application:

```php
Mail::to('taylor@laravel.com')->send(new Mail);

Mail::mailer('other-mailer')->to('taylor@laravel.com')->send(new Mail);
```

I believe I was able to do this with basically no breaking changes as support for the old format of the `mail` configuration file is still provided within the new `MailManager` class.

`Mail::fake()` still works as normal.

`Mail::extend('name', Closure)` may be used to register callbacks for creating custom transports.

The new Laravel 7.x `mail` configuration file would look something like this:

```php
<?php

return [

    'default' => env('MAIL_DRIVER', 'smtp'),

    'mailers' => [

        'smtp' => [
            /*
            |--------------------------------------------------------------------------
            | Mail Transport Driver
            |--------------------------------------------------------------------------
            |
            | Laravel supports both SMTP and PHP's "mail" function as drivers for the
            | sending of e-mail. You may specify which one you're using throughout
            | your application here. By default, Laravel is setup for SMTP mail.
            |
            | Supported: "smtp", "sendmail", "mailgun", "ses",
            |            "postmark", "log", "array"
            |
            */

            'transport' => env('MAIL_TRANSPORT', 'smtp'),

            /*
            |--------------------------------------------------------------------------
            | SMTP Host Address
            |--------------------------------------------------------------------------
            |
            | Here you may provide the host address of the SMTP server used by your
            | applications. A default option is provided that is compatible with
            | the Mailgun mail service which will provide reliable deliveries.
            |
            */

            'host' => env('MAIL_HOST', 'smtp.mailgun.org'),

            /*
            |--------------------------------------------------------------------------
            | SMTP Host Port
            |--------------------------------------------------------------------------
            |
            | This is the SMTP port used by your application to deliver e-mails to
            | users of the application. Like the host we have set this value to
            | stay compatible with the Mailgun e-mail application by default.
            |
            */

            'port' => env('MAIL_PORT', 587),

            /*
            |--------------------------------------------------------------------------
            | Global "From" Address
            |--------------------------------------------------------------------------
            |
            | You may wish for all e-mails sent by your application to be sent from
            | the same address. Here, you may specify a name and address that is
            | used globally for all e-mails that are sent by your application.
            |
            */

            'from' => [
                'address' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
                'name' => env('MAIL_FROM_NAME', 'Example'),
            ],

            /*
            |--------------------------------------------------------------------------
            | E-Mail Encryption Protocol
            |--------------------------------------------------------------------------
            |
            | Here you may specify the encryption protocol that should be used when
            | the application send e-mail messages. A sensible default using the
            | transport layer security protocol should provide great security.
            |
            */

            'encryption' => env('MAIL_ENCRYPTION', 'tls'),

            /*
            |--------------------------------------------------------------------------
            | SMTP Server Username
            |--------------------------------------------------------------------------
            |
            | If your SMTP server requires a username for authentication, you should
            | set it here. This will get used to authenticate with your server on
            | connection. You may also set the "password" value below this one.
            |
            */

            'username' => env('MAIL_USERNAME'),

            'password' => env('MAIL_PASSWORD'),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Sendmail System Path
    |--------------------------------------------------------------------------
    |
    | When using the "sendmail" driver to send e-mails, we will need to know
    | the path to where Sendmail lives on this server. A default path has
    | been provided here, which will work well on most of your systems.
    |
    */

    'sendmail' => '/usr/sbin/sendmail -bs',

    /*
    |--------------------------------------------------------------------------
    | Markdown Mail Settings
    |--------------------------------------------------------------------------
    |
    | If you are using Markdown based email rendering, you may configure your
    | theme and component paths here, allowing you to customize the design
    | of the emails. Or, you may simply stick with the Laravel defaults!
    |
    */

    'markdown' => [
        'theme' => 'default',

        'paths' => [
            resource_path('views/vendor/mail'),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Log Channel
    |--------------------------------------------------------------------------
    |
    | If you are using the "log" driver, you may specify the logging channel
    | if you prefer to keep mail messages separate from other log entries
    | for simpler reading. Otherwise, the default channel will be used.
    |
    */

    'log_channel' => env('MAIL_LOG_CHANNEL'),

];

```

### CODE REVIEW

**Comment by martinbean** [comment]
This looks great. I can see it being helpful for multi-tenant (I know you hate that term 😅) applications where one particular client may require messages to be sent through a provider of their choosing, or what have you.

**Comment by mikemand** [comment]
You said you don't think there are any breaking changes. Do you think this is something that can be done in a minor release? Or are you waiting for 7.0 to release?

**Comment by GrahamCampbell** [comment]
There is technically a breaking change, since the facade is now bound to the manager instance, which could have consequences for people doing mocking, or other things.

**Comment by browner12** [comment]
v7 will be here soon&trade; anyway

**Comment by Propaganistas** [comment]
Yes! At last...

https://github.com/laravel/framework/pull/23183

**Comment by dmitry-ivanov** [comment]
@taylorotwell @GrahamCampbell But why `Illuminate\Mail\MailServiceProvider` [still provides 'swift.mailer' and 'swift.transport'](https://github.com/laravel/framework/blob/62b1f8d7af46cc288ab95a5ecf087d1f736f4922/src/Illuminate/Mail/MailServiceProvider.php#L70-L71)?

There are no such bindings now.

**Comment by GrahamCampbell** [comment]
Please open a fresh issue or PR.

**Comment by Stenfrank** [comment]
This is my solution for multiple mail servers configured via .env file:

[https://laravel-mailers.soenac.com/](https://laravel-mailers.soenac.com/)

**Comment by ArtisanTinkerer** [comment]
So how do you use this with notifications?

**Pull request merged**
