### PR TITLE
[5.8] Add support for PhpRedis sharding array

### PR DESCRIPTION
**Pull request by akalongman**
Considering the previous experience of submitting PR's in this repository, I don't think this PR will be merged or well discussed :smile:  But anyways I already implemented this feature for my Laravel projects and want to share this to the community.

The goal of this PR is to add support for PhpRedis arrays, which allows us to easily implement consistent hashing (client side partitioning) for large caches, also distribute network traffic between multiple Redis servers. More from redis.io: https://redis.io/topics/partitioning

> A Redis array is an isolated namespace in which keys are related in some manner. Keys are distributed across a number of Redis instances, using consistent hashing. A hash function is used to spread the keys across the array in order to keep a uniform distribution.

More information about `RedisArray` class usage: https://github.com/phpredis/phpredis/blob/master/arrays.markdown

To use the new feature in Laravel, database.php should be updated and added new key `array`. The structure is similar to the already existing `cluster` configuration.
Also, client should be changed to `phpredis`. Example:

```php
'client' => 'phpredis',

'array' => [
    'options' => [
        'retry_interval'  => 100,
        'lazy_connect'    => true,
        'connect_timeout' => 3,
        'read_timeout'    => 3,
        'password'        => env('REDIS_PASSWORD', null),
        'database'        => env('REDIS_DATABASE', 0),
        'prefix'          => env('REDIS_PREFIX'),
    ],

    'default' => [
        [
            'host' => env('REDIS_SHARD1_HOST', '127.0.0.1'),
            'port' => env('REDIS_SHARD1_PORT', 6379),
        ],
        [
            'host' => env('REDIS_SHARD2_HOST', '127.0.0.1'),
            'port' => env('REDIS_SHARD2_PORT', 6380),
        ],
        // ...
    ],
],
```

I'd be happy to discuss any aspect of this PR.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm curious why not just re-use the existing `clusters` option that is already used when implementing client-side sharding with Predis?

**Comment by akalongman** [comment]
Unfortunately, Predis is much slower, than PhpRedis (even with ext-phpiredis installed). Also, looks like Predis project is dead. The last commit is from Jul 12, 2017

**Comment by taylorotwell** [comment]
Sorry, that wasn't really my question.

We already use the `clusters` configuration option for this same behavior. Why not just use that same key? Why did you need to invent a new key?

**Comment by akalongman** [comment]
Ah, I got now. 

For PhpRedis client classes are different for a cluster (`RedisCluster` class) and for a sharding (`RedisArray` class). If we use `cluster` key, then we need some other configuration option to distinguish which instance to create

**Comment by akalongman** [comment]
In documentation here https://laravel.com/docs/5.7/redis#introduction mentioned:

> If you would like to use native Redis clustering, you should specify this in the  options key of your Redis configuration

So, maybe consider that option? And if 
```php
'options' => [
    'cluster' => 'redis',
],
```
exists, create `RedisCluster` instance, if not - `RedisArray` instance.

What do you think @taylorotwell ?

**Comment by akalongman** [comment]
Now its totally compatible with the documentation. For PhpRedis you have to use 
```php
'options' => [
    'cluster' => 'redis',
],
```
configuration, like Predis.

Maybe its worth to write some simple unit tests, which will check just connector class instances depending on configuration?

**Comment by taylorotwell** [comment]
I don't think I'm going to support this. It has a lot of other features that would have to be exposed such as when adding or removing nodes from the array. I think I would prefer to just steer people towards the official Redis Cluster.

**Comment by taylorotwell** [comment]
Feel free to release your own Laravel compatible package with support for this though. You can bind your own extended RedisManager into the container.

**Comment by akalongman** [comment]
@taylorotwell 
> I don't think I'm going to support this

I always support my changes in any project, if you mean this. So I will be responsible for this feature :relaxed:

> I think I would prefer to just steer people towards the official Redis Cluster.

But currently, documentation is not compatible with framework behavior, because in the
https://laravel.com/docs/5.7/redis#introduction we can see
> By default, clusters will perform client-side sharding across your nodes, allowing you to pool nodes and create a large amount of available RAM

Is it ok? With my changes, it would be fixed. 

> It has a lot of other features that would have to be exposed such as when adding or removing nodes from the array.

A developer should care about that. I think it's not a framework responsibility. Predis supports many things, but they are not exposed to the framework.

**Comment by akalongman** [comment]
I've implemented this in the package Laravel Lodash: https://github.com/akalongman/laravel-lodash

**Pull request closed without merging**
