### PR TITLE
remove page=1

### PR DESCRIPTION
**Pull request by AgelxNash**
Pages /path/ and /path/?page=1 equivalents. 
This commit remove page=1 from url

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please don't mess with the indentation.

**Comment by GrahamCampbell** [comment]
You also broke the tests.

**Comment by AgelxNash** [comment]
But is the first page pagination not duplicate content? For example: https://laracasts.com/discuss/ and https://laracasts.com/discuss/?page=1

**Comment by Sladewill** [comment]
Look into canonical meta tag not the paginators responsibility.

**Comment by AgelxNash** [comment]
So, maybe someone come in handy https://github.com/AgelxNash/SEOPagination

**Comment by rafis** [comment]
@Sladewill , canonical meta tag is not supported by half of search bots and only Google bot properly supports it.

**Pull request closed without merging**
