### PR TITLE
[5.6] Add argon helper

### PR DESCRIPTION
**Pull request by mputkowski**
As of version 5.6, Laravel supports Argon hash algorithm. It will be nice to have helper as in the case of Bcrypt.

### CODE REVIEW

**Comment by mfn** [comment]
Please not more global helper functions, thx.

**Comment by francislavoie** [comment]
@mfn Then maybe consider deprecating the `bcrypt()` global helper? There's an inconsistency here where there's a global for one but not the other.

**Comment by taylorotwell** [comment]
No plans on adding more.

**Comment by mputkowski** [comment]
@taylorotwell if you don't plan to add more maybe consider editing of existing one? Hash method for multiple algorithms instead of for a single.

```php
function hash($value, $driver = 'bcrypt', $options = [])
{
    return app('hash')->driver($driver)->make($value, $options);
}
```
I think this will do the trick, it'll open the possibility of implementation of new algorithms in the future - just add algorithm's driver.

What do you think about that?

**Pull request closed without merging**
