### PR TITLE
[4.2] Reset STMP transport adapter for Swift_Mailer

### PR DESCRIPTION
**Pull request by YOzaz**
Update for 4.2 as well.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
4.2 is closed for non-critical fixes.

**Comment by YOzaz** [comment]
@GrahamCampbell without this fix, Queue deamon worker for queued emails doesn't work at all...

**Comment by GrahamCampbell** [comment]
It's still a non-critical fix. If it goes through into 5.0, then perhapse we can reconsider.

**Comment by YOzaz** [comment]
Please... there are lots of people still using 4.2 heavily (wihout so easy way of upgrade) and arguing about this issue - just take a look at StackOverflow, or directly into Swift Mailer package issues. Including me :)

**Comment by GrahamCampbell** [comment]
@YOzaz 4.2 is officially not supported. We port security fixes and **big** issues back only.

**Pull request closed without merging**
