### PR TITLE
[5.3] Allow Gate to explicitly check abilities for guests

### PR DESCRIPTION
**Pull request by mmghv**
See #10568

Currently, the Gate immediately denies abilities if there is no authenticated user. This PR makes it possible to allow abilities to be checked for guests (closure abilities or abilities in policies).

Say for example, We want to allow guests to comment on posts but we may change our mind in the future, So if we don't use an ability for commenting at all, Then in the future when we change our mind we have to update the views and/or controllers.
But now we can use an ability for commenting and we can mark it to be checked for guests, Then in the future when we change our mind we only have to change the ability's logic.

### Closure abilities

By default, when we define an ability as normal, If no user is logged-in, it will immediately deny the ability:

```PHP
$gate->define('update-article', function ($user, Article $article) {
    // If no user is logged-in, the guest will be denied before reaching here
    return $user->id === $article->user_id;
});
```

but if we want to mark the ability to be checked for guests, We can pass `true` to the third parameter (`includeGuest`) :

```PHP
$gate->define('show-article', function ($user, Article $article) {
    // If user is logged-in or not, this ability will be check because we told it so
    return $user || $article->visibility == 'all';
}, true);
```

**Note** The same applies for the `before` and `after` methods, If we want them to be called for guests we have to explicitly tell it so, Meaning that if we have an ability that is marked to be checked for guests, Then when this ability is called, It will be interrupted **only** by the `before` methods which are marked to be called with guests.

**Note** In case of guest, The `$user` parameter will be `null`.

### Policies

For abilities in policies, To mark any of them to be checked for guests, We can add an attribute named `$includeGuest` and include the names for the abilities that we want them to be checked for guests :

```PHP
// app/policies/ArticlePolicy.php

namespace App\Policies;

use App\Models\Article;

class ArticlePolicy
{
    /**
     * Array of abilities allowed to be checked for guests
     *
     * @var array
     */
    public $includeGuest = ['index', 'view'];

    /**
     * Ability to show index page
     *
     * @return bool
     */
    public function index()
    {
        return true;
    }

    /**
     * Ability to view specific article
     *
     * @param  User|Null  $user
     * @param  Article $article
     * @return bool
     */
    public function view($user, Article $article)
    {
        // View all articles for the users, but only articles with 'all' visibility level for guests
        return $user || $article->visibility == 'all';
    }

    /**
     * Ability to create new article
     *
     * @param  User  $user
     * @param  Article $article
     * @return bool
     */
    public function create($user)
    {
        return $user->isAdmin;
    }

    /**
     * Ability to edit specific article
     *
     * @param  User  $user
     * @param  Article $article
     * @return bool
     */
    public function edit($user, Article $article)
    {
        return $user->id === $article->user_id;
    }

    /**
     * Ability to delete specific article
     *
     * @param  User  $user
     * @param  Article $article
     * @return bool
     */
    public function delete($user, Article $article)
    {
        return $user->id === $article->user_id;
    }
}
```

**Note** Like closure abilities, If the `before` method is not included in the `$includeGuest` attribute, It will not be called with guests.

## The benefit of allowing abilities to be checked for guests

* This way we can always have abilities like `index` and `view` in our policies and making them default to allow all users and guests, And change them when we want, For example if we decide to restrict some page to be only accessible for users (or admins), Then we can remove the `index` item from the `includeGuest` attribute and add some logic in the ability.

* Also it will make it easy to give partial abilities for guests

* And leads for good practice when letting the `Gate` responsible for all the permissions, Even if one of them is currently allowed for all users and guests and could be removed.

* Also will allow (in the future) to use the abilities instead of some middlewares (like the `Auth` middleware), So we won't have to add the `Auth` middleware on the routes we want to allow only for users , This should be the responsibility of the `Gate` to determine.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Again, we never make users pass a boolean parameter.

**Comment by mmghv** [comment]
I was going for `$gate->allowGuest('ability-name');` but that's won't work with the `before` and `after` filters because one may register any number of them :
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Auth/Access/Gate.php#L147

So I can't do `$gate->allowGuest('before');`.

But there's an idea came to my mind here, We may solve this by chaining the definition of the ability with a method to `allowGuest` for the last defined ability, Something like that :

```PHP
$gate->define('show-article', function ($user, Article $article) {
    //
})->allowGuest();
```

and the same for `before` filter :

```PHP
$gate->before(function ($user, Article $article) {
    //
})->allowGuest();
```

But just **note** this way calling `$gate->allowGuest();` anytime will mark the last defined ability to be called with guests.

We may also use the parameter abroche but maybe passing an array of options to make the user type `allowGuest` by his hand .. would be like that :

```PHP
$gate->define('show-article', function ($user, Article $article) {
    //
}, ['allowGuest' => true])
```

@taylorotwell 
What do you think about that?
Do you have a better suggestions to make it work with both ability and filters in a consistent way?

**Comment by mmghv** [comment]
Also, Do you have a better name for `allowGuest` that shows we are allowing the ability to be **checked** with guests, Not allowing the ability to be absolutely **given** to guests.

**Comment by Jaspaul** [comment]
@mmghv To solve the problem you're running into, would you be able to just update your base request class to resolve a `User` that is flagged as a guest instead of returning a null? Then you could simply leverage something like `isGuest()` right on that object?

**Comment by mmghv** [comment]
@Jaspaul The problem is not how to make the ability accept a guest user (which is basically null), It's how can the developer mark an ability to be called with guests, The default behavior **MUST** stay the same (which is guests are immediately denied the ability [If not told otherwise]). 

Beside, If `$user` is an object, It should correspond to an authenticated user, Otherwise it's a BC break.

**Comment by Jaspaul** [comment]
@mmghv I was suggesting that you modify your application code instead of changing the underlying framework. You would likely have to update a few of your policies to work, based on the example you've provided, but the changes should be minor.

**Comment by mmghv** [comment]
@Jaspaul Of course this is up to the developer he can do that, Actually some of who wanted this feature did something similar to that, But it's a bit of extra work and would be nice if the framework supports this feature out of the box, Beside, If it's done the way you suggests, It won't provide some of other later benefits and best-practices that the framework can provide out of the box (like including the `index` ability by default with the `ResourceAbilityMap`)

**Comment by donnysim** [comment]
Wouldn't this introduce unwanted behavior? Let's say I defined `can-comment` ability and allowed it for the guest, logged in user goes to a post and makes a comment - no problem, now the logged in user goes to take coffee or something, leaves the page too long, sessions expires, get's back and makes another comment - what would happen is that he made a comment as a guest without even knowing. How would this be handled? the example is probably terrible but I bet it's valid.

**Comment by mmghv** [comment]
@donnysim Of course that's the developer problem if he `decided` to allow guests to comment,  here I'm not suggesting you allow abilities for guests, I'm just making sure you can do so when this is the desired behavior. 

And to answer your question, I would make sure that guest commenting is distinguished from users,  Maybe a note below the input and the user profile picture

**Comment by donnysim** [comment]
But you basically write policy map in AuthServiceProvider, if you'd define closure abilities, probably would do it in AuthServiceProvider, so what prevents you from adding separate array with abilities for guests in gate and then just checking it when user is null instead?

```
    protected $guestAbilities = [];

   ....

        if (!$user) {
            if (isset($this->guestAbilities[$ability . '-' . $arugments[0]]) {  // some logic to resolve ability and model etc
                 return true;
            }

            return false;
        }
```

**Comment by mmghv** [comment]
That's perfectly okay with abilities, but can't work with `beforr` and `after` filters because it might be more than one filter, the gate allows so, so i need a way that is consistent with abilities and before filters.

**Comment by donnysim** [comment]
But it wouldn't reach before and after filter if you check on `if (!$user) {`. What would you do in before/after filter for guests anyway? Check their IP and deny based on that?

**Comment by mmghv** [comment]
You could do anything, maybe based on other things you absolutely allow or deny all abilities, or maybe just add some log, the important thing that if you have the ability to allow guests to call some abilities you also should be able to interrupt them at the before/after filters.

**Comment by donnysim** [comment]
Wouldn't it be better to separate user and guest behaviors then instead of trying to clump them together?   I mean where it works for one or the other, not both, and by that I mean if it's guest, authenticated checks are ignored, if it's authenticated user - guest checks are ignored. And maybe I want to have `guestResolver` where it passes a `Guest` object which contains some information or methods, which I actually did have a though about, but never decided if it's worth making.

**Comment by mmghv** [comment]
You mean we define two `add-comment` abilities one is checked if user is authenticated and one if it's guest? I guess that would be harder than doing something like this :

```PHP
$gate->define('show-article', function ($user, Article $article) {
    return $user || $article->visibility = 'all';
}, true);
```

**Comment by donnysim** [comment]
I didn't specifically had in mind that you'd specify it twice, for policy it could check if `guestIndex` method exists for guests and `index` method for , etc.. didn't think about closures as I never used them in any project.

**Comment by mmghv** [comment]
That seems a good idea for policies but I can't think of a consistent way to do the same with closure abilities without repeating ourselfs especially most of the time the logic in the ability is just simple.

**Comment by taylorotwell** [comment]
I'm just not a big fan of this approach I don't think.

**Comment by taylorotwell** [comment]
IMO the whole point of authorization is that there is some unique thing about the given user that does or does not give them permission to perform X. All guests can inherently perform the same actions as all other guests.

**Comment by mmghv** [comment]
@taylorotwell 
>  All guests can inherently perform the same actions as all other guests.

I guess you misunderstood the purpose of the PR, It doesn't distinguish one guest from another, It just allows you to set (chosen) abilities to be called with guests instead of immediately denying all abilities for guests.

**Comment by mmghv** [comment]
If it's the `boolean` parameter I can redo the PR and make it work with chaining by making the `define` method return an `Ability` object and send this PR to the `master` branch .

**Comment by eduarguzher** [comment]
is there a work around for that? i would like to use policies on guest users

**Comment by mmghv** [comment]
@eduarguzher You will need to extend the `Gate` class to add the desired behavior then you need to override the the gate service provider `Illuminate\Auth\AuthServiceProvider` registered in `config/app.php` to register your own version of the `Gate` class.

**Comment by jfsullivan** [comment]
@taylorotwell I have a use case that this enhancement would help to meet.  

I have multiple levels of security for a multi-tenant site where each tenant can set documents to be available to the public or to members-only using a site setting in the database.   In addition, each individual document could be set to be accessible only to certain groups of logged in users.  So in essence, the policy would need to check if the document itself is secured to a group and if not it would check the site setting.  If the site setting says "public" then a guest would have access but if it is "members" it would require a logged in user.  This is not currently possible with policies since they don't get called for guests.

**Comment by devcircus** [comment]
Authorization, in the context of abilities, gates, etc., doesn't make sense without an authenticated user. There are many ways to handle this. Seems like a good use case for a simple decorator.

**Pull request closed without merging**
