### PR TITLE
[5.6] Catches InvalidFileException when loading environment file with dotenv

### PR DESCRIPTION
**Pull request by shrink**
Dotenv may throw an exception when loading a `.env` file, either `InvalidPathException` or `InvalidFileException`. At present `LoadEnvironmentVariables` is only catching `InvalidPathException`. This means that when you provide an invalid `.env` file Laravel outputs an unhelpful error message, e.g:

```
APP_NAME=Laravel Framework
```

```
Fatal error: Uncaught ReflectionException: Class config does not exist in /app/vendor/laravel/framework/src/Illuminate/Container/Container.php:767 Stack trace: #0
/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('config') #1 
/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('config') #2 
[...]
```

Many are confused by this error: [1](https://github.com/laravel/dusk/issues/99), [2](https://github.com/barryvdh/laravel-dompdf/issues/192), [3](https://stackoverflow.com/questions/42025231/laravel-dusk-class-config-does-not-exist), [4](https://joelennon.com/fixing-uncaught-reflectionexception-laravel), [5](https://laracasts.com/discuss/channels/laravel/class-config-does-not-exist-in-laravel-54), [6](https://laracasts.com/discuss/channels/laravel/laravel-migration-from-52-to-55-class-config-does-not-exist).

This change captures the additional error, meaning that when invalid `.env` file is provided (usually because a value containing a space lacks quotation marks) Laravel will fall back to the default application config.

---

I think that when this error occurs Laravel should not continue executing[1] because it is a very difficult situation to debug without an error, and it's unlikely a developer will want their application to run without a `.env` — and if they do, they can create an empty `.env` file — but I haven't added it in case there is a use case I am not aware of that necessitates allowing the application run even with an invalid `.env` file provided. Any thoughts on terminating execution here?

[1] As far as I know the only way to output an error here would be `dd($e)` because the error handling functionality isn't loaded at this point in the bootstrap process.

### CODE REVIEW

**Comment by taylorotwell** [comment]
How do you trigger an InvalidFileException in this case?

**Comment by citricsquid** [comment]
The exception is thrown when a value that contains a space is not enclosed in quotation marks, e.g:

```
APP_NAME=Laravel Framework
```

https://github.com/vlucas/phpdotenv/blob/master/src/Loader.php#L220

```php
    // Unquoted values cannot contain whitespace
    if (preg_match('/\s+/', $value) > 0) {
        throw new InvalidFileException('Dotenv values containing spaces must be surrounded by quotes.');
    }
```

**Comment by decadence** [comment]
+1 for this. It's hard to debug because current Exception message says nothing about .env file.

**Comment by ntzm** [comment]
Surely this will make it harder to debug?

**Comment by citricsquid** [comment]
Although Laravel does create a `.env` file on install and Laravel does by default depend on the `APP_KEY` value in `.env` to be secure, it *is* possible that some Laravel applications out there do not have a `.env` file and so to implement my preferred solution would potentially break some applications (until they added an empty `.env` file).

The alternative is to keep the current behaviour and add additional behaviour for `InvalidFileException`, e.g:

```php
try {
    (new Dotenv($app->environmentPath(), $app->environmentFile()))->load();
} catch (InvalidPathException $e) {
    //
} catch (InvalidFileException $e) {
    dd('Fatal Error: Values in .env containing spaces must be surrounded by quotes.');
}
```

1. An application does not have a `.env` file: the default configuration is loaded
2. An application has an invalid `.env` file: the error message ("Values in .env containing spaces must be surrounded by quotes.") is dumped.

I have updated the pull request to use the backwards compatible behaviour — missing `.env` does not trigger an error, an error is only triggered when the `.env` is invalid.

**Comment by GrahamCampbell** [comment]
I don't think this is right. There are way more reasons parsing can fail than just double quotes missing!

**Comment by citricsquid** [comment]
@GrahamCampbell Are you sure? As far as I can tell the only place the `InvalidFileException` is used is when checking the file for values containing spaces that are missing quotes: https://github.com/vlucas/phpdotenv/blob/master/src/Loader.php#L251 — so the only way this error can occur is if a value is missing quotes.

**Comment by citricsquid** [comment]
@GrahamCampbell That would be my preference, if there is a way to handle errors correctly then that would be much better. However, as far as I can tell, at this point in the bootstrap process Laravel doesn't have access to anything necessary to error properly (i.e: the exception system depends on valid configuration) so it would require changes to the architecture. I could very well be wrong there, though, are there ways to error properly here?

Re: dumping exception message vs. a custom error message, the exception message does not explicitly state the issue is with the `.env` file and some developers (novice, esl) may not make the connection between the package name "Dotenv" and the file ".env", as the exception message is: "Dotenv values containing spaces must be surrounded by quotes.".

That said, *anything* (whether it's dumping the exception, or a custom error message, or even loading the default configuration) is an improvement over the current non-descript uncaught fatal error that causes so much confusion, so if there's a different approach to this problem that is better than mine then I support it.

**Comment by chrissound** [comment]
This also seems to occur if you have an error (In my case a call to a undefined function) within `config.php`.

**Pull request merged**
