### PR TITLE
[7.x] Fix: replaceInputPlaceholder() should replace :input by its displayable value

### PR DESCRIPTION
**Pull request by mpyw**
# Overview

This PR makes `Validator` to use custom values for replacing `:input` placeholders. The `getDisplayableValue()` method was used in rule-specific placeholders of the following rules but it did not support `:input`.

- `in`
  - `:values`
- `required_if`
  - `:other` `:value`
- `required_unless`
  - `:other` `:values`
- `before`
  - `:date`
- `ends_with`
  - `:values`
- `starts_with`
  - `:values`

From the testing code:

```php
$frameworks = [
    1 => 'Laravel',
    2 => 'Symfony',
    3 => 'Rails',
];

$trans = $this->getIlluminateArrayTranslator();
$trans->addLines(['validation.framework_php' => ':input is not a valid PHP Framework'], 'en');

$v = new Validator($trans, ['framework' => 3], ['framework' => 'framework_php']);
$v->addExtension('framework_php', function ($attribute, $value, $parameters, $validator) {
    return in_array($value, [1, 2]);
});
$v->addCustomValues(['framework' => $frameworks]);

$this->assertFalse($v->passes());

// Previously it was "3 is not a valid PHP Framework"
$this->assertSame('Rails is not a valid PHP Framework', $v->messages()->first('framework'));
```

# Diff

```diff
diff --git a/src/Illuminate/Validation/Concerns/FormatsMessages.php b/src/Illuminate/Validation/Concerns/FormatsMessages.php
index 378eb6c6b4f..b260dbecf58 100644
--- a/src/Illuminate/Validation/Concerns/FormatsMessages.php
+++ b/src/Illuminate/Validation/Concerns/FormatsMessages.php
@@ -295,7 +295,7 @@ protected function replaceInputPlaceholder($message, $attribute)
         $actualValue = $this->getValue($attribute);
 
         if (is_scalar($actualValue) || is_null($actualValue)) {
-            $message = str_replace(':input', $actualValue, $message);
+            $message = str_replace(':input', $this->getDisplayableValue($attribute, $actualValue), $message);
         }
 
         return $message;
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I suppose it's not tested. ;)

**Comment by mpyw** [comment]
I was checking that the existing tests were not broken :D

**Comment by GrahamCampbell** [comment]
> (If it breaks any tests, we should target 7.x rather than 6.x)

If, but not only if. Breaking changes are not just those that break the tests, since the framework doesn't have full test coverage of every feature and every expected behaviour. :)

**Comment by GrahamCampbell** [comment]
This does look like a breaking change, and so I'll update the target to 7.x.

**Comment by mpyw** [comment]
@GrahamCampbell Has it been fixed that the switching target branch breaks diff on GitHub? Previously I was need to close and resubmit my PR for preventing it from the bug.

**Comment by GrahamCampbell** [comment]
> Has it been fixed that the switching target branch breaks diff on GitHub?

This has never been the case. What you might be describing is that if you base your PR on master and send to 6.x, then you get all the commits from master in your PR as well. This is to be expected.

**Comment by driesvints** [comment]
> This has never been the case. 

Actually it was for a while in the past. You'd change the branch and sometimes a certain set of commits didn't show up. It caused quite some problems for us so we didn't allow branch switching for a while. Github has fixed this by now.

**Comment by GrahamCampbell** [comment]
> change the branch and sometimes a certain set of commits didn't show up.

That's a different bug though. That's "commits not showing up", rather than "loads of commits showing up before 'my changes'". ;P

**Pull request merged**
