### PR TITLE
[5.2] Support Arr:: and Collection::first() with a 1-param callback that operates only on collection values

### PR DESCRIPTION
**Pull request by evictor**

### CODE REVIEW

**Comment by adamwathan** [comment]
Having the index get passed as the first param has definitely bitten me in the ass a ton of times, but this would be a breaking change for anyone who ever has a situation where they _only_ care about what index was matched and are not using the second param :/

I wish the params were at least flipped, I dunno how much breakage is gonna be tolerated though.

**Comment by JosephSilber** [comment]
1. Reflection is slow. It shouldn't be used in these low-level utility functions.
2. We already have *many* callbacks that take the key as the second argument.

**Comment by anteriovieira** [comment]
I have the same opinion of @JosephSilber , the use of reflection in this case may require further processing.

**Comment by GrahamCampbell** [comment]
:-1: from me.

**Comment by evictor** [comment]
For your guys' edification, on a good machine the reflection used runs at 0.0000009ms and on a total piece of shit VM it runs at 0.000008ms.

So I appreciate your concern for performance, but in my opinion it is unfounded. Anyway if you're going to strike it down the least you could have done is not have encouraged me to resubmit under a different PR as you did. I mean, you're getting free labor—it's a gift, even if you don't like it. :)

Thanks,
Zeke

**Pull request closed without merging**
