### PR TITLE
[5.3] Hide pagination if it does not have multiple pages

### PR DESCRIPTION
**Pull request by garygreen**
Fixes #15125

### CODE REVIEW

**Comment by JosephSilber** [comment]
I'm not sure hiding the paginator is good UX. People will be looking for the pagination links.

**Comment by garygreen** [comment]
@JosephSilber it's how 5.2 behaved and all previous Laravel versions, never had a problem. Have you taken a look at the screenshots in #15124 ? It looks pretty silly to render those by default.

An alternative option could be to add a class to the paginator for `paginator-empty` when it detects there are not more than 1 page, that way the paginator can be easily hidden by css or styled differently if people wish.

**Comment by taylorotwell** [comment]
Did we actually test this one to see if it works :/

**Comment by garygreen** [comment]
@taylorotwell yes it's been tested, last one was a silly mistake.

The code now works the same as it did in 5.2:

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Pagination/BootstrapThreePresenter.php#L57
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Pagination/SimpleBootstrapFourPresenter.php#L38

**Pull request merged**
