### PR TITLE
[6.x] Improve Str::startsWith performance

### PR DESCRIPTION
**Pull request by dmitryuk**
Moving PR https://github.com/laravel/framework/pull/30949 to 6.x branch

### CODE REVIEW

**Comment by SjorsO** [comment]
It is counter-intuitive, but `strpos` actually performs worse than `substr`. This has been changed and reverted before, see https://github.com/laravel/framework/pull/16761#issuecomment-266558361

**Comment by GrahamCampbell** [comment]
@taylorotwell Why was this closed? This actually reduces my app's latency by 1.5% due to it registering so many events.

**Comment by 36864** [comment]
>It is counter-intuitive, but strpos actually performs worse than substr. This has been changed and reverted before, see #16761 (comment)

That is true very large haystacks, but false for small haystacks.

An even faster approach would be to use `preg_match` but only if we use a fixed delimiter, which would limit the usefulness of the function.

Maybe we can identify where `startsWith` is being called and replace it with `preg_match` in places where we know the allowed range of characters?

**Comment by taylorotwell** [comment]
@GrahamCampbell because it's slower.

**Comment by 36864** [comment]
Adapted the benchmark in the linked PR to test over a range of haystack lengths and also compare calling the functions directly to calling the current implementation of `Str::startsWith`:
```php
$nb = 100000;
    $haystack_length = 10;
    while ($haystack_length < 100000000) {
      $haystack = (string) str_repeat('a', $haystack_length);
      $needle = 'b';
      $t1 = microtime(true);
      for ($i = $nb; $i--; ) {
        substr($haystack, 0, strlen($needle)) === (string) $needle;
      }
      $t2 = microtime(true);
      for ($i = $nb; $i--; ) {
        strpos($haystack, (string) $needle) === 0;
      }
      $t3 = microtime(true);
      for ($i = $nb; $i--; ) {
        preg_match("/^$needle/", $haystack);
      }
      $t4 = microtime(true);
      for ($i = $nb; $i--; ) {
        Str::startsWith($haystack, $needle);
      }
      $t5 = microtime(true);

      $times = [
        'substr' => $t2 - $t1,
        'strpos' => $t3 - $t2,
        'preg_match' => $t4 - $t3,
        'startswith' => $t5 - $t3,
      ];
      asort($times);
      $this->info("Haystack Length: $haystack_length");
      print_r($times);
      $haystack_length *= 10;
    }
```

Test results on my laptop, PHP 7.2.10:

```Haystack Length: 10
Array
(
    [strpos] => 0.0066189765930176
    [substr] => 0.0094060897827148
    [preg_match] => 0.016417026519775
    [startswith] => 0.042016983032227
)
Haystack Length: 100
Array
(
    [strpos] => 0.0068380832672119
    [substr] => 0.010514974594116
    [preg_match] => 0.017052888870239
    [startswith] => 0.043543815612793
)
Haystack Length: 1000
Array
(
    [substr] => 0.0099210739135742
    [strpos] => 0.012561082839966
    [preg_match] => 0.015492916107178
    [startswith] => 0.043156862258911
)
Haystack Length: 10000
Array
(
    [substr] => 0.010730028152466
    [preg_match] => 0.016089916229248
    [startswith] => 0.042931795120239
    [strpos] => 0.054877042770386
)
Haystack Length: 100000
Array
(
    [substr] => 0.009943962097168
    [preg_match] => 0.01657509803772
    [startswith] => 0.041932106018066
    [strpos] => 0.5598418712616
)
Haystack Length: 1000000
Array
(
    [substr] => 0.0098121166229248
    [preg_match] => 0.016644954681396
    [startswith] => 0.0452561378479
    [strpos] => 5.5760638713837
)
Haystack Length: 10000000
Array
(
    [substr] => 0.010479927062988
    [preg_match] => 0.015511035919189
    [startswith] => 0.040539979934692
    [strpos] => 84.734483003616
)```

`strpos` is clearly unusable for long strings, but it is faster for small strings.
`preg_match` isn't actually faster as I stated earlier. I had run a couple of tests but either I misread the results or they were too small to account for timing variations.

One of the reasons mentioned for this PR was startup time when many events are registered. I am unsure of where `startsWith` is used in that process, but event names are likely to be small (< 100 characters) so it might be worth going through and replacing `startsWith` with straight `strpos` in those instances, assuming the extra features of startsWith aren't needed.

**Comment by taylorotwell** [comment]
I agree that if there is a hot location in the framework where we use `startsWith` consistently on small strings then we could just switch to using regular `strpos` in those cases.

**Comment by GrahamCampbell** [comment]
Fair enough. I'll see which cases I think should change shortly. The biggest optimisation I found for the framework bootup was to comment out the notification service provider, actually. It takes a while to boot, so if people are not using notifications, they can get a decent improvement (larger than the speedup from this PR).

**Comment by Arkanius** [comment]
> The biggest optimisation I found for the framework bootup was to comment out the notification service provider, actually. It takes a while to boot, so if people are not using notifications, they can get a decent improvement (larger than the speedup from this PR).

Do you think this could be documented? I'll try to remove and do some benchmarks in my apps

**Pull request closed without merging**
