### PR TITLE
[5.2] Allow to pass multiple arguments to Authorize

### PR DESCRIPTION
**Pull request by jvdlaar**
My first pull request to Laravel so if I'm doing things wrong, please be gentle ;-)

I have a situation where I have a policy where user X is allowed to do an action on user Y only if user X has a specific role and user Y has a relation to user X. So for this policy I need both objects.

My url is: user/{user}/disconnect/{professional}

So I have this for a route (I'm using laravel collective annotations):

```
    /**
     * @Get("{user}/disconnect/{professional}", as="users.disconnectProfessional")
     * @Middleware("can:disconnect-professional,user,professional")
     */
```

As far as I've tried it's not possible to do this with the current Authorize middleware. Therefore my patch.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks. Please use camelCase though, and since you've made a breaking change to a public method, this probably needs to go to L5.3.

**Comment by jvdlaar** [comment]
Would it be better if I left the function signature the same?

Also perhaps the function comments should indicate that there is the possibility to pass multiple params.

**Comment by taylorotwell** [comment]
Is `user` the authenticated user? If so, you don't need to pass it since it will be the first argument given to the policy anyways? Or is it not the authenticated user?

**Comment by jvdlaar** [comment]
No user is a different user. The use case is like this:

You are logged in as a manager.
The user is a client of your company.
The professional is an employee of your company.

The manager can assign professionals to a client. And with the url above you go to a page where you can disconnect this professional from the client.

So the access checks are:
- logged in user is allowed to do this
- professional is connected to the client

So the first check only needs the logged in user, which currently is possible.
The second check is only possible if you have both the professional and the client object.

**Comment by taylorotwell** [comment]
My suggestion would be to send this to 5.3 which requires PHP 5.6 and then you won't need do that func_get_args stuff since you can just use argument unpacking.

**Pull request closed without merging**
