### PR TITLE
Config recursive merge

### PR DESCRIPTION
**Pull request by cxbyte**
It would be great if i could recursive merge main config with package config, for example for new broadcasting driver support

config/broadcasting.php
```
'default' => env('BROADCAST_DRIVER', 'null'),
    'connections' => [
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_KEY'),
            'secret' => env('PUSHER_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                //
            ],
        ],
        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
        ],
        'log' => [
            'driver' => 'log',
        ],
        'null' => [
            'driver' => 'null',
        ]
    ]
```
package broadcasting.php
```
    'connections' => [
        'zmq' => [
            'driver' => 'zmq',
        ]
    ]
```

### CODE REVIEW

**Comment by JoostK** [comment]
This will likely break a lot of applications.

**Comment by GrahamCampbell** [comment]
The merge is intentionally not recursive, because a recursive merge is not desirable.

**Comment by cxbyte** [comment]
Yes you are probably right. Maybe add separate method mergeRecursiveConfigFrom?

**Comment by cxbyte** [comment]
Although. Probably not necessary. Many people do not need it. Ok, i will make it manually.

**Pull request closed without merging**
