### PR TITLE
Add Event as parameter to the before/after callbacks Scheduled Events

### PR DESCRIPTION
**Pull request by makije**
Add the Event as parameter for the callbacks, so that the closure can get data about the Event.

The use case is that I want to log before and after all my scheduled tasks.
Hence I would like to use the same closure, and get the description from the Event.

### CODE REVIEW

**Comment by sisve** [comment]
The problem with adding these things in the middle of the 5.5 lifecycle is that you could release your code as a package, and target Laravel 5.5, but it wouldn't work for all released versions of Laravel 5.5. Your package could break for me since I've got an older release of Laravel 5.5, depending on how your declared your parameters for the callbacks.

It's easiest to just target the next release where these type of problems are more accepted.

**Comment by taylorotwell** [comment]
Needs better code example of what this could be used for.

**Comment by makije** [comment]
We would like to log every time a Scheduled command executes, and find out for how long they run,
so we can present the data for one, and two figure out which commands takes the longest time, so we can dig deeper into why they take so long and optimize run time.

I hope it make sense.

Consider the following:
```
$schedule->command('command')
    ->everyMinute()
    ->name('command')
    ->before(function() {
        CronLog::create([
            'command' => 'command',
            'action' => 'started',
        ]);
    })
    ->then(function() {
        CronLog::create([
            'command' => 'command',
            'action' => 'stopped',
        ]);
    });
```
We have a lot of jobs like this, for different types of reporting for the users and will add more in the future.
So it would be cool if we could translate the closures into a more generic one, since we now have one for each case for each scheduled command.

The idea is to translated it into something like

```
$before = function($event) {
    CronLog::create([
        'command' => $event->getSummaryForDisplay(),
        'action' => 'started',
    ]);
};

$after = function($event) {
    CronLog::create([
        'command' => $event->getSummaryForDisplay(),
        'action' => 'stopped',
    ]);
};

$schedule->command('command')
    ->everyMinute()
    ->name('command')
    ->before($before)
    ->then($after);

```
This will reduce the amount of line to read to understand the schedule.
Perhaps even an other parameter could be added to the callback about when it was called "before" or "after" but I am ok with having two closures

**Comment by sisve** [comment]
This can be done by extending/replacing the schedule:run command, and adding your logging calls before and after the call to `$event->run(...)`.

https://github.com/laravel/framework/blob/2e57d9646263ceb43ed34c170291a4c1b4fb8342/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php#L52-L62

**Comment by makije** [comment]
@sisve Thanks for the suggestion, might end up doing that.
It is just a bit more inconvenient, and kind of an odd place to do it.
Especially when the day comes, only a subset of command should do this kind of logging we are currently looking for.

**Pull request closed without merging**
