### PR TITLE
Updated SqlServer grammar date format.

### PR DESCRIPTION
**Pull request by MacTEC**
Previous format (`Y-m-d H:i:s.000`) caused 'The format separator does not match' error when a DateTime string with non-zero millisecond value was supplied.

Note that although `u` in the format stands for microseconds rather than milliseconds, it does not make any difference as Carbon does not support fraction of a second anyway.

Fixes #2591 #2235.

### CODE REVIEW

**Comment by jaybill** [comment]
@ricksuggs Code worked for me with one minor change.

My timestamps are coming back as:

    Nov  6 2014 06:15:000PM

So my getDateFormat() function is:

    public function getDateFormat()
    {
        return 'M  j Y h:i:s:uA';
    }

And everything works correctly.

**Comment by priithansen** [comment]
@MacTEC just stumbled on this same bug with sql server. What are the issues You discovered with the :u approach?

**Comment by blindMoe** [comment]
I cannot seem to find a solution that works for me in all scenarios.  If I just set it to this I can do SELECTs just fine but I cannot perform INSERTs:

```
return 'Y-m-d H:i:s';
```

When I set it to the following I can INSERT but not SELECT.  Really frustrating

```
return 'Y-m-d H:i:s.000';
```
or
```
return 'Y-m-d H:i:s+';
```

When I try to use :u .u0 or .uA I get errors all the time.  This is on an Amazon EC2 instance connecting to an MS SQL 2012 RDS instance.  I would love if someone could provide a solution that worked all the way around.  I am pretty stumped.

**Comment by priithansen** [comment]
So far my workaround has been making sure my milliseconds are always 000. Laravel never saves anything other anyway just have to make sure all the other scripts saving data also do that.

**Comment by priithansen** [comment]
I think the problem lies in that the sql grammar date fromat is used in both when formating the sql server **millisecond** percision date string "2015-10-20 10:12:11.040" and also when formating the DateTime object with **microsecond** percision "2015-10-20 10:12:11.040000" pack to string for saving in sql. 

So with current system as I understand it the format string needs to work both for creating a date from sql string with DateTime::createFromFormat($dateFromatString, $stringDateFromSql) and also with $dateTimeObject->format($dateFromatString) when saving DateTime objects back to database.

Using .*** or + when selecting data is fine but results in date sting with **** or + appended to the date string when going the other way around.

**Comment by priithansen** [comment]
So in short with the current system in place using the formating string in both ways I don't see any way we could find a combination that would work with

$format = ?
$dateStringFromSql = '2015-10-20 12:00:00.123';

$dateObject = Carbon::createFromFormat('$format, $dateStringFromSql);
$dateStringToSql = $dateObject->format($format);

Should be $dateStringFromSql === $dateStringToSql

@taylorotwell any possilibity we could also introduce setDateFormat to sql grammar so to finally get it working correctly with mssql dates that have milliseconds?

**Comment by tschallacka** [comment]
Old issue, but I ran into it, 
I fixed it by adding this to attributesToArray in  lluminate\Database\Eloquent\Model;

    foreach ($this->getDates() as $key)   {
        if ( ! isset($attributes[$key])) continue;
        if(substr($attributes[$key],-3) != '000') {
            $attributes[$key] = substr($attributes[$key],0,-3).'000';
         }

**Pull request closed without merging**
