### PR TITLE
[5.4] Updating Filesystem to be compatible with contract

### PR DESCRIPTION
**Pull request by lk77**
Hello,

i'm adding recursive parameter to files function in Filesystem class to be compatible with the Filesystem 
contract :
```
    /**
     * Get an array of all files in a directory.
     *
     * @param  string|null  $directory
     * @param  bool  $recursive
     * @return array
     */
    public function files($directory = null, $recursive = false);
```
 thanks.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
When was this contract updated?

**Comment by GrahamCampbell** [comment]
Oh, but this class does not implement the contract?

**Comment by GrahamCampbell** [comment]
The contract is for https://github.com/laravel/framework/blob/5.4/src/Illuminate/Filesystem/FilesystemAdapter.php.

**Comment by GrahamCampbell** [comment]
👎 for this code changing, since boolean parameters are against laravel's original ease of use vision.

**Comment by lk77** [comment]
Sorry then , i thought it was for Filesystem class.

**Comment by GrahamCampbell** [comment]
No problem. :)

**Pull request closed without merging**
