### PR TITLE
[5.6] Retrieve the validated data of multidimensional input

### PR DESCRIPTION
**Pull request by louisfisch**
## The problem:
The `validated()` method is used to retrieve no more than the data that passed the validation when using a form request. For now it filters only the first level. It means if your request data is structured on two (or more) levels and some unwanted data is present in a sub level, then it will still be present even if the validated method was used.

### Example

The rules for the request
```
[
    'main_address.city' => 'required',
    'other_addresses.*.city' => 'required',
    'password' => 'required',
    'username' => 'required'
]
```

Request input data
```
[
    'foo' => 'bar',
    'main_address' => [
        'city' => 'specified',
        'country' => 'specified'
    ],
    'other_addresses' => [
        [
            'city' => 'specified'
        ],
        [
            'baz' => 'qux',
            'city' => 'specified'
        ]
    ],
    'password' => 'specified',
    'username' => 'specified'
]
```

The `validated()` method's result
```
[
    'main_address' => [
        'city' => 'specified',
        'country' => 'specified',
    ],
    'other_addresses' => [
        [
            'city' => 'specified'
        ],
        [
            'baz' => 'qux',
            'city' => 'specified'
        ]
    ],   
    'username' => 'specified',
    'password' => 'specified'
]
```
The attributes `foo` and `email_address` that weren’t validated are not present anymore. Yet the attributes `main_address.country` and `other_addresses.1.baz` are still present.

## The solution
This pull request makes sure the `validated()` method returns no more than the validated data even if the request input data is structured on multiple levels

### Example
Given the rules and the input data above, the  `validated()` method's result is now
```
[
    'main_address' => [
        'city' => 'specified'
    ],
    'other_addresses' => [
        [
            'city' => 'specified'
        ],
        [
            'city' => 'specified'
        ]
    ],   
    'username' => 'specified',
    'password' => 'specified'
]
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Comment by taylorotwell** [comment]
This will need a test.

**Comment by louisfisch** [comment]
I tried to better explain the problem and the benefit of this pull request (see my edited first comment). I improved the unit test of the `validated()` method in a commit. Maybe you could re-open this pull request.

**Comment by renanBritz** [comment]
Hello @taylorotwell !

I had this issue today as well.

The $request->validated() method does not filter array fields, it simply includes all fields in an array.

That could lead to potential vulnerabilities.

I'm using Doctrine, so Eloquent's $guarded and $fillable are not an option to me.

@louisfisch example demonstrates that. His **other_addresses** array expects only a **city** field. But when passed a **baz** field, that field was present in the validated() method result.

Unfortunately I'm not familiar with contributing, testing, etc. Maybe someone from the community could help us?

Best regards!

**Pull request closed without merging**
