### PR TITLE
[5.7] Fix(tester): TestResponse assertExactJson does not work for empty JSON objects

### PR DESCRIPTION
**Pull request by alberthuang24**
Solved the problems mentioned in #25960 and #25769.

After the old decodeResponseJson directly operates on the response content json_decode($content, true), it is impossible to tell the difference between empty object and empty array.

```
$data = [
    'a' => new class {}
];

var_dump(json_encode($data)); 
var_dump(json_decode(json_encode($data), true)); 
var_dump(json_decode(json_encode($data)));


result: 

string(8) "{"a":{}}"
array(1) {
  ["a"]=>
  array(0) {
  }
}
object(stdClass)#4313 (1) {
  ["a"]=>
  object(stdClass)#4315 (0) {
  }
}
```
Therefore, if we want to distinguish between empty object and empty array, we need to change the second parameter $assoc to false.
But that's not compatible with the logic that preceded it. The assoc array is resolved to stdclass.
So. for compatibility, I have json_decode($data, true) and json_decode($data, false); Only get json_decode($data, false); The empty object inside is thus compatible with the previous logic, and the bug is fixed.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I feel like your method needs a more descriptive name... something about maybe normalizing arrays and objects...

Also I think the conditional in your loop could be extracted into something more descriptive as well. It's not clear what is going on there.

**Comment by HongjiangHuang** [comment]
Ok, Well, I'm going to improve it.

**Comment by taylorotwell** [comment]
OK feel free to re-submit with those changes when you have time.

**Comment by dbudwin** [comment]
Thanks for your continued work on this @HongjiangHuang!  This issue is blocking progress on my project (we don't submit code without proper tests around it), so I'm looking forward to seeing this bug fix.  Please let me know if I can be of help.

**Pull request closed without merging**
