### PR TITLE
[5.1] Add string representations of boolean values

### PR DESCRIPTION
**Pull request by rosswilson252**
true/false values from ajax request get cast to string so validateBoolean() currently returns false for these values.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
This is a breaking change in behaviour.

**Comment by taylorotwell** [comment]
They don't really get casts to strings though do they? At least not in my experience when using Angular / Vue.

**Comment by rosswilson252** [comment]
They do when posting with jQuery (I've only just started looking into Vue and I haven't used Angular before).
I've found a few pages on the issue that support what I've found:

[jQuery Forum](https://forum.jquery.com/topic/ajax-sending-json-data-with-boolean-value)
[SO Question](http://stackoverflow.com/questions/14716730/send-a-boolean-value-in-jquery-ajax-data)
[So Question](http://stackoverflow.com/questions/3654454/boolean-variables-posted-through-ajax-being-treated-as-strings-in-server-side)

However, if I am just missing something then my I'm sorry.

Also, apologies, I should have read the tests for this method before submitting my request. 

Either way, I know I can always just use 1/0 instead of true/false for submitting requests, however, it just seemed to be more readable and accurate to use the correct data types when using jQuery.

**Comment by ahmed-aliraqi** [comment]
What about using `filter_var` @GrahamCampbell @taylorotwell ?
```php
/**
 * Validate that an attribute is a boolean.
 *
 * @param  string  $attribute
 * @param  mixed  $value
 * @return bool
 */
public function validateBoolean($attribute, $value)
{
    return filter_var($value, FILTER_VALIDATE_BOOLEAN);
}
```

**Pull request closed without merging**
