### PR TITLE
[8.x] Adding support for using a different Redis DB in a Sentinel setup

### PR DESCRIPTION
**Pull request by tim-hanssen**
Following the Cache and Database documentation, it should be possible to create multiple cache stores from the Laravel database config.

This doest work if someone is using a Redis Sentinel configuration.

The host can be changed, but not the selected DB. This change won't break current configurations.

Current config:
```
    'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'replication' => 'sentinel',
            'service' => 'mymaster',
            'parameters'  => [
                    'password' => env('REDIS_PASSWORD', null),
                    'database' => env('REDIS_DATABASE', null),
            ],
        ],

        'default' => [
            'tcp://'.env('REDIS_HOST_1').':26379?timeout=0.100',
            'tcp://'.env('REDIS_HOST_2').':26379?timeout=0.100',
            'tcp://'.env('REDIS_HOST_3').':26379?timeout=0.100',
        ],

        'storetwo' => [
            'tcp://'.env('REDIS_HOST_1').':26379?timeout=0.100',
            'tcp://'.env('REDIS_HOST_2').':26379?timeout=0.100',
            'tcp://'.env('REDIS_HOST_3').':26379?timeout=0.100',
        ],
    ],
```

New config:

```
    'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'replication' => 'sentinel',
            'service' => 'mymaster',
            'parameters'  => [
                'default' => [
                    'password' => env('REDIS_PASSWORD', null),
                    'database' => env('REDIS_DATABASE', null),
                ],
                'storetwo' => [
                    'password' => env('REDIS_PASSWORD', null),
                    'database' => env('REDIS_DATABASE_TWO', null)
                ]
            ],
        ],

        'default' => [
            'tcp://'.env('REDIS_HOST_1').':26379?timeout=0.100',
            'tcp://'.env('REDIS_HOST_2').':26379?timeout=0.100',
            'tcp://'.env('REDIS_HOST_3').':26379?timeout=0.100',
        ],

        'storetwo' => [
            'tcp://'.env('REDIS_HOST_1').':26379?timeout=0.100',
            'tcp://'.env('REDIS_HOST_2').':26379?timeout=0.100',
            'tcp://'.env('REDIS_HOST_3').':26379?timeout=0.100',
        ],
    ],
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please can you include some tests?

**Comment by tim-hanssen** [comment]
@GrahamCampbell sure, I added a connection test.

**Comment by driesvints** [comment]
Wouldn't it be better to override options directly on the stores instead of in the options array?

**Comment by tim-hanssen** [comment]
If you would ask me @driesvints I think this would make more sense; 

`     'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),
        
        'default' => [
            'hosts' => [
                'tcp://'.env('REDIS_HOST_1').':26379?timeout=0.100',
                'tcp://'.env('REDIS_HOST_2').':26379?timeout=0.100',
                'tcp://'.env('REDIS_HOST_3').':26379?timeout=0.100',
                ],
            'options' => [
                'replication' => 'sentinel',
                'service' => 'mymaster',
                'parameters'  => [
                        'password' => env('REDIS_PASSWORD', null),
                        'database' => env('REDIS_DATABASE', null)
                ],
            ]
        ],

        'storetwo' => [
            'hosts' => [
                'tcp://'.env('REDIS_HOST_1').':26379?timeout=0.100',
                'tcp://'.env('REDIS_HOST_2').':26379?timeout=0.100',
                'tcp://'.env('REDIS_HOST_3').':26379?timeout=0.100',
                ],
            'options' => [
                'replication' => 'sentinel',
                'service' => 'mymaster',
                'parameters'  => [
                        'password' => env('REDIS_PASSWORD', null),
                        'database' => env('REDIS_DATABASE_TWO', null)
                ],
            ]
        ],
    ],`

**Comment by driesvints** [comment]
That's a big breaking change so we cannot do that. Maybe something more like:

```php
    'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'replication' => 'sentinel',
            'service' => 'mymaster',
        ],

        'default' => [
            'tcp://'.env('REDIS_HOST_1').':26379?timeout=0.100',
            'tcp://'.env('REDIS_HOST_2').':26379?timeout=0.100',
            'tcp://'.env('REDIS_HOST_3').':26379?timeout=0.100',
            'options' => [
                'parameters'  => [
                        'password' => env('REDIS_PASSWORD', null),
                        'database' => env('REDIS_DATABASE', null),
                ],
            ],
        ],

        'storetwo' => [
            'tcp://'.env('REDIS_HOST_1').':26379?timeout=0.100',
            'tcp://'.env('REDIS_HOST_2').':26379?timeout=0.100',
            'tcp://'.env('REDIS_HOST_3').':26379?timeout=0.100',
            'options' => [
                'parameters'  => [
                        'password' => env('REDIS_PASSWORD', null),
                        'database' => env('REDIS_DATABASE_TWO', null),
                ],
            ],
        ],
    ],
```

But not ideal. I agree that your solution is better but every app would break if we changed it like that.

**Comment by tim-hanssen** [comment]
Yes I agree, that last comment looks to me as the most easy way, would you like me to reflect that into the commit?

**Comment by driesvints** [comment]
Let's see what Taylor says.

**Comment by taylorotwell** [comment]
Where do we even document that you can pass these `replication` option keys, etc.?

**Comment by tim-hanssen** [comment]
I don't think there are any docs on how to do this, but since the config is passed to predis, it's just works with their documentation (except the store parameters). But Sentinel is a very much used setup in a more enterprise infra.

**Pull request merged**
