### PR TITLE
[10.x] Integrate PHP-FPM in docker-compose for development

### PR DESCRIPTION
**Pull request by akiyamaSM**
The motivation of this PR is to integrate the PHP-FPM container to allow more developers to contribute to the framework without being forced to install/switch to the correct PHP version unless I missed something.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by akiyamaSM** [comment]
Sorry @taylorotwell but i don’t see how this can be done as package. The whole idea is not to install dependencies. The whole docker-compose file won’t affect the end experience. I understand that you have many PR to review but i would love to give it a try.

**Comment by moghwan** [comment]
@taylorotwell I'm one of those who has been waiting for this docker integration since i'm working with different PHP versions. Is there any chance we can contribute to this branch so you can reconsider reviewing it?

**Comment by akiyamaSM** [comment]
@driesvints @nunomaduro @timacdonald 
If you have a 5min of your time. can you review this PR?

**Comment by driesvints** [comment]
We're currently not considering this, sorry. Please also do not mass-mention people in PRs.

**Pull request closed without merging**
