### PR TITLE
4.2 fix pagination error when perPage attribute is less than zero

### PR DESCRIPTION
**Pull request by phpawy**
This commit is to display a user friendly message when someone use the function paginate() with a negative parameter for number of pages.

Sample code for reproducing the error:
<?php
.....
$adsnum = 25;
$list_ads = Ads::paginate(15 - $adsnum);
?>

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please send to 5.1.

**Comment by GrahamCampbell** [comment]
Also, this diff is impossible to read because yo've changed loads of stuff...

**Comment by phpawy** [comment]
ok I will fix the diff. but you don't accept sending for 4.2?

**Comment by GrahamCampbell** [comment]
Only 5.1 is supported, sorry.

**Comment by GrahamCampbell** [comment]
* Support for 4.0 was dropped as soon as 4.1 was released.
* Support for 4.1 was dropped as soon as 4.2 was released.
* Support for 4.2 was dropped as soon as 5.0 was released.
* Support for 5.0 was dropped as soon as 5.1 was released.
* 5.1 is an LTS release, so will continue to receive bug fixes even after 5.2 has been released.

**Comment by GrahamCampbell** [comment]
https://i.starbs.net/XRMb

**Pull request closed without merging**
