### PR TITLE
[5.8] Fix isset if not array or ArrayAccess

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Review by matthewnessworthy — APPROVED** [review]

**Comment by taylorotwell** [comment]
This feels hard to read. What are you trying to check?

**Comment by taylorotwell** [comment]
Why did we stop using array_key_exists in the first place? Was it a PHP 7.4 reason?

**Comment by jasonvarga** [comment]
I haven't wrapped my head around the change yet, but I can confirm that upgrading from 5.8.34 to 5.8.35 broke because of [this change](https://github.com/laravel/framework/commit/dbb3b8c7f503f872d63b0fd8aecfcc60b1a19ca8#diff-051f4207f04389c85d22b75ab28c71a6L53) (which this PR fixes, at least for me)

**Comment by taylorotwell** [comment]
In what situation is `$offset` an array?

**Comment by jasonvarga** [comment]
Its `$this->resource` that's the issue.

See [this comment](https://github.com/laravel/framework/commit/dbb3b8c7f503f872d63b0fd8aecfcc60b1a19ca8#r34945768)

> Cannot use object of type Results\ListingResult as array

If your resource doesn't implement ArrayAccess, you now get an error.
When it was using `array_key_exists`, it would just return false and continue without an issue.

**Comment by taylorotwell** [comment]
How does yours not implement ArrayAccess? Are you extending the built-in Laravel resource stuff?

**Comment by jasonvarga** [comment]
```
return Illuminate\Http\Resources\Json\Resource::collection($items);
```

where `$items` is a collection of `Arrayable` (but not `ArrayAccess`) objects.

To be fair, the items are not Eloquent models, but it worked just fine.

**Comment by taylorotwell** [comment]
Can someone post an entire stack trace so we can see where this is even being called from and get a better idea of the overall use case?

**Comment by matthewnessworthy** [comment]
There are a couple of cases where the Resource is instantiated with a non array, non ArrayAccess object

**Comment by taylorotwell** [comment]
@matthewnessworthy Like? Where? When? How? We need more details.

**Comment by driesvints** [comment]
Where does the `offsetExists` happen?

**Comment by jasonvarga** [comment]
I misspoke - `$items` in my comment above is a `LengthAwarePaginator`.

The stack trace looks like:

```
[2019-09-04 20:51:57] local.ERROR: Cannot use object of type Statamic\Data\Entries\Entry as array {"userId":"jason","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Cannot use object of type Statamic\\Data\\Entries\\Entry as array at /Users/jason/Code/statamic/three/laravel/vendor/laravel/framework/src/Illuminate/Http/Resources/DelegatesToResource.php:53)
[stacktrace]
#0 /Users/jason/Code/statamic/three/laravel/vendor/laravel/framework/src/Illuminate/Support/Arr.php(148): Illuminate\\Http\\Resources\\Json\\JsonResource->offsetExists('resource')
#1 /Users/jason/Code/statamic/three/laravel/vendor/laravel/framework/src/Illuminate/Support/helpers.php(524): Illuminate\\Support\\Arr::exists(Object(Illuminate\\Http\\Resources\\Json\\Resource), 'resource')
#2 /Users/jason/Code/statamic/three/laravel/vendor/laravel/framework/src/Illuminate/Support/Arr.php(387): data_get(Object(Illuminate\\Http\\Resources\\Json\\Resource), Array)
#3 /Users/jason/Code/statamic/three/laravel/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1107): Illuminate\\Support\\Arr::pluck(Array, Array, NULL)
#4 /Users/jason/Code/statamic/three/laravel/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Support\\Collection->pluck('resource')
#5 /Users/jason/Code/statamic/three/laravel/vendor/laravel/framework/src/Illuminate/Pagination/AbstractPaginator.php(647): Illuminate\\Pagination\\AbstractPaginator->forwardCallTo(Object(Statamic\\Data\\Entries\\EntryCollection), 'pluck', Array)
#6 /users/jason/code/statamic/three/cms/app/Extensions/Pagination/LengthAwarePaginator.php(34): Illuminate\\Pagination\\AbstractPaginator->__call('pluck', Array)
#7 /Users/jason/Code/statamic/three/laravel/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(28): Statamic\\Extensions\\Pagination\\LengthAwarePaginator->__call('pluck', Array)
#8 /Users/jason/Code/statamic/three/laravel/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1124): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->Illuminate\\Http\\Resources\\Json\\{closure}(Object(Illuminate\\Http\\JsonResponse))
#9 /Users/jason/Code/statamic/three/laravel/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(31): tap(Object(Illuminate\\Http\\JsonResponse), Object(Closure))
#10 /Users/jason/Code/statamic/three/laravel/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(71): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse(Object(Illuminate\\Http\\Request))
#11 /Users/jason/Code/statamic/three/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(733): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse(Object(Illuminate\\Http\\Request))
```

**Comment by taylorotwell** [comment]
It's a LengthAwarePaginator of plain PHP objects? No Eloquent stuff, etc?

**Comment by jasonvarga** [comment]
That's right, they are not Eloquent models.

**Comment by taylorotwell** [comment]
Hmm, OK. We may have to add this to the upgrade guide that all underlying objects of resources should implement ArrayAccess.

**Comment by driesvints** [comment]
@jasonlbeggs can you post the code of that object?

**Comment by GrahamCampbell** [comment]
For Laravel 5.8, at least, we shouldn't break code.

**Comment by jasonlbeggs** [comment]
@driesvints, I think you meant to tag @jasonvarga?

**Comment by jasonvarga** [comment]
I spoke to Dries outside of this thread, and landed on if you're not putting actual Resource objects in there, it was basically being misused. If it was working, it was a coincidence.

Might apply to @matthewnessworthy 's [issue](https://github.com/laravel/framework/issues/29858) too.

**Comment by driesvints** [comment]
@jasonlbeggs yes, sorry!

@jasonvarga yeah exactly. All resource objects should extend the `JsonResource` class (as it's shown in the docs). If you do that then you'll never run into this issue.

@GrahamCampbell @taylorotwell I think in this case this PR can be closed.

**Comment by GrahamCampbell** [comment]
The phpdoc should be changed from mixed to `JsonResource` then.

**Comment by driesvints** [comment]
@GrahamCampbell no. It's the property that needs to be an instance of JsonResource. Not `$offset`.

**Comment by GrahamCampbell** [comment]
Yeh, exactly. That property has type documented as `mixed`. It should be `JsonResource`.

**Comment by driesvints** [comment]
@GrahamCampbell ah yeah. Feel free to send in a PR 👍

**Comment by GrahamCampbell** [comment]
Hmmm, why would someone construct a JsonResource with a JsonResource?

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/v5.8.35/src/Illuminate/Http/Resources/Json/JsonResource.php#L48-L57

**Comment by driesvints** [comment]
@GrahamCampbell resources' collections work a little weird and are needed for this I think

**Comment by GrahamCampbell** [comment]
Heh. Maybe a note in the docs is sufficient.

**Comment by Khlyl** [comment]
Ok

**Comment by lbavendanos** [comment]
I believe that the result obtained when using Query Builder should be a class that implements ArrayAccess and not a stdClass, since not everyone uses Paginator from a Model Eloquent. It is for this reason that it also throws an error when using Resources.

**Pull request closed without merging**
