### PR TITLE
[7.x] Add support for Arr::group

### PR DESCRIPTION
**Pull request by LarsGrevelink**
Made the PR towards 7.x due to the release coming next week.

Was generally wondering why this wasn't added previously. :) Made a simple implementation for grouping array-like structures compared to the `Collection::groupBy` functionality but one which comes in handy when working with plain arrays. It differentiates by keeping everything array related instead of creating new Collection instances.

I found a couple of occurrences in the framework which could also use this method and added them to the pull request. If I've missed possible usages or missed any preferred functionality, let me know. Love to adjust it where needed.

Cheers,
L

### CODE REVIEW

**Comment by taylorotwell** [comment]
This works differently than the collection->groupBy method... It seems like we would want them to behave exactly the same?

image

**Comment by LarsGrevelink** [comment]
Hi @taylorotwell!

Thanks for the response. We could - chose to apply key preservation by default in this case. Will push a change which adds a separate argument for this choice as is done with `Collection->groupBy`.

Cheers,
L

**Comment by taylorotwell** [comment]
Personally I think it should behave exactly like Collection@groupBy.

**Comment by taylorotwell** [comment]
But, at that point part of me wonders what is the point of making this method since you could just collect() your array and call groupBy?

**Comment by LarsGrevelink** [comment]
Part of the gain was not using a collection at places where it shouldn't be necessary but in some cases, you actually want different behaviour than `toArray` or `all` is giving you.

`toArray` also creates arrays of models used inside of the collections and `all` is returning the grouped `Collection` instances which therefore alters the structure of the data we put in. Might be that I'm overlooking something, let me know if I do.

I will adjust the functionality to move more towards `Collection->groupBy` by dropping the `$default` support and adding the `$preserveKeys` param. The main difference between them after that is the multiple grouping method which is supported by `Collection->groupBy`. The more complex structures could still reside in the `Collection` class IMO while `Arr::group` supports most of the generic cases.

Let me know,
L

**Comment by taylorotwell** [comment]
I think I will just hold off on this for now.

**Comment by LarsGrevelink** [comment]
Hi @taylorotwell,

I saw you closed the pull request. Updated the branch anyway to match the outcome structure-wise to `Collection->groupBy`. To elaborate more on the differences and why this might be a valid addition I've added a test case with a `Model` instance. I added the differences in outcome below;

**Input**
```
[
    $this->getMockForAbstractClass(Model::class)->forceFill(['type' => 'desk']);
]
```

**Output Collection->groupBy()->all();**
```
^ array:1 [
  "desk" => Illuminate\Support\Collection^ {#297
    #items: array:1 [
      0 => Mock_Model_6a3bd8a9^ {#298 …30}
    ]
  }
]
```

**Output Collection->groupBy()->toArray()**
```
^ array:1 [
  "desk" => array:1 [
    0 => array:1 [
      "type" => "desk"
    ]
  ]
]
```

**Output Arr::group**
```
^ array:1 [
  "desk" => array:1 [
    0 => Mock_Model_53d4e67a^ {#298 …30}
  ]
]
```

I think each of the methods has its own purpose and its own use case. If you see the above as a beneficial addition I would love to open the pull request once more. The current state of the code can be found here; https://github.com/laravel/framework/compare/7.x...LarsGrevelink:feature/support-arr-group

Thanks,
L

**Pull request closed without merging**
