### PR TITLE
[5.2] Deprecated array_build

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by anteriovieira** [comment]
:+1:

**Comment by tomschlick** [comment]
Just curious... what is the reason to deprecate/remove this?

**Comment by anteriovieira** [comment]
Reason [#1916](https://github.com/laravel/docs/pull/1916)

**Comment by tomschlick** [comment]
Ah gotcha

**Comment by tomschlick** [comment]
Thanks

**Pull request merged**
