### PR TITLE
[8.x] Support conditional `URL::forceScheme` calls

### PR DESCRIPTION
**Pull request by ryangjchandler**
This pull requests adds a second parameter to the `UrlGenerate::forceScheme` method that will allow you to provide a `bool` or `Closure` callback to determine if the scheme should be forced.

_Inside of `AppServiceProvider::boot()`_

```php
URL::forceScheme('https', $this->app->environment('production'));
```

In this scenario, the scheme will only be forced in `production`. Inspiration for this came from `Model::preventLazyLoading` where you can provide a boolean and change when it is enabled without needing an `if` statement.

### CODE REVIEW

**Comment by crynobone** [comment]
I feel this method breaks Laravel coding style, maybe `URL::forceSchemeWhen(true, 'https')`.

**Comment by ryangjchandler** [comment]
@crynobone Yeah, I thought about adding a completely separate method. Let's see if this is something that is even wanted.

**Comment by taylorotwell** [comment]
It's a breaking change for us to expand the signature on a patch release. Anyone overriding the method already will break.

**Comment by ryangjchandler** [comment]
@taylorotwell Understood. I didn't think **adding** a parameter would have been a breaking change.

**Pull request closed without merging**
