### PR TITLE
Adds route resources option

### PR DESCRIPTION
**Pull request by pet1330**
This PR adds the options parameter when using `Route::resources` and `Route::apiResources` by taking an options array as the second parameter. These are then passed to each of the resource function calls.

An example of the suggested addition
```php

Route::resources([
        'resource-one'      => 'ResourceOneController',
        'resource-two'      => 'ResourceTwoController',
        'resource-three'    => 'ResourceThreeController',
    ], [ 'except' => [ 'create', 'show' ] ] );

```

Which can replace doing:
```php
Route::resource('resource-one', 'ResourceOneController', ['except' => ['create', 'show']]);
Route::resource('resource-two', 'ResourceTwoController', ['except' => ['create', 'show']]);
Route::resource('resource-three', 'ResourceThreeController', ['except' => ['create', 'show']]);

```

Which in the end would generate:

```

POST      | resource-one                          | resouce-one.store      | App\Http\Controllers\ResourceOne@store      | web |
GET|HEAD  | resource-one                          | resouce-one.index      | App\Http\Controllers\ResourceOne@index      | web |
DELETE    | resource-one/{resource_one}           | resouce-one.destroy    | App\Http\Controllers\ResourceOne@destroy    | web |
PUT|PATCH | resource-one/{resource_one}           | resouce-one.update     | App\Http\Controllers\ResourceOne@update     | web |
GET|HEAD  | resource-one/{resource_one}/edit      | resouce-one.edit       | App\Http\Controllers\ResourceOne@edit       | web |

POST      | resource-two                          | resouce-two.store      | App\Http\Controllers\ResourceTwo@store      | web |
GET|HEAD  | resource-two                          | resouce-two.index      | App\Http\Controllers\ResourceTwo@index      | web |
DELETE    | resource-two/{resource_two}           | resouce-two.destroy    | App\Http\Controllers\ResourceTwo@destroy    | web |
PUT|PATCH | resource-two/{resource_two}           | resouce-two.update     | App\Http\Controllers\ResourceTwo@update     | web |
GET|HEAD  | resource-two/{resource_two}/edit      | resouce-two.edit       | App\Http\Controllers\ResourceTwo@edit       | web |

POST      | resource-three                        | resouce-three.store    | App\Http\Controllers\ResourceThree@store    | web |
GET|HEAD  | resource-three                        | resouce-three.index    | App\Http\Controllers\ResourceThree@index    | web |
DELETE    | resource-three/{resource_three}       | resouce-three.destroy  | App\Http\Controllers\ResourceThree@destroy  | web |
PUT|PATCH | resource-three/{resource_three}       | resouce-three.update   | App\Http\Controllers\ResourceThree@update   | web |
GET|HEAD  | resource-three/{resource_three}/edit  | resouce-three.edit     | App\Http\Controllers\ResourceThree@edit     | web |


```

### CODE REVIEW

**Comment by jmarcher** [comment]
Since this is a breaking change please target this to 5.7

**Comment by pet1330** [comment]
I don't think this is a breaking change, it should work exactly the same as before?

The current method is: 
```php
    public function resources(array $resources)
```
The proposed method simply adds the `options` parameter as an optional addition:

```php
    public function resources(array $resources, array $options = [])
```
So calling the proposed method without an `options` parameter, should perform exactly the same way as the original method

**Comment by 36864** [comment]
Changes in method signatures are breaking changes.
Anyone who is extending this class and overriding those methods would need to update their code to include the extra parameter.

**Comment by pet1330** [comment]
Ah right. I'll close this and send a new PR targeting 5.7

**Pull request closed without merging**
