### PR TITLE
[5.3] Resolve user in request with token driver

### PR DESCRIPTION
**Pull request by tlaverdure**
Allows identifying a user with the token guard using `$request->user();`

### CODE REVIEW

**Comment by taylorotwell** [comment]
Hmm I would expect this to already work. I guess it's not for you? :smile: Where are you accessing $request->user() that is causing the problem?

**Comment by tlaverdure** [comment]
Yes it does does work in most cases. This is actually particular to the BroadcastController in 5.3 (https://github.com/laravel/framework/blob/master/src/Illuminate/Broadcasting/BroadcastController.php#L20). I'm not getting a user instance from the request even though I'm using the auth:api middleware in my BroadcastServiceProvider.

```php
Broadcast::route(['middleware' => ['auth:api']]);
```

**Comment by taylorotwell** [comment]
I fixed this in a slightly different way. Can you verify it's working on your end with my latest changes?

**Comment by tlaverdure** [comment]
Thanks, I checked it out but it's still not working. I couldn't find where the `shouldUse()` function is implemented from the AuthManager if that is intended to fix the issue.

**Comment by taylorotwell** [comment]
Are you trying it on latest 5.3?

**Pull request closed without merging**
