### PR TITLE
[5.7] Track abstracts being resolved, fire resolving events once

### LINKED ISSUE #23699: resolving() events on interfaces are called twice
In L5.5, 5.6 I experience an issue with _resolving_ callbacks on dependencies registered in the container with an interface class as abstract. A demonstration:

Having some interface 

```php
IBar {}
```

and an implementation 

```php
Foo implements IBar {}
```

registered (here as a singleton) in the container 

```php
app()->singleton( IBar::class, Foo::class );
```

with a _resolving_ callback 

```php
app()->resolving( IBar::class, $callback );
```

fires `$callback` **twice** when the abstract is resolved!

This is probably because:

1. When the abstract `IBar` resolves, it triggers the callback
2. To resolve `IBar`, `Foo` must be constructed. As `Foo` implements `IBar`, it triggers the `resolving` event too! 

This problem can be omitted when avoiding Laravel's container to build Foo by registering a callback instead:

```php
app()->singleton( IBar::class, f(){ return new Foo; } )
```

But this abolishes the ease of automatic dependency injection. 

So... can we solve this issue by not firing the `resolving()` callback when we are building the implementation of an interface that the callback is registered for?

### PR DESCRIPTION
**Pull request by tomlankhorst**
Fixes #23699 by tracking abstracts that are currently being resolved. 
If an object is built that is an `instanceof` of an object that is already on the stack, firing the resolving() callbacks is inhibited. 
These callbacks are fired eventually when the `instanceof` object is resolved.

### CODE REVIEW

**Comment by tomlankhorst** [comment]
Put this on master, btw, because it changes behavior and that might break existing apps.

**Comment by sisve** [comment]
1. There's a missing array_pop in the resolve() method for the early return.
2. These changes will still trigger the resolving-event for the class twice.

<br>

    interface LoggerInterface {}
    
    class LoggerImpl implements LoggerInterface {
        function __construct() {
            dump('logger constructor');
        }
    }

    class DepA {
        function __construct(LoggerInterface $logger) {}
    }

    class DepB {
        function __construct(LoggerInterface $logger) {}
    }

    class Service {
        function __construct(DepA $a, DepB $b, LoggerInterface $logger) {}
    }

    app()->singleton(LoggerInterface::class, LoggerImpl::class);
    app()->resolving(LoggerInterface::class, function() {
        dump('resolving iface');
    });
    app()->resolving(LoggerImpl::class, function() {
        dump('resolving class');
    });
    app()->afterResolving(LoggerInterface::class, function() {
        dump('resolved iface');
    });
    app()->afterResolving(LoggerImpl::class, function() {
        dump('resolved class');
    });
    $service = app(Service::class);

The output is ...

    "logger constructor" // separate weirdness, shouldn't this be between resolving and resolved?
    "resolving iface" // removed by this pr
    "resolving class" // still triggered with this pr
    "resolved iface" // removed by this pr
    "resolved class" // still triggered with this pr
    "resolving iface"
    "resolving class"
    "resolved iface"
    "resolved class"

The fact that the resolving event is triggered after the class has resolved is weird. I didn't expect that all.

**Comment by tomlankhorst** [comment]
You're totally right on the missing `array_pop`. 
The `resolving` and `afterResolving` callbacks are all called in `fireResolvingCallbacks()`, after the construction of the object, before injecting it in the depending class' constructor.

**Comment by tomlankhorst** [comment]
Interesting... resolving() callbacks are registered per `$abstract` but the callbacks to fire are determined per `$concrete`. 

I modified the `getCallbacksForType` method such that it checks callbacks by `$abstract` instead:

```php
protected function getCallbacksForType($abstract, $object, array $callbacksPerType)
{
    // ...
    foreach ($callbacksPerType as $type => $callbacks) {
        if ($type === $abstract || ($abstract instanceof $type && ! in_array($type, $this->resolveStack))) {
            $results = array_merge($results, $callbacks);
        }
    }
   // ...
}
```

and that seems to work, including all tests **except** those in which a callback is registered on a type-name! 

```php
app()->resolving('stdClass', function(){ /* ... */ });
```

**Comment by tomlankhorst** [comment]
@sisve I've added the situation you describe to the test.

**Comment by laurencei** [comment]
Before this is merged - can you run some scripts that creates like 10,000 Eloquent objects? What is the memory usage before/after this patch?

The reason is - using arrays to track things was a cause to a bug I fixed a while ago in the container back in 5.4 here: https://github.com/laravel/framework/pull/18812

It started crashing people's applications - so you gotta be careful with arrays and the container and memory.

**Comment by tomlankhorst** [comment]
@laurencei Thanks for your comment. The `$resolveStack` is tracking an array of abstracts which are string types. Furthermore, the stack tracks currently resolving abstracts, not all abstracts. 
So, the memory usage of this stack would have a maximum that scales linearly with the deepest dependency level in the application. 

Simplified demo: https://3v4l.org/cEoe4

**Comment by taylorotwell** [comment]
This loop at every step of resolution is a little concerning. Could be a performance problem.

**Comment by tomlankhorst** [comment]
I'll assess the performance impact.

**Comment by taylorotwell** [comment]
Closing pending inactivity on performance reports.

**Pull request closed without merging**
