### PR TITLE
[7.x] throws docblocks cleanup.

### PR DESCRIPTION
**Pull request by lucasmichot**
This PR removes throws docblock when the exception is not thrown directly within the method.
It also adds missing throws docblocks.

### CODE REVIEW

**Comment by driesvints** [comment]
Some of these are intentionally set there to note the cascading. So I don't think we should remove all of them.

**Comment by lucasmichot** [comment]
To which level does this cascading apply?

Because even with exception bubbling on one extra level, it would mean that many throws docblocks are missing

**Comment by driesvints** [comment]
There's no fixed rule.

**Comment by nunomaduro** [comment]
I think those methods are the public API of the framework. Therefore, the cascading should be applied to the very last level.

Still, it's important to document what can realistically get thrown, where is an example:

```php
public function frameworkMethod()
{
    return new \ReflectionClass(Illuminate\Database\Eloquent\Model::class);
}
```

The code above theoretically can throw a ReflectionException, but realistically that will **never** happen, so we shouldn't document it on phpdocs.

**Pull request closed without merging**
