### PR TITLE
[5.6] Update AuthenticatesUsers.php

### PR DESCRIPTION
**Pull request by guizoxxv**
Added function loggedOut based on registered and authenticated methods from Laravel authentication scaffold.

### CODE REVIEW

**Comment by jmarcher** [comment]
I do not undestand what this method is soposed to do...

We have something like 

> auth()->check()

**Comment by devcircus** [comment]
He just didn't explain it well. It's just like the "registered" method in the "RegistersUsers" trait. It gives you an option to do something other than "redirect()", after you log-out.

In my opinion, it is unnecessary, as you can simply override the "logout" method and run your custom code.

**Comment by guizoxxv** [comment]
Yes, the idea is to be able to do something after logging out. Yes, you can overwrite the logout method, but the idea is to make the code inside `/app/Http/Controllers/Auth` controllers cleaner. I believe that is the point of having the authenticated() and registered() methods. Without the suggested implementation I would have to overwrite the logout() method like this:

```
    public function logout(Request $request)
    {
        $this->guard()->logout();

        $request->session()->invalidate();
        
       // Do something

        return redirect('/');
    }
```
`$this->guard()` is referencing a method only visible in the vendor folder so it would be cleaner if it didn't show. Also the logout method is running behind the scenes like an abstraction so it should only appear outside the vendor folder when the user wants to change the code. That's not the case, I'm only interested in adding a functionality after logging out which is rather normal.

PS: I don't get why `continuous-integration/styleci/pr` failed. I see no message specifying the error.

**Comment by devcircus** [comment]
The style error is an issue with the blank line, or lack thereof, between the end of the method and the next docblock.

```php
    //
    return $this->loggedOut($request) ?: redirect('/');     
}
-
+
     /**      
      * The user has logged out.
      *
--

**Pull request merged**
