### PR TITLE
[9.x] Allow the "order by field()" use, in MySQL

### PR DESCRIPTION
**Pull request by fgaroby**
This PR adds the "order by FIELD()"  sorting, in MySQL.

Currently, if we want to order a query with the `FIELD()` method, we have to create a raw query, but it's not portable (if we decide to migrate from MySQL to another database).
With this PR, we have a new method `orderByField()`, which works with MySQL.
Use with MySQL:
```php
$builder->select('*')->from('users')->orderByField('age', [5, 7, 9]);
// select * from `users` order by field(`age`, "5", "7", "9")
```

Of course, if we use another database than MySQL, this method works too!
The same query, but with another database:
```php
$builder->select('*')->from('users')->orderByField('age', [5, 7, 9]);
// select * from "users" order by case when "age"="5" then 1 when "age"="7" then 2 when "age"="9" then 3 else 0'
```

### CODE REVIEW

**Comment by PaolaRuby** [comment]
Question
Default value on `else`, shouldn't it be zero?
```
// select * from "users" order by case when "age"="5" then 1 when "age"="7" then 2 when "age"="9" then 3 else 0
```

**Comment by fgaroby** [comment]
Yes, you're right.
I'm updating my code, to have 0 as `else` value, and other stuff.

**Comment by PaolaRuby** [comment]
`order by field()` also supports direction, (`DESC`, `ASC`)

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
