### PR TITLE
[5.6] Add support for ResetPassword

### PR DESCRIPTION
**Pull request by dinhquochan**
Just suggestion, and it assumes we use the existing auth.php file in resources/lang/en to translate ResetPassword Notification Mail.

Thanks.

### CODE REVIEW

**Comment by shadoWalker89** [comment]
One problem though, because the language files of existing apps does not contain the translations, people's applications will be sending the language variable names like `auth.reset_password` instead of `You are receiving this email because we received a password reset request for your account.`

Maybe this should go on 5.7 ?

**Comment by ludo237** [comment]
@shadoWalker89 is right this is technically a breaking change

**Comment by dinhquochan** [comment]
Should on 5.7?

**Comment by taylorotwell** [comment]
Use JSON approach.

**Comment by dinhquochan** [comment]
Should it on 5.6 or 5.7 @taylorotwell

**Comment by jmarcher** [comment]
@dinhquochan If you use the JSON approach as Taylor mentioned then it does not matter, it will work as before.

**Pull request closed without merging**
