### PR TITLE
[5.8] Update observer.stub to handle all events

### PR DESCRIPTION
**Pull request by iamoat**
Update observer.stub to handle all events
- retrieved
- creating
- created
- updating
- updated
- saving
- saved
- deleting
- deleted
- restoring
- restored
- force deleted

### CODE REVIEW

**Review by oliverquynh — COMMENTED** [review]
I think it's a good idea to separate this into some smaller stubs. For example,

```bash
php artisan make:observer --basic
php artisan make:observer --all
```

**Comment by iamoat** [comment]
> I think it's a good idea to separate this into some smaller stubs. For example,
> 
> ```shell
> php artisan make:observer --basic
> php artisan make:observer --all
> ```

Noted.

**Comment by iamoat** [comment]
> I think it's a good idea to separate this into some smaller stubs. For example,
> 
> ```shell
> php artisan make:observer --basic
> php artisan make:observer --all
> ```

Done !!!

**Comment by taylorotwell** [comment]
Why separate this? That is just more configuration options. Who defines what is "basic"? Generated observers should just be able to handle all events.

**Comment by iamoat** [comment]
> Why separate this? That is just more configuration options. Who defines what is "basic"? Generated observers should just be able to handle all events.

So should I just update the observer.stub to include all events instead? That was what I did in the first place.

**Pull request closed without merging**
