### PR TITLE
[5.5] Add isFromApi method to Request object

### PR DESCRIPTION
**Pull request by maxalmonte14**
I think this feature is useful when you are using the same controllers for manage API and web requests, maybe you want to know when a user is requesting from an api and return a different set of data that when the request came from the web.

This method bring a clean way for read and implement. For example if you want to return a set of posts in JSON format when someone make a request from an api but return a view when the request came from the web, you can do this.

```php

public index (Request $request)
{
    $posts = Post::paginate();
    if ($request->isFromApi()) {
        return $posts;
    } else {
        return view('posts.index', ['posts' => $posts]);
   }
}
```

### CODE REVIEW

**Comment by a-komarev** [comment]
@maxalmonte14 I don't have `/api` segment in my URL. API is on subdomain, this wouldn't work then.

**Comment by a-komarev** [comment]
In my point of view all API endpoints should have special middleware which will define that it's API route.

**Comment by maxalmonte14** [comment]
@a-komarev Well, maybe in your case this not apply at all but when you create an api (using Laravel Passport for example) the default way for access to the endpoints is using your main domain and the segment "api", (http://www.myawesomesite.com/api/users).

I created the method as a little helper function but I believe it is most useful like a Request method.

**Comment by taylorotwell** [comment]
Eh, holding off on this. Request is macroable.

**Pull request closed without merging**
