### PR TITLE
[8.x] Consume Blade Directive

### PR DESCRIPTION
**Pull request by taylorotwell**
From an idea by @calebporzio ...

When building complex Blade components, it's hard / impossible to access data passed into the parent from children in the parent's slot.

For a concrete example of the problem (using a `x-menu` component):

**Usage**
```html
<x-menu color="blue">
    <x-menu.item>Foo</x-menu.item>
    <x-menu.item>Bar</x-menu.item>
    ...
</x-menu>
```

Notice we are passing in a "color" attribute to the parent component. Here's the parent component definition:

**x-menu**
```html
@props(['color' => 'black'])

<ul ...>
    {{ $slot }}
</ul>
```

Now this component has access to `$color`, but it doesn't actually need it. We need to access `$color` from each `menu-item` component:

**x-menu.item**
```html
<li class="bg-{{ $color }}-500">
    {{ $slot }}
</li>
```

Can now be done via `@consume` directive in the child... defaults are also supported if no consumable data with the given name can be found in the parent component stack...

**x-menu.item**
```html
@consume(['color', 'foo' => 'default'])

<li class="bg-{{ $color }}-500">
    {{ $slot }}
</li>
```

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
Amazing @taylorotwell 
I needed it for my package https://github.com/datalogix/tall-kit

Is it possible to access recursively?

```blade
<x-menu color="blue">
    <x-menu.item>
        <x-link>Acceess here color</x-lik>
    </x-menu.item>
    ...
</x-menu>
```

**Comment by taylorotwell** [comment]
@ricardogobbosouza 

In your example, you are at a level where you already have access to the color?

```blade
<x-menu color="blue">
    <x-menu.item>
        <x-link>blue</x-lik>
    </x-menu.item>
    ...
</x-menu>
```

**Comment by Bazzly** [comment]
This is a great one..👍

**Comment by inxilpro** [comment]
Is there a story for using this in class components? It reminds me a lot of https://github.com/laravel/framework/pull/36512 and https://github.com/laravel/framework/pull/36472 — it'd be nice to have a way for parents/children to share data easily that works for both anonymous and class-based components.

**Comment by taylorotwell** [comment]
@inxilpro yeah I think this whole idea needs a bit more work IMO. Spatie took a `context` component approach but that approach won't work with slots (as noted in their documentation), which is one of the use cases we are trying to solve here. This approach works with slots but doesn't work great with plain components and child components.

**Comment by delta1186** [comment]
So in this specific example would this implementation not work with the tailwind tree shaking?  I realize that this is just an example and an actual implementation could be used in the abstract and so this feature will still be awesome to have available. 🤙🏻

**Comment by ricardogobbosouza** [comment]
@taylorotwell Another related issue would be slot props https://github.com/laravel/ideas/issues/2116#issuecomment-837402404 has a package does this https://github.com/konradkalemba/blade-components-scoped-slots could be part of the core?

**Comment by inxilpro** [comment]
It seems like a child component could theoretically call `getConsumableComponentData` — maybe we could even add a `$consumes` property to `View\Component` to make it automatic:

```php
abstract class Component
{
    protected $consumes = [];

    public function data()
    {
        $this->attributes = $this->attributes ?: $this->newAttributeBag();

        return array_merge(
            $this->extractPublicProperties(),
            $this->extractPublicMethods(), 
            $this->getConsumableComponentData()
        );
    }

    protected function getConsumableComponentData()
    {
        return View::getConsumableComponentData($this->consumes);
    }
}
```

**Comment by taylorotwell** [comment]
@inxilpro if the child is an anonymous component that unfortunately doesn't solve the issue

**Comment by inxilpro** [comment]
But doesn't `@consume` address it for anonymous components?

**Comment by taylorotwell** [comment]
No - it mainly only addresses it for slots sadly.

For example:

```php
<div>
    <x-menu-item />
</div>
```

If this code example is the source of the parent component, that `x-menu-item` can't `@consume` data from the parent.

**Comment by inxilpro** [comment]
Ooh. I have an idea! How would you feel if this just worked implicitly? For example, in the code sample above `$color` would just be available to the child unless you explicitly passed a different color value to it? I have that working locally in a test branch…

**Comment by taylorotwell** [comment]
@inxilpro I'm not entirely opposed to that if you want to PR it to this branch.

**Comment by inxilpro** [comment]
@taylorotwell take a look at #39092 when you have a chance.

**Comment by inxilpro** [comment]
Alright. I put together one more try with #39100.

**Pull request closed without merging**
