### PR TITLE
[9.x] No need to use Str helpers

### PR DESCRIPTION
**Pull request by lucasmichot**
No need to use helpers instead of the native `str_contains`, `str_starts_with` and `str_ends_with`  functions.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We need to be careful. These functions are not identical, in particular in the null or empty string cases.

**Comment by lucasmichot** [comment]
> We need to be careful. These functions are not identical, in particular in the null or empty string cases.

This has been taken in consideration, same for the string as a 2nd argument, and the absence of `$ignoreCase` argument

**Comment by taylorotwell** [comment]
@lucasmichot can you fix the conflicts here?

**Comment by lucasmichot** [comment]
> @lucasmichot can you fix the conflicts here?

Conflicts fixed @taylorotwell 👌

**Pull request merged**
