### PR TITLE
[5.5] Add the power of Arr::get() to Collection get()

### PR DESCRIPTION
**Pull request by nmfzone**
By using `Arr::get()`, now It's possible to get nested value using collection get().

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
and tests …

**Comment by nmfzone** [comment]
@Dylan-DPC Thanks..

**Comment by sisve** [comment]
Are we really _really_ sure that we can just add new wildcard capabilities to such a globally used class like Collection without causing problems for people? Are we really sure that no one use `::get($key)` with keys that already looks like wildcards?

**Comment by 36864** [comment]
`Arr::get()` first checks if the full key exists in the array before trying to access sub-arrays using the dot notation. It also doesn't do wildcards.

**Comment by jeroennoten** [comment]
Strictly spoken, this is a breaking change: `(new Collection(['a' => ['b' => 'c']]))->get('a.b', 'd')` returned `'d'` in the old situation and `'c'` in the new situation.

**Comment by sisve** [comment]
@jeroennoten Yes, but can we do anything about it? It has already been merged and released.

**Comment by jeroennoten** [comment]
A rollback in a next version is an option. This is already done more often than once (e.g. https://github.com/laravel/framework/pull/22478).

But not sure if that is necessary, my comment was more or less informative without opinion.

**Comment by jasonvarga** [comment]
I also noticed that `$collection->get(null)` will now return the whole array. Before this change, it would return `null`.

**Comment by mariosvasiliou** [comment]
The new method not working as it should. I have the same problem. default value is always ignored and whole array is returned instead of null....

**Comment by devcircus** [comment]
If you're experiencing problems that you believe is a bug, please open an issue and explain the problem in detail, including a description of the behavior before and after this pr. Your issue will be noticed much more quickly there than on a closed pr.

**Comment by sisve** [comment]
Note how there's now a commit with the message "revert breaking change", but it didn't actually revert anything.

There's now a follow up for the default value at https://github.com/laravel/framework/pull/22837, but we're still using Arr::get which @jeroennoten has shown is a change in behavior.

**Comment by taylorotwell** [comment]
Reverting this entirely.

**Pull request merged**
