### PR TITLE
[11.x] Introduced `ensure()` helper method

### PR DESCRIPTION
**Pull request by pascalbaljet**
As generics and static analysis tools like PHPStan are increasingly getting more popular, this `ensure()` method can help with mixed return types. A clear example is in Form Requests, where you can resolve the authenticated user, but the framework theoretically can return `null`:

```php
class ProfileUpdateRequest extends FormRequest
{
    public function rules(): array
    {
        $user = $this->user();

        return [
            'username' => ['required', Rule::unique(User::class)->ignore($user->id)],
        ];
    }
}
```

You may overcome this by type hinting the variable or by using `assert()`. I saw the latter being used in Pinkary, which passes PHPStan at level max:

```php
/** @var User */
$user = $this->user();

// or

$user = $this->user();
assert($user instanceof User);
```

The `ensure()` method is more strict like `assert()`, but its main advantage is that it returns the value. Due to the generics, PHPStan and IDEs understand that the return value is of the expected type.

```php
$user = ensure($this->user(), User::class);
```

I named it `ensure` as there's a similar method on the `Collection` class.

### CODE REVIEW

**Comment by henzeb** [comment]
If this would pass, I'd expect it to behave more similar to the ensure method on the Collection class...

**Comment by taylorotwell** [comment]
I do think people would expect this to have parity with Collection@ensure at least.

**Comment by pascalbaljet** [comment]
I've updated the PR so it supports multiple types and scalar types:

```php
ensure(10, 'int');
ensure([], ['array', Collection::class]);
```

**Comment by taylorotwell** [comment]
Talked a bit about this with @nunomaduro and we're going to table this idea for now. Feel free to ship a package that provides this type of thing!

**Comment by pascalbaljet** [comment]
Totally understandable! For future readers: check out [type-guard](https://github.com/another-library/type-guard)

**Pull request closed without merging**
