### PR TITLE
[6.0] Add result Generator

### PR DESCRIPTION
**Pull request by barryvdh**
When chunking queries, a callback is required. The `each` method makes it a bit less awkward by providing a callback for just the result, but using callbacks stills requires the `use` of variables to include them in te scope. The syntax is also different from the regular `foreach`.

By using `yield` you get the same benefits from chunking; chunked parts and ability to stop. I find the syntax more easy to use, but that might be personal.

```php
$query = User::query();

$results = [];
$query->each(function($user) use(&$results) {
    $results[] = $user->id;
    if (count($results) > 50) {
        return false;
    }
}, 100);

dump($results);

$results = [];
foreach ($query->generator(100) as $user) {
    $results[] = $user->id;
    if (count($results) > 50) {
        break;
    }
}
```

(I originally tried to yield from the `each` method to re-use more logic, but that's allowed unfortunately..)
/cc @staudenmeir for DB related stuff ;)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Could we refactor the each method to use the generator under the hood, to avoid duplicated code?

**Comment by barryvdh** [comment]
Not directly I think, because `chunk` is returning the resultsets, not individual results.

**Comment by staudenmeir** [comment]
What advantages does this method have over `cursor()`?

**Comment by barryvdh** [comment]
Does cursor also chunk the results? In that case I may have misunderstood the cursor function.

**Comment by staudenmeir** [comment]
Not in the "traditional sense", but isn't that the idea? `cursor()` only fetches the requested rows, one at a time. Your method fetches a certain amount of rows at once and returns a generator for them. 

Doesn't `cursor()` give you the same result without the potential overhead of unused rows? In your example, you fetch 100 rows but only use the first 50. `$query->cursor()` only fetches the first 50 rows.

**Comment by barryvdh** [comment]
Well yes, that example was to illustrate stopping early. The example doesn't make much sense otherwise ;)

The cursor would generate a query for each result right? So that means 100 queries for 100 results and without the possibility of eager loading.

An option could be to adjust the `cursor` method to allow chunking otherwise?

**Comment by staudenmeir** [comment]
`cursor()` only executes a single query, that's what's so great about it.

**Comment by barryvdh** [comment]
Except that you cannot eagerload relationships in chunks that way?

**Comment by staudenmeir** [comment]
That would only be possible with lazy eager loading.

Are there other queries that don't work with `cursor()`?

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
