### PR TITLE
[5.3] Fix namspaced invokable controller route action error

### LINKED ISSUE #16288: Failed to set namespaced invokable controller as route action using ::class notation
- Laravel Version: 5.3.22
- PHP Version: 7.0
- Database Driver & Version: any

### Description:

As description said:  setting namespaced invokable controller as route action using ::class notation causes `Invalid route action` exception when that controller class imported in `routes.php` using `use` statement and then controller name retrieved using `::class notation.`

To keep track classes usage and to enable type analysis in IDE to be able to utilizing IDE refactoring features (rename/move) in PHPStorm we import controller classes and use `::class` notation. Having `App\Http\Controllers\Test` controller but referencing it as `Test` breaks this approach, as well as IDE types analysis (but not limited to IDEs only). While there are a lot of nice workarounds from swapping with own Route facade root to patching laravel/framework and using own fork, I decided to discuss it here as I'm pretty sure I'm not the one who faces with this issue (I hit it with 5.1 initially, if I recall it right).

### Steps To Reproduce:

1. Create namespaced controller with `__invoke()` method.
2. Set controller as route action, e.g. `Route::get('/login', App\Http\Controllers\Test::class)`.
3. Request any http url or run any artiasn command to see the error.

### PR DESCRIPTION
**Pull request by srmklive**
Fixes #16288 as proposed by @pinepain.

### CODE REVIEW

**Comment by pinepain** [comment]
@srmklive as fix was proposed in issue itself, I would really appreciate if you mention it author in pull request at least.

**Comment by srmklive** [comment]
@pinepain comment updated.

**Comment by pinepain** [comment]
Thanks!

**Comment by taylorotwell** [comment]
Copied from issue:

Meh, it's really a bug in the route registration. The web.php routes file is already loaded with a namespace prefix but you are still passing the full controller class name. Fixing this "bug" would just open up another one where I can't have a controller with a namespace that matches the root namespace.

**Comment by taylorotwell** [comment]
If you want to register your routes this way, I suggest removing the namespace from the web route group in RouteServiceProvider.

**Comment by pinepain** [comment]
Ok. I guess then tweaking `RouteServiceProvider`  in way you proposed is really a good solution, thanks.

**Pull request closed without merging**
