### PR TITLE
make Eloquent/Model is() and isNot() signatures consistent and fix possibility of invalid call exceptions on is()

### PR DESCRIPTION
**Pull request by SlyDave**
make Eloquent/Model is() and isNot() signatures consistent and fix possibility of invalid call exceptions on is()

### CODE REVIEW

**Comment by SlyDave** [comment]
Note: This undoes as change #18511, which incorrectly states to make the method support nulls, the type hint had to be removed, thus allowing any type to be passed in. However doing so it introduced the possibility of invalid call exceptions.

**Comment by taylorotwell** [comment]
Breaking change. We have to allow null to be passed.

**Comment by SlyDave** [comment]
It does... check the tests

**Comment by SlyDave** [comment]
The only reason I can think you refer to this a breaking is because of the change of type of Exception that might be thrown, but...

*Before 5.5*: throws TypeError, do not allow nulls
*5.5*: throws BadFunctionCallException exception, do allow nulls
*After this fix*: throws TypeError exceptions, allow nulls

As we can see, if anything, the 5.5 change is the breaking change, it changed the exception behaviour, whilst trying to add support for nulls.

My fix returns the exception behaviour back to 5.4 (thus not breaking anyones could that is handling exceptions the method throws) and provides null support (as per the feature request)

**Pull request closed without merging**
