### PR TITLE
[6.x] Add Aircraft To List of Uncountable Words?

### PR DESCRIPTION
**Pull request by AndyTWF**
Add "aircraft" to the list of words that are uncountable.

### CODE REVIEW

**Comment by AndyTWF** [comment]
Argh, this is one of the edge cases where the word is technically countable but really doesn't look it, so this might be a problem with Inflector itself. Will close this.

**Comment by GrahamCampbell** [comment]
Aircraft are countable. Being countable is not related to how it is pluralised. :)

**Comment by GrahamCampbell** [comment]
Doctrine need to fix their pluraliser.

**Comment by GrahamCampbell** [comment]
> Jedi, Pokemon

Kinda odd that they appear. They are countable?

**Comment by GrahamCampbell** [comment]
TBH, a lot of these so called uncountable words are countable?

**Comment by AndyTWF** [comment]
Yeah a lot of them are, I thought it was a bit odd - which is why I opened this just incase it was something you wanted to handle here. Happy to take it to Doctrine if that's where it should be!

**Comment by AndyTWF** [comment]
Having dug a bit further, @GrahamCampbell - it looks like Doctrine have fixed the Inflector on master so this issue will resolve itself when that's released, so happy for this to be closed, or I'm happy to change this into a "remove the countable words", if you would like :)

**Comment by GrahamCampbell** [comment]
It looks like we could allow v2 of the library due to https://github.com/doctrine/inflector/pull/132.

**Comment by GrahamCampbell** [comment]
Although the other doctrine dependencies we have could block the install of v2.

**Comment by rimace** [comment]
Beside all discussions, wouldn't that break existing applications that rely currently on the pluralization of the word?
In my opinion this change should be done in a major version.

**Comment by AndyTWF** [comment]
Wouldn't the vast majority of consumers who have Laravel packages as part of their applications already have Inflector locked via Composer? So if Laravel specified a version of "^1.3 | ^2.0" (given the BC wrapper from the API perspective), at least in the first instance,  it would then be down to the consumers to upgrade and shouldn't cause any BC-breaks?

**Comment by alcaeus** [comment]
@AndyTWF if any other dependency you are using only specifies `^1.3` it would still install 1.x. It would however allow the ecosystem to upgrade and migrate to the new API once 1.3 is no longer supported.

I'll see if I can back port the changes from 2.0 into 1.x to fix this issue. I'm not sure when I'll have the time to wrap up inflector 2.0 as we're still missing a crucial feature (custom rules).

**Comment by AndyTWF** [comment]
Amazing, thank you @alcaeus :)

**Comment by taylorotwell** [comment]
If we make any change here we would definitely have to do it on 7.x branch because it would affect how Eloquent model table names are guessed etc and there could be applications out there with Aircraft models.

**Comment by alcaeus** [comment]
@taylorotwell just for clarification so I don't break your stuff, would changing the Pluralizer in doctrine/inflector from `aircrafts` to `aircraft` cause similar problems?

**Pull request closed without merging**
