### PR TITLE
[Add Feature]add Validator exists different connection support

### PR DESCRIPTION
**Pull request by xyxu**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This doesn't look right. You're overriding the table variable.

**Comment by xyxu** [comment]
as same as #8652

**Comment by GrahamCampbell** [comment]
> as same as #8652

That's a totally different context.

**Comment by GrahamCampbell** [comment]
This method here actually has a `$table` parameter in it's method signature, and then you're overriding it.

**Pull request closed without merging**
