### PR TITLE
[5.4] [WIP] Add db:empty command

### PR DESCRIPTION
**Pull request by laurencei**
Background and discussion here: https://github.com/laravel/internals/issues/421

This PR adds the `db:empty` command. This allows you to empty an entire database, which can help people who dont want to use `down` migrations (especially during development). You can use it in a couple of ways:

**Option 1:** Just empty the database:
`php artisan db:empty`

**Option 2:** Empty the database and then re-run all migrations:
`php artisan db:empty --migrate`
 
**Option 3:** Empty the database, re-run all migrations, then seed:
`php artisan db:empty --migrate --seed`

I've added some tests that should cover most situations.

Note: it would be nice if someone with an _actual_ SQL Server could test the command there (ideally with a table with foreign constraints). The SQL code I've used to drop all tables is from StackOverflow - and I dont have a SQL Server to test against.

Credit to @spatie @freekmurze for inspiration for this PR and some of the code is from the package here https://github.com/spatie/laravel-migrate-fresh (used with permission from @freekmurze) .

### CODE REVIEW

**Comment by devcircus** [comment]
how does this differ from
```
php artisan:migrate reset
php artisan:migrate refresh 
php artisan:migrate refresh --seed
```

**Comment by devcircus** [comment]
Ok. I see. For those who don't write down migrations.

**Comment by lioannou** [comment]
Not just for lack of `down` migrations though; I've had situations where I've written failed `up` migrations that create a few tables, but then throw an exception half way through. Running `migrate:refresh` doesnt always work in those situations - so this is an easier way to reset and try again (during development).

**Comment by RryLee** [comment]
@lioannou  Maybe your application have many db connections, so you should empty all

**Comment by lioannou** [comment]
@RryLee - it can actually already handle that and specify different connections other than the default

    php artisan db:empty --database=mysql
    php artisan db:empty --database=other

**Comment by taylorotwell** [comment]
I don't mind this particular feature but not sure about this implementation. Be simpler to just have the migration skip calling down if it doesn't exist?

**Comment by lioannou** [comment]
Hi @taylorotwell - but the migrator skipping `down` doesnt actually solve the problem.

The problem is you are still left with tables in your database - with no way to remove them from the artisan command without manually writing something to remove those tables.

This provides a way to do it as an artisan call (and then some flags to re-migrate and re-seed if required). Then people who down want `down` commands can still re-migrate there databases during development.

**Comment by tillkruss** [comment]
@lioannou: We talked about this a little bit today and agreed, that the `TableDropper` stuff should be directly on the connection. Something like `$connection->dropAllTables()`. Can you please update the PR?

**Comment by lioannou** [comment]
Ok @tillkruss - I'll make some changes and update the PR.

**Comment by taylorotwell** [comment]
I agree with @tillkruss

**Comment by DojoGeekRA** [comment]
@lioannou @tillkruss `db:nuke` will be cool as hell :metal:

**Comment by barryvdh** [comment]
Why not just `db:drop` or `db:drop-tables`?

**Comment by driesvints** [comment]
`db:reset` makes the most sense imo.

**Comment by lioannou** [comment]
@barryvdh - cant be `db:drop` because that sounds like it is dropping the database itself.

I'm thinking `db:drop-all-tables` - as that is the most expressive verbose command and there would be no confusion what it means.

Would give something like `php artisan db:drop-all-tables --migrate --seed`

**Comment by driesvints** [comment]
drop-all-tables is too long and doesn't really fits in with the other commands. I still think db:reset is the best option because that's exactly what this command will do.

**Comment by Garbee** [comment]
What if people make custom functions and views? This isn't clearing those
out for a fresh start.

**Comment by driesvints** [comment]
@Garbee seems out of scope for this issue I think? Perhaps we can add an extra flag for that in another PR?

**Comment by Garbee** [comment]
I don't really think it is out of scope. If the idea is to nuke/clear/empty the database for re-migration, then that could be a key part to make sure your migrations run right again. Especially if you do raw SQL (which is supported) to add more advanced features in. Otherwise, if your developing your stuff and you nuke to reload, your stuff won't work. In fact, with views in Postgres your tables will fail to drop with this. Since the view depends upon a table and the table won't drop until the view gets removed.

I'd need to test to see if drop cascade works in the view scenario, but iirc from the other day working with them it doesn't. Postgres requires the view to go out first in a separate transaction.

**Comment by lioannou** [comment]
An alternative; - drop the actual database - and then create a new database. That ensures a clean slate.

The only issue is possible database permissions for users - but given this would a development only command - would it really matter?

**Comment by tillkruss** [comment]
`db:reset` makes the most sense to me as well. I wouldn't make this command dev-only, can come in really handy in staging or testing environments as well

**Comment by Garbee** [comment]
Just tested and when you cascade drop tables the *views* relating to them do drop as well. So that's clear as long as the drop is a cascade.

That still leaves functions being a problem though, as those are external objects not bound to the tables (the triggers should drop like views.) So for postgres functions should be queried up and dropped as well after the tables are dumped.

**Comment by lioannou** [comment]
@Garbee - I can do that - as each `connection()` will implement its own version of `dropAllTables()` - so we can include that for Postgres.

I could even add a flag `--drop-database-functions` - so it only does that if you want, rather than by default?

**Comment by lioannou** [comment]
@tillkruss - question; if I add `dropAllTables()` to the `Illuminate\Database\Connection` - then do we want that method added to the `ConectionInterface` - forcing anyone who creates their own custom DB connection to implement their own version?

If I do that though - it would make this a `5.5` feature, since we couldnt implement an interface change in `5.4`?

The alternative is just leave it as an empty method on `Illuminate\Database\Connection` - and have each current database connection extend it with their implementation.

Please let me know which you prefer and I'll finish the PR.

**Comment by tillkruss** [comment]
I personally would go with an interface change and target 5.5. @freekmurze, thoughts?

**Comment by driesvints** [comment]
Yeah 5.5 might be a better target.

**Comment by freekmurze** [comment]
Yea, interface change and target 5.5 sounds great.

**Comment by deleugpn** [comment]
`db:nuke` is the best name this could ever have.

**Comment by joshmanders** [comment]
I'd do `db:reset` also.

**Comment by lioannou** [comment]
Does anyone here have an *actual* SQL Server? Could you test the current PR to confirm if actually drops the tables (ideally with some tables with foreign constraints)? The SQL code I've used to drop all tables is from StackOverflow - and I dont have a SQL Server to test against.

Dont worry about the rest of the PR - I'm redoing it - but would be good to confirm the current drop code actually works for SQL for the new PR.

**Comment by Garbee** [comment]
Anyone can get a copy of [SQL Server vnext](https://www.microsoft.com/en-us/sql-server/sql-server-vnext-including-Linux) (even for Linux) and test things out. This is a pre-release version of MS's next SQL Server offering which works across platforms. It should be good enough for testing basic table drop functionality.

**Pull request closed without merging**
