### PR TITLE
[5.0] Defer Query Builder Bindings Until The Query Is Being Compiled

### PR DESCRIPTION
**Pull request by jonspalmer**
## The problem

The old design of adding bindings as clauses are added to the query worked most of the time had two major issues:
1. For some complex queries, like unions or sub queries involving joins, the bindings fail to apply or are applied in the wrong order. See #5833 for examples.
2. Cleanly removing global scopes that introduced bindings is impossible to guarantee, especially if other global scopes are in use.
## The fix

To fix this we take a very simple approach to defer assigning the query bindings until the query is being compiled. We introduce a CompiledQuery class that holds the sql string and the bindings array. It also takes care of a lot of the complexity of the concatenating and trimming sql string so the Grammar doesn't have to care about those details or imploding arrays of strings. This has two effects:
1. Query bindings are guaranteed to be added in the same order that the sql string is concatenated.
2. When removing global scopes you don't need to worry about removing bindings. Just remove the appropriate query clauses and the bindings will be taken care of at compile time.
## Unit tests

Note that all unit tests pass as is with only a minor refactoring to allow us to assert the sql string and bindings in one helper method. I've added a significant number of new tests some of which failed without the fixes.
## API changes

There are a fewAPI change:
1. Remove all the `Query\Builder` binging methods `getBindings`, `getRawBindings`, `addBinding`, `setBindings` and `mergeBindings` which have no meaning in the world of compile deferred bindings. This API was most being used by developers of Global Scopes so they could attempt to remove the bindings. A problem they don't need to solve anymore.
2. Rename `Query\Builder` `toSql` to `compile`

We could add some backwards compatible `toSql` and `getBindings` methods and mark them as deprecated but I'm not sure its really safe to do so. Anyone using those old APIs need to think hard about how to use the new `compile` method.
## Removing Bindings and Global Scopes

The early assignment of bindings makes the removal of global scope particularly challenging. See for example this SO question: [laravel-how-to-disable-a-global-scope-in-order-to-include-inactive-objects](http://stackoverflow.com/questions/25312386/laravel-how-to-disable-a-global-scope-in-order-to-include-inactive-objects). The problem is that there is no guaranteed way to identify the bindings a global scope added and its therefore hard to ensure that you remove them cleanly. Most techniques are relying on storing the index into the where and binding arrays when the scope was added and then using that when removing. However, that technique, and all others, are extremely brittle if more than one global scope are involved.

### CODE REVIEW

**Comment by ashleydw** [comment]
+1 what's the solution to running union queries if this isn't going to be merged?

**Comment by rodrigopedra** [comment]
@ashleydw I extended MySqlGrammar and added the mergeBindings inside the foreach that compile the unions:

~~~php
    protected function compileUnions(Builder $query)
    {
        $sql = '';

        foreach ($query->unions as $union)
        {
            $sql .= $this->compileUnion($union);

            // done again???
            $query->mergeBindings( $union['query'] );
        }

        if (isset($query->unionOrders))
        {
            $sql .= ' '.$this->compileOrders($query, $query->unionOrders);
        }

        if (isset($query->unionLimit))
        {
            $sql .= ' '.$this->compileLimit($query, $query->unionLimit);
        }

        if (isset($query->unionOffset))
        {
            $sql .= ' '.$this->compileOffset($query, $query->unionOffset);
        }

        return ltrim($sql);
    }
~~~

You'll need to register a custom connection to use your custom grammar. It doesn't feel right, but I didn't find a better solution yet.

**Comment by ashleydw** [comment]
Thanks @rodrigopedra, I tried your suggesting but it didn't work for me. Instead, I chose to override the `getBindings` function in my own Builder class. My method ensures that bindings are added in order of query inclusion into the union. I'm yet to test if this works 100% correctly, but so far I have found it to work:

```php
	public function union($query, $all = false)
	{
		if ($query instanceof Closure)
		{
			call_user_func($query, $query = $this->newQuery());
		}

		$this->unions[] = compact('query', 'all');

//		return $this->mergeBindings($query); // don't do this here, but later check for the union bindings

		return $this;
	}

	public function getBindings()
	{

		$bindings = array_flatten($this->bindings);

		if(count($this->unions)) {

			foreach($this->unions as $_union) {
				foreach($_union['query']->getBindings() as $_binding)
					$bindings[] = $_binding;

			}

		}

		return $bindings;
	}
```

**Comment by ashleydw** [comment]
My proposed function passes the unit tests below that were added by @bostanio in https://github.com/Nanigans/framework/blob/ad68eeecf4072c4f10099864c21e9188133c2900/tests/Database/DatabaseQueryBuilderTest.php

```
testUnions
testUnionAlls
testUnionsWithJoins
testUnionsWithOrder
testUnionsWithHavings
testMultipleUnions
testMultipleUnionAlls
```

**Pull request closed without merging**
