### PR TITLE
[9.x] Vite asset url helper

### PR DESCRIPTION
**Pull request by timacdonald**
When using plain Blade as your templating platform, it can be useful to still process images that are not referenced in your JS with Vite - it may even be the case that you don't have any JS and still want to minify your projects' images.

This PR introduces a `Vite::asset()` helper, which can be used in Blade templates to generate the URLs to your projects build assets.

With the following manifest:

```json
{
  "resources/images/logo.jpeg": {
    "file": "assets/logo.1ddf943b.jpeg",
    "src": "resources/images/logo.jpeg"
  },
  "resources/js/app.js": {
    "file": "assets/app.e5198d1b.js",
    "src": "resources/js/app.js",
    "isEntry": true
  }
}
```

You can now generate a URL to the profile image in Blade with the following:

```blade
<img src="{{ Vite::asset('resources/images/logo.jpeg') }}">
```

Which would result in the following HTML:

```html
<img src="http://asset-url.com/build/assets/logo.1ddf943b.jpeg">
```

In build mode, this will generate a URL to the dev server, resulting in the following HTML:

```html
<img src="http://[::1]:5173/resources/images/logo.jpeg">
```

For more information on including static assets in your applications build, see https://github.com/laravel/docs/pull/8124

### CODE REVIEW

**Review by jessarcher — APPROVED** [review]

**Comment by driesvints** [comment]
Test

**Comment by timacdonald** [comment]
Marking this one as draft as it conflicts with https://github.com/laravel/framework/pull/43714, which I believe is more urgent to get merged. Will re-open and resolve conflicts tomorrow.

**Comment by vlados** [comment]
Currently vitejs is generating:
```js
  "resources/images/logo-1024-01.jpg": {
    "file": "assets/logo-1024-01.a480100e.js",
    "src": "resources/images/logo-1024-01.jpg",
    "isDynamicEntry": true,
    "assets": [
      "assets/logo-1024-01.d91e6c7b.jpg"
    ]
  },
```
So if we use file attribute in the blade the image src will be the .js file.
Why not use assets[0]?

**Comment by timacdonald** [comment]
Hey @vlados, I'm unable to generate a manifest with what you have shown here. Here is what I get with a fresh project install...


Importing images in your `app.js`:

```js
import './bootstrap';
import '../images/profile.png'
```

results in:

```json
{
  "resources/images/profile.png": {
    "file": "assets/profile.1f676f34.png",
    "src": "resources/images/profile.png"
  },
  "resources/js/app.js": {
    "file": "assets/app.334e7359.js",
    "src": "resources/js/app.js",
    "isEntry": true
  }
}
```

Globing your images in the `app.js`:

```js
import './bootstrap';
import.meta.glob('../images/**')
```

results in:

```json
{
  "resources/images/profile.png": {
    "file": "assets/profile.1f676f34.png",
    "src": "resources/images/profile.png"
  },
  "resources/js/app.js": {
    "file": "assets/app.334e7359.js",
    "src": "resources/js/app.js",
    "isEntry": true
  }
}
```

Referencing an image from a Vue component:

```vue
<script setup>
// ...
</script>
<template>
    <Head title="Welcome" />

    <img src="../../images/profile.png">
</template>
```

results in:

```json
{
  "resources/images/profile.png": {
    "file": "assets/profile.1f676f34.png",
    "src": "resources/images/profile.png"
  },
  "resources/js/app.js": {
    "file": "assets/app.d0e20605.js",
    "src": "resources/js/app.js",
    "isEntry": true,
    "dynamicImports": [
      "resources/js/Pages/Welcome.vue"
    ],
    "css": [
      "assets/app.1fc51312.css"
    ]
  },
  "resources/js/Pages/Welcome.vue": {
    "file": "assets/Welcome.6e7da9ff.js",
    "src": "resources/js/Pages/Welcome.vue",
    "isDynamicEntry": true,
    "imports": [
      "resources/js/app.js"
    ],
    "assets": [
      "assets/profile.1f676f34.png"
    ]
  },
  "resources/js/app.css": {
    "file": "assets/app.1fc51312.css",
    "src": "resources/js/app.css"
  }
}

```

Could you please share the minimal reproduction steps required to generate the manifest you have?

**Comment by vlados** [comment]
I found the problem. When using `assetsInclude` in vite.config.js
```js
export default defineConfig({
    assetsInclude: ["**/*.mp4"],
    plugins: [
        laravel({
            input: ["resources/css/app.css", "resources/js/app.ts", "resources/js/wireui.ts"],
        }),
    ],
});
```

This is generating all assets as mentioned before. Removing this line is fixing the problem and the manifest.json is correct

**Comment by timacdonald** [comment]
Awesome!

`assetsInclude` is not meant to be used to include files in the manifest, but instead to tell Vite when parsing JavaScript what it should consider a static asset.

For example, imagine you had the following Vue template...

```js
<template>
    <Head title="Welcome" />

    <img src="../../images/profile.png">
</template>
```

Vite detects the image and makes it a "static" file that it treats differently. However, imagine for whatever reason we rename `profile.png` to `profile.foo`:

```js
<template>
    <Head title="Welcome" />

    <img src="../../images/profile.png">
</template>
```

Vite will now explode...

Screen Shot 2022-08-19 at 10 47 30 am

Now what we need to do is to tell Vite to treat `.foo` files as a static asset:

```js
export default defineConfig({
    assetsInclude: '**/*.foo',

    /* ... */
});
```

**Comment by vlados** [comment]
Thank you @timacdonald for the extensive explanation! ❤️

**Comment by timacdonald** [comment]
No troubles at all

**Comment by fflnvb** [comment]
Hi @timacdonald,
I am using the function right now by building the assets for my js and css via `npm run build` and on my preview and instead of the path the result on my Website is looking like this (uppercase inserted by me):
`http://HOST:ENTRYPOINT/resources/js/app.js`
I can see that this is supposed to be displayed when HMR or Hotmode is enabled.

What do I have to do in order to get the versioned file path for the asset as described in docs?

Can´t find anything on the web regarding disabling HMR.
Manifest seems to be looking fine:
`{
  "resources/js/app.js": {
    "file": "assets/app.aac2dc08.js",
    "src": "resources/js/app.js",
    "isEntry": true
  },
  "resources/sass/app.scss": {
    "file": "assets/app.c090eeea.css",
    "src": "resources/sass/app.scss",
    "isEntry": true
  }
}`

**Comment by timacdonald** [comment]
Hey there,

The plugin is already setup to clear the `hot` file when `npm run dev` is killed. Something funky must have happened for you.

Also, make you have have added the hot file to your git ignore as per the upgrade guide / new app skeleton - that way you will never push the hot file to your server.

**Comment by timacdonald** [comment]
Before we get into debugging this @IronSinew I just wanna ask if you are using Inertia and Vue, do you have an actual need for the asset helper?

You should just reference files in your Vue templates:

```
<template>
    <img src="../../path/to/image.jpg">
<template>
```

**Comment by IronSinew** [comment]
> Before we get into debugging this @IronSinew I just wanna ask if you are using Inertia and Vue, do you have an actual need for the asset helper?

We wanted to keep our public-facing files in blade and internal application in inertia so we wouldn't have to set up SSR (for SEO purposes, etc). One could argue that that is an _actual need_ for using the asset helper.

**Comment by timacdonald** [comment]
Makes sense. Could you put together a minimal reproduction project so I can see what is happening and help you with the issue:

```sh
laravel new bug-report --github="--public"
```

**Comment by prattcmp** [comment]
Screen Shot 2022-09-12 at 8 27 45 PM

I'm experiencing the same issue as @IronSinew but my packages are updated. Not sure what could be going wrong.

**Comment by chrispage1** [comment]
It would have been nice to reference my PR which this code appears to have taken a fair bit of inspiration from #43098

It's a shame my PR with fewer lines of code was rejected as 'we need to be very careful regarding the amount of code we include' being the reason cited. Nothing like a bit of community spirit :)

**Comment by timacdonald** [comment]
I apologise I didn't reference your previous PR @chrispage1.

When you first opened your PR we didn't see the need for the feature, but later came to realise it was a useful feature. I had unfortunately forgotten about your previous PR for this feature when I opened this one.

We appreciate your suggestions and contributions and sometimes I need to see something a few times to really see the community need for it.

I'm sorry if I rubbed you the wrong way with this and I hope it doesn't put you off continuing to contribute and help us make Laravel better in the future.

**Comment by chrispage1** [comment]
No worries @timacdonald it's one of those things. I look forward to one day hoping to make a contribution that does get merged! 😅

**Pull request merged**
