### PR TITLE
[5.3] add $default parameter to query builder when() method

### PR DESCRIPTION
**Pull request by tomschlick**
Originally opened in #15421 but @themsaid asked I open it against master
## 

This allows you to specify a default closure to run if the `when()` $value attribute is false.

I recently found myself creating a sorting / filtering system with defaults that the user could change. Without this you would have to do all kinds of wackiness to clear the previous where() clause on $value being true.

Here is an example of this in action

``` php

Time::when($request->has('type'), function ($query) use ($request) {
    return $query->where('type', $request->input('type'));
}, function ($query) {
    return $query->where('type', 1);
})
->get();


```

### CODE REVIEW

**Comment by tomschlick** [comment]
Looks like composer is having some issues on Travis... Any way to schedule a rebuild on that?

**Comment by taylorotwell** [comment]
Do you want to send this to 5.3?

**Comment by tomschlick** [comment]
Ugh, this branch switcher from GH sucks. I'll re-submit.

**Comment by themsaid** [comment]
@tomschlick I was the reason for all this opening/closing hassle, sorry :)

**Comment by tomschlick** [comment]
No problem haha

**Pull request closed without merging**
