### PR TITLE
[5.3] Allow `SerializesModels` to optionally restore models excluded by global scope (`SoftDeletes`, for example)

### PR DESCRIPTION
**Pull request by inxilpro**
Currently, if you want to queue jobs with deleted models (or anything else restricted by default via a global scope), you cannot use `SerializesModels`. This change adds a method to `Illuminate/Queue/SerializesAndRestoresModelIdentifiers` called `restoresModelsWithoutScopes()`, which returns `false` by default, but can be overridden by classes that use it to change this behavior.

Now you can do:

```php
class DoSomethingWithDeletedUsers extends Job implements ShouldQueue
{
    use SerializesModels;

    public function __construct(User $user)
    {
        $user->delete();
        $this->user = $user;
    }

    public function handle()
    {
        $this->user->trashed(); // true
    }

    protected function restoresModelsWithoutScopes()
    {
        return true;
    }
}
```

By having `restoresModelsWithoutScopes()` return `true`, the `getRestoredPropertyValue()` method will call `newQueryWithoutScopes()` instead of `newQuery()`.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Personally it seems like it should always be without scopes and not even be configurable. If you queued the model instance surely that means you want it to be available.

**Comment by inxilpro** [comment]
That's what I thought at first, but I can think of some cases where that's not true. For example, say you queued an email to a user to be delivered in 3 hours and then deleted the user for some reason 2 hours later—in that case you probably wouldn't want the job to run.

I could see a strong argument for defaulting `restoresModelsWithoutScopes()` to return `true`, though, because I think you're right in most cases.

**Comment by taylorotwell** [comment]
Yeah, I can't decide there. I mean that sounds fairly edge case and could be mitigated by checking if the user has been deleted or not before sending the email. I'm still of the opinion it should be without scopes by default.

**Comment by inxilpro** [comment]
I'll update tonight making no scopes the default. I don't think it hurts much to make it configurable, especially because it's a pretty big pain to modify this particular behavior via inheritance/composition.

**Comment by GrahamCampbell** [comment]
Looks like a nice idea. :+1:

**Comment by inxilpro** [comment]
Done.

**Comment by taylorotwell** [comment]
I tweaked this a bit. If you want scopes you can just override the `getQueryForModelRestoration` method. There isn't really a need for an option then.

**Comment by inxilpro** [comment]
Oh, good call. That's certainly simpler is we assume that most people won't want to change this.

**Pull request merged**
