### PR TITLE
[5.5] Mix() won't throw an exception

### PR DESCRIPTION
**Pull request by adampatterson**
I am not 100% confident that I am using `report()` correctly but I am getting what I expected as the outcome.

I added `report()` to `mix()`. In both cases, Sentry collected an entry, and with debut turned off Loggly also collected an entry.

**Debug = False**

`<link rel="stylesheet" href="{{ mix('/static/css/basemissing.css')}}">`

image

**Debug = True**

`<link rel="stylesheet" href="{{ mix('/static/css/basemissing.css')}}">`

image

ref laravel/framework#20376

### CODE REVIEW

**Comment by taylorotwell** [comment]
You still have log in there. Remove any reference to logging entirely. Report will take care of that.

**Comment by taylorotwell** [comment]
It still throws an uncaught exception earlier in the method. Is this intentional? Also, don't see what this has to do with debug mode even though the title to this PR mentions debug mode.

**Comment by adampatterson** [comment]
@taylorotwell sorry. I miss understood your previous comment. The original use case was to allow `mix()` to return the invalid resource that was passed through and not throw an exception. That is why I had debugged mode in there.

At the moment when using `report()` no exception is thrown. So I have questions around how to properly use `report()`.  How will others who thought that the exception should be thrown be able to handle their expected outcome? 

I have limited knowledge of how to do good error handling but I am guessing that a custom exception for Mix needs to be made and thrown so that it can optionally be handled by developers as they see fit.

If that is the case then I will close this PR and give that a try.

**Comment by taylorotwell** [comment]
@adampatterson report() calls the report() method of your Exception Handler. So the exception will still be reported to your logs or Sentry or Bugsnag or whatever else you do in your exception handler's report method.

**Pull request merged**
