### PR TITLE
[5.5] add `abilities` method to Gate contract

### PR DESCRIPTION
**Pull request by browner12**

### CODE REVIEW

**Comment by tillkruss** [comment]
Why was this added? It's hard to piece so many commits together without a PR description.

**Comment by browner12** [comment]
Relevant PR 

https://github.com/laravel/framework/pull/19173

**Comment by a-komarev** [comment]
@browner12 you've posted a recursion link :)

**Comment by tillkruss** [comment]
Yeah, #19173 is is this issue.

**Comment by browner12** [comment]
sorry, was on mobile and in a rush.  https://github.com/laravel/framework/pull/19143

**Comment by tillkruss** [comment]
Thanks!

**Pull request merged**
