### PR TITLE
Allow MailChannel::class to be used for routing information in anonymous notification

### PR DESCRIPTION
**Pull request by dejagersh**
PR fixing issue #41261.

## Problem
Consider the following code:

```php
class InvoicePaid extends Notification
{
    public function via() {
        return [MailChannel::class];
    }
    
    // ...
}
```

```php
Notification::route(MailChannel::class, 'taylor@example.com')
            ->notify(new InvoicePaid($invoice));
```

This will not send anything nor notify anyone of it not sending anything

You have to use `'mail'` in `Notification::route()`:

```php
Notification::route('mail', 'taylor@example.com')
            ->notify(new InvoicePaid($invoice));
```

To me, this is very unintuitive. Why can I use `MailChannel::class` in `via()`:

```php
class TestMailNotification extends Notification
{
    public function via($notifiable)
    {
        return [MailChannel::class];
    }
}
```

but then I can't use `MailChannel` in the following context?

```php
Notification::route(MailChannel::class, 'taylor@example.com')
            ->notify(new InvoicePaid($invoice));
```

## Solution
This PR adds support for `MailChannel::class` in `Notification::route(MailChannel::class, 'taylor@example.com');`. `MailChannel` will check `'mail'` first and as fallback it will check `MailChannel::class`. The implementation is taken from the suggested solution that Derek commented on my issue: https://github.com/laravel/framework/issues/41261#issuecomment-1052468893 Credits to him :)

### CODE REVIEW

**Comment by ankurk91** [comment]
So you changes will only allow to use `MailChannel::class`, if yes, what about other channels like
`SlackChannel::class`, `SMSChannel::class`

Can we make other channel work in the same way?

**Comment by thejager** [comment]
Hi @ankurk91 thanks for your message.

I've thought about this, but `laravel/framework` does not contain these channels, so I can't make those changes in this PR.

**Comment by ankurk91** [comment]
The `via()` method on a notification class can accept FCQN already, there must be a way to use FCQN for anonymous notifications too

```php
    public function via($notifiable): array
    {
        return [FCMChannel::class, SlackChannel::class, NexemoChannel::class,  'database', 'mail'];
    }
```

**Comment by taylorotwell** [comment]
Right we just document strings for first-party channels and FQCN are used for third-party channels. If we are going to do this I agree we would probably want to support it across every first-party channel.

**Pull request closed without merging**
