### PR TITLE
[5.7] Add oxford comma

### PR DESCRIPTION
**Pull request by m1guelpf**
I don't think this needs an explanation, does it?

:octocat:

### CODE REVIEW

**Comment by jordyvandomselaar** [comment]
Grammar nazi's are evolving.

Build failed, how did you manage to do that?

**Comment by jmarcher** [comment]
I do not think this is necessary, there is even a big controversy inside the Oxford University about this. If we do not use them everywhere I find it better to not use them at all.

**Comment by Riari** [comment]
Sometimes it's necessary, but this isn't one of those times. 😄

**Comment by ludo237** [comment]
Really 😕 ?

**Comment by GrahamCampbell** [comment]
> Grammar nazi's are evolving.

Little bit ironic that Oxford is spelt wrong, but hey. :P

**Comment by browner12** [comment]
o god, what have I started?!?

fun reading on part of the reason I completely support use of the Oxford Comma.

https://www.nytimes.com/2017/03/16/us/oxford-comma-lawsuit.html

**Pull request merged**
