### PR TITLE
[5.7] Add possibility to configure `verificationUrl` live time.

### PR DESCRIPTION
**Pull request by TBlindaruk**
- Improvements of https://github.com/laravel/framework/pull/24655

### CODE REVIEW

**Comment by TBlindaruk** [comment]
@m1guelpf , changed

**Comment by taylorotwell** [comment]
Why do you want to change it?

**Comment by zaknesler** [comment]
@taylorotwell Does it more sense to hardcode it? I can imagine many people wanting tighter or more lenient time frames for the validation link.

**Comment by TBlindaruk** [comment]
I have the same opinion as @zaknesler

**Comment by antonkomarev** [comment]
It could be used for key rotation to improve security.

**Comment by taylorotwell** [comment]
If this isn't a good default value, provide a better one to the core.

**Comment by zaknesler** [comment]
A better.. default value? Why is it wrong to have this value configurable? Does this bloat the framework in any negative way?

Can't say I'm surprised. 👍

**Pull request closed without merging**
