### PR TITLE
[5.5] Adds task command output to Artisan commands

### PR DESCRIPTION
**Pull request by nunomaduro**
This PR addresses a creation of new **command output**. Adding a new method to the Artisan `Illuminate\Console\Command` class that allows the an user to understand the result of the given task.

- The task method code

```php
    /**
     * Write a string as task output.
     *
     * @param  string  $string
     * @param  callable  $callable
     * @return void
     */
    public function task($string, callable $callable)
    {
        $result = $callable() ? '<info>✔</info>' : '<error>fail</error>';

        $this->output->writeln("$string: $result");
    }
```

- Usage example

```php
    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->task('Downloading Laravel', function () {
            $response = Client::download('cabinet.laravel.com/latest.zip', storage_path('latest.zip'))

            return response->success();
        });
    }
```

- Result

task

### CODE REVIEW

**Review by LKaemmerling — APPROVED** [review]

**Comment by phanan** [comment]
This should be in your own extending class IMO.

**Comment by taylorotwell** [comment]
I do kind of like it but also agree that probably we should leave it up to the developer to add this helper to their own class. Thanks!

**Comment by deleugpn** [comment]
Pretty cool, indeed.

**Comment by OwenMelbz** [comment]
Is the command macroable to allow this method to get added? And if not - is that more of a solution to enable this functionality for people?

**Comment by nunomaduro** [comment]
@OwenMelbz I may create a package for this. I keep you posted 🙂

**Comment by nunomaduro** [comment]
@OwenMelbz @m1guelpf Just created a package with this feature: [https://github.com/nunomaduro/laravel-console-task](https://github.com/nunomaduro/laravel-console-task)

**Comment by deleugpn** [comment]
@nunomaduro maybe you could even look at how spatie implemented the parallelMap in order to try parallel task.

**Pull request closed without merging**
