### PR TITLE
[5.2] Set .php extension for compiled view files

### PR DESCRIPTION
**Pull request by amenk**
Having the proper extensions (it's PHP code in there), makes developer's live easier
- Code highlighting in the IDE
- Debugging functionality (at least in PHPStorm)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Seems like a reasonable idea. :+1:

**Comment by GrahamCampbell** [comment]
Please could you update the tests though.

**Comment by garygreen** [comment]
:+1:

**Comment by ibrasho** [comment]
:+1:

**Comment by amenk** [comment]
What is @coveralls trying to tell us?

**Pull request merged**
