### PR TITLE
[5.7] Use Plus Combined Assignment operator when possible

### PR DESCRIPTION
**Pull request by carusogabriel**

### CODE REVIEW

**Comment by taylorotwell** [comment]
If there is no existing bug I see no point in this change.

**Comment by jeremyFreeAgent** [comment]
I thought it were easier to merge it and to say thank you. Obviously I was wrong!

**Comment by ravanscafi** [comment]
[image](https://laravel.com/docs/5.6/contributions)
* unless it's working, in this case keep it like that and close all related Pull Requests

**Comment by Majkl578** [comment]
> If there is no existing bug I see no point in this change.

Should these PRs be reverted then? They don't fix any _bug_.
- #25418
- #25414
- #25412
- #25400
- #25394
- #25334
- #25293
- #25199
- #25188 
- #25187
- #25050
- #25017
- #25080
- #25079
- #25329

**Comment by devcircus** [comment]
😂 The whining in open source has reached epic levels.

**Comment by Dylan-DPC** [comment]
They actually have a valid point. There is stark irrelugarility in home some PRs that address similar concerns were fixed.

**Comment by taylorotwell** [comment]
If you want to re-open it I’ll merge it. I explained on Twitter why I don’t like to deal much with cosmetic changes and prefer to focus on actual bugs or feature improvements, but since people are apparently frustrated by this and airing it out on Twitter I will merge it.

**Comment by Majkl578** [comment]
> I don’t like to deal much with cosmetic changes

Who does, right? 😊 That's why people have coding standards and tools to help them.

To help you end the code style anarchy, if you would be interested, I (we) can prepare a PR that will integrate Doctrine CS, incl. Travis checks. Of course you can adjust some nitpicks here and there if the out-of-box defaults don't fit your preferences.

**Comment by ntzm** [comment]
Laravel already uses StyleCI for that, which I believe uses PHP-CS-Fixer under the hood (feel free to correct me). I've been working on a PR for PHP-CS-Fixer for a while that will fix these cases.

**Pull request closed without merging**
