### PR TITLE
Fix some typos in "Auth" directory root files.

### PR DESCRIPTION
**Pull request by GinoPane**
Fix some typos:
1) AuthManager.php - hyphens by a rule: http://www.oxforddictionaries.com/words/hyphen (compound adjective);
2) RequestGuard.php, TokenGuard.php - indefinite article is not used with plural nouns;
3) SessionGuard.php - commentary for property changed to correspond commentary for its getter ("Get the last user we attempted to authenticate.").

I've removed controversial parts.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
These changes are not required as previously discussed.

**Comment by GinoPane** [comment]
These changes were not discussed, we've talked about pronouns. I'm interested why don't you want to fix grammar errors. All these changes are based on rules.

**Comment by GrahamCampbell** [comment]
There are no actual errors here.

**Comment by GinoPane** [comment]
But I have even provided corresponding rules, that's why I do not understand the reason:)

**Comment by rizqidjamaluddin** [comment]
For what it's worth, the hyphens are a solid case.

**Pull request closed without merging**
