### PR TITLE
[8.x] Add method to determine if a Collection contains a specific amount of items

### PR DESCRIPTION
**Pull request by bradyrenting**
This PR introduces the method `containsItems()` to Collection and LazyCollection. Example below.

Currently you can already check if a Collection contains a single item by calling `containsOneItem()` on a Collection.
I believe it would be useful (and for consistency) to have a similar method to be called on a Collection which contains of more than 1 item.

### LazyCollection

```php
// Instead of ..

if ($lazyCollection->take(3 + 1)->count() === 3) {
   // do something..
}

// You can..

if ($lazyCollection->containsItems(3) {
   // do something..
}
```

### Collection

```php
// Intead of..

if ($collection->count() === 3) {
   // do something..
}

// You can..

if ($collection->containsItems(3) {
   // do something..
}
```

Thanks!

### CODE REVIEW

**Comment by BrandonSurowiec** [comment]
Laravel 8 isn't open to new features, need to target 9.x. 

I think `containsItems(3)` is less clear than `$collection->count() === 3`.

**Comment by bradyrenting** [comment]
> Laravel 8 isn't open to new features, need to target 9.x.

Ah. I thought they still allow non-breaking feature implementations. I was planning on also creating a PR (if this one would get merged) for 9.x, as well for the docs.


> I think `containsItems(3)` is less clear than `$collection->count() === 3`.

What do you suggest? I feel like there is a good reason to add this functionality because `containsOneItem()` also exists.

**Comment by bradyrenting** [comment]
Seems like I have made some mistakes with the Lazy implementation. Will be fixing that first.

**Comment by BrandonSurowiec** [comment]
@bradyrenting For the lazy implementation `->take($amount +1)->count() === $amount` should work.

@bradyrenting  I didn't know `containsOneItem()` existed before this PR. Push the PR back up as `containsItems` like you have it and see what happens. It keeps the same naming convention as the method above so it's probably good as-is name-wise. I was questioning the need for the method, but I can see it being useful for lazy collections. It's just my opinion is all. I'm not Taylor so don't let this discourage you. Push it back up. 👍

**Comment by BrandonSurowiec** [comment]
@bradyrenting You still need to re-target the `9.x` branch or this PR will just be closed.

**Comment by bradyrenting** [comment]
> For the lazy implementation `->take($amount +1)->count() === $amount` should work.

Thank you, I closed the PR because I didn't think I had enough time for a quick fix, but you helped me out. 
Fixed the Lazy implemenation, which for me feels like another advantage of this feature.

Instead of..
```php
if ($lazyCollection->take($count + 1)->count() === $count {
   // do something..
}
```

You can..
```php
if ($lazyCollection->containsItems(3) {
   // do something..
}
```

I have decided to go with `containsItems` because of the naming convention, but I think `itemsCount()` describes this functionality a bit better.

**Comment by bradyrenting** [comment]
> @bradyrenting You still need to re-target the `9.x` branch or this PR will just be closed.

Are you sure? I believe there are still minor features like this getting merged into 8.x.

**Comment by bradyrenting** [comment]
I have updated my initial comment to describe more about the LazyCollection benefits.

**Comment by BrandonSurowiec** [comment]
@bradyrenting Yep, bug fixes only on 8.x:
https://github.com/laravel/framework/pull/41404#issuecomment-1062837585

All the PRs you've been seeing merged have been bug fixes.
https://laravel.com/docs/9.x/releases#support-policy

**Comment by bradyrenting** [comment]
> @bradyrenting Yep, bug fixes only on 8.x: [#41404 (comment)](https://github.com/laravel/framework/pull/41404#issuecomment-1062837585)
> 
> All the PRs you've been seeing merged have been bug fixes. https://laravel.com/docs/9.x/releases#support-policy

@BrandonSurowiec You're right, Thanks! 

I will close this PR and create a new one targetting 9.x. This also gives me the opportunity to explain how it benefits LazyCollection in a new thread.

**Pull request closed without merging**
