### PR TITLE
[5.4] test both phpredis and predis drivers

### PR DESCRIPTION
**Pull request by halaei**
Tests should fail because now because of my bad PR  https://github.com/laravel/framework/pull/17477

Sorry :(

### CODE REVIEW

**Comment by taylorotwell** [comment]
I've reverted 2 of the PRs.

**Comment by GrahamCampbell** [comment]
Please rebase this. :)

**Comment by taylorotwell** [comment]
I may just merge #17196 to normalize all this.

**Comment by halaei** [comment]
@GrahamCampbell you mean I should resubmit this?

**Pull request closed without merging**
