### PR TITLE
[8.x] PHPUnit 10 Support

### PR DESCRIPTION
**Pull request by driesvints**
Pending PHPUnit v10 release.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Maybe we should do the same actions trick you did for browserkit, here @driesvints?

**Comment by nuernbergerA** [comment]
@driesvints `phpunit.xml.dist` will be renamed to `phpunit.dist.xml`

---

See https://github.com/sebastianbergmann/phpunit/commit/07a022ad0548823b04c8fab073a7bff2fbcf9c8c

**Comment by crynobone** [comment]
@nuernbergerA we can't rename it until we remove support for older PHPUnit versions.

**Comment by nuernbergerA** [comment]
@crynobone yeah you are right maybe it's a thing for 9.x

**Comment by crynobone** [comment]
`9.x` still needs to support PHP 7.4, which PHPUnit 10 doesn't support.

**Comment by driesvints** [comment]
@crynobone @nuernbergerA even so: it doesn't seems to me that the old convention will be removed?

**Comment by nuernbergerA** [comment]
@driesvints I think it will be removed in V12 so there is plenty of time

**Review by valehasadli — APPROVED** [review]

**Comment by driesvints** [comment]
Gonna close this until there's more news on PHPUnit 10's release date.

**Pull request closed without merging**
