### PR TITLE
[9.x] Validate ulid before route binding query

### PR DESCRIPTION
**Pull request by michaelnabil230**
See: https://github.com/laravel/framework/pull/44945

### CODE REVIEW

**Comment by taylorotwell** [comment]
I don't think this handles child route bindings.

**Comment by taylorotwell** [comment]
@michaelnabil230 can you fix the file conflicts here?

**Comment by michaelnabil230** [comment]
> 

Okay

**Comment by michaelnabil230** [comment]
@taylorotwell I'm fixed the conflicts, can be now merged

**Comment by taylorotwell** [comment]
Tests are failing @michaelnabil230

**Pull request merged**
