### PR TITLE
[8.x] Add regression tests for booting service from another service provider

### PR DESCRIPTION
**Pull request by crynobone**
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>

### CODE REVIEW

**Review by nunomaduro — APPROVED** [review]
This looks good to me.

**Comment by GrahamCampbell** [comment]
NB Tests failing because they need https://github.com/laravel/framework/pull/37405 to be merged first.

**Review by GrahamCampbell — APPROVED** [review]

**Review by ConsoleTVs — APPROVED** [review]
I would also make sure that registering a provider in the register method of another provider works as well but this sure fixes future problems on the issue. Great!

**Comment by crynobone** [comment]
> I would also make sure that registering a provider in the register method of another provider works as well but this sure fixes future problems on the issue.

This doesn't break on 8.41 and wouldn't be affected by `Illuminate\Foundation\Application::boot()` since, at that point, all service providers should be registered.

**Pull request merged**
