### PR TITLE
[5.5][WIP] custom relations

### PR DESCRIPTION
**Pull request by browner12**
this PR is the *very delayed* result of the following issues.

https://github.com/laravel/framework/issues/8830
https://github.com/laravel/framework/issues/13056
https://github.com/laravel/internals/issues/47

The motivation behind this PR is to allow the Null Object pattern to work with Eloquent relationships.  I have the need in some applications for both a null object and a pseudo object, and this PR should hopefully allow for both of those options.

### Examples

I've tried to simplify the examples down as best I can to make them easier to understand. Please be aware that I'm sure there are other ways to accomplish certain things other than the way I've presented it in the code. If you'd like to share other ways you are accomplishing this goal, please leave a comment. It is much appreciated to see other ways of looking at it.

**Null Object**

The application has `Order`s that have discounts applied to them through `Coupon`s (example stolen from @adamwathan 's Laracon EU talk).

Our 'orders' table has the structure:

- id
- coupon_id

Our order would look something like this:

```php
class Order
{
    public function coupon
    {
        return $this->belongsTo(Coupon::class);
    }
}
```

The view might look like:

```blade
@if ($order->coupon)
    Your coupon has given you a discount of {{ $order->coupon->discount }}.
@else
    Your coupon has given you a discount of 0.
@endif
```

With our updated code:

```php
class Order
{
    public function coupon
    {
        if ($this->coupon_id) {
            return $this->belongsTo(Coupon::class);
        }

        $nullCoupon = new Coupon([
            'discount' => 0,
        ]);

        return $this->customRelation($nullCoupon);
    }
}
```

our view could be:

```blade
Your coupon has given you a discount of {{ $order->coupon->discount }}.
```

**Pseudo Object**

The application displays blogs, that can be written by a registered user in the system, or a guest user.  The table structure looks like the following:

- id
- title
- content
- author_id (nullable)  --> foreign key to the user table
- first_name (nullable)
- last_name (nullable)
- email (nullable)

In the current version of Laravel, you would have a simple `belongsTo` relationship.

```php
class Blog
{
    public function author()
    {
        return $this->belongsTo(User::class);
    }

    public function getGuestAuthorAttribute()
    {
        return new User([
            'first_name' => $this->first_name,
            'last_name'  => $this->last_name,
            'email'      => $this->email,
        ]);
    }
}
```

Then in the views you could do something similar to the following:

```blade
This blog was written by {{ ($blog->author) ? $blog->author->name : $blog->guestAuthor->name}}.
```

With the change we could combine some things and move the conditional into the Model.

```php
class Blog
{
    public function author()
    {
        if ($this->author_id) {
            return $this->belongsTo(User::class);
        }

        $guestAuthor = new User([
            'first_name' => $this->first_name,
            'last_name'  => $this->last_name,
            'email'      => $this->email,
        ]

        return $this->customRelation($guestAuthor);
    }
}
```

and our view might be simplified to

```blade
This blog was written by {{ $blog->author->name}}.
```

### Limitations

Originally I was thinking with this method we would essentially be able to return *anything* from the custom relationship. However, due to the fact we call `setRelation` on the results of the relationship, we **need** to pass in an Eloquent Model.

Also, because we are returning this dummy model, chaining will not work properly. Not sure if there is any way around this.

### Questions

1. Could we refactor to allow things other than Eloquent models in the custom relation?
2. Would it be better to refactor the `getRelationshipFromMethod` function to allow things other than `Relation`s? This would require checking that the `$relation` was an instance of `Relation` before we called the `getResults` method.

### Summation

In these examples I've used the default objects to create the Null and Pseudo objects. You could just as easily create custom objects like `GuestUser` and `NullTeam`.

Is this perfect? Probably not, but I want to get the conversation started, and hopefully this is a good jumping off point to start supporting this type of ability.

### Side Note

the branch name of this PR is a little off topic, because originally I was trying to allow null objects to be returned from relationships, but I realized half way through essentially you could create any type of custom relationship with this edit.

😅  *phew*

### CODE REVIEW

**Comment by lucasmichot** [comment]
Really nice - could replace the `NullUser` that I often use

> Could we refactor to allow things other than Eloquent models in the custom relation?

At some point, I always find myself returning sometimes something else, like the content of a JSON file or some JSON data from NoSQL storage engine - this would rock

**Comment by ruchern** [comment]
I like this a lot. Makes the Blade view looks cleaner and a few lines of code to check for null values.

**Comment by taylorotwell** [comment]
Is this only applicable with belongsTo relationships? What do you mean by method chaining doesn't work?

**Comment by marcvdm** [comment]
Why not a method on the `Illuminate\Database\Eloquent\Relations\BelongsTo` class

```php

class Blog
{

    // With simple default array, uses the relation "User::class"
    public function author()
    {
        return $this->belongsTo(User::class)->withDefault([
            'first_name' => $this->first_name,
            'last_name'  => $this->last_name,
            'email'      => $this->email,
        ]);
    }

    // With callback
    public function coAuthor()
    {
        return $this->belongsTo(User::class)->withDefault(function($blog) {
            return new User([
                'first_name' => $this->first_name,
                'last_name'  => $this->last_name,
                'email'      => $this->email,
            ]);
        });
    }
}

```

**Comment by taylorotwell** [comment]
Yeah, we already have `withDefault` on `HasOne`. We should just add the same functionality here.

**Comment by marcvdm** [comment]
Lol, did not even know of that feature.

Maybe make a trait for it and use it on `HasOne`, `BelongsTo`, `MorphOne` and `MorphTo`

**Comment by browner12** [comment]
wow, cool. I did not know that `withDefault` existed either.

The `CustomRelation` is its own independent relationship, so you could pair it with any of the other relationships.  Basically its main purpose is to have the `getResults()` method, since that gets called automatically.

What I mean by being unable to chain is we no longer have a useful query builder object returned to us when we call the actual method instead of the dynamic property.  So in our Order/Coupon example above lets say each `Order` could have many `Coupon`s.  If we wanted to tack additional conditionals onto the relationship, we would be SOL.

```php
$coupons = Order::find(1)->coupons()->where('value', 5);
```

This would be okay if we returned the `hasMany` relationships, but I'm not sure if the `customRelation` would be valid here.  Now that I'm thinking about it, maybe it wouldn't matter since you're already returning a `null` result so tacking clauses at the end wouldn't make a difference.

While I think the `withDefault` is a really cool feature, and I'm definitely going to start using it in some spots, I think the `customRelation` might still be necessary in specific situations.  Here's an example.

We have `Game` and `Team` models.  Each game has a home `Team` and away `Team` that participate. We need a way to figure out who the winning team was.

```php
class Game
{
    public function winningTeam()
    {
        if ($homeTeamWonTheGame) {
             return $this->belongsTo(Team::class, 'home_team_id');
        }

        elseif ($awayTeamWonTheGame) {
             return $this->belongsTo(Team::class, 'away_team_id');
        }

        return $this->customRelation(new Team());
    }
}
```

As I'm writing this example, I realize you could just use the default in the `elseif` clause and it would essentially behave the same way, but maybe we lose a little bit of readability that way.

**Comment by decadence** [comment]
Here I asked about `withDefault` for BelongsTo but have no answers.
https://github.com/laravel/framework/issues/16614

**Comment by marcvdm** [comment]
@browner12 You could solve that with the following when `withDefault` is a trait on the belongsTo class

```php
class Game
{
    public function winningTeam()
    {
        return $this->belongsTo(Team::class)
            ->withDefault([])
            ->where('id', $this->winning_team_id);
    }
}
```

**Comment by browner12** [comment]
great idea @marcvdm !

might even take that another step and make a custom accessor for the `winning_team_id`.

```php
public function getWinningTeamIdAttribute()
{
    //logic to return winning team id
}
```

then you could omit the `where` clause

**Comment by browner12** [comment]
so it that the direction we want to go?  extract `withDefault` functionality to a trait and then use it in appropriate relationships?

I will definitely make a docs PR as well with this, because it seems like `withDefault` is not very well known.

**Comment by taylorotwell** [comment]
@decadence I don't necessarily crawl issues for things to implement. Anyone can contribute the feature to the framework.

**Comment by taylorotwell** [comment]
@browner12 I wouldn't even extract it to a trait. I would just implement it totally separately and then we can discuss it from there.

**Comment by decadence** [comment]
@taylorotwell I didn't expect you to implement this. @sileence asked there for your opinion. He made `withDefault` initially.

**Comment by sileence** [comment]
I think adding `withDefault` to belongsTo would be the more consistent option here + you don't need to add the extra IF. Please let me know if you want to submit the PR or you want me to go ahead and submit it for you @browner12.

**Comment by sileence** [comment]
@decadence to be honest I wasn't sure this was necessary because when I've faced this issue (for example when working with Posts and Categories and the category can be null), I just create a need object and save it to the database, that way I avoid checking for null relationships.

However after I read the author / guest author example it makes perfect sense to support this.

**Comment by taylorotwell** [comment]
Closing this since other PR is open.

**Pull request closed without merging**
