### PR TITLE
[9.x] Add `Arrayble` in to `Arr`

### PR DESCRIPTION
**Pull request by michaelnabil230**
**NOTE**
If the idea is good for the laravel team, I can complete the code and add tests and all functions. I just want approval from the team to complete the code

This PR adds an `of` method to the `Arr` class so that we can create more than one process at the same time

For Example:

```php
$data = [
    'id' => 1,
    'name' => 'Michael Nabil',
    'role' => [
        'id' => 1,
        'name' => 'admin',
    ],
];

return (array) Arr::of($data)
    ->when(true, function ($arrayable) {
        $arrayable->add('age', 23);
    })
    ->undot()
    ->except('age');
```

### CODE REVIEW

**Comment by andiLeong** [comment]
we can pass the array to collection if we want chaining method call :green_heart:

**Comment by huangdijia** [comment]
What's the difference with collection?

**Comment by ankurk91** [comment]
I would rather use collection.
There is no benifit of carrying 2 similar implementation in framework.

New feature also bring the cost of maintaining them.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
