### PR TITLE
[5.4] Make FileViewFinder Macroable

### PR DESCRIPTION
**Pull request by m1guelpf**

### CODE REVIEW

**Comment by a-komarev** [comment]
Hah... as I said recently: https://github.com/laravel/framework/pull/18796#issuecomment-294211418

**Comment by m1guelpf** [comment]
@a-komarev Change the way views are loaded (For example, I recently had to change this, and had to fork the whole framework and make this little change)

**Comment by a-komarev** [comment]
@m1guelpf I mean concrete code block example & unit tests would be very useful as I think. Thanks.

**Comment by taylorotwell** [comment]
I don't think making it Macroable is the answer. We can build other ways of customization besides making it macroable.

**Pull request closed without merging**
