### PR TITLE
Update PasswordBroker.php

### PR DESCRIPTION
**Pull request by pilot911**
Add setter and getter for $emailView

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Duplicate. Already rejected,

**Comment by GrahamCampbell** [comment]
This property is not meant to be dynamically set.

**Comment by pilot911** [comment]
Then please describe how can we change PasswordBroker's $emailView for different parts of site - eg for backend and frontend. As i understand it's not possible becouse it use \Config('auth.password.email') value. And it's impossible change this value for specific part of site.

So please explain how use different views for password reset.

**Comment by pilot911** [comment]
Sorry, please, how can i use diffrent emailView for diffrent part of site (backend reset password and frontend reset password) ?

Thanks

**Comment by Anahkiasen** [comment]
Here https://github.com/laravel/laravel/blob/master/config/auth.php#L62

**Comment by pilot911** [comment]
thanks but i see one line.. how set more? thanks

**Pull request closed without merging**
