### PR TITLE
[5.8] Pass guards to redirectTo method in Authenticate middleware

### PR DESCRIPTION
**Pull request by ankurk91**
closes https://github.com/laravel/framework/issues/26292

After merging this, we will be able to use `guards` in `Authenticate` middleware
```php
<?php

namespace App\Http\Middleware;

use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Illuminate\Support\Facades\Route;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  array  $guards
     * @return string
     */
    protected function redirectTo($request, $guards)
    {
        if (!$request->expectsJson()) {
            // do something with $guards array here
        }
    }
}
```

* [PR](https://github.com/laravel/laravel/pull/4849) to https://github.com/laravel/laravel to make it compatible with v5.8
* [PR](https://github.com/orchestral/testbench-core/pull/14) to https://github.com/orchestral/testbench to make test pass

### CODE REVIEW

**Review by driesvints — APPROVED** [review]

**Comment by ankurk91** [comment]
@driesvints 
The PR to techbench has been merged.
All test passes as well, see
https://travis-ci.com/ankurk91/framework/builds/90847968
You can restart build on travis-ci  to make those checks green.

**Review by driesvints — CHANGES_REQUESTED** [review]
@ankurk91 can you also add the change from this PR? https://github.com/orchestral/testbench-core/pull/15

**Review by driesvints — APPROVED** [review]

**Comment by driesvints** [comment]
Nvm. Did it myself quickly.

**Comment by ankurk91** [comment]
It is strange to see travis build failed only on php v7.2.

**Comment by crynobone** [comment]
What's the status of this? I feel it is wrong for testbench-core to use the updated changes when this isn't approved yet since it will cause any other PR to 5.8 to return fail on travis.

**Comment by ankurk91** [comment]
@crynobone 
Travis is failing for a different reason that seems unrelated to the PR that was sent to testbench-core

https://travis-ci.org/laravel/framework/jobs/453548189#L791
The build is only failing on php v7.2
>1) Illuminate\Tests\Cache\CacheRepositoryTest::testRememberMethodCallsPutAndReturnsDefault
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_33_Illuminate_Contracts_Cache_Store::put('foo', 'bar', 10.016666666667). Either the method was unexpected or its arguments matched no expected argument list for this method


All new PR that targets laravel/framework 5.8 is failing for the same reason
https://travis-ci.org/laravel/framework/jobs/453545744#L790

**Comment by ankurk91** [comment]
This PR was initially approved by @driesvints and was rebased with `master` branch by me today to see if travis build passes.

**Comment by taylorotwell** [comment]
Yeah, it is wrong to update test bench before we have this merged really. Now all master PRs are broken because they have a signature incompatibility. 

Regarding this PR specifically... what do you want to do with the guards in the redirectTo method specifically? How are you going to actually use this in your application. 

I should point out it's also already possible to use guards in the redirectTo method by just assigning them to a property from your handle method.

**Comment by ankurk91** [comment]
I have multiple guards in my app. Each guard have its own login page. I want to redirect each different type of user to their login page.

Yes, it is possible to expose the guards in a class property.
I can make a PR for the same.

**Comment by ankurk91** [comment]
I was able to get the guard name by overriding the `handle` method.

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    protected $guards;

    public function handle($request, Closure $next, ...$guards)
    {
        $this->guards = $guards;
        return parent::handle($request, $next, ...$guards);
    }
    
    protected function redirectTo($request)
    {
        if (!$request->expectsJson()) {
            if (array_first($this->guards) === 'admin') {
                return route('admin.login');
            }
            return route('login');
        }
    }
}
```
@driesvints Let me know if you still wants to go this PR.
Feel free to close this PR.
I can send another PR to revert the changes made to testbench-core.

**Comment by driesvints** [comment]
Yeah, let's just revert things.

**Comment by ankurk91** [comment]
PR send to testbench-core to
https://github.com/orchestral/testbench-core/pull/16

**Pull request closed without merging**
