### PR TITLE
[12.x]Supports for Dameng DataBase

### PR DESCRIPTION
**Pull request by dmmars**
Dameng DataBase(we always call it 'dm') is a popular Chinese DataBase, this PR add support for Dameng DataBase. It's mainly changes the "framework/Illuminate/Database" folder. After this change you can set in the .env to connnect to Dameng,and use migrations,Query Builder,and Eloquent Model to operate the database like other database.
The common version of the Dameng DataBase is DM8. Use pdo to connect to Dameng need the driver of dmpdo. Such as use php8.2-nts-x64 in windwos,you need to add the pdo82nts_dm.dll to php. After you install Dameng, you can find these drivers in "dmdbms\drivers\php_pdo".

setting in the .env:
```
DB_CONNECTION=dm
DB_HOST=localhost
DB_PORT=5236
DB_SCHEMA=SYSDBA
DB_USERNAME=SYSDBA
DB_PASSWORD=SYSDBA

```

### CODE REVIEW

**Comment by NickSdot** [comment]
Dameng is fully proprietary?

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

**Comment by taylorotwell** [comment]
You should be able to add support via a package 👍

**Comment by DDDzzz99** [comment]
> Dameng is fully proprietary?

yes

**Comment by DDDzzz99** [comment]
> You should be able to add support via a package 👍

Thanks for you replay, I will try it.

**Pull request closed without merging**
