### PR TITLE
[5.0] Fixed FilesystemAdapter::allDirectories() method signature

### PR DESCRIPTION
**Pull request by paulofreitas**
Removed unused/unneeded $recursive argument.

### CODE REVIEW

**Comment by lukasgeiter** [comment]
Even if this PR makes total sense, it could break things for someone overriding that method because the signatures wouldn't match anymore. Please send to the master branch for 5.1 release.

**Comment by GrahamCampbell** [comment]
It's not actually breaking.

**Comment by GrahamCampbell** [comment]
PHP is fine with you passing arguments that don't exist, and this second argument was never added to the contract anyway, so nothing will break removing this.

**Comment by lukasgeiter** [comment]
@GrahamCampbell Yes it is if someone extended the class and overrode this method. Overriding method signatures have to match exactly in PHP.

**Comment by lukasgeiter** [comment]
@GrahamCampbell Whoops ye you're right... Ready to merge then ;)

**Pull request merged**
