### PR TITLE
[5.3] It lets you specify the model, when you have inheritance in morph[..]/has[..]/belongsTo[...]

### PR DESCRIPTION
**Pull request by emtudo**
To be able to specify the model.

The problem is that, when I have:

```
namespace Domain\Client;

use Domain\Address\Address;
use Illuminate\Database\Eloquent\Model;

class Client exenteds Model {
    public function addresses()
    {
        return $this->morphMany(Address::class, 'owner');
    }
}

----
namespace Domain\Customer;

class Customer extends \Domain\Client\Client
{
}

```

The "addresses" relationship doesn't work because the class morphMany is getting (by default) the class name "Domain\Customer\Customer" and in reality, it must get the "father class" which is "Domain\Client\Client".
I propose to solve this problem by adding a parameter to inform the "father class" in the following way:

```
namespace Domain\Client;

use Domain\Address\Address;
use Illuminate\Database\Eloquent\Model;
class Client extends Model {
   public function addresses()
   {
       return $this->morphMany(Address::class, 'owner', null, null, null, Self::class);
//or
       return $this->morphMany(Address::class, 'owner', null, null, null, new Self);
   }
}
```

and for morphOne

```
namespace Domain\Client;

use Domain\Address\Address;
use Illuminate\Database\Eloquent\Model;

class Client extends Model {
   public function addresses()
   {
       return $this->morphOne(Address::class, 'owner', null, null, null, Self::class);
//or
       return $this->morphOne(Address::class, 'owner', null, null, null, new Self);
   }
}
```

### CODE REVIEW

**Comment by Milewski** [comment]
instead of new Self why not self::class ?

**Comment by emtudo** [comment]
Becasue MorphMany and MorphOne use instead, and self::class returns string

**Comment by Milewski** [comment]
i mean... you could wrap it around to instead of using new self, give it the class u want it to be.... just like the `Address::class` internally you can make the initialization.. dont leave to the user to make it.. 

because in pretty much every place in laravel where you can give some class to some thing.. u are able to give it as a ::class path instead of a initialized instance of it... 

it just feels more laravel to me.

**Comment by emtudo** [comment]
Well this can be done easily, but do not want to add new commit, and increase the chances of not being accepted.

**Comment by fernandobandeira** [comment]
@emtudo Your commits will be squashed before merging, thus it will result into a single commit with all of your changes, so you can commit as much you desire. Also i'm :+1:  for keeping the standard ::class syntax.

**Comment by emtudo** [comment]
now accepts both:
accepts: self::class and new Self;

**Comment by emtudo** [comment]
If accept https://github.com/laravel/framework/pull/15512
continuous-integration/travis-ci/pr passed!

**Comment by taylorotwell** [comment]
You could probably use morphMap to solve this by mapping a class to another class name. This is also a breaking change.

https://laravel.com/docs/5.3/eloquent-relationships#polymorphic-relations

"Custom Polymorphic Types"

**Pull request closed without merging**
