### PR TITLE
[5.3] Flash messages are now displayed on login page when REFERER is not sent

### PR DESCRIPTION
**Pull request by pgrenaud**
This is a fix for a bug I found while writing test for a project. If the client doesn't send a `REFERER` header when posting data on a login form, the client is not redirected properly and the flash messages (containing the errors) are lost in the process. 

The bug occur in the following circumstances:
- You have a route redirecting from `/` to `/login`
- The client post his (wrong) credentials on the `/login` page without the  `REFERER` header
- Laravel return `/` when executing `redirect()->back()` because the referer is missing and the session cannot be accessed (session is always `null`)
- The client tries to access `/` but is redirected to `/login`, losing the flash messages (flash messages are flushed once the request is completed)
- The client access `/login` with no error messages displayed

Here's relevant code snippets mentioned in the flow above:
- https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L118
- https://github.com/laravel/framework/blob/5.3/src/Illuminate/Routing/Redirector.php#L55
- https://github.com/laravel/framework/blob/5.3/src/Illuminate/Routing/UrlGenerator.php#L136

The bug affect 5.2 and 5.3 and exists since this commit: https://github.com/laravel/framework/commit/4326dc07d8d96161fdc18d0d5859928c395819ad

The fix I propose is relatively simple. It gives UrlGenerator access to the session, so it is able to access `$session->previousUrl()` when the referer is missing. The session is set from Redirector when `setSession($session)` is called.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I don't understand why this is necessary because the URL generator already receives a session resolver in RoutingServiceProvider.

**Comment by pgrenaud** [comment]
I don't know the Laravel internals enough to tell why, but the `setSessionResolver()` method is never called. If I place a break point here https://github.com/laravel/framework/blob/5.3/src/Illuminate/Routing/UrlGenerator.php#L739 and execute the flow in my browser using the xdebug plugin, this line is never called.

**Comment by pgrenaud** [comment]
I was running on v5.2.43 and I just updated to v5.2.45. The issue is still there.

**Comment by pgrenaud** [comment]
Well, I'm sorry. The issue was on my side. A co-worker found the issue and fixed it.

**Pull request closed without merging**
