### PR TITLE
Minor split to variables

### PR DESCRIPTION
**Pull request by dotuancd**
Naming variables for easier understanding

### CODE REVIEW

**Comment by devcircus** [comment]
I'm usually not a fan of these PRs, but I really did like the way that reads compared to the current implementation.

**Comment by GuidoHendriks** [comment]
Way cleaner. Performing the same explode twice isn’t that nice.

**Comment by dotuancd** [comment]
What wrong with this PR?

**Comment by devcircus** [comment]
Often, if the pr doesn't change the behavior and it was working fine before, it won't be merged. I'm sure they've been burned in the past with PRs that were supposed to just make the code more readable, and it ended up breaking something. 🤷🏼‍♂️

**Pull request closed without merging**
