### PR TITLE
[7.x] UrlGenerator argument depends on contract not implementation

### PR DESCRIPTION
**Pull request by gerardnll**
Application crashes if routes are cached.

### CODE REVIEW

**Comment by taylorotwell** [comment]
We need more information on how to recreate this.

**Comment by driesvints** [comment]
@gerardnll please post some code examples so we can reproduce.

**Comment by driesvints** [comment]
@gerardnll I can't reproduce it with just that. We'll need more info here what's going on.

**Comment by taylorotwell** [comment]
Can you share your controller code?

**Comment by taylorotwell** [comment]
Can you also share your form request?

**Comment by taylorotwell** [comment]
I recreated it, nevermind.

**Comment by gerardnll** [comment]
Ok! I was trying to simplify the situation to avoid copying here too much and making it easy to debug but you were faster. I just get a CompiledRouteCollection. Still not sure how it happens

**Comment by driesvints** [comment]
Thanks, I've sent in an alternative pr with the fixed tests here: https://github.com/laravel/framework/pull/31740

**Comment by driesvints** [comment]
Released 7.0.3 with a fix for this.

**Pull request closed without merging**
