### PR TITLE
[5.0] Cast to an object in case we got an associative array

### LINKED ISSUE #8052: Unable to listen queue when fetch mode is set to ASSOC
I created command that implements ShouldBeQueued interface
After launching artisan queue:listen I got error

exception 'ErrorException' with message 'Trying to get property of non-object' in /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php:151

If change fetch_assoc to OBJ -> everithing is fine

### PR DESCRIPTION
**Pull request by JosephSilber**
Fixes #8052

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks @JosephSilber. :)

**Comment by GrahamCampbell** [comment]
:+1: from me.

**Comment by franzliedke** [comment]
-1.

There have been other bugs reported caused by this setting, and building workarounds in all places where it could cause trouble is a maintenance nightmare.
In my opinion, we should just get rid of this fetch mode setting. Finally. ;)

**Comment by GrahamCampbell** [comment]
> In my opinion, we should just get rid of this fetch mode setting. Finally. ;)

I agree - we should ditch it in 5.1. For now, though, I like this fix for 5.0.

**Comment by JosephSilber** [comment]
@franzliedke Just curious: where else were bugs caused by this setting? There aren't that many components that talk to the database (queue and cache come to mind).

Is it really that hard to fix in these few places?

**Comment by franzliedke** [comment]
I remember there being several bug reports.

It's probably not hard to fix, but most likely hard to maintain.

**Comment by taylorotwell** [comment]
Agree this needs to just be removed in an upcoming version.

**Pull request merged**
