### PR TITLE
[5.5] Add the batch number to `migrate:status` command

### PR DESCRIPTION
**Pull request by moElwan**
Add the batch number to `migrate:status` command
laravel-migration

### CODE REVIEW

**Comment by Kyslik** [comment]
This is good; I always end up opening up migration table and inspecting batch integer.

**Comment by taylorotwell** [comment]
Changes interface on a patch release so can't put it on 5.5.

**Comment by Kyslik** [comment]
@Mohamed-Elwan send it to `master`.

**Comment by Mohamed-Elwan** [comment]
I've create a new PR #21391 sending to master

**Pull request closed without merging**
