### PR TITLE
[5.2] less than one min for redis cache

### PR DESCRIPTION
**Pull request by halaei**
It hurts nobody and makes me happy. Please ...

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ah, yes. This change looks good. I must have misunderstood what you were asking before @halaei. 

Infact, I think we should actually apply this bug fix to L5.1 LTS @taylorotwell.

**Comment by tillkruss** [comment]
@halaei Can you explain what this change exactly does?

**Comment by GrahamCampbell** [comment]
> Can you explain what this change exactly does?

It allows the cache to be as low as 1 second instead of 1 min.

**Comment by tillkruss** [comment]
@GrahamCampbell Thanks a lot!

**Pull request merged**
