### PR TITLE
RuleToStringInterface introduced and added to all rules which support __toString()

### PR DESCRIPTION
**Pull request by vern-da-coda**
The intention is to be able to convert rules reliably to strings  e.g.

``` php
/** @var RuleToStringInterface $rule */
foreach ($rules as $key => $rule) {
    $stringRules[$key] = $rule->__toString();
}
```

### CODE REVIEW

**Comment by dennisprudlo** [comment]
Why do we need to create a new interface that just requires `__toString()`? Instead we could use PHPs own `Stringable` interface. But as it states in the docs this interface is automatically present when the class contains a `__toString()` method.
https://www.php.net/manual/en/class.stringable.php

**Comment by vern-da-coda** [comment]
Good point but _'Stringable' is available starting with 8.0 PHP version_ but Laravel supports "php": "^7.3|^8.0",

**Comment by crynobone** [comment]
`Stringable` should be a good addition for Laravel 9 since we bumping to php 8

**Comment by GrahamCampbell** [comment]
👎 For merging this, because we're only gonna immediately deprecate it.

**Comment by GrahamCampbell** [comment]
Stringable is the right way to go.

**Comment by vern-da-coda** [comment]
It's perfectly fine for me not to merge it. 
If only PHP 8 is used in [9.x]  **_Stringable_** is way more elegant.

**Pull request closed without merging**
