### PR TITLE
[5.7] Csrf Verification should accept named routes

### PR DESCRIPTION
**Pull request by adam1010**
The exceptions array doesn't currently accept named routes.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I think there might be a few other bits in the codebase that also need updating. Could you check please?

**Comment by adam1010** [comment]
@GrahamCampbell I'm not sure I follow. You mean other places relating to this CSRF middleware?

**Comment by GrahamCampbell** [comment]
I mean there are other middlewares where this change needs mimicking in, I think?

**Comment by adam1010** [comment]
It's possible. I just ran into this one on a project so needed to get it fixed.

**Comment by m1guelpf** [comment]
Maybe the order should be documented somewhere. Right now, it first checks for URL and then for route, and I can see this being hard to debug in some situation.

**Comment by staudenmeir** [comment]
This is a potential security risk if the name of a route matches the URI of a different route:

```php
Route::post('foo', 'Controller@foo');
Route::post('bar', 'Controller@bar')->name('foo');

VerifyCsrfToken::$except = ['foo'];
```

With this change, both routes would be excluded from the CSRF protection.

**Comment by m1guelpf** [comment]
@staudenmeir Yeah, that's what I was refering too. Althrough it's highly improbable, it could happen. If we're doing this, it needs to be documented & added to the upgrade guide.

**Comment by taylorotwell** [comment]
I agree the security risk of this makes me a bit uncomfortable.

**Pull request closed without merging**
