### PR TITLE
[5.6] Changed '/' to DIRECTORY_SEPARATOR

### PR DESCRIPTION
**Pull request by TBlindaruk**

### CODE REVIEW

**Comment by carusogabriel** [comment]
Maybe is something we can do everywhere, as Laravel is use in different environments :thinking:

**Comment by a-komarev** [comment]
@carusogabriel windows eats both of slashes as valid ones and Unix uses `/`.
This comment is not against this commit. It's just about thing that nothing will be changed by this commit.

**Comment by TBlindaruk** [comment]
@a-komarev ,
I agree with you about `nothing will be changed by this commit` from the technical perspective.
But we have a lot of DIRECTORY_SEPARATOR constants in `Foundation/Application.php`.
I think will be better to have a one code style (at list in one file)

**Comment by a-komarev** [comment]
@TBlindaruk I'm totally agree that consistency is a key for a good software. Glad you've linked issues to this PR. This gives it more weight.

**Pull request merged**
