### PR TITLE
[5.8] Read an optional mix asset url from MIX_ASSET_URL env variable

### PR DESCRIPTION
**Pull request by themsaid**

### CODE REVIEW

**Comment by danilopinotti** [comment]
When caching the configs by artisan command, the env helper does not always return null?

**Comment by themsaid** [comment]
@danilopinotti thanks, did that :)

**Comment by X-Coder264** [comment]
IMO, there should be tests for when the repository actually returns some value for the `app.mix_url` key. Currently all the mock ensures is that the `get` method gets called with the proper key (but it doesn't return anything).

**Comment by laurencei** [comment]
Does it have to go into the `app.php` config file? That is rapidly becoming a "dump all" place to put things.

Wouldnt the `view.php` config file make more sense in this case?

**Pull request merged**
