### PR TITLE
[5.3] Remove controller inspection from routing

### PR DESCRIPTION
**Pull request by rkgrep**
This method has quite a lot of issues and also makes routes definitions confusing as they are not directly referenced in routes file. This sometimes may lead to unexpected route definitions (e. g. if method like `getFilesystem` is added to parent or trait - developer mistake, but may be unnoticed).

It also may cause security mistakes when middleware is applied on specific methods (e. g. someone adds new method to controller and forgets to add middleware), which arise rarely when routes are defined manually.

And at last - parameters issue, which is hard to fix because of grouping or other unexpected route combinations (See #10774).

To decrease amount of breaks it should be marked as `deprecated` in next `5.1.x` release.

Possible alternative: mark this method as `deprecated` in `master` and remove in next major release.

### CODE REVIEW

**Comment by rkgrep** [comment]
CS fixed in #10778

**Comment by GrahamCampbell** [comment]
You can rebase this now. :)

**Comment by GrahamCampbell** [comment]
> To decrease amount of breaks it should be marked as deprecated in next 5.1.x release.
> Possible alternative: mark this method as deprecated in master and remove in next major release.

I think we should deprecate in 5.1 and remove in 5.2.

**Comment by taylorotwell** [comment]
We can't really mark something as deprecated in 5.1 just a few weeks before release of 5.2. :smile: ... I'm OK with deprecating this in 5.2 and removing in 5.3 though. Agree it is not really a good idea to use it.

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Can we keep this PR open then, and mark it as 5.3?

**Comment by GrahamCampbell** [comment]
Then, this can be merged as soon as we have a 5.2 branch made.

**Comment by GrahamCampbell** [comment]
Please could you rebase this, then we can merge this once we have a 5.2 branch.

**Pull request merged**
