### PR TITLE
[5.8] Merge policy callback guesses with default guess

### PR DESCRIPTION
**Pull request by CupOfTea696**
Appends the default guessed policy name to the guesses returned from the guess policy callback.

### CODE REVIEW

**Comment by driesvints** [comment]
Can you add a test for this?

**Comment by CupOfTea696** [comment]
@driesvints Done!

**Comment by CupOfTea696** [comment]
Added an additional policy class to ensure the callback tests all pass because it receives the policy form the callback and not because it's the default result.

**Comment by taylorotwell** [comment]
**Note: This PR lacks an explanation of what benefit the gives users.**

I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Pull request closed without merging**
