### PR TITLE
[5.7] Add Model to sync & syncWithoutDetaching docblocks

### PR DESCRIPTION
**Pull request by mbabker**
Both methods internally use the `parseIds` method which, unless extended by a model, handles a `Model`.  Since these methods list out all of the supported argument types, list this alternative as well.

### CODE REVIEW

**Comment by antonkomarev** [comment]
`Model` isn't fully qualified :\

**Comment by mbabker** [comment]
The class is imported in the file already, hence I didn't use the FQCN (TBH I don't know what the Laravel convention is around that so if I'm wrong on that my apologies).

**Comment by antonkomarev** [comment]
Even imported classes should use the FQCN. For example `\Illuminate\Database\Eloquent\Collection` is imported too. In this case line will be way too long >_<

**Comment by antonkomarev** [comment]
Do we really need to specify `\Illuminate\Database\Eloquent\Collection` class in those docblocks since it's just a subclass of `\Illuminate\Support\Collection`?

**Comment by antonkomarev** [comment]
I've done changes described above in PR #26639

**Pull request merged**
