### PR TITLE
Change markdown button plain text view in emails

### PR DESCRIPTION
**Pull request by ghost**
Now the button in plain text markdown emails looks like that:

```
[Confirm or reject supplier](https://www.emaple.com/admin/suppliers/25)
```

Nobody writes that! It's automatic translation from links in running text. Here we have the whole paragraph for one link, I suggest it should look more human-readable:

```
Confirm or reject supplier:
https://www.emaple.com/admin/suppliers/25
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why not just put them on the same line?

**Comment by danilcha** [comment]
Possible, but usually those urls are long and it will anyway occupy a couple of lines. Seems prettier to me like that. Also like that the label looks a bit like a caption.

Compare:
```
Confirm or reject supplier:
https://www.emaple.com/admin/suppliers/25/7827365453713457239845230458729034587
```

And
```
Confirm or reject supplier: https://www.emaple.com/admin/suppliers/25/7827365453713457239845230458729034587
```

**Comment by GrahamCampbell** [comment]
Looks better on the same line.

**Comment by taylorotwell** [comment]
If you want to put them on the same line you can re-submit. Thanks.

**Pull request closed without merging**
