### PR TITLE
Type-hinting fix in PasswordBroker

### PR DESCRIPTION
**Pull request by shehi**
Just a small type-hinting related fix to make the code more readable.

### CODE REVIEW

**Comment by shehi** [comment]
I also fixed AuthPasswordBrokerTest for wrong mock-object. ```\Illuminate\Mail\Message``` type has been provided to mocker.

**Comment by GrahamCampbell** [comment]
There is no reason to force the `Illuminate\Mail\Message` typehint on people.

**Comment by shehi** [comment]
@GrahamCampbell , can it receive any other type of object?

**Comment by shehi** [comment]
@GrahamCampbell , could you please be so kind to answer my question? I know you guys are busy, but I'd like to know the answer in order not to miss anything.

**Pull request closed without merging**
