### PR TITLE
[5.2] Return Changes in Illuminate\Htttp\Request

### PR DESCRIPTION
**Pull request by ConnorVG**
I was wondering... Are they like this on purpose? If so, could you please share why? I'm interested.

Cheers,

### CODE REVIEW

**Comment by lagbox** [comment]
@ConnorVG been a long time.

**Comment by ConnorVG** [comment]
@lagbox holy crap it has - miss you fam.

**Comment by lagbox** [comment]
@ConnorVG we all miss you too

but about your question, I am not sure actually, as your change is what I would do.

**Comment by GrahamCampbell** [comment]
Sorry, but we don't accept changes like this. Both this code, and the reverse PR are valid, and we have no reason to accept one over the other. I understand Taylor prefers the current style for readability too.

**Comment by lagbox** [comment]
Makes sense, its a style thing ... question => answered :)

**Comment by ConnorVG** [comment]
@GrahamCampbell I only posted it to find out why, like I mentioned.

Cheers for the answer mate!

**Comment by GrahamCampbell** [comment]
No problem. ;)

**Pull request closed without merging**
