### PR TITLE
[5.3] Fix authentication responses for session-less requests

### PR DESCRIPTION
**Pull request by rkgrep**
See https://github.com/laravel/framework/commit/9e68e91cef5df661cd64217c9242cea998a66883#commitcomment-18256835

### CODE REVIEW

**Comment by taylorotwell** [comment]
The built-in auth stuff assumes you are using sessions. If you want to change that override the methods. I really don't want the auth stuff to devolve into the uber-customizable mess it was in 5.2.

**Comment by rkgrep** [comment]
It is not uber-customizable 😄 but at least it worked for most of general cases. But now it is restricted to session case only, which is quite silly, considering there are still methods for request/response handling which allow very flexible ways to work with APIs

**Comment by taylorotwell** [comment]
I guess I don’t follow why you need login / logout for APIs? Aren’t APIs token based and therefore have no concept of logging in and logging out?

**Comment by rkgrep** [comment]
You need to get the token somehow - that's why login is needed

**Comment by taylorotwell** [comment]
I wouldn't try to re-use the built-in auth stuff for this honestly. That is trying to use it for things it wasn't intended for.

**Pull request closed without merging**
