### PR TITLE
[10.x] Ensuring Primary Reference on Retry in `createOrFirst()`

### PR DESCRIPTION
**Pull request by mpyw**
# Summary

This PR refines the `createOrFirst()` method to guarantee referencing the primary database when re-attempting record retrieval after a `UniqueConstraintViolationException`.

# Details:

- #47973
  - #48144

The existing `createOrFirst()` method, when facing a unique constraint violation, retries by fetching the matching record. However, in environments with replication, there's no assurance that the newly created record is immediately available on replicas due to possible replication lags.

To address this:

```php
public function createOrFirst(array $attributes = [], array $values = [])
{
    try {
        return $this->getQuery()->withSavepointIfNeeded(fn () => $this->create(array_merge($attributes, $values)));
    } catch (UniqueConstraintViolationException $exception) {
        return $this->useWritePdo()->where($attributes)->first();
    }
}
```

With this change, in case of a retry, the method explicitly references the primary database using `useWritePdo()`, ensuring immediate and accurate record retrieval without being affected by replication delays.

### CODE REVIEW

**Comment by mpyw** [comment]
We need to fix unit tests with Mockery. Okay

**Comment by taylorotwell** [comment]
Why did you only update one of the `createOrFirst` methods?

**Comment by mpyw** [comment]
@taylorotwell Are you suggesting that the same changes should be extended not only to `createOrFirst` but also to `firstOrCreate` and `updateOrCreate`? If that's the case, you should note that by modifying the behavior of `createOrFirst`, it inherently applies the changes to both `firstOrCreate` and `updateOrCreate` (#48160) since they internally utilize `createOrFirst`.

For these methods, the expected flow is:

1. Retrieve from the replica connection. If successful, end.
2. If no record is found, attempt to create on the primary connection. If successful, end.
3. If there's a unique constraint error, retrieve from the primary connection.
4. (Only for `updateOrCreate`) Update on the primary connection.

The only part where we explicitly need to specify `useWritePdo()` is in the 3rd step; which is the part of `createOrFirst()`.

**Comment by mpyw** [comment]
Oops, sorry. I've just noticed that there are more `createOrFirst` methods. I'll check it out, thanks

**Comment by tonysm** [comment]
@mpyw doesn't Eloquent automatically switches to the write instances after a write attempt (`INSERT` or `UPDATE`)? I thought about that in the original PR but I thought it was the case.

The docs say that the [`sticky` option](https://laravel.com/docs/database#the-sticky-option) can be used to control that and the example for using read/write replicas has it set to `true`, so I assumed that was the "default" behavior:

> The sticky option is an optional value that can be used to allow the immediate reading of records that have been written to the database during the current request cycle. If the sticky option is enabled and a "write" operation has been performed against the database during the current request cycle, any further "read" operations will use the "write" connection. This ensures that any data written during the request cycle can be immediately read back from the database during that same request. It is up to you to decide if this is the desired behavior for your application.

**Comment by mpyw** [comment]
@tonysm I am aware of this feature, but I believe the read connection actually switches to the primary only after a successful write attempt.

https://github.com/laravel/framework/blob/3365194f659e9d17083fa715e09db65b6154c18f/src/Illuminate/Database/Connection.php#L560-L613

According to this, `statement` pre-emptively calls `recordsHaveBeenModified`, whereas the actual **`affectingStatement`** used by `create` calls it **post-execution**. This indicates that **`recordsHaveBeenModified` is not called when an exception is thrown in `execute`**. Therefore, after catching an exception and correcting the primary reference, this mechanism does not work, and we need to explicitly apply `useWritePdo` in our code.

**Pull request merged**
