### PR TITLE
[5.8] Collection firstOrFail

### PR DESCRIPTION
**Pull request by dmitryuk**
PR introduces new FirstOrFail method in Collections like Query Builder one.
+ StyleCi refactor

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please revert all the code style changes.

**Comment by dmitryuk** [comment]
> Please revert all the code style changes.

I should ignore styleci failed checks?

**Comment by devcircus** [comment]
Of course don't ignore Laravel's styleci, however there are changes that were made that were not suggested by styleci, like reordering imports. Laravel orders these by length.

**Comment by devcircus** [comment]
Also laravel uses ```new Collection``` not ```new Collection()```

**Comment by mfn** [comment]
Regarding the many StyleCI commits => if StyleCI fails you can click on the red icon and download the diff there for all suggested changes.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
