### PR TITLE
[5.2] Prefer dist installs instead of clones

### PR DESCRIPTION
**Pull request by barryvdh**
Alternative to #12698, without the caching.
Using dist should speed up builds.

### CODE REVIEW

**Comment by lucasmichot** [comment]
But in this case a Github token should be set in Travis environment variables
https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens

**Comment by barryvdh** [comment]
API limits are removed, see https://github.com/composer/composer/issues/4884#issuecomment-195229989

**Comment by lucasmichot** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
:+1:

**Pull request merged**
