### PR TITLE
[5.5] Add a simple transformer

### PR DESCRIPTION
**Pull request by crynobone**
Moved from #14339 since 5.3 is almost ready for release.

---

Would be useful to support simple transformer without requiring full-blown thephpleague/fractal. The idea is to provide basic transformer so we can have standard output when transforming single
model or a collection.

This is essentially useful for API response development since whenever we add new fields to say a Model, our API would then automatically has access to this information. It would be nice to have an explicit transformer to format the output.

Got this idea based on #14333

Signed-off-by: crynobone crynobone@gmail.com

### CODE REVIEW

**Comment by fernandobandeira** [comment]
I also like the idea of having the abstract class suggested in your previous PR, however i think that it should handle relations, maybe something like the include's from the fractal package, (or something similar).

IMO if we are adding that class it should at least properly handle the transforms of the relationships.

**Comment by crynobone** [comment]
I have already using thia style on my project and loving it. Some might argue that it's similar to many presenter packages but the things with presenter is that you only have one "transformer" per model. However with this you can have different transformer for e.g v1 and v2 api.

**Comment by themsaid** [comment]
I use [this package I built](https://github.com/themsaid/laravel-model-transformer) almost a year ago, it uses an abstract transformer class, within the Model Transformer class I can pass options that customizes the output instead of having multiple transformers per entity.

The thing I like about this package too is having these two functions:

`isRelationshipLoaded()` which tells if a specific reltionship is eagerly loaded so that I can display it within the transformed object.

`isLoadedFromPivotTable()` which tells if the model is being loaded from a pivot table so that I can prepend the pivot data and transform it if I need.

Having something like that in laravel would be great, although people are used to external packages that provide the same functionality + more, but having just a simple transformer with these 2 helpers would save 1 more `composer require`.

**Comment by taylorotwell** [comment]
Using this example, how do you define multiple transformers per model?

**Comment by crynobone** [comment]
For my use case I can either have separate route for different API version, or using IoC to resolve which namespace I could fetch the transformer from.


https://twitter.com/crynobone/status/757747712594808832

**Comment by theofidry** [comment]
@crynobone why not using a listener with a generic serializer like we do in [api-platform/core](https://github.com/api-platform/core) and [EloquentSerializer](https://github.com/theofidry/EloquentSerializer) instead?  Sure it requires another package, but it provides a solution working with most of the use cases (i.e. no longer require any transformer) and doesn't require anything to be added to the core.

**Comment by taylorotwell** [comment]
I guess maybe I'm confused as to how this is used. If I have a collection of Users I want to return from an API how do I use this? Maybe I need a bigger code sample?

**Comment by crynobone** [comment]
> Sure it requires another package, but it provides a generic solution working with most of the use cases

Use case to transform `Carbon` to datetime, hiding `Model::$hidden` attributes or does it handle more than that. Sorry I don't have experience using it and commenting purely on the code example. 

For me, the problem with that is that you either have configure `Model::$hidden`, or use `$model->setAccessible()` to filter the output. Let so example you integrate `laravel/cashier` to your project. So you would have `stripe_id`, `card_brand`, `card_last_four` set under `Model::$hidden`, which is valid. What what if you need to prepare API endpoint for billing info. 

```php
use App\User;

class UserProfile {
    public function __invoke(User $user) {
        return [
            'fullname' => $user->firstname . ' ' $user->lastname,
            'email' => $user->email,
        ];
    }
}
````

```php
use App\User;

class UserBilling {
    public function __invoke(User $user) {
        return [
            'stripe_id' => $user->stripe_id,
            'card_brand' => $user->card_brand,
            'card_last_four' => $user->card_last_four,
        ];
    }
}
````

```php
Route::get('users', function () {
    return User::all()->transform(new UserProfile());
});

Route::get('users/{user}', function (User $user) {
    return $user->transform(new UserProfile());
});

Route::get('users/{user}/billing', function (User $user) {
    return $user->transform(new UserBilling());
});
```

**Comment by crynobone** [comment]
Since the PR for Paginator::transform() was rejected, returning is slightly different.

```php
Route::get('users', function () {
    $users = User::paginate()

    $user->getCollection()->transform(new UserProfile());

    return $users;
});
```

**Comment by crynobone** [comment]
In regards to versioning API, my main objective is that once I come out with v1 API, we have a standard transformer given consistent output all the time. Let say given the `User` example, many example would just `return $user->toArray();`. This would be bad if for any reason we change field name from `users.email` to `users.email_address`. Now, any API that was returning `email` would suddenly return `email_address`. 

Related to my use case, I have a public API that I have release and our iOS and Android developer would depends on when building the app. Given that I have the above `UserProfile`, if at any point of time I would need to change the schema from `email` to `email_address`, I would simply need to update the transformer to 

```php
class UserProfile {
    public function __invoke(User $user) {
        return [
            'fullname' => $user->firstname . ' ' $user->lastname,
            'email' => $user->email_address,
        ];
    }
}
```

With this simple change, I prevent any breaking changes on my API, until for example I release v2 of the API.

**Comment by theofidry** [comment]
>Use case to transform Carbon to datetime, hiding Model::$hidden attributes or does it handle more than that? Sorry I don't have experience using it and commenting purely on the code example.

Yep it does.

>What if you need to prepare API endpoint for billing info, you then have to use $model->setAccessible(), and this become hard to maintain when you carry on your project.

In case it wasn't obvious I was referring to the [Symfony Serializer](http://symfony.com/doc/current/components/serializer.html). The integration to Laravel is fairly easy and it supports some feature you are looking for like [groups](http://symfony.com/blog/new-in-symfony-2-7-serialization-groups) which offer more flexibility than `$hidden`.

**Comment by fernandobandeira** [comment]
Well this proposal seems halted, indeed there's many packages out there that can provide similar functionality (this is a pretty simple concept after all), however having a default one that provides some built in hooks with Eloquent would be a god's blessing, like the ones mentioned by @themsaid  for example ``` isRelationshipLoaded() ```, ``` isLoadedFromPivotTable() ``` and many more would already be a good reason for having this in core. 

Currenty this PR doesn't have these hooks but it will open the doors for such new functionalities.

**Comment by anderly** [comment]
What about something like this: http://anderly.com/2016/09/08/laravel-transformable-a-model-trait-for-consumable-models/

**Comment by crynobone** [comment]
@anderly

* The options only simple single transformer per model. (see https://github.com/laravel/framework/pull/14357#issuecomment-237132806)
* You can only set output to JSON, while with exporting to array, you can now have to converted to JSON, CSV, XML, etc.
* Loading relations seem to be manual/not supported. (https://github.com/laravel/framework/pull/14357#issuecomment-234315471)

**Comment by anderly** [comment]
@crynobone

Yes, the default would be a single transformer per model using the `Transformable` trait.

To create multiple transformers, I would leave my main User model in `App\Models` and it would import and `use Transformable`. Then maybe under `App\Models\Transformers`, I could subclass `User` and define `UserProfile` and `UserBilling` which can override the $transformation_map property.

You can define relations just like you would on eloquent models and they'll respect the transformable attribute names.

Just a thought. Plus, consumers can instantiate the models using the transformed attribute names without knowledge of the underlying db schema names.

I'm working on support for `where*` methods so you can also query based on a transformed attribute name without knowledge of the schema names.

Just a different approach was curious to get some feedback.

**Comment by crynobone** [comment]
> To create multiple transformers, I would leave my main User model

This is where I wouldn't agree on this structure, having many duplicate models is far worst that having many transformers, but the responsibility of a transformer class is small, which you're duplicating the responsibility of many models, that not a good way to do it.

Let's say you do this for `v1` of your API, what happen when you need to make `v2`, more duplicates? `v3`?

**Comment by anderly** [comment]
Wouldn't you run into the same issue with versioning with your transformer classes? You'd need to be backward-compatible or version the transformer classes (i.e. create new ones for breaking changes).

Instead of sub-classing the Eloquent model, I could achieve a similar approach to yours by just accepting the underlying model as an argument or injecting it via the constructor. I just didn't like all the calls to `$user->transform(new UserProfile())` or '$user->transform(new UserBilling())`. I'd rather just call the transformer class directly. Thoughts?

**Comment by crynobone** [comment]
> Wouldn't you run into the same issue with versioning with your transformer classes? You'd need to be backward-compatible or version the transformer classes (i.e. create new ones for breaking changes).

There's many ways to handle it, which is why if you looks at the file changes for this approach is minimal (so there no restriction on how you want, or can handle it, on one of my current project I'm using https://github.com/orchestral/lumen/blob/3.3/src/Routing/Helpers.php, since I backporting fractal transformation to this simple structure.

For other purpose, you can have something similar to:

```php
<?php 

class UserTransformer 
{
    protected $version = 'v1';

    protected $supportedVersion = [
        'v1' => 'handleOne',
        'v2' => 'handleTwo',
    ];

    public function __construct($version) {
        $this->version = $version;
    }

    public function __invoke(...$parameters)
    {
        $method = $this->supportedVersion[$this->version];

        return $this->{$method}(...$parameters);
    }

    public function handleOne(User $user) 
    {
        return [
            'email' => $user->email,
            'fullname' => $user->firstname.' '.$user->lastname,
            'prjects' => $user->projects->transform(new ProjectTransformer());
        ];
    }

    public function handleTwo(User $user) 
    {
        return [
            'email_address' => $user->email,
            'fullname' => $user->fullname,
            'projects' => $user->projects->transform(new ProjectTransformer());
        ];
    }
}
```

Again, this is one of endless possibility that you can do with it, and that the reason why I would prefer `$user->transform(new UserTransformer());`, so this would also be possible `$user->transformer(app('user.transformer')`, or even `$user->transform(new UserTransformer($request->input('version'));` etc.

**Comment by anderly** [comment]
I like your versioned approach above. Just curious, how do you handle instantiation and persistence of the transformed model? For instance, I wanted to be able to instantiate and persist the model using the transformed attributes (the contract) just like I use the transformed attributes on the consumption side. Do you use your transformer class for that as well?

**Comment by taylorotwell** [comment]
I think the idea behind this feature is good but want to think about the implementation more.

**Comment by taylorotwell** [comment]
Leaving this open actually so I can review further since it's pretty simple.

**Comment by arjasco** [comment]
I've used league fractal and not really liked it. 

I've done something like this in the past

```php
<?php

class User extends Authenticatable implements Transformable
{

    public function transform()
    {
        return [
            'full_name' => $this->first_name . ' ' . $this->last_name,
            'email' => $this->email,
            'creation_time' => $this->created_at->timestamp
        ];
    }
}

```

```php
User::find(1)->transform()
```

If I have a collection of models then..

```php
$data = $collection->map(function ($model) {
    return $model->transform();
});

return response()->json($data);

```

A bit like the `getModelKeys` method on eloquent collections, there could be a shorter way to transform your model data with maybe.

I see the benefit of really simple way to define these structures that doesn't mean including another dependancy to try and help..

**Comment by taylorotwell** [comment]
Is the main reason this uses Fluent just to take advantage of the Jsonable implementation of it?

**Comment by crynobone** [comment]
Both Jsonable and Arrayable implementation.

**Comment by jodiedunlop** [comment]
I've built quite a few API's using fractal, and admittedly it is kinda clunky so it would be nice to have something a little more built-in. 

I think the following are necessary for an implementation:

- Multiple transformers per model: I need to represent my User model in different ways depending on the API call / resource
- Ability to selectively include relationships - I do not want my User "photos" collection to be included in a GET /users request, but I would like them present in a `/users/1234`  single resource request
- Make it simple to have a default transformer - if i can just call `$user->transform()` for most cases that would be nice, and `$user->transform(UserSnippetTransformer::class)`, for other cases
- Some convenience functionality for pagination (embed paging data in output, get paging from input)  `$collection->transformWithPagination()` etc.

**Comment by flugger** [comment]
I created a package for handling this, might bring some ideas to the table if this feature ends up being added to the framework: https://github.com/flugger/laravel-responder

**Comment by CurosMJ** [comment]
I have implemented a transformer based structure in a Lumen based project of mine. The structure is pretty basic and consists of :

```php

interface Transformable
{
    // This interface is implemented by all models

    // Return the name of the transformer for this model. For 'User', it would be 'UserTransformer'
    static public function transformerName();

    // Return the transformed model
    public function transform();
}

trait Transforms {
    // This trait is implemented by the models which want to utilize the default mechanism

    static public function transformerName() { 
        /* Return the default transformer name, i.e, UserTransformer for User*/
    }

    public function transform()
    {
        return app(self::transformerName())->transform();
    }
}

abstract class TransformerContract {
    // This is extended by all the Transformer classes.

    // Transform the model into an associative array
    public function transform(Transformable $model);
}
```

And then I overrided the Response class to use the Transformer's transform method, if the passed variable was an instance of `Transformable`.

Now, I have also seen some pitfalls to be considered with this approach : 
- Recursion : if by mistake someone tries to transform a model within its own transformer, bad things happen. 
- Common Properties : we need to keep some mechanism, so that a few attributes can go straight away into the transformed array without the need to write code for them. For example, id, created_at and updated_at.
- Performance : If the users are  allowed to do serialization themselves, they might add too much code in the `transform` method. And especially when transforming a set of models, this situation gets worse.

**Comment by CurosMJ** [comment]
If we use [Fractal](http://fractal.thephpleague.com/), it can serve our purpose, but, adding Laravel specific abstract classes above it will also help, so that we can leverage the IoC container properly.

This could be a big addition to Lumen, more than Laravel.

**Comment by robclancy** [comment]
We found Fractal horribly coded and just a pain to use causing more issues than anything. And very tedious to use it. So we wrote a trait to extend eloquent with transformer like properties along with eloquents built in transforming and it has worked far better than multiple methods we tried in the past by using a fluent API. Needs more work to be able to release (and renaming some things). Hopefully we will have time oneday to release.
eg.
```php
return $contentRequest->includeRelation(['type', 'user'])->append('dragons');
```
It also does the same nesting as eloquent does when using `with`. So if you had comments and wanted users with them when transformed you would do:
```php
$contentRequest->includeRelation('comments.user')`
```

On top of that this is done using the `toArray` so each model goes through it's own transformations when nesting. The models also set default includes and permissions so that there is a "normal" response but we can easily change the responses based on the users permissions etc. We also add in policies if specified `$contentRequest->includePermission('delete')` will add `canDelete` to the response by checking the `delete` policy action of `$contentRequest`.

Not really much to add to this proposal since it would need to work well without Eloquent to be in core I imagine but basically saying YES PLEASE.

**Comment by jaketoolson** [comment]
@robclancy using Fractal increased our benchmark response times so dramatically, we had to stop using it.  And we weren't doing anything extraordinary -- pretty much out of the box usage!

**Comment by crynobone** [comment]
@GrahamCampbell push to 5.5? this PR was made just right after 5.4 was released.

**Comment by GrahamCampbell** [comment]
It may go to 5.4. Just leaving on 5.5 for now. I don't know the exact plans for this.

**Comment by crynobone** [comment]
Then don't change it,!

**Comment by GrahamCampbell** [comment]
I didn't change it. The target as remained as master. The master has just become 5.5 now. It would have been a change to retarget this at 5.4.

**Comment by crynobone** [comment]
You could wait and ask me to rebase this, the new branch was only available 6-8 hours ago while I was still sleeping.

**Comment by GrahamCampbell** [comment]
Nothing to rebase. We can switch this from 5.4 to master and back as much as we want, without issue.

**Comment by GrahamCampbell** [comment]
If you do want to rebase this, best to rebase on 5.4, not master, then it can be merged into either.

**Comment by crynobone** [comment]
It is already retargetting `5.4`, you should know GitHub already provide the ability to retargetting branch from UI.

**Comment by GrahamCampbell** [comment]
> you should know GitHub already provide the ability to retargetting branch from UI.

yes, i know, but i left it on 5.5 on purpose

**Comment by lucasmichot** [comment]
What are the reasons why it's not merged in `5.4` ?
I feel this PR from @crynobone would be pretty useful

**Comment by MrMashy** [comment]
I hope this is going into 5.4

**Comment by lucasmichot** [comment]
Any chance to get this PR re-opened and merged in `5.4` ?
cc @taylorotwell / @crynobone 

It would be a **REALLY** pity that the community cannot get it

**Comment by crynobone** [comment]
@lucasmichot I have no interest to pursue this anymore, and in fact have handle it own my own for my project. Up to you if you want to PR it, don't really care.

**Comment by lucasmichot** [comment]
See https://github.com/laravel/framework/pull/17363

**Pull request closed without merging**
