### PR TITLE
[5.1] Change order calling touchIfTouching method

### PR DESCRIPTION
**Pull request by valeryq**
We need to do touching model after detach (delete) rows. That similary an attach method.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Could you explain why we'd want that please? I think this was intentionally done this way around.

**Comment by valeryq** [comment]
@GrahamCampbell it's logically correct, that at first we execute action (insert or delete row) and after that we need to do touching the parent model. But now, its touching before.

See method attach in this file, there it's correctly. And you can see comment in detach:
```php
// Once we have all of the conditions set on the statement, we are ready
// to run the delete on the pivot table. Then, if the touch parameter
// is true, we will go ahead and touch all related models to sync.
$results = $query->delete();
```

**Comment by GrahamCampbell** [comment]
The reason we normally do deletes after other stuff is incase someone wants to read the thing we're going to delete.

**Comment by valeryq** [comment]
@GrahamCampbell touchIfTouch() doesn't relate with deleting entity. It just update the timestamps. But if we want to get updated state of the related entities after deleting, we can't do it (on touch - the only and simplest way we could).

**Comment by GrahamCampbell** [comment]
delete, modify, same issue, if you see what i mean

**Comment by valeryq** [comment]
@GrahamCampbell I expect updated state of parent model (if I need touching) after execute action, but not before that.

In comment wrote: "Once we have all of the conditions set on the statement, we are ready  to run the delete on the pivot table. Then, if the touch parameter is true, we will go ahead and touch all related models to sync.". Please, read comment. "we will go ahead and touch all related models to sync" - but now it works incorrectly, touching related models do before delete.

**Comment by valeryq** [comment]
@GrahamCampbell and you can see on the method "sync", touchIfTouching() located at the end.

**Comment by valeryq** [comment]
In analogy to RDBMS trigger functions: there is no need to trigger the action before action itself. IMHO touchIfTouching() method is a kind of trigger function.

**Comment by GrahamCampbell** [comment]
I'm not trying to pointlessly oppose changes, but there has to be a good reason to change something that already works fine. I think it makes the most sense as is.

**Comment by GrahamCampbell** [comment]
We need to be super careful not to break things. Community contributions to the database component don't have a good history I'm afraid.

The fact that the tests didn't fail means that this are isn't so well tested.

**Comment by valeryq** [comment]
For example:

User.php
```php
class User extends Model
{
   public function roles()
   {
       return $this->belongsToMany(Role::class, 'user_roles');
   }
}
```

Role.php
```php
class Role extends Model
{
       /**
     * The relationships that should be touched on save.
     *
     * @var array
     */
    protected $touches = [
        'clients'
    ];

    /**
     * List of users by role
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function users()
    {
        return $this->belongsToMany(User::class, 'user_roles');
    }
}
```

When I do User::find(1)->roles()->attach(1); -- it was correctly, it was good, but if I do
User::find(1)->roles()->detach(1); -- it was incorrect.

I override the method touch in User.php
```php
public function touch()
{
    $this->fireModelEvent('saved', false);
}
```

And I need the fire event after delete row, but now it works before.

Maybe someone else answer to my question???

**Comment by ypppa** [comment]
What about this pull request? Can anyone give the answer?

**Comment by taylorotwell** [comment]
I understand what he means. It makes decent sense. On the `saved` event that is would be fired on the parent models when touching, he would still be getting the "detaching" models if he accesses the relation, when really you would probably expect them to already be detached.

**Comment by ypppa** [comment]
Thanks a lot!

**Comment by valeryq** [comment]
Thanks!

**Pull request merged**
