### PR TITLE
[5.4] Add a simple transformer

### PR DESCRIPTION
**Pull request by lucasmichot**
Add a simple transformer.
Re-open #14357

---

See #14333 & #14339
Could not get the original commits that are based on the work of @crynobone & @jansenfelipe

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Probably best for you to still "author" the commit as @crynobone. Please update the PR.

**Comment by lucasmichot** [comment]
Added login in in commit message - see https://github.com/laravel/framework/pull/17363/commits/81117d3452dfd11a6ed7dba3501be4ff9d4144a8

**Comment by crynobone** [comment]
I honestly don't really care who's the author of the commit.

**Comment by GrahamCampbell** [comment]
It's possible to author a commit as someone, nothing to do with putting their name in the commit.

**Comment by lucasmichot** [comment]
Done https://github.com/laravel/framework/pull/17363/commits/dc8514e51f57c0b212d15a85a26ec8dd55888113

**Comment by lucasmichot** [comment]
Well sorry guys, but in fact I really don't like this; this makes me quite uncomfortable
I cannot imagine anyone on this project would kind of "imitate" my commits - so I won't do the same with @crynobone

**Comment by atehnix** [comment]
:man_facepalming: 
Just merge it finally...

**Comment by crynobone** [comment]
Good to see Graham manage to close another PR via non-trivia arguments.

I clearly said do whatever you want with the code, it not like I have any interest on bragging about it.

**Comment by jaketoolson** [comment]
@crynobone I feel ya.  Graham is a tool.

**Comment by kamui545** [comment]
Can we stop the drama/bashing here?

The PR is pretty simple and yet powerful, it would be a shame not to be merged in 5.4...

**Comment by karmendra** [comment]
Can this be made a laravel package that I can just require in my project and use it?

It is definitely a thing laravel should have in its core.

**Pull request closed without merging**
