### PR TITLE
[5.1] Release method for Illuminate\Queue\Jobs\SqsJob

### PR DESCRIPTION
**Pull request by clslrns**
This is my third try, sorry for annoyance. Original issue: #5373, previous PRs: #7113, #7114.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks.

**Comment by taylorotwell** [comment]
Have you tested this in a real app to confirm it works?

**Comment by clslrns** [comment]
Yes, sure. It has been working in production for 6 months. But it's Laravel 4.2. Give me a few hours, I gotta test it along with current `master`.

**Comment by clslrns** [comment]
Now 100% sure.

**Pull request merged**
