### PR TITLE
[5.0] Route prefixing not working in some cases

### PR DESCRIPTION
**Pull request by litvinchuk**
Route '/' does not work after using `$route->prefix('someprefix');`

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can't recreate issue.

**Comment by litvinchuk** [comment]
@taylorotwell, Issue reproduced in tests, add prefix directly and not by grouping

**Comment by taylorotwell** [comment]
Can you send it to 5.1 branch?

**Comment by litvinchuk** [comment]
@taylorotwell , of course.

**Pull request closed without merging**
