### PR TITLE
[5.7] Fix distinct pagination on the Eloquent query builder

### PR DESCRIPTION
**Pull request by stayallive**
When doing a `distinct` query I tried to make the paginator also use a distinct query. The only way to do this seems to be to pass the columns to the paginator so it in turn should build a correct count query.

```php
$query->paginate(10, ['table.id']);
```

However it seems that the columns are never passed to the `getCountForPagination` in the Eloquent builder. It does in the "regular" query Builder. This corrects that.

This seems to be the way since the initial refactor 2 years ago and thus possible longer, maybe this should also be backported to earlier version.

----

Edit: I missed the `EloquentPaginateTest`, seeing that now I can see why this is done. However this means a paginate on a distinct query will not work when using the Eloquent builder. 

Possibly passing the model's primary key as a distinction column is the way to go... however I'm not too sure about it... it works for my use case but not sure if correct and/or covers most cases.

(also the test is not how you would use this but I tried to keep the query and test to a minimum to prevent overcomplicated queries clouding the purpose of the test)

----

Edit 2: This is discussed already a few times but never fixed: #21242 (PR's: #21891 #21899)

I hope this can be reconsidered for 5.7 or possibly 5.8 since pagination is just plain broken when using a distinct.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can you explain why this attempt works where all others failed?

**Comment by taylorotwell** [comment]
I don't think I'm going to change this now until you feel more confident about it. It has been something that breaks applications repeatedly.

**Comment by deleugpn** [comment]
Good idea on distinct taking a column (or array of columns). It would solve the issue without breaking anything. Though it would need to target 5.8.
Are you planning on sending a PR for this?

**Comment by stayallive** [comment]
@deleugpn if you have the time and want to make the PR yourself that would be very nice. I don't think I'll have the time in the coming days 👍 happy to look over it ofcourse FWIW.

**Pull request closed without merging**
