### PR TITLE
[5.7] Add Log::fake()

### PR DESCRIPTION
**Pull request by timacdonald**
This PR introduces the ability to fake the logger, like you can with many other services during testing. There are a couple of instances where faking the logger can come in handy. I wanted to ensure that certain logging was happening in the Exception handler, depending on certain criteria in my tests. This fake helped me make that happen.

It takes into account the new logging system introduced in 5.6. I think the implementation (shown in the examples) is the way to go, but I'd say I'm a lightweight logger user, so feedback and criticisms to improve this is appreciated.

### Basic example

```php
Log::fake();

Log::alert('Donuts have arrived');

Log::assertLogged('alert', function ($message, $context) {
    return str_contains($message, 'Donuts');
});
```

### Channels and stacks

My thinking with channels and stacks is that keeping them separated and checking them the way they are called on the facade makes for a more consistent experience, instead of passing through a string or stack array as another argument to the assert methods.

#### Channel example

```php
Log::fake();

Log::channel('slack')->alert('Donuts have arrived');

Log::assertLogged('alert');  ❌ FAILS
Log::channel('slack')->assertLogged('alert');  ✅ PASSES
```

#### Stack example

```php
Log::fake();

Log::stack(['bugsnag', 'sentry'])->alert('Donuts have arrived');

Log::assertLogged('alert'); ❌ FAILS
Log::stack(['bugsnag', 'sentry'])->assertLogged('alert');  ✅ PASSES
Log::stack(['sentry', 'bugsnag'])->assertLogged('alert');  ✅ PASSES
```

I put this up on `laravel/ideas` a while ago and it seems there are a _few_ people out there that might benefit from this: https://github.com/laravel/ideas/issues/1084

### CODE REVIEW

**Review by phroggyy — COMMENTED** [review]
I like the overall idea, although I'm wondering if we really need to make the `LogFake` have its own store of logs? I'd probably prefer to proxy it to the default channel since that's what the `LogManager` does, so proxy the calls to a channel fake that's the default driver, just to clean up the code.

I'm also not entirely certain about the value of it – on the one hand it's nice being able to assert that messages have been recorded; on the other, log messages are fundamentally a developer tool rather than a business feature. Thus, if a log message is so important that you need a test to check that it happens, I wouldn't use logs for that purpose. I further don't really see much value in being able to assert that nothing was logged; to me that's not a scenario you want to be in (if you care enough about logs to test for them, you won't want to make sure they're _not_ present).

**Comment by timacdonald** [comment]
Thanks heaps for taking the time to look over this!

I totally agree asserting nothing was logged doesn’t have any value.

So for real world example of when I actually used this kind of thing in a project: we started tracking, via Bugsnag, API throttle exceptions. Under the exception handler hood, Laravel makes these not be reported, so I wrote a test to make sure that, when hitting the API limit, the exception was using the logger to hit bugsnag, and then made the required adjustments needed to ensure the exceptions were reported in the handler.

But definately not something I’ve needed to do since, but when I did it was handy.

**Comment by timacdonald** [comment]
No worries Taylor, thanks for checking it out

**Comment by timacdonald** [comment]
For those wanting this, I’ll throw it in a package and you can still use it in your tests. Will post here when it is ready.

**Comment by timacdonald** [comment]
Here is the packaged version for anyone interested in this: https://github.com/timacdonald/log-fake

**Comment by Hatsunyan** [comment]
You can use MessageLogged event
```php
\Event::fake();
\Event::assertDispatched(MessageLogged::class, function ($e) use ($message) {
    return $e->message === $message
});
```
its help to me, and this dont require package and Log::fake();
@timacdonald

**Comment by AmirrezaNasiri** [comment]
@Hatsunyan Genius, genius everywhere ...

**Pull request closed without merging**
