### PR TITLE
Add the SeeJsonStructureEquals method

### PR DESCRIPTION
**Pull request by mathieutu**
With the actual `SeeJsonStructure`, you can't know if some undesirable fields are returned by the application (some fields which shouldn't be public in particular cases for example). 

With this `SeeJsonStructureEquals` method you can check if a response is *exactly* the type of response that you are expecting. No more, no less.

It's a kind of "_security fence_" for our apis 😉  .

Suggestions and feedbacks are obviously welcomed, I'm open !

### CODE REVIEW

**Comment by mathieutu** [comment]
What's wrong with StyleCI ?
It errored on the PR without explanation : 
screen shot 2016-11-21 at 20 28 02

**Comment by mathieutu** [comment]
Something apparently went wrong with StyleCI..
It errored on the PR but without explanation :

screen shot 2016-11-21 at 20 34 50

I tried to repushed, and it was exactly the same thing.

**Comment by GrahamCampbell** [comment]
Fixed now. Failing due to your code now. :P

**Comment by mathieutu** [comment]
@GrahamCampbell Done, thx ! What was the problem ?
(Anyway it could be interesting to have a tool/conf locally (like [phpcs](https://github.com/squizlabs/PHP_CodeSniffer)) with the constraints, to avoid failing once pushed :slightly_smiling_face: )

**Comment by taylorotwell** [comment]
Going to let additional versions of these helpers be more package based.

**Pull request closed without merging**
