### PR TITLE
[5.3] groupBy() minor changes

### PR DESCRIPTION
**Pull request by KennedyTedesco**
Making `groupBy()` a variadic function, also one more test was added.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Tests are failing.

**Comment by KennedyTedesco** [comment]
Don't know why but seems to be a Mockery bug with Variadic Functions.

image
https://travis-ci.org/laravel/framework/jobs/123722993

```
1) DatabaseEloquentBelongsToManyTest::testModelsAreProperlyHydrated
Declaration of Mockery_38_Illuminate_Database_Query_Builder::groupBy() should be compatible with Illuminate\Database\Query\Builder::groupBy(...$groups)

/home/travis/build/laravel/framework/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php:16
/home/travis/build/laravel/framework/vendor/mockery/mockery/library/Mockery/Container.php:216
/home/travis/build/laravel/framework/vendor/mockery/mockery/library/Mockery.php:74
/home/travis/build/laravel/framework/tests/Database/DatabaseEloquentBelongsToManyTest.php:23
```

I have tested this both on PHP 5.6 and PHP 7.0 on my production app and all worked fine.

If you want to wait Mockery fix this before merging, feel free to close.

**Comment by GrahamCampbell** [comment]
We can just bump the min mockery version.

**Comment by taylorotwell** [comment]
So how do I fix this?

**Comment by GrahamCampbell** [comment]
One sec @taylorotwell.

**Comment by GrahamCampbell** [comment]
Passing now.

**Pull request merged**
