### PR TITLE
tests : various ways to push a job under QueueFake

### PR DESCRIPTION
**Pull request by challet**
Test cases for #21189.
For now two over three are failing, they are the ones using `dispatch(new CallQueuedHandlerTestJob);` and `CallQueuedHandlerTestJob::dispatch();`

```shell
$ vendor/bin/phpunit -vvv tests/Integration/Queue/QueueFakeTest.php
PHPUnit 6.3.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.4
Configuration: /somewhere/laravel-framework/phpunit.xml

F.F                                                                 3 / 3 (100%)

Time: 64 ms, Memory: 6.00MB

There were 2 failures:

1) Illuminate\Tests\Integration\Queue\QueueFakeTest::test_job_through_helper_is_not_fired
The expected [Illuminate\Tests\Integration\Queue\CallQueuedHandlerTestJob] job was not pushed.
Failed asserting that false is true.

/somewhere/laravel-framework/src/Illuminate/Support/Testing/Fakes/QueueFake.php:33
/somewhere/laravel-framework/src/Illuminate/Support/Facades/Facade.php:221
/somewhere/laravel-framework/tests/Integration/Queue/QueueFakeTest.php:27

2) Illuminate\Tests\Integration\Queue\QueueFakeTest::test_job_through_static_is_not_fired
The expected [Illuminate\Tests\Integration\Queue\CallQueuedHandlerTestJob] job was not pushed.
Failed asserting that false is true.

/somewhere/laravel-framework/src/Illuminate/Support/Testing/Fakes/QueueFake.php:33
/somewhere/laravel-framework/src/Illuminate/Support/Facades/Facade.php:221
/somewhere/laravel-framework/tests/Integration/Queue/QueueFakeTest.php:47
```

### CODE REVIEW

**Comment by themsaid** [comment]
These tests are wrong, please try these cases in the context of a laravel application and it'll work, for example:

```
public function testBasicTest()
{
    Queue::fake();

    dispatch(new \App\Jobs\TestJob());

    Queue::assertPushed(TestJob::class);
}
```

Works fine.

**Comment by challet** [comment]
@themsaid I'm sorry but I've dont exactly that and it fails : 

```shell
$ laravel new test
Crafting application...
[...]

$ vendor/bin/phpunit tests
PHPUnit 6.3.0 by Sebastian Bergmann and contributors.

.F                                                                  2 / 2 (100%)

Time: 139 ms, Memory: 10.00MB

There was 1 failure:

1) Tests\Unit\ExampleTest::testBasicTest
The expected [Tests\Unit\TestJob] job was not pushed.
Failed asserting that false is true.

/somewhere/test/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/QueueFake.php:33
/somewhere/test/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
/somewhere/test/tests/Unit/ExampleTest.php:21

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

with : 
```
<?php

namespace Tests\Unit;

use Tests\TestCase;

class ExampleTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        \Queue::fake();

        dispatch(new TestJob());

        \Queue::assertPushed(TestJob::class);
    }
}


class TestJob
{
    public function handle()
    {
    }
}
```

I even have an error if I omit he handle method : `1) Tests\Unit\ExampleTest::testBasicTest
ReflectionException: Method Tests\Unit\TestJob::handle() does not exist`

**Comment by themsaid** [comment]
So this test fails in your application?

```
public function testBasicTest()
{
    Queue::fake();

    dispatch(new \App\Jobs\TestJob());

    Queue::assertPushed(TestJob::class);
}
```

It works fine for me, all green.

**Comment by challet** [comment]
@themsaid Yes, basically it fails, but I found out that it can be changed by adding the `Illuminate\Contracts\Queue\ShouldQueue` interface to the TestJob class, no matter the traits being used or not : Dispatchable, InteractsWithQueue or Queueable.
In the code this condition is tested [here](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Bus/Dispatcher.php#L72).

That leads me to two opposite thoughts : 
* A job that shouldn't be queued is executed immediatly, and then *not pushed in queue*. The test is indeed not the good one : I want to check that it has been dispatched, and I'm actually checking it has been queued.
* From the documentation "The dispatch function pushes a new job onto the Laravel job queue", while it does accept jobs that shouldn't been queued. I would then assume that this job *has been pushed* even if executed immediatly.

In my humble opinion, clarification could be made. For instance, if I understand well, one job without ShouldQueue could be both : 
* not queued but executed, through `dispatch($job)` or `Job::dispatch` (if trait Dispatchable)
* explicitely queued and defered, through `Queue::push($job)`

By adding the synchronous queue driver to the thinking, that gives me a sense of too many ways (each one with its own specifics) to achieve the same goal.

**Pull request closed without merging**
