### PR TITLE
[5.4] Don't reverse the pushed data

### LINKED ISSUE #14876: [5.3] @push order isn't correct
Hi,
The problem is that the pushed content used @push isn't in the correct order.

I have a layouts/html.blade.php

``` blade
<html>
    <head>
        @stack('header-assets')
    </head>

    <body>
        @yield('site')
    </body>
</html>
```

A master.blade.php that extends the html.blade i have the first @push in the following file

``` blade
@extends('layouts.html')

@push('header-assets')
    <link rel="stylesheet" href="{{ url(elixir('css/all.css')) }}">
@endpush


@section('site')
    @include('partials.app._sidebar')
@endsection
```

A partials/app/_sidebar.blade.php, this file contains the second @push

``` blade
@push('header-assets')
    <style>
        .opened_sidebar {
            overflow: visible !important;
        }
    </style>
@endpush
```

When i preview the source code i get 

``` html
     <style>
        .opened_sidebar {
            overflow: visible !important;
        }
    </style>
    <link rel="stylesheet" href="http://fseg.edoc.dev/build/css/all-018dc6ddfb.css">

```

But instead the `<style>` tag should be after the `<link>` tag.

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes #14876

### CODE REVIEW

**Comment by taylorotwell** [comment]
I feel like we must have been doing this for a reason? :smile:

**Comment by jbrooksuk** [comment]
@taylorotwell I originally thought that, but the change that introduced the reversal didn't explicitly state why.

**Comment by taylorotwell** [comment]
Would like to get to the bottom of that if possible.

**Comment by taylorotwell** [comment]
@mark86092 can you let us know why you introduced an array_reverse on the push?

**Comment by jbrooksuk** [comment]
Pinging @mark86092?

**Comment by jbrooksuk** [comment]
Oh, you beat me.

**Comment by mark86092** [comment]
Wait me a moment, I'll reply soon

**Comment by mark86092** [comment]
The reason goes to several statements:

1) Rendering Ordering:

The first is child --> then parent --> then the grand parent blade template

**with `renderCount` increases to identify**

So, the PR #12808 's tests use the `$factory->incrementRender();` in L285, to mimic the `@push` in parent.

2) The Push Content Ordering:

I would expect the `@push` content in parent should appear before child, and the `@push` content in grand parent should appear before parent blade template

## Reason from 1) and 2)

So, I think when render the `$this->pushContentsStack[$section]`, it is better to array_reverse it.

Making the parent's push content (i.e. `$this->pushContentsStack[$section][1]`) appears before the child's push content (i.e. `$this->pushContentsStack[$section][0]`)

**Comment by mark86092** [comment]
During the investigation of the reason, I found that in `BladeCompiler.php`, `compileExtends` and `compileInclude` share almost the same render behaviors. Could it be the reason why array_reverse or not array_reverse ?

**Comment by taylorotwell** [comment]
@jbrooksuk any thoughts on that? :smile:

**Comment by taylorotwell** [comment]
I tend to agree with removing this. It becomes more apparent the behavior is wrong when you use something like the new 5.4 components and slots... your pushes are in reverse order when you dump them in that situation.

**Comment by taylorotwell** [comment]
I think there are situations where the array_reverse behavior makes sense but perhaps it needs to be thought out more. To me `push` should render its contents in the order they were pushed. Otherwise its not a push its just a prepend.

**Comment by jbrooksuk** [comment]
Sorry, @taylorotwell I missed your message. But yeah, slots would make the reverse weirder.

**Comment by rico-ocepek** [comment]
From my point of view the 5.3 order was better (maybe not correct but better).
Just updated to 5.4 and all my javascript inclusions broke due to the child's javascript being rendered before the parent's.
It's probably the correct behavior for something called 'stack' but I really wish for something queue-like now. 

Any ideas how to work arround this?

**Pull request merged**
