### PR TITLE
[5.8] Add foreign to fluent indexes

### PR DESCRIPTION
**Pull request by dmitrybubyakin**
Usually I write something like this in my migrations:

```php
Schema::table('users', function (Blueprint $table) {
    $table->unsignedInteger('group_id')->nullable();
    $table->foreign('group_id')->references('id')->on('groups');
});
```

This PR makes it a bit more simpler:

```php
Schema::table('users', function (Blueprint $table) {
    $table->unsignedInteger('group_id')->nullable()->foreign();
});
```

### CODE REVIEW

**Comment by devcircus** [comment]
This has been pr'd several times. Personally I believe migrations should be explicit as possible. A method like this hides a lot about the details of your db structure.

It's true that shortcut methods exist, but those are for very specific functionalities that laravel offers, like softDeletes. 

This is already designed fluently and is very readable. 

### To me, the best place to build migration shortcuts, is your IDE, via snippets.

But 🤷🏻‍♂️

**Comment by dmitrybubyakin** [comment]
@devcircus Thanks for the explanation.

**Comment by devcircus** [comment]
Hey you may want to keep it open. Sometimes after 4-5 tries, Taylor will decide to merge something. I was just sharing my thoughts. A lot of people would probably end up using this. 😉

**Comment by dwightwatson** [comment]
I get the argument for being explicit, but I have to look up the foreign key syntax every single time I use it. 

I suppose another approach could be` $table->foreign('group_id')` that infers the other arugments unless provided, but is still separated from the column definitions.

**Comment by deleugpn** [comment]
I feel this implementation is less intrusive than the ones proposed before. I have a problem with changing the signature of `$table->foreign()` because it will introduce breaking changes for people that have migration out of the standards. This implementation, however, allows for an optional usage. If you're following the standard database schema, you may opt to use the helper, otherwise you're still free to fallback into the explicit definition.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
