### PR TITLE
[6.x] Add using route name support for redirect after email verification

### PR DESCRIPTION
**Pull request by om3rcitak**
This PR support using route name instead route path for email verification to developers. Now, developers add redirect path hardcoded in to controllers. This way is not make sense. Because route paths is may change but route names is not change. 

I think should be using route name instead route paths.

### CODE REVIEW

**Comment by om3rcitak** [comment]
Btw, I think this changes should be do for other Auth controllers.

**Comment by taylorotwell** [comment]
This PR has no description or explanation of what is trying to solve or make better for users.

**Comment by om3rcitak** [comment]
@taylorotwell Hi, sorry for no description. I add description.

**Comment by devcircus** [comment]
Can't you return whatever you like from a ```redirectTo``` method? Including just using the route helper?

**Pull request closed without merging**
