### PR TITLE
[5.3] optimize validator

### PR DESCRIPTION
**Pull request by petar-dambovaliev**
accepted optimization linked to https://github.com/laravel/framework/issues/16071

### CODE REVIEW

**Comment by sisve** [comment]
How many validation failures do I need to have for this to same, let's say, 0.1 seconds in any real production environment?

**Comment by PetarDambovaliev** [comment]
@sisve ,a lot. 0.1 seconds is quite a long time for calculations. This is not an optimisation of a bottleneck but rather a smaller one. Gaining performance when there is no bottleneck is quite a big amount of work because it's not a quick fix, It's a long process across the whole application.

**Comment by taylorotwell** [comment]
Performance PRs require before / after benchmarks.

**Comment by BrandonSurowiec** [comment]
@taylorotwell Did you see the performance screenshot in issue #16071 that @PetarDambovaliev linked to?

**Comment by PetarDambovaliev** [comment]
@BrandonSurowiec I did one PR over this yesterday and @taylorotwell requested benchmark of some sort. I did a debugbar benchmark of both piece of code, if he wants more specific type of benchmark he has to give a more direct guideline of the thing he wants.

**Pull request closed without merging**
