### PR TITLE
[10.x] Add test for `getActionName` method in Route

### PR DESCRIPTION
**Pull request by milwad-dev**
Related : https://github.com/laravel/framework/pull/47289

Coverage : 100%

### CODE REVIEW

**Comment by henzeb** [comment]
@milwad-dev, do you read the comments from @taylorotwell ? he wants real improvements right now and not just tests and code style fixes.

**Comment by milwad-dev** [comment]
I don't have any idea to test further, I got coverage it's 100% !

**Comment by milwad-dev** [comment]
I don't have any idea to test further, I got coverage it's 100% !
Taylor himself can add it if he needs a change

**Comment by driesvints** [comment]
Please read taylor's comment in the previous PR. Thanks

**Pull request closed without merging**
