### PR TITLE
[5.1] Add support for localization in ThrottlesLogins

### PR DESCRIPTION
**Pull request by antonybudianto**
Just suggestion, and it assumes we use the existing passwords.php file in resources/lang/en

Usage in laravel/laravel -> resources/lang/en/passwords.php (just like validation messages)

``` php
[
    "throttle" => "Too many login attempts. Please try again in :seconds seconds.",
];
```

Here is the PR for [laravel/laravel for lang](https://github.com/laravel/laravel/pull/3444)

Thank you.

### CODE REVIEW

**Comment by lukasgeiter** [comment]
Using `'passwords.'.$this->loginUsername();` as translation key makes no sense to me. Isn't that always a different value? I suggest something like `passwords.throttle` or `passwords.too_many_attempts`

**Comment by lukasgeiter** [comment]
Oh and instead of using an if I'd just add the default message to the translation file in `laravel/laravel`

**Comment by antonybudianto** [comment]
Agree with "passwords.throttle" one, soon after approved, I'll PR to laravel/laravel for translation file.
Thank you for suggestion :+1:

**Comment by antonybudianto** [comment]
By the way, the key in AuthenticatesUser trait also uses the same key "$this->loginUsername()" for failed login message, and its error message still hardcoded, the same with this issue.

**Comment by lukasgeiter** [comment]
Yes but it's used as error key not for translation. And the hardcoded message there can easily be overridden with the `getFailedLoginMessage` method. I think there was already a PR for that and Taylor rejected it. Let's see what he thinks of this...

With your changes the key of the errors array is now wrong.. This should be right:


    ->withErrors([
        $this->loginUsername() => trans()->has('password.throttle') ? trans('password.throttle', ['seconds' => $seconds]) : 'Too many login attempts. Please try again in '.$seconds.' seconds.',
    ]);

**Comment by antonybudianto** [comment]
but overriding that will be bad for my opinion, it's better to just read from the language files
then let's just wait

**Comment by antonybudianto** [comment]
Thank you @taylorotwell  :smiley:

**Comment by overcrookd** [comment]
It seems like the 'throttle' key is missing in the passwords.php lang file, it is present in the auth.php file though.

**Comment by crynobone** [comment]
Already updated? <https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Auth/ThrottlesLogins.php#L69>

**Comment by antonybudianto** [comment]
yup, it's now in ```resources/lang/en/auth.php``` file, together with failed auth message :smiley: 
and since it's on master branch, will have to wait for the next release, 
the [current tag 5.1.6](https://github.com/laravel/framework/blob/v5.1.6/src/Illuminate/Foundation/Auth/ThrottlesLogins.php) still uses ```resources/lang/en/passwords.php```

**Pull request merged**
