### PR TITLE
[5.5] Add sortNaturally

### PR DESCRIPTION
**Pull request by jbrooksuk**
This is a "nice to have" method.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Looks like I messed this up 🤦‍♂️

**Comment by jbrooksuk** [comment]
Fixed!

**Comment by ntzm** [comment]
Can't you just pass the sort type into the second param of `sortBy`?

**Comment by jbrooksuk** [comment]
Yes, yes you can 🤦‍♂️

**Pull request closed without merging**
