### PR TITLE
[11.x] Add component view instance caching

### PR DESCRIPTION
**Pull request by amir9480**
This PR will add a view instance caching support to components and prevent creating new view instances on each render resulting in increasing +20% performance rendering components.

Benchmarks:
Before the view instance caching:
image

After the view instance caching:
image

### CODE REVIEW

**Comment by taylorotwell** [comment]
With the merge of other recent performance improvement PRs I'm actually not seeing any meaningful performance benefit from this PR anymore. Can you re-run your tests with latest code in 11.x? Mark as ready for review if you want me to take another look or after you comment.

**Comment by amir9480** [comment]
@taylorotwell 

This PR is not needed anymore.

But my closed PR (#51141) still can improve performance.

Without in-memory cache support for Blade:
image

With in-memory cache support for Blade:
image

**Comment by amir9480** [comment]
@taylorotwell 
This PR can cause side effect issues as it caches view data.

web.php:
```php
Route::get('/', function () {
    return view('home');
});
```

home.blade.php:
```blade
<x-sample param1="Hello" />
<hr />
<x-sample param1="Hello" param2="World" />
<hr />
<x-sample param1="Hello" />
```
sample.blade.php:
```blade
@if (isset($param1))
    <p>Param 1: {{ $param1 }}</p>
@else
    <p>Param 1 is not set</p>
@endif

@if (isset($param2))
    <p>Param 2: {{ $param2 }}</p>
@else
    <p>Param 2 is not set</p>
@endif
```

Output:
image

**Comment by amir9480** [comment]
Fixed the reuse data issue and this PR still can improve performance while using `View::compose`.

Without view instance caching:
image

With view instance caching:
image

**Comment by amir9480** [comment]
Causing other side effects, closing the PR.

**Pull request closed without merging**
