### PR TITLE
Unlock withoutOverlapping method when the process receiving signal

### PR DESCRIPTION
**Pull request by cesargb**
Task Scheduling: Unlock withoutOverlapping method when the process receiving signal

With this change I try unlock withoutOverlapping method when the process receiving signal, for example kill -9 (OOM killed, ...)

This PR add the catch [RuntimeException](https://github.com/symfony/process/blob/master/Exception/RuntimeException.php) when the schedule runs. This catch unlock mutex in withOverlapping method when this exception throws.

This Exception is [throw for symfony/process](https://github.com/symfony/process/blob/4f10286a128df6b60b3706752e11f6227fcac844/Process.php#L193)

Additionally this PR add these task hook:

* fail; specify code to be executed when the scheduled task fails (same before, after)
* pingFail; the scheduler can automatically ping a given URL when task fails

### CODE REVIEW

**Comment by sisve** [comment]
How would the php engine execute any code all if it was killed by either a SIGKILL signal or killed by the out-of-of-memory killer?

**Comment by cesargb** [comment]
@sisve Really this work because the signal kill is received by subprocess. https://symfony.com/doc/current/components/process.html#running-processes-asynchronously

Schedule is the parent and run a new subProcess (the command) In this case, the schedule received the signal respect the subprocess (command) and then the parent can work.

Normally the command load more  resource of system, example: export, ...

But we get other signal for subprocess, example kill -15 if the system is reboot.

**Comment by sisve** [comment]
Ah, that would explain your initial description. I was thinking of, what could then be described as, the "host script".

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Pull request closed without merging**
