### PR TITLE
Fixed docblock for errors method on ValidationException

### PR DESCRIPTION
**Pull request by boris-glumpler**
The title said it all.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
No, the contract is correct.

**Comment by shabushabu** [comment]
This is taken straight from the exception in question:

```
	/**
	 * Get the validation error message provider.
	 *
	 * @return \Illuminate\Contracts\Support\MessageProvider
	 */
	public function errors()
	{
		return $this->provider->getMessageBag();
	}

	/**
	 * Get the validation error message provider.
	 *
	 * @return \Illuminate\Contracts\Support\MessageProvider
	 */
	public function getMessageProvider()
	{
		return $this->provider;
	}

```

Here we have 2 methods that return different things, yet somehow they end up with the exact same docblocks. Funny that, isn't it? Care to explain how that's correct?

**Comment by GrahamCampbell** [comment]
They are both returning implementations of this contract.

**Comment by shabushabu** [comment]
Thanks for clearing that up. Didn't see that.

**Pull request closed without merging**
