### PR TITLE
[5.3] bind double as PDO::PARAM_INT

### PR DESCRIPTION
**Pull request by themsaid**
This PR fixes this issue: https://github.com/laravel/framework/issues/16063

### CODE REVIEW

**Comment by taylorotwell** [comment]
We used to have this as the code and it causes other problems. I'm sure there are GitHub threads about it.

**Comment by themsaid** [comment]
@taylorotwell I've altered the implementation to only affect MySQL connections, so only in MySQL a double will be bound as PDO::PARAM_INT

**Comment by taylorotwell** [comment]
Did you find the original issue I was referring to?

**Comment by themsaid** [comment]
I found this one: https://github.com/laravel/framework/pull/14881

> If for example a float is bound with PDO::PARAM_INT, SQLite (haven't tested with any other DBMS) will discard the decimal part (0.5 will become 0.0 in the DB). This totally broke my application.

So I'm doing this change only on a MySQL connection since it's the one with consistency issues.

**Pull request merged**
