### PR TITLE
[5.2] Proposal: string wrapper

### PR DESCRIPTION
**Pull request by acasar**
This PR proposes a string wrapper (similar to how collections wrap arrays). Basically, I had to deal with a lot of string manipulation in a project recently, so I wrote this class to make my code more readable and avoid all of that UTF-8 and needle-haystack problems. Would you consider adding something like that into core? If not, I'll just make a package for anyone who'd like to use it.

I also added a `str` helper, since we already have a `collect` helper for collections. Below are some real world scenarios that this PR helps to solve:

``` php
// lets say that a user provides tags in the following format: "tag1, tag2, tag3"

str($tags)->words()->each(function ($tag) {
    // do something with a tag here
});
```

``` php
// we can avoid nesting str functions and needle-haystack problems

str('  some text  ')->trim()->substring(0, 4); // returns "some"
```

``` php
// lets say we have a slug "my-blog-title-4" and we need to find the index "4"

$lastIndex = str($lastSlug)->explode('-')->last();
```

``` php
// lets say we have some custom "colon separated" multi line file that we need to import

str($content)->lines()->each(function ($row) {
    $data = str($row)->explode(':');
    // do something with data here
});
```

etc.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Gonna hold off on bringing this in core for now, though it would be a cool package

**Comment by JosephSilber** [comment]
@acasar if you turn that into a package, I'll be the first one to get it.

**Comment by acasar** [comment]
@JosephSilber @taylorotwell Cool, I'll make a package by tomorrow ;)

**Comment by acasar** [comment]
@JosephSilber Here we go: https://packagist.org/packages/laraplus/string

**Comment by freekmurze** [comment]
@JosephSilber @acasar I also took a stab at creating a string package a while ago: https://github.com/spatie/string

**Pull request closed without merging**
