### PR TITLE
[10.x] Improve inspiring quote method

### PR DESCRIPTION
**Pull request by blaysku**
Small improvements

### CODE REVIEW

**Comment by henzeb** [comment]
Why?

**Comment by mpyw** [comment]
Reduction of calculation. There are no reasons to be closed...

**Comment by blaysku** [comment]
@mpyw Thanks, reopened at #48516

**Comment by henzeb** [comment]
> Reduction of calculation. There are no reasons to be closed...

I don't understand why we need to optimize a demo command.

**Comment by mpyw** [comment]
This is absolutely not a over-optimization but a natural code.

**Comment by henzeb** [comment]
Semantics, why are we updating demo code? It's not broken...

**Pull request closed without merging**
