### PR TITLE
[5.8] Collection method to Search for key of last occurrence

### PR DESCRIPTION
**Pull request by me-shaon**
`search` method in Collection returns the key of the **first** occurrence of the given item. 
In this PR, I've added a new method in Collection named `searchLast` which will return the key of the **last** occurrence of the given item.

### CODE REVIEW

**Comment by me-shaon** [comment]
Documentation added in [this PR](https://github.com/laravel/docs/pull/5399).

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by decadence** [comment]
You can use reverse and then search

**Comment by me-shaon** [comment]
@decadence Yeah, definitely. But if the Collection is large, It will be slower than what I've implemented.

**Pull request closed without merging**
