### PR TITLE
Add hasAttribute() to Eloquent/Model

### PR DESCRIPTION
**Pull request by johannesschobel**
This PR adds the `hasAttribute()` method to `Eloquent/Model` in order to check, if a given attribute exist in this model

### CODE REVIEW

**Comment by taylorotwell** [comment]
I would just suggest using isset($model->key).

**Comment by decadence** [comment]
@taylorotwell it returns false if attribute exists but has `null` value.

**Comment by johannesschobel** [comment]
Actually, i think, `isset($field)` would have a different behavior.. Additionally, i think, it would be more `laravelish` to allow it to directly check it at the model itself by calling `$model->hasAttribute(...)`

**Comment by johannesschobel** [comment]
@taylorotwell can you please re-open this PR and rethink it?

**Comment by johannesschobel** [comment]
see this example here:

```php
// let $user be a User model
$user->name = null;
dd(isset($user->name)); // false, even it is set!
dd($user->hasAttribute('name')); // true, even it is null
```

So i think, the `isset(...)` approach is not valid here..

**Comment by decadence** [comment]
@johannesschobel Yes. That's what I write about. I think you should make another PR with this description because Taylor doesn't look on closed PRs.

**Comment by denis-chmel** [comment]
Need the same, and totally agree with @johannesschobel
```
// let $user be a User model
$user->name = null;
dd(isset($user->name)); // false, even it is set!
dd($user->hasAttribute('name')); // true, even it is null
```

I left a petition on change.org for @taylorotwell to merge this.

**Comment by royduin** [comment]
It's added in Laravel 11.3: https://github.com/laravel/framework/pull/50909

**Comment by donnysim** [comment]
@royduin it's still wrong because it will return true just because you have a cast or a mutator, which will never indicate that the attribute actually exists.

**Pull request closed without merging**
