### PR TITLE
[11.x] Adds an optional restorable route for resource and singleton routes

### PR DESCRIPTION
**Pull request by tonysm**
### Changelog

- Adds an optional  _restorable_ verb to resource and singleton routes

----

When working with soft-deleted models, we often need an endpoint for restoration (when convenient). This PR makes it part of the resource model convention as an optional route.

**Use with resource routes:**

```php
Route::resource('organizations', OrganizationsController::class)->restorable();
```

This will register all the regular 7 resource routes with the extra `POST /organizations/{organization}/restore` route.

Works with singleton resource routes too:

**Use with singleton routes:**

```php
Route::singleton('user.avatar', AvatarController::class)->destroyable()->restorable();
```

This will register all the 3 singleton resource routes, plus the `DELETE /user/{user}/avatar` for destroyable and `POST /user/{user}/avatar/restore` for restorable.

---

My primary need with this is on resource routes, but added to singleton resources too since it supports destroying them.

The restore routes automatically attach the `->withTrashed()` modifier, so implicit route model binding keeps working.

Prior similar PRs:
- https://github.com/laravel/framework/pull/44420
- https://github.com/laravel/framework/pull/44421

If there's interest in this PR, I can send a docs update and maybe update the `make:controller` command to add the `--restorable` option there too.

### CODE REVIEW

**Comment by rodrigopedra** [comment]
Can you add an assertion to this test case?

https://github.com/laravel/framework/blob/f0de069d2c40e77cae9d669bb712a21f9bdee1cb/tests/Routing/RoutingRouteTest.php#L1476-L1485

It tests for using localized verbs. Thanks!

**Comment by rodrigopedra** [comment]
Looking closely, maybe there are other test cases on that file that need to be updated to accommodate the new method. 

In particular, the ones that test route naming.

**Comment by tonysm** [comment]
I'll move the `RoutingResourceTest` methods to that one, I think they belong there instead. But I don't think anything needs to change on any other method, they just need to keep working. ;)

**Comment by taylorotwell** [comment]
I'm torn on this. I see the utility but doesn't feel very RESTful or resourceful. My hunch is I needed this I would make it part of `PATCH /resource` where I send `{ deleted_at: null }` or something.

**Comment by taylorotwell** [comment]
I think I will table this one for now for reasons above. Just not sold on appending `/restore` to a route. 😬

**Pull request closed without merging**
