### PR TITLE
[5.6] Return 201 in case of a Model just created.

### PR DESCRIPTION
**Pull request by mathieutu**
https://github.com/laravel/framework/pull/21603

### CODE REVIEW

**Comment by gabriel-caruso** [comment]
Why would this be helpful?

**Comment by m1guelpf** [comment]
@mathielo Tests?

**Comment by mathieutu** [comment]
@m1guelpf If only I could... 😔
As I've seen, the whole file isn't tested, and IMO the purpose of this PR isn't to add a bunch of tests. I can create a new file for the router and just test the modification, but I had trouble with people in some of my PRs because of tests (when more modifications in tests than in feature), so I'm a bit _cautious_ with that.

**Comment by ConnorVG** [comment]
Added behaviour? Add some tests.

**Comment by ntzm** [comment]
> had trouble with people in some of my PRs because of tests

Why would people have trouble with you adding tests?

**Comment by mathieutu** [comment]
>Added behaviour? Add some tests.
Totally agree..!

>Why would people have trouble with you adding tests?
As I said, there is a difference between adding some tests in the middle of others, and creating some new tests classes and way to tests features. When it's only one understandable line added to the code it's ok, but when you add more modifications in the tests that in the features, it can "fear" some people. ¯\_(ツ)_/¯

But guys I totally agreed with all of you, and I'm a TDD guy, so no need to argue about that with me.
Will add a file to test the router, and some tests for this one.

**Comment by taylorotwell** [comment]
You can easily write an integration test for it.

**Comment by taylorotwell** [comment]
Looks at the routing tests in the Tests/Integrations folder.

**Pull request merged**
