### PR TITLE
add `if_isset()` function

### PR DESCRIPTION
**Pull request by neatlife**
replace many isset() and default value statement to `if_isset()` function

### CODE REVIEW

**Comment by crynobone** [comment]
why not just `$user->foo ?? 'bar'`?

**Comment by neatlife** [comment]
@crynobone may be it is still to long, because this scene will happen many times in project

**Comment by crynobone** [comment]
Yeah but what about that just a duplicate of 

```php
$user['foo'] = array_get($user, 'foo', 'bar');
$user['name'] = array_get($user, 'name', 'defaultName');
$user['age'] = array_get($user, 'age', 'defaultAge');
```

Furthermore, you can't really do something like:

```php
$user['foo'] = $users[0]['foo'] ?? 'bar';
$user['name'] = $user[0]['name'] ?? 'defaultName';
$user['age'] = $user[0]['age'] ?? 'defaultAge';
```

**Comment by X-Coder264** [comment]
👎 from me. We don't need another global helper function unless there is a very good reason for it.

**Pull request closed without merging**
