### PR TITLE
[6.x] Correct implementation of float casting comparison

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
// cc @CraigHarley

**Review by CraigHarley — APPROVED** [review]
Looks good to me, and doesn't mean a dependency on `ext-bcmath` 🚀

**Comment by Quintile** [comment]
With this change, if you have a decimal column set to null, and try to update it to 0.0, it will fail to update because `originalIsEquivalent` will return true, because 0.0 - null = 0.0 and 0.0 is < PHP_FLOAT_EPSILON * 4.

So it's currently impossible to update a null column to a 0.0 value.

**Comment by GrahamCampbell** [comment]
No it won't, because nulls are checked above.

**Comment by Quintile** [comment]
I believe the $attribute is checked as null, not the $original. In this scenario $attribute is 0.0 and $original is null. It won't update in that case.

**Pull request merged**
