### PR TITLE
Helper logger() returning "mixed" instead of "void"

### PR DESCRIPTION
**Pull request by h4cc**

### CODE REVIEW

**Comment by Sladewill** [comment]
That's incorrect if you trace it back to https://github.com/h4cc/framework/blob/patch-1/src/Illuminate/Log/Writer.php#L197 it doesn't actually return anything.

**Comment by h4cc** [comment]
@Sladewill Line number 300 states different: `if (is_null($message)) return app('log');`

**Comment by GrahamCampbell** [comment]
`void` means undefined, not null.

**Comment by h4cc** [comment]
According to PHPDocumentor, `@return void` should be used when there is no return value: http://www.phpdoc.org/docs/latest/references/phpdoc/tags/return.html
But the logger() helper can be returning the logger service, so it can not be `void`.

Having `@return void` at the helper will make PHPStorm and other editors show errors when using code like this, what should not be the intention of such a helper:
```
<?php
logger()->info('Hello World.');
```

**Comment by GrahamCampbell** [comment]
phpdoc.org is incorrect then. php.net says it means unddefined.

**Comment by franzliedke** [comment]
Out of interest: Are you referring to [this page](http://php.net/manual/en/language.pseudo-types.php)? That's the only one I could find, but it only applies to the PHP docs...

**Comment by h4cc** [comment]
How about changing it to `@return void|\Illuminate\Contracts\Logging\Log`? That would do the trick.

**Comment by GrahamCampbell** [comment]
@h4cc What, not it wouldn't. If `void` is used, you can NOT mix it with anything else. Having the return defined as ether "totally useless" or an instance of "Log" is wrong.

**Comment by GrahamCampbell** [comment]
Gah. I really hate mixed, because it's totally useless, you might as well not document it.

**Comment by GrahamCampbell** [comment]
That;s why we didn;t...

**Comment by GrahamCampbell** [comment]
Leaving for taylor to decide.

**Comment by h4cc** [comment]
Only thing i want to achieve, is to get this supported in PHPStorm as it should:
```php
logger()->info('Hello World.');
```

**Comment by GrahamCampbell** [comment]
`@return \Illuminate\Contracts\Logging\Log|null` would work perhapse, just not using `void`.

**Comment by taylorotwell** [comment]
`\Illuminate\Contracts\Logging\Log|null` works for me.

**Comment by h4cc** [comment]
Works for me too :shipit:

**Comment by GrahamCampbell** [comment]
If you remove the `@` from the commit message, we're good to go, otherwise, you're referencing the user on github called return.

**Comment by h4cc** [comment]
@GrahamCampbell Thanks, did not think about that. Fixed now.

**Comment by ibrasho** [comment]
Finally. :heart: 

I wish PHPStorm warning were customizable...

**Pull request merged**
