### PR TITLE
[11.x] Adds Enums folder to `make:enum` command

### PR DESCRIPTION
**Pull request by milwad-dev**
https://github.com/laravel/framework/pull/50394

In our previous PR, we didn't include the option to create enums in the `Enums` folder or `App` folder. However, we have now added this feature! If someone would like to create an enum file in the `Enums` folder, they just need to create a folder named `Enums` :)
Like models

### CODE REVIEW

**Comment by milwad-dev** [comment]
@driesvints 
I think we need to re-run the tests.
Also, I can't access to the Styleci!!

**Comment by driesvints** [comment]
@milwad-dev seems tests still fail

**Comment by martinbean** [comment]
@milwad-dev Would be nice if this were configurable. I use `Enumerations` as my directory/namespace name, for example.

**Comment by milwad-dev** [comment]
"We cannot do that because if we do it for one command, we will have to do it for all commands such as models

**Comment by taylorotwell** [comment]
Added `Enumerations` support @martinbean

**Comment by dvlpr91** [comment]
I was expecting this command to default to the 'Enums' folder, regardless of whether it exists or not... Sad.

**Pull request merged**
