### PR TITLE
Add version() to Application

### PR DESCRIPTION
**Pull request by antonioribeiro**

### CODE REVIEW

**Comment by Anahkiasen** [comment]
What would this be used for that'd require a method instead of simply accessing the constant?

**Comment by antonioribeiro** [comment]
Why is it present on Laravel 5 and not on 4?

**Comment by antonioribeiro** [comment]
The `app()->version()`, or `$this->app->version()` is handy on Laravel 5, specially whe you are trying to develop a Laravel package supposed to work on both (4 and 5), we could do something like:

	protected function laravel4OrPrior()
	{
		return $this->app->version() < '5.0.0';
	}

And the package wouldn't have to be aware of what exactly is the current Laravel Application class.

**Comment by Anahkiasen** [comment]
No yes I get that but, what can't you just do `return Application::VERSION < '5.0.0'`

**Comment by antonioribeiro** [comment]
Yes, I am, but in the process of writing it:

	use Illuminate\Foundation\Application as Laravel;

	private function laravel5()
	{
		return Laravel::VERSION >= '5.0.0';
	}

But while writing it I realized my class should not be responsible for knowing how to get the Laravel version, that `use` was just wrong. And if it Taylor changes it, I'll have to change it too.

**Comment by GrahamCampbell** [comment]
I'm pretty sure the removal of the method was totally intentional.

**Comment by taylorotwell** [comment]
If you're developing a package to work on both 4 and 5, you should do that on two separate branches, similar to how Cashier is developed, with 3.0 being 5.0 support, and 2.0 branch being 4.x support.

**Pull request closed without merging**
