### PR TITLE
[10.x] Display error message if json_encode() fails

### PR DESCRIPTION
**Pull request by aimeos**
Adding the error code to the exception isn't useful. Instead, the error message can give details about the problem.

### CODE REVIEW

**Comment by henzeb** [comment]
If this needs to be changed, I suggest concat the error code in the string, for backwards compatibility.

**Comment by aimeos** [comment]
@henzeb This is just an error string that's displayed in debug mode if the exception is thrown and not parsed by anyone, so adding the error code makes no sense to me at all.

**Comment by driesvints** [comment]
@aimeos can you rebase your pr against 10.x to fix the tests?

**Comment by rodrigopedra** [comment]
@aimeos changing from using the error code to the error message is a breaking change.

On one project I work on, we log all the exceptions messages, and do some assessments on their frequency.

Some of these assessments, group exceptions by their message. Specially on exceptions that are considered "stable", such ones that have a clear error code in it.

I believe some error tracking platforms also allow a similar workflow for tracking bugs/exceptions.

Although I wouldn't drop the error code altogether, I agree having the message along is useful.

But this change should target Laravel 11, so people who have error tracking mechanisms in place are not surprised.

**Comment by crynobone** [comment]
I guessing it also possible to trigger `JsonException` here instead and set it as `$previous` when throwing `InvalidPayloadException`? https://www.php.net/manual/de/class.jsonexception.php

**Comment by crynobone** [comment]
@aimeos does #48884 fit your requirements?

**Comment by aimeos** [comment]
@crynobone Is the nested exception shown in the Laravel debug view if an error occurs?

**Comment by driesvints** [comment]
@aimeos are you still working on this?

**Pull request merged**
