### PR TITLE
[5.6] Added 'rules' method to SendsPasswordResetEmails class

### PR DESCRIPTION
**Pull request by PedroFTW**
Implemented a rules() method that returns an array of rules for the email validation.

Utilized the new rules() method in the validateEmail() method.

The intention is to simplify rules extension in this trait, by simply overriding the rules() method in the controller, while maintaining the current funcionality stable.

### CODE REVIEW

**Comment by devcircus** [comment]
Thinking the docblock comment is ok as-is.

**Comment by PedroFTW** [comment]
@devcircus Should I take the change in the comment?

**Comment by devcircus** [comment]
I'd just leave and see what Taylor says

**Comment by taylorotwell** [comment]
You can just override the method entirely and specify your rules.

**Comment by PedroFTW** [comment]
@taylorotwell Ok, it's just that a really close trait (ResetsPasswords) works with the rules() method.

IMO, having two different ways to extend such close traits it's counter-intuitive. I had already overriden the rules() method in ResetsPasswords, when I tried to do the same with SendsPasswordResetEmails I was shocked it didn't worked, since most things in Laravel follow a pattern.

**Pull request closed without merging**
