### PR TITLE
[11.x] Prevent destructive commands from running

### PR DESCRIPTION
**Pull request by jasonmccreary**
This PR introduces a `Preventable` trait which may be added to "destructive" commands to prevent them from running. 

While many commands are "confirmed" in production, they are still possible to run. This trait takes that a step further by effectively disabling them. So, for example, you can't inadvertently run `migrate:fresh` in production (like I did this morning).

Similar to other _safety methods_, you may add calls to prevent certain commands to the `boot` method of your `AppServiceProvider`:

```php
public function boot(): void
{
    FreshCommand::preventFromRunning();
    RefreshCommand::preventFromRunning();
    ResetCommand::preventFromRunning();
    WipeCommand::preventFromRunning();
}
```

By default, this method will prevent the command from running - immediately terminating the command with a warning and non-zero exit code.

**Note:** you may limit this to certain environments by passing a boolean argument to this method. For example, only preventing them in production.

```php
FreshCommand::preventFromRunning($this->app->isProduction());
```

---
**Update**
For future readers, Taylor "Wordsmith" Otwell changed the method name to `prohibit` and added a single method for preventing all these commands at once.

You may add the following call to the `boot` method of your `AppServiceProvider` to prevent these commands in production environments:

```php
DB::prohibitDestructiveCommands($this->app->isProduction());
```

---
Co-authored with @joelclermont

### CODE REVIEW

**Comment by PerryvanderMeer** [comment]
Is there a way to easily extend this to all commands, for example, when I also want to prevent the use of `queue:clear`?

**Comment by jasonmccreary** [comment]
@PerryvanderMeer, yes. If merged, other native commands or even third-party commands could use the `Preventable` trait.

**Comment by shalvah** [comment]
> If merged, other native commands or even third-party commands could use the Preventable trait.

This is cool! But this is actually 3 opt-ins (trait + service provider + manual check in handle() method), which seems a bit redundant. How about adding the Preventable trait directly to the base Command class, which means you only need the service provider call to opt in? IMO, that should be enough, as it still won't do anything unless you explicitly opt in.

**Comment by ahinkle** [comment]
What are your thoughts on providing an option to encapsulate all preventive commands throughout the framework?

```php
// All
public function boot(): void
{
    FreshCommand::preventFromRunning();
    RefreshCommand::preventFromRunning();
    ResetCommand::preventFromRunning();
    WipeCommand::preventFromRunning();
}

// eg. Grouped Example
public function boot(): void
{
    DestructiveCommands::preventFromRunning();
}
```

**Comment by jasonmccreary** [comment]
@ahinkle, absolutely. Joel and I discussed it while pairing. But I like to keep my PR _atomic_ to first see if this is something the team wants. If so, I can imagine that being one of the fast follows, along with potentially other commands being preventable.

**Comment by hameedraha** [comment]
Wonderful idea. This should definitely be a framework-level feature.

**Comment by morloderex** [comment]
I like the idea, but i wish the implementation had some more flexibility. 

How about allowing a \Closure that when executed should return a boolean instead of a simple boolean flag? This way we can do stuff like `fn() => $this->app->isProduction() || $this->app->isDownForMaintiance()`. And have it be executed correctly in octane.

Not that the in the example is a good idea but the general idea is not possible currently.

**Comment by joshuaziering** [comment]
I love this. What if it just made you type "YES" the way Github makes you type the repo name to delete it? Rather than getting rid of all the functionality.

**Comment by jasonmccreary** [comment]
@joshuaziering, the `ConfirmTrait` has that covered for production environments. This is kind of that next level, protect me from myself type thing.

The state of mind I was in, I truly thought I was on another site and knew what I was doing and would have typed "YES" anyway. 😅

**Comment by pxpm** [comment]
> @shalvah, adding it to the base `Command` seems extreme in reach. I was following what existed with the `ConfirmableTrait` added to individual commands already. But I'm open to whatever the team thinks.

Hey @jasonmccreary excellent contribution. Much appreciated 🙏 

I just won't 100% agree here with you. I think you have a valid point too, but in my opinion this is something that shouldn't be opt-in for commands.
Preventing something from running has different security implications than: "type yes to run". 

Adding it as a trait to "core" commands, or the commands you develop is fine I guess, but it's also something that's currently not implemented in the millions of commands developed by 3rd parties that shouldn't run in production. 

It's mainly a developer decision on what commands to run on what environments, so why not just provide a way in the framework to disable some commands on some given conditions ? Similar to how we configure `preventsLazyLoading`, a similar `preventsFromRunning`. 

Anyway this lands in the framework, I think everyone will benefit from the added security. 

Cheerss

**Comment by johanrosenson** [comment]
> @joshuaziering, the `ConfirmTrait` has that covered for production environments. This is kind of that next level, protect me from myself type thing.
> 
> The state of mind I was in, I truly thought I was on another site and knew what I was doing and would have typed "YES" anyway. 😅

I agree 100%, there should not be a way to override it and run the command anyway, there are many occasions where I would have run something on the wrong server even if asked to confirm it.

**Review by msonowal — COMMENTED** [review]
I agree its one more step per project level so we do that

**Comment by justinkekeocha** [comment]
This Laravel package [https://github.com/justinkekeocha/database-dump] can also help with generating a dump file  whenever you run `migrate:fresh`. This can be very helpful when working in development environment and you don't want to accidentally lose data. You can also use the package to seed the database with the same dump file generated. This can be helpful when one wants to make breaking changes in production.

**Comment by h-sigma** [comment]
> So, for example, you can't inadvertently run migrate:fresh in production (like I did this morning).

Programming equivalent of seeing another guy get kicked somewhere... unpleasant.

**Comment by ahinkle** [comment]
@jasonmccreary 

I thought I was imagining things when I remembered this feature and found a use case for it today, but I noticed it’s undocumented. Do you think it’s worth documenting now, or should we leave it undocumented for the time being?

**Comment by jasonmccreary** [comment]
@ahinkle, I haven't made any PRs for it. Anyone is welcome to open a PR to [laravel/docs](https://github.com/laravel/docs). Sometimes you just need an nudge and Taylor "Wordsmith" Otwell will take it the rest of the way.

**Comment by hugomatheuss** [comment]
Hi @jasonmccreary.
Can I use the Prohibitable trait in any of my commands? For example, I created a command with make:command and used the trait inside it to later configure it in the AppServiceProvider and ignore it in production?

**Pull request merged**
