### PR TITLE
Str startsWith and endsWith with case insensitive param

### PR DESCRIPTION
**Pull request by ricventu**
I added param to make Str::startsWith and Str::endsWith case insensitive, same like Str::contains

### CODE REVIEW

**Comment by ricventu** [comment]
tests / PHP 8.0 - prefer-lowest (pull_request)
fails but its an error in docker workflow, not related to the code

**Comment by taylorotwell** [comment]
I think you could just strtolower your parameters before calling this method.

**Comment by ricventu** [comment]
sure,
but therefore also Str::contains should not have the $ignoreCase parameter

Thanks for your attention )

**Comment by caendesilva** [comment]
> I think you could just strtolower your parameters before calling this method.

@taylorotwell Would you be open to reconsidering this? `Str::contains` supports this parameter even though you can call strtolower beforehand, so merging this PR would both add value and consistency.

**Pull request closed without merging**
