### PR TITLE
specified the PHPDoc parameters for search in Collection

### PR DESCRIPTION
**Pull request by maxwilms**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Wrong. `mixed` can't be added to anything else since eveything else is a subset of mixed.

**Comment by GrahamCampbell** [comment]
Thus `mixed|callable` makes no sense.

**Comment by maxwilms** [comment]
Yes, `callable|mixed` this is over-specification. But this could save some time for developers as you don't need to reach for the docs or even the source to find out that indeed you can pass a callable to `search()`.

Additionally many methods have such a signature. A quick `egrep -r "\|mixed|mixed\|" .` will reveal some of them. And [phpDocumentator](http://www.phpdoc.org/docs/latest/guides/types.html#multiple-types-combined) does not state that you cannot combine mixed within an OR.

Please reconsider this PR.

**Comment by GrahamCampbell** [comment]
If we have any other cases of `mixed|`, then need fixing.

**Comment by rizqidjamaluddin** [comment]
I'd agree with `mixed|callable` just because it tells IDEs and their users that they can use a search test instead of just a searched value, semantics aside. This tripped me up earlier when I wanted to search for an object in a collection by property, so it'd definitely be helpful for IDE users.

And to be fair, in a more OO language we'd use `object` to act as a superset of integers, strings, an instance of an object etc, but we can't do that in PHP.

**Pull request closed without merging**
