### PR TITLE
[10.x] Add `whenAggregated` method to `ConditionallyLoadsAttributes` trait

### PR DESCRIPTION
**Pull request by akr4m**
This PR introduces a new method, `whenAveraged()`, to the `ConditionallyLoadsAttributes` trait. This function is designed to work similarly to `whenCounted()`, but retrieves a relationship's column average value if it exists, expanding upon the trait's conditional loading capabilities.

Eloquent example with [withAvg](https://laravel.com/docs/10.x/eloquent-relationships#other-aggregate-functions)
```php
$endpoints = $currentSite
            ->endpoints()
            ->withAvg('checks', 'response_time')
            ->get();
```

Eloquent Resource example with additional conditional relationship (`whenAveraged`)
```php
public function toArray($request)
{
    return [
       'response_time_avg' => $this->whenAveraged('checks', 'response_time'),
    ];
}
```

The `whenAveraged()` method takes in a relationship, a column name, an optional value, and an optional default value. It generates an attribute name by appending the string '_avg_' to the snake-cased version of the relationship name, followed by the column name. If this attribute does not exist in the resource's attributes, it returns the default value (or null if no default is provided).

This new method is particularly useful when dealing with large datasets where you want to conditionally load averages. It provides a convenient and readable way to handle such scenarios directly in the resource class, expanding upon the conditional loading capabilities of `whenCounted()`.

### CODE REVIEW

**Comment by akr4m** [comment]
The eloquent also provides `withMin`, `withMax`, `withSum`, and `withExists` methods alongside `withCount`. And these methods place a `{relation}_{function}_{column}` attribute result.

So, in Eloquent Resources, some additional Conditional Relationships are sometimes necessary.

**Review by akr4m — COMMENTED** [review]
I've made updates based on the feedback received. The initial `whenAveraged` method has been replaced with a more generic `whenAggregated` method. This new method can handle multiple aggregate functions including `min`, `max`, `avg`, `sum`, `exists`, and more.


The `whenAggregated` method takes an additional parameter, `$aggregate`, which specifies the type of aggregation to perform. The attribute is then generated by appending an underscore, the aggregate function, and another underscore to the snake-cased version of the relationship name, followed by the column name.

**Comment by taylorotwell** [comment]
Could use a test or two?

**Comment by akr4m** [comment]
> Could use a test or two?

Absolutely, I've added two tests along with the resource implementation. Please take a look and let me know if any adjustments are needed.

**Pull request merged**
