### PR TITLE
[5.8] Fix 26186 allow serialize igbinary

### LINKED ISSUE #26186: RedisStore, cant set Redis::OPT_SERIALIZER to Redis::SERIALIZER_IGBINARY because of hardcoded serialization
- Laravel Version: 5.7.+
- PHP Version: 7.2.11
- Database Driver & Version:
PECL redis 4.1.1
### Description:
Cant set Redis::OPT_SERIALIZER to any value, thats because of:
[serialize](https://github.com/laravel/framework/blob/c3b7a12f36b3eec1bdd7633c61a2dc1b7d6043f3/src/Illuminate/Cache/RedisStore.php#L276src/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php:287)
and
[unserialize](https://github.com/laravel/framework/blob/c3b7a12f36b3eec1bdd7633c61a2dc1b7d6043f3/src/Illuminate/Cache/RedisStore.php#L287)
methods in RedisStore.

Store needs refactor, to accept Redis::SERIALIZER_IGBINARY

### PR DESCRIPTION
**Pull request by Dudemullet**
This PR aims to fix #26186 adding the ability to configure the PhpRedis module to use any of its supported [custom serializers ](https://github.com/phpredis/phpredis#example-6) (php-builtin, igBinary, msgpack).

PredisConnection will use PHP's default `serialize` & `unserialize`

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please remove the extra blank file. :)

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by Dudemullet** [comment]
Hey @taylorotwell, the bug being addressed in this PR is #26186. 

To be clear, the main issue is exposing a feature inside of PhpRedis. You see, PhpRedis allows different serializers when storing the data in redis (php-builtin, igBinary, msgpack). You might also be wondering if these serialization methods have any benefits. Well, here is a comparison using `PHP: v7.2.15` and `Laravel: v5.7.25`.

```
PhpRedis (serializer: php)
Execution time: 00:01:36.9863
Cache storage used: 936.75MB
— — — — — — — — — — — — — — — — — 
PhpRedis (serializer: igbinary)
Execution time: 00:01:37.3176
Cache storage used: 342.66MB
```

Taken from [this post](https://medium.com/@akalongman/phpredis-vs-predis-comparison-on-real-production-data-a819b48cbadb) in Medium.

I understand your concern of project maintenance for sanities sake. But if I did this under a standalone package, I'd technically just be reproducing all of the _PhpRedisConnections_ functionality. Have you considered extracting all of PhpRedis's functionality to its own package and only supporting predis in the core framework package ?

**Comment by Dudemullet** [comment]
@taylorotwell Pinging you again for visibility on this bug. Also, if this code is to be delayed for merging. Could we at least keep the issue open ? 

RE:
> If you feel absolutely certain that this code corrects a bug in the framework

For reference, @driesvints Tagged the issue this PR addresses as a bug. Don't mean to just randomly tag more maintainers in here but if you feel this isn't a bug he might have more insight as to why this **is a bug**

**Comment by driesvints** [comment]
@Dudemullet I flagged it as a bug because I believe the `SERIALIZER_IGBINARY` option isn't correctly handled. I think you can re-attempt this pr. Maybe against the master branch. Also make sure you remove the blank file and such from this pr.

**Pull request closed without merging**
