### PR TITLE
[5.3] add $default parameter to query builder when() method

### PR DESCRIPTION
**Pull request by tomschlick**
This allows you to specify a default closure to run if the `when()` $value attribute is false.

I recently found myself creating a sorting / filtering system with defaults that the user could change. Without this you would have to do all kinds of wackiness to clear the previous where() clause on $value being true.

Here is an example of this in action

``` php

Time::when($request->has('type'), function ($query) use ($request) {
    return $query->where('type', $request->input('type'));
}, function ($query) {
    return $query->where('type', 1);
})
->get();


```

### CODE REVIEW

**Comment by themsaid** [comment]
Submit to master?

**Comment by themsaid** [comment]
@tomschlick thank you but please submit to master since it's a breaking change.

**Comment by tomschlick** [comment]
I can switch it if necessary... was just following what I have done in the past and what is done in the existing pull requests.

If you re-open the pull request I can change the branch on it through the edit button... Github enabled that a few weeks ago.

This also is not breaking...

**Comment by tomschlick** [comment]
Ugh I guess that doesn't work that well. I'll re-open on master.

**Comment by themsaid** [comment]
@tomschlick I guess it's better that you open a new PR to master, this switching thing on GitHub sometimes acts weird, and till this point I was too lazy to understand why it acts that way :)

**Pull request closed without merging**
