### PR TITLE
[5.2] Fixes resource routes collision with 'prefix' and 'as'

### PR DESCRIPTION
**Pull request by EliasZ**
Please see #11657 for details.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I don't think this is a fix. It's a breaking change. :-1: for merging to 5.2.

**Comment by GrahamCampbell** [comment]
If it actually is a "fix", then 5.2 is the incorrect target anyway. All bug fixes must go to 5.2 for 2 years.

**Comment by GrahamCampbell** [comment]
*5.1

**Comment by EliasZ** [comment]
I am thinking it is a fix because currently `as` collides with `prefix` for resource routes when in a group.

**Comment by taylorotwell** [comment]
It's definitely a breaking change and has already been made for 5.3.

**Comment by EliasZ** [comment]
@taylorotwell Alright then. Maybe you should document this in the as a quirk in the <5.3 docs.

**Pull request closed without merging**
