### PR TITLE
[5.8] Arr::flatten performance

### PR DESCRIPTION
**Pull request by bbsnly**
MacBook Pro (2017), i5, 16 GB

**Before**: 1.92s
**After**: 6.5ms
```php
$arr = [];
for ($i = 0; $i < 20000; $i++) {
    $arr[] = ['test'];
}
Arr::flatten($arr);
```

**Before**: 6.33s
**After**: 87ms
```php
$arr = [];
for ($i = 0; $i < 20000; $i++) {
    $arr[] = ['name' => 'John', 'email' => 'john@me.com'];
}
app('db')->table('users')->insert($arr);
```

**Before**: 5.7s
**After**: 88.93ms
```php
$arr = [];
for ($i = 0; $i < 20000; $i++) {
    $arr[] = ['name' => 'John', 'email' => 'john@me.com'];;
}
User::insert($arr);
```

### CODE REVIEW

**Comment by laurencei** [comment]
That's some impressive performance increases. For my own curiosity, and to help Taylor when he comes to review this PR, are you able to explain what the change actually is? i.e. we can see the code that has been changed, but what is the "logic" that allowed you to release there was such a performance improvement here.

And how do you know this gives the same result in all situations etc etc.

**Comment by bbsnly** [comment]
@laurencei I was comparing the `insert` performance between Eloquent and Doctrine, to do so I prepared ten different ways to insert new data with Laravel (Eloquent, QueryBuilder, direct connection). At some point I saw that when doing bulk insertion with thousands of items the performance was very poor.
When debugging I found the bottleneck here `Illuminate/Database/Query/Builder::insert` - `Arr::flatten`. It worked perfectly with a low amount of items but when using it with tens of thousands of items it was very slow.
The explanation of my solution is very easy: `array_merge` is slow when merging to a big array as it looks and compares keys where the concatenation operation is very fast. We are not interested in keys (`array_values` is used) so by using the `array_merge` function we will perform many operations we do not need.

**Comment by taylorotwell** [comment]
Nice, thanks!

**Comment by mfn** [comment]
Very nice improvements, thanks @bbsnly 

> `array_merge` is slow when merging to a big array

Can confirm, in my experience the 2nd worst bottleneck (1st being the database 😉) I've seen in practice (and: being easily identifiable) is this function. If used in a loop and large datasets, almost always a recipe to avoid.

**Comment by Korko** [comment]
Nice once! I would have preferred array_push($result, ...$values) instead of a foreach loop but the performance are almost the same between the 2 solutions https://3v4l.org/AH1ZX

**Comment by mfn** [comment]
> array_push($result, ...$values)

wow, that's neat trick!

I wonder if there are downsides or limitations of argument unpacking a large set for a function call?

**Comment by solofeed** [comment]
@mfn We can add a check for the size of the array and decide what to use

@bbashy What you think? maybe you can improve speed more?)

**Comment by mfn** [comment]
> We can add a check for the size of the array and decide what to use

Yeah but that already requires a conclusion if there is an issue with bigger sets. Is there ? ;)

**Comment by bbashy** [comment]
@solofeed why the mention?

**Comment by solofeed** [comment]
> @solofeed why the mention?

Sry) It was a mistake)

**Comment by ad-mos** [comment]
Looks like I am doing something wrong)
Tested by merging 2 arrays with 5M elements each.
```
foreach ... $old[] = $item;
0.58910183906555

array_push($old, ...$new);
0.52405204772949

array_merge($old, $new);
0.36471142768860
```

Here is the code:
```
$count = 10000000;
$iter = 5;

$resInsert = 0.0;
$resPush = 0.0;
$resMerge = 0.0;

for ($i = 0; $i < $iter; $i++) {
    $resInsert += testInsert($count);
    $resPush += testPush($count);
    $resMerge += testMerge($count);
}

echo 'foreach ... $old[] = $item;' . "\n";
echo sprintf("%.14f\n\n", $resInsert / $iter);

echo 'array_push($old, ...$new);' . "\n";
echo sprintf("%.14f\n\n", $resPush / $iter);

echo 'array_merge($old, $new);' . "\n";
echo sprintf("%.14f\n\n", $resMerge / $iter);

die;

function testPush($count)
{
    [$old, $new] = getArrays($count);

    $t1 = microtime(true);
    array_push($old, ...$new);
    $t2 = microtime(true);

    unset($old);
    unset($new);

    return $t2 - $t1;
}

function testMerge($count)
{
    [$old, $new] = getArrays($count);

    $t1 = microtime(true);
    $old = array_merge($old, $new);
    $t2 = microtime(true);

    unset($old);
    unset($new);

    return $t2 - $t1;
}

function testInsert($count)
{
    [$old, $new] = getArrays($count);

    $t1 = microtime(true);
    foreach ($new as $item) {
        $old[] = $item;
    }
    $t2 = microtime(true);

    unset($old);
    unset($new);

    return $t2 - $t1;
}

function getArrays(int $count)
{
    $halfCount = floor($count / 2);

    $old = [];
    for ($i = $halfCount; $i > 0; $i--) {
        $old[\Illuminate\Support\Str::random(3) . $i] = 'a';
    }

    $new = array_fill(0, $halfCount, 'a');

    return [$old, $new];
}
```

**Pull request merged**
