### PR TITLE
[5.1] Supporting FormRequests in Controllers' constructor

### PR DESCRIPTION
**Pull request by peterpan666**
This commit refers to this discussion #10908.

Don't know if it's the right way to go, but it seems to work perfectly fine :)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Things other can requests can be validated on resolving, so this would break everything processed by a queue worker for example.

**Comment by peterpan666** [comment]
I don't get what you mean?

**Comment by GrahamCampbell** [comment]
> I don't get what you mean?

Things other than form requests might want to be validated when they're resolved.

**Comment by GrahamCampbell** [comment]
That property is not unique to a form request.

**Comment by peterpan666** [comment]
Oh ok didn't knew that, sorry.

Maybe with something more specific? Like testing if artisan route:list is running?

Would that be better?

**Comment by peterpan666** [comment]
Tell me if I'm wrong but isn't this method only called after a route call?

**Comment by ArjanSchouten** [comment]
This whole discussion seems very strange to me! A request for a controller is specific to one route and one route is dispatched to one controller on one method (no HMVC;)). Not two methods! By bounding things on the controllers constructor you're destroying the whole idea. The injection of a ```Request``` object through the constructor seems strange to me! 

I think you've to use the IOC container with some bindings. For example do
```
App::bind('mycontroller', function ($app) {
    if ($app->runningInConsole()) {
        return MyController::createInstance($app->make('Illuminate\Http\Request'));
    }
    
    return new MyController();
});
```

Is this helping you or have I misunderstood the problem:smile:?

**Comment by taylorotwell** [comment]
Will break when running unit tests to actually test form requests.

**Comment by peterpan666** [comment]
Hi @ArjanSchouten if you read carefully this discussion #10908 you can see a bit of code that I use (see it here http://laravel.io/bin/rolJV ).

Anyway, it seems clearly that nobody likes it lol that's ok for me ;)

**Pull request closed without merging**
