### PR TITLE
[5.5] Ability to build a response using a fallback route name

### PR DESCRIPTION
**Pull request by themsaid**
Having:

```php
Route::fallback('ServersController@notFound')->name('notFoundServer');
```

In your exception handler or inside another route you can do:

```php
return Route::respondWith('notFoundServer');
```

This will run the `ServersController@notFound` action and return its response.

This is useful for when you want to catch a `ModelNotFound` exception and return a fallback route instead of the `404.blade.php` view.

### CODE REVIEW

**Comment by sisve** [comment]
Would this support route middlewares like StartSession so we can get session support on the custom 404 pages?

**Comment by themsaid** [comment]
@sisve yes

**Comment by decadence** [comment]
Is this can be used with any route name?

**Comment by browner12** [comment]
@decadence I was able to use it with any route name.

**Comment by decadence** [comment]
@browner12
Any route as long as it doesn't require parameters © @themsaid

**Comment by unstoppablecarl** [comment]
Where would be the best place to catch response exceptions and return `return Route::respondWith('notFoundServer');` to override of normal behavior in the whole app?

**Comment by themsaid** [comment]
@unstoppablecarl the exception handler.

**Pull request merged**
