### PR TITLE
[5.2] [WIP] Resource : allows to set a base for routes

### PR DESCRIPTION
**Pull request by lucasmichot**
Related to #5556 #12056 #11984
cc/ @ryanmortier @dwightwatson 

---

TODO
- [x] Test for master resource
- [x] Code for master resource
- [ ] Test for child resource
- [ ] Code for child resource

NEXT
- [ ] rename to base to wildcard ?
- [ ] allow base argument to be a closure ?

### CODE REVIEW

**Comment by garygreen** [comment]
Personally I like the name simply `wildcards` rather than `base`

**Comment by lucasmichot** [comment]
@garygreen yeah, this can be changed

**Comment by lagbox** [comment]
So I guess I don't need to PR the working copy of this then :)

**Comment by vinicius73** [comment]
I really think this will be very useful!
@lucasmichot You can show a code example for this PR?

**Comment by dwightwatson** [comment]
Looks good. I think there's an even bigger argument for this to be a feature now we have implicit model binding, which won't work with pluralised bindings.

**Comment by lucasmichot** [comment]
Closing in favor of #12061

**Pull request closed without merging**
