### PR TITLE
[8.x] Set chain queue and connection only when explicitly configured

### LINKED ISSUE #35041: [8.x] Enexpected `withChain(...)` behaviour
- Laravel Version: `8.12.3`
- PHP Version: `7.4.11`
- Database Driver & Version: `mysql  Ver 8.0.19 for macos10.15 on x86_64 (MySQL Community Server - GPL)`

### Description:

There are 3 classes:

#### Base job

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;

abstract class BaseJob
{
    use Queueable;
}
```

#### `JobHigh` that should be processed in the `high` queue

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class JobHigh extends BaseJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, SerializesModels;

    public $queue = 'high';

    public function handle()
    {
        //
    }
}
```

#### `JobMedium` that should be processed in the `medium` queue

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class JobMedium extends BaseJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, SerializesModels;

    public $queue = 'medium';

    public function handle()
    {
        //
    }
}
```

While in Laravel 7 (`7.28.4`) both `dispatch(new JobHigh); dispatch(new JobMedium);` and `JobHigh::withChain(new JobMedium)->dispatch()` throw jobs to the appropriate queues, in Laravel 8 (`8.12.3`) that's not a case for `withChain(...)`.

Is that a bug? Or that's a change that was accidentally not included `Upgrade Guide`.

### Steps To Reproduce:

```php
dispatch(new JobHigh);

dispatch(new JobMedium);
```

#### Laravel 7:

image

#### Laravel 8:

image

```php
JobHigh::withChain([
    new JobMedium,
])->dispatch();
```

#### Laravel 7:

image

#### Laravel 8:

image

### PR DESCRIPTION
**Pull request by themsaid**
This PR fixes https://github.com/laravel/framework/issues/35041

It sets the chain queue and connection only when specified. Otherwise the dispatcher will push each job in the chain to the queue/connection assigned to it.

### CODE REVIEW

**Comment by hivokas** [comment]
Should we also do the same with delay and maybe other properties?

**Comment by themsaid** [comment]
@hivokas did it for delay as well.

**Comment by taylorotwell** [comment]
Is this the behavior we want? For example, if I do:

```php
Bus::chain([
    (new Job1)->onQueue('foo'),
    new Job2,
])->onQueue('bar');
```

Don't I want Job1 to still run on the `foo` queue since I explicitly specified it? While Job2 would run on the `bar` queue since it had no explicit queue specification?

**Comment by hivokas** [comment]
@taylorotwell @themsaid thanks guys!

**Pull request merged**
