### PR TITLE
[5.6] Created UIKit pagination view

### PR DESCRIPTION
**Pull request by ConsoleTVs**
## Purpose
Since not everybody uses bootstrap 3 / 4, other pagination templates should be added for easy pickup. As far as I know, semantic UI has already been added. So I'm willing to add a few more, starting with UIKit. If you would like, I could be adding a few more for other well-known CSS libraries (like bulma).

## Screenshot

image

### CODE REVIEW

**Comment by deleugpn** [comment]
user-land stuff?

**Comment by Dylan-DPC** [comment]
This is not a bug. You can open a proposal in the laravel/internals repo

**Comment by m1guelpf** [comment]
@ConsoleTVs You migth want to PR this to the [UIKit Preset repository](https://github.com/laravel-frontend-presets/uikit3) instead.

**Comment by ConsoleTVs** [comment]
Wondering why semantic UI have it's place here then ?

**Comment by taylorotwell** [comment]
I think I'll leave this to user-land for now.

**Pull request closed without merging**
