### PR TITLE
[5.8] Fix problem with methods using executeRaw() using Redis Cluster

### PR DESCRIPTION
**Pull request by sera527**
Methods Redis::rawCommand() and RedisCluster::rawCommand() has incompatible interface, so methods zadd() and exists() need different realisation for PhpRedisClusterConnection.
More details in the issue: #29637

### CODE REVIEW

**Comment by taylorotwell** [comment]
Hmm, I use PhpRedis on Vapor with delay without issue.

**Comment by sera527** [comment]
@taylorotwell 
If  I modify method `Illuminate\Redis\Connections\Connection::command()` and run the code from the issue
```php
public function command($method, array $parameters = [])
    {
        $start = microtime(true);

        $result = $this->client->{$method}(...$parameters);
dd($method, $parameters, $result);
        $time = round((microtime(true) - $start) * 1000, 2);

        if (isset($this->events)) {
            $this->event(new CommandExecuted($method, $parameters, $time, $this));
        }

        return $result;
    }
```
I get the following result:
```
"rawCommand"
array:4 [
  0 => "zadd"
  1 => "queues:{some_queue}:delayed"
  2 => 1566892077
  3 => "{"displayName":"App\\Jobs\\SomeJob","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"delay":null,"timeout":null,"timeoutAt":null,"data":{"commandName":"App\\Jobs\\SomeJob","command":"O:16:\"App\\Jobs\\SomeJob\":7:{s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";s:12:\"{some_queue}\";s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";O:25:\"Illuminate\\Support\\Carbon\":3:{s:4:\"date\";s:26:\"2019-08-27 07:47:57.491223\";s:13:\"timezone_type\";i:3;s:8:\"timezone\";s:3:\"UTC\";}s:7:\"chained\";a:0:{}}"},"id":"lp3cKUYhKDGrREwMVDnilS6FyGm1phSk","attempts":0}"
]
false

```
As you can see, the first parameter to the function comes "zadd" - name of command. 
But according to the description of the method `RedisCluster::rawCommand() `, the first parameter should be $nodeParams.
```php
/**
     * Send arbitrary things to the redis server at the specified node
     *
     * @param String | array $nodeParams key or [host,port]
     * @param String         $command    Required command to send to the server.
     * @param mixed          $arguments  Optional variable amount of arguments to send to the server.
     *
     * @return  mixed
     */
    public function rawCommand($nodeParams, $command, $arguments) { }
```
The $result is false, which means that the command was not executed and the record did not get into the Redis.

**Comment by taylorotwell** [comment]
Curious how you tested this since you are extending a private method which isn't allowed in PHP?

**Comment by sera527** [comment]
Do you mean the `applyPrefix()` method? Yes, I agree that in this case I did wrong.
But still, do you agree that the problem I described is present?

It seems to me that the extending of the `PhpRedisClusterConnection` class from `PhpRedisConnection` is incorrect. These classes must implement the interface `Illuminate\Contracts\Redis\Connection` but have separate implementations. You agree with me? If you agree, then I could deal with changing the `PhpRedisClusterConnection` class.

**Comment by taylorotwell** [comment]
Well, sure, the issue may be present, but I'm curious how to are sure you fixed the issue since your PHP code submitted in the PR will not run without an error?

**Comment by taylorotwell** [comment]
Closing pending inactivity and because code is not valid PHP and therefore could not have been tested at all. There may still be a bug here but I can't merge totally unproven solutions into the code base of the framework. Feel free to resubmit code that you have run and tested.

**Pull request closed without merging**
