### PR TITLE
[5.8] Improve Resource Nested Casting to Array

### PR DESCRIPTION
**Pull request by dbpolito**
Fix for https://github.com/laravel/framework/pull/28313#issuecomment-486756137

This handles better nested resources.

### CODE REVIEW

**Comment by dbpolito** [comment]
@mathieutu hey... this should fix the problem you pointed.

**Comment by mathieutu** [comment]
Hi, I'm sorry but nope, this can't work too. 😕

Quick example, modify your test resource with 
```php
 public function toArray($request)
    {
        return [
            'id' => $this->id,
            'title' => $this->title,
            'custom' => true,
            'linkedPost' => self::make($this->whenLoaded('linkedPost')),
            'otherPost' => $this->mergeWhen(!$this->stop, new Post(['stop' => true])),
            'collection' => collect(['foo', 'bar']),
			'object' => (object) ['foo' => 'bar'],
        ];
    }
```

This values are _standard_ ones and so it should work with them. But there are a infinity of objects that are automatically parsed when transformed to json, so  you can't handle all of them.

For me, and after thinking we can't avoid the json step here if we want a real array of scalar at the end (which is what are Resources for).

**Comment by taylorotwell** [comment]
Can we just revert all of this please?

**Comment by devcircus** [comment]
This can all be done using the existing methods on Resources. It's not a quick one-step process, but as you go outside the norm a little, it'll take  a few more steps to get there.

**Comment by taylorotwell** [comment]
We are going to be reverting this.

**Pull request closed without merging**
