### PR TITLE
[5.4] [WIP] Improve the Eloquent push method

### PR DESCRIPTION
**Pull request by sileence**
Currently the `push` method has issues when saving inverse ("belongs to") relations.

Let's say we have a new Post that belongs to a new Category:

```
        $category = factory(Category::class)->make();

        $post = factory(Post::class)->make();

        $post->category()->associate($category);

        $post->push();
```

Since the push method saves the model first and all the relations after, we run into this:

1. If the `category_id` field is `not nullable` we will get a constraint error.
2. If it is `nullable` we won't get an error but `category_id` will be null, because the Category will be created *after* the Post.

You can read more about the issue here: https://github.com/laravel/framework/issues/10531

And check my functional tests here: 

https://github.com/sileence/eloquent_push_tests/blob/master/tests/EloquentPushTest.php

This does not work with belongs to many or polymorphic relationships just yet, but I'd like to get some feedback.

### CODE REVIEW

**Comment by sileence** [comment]
I feel this is more a fix than a breaking change, so please let me know if I should submit this for Laravel 5.3 instead.

**Comment by taylorotwell** [comment]
I don't understand why its null if you're calling ->associate before push.

**Comment by sileence** [comment]
@taylorotwell because the category is not in the database just yet, the idea is to use push to save both the post and the category (the category first and then the post) or isn't that an intended behaviour of the method `push`?

**Comment by taylorotwell** [comment]
Well, my original intention behind push was that it was a "downward" action, although it does seem to save upward relations too probably just as a by-product. I never really pictured it being used in this fashion as it's a little bit of an awkward way to save things.

**Comment by taylorotwell** [comment]
Going to hold off on this.

**Pull request closed without merging**
