### PR TITLE
[5.3] Add workaround to use Memcached 3.0.0 with Many, Fix issues in #13002

### PR DESCRIPTION
**Pull request by nikkiii**
This fixes the issues with referencing null in #13002, along with supporting Memcached 3.0.0's changed `getMulti` call.

If the ReflectionMethod call isn't satisfactory, we could also compare versions with something like this:

`version_compare('3.0.0', phpversion('memcached'), '>=')`

### CODE REVIEW

**Comment by taylorotwell** [comment]
Yeah I would use `phpversion` instead of Reflection.

**Comment by nikkiii** [comment]
version_compare/phpversion doesn't seem to work as-is, my testing showed it was extremely unreliable, likely because of the "beta" designation on 3.0.0.

Version comparison using preg_match, or even strpos possibly? I'd hate to do it, but it could be cleaner than Reflection...

**Comment by GrahamCampbell** [comment]
Do a compare on the extension version.

**Comment by taylorotwell** [comment]
version_compare and probably phpversion do not consider beta or RC releases to be final releases. But, I still think that is probably the best way to determine the version.

**Comment by taylorotwell** [comment]
Can you post a link to the change-log for this Memcached 3.0 and how to install it?

**Comment by nikkiii** [comment]
The change is not exactly documented well, but:
https://github.com/php-memcached-dev/php-memcached/issues/229

It's the standard package in Dotdeb and possibly Ubuntu 16.04 PHP7 installs, and manual build/installation information can be found here: https://github.com/php-memcached-dev/php-memcached

**Pull request merged**
