### PR TITLE
[8.x] Columns in the order by list must be unique

### LINKED ISSUE #37581: L8.45 - Undefined index: column
- Laravel Version: 8.45.0
- Database Driver & Version: MariaDB 10.3 and 10.5

### Description:

After update Laravel from 8.44 to 8.45 I am receiving this error: "undefined index: column". It happens here:

https://github.com/laravel/framework/commit/7ad6ba202920e28c8fc8c78df55a92743d223478#diff-2ed94a0ea151404a12f3c0d52ae9fb5742348578ec4a8ff79d079fa598ff145dR1988

### PR DESCRIPTION
**Pull request by Javdu10**
Sorry for the inconveniences...

See:  #37505 for more context
Fixes: #37581

### CODE REVIEW

**Comment by BrandonSurowiec** [comment]
@Javdu10 Would be a good idea to add a regression test using `orderByRaw()`.

**Comment by Javdu10** [comment]
@BrandonSurowiec done, I'm not sure what form it should have, let me know if it's correct

**Comment by BrandonSurowiec** [comment]
@Javdu10 Looks good to me!

**Comment by driesvints** [comment]
This PR was reverted because it continued to break things. See https://github.com/laravel/framework/pull/37647

**Comment by Javdu10** [comment]
Hello @driesvints, thank you for the notice!

@taylorotwell, that person's test pass if it's not overridable by calling order by again (see: https://github.com/laravel/framework/pull/37505#issuecomment-851547168)

So what should we do?

**Comment by driesvints** [comment]
@Javdu10 I doubt we'll be making more changes to this for the time being, sorry.

**Pull request merged**
