### PR TITLE
[5.2] Fix environment setting

### PR DESCRIPTION
**Pull request by nowak-ninja**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Don't worry about the CS. StyleCI automatically merges the fixes after we merge PRs. Also note that you can download and apply the diff StyleCI gives instead of manually making fixes.

**Comment by flashek** [comment]
@GrahamCampbell good point, I'm kind of newbie in making PRs :)

**Comment by GrahamCampbell** [comment]
> I'm kind of newbie in making PRs here :)

No problem at all. ;)

**Comment by taylorotwell** [comment]
What does this actually do / fix?

**Comment by flashek** [comment]
@taylorotwell It fixes ability to run CLI in chosen environment based on `.env.*` file

**Comment by vlakoff** [comment]
Could `$app->detectEnvironment` be called sooner by the user? Because this method writes over `$this['env']`...

**Comment by taylorotwell** [comment]
What this code does is just not obvious from reading it. Perhaps there is a better solution another way.

**Comment by vlakoff** [comment]
Ouch, that's a complicated one.

* Refs notably #11844
* @taylorotwell, about [this change](https://github.com/laravel/framework/commit/90af3becf192e8b28c3c859a8dd3d81723935b55#diff-e7feeabc664abb49798da6517f205f40), are you sure Dotenv shouldn't load if config is cached? Aren't they two different things?

**Pull request closed without merging**
