### PR TITLE
[10.x] Strip token from config options when making new AWS (DynamoDB) clients

### PR DESCRIPTION
**Pull request by mmehmet**
* strip token from config options on DynamoDB clients
* only strip token for now

### CODE REVIEW

**Comment by driesvints** [comment]
This will need a much more thorough explanation why this is needed.

**Comment by mmehmet** [comment]
@driesvints this fixes the same issue that was mentioned [here](https://github.com/laravel/framework/pull/44979#issuecomment-1637267131) - using similar fix to that PR, which strips out the `token` element from the config, when using recent versions of the AWS PHP SDK (as mentioned in [this issue](https://github.com/aws/aws-sdk-php/issues/2567)) - but that PR does not fix the issue for the `CacheManager` - which also affected by this, when creating a new DynamoDB client

**Comment by joedixon** [comment]
Hey @mmehmet, I'm not sure how `token` is ever present in the top level of the `$dynamoConfig` array.

As far as I can see, that variable is created in the method and the `token` key is never set.

**Comment by mmehmet** [comment]
@joedixon you're right - it needs to be stripped from the 'credentials` array element - I will make a new PR

**Pull request closed without merging**
