### PR TITLE
[5.4] Call eval() magically since it's an invalid method name in PHP 5.6

### PR DESCRIPTION
**Pull request by themsaid**
[Reserved keywords](http://php.net/manual/en/reserved.keywords.php) can't be used as method names up until [PHP7](https://wiki.php.net/rfc/context_sensitive_lexer)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Is it a valid method "call"?

**Comment by themsaid** [comment]
Yeah, tested that.

**Comment by GrahamCampbell** [comment]
We can revert this on L5.5 though, right?

**Comment by tillkruss** [comment]
Yes.

**Pull request merged**
