### PR TITLE
[9.x] RateLimiting: Fix tooManyAttempts method

### PR DESCRIPTION
**Pull request by ismailnakkar**
The current usage of tooManyAttempts has some issues. In this pull request I tried fixing it
Currently, tooManyAttempts never resets when the timer finishes

### CODE REVIEW

**Comment by driesvints** [comment]
Please provide more info why the current way doesn't work for you.

**Comment by ismailnakkar** [comment]
As you can see, the function does not take into consideration the time limit, which means that it never resets when 1 minute passes. This makes RateLimiting unintuitive and I need to clear the cache key every time with the help availableAt method as a work around this

**Comment by ismailnakkar** [comment]
The method "attempt" does not work also because it relies on tooManyattemps method, and thus, when the check fails because too many attempts one time, it never resets

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Pull request closed without merging**
