### PR TITLE
[5.7] Added the ability to send an array to getJson method

### PR DESCRIPTION
**Pull request by vgirbes**
Added the ability to send an array to getJson method.

Like:
`$this->getJson('path/to', ['param' => 'test'])`

### CODE REVIEW

**Comment by jmarcher** [comment]
Is this breaking change really worth it when you could simply do:
`$this->getJson('path/to?param=test')`
Is even shorter and familiar to everyone.

**Comment by ludo237** [comment]
Agree with @jmarcher the change is not worth to be honest

**Comment by vgirbes** [comment]
But, what happens when you need to send a list of parameters?

I think it could be helpful, to be honest :-)

**Comment by jmarcher** [comment]
```
$parameters = collect($list)->map(function($value, $key){ return $key.'='.$value; })->implode('&');

$this->getJson('path/to?'.$parameters);
```

Yes is more code but I believe that not really often is this functionality needed.

**Comment by arjasco** [comment]
```php
$this->getJson('my/path?' . http_build_query([
    'param1' => 'value1',
    'param2' => 'value2',
    'param3' => 'value3',
    'param4' => 'value4',
]));
```
😄

**Comment by victordzmr** [comment]
Class `Symfony\Component\HttpFoundation\Request` builds query strings when an array of parameters is passed (see `create` method), so I don't understand why methods `get` and `getJson` should not accept these parameters. It is a functionality that is already implemented and should be used.

@arjasco's solution works, but it is what Symfony already does. Moreover, it is true that doing `$this->getJson('path/to?param=test')` works, but it is also true that `$this->getJson('path/to', ['param' => 'test'])` is more elegant and natural.

In my opinion, signatures of `get` and `getJson` are wrong and they should be changed, even though it is backwards incompatible. It's never too late to fix it. It would be more consistent with the framework and easier to use. Tests should also be modified, as method signatures have changed.

**Pull request closed without merging**
