### PR TITLE
[5.2] Job patch

### PR DESCRIPTION
**Pull request by amin101**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is technically a breaking change to the job contact. It says this method must not return anything.

**Comment by amin101** [comment]
your right, so whats the solution ?
having access to the released job id is a need

**Comment by taylorotwell** [comment]
It's not really a breaking change.

**Comment by GrahamCampbell** [comment]
Please at least update JobContract too then. ;)

**Comment by GrahamCampbell** [comment]
What about the sync job?

**Comment by GrahamCampbell** [comment]
I think this should only be allowed into L5.3, not 5.2.

**Comment by taylorotwell** [comment]
@GrahamCampbell why? how is it really breaking?

**Comment by GrahamCampbell** [comment]
It';s changing the definition of the job contract, so existing implementations in packages are broken because they now have to return an integer, but before, they were forced to return nothing.

**Comment by GrahamCampbell** [comment]
Say, for example, iron queue jobs.

**Comment by taylorotwell** [comment]
Well they aren’t “broken”, people just wouldn’t get an int, which they aren’t already so it’s not like it would break anything? But, whatever, just send it to 5.3.

**Pull request closed without merging**
