### PR TITLE
Readable code, remove elseif's and leave just the if

### PR DESCRIPTION
**Pull request by akiyamaSM**

### CODE REVIEW

**Comment by browner12** [comment]
Can you explain what benefit we get from this change? 

If the benefit is just readability, that's very subjective, and I would argue it is more readable the original way.

**Comment by akiyamaSM** [comment]
The same pattern applied in many places. And as you said its subjective. Let's wait and see.

**Comment by browner12** [comment]
Can you provide references to other places that pattern is used? I agree code consistency is important.

**Comment by taylorotwell** [comment]
No plans to merge at this time.

**Pull request closed without merging**
