### PR TITLE
[5.8] Add trans_if to the helpers

### PR DESCRIPTION
**Pull request by ahmadmayahi**
Hey guys 🙌🏼,

Today I came across a situation where I needed to translate a string based on a specific condition, so, inside blade template, I had something like this:
```php
if ($user->isAdmin())
    trans('user.hello-admin')
else
    trans('user.hello-user')

```
I was thinking why don't we have a helper that it can handle both situations, something like `trans_if`:
```php
trans_if($user->isAdmin(), 'user.hello-admin', 'user.hello-user')
```

> I know using ternary could make the if statement shorter, but is still an if statement.

### CODE REVIEW

**Comment by driesvints** [comment]
It's definitely not a bad idea but this is something you can add in your own codebase if you want. I'd really not want to see too much more helpers being added to the framework core.

**Comment by ahmadmayahi** [comment]
@driesvints You might be right, I also don't like to see many helpers, but let's see what others think about it.

**Comment by SjorsO** [comment]
A shorthand if statement uses a character less than your new helper: `trans($user->isAdmin() ? 'user.hello-admin' : 'user.hello-user')`

**Comment by mfn** [comment]
> not want to see too much more helpers being added to the framework core

IMHO especially global ones

**Comment by xuanquynh** [comment]
I agree with driesvints. I often do something like this in my own package, then share it between Laravel projects.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
