### PR TITLE
[5.5] Changing events property to avoid any conflicts with relations

### PR DESCRIPTION
**Pull request by arcanedev-maroc**
**Related to :**
 * Issue: #17959
 * PR: #17960

### CODE REVIEW

**Comment by fernandobandeira** [comment]
Maybe we should just document this as a reserved word somewhere since it won't be the only property name that may cause issues with relationship names.

Also if we were changing this personally i'd prefer to use something like ``` _events ``` since its shorter, this way we could maybe define and use a prefix to avoid these kind of conflicts in the future, still IMHO it's not worth changing this since it'll break packages that rely on this variable name...

**Comment by arcanedev-maroc** [comment]
Hi @fernandobandeira, 

It's not going to be prefixed with `underscore` because it's againts the PSR-2.

And since this change going to be a breaking compatibilty, i put it in the future release instead (`master` branch).

I like the `events` as relationship name because it make sense when you work with calendars.

**Comment by fernandobandeira** [comment]
According to ``` PSR-2 ```

> Property names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.

We are not prefixing it to indicate protected or private visibility we would be prefixing to avoid a conflict, also we can use another prefix if undescore is a bad thing, ``` PSR-2 ``` doesn't seems to restrict this. ( It's up to your interpretation :trollface:  )

Honestly docummenting it would be the best thing since you wouldn't create a BC and it seems like an edge case, just giving my opinion here... :smile: 

IK it won't look as nice as events but you can easilly rename it to something else, now think if a package is using this directly they'll have to make a check for versions >= 5.5 and use another variable just for this change that isn't really necessary...

**Comment by arcanedev-maroc** [comment]
If the `events` name is reserved for the model observers (HasEvents Trait) and may have conflicts when they are using it as table/relationship name.

It should warn us in the documentation before it's late 😢

**Comment by bryannielsen** [comment]
I'd love to know what the official decision on this is.  I have a few projects that refer to calendar events as well so I don't really want to rename the models/relationships if possible.

**Comment by taylorotwell** [comment]
Changed this to `$dispatchesEvents`.

**Comment by arcanedev-maroc** [comment]
Great job @taylorotwell 👍

**Pull request merged**
