### PR TITLE
 [8.x] Correct stack driver creator

### PR DESCRIPTION
**Pull request by HiHub-Online**
Hello.

### Description of problem
Logging processors must be used only on configured handlers.

**config/logging.php**
```php
<?php
return [
    'default' => env('LOG_CHANNEL', 'stack'),

    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['channel_1', 'channel_2'],
            'ignore_exceptions' => false,
        ],
        'channel_1' => [
            'driver' => 'monolog',
            'handler' => SomeHandler1::class,
            'handler_with' => [...]
            'level' => 'info',
            'tap' => [
                Service1SpecialTagAdd::class,
                PublicInfoAdd::class,
            ],
        ],
        'channel_2' => [
            'driver' => 'monolog',
            'handler' => SomeHandler2::class,
            'handler_with' => [...]
            'level' => 'error',
            'tap' => [
                Service2SpecialTagAdd::class,
                PrivateInfoAdd::class,
            ],
        ],
    ],
];
```

_All taps in this case is different monolog processors_

#### Currently in laravel this is equivalent to:
```php
$stack = new Monolog(
    $name,
    [
        new SomeHandler1(...),
        new SomeHandler2(...),
    ],
    [
        new Service1SpecialTagAdd(...),
        new PublicInfoAdd(...),
        new Service2SpecialTagAdd(...),
        new PrivateInfoAdd(...),
    ]
);
```

Log channel `channel_1` must not receive private data.
But he gets.

#### With this merg this convert to:
```php
$stack = new Monolog(
    $name,
    [
        new \Monolog\Handler\GroupHandler(
            [
                new SomeHandler1(...),
            ],
            [
                new Service1SpecialTagAdd(...),
                new PublicInfoAdd(...),
            ]
        ),
        new \Monolog\Handler\GroupHandler(
            [
                new SomeHandler2(...),
            ],
            [
                new Service2SpecialTagAdd(...),
                new PrivateInfoAdd(...),
            ]
        ),
    ],
);
```

This eliminates the ingress of unnecessary information from one channel to another.

<hr/>
Respectfully yours,
<br>HiHub developer,
<br>Корочагин Денис Владимирович.

### CODE REVIEW

**Comment by driesvints** [comment]
Taylor asked for more info why this is needed but this is the same description as the last PR. Please re-send this with a thorough explanation why you need this.

**Comment by HiHub-Online** [comment]
@driesvints Not same - i think i can reopen merge - and at first edit description in first merge.

**Comment by driesvints** [comment]
@HiHub-Online it's pretty much the same. Please add a thorough explanation in your next PR.

**Comment by HiHub-Online** [comment]
@driesvints 
With old code some private info added to specific log channel (with monolog processors) also added to all stack channels.
With this changes - this is not happening.

Is this description better? Or is my English terrible?

**Pull request closed without merging**
