### PR TITLE
[6.x] Add AsMorphPivot trait

### PR DESCRIPTION
**Pull request by idsulik**
The benefit of the trait is that you can add it to your custom model(which extends base `Model`, but not `Pivot` or `MorphPivot` model).  
There is already exists AsPivot trait which is useful, so I add AsMorphPivot for morph pivot models

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why would you have a morph pivot model that does not extend MorphPivot?

**Comment by idsulik** [comment]
@taylorotwell , because of the error - `Invalid parameter number: parameter was not defined (SQL: update "model_properties" set "status" = rejected, "updated_at" = 2020-09-23 12:48:00 where "" = section and "" = 469)`
```
$sectionProperty = factory(ModelProperty::class)->create([
  'relation_type' => ModelProperty::RELATION_TYPE_SECTION,
  'relation_id' => $section->id,
  'status' => ModelProperty::STATUS_DRAFT,
]);
$sectionProperty->status = $newStatus;
$sectionProperty->save();
```

It works only if I extends base Model and use AsMorphPivot trait

**Comment by idsulik** [comment]
@taylorotwell  One more reason https://github.com/laravel/framework/pull/25851 to use it on model which extends my own abstract model

**Comment by idsulik** [comment]
If extends MorphPivot and try to update the model I get the sql:
`update "model_properties" set "status" = ?, "updated_at" = ? where "" = ? and "" = ?` - where are morph column names?
image

ModelProperty is simple MorphPivot model:
image


It works only if I add the `AsMorphPivot` trait

**Comment by taylorotwell** [comment]
We aren't adding new features to 6.x and this also needs a lot more explanation. It feels like we should fix the root cause of your problem - not just slap everything in a trait and say you need to extend Model.

**Pull request closed without merging**
