### PR TITLE
[5.1] Make AuthManager use Guard interface

### LINKED ISSUE #9597: AuthManager must make use of Guard interface.
I am making my own guard that implements `Illuminate\Contracts\Auth\Guard` interface just like the original `Illuminate\Auth\Guard` does. I'm doing it without extending the original due to strong reasons.

The problem occurs when `AuthManager` calls `callCustomCreator()` inside which it does:

    if ($custom instanceof Guard) {
        return $custom;
    }

Since I did not extend original `Guard`, this will fail. So instead, `instanceof` should be done to `Illuminate\Contracts\Auth\Guard` to make sure my `$custom` is an instance implementing `Guard` interface.

### PR DESCRIPTION
**Pull request by ifeltsweet**
AuthManager should make use of Illuminate\Contracts\Auth\Guard interface instead of concrete Illuminate\Auth\Guard class to allow replacement of Guard implementation with a custom guard class.

Closes #9597.

### CODE REVIEW

**Comment by crynobone** [comment]
Shouldn't this go to 5.2? 

As of now, Guard contract does not have the following as it's contract: <https://github.com/laravel/framework/blob/5.1/src/Illuminate/Auth/AuthManager.php#L23-L27>

**Comment by ifeltsweet** [comment]
I've added missing method signatures into Guard contract.

**Comment by GrahamCampbell** [comment]
@ifeltsweet You can't do that. That's a breaking change.

**Comment by GrahamCampbell** [comment]
Revert that last commit.

**Comment by ifeltsweet** [comment]
@GrahamCampbell, yeah sorry. I've removed the last commit.

So taking into account what @crynobone said I'm guessing this won't be merged into 5.1, right?

**Comment by Arrilot** [comment]
I guess it's okay in 5.1 since ppl need it right now. It's kinda tricky to use but still better than nothing imo.
The missing methods can be added to the contract in 5.2.

**Comment by GrahamCampbell** [comment]
> The missing methods can be added to the contract in 5.2.

No! Setter methods NEVER go into our contracts.

**Comment by GrahamCampbell** [comment]
All you need to do is check the methods exist in the auth manager before calling them, then this is fine for 5.1 IMO.

**Comment by ifeltsweet** [comment]
@GrahamCampbell, should I add another commit to describe what you said?

**Comment by taylorotwell** [comment]
@ifeltsweet yes, probably.

**Comment by GrahamCampbell** [comment]
This looks better now.

**Pull request merged**
