### PR TITLE
[5.3] Rename $e to $exception

### PR DESCRIPTION
**Pull request by lbausch**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. Why would we want to rename this though? The meaning is already clear is it not?

**Comment by lbausch** [comment]
I think it's more consistent with the way it's handled in https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php where $e was renamed recently as well.

**Comment by GrahamCampbell** [comment]
What about every try catch?

---

Disclaimer: please don't PR that too. I was jsut trying to make the point that this change is unnecessary imo.

**Comment by lbausch** [comment]
Nevermind, I just thought this could make things more clear since it's not type hinted in the method definition. :)

**Comment by JoostK** [comment]
I like this change. When inside a `catch` block it is clear that `$e` is the current exception, as a method parameter however that context is lost. Given that the typehint is only in the phpdoc and not asserted in the method signature (in order to support PHP 7's `Throwable` and compatibility with PHP 5 at the same time) it would be nice to at least give it a proper name; and to be consistent with @lbausch earlier example.

**Comment by bobbybouwmann** [comment]
So if we want to do this we need to add multiple PR's for each class or directory? It might be nice to do it throughout the whole framework

**Comment by taylorotwell** [comment]
Kind of a breaking change. I see no need to rename all this throughout the framework. $e is pretty common to use for exceptions.

**Comment by bobbybouwmann** [comment]
@taylorotwell May I ask why this would be a breaking change? Or do you mean by breaking that it's not the same throughout the framework?

**Pull request closed without merging**
