### PR TITLE
[5.6] Update whereBetween for support values in wrong order

### PR DESCRIPTION
**Pull request by asanikovich**
I update whereBetween with adding array_reverse for support values in wrong order.
A also add a check for a count of values pass to method.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Why is this labelled 5.5 and targetted to master? :thinking:

**Comment by allok** [comment]
@Dylan-DPC updated.

**Comment by taylorotwell** [comment]
Just pass them in the right order to begin with.

**Comment by allok** [comment]
@taylorotwell It is not convenient to watch on this. Иecause of this, often there are errors, because it turns out wrong bindings.

**Pull request closed without merging**
