### PR TITLE
[12.x] Route aliases

### PR DESCRIPTION
**Pull request by 7snovic**
Adding the ability to alias a named route by another name/alias.

### Motivation
Considering the following scenario, we have a package that implements some UI features with a basic routes, and another package that implementing some functionalities that needed to be used within the first package, if the first package does not allow configuring it's used routes, there will be no direct way to integrate the two packages.
Although, the previous scenario is considered as an edge-case due to the bad design that had been followed in the first package, yet, aliasing routes remain a good features that may be added value if it had been implemented in Laravel.

### Usage
```php

Route::get('some-path/', 'Controller@method')->name('base-name');

Route::alias('alias-route-name', 'base-name');

// .... now we can use the defined alias as a route name when we try to retrieve the route info, for example
return redirect('alias-route-name');
```

reference discussion #51306

### CODE REVIEW

**Comment by crynobone** [comment]
Please describe the reasoning for this PR instead of just linking to a discussion.

**Comment by driesvints** [comment]
Feel free to mark this as ready once you added a thorough description. Thanks

**Comment by 7snovic** [comment]
@crynobone @driesvints I'd added some description to the PR. Not sure of the process, I just followed the Contribution section in the documentation, so, I am not sure if we should continue in the discussion approach or in the PR.

**Comment by 7snovic** [comment]
todo:
- throw an exception in case if the alias is already exists as a named route
- show the aliases in the `route:list` artisan command
- add test cases

**Comment by morloderex** [comment]
How will this work with route caching?

**Comment by 7snovic** [comment]
@morloderex good point, will consider it, thank you.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
