### PR TITLE
[x10] Feature/wrapper-spell-number

### PR DESCRIPTION
**Pull request by rmunate**
I know that at first glance we may see it as something very risky, but it is a great utility, the package already has all the validations and processing for various languages, reviewed by natives of different languages as well as tested and installed in thousands of projects.

Now we would have these solutions with the Laravel flavor:

```php

Number::spell(100)->toLetters();
// "One Hundred"

Number::spell(100, 'es')->toLetters();
// "Cien"

Number::spell(100, 'fa')->toLetters();
// "صد"

Number::spell(100, 'hi')->toLetters();
// "एक सौ"

Number::spell(123456789.12)->toLetters();
// "One Hundred Twenty-Three Million Four Hundred Fifty-Six Thousand Seven Hundred Eighty-Nine And Twelve"

Number::spell(123456789.12, 'es')->toLetters();
// "Ciento Veintitrés Millones Cuatrocientos Cincuenta Y Seis Mil Setecientos Ochenta Y Nueve Con Doce"

Number::spell(123456789.12, 'hi')->toLetters();
// "बारह करोड़ चौंतीस लाख छप्पन हज़ार सात सौ नवासी और बारह"

Number::spell(100)->currency('Dollars')->toMoney();
// "One Hundred Dollars"

Number::spell(100, 'es')->currency('Pesos')->toMoney();
// "Cien Pesos"

Number::spell(100, 'fa')->currency('تومان')->toMoney();
// "صد تومان"

Number::spell(100, 'hi')->currency('रूपये')->toMoney();
// "एक सौ रूपये"

Number::spell(100.12, 'en')->currency('Dollars')->fraction('Cents')->toMoney();
// "One Hundred Dollars And Twelve Cents"

Number::spell(100.12, 'es')->currency('Pesos')->fraction('Centavos')->toMoney();
// "Cien Pesos Con Doce Centavos"

Number::spell(100.12, 'hi')->currency('रूपये')->fraction('पैसे')->toMoney();
// "एक सौ रूपये और बारह पैसे"

Number::spell(100.65, 'pl')->currency('złotych')->fraction('groszy')->toMoney();
// "Sto Złotych I Sześćdziesiąt Pięć Groszy"

Number::spell(2)->toOrdinal(Number::ORDINAL_DEFAULT);
// "Second"

Number::spell(2, 'es')->toOrdinal(Number::ORDINAL_MALE);
// "Segundo"

Number::spell(2, 'es')->toOrdinal(Number::ORDINAL_FEMALE);
// "Segunda"
```

I ask you to see the documentation and consider it, if you wish I can adjust the sources or you can be part of this package and make it a great complement avoiding creating all the possible language logic on the main Core of the framework.

https://rmunate.github.io/SpellNumber/

### CODE REVIEW

**Comment by milwad-dev** [comment]
👎 I don't agree
If someone needs it, he can install it in his project

**Comment by rmunate** [comment]
> 👎 I don't agree
> 
> If someone needs it, he can install it in his project

I value your comment

**Comment by rmunate** [comment]
😔 Okay, I think I'll try to find a good name for a macro that allows you to use this new kind of frame.

'Number' as an entry to SpellNumber, it won't be easy but I may think of one.

**Comment by dennisprudlo** [comment]
@rmunate Here are some points why I think it's highly unlikely that this package will be included:

- **Dependency burden:** Adding a new package results in more burden for the maintainers to always keep the package in sync with the current Laravel version. They need to completely read and understand your code so they can be sure to include it (otherwise it's just a black box of code the team forces every Laravel developer to download)
- **Maintenance Responsibility:** In the end the Laravel team is responsible for the dependencies they include. So I would assume they would only include packages that are absolutely necessary – where it doesn't make sense to create an own solution – and where they can be sure that the package will be maintained and kept up to date. Even if you have these intentions, you are still some random developer offering this package and there is the risk of you just abandoning the package in a few weeks or months. The workload then lies once again with the Laravel team to remove your package as a dependency and find another solution for the spell methods that maybe some developers are already using.
- **Accuracy:** The Laravel team cannot be sure of the accuracy of the spell methods in your package. I just skimmed the package code and found a line that indicates replacing `illion` with `illion Von` in german. I couldn't think of a situation where this would make sense so I quickly loaded the package and tested it:

```php
SpellNumber::value(1_000_000.99)
    ->locale('de')
    ->currency('Euro')
    ->fraction('Cent')
    ->toMoney();

// Eine Million Von Euro Und Neunundneunzig Cent
```

As a german I can assure you there are some things wrong with this:
- **The replacement makes no sense.** "Eine Million Von Euro" is grammatically incorrect and it should simply be "Eine Million Euro." Even if the "von" was correct it would have to be written in lowercase.
- **Capitalization is wrong.** I found a `Str::title(...)` in the code that just capitalizes every word. This makes it easy but results in a wrong output as well. The "Eine" for example is correctly capitalized in case the output is at the beginning of a sentence but should be lowercased when it's not ("Eine Million [...] fehlen noch" but "Ich habe eine Million [...]"). Spellouts up to a million (but not including) are generally lowercased, so the output should/could be "Eine Million Euro und neunundneunzig Cent" (the "und" and "neunundneunzig" are lowercased).

I understand that it's hard to conform to all grammatical rules for all of the supported languages but I would expect nothing less from the Laravel framework when it includes such spellout functions and advertises them as multi-language capable. I'd then rather have a `Number` utility class that can only spell out the number in english (but it's accurate) and creating my own utility class for german numbers when I need it, instead of having a utility class that can spell out in different languages and the output is _more or less_ accurate and people not being native to the language rely on the spellouts accuracy because they can't verify it.

I don't know about the other supported languages such as Farsi, Hindi, Romanian and so on.

**Pull request closed without merging**
