### PR TITLE
[5.5] Use only created_at or updated_at (#10005)

### LINKED ISSUE #10005: Allow only create_at or updated_at
Currently Laravel forces users to use Blueprint::timestamps() to create `created_at` and `updated_at` (or disable both). If user need only of `created_at` or `updated_at`, they will need hardcode it.

**Suggestion is allow define separately this behaviours.**

Example:

```php
class User extends Model
{
    public $timestamps = false; // disable all behaviour
    public $timestamps = true; // enable all behaviour
    public $timestamps = [ "created_at" ]; // enable only to created_at
    public $timestamps = [ "updated_at" ]; // enable only to updated_at
    public $timestamps = [ "created_at", "updated_at" ]; // same that true
}
```

It'll not cause break-changing, I guess.

### PR DESCRIPTION
**Pull request by mpyw**
This resolves #10005

### CODE REVIEW

**Comment by taylorotwell** [comment]
I don't plan to implement this.

**Comment by mpyw** [comment]
Okay, I'll implement on my own traits

**Comment by mpyw** [comment]
### Another solution

We can set in the schema definition:

```php
$table->datetime('created_at')->default(DB::raw('CURERNT_TIMESTAMP'));
$table->datetime('updated_at')->default(DB::raw('CURERNT_TIMESTAMP'));
```

If we need to use both `created_at` and `updated_at`:

```php
public $timestamp = true;
```

if we need to use only `created_at`:

```php
public $timestamp = false;
```

**Comment by dsandber** [comment]
Hi Taylor, how come you're not planning to merge the PR that mpyw supplied?  

It's a fairly common occurrence to have a table that allows creates but not updates -- for example, a change history table, or a table that keeps track of e-mails sent.   In this case, it's a waste to have an updated_at column, since the records are never updated.

**Comment by salarmehr** [comment]
It's strange. In Laravel <5.5 setting `const UPDATED_AT = null;`  does the magic. not work in laravel 5.5 anyway.

**Comment by devcircus** [comment]
Merged last week. https://github.com/laravel/framework/pull/21178

**Comment by jbnv** [comment]
Why is Laravel hardcoding column names into the database migration in the first place? It's completely illogical that you can point to different names in the Eloquent model, but you're virtually forced to use those names when making your database in the first place. (Your choice is to use ::timestamp and ::softDeletes with the built-in names or manually create the fields on your own, which defeats the purpose of having ::timestamp and ::softDeletes in the first place.)

**Comment by devcircus** [comment]
The softdeletes method already accepts a string name for the column name and It's simple to add your own custom timestamps. Honestly, since there are now constants on the base model for timestamps, I don't see we couldn't pr the option to pass names to the timestamps method as well. 🤷🏻‍♂️

**Pull request closed without merging**
