### PR TITLE
[5.6] get contents of uploaded file

### PR DESCRIPTION
**Pull request by browner12**
sometimes when we upload a file, we don't actually care about the file itself, but rather the contents of the file.  this is simply a helper method to get the contents of the file

### CODE REVIEW

**Comment by sisve** [comment]
Should you be checking [is_uploaded_file](https://secure.php.net/manual/en/function.is-uploaded-file.php) to make sure no-one is tricking you into reading something they shouldn't be reading? Or perhaps check `$this->isValid()` which does this with support for testing?

**Comment by browner12** [comment]
Didn't know that function existed, good to know.  I like taking advantage of the existing `isValid()` method. Can I omit my `file_exists()` call then, does `is_uploaded_file` inherently check for the existence of the file?

```php
if ($this->isValid()) {
    return file_get_contents($this->getPathname());
}
```

**Comment by sisve** [comment]
I think you need both. The isValid() check doesn't call is_uploaded_file when you've created an UploadedFile for testing (it's a parameter in the constructor), so it would be nice to keep the error message for those cases to handle missing fixtures and such.

**Comment by browner12** [comment]
@sisve after digging in a bit more, I found we already check for a valid file here:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/File/File.php#L36

therefore I just went with `isValid()` for this method

**Comment by browner12** [comment]
what does `setup = lowest` mean on the travis build? is that referring to PHP versions, or composer dependencies?

**Comment by browner12** [comment]
found it.  debugging now why it passes on the normal run, but fails on the 'lowest'

**Comment by browner12** [comment]
Symfony changed the signature of their constructor when switching from `4.0` to `4.1`, which caused the tests to fail on the 'lowest' composer depenedencies.  This commit switches the test from using the `4.1` signature to the `4.0` signature so it passes for all users in the range of dependencies.  IMO, this was a BC break on Symfony's part that should never have happened, but we'll adjust to satisfy it.

symfony/http-foundation@4.0...4.1#diff-6c8d56052f6c60629eaaa4fca7887288L58

**Pull request merged**
