### PR TITLE
[5.1] Changes type casting to Swift's toString() method, enabling Exceptions

### PR DESCRIPTION
**Pull request by xfxf**
Changes type casting used in raw_message to use Swift's built-in toString() method, allowing Exceptions to be properly thrown. This works around PHP's inability for __toString() to throw an exception - see https://bugs.php.net/bug.php?id=53648

I did this as I had an issue with some of my code, and I was only getting unhelpful errors such as:
`exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Method Swift_Message::__toString() must not throw an exception' in /var/www/application/releases/release-last/vendor/laravel/framework/src/Illuminate/Mail/Transport/MandrillTransport.php:0 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []`

With this change, I'm now receiving useful exceptions detailing the actual problem.

This is updated & tested with 5.1, after discussions in PR #11030

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Are there any other places where this change needs making too?

**Comment by xfxf** [comment]
Outside of MandillTransport.php?  Possibly, but this change has been tested; I've got no quick way of testing additional changes in other parts of Laravel 5.1 currently outside of writing a bunch of test cases (I'm still working with 4.2 in the project where I'm using Laravel for now).

**Comment by lucasmichot** [comment]
@xfxf , I've just checked: there are many more.
All `(string) $message`should be replaced by `$message->toString()` in `src/Illuminate/Mail/Transport/*`
Each time `$message` is an instance of `\Swift_Mime_Message`

**Comment by xfxf** [comment]
@lucasmichot indeed, should affect anything using Swift_Mime_Image that tries to typecast to a string - I just didn't want to change things I can't test easily.  Have merged in your PR to my repo, so this PR should now represent your changes too.

**Comment by taylorotwell** [comment]
So is this ready to merge?

**Comment by xfxf** [comment]
Yes.

**Pull request merged**
