### PR TITLE
Add hydrateWith to hydrate models and their relations

### PR DESCRIPTION
**Pull request by dariusj18**
Create method to assist in hydrating models and their relations.

https://github.com/laravel/ideas/issues/1032

### CODE REVIEW

**Comment by driesvints** [comment]
Please submit this PR when it is ready, thanks.

**Comment by dariusj18** [comment]
I created this as a draft PR to elicit feedback and collaboration.

**Comment by driesvints** [comment]
@dariusj18 Only finished prs are reviewed

**Comment by dariusj18** [comment]
I guess I am confused then, I created the PR as a draft to indicate that it wasn't ready for review.  Is there a better process for collaboration?

**Comment by mfn** [comment]
TBH I also find this strange; what good is the draft mode for, then?

The guide at https://laravel.com/docs/8.x/contributions doesn't seem to be clear on that specific part, btw.

**Comment by driesvints** [comment]
Okay, we'll allow draft PR's from now on but they won't be reviewed or provided feedback on from the Laravel team until they're finished, out of draft mode and all tests are passing. I'll also send in a PR to the docs to clarify this.

**Comment by mfn** [comment]
Sounds nice: in case only non-draft PRs are reviewed, I assume whoever does it uses a bookmark like https://github.com/laravel/framework/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+ anyway

**Comment by dariusj18** [comment]
Closing this because I created it from 8.x branch rather than master as I should have, new pull request https://github.com/laravel/framework/pull/37304

**Pull request closed without merging**
