### PR TITLE
[7.x] Re-use `Router::newRoute()` inside `CompiledRouteCollection`

### LINKED ISSUE #32415: New route caching breaks usage of the custom Route class
- Laravel Version: 7.2.1
- PHP Version: 7.3.13
- Database Driver & Version: *

### Description:

New route caching system, which uses `CompiledRouteCollection` breaks usage of custom Route class. It breaks packages and solutions, which customize routing, like [illuminatech/url-trailing-slash](https://github.com/illuminatech/url-trailing-slash).

### Steps To Reproduce:

* declare custom `MyRouter` class extending standard `Illuminate\Routing\Router`

* declare custom `MyRoute` class extending standard `Illuminate\Routing\Route` with some custom logic.

* override `newRoute()` method for the router in the way it instantiates custom `MyRoute` instead of standard one

* define some routes

* use `php artisan route:cache` to cache the routes

As the result all additional logic placed in `MyRoute` is lost.

### Code snippet

```php
class MyRoute extends Illuminate\Routing\Route
{
    public function run()
    {
        // custom run logic
        // echo something for the test
        echo __METHOD__; // works only if routes are not cached
        return parent::run();
    }
}

class MyRoute extends Illuminate\Routing\Router
{
    protected function newRoute($methods, $uri, $action)
    {
        return (new MyRoute($methods, $uri, $action))
            ->setRouter($this)
            ->setContainer($this->container);
    }
}
```

Relates to https://github.com/illuminatech/url-trailing-slash/issues/4

### Suggestion

`CompiledRouteCollection::newRoute()` should invoke `Router::newRoute()` inside of it, so any custom route creation logic is not lost.
This however requires to change visibility of the method from `protected` to `public`.

### PR DESCRIPTION
**Pull request by klimov-paul**
Fixes #32415 

Re-use `Router::newRoute()` inside `CompiledRouteCollection`, allow to use single place for the custom route definition.

### CODE REVIEW

**Comment by driesvints** [comment]
I don't immediately see anything wrong with this so I guess it's fine. Can we remove the `->setRouter($this->router)` and `->setContainer($this->container)` calls as well in the old method?

**Comment by klimov-paul** [comment]
Redundant invocations of `setRouter()` and `setContainer()` have been removed.

**Review by driesvints — APPROVED** [review]

**Comment by pgrenaud** [comment]
@klimov-paul Your bug report said that current behavior was breaking custom `Route` class, but your fix just broke any custom `Router` class that was overriding the `newRoute()` method. That broke our custom `Router` and we now have to maintain a separate branch for when `laravel/framework >= 7.13.0`.

@driesvints A minor update should remain backward compatible and changing a method signature is definitely not. Is it possible to revert this and postponed this change for the next Laravel release? Thanks.

**Comment by driesvints** [comment]
@pgrenaud given that this has been done since a few releases already I don't think it's wise to revert and do another breaking change for anyone who already adapted their code.

**Comment by pgrenaud** [comment]
@driesvints I just notice that I got the version wrong and it's actually since `7.7.0`. I wish I had caught that sooner.

**Comment by driesvints** [comment]
@pgrenaud what's your use case for overwriting the method?

**Comment by pgrenaud** [comment]
@driesvints We have a custom router that provides localized routes. We added a custom method `Route::groupLocales()` to prefix URL with locales. For instance:

    http://example.com/en/home

Will get routed to the `home` route with the locale `en`.

You can find out more here: https://github.com/eXolnet/laravel-translation

**Comment by devcircus** [comment]
Definitely agree that method signature changes like this should never slip through. However it could be too late now as it may compound the problem. 🤦🏼‍♂️

**Comment by klimov-paul** [comment]
> we now have to maintain a separate branch for when laravel/framework >= 7.7.0.

It is sad to hear someone suffers from this update.
If it will give you some comfort, you do not need a separated branch.
PHP allows publishing of the protected method inherited from parent class. For example:

```php
class A
{
    protected function foo() {}
}

class B extends A
{
    public function foo() {} // no error! 
}
```

If you release a patch which `newRoute()` overridden as `public` it will work both for 7.x and 6.x.

**Comment by driesvints** [comment]
@klimov-paul the problem is that in this case it's the other way around. The upstream is now public but all downstreams who were overriding it are protected. And that does trigger an error.

@pgrenaud sorry you got caught by this. We try to pay attention to these things but sometimes things slip through. It's a little late to revert now unfortunately. We'll try to take care of this better in the future.

**Comment by pgrenaud** [comment]
@klimov-paul TIL! Thanks for letting me know. I'll look into it.

**Pull request merged**
