### PR TITLE
[8.x] Init the traits when the model is being unserialized

### PR DESCRIPTION
**Pull request by mtawil**
This change calls the trait initializers when the model is being unserialized; the same happened with the model boot methods.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for this. Please add some tests. :)

**Comment by mtawil** [comment]
@GrahamCampbell Sure! just gimme a few hours, and I will be back with tests 👍🏼

**Comment by taylorotwell** [comment]
If the model has already been booted, isn't the trait boot now going to run twice? Possible even more times if another model is unserialized?

**Comment by taylorotwell** [comment]
Can you provide an example of the problem you are trying to solve in your code?

**Comment by mtawil** [comment]
@taylorotwell, I believe I can think of any scenario of any model that uses any traits with initializations; the initializations won't be executed when the model being unserialized.

Also, check the [`Model` __construct](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Model.php#L190-L192) here:
```php
/**
 * Create a new Eloquent model instance.
 *
 * @param  array  $attributes
 * @return void
 */
public function __construct(array $attributes = [])
{
    $this->bootIfNotBooted();

    $this->initializeTraits();

    $this->syncOriginal();

    $this->fill($attributes);
}
```

It makes sense that the magic method `__wakeup` should behave the same as `__construct` do

**Comment by mtawil** [comment]
Wait, if the model is already booted, then why are you trying to re-boot it on `__wakup`? I guess the boot methods won't be executed again.

**Comment by mtawil** [comment]
@GrahamCampbell I've added the tests.

**Comment by gaborbencebekesi** [comment]
I ran into a problem with this. I put typed property into a trait and initialized in the initialization method. (This sounds a logical design pattern for me, but correct me if I'm wrong.) Then I put the model into cache and fetched; serialize and unserialize methods were called, so __wakup was activated. Needless to say, trait initialization method ran again and properties were set to default, I lost their state. Example:

```php
trait TestTrait
{
    protected string|null $property;

    protected function initializeTestTrait(): void
    {
        $this->property = null;
    }
}

class TestModel {
    use TestTrait;
}
```

I'm not sure whether this should be the expected behaviour. I would say no and here's my reasons.

- Before serialize is called on any model at any time, initialization has been completed. Serialization doesn't change this, so running initialization again is more likely to be reinitialization rather then initialization.

- _By default_ between serializing and unserializing, a PHP object should keep its state. In current implementation a trait initialization method is not idempotent out of the box. (But boot method is.)

I have some ideas to solve this, but first please share your option on this. Thank you.

**Comment by mtawil** [comment]
Hi @gaborbencebekesi,

I believe you can check the property state first before resetting it, like this way:
```php
trait TestTrait
{
    protected string|null $property;

    protected function initializeTestTrait(): void
    {
        if (! isset($this->property)) {
            $this->property = null;
        }
    }
}

**Pull request merged**
