### PR TITLE
[9.x] Added push method to Cache Repository 

### PR DESCRIPTION
**Pull request by foremtehan**
Hello laravel,

This PR added `push()` method to Cache Repository which allow to pushing items into exist cache key and return the items in collection instance.

```php
//before
Cache::put('foo', 'bar');

$key = Cache::get('foo');

$key[] = 'baz';

Cache::put('foo', $key);

Cache::get('foo');
// ['bar', 'baz]
```

```php
//after
Cache::push('items.key', 'bar');
// ['bar']

$items = Cache::push('items.key', 'baz');
// ['bar', 'baz]
```

### CODE REVIEW

**Comment by foremtehan** [comment]
Can someone please help me to write the actual test for this😬? Because this is my first PR in open source world and i dont know how to test this correctly, I mocked that but i couldnt test that it returns two items with instance of collection, the output only have one item

**Comment by taylorotwell** [comment]
You can put collections in the cache? Where are they serialized?

**Comment by foremtehan** [comment]
I often use this as macro (file driver) in my projects an it will work i dont know the rest,

So should i change the second arg of put to `$collection->toArray()` ?

**Comment by taylorotwell** [comment]
Looks like the other drivers do actually support it I guess.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by foremtehan** [comment]
@taylorotwell We really need something like `add` or `push` functionality for Cache system, Something that push value to existing key, I tried to PR this by you rejected it other framework have this method

**Pull request closed without merging**
