### PR TITLE
[5.3] Add seeJsonTypedStructure method 

### PR DESCRIPTION
**Pull request by welcoMattic**
Ref. https://github.com/laravel/internals/issues/193

I miss a testing method to assert a typed structure returned by API endpoint, it's why I've been worked on the `seeJsonTypedStructure` method

### CODE REVIEW

**Comment by taylorotwell** [comment]
I feel like we're getting a little carried away with all of these testing methods and they need to be provided via packages.

**Comment by mathieutu** [comment]
Hem.. Too bad, this could be really useful !
Weird to have to install a package just to test Json in a way as simple as that.

But apparently I'm not the only one, as @themsaid suggested a PR...

**Comment by welcoMattic** [comment]
👍 to @mathieutu, I spent time on it on suggestion of @themsaid. I think it's not a completely new testing method but a addition to JSON tests methods group. Except if we decide to put all of these methods into a third party package (ApiJsonTestingMethods for example), my opinion is that `seeJsonTypedStructure` fit in the actual state of Laravel.

**Comment by welcoMattic** [comment]
I really think that we miss some methods [here](https://laravel.com/docs/5.3/application-testing#testing-json-apis) to be able to test properly a JSON API. Not only my proposed method, but something like `seeJsonStructureEquals` to test a strict JSON structure. So, we could add them to Laravel, or extract actual JSON test methods to put them into a external package with our new methods. To be clear, we have to take a decision. Ping @taylorotwell @themsaid @mathieutu

**Comment by mathieutu** [comment]
@welcoMattic let's go for a package guy !
https://github.com/laravel/framework/pull/16492#issuecomment-262259292

**Pull request closed without merging**
