### PR TITLE
PHP7ize Laravel 4.2

### PR DESCRIPTION
**Pull request by kampernet**

### CODE REVIEW

**Comment by kampernet** [comment]
sorry, accidentally created a pull request to the 4.2 branch, am actually just trying to fork it and get it to run under PHP7 in a controlled way.

**Comment by GrahamCampbell** [comment]
Note that your changes here area breaking php 5.

**Comment by GrahamCampbell** [comment]
They are also breaking lots of packages by modifying method definitions.

**Comment by GrahamCampbell** [comment]
We fixed things in a better way on 5.1.

**Comment by kampernet** [comment]
hey thanks Graham, do you mind pointing me to where you fixed things in a better way in 5.1?  specifically how you made it runnable on both 5 and 7?  I searched the code base and am pretty sure I found direct references to the Throwable interface, I may not be understanding you correctly.

**Comment by jonstavis** [comment]
@GrahamCampbell are there any plans/is it possible to apply a fix like this for 4.2?  Would be awesome to deploy legacy apps with PHP7

**Comment by GrahamCampbell** [comment]
Only Laravel 5.1 is supported. We dropped support for 4.2 the same day 5.0 was released.

**Comment by jonstavis** [comment]
Thanks for your response.  Could you offer any advice for people wanting to run legacy apps on PHP7?  Seems like this person opened a PR to attempt a fix and is looking for feedback.  

For a lot of people the budget just isn't there to port a huge legacy app to 5.x considering the official docs basically say start from scratch.  There are no security issues with 4.2 as far as I know, so there really isn't any reason why one couldn't stick with 4.2 on an old app.

It seems like the big issue most people are hitting is the Whoops package.  Are there any other pitfalls that come to mind for those who want to attempt doing this?

Not asking for official support, just some advice from the experts.  Thanks very much!

**Comment by kampernet** [comment]
@jonstavis what I did in the end was extend the Illuminate\Exception\Handler class to do this:
    `		$e = $exception;
		if (!$exception instanceof Exception) {
			try {
				throw new Exception($exception);
			} catch(Exception $e) {
				// caught ya
			}
		}

		$displayer = $this->debug ? $this->debugDisplayer : $this->plainDisplayer;

		return $displayer->display($e);`

so basically, if it's not an exception, throw it as an exception ( to cast it to an Exception )

then I just also extended the Illuminate\Foundation\Application class and the ExceptionServiceProvider class to use my new Handler

**Comment by jonstavis** [comment]
Awesome!  This is a great idea, I'll give it a shot.  Thank you!

So the last bit of it is you just changed one line of bootstrap/start.php to

````
$app = new My\Custom\Application;
````

?

**Comment by kampernet** [comment]
yes, exactly, and in that subclass, override the registerExceptionProvider method to use your Service provider that overrides the registerHandler method to use your Handler that casts the Error / Throwable to an Exception.

**Pull request closed without merging**
