### PR TITLE
[7.x] Optimize Arr::forget() method

### PR DESCRIPTION
**Pull request by BSN4**
This PR replaces `while:array_shift` with  `foreach:unset` just like the other two PRs did  #32192 & #32282

### CODE REVIEW

**Comment by nguyenyou** [comment]
https://www.php.net/manual/en/function.current.php#116128
This note on PHP documentation said:

> If you do current() after using unset() on foreach statement, you can get FALSE in PHP version 5.2.4 and above.

Don't know if this should be considered...

**Comment by if4lcon** [comment]
didn't saw this not I guess we need array_shift ?

**Comment by if4lcon** [comment]
@nguyenyou tested `current` and `reset` both works on php 7.4
 reset is guaranteed to be the first item while `current` is based on the pointer at calltime

**Comment by taylorotwell** [comment]
Let's hold off on this for now. I don't want to introduce subtle bugs for very little real world performance gain.

**Comment by if4lcon** [comment]
@taylorotwell thanks

**Pull request closed without merging**
