### PR TITLE
[8.x] "Merge" two string

### PR DESCRIPTION
**Pull request by lbeauvisage**
Hi 

The purpose of this function is to "merge" a string over a placeholder 

this is pretty much the same idea as the pad function 

don't know if "merge" if the good word for this.

Thank's

### CODE REVIEW

**Comment by claudiodekker** [comment]
Definitely a neat addition! I can easily count the number of times I actually needed this on one hand, but the same could be said for padLeft etc., so..

Just for added context, this is referred to as [**Overtype** mode](https://support.microsoft.com/en-us/office/type-over-text-in-word-for-windows-62c15c48-0936-4902-affe-4cadd71b7038) in Microsoft Word, whereas generally it's simply referred to as [overwrite mode](https://www.webopedia.com/definitions/overwrite-mode/). Perhaps `overwrite` could be a better-suited name here?

**Comment by GrahamCampbell** [comment]
I agree merge is a bad function name. Maybe overlap, overlay, overwrite?

**Comment by lbeauvisage** [comment]
`overwrite` sounds good for me.

Do you want me to rewrite it with this name ?

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
