### PR TITLE
[8.x] Implement DynamoDB table command

### PR DESCRIPTION
**Pull request by driesvints**
This PR implements a new `cache:dynamodb` command. It'll set up the cache table for the current DynamoDB cache store connection. This saves people from having to do this manually in AWS themselves. I've also re-used the command in the DynamoDB cache store tests so it's also tested.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is something people should probably be doing using cloudformation etc?

**Comment by driesvints** [comment]
@GrahamCampbell that's already a barrier they'd need to overcome. This gives a very easy entry point to get started with DynamoDB caching.

**Comment by driesvints** [comment]
@GrahamCampbell I've documented on how to set it up using CloudFormation alongside this command: https://github.com/laravel/docs/pull/6951

**Comment by taylorotwell** [comment]
I don't think I will bake in a command for this.

**Pull request closed without merging**
