### PR TITLE
[8.x] Add test coverage for Mail::alwaysTo() and Mail::alwaysReplyTo()

### PR DESCRIPTION
**Pull request by clemblanco**
Just adding some test coverage.

Before
```
Mail Mailer (Illuminate\Tests\Mail\MailMailer)
 ✔ Global from is respected on all messages  2 ms
 ✔ Global return path is respected on all messages  2 ms
```

After
```
Mail Mailer (Illuminate\Tests\Mail\MailMailer)
 ✔ Global from is respected on all messages  2 ms
 ✔ Global reply to is respected on all messages  1 ms
 ✔ Global to is respected on all messages  1 ms
 ✔ Global return path is respected on all messages  2 ms
```

Linked to [laravel/docs #7620](https://github.com/laravel/docs/pull/7620) and #40561

### CODE REVIEW

**Comment by clemblanco** [comment]
Hey @driesvints I can see all PR builds are failing this today but none of it seems to be related to code changes.

Anything we can help with?

**Comment by driesvints** [comment]
@clemblanco seems like an upstream library is the culprit. I sent in a report: https://github.com/voku/portable-ascii/issues/74

**Comment by clemblanco** [comment]
Awesome, thanks @driesvints!

**Comment by driesvints** [comment]
We've fixed the build on 8.x so please rebase and mark as ready when tests pass. Thanks!

**Comment by samirmhsnv** [comment]
Is `alwaysTo` works on Notifications?

**Comment by clemblanco** [comment]
@samirmhsnv it works at the Mailer level so if your Notification is sent by email, yes it will only be sent to the address specified by `alwaysTo()`

**Comment by samirmhsnv** [comment]
But looks like it doesn’t work for me on notification emails.

Could queues affect `alwaysTo` ?

Because I’m using queue for toMail on notification.

**Comment by clemblanco** [comment]
Sorry @samirmhsnv but I just tried on a blank new application and it does work as expected.

You need to make sure you restart your queue worker so the change is taken into consideration by the long running instance of your application.

**Pull request merged**
