### PR TITLE
[5.0] Improve Str::limit()

### PR DESCRIPTION
**Pull request by Gwill**
Improve Str::limit(). Do better with CJK text.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Could you include tests that were failing on the old implementation that are now passing please?

**Comment by GrahamCampbell** [comment]
I say "tests". A minimum of 1 test case would fine. :)

**Comment by phanan** [comment]
Just curious, how exactly does explicitly setting the encoding to 'UTF-8' instead of relying on `mb_internal_encoding()` (the default value) help in this case?

**Comment by Gwill** [comment]
@phanan, In some encoding the non-ascii charsets are too long (more than 2 ascii charset width). With UTF-8:


Chars|Width
-------|-------------
U+0000 - U+0019 | 0
U+0020 - U+1FFF | 1
U+2000 - U+FF60 | 2
U+FF61 - U+FF9F | 1
U+FFA0 -  | 2

**Pull request merged**
