### PR TITLE
[5.1] Fix docblocks params spacing

### PR DESCRIPTION
**Pull request by lucasmichot**
Fix docblocks params spacing

### CODE REVIEW

**Comment by JosephSilber** [comment]
Wow!

You didn't do this by hand, did you?

Hope you did this through some regex or something.

**Comment by lucasmichot** [comment]
PHPStorm Regex ;-)
`@param(\s+)(.[^\s]*)(\s+)(.*)` -> `@param  \$2  \$4`

**Comment by taylorotwell** [comment]
This kind of stuff just always ends up creating too much headache merge conflicts for me to deal with :|

**Comment by GrahamCampbell** [comment]
I'm pretty sure this PR was tried before and closed too?

**Pull request closed without merging**
