### PR TITLE
[11.x] Add `Request::fluent` method

### PR DESCRIPTION
**Pull request by stevebauman**
### Description

This PR adds a new `fluent()` method to the `Illuminate\Http\Request` class. 

Similar to the `Request::collect` method, being able to transform the request input to a `Fluent` instance helps in being able to transport the input data around your application (such as an action or a queued job) and provides you null-safe access instead of using an array.

### Usage

Consider an action that consumes a `Fluent` instance to access request data safely that may be nullable, while also being portable for easy testing without having to provide a request instance:

```php
use App\Actions\CreateComment;

class CommentController extends Controller
{
    public function store(CommentRequest $request)
    {
        $comment = (new CreateComment)->handle(
            $request->fluent()
        );

        return response($comment);
    }
}

class StoreComment extends QueuedJob
{
    public function __construct(
        public Fluent $data
    ) {}

    public function handle(): Comment
    {
        return Comment::create([
            'title' => $this->data->title,
            'body' => $this->data->body,
            // ...
        ]);
    }
}
```

### CODE REVIEW

**Comment by GavG** [comment]
Nice 👌 what're your thoughts on a FluentRequest class that can be used to type hint the controller function param to allow auto-injection of the fluent wrapped version, avoiding need for the manual call to ->fluent()?

Easy enough to write in userland I guess, but a nicety I'd probably never get round to in my projects.

**Comment by stevebauman** [comment]
@GavG I'm not sure if that'd be easily do-able, and/or worth the pay-off, imo. How would it work?

**Comment by GavG** [comment]
> @GavG I'm not sure if that'd be easily do-able, and/or worth the pay-off, imo. How would it work?

Having had a look through, I'd agree, it's not worth the pay off.

It could be done when resolving controller method params, but it wouldn't be very clean (casting to a subclass 👎).

Resolving it earlier on also wouldn't be feasible with the way Laravel routing currently works.

So I retract my idea, for the sake of saving one line of code 😂

**Comment by stevebauman** [comment]
@GavG haha okay sounds good! Appreciate the discussion though.

**Pull request merged**
