### PR TITLE
[5.1] Update Validator.php

### PR DESCRIPTION
**Pull request by chengguoqiang**
If this value is an instance of the array, failed when remove the files from the data

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please add tests.

**Comment by chengguoqiang** [comment]
#15659 for laravel:5.1
#15660 for laravel:5.3

**Comment by chengguoqiang** [comment]
tests #15663

**Comment by chengguoqiang** [comment]
@GrahamCampbell Add it

**Comment by themsaid** [comment]
The test passes without the change, please describe what issue you're trying to fix. Also please add a test that would fail without your changes.

**Comment by GrahamCampbell** [comment]
Replaced by #15663.

**Pull request closed without merging**
