### PR TITLE
[5.0] Allow jsonb field key notation for postgres

### PR DESCRIPTION
**Pull request by modmanx**
Connected with #8240 issue. After this commit it's possible to do this

```
$content = \App\Content::where('id', '=', 1)->select('id', "title->'en' AS title")->get();
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please fix the cs.

**Comment by modmanx** [comment]
Coding style - what did I miss?

**Comment by GrahamCampbell** [comment]
Braces are in the wrong place, and you need correct the placement of spaces.

**Comment by taylorotwell** [comment]
You can use DB::raw for this.

**Pull request closed without merging**
