### PR TITLE
added uuid to helpers

### PR DESCRIPTION
**Pull request by Chrisx84**
i found doing just uuid() easier to do then trying to remember Str::uuid() so i added it to the helper.php file and hope it helps others. Sorry if i screwed up, first time ever doing a PR.

### CODE REVIEW

**Comment by X-Coder264** [comment]
Just no, please. We need less helpers polluting the global namespace, not more. A bunch of these `Illuminate/Support` helpers that are just aliases to Str::something or Arr::something etc. should actually be deleted IMO.

**Comment by Chrisx84** [comment]
and assholes like you are why new developers are leaving the open source community.

**Comment by X-Coder264** [comment]
Lol. And why am I an asshole? For just stating my opinion in a completely polite way?

**Comment by BrandonShar** [comment]
@X-Coder264 It's because of your phrasing. "Just no, please" and implying that his PR is contributing to "pollution" are both pretty negative ways to review a pull request and are completely opinion based.

Had you said something like "I don't think we should be adding any more global functions to alias Str functions because ..." I doubt he would've minded at all.

**Comment by Chrisx84** [comment]
@BrandonShar ya it is how he said it that really hurt me

**Pull request closed without merging**
