### PR TITLE
[7.x] When trying to render a user exception fails, throw it

### PR DESCRIPTION
**Pull request by allowing**
If this exception is not thrown, developers may not be able to get information in time

### CODE REVIEW

**Comment by taylorotwell** [comment]
Please post how to recreate the issue you are trying to fix.

**Comment by taylorotwell** [comment]
The information may still be logged. If we rethrow here I think we risk exposing the exception details even in production.

**Comment by allowing** [comment]
Sorry, due to the time difference, I could not reply in time.

If the configuration file is abnormal, the services that depend on the configuration will be invalid.

Therefore, this exception is not re-thrown, and the developer will not know what happened.

As shown in the screenshot, there is an exception in the configuration, but the exception cannot be found from the error message.

微信截图_20200512181035
微信截图_20200513094515

**Comment by allowing** [comment]
@taylorotwell

**Pull request closed without merging**
