### PR TITLE
[5.3] add dc-helper-function (dump & continue)

### PR DESCRIPTION
**Pull request by willgopublic**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Any reason you targeted 5.3 rather than 5.2?

**Comment by willgopublic** [comment]
no , not really .. quite new to this stuff , thought i'd best select the latest master-branch.

**Comment by taylorotwell** [comment]
Going to hold off on this for now since you can just use `dump` function.

**Comment by willgopublic** [comment]
You can't "just use" the `dump` function .. ?
You'll have to create an instance and then call it's method,
which is something completely different from just using an alias like this.

I'd consider typing

    (new \Illuminate\Support\Debug\Dumper())->dump($x);

something different from typing:

    dc($x);

And I guess a Debug-helper wouldn't come into a deployment distribution of the software, so I don't see the overhead of such an alias. Nonetheless, I stick it in my bootstrap/app.php as long as it's not in the framework itself, so it's no problem at all.

**Pull request closed without merging**
