### PR TITLE
[WIP] [7.x] Switch to ramsey/uuid v4

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Let's wait an see if a v4.0.0 release comes out in time. Otherwise, we can put this into Laravel 8.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Ping me on Slack if he releases it in time and I will reopen this. Just want to clear it off my list while we wait.

**Comment by GrahamCampbell** [comment]
Sure. Otherwise, I'll retarget to master, for 8.x.

**Comment by mingyoung** [comment]
image
@taylorotwell @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Thanks, we're aware of this.

**Pull request closed without merging**
