### PR TITLE
[8.x] Remove useless parenthesis

### PR DESCRIPTION
**Pull request by lucasmichot**
This PR ensures that useless parentheses are removed.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Are all these huge changes going to give me merge conflict nightmares soon 😬

**Comment by GrahamCampbell** [comment]
👎 for this change, for that reason. StyleCI can also get rid of these brackets, if wanted. That is not in the Laravel preset at the moment.

**Comment by lucasmichot** [comment]
> Are all these huge changes going to give me merge conflict nightmares soon 😬

I would absolutely prefer to avoid this! I also hate conflicts

> 👎 for this change, for that reason. StyleCI can also get rid of these brackets, if wanted. That is not in the Laravel preset at the moment.

Any reason why this is not enabled?

**Comment by GrahamCampbell** [comment]
> Any reason why this is not enabled?

Because enabling it would cause conflicts, and applying that code style rule is not urgent. It doesn't do much to improve readability.

**Comment by driesvints** [comment]
Tbvh, there's lots of situations in this PR where parenthesis make the code more clear to read. Take the following for example:

```php
if ($times < 1 || ($when && ! $when($e))) {
    throw $e;
}
```

vs.

```php
if ($times < 1 || $when && ! $when($e)) {
    throw $e;
}
```

The former is much more clear and immediately discerns the logic on how the operation is handled while for the latter you'll have to process it more to know how it's actually handled. Both are syntactic correct but there's something to be said for code clarity.

**Pull request closed without merging**
