### PR TITLE
[5.8] Added `hasUser` method to Guard contract;

### PR DESCRIPTION
**Pull request by TBlindaruk**
- https://github.com/laravel/framework/pull/24518 in this PR was added method `hasUser` to the GuardHelper trait. As for me it will be useful to have this method in the contract.

### CODE REVIEW

**Comment by taylorotwell** [comment]
What does this improve in terms of user functionality?

**Comment by TBlindaruk** [comment]
@taylorotwell , 
In case if someone used the contracts instead of the concrete classes then they are available to use this method.

For now, I cannot use the method based on the contract.

**Comment by X-Coder264** [comment]
I completely agree with @TBlindaruk . I don't know why Laravel treats contracts like they don't matter and like if all people just use the concrete classes that the framework provides. I don't understand then what is the point of having any contract in the framework... @TBlindaruk as Taylor probably won't see this I'd suggest creating a new MR for this, as well as for https://github.com/laravel/framework/pull/25631

**Comment by X-Coder264** [comment]
Not to mention how these PRs get selectively merged, for example https://github.com/laravel/framework/pull/25616 got merged just two days ago.

**Comment by mpyw** [comment]
@taylorotwell 

> What does this improve in terms of user functionality?

Please consider who are developing on PhpStorm (with Laravel IDE Helper).

**Comment by xuanquynh** [comment]
@X-Coder264 When I works on a package for Laravel projects, I just requires laravel contracts for dependency injection but I have to call some methods from the concrete classes. It's very bad. I finally decide to use facades because calling some undefined methods of an interface has no meaning.

**Comment by xuanquynh** [comment]
@mpyw I think tt is not about the developers' tools. It's about software or code designing.

**Comment by X-Coder264** [comment]
> @X-Coder264 When I works on a package for Laravel projects, I just requires laravel contracts for dependency injection but I have to call some methods from the concrete classes. It's very bad. I finally decide to use facades because calling some undefined methods of an interface has no meaning.

@xuanquynh  Using the facade instead of the contract is the same thing as the root service that the facade will resolve from the container implements that same contract. Just because there are some magical docblocks on the facade that document methods that are present only on the concrete implementation doesn't make that any better. And if there is no other way to achieve some functionality other than to use some method that is not on the contract then that is a very good indicator that a method is missing on the contract. Whatever the case, using methods that are not on the contract for a Laravel package is a very bad thing.

**Comment by mpyw** [comment]
@xuanquynh Surely I know. I'm also insisting on the following code is **contract-based**.

> ```php
> Auth::guard()->hasUser()
> ```

**Pull request closed without merging**
