### PR TITLE
Update Reflector.php

### PR DESCRIPTION
**Pull request by Faks**
1.) added: bugfix to refactor method.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This change is incorrect.

**Comment by Faks** [comment]
> This change is incorrect.

why ?, can you explain ?
Note:
also please read this https://github.com/laravel/framework/issues/46515

**Comment by driesvints** [comment]
As you can see, this breaks the test suite. If you want union types support, we'd appreciate a PR without any current tests breaking. Thanks

**Comment by driesvints** [comment]
I just saw there's a better PR for this here: https://github.com/laravel/framework/pull/46511

**Pull request closed without merging**
