### PR TITLE
[7.x] Add support of relation using casted key

### PR DESCRIPTION
**Pull request by vdauchy**
This PR follow the bug report moved to ideas:

https://github.com/laravel/ideas/issues/2144

In summary this PR adds a function HasAttributes::onlyRaw() to get attributes as they shall be saved in database after casting. This is then used in all relations methods to get the real key's value to be used for the relation query.

In the code 2 patterns can be found:

`$this->child->{$this->foreignKey}` changed to: `$this->child->onlyRaw($this->foreignKey)[$this->foreignKey] ?? $this->child->{$this->foreignKey})`.

And:

`$model->getAttribute($this->ownerKey)` changed to:
`$model->onlyRaw($this->ownerKey)[$this->ownerKey] ?? $model->getAttribute($this->ownerKey)`

I believe this might be an inconsistent behavior as the first one authorize the user to create his own property which will be used instead of the one in `$attributes` .
In all changes, I in purpose let the `?? previous_behaviour` to reduce the risks of back compatibly breaks.

This make the code cumbersome, I belive the use of `$model->onlyRaw($this->keyName)[$this->keyName]` shall be enough. (however this will break some tests using real properties instead of $attribute[$key]).

A better/lighter name could be found to replace `$model->onlyRaw($this->keyName)[$this->keyName]` too..., if you got ideas, let's find something :-)

Please let's me know if you have any ideas, comments, etc...

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by VictorDauchy** [comment]
@taylorotwell Hi, I understand your point and I agree this PR has more changes that I would have like...
Is this a bug? Well Laravel just crash on columns being used as relation's key and having a cast. To me this looks like a bug but this only my point of view.
As suggested by @staudenmeir a more lightweight fix would be to add a string cast in front of every key value (as the bug is due to the values being used as array's keys) .
This would have minimal change and shall have no down side but to force the object return by the caster to have a __toString() the match the set() function.

**Comment by pricop** [comment]
> @taylorotwell Hi, I understand your point and I agree this PR has more changes that I would have like...
> Is this a bug? Well Laravel just crash on columns being used as relation's key and having a cast. To me this looks like a bug but this only my point of view.
> As suggested by @staudenmeir a more lightweight fix would be to add a string cast in front of every key value (as the bug is due to the values being used as array's keys) .
> This would have minimal change and shall have no down side but to force the object returned by the caster to have a __toString() that match the set() function.

Just encountered this today while trying to make a relationship between a fill-in table (calendar) and my `stats` table. Did you found a solution to this? It does sound like a bug to me too.

**Comment by vdauchy** [comment]
The only way I found was to use a different name for the cast, for example: 

- In the db I have `table.column_a`.
- For getter/setter using the cast I use a different name like `column_a_cast`

It's a bit misleading when doing queries with `where(...)` as you must the right column's name :-s

**Comment by pricop** [comment]
@vdauchy yeah, figured the same, thank you. In the meantime I've decided to drop the cast altogether from that field as it looked cleaner, and just did the date mutation in my views. I was still expecting Laravel to do a string conversion if the value was an object, but upon reading further, I can see why they wouldn't.

**Pull request closed without merging**
