### PR TITLE
[5.2] Delete unnecessary unit tests

### PR DESCRIPTION
**Pull request by sileence**

### CODE REVIEW

**Comment by sileence** [comment]
Still tweaking this. Don't merge yet, please.

**Comment by GrahamCampbell** [comment]
Why?

**Comment by sileence** [comment]
@GrahamCampbell https://twitter.com/taylorotwell/status/706142963701719040

TL;DR: The methods seeInElement, etc. are already being tested with integration tests in `FoundationInteractsWithPagesTest` which are better.

**Comment by GrahamCampbell** [comment]
Integration tests don't replace unit tests. They just compliment them. Having complete test coverage from both is never a bad thing.

**Comment by GrahamCampbell** [comment]
Meh, just read Taylor's tweet. I'll let him decide.

My vote here is :-1: for removing them. We should only remove them if updating them in the future becomes a mess.

**Comment by sileence** [comment]
I feel this is out of control: https://github.com/laravel/framework/pull/12639/files#diff-5b5766814f4efa52aba6c06a81febb90L156

The amount of code needed to mock something related to the crawler is absurd. TBH I was unable to test all the methods I wrote with that style.

That's why I came with this solution that looks much better: https://github.com/sileence/laravel-framework/blob/tests/5.2/deleteUnitTests/tests/Foundation/FoundationInteractsWithPagesTest.php

Easier to write, understand, maintain, etc. I want other developers who decide to contribute to the integrated test package to write these kind of tests instead of the other ones.

**Comment by GrahamCampbell** [comment]
> I feel this is out of control: https://github.com/laravel/framework/pull/12639/files#diff-5b5766814f4efa52aba6c06a81febb90L156

I agree there.

> The amount of code needed to mock something related to the crawler is absurd. TBH I was unable to test all the methods I wrote with that style.

I also agree that in those cases, the tests are a bit silly.

---

Maybe just remove the tests with crazy mocking, and keep the others?

**Comment by sileence** [comment]
@GrahamCampbell all of them have crazy mocking and are covered in the other file.

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell all of them have crazy mocking and are covered in the other file.

I don't agree. Ones depending on `mockInput` are fine, but `mockOptGroupSelect` is crazy.

**Comment by taylorotwell** [comment]
I agree basically all of these are pretty over-mocked.

**Pull request closed without merging**
