### PR TITLE
[5.8] provide a try_data_get method to not need a random string in-existence checking

### PR DESCRIPTION
**Pull request by joelharkes**
Even though it will be very rare the random string will ever hit a real value, it still hurt me looking at it. Very innovative but maybe my solution works better? please criticize it if not, so i can learn 👍 .

I provided this alternative try_data_get method with an out value as a way to get the caught value instead.

Its technically a copy of data_get(), like all the other methods that support the "dot" notation.

Ran the tests but not sure, i get failing tests because of: redis, memcache, mysql etc (is there no docker-compose file to run the tests?).

### CODE REVIEW

**Comment by mfn** [comment]
I'm against introducing new global helpers 👎

**Comment by joelharkes** [comment]
I could place it inside the class as private instance method.

i've been needing this method already a few times, since there is no distinction between null and undefined. any others? untill now ive just used, has/exists + get instead of this method.

**Comment by mfn** [comment]
Another thing is: your code has zero tests.

But before investing too much I wait would and gauge interest. Or you could just release your own package if you need it that often.

**Comment by driesvints** [comment]
Let's please not introduce any more new helpers if they don't provide a clear benefit to the framework as a function. I also don't see the benefit of adding this to the framework. You can add this to your own codebase if you want.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
