### PR TITLE
[5.3] HasOneThrough relationship

### PR DESCRIPTION
**Pull request by pdscopes**
An implementation of a HasOneThrough relationship. Constructs a relationship between the **FarParent** and **Related** models through the **Parent** model. Internally it creates the following SQL:

```sql
select `Related`.*, `Parent`.`ForeignKey`, `FarParent`.`ForeignKey`
from `Related`
 inner join `Parent`    on `Parent`.`ForeignKey`    = `Related`.`PrimaryKey`
 inner join `FarParent` on `FarParent`.`ForeignKey` = `Parent`.`PrimaryKey`
 where
     `FarParent`.`PrimaryKey` = ?
 and `FarParent`.`PrimaryKey` is not null
limit 1
```

 In part linked to Issue: https://github.com/laravel/framework/issues/8721

### CODE REVIEW

**Comment by taylorotwell** [comment]
This does not work like the Rails hasOneThrough. You can set it up as per their documentation and it does not work. This seems to function more like a "belongsToThrough" relationship.

**Comment by taylorotwell** [comment]
screen shot 2016-12-07 at 10 14 24 am

**Comment by taylorotwell** [comment]
If you setup the tables and models like the Rails documentation for hasOneThrough you will get the following error:

screen shot 2016-12-07 at 10 23 04 am

**Comment by taylorotwell** [comment]
Feel free to re-submit when that HasOneThrough use case documented in Rails works.

**Comment by pdscopes** [comment]
I will do, thank you for your feedback!

**Comment by kasperhartwich** [comment]
Damn. Was really hoping for it to be implemented this time. @pdscopes Hope you will add a new PR. :-)

**Pull request closed without merging**
