### PR TITLE
[11.x] Fix incorrect PHPDoc for Builder relation

### PR DESCRIPTION
**Pull request by kayw-geek**
In PHPStan, the parameters in a Closure are non-covariant by default. So, when you define a Closure with a parameter type-hinted as a subclass of Relation, PHPStan will throw the following error:

```bash
expects 
array<(Closure(Illuminate\Database\Eloquent\Relations\Relation<*, *, *>): mixed)|string>|string, 
array<string, Closure(Illuminate\Database\Eloquent\Relations\HasOne): void} given
```

This issue may be caused by #52729

### CODE REVIEW

**Comment by Plytas** [comment]
Also, I'm pretty sure it doesn't work with [nested eager loading](https://laravel.com/docs/master/eloquent-relationships#nested-eager-loading) as the value in the array can be another array.

**Comment by calebdw** [comment]
@Plytas,
> Also, I'm pretty sure it doesn't work with [nested eager loading](https://laravel.com/docs/master/eloquent-relationships#nested-eager-loading) as the value in the array can be another array.

Recursive array types are a bit painful, I'll add `array` to the definition and then open a PHPStan issue to see if it would be possible to get an `array-rec` type

**Comment by kayw-geek** [comment]
PHPStan playground is not support, but PHPStan program is supported.

**Comment by calebdw** [comment]
> PHPStan playground is not support, but PHPStan program is supported.

Sorry, you're mistaken here---the playground **is** the phpstan program. The only reason why you're not seeing errors in that the framework phpstan level is too low, however, this results in a phpstan parse error and the result is that it now knows nothing about the parameter type

**Comment by kayw-geek** [comment]
@calebdw 
I want to more accurate native type hint in my project.

**Comment by Plytas** [comment]
@calebdw I think `array` will be fine for now.

Regarding using `Relation` as type hint:
> In the meantime you can simply change your closure to specify the `Relation` instead of `HasOne`:
> 
> ```diff
> - $query->with(['foo' => fn (HasOne $q) => $q]);
> + $query->with(['foo' => fn (Relation $q) => $q]);
> ```

There's a slight issue with it if you need to perform other operations on the inner query like `->select()` or `->where()`. PHPstan will complain that those methods are not available on `Relation`.

**Comment by calebdw** [comment]
@Plytas, the Relation forwards those method to the mixed in Builder

**Comment by Plytas** [comment]
It does on runtime, but I wan't able to get PHPstan happy with it.

**Comment by calebdw** [comment]
> It does on runtime, but I wan't able to get PHPstan happy with it.

Then there's a bug somewhere, but it does work: https://phpstan.org/r/a17bc6f0-ca28-4dd5-9c66-fbebf28db054

**Comment by Plytas** [comment]
Thanks for going extra length to confirm it. I'll try to debug why it's not working on my end.

**Comment by calebdw** [comment]
Might be an issue with Larastan

**Comment by calebdw** [comment]
Larastan has ClassReflectionExtensions that handle the mixin magic---please raise an issue over there and I'll look into it

**Pull request closed without merging**
