### PR TITLE
Create alias-classes-ide-help.php

### PR DESCRIPTION
**Pull request by windqyoung**
help ide zend studio to autocomplete the alias classes's method.

when I installed the framework, I feel very sad, because I do not know where is the class(like App, Config, Route,...).
I use ctrl + mouse click the class name, zend do nothing.

in chinese below

让ide能知道如何提供别名类的方法, 参数.
我把框架装好后, 看到第一个类: Route::get('/', function () {})
我完全不知道这个类是在哪里定义的.
虽然后来能过看文档, 知道了fascade是怎么回事.
但我写代码的时候, IDE没办法提示.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This isn't even correct.

**Comment by GrahamCampbell** [comment]
If zend studio doesn't work properly, that's up to them to fix.

**Comment by windqyoung** [comment]
只是一个建议, 希望不仅程序能正确运行, 也有IDE工具的辅助.

**Comment by montogeek** [comment]
@windqyoung I think you can use https://github.com/barryvdh/laravel-ide-helper

**Comment by windqyoung** [comment]
think you.

**Pull request closed without merging**
