### PR TITLE
[5.3] Return a BaseCollection when an Eloquent Collection is mapped to no longer hold only models

### PR DESCRIPTION
**Pull request by BrandonShar**
Moving of #14565 into 5.3 since it introduces a breaking change.

Collections have confusing behavior when you map an instance of Database\Eloquent\Collection to something other than a collection of models.

Writing code like the following:

```
App\Post::all()->map(function($post) {  
  return ['title' => $post->title];
})->merge($anotherCollection);
```

Will throw a fatal error when getKey is called on what is no longer a model (since the collection is now a collection of arrays)

`PHP Fatal error: Call to a member function getKey() on a non-object in .../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php on line 240`

The toBase() function exists on instances of Database\Eloquent\Collection (and would solve this issue), but since the intention of a collection is to be treated just like any other data structure, I think requiring a developer to know so much about the specific implementation and prior use is a flaw.

I would also be in favor of changing the visibility of Illuminate\Database\Eloquent\Collection::toBase() to private, but since I may not be considering all use cases, I'd appreciate some feedback before I introduce that. It's not necessary for this PR to have value.

### CODE REVIEW

**Comment by BrandonShar** [comment]
tests had an issue when merged from my other branch. Closing while I take a look.

**Comment by BrandonShar** [comment]
corrected the test with new 5.3 change.

**Comment by JosephSilber** [comment]
Why didn't you also bring along the `toBase` method on the base collection?

Actually, if you check for `self`, you can also remove it from the Eloquent Collection class:

```php
public function toBase()
{
    return $this instanceof self ? $this : new static($this->items);
}
```

**Comment by BrandonShar** [comment]
The only reason I added that `toBase` method on the Base Collection was to prevent a breaking change in 5.2 (since that's where I branched from).  I didn't like that setup though since, while it worked, it was clearly just a hack to prevent a break and the implementation didn't make sense.  

Since Taylor preferred this PR into 5.3, I assume he's comfortable with it being a breaking change and I think this is the best/cleanest implementation.

**Pull request merged**
