### PR TITLE
[11.x] Add format artisan command

### PR DESCRIPTION
**Pull request by 1weiho**
Because Laravel Pint has been built into the Laravel framework in the recent release, this PR provides a new artisan command: `php artisan format`, offering developers a more convenient and intuitive way to format code.

https://github.com/user-attachments/assets/49d8d1c2-ec4b-461f-bc47-f847470e0547

## Usage

> The command's options all refer to the https://laravel.com/docs/11.x/pint#running-pint file, and the usage method is the same.

### Format all files
```bash
php artisan format
```

### Format specific files or directories
```bash
php artisan format app/Models
php artisan format app/Models/User.php
```

### Format and display the updated list and detailed changes
```bash
php artisan format -v
```

### Inspection without changes
```bash
php artisan format --test
```

### Format only uncommitted files
```bash
php artisan format --dirty
```

### CODE REVIEW

**Comment by milwad-dev** [comment]
I think using vendor dir is the best way:
```bash
.\vendor\bin\pint
```

But if you want to use artisan, you can create a command in your project.

**Comment by 1weiho** [comment]
> I think using vendor dir is the best way:
> 
> ```bash
> 
> .\vendor\bin\pint
> 
> ```
> 
> 
> 
> But if you want to use artisan, you can create a command in your project.

I completely agree, and I also always use the vendor directory myself. My point is that for some beginner Laravel developers, they might not easily discover Pint, but code formatting is a very important feature. They might be more familiar with commands starting with `php artisan`, and could even guess that `format` represents formatting. So, this command would be more user-friendly and intuitive for them.

**Comment by jorqensen** [comment]
> Because Laravel Pint has been built into the Laravel framework in the recent release

Worth noting that it's only a dev dependency [on the apps skeleton](https://github.com/laravel/laravel/blob/11.x/composer.json#L14).

I think people should leverage aliases in their shell of choice instead.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

**Pull request closed without merging**
