### PR TITLE
[5.3] Allow scopes return null

### PR DESCRIPTION
**Pull request by kuczmaja**
This is an example from Laracasts, Monstrous Code serie, Consider Normalizing episode.

``` php
class Coupon extends Eloquent\Model
{
    public function scopeHavingCode($code)
    {
        return $query->where('code', $code);
    }
}
```

I can perfectly use it like this:

``` php
$coupon = Coupon::havingCode('1234')->first();
```

If I use this line many times, I can use it other way:

``` php
public function scopeHavingCode($code)
{
    return $query->where('code', $code)->first();
}
```

and then:

``` php
$coupon = Coupon::havingCode('1234');
```

It is working. I have a Coupon object, what is totally expected and usefull.

But what if there are no coupons with given code?
I can expect that `$coupon` is `null`, but it is not.
`$coupon` will be instance of Illuminate\Database\Eloquent\Builder, and this is not super consistent for me. And it is not going to work as @JeffreyWay expected.

I propose to allow local scopes return `null`.

It also forces to return Builder object in the rest of local scopes, but it is consistent with current documentation.

``` php
// For example this will not be working:
public function scopeHavingCode($code)
{
    $query->where('code', $code);
}
// because of missing `return`
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
@acasar any thoughts?

**Comment by acasar** [comment]
It kinda makes sense, but it is a BC break. If we go with this, we need to mention in the upgrade guide that scopes must always return a value in 5.3.

In short, this won't work any more:
```php
public function scopeActive($query) {
    $query->where('is_active', 1); // fails due to the missing return statement
}
```

**Comment by kuczmaja** [comment]
[5.2 documentation](https://laravel.com/docs/5.2/eloquent#local-scopes) already says:
"Scopes should always return a query builder instance".
And all examples have return statement.
If developers followed the change would not be painful.
But still, that it is good to mention about this in the upgrade guide if you accept the change.

**Comment by BrandonSurowiec** [comment]
@kuczmaja Why not create a static constructor instead of a scope? Something like...

```
public static function havingCode($code) {
return (new static)->whereCode($code)->first();
}
```

That will solve your issue. I don't like the BC break.

**Comment by kuczmaja** [comment]
@BrandonSurowiec It cannot be stacked if you use static function.

```php
Coupon::unused()->havingCode('1234'); // havingCode must be a scope
```

But this is not a problem with this particular example. I showed as simple as possible that there is a part of code which might be a little confusing in some cases.

Maybe I tried to use scopes more than it is suggested, but after I watched that laracast I realized that it is possible I am not alone :)

**Comment by taylorotwell** [comment]
I think we should keep current behavior. I don't think scopes should be calling ->first() or ->get() at all.

**Pull request closed without merging**
