### PR TITLE
[11.x] Add magical enum feature

### PR DESCRIPTION
**Pull request by saMahmoudzadeh**
In this PR, a Trait named `MagicalEnum` has been added to `Illuminate\Support\Traits`, providing attractive and practical features for working with enums.

```php

enum MagicalUnitEnum
{
    use MagicalEnum;

    case Laravel;
    case Livewire;
    case Nova;
    case Horizon;
}

enum StringBackedMagicalEnum: string
{
    use MagicalEnum;

    case Taylor = 'Otwell';
    case Laravel = 'Framework';
}

enum IntBackedMagicalEnum: int implements EnumerationInterface
{
    use MagicalEnum, ExampleTrait;

    case ONE = 1;
    case TOW = 2;
    case THREE = 3;
}

```

### names() , values()

```php
StringBackedMagicalEnum::names() ; // [ 'Taylor' , 'Laravel' ]
StringBackedMagicalEnum::values(); // [ 'Otwell' , 'Framework' ]

MagicalUnitEnum::names(); // [ 'Laravel' , 'Livewire' , 'Nova' , 'Horizon' ]

// Unit enums only have names and do not have any values, unlike BackedEnums
MagicalUnitEnum::values(); // [] 
```

### count()

```php

StringBackedMagicalEnum::count(); // 2
IntBackedMagicalEnum::count(); // 3
MagicalUnitEnum::count(); // 4

```

### hasCase() , isValidEnumValue()

```php
StringBackedMagicalEnum::hasCase('Taylor'); // true
StringBackedMagicalEnum::hasCase('Mahmoudzadeh'); // false

StringBackedMagicalEnum::isValidEnumValue('Otwell'); // true
IntBackedMagicalEnum::isValidEnumValue(100); // false

MagicalEnum::hasCase('Laravel'); // true
MagicalEnum::hasCase('CodeIgnitor'); // false
MagicalEnum::hasCase('Wordpress'); // false

// Unit enums only have names and do not have any values, unlike BackedEnums
MagicalEnum::isValidEnumValue('Laravel'); // false

```

## toArray() , toReverseArray()

```php
StringBackedMagicalEnum::toArray(); // [ 'Taylor' => 'Otwell' , 'Laravel' => 'Framework'  ]
StringBackedMagicalEnum::toReverseArray(); // [ 'Otwell' => 'Taylor' , 'Framework' => 'Laravel' ]

IntBackedMagicalEnum::toArray(); // [ 'ONE' => 1 , 'TOW' => 2 , 'THREE' => 3]
IntBackedMagicalEnum::toReverseArray(); // [ 1  =>  'ONE' ,  2 => 'TOW' , 3 => 'THREE' ] 


// note: In Unit Enums, toArray and toReverseArray methods are identical.
MagicalUnitEnum::toArray(); // [ 'Laravel', 'Livewire', 'Nova', 'Horizon']
MagicalUnitEnum::toReverseArray(); // [ 'Laravel', 'Livewire', 'Nova', 'Horizon']
```

### isBackedEnum()

```php
MagicalUnitEnum::isBackedEnum();  // false
StringBackedMagicalEnum::isBackedEnum(); // true
```

### getBackingType()

```php

StringBackedMagicalEnum::getBackingType(); // 'string'
IntBackedMagicalEnum::getBackingType(); // 'int'
MagicalUnitEnum::getBackingType(); // null

```

### isImplementsInterface() , isTraitUsed()

```php
IntBackedMagicalEnum::isImplementsInterface(EnumerationInterface::class); // true
IntBackedMagicalEnum::isTraitUsed(ExampleTrait::class); // true
```

### make:enum
In Laravel 11, a new command, make:enum, has been introduced. In this feature, two stub files (enum.backed.stub, enum.stub) have been edited, and this trait has been added to enums.

### Testing
In this feature, I have added tests for all methods of the trait.

### Documentation
I'll send a separate PR to update the doc, if this PR is merged.

Thank you!

### CODE REVIEW

**Comment by mohammadqasemi** [comment]
Wow! awesome

**Comment by henzeb** [comment]
If this is not going to reach codebase: https://packagist.org/packages/henzeb/enumhancer which also takes away the challenge of working with backed or unit enums and handles uppercase/lowercase freedom, including a lot of other features.

I think a lot of features of this trait doesn't sense. Why would you count cases? Why checking if a case exists, if you can use tryFrom? Also the naming of it is not consistent with what we are used with Laravel.

**Comment by saMahmoudzadeh** [comment]
> If this is not going to reach codebase: https://packagist.org/packages/henzeb/enumhancer which also takes away the challenge of working with backed or unit enums and handles uppercase/lowercase freedom, including a lot of other features.
> 
> I think a lot of features of this trait doesn't sense. Why would you count cases? Why checking if a case exists, if you can use tryFrom? Also the naming of it is not consistent with what we are used with Laravel.

Thanks!, If this stage is merged, many features will be added to the enum in future.

**Comment by taylorotwell** [comment]
I think this is a great idea for a package. Not sure I would name the feature `MagicalEnum`.

**Pull request closed without merging**
