### PR TITLE
[8.x] Fix Queued MessageSent Listener With Attachments

### LINKED ISSUE #28847: Listening on Illuminate\Mail\Events\MessageSent causes Error code: 5 when email has attachments
- Laravel Version: 5.8.22
- PHP Version: 7.2.3
- Database Driver & Version: MySQL 5.7

### Description:

We are attempting to run a listener for the Illuminate\Mail\Events\MessageSent, this causes issues when the email being sent has attachments. This is happening while using the redis queue but i believe will happen when database queue is used as well.

The error returned is: Unable to JSON encode payload. Error code: 5

### Steps To Reproduce:

Create a listener that listens on Illuminate\Mail\Events\MessageSent, send an email with an attachment, when the queue picks up the job it'll throw the error mentioned above.

I believe this is due to the fact that the event exposes the entire Swift Message instance with the attachments raw data. I am not sure what the best solution is here but i thought i'd report it to see if there is anything that can be done or a workaround (i've searched and found nothing so far).

Thank You.

### PR DESCRIPTION
**Pull request by taylorotwell**
This fixes https://github.com/laravel/framework/issues/28847 by using `base64_encode` on the serialized message if attachments are present. 

This uses the new `__serialize` and `__unserialize` methods available in PHP 7.4+.

### CODE REVIEW

**Comment by vladislavtkachenko** [comment]
@taylorotwell Laravel 8.x require php ^7.4 ?
composer.json php ^7.3

**Comment by GrahamCampbell** [comment]
Doesn't matter. This code just does nothing on PHP 7.2 and 7.3.

**Comment by GrahamCampbell** [comment]
NB This PR was actually backported to Laravel 6 and 7 too.

**Comment by vladislavtkachenko** [comment]
Sorry, thank you

**Pull request merged**
