### PR TITLE
[5.1] Added cached compile and service path methods to the Application interface

### LINKED ISSUE #8229: Illuminate\Foundation\Console\ClearCompiledCommand uses methods not defined in contract
See https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Console/ClearCompiledCommand.php#L28

`Illuminate\Foundation\Console\ClearCompiledCommand::fire()` uses two methods that are actually not part of the Illuminate\Contracts\Foundation\Application interface:

`$compiledPath = $this->laravel->getCachedCompilePath(); $servicesPath = $this->laravel->getCachedServicesPath();`

As the command objects depend on the Application contract / interface only (https://github.com/laravel/framework/blob/5.0/src/Illuminate/Console/Command.php#L382), not the Illuminate\Foundation\Application implementation, **should any commands rely on methods not available in the interface**?

The `ClearCompiledCommand::fire()` seems to be tightly-coupled to the implementation class, not the interface.

### PR DESCRIPTION
**Pull request by proshanto**
Fixes #8229 and requested by @GrahamCampbell

### CODE REVIEW

**Comment by jonathanpmartins** [comment]
@proshanto, I think its not completely resolved. I have the same problem that @martinssipenko have. In this issue: https://github.com/laravel/lumen-framework/issues/137

**Comment by GrahamCampbell** [comment]
Yes, we know...

**Comment by GrahamCampbell** [comment]
Lumen 5.1 is NOT meant to be used yet.

**Comment by jonathanpmartins** [comment]
Only testing... no production!

**Comment by GrahamCampbell** [comment]
Same goes there really.

**Comment by jonathanpmartins** [comment]
@taylorotwell @GrahamCampbell Sorry... try it later on!

**Comment by proshanto** [comment]
@jonathanpmartins Application contract is not perfect. There are lots of things to be done. Laravel right now is tightly coupled to the foundation implementation.

**Comment by GrahamCampbell** [comment]
Not really. All we need to do is change our contracts so that they extend array access.

**Comment by franzliedke** [comment]
Nah, there are still quite a lot other places where methods are used that aren't in the contract. Take a look at some of the bootstrapper classes, for example.

**Comment by proshanto** [comment]
@franzliedke Yeah from some artisan commands too.

**Comment by GrahamCampbell** [comment]
I'm sure Taylor would accept PRs to 5.2 to improve this provided they're not adding a massive load of methods to the contracts. NB getter/setter stuff won't get accepted to contracts.

**Comment by proshanto** [comment]
:+1:

**Pull request merged**
