### PR TITLE
[5.5] Remove else

### PR DESCRIPTION
**Pull request by lilianjin**

### CODE REVIEW

**Comment by lagbox** [comment]
I ...

**Comment by browner12** [comment]
again, thank you for trying to contribute, but these PRs are traditionally not accepted because they add no value, and the ***better*** readability is just an opinion.

**Comment by devcircus** [comment]
¯\_(ツ)_/¯

**Comment by browner12** [comment]
hah, sometime I think he's just messing with me 😁

**Comment by mfn** [comment]
For reference: https://github.com/laravel/framework/pull/22492

**Pull request merged**
