### PR TITLE
Fix out of range value for jobs.attempts

### PR DESCRIPTION
**Pull request by Quezler**
If jobs.attempts reaches the maximum (255 by default), it does not fail the job, and throws exceptions to the Laravel log.

This proposal catches the exception and puts back the old value, while still updating the intended timestamp.

Due to the nature of the Jobs system, I opted not to delete the job when it reaches the max.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I think a better option would be to simply modify the migration to store a larger integer.

**Comment by Quezler** [comment]
Even with a larger integer jobs will continue retrying until they eventually reach the limit. @taylorotwell

**Comment by taylorotwell** [comment]
An unsigned big integer will keep retrying until long after you and I have ceased to exist.

**Comment by taylorotwell** [comment]
Even if the job ran every second it would keep retrying for many many thousands of years.

**Comment by Quezler** [comment]
Something to keep in mind is the [MySQL integer storage sizes](http://dev.mysql.com/doc/refman/5.7/en/storage-requirements.html), which will creep up 4 times as fast.
(since the current jobs + new jobs will continue failing)

This is not a big issue for most of us, but there are web/vps/dedi hosting services that only give you a small disk/ssd of ±10 gb, and then it will get dangerous.

**Pull request closed without merging**
