### PR TITLE
[5.2] better/faster session driver bug fix

### PR DESCRIPTION
**Pull request by j42**
This should pass the style guide

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thank you for the pull request. Could you please describe what bug this fixes?

**Comment by j42** [comment]
It fixes this bug here:

https://github.com/laravel/framework/pull/11520

Many other people have encountered it.  It's caused by a multitude of 3rd party packages.  Personally, I experienced it after using the `jenssegers/agent` package -- he usually writes great code -- so I think having an `isset` check here isn't such a bad idea.

Not to mention it's a cryptic failure state anyway.  It was hard to trace, and determine what went wrong.

**Comment by GrahamCampbell** [comment]
I don't agree that this is a bug that needs fixing in the core I'm afraid.

**Comment by j42** [comment]
Could you then explain why the error is occurring, what that cryptic missing key is, and why it's breaking so many 3rd party packages?

You must know something I do not :)

**Comment by GrahamCampbell** [comment]
@taylorotwell If this a bug fix, then it must go to 5.1 also.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/pull/11542

**Pull request merged**
