### PR TITLE
[5.0] Database postgres grammar: added timezone support

### PR DESCRIPTION
**Pull request by muratyaman**

### CODE REVIEW

**Comment by Arrilot** [comment]
1. Tests?
2. I bet the tests will show you that it does not work. Seems that you forgot to add a method to https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Schema/Blueprint.php
3. There is a convention to have a single set of methods for all DBMSs, so you probably need to add     fallbacks for other DBMSs (look at $table->json())

**Comment by muratyaman** [comment]
Thanks for your feedback. I think I've added more relevant code as you suggested. Please check.

As a summary, my intention was to highlight this;
In apps for users all around the world (even in apps for local users where DST applies) correct time zones should be set, after db connection is established, based on the user's time zone setting (rather than hard-coded setting in app). Then, data read/write ops should be automatically handled by the db.

For example, in PostgreSQL, date data are recorded in UTC format but they are converted to user's time zone with almost no PHP code involved like manual conversions back/fort.

**Comment by Arrilot** [comment]
Intedation is broken and all these notes and todos are not really needed.

The rest seems ok to me, but it's up to Taylor to decide anyway.

**Comment by shehi** [comment]
Shouldn't all times be in UTC and app itself compensate for TZ settings?! Why clutter the framework with additional layer of code which can be fixed programmatically - considering not all RDBMS's are TZ sensitive (I know PgSQL is, but MySQL isn't), adding this kind of control will make us add cluttering failovers to other drivers' grammars. Just my opinion anyway.

**Comment by muratyaman** [comment]
That does not make sense. Mysql also supports timezones. All dates are
already automatically stored as UTC, please read more about it. Why do it
by PHP while it can be solved by one line which is already in connectors
code after connect?!

**Comment by shehi** [comment]
@muratyaman By "TZ sensitive"ness I didn't mean MySQL doesn't have TZ support. MySQL rather doesn't have TZ-based field support, but instead only server-TZ settings. MySQL rather leaves all TZ related work to ```CONVERT_TZ()``` function - [and that is the *only* TZ-related function](https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html) it has at all. On the other hand, PgSQL being SQL-92-compliant, has full support for TZs in DDL level which auto-converts the data between TZ-enabled fields and non-TZ fields automatically, out of the box. So yea, I know a bit about this stuff :) 

I still strongly believe we shouldn't have TZ support within framework, to keep it RDBMS-agnostic (since we officially support multiple RDBMS, not all of which are SQL-92-compliant).

**Comment by muratyaman** [comment]
Yeah you might as well use flat files!
Thanks guys.

**Comment by shehi** [comment]
Don't worry! Thankfully (for you) I ain't in charge of merges here ;)

**Comment by muratyaman** [comment]
http://www.muratyaman.co.uk/wp/index.php/2015/04/managing-date-fields-properly-with-correct-time-zones-in-postgresql/

It is up to developers who are using the framework. They cannot do it if
you penalize them because of your love of imperfections of MySQL.

**Comment by GrahamCampbell** [comment]
Please fix the indention.

**Comment by muratyaman** [comment]
How can I break the indentation if I copy and paste an existing function and add "tz"?
I'll check my updates and push again.

It seems like PSR is not followed in this codebase:
http://www.php-fig.org/psr/psr-2/

**Comment by GrahamCampbell** [comment]
> It seems like PSR is not followed in this codebase:

Laravel 5.0 doesn't follow PSR-2. By the end of May, all Laravel projects will though. Laravel 5.1 will be the last to switch over to PSR-2.

**Pull request merged**
