### PR TITLE
[10.x] `setValue()` in Validator

### PR DESCRIPTION
**Pull request by joelharkes**
Followup of: https://github.com/laravel/framework/pull/46162

### Why

For package development, i would like to make it possible for rules to override data to make the validation 'type-safe'.
There is now no possible way to efficiently update a value inline. i can call `setData()` but it would completly reload the rules itself as well cause in big slowdown.

Alternatively I could sub-class Validator and add it myself, but this would greatly risk my package no longer being compatible with other packages AND people their own code repository.

### Usage:

```php
abstract class BaseTypeSafeRule implements ValidationRule, DataAwareRule, ValidatorAwareRule
{
    private array $data;
    private Validator $validator;

    public function setData(array $data)
    {
        $this->data = $data;
    }

    public function setValidator(Validator $validator)
    {
        $this->validator = $validator;
    }

    protected function modifyValue(string $attribute, mixed $value): void
    {
       // with this PR:
       $this->validator->setValue($attribute, $value);

        // previously: very slow!
        Arr::set($this->data, $attribute, $value);
        $this->validator->setData($this->data);
    }

    protected function translate(string $key, array $replacements = []): string|array
    {
        return $this->validator->getTranslator()->get($key, $replacements);
    }
}
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
Please fix the docblock to match the rest of the framework.

**Comment by joelharkes** [comment]
@taylorotwell I fixed to docs according to styleCI. 
I don't see it anywhere but is there a linter for this that i can just run to do it for me?

**Comment by bert-w** [comment]
@joelharkes Remove the parameter descriptions, they are not used anywhere else. I think that should be it. There is no styleci for it atm.

**Comment by mreduar** [comment]
I had been wanting to do this for a while. Thank you @joelharkes!

**Pull request merged**
