### PR TITLE
Add parameter to allow optional secret questions

### PR DESCRIPTION
**Pull request by simonhamp**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Eh, I don't really like those types of boolean values on methods.

**Comment by simonhamp** [comment]
@taylorotwell can you recommend another way to achieve this?

**Comment by Dylan-DPC** [comment]
> Eh, I don't really like those types of boolean values on methods.

This is odd considering https://github.com/laravel/framework/pull/22888#issuecomment-360071196 (which adds a boolean value to an existing function) was merged on the same day.

**Comment by simonhamp** [comment]
@Dylan-DPC I do understand from one point of view... the method call looks a bit ambiguous: `$command->secret('Question?', false, true)` so it's harder to know what each boolean means without IDE assistance/jumping to the source.

Until we get [named parameters](https://wiki.php.net/rfc/named_params) in PHP though, the best alternative is to pass an array, but this would be a breaking change or at least require a lot more messy/temporary code to make it BC. Plus that also breaks IDE help.

**Comment by Dylan-DPC** [comment]
I am not a fan of those "ambiguous call" as well and I might not even use them if named parameters were available. 

My point wasn't about the params but more about consistency across PRs.

**Comment by simonhamp** [comment]
I'm unlucky at Laravel PRs... but lucky in love, so it's ok 😄

**Pull request closed without merging**
