### PR TITLE
[8.x] Adds an `--install` option when using the `make:provider` command

### PR DESCRIPTION
**Pull request by lukeraymonddowning**
Hi guys,

Hope you're all well.

This PR is a small QOL improvement when using the `php artisan make:provider` command. It allows you to specify an `--install` option (or `-i` for shorthand) that will automatically add an entry in your `config/app.php` file.

The logic for inserting this into the file is taken from Telescope's `InstallCommand`: https://github.com/laravel/telescope/blob/4.x/src/Console/InstallCommand.php, with some modifications to make it more generic.

## Usage

Usage is identical to before, but now you can add the register option if desired:

```bash
php artisan make:provider MyVeryOwnServiceProvider --install
# Or
php artisan make:provider MyVeryOwnServiceProvider -i
```

The provider will be inserted under the `RouteServiceProvider` that ships with Laravel.

Thanks for all your hard work 🥳

Kind Regards,
Luke

### CODE REVIEW

**Comment by danharrin** [comment]
Hey Luke! This looks great. I usually register my providers in alphabetical order, to follow the others - any chance that could be the default behaviour here?

**Comment by lukeraymonddowning** [comment]
Decided to move to the more up-to-date and simpler Jetstream way of handling this: https://github.com/laravel/jetstream/blob/8cc54788c657142053a2e6becb4e406109830f8a/src/Console/InstallCommand.php#L474

**Comment by lukeraymonddowning** [comment]
@danharrin we certainly could do that. Will wait and see what the team say; I know that their official packages don't do that, so don't want to assume.

**Comment by lukeraymonddowning** [comment]
Also, think the tests might need re-starting; the failures seem to be non-related (to do with Redis and zstd compression)

**Comment by crynobone** [comment]
I feel `--install` has been the common term for this usage. At first read of the PR title, I assume `--register` related to Service Provider's `register()` method.

**Comment by lukeraymonddowning** [comment]
@crynobone good call. Will update 👍

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by rezaamini-ir** [comment]
Hello @lukeraymonddowning.
I think it doesn't make sense to put namespace under the RouteServiceProvider namespace.
What if we had changed the namespace of RouteServiceProvider or, what if we want to put the provider's namespace in alphabetical order or under all of the previous namespaces.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
