### PR TITLE
[11.x] Only create `framework/maintenance.php` file when using file driver

### PR DESCRIPTION
**Pull request by JaZo**
### Change
When you're using the cache based maintenance mode, Laravel still tries to create the `framework/maintenance.php` file. However, this file [does nothing when there's no down-file](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Console/stubs/maintenance-mode.stub#L4-L6), so basically it is useless. I moved the creation of this file to the file based implementation, so it's only created when relevant.

N.B. I deliberately left [the deletion](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Console/UpCommand.php#L43-L45) in the up command to make sure it is always deleted.

### Context
We're running our apps in multiple read-only containers and thus need to use the cache based maintenance mode. This works fine, but we always get an error because Laravel tries to create this `framework/maintenance.php` file on a read-only filesystem.

### CODE REVIEW

**Comment by taylorotwell** [comment]
This is the file that actually handles the request though, as you can see in the default public/index.php. So, if this file doesn't exist, all of the maintenance mode features like bypass, except URIs, etc. would be broken when using the cache driver.

**Comment by JaZo** [comment]
That maintenance file [does nothing when there's no down-file](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Console/stubs/maintenance-mode.stub#L4-L6), which is the case when you're using the cache driver. Also, when running a multi server environment, only the server where the down command is ran, will have the maintenance file and the others don't. Isn't this use case the whole point of the cache driver?

We're currently using features like bypass etc. using the cache driver on a read-only filesystem, so the maintenance file isn't present, and it is working fine. Please reconsider. I'm happy to help with another solution!

**Comment by johanrosenson** [comment]
I don't think that file is even required for the file based maintenance driver any longer. 

Since the real checks are done in [Middleware/PreventRequestsDuringMaintenance.php](https://github.com/laravel/framework/blob/d61d4f291c8954d1758bab2c58d4dbe73f7a8b3c/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php#L13)

So maybe your PR should be to remove it completely, not only for the cache based driver.

**Comment by donnysim** [comment]
@johanrosenson that middleware is not reach unless the standalone maintenance file allows the request to proceed to the framework with a bypass etc. as the middleware is also responsible for setting the bypass cookie, double checking everything etc..

**Pull request closed without merging**
