### PR TITLE
[8.x] Eager load pivot relations

### PR DESCRIPTION
**Pull request by lonnylot**
This allows you to use protected $with = []; on custom pivot models.

Since Pivot classes are `Model` classes we're just adding in this missing bit of functionality.

### CODE REVIEW

**Comment by ajcastro** [comment]
Putting this here for reference, https://github.com/laravel/framework/pull/37456

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by lonnylot** [comment]
@ajcastro Would you consider adding this support to your ajcastro/eager-load-pivot-relations package? If so, I can make a PR.

**Comment by ajcastro** [comment]
@lonnylot yes please thanks!

**Pull request closed without merging**
