### PR TITLE
[5.3] Fixed the bug of same multiple connection

### PR DESCRIPTION
**Pull request by Hanson**
see [issue #17747 ](https://github.com/laravel/framework/issues/17747)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
5.3 is closed for bug fixes now. Please send to 5.4 if still relevant on that branch.

**Comment by taylorotwell** [comment]
It hasn't been 6 months since 5.3 was released.

**Comment by taylorotwell** [comment]
This would be a breaking change, however.

**Comment by HanSon** [comment]
so how to fix this problem with a best solution?

**Pull request closed without merging**
