### PR TITLE
[5.1] Add user() helper

### PR DESCRIPTION
**Pull request by pascalschwientek**
get the currently authenticated user with a user() helper function.

### CODE REVIEW

**Comment by janyksteenbeek** [comment]
This would be a cool little helper to save some time. +1

**Comment by lukasgeiter** [comment]
Because `auth()->user()` isn't simple enough? :wink:

**Comment by pascalschwientek** [comment]
@lukasgeiter yes, that works too but just calling user() is a lot simpler in my opinion. You can also do session()->get(KEY) or just session(KEY).
Helpers are there to simplify stuff as much as possible and provide the easiest best to use api.
And a user() function would definitely do that.

**Comment by LiamSeys** [comment]
This function would be really useful. +1

**Comment by taiyaei** [comment]
Taylor previously closed this https://github.com/laravel/framework/pull/6485#issuecomment-64718554

:+1: though

**Comment by taylorotwell** [comment]
You can just define it yourself.

**Pull request closed without merging**
