### PR TITLE
[5.1] [Should be 5.0] Allow Toggling Route Filtering

### PR DESCRIPTION
**Pull request by crynobone**
This is useful for testing filters separately.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
?

**Comment by denaje** [comment]
Not sure why this was deleted, but it would be really useful.

**Comment by GrahamCampbell** [comment]
I've opened a new issue for this: #7360.

**Comment by crynobone** [comment]
Sorry, didn't realize it close the issue when I was spring cleaning my PR branches.

**Comment by GrahamCampbell** [comment]
Don't worry about it. :)

**Pull request closed without merging**
