### PR TITLE
[9.x] Add getModelChanges to HasAttributes

### PR DESCRIPTION
**Pull request by dbfun**
Our team constantly uses the same piece of code to get a list of changes in the model. We log these changes to a log file or a special database table. This allows you to keep track of the changes that have been made.

Example:

```
$model->getModelChanges();
```

Result:

```
array:2 [
  "name" => array:2 [
    "old" => "Otwell Taylor"
    "new" => "Taylor Otwell"
  ],
  "email" => array:2 [
    "old" => "taylor@laravel.org"
    "new" => "taylor@laravel.com"
  ]
]
```

### CODE REVIEW

**Comment by evgenmedia** [comment]
+1

**Comment by donnysim** [comment]
Do you use this before or after save? because usually this does not work after save, as the original and changed values are the same - syncOriginal is called after save.

**Comment by dbfun** [comment]
@donnysim, yes, saving the model resets changed model attributes, and you can't get changes.

We use this method in the model observer:

```
class PointObserver
{
    public function updated(Model $model): void
    {
        $changes = $model->getModelChanges();
        
        Log::channel('business')->info('Point updated', [
            'object' => 'Point',
            'object_id' => $model->getKey(),
            'action' => 'update',
            'result' => 'success',
            'data' => $changes,
        ]);
    }
}
```

**Comment by taylorotwell** [comment]
Hello! Feel free to add this to your own application in a base model.

**Pull request closed without merging**
