### PR TITLE
[5.5] Use dropAllTables

### PR DESCRIPTION
**Pull request by lkmadushan**
use drop all tables instead of rollback in database migrations trait

### CODE REVIEW

**Comment by ntzm** [comment]
This changes the behaviour

**Comment by lkmadushan** [comment]
@ntzm why?

**Comment by decadence** [comment]
It's dropping tables not doing rollback. It's not the same.

**Comment by lkmadushan** [comment]
@decadence ah yeah. but do we really need to use rollback for testing since we always want to clean the database end of the test. rollback uses multiple queries to finish the task this improves the speed of testing. is this unnecessary feature or any suggestions to improve this?

**Comment by ntzm** [comment]
Because rolling back doesn't necessarily mean dropping all the tables. All it does it run `down` on each migration

**Comment by lkmadushan** [comment]
@ntzm what about using a different trait like FreshDatabase?

**Comment by decadence** [comment]
People can want to test their down methods instead of just clearing database.

**Comment by laurencei** [comment]
There's no need for any of this - there is a new trait in 5.5 called RefreshDatabase that already does all of this:

https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Testing/RefreshDatabase.php

**Comment by ntzm** [comment]
Didn't know about that @laurencei, thanks

**Pull request closed without merging**
