### PR TITLE
[7.x] Pass columns when computing pagination count

### PR DESCRIPTION
**Pull request by juancho48**
Simple PR from something else merged today that's not using the param passed into the function.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I think the columns are intentionally not passed?

**Comment by juancho48** [comment]
if that's the case maybe I can remove the param?

**Comment by taylorotwell** [comment]
They are not needed in this particular call.

**Comment by GrahamCampbell** [comment]
> if that's the case maybe I can remove the param?

No, not in 7.x. This method is not private and the class is not final, so that would be a major breaking change.

**Comment by GrahamCampbell** [comment]
There param is not unused anyway. It's used on the line `->setAggregate('count', $this->withoutSelectAliases($columns))`.

**Pull request closed without merging**
