### PR TITLE
[5.7] Use asset helper to generate full path urls in exception views 

### PR DESCRIPTION
**Pull request by mattdfloyd**

### CODE REVIEW

**Comment by sisve** [comment]
What happens if it was the url-generation for assets that caused the initial exception? Wouldn't that cause an eternal loop of view rendering and the exception handler, where the exception view itself causes another exception?

**Comment by mattdfloyd** [comment]
@sisve No, it wouldn't.

**Comment by taylorotwell** [comment]
Why?

**Comment by mattdfloyd** [comment]
My need is to serve a Laravel application from a subdirectory via an Nginx proxy and without the asset helper, the files are served from the root url. I know the current stance is to not install a Laravel application into a subdirectory - I’m not. Instead I’m following this Servers For Hackers article: https://serversforhackers.com/c/nginx-php-in-subdirectory

**Pull request merged**
