### PR TITLE
[5.4] If a route::group namespace begins with `\` then reset

### PR DESCRIPTION
**Pull request by AlbertMarashi**
If a route::group namespace begins with `\` then reset

### CODE REVIEW

**Comment by MrMashy** [comment]
View Issue #18081

**Comment by MrMashy** [comment]
This fixes my project with no issues. The only breaking change would be if other programmers (stupidly) started namespaces with `\`

**Comment by themsaid** [comment]
Can you please share a simple example on what issue you're trying to solve?

**Comment by MrMashy** [comment]
It's useful for when you reuse a routes file, eg: an authentication file that you require in multiple versions of a API.

ReusedAuth.php
```
class ReusedAuth{

    public function Routes(){ //notice the slash at the front
        return Route::group(['namespace' => '\App\Http\Controller\Auth'], function(){
            Route::get('login', 'AuthController@login');
        });
    }
}
```

apiroutes.php
```
//Current namespace for the file is 'App\Http\Controller'
return Route::group(['namespace' => 'API', 'prefix' => 'api'], function(){
    return Route::group(['namespace' => 'v1', 'prefix' => 'v1'], function(){
        \App\Http\Controller\Auth\AuthController::routes();
    });
    return Route::group(['namespace' => 'v2', 'prefix' => 'v2'], function(){
        \App\Http\Controller\Auth\AuthController::routes();
    });
});
```

without it, even if the forward slash was there  (for the AuthController file)
the routegroup inside would use the old namespace which would make the namespace:
`App\Http\Controller\API\v1\App\Http\Controller\Auth`
and
`App\Http\Controller\API\v2\App\Http\Controller\Auth`
Which causes huge problems.

If a Route::group namespace begins with `\` it should be treated like a global/root namespace, how PHP works.

**Comment by taylorotwell** [comment]
This would be a breaking change.

**Comment by MrMashy** [comment]
@taylorotwell The build was successful and had no problems. Try testing this in a large project, you only need to change `RouteGroup.php`. I don't believe it's a breaking change, let me know thanks.

**Comment by MrMashy** [comment]
By the way, I tested it in my project with 0 problems. artisan route:list works perfectly.

**Comment by MrMashy** [comment]
I'd like you to reconsider and test this in your project. It's not a breaking change.

**Comment by OliverZiegler** [comment]
As this is an issue for us also...
I think as L5.5 is a "breaking change" upgrade with upgrade-guide this should be considered.

**Pull request closed without merging**
