### PR TITLE
5.3 Fix for Graham's #14741 also see #14909

### PR DESCRIPTION
**Pull request by gholol**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
It's not good to silently throw away the timeout. If you don't want it, explicitly set it to 0.

**Comment by gholol** [comment]
@GrahamCampbell Okay, But I'm kinda lost here. Where I'm throwing out the timeout? It's still set to 60 in this line : 

    $timeout = $this->option('timeout', 60);


   And your default implementation is not working, at least on PHP 7 because with and without the --timeout switch it throws the following error 

    >The pcntl extension is required in order to specify job timeouts.

**Comment by GrahamCampbell** [comment]
Yes, the default is timeout turned on.  Actually setting it to 0 shouldn't cause it to fallback.

**Comment by GrahamCampbell** [comment]
Hmmm. I'm confused how that line would even work actually since that option function only takes on parameter. The 2nd on just gets ignored.

**Comment by GrahamCampbell** [comment]
I'd say it looks like symfony is treating "0" as being nothing, so it's falling back before we get to it. I propose we change the implementation so that `-1` means no timeout.

**Comment by gholol** [comment]
@GrahamCampbell 

Okay Graham, sorry for the confusion. Looks like it's working fine, you just have to use `--timeout 0` instead of `--timeout=0`.

Now that option method takes only one argument and the second is ignored https://github.com/laravel/framework/pull/14741/files somebody should remove this.

**Comment by GrahamCampbell** [comment]
Yeh, I know. I already fixed this. :)

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/pull/14912

**Pull request closed without merging**
