### PR TITLE
[9.x] New flag -F for --force in make:model Commands

### PR DESCRIPTION
**Pull request by salahhusa9**
New flag -F for --force in make:model Commands

### CODE REVIEW

**Comment by shadoWalker89** [comment]
This would be very confusing having the same letter but in different case
-f for factory and -F for force

**Comment by salahhusa9** [comment]
@shadoWalker89 yeah but the case of letter is different,
The **capital** letter **(-F)** means something **force**

**Comment by driesvints** [comment]
Hi, I've fixed the tests on 9.x so please rebase your PR and mark your PR as ready when tests pass. Thanks

**Comment by salahhusa9** [comment]
@driesvints the problem is laravel 9.x require php 8.0.2 and the test run in php 8.0.15 

`==> Setup PHP 
√ PHP Installed PHP 8.0.15 `

**Comment by salahhusa9** [comment]
@driesvints Now good

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by salahhusa9** [comment]
@taylorotwell I don't think this addition will be a problem, it's a good **shortcut** for **remember** and **write** it.
I hope to clarify your point

**Pull request closed without merging**
