### PR TITLE
[8.x] Add complimentary `Str::doesntContain`

### PR DESCRIPTION
**Pull request by jasonmccreary**
Similar to the recent additions to the `Collection` class, this PR adds a complimentary `doesntContain` method. This may be used to test a string does not contain a substring or set of substrings, which allow the developer to write more expressive code.

**Before**
```php
if (! Str::contains('foo', 'bar')) {
    // ...
}

if (! Str::containsAll('foo', ['bar', 'baz'])) {
    // ...
}
```

**After**
```php
if (Str::doesntContain('foo', 'bar')) {
    // ...
}

if (Str::doesntContain('foo', ['bar', 'baz'])) {
    // ...
}
```

### CODE REVIEW

**Comment by foremtehan** [comment]
Can you also add those to Stringable class ? https://github.com/laravel/framework/blob/8.x/src/Illuminate/Support/Stringable.php

**Comment by jasonmccreary** [comment]
@foremtehan, you got it.

**Comment by taylorotwell** [comment]
Going to hold off on this for now - mainly because the wording around it confuses my brain when I start thinking about possible methods for a method that would determine if a string doesn't contain at least one of the given strings.

**Comment by jasonmccreary** [comment]
No problem. Negated methods can be rather mind bending. Especially with parameter overloading like this one. I really only chose this name because you used it [for the same method on the Collection class](https://github.com/laravel/framework/commit/3e3cbcf4cb4b8116f504a1e8363c7c958067b49a). I'd probably call have called it `missing`, `doesntContainAny`, or `doesntInclude`.

**Pull request closed without merging**
