### PR TITLE
[5.5] Confirm before overwrite controllers when running make:auth artisan command

### PR DESCRIPTION
**Pull request by mohamednagy**
I have executed `make:auth` artisan command on an existing project, unfortunately i forgot to add `--view` option. This mistake caused to overwrite my `HomeController` :(. 
This PR cheks if the `HomeController` exists. if yes, then show a confirmation message.

### CODE REVIEW

**Comment by jmarcher** [comment]
I do not think this is necessary "php artisan make:auth" is meant to be run on project start.

**Comment by mohamednagy** [comment]
@jmarcher i think `make:auth` should be more flexible to be run on an existing projects, also it confirms before replacing views and `Auth::routes();` is appended, so it makes sense to follow the same scenario for controllers.

**Comment by taylorotwell** [comment]
Use your source control tool to back out the changes.

**Comment by mohamednagy** [comment]
@taylorotwell  I see this is not a solution, what if i need to refactor a legacy application and want to use awesome laravel features. laravel should be more flexible to avoid human mistakes such i didn't commit my changes or can't restore my changes for whatever reason.

**Comment by devcircus** [comment]
This is a simple convenience that can be manually reproduced in just a couple of minutes. This isn't something that has to be run multiple times in a project, so if the current setup doesn't match your needs, just copy the routes and views that you need.

**Pull request closed without merging**
