### PR TITLE
[6.0] Deprecate Illuminate\Support\Carbon

### PR DESCRIPTION
**Pull request by lucasmichot**
Since the introduction of `\Illuminate\Support\DateFactory` and as `\Illuminate\Support\Carbon` only extends `\Carbon\Carbon`, this class has become totally useless.

`\Illuminate\Support\Carbon` can thus be deprecated.

Note:

- PHP-CS-Fixer fix is puprosedly not applied, to ease up review.
- For review, places of intereset are:
  - https://github.com/laravel/framework/compare/master...lucasmichot:feature/6.0/base-carbon?expand=1#diff-8302df76705ba4c39ecf0109b2e0c8abR7-R9
  - https://github.com/laravel/framework/compare/master...lucasmichot:feature/6.0/base-carbon?expand=1#diff-ce42eb98bed63cd105c92c7e3e712b4bR92

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why not just delete the class entirely?

**Comment by lucasmichot** [comment]
> Why not just delete the class entirely?

This is really up to @taylorotwell.

**Comment by driesvints** [comment]
@lucasmichot can you fix the StyleCI warnings?

**Comment by taylorotwell** [comment]
No plans to change this because I may need it in the future and would introduce another breaking change with absolutely no benefit to end users.

**Pull request closed without merging**
