### PR TITLE
Throttle expiration time

### PR DESCRIPTION
**Pull request by mayoz**

### CODE REVIEW

**Comment by damiencriado** [comment]
Why not add `protected $throttleMaxAttempt = 3;`

**Comment by lukasgeiter** [comment]
If your goal is to make it configurable this won't help. From [php.net](http://php.net/manual/en/language.oop5.traits.php):
>If a trait defines a property then a class can not define a property with the same name, otherwise an error is issued.

**Comment by damiencriado** [comment]
I think he want to make the trait more readable

**Comment by antonybudianto** [comment]
It's configurable if you don't define the property in the trait, we're supposed to define it in the controller and check it in the trait using
```php
property_exists($this, 'loginPath') ? $this->loginPath : 'just_default_value';
```

**Comment by GrahamCampbell** [comment]
Wrong branch.

**Pull request closed without merging**
