### PR TITLE
[7.x] Fix problems with dots in validator

### PR DESCRIPTION
**Pull request by driesvints**
Backport for https://github.com/laravel/framework/issues/34263

### CODE REVIEW

**Comment by BenWalters** [comment]
@driesvints Do you know when we can expect this release to be tagged?

**Comment by driesvints** [comment]
@BenWalters probably next tuesday.

**Comment by BenWalters** [comment]
@driesvints  no chance of it being patched sooner as it's a bug? Sorry to be a pain, it's just without it we cannot push out our upgrade.

**Comment by driesvints** [comment]
@BenWalters we patched this yesterday btw 👍

**Comment by airgrim** [comment]
Any chances this fix will be ported to 6.x "LTS" ?

**Pull request merged**
