### PR TITLE
[11.x] Add New `isSequential` Method to Illuminate\Support\Arr

### PR DESCRIPTION
**Pull request by eyedroot**
## Introduction

This pull request introduces a new method, `isSequential`, to the `Illuminate\Support\Arr` class. The purpose of this method is to provide a straightforward way to verify if an array consists of a sequence of continuous numbers or alphabetical characters. This addition aims to enhance the utility of the `Arr` class with a functionality that checks for sequential integrity within an array.

## Background

When working with arrays, it's common to encounter situations where verifying the sequential order of its elements is necessary. Whether dealing with numeric ranges or alphabetical sequences, ensuring the integrity of such sequences is crucial in various applications. Until now, developers had to implement custom solutions to achieve this, lacking a native, concise method within the Laravel framework.

## Implementation

The `isSequential` method checks if an array is empty, contains all numeric values, or contains all alphabetical characters. It then determines if the elements form a continuous sequence without gaps or duplicates. This is particularly useful for validating data integrity and consistency.

## Usage

```php
use Illuminate\Support\Arr;

// Numeric sequence
Arr::isSequential([1, 2, 3, 4]); // true
Arr::isSequential([1, 3, 4]); // false

// Alphabetic sequence
Arr::isSequential(['a', 'b', 'c', 'd']); // true
Arr::isSequential(['a', 'c', 'd']); // false

### CODE REVIEW

**Comment by henzeb** [comment]
Just so you know, there is already a isList method. https://laravel.com/docs/11.x/helpers#method-array-islist

**Comment by eyedroot** [comment]
> Just so you know, there is already a isList method. https://laravel.com/docs/11.x/helpers#method-array-islist

@henzeb 

Thanks for the comment!

I have a question for you. I wanted to check if the values in the array are "sequential", so I wrote the method and created a PR.

For example, the array `[1, 3, 4, 5]` is not a sequence of numbers and should return `false`. However, the `Arr::isList()` method is not able to determine that.

This is my first PR and I still don't know a lot about Laravel, so please forgive me if I'm not understanding this correctly, thanks! 🙏

**Comment by henzeb** [comment]
No, you are right, but if your selling point is not strong enough, it will not be merged into the framework... This is so close to what is List does, you should make sure Taylor knows you know that he knows that you know that your feature is similar and why it is different and why this is needed in the framework.

**Comment by Seb33300** [comment]
What about `[2, 3, 4]`?

**Comment by Rizky92** [comment]
> What about `[2, 3, 4]`?

See tests in PR.

**Comment by JayBizzle** [comment]
If we want to abide by the true definition of `sequential` then `[1, 3, 5, 7, 9]` should return `true`

**Comment by henzeb** [comment]
> If we want to abide by the true definition of `sequential` then `[1, 3, 5, 7, 9]` should return `true`

And then we can forget about this, use isList and sort by key...

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by marcovo** [comment]
If I read 'sequential', I would interpret that as checking that the items are in increasing order, arguably with a step size equal to 1 between each pair of successive items. This is also what the positive tests do check.

I think the implementation given here includes necessary conditions to be sequential, but in this regard does not guarantee sufficient conditions.
E.g., I suspect the following sequences to be falsely reported as sequential (as per my definition):
1, 3, 2, 4
1, 2.1, 2.2, 4
'0', '2e-6', '2'
'a', 'asdf', 'c'

Also, the `sort` in line 480 seems redundant to me.

**Comment by eyedroot** [comment]
@marcovo @taylorotwell @henzeb @JayBizzle @Rizky92 

The PRs I've posted have given me a lot to think about and I feel like I've learned a lot in a short time.

Thanks for all the nice comments and blessings!

**Pull request closed without merging**
