### PR TITLE
Removed unnecessary $tokenCount var

### PR DESCRIPTION
**Pull request by phanan**
I know @taylorotwell [said](https://github.com/laravel/framework/pull/8039#issuecomment-83893775) he tends to "shy away" from these "cleanup PRs," but can't help it.

### CODE REVIEW

**Comment by Arrilot** [comment]
Using `count()` inside `for` is an anti-pattern because it executes on every iteration and leads to performance degradation on large arrays

**Comment by phanan** [comment]
@Arrilot No.

**Comment by TheShiftExchange** [comment]
So out of curiosity - I was wondering how much effect using `count()` on the loop had.

For a 100,000 array:
- Using `$tokenCount` ran the 100,000 loop in 0.005 secs
- Using `count($array)` ran the 100,000 loop in 0.05 secs 

So it is an order of magnitude faster. However that is only for an extremely large array. Arrays less than 1,000 had no noticeable runtime difference.


Note - I dont support or deny the PR one way or the other - was just curious and thought I'd post my results here "for science"

**Comment by andrewhood125** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
@phanan, unfortunately, you are not correct.

**Comment by phanan** [comment]
@GrahamCampbell No worries, I've been wrong numerous times in my life :smile: But which statement of mine is incorrect this time? 

@TheShiftExchange and @Arrilot According to the [for loop documentation](http://php.net/manual/en/control-structures.for.php):

> The first expression (expr1) is evaluated (executed) once unconditionally at the beginning of the loop.

Which means the call to `count($array)` is evaluated only once. Try for yourself:

``` php
<?php

function called() {
	echo 'Called';
	return 10;
}

for ($i = 0, $j = called(); $i < $j; ++$i) {
	echo $i;
}

// output: Called0123456789
```

**Comment by TheShiftExchange** [comment]
@phanan - you need to read further down that page

`The above code can be slow, because the array size is fetched on every iteration. Since the size never changes, the loop be easily optimized by using an intermediate variable to store the size instead of repeatedly calling count():`

**Comment by GrahamCampbell** [comment]
Ohhh, @phanan you are actually correct. I apologise. I misread the diff as having the function call after the semicolon, rather than before it, in the bit where we initialise the iteration.

**Comment by GrahamCampbell** [comment]
@TheShiftExchange No, this isn't executed every time. If it were, then `$i` would get initialised on every iteration, which of course isn't what happens.

**Comment by TheShiftExchange** [comment]
Yep - in my test I didnt do the var initizilation the way @phanan did it.

His way is correct and produces same run times for the array

**Comment by GrahamCampbell** [comment]
Even then, this change is totally pointless. We could put every single variable in that bit of the for statement if we wanted to, but why would we? The current way is actually more readable.

**Comment by GrahamCampbell** [comment]
And the performance is identical.

**Comment by GrahamCampbell** [comment]
You say "removed", but actually, you've basically just renamed it, and moved it a little bit lower in the code...

**Comment by phanan** [comment]
@GrahamCampbell Agreed. I tend to be too nitpicking time to time...

**Pull request closed without merging**
