### PR TITLE
[5.8] Add option to output route:list as JSON

### PR DESCRIPTION
**Pull request by jasonmccreary**
The `route:list` command is big window into the application. This adds a `--json` option which outputs the report in JSON format. As this is easily parseable programmatically it allows this comand to be used readily by other tools and services.

### CODE REVIEW

**Comment by reinink** [comment]
@DanielCoulbourne @mattstauffer Helpful for Ziggy maybe?

**Comment by belguinan** [comment]
@reinink Very helpful!

**Comment by Namoshek** [comment]
Wouldn't it make sense to have the HTTP methods of a route be returned as array instead of a `|` separated string as seen in the normal output?

**Comment by jasonmccreary** [comment]
I didn't want to modify existing code in hopes this could squeeze into a patch release as I needed it for my project. But yes, it might be nice to return the `methods` and `middleware` as an array. Feel free to make a new PR with those changes. :+1:

**Pull request merged**
