### PR TITLE
[5.9] Added ability to update other columns when performing soft deletion

### PR DESCRIPTION
**Pull request by ddzobov**
Added ability to update other columns when performing soft deletion. 
Currently need to call save() method in static::deleting(). Tests included.

Example usage:
```
<?php

use Illuminate\Database\Eloquent\Model;

class SomeModel extends Model
{
    use SoftDeletes;

    protected static function boot()
    {
        static::deleting(function (self $model) {
            $model->somecolumn = 'some-new-value';
//            $model->save(); - not needed from now
        });
    }
}

$model = SomeModel::create([
    'somecolumn' => 'somevalue'
]);
$model->delete();
```

### CODE REVIEW

**Comment by driesvints** [comment]
I don't see why this is necessary tbh. It's better to be explicit in the deleting callback imo and note that you want to save the changes.

**Comment by ddzobov** [comment]
It will be second query - not good for performance

**Comment by driesvints** [comment]
In any case this is a breaking change and best sent to master imo.

**Comment by ddzobov** [comment]
> In any case this is a breaking change and best sent to master imo.

Switched to master.
But why it is breaking change? Without calling save it will never work. With calling - same behavior, two queries.

**Comment by driesvints** [comment]
@ddzobov because people could currently set changes on this listener and don't expect them to be saved.

**Comment by d3jn** [comment]
@ddzobov updating dirty attributes together with `deleted_at` column on `delete()` sounds like a bad change that can lead to a lot of problems like @driesvints already pointed out. 

Someone might have filled model's attributes with some values, but then decided to delete this model in the code - expected (and logical) behavior here would be that those changes will not be persisted into database (since we haven't called `save()` implicitly), but with your changes they will be.

I would certainly vote for similar change to be introduced in the non-breaking (disabled by default unlesss you override/change something within the model) manner. Also, currently if the need arrives to update other columns and extra update query is an issue you can always just override trait's `runSoftDelete()` method to introduce this specific behavior.

**Comment by driesvints** [comment]
It's also a case of what you expect. I personally don't expect other stuff to be saved when I perform a "delete". I expect a delete to do the bare minimum necessary to delete the model.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
