### PR TITLE
[7.x] Make LengthAwarePaginator::elements() public

### PR DESCRIPTION
**Pull request by JamesFreeman**
I need the ability to push this method's data to a Vue component via the controller, as it stands at the moment I can only push get access to this method via `render` but this returns the whole HTML.

I've targeted this PR to master as I wasn't sure if this is deemed a BC.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can you describe what you are trying to accomplish?

**Comment by iamthefreeman** [comment]
I have a rather complex e-commerce setup of product listings pages, where user interaction can change the products within the page via an AJAX request. After user interaction I receive back a JSON string which I then re-render my Vue components, which includes the pagination object:

Screenshot 2019-12-02 at 14 24 53

With the elements method avaiable, I would be able to do something like this in my `Links.vue`:

```
<template v-for="element in links.elements">
    <template v-if="typeof element === 'string'">
        <li class="page-item disabled" aria-disabled="true">
            <span class="page-link" v-text="element"></span>
        </li>
    </template>

    <template v-if="typeof element === 'object'" v-for="(url, page) in element">
        <template v-if="page === links.current_page">
            <li class="page-item active" aria-current="page">
                <span class="page-link" v-text="page"></span>
            </li>
        </template>
        <template v-else>
            <li class="page-item">
                <a class="page-link" :href="url" v-text="page"></a>
            </li>
        </template>
    </template>
</template>
```

**Comment by driesvints** [comment]
Aren't https://github.com/laravel/framework/pull/30729 and this PR closely related?

**Comment by deleugpn** [comment]
@driesvints not necessarily. I'm working exclusively with API and the proposal there relates to Eloquent Resource while this case wants to bypass Blade and render the navigation using Vue instead. At least that's my understanding.
From this snippet, the Query Parameters are not important for this particular case while for me (in PR 30729) they're the the essence.

**Comment by iamthefreeman** [comment]
@driesvints @taylorotwell If you are happy with this change, do you think `master` is the correct branch to target, or do you think it's okay to go into `6.x`?

**Review by darielopper — APPROVED** [review]

**Comment by taylorotwell** [comment]
Personally I'm not a huge fan of this idea. IMO you should use the JSON structure we already give you to build your links the way you want. I don't want people depending on this (now internal) data structure in their public UIs. It would mean I could never change that or optimize it for the paginator without breaking applications and I don't want to do that.

**Pull request closed without merging**
