### PR TITLE
[9.x] add whereLike

### PR DESCRIPTION
**Pull request by milwad-dev**

### CODE REVIEW

**Comment by ankurk91** [comment]
How does it work in Postgres?

What about `whereiLike() `

**Comment by milwad-dev** [comment]
@ankurk91 
I think they are the same

**Comment by ankurk91** [comment]
@milwad-dev 

`like` and `ilike` are not the same for postgresql

**Comment by milwad-dev** [comment]
@ankurk91 
Sorry, I had another thought.
We can make new method for ``ilike`` or make property for check like & ilike.

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
