### PR TITLE
Add touchOwners method to DB/Eloquent/Collection

### LINKED ISSUE #6386: $touches causes fatal error if no ManyToMany relations exist
You can set up a pair of Eloquent models like this:

    class Product extends \Eloquent {
        public function assets() {
            return $this->belongsToMany('Asset');
        }
    }

    class Asset extends \Eloquent {
        protected $touches = [ 'products' ];

        public function products() {
            return $this->belongsToMany('Product');
        }
    }

By doing this, you can call

    Product::find( $validProductId )->assets()->attach( $validAssetId );

the `Asset` will go and update the `updated_at` field on every related `Product` to indicate that its relations have changed.

However, if you make a new `Asset`, or take an `Asset` which has no related `Product`s yet, you'll get a fatal error as the `Model::touchOwners` method only checks if `$this->relation` isn't null:

	public function touchOwners()
	{
		foreach ($this->touches as $relation)
		{
			$this->$relation()->touch();

			if ( ! is_null($this->$relation)) // this is the problem
			{
				$this->$relation->touchOwners();
			}
		}
	}

I have a tentative fix in place locally (for now) by just adding in a check for `&& ! $this->$relation->isEmpty()`, but that may affect other relations, I'm not sure:

	public function touchOwners()
	{
		foreach ($this->touches as $relation)
		{
			$this->$relation()->touch();

			if ( ! is_null($this->$relation) && ! $this->$relation->isEmpty())
			{
				$this->$relation->touchOwners();
			}
		}
	}

### PR DESCRIPTION
**Pull request by impleri**
Fixes #6386.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
4.2 is only open for security fixes.

**Comment by commandantp** [comment]
Can we have this fix merged in the framework please? I can't update from 4.2.6 because of this bug - meaning I don't get the security fixes that have been released since then... 
Thanks!

**Comment by commandantp** [comment]
Can this be pulled please? Impossible to get the security fixes if I cannot update... thanks a lot!

**Comment by GrahamCampbell** [comment]
@commandantp This is already done in 5.0.

**Comment by GrahamCampbell** [comment]
Hmmm, or maybe not. Feel free to send a PR.

**Comment by commandantp** [comment]
@GrahamCampbell It has been done for 5.0 but not for 4.2. Any chance this could be done? I cannot move to 5.0 yet and being stuck at 4.2.6 is not the best since there have security fixes since then. Thank you so much for your help!

**Comment by Sladewill** [comment]
Why not get all your classes to extend your own class which extends that class and implement it there, then you dont need to have it implemented into the main framework.

**Comment by commandantp** [comment]
@Sladewill thanks! I'm not sure I know how to do that, how should I start (or look for) ? Would that mean create an intermediary class? Never did that yet but I can learn if needed

**Comment by GrahamCampbell** [comment]
> It has been done for 5.0 but not for 4.2. Any chance this could be done? 

No, sorry. Maybe Laravel 5.1 would be good for you to move to - it'll be an LTS relesae.

**Comment by GrahamCampbell** [comment]
Once we actually ship it in 4 weeks.

**Comment by commandantp** [comment]
@GrahamCampbell thanks man! I will definitely do it. Just hope that everything will be compatible :)

**Comment by GrahamCampbell** [comment]
If you're using laravel packages, you will definitely need to check if the maintainers have updated them. Things like resources and config will have been broken by L5.

**Pull request closed without merging**
