### PR TITLE
handle circular dependency exception

### PR DESCRIPTION
**Pull request by niyiomotoso**
**This PR is to handle circular dependency exception. It also prevents memory leak issue on dev machine**

                                            Current Situation

 When you have objects in your code that are directly dependent on each other, and are injected via constructor, the final result is SERVER ERROR, because of the infinite loop. This also leads to memory leak in the application.

 **Example** 

AuthController injects AuthService
Screenshot 2023-05-29 at 3 28 43 AM

AuthService injects AuthController
Screenshot 2023-05-29 at 3 28 21 AM

The error output in dev machine console: 

Screenshot 2023-05-28 at 2 32 12 AM

                                          After the Fix

The exception is rightly handled, also the developer knows to refactor the code.

Screenshot 2023-05-29 at 3 29 53 AM

### CODE REVIEW

**Comment by henzeb** [comment]
Of course you should test your work and this should only happen on your dev machine. But I've seen dev machines hanging on this.

**Comment by niyiomotoso** [comment]
> Of course you should test your work and this should only happen on your dev machine. But I've seen dev machines hanging on this.

Thanks. Tests added. True, the memory leak output is seen on dev machine, but server error is returned without any clear cause regardless of the environment.

**Comment by driesvints** [comment]
This PR contains multiple breaking changes unfortunately. Please send this to 11.x

**Comment by niyiomotoso** [comment]
> This PR contains multiple breaking changes unfortunately. Please send this to 11.x

@driesvints Do you mean I should consider pointing it to 11.x? I don't see any branch named that

**Comment by driesvints** [comment]
@niyiomotoso it's `master`

**Comment by niyiomotoso** [comment]
> @niyiomotoso it's `master`

thanks @driesvints. I just took care of it

**Pull request closed without merging**
