### PR TITLE
[5.2] Add knowledge,love and rain to uncountable word forms.

### PR DESCRIPTION
**Pull request by unicodeveloper**
I have created `Knowledge`, `Love` and `Rain` amidst other models like Tea and Coffee but the Pluralizer couldn't handle them because they are not accounted for in the `$uncountable` array and I had just moved with using the `protected $table` property.

Now, I know there are so many words like these ones above that we might not be able to account for but `knowledge`, `love`, `rain` are very popular words and my colleagues and beginners have had issues several times.

So I decided to submit this PR to add them to the uncountable word forms.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
There's something quite profound about knowledge being uncountable.

**Comment by GrahamCampbell** [comment]
@taylorotwell I wonder if 5.1 is really the correct target branch for this PR?

**Comment by unicodeveloper** [comment]
@GrahamCampbell Yeah quite profound. @taylorotwell what do you think. I could submit it to 5.1 if you want?

**Comment by taylorotwell** [comment]
5.1 is fine.

**Pull request closed without merging**
