### PR TITLE
Ensure that the integer value is delivered.

### PR DESCRIPTION
**Pull request by emtudo**
Laravel Version: 5.8.29
PHP Version: 7.3

Description:

Ensure that the integer value is delivered.
For if the user happens to enter in paginate ("100")

this method will return string "100", not 100

### CODE REVIEW

**Comment by mfn** [comment]
Please check your code, I believe your code initially passes a string into it in the constructor

**Comment by driesvints** [comment]
Please pass an integer to the paginate method.

**Comment by driesvints** [comment]
You can also typecast the argument in the paginate method.

**Comment by PlayerLinkPL** [comment]
Yes, I can and I did that. But if the method in the documentation says that it returns an integer shouldn't it guarantee the return of an integer?

**Comment by driesvints** [comment]
@PlayerLinkPL might be better to enforce this through the setters/constructors.

**Pull request closed without merging**
