### PR TITLE
Remove the 3 artisan commands that are no longer used anymore.

### PR DESCRIPTION
**Pull request by jumilla**
Remove unnecessary artisan commands for Laravel 5.1 or later.
- make:command
- handler:command
- handler:event

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
There's no reason why someone wouldn't want to use those commands. Just because the default app structure is different - that means nothing.

**Comment by jumilla** [comment]
Workbench should but has been removed in Laravel 5.0, had some people are using.

Or necessary or unnecessary, than may be discussed?

At least I do not think need to laravel/framework repository. It is because they already old because.

**Comment by GrahamCampbell** [comment]
They're not old. There is no reason why someone can't structure their app like 5.0 had things. Infact, I do that out of choice on new applications.

**Comment by GrahamCampbell** [comment]
The 5.1 structure is more suitable for most use cases which is why it's the default, but many people find the 5.0 structure more useful.

**Comment by jumilla** [comment]
Command than became a Job in 5.1? If the 5.0 concept of need, or not sufficient to copy the source of Artisan command to your project. Or, it might be good to prepare a flag that can control the display of legacy command in `config/artisan.php`.

`make:command` and `make:job` is not a simple thing to co-exist. It is useless for people who do not require historical reasons, only just confusion occurs.

**Comment by GrahamCampbell** [comment]
No. Both are the same.

**Pull request closed without merging**
