### PR TITLE
[9.x] Make local test setup os and composer independent

### PR DESCRIPTION
**Pull request by TheLevti**
The current `./bin/test.sh` has multiple issue:

1. Specifically written for a MacOS environment only (does not run on linux).
2. Assumption that everyone has a www-data user locally to mount the filesystem with.
3. Composer and php is installed on the host machine.

This pull request solves all those issues so that the local test suite can be run on either mac or linux. It mounts the project with the same user as the currently logged in user on the host so that no file permission or missing user issues appear. Also the changes make sure that an os agnostic host is used for all the services instead of `docker.for.mac.localhost`. On top of that it is no longer required that the host has php or composer installed. The test suite can be fully run within the docker container, making sure that composer installs the latest packages within the composer.json constraints before running the tests.

### CODE REVIEW

**Comment by driesvints** [comment]
Hey @TheLevti. Thanks for this. But I never get MySQL to start: 

> MySQL never became available

Anything that I'm missing here?

**Comment by TheLevti** [comment]
> Hey @TheLevti. Thanks for this. But I never get MySQL to start:
> 
> > MySQL never became available
> 
> Anything that I'm missing here?

Do you have a older deployment still running?

**Comment by driesvints** [comment]
@TheLevti no idea. I did run the `./bin/test.sh` script before if that's what you mean. How do I start from scratch?

**Comment by TheLevti** [comment]
>

**Comment by TheLevti** [comment]
> @TheLevti no idea. I did run the `./bin/test.sh` script before if that's what you mean. How do I start from scratch?

Yes, then it might be it. Can you please first run `./bin/test.sh down` so that the old containers are shut down first before you check out my branch.

**Comment by driesvints** [comment]
Both executions are not working at all for me:

Screenshot 2022-08-22 at 13 17 20

**Comment by TheLevti** [comment]
> Both executions are not working at all for me:
> 
> Screenshot 2022-08-22 at 13 17 20

Ok thanks, something seems to be messed up with the down command. You should be calling down with the 9.x branch first to make sure to disable everything on the old branch. Not on my branch.

**Comment by driesvints** [comment]
Still nothing I'm afraid...

Screenshot 2022-08-22 at 13 22 42

**Comment by TheLevti** [comment]
> Still nothing I'm afraid...
> 
> Screenshot 2022-08-22 at 13 22 42

Thank you very much, will investigate this and come back with a solution.

**Comment by TheLevti** [comment]
I have pushed a version with more output. Could someone with a mac please test the local test execution again?

In addition I removed the --down option. The script will automatically clean up after the run and recreate the containers if they are already there from another deployment.

**Comment by driesvints** [comment]
@TheLevti I now get this:

Screenshot 2022-09-05 at 15 58 11

**Comment by TheLevti** [comment]
> @TheLevti I now get this:
> 
> Screenshot 2022-09-05 at 15 58 11

Thanks, thats an interesting issue. Do you have any other mysql instances running? Either that or the php image fails to run migrations somehow.I also don't see the section that pulls/creates the php image. Did you try to clean up old unused images? `docker system prune -a` would remove all old unused images.

**Comment by driesvints** [comment]
While I appreciate it what you're trying to do here @TheLevti I think I'm going to respectfully leave things be here. It's best that you try to find someone who can help you put this together and send this in once you're certain it works on macOS. Thanks

**Comment by TheLevti** [comment]
Shouldn't we encourage collaboration so that everyone can contribute? Maybe there are others that would like to help that use a mac. Or is it a problem that there could be too many open pull requests? I understand closing abandoned/declined pull requests, but those that are actively developed is a bit counter productive, especially those where it would be helpful to get input from others like in this example to solve a cross OS problem?

**Comment by driesvints** [comment]
You can try one of these channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by TheLevti** [comment]
> You can try one of these channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Amazing, thank you! Will come back when I have proof that it works on both platforms.

**Pull request closed without merging**
