### PR TITLE
[5.0] Add Route Macro

### PR DESCRIPTION
**Pull request by lucasmichot**

### CODE REVIEW

**Comment by ibrasho** [comment]
This should be closed now? I think another PR was merged.

**Comment by GrahamCampbell** [comment]
Don't think so?

**Comment by ibrasho** [comment]
My apology... I think #6863 contained this update.

**Comment by GrahamCampbell** [comment]
No, it didn't. :)

**Comment by lucasmichot** [comment]
Done @GrahamCampbell

**Pull request merged**
