### PR TITLE
[5.6] The method of obtaining the current subdomain name is added

### PR DESCRIPTION
**Pull request by andrey-helldar**
Example:
```php
return request()->route()->getSubdomain();
// from domain `test.mysite.local` will return `test` (string).

return request()->route()->getSubdomain(0);
// from domain `subdomain.example.co.uk` will return `subdomain` (string).

return request()->route()->getSubdomain(1);
// from domain `subdomain.example.co.uk` will return `example` (string).

return request()->route()->getSubdomain(3);
// from domain `subdomain.example.co.uk` will return `uk` (string).

return request()->route()->getSubdomain(5);
// from domain `subdomain.example.co.uk` will return `null` (null).
```

(recreating pr #23926 for branch 5.6)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmm, so two things:

## 1. I don't see the point in this, honestly

What's so hard about:

```
explode('.', $route->action['domain'])[0] ?? null
```

## 2. This is surely very unreliable.

What if you have `dev.foo.example.com`. What should the sub domain be? Should we not just leave it up to users to implement their own tiny bit of code, that does what they want?

**Comment by andrey-helldar** [comment]
1. The design of the `explode('.', $route->action['domain'])[0] ?? null` view is bad in that if the method is called on the base domain, it will return its name.
```
example.com
// returned `example`, but should be `null`.
```

2. To solve the problem with domain names 4 and above the levels, I added the code.

**Comment by andrey-helldar** [comment]
> Should we not just leave it up to users to implement their own tiny bit of code, that does what they want?

When I asked in a chat whether someone saw such a mechanism "out of the box," several people answered that they wrote it themselves, and all the code was almost identical in implementation, and absolutely identical in the result.

I thought why not send it as PR.

**Comment by 36864** [comment]
How does your code handle "subdomain.example.co.uk" and similar TLDs?

**Comment by 36864** [comment]
I don't like it. You have a method called `subDomain` which can return the TLD, or the second-level domain, or basically any part of the domain, but can't return `billing.clients` from the `billing.clients.example.com` domain.

I don't see this as a problem that needs to be solved at the framework level, and I don't see it as a problem with a universal solution.

**Comment by JayBizzle** [comment]
Should return `null` if `$this->action['domain']` is not set like `getDomain()` does...

https://github.com/laravel/framework/blob/a71dc5cd365431097a1d4d4d983b60610855ddc0/src/Illuminate/Routing/Route.php#L570

Also, needs tests

**Pull request closed without merging**
