### PR TITLE
[5.8] Pass severity information to work command log method to enable filtering

### PR DESCRIPTION
**Pull request by cweiske**
Now it is possible to control the output of job workers with the standard verbosity parameters (-v, -vv etc).

Standard worker messages ("Processing: \App\Job\Foo", "Processed: \App\Job\Foo") are now only visible when using `-v` or `-vv`, while errors are always shown.

Resolves: https://github.com/laravel/framework/issues/27483

### CODE REVIEW

**Comment by mfn** [comment]
What does this mean to stay "backwards compatible" when using horizon to receive the same output?

Starting `./artisan horizon -v` ?

I'm asking because this talks only about workers which you don't control individually when using horizon.

**Comment by cweiske** [comment]
Yes, you have to use `-v` for getting "Processed" messages, `-vv` for both "Processing" and "Processed" messages.

Using `-vv` gets back the previous behavior.

**Comment by mfn** [comment]
Thanks for clarifying!

IMHO this is a change for 5.8, I wouldn't expect such a change within a 5.7 upgrade were you usually don't consult the upgrading guide (where this belongs IMHO).

**Comment by cweiske** [comment]
Ok, I rebased it against master.

**Comment by driesvints** [comment]
Seems like something went wrong. Please resubmit this for the 5.8 branch.

**Pull request closed without merging**
