### PR TITLE
[5.4] Return errors in JSON

### PR DESCRIPTION
**Pull request by m1guelpf**
Return all HTTP errors in JSON if the request expected json. Prevents redirects  + getting a bunch of HTML in API requests

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎 This is a breaking change.

**Comment by GrahamCampbell** [comment]
I don't think we should ever include this in the core exception handler actually, anyway.

Maybe a good place to put this, if at all, would be in laravel/laravel.

**Comment by m1guelpf** [comment]
@GrahamCampbell 
> Maybe a good place to put this, if at all, would be in laravel/laravel.
Should I open another PR on laravel/laravel and close this or wait for Taylor?

**Comment by taylorotwell** [comment]
We're already working on this for 5.5.

**Pull request closed without merging**
