### PR TITLE
[5.3] Add css and js functions to helpers

### PR DESCRIPTION
**Pull request by AbdelkaderBah**
Useful and time saving functions for any developer

### CODE REVIEW

**Comment by piotr-cz** [comment]
The css helper is missing an option to set media attribute.
Generally I'm against rendering HTML tags using helpers, unless it adds more functionality like assets dependency management

**Comment by srmklive** [comment]
I would have the `$path` parameter as an array for both functions.

**Comment by morloderex** [comment]
I feel like these helpers doesn't belong to core.

**Comment by GrahamCampbell** [comment]
I agree. These helpers would also have to return an html string object anyway, not a string.

**Comment by taylorotwell** [comment]
No plans to add these helpers.

**Pull request closed without merging**
