### PR TITLE
Generate class name validated with keywords

### PR DESCRIPTION
**Pull request by pavinthan**
`php artisan make:model Class` will throw Class is a keyword!

### CODE REVIEW

**Comment by pavinthan** [comment]
someone help me to fix the style issue

**Comment by mfn** [comment]
> someone help me to fix the style issue

- go to the link provided by styleci => https://styleci.io/analyses/XVxkeV
- either manually apply the changes _or_ click on "download raw diff" and simply apply them via your editor/IDE/terminal

Couldn't be any easier ;) (well, except auto-commiting them…)

**Comment by mfn** [comment]
> will throw Class is a keyword!

Personally I'm 👎 , having a list to maintain when PHP changes that in the future is just maintenance overhead; time best spent elsewhere. The developer **will** find out quickly if it works or not anyway.

**Comment by pavinthan** [comment]
Thanks, @mfn and @taylorotwell

**Pull request closed without merging**
