### PR TITLE
[6.x] Fix migration class duplicate check

### LINKED ISSUE #30062: make:migration: Class duplicate check is not working
- Laravel Version: 6.0.2
- PHP Version: 7.3.9
- Database Driver & Version: not relevant

### Description:

The `make:migration` command has class duplication checking logic, but it doesn't seem to work.

### Steps To Reproduce:

```console
% php artisan make:migration foo
% php artisan make:migration foo
```

The second `make:migration` is expected to fail with `class already exists` error, but will succeed.

An error occurs when the `php artisan migrate` command is executed later because the class name is duplicated.

### Note

This check is performed by the [`\Illuminate\Database\Migrations\MigrationCreator::ensureMigrationDoesntAlreadyExist`](https://github.com/laravel/framework/blob/3ec56b8810bc40016252977c69ba27057dcecf7d/src/Illuminate/Database/Migrations/MigrationCreator.php#L70) function. This uses the `class_exists` function to determine whether the class you are trying to create already exists.

I think it is needed to require all migration files to define the migration classes before duplication check.

### PR DESCRIPTION
**Pull request by ROOKIE20570**
Closes #30062.

### CODE REVIEW

**Comment by sisve** [comment]
This changes a method signature and may break existing code. Should it target another Laravel version?

**Comment by ROOKIE20570** [comment]
> This changes a method signature and may break existing code. Should it target another Laravel version?

I am wondering if I can add another method to verify that it already exists, but that is not in line with the DRY principle.Let me think about it

**Comment by ROOKIE20570** [comment]
> This changes a method signature and may break existing code. Should it target another Laravel version?

I added a default parameter, so the code that depends on this method can run

**Comment by gocanto** [comment]
Nice work :star:

> I added a default parameter, so the code that depends on this method can run

It might bring issues if `somebody` is extending this class since the given method is marked as `protected`. 

You probably can `extract` the common path logic check from there, so you duplicated yourself. Therefore, this change can still be applied without breaking the `API`.

Nevertheless, you might want to wait for official feedback to keep working on it.

**Comment by taylorotwell** [comment]
While this does add an argument to a protected method, the likelihood of any given Laravel application extending this specific method seems pretty negligible to me.

**Comment by driesvints** [comment]
This broke the build. @ROOKIE20570 please make sure that the tests pass next time, thanks.

**Comment by ROOKIE20570** [comment]
> This broke the build. @ROOKIE20570 please make sure that the tests pass next time, thanks.

Sorry, I was not familiar with it before, I will definitely do better next time.

**Comment by driesvints** [comment]
@ROOKIE20570 no worries at all 👍

**Pull request merged**
