### PR TITLE
[5.5] Auto register commands in app/console/commands

### PR DESCRIPTION
**Pull request by themsaid**
I always find it annoying having to include the console commands in Kernel's `commands` class property after creating the command using `make:command`, this PR is an attempt to auto register commands residing inside `app/console/commands`.

- The auto-registerer will find commands in sub directories as well.
- Commands that aren't sub classes of `Illuminate\Console\Command` are excluded.

### CODE REVIEW

**Comment by jmarcher** [comment]
the folder app/Console/Commands is not in Laravel's default installation

**Comment by browner12** [comment]
the directory is created when you make your first command.

**Comment by jmarcher** [comment]
But what will happen if I do not create any command, this change will still want to scan that non-existing folder.

**Comment by browner12** [comment]
good call. looks like the function will error out if the directory doesn't exist, so just need to add a check for directory existence first.

**Comment by themsaid** [comment]
@jmarcher  @browner12 just added a check

**Comment by brayniverse** [comment]
I occasionally deregister commands that I don't want to completely delete - for various reasons. With this change, is it possible to exclude a deregistered command from being auto-registered?

**Comment by jmarcher** [comment]
@brayniverse You could move them to a Disabled folder something like: app/Console/Commands/Disabled

**Comment by brayniverse** [comment]
@jmarcher I also occasionally nest commands in subdirectories to group functionality. I did assume this auto-registering of commands would also allow nesting.

**Comment by laurencei** [comment]
What about a different approach.

>  ...after creating the command using `make:command`

Why dont you just add a section on `make:command` that writes to the actually `Kernel.php` file the new filename you just created. Wouldnt be too hard to have it write add a string to the end of the array using some basic string parsing.

That way the command registering is still "static" - but has an automated action from the make command?

Dunno... just a thought...

**Comment by themsaid** [comment]
I'm fine with including commands in sub-directories as @brayniverse mentioned, but don't like the approach mentioned in @laurencei's comment, feels like a bad idea to touch a user-accessible file.

**Comment by laurencei** [comment]
No dramas - it was just an alternative idea 😃

**Comment by themsaid** [comment]
@brayniverse pushed an update, commands not extending the Illuminate\Console\Command class are excluded from auto-registery. If you want to exclude a command you just remove the class extension.

**Comment by brayniverse** [comment]
That works for me. Thanks @themsaid.

**Comment by browner12** [comment]
seems a little weird and unintuitive. not sure what the right answer is though

**Comment by laurencei** [comment]
It's kinda what the Console route file is for? If you want to write a bunch of quick small commands - you place them in the console file.

Otherwise you create dedicated classes and register them explicitly in the kernel?

**Comment by brayniverse** [comment]
@browner12 I see your point, and if it's just me wanting to disable commands then please don't add any "weird" functionality to suit my needs when all I'd have to do is move the file to a different directory.

**Comment by decadence** [comment]
I see both solution for ignore (move file or remove `extend`) are not intuitive. But if choose one of them I would go with move file outside Command folder. At least it obvious: if file is not there then it will not be auto-registered.
With deleting `extend` you have 2 problems:
- you can forget about it and spent some time to figure out why your Command is not auto-loaded.
- if you call `parent` methods you will get IDE warnings after removing `extend`.

Personally for me will be more convenient to explicitly specify ignored Command in some config section. I don't think it would be needed often.

**Comment by deleugpn** [comment]
Having both approaches in the Kernel could be cool:
```
public $autoRegister = true;

public $except = [];
```

This could offer a backward compatible solution by setting auto register to false.

**Comment by themsaid** [comment]
Checking of the command is a subclass of `Command` is not a bad thing anyways, it's a way to make sure we don't consider any other classes as a command and thus error while loading the application, so it's not only done to allow excluding commands.

**Comment by flugger** [comment]
What about using a wildcard in the kernel, meaning "register all commands":

```php
$commands = ['*'];
```

However, this doesnt give an easy solution to quickly disable single commands.

**Comment by lucasmichot** [comment]
Nice @themsaid 
Why not providing an empty `\Illuminate\Contracts\Console\ShouldAutoRegister` interface ?
By default a new command generated with `make:console` implements this interface.
`autoRegisterCommands`  function could filter on that.

The developer can remove this implementation in his command if he feels so...

**Comment by lucasmichot** [comment]
And if you want to push things a bit further @themsaid, you could also implements a `Schedulable` interface for commands.
This was each auto-registered commands that also implement the `Schedulable` interface would return `getSchedule`:

Thus you could also define the schedule **inside** the command 🎉🇪🇬

_Just thinking out loud_

**Comment by themsaid** [comment]
@lucasmichot nice idea :)

Just implemented your approach.

**Comment by laurencei** [comment]
@lucasmichot - the only problem with defining a schedule inside a command is it might make it difficult to schedule multiple different timelines of a schedule.

i.e. I know people run different "schedules" using the one command.

**Comment by lucasmichot** [comment]
@laurencei , I see your concern, this could be easily implemented: either you return a schedule, either an array of schedules:

```php
/**
 * @param \Illuminate\Foundation\Scheduling $scheduling
 * @return \Illuminate\Console\Scheduling|array
 */
public function getSchedule(Scheduling $scheduling)
{
    // return $scheduling->daily();

    return [
        $scheduling->daily(),
        $scheduling->weekly(),
    ];
}
```

**Comment by laurencei** [comment]
I dunno... I kinda feel like the schedule is not the responsibility of the command? i.e. it is the application that has the "concern" of when the command runs - not the command itself?

**Comment by lucasmichot** [comment]
The registration is not the command responsibility either - but still auto-register is a good addition
I believe the same for this schedulable feature
At the end you could register the command in the command itself or in the Kernel, as for the schedule.

But once more, just thinking out loud 😃

**Comment by taylorotwell** [comment]
Did this a little differently. You can just call `load` from your `commands` method:

screen shot 2017-07-17 at 9 11 43 am

Thanks @themsaid

**Pull request closed without merging**
