### PR TITLE
[5.1] Allow --path option for migrate:refresh command

### PR DESCRIPTION
**Pull request by CupOfTea696**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Would prefer to keep all migrations exported into the single migrations directory.

**Comment by JosephSilber** [comment]
We [already have](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L119) the `path` option for the regular `migrate` command.

This just makes the two consistent.

If you don't like this, we should remove it from there too.

**Comment by GrahamCampbell** [comment]
Please squash to one commit.

**Comment by CupOfTea696** [comment]
@GrahamCampbell I have no idea how to do that :/

**Comment by spencerdeinum** [comment]
You need to use rebase or another method to squash your 3 commits into one.

http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

In your case you'd want to do `git rebase -i HEAD~3` and put an s for the last two.

**Pull request merged**
