### PR TITLE
[5.6] Reuse code from DatabaseTransactions in RefreshDatabase

### PR DESCRIPTION
**Pull request by mnabialek**

### CODE REVIEW

**Comment by laurencei** [comment]
Nice.

Any reason not to target this straight to 5.5?

**Comment by GrahamCampbell** [comment]
No urgency to get into 5.5, it doesn't fix or add anything?

**Comment by mnabialek** [comment]
@GrahamCampbell Right, this is only code cleanup so it can wait until 5.6

**Comment by laurencei** [comment]
> No urgency to get into 5.5, it doesn't fix or add anything?

My thinking was just 5.5 is LTS - so putting this in now makes sense. 

Meh - doesnt really matter either way - just a thought.

**Comment by skollro** [comment]
This change needs to be reverted, it causes problematic side effects.

We're evaluating all the used traits of `TestCase` recursively. If we apply the `RefreshDatabase` trait to one of our tests, this applies `DatabaseTransactions` in addition. 

So two transactions are started instead of one. This leads to errors on rollbacks and the strange behaviour I showed in https://twitter.com/skollro/status/962695003624628225

For the desired code reuse we have to come up with another solution.

https://github.com/laravel/framework/blob/735b8771263bba951a3198fa374d2cc1a577e2bf/src/Illuminate/Foundation/Testing/TestCase.php#L99-L113

**Comment by a-komarev** [comment]
@skollro I've found this issue too. I recommend you to create PR or at least separate issue.

**Comment by skollro** [comment]
It doesn't change the code, but its behavior as we implement two traits now implicitly. The problem is that we're now starting two transactions instead of one wrapping each test where `RefreshDatabase` is used. So something's wrong here anyway...

Now both of the two blocks are executed, before it was only one of them. The first one is calling `$this->beginDatabaseTransaction()` in `refreshDatabase()`.

```php
$uses = array_flip(class_uses_recursive(static::class));

if (isset($uses[RefreshDatabase::class])) { 
    $this->refreshDatabase();
} 
// ...
if (isset($uses[DatabaseTransactions::class])) { 
     $this->beginDatabaseTransaction(); 
}
```

**Comment by laurencei** [comment]
Ok - I see the issue now.

I've got a solution in mind - I'll submit a PR

**Comment by skollro** [comment]
Thank you! Yeah, the issue isn't very easy to track down...

**Comment by skollro** [comment]
#23121

**Comment by laurencei** [comment]
No - I've got a different idea. I'm testing it now before I submit a PR.

**Comment by laurencei** [comment]
Ok - I've submitted a PR with a different way to fix this.

**Pull request merged**
