### PR TITLE
[5.0] add getDates function with DELETED_AT constant in SoftDeletes Trait

### PR DESCRIPTION
**Pull request by dbwhddn10**
and laravel user use softDelete like https://github.com/laravel/docs/pull/1020

### CODE REVIEW

**Comment by kbirmhrjn** [comment]
Not sure this is the right way to go, if the Model itself has getDates method it will be overwritten.

**Comment by dbwhddn10** [comment]
This seems to delivery better what I want.

i will pull request refectory code like below code when this commit accepted 
```php
public function getDates()
{
    return array_merge(parent::getDates(), [static::DELETED_AT]);
}
```

**Comment by kbirmhrjn** [comment]
:+1:

**Comment by RomainLanz** [comment]
Why not just change your commit?

**Pull request closed without merging**
