### PR TITLE
[8.x] Illegal offset type in some relations

### PR DESCRIPTION
**Pull request by 0xbad0c0d3**
In case you have relations belongsTo or belongsToMany based on a casted to objects values and you are using `Model::with('belongsToRelationWithCasting')` you'll get `Illegal offset type`
Here is some example:
```php
class Video extends Model
{
    public function user_profile(): BelongsTo
    {
        return $this->belongsTo(UserProfile::class, 'user_profile_uuid', 'uuid');
    }
}
class UserProfile extends Model
{
    protected $casts = [
        'uuid' => UuidCast::class,
    ];
}
```
Without the patch
```php
>>> Video::with('user_profile')->first()
[!] Aliasing 'Video' to 'App\Models\Video' for this Tinker session.
<warning>PHP Warning:  Illegal offset type in /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php on line 179</warning>
=> App\Models\Video {#4604
     uuid: "f09ff84b-7ca8-4a57-acc2-f2fb88686ecd",
     user_profile: null,
   }

```
With applied patch:
```php
>>> Video::with('user_profile')->first()
[!] Aliasing 'Video' to 'App\Models\Video' for this Tinker session.
=> App\Models\Video {#4604
     id: 1,
     uuid: "f09ff84b-7ca8-4a57-acc2-f2fb88686ecd",
     user_profile: App\Models\UserProfile {#4837
       uuid: Ramsey\Uuid\Lazy\LazyUuidFromString {#4565
         uuid: "4c95d6cb-c3e9-455b-8789-40c8c90a1e25",
       },
     },
   }
```

### CODE REVIEW

**Comment by vdauchy** [comment]
Hi @0xbad0c0d3 

I just saw your PR and make me think of an old PR I did: https://github.com/laravel/framework/pull/32175

The cool thing is you follow one of the idea given by @staudenmeir ( https://github.com/laravel/ideas/issues/2144#issuecomment-601490311 ): `Casting the attribute to a string.`

The only issue I see with your PR is that it may not cover all relation types, which brings some inconsistencies. 

Good luck your PR :-)

**Comment by 0xbad0c0d3** [comment]
> Hi @0xbad0c0d3
> 
> I just saw your PR and it made me think of an old PR I did: #32175
> 
> The cool thing is you follow one of the ideas given by @staudenmeir ( [laravel/ideas#2144 (comment)](https://github.com/laravel/ideas/issues/2144#issuecomment-601490311) ): `Casting the attribute to a string.`
> 
> The only issue I see with your PR is that it may not cover all relation types, which brings some inconsistencies.
> 
> Good luck with your PR :-)

Thank you for your comment. I didn't notice I missed some other relations

**Comment by BrandonSurowiec** [comment]
@0xbad0c0d3 it would be a great idea to add a test to prove your fix. I've encountered this bug in the past trying to do a relation using a casted date field. :)

**Comment by 0xbad0c0d3** [comment]
> @0xbad0c0d3 it would be a great idea to add a test to prove your fix. I've encountered this bug in the past trying to do a relation using a casted date field. :)

Yes, you are right. Will find a time to do it

**Comment by taylorotwell** [comment]
Merged.

**Pull request closed without merging**
