### PR TITLE
[12.x] Remove unused parameter `$connection`

### PR DESCRIPTION
**Pull request by saMahmoudzadeh**
This PR, removes the unused parameter `$connection` from the methods `addFluentCommands`, `addFluentIndexes`, and `addImpliedCommands`.

### CODE REVIEW

**Comment by Jacobs63** [comment]
Changing method signatures is a breaking change, this cannot target 11.x

**Comment by saMahmoudzadeh** [comment]
Hi @Jacobs63 

These changes pertain to two protected methods that are not used anywhere else externally. Of course, I can also send it for version 12, depending on @taylorotwell  approval and feedback.

**Comment by Jacobs63** [comment]
> Hi @Jacobs63
> 
> These changes pertain to two protected methods that are not used anywhere else externally. Of course, I can also send it for version 12, depending on @taylorotwell approval and feedback.

Which, still, doesn't mean someone couldn't have extended the Blueprint class in their codebase, making this a breaking change.

**Comment by saMahmoudzadeh** [comment]
Great, no problem. We can send it in version 12.

**Pull request closed without merging**
