### PR TITLE
[10.x] Config markdown theme ignored

### PR DESCRIPTION
**Pull request by AEM5299**
This is a bug introduced by my earlier PR #46200. It is always defaulting to `default` theme unless explicitly set in the Mailable class, which ignored the config option ([reported by @pikseli](https://github.com/laravel/framework/pull/46200#issuecomment-1448217021)). This should fix that bug.

I am not sure if this is the best approach, so open to any suggestions or other ideas.

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks @AEM5299. But I'm afraid this PR can't be merged as it contains breaking changes to class constructs and replaces properties. I'll try to have a look myself.

**Comment by AEM5299** [comment]
We can get the value from config instead of always setting it to `'default'` [here](https://github.com/laravel/framework/blob/3c5ae94660bc72e9527e96cbd263733d9c5f9d6f/src/Illuminate/Mail/Mailable.php#L327). We can also change `Markdown` to not be a singleton, since it correctly sets the config value on construction.

**Comment by driesvints** [comment]
I think the former would work. You can maybe use ` Container::getInstance()` to resolve the config value.

**Review by driesvints — APPROVED** [review]

**Comment by u01jmg3** [comment]
@AEM5299: not sure if it's intentional but your PR no longer has any test coverage.

**Comment by taylorotwell** [comment]
Can you please fix conflicts?

**Comment by taylorotwell** [comment]
Fixed here: https://github.com/laravel/framework/commit/791f8ea70b5872ae4483a32f6aeb28dd2ed4b8d7

**Pull request closed without merging**
