### PR TITLE
[5.1] Allow migrations to be "batched" individually

### PR DESCRIPTION
**Pull request by cviebrock**
This adds a `--step` flag to the `artisan migrate` command that runs pending migrations sequentially, instead of in the same batch.  That way, you can roll them back individually instead of in the batch.

### CODE REVIEW

**Comment by cviebrock** [comment]
Sorry ... but I'm not sure how to fix the tests. Can someone maybe help?

**Comment by GrahamCampbell** [comment]
Update the mocking.

**Comment by CupOfTea696** [comment]
@cviebrock fixed the mocking for you, but you'll probably want to add some tests for the `--step` flag. I think once you merge the PR with your branch it should automatically appear here. 
https://github.com/cviebrock/framework/pull/1

**Comment by cviebrock** [comment]
Thanks @taylorotwell ... do you need me to make a PR against the documentation as well?

**Pull request merged**
