### PR TITLE
[master] Added type hinting to the request method parameter

### PR DESCRIPTION
**Pull request by michaeltintiuc**
Added type hinting to the request method parameter

### CODE REVIEW

**Comment by tillkruss** [comment]
Why?

**Comment by michaeltintiuc** [comment]
For the same reason we type hint Exceptions, I'm open to more constructive criticism though.

**Comment by tillkruss** [comment]
Sorry, didn’t mean to be rude. I’m curious why you want a type hint there.

**Comment by michaeltintiuc** [comment]
No worries, I've noticed that nowhere in the docblocks does it say that the `$request` could be any other class, could be good to reinforce it. But too many other packages may rely on the current implementation though.

**Comment by paulofreitas** [comment]
Unfortunately this would be a breaking change. You can't change the method signature of a contract or a inheritable class/trait in a point release. Note that this would break every installation because the `App\Exceptions\Handler` class extends the `Illuminate\Foundation\Exceptions\Handler`class and overloads the `render()` method. People often overload other changed methods. 👍 

When changing a method signature of a contract or inheritable class/trait you will want to propose the change for the next major release. 😉

**Comment by michaeltintiuc** [comment]
Couldn't agree more, thanks for a thorough explanation, would it be acceptable to change the base of the PR to master?

**Comment by paulofreitas** [comment]
@michaeltintiuc Yup, the change can still be rejected for whatever other reason, but you surely will want to target the `master` branch in this proposal - you can also add the `[master]` prefix to the PR title. 😉

**Comment by sisve** [comment]
This would be a certain breaking change for every Laravel 5 installation, everyone has a exception handler they need to change. This would also mean that any package that provides an exception handler for 5.5 LTS will no longer be able to provide one 5.6 or newer without keeping separate codebases/branches.

**Comment by michaeltintiuc** [comment]
I agree that this certainly is a breaking change, however it is a minor one which is easily spotted, there is a problem of separate code-bases, on the other hand this might be a good time to introduce new features with 5.5 being LTS. I'm still wondering why was this not type-hinted

**Pull request closed without merging**
