### PR TITLE
[9.x] Added ShouldDispatch

### PR DESCRIPTION
**Pull request by vinnygambiny**
This change adds an optional `shouldDispatch` function to jobs. The function gives the ability to keep the condition for dispatching or not a job inside of the job itself. With this, you can dispatch a job and if the shouldDispatch is false, the job will not be dispatched to queue and reduce processing.

### CODE REVIEW

**Comment by DarkGhostHunter** [comment]
What about forcing the dispatch? If I add the method, I'm forever bound to what the method returns.

I think this could be fixed with a `forceDispatch` on the job itself that changes de job condition to true.

**Comment by bert-w** [comment]
This adds unnecessary complexity imo.

**Comment by vinnygambiny** [comment]
I see it useful for keeping condition if the job needs to be run inside, in one place. These conditions can be like services are enabled, a user has subscribed to. It removes the condition from the handler, so the model isn't fetched to only discard the job at the first line. When you have more than 1k jobs per minute and you can discard job dispatch that will not be executed, that will help.

**Comment by BrandonSurowiec** [comment]
I like the strategy of adding my own static method to my job.

```php
public static function dispatchOnChange($model)
{
    return static::dispatchIf($somecheck, $model);
}
```

**Comment by bert-w** [comment]
What about sending a PR for `dispatchIf` and `dispatchUnless` so you can provide a callback as the argument? i.e. 
```php
public static function dispatchIf($condition, ...$arguments)
    {
        return value($condition)
            ? new PendingDispatch(new static(...$arguments))
            : new Fluent;
    }
```

(`dispatchNow()` is deprecated btw)

**Comment by vinnygambiny** [comment]
@bert-w like this, you need to repeat the condition everywhere you dispatch the job. With my solution, the job is responsible for knowing if we need to dispatch or not.

**Comment by bert-w** [comment]
yea thats true. Nothing a simple inheritance cant fix :)

**Comment by DarkGhostHunter** [comment]
```php
trait DispatchesConditionally
{
    protected $dispatchable = true;

    public function shouldDispatch()
    {
        return $this->dispatchable;
    }

    public function forceDispatch()
    {
        $this->dispatchable = true;

        return $this;
    }
}
```

```php
// Before
if ($message->isNotEmpty()) {
    $user->notify(new Notification($message));
}

// After
$user->notify(new Notification($message));

// Forcefully

$user->notify((new Notification($message))->forceDispatch());
```

Anyway, I don't think this is gonna pass as it's somewhat difficult tomake a "everyone should use this" case. I've been around quite a number of projects and haven't seen the need to.

**Pull request closed without merging**
