### PR TITLE
[5.4] Ability to check if messages exist in any named MessageBag

### PR DESCRIPTION
**Pull request by JayBizzle**
We quite often use named message bags and for various reasons, the message bags can contain messages with the same keys across multiple form submissions.

Currently in our templates, we have to do something like this...

```smarty
{if $errors->has('cv_file') || $errors->register->has('cv_file') || $errors->login->has('cv_file')}
    <div class="has-error">
{/if}
```

This PR would allow us to do this...

```smarty
{if $errors->anyBagHas('cv_file')}
    <div class="has-error">
{/if}
```

I added the `anyBagHasAny()` method as well to be consistent with the `MessageBag` functionality.

### CODE REVIEW

**Comment by taylorotwell** [comment]
anyBagHasAny is pretty gnarly. I'm not sure what that name means just glancing at it.

**Comment by JayBizzle** [comment]
@taylorotwell Yeah, i agree it's a bit of an awful method name, struggling to come up with a better one though.

Verbosely, it means `anyMessageBagHasAnyOfTheSpecifiedErrorKeys()`

Suggestions welcome from anyone 😕

**Comment by BrandonSurowiec** [comment]
@JayBizzle Maybe new up a class in a `bags()` method and have a more fluent interface?

```
$errors->bags()->has('cv_file')
```

**Comment by JayBizzle** [comment]
Went with the suggestion by @BrandonSurowiec

**Comment by taylorotwell** [comment]
Why not just makes bags() return a simple collection and you could do:

`$errors->bags()->contains->hasAny(['foo', 'bar'])`

**Comment by JayBizzle** [comment]
Yes, that would work, but there would be really no need to add even a `bags()` method as we could simply do this without any of this PR...

```php
$errors->getBags()->contains->hasAny(['foo', 'bar']);
```
The `$errors->bags()->haveAny(['cv_file', 'covering_letter']);` is obviously a little more fluent, but I am happy either way as long as I don't have to do those horrible `||` statements like in my original post. I never thought to use the `contains()` method like that.

**Comment by taylorotwell** [comment]
I like ->bags() more than ->getBags()

**Comment by taylorotwell** [comment]
Closing pending inactivity.

**Pull request closed without merging**
