### PR TITLE
[5.5] Add firstOrCreate method to factory builder

### PR DESCRIPTION
**Pull request by ahmed-aliraqi**
If you want to add item for one time without repeating or if it is unique.

For example : 
```php
factory(\App\User::class)->firstOrCreate(['email' => 'aliraqi.dev@gmail.com']);
```

in this example if you call `php artisan db:seed` more than once no errors will appeary

### CODE REVIEW

**Comment by morloderex** [comment]
This feels redundant why not just use `php artisan db:fresh --seed`?

**Comment by ahmed-aliraqi** [comment]
@morloderex If you later upgrade the application and add another table to the database, deleting the old data is not recommended :)

**Comment by Dylan-DPC** [comment]
Yeah i find this redundant as well. What if you have multiple rows with the same value?

**Comment by devcircus** [comment]
As factories are for specifically for testing purposes, the idea of firstOrCreate doesn't really make sense to me. Just my personal opinion. Then again, maybe there's  a use-case I've never thought of before.

**Comment by Dylan-DPC** [comment]
Yeah i agree with @devcircus. Also factories are mainly used for dummy data so it doesn't matter if the data is already present in your db or not.

**Comment by bloggervista** [comment]
But we need to think sometime there is collision on some column like username creating problem . It may fix those problems?

**Comment by ahmed-aliraqi** [comment]
Since you can add attributes on creating, I think you should not repeat these records when you run the factory again

**Comment by taylorotwell** [comment]
No plans to add this.

**Pull request closed without merging**
