### PR TITLE
Add missing newline

### PR DESCRIPTION
**Pull request by martinbean**
Added a newline missing from the file for consistent code formatting.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please send to 5.7. :)

**Comment by martinbean** [comment]
@GrahamCampbell I’ve changed the base to be `5.7`. Can you re-open this PR?

**Comment by driesvints** [comment]
Thanks!

**Comment by driesvints** [comment]
FYI: we had to revert this because this PR merged all the changes from master into 5.7. Why these commits didn't show up here is beyond me but it seems that there's a bug in Github when switching branches.

**Comment by martinbean** [comment]
@driesvints Ah, sorry about that!

**Comment by driesvints** [comment]
@GrahamCampbell yeah but the bug is the fact that the commit history in the PR doesn't reflect this. You're merging in all the commits from master but have no clue knowing that you're doing this.

**Comment by martinbean** [comment]
@driesvints It’s my bad for not checking which branch I made the change in but yeah, GitHub’s UI should have shown it was going to merge more than my commit when clicking the big green button.

**Comment by driesvints** [comment]
@GrahamCampbell yeah I can follow that reasoning. I've sent them a support ticket but they haven't got back yet.

**Pull request merged**
