### PR TITLE
[8.x] Support created_at timestamps on upserts

### PR DESCRIPTION
**Pull request by paras-malhotra**
As a follow-up to https://github.com/laravel/framework/pull/34698, this PR adds support for updating `created_at` timestamps on upserts.

I've modified the signature of the `upsert` method to include an optional third argument to be an array of the columns to be updated. If not provided, all columns will be updated.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Should we update `DatabaseQueryBuilderTest` to check the the raw SQL is correct using the new feature?

**Comment by paras-malhotra** [comment]
@taylorotwell, I've added `DatabaseQueryBuilderTest` tests for the new feature as well.

**Comment by taylorotwell** [comment]
I still don't really understand this method. Assume I have a `Post` database model. The table has `slug` (unique), `title` (string), and creation / update timestamps.

I want to bulk edit my post titles and upsert the posts... any new records should be inserted with a created at timestamp. I can't do this:

```php
    $results = Post::upsert([
        ['slug' => 'foo', 'title' => 'foo updated'],
        ['slug' => 'bar', 'title' => 'bar updated'],
    ], 'slug');
```

What am I supposed to do?

**Comment by paras-malhotra** [comment]
@taylorotwell for that case, you'd have to do this:

```php
$results = Post::upsert([
        ['slug' => 'foo', 'title' => 'foo updated'],
        ['slug' => 'bar', 'title' => 'bar updated'],
], 'slug', ['title']);
```

**Comment by mariomka** [comment]
Amazing work, I love it!

This PR also adds the possibility to define the value when a row is being updated, and it allows DB expressions. It is awesome, for example, you can add numbers:

```php
Stats::upsert(
    [
        ['id' => 1, 'page_views' => 1],
        ['id' => 2, 'page_views' => 5],
    ],
    'slug',
    [
        'visits' => DB::raw('stats.page_views + excluded.page_views'),
    ]
);
```

**Pull request merged**
