### PR TITLE
[5.1] Improve validateRequired method

### PR DESCRIPTION
**Pull request by dschniepp**
Fixed the conditions for countable elements #9885.

Sorry for the second pull request, I messed it up.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Is this not a breaking change anyway?

**Comment by dschniepp** [comment]
As far as I can see it will only cause a problem if somebody relies on the keys of an array of empty elements.

**Comment by GrahamCampbell** [comment]
I guess. Could you include a couple of tests please?

**Comment by GrahamCampbell** [comment]
There's still no test coverage of the countable changes.

**Comment by dschniepp** [comment]
But the existing tests for this method have been written in that way or am I missing something.
`public function testValidateRequired()` is covering `protected function validateRequired($attribute, $value) `.

**Comment by taylorotwell** [comment]
This is still a breaking change I think. What I suggest is using $validator->after(function() {}); to add in your custom hook to do whatever you want. It's easy to do custom validation this way.

**Comment by dschniepp** [comment]
For me it seems to be wrong when an empty array for an required field is fine but an empty string (character array) is false.

**Comment by lukasgeiter** [comment]
It doesn't matter if the current behavior makes sense or not. The change is still breaking and should go into 5.2 (`master` branch)

**Pull request closed without merging**
