### PR TITLE
[5.6] Reuse most of code of In rule in NoIn rule

### PR DESCRIPTION
**Pull request by mnabialek**

### CODE REVIEW

**Comment by ntzm** [comment]
This is a BC I believe, if someone was doing a check like this:

```
if ($rule instanceof In) {
    // Something
} elseif ($rule instanceof NotIn) {
    // Something else
}
```

It would change the behaviour

**Comment by mnabialek** [comment]
@ntzm Right, maybe we should target this to 5.6 then ?

**Comment by sisve** [comment]
It's semantically wrong. A NotIn rule is never a In rule.

**Comment by ntzm** [comment]
A better solution would be to create a new abstract class for these and make both extend that

**Pull request closed without merging**
