### PR TITLE
Make middleware stub implement middleware contract

### PR DESCRIPTION
**Pull request by hipsterjazzbo**
See also laravel/laravel#3241

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This isn't required.

**Comment by HipsterJazzbo** [comment]
I'd like to know why this isn't required. It makes the stub self-documenting, and enforces the contract over time, protecting against breaking changes. The contract is there, why not use it?

**Comment by GrahamCampbell** [comment]
Not using it allows people to use method injection. Taylor removed the interface by default because that; what he wants people to have by default. :)

**Comment by HipsterJazzbo** [comment]
Ah, that makes sense.

Is it documented anywhere, what places one can use method injection vs just constructor injection?

**Pull request closed without merging**
