### PR TITLE
Add missing functions in Dispatcher contract (#22951)

### PR DESCRIPTION
**Pull request by Naouak**

### CODE REVIEW

**Comment by taylorotwell** [comment]
No plans to add these right now.

**Comment by Naouak** [comment]
It's a bugfix, see #22951 not a new feature.

**Comment by laurencei** [comment]
@Naouak - the problem is you cannot change a contract on a point release, even if it is technically a bug fix. 

Your best bet is to target this to the 5.6 branch.

Also - you posted this PR without providing any description, examples or tests to show Taylor what this PR is for. You should take the time to write a detailed description of the problem, how this fixes it etc, and that way Taylor can judge it for inclusion.

**Comment by Naouak** [comment]
So basically, the LTS version is doomed to have broken tests and broken dispatchers because the contract is no good. You are telling developers to either not be able to test everything or go with a more heavy maintenance. This is not good. An incomplete contract is a serious bug that should be fixed ASAP as it makes the contract system useless.

I did provide a huge description of the problem, the consequences and how to reproduce it in the issue mentioned in the title and the commit message. I'm sorry if this was not clear enough.

**Comment by laurencei** [comment]
@Naouak  - but it cant be fixed - because it will be a breaking change to anyone doing a normal update. So the only solution is to put it into 5.6.

You should be able to extend the class, add your functions, then mock it for your tests - so there is a way around it for 5.5, although it is not ideal.

**Pull request closed without merging**
