### PR TITLE
[5.2] Add after and before to dependent rules array

### PR DESCRIPTION
**Pull request by themsaid**
Fixes https://github.com/laravel/framework/issues/11648#issuecomment-205878088

### CODE REVIEW

**Comment by vlakoff** [comment]
The 4 tests you added here fail on my computer ("Failed asserting that false is true")

**Comment by vlakoff** [comment]
Not really familiar with the code here, @themsaid do you have an idea what could be the cause of this platform discrepancy?

**Comment by themsaid** [comment]
@vlakoff hmmmm, it's hard to say. I think you'll need to trace the issue in `validateAfter` and `validateBefore` to see why they're failing, maybe it's related to using the year `2046` in the tests, but not sure at all.

**Comment by vlakoff** [comment]
Good catch, I tested on a 32-bit PHP. Will check this.

**Comment by vlakoff** [comment]
Yep, that's it.

Max working value is `2038-01-19`, as we will be very sad at 03:14:07 UTC on 19 January 2038 (that's only 12 years!).

Do you want to PR this?

**Comment by vlakoff** [comment]
ahem, 22 years left, not 12.

**Comment by themsaid** [comment]
Yup, I don't even know why I used `2046` :D It was totally random, maybe it's a sign something will happen this year, hopefully something good.

I'll fix that :)

**Pull request merged**
