### PR TITLE
[5.5] Remove useless braces in constructors

### PR DESCRIPTION
**Pull request by lucasmichot**
Remove useless braces in constructors

### CODE REVIEW

**Comment by browner12** [comment]
from what I've read it seems like there is no difference between the 2 (performance or functionality) so this seems unnecessary. what is the thought behind this?

**Comment by askaoru** [comment]
Although the brackets is not needed there, for me it would be good to keep them for the sake of being consistent with instantiating a class which have parameter in the constructor. Also in php official docs, the examples would always include the bracket.

**Comment by lucasmichot** [comment]
@browner12 @askaoru there is no performance difference - this is just for consitancy

**Comment by mathieutu** [comment]
Ok, I'm not the only one who think it's weird to remove them...

**Comment by lucasmichot** [comment]
A bit like short or long array notation, it's not about liking them or not, it's about consistency - as they are not set anywhere else

**Comment by TomasVotruba** [comment]
Great job!

**Pull request merged**
