### PR TITLE
Cast deleted_at to Carbon when using SoftDeletes

### PR DESCRIPTION
**Pull request by mul14**
Fix issue #10467

### CODE REVIEW

**Comment by ghprod** [comment]
:+1: 

Keren beuuddd om Mull :dancer:

**Comment by taylorotwell** [comment]
We want this to be added manually.

**Comment by jbrooksuk** [comment]
> We want this to be added manually.

For what reason? We automatically cast `created_at` and `updated_at`, so doesn't it make sense to be consistent?

**Comment by ghprod** [comment]
Maybe because not all of use using softDeletes trait in model

**Pull request closed without merging**
