### PR TITLE
[7.x] Log Fake

### PR DESCRIPTION
**Pull request by browner12**
The purpose of this is **solely** to fake the logger, **NOT** to provide assertions. All this does is send any generated logs into oblivion.

Here are some PRs that tried this in the past with assertions:

#22523
#25914

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Don't we already have a null logger?

**Comment by driesvints** [comment]
Hmm yeah I think our null logger works for this @browner12?

**Comment by GrahamCampbell** [comment]
Also, surely the stack logger with an empty array of stuff would work just fine too?

**Comment by browner12** [comment]
I'm not seeing the null logger in the docs or the code... am I missing it?

Also, I don't understand how I would use it if I call a specific channel or stack in the code.  For example:

``php
class MainController
{
    public function index()
    {
        //do some stuff

        Log::channel('slack')->warning('message');
    }
}
```

If I'm running a test, I can't change the code, so what do I change to not execute this Log?

**Comment by driesvints** [comment]
https://github.com/laravel/laravel/blob/master/config/logging.php#L94-L97

Then add this to your phpunit file:

```
        <server name="LOG_CHANNEL" value="null"/>
```

**Comment by browner12** [comment]
The problem is, that only sets the *default* log channel. Any code using the `channel()` or `stack()` method are going to ignore that completely, and continue to deliver to wherever the code has specified.

**Comment by driesvints** [comment]
Ah I see what you mean. Yeah then there's definitely merit in this 👍

**Comment by browner12** [comment]
As I look at the other Fakes a little more, it makes me think that the point of Mocking is so we can make assertions. If we're not making assertions, is a Mock the appropriate way to handle this?

Would adding a config value to `logging.php` called 'enabled' be more appropriate?  Then we could enable or disable **all** logging in our tests via the environment variable as needed.  Otherwise with this solution we're going to be adding `Log::fake()` to (possibly) ***a lot*** of tests.

**Comment by GrahamCampbell** [comment]
But why do we need the extra class in this PR. Just have fake use the exisiting stuff?

**Comment by browner12** [comment]
do we already have a class that implements the LoggerInterface that throws away the logs? If so I'd be happy to use that, but I don't see it.

@GrahamCampbell  what are your thoughts on my alternative idea of doing it with a `logging.enabled` config option?

**Comment by GrahamCampbell** [comment]
I'm 👎 on this entire PR tbh. Lots of logging happens without using the log facade in real apps too, so I don't think this is the best approach.

**Comment by browner12** [comment]
I don't think I follow. The Facade `fake()` method swaps out the bound `LogManager` (not just the Facade) in the container, so wouldn't all logging use the `LogFake` now instead?

What do you think of the config alternative?

**Comment by taylorotwell** [comment]
https://github.com/timacdonald/log-fake

**Comment by browner12** [comment]
I still think we need a way native to the framework to disable logging.

I'll put together another PR using the config method.

**Comment by lptn** [comment]
>I still think we need a way native to the framework to disable logging.
>https://github.com/timacdonald/log-fake

As a user of `Log::channels()` and `Log::stack()`, I expect that I can easily fake Log facade as it's possible with other facades. Having null driver is not enough for `Log::channels()` and `Log::stack()` cases.

**Pull request closed without merging**
