### PR TITLE
[6.0] Ensure all test methods are camelCased

### PR DESCRIPTION
**Pull request by lucasmichot**
At the moment all test methods are camelCased.

This PR ensures that the few tests which were snaked_cased (especially in `tests/Integration`) also respect this convention.

### CODE REVIEW

**Comment by browner12** [comment]
can this be enforced in StyleCI at all?

**Comment by driesvints** [comment]
This is kind of awkward but we've actually decided a while ago to go with snake case instead. I have it on my list to implement for all the libraries. Just fyi.

**Comment by CaddyDz** [comment]
Does that mean that this PR will be reverted in the future? @driesvints

**Comment by driesvints** [comment]
@CaddyDz we'll probably rename all test methods at some point yeah.

**Pull request merged**
