### PR TITLE
Add @logged to BladeEngine

### PR DESCRIPTION
**Pull request by ghost**
Check if current user is logged with this snippet of code 
```
@logged 
// do something for authenticated users
@endlogged
```
instead of 

``` 
@if (\Auth::user())
// do something for authenticated users
@endif
```

### CODE REVIEW

**Comment by eskrano** [comment]
don't use facade . If i disable Auth facade i get error in `@logged`  .

**Comment by mg-freelancer** [comment]
@eskrano so how to check current logged without facade ?

**Comment by eskrano** [comment]
@mg-freelancer  http://prntscr.com/eocb61 http://prntscr.com/eocbgj  look

**Comment by mg-freelancer** [comment]
OK I will fix it

**Pull request closed without merging**
