### PR TITLE
[5.4] Casted attributes should not be dirty

### PR DESCRIPTION
**Pull request by caiquecastro**
Casted attributes should not be dirty unless they are actually changed.

### CODE REVIEW

**Comment by caiquecastro** [comment]
Other alternative is to add a check like the originalIsNumericallyEquivalent method on HasAttributes trait.

**Comment by tillkruss** [comment]
Can you update the title to something that makes more sense?

**Comment by taylorotwell** [comment]
We should never be changing the `original` array. That is why it is called "original".

**Comment by caiquecastro** [comment]
@taylorotwell Can I update the PR with the suggested alternative:

add a check like the originalIsNumericallyEquivalent method on HasAttributes trait, but something like originalIsLogicallyEquivalent or originalIsBooleanEquivalent ?

**Pull request closed without merging**
