### PR TITLE
Backport allowing ramsey/uuid 4.0 for laravel 5.6.x

### PR DESCRIPTION
**Pull request by suadhuskic**
https://github.com/laravel/framework/pull/32086 for 5.6 🙏 

Is this possible to get a release of 5.6?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Sorry, no. Laravel 5.6 is not receiving any updates now. We might consider security updates if it was super major, but otherwise, nothing will be merged into 5.6.

**Comment by GrahamCampbell** [comment]
Please upgrade to Laravel 6 LTS as soon as possible.

**Comment by GrahamCampbell** [comment]
UUID v4 is a new feature, and not a bug fix.

**Comment by suadhuskic** [comment]
@GrahamCampbell -- trust me, i know bro -- i've been preaching the upgrade but its hard to find the resources, especially in this shitty time we are in right now. Is there really more than 10minutes of work to get this merged and released?

**Comment by GrahamCampbell** [comment]
Upgrading shouldn't take you long either.

**Pull request closed without merging**
