### PR TITLE
[5.2] Adding JSON_UNESCAPED_UNICODE to the method `asJson` in the `Model`

### PR DESCRIPTION
**Pull request by iv4art**
Need for correct JSON encoding of non-ASCII chars

### CODE REVIEW

**Comment by lucasmichot** [comment]
Tests?

**Comment by iv4art** [comment]
Sorry, it's not so pretty, my firs PR. This test? Or i need to make a new test?

**Comment by lucasmichot** [comment]
You have to demonstrate that a non-ASCII string will be properly json-encoded

**Comment by barryvdh** [comment]
Isn't this considered breaking? You could also consider adding $options as optional parameter, to pass that to json_encode.

**Comment by iv4art** [comment]
In the Model's method `asJson` for array casting using PHP function `json_encode`. Without option JSON_UNESCAPED_UNICODE cyrillic chars encoding to strings like `\uXXXX` and it makes unpossible searching with MySQL's `LIKE`.
8d65eaac-2bfd-11e6-800a-57f9baf4de26
8d6162e8-2bfd-11e6-8314-7716c83fc3b1

**Comment by GrahamCampbell** [comment]
Please send to 5.3.

**Comment by zanozik** [comment]
So are you going to send this patch to 5.3 anytime "soon"?

**Pull request closed without merging**
