### PR TITLE
[5.1] Add shortcut url() to app('url').

### PR DESCRIPTION
**Pull request by jumilla**
Add shortcut url() to app('url').

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is a breaking change as you're no longer resolving the contract.

**Comment by GrahamCampbell** [comment]
The two bindings COULD be different if people have rebound the contract.

**Comment by jumilla** [comment]
> This is a breaking change as you're no longer resolving the contract.
> The two bindings COULD be different if people have rebound the contract.

It can be understood from the angle of LTS.

But, why does two in case of url(), secure_url() use app('Illuminate\Contracts\Routing\UrlGenerator') ?

route(), action(), asset() uses app('url'), is it classified by a clear aim?

**Comment by GrahamCampbell** [comment]
Breaking changes aren't allowed in here anyway. LTS doesn't matter.

**Comment by jumilla** [comment]
Well...

```
if (is_null($path)) {
    return app('Illuminate\Contracts\Routing\UrlGenerator');
}

return app('Illuminate\Contracts\Routing\UrlGenerator')->to($path, $parameters, $secure);
```

is ok?

**Comment by franzliedke** [comment]
Yep, should be. This should fix the concerns.

@GrahamCampbell Can you reopen, please? :)

**Comment by GrahamCampbell** [comment]
Yes, but I'm still :-1: on the change.

**Comment by lukasgeiter** [comment]
I suggest we make this change in 5.2

**Comment by GrahamCampbell** [comment]
Maybe we should wait for @taylorotwell before doing anything?

**Comment by taylorotwell** [comment]
Going to hold off on this.

**Pull request closed without merging**
