### PR TITLE
[5.6] Accept "true" and "false" strings as acceptable boolean value during validation

### PR DESCRIPTION
**Pull request by frowhy**
#22241 Optimize can not verify boolean "true" and "false".

### CODE REVIEW

**Comment by sisve** [comment]
This isn't an optimization. It's adding more acceptable values to the boolean validation rule.

**Comment by Dylan-DPC** [comment]
So what happens to 'TRUE', 'FALSE', 'True', 'False'?

**Comment by jmarcher** [comment]
I do not think this is the right way to do it, just use 1 or 0 for form/url parameter booleans.

**Comment by frowhy** [comment]
@jmarcher But I see that 'accepted' can use strings.

**Comment by jmarcher** [comment]
Of course it does but I do not believe we should take the string "true" as an accepted value.

I mean we do not accept "one", "two", "three", etc. as acceptable numeric values.

**Comment by frowhy** [comment]
@jmarcher I know, but I think 'true' should be accepted as boolean.

**Comment by Dylan-DPC** [comment]
I agree with @jmarcher here. Also at some later point in your code, you might end up doing `$request->someBooleanOutput === true` and you will get some interesting results :wink:

**Comment by frowhy** [comment]
@Dylan-DPC This seems to be the case, but the result of 0 or 1 or '0' or '1' is also interesting because the 'request' can not directly convey the real Boolean value.

**Comment by 36864** [comment]
`false`, `0` and `'0'` all evaluate to false. `'false'` evaluates to true. This would lead to inconsistent behavior if you have code like `if ($input) doStuff()`.

```
php > if (true) echo 1; else echo 0;
1
php > if (false) echo 1; else echo 0;
0
php > if (1) echo 1; else echo 0;
1
php > if (0) echo 1; else echo 0;
0
php > if ('1') echo 1; else echo 0;
1
php > if ('0') echo 1; else echo 0;
0
php > if ('true') echo 1; else echo 0;
1
php > if ('false') echo 1; else echo 0;
1
```

**Comment by frowhy** [comment]
@36864 Implicit type is not recommended, we should use `if (1 === true)`, but this can not be verified. This is a problem. We should find a solution instead of using implicit 0, 1, '0', '1'.

**Comment by themsaid** [comment]
@taylorotwell check https://github.com/laravel/framework/pull/22243#issuecomment-347816281

**Comment by taylorotwell** [comment]
No plans to change this right now.

**Comment by DavidWiseGroup** [comment]
Any updates here?

> I do not think this is the right way to do it, just use 1 or 0 for form/url parameter booleans.

Framework provides casts on `Eloquent\Models`, provides various validation options for every type. 
However when you try to be consistent with the parameters, you should remember - no `'true'` and `'false'` booleans are accepted in laravel, just make your workaround by yourself, do I get it right?
Framework is going to be consistent and provide nice support for various cases, so why should it leave this unexpected behaviour for url encoded params?

> So what happens to `'TRUE'`, `'FALSE'`, `'True'`, `'False'`?

So the framework validates url params:
- [✔] Integer if string passed and `integer` rule set. As expected.
- [✔] Booleans if string passed and `accepted` rule set. As expected.
- [✖] Boolean if string passed and`boolean` rule is passed. As expected?

Maybe I should open new pull request and write an warning about boolean rule that does not accept `'true'` and `'false'` on url params? 🤔

**Comment by xyfantis** [comment]
@DavidWiseGroup i think this (https://github.com/laravel/framework/pull/18720) is relevant but ... no fix yet!? my way of fixing this:
```
if ($request->has('deleted') && !is_numeric($request->get('deleted'))) {
    $request->merge(['deleted' => ('true' == $request->get('deleted') ? true : false)]);
}
```

**Pull request closed without merging**
