### PR TITLE
[8.x] A method of making conditional attributes for multiple elements

### PR DESCRIPTION
**Pull request by mertasan**
~~Before:~~

```blade
<div {{ $attributes->merge(['class' => 'block']) }}>
    <div class="w-full @if($label) mt-2 @else mt-4 @endif"> ...
    <div @if($type) type="{{ $type }}" @endif class="mt-2 @if($inline) ml-2 @elseif($label) mt-2 @endif"> ...
</div>
```

~~Before:~~

```blade
<div {{ $attributes->class(['block' => true]) }}>
    <div class="w-full @if($label) mt-2 @else mt-4 @endif"> ...
    <div @if($type) type="{{ $type }}" @endif class="mt-2 @if($inline) ml-2 @elseif($label) mt-2 @endif"> ...
</div>
```

~~Before:~~

```
@if($label)
<div class="block @if($label) mt-2 @else mt-4 @endif">
 ...
@elseif($helpText)
<div class="block @if($label) mt-2 @else mt-4 @endif">
 ...
@endif
```

### After

```blade
<button @attributes('class' => 'bg-blue')>
{{-- or: --}}
<button {{ $attributes->make('class' => 'bg-blue') }}>
```
```html
<button class="bg-blue">
```
---
```blade
<button @attributes('class' => ['bg-blue' => true, 'bg-red' => false])>
{{-- or: --}}
<button {{ $attributes->make('class' => ['bg-blue' => true, 'bg-red' => false]) }}>
```
```html
<button class="bg-blue">
```
---
```blade
<button @attributes([
    'class' => ['text-white', 'bg-blue' => true],
    'disabled' => true
])>
{{-- or: --}}
<button {{ $attributes->make([
    'class' => ['text-white', 'bg-blue' => true],
    'disabled' => true
]) }}>
```
```html
<button class="text-white bg-blue" disabled="disabled">
```
---
```blade
<button @attributes([
    'class' => ['bg-blue' => true, 'bg-red' => false],
    'type' => ['button' => false, 'submit' => true]
])>
{{-- or: --}}
<button {{ $attributes->make([
    'class' => ['bg-blue' => true, 'bg-red' => false],
    'type' => ['button' => false, 'submit' => true]
]) }}>
```
```html
<button class="bg-blue" type="submit">
```
---
```blade
<input @attributes([
    'type' => ['text' => false, 'password' => true],
    'name' => ['new_password' => true],
    'wire:model' => ['new_password' => false],
    'disabled' => false
]) />
{{-- or: --}}
<input {{ $attributes->make([
    'type' => ['text' => false, 'password' => true],
    'name' => ['new_password' => true],
    'wire:model' => ['new_password' => false],
    'disabled' => false
]) }} />
```
```html
<input type="password" name="new_password">
```
---

### Example:

```blade
<x-form class="m-5"/>
```

```blade
<form $attributes->merge(['class' => 'block'])> {{-- or {{ $attributes->class(['block' => true]) }} --}}

    <div {{ $attributes->make('class', [
        'w-full',
        'ml-2' => $inline,
        'mt-2' => $label
    ]) }}></div>

    <button {{ $attributes->make('class', [
        'bg-blue' => $updateMode,
        'bg-green' => !$updateMode
    ]) }}></button>

    <button {{ $attributes->make([
        'type' => ['button' => $updateMode, 'submit' => !$updateMode],
        'class' => ['flex', 'bg-blue' => $updateMode, 'bg-green' => !$updateMode],
        'disabled' => !$hasPermission
    ]) }}></button>

    <input {{ $attributes->make([
        'type' => ['text' => $isText, 'password' => $isPassword, 'date' => $isDate'],
        'class' => ['form-input', 'text-red' => $hasError],
        'name' => [$name => is_null($wireModifier)],
        'wire:model' => [$wireModifier => !is_null($wireModifier)],
        'id' => ['one' => false, 'two' => true, 'three' => true]
    ]) }} />

</form>
```

### or @attributes directive:

```blade
<form @attributes(['class' => 'm-5 block'])>

    <div @attributes('class', [
        'w-full',
        'ml-2' => $inline,
        'mt-2' => $label
    ])></div>

    <button @attributes('class', [
        'bg-blue' => $updateMode,
        'bg-green' => !$updateMode
    ])></button>

    <button @attributes([
        'type' => ['button' => $updateMode, 'submit' => !$updateMode],
        'class' => ['flex', 'bg-blue' => $updateMode, 'bg-green' => !$updateMode],
        'disabled' => !$hasPermission
    ])></button>

    <input @attributes([
        'type' => ['text' => $isText, 'password' => $isPassword, 'date' => $isDate'],
        'class' => ['form-input', 'text-red' => $hasError],
        'name' => [$name => is_null($wireModifier)],
        'wire:model' => [$wireModifier => !is_null($wireModifier)],
        'id' => ['one' => false, 'two' => true, 'three' => true]
    ]) />

</form>
```

Output:
```html
<form class="m-5 block">

    <div class="w-full ml-2 mt-2"></div>

    <button class="bg-blue"></button>

    <button type="button" class="flex bg-blue" disabled="disabled"></button>

    <input type="text" class="form-input" name="laravel" id="two" />

</form>
```

**Note:**
- There may be typographical errors in the examples I have given here. (I tried to prepare quick examples.)

### CODE REVIEW

**Comment by taylorotwell** [comment]
I think something like this could be generally useful - but right now this would only work within a component. What if you want something similar to this but you aren't within a component?

**Comment by mertasan** [comment]
Thank you @taylorotwell 

It can be used on all Blade Components. It can also be used in Livewire Components. Please tell me if I'm wrong.

If you mean this should be used on all Blade templates with the component, I have a new suggestion.

I can create a PR for the example below.

```blade
{{-- welcome.blade.php --}}

<button @make([ {{-- or @attributes(...) or @attribute(...) or @makeAttributes(...) etc. --}}
        'type' => ['button' => false, 'submit' => true,
        'class' => ['flex', 'bg-blue' => false, 'bg-green' => true],
        'disabled' => false
    ]) }}></button>
```

I can create a new class. The blade directive and `$attributes->make(...)` method are processed in the new class.

For example:

```php

// class ComponentAttributeBag

public function make($attributes, $constraints = null, $escape = true)
{
    return Attributes::make($attributes, $constraints, $escape);
}
```

If there are other suggestions, I can devote all my time to it.

**Comment by mertasan** [comment]
I have added new examples containing Blade directives to my first post. I updated the PR.

**Comment by taylorotwell** [comment]
This a lot of code for me to take on the maintenance of forever, and contains `eval` statements, etc. I think I will hold off for now.

**Comment by taylorotwell** [comment]
Furthermore - it is actually already possible to just do this - so I'm not sure if we need a lot more code to handle this? Just a simple shortcut for creating a new attribute bag:

image

**Pull request closed without merging**
