### PR TITLE
[10.x] Add support for streamed JSON Response

### PR DESCRIPTION
**Pull request by pelmered**
This adds support for the [StreamedJsonResponse](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/HttpFoundation/StreamedJsonResponse.php) that was added in Symfony 6.3. 

Here is the Symfony documentation for this feature:
https://symfony.com/doc/6.3/components/http_foundation.html#streaming-a-json-response

This is how it can be used in Laravel with this PR:
```
<?php

namespace App\Http\Controllers;

use Generator;
use App\Models\User;

class ExampleController extends Controller
{
    public function index()
    {
        return response()->streamJson([
            'users' => $this->yieldUsers(),
        ]);
    }

    protected function yieldUsers(): Generator
    {
        foreach (User::query()->cursor() as $user) {
            yield $user;
        }
    }
}
```

The main benefits of streamed responses is that it uses a lot less memory and can be a lot faster, especially for very large responses. You can yield data that flushes straight into the response stream and the client can start to process the data before all the data is ready and sent on the server side. 

I also added a test helper:
```
$response->assertStreamedJsonContent([
    'data' => [
        ['id' => 1],
        ['id' => 2],
        ['id' => 3],
    ],
]);
``` 

I also added some test, but I'm not sure if they are enough.

### CODE REVIEW

**Review by driesvints — APPROVED** [review]

**Comment by amcsi** [comment]
Is there some counterpart to this for reading JSON requests streamed?

**Comment by pelmered** [comment]
> Is there some counterpart to this for reading JSON requests streamed?

I haven't super much experience with this just yet, but I have read some theory and I am going to implement this in our application the next weeks. 

Do you mean server side or client side? 
PHP is not that well equipped to handle this in a good way I think. With node you can use something like [stream-json](https://www.npmjs.com/package/stream-json) and with JS on the frontend you can consume this with fetch and some additional parameters. 
I can write an article about this when I have tested everything out.  Maybe also add some documentation about this in the Laravel docs?

**Comment by JosephSilber** [comment]
@pelmered In your example, what's the point of the `yieldUsers` method? Can the user cursor not be passed off directly?

Would this not work?

```php
response()->streamJson([
    'users' => User::cursor(),
]);
```

**Comment by JosephSilber** [comment]
> Do you mean server side or client side?
>
> PHP is not that well equipped to handle this in a good way I think.

While it seems @amcsi was asking about the client, I just want to give a shoutout to @cerbero90's excellent [Lazy JSON](https://github.com/cerbero90/lazy-json) PHP package 👌

**Comment by cerbero90** [comment]
@JosephSilber honoured to be mentioned by the Jedi master of Lazy collections! 🙏

**Comment by ppwalks24** [comment]
I've seen this prior as stated above. Plagiarism springs to mind!

**Comment by JosephSilber** [comment]
@tomgrohl nice work 👍 

[Is there a reason the cursor can't be used directly](https://github.com/laravel/framework/pull/49873#issuecomment-1936584370)?

**Comment by pelmered** [comment]
> Looks like this PR was based on an article I wrote here: https://blog.devgenius.io/how-to-stream-json-responses-in-laravel-9-and-10-6eccd67b0d65
> 
> You can see there has been a copy/paste for this section:
> 
> ```
> /** @var TestResponse $this */
> $this->baseResponse = new JsonResponse(
>     getResponseContent($this->baseResponse),
>     $this->baseResponse->getStatusCode(),
>     $this->baseResponse->headers->all(),
>     0,
>     true
> );
> ```
> 
> FYI `/** @var TestResponse $this */` was only needed because I was declaring a test response macro, so this could have been left out
> 
> It would have been nice to have been cited on this.

I did the whole implementation by just looking at the Symfony documentation. 
At the end I realised I might need some testing in the PR and I wasn't sure how to do that in PHP. That is is when I found that article though some Googling. In the end, I ended up not using that code anyway as it was better to just use `assertStreamedContent` instead. 

So why would I cite you?

**Comment by tomgrohl** [comment]
@cerbero90 thanks for confirming.

I was retesting this morning to check if it worked. Makes it nicer and easier to implement if you don't have to write the generator closure.

@pelmered If you didn't use my work then thats fine, no need to cite.

**Comment by tomgrohl** [comment]
As a side note I've updated my article to say its now in Laravel from 10.43: https://blog.devgenius.io/how-to-stream-json-responses-in-laravel-9-and-10-6eccd67b0d65

**Comment by pelmered** [comment]
> @JosephSilber according to the [implementation](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpFoundation/StreamedJsonResponse.php#L104) all sort of objects are supported:
> 
>     * iterables will be traversed
> 
>     * all other objects will be simply json encoded
> 
> 
> so in short, this is possible:
> 
> ```
> response()->streamJson([
>     'users' => User::cursor(),
> ]);
> ```
> 
> as the lazy collection will be iterated 👍
> 
> side note for @pelmered: thanks for this PR! :) it would also be great to add the method `streamJson()` to the `Illuminate\Contracts\Routing\ResponseFactory` interface

Yes, that sounds like a good addition. I will see if I can add that.

**Pull request merged**
