### PR TITLE
[5.6] Cast model attribute to any class

### PR DESCRIPTION
**Pull request by Whyounes**
Currently, you can cast a model attribute to a primitive type or JSON. This PR will let model attributes to cast to any class. Here's an example:

```
Class MyModel extends EloquentModel {
	protected $casts = [
		‘age’ => ‘int’,
		‘settings’ => Settings::class
	];
}

Class Settings implements Castable{
	protected $settings;

	public function __construct($value)
	{
		$value = json_decode($value);
		if ($value === false) {
			throw new InvalidArgumentException(“Invalid value”);
		}

		$this->settings = $value;
	}

	public static function fromModelValue($value) {
		return new static($value);
	}
}

$myModel = MyModel::first();

dump($myModel->settings);

// will return an instance of Settings class.
```

### CODE REVIEW

**Comment by a-komarev** [comment]
Casting model attributes to classes PRs raised couple of times already, but all the time they were rejected. This will be useful to create Value Objects.

**Comment by sisve** [comment]
How is this attempt better than anything previously attempted?

1. This implementation assumes that I am the creator of the value objects and can change them. I cannot use this if I want someone else's value objects.
2. How would this implement value objects that requires two columns? For example; a Money class that has both an amount and a currency.
3. How would this handle the reverse; `User::where('email', '=', $emailObjects)`?

**Comment by Whyounes** [comment]
@sisve 

I wasn't following all the previous propositions. This is just something I did a couple times in a Laravel app and I thought it could be useful to have out of the box instead of falling back to mutators.

1. If you're not the creator of the value object, create a factory class for the value. Which can build the value from different inputs.

2. Normally, a model attribute is just one column not too. So in this case you use your factory method to decide how to build the value object.

3. This can be in another PR maybe. We can just call toString on the object?

**Comment by RoccoHoward** [comment]
@Whyounes My implementation of something similar can be found at https://github.com/hnhdigital-os/laravel-model-schema

It's more than just attribute casting though, I've worked in a different approach to casts/hidden etc into a single schema array.

**Comment by sisve** [comment]
If you're interesting in catching up on previous discussions, start at https://github.com/laravel/framework/pull/18229

**Pull request closed without merging**
