### PR TITLE
[5.1] Fixing date validation for relative dates

### PR DESCRIPTION
**Pull request by jdavidbakr**
Changing the date validation for relative dates to check for
error_count instead of looking for a month/day/year set which are not
returned by date_parse for relative dates.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We probably need more tests here.

**Comment by taylorotwell** [comment]
Can you give some more examples of where our current setup fails? I don't often validate dates so it would help me understand. Thanks!

**Comment by jdavidbakr** [comment]
Specifically the issue I'm running into is "now"

Other relative dates that strtotime() will parse that fail validation are "next week" or "+1 month"

**Comment by jdavidbakr** [comment]
I gave some examples including the date_parse() output in the issue here:

https://github.com/laravel/framework/issues/10753

**Comment by taylorotwell** [comment]
I think one issue is: do we even want this validation function to allow "next week" as a valid date. I think people are probably expecting a more sensible date format from their UI? It certainly could be a breaking change since people won't be expecting this kind of input. If you want a more "free" date validation you might wish to use Validator::extend to define your own validator in which you could do this.

**Comment by jdavidbakr** [comment]
Thanks, I did use the extend for my use case - and thanks for fixing the docs as well.

**Pull request closed without merging**
