### PR TITLE
[5.5] Avoid getting meta from Paginator::toArray In PaginatedResourceResponse

### PR DESCRIPTION
**Pull request by eddiclin**
Paginator::toArray will make the items in it `toArray`, and sometimes the items are Eloquent Models, also make their `relationsToArray`, but this is not necessary in here.

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
This is a breaking change since you are changing the behaviour of the functions

**Comment by eddiclin** [comment]
Yeah, maybe. But I like the Resource feature and want to improve it. What can I do for this breaking change ?

**Comment by Dylan-DPC** [comment]
PR it to master (5.6)

**Comment by eddiclin** [comment]
Beside this problem, I have two confused points : 
1. How to remove some keys in the resource `meta` without changing the source code?
2. Could we advise the structure of keys in the resource `meta` in next version (5.6), like [this](https://github.com/thephpleague/fractal/blob/master/src/Serializer/ArraySerializer.php#L97). I think it looks better.

**Comment by deleugpn** [comment]
Great contribution. I specially like the idea of relying on an interface instead of checking for magic keys in the array.

**Comment by taylorotwell** [comment]
Looks like a breaking change and also doesn't clearly explain what is happening, doesn't show before / after behavior in description, etc.

**Comment by eddiclin** [comment]
@taylorotwell 
We just want to fetch some `paginationInformation` in `PaginatedResourceResponse` , but if using [this code](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php#L40)  it is `Paginator::toArray`, it will make [the paginator's items `toArray` ](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Pagination/LengthAwarePaginator.php#L165)
And sometimes these items are Eloquent Models, the model also make their [relationsToArray](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Model.php#L940), and relations model will make their [relationsToArray](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L237) one by one.
But the paginator's items is not necessary `toArray` in here, they have not relations with the paginate information.
So I change the code, make it call some functions of paginator directly. Avoid using `Paginator::toArray`.

**Pull request closed without merging**
