### PR TITLE
Update Hub.php

### PR DESCRIPTION
**Pull request by lilianjin**
formatting.

### CODE REVIEW

**Comment by jmarcher** [comment]
What?
Can you explain why this is needed? Clearly has nothing to do with formatting.
Please do not deliberately do a breaking change like this and do not give a proper description of why.

**Comment by lilianjin** [comment]
@jmarcher In the entity class Hub, when the variable $pipeline is false, the default variable $pipeline is the default, and the parameter 2 is type string|null. I think the ternary operation is more than one. Can directly let parameter 2 be string

Before
```php
   /**
     * Send an object through one of the available pipelines.
     *
     * @param  mixed  $object
     * @param  string|null  $pipeline
     * @return mixed
     */
    public function pipe($object, $pipeline = null)
    {
        $pipeline = $pipeline ?: 'default';
        return call_user_func(
            $this->pipelines[$pipeline], new Pipeline($this->container), $object
        );
    }
```

After
```php
   /**
     * Send an object through one of the available pipelines.
     *
     * @param  mixed  $object
     * @param  string $pipeline
     * @return mixed
     */
    public function pipe($object, string $pipeline = 'default')
    {
        return call_user_func(
            $this->pipelines[$pipeline], new Pipeline($this->container), $object
        );
    }
```

**Comment by jmarcher** [comment]
You changed a contract but did not change the implementation, this will break if I
 `$hub->pipe($object, null)` because the interface is expecrting a string.

I do not see this as a win, introducing a breaking change just for the sake of type hinting.

**Comment by lilianjin** [comment]
Of course, this is just a representation of my personal point of view. Officials can keep their own mode! I think that the separation of responsibilities can reduce some unnecessary overhead of the program.

**Comment by lilianjin** [comment]
I personally prefer the simple style,That's it!

**Pull request closed without merging**
