### PR TITLE
[5.2] Use class preloader 2.x

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Class preloader 2.x no longer requires us to hackyly run a console command within the code.

### CODE REVIEW

**Comment by taylorotwell** [comment]
This produces the same output as the 1.x version? Did you compare the output files?

**Comment by GrahamCampbell** [comment]
> This produces the same output as the 1.x version? Did you compare the output files?

It should do. My tests in the class preloader package pass before and after.

> Did you compare the output files?

I haven't checked the output within the context of laravel.

**Comment by taylorotwell** [comment]
Let's try to check the output in regards to Laravel and compare them.

**Comment by GrahamCampbell** [comment]
Sure, class preloader 2.x is still a moving target. I'll check back here in 2 days or so once I'm happy with class preloader 2.x.

**Comment by GrahamCampbell** [comment]
Will resend this later today. Want to do some other stuff at the same time. :)

**Pull request closed without merging**
