### PR TITLE
[5.2] Improved exception output for migrations and use DB Transactions

### PR DESCRIPTION
**Pull request by stanfieldr**
You would think migrations would always work, but sometimes developers do not use them properly. It becomes very difficult to track down where things went wrong when your migration folder is huge.

This PR does two things:
1) If a migration fails half way through, a DB transaction rolls it back
2) Shows a relevant error with a trace showing the migration that is messed up

migrations

### CODE REVIEW

**Comment by thecrypticace** [comment]
It might be worth noting that not all databases support rolling back DDL statements and that the databases that do may only support rolling back _some_ DDL statements. Of the databases Laravel supports MySQL is the only one (afaik) to not support it _at all_. The rest have fairly good support for transactional DDL.

**Comment by stanfieldr** [comment]
@thecrypticace I haven't thought about that, good point. I'll look at some different databases tomorrow and get a better idea. We can probably ignore calls from begin, commit and rollback if the database isn't supported maybe. And now that I think about it, I should really utilize this code in the `artisan migrate:rollback` too.

**Comment by stanfieldr** [comment]
Alright I think it's ready. On Illuminate\Database\Connection I implement a method to determine whether transactions are fully supported. That way in cases like MySQL it will not rollback only certain parts of the migration and confuse the developer. It defaults to false, but the child classes for postgres, sql server and sqlite override it and return true.

**Comment by taylorotwell** [comment]
We can't use facades in the core like this. They are for userland only.

**Pull request closed without merging**
