### PR TITLE
[5.4] Postgres: Grammar for pivot-related DELETE

### PR DESCRIPTION
**Pull request by ddzobov**
Added grammar for DELETE with USES clause

### CODE REVIEW

**Comment by tillkruss** [comment]
Could you please add a test for this?

**Comment by ddzobov** [comment]
#19989

**Comment by tillkruss** [comment]
I meant a unit test.

**Comment by taylorotwell** [comment]
No tests so not sure what it does.

**Comment by srmklive** [comment]
@taylorotwell Basically the issue pointed out by @ddzobov is that you can't delete related records for a relation using the `delete` method. For example:

```
$foo->bar()->delete()
```

works in MySQL but doesn't in PostgreSQL as described in #19989.

**Comment by srmklive** [comment]
As you can see the issue as stated by @ddzobov in #19989 happens in PostgreSQL & sqlite but not in MySQL.

screenshot from 2017-07-14 12 57 12

Error in Postgres
screenshot from 2017-07-14 12 58 29

No issue in MySQL 5.7
screenshot from 2017-07-14 13 06 47

**Comment by ddzobov** [comment]
I will add tests, refactor code and submit new PR in few hours.

**Comment by ddzobov** [comment]
#20062

**Pull request closed without merging**
