### PR TITLE
[5.2] Adding nutrition to uncountable list

### PR DESCRIPTION
**Pull request by chrispecoraro**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What use case do you have for this word? Laravel has intentionally missed out less common words.

**Comment by chrispecoraro** [comment]
I'm building a API for diabetics where there is a table of nutrition information. Many apps in the IoT era will deal with this (wearable devices, smart phone apps, etc).

**Comment by daylerees** [comment]
Probably more common than plankton. :D

**Comment by GrahamCampbell** [comment]
;)

**Pull request merged**
