### PR TITLE
Created a changelog website

### PR DESCRIPTION
**Pull request by JonasHiltl**
Hi, I'm the creator of [Openchangelog](https://github.com/JonasHiltl/openchangelog) and a big fan of the whole laravel ecosystem. 

I saw that this repo uses the `keep a changelog` format so I thought I would create a changelog website which you can check out at [laravel-frame.openchangelog.com](https://laravel-frame.openchangelog.com/).
It automatically stays in sync with your `CHANGELOG.md` file.

Would love to have this linked in your `README`. After all who really wants to read a `CHANGELOG.md` file when they could have a beautiful, styled website.

The badge I created for the `README` is just an idea, if you have a different idea or don't want the link in the repo just let me know.

### CODE REVIEW

**Comment by tontonsb** [comment]
> I saw that this repo uses the keep a changelog format

Does it tho? I'm not sure if your site is supposed to add some functionality compared to the `.md` on GitHub, but maybe it doesn't work because the changelog here doesn't actually follow the format. Currently it looks like a slightly different design and that's it.

**Comment by JonasHiltl** [comment]
@tontonsb if you don't see much value in it, that's fine for me. Just wanted to share it🤷‍♂️

**Comment by shaedrich** [comment]
> [laravel-frame.openchangelog.com](https://laravel-frame.openchangelog.com/).

Why "frame"? Does the sub domain have a character limit? If that's the case, just "laravel" should do fine.

Apart from that, it looks very much like [the releases overview page](https://github.com/laravel/framework/releases) so where's the benefit?

**Comment by taylorotwell** [comment]
No plans to add atm.

**Pull request closed without merging**
