### PR TITLE
Redirect output in quiet mode

### PR DESCRIPTION
**Pull request by peterpan666**
I find it annoying to have all the requests logged into the console sometimes. So I think in quiet mode that's a good idea to not output anything.

I wasn't sure about the naming though, maybe a seperate option would be better? Like `--dont-log-requests`, maybe a little verbose...

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This isn't a correct way to do it. We should be using symfony's verbosity flags instead of inventing something else.

**Comment by peterpan666** [comment]
Ok so you mean default to output nothing and trigger the output at a verbosity level?

Which verbosity level do we have to use? -v|vv|vvv?

**Comment by GrahamCampbell** [comment]
Probably `-v`.

**Comment by peterpan666** [comment]
Ok thanks

**Comment by peterpan666** [comment]
Since the OutputInterface is not used to echo those messages, is it still relevant to use the verbosity level?

**Comment by peterpan666** [comment]
Also I was thinking of this naming `--dont-log-requests` because maybe that would be interesting to store the requests into a file, then we could specify which file as an option or default it to a file in storage?

Don't really know which option is better

**Comment by GrahamCampbell** [comment]
Well logging an output to a file should still really be done by piping standard output to a file if one wants to do that?

**Comment by peterpan666** [comment]
Problem is all these messages from php -S seems to be on stderr not stdout

**Comment by taylorotwell** [comment]
Going to hold off on this.

**Comment by peterpan666** [comment]
Ok no problem.

Just for the records, I use this alias instead

```
alias serve='php artisan serve >& /dev/null'
```

**Pull request closed without merging**
