### PR TITLE
[5.4] Mark all unread notifications as read in one query

### PR DESCRIPTION
**Pull request by BSN4**
`auth()->user()->unreadNotifications->markAsRead();`

instead of loop and execute a query foreach unread notification .. this approach will only execute one query

### CODE REVIEW

**Comment by devcircus** [comment]
With the current implementation, if some of the notifications in the collection are already 'marked' as read, they will be skipped over and left untouched. With this implementation, all notifications in the collection will have their 'read_at' timestamp updated.

If we could keep this current functionality, that would be great.

**Comment by phpfalcon** [comment]
@devcircus `->whereNull('reat_at')` ?

**Comment by taylorotwell** [comment]
We already show how to do this in the docs. This will be a breaking change since events won't be fired, etc.

**Comment by phpfalcon** [comment]
@taylorotwell link? Please ?

**Comment by devcircus** [comment]
https://laravel.com/docs/5.4/notifications#marking-notifications-as-read
specifically:
> You may also use a mass-update query to mark all of the notifications as read without retrieving them from the database:
```php
$user = App\User::find(1);

$user->unreadNotifications()->update(['read_at' => Carbon::now()]);
```

**Comment by phpfalcon** [comment]
yes sure this code 

```php
$user->unreadNotifications()->update(['read_at' => Carbon::now()]);
```

better than :

```php
$user->unreadNotifications()->markAsRead();
```

👎

**Pull request closed without merging**
