### PR TITLE
[11.x] Add a new method "whereNullOr" to the Query Builder

### PR DESCRIPTION
**Pull request by musiermoore**
Hello guys 👋

### Introduction
The method simplifies `whereNullOr` (and `orWhereNullOr`) the process of adding a "where" clause that checks if a column is null or satisfies a given condition. This enhancement aims to improve code readability and maintainability when dealing with such common query patterns

### Motivation
I often write queries to check if a column is either null or meets a certain condition. Currently, this requires a nested closure with a where clause and sometimes using "use", which can be verbose and repetitive:
```
->where(function ($query) use ($id) {
    $query
        ->whereNull('category_id')
        ->orWhere('category_id', '=', $id);
})
```

With the introduction of the whereOrIsNull method, this can be simplified to:
```
->whereNullOr('column_name', '=', $id)
```

I think there should be another name for it, maybe `whereOrNull` or something else 🤔. So if you have a better one, it'll be great

And also, if you see it useful, I can add similar methods to others like `whereIn`, `whereDate`, etc. 

Thanks,
Alex 🐾

### CODE REVIEW

**Comment by calebdw** [comment]
Would the following not work?

```php
->whereIn('column_name', [$id, null])
```

**Comment by musiermoore** [comment]
In MySQL, it doesn't :(

**Comment by chu121su12** [comment]
Borrowing method names from migration, how about `whereNullable()`?

**Comment by musiermoore** [comment]
Won't it be confusing? It seems like `whereNull` or another condition at all to check if a column is nullable (?)

For me, atm, `whereOrNull` is the best suitable name and it can be applied to another methods (`whereIn`, `whereDate`, etc)

And a list of the rest names:
- `whereNullOr` (current name)
- `whereNullOrValue`

**Comment by taylorotwell** [comment]
Hmm, I think the idea isn't terrible but worry about the onslaught of PRs like `whereNullOrBetween`, etc. for every possible where type.

**Comment by musiermoore** [comment]
I agree, adding one method by one PR doesn't make sense

@taylorotwell Is it worth to add to every where type and send it in one PR? If you agree, I'll do it

**Pull request closed without merging**
