### PR TITLE
[5.5] Add array support to Optional

### PR DESCRIPTION
**Pull request by JosephSilber**
Lets you pass a _maybe array_ to `optional`, then access one of its keys:

```php
$location = optional($order->meta)['location'];
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
Is it super necessary since you could just do `$order->meta['location'] ?? null`?

**Comment by 36864** [comment]
I don't quite get what you're intending to fix here. Your tests would work just the same without the call to optional.
Quick tinker test:
```
>>> null['missing']
=> null
>>> ['present' => 'here']['present']
=> "here"
```
You're not testing for missing keys, which is the one thing that a call to optional might be able to help. As @taylorotwell mentioned, the null coalescing operator works just fine for that sort of call, but having optional array access could arguably improve consistency when you have a lot of objects and arrays you're trying to optionally access, or maybe even help with chaining this sort of call.

**Comment by JosephSilber** [comment]
@36864 wow! didn't even know that works in PHP :scream: 

Even now that I do know, I don't want to use that. Feels utterly wrong, and I have a feeling this might change in a future version of PHP. Silently ignoring array access on `null` is not the type of thing a sane language should allow (╯°□°）╯︵ ┻━┻)

**Comment by 36864** [comment]
You're using a language that lets you use variables without so much as a type hint, we've passed "sane" a long time ago.

This is documented behavior.
>Array dereferencing a scalar value which is not a string silently yields NULL, i.e. without issuing an error message. 
source: http://php.net/manual/en/language.types.array.php

Null is a scalar value, so attempting to access any position on it would naturally result in null.

As for not wanting to use it, that doesn't jive with this PR. You literally made a PR because you wanted to access null values as arrays. PHP lets you do that straight out of the box.

**Pull request merged**
