### PR TITLE
[5.0] Add "whereNot" To Collection

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Replaces #7177.

### CODE REVIEW

**Comment by JosephSilber** [comment]
I commented on the other PR, and I'll put that comment here too:

All 4 of these methods (and more) can be handled by [this single method](https://github.com/laravel/framework/pull/6502).

...and with a saner interface if you ask me.

@taylorotwell any chance you'd reconsider on that one?

**Comment by GrahamCampbell** [comment]
I think we should re-consider that and do it in 5.1. :)

**Comment by JosephSilber** [comment]
@GrahamCampbell it is a backwards compatible change, so we can do it in 5.0.

**Comment by GrahamCampbell** [comment]
Oh right. :0

**Comment by FractalizeR** [comment]
Looks, like this commit didn't make it into 5.0, right? There is no `whereNot` in the current 5.3.

**Comment by JosephSilber** [comment]
@FractalizeR in 5.3, you can do `where('foo', '!=', 'bar')`

**Comment by FractalizeR** [comment]
Yeah, I know. Just with WhereNot it's more declarative.

**Comment by JosephSilber** [comment]
@FractalizeR  "where not foo bar" is more intuitive than "where foo != bar"???

🤔

**Pull request closed without merging**
