### PR TITLE
[5.6] FilesystemManger return $this, after set a cutom disk

### PR DESCRIPTION
**Pull request by meteguerlek**
Hi, maybe we return $this after set custom disk.

```php 
Storage::set('server_name', $serverArray)
       ->put($fileName, $fileContents);
```

### CODE REVIEW

**Comment by meteguerlek** [comment]
setDisk() sounds good or?

**Comment by deleugpn** [comment]
sisve is probably feeling feeling the breaking changes being introduced somewhere.

**Comment by TBlindaruk** [comment]
I cannot see the `use case` when it can be the `breaking changes`

**Comment by meteguerlek** [comment]
fixing

**Pull request merged**
