### PR TITLE
[12.x] Replace md5 with much faster xxhash

### PR DESCRIPTION
**Pull request by GrahamCampbell**
In particular, this may make a noticeable difference for the etag content hashing. md5 doesn't really have a purpose in 2024: xxh128 is much faster and produces the same size hash as md5.

### CODE REVIEW

**Comment by hafezdivandari** [comment]
What about `File::hash()`?
- [ ] https://github.com/laravel/framework/blob/8ca1b5bbb9811585b58154a9e69aa0c67583e097/src/Illuminate/Support/Facades/File.php#L14
- [ ] https://github.com/laravel/framework/blob/8ca1b5bbb9811585b58154a9e69aa0c67583e097/src/Illuminate/Filesystem/Filesystem.php#L189

`hash_file` instead of `md5_file`?

- [ ] https://github.com/laravel/framework/blob/8ca1b5bbb9811585b58154a9e69aa0c67583e097/src/Illuminate/Filesystem/Filesystem.php#L544-L549
- [ ] https://github.com/laravel/framework/blob/8ca1b5bbb9811585b58154a9e69aa0c67583e097/src/Illuminate/Foundation/Vite.php#L765

**Comment by GrahamCampbell** [comment]
No, that is intentionally omitted, and should not be changed.

**Comment by timacdonald** [comment]
We would need to note in the upgrade guide that on the first deploy of an upgraded Laravel 12 app it will reset active rate limiters.

Could be important for applications.

**Comment by GrahamCampbell** [comment]
Alternatively, I could also revert that portion of this PR, if we don't want this upgrading step.

**Comment by timacdonald** [comment]
FWIW we _already_ use `xxh128` in a few places within the framework related to view hashing.

https://github.com/laravel/framework/blob/8ca1b5bbb9811585b58154a9e69aa0c67583e097/src/Illuminate/View/Compilers/Compiler.php#L85

https://github.com/laravel/framework/blob/8ca1b5bbb9811585b58154a9e69aa0c67583e097/src/Illuminate/View/Component.php#L201

https://github.com/laravel/framework/blob/8ca1b5bbb9811585b58154a9e69aa0c67583e097/src/Illuminate/View/Concerns/ManagesLayouts.php#L181

https://github.com/laravel/framework/blob/8ca1b5bbb9811585b58154a9e69aa0c67583e097/src/Illuminate/View/Compilers/Concerns/CompilesComponents.php#L52

**Comment by taylorotwell** [comment]
Agree with @timacdonald we probably only want to do this where it isn't "breaking" in the sense of resetting rate limiters, etc.

**Comment by valorin** [comment]
I like the idea of swapping to a more efficient hash. Also gets rid of more uses of MD5! 😁

One idea to avoid the breaking change issue is to define the hashing algo in a config file.

 Both algos can be used through `hash($algo, ...)`, so it would be trivial to swap between the two by changing the config value without making the code any more complicated. The next major release could default to `xxh128`, with an upgrade guide step to change back to `md5` if your application relies on cache, rate limiters, etc, across upgrades.

**Comment by imanghafoori1** [comment]
Maybe obvious but let me note the switch to the newer, faster algorithm in Laravel core can be done in an optional manner so that upgraders will continue to use `md5` without doing anything, and installers from scratch can enjoy and build upon `xxHash` but this requires introducing a new env variable though.
`config('app.hashing_algo', 'md5')` will do the trick.
`laravel/laravel` needs to include the variable in `.env.example`

**Comment by imanghafoori1** [comment]
> The next major release could default to `xxh128`, with an upgrade guide step to change back to `md5` if your application relies on cache, rate limiters, etc, across upgrades.

Maybe, It is better to default to `md5` in source code like this `config('app.hash_algo', md5);` and add `HASH_ALGO=xxh128` to `.env.example` in `laravel/laravel`, So upgraders from v11 do not break without noticing anything and installers v12 from scratch also get the performance benefit without noticing anything.

**Comment by GrahamCampbell** [comment]
There is negligible performance benefit. The cost of reading the config and checking it will be more than the performance gain of changing the algorithm for hashing like 10 bytes of data.

**Comment by GrahamCampbell** [comment]
OK, I've rolled back the rate limiter change. I think the etag change is low impact and is the place in this PR where we will see the main performance benefit. I think we should note this change in the upgrading guide.

**Pull request merged**
