### PR TITLE
[5.2] Use table name to derive foreign key from model

### LINKED ISSUE #10724: Foreign Key name should be derived from table name
```patch
...
     /**
     * Get the default foreign key name for the model.
     *
     * @return string
     */
    public function getForeignKey()
    {
-        return Str::snake(class_basename($this)).'_id';
+        return Str::singular($this->getTable()).'_id';
    }
...
```

### PR DESCRIPTION
**Pull request by znck**
Fixes #10724

### CODE REVIEW

**Comment by lukasgeiter** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Are there any other cases where this should be happening?

**Comment by GrahamCampbell** [comment]
Also, maybe this is actually a breaking change and needs to go to 5.2? Ping @taylorotwell.

**Comment by GrahamCampbell** [comment]
The fact you had to change the tests indicates that this is more a change to a behaviour you prefer, rather than a bug fix.

**Comment by lukasgeiter** [comment]
> Also, maybe this is actually a breaking change and needs to go to 5.2?

Definitely, and it is already ;)

**Comment by GrahamCampbell** [comment]
> Definitely, and it is already ;)

So this PR can be closed then?

**Comment by GrahamCampbell** [comment]
If it's already fixed on 5.2?

**Comment by GrahamCampbell** [comment]
Just looked at 5.2 and it's not already fixed here.

**Comment by GrahamCampbell** [comment]
Oh, wow. I see what's going on here. I misslabeled this PR.

**Comment by GrahamCampbell** [comment]
This is already targeted at 5.2, rather than is already fixed. Sorry for the confusion.

**Comment by taylorotwell** [comment]
What is your model's name that this needed to be done. Your model has a plural name?

**Comment by crynobone** [comment]
> What is your model's name that this needed to be done. Your model has a plural name?

I believe the problem is his has a model `Member` with `Member::$table = "users"`. However it mostly common in Laravel to pass in second parameter in this scenario.

**Comment by znck** [comment]
Surely its not a bug. Its more appropriate to derive foreign key from table name.

Secondly it would be easier to use table prefixes.

**Comment by taylorotwell** [comment]
@znck What is your model name and what is your foreign_key name... Do you have a $table variable on the model?

**Comment by znck** [comment]
@taylorotwell 
```
classes:
  id: integer

groups:
  id: integer
  class_id: integer
```

```php
...
class ClassModel extends Model {
  protected $table = 'classes';
}
...
class Group extends Model {
  public function relation()  {
    return $this->belongsTo(ClassModel::class);
  }
}
...
```


If `$table` field is there then its better to get foreign key column from table name. If `$table` field is not there then derive table name from model class and foreign key from derived table name.

**Comment by JosephSilber** [comment]
I am :+1: on this change. Makes more sense than what we have now.

**Comment by taylorotwell** [comment]
This is really the first time in 4-5 years that this has come up as a problem in Eloquent so I'd really like to just avoid doing this. I don't want to deal with the potential edge case BC breaks this would cause. Just pass the foreign key manually to the relationship methods in this case.

**Pull request closed without merging**
