### PR TITLE
[7.x] Add optional parameter $key to validated() methods

### PR DESCRIPTION
**Pull request by JeftavanderHorst**
Right now, it is possible to do this:
```PHP
$model->update($request->input('foo.bar.baz'))
```
but not this:
```PHP
$model->update($request->validated('foo.bar.baz'))
```

I think using `validated()` is better than using `input()`, because it filters out any data that is not explicitly allowed by the validator. This provides a (very) small security benefit, for example during mass assignment. Right now, the `validated()` method does not allow for any querying and therefore is less ergonomic when working with nested forms, which means I personally just don't bother very often.

This PR adds an optional parameter to `Validator::validated()` and `FormRequest::validated()` so that they work the same way as `Request::input()`.

Example usage:

Form:
```HTML
<input type="text" name="pet[owner][name]" required>
```

FormRequest:
```PHP
class UpdatePetRequest extends FormRequest {
    public function rules() {
        return ['pet.owner.name' => 'required'];
    }
}
```

Controller:
```PHP
public function update(UpdatePetRequest $request, Pet $pet) {
    // currently
    $pet->update(data_get($request->validated(), 'pet.owner'));

    // would be nicer as
    $pet->update($request->validated('pet.owner'));
}
```

As far as I can tell, this PR does not contain any breaking changes. I created some tests that are passing, and all existing tests are also still passing. Since this is my first PR to this project, I might be missing something in this regard. I would be happy to fix any issues that might arise.

### CODE REVIEW

**Comment by themsaid** [comment]
I we'll add this I think it's better we allow passing an array of attributes as well:

```
$request->validated(['name', 'email'])
```

**Comment by JeftaDotEU** [comment]
Sounds cool, I'll try to add that over the weekend. Should I add that to this pull request or would it be better to create a new one?

**Comment by taylorotwell** [comment]
This isn't thought through. If it's going to have consistency with something like "only" method on input then that uses Arr::set and has more intelligence in terms of missing value handling. The parameter should just be called "keys"... etc. There is no need to use `reduce` when you are actually doing a `map` operation, etc.

**Comment by JeftaDotEU** [comment]
Thank you for your response. I believe your feedback applies mostly to my second commit and not to the first one. I considered submitting a second PR rather than adding to this one, since they implement different features, but decided against it since they modify the same methods.

The first commit implements a single `key` parameter, which allows `validated()` to be used like `input()`. The second commit allows for multiple keys, which enables it to mimick `only()` as well. I do believe the latter would be useful and works as intended, but if you believe this is poorly thought out, maybe you could consider merging just the first one?

**Pull request closed without merging**
