### PR TITLE
[5.8] IDE autocomplete support for Blueprint::foreign() construction

### PR DESCRIPTION
**Pull request by pippinsmith**
Added ForeignDefinition class with methods for constructing foreign constraints, similar to the ColumnDefinition class. This allows for IDE autocomplete on foreign construction.

Can be split up into multiple classes so it only suggests the methods available in the current state of the construction flow (e.g. only suggest 'references' on foreign, only suggest 'on' on references). But this would create 3 extra classes (and therefor files, if classes need to each have their own file) instead of 1, which seems overkill in my personal opinion for a nice-to-have autocomplete feature, but feel free to disagree.

I also thought about possibly including constants for onDelete values, but I didn't want to squash too many features in this pull request

### CODE REVIEW

**Comment by staudenmeir** [comment]
The last time, this has been reverted: #26563

**Comment by pepijn-de-wachter** [comment]
I see, I didn't notice that revert, or the original implementation for that fact, my apologies.

Would the outcome change if this method was also altered?
```diff
/**
     * Create a new Fluent command.
     *
     * @param  string  $name
     * @param  array  $parameters
+    * @return \Illuminate\Support\Fluent|\Illuminate\Database\Schema\ForeignDefinition
-    * @return \Illuminate\Support\Fluent
     */
    protected function createCommand($name, array $parameters = [])
    {
+   if($name === 'foreign') {
+       return new ForeignDefinition(array_merge(compact('name'), $parameters));
+   }
        return new Fluent(array_merge(compact('name'), $parameters));
    }
```

that would be a rather easy change, and then it would also actually return that class implementation like in the case of ColumnDefinition

I didn't notice that option being discussed in #26563

Thank you for referencing that pull however, since I had no idea there were extra methods available on PostgreSQL, and your phpdoc is in many ways better than mine (I forgot to double type-hint the references method, I didn't even know you could do that)

**Comment by pepijn-de-wachter** [comment]
I have in the meantime committed changes that make this class functional as to TBlindaruk's original "complaint" of having a class pure for IDE purposes.
(I too don't see the difference between ColumnDefinition and ForeignKeyDefinition, they both don't have any additions in their class body, they rely on pure phpdoc for their functionality)
I'd like it if this PR would be accepted, tab-completing chained methods is always easier
(I'm the kind of person that type-hints the $query param in deep nested Eloquent Builder constructs so I always have completion for whichever type of where I'm using, and if the syntax is correct for all the intermediary ones.)

**Comment by driesvints** [comment]
Hmm, not a fan of adding stuff purely for IDE purposes. Have you tried looking into a package like https://github.com/barryvdh/laravel-ide-helper ? Even if the functionality you're proposing doesn't exists there, they might be wanting to accept a PR for it?

**Comment by pepijn-de-wachter** [comment]
> Hmm, not a fan of adding stuff purely for IDE purposes.

@driesvints in a way I totally get that, it doesn't make much sense to put something like that in the core framework when it doesn't add any functionality, though it makes me wonder why multiple people have a problem with this implementation, while if you look at #24444 it was merged without anyone raising that concern
I won't be completely devastated if this gets rejected or anything, but it's more of a consistency thing I'm trying to achieve. If multiple people vote against this for the sake of not mudding up the code with empty classes, then I'd say let's revert #24444 aswell, as it is in almost every way no different from this PR (in my humble opinion at least)

**Comment by driesvints** [comment]
yeah let's see how it goes :)

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
