### PR TITLE
[5.5] Add support for 'year' datatype for Schema migrations

### PR DESCRIPTION
**Pull request by nonsocode**
This commit adds support for year datatype for the different supported databases. Originally, only MySQL has native support for `year` datatype and as such, year type was left out of schema migrations.

This adds support for the `year` type and poly-fills with the `integer` datatype for other databases (PostgreSQL, SQLite, SqlServer)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I think something went a bit wrong here?

**Comment by nonsocode** [comment]
I'm a bit lost. what went wrong?

**Comment by GrahamCampbell** [comment]
>  Conversation 2 Commits 165 Files changed 129

**Comment by devcircus** [comment]
Close and try again.

**Comment by nonsocode** [comment]
Ok. I will. This is my first PR though and I changed about 7 files. not sure what i did wrong but i'll give it another go.

**Comment by devcircus** [comment]
Here's a good run-through on submitting a pull request, if you need assistance.
[Submitting a pull request to an open source project](https://mattstauffer.com/blog/how-to-contribute-to-an-open-source-github-project-using-your-own-fork/)

**Comment by nonsocode** [comment]
Thanks. I figured out what I did wrong. I branched off of master instead of 5.5

**Pull request closed without merging**
