### PR TITLE
[5.8] Use @error directive in auth stubs

### PR DESCRIPTION
**Pull request by antimech**
This makes code pretty neat by default.

Related to #28062

### CODE REVIEW

**Comment by taylorotwell** [comment]
Isn't the point you don't need to use $error->first anymore either? Feel free to re-submit with the full changes.

**Comment by antimech** [comment]
@taylorotwell what do you mean by full changes?

**Comment by driesvints** [comment]
@antimech see https://github.com/laravel/framework/pull/28273

**Comment by antimech** [comment]
Sorry, I did not notice it.

**Pull request closed without merging**
