### PR TITLE
[8.x] Improve Rate Limiter With Lock

### PR DESCRIPTION
**Pull request by paras-malhotra**
The current rate limiter is not atomic, which can cause bugs with high frequency hits. This PR improves it by wrapping the `hit` operation in a blocking lock. Symfony's new RateLimiter component uses the same strategy.

This also makes it possible for us to allow rate limiting per second (https://github.com/laravel/framework/pull/34856). I'm not quite sure if this is considered a breaking change. If yes, I can send to master.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can you link to Symfony's implementation. One thing I don't really like about this is it slows down web requests due to the blocking.

**Comment by paras-malhotra** [comment]
@taylorotwell, here are the [docs for the Symfony RateLimiter](https://github.com/symfony/symfony-docs/blob/5.x/rate_limiter.rst#rate-limiter-storage-and-locking) and the [source code](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/RateLimiter/FixedWindowLimiter.php#L48-L87).

I've also included a slide below from the Symfony Live Keynote on the RateLimiter.
Screenshot 2020-10-20 at 12 16 55 AM

**Comment by taylorotwell** [comment]
How long does their rate limiter block for if it can't retrieve a lock... how many milliseconds does it wait in between attempts to obtain a lock if it doesn't acquire one the first time?

**Comment by paras-malhotra** [comment]
@taylorotwell their sleep is [90-110 ms](https://github.com/symfony/symfony/blob/6e4d6eb2ddcfcbcab5b60bb4f13b9be70816f6b5/src/Symfony/Component/Lock/Lock.php#L77-L79) (random sleep in that range).

The blocking time is configurable by the users with a default of "unlimited".

**Comment by paras-malhotra** [comment]
@taylorotwell on a second look on the Symfony code, the lock is also optional with a default of `NoLock`. I guess we can close this if we don't want to support per second rate limiting.

**Comment by taylorotwell** [comment]
To be honest we don't receive a lot of requests for per-second rate limiting. So for now I think I will close this.

**Comment by arjanwestdorp** [comment]
Today I ran into a situation where rate limiting per second would be useful. We have a cron that is daily checking Algolia for new records, based on the user's saved queries. As our plan has a max queries per second where they really calculate it per second(https://www.algolia.com/doc/faq/accounts-billing/how-does-algolia-calculate-the-maximum-qps/), we would like to introduce rate limiting per second for this case. 

I can go with the Redis::throttle to achieve this but wanted to show this use case where per-second rate limiting would be useful.

**Pull request closed without merging**
