### PR TITLE
[5.4] Use UrlGenerator interface instead of concrete implementation

### PR DESCRIPTION
**Pull request by mpociot**
This PR fixes an issue where the Redirector class is using the concrete UrlGenerator implementation instead of the interface/contract.

### CODE REVIEW

**Comment by sgc-fireball** [comment]
vendor/laravel/framework/src/Illuminate/Routing/Redirector.php
```php
class Redirector
{
    public function __construct(UrlGenerator $generator)
    {
        $this->generator = $generator;
    }
    public function back($status = 302, $headers = [], $fallback = false)
    {
        return $this->createRedirect($this->generator->previous($fallback), $status, $headers);
    }
}
```

The method `previous` doesn't exists on the interface `\Illuminate\Contracts\Routing\UrlGenerator` but it exists in `Illuminate\Routing\UrlGenerator::previous`.

This Pull Request works but you can became problems if and instance of other UrlGenerator instances will be give in (without __call fallback to original UrlGenerator).

**Comment by mpociot** [comment]
@sgc-fireball you're right. There are a few methods missing on the interface, that are used in the Redirector:

* `previous`
* `full`
* `getRequest`

So it's not possible to swap out the UrlGenerator inside the Redirector right now.

Adding the missing methods to the UrlGenerator contract would break existing classes using the interface.

@taylorotwell @themsaid should I update the contract and add the methods to it?
The PR should then be sent to 5.5/master branch of course.

**Comment by taylorotwell** [comment]
This will probably need to go to 5.5, and yes would need to be updated if we want to use the interface.

**Comment by sgc-fireball** [comment]
Yes! We want to use an Interface =)

**Pull request closed without merging**
