### PR TITLE
Add Guard Parameter Support to Authentication Redirection Logic

### PR DESCRIPTION
**Pull request by itxshakil**
This PR enhances the `RedirectIfAuthenticated` and `Authenticate` middleware by introducing support for guard parameters in the redirection logic.

These additions allow for more granular control over the redirection process based on the guard used during authentication. It modifies the handle method to accept variable guard(s) parameters and adjusts the `redirectTo` method to utilize these guards when determining the appropriate redirect path.

This feature is handy in applications with multiple guards, enabling distinct redirection paths for different types of authenticated or unauthenticated users.

**Key Changes:**
- Modified the handle method to accept various guard parameters and process them accordingly.
- Updated the `redirectTo`  method to include an optional guard parameter, allowing for guard-specific redirection logic.
- Modified the unauthenticated method in `Authenticate`  to pass the guards array to the `redirectTo` method, ensuring that redirection logic can be customized based on the guards involved in the authentication attempt

**Benefits:**
- Increased flexibility in handling post-authentication redirects for applications using multiple guards.
- Allows for customized redirection paths based on the type of authenticated user, improving the user experience.
- Provides a more dynamic and context-sensitive redirection strategy for unauthenticated users, improving the overall user experience.
- Enhances the middleware's capability to support applications with complex authentication requirements, including those using multiple guards.
- Allows developers to implement guard-specific redirection logic, offering a higher degree of customization for application routing.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I think you could send this to 11.x branch.

**Comment by justconsult-dev** [comment]
> I think you could send this to 11.x branch.

I had opened a PR with 11.x but it goes closed because of backward compatibility issue and I was suggested to attempt master


https://github.com/laravel/framework/pull/52055

**Comment by itxshakil** [comment]
> I think you could send this to 11.x branch.

I had opened a PR with 11.x but it was closed due to backward compatibility issue and was suggested to attempt master

Link to previous 11.x PR
https://github.com/laravel/framework/pull/52055

**Comment by driesvints** [comment]
@taylorotwell the `redirectTo` method is being overwritten on quite a big portion of Laravel apps. It's best that this is done on master.

@itxshakil I can't re-open your PR because you deleted the branch.

**Comment by itxshakil** [comment]
@driesvints Should I send a new PR for the same

**Pull request closed without merging**
