### PR TITLE
Support direction from language file

### PR DESCRIPTION
**Pull request by mohamedsabil83**
Instead of publishing files and edit them to just change direction, especially for multilingual direction, the direction auto-imported from the language file.

### CODE REVIEW

**Comment by jmarcher** [comment]
The translation string does not make any sense, ltr = rlt, is counterintuitive.

**Comment by mohamedsabil83** [comment]
Any suggestion to support RTL without `vendor:publish`?

**Comment by jmarcher** [comment]
What is the problem with publishing the view? It makes sense if you want to modify it.

**Comment by mohamedsabil83** [comment]
As benefits of language files, I think that is better to control **direction** from **translation** or **config** file instead of publishing all files to just add `dir="rtl"`.

**Pull request closed without merging**
