### PR TITLE
[5.8] Add optional enforceOrderBy flag for DB Chunk

### PR DESCRIPTION
**Pull request by thomasm789**
I don't always want to order by when chunking through data - specially for dumping static data to third party products like Google BigQuery.

Adding the additional boolean with a default of true doesn't change any existing behaviour and allows you to declare a true or false after the callback.

Example

```php
DB::connection($dbConnection)
                ->table($source)
                ->chunk( $chunk, function ($row) use ($bigQ, $temp) {
                    $data = $bigQ->prepareData($row);
                    $bigQ->insert($temp, $data);
                }, false); 
```

### CODE REVIEW

**Comment by thomasm789** [comment]
I've tried clearing the whitespace issue that's failing the styleci and it doesn't seem to want to update

**Comment by driesvints** [comment]
@thomasm789 can you fix the StyleCI warning?

**Comment by taylorotwell** [comment]
I don't generally add boolean flags to methods. They aren't very readable from the consumer side. Also I'm not sure chunk is reliable at all with no order by.

**Comment by xiaoronghuang** [comment]
@taylorotwell enforceOrderBy method will cause slow query.
Because the primary key is added as the order by column by default, the query statement finally uses the primary key index to start a full table scan, but the index where we want to take effect in the where condition is invalid.
So I think it is necessary to add a flag to judge whether to use order by.

**Pull request closed without merging**
