### PR TITLE
[5.7] Add Arr::stack() method.

### PR DESCRIPTION
**Pull request by lucasmichot**
This PR introduce a `\Illuminate\Support\Arr::stack()` method (in lack of a better name).

This method give the ability to push a value onto an array using dot notation.

This PR targets `5.7` on purpose, as some developer might already have a `stack` macro.

### CODE REVIEW

**Comment by sisve** [comment]
This sounds like array_push, which does a totally different thing.

1. Why should pushing a null key return an empty array?
2. Why are some valid array keys (empty strings, string with space) returning empty arrays?
3. Why should an existing non-array value be lost?

**Comment by devcircus** [comment]
Yeah seems like "push" doesn't tell the story here. 

It let's you push a value to an existing key if that key's value was already an array. Otherwise it drops the existing value for that key and starts with an empty array, to which it adds the passed value.

**Comment by lucasmichot** [comment]
@sisve, this has been renamed to `Arr::stack`, passing an empty or null key returns the original array and an exception is thrown when a now array value already exists.

**Comment by taylorotwell** [comment]
No plans to add this to the core right now.

**Pull request closed without merging**
