### PR TITLE
[5.0] Pagination removed from root and fixed the data

### PR DESCRIPTION
**Pull request by bingvanmoorsel**
<h1> Pagination </h1>

I bumped into 2 bugs in the pagination and in the test for the pagination.

<h2> Data </h2>

The data that was beeing fetched was the same on every page.
I fixed this by edditing the formula for the items.

<h2> Root </h2>

The paginator worked fine as long as you used it on the root of your application. Saw more people struggeling with the use of the setPath('') fix. I changed the default path to null and removed the forward slash in the constructor so the pagination is usable on a subpage.

I had to fix the matching test, the test results didn't check for the correct values. The second page only should have 1 record.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I can't recreate your data the same on every page thing, which makes me a little nervous to merge this. Also have never heard that from anyone else on 5.0. Can you show me how to recreate that?

**Comment by GrahamCampbell** [comment]
This looks to be breaking too. The pagination component is one thing that people definitely mess with. We can't change it's behaviour like this.

**Comment by bingvanmoorsel** [comment]
This is the array slice problem:

```php
Route::get('paginator', function(){
   $data = ['item1','item2','item3','item4','item5','item6','item7','item8','item9'];

   $data = new Paginator($data, 4, 2);

   dd($data);
});
```

Gives me the following result
image
You see that the items in the array of the second page are item 1 to 4. These should be 5 to 8.
This is tested in the last unit test, but it wasn't checking for the correct values


For the page problem I changed my 
```php
dd($data);
```
to
```php
echo $data->render();
```
image
You see that the link to the next page is pointing to the root path, instead of paginator?page=3

**Comment by taylorotwell** [comment]
OK, this is somewhat of a common misconception. The Paginator accepts data that is already "sliced" (i.e. from a Database limit and offset statement)... it does not do the slicing itself.

**Comment by bingvanmoorsel** [comment]
Oke, I indeed expected the paginator to slice the data for me (this is what I changed the code to in my fork). The official documentation states: "Sometimes you may wish to create a pagination instance manually, passing it an array of items.".
I was under the impression that this ment passing the entire array of items. My misunderstanding, maybe an idea for 5.1 ?

As for the path, I dont think it should redirect the next page to the root of my application by default?

**Comment by taylorotwell** [comment]
I can't recreate that root path issue either, let me look at it again.

**Comment by bingvanmoorsel** [comment]
http://laravel.io/forum/02-09-2015-laravel-5-pagination-query-string-after-slash-issue

Here is a forum post about the same problem.

**Comment by taylorotwell** [comment]
You should just pass it the path like the query builder does:

```
return new LengthAwarePaginator($results, $total, $perPage, $page, [
     'path' => Paginator::resolveCurrentPath()
]);
```

Instead of `resolveCurrentPath`, just use `Request::url()`.

**Pull request closed without merging**
