### PR TITLE
[5.6] Breaking the loop when abstract alias is found

### PR DESCRIPTION
**Pull request by oguz-yilmaz**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. Is this not a breaking change though?

**Comment by GrahamCampbell** [comment]
What does this fix please?

**Comment by tillkruss** [comment]
Prevents unnecessary iterations?

**Comment by thecrypticace** [comment]
I think this is fine. The same alias shouldn't appear multiple times in the aliases array.

**Comment by oguz-yilmaz** [comment]
@tillkruss Exactly.Like @thecrypticace said, same alias shouldn't appear multiple times.

**Pull request closed without merging**
