### PR TITLE
[5.6] Postgres add comment (#18782)

### PR DESCRIPTION
**Pull request by andersondanilo**
https://github.com/laravel/framework/issues/18782

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
This is a breaking change.

**Comment by xakzona** [comment]
usefull commit

**Comment by taylorotwell** [comment]
Why not implement it like the MySQL grammar?

**Comment by andersondanilo** [comment]
Hi @taylorotwell,

I tried to imitate MySql, but in postgres the comment is added in another statement, not as a "modifier"

**Pull request merged**
