### PR TITLE
[5.8] Fix the collation bug when changing columns in a migration.

### PR DESCRIPTION
**Pull request by jensdenies**
This allows the user to add custom schema options to the Doctrine DBAL column. This serves as a fix for #28487.

### CODE REVIEW

**Comment by driesvints** [comment]
This could use a test. Can you add one? Also needs some StyleCI fixes.

**Comment by driesvints** [comment]
This is odd... StyleCI passes but the styling is completely wrong.

**Comment by driesvints** [comment]
@GrahamCampbell do you might know why StyleCI passes for these changes but the styling is completely different than what the `.styleci.yml` file requires? https://github.com/laravel/framework/blob/5.8/.styleci.yml

**Comment by JacksonIV** [comment]
@driesvints I've added a test, please let me know what you think. By the way, StyleCI shouldn't check the "tests" directory, right?

**Comment by driesvints** [comment]
@JacksonIV it should but there's something really wrong with this PR for some reason. I need @GrahamCampbell's input before we proceed. 

This isn't by coincidence a really old branch from before we added the StyleCI config file?

**Comment by JacksonIV** [comment]
@driesvints That could be the problem. I'll send in a new PR.

**Pull request closed without merging**
