### PR TITLE
Fix DB offset method. Can not be negative.

### PR DESCRIPTION
**Pull request by KaneCohen**
As suggested, pulling to 4.1.

### CODE REVIEW

**Comment by vlakoff** [comment]
@KaneCohen Out of curiosity, could you quickly explain your use case, where the application calculates negative offsets (and capping to 0 is an acceptable solution)?

**Comment by KaneCohen** [comment]
@vlakoff, it's used in situations where user might manually set page to a negative number in GET params. For example: https://example.com/list?page=-3

**Comment by vlakoff** [comment]
Thank you for your reply. I have just answered on a similar case: https://github.com/laravel/framework/pull/21658#issuecomment-336791223

**Comment by KaneCohen** [comment]
I more or less agree with your comment since in the referenced issue pagination is called manually. However Eloquent database pagination accesses request variables internally and therefore should gracefully handle incorrect user input - framework should be helpful to the end user after all.

Besides, MySQL and Postgres and probably other databases do not accept negative values in offset and limit, so no functionality is lost.

**Pull request merged**
