### PR TITLE
Included changed namespace for symfonyuploadedfile

### PR DESCRIPTION
**Pull request by robjbrain**
Just copied across Taylor's fix for the 5.2 branch here (https://github.com/laravel/framework/commit/85249beed1e4512d71f7ae52474b9a59a80381d2) into the 5.1 branch as well.

From the issue discussed here: https://github.com/laravel/framework/issues/12335

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This isn't needed on 5.1. There is no laravel uploaded file class, so there is no need to resolve naming conflicts.

**Comment by robjbrain** [comment]
Hi @GrahamCampbell to be clear, the naming conflict wasn't what I was trying to fix. The second commit simply changed the name of the class to fix my own typo (I had used SymfonfyUploadedFile  further down the file).

The original commit was simply fixing the bug https://github.com/laravel/framework/issues/12335 in the 5.1 branch using Taylor's own fix https://github.com/laravel/framework/commit/85249beed1e4512d71f7ae52474b9a59a80381d2 from the 5.2 branch.

Should I resubmit without the namespace changed?

I'm not too familiar with contributing to projects such as Laravel so some explanation may be necessary if i'm not doing it properly :)

**Comment by GrahamCampbell** [comment]
I think this change was intentionally not put into 5.1 because of it's breaking nature. 5.1 users are already compensating for the 5.1 behaviour.

**Comment by robjbrain** [comment]
Ah I didn't realise it would be a breaking change, nothing in it looking breaking. Can you explain how people are "compensating" for the 5.1 behaviour. I haven't been able to find any reference to it.

**Pull request closed without merging**
