### PR TITLE
[10.x] Prevent encoding of IPv6 brackets in URL from route helper

### PR DESCRIPTION
**Pull request by MuriloChianfa**
Solving the issue of: [IPv6 URLs with square brackets are not supported by Laravel's routing system](https://github.com/laravel/framework/issues/46315)

Adding test before change, and running the same test after changes:
before-and-after-modifications-for-laravel-framework-ipv6-encoding-brackets-in-domain

### CODE REVIEW

**Comment by MuriloChianfa** [comment]
The test failure is not related to this PR:

1) Illuminate\Tests\Support\SleepTest::testItSleepsForSecondsWithMilliseconds
Failed asserting that 1.5307338237762451 matches expected 1.5.

D:\a\framework\framework\tests\Support\SleepTest.php:39

**Comment by GrahamCampbell** [comment]
This is a breaking change. Most people do want to encode braces. For example applications running behind aws cloudfront will break without the en coding.

**Comment by GrahamCampbell** [comment]
I think it is pretty unusual to want to use ipv6 ips directly as hostnames (not the same as having an AAAA record).

**Comment by MuriloChianfa** [comment]
> This is a breaking change. Most people do want to encode braces. For example applications running behind aws cloudfront will break without the en coding.

Reading the [RFC - Uniform Resource Identifier (URI): Generic Syntax](http://www.faqs.org/rfcs/rfc3986.html), i can undertand you, the square brackets must be encoded for the URI part of a complete URL.

But in the same [RFC3986](http://www.faqs.org/rfcs/rfc3986.html) in section 3.2.2, he said with the new IPv6 identifier notation using "[" and "]" to identify the IP literal of host, we cannot encode these characters.

image

Maybe we can modify the method of encode the entire URL at [rawurlencode](https://github.com/laravel/framework/blob/c59d540ab142d36ee0f62c3ddc749329a968466b/src/Illuminate/Routing/RouteUrlGenerator.php#L96) for two encodes, not encoding square brackets for literal IPs and encoding for the URI as described on the [RFC3986](http://www.faqs.org/rfcs/rfc3986.html).

**Comment by GrahamCampbell** [comment]
Only brackets as part of the hostname should not be encoded. The problem is that your changes applies across the whole URL. My point is that it's better to get this wrong for hostnames because this affects almost nobody (possibly you are the first ever person to have encountered this issue) vs the issues this fix will in turn cause. I don't object to a proper fix, but this isn't a proper fix, unless I'm missing something?

**Comment by MuriloChianfa** [comment]
> I think it is pretty unusual to want to use ipv6 ips directly as hostnames (not the same as having an AAAA record).

In my use case, its not just simple like that...

My application is self hosted by the customers and they cannot trust in the domain name resolutors for access their system, given that systems not be able have any time of downtime (like SLA of 99.99999% of acessibility a year). Them have a few problems with can occore to cause a inacessibility:

- DNS server going down => the web server is up and running, but the name resolver is down.
- The route for server in IPv4 is congested or down (maybe a DDoS attack via IPv4) and have only up the IPv6 network.
...

**Comment by MuriloChianfa** [comment]
> Only brackets as part of the hostname should not be encoded. The problem is that your changes applies across the whole URL. My point is that it's better to get this wrong for hostnames because this affects almost nobody (possibly you are the first ever person to have encountered this issue) vs the issues this fix will in turn cause. I don't object to a proper fix, but this isn't a proper fix, unless I'm missing something?

I wasnt the first person hahaha, @kronos1345 on [IPv6 URLs with square brackets are not supported by Laravel's routing system](https://github.com/laravel/framework/issues/46315) that was.

And yes, now reading the RFC, I realize the correction is wrong and could cause problems, I'll try to modify it to cover the other use cases, and to be right with the RFC.

**Comment by GrahamCampbell** [comment]
> The route for server in IPv4 is congested or down (maybe a DDoS attack via IPv4) and have only up the IPv6 network.

That would not cause a problem, because the hostname would just be a string.

**Comment by MuriloChianfa** [comment]
> > The route for server in IPv4 is congested or down (maybe a DDoS attack via IPv4) and have only up the IPv6 network.
> 
> That would not cause a problem, because the hostname would just be a string.

Not all of my customers use domain names for their internal systems, or havent the two A and AAAA records, so they directly use IPv4 and IPv6 addresses to access the systems in cause of problems, and if the route for the system using IPv4 address is unavailable, the last option to use is IPv6 address directly using the syntax of "http://[IPv6Address]".

Idk if it would be a framework guideline to just use it with domain names.

**Comment by NiKiZe** [comment]
So everything is URL encoded, even host and other parts that should not be url encoded?
The correct thing here is to split the URL and then encode the parts correctly.

IPv6 literals is not uncommon, and should work just like your http://192.168.0.1 urls does, if not then the dots in IPv4 literals should be encoded as well to make sure we have consistent behavior between Legacy IPv4 and IPv6

**Pull request closed without merging**
