### PR TITLE
[7.x] Remove temporary variable

### PR DESCRIPTION
**Pull request by browner12**

### CODE REVIEW

**Comment by danilopinotti** [comment]
Out of curiosity, what is the advantage of not using temporary variables?

**Comment by browner12** [comment]
if you go overboard on them, it can have negative memory usage impact.

removing just one of these probably has minimal impact from a memory standpoint, and if the readability is significantly reduced I will usually just leave the temp variable in.

**Comment by GrahamCampbell** [comment]
This PR makes no difference when opcache is enabled, actually.

**Comment by browner12** [comment]
good to know, thanks Graham.

**Pull request merged**
