### PR TITLE
Removing unnecessary switch

### PR DESCRIPTION
**Pull request by carloscarucce**
Simplify this method by removing an unnecessary switch/case

### CODE REVIEW

**Comment by JoostK** [comment]
This is done intentionally. It improves performance and readability of stack traces.

**Comment by kamui545** [comment]
I think it's done on purpose for perfomance

**Comment by barryvdh** [comment]
See #12120 which was merged for L5.3, which is even faster.

**Comment by xxnoobmanxx** [comment]
@barryvdh Cool! Php 5.6+, right?

**Comment by GrahamCampbell** [comment]
We already made this change in 5.3.

**Pull request closed without merging**
