### PR TITLE
[8.x] make method has public access

### PR DESCRIPTION
**Pull request by zoulux**
make method increment and decrement then become public
#34107

### CODE REVIEW

**Comment by zoulux** [comment]
#34112

**Comment by zoulux** [comment]
@taylorotwell
Hello , I have the following question.
```php
     $course = Course::query()->first();
     $course->increment('total_star_score', $star);
```

the phpStorm tip `Member has protected access, but class has magic method __call`

I found the increment method is protected.

**Comment by zoulux** [comment]
@taylorotwell 
I don't understand why this method needs protected.

**Comment by siarheipashkevich** [comment]
@taylorotwell could you please explain why these methods should be protected and can't be public?

**Comment by GrahamCampbell** [comment]
The objection is to the target branch. This is a major breaking change.

**Pull request closed without merging**
