### PR TITLE
[5.5] Promote RouteGroup to first-class citizen, enabling $router->getGroups().

### PR DESCRIPTION
**Pull request by DanielCoulbourne**
I've always wanted to do more with Route groups, but because they have been primarily used as stacks of attributes which were immediately flattened and didn't persist outside of their registration, there wasn't much to do.

This PR introduces a `RouteGroup` object and a `$groups` array on `Router` which is a persistent registry of RouteGroups. `RouteGroup` objects are aware of their routes via a RouteCollection.

I also added a `getGroups()` method to `Router`.

While pretty in depth in its changes, this is just an introductory "testing the waters" PR. If this PR is merged there are lots of things that could be built on top of persistent route groups:
 - Routes could know their groups, allowing `$router->getRoutes()->getRoutesByGroup()`
 - Groups could be refactored to contain all of their own attributes and know their parent groups, allowing all of the "group stack" and "attribute flattening" logic to live inside RouteGroup (which seems more natural to me)

_Note that the classname `RouteGroup` was already in use for a class of static methods relating to merging Route Group Attributes. I renamed this class to `RouteGroupAttributes`_

Please let me know what you think of this PR. I think its a step in the right direction. I love Route Groups and would love to do more work with them, but I think they deserve a promotion.

### CODE REVIEW

**Comment by browner12** [comment]
I'm not super familiar with the code here, so I can't speak to that, but the idea sounds really interesting.

**Comment by DanielCoulbourne** [comment]
I think TravisCI may need a little kick 😄

**Comment by tillkruss** [comment]
That will have to go to v5.6 now.

**Comment by DanielCoulbourne** [comment]
Just noting that I don't think this actually needs to go in 5.6
There are no breaking changes and all the 5.5 tests still pass. I think this is minor enough that it can go in 5.5

**Comment by tillkruss** [comment]
I changed the branch to v5.5.

**Comment by DanielCoulbourne** [comment]
Oh yeah thanks! Shoulda remembered that.

**Comment by taylorotwell** [comment]
What will this enable application developers to do?

**Comment by hawkleaf** [comment]
I believe this was tied to this package:
https://github.com/tightenco/ziggy

I'm not sure what exactly it was for, it can be found on the twenty percent time podcast. Would be nice if @DanielCoulbourne could explain though ^^

**Comment by DanielCoulbourne** [comment]
@taylorotwell This pull itself will only enable devs to get the route groups. Probably not the most useful feature on its own. But like I said above this is kind of a "test the waters" PR to see if you're even open to this sort of thing. If you are, there are a few ancillary things I'd like to PR in that I do have a need for:

The biggest one is building `$routeCollection->getRoutesByGroup()` which would be SUPER useful to me in building out configuration options for Ziggy (but also could be useful to anyone who wants to do stuff with group-structured routes). This could even allow me to write a `Route::macro` that would let me do something like `Route::getResources()` which would be awesome if someone (who may or may not be me) was dreaming of building a frontend client for resources.

**Comment by m1guelpf** [comment]
Also, for reference, this PR, its implications, etc was discussed in [Twenty Percent Time](http://twentypercent.fm/router)

**Comment by taylorotwell** [comment]
Could you take a look at the conflicts on this? I plan to pull it down today to play with it.

**Comment by DanielCoulbourne** [comment]
Yep just a sec

**Comment by DanielCoulbourne** [comment]
@taylorotwell fixed. Sorry about that. I was trying to resolve merge conflicts in the branch I used for the 5.4 version and lost my mind for a bit. Derp.

**Comment by m1guelpf** [comment]
@taylorotwell Any updates?

**Comment by DanielCoulbourne** [comment]
@m1guelpf We've been talking back and forth on it a bit. I know Taylor has taken a look at it.

**Comment by GrahamCampbell** [comment]
There definitely are breaking changes. Protected methods have been deleted from non-final classes. Should go to 5.6.

**Comment by taylorotwell** [comment]
Going to hold off for now until I see the end-goal macro implemented using this PR's functionality. Without that I'm scared we don't have hard proof this acutally solves what we're trying to achieve.

**Comment by DanielCoulbourne** [comment]
Challenge accepted 😛 
It's gonna be a week or two though.

**Pull request closed without merging**
