### PR TITLE
[5.4] Add assertJsonStructure method to TestResponse

### PR DESCRIPTION
**Pull request by cretueusebiu**
Adds `TestResponse::assertJsonStructure`.

### CODE REVIEW

**Comment by ahjorth** [comment]
@cretueusebiu Would it be possible to also add a `assertExactJsonStructure()` method, or allow this method to optionally check for an exact structure?

For example:
If you expect `foo, bar` this method fails if it receives `foo, baz` but will NOT fail if it receives `foo, bar, baz`

In some cases it could be nice to see if a structure matches an exact pattern and fail if it receives more than it expects

**Comment by cretueusebiu** [comment]
You can add it with a macro in your `TestCase::setUp` method:

```php
use Illuminate\Support\Arr;
use Illuminate\Foundation\Testing\TestResponse;

....

TestResponse::macro('assertJsonEquals', function ($expected) {
    $actual = json_encode(Arr::sortRecursive((array) $this->json()));

    TestCase::assertEquals(json_encode(Arr::sortRecursive($expected)), $actual);
});
```

**Comment by ahjorth** [comment]
Good idea, but unfortunately it won't work with how I have it set up at the moment.

This assumes I know the values as well, but I want to only test for the actual structure.

So say I have a constant

```
const EXPECTED_STRUCTURE = [
    'foo', 'bar'
]
```

Using  `assertJsonStructure()` works fine like this

```
->assertJsonStructure([
                'data' => self::EXPECTED_STRUCTURE
            ]);
```

But again, it will pass even if the data contains the keys `foo, bar, baz` but fail if the data has `foo, baz`

Your suggestion assumes `$expected` has the values of the array as well, an assumption that isn't made using `assertJsonStructure()` - which only tests for keys not values

**Comment by cretueusebiu** [comment]
Try this then:

```php
TestResponse::macro('assertExactJsonStructure', function ($expected) {
    $actual = json_encode(Arr::sortRecursive(array_keys($this->json())));

    TestCase::assertEquals(json_encode(Arr::sortRecursive($expected)), array_keys($actual));
});
```

**Comment by ahjorth** [comment]
That works fine but not for multidimensional arrays :P
Sorry if this is getting annyoing. It's just that the `assertJsonStructure()` works so well with various use case scenarios, where you would have a `data` array wrapped around for example, and the `*` key for multiple items etc. Having the same flexibility of the `assertJsonStructure()` but checking for exact key match would be very useful, especially for me

**Comment by brunocascio** [comment]
I agree with @ahjorth, It doesn't work properly...

I have this code:

```
$this->json('GET', '/api/endpoint')
            ->assertStatus(200)
            ->assertJsonStructure([ ['id', 'name'] ]);
```

The API response:

```
[
  [
    id: 1,
    name: 'the name',
    slug: 'the-name'
  ]
]
```
So, tests are passed, but the structure does not match. :(

**Comment by behzadsh** [comment]
@ahjorth for multidimensional arrays, you want to pass whole json structure to pass the test?

I mean, if we have a json response like this:
```
{
    "foo": "bar",
    "baz": "foo",
    "foobar": {
        "foobar_foo": "foo",
        "foobar_bar": "bar"
    }
}
```

you want testing it like this?
```php
$this->json('GET', '/path/to/api')
     ->assertExactJsonStructure([ 'foo', 'bar',  'foobar' => [ 'foobar_foo', 'foobar_bar' ]]);
```

**Pull request merged**
