### PR TITLE
[5.5] Added 401 response code to AuthenticationException

### PR DESCRIPTION
**Pull request by eusonlito**
As RFC2616 recomends, authentications errors should return 401 error code:

10.4.2 401 Unauthorized

The request requires user authentication. The response MUST include a WWW-Authenticate header field (section 14.47) containing a challenge applicable to the requested resource. The client MAY repeat the request with a suitable Authorization header field (section 14.8).

Similar to 403 Forbidden, but specifically **for use when authentication is required and has failed** or has not yet been provided.

### CODE REVIEW

**Comment by laurencei** [comment]
At the minimum this would need to go to 5.5 - as it could break an existing app/api built to expect a different response code

**Comment by laurencei** [comment]
@eusonlito - the title says `5.5` - but the PR is into `5.4`. Probably need to close this PR and re-submit to master?

**Comment by decadence** [comment]
You can retarget PR without creating new one.

**Comment by eusonlito** [comment]
A lot of merge conflicts. Closing and sending again. Thanks.

**Pull request closed without merging**
