### PR TITLE
[5.6] Allow dependency injection on exception->report call

### PR DESCRIPTION
**Pull request by netpok**
Currently using the report method on an exception the implementer has no choice but using Facades or the app()->make service locator. This change makes possible to use dependency injection too.

If the idea is supported I can make the necessary modifications for the render method too.

### CODE REVIEW

**Comment by jmarcher** [comment]
This change could use some tests.

**Comment by GrahamCampbell** [comment]
I'm :-1: here. Just adding more things to go wrong. Using the container to do this can also crash at runtime too.

**Comment by netpok** [comment]
Looking at the code of the container call method as long as BoundMethod works correctly (which is covered by tests) and the method doesn't have defined dependencies it can't fail. If it has defined dependencies and it would fail then it would fail with the service locator or facade too.

If it needs test I can write some.

**Comment by sisve** [comment]
But what if an exception occurs, for any reason, while resolving? What will be the behavior then?

**Comment by netpok** [comment]
I see three solution:
 1) Falling back to the default handler (reporting via the Logger)
 2) Reporting the second error like it would happen in an app->make
 3) Reporting both

I would say the third option is preferable since it does not hide either exception

**Pull request closed without merging**
