### PR TITLE
[5.2] HasManyThrough over a polymorphic relation

### PR DESCRIPTION
**Pull request by churiart**
`HasManyThrough` couldn't fetch right rows over a polymorphic relation. This PR will handle this issue correctly. 

Table 1: `Users`

```
id
name
```

Table 2: `Invoices`

```
id
user_id
invoiceable_id
invoiceable_type
```

Table 3: `Commissions`

```
id
invoice_id
amount
```

Models:

`Invoice`'s Model:

```
<?php
.
.
.
class Invoice extends Model
{
    public function invoiceable()
    {
        return $this->morphTo();
    }

    public function commission()
    {
        return $this->hasOne('\App\Commission');
    }
}
```

`Commission`'s Model:

```
<?php
.
.
.
class Commission extends Model
{
    public function invoice()
    {
        return $this->morphOne('\App\Invoice');
    }
}
```

`User`'s Model:

```
<?php
.
.
.
class User extends Model
{
    public function invoices()
    {
        return $this->hasMany('\App\Invoice');
    }

    public function commissions()
    {
        return $this->hasManyThrough('\App\Commission', '\App\Invoice', 'invoiceable_id', 'invoice_id', null, 'invoiceable_type');
    }
}
```

### CODE REVIEW

**Comment by churiart** [comment]
`HasManyThrough` couldn't fetch right rows over a polymorphic relation. This PR will handle this issue correctly.

**Comment by taylorotwell** [comment]
Can you not just do: 

```
    public function commissions()
    {
        return $this->hasManyThrough('\App\Commission', '\App\Invoice', 'invoiceable_id', 'invoice_id')->where('invoicable_type', 'Foo');
    }
```

**Comment by bryannielsen** [comment]
I ran into this issue the other day and took the route @taylorotwell mentioned above, so far so good :+1:

**Comment by donnigunawan** [comment]
hi, what will be the inverse of this hasManyThrough polymorpic? Thank you

**Comment by leobeal-git** [comment]
I was trying to solve this issue without having the **invoice_id** field in **Commissions** table, but seeing this make me think it's impossible, right?

**Comment by MikeMnD** [comment]
@leobeal-git 
I'm trying the same since my raw query is:

```
SELECT
	*
FROM
	`commissions`
LEFT JOIN `invoices` ON `invoices`.`invoiceable_id` = `commissions`.`id`
WHERE
invoices.user_id = 1
 AND
invoices.invoiceable_type= 'App\\Commision'
```
But it seems that hasManyThrough can't produce this kind a query and it requires that in the commision table there is column with the invoice_id... which kind brakes the purpose of invoice being polymorphic.

**Pull request closed without merging**
