### PR TITLE
[5.4] Correct variable name

### PR DESCRIPTION
**Pull request by jonbaldie**
'Amount' is for continuous quantities, not discrete quantities. 'Number' is the correct variable name in the cases I've changed.

E.g. "I had a small amount of ketchup" - correct
"I adopted a large amount of dogs" - wrong, should be 'number' of dogs.

### CODE REVIEW

**Comment by vlakoff** [comment]
Agree, let's not propagate English mistakes.

By the way, would conflict with #20439.

**Comment by taylorotwell** [comment]
Has conflicts.

**Comment by jonbaldie** [comment]
Conflicts resolved.

**Comment by vlakoff** [comment]
You should also correct `Arr::random()`.

**Pull request merged**
