### PR TITLE
[5.8] Adding toResponseArray to Resources

### PR DESCRIPTION
**Pull request by dbpolito**
In my use case i want to use Pagination with Resources but i want an Array instead of a JsonResponse, because i want to inject the data as props in a Vue Compoenent.

Currently there is no way of fetching the Pagination Data, only as `JsonResponse`.

My change doesn't change anything, it only introduces a new method for getting array instead of `JsonResponse`.

### CODE REVIEW

**Comment by devcircus** [comment]
Curious how you are trying to use this that doesn't work as-is?

**Comment by dbpolito** [comment]
If you want to use something like:

```php
return view('something', ['data' => Resource::collection(Model::paginate())])
```

And you want to inject this to a Vue Component as prop, you can't transform it on the same format as you get when you return that directly from your controller, what i want is to the same return i would have, something like:

```
        [
            'data' => [
                [
                    'id' => 5,
                    'title' => 'Test Title',
                    'custom' => true,
                ],
            ],
            'links' => [
                'first' => '/?page=1',
                'last' => '/?page=1',
                'prev' => null,
                'next' => null,
            ],
            'meta' => [
                'current_page' => 1,
                'from' => 1,
                'last_page' => 1,
                'path' => '/',
                'per_page' => 15,
                'to' => 1,
                'total' => 10,
            ],
        ]
```

So i could work the same for when it comes from `prop` or from `ajax`.

**Comment by mathieutu** [comment]
Please could you test it with nested resources?

Because I think you will not have a plain recursive array with your implementation, only the first level and then nested objects or resources.

On my side, for testing purposes, I've implemented it with a simple 
```php
public function parse(): ?array
{
    if (!$this->resource) {
        return null;
    }

    return jsonDecode(jsonEncode($this));
}
```

But I'm sure we can do better than that.

**Comment by dbpolito** [comment]
Well i'm using the very same implementation as the one that generates the response, so i can't see a reason to not work, but i'll do some more testing later today.

**Comment by mathieutu** [comment]
@dbpolito the main difference is that the recursivity is handled directly by json_encode, jsonSerializing automatically all the nested objects. 

@taylorotwell I think you merged something that doesn't work... 😕

**Comment by dbpolito** [comment]
@mathieutu Well, won't it work because it will be casted as array? json_encode basically calls `toArray`, the logic should be the same.

Can you give me an resource example with nested resource so i can test?

**Comment by mathieutu** [comment]
I think you didn't understand my point.
It's about recursivity. json_encode is natively made to handle recursivity to construct proper json until the last nested object, calling jsonSerialize on all of them. 

JsonResources use that principle, and it's standard to have nested objects in them because of relations.

I let you try with this updated test: https://gist.github.com/62f8859cc8396a38d3da669ab23547f4

So @taylorotwell I can confirm that **this PR isn't working**. For now only a `json_decode(json_encode(..))` can do the job.

**Comment by dbpolito** [comment]
Now i see, i'm experimenting a possible fix.

**Comment by driesvints** [comment]
I've reverted this PR. Please try to resubmit once all concerns stated here and in the other PR are taken care of.

**Pull request merged**
