### PR TITLE
Update Application.php with DIRECTORY_SEPARATOR constants

### PR DESCRIPTION
**Pull request by ghost**
Fix application paths to use DIRECTORY_SEPARATOR for Windows support.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Whaaaat? This is totally not required!

**Comment by portonefive** [comment]
If you would like to support Windows it is necessary. Please see the discussion at #7632

**Comment by GrahamCampbell** [comment]
I have read, I just don't really like this solution. No point in wasting any more time on it.

**Comment by tekkenking** [comment]
I just experience this error today after updating on laravel 5.1..

To solve the error you'll have to go to Illuminate\Foundation\Bootstrap\LoadConfiguration

Go to line 72 i think.

And change

$files[$nesting.basename($file->getRealPath(), '.php')] = $file->getRealPath();

To

$files[basename($file->getRealPath(), '.php')] = $file->getRealPath();

Works for me..

**Pull request merged**
