### PR TITLE
[5.1] Fire saved event when updating touched relation's timestamp

### LINKED ISSUE #11198: [5.1] No fireModelEvent for models touched by touches
Not sure if this is a bug or by design?

Any model for which you have registered an observable event (like saved), that event won't get called when it's triggered by a child that touches the parent model.

So if you have code that runs when the 'saved' event is observed on model A, that code won't get triggered if a model which touches model A is saved.

But model A is being saved, its timestamp changes and that change is saved.

### PR DESCRIPTION
**Pull request by mattmcdev**
Fixes #11198 

The proposed would fire the saved event when the a model's timestamp is updated due to it being touched by another model.

It may also be desirable to call other events like saving, updating, etc.?

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm curious why we would fire a saved event on the related model when it's touching the other relations? It looks like touchOwners just loops through all relations and touches them.

**Comment by mattmcdonald-uk** [comment]
Touching owners lets you know that something has changed with the parent model. And a saved (or updated) event is something you observe because you're watching for changes. So would you not also want to fire the event when you've been touched. Perhaps it needs  a new observer instead? Like a touched event? But that doesn't seem quite as clean - would need to listen for touched and saved and not just saved. 

The specific use case here is an aggressively cached e-commerce site. All product models are cached forever, and that cache is only updated when the model is saved. But there are lots of child models on a product - e.g. images, stock, reviews, etc. So when a child model changes we want to update the cache for its parent product. Currently that requires watching all of the models, but with the proposed (or similar) you could just have a single listener.

**Comment by tomschlick** [comment]
Any thoughts on created a "touched" event instead of using "saved"? That would allow you to differentiate between models modified directly vs models modified by the touchOwners...

**Comment by mattmcdonald-uk** [comment]
@tomschlick Yes - except this does still require watching two events not one.

**Comment by boynet** [comment]
+1 for this, my use case is:
I have article view that get cache by nginx, and I need to purge the cache for each change. there is like 5-10 different class that can make the view change(comments,images,edit text,view refactor), so it will be nice if I could touch the parent on change and listen for that

**Comment by tomlankhorst** [comment]
Note that touching triggers a `saved` event but no, `updated`, `saving`, `saved` etc.

**Comment by gedeef** [comment]
@mattmcdonald-uk Maybe there was a better way to do it, I added the _touched_ event, that lets me decide how I want to propagate the touch to children.
https://github.com/gedeef/LaravelTouchedEvent

**Pull request merged**
