### PR TITLE
[5.2] Set connection timeout for mail transports

### PR DESCRIPTION
**Pull request by hoomanna**
Hi,
By sending this PR I want to set connection timeout for drivers that use GuzzleHttp to send request
GuzzleHttp Use 0 to wait indefinitely (the default behavior) for connection timeout and that's really bad for background jobs like queue
it could cause infinite loops.

Regards,

### CODE REVIEW

**Comment by it-can** [comment]
maybe make it a config option?

**Comment by it-can** [comment]
Maybe make it a config option?

**Comment by RTLer** [comment]
i see it now, in TransportManager they made pussible set guzzle config for driver's that work with guzzle, 
```php
'sparkpost' => [
    'secret' => 'c0100484e20bfa12e20632b1d9b4761a51c482c2',
    'guzzle' => [
        'connect_timeout' =>60,
    ],
]
```
i added the getHttpClient to create http client 
and set config's and set default config for connect_timeout
in TransportManager
1be806a

**Comment by taylorotwell** [comment]
Thanks!

**Pull request merged**
