### PR TITLE
[5.5] Revert #22649

### PR DESCRIPTION
**Pull request by timoschwarzer**
That commit caused unit tests using the actingAs helper to fail

### CODE REVIEW

**Comment by sisve** [comment]
It would be nice to have a tests for actingAs so it doesn't fail again.

**Comment by crynobone** [comment]
I would actually opt for fixing `actingAs()` instead of doing this.

**Comment by taylorotwell** [comment]
How exactly did it cause it to fail. We need more information?

**Comment by timoschwarzer** [comment]
@taylorotwell the `actingAs`  helper called `setRequest`  which has set the user to `null`  again.

**Comment by vlakoff** [comment]
Refs #22817 that subsequently added tests for this.

**Comment by crynobone** [comment]
Should note the added tests doesn't break with and without the "broken" changes. I don't have enough information to replicate the issues.

In the other thread it does mention that request is being rebind before `call()` is being made but auth service provider already cover these scenarios.

If anyone want to properly prevent such issues, need to further improve the test. Otherwise same thing can happen again, since tests is green.

**Pull request merged**
