### PR TITLE
[5.5][wip] add type declarations of php 7.0 on functions

### PR DESCRIPTION
**Pull request by ghost**
That pr is for add types declarations of variables on each functions allowed with php 7.0

### CODE REVIEW

**Comment by decadence** [comment]
Core team doesn't like this :)

**Comment by NGT-11** [comment]
PHP errors are more understandable with types

**Comment by m1guelpf** [comment]
Nominating @JeffreyWay for review :laughing:

**Comment by JeffreyWay** [comment]
👀

**Comment by tillkruss** [comment]
🍿 😃

**Comment by deleugpn** [comment]
@NGT-11 please don't take it personal. People laughing at this thread is not a reflex on your contribution to the project, it's just a reflex of a subject that was widely discussed and has been the reason for a lot of name-calling on Reddit.

Sometimes it may be the case where type-hitting may help, but for now the Laravel community is not taking that as a golden rule. If it works as is and it's not necessary, why change it?

**Pull request closed without merging**
