### PR TITLE
Array access for higher-order collection operations

### PR DESCRIPTION
**Pull request by franzliedke**
I advise to implement real array access for collection items that are arrays, as replacement for the magical #16274.

This PR implements that. :)

### CODE REVIEW

**Comment by JosephSilber** [comment]
This feels like a terrible hack.

I'd rather we use `data_get` in `__call`.

It'll be much nicer syntax too.

**Comment by taylorotwell** [comment]
Yeah, I prefer the current implementation.

**Comment by franzliedke** [comment]
@JosephSilber To be honest, I'm somewhat irritated about that feedback. How is this in any way "dirty" - if anything, the whole feature is dirty. This just follows the implementation of the method and object access proxy feature, and does what we have to do to enable array access - that's a normal PHP feature.

As I've explained in #16274, this is about expectability. If you have objects in your collection, you can access their properties like object properties, and object methods like object methods through the proxy (as if you're dealing with one object, even though it is a whole collection); if you have a collection of arrays, what would be more straightforward then accessing them like you would access a normal array?

**Comment by JosephSilber** [comment]
> this is about expectability

Honestly, there's zero "expectability" here. This is a beautifully magical feature, and you learn to use it the way it was designed.

> if you have a collection of arrays, what would be more straightforward than accessing them like you would access a normal array

We've actually had *many* requests from people to add `__get` accessors onto the collection, for when the collection contains a single-dimensional associative array (luckily we never did, or we wouldn't have been able to get your delicious higher order operations). Just goes to show people really hate array syntax, and much prefer object syntax (just like the `Fluent` class).

**Comment by franzliedke** [comment]
Doesn't matter whether you call it expectability or consistency. There is a lot of magic going on here, true - that makes it even more important to be consistent with the rest of the language in as many ways as we can - in this case in the way we access the collection items.

Anyway, how do we access array elements with names that aren't allowed as property names now?

~~~php
$collection->map->field-name; // doesn't work
$collection->map['field_name']; // would work
~~~

**Comment by JosephSilber** [comment]
> Anyway, how do we access array elements with names that aren't allowed as property names now?

For those rare cases, you can use curly braces:

```php
$collection->map->{'field-name'};
```

**Pull request closed without merging**
