### PR TITLE
[10.x] Add WithoutRelations attribute for model serialization

### PR DESCRIPTION
**Pull request by Neol3108**
Hey all,

I normally serialize my models without their relations, I've had some issues with circular dependencies and often don't even need them after unserialization. I usually do this by calling `withoutRelations` on the model(s) in my constructor like this:
```php
<?php

use App\Models\User;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\SerializesModels;

class Queued implements ShouldQueue
{
    use SerializesModels;

    public User $user;

    public function __construct(User $user)
    {
        $this->user = $user->withoutRelations();
    }
}
```

There is however no way to do this with property-promotion. And apart from that I like to keep my job (etc.) constructors as slim as possible.

The following is possible with this PR:
```php
<?php

use App\Models\User;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\Attributes\WithoutRelations;
use Illuminate\Queue\SerializesModels;

class Queued implements ShouldQueue
{
    use SerializesModels;

    public function __construct(
        #[WithoutRelations]
        public User $user,
    ) {
        //
    }
}
```
I don't know if my approach is the best but it's the first that came to mind.

I'm curious to know what you think.

### CODE REVIEW

**Comment by cosmastech** [comment]
https://github.com/laravel/framework/pull/47097 I made this exact same feature a few months ago and it was closed. Would love to see something like this get to merged, as it's very useful.

**Comment by driesvints** [comment]
Please mark this as ready for review if you want one. Draft PRs aren't looked at. Thanks!

**Comment by timacdonald** [comment]
Love this.

**Comment by siarheipashkevich** [comment]
Hi @Neol3108 is it possible to use this attribute for `events` ?

**Comment by Neol3108** [comment]
@siarheipashkevich yea sure, anything that uses the SerializesModels trait.

**Comment by siarheipashkevich** [comment]
@Neol3108 what do you think about adding this to the documentation?

**Comment by Neol3108** [comment]
@siarheipashkevich I mean, it's fine by me. Feel free to PR, Taylor will have to judge I guess.

**Pull request merged**
