### PR TITLE
[5.7] Standardize the console commands help output

### PR DESCRIPTION
**Pull request by scrubmx**
Remove the period at the end of the options and arguments of console
commands that have it. Now all commands use the same format.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I'd actually rather standardize the other way, with the periods included.

**Comment by scrubmx** [comment]
@GrahamCampbell I can make that happen. I choose to remove them because the console command already outputs some information without periods. For example `--verison` or `--env`.

screen shot 2018-06-03 at 3 12 20 pm

**Comment by GrahamCampbell** [comment]
By comparison, what does the Symfony framework do with periods?

**Comment by taylorotwell** [comment]
@GrahamCampbell Symfony does not use periods on options.

**Comment by GrahamCampbell** [comment]
Perfect.

**Pull request merged**
