### PR TITLE
[5.8] Fix `chunkById` when used after `orWhere`

### LINKED ISSUE #29655: chunkById misbuilds query between where/orWhere
- Laravel Version: 5.8.32
- PHP Version: 7.3.8
- Database Driver & Version: MariaDB 10.2.23

### Description / Repro Steps:
1. Build a query that leverages where/orWhere
```
        User::query()
            ->where(function (Builder $query) {
                // basic where
            })
            ->orWhere(function (Builder $query) {
                // basic where
            })
            ->chunkById(50, function (Collection $users) {
                // logic
            });
```

This generates
```
SELECT * FROM … WHERE a OR b AND id > X
```

Which when grouped becomes
```
SELECT * FROM … WHERE a OR (b AND id > X)
```

While I think it should be
```
SELECT * FROM … WHERE (a OR b) AND id > X
```

This led to a situation where our queue system ran out of bounds and just queued millions of millions of jobs until redis died out.

### Workaround
```
        User::query()
            ->where(function (Builder $query) {
                $query->where(function (Builder $query) {
                    // basic where
                })
                ->orWhere(function (Builder $query) {
                    // basic where
                });
            })
            ->chunkById(50, function (Collection $users) {
                    // logic
            });
```

We basically just shove the logic into a where closure to force the grouping. I think this is a bug or at least unexpected behavior.

### PR DESCRIPTION
**Pull request by rgehan**
This PR fixes #29655

When using `chunkById` after `orWhere`, the condition is invalid, as it generates something like `WHERE a OR b AND id > N`, while it should be `WHERE (a OR b) AND id > N`.

---

This fix feels a tad inelegant, as I don't have much experience with how the query builder work internally.

I've tried using `cloneWithout(['wheres'])` to generate a new query without the original where clause, but it didn't work, and I haven't been able to find out why.

@staudenmeir you might have some ideas about how we could make that more elegant

### CODE REVIEW

**Comment by morloderex** [comment]
I belive this is not a problem by the query builder. But rather something along the lines of a documentation issue. As i believe using a `Closure` within the `where` method on the query builder as the first argument and then nesting the calls to `orWhere` from the `Closure` should produce the desired result.

Look at this example for inspiration:

```php
$query->where(function($query) {
    return $query->where('a', 'something')->orWhere('b', 'something')
})->where('id', '>', 5)
->chunkById(25, function ($items) {
    /// do something with items
})
```

**Comment by staudenmeir** [comment]
@morloderex I think the user shouldn't have to think about the constraints a method `chunkById()` adds to the query. Laravel already "fixes" queries with `orWhere()` when applying scopes.

**Comment by staudenmeir** [comment]
@rgehan I would leave it like this for now. 

Eloquent uses a slightly different approach when applying scopes and we could share the code, but that would require breaking changes. I'll keep it in mind.

**Comment by rgehan** [comment]
@staudenmeir Can you point me to the logic that fixes ˋorWhereˋ when used with scopes?

I'm curious about how it's done

**Comment by rgehan** [comment]
@taylorotwell While I agree this might be confusing for ˋforPageAfterId`, it also fixes the behavior of `chunkById`, which you wouldn't expect to be used between where/orWhere, but rather on its own, at the end of an expression.

Don't you think this might be worth fixing?

**Comment by staudenmeir** [comment]
@rgehan I was referring to `Eloquent\Builder::groupWhereSliceForScope()` and `createNestedWhere()`.

**Comment by halaei** [comment]
> Don't` you think this might be worth fixing?

@rgehan I think it worth fixing that way. Just my opinion.

**Pull request closed without merging**
