### PR TITLE
Add table comment support for creating table.

### PR DESCRIPTION
**Pull request by peixinchen**
We can use it as below:
```php

Schema::create('your table', function (Blueprint $table) {

    $table->comment = 'Some blabla';

});

```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What about all the other grammars?

**Comment by fernandobandeira** [comment]
We could make it work for Postgres too, but the syntax is kinda weird, currently we don't support any comments for Postgres, example of the syntax:

Table comment:
```sql
comment on table session_log is 'Our session logs';
```

Column comment:
```sql
comment on column session_log.userid is 'The user ID';
```

So it doesn't work as mysql where you just add a modifier, you have to run a separate query for this AFAIK...

**Comment by taylorotwell** [comment]
No plans to implement table comments at this time.

**Comment by StephaneBour** [comment]
:'(

**Comment by uonick** [comment]
Just use a [package](https://github.com/diplodocker/comments-loader) 😄

**Pull request closed without merging**
