### PR TITLE
[5.4] Revert change to inflector

### PR DESCRIPTION
**Pull request by GrahamCampbell**
It doesn't make sense to block people from installing the latest version.

### CODE REVIEW

**Comment by taylorotwell** [comment]
@themsaid won't this just put us right back in the position we were in?

**Comment by GrahamCampbell** [comment]
> @themsaid won't this just put us right back in the position we were in?

I don't see any bug?

**Comment by GrahamCampbell** [comment]
is the bug that the laravel installer pulls in incompatible deps. This can be fixed by setting a target php version in laravel/laravel.

**Comment by taylorotwell** [comment]
@themsaid ?

**Comment by themsaid** [comment]
@taylorotwell sorry just noticed, yes the issue was related to laravel installer, now that we lock PHP there to 5.6 I think reverting that change is ok.

**Comment by GrahamCampbell** [comment]
:+1: Similarly, Laravel 5.5 will need locking to 7.0.0. :)

**Comment by GrahamCampbell** [comment]
🚀

**Comment by ropmansk** [comment]
This issue is reoccurring after the fix revert, so again it is not possible to install laravel 5.4 on PHP < 7

>  Your requirements could not be resolved to an installable set of packages.
>   Problem 1
>     - Installation request for doctrine/inflector v1.2.0 -> satisfiable by doctrine/inflector[v1.2.0].
>     - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.12) does not satisfy that requirement.
>   Problem 2
>     - Installation request for phpunit/php-token-stream 2.0.1 -> satisfiable by phpunit/php-token-stream[2.0.1].
>     - phpunit/php-token-stream 2.0.1 requires php ^7.0 -> your PHP version (5.6.12) does not satisfy that requirement.
>   Problem 3
>     - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.12) does not satisfy that requirement.
>     - laravel/framework v5.4.33 requires doctrine/inflector ~1.1 -> satisfiable by doctrine/inflector[v1.2.0].
>     - Installation request for laravel/framework v5.4.33 -> satisfiable by laravel/framework[v5.4.33].

**Pull request merged**
