### PR TITLE
Add "db" helper

### PR DESCRIPTION
**Pull request by manan-jadhav**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Bad idea.

**Comment by CurosMJ** [comment]
I dont like putting `use DB;` everytime I want to use QueryBuilder. And code looks bad if I use `\DB::whatever ()`.

**Comment by GrahamCampbell** [comment]
You should be writing `use Illuminate\Support\Facades\DB`, then writing `DB::whatever()`.

**Comment by RomainLanz** [comment]
@CurosMJ You can still add this helper to your application.

**Comment by barryvdh** [comment]
Why is this a bad idea and all other similar helpers aren't?

**Comment by pilot911** [comment]
Good idea!

**Pull request closed without merging**
