### PR TITLE
[5.1] Set .php extension for compiled view files

### PR DESCRIPTION
**Pull request by amenk**
Having the proper extensions (it's PHP code in there), makes developer's live easier
- Code highlighting in the IDE
- Debugging functionality 
  (at least in PHPStorm)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please send this to 5.2, the master branch. :)

**Comment by amenk** [comment]
okay #10461

**Comment by GrahamCampbell** [comment]
Thanks.

**Comment by vlakoff** [comment]
Why not 5.1?

**Comment by GrahamCampbell** [comment]
Because it's a breaking change.

**Comment by amenk** [comment]
Hm, what does it break? The tests?

**Comment by GrahamCampbell** [comment]
No.

**Comment by GrahamCampbell** [comment]
Well, yes, but that's not why.

**Comment by amenk** [comment]
But what is it? No problem about 5.2 though... But would be cool to understand it...

**Comment by vlakoff** [comment]
Off the top of my head, it would result in stale cache files from the previous naming method. But apart from this?

**Comment by GrahamCampbell** [comment]
People messing with blade at a low level is quite common, and i don't think we should make uneeded changes to 5.1 that could mess with them. This has been merged to 5.2 anyway.

**Pull request closed without merging**
