### PR TITLE
Fix pagination when a "having" clause is added to the query

### PR DESCRIPTION
**Pull request by anlutro**
When using a "having" clause on a query builder, paginating is impossible because the column you're trying to check against won't be part of the select clause. This is crudely fixed by checking if the query has a having clause and then adding the necessary columns as selects.

This honestly feels like somewhat of a hack to me, but all tests pass. The array_diff is there to prevent `select *, count(*)` but there may be a better way.

Related: #3105, #3416, #4532

### CODE REVIEW

**Comment by tsesci** [comment]
@sangar82  hey did you solve this problem without creates the paginator manually?

**Comment by ajcastro** [comment]
Hey guys, you might be interested with my work-arounds. I just created a datagrid-paginator which supports search all columns filter based from result set columns. Therefore it is using HAVING clauses.  
It is one seearch value and searches all matching columns containing the search value. 
https://github.com/ajcastro/laravel-datagrid-paginator

**Comment by sangar82** [comment]
sorry @tsesci I create the paginator manually as the stackoverflow example

**Comment by straube** [comment]
No workaround is needed. Please take a look at this answer: http://stackoverflow.com/a/20949852/1128918

**Comment by pjsinco** [comment]
I'm still having this problem in 5.1. 

This solution worked for me:
https://laracasts.com/discuss/channels/general-discussion/any-idea-how-to-solve-pagination-issue-with-having-clause?page=0/#reply-55686

**Comment by Sladewill** [comment]
```php
$query->select('*', DB::RAW('(
	6373 *
		acos(
			cos(radians(' . $latitude . ')) *
			cos(radians(`latitude`)) *
			cos(
				radians(`longitude`) - radians(' . $longitude . ')
			) +
			sin(radians(' . $latitude . ')) *
			sin(radians(`latitude`))
		)
	) distance'))
->having('distance', '<', 101)
->orderBy('distance')
->paginate($perpage);
```

What we are using and don't have any issues.

**Comment by cerw** [comment]
@Sladewill  I have tried your query in Laravel 5.2 and it's not working with error: 

```
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'distance' in 'having clause' (SQL: select count(*) as aggregate from `beaches` where `beaches`.`deleted_at` is null having `distance` < 101)"
```

Did you change it to work with new L5.2?
Ta

**Comment by solofeed** [comment]
@Sladewill why is 6373? Radius of the earth in miles is 3959

**Comment by Sladewill** [comment]
It is in km not miles "6373" looks wrong as well this is really old code "6371" it should be.

**Pull request closed without merging**
