### PR TITLE
[5.1] Make log level configurable through the app config

### PR DESCRIPTION
**Pull request by kielabokkie**
This will make it possible to set the `log_level` in the app.php file. I'll create a PR for the docs and an update for the `.env.example` file if this PR approved.

### CODE REVIEW

**Comment by anteriovieira** [comment]
This allows me to do ```log_level = debug``` correct? But what if I need register more than one level?

**Comment by kielabokkie** [comment]
@anteriovieira It will log everything from the log level you set up to the highest level. So if you set your log level to `debug` your logs will include everything from `debug` to `emergency`. Does that answer your question?

**Comment by anteriovieira** [comment]
Yes, thank @kielabokkie . I think not need to change the configuration file ```.env.example``` just document I believe to be enough.

**Comment by taylorotwell** [comment]
Check out the `$app->configureMonologUsing` method. It's in the docs.

**Comment by kielabokkie** [comment]
@taylorotwell What is there against allowing the user to set the log level through the `app.php` config file using existing functionality in the `ConfigureLogging` class? The `useFiles` and `useDailyFiles` functions already accept a parameter for setting the level but it wasn't utilized.

Won't it be easier if the framework natively support this instead of the user having to mess around with the `bootstrap/app.php` file for each project?

**Pull request closed without merging**
