### PR TITLE
[5.0] Use dependency injected boot method

### PR DESCRIPTION
**Pull request by hannesvdvreken**

### CODE REVIEW

**Comment by franzliedke** [comment]
Why? I think this might be cool in the application's service providers, but it's not really necessary here, is it? The explicit way has exactly the same result, but is more performant.

**Comment by hannesvdvreken** [comment]
It was already used [here](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Support/Providers/EventServiceProvider.php#L36) and [here](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php#L36).

Performance is not an issue, it's an alias and it's only executed once. The gain is in the readability.

**Comment by crynobone** [comment]
Both of them are support providers, which normally extends from app.

**Comment by franzliedke** [comment]
I'd argue performance is an issue. If we can get around it, reflection should be avoided in my opinion.

**Comment by hannesvdvreken** [comment]
Are there blog posts around on the impact of reflection on performance in laravel? Backed with data measured with blackfire or something?

**Comment by Anahkiasen** [comment]
I always thought the whole "Reflection is bad for perfs" was kind of an old myth from 5.3 that just refused to die, would be interested to see if it's actually still true.

**Pull request closed without merging**
