### PR TITLE
[5.1] Fixes bug on negative number sort

### PR DESCRIPTION
**Pull request by antonybudianto**
According to this [issue](https://github.com/laravel/framework/pull/9923)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please squash to one commit.

**Comment by GrahamCampbell** [comment]
Please also include the test case.

**Comment by antonybudianto** [comment]
Ok, I will, but the test case is already on this [PR](https://github.com/laravel/framework/pull/9923) ?

**Comment by GrahamCampbell** [comment]
You need to cherry-pick that commit into this PR please.

**Comment by antonybudianto** [comment]
oh i see, wait a moment

**Comment by antonybudianto** [comment]
do I need to squash all or leave the add test commit alone?

**Comment by GrahamCampbell** [comment]
Please retain the original author on the commit.

**Comment by antonybudianto** [comment]
Sorry, but how to do that?

**Comment by GrahamCampbell** [comment]
`git cherry-pick`

**Comment by GrahamCampbell** [comment]
Instead of just copying the code.

**Comment by GrahamCampbell** [comment]
Alternative, you can just copy/paste it if you ask the original author for permission.

**Comment by antonybudianto** [comment]
I already asked the permission from the author on the facebook group :smiley:

**Comment by GrahamCampbell** [comment]
Great. :)

**Comment by antonybudianto** [comment]
Then should these commits squashed to one?

**Pull request merged**
