### PR TITLE
[5.6] Implements `belongs` method to Schema Blueprint

### PR DESCRIPTION
**Pull request by iget-esoares**
I've made this PR to solve the problem of https://github.com/laravel/ideas/issues/815 by creating a shorthand that creates both the column and the foreign index.

It allows the following usages:

```
$table->belongs('users');
> Creates a `user_id` column, and a foreign key referencing it to the `users.id`

$table->belongs('users', 'buyer_user_id');
> Creates a `buyer_user_id` column, and a foreign key referencing it to the `users.id`

$table->belongs('users', null, 'uuid');
> Creates a `user_uuid` column, and a foreign key referencing it to the `users.uuid`

$table->belongs('users', null, 'id', 'custom_index_name');
> Creates a `user_id` column, and a foreign key (named `custom_index_name`) referencing it to the `users.id`
```

This feature doesn't implement anything new, just a shorthand to **Laravel keep being awesome**.
It **doesn't* introduce any breaking changes.

**Note:** This is an update for #23840 including the related tests as requested by @sisve

### CODE REVIEW

**Comment by iget-esoares** [comment]
If this PR is merged, I'll do a PR on laravel/docs to complement it.

**Comment by francislavoie** [comment]
This unfortunately only lets you use unsigned int columns, but I use `blob` keys (binary UUIDs). If it was possible to specify the column type, that'd be great!

**Comment by iget-esoares** [comment]
@francislavoie that's true. I've created only to `uint` because is the most common use case. The `morphs` method also accept only `uint`. But I agree that allowing `blob` keys is a great feature.

**Comment by devcircus** [comment]
In migrations, I like to be explicit. Methods like these can make things not so clear.

IMO we should stick with the explicit calls.

**Comment by iget-master** [comment]
@devcircus That's just a shortcut, you can still keep using the explicit calls.

This weekend I've participated of an Uber Hackaton, and had to write and complete API in a few hours. Every second lost counts. And I've noticed how many times I did a foreign key manually.

When we spread the develop along time, there's no difference. But when we really need to be time efficient developing, every second matters.

**Comment by devcircus** [comment]
I understand it's a shortcut. I just don't believe the framework should encourage these "shortcuts" in migrations. You're entire foreign key creation is hidden. 

 just my opinion

**Comment by arjasco** [comment]
To be honest, `->belongs` is rather implicit. Yeah, most developers will get the gist and understand what is going on, but the readability is a no from me. 

This isn't a personal attack, I appreciate every contribution everyone has but I think there is too much obsession with the whole "making developers lives easier". 2/3 chained method calls opposed to 1 saves what.. 2-3 seconds? build a macro if it's that bad, create a snippet in your IDE.. Laravel is a tool, a solid basis to build upon, not a shortcut to every single issue someone might have.

**Comment by iget-master** [comment]
Your arguments makes sense. Actually I already have a IDE snippet to create it, but I thought that was great to offer this as a framework feature, since the `morphs` itself already exists.

**Comment by devcircus** [comment]
Honestly, it may get pulled in. If so, I'm sure I'll eventually end up using it in personal projects. 

```->morphs``` makes me sad too.

**Comment by roodz** [comment]
What about onDelete('cascade|restricted')?

**Comment by taylorotwell** [comment]
No plans to add this. Thanks.

**Pull request closed without merging**
