### PR TITLE
[5.3] Remove broken timestamps option

### PR DESCRIPTION
**Pull request by acasar**
Following https://github.com/laravel/framework/pull/12572 I think it's best to do it in 5.3 then. 

@taylorotwell @vlakoff

### CODE REVIEW

**Comment by vlakoff** [comment]
The feature doesn't work so I think it's not a problem to remove it in 5.2.

And if someone was extending `performUpdate` or `performInsert` protected methods, as the parameter was optional this shouldn't be breaking under normal circumstances.

**Comment by GrahamCampbell** [comment]
5.3 is fine imo.

**Comment by acasar** [comment]
@vlakoff We can still remove the feature from 5.1 and 5.2 without modifying method parameters, but I'm not sure if it's worth it.

**Comment by acasar** [comment]
No idea why tests are failing :/ But it seems unrelated to this PR.

**Comment by GrahamCampbell** [comment]
Try rebasing your fork.

**Comment by mark86092** [comment]
The build fail due to the change of symfony class, I send a PR #12623.

**Pull request merged**
