### PR TITLE
[9.x] Add confirmation to model:prune command

### PR DESCRIPTION
**Pull request by ankurk91**
Hi,

Lets add confirmation to model:prune command since it is a destructive command.

Users need to add `--force` flag to command in production.

thanks

### CODE REVIEW

**Comment by JamesFreeman** [comment]
This would be a breaking change and would have to go into 9.x?

**Comment by driesvints** [comment]
@JamesFreeman this is targeting master already.

**Comment by driesvints** [comment]
@ankurk91 please fix the tests here first. Thanks

**Comment by JamesFreeman** [comment]
> @JamesFreeman this is targeting master already.

Doh! My bad.

**Comment by ankurk91** [comment]
looks like that too much work,  i can live without this feature so closing

**Pull request closed without merging**
