### PR TITLE
[6.0] Use table.* instead of * as default for select queries

### PR DESCRIPTION
**Pull request by liamkeily**
When fetching an Eloquent model using a join query, it automatically uses `select *` which ends up using a joined models id as the main id, and causes unexpected issues when saving.

For example, if i used the following query to fetch a user: (I know this query doesn't make much sense, its just an example). 

```
$user = User::query()
    ->join('account', 'account.id', '=', 'user.account_id')
    ->where('account.id', '=', 7)
    ->first();
```

I would now like to change a column on the user model:

```
$user->name = 'Test';
$user->save();
```

Instead of updating the user i expected (e.g. 20), it actually updates user 7 (which is actually the account.id). 

I think this behaviour can easily cause unexpected bugs, and could be prevented with a safer default. 

--

This PR changes `->get()` and `->cursor()` to default to using `select "table".*` unless otherwise specified using the `->select()` method. 

Note: This will cause a breaking change for users that don't specify a select and rely on columns that are automatically returned by `select *`.

### CODE REVIEW

**Comment by taylorotwell** [comment]
No plans to change this behavior so close to release.

**Comment by l0rb** [comment]
There has been a release now, maybe this could be reconsidered?

**Comment by wdelfuego** [comment]
Another upvote for accepting this pull request to fix the issue where Eloquent objects are silently hydrated with wrong data; just ran into this today while implementing a custom Filter in Laravel Nova. Due to the issue fixed by this pull request, adding a simple `join` to the query builder in the Nova Filter's `apply` method directly and silently makes Nova present corrupted data objects to the end user.

**Comment by jordanade** [comment]
Another upvote here. The fact this doesn't even merit a warning in the docs is terrible!

**Comment by vmingam** [comment]
Another upvote. Had the same issue.

**Pull request closed without merging**
