### PR TITLE
[5.5] Compile or in blade with Null Coalesce Operator

### PR DESCRIPTION
**Pull request by carusogabriel**

### CODE REVIEW

**Comment by deleugpn** [comment]
Unless there's a bug, these types of PR rarely gets merged. Specially when they change tests. It's hard to revise and easy to introduce bugs for not much benefit.

**Comment by sisve** [comment]
I see no reason to rewrite existing code that already works just to use a new PHP7.0 feature. Can you describe what bugs this actually fixes?

**Comment by carusogabriel** [comment]
It doesn't fix any bugs, it's just for a shorter solution :disappointed:

**Comment by Dylan-DPC** [comment]
This doesn't fix any bugs but then if a newer version of a language provides us with a way to write the code in a better form then why not use it? 

Also `??` is more readable compared to an `isset(..)? .. : foo` (since some people want code to be more readable than performant :stuck_out_tongue: ).  

I don't see why there should be a concern for a rewrite, this change won't introduce any side-effects (bugs).

**Comment by taylorotwell** [comment]
Seems like it could be slightly different behavior if magic __isset is overridden.

**Pull request closed without merging**
