### PR TITLE
[5.5] Fix bug when use SoftDeletes and no column updated_at `cons UPDATED_AT = null;`

### PR DESCRIPTION
**Pull request by ThunderBirdsX3**
I always had a problem with this, When I have no `updated_at` column and use `SoftDeletes`.

> Type error: Too few arguments to function Illuminate\Database\Eloquent\Model::setAttribute(), 1 passed in /...path_to_directory.../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 525 and exactly 2 expected 

With set this in Model.

```
    use SoftDeletes;

    const UPDATED_AT = null;

    /**
    * Set the value of the "updated at" attribute.
    *
    * @param  mixed  $value
    * @return $this
    */
    public function setUpdatedAt($value)
    {
        return $this;
    }
```

### CODE REVIEW

**Comment by sisve** [comment]
... and where's the test?

**Comment by ThunderBirdsX3** [comment]
@sisve Sorry, How about this. I never wrote test before. Hope it does not look too ugly.

**Comment by taylorotwell** [comment]
Fixed by another PR.

**Comment by ThunderBirdsX3** [comment]
Thanks for "Fixed by another PR.", Not "This is not a bug.". Hahahaha.

**Pull request closed without merging**
