### PR TITLE
[5.2] Add support for using keys in Collection filter

### PR DESCRIPTION
**Pull request by besologic**
This PR adds support for being able to use a collection's keys when using the filter method.

Paired with @mattstauffer.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
> Fix formatting from php-cs-fixer

Don't worry about that (its still not quite right anyway). We have StyleCI setup to fix code style after the PR is merged so contributors don't need to worry about getting that stuff perfect.

**Comment by GrahamCampbell** [comment]
I see you just force pushed another fix. ;)

**Comment by besologic** [comment]
@GrahamCampbell decided to squash them into the original commit :) Thanks!

**Comment by JosephSilber** [comment]
You should add this to `reject` as well.

**Comment by GrahamCampbell** [comment]
> You should add this to reject as well.

Yes, please do.

**Pull request merged**
