### PR TITLE
[5.3] Fix database factory error when zero is provided

### LINKED ISSUE #15755: Eloquent model factory makes 2 models when it should build 0
- Laravel Version: 5.3.15
- PHP Version: 7.0.8-2+deb.sury.org~xenial+1 (cli) ( NTS )
- Database Driver & Version: Irrelevant

### Description:
 Eloquent model factories (the ones for seeding test data and such) that reside in `database/factories/ModelFactory.php`, have a strange behavior.
The `FactoryBuilder::make()` method makes multiple models even when `FactoryBuilder::$amount `
is set to `0`.

### Steps To Reproduce:
```php
vagrant@homestead: php artisan tinker
Psy Shell v0.7.2 (PHP 7.0.8-2+deb.sury.org~xenial+1 — cli) by Justin Hileman
>>> factory(App\User::class, 0)->make();
=> Illuminate\Database\Eloquent\Collection {#704
     all: [
       App\User {#700
         name: "Emie Will",
         email: "nicolas.kathleen@example.org",
       },
       App\User {#687
         name: "Anna Jones",
         email: "eli76@example.org",
       },
     ],
   }
```
As per the above, one would expect the `make()` method to create an empty array or some other indicator that no models were created. Instead an array with  2 models is returned.

### PR DESCRIPTION
**Pull request by srmklive**
Fixes #15755

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by taylorotwell** [comment]
I'm more curious in why when you pass zero before you would get models?

**Comment by themsaid** [comment]
@taylorotwell I think because `range(1, 0)` returns `[1,0]`

    public function make(array $attributes = [])
    {
        if ($this->amount === 1) {
            return $this->makeInstance($attributes);
        }

        return new Collection(array_map(function () use ($attributes) {
            return $this->makeInstance($attributes);
        }, range(1, $this->amount)));
    }

**Comment by srmklive** [comment]
@taylorotwell because passing `0` always create 2 items for a specific model as reported in #15755. If we skip it entirely, one instance of the model is created.

**Comment by taylorotwell** [comment]
Would it better to just return an empty Collection instead of throw an exception?

**Comment by srmklive** [comment]
@taylorotwell yeah i think that will be better.

**Comment by srmklive** [comment]
@taylorotwell Code updated. An empty collection is returned instead of exception.

**Comment by bobbybouwmann** [comment]
I think the real question is why would you use factory with 0? I mean calling a factory method with 0 will never return any models so it's not logic to call it with 0 right?

**Comment by etherealite** [comment]
Wow, holy man you guys are super duper quick on issues! I figured I'd check back in next week to see if any cared about fixing such a minor issue, but you guys got on it within hours.

The story goes I wanted to generate a random number of dependent records for a set of given parent records. The random range was 0 to 15 children per parent record. I noticed that my `$parent->dependants()->save($dependant);` call was being passed an `array()` when the random value was equal to 0 and not the `Eloquent\Model` instance I was expecting.

Don't ask me why I did it this way. I was working on a project as fast as I could go and this is what I ended up producing.

```php
$parents = factory(App\Parent::class, 5)->create();
$parents->each(function ($parent) {
      $random = rand(0, 15);
      if ($random <= 1) {
             $parent->dependants()->save(factory(App\Dependant::class, $random)->make());
    });
```
results in
```
TypeError: Argument 1 passed to Illuminate\Database\Eloquent\Relations\HasOneOrMany::save() 
must be an instance of Illuminate\Database\Eloquent\Model, array given on line 1

```

**Comment by srmklive** [comment]
@etherealite Why don't you try this. May fix your issue.

```
$parents = factory(App\Parent::class, 5)->create();
$parents->each(function ($parent) {
    $random = rand(0, 15);
    if ($random <= 1) {
        $item = factory(App\Dependant::class, $random)->make();

        $parent->dependants()->save($item);
    }
});
```

**Comment by etherealite** [comment]
Thanks for the tip @srmklive. I solved the issue by making a check `$random > 1 `  call `$model->saveMany()` and then adding an additional check for `$random === 1` that will call `$model->save()`. 

This is just experimental code, so I can be as dirty as I would like. 

Again, I'm super impressed by the responsiveness and eager to contribute in this community.

**Pull request merged**
