### PR TITLE
[11.x] Fixes old() function param & return type

### PR DESCRIPTION
**Pull request by wietsewarendorff**
Fix param & returntype to match actual values, see: https://github.com/laravel/framework/blob/923ee74bff9aeb16919f7bfbc14cde9091b4949b/src/Illuminate/Http/Concerns/InteractsWithFlashData.php

### CODE REVIEW

**Comment by wietsewarendorff** [comment]
What's your suggestion: update the docblock in the `InteractsWithFlashData.php`-trait as well (add integer as an option)?

btw: just noticed that the `old()`-method in the trait will return the session-data `$this->session()->getOldInput($key, $default)` which has a mixed return type... so both docblocks seems to be out-of-date

**Comment by rodrigopedra** [comment]
If `$default` is `mixed`, then the return will be `mixed`. 

Any `Stringable` or `Htmlable` could be used as a default value. Also floats, booleans, or basically any value that can be echo'ed.

I actually don't see how a `Model` instance, as currently is proposed, would be helpful as a default value. But nonetheless, maybe someone uses it like that.

I don't see a reason to change these type hints when `$default` can accept anything.

**Comment by wietsewarendorff** [comment]
Looks as if I opened a can of worms here: I think mixed is too wide for this parameter and/or the return type. I could argue that the `old()`-method in the `InteractsWithFlashData` has incorrect docblocks then, but that's another story.

Thanks for your input!

**Comment by rodrigopedra** [comment]
Looking at `InteractsWithFlashData` I never knew about passing a model as `$default` and getting the `$key` as an attribute, that is interesting...

But yes, I would say it seems to have incorrect docblocks. Maybe that could be fixed.

**Pull request closed without merging**
