### PR TITLE
[8.x] Test relation count when disabling its constraints

### PR DESCRIPTION
**Pull request by mtawil**
I am opening this PR with only the test case to show and prove that this will **fail** because of not getting the correct count of a model relationship.

Here, on [`testItBasic`](https://github.com/mtawil/framework/blob/disabling-constraints-leads-test-to-fail/tests/Integration/Database/EloquentWithCountTest.php#L39-L61) test, we've created two records for `Model1`, each one of it is created only one record of `Model2`, so basically, we have only one record of `Model2` for each `Model1`, and a total of two records when doing `Model2::all()->count()`

This closed PR is solving this test case: https://github.com/laravel/framework/pull/37489

### CODE REVIEW

**Comment by mtawil** [comment]
[Failed asserting that 2 matches expected 1.](https://github.com/laravel/framework/pull/37506/checks?check_run_id=2689653919#step:8:124)

**Comment by mtawil** [comment]
Now, with the commit that fixes this issue, the tests are pass.

I believe that the relation constraints must be enabled when booting models or initializing model traits to avoid wrong relation queries.

**Comment by taylorotwell** [comment]
I really don't think you should be executing queries within a model boot method?

**Comment by mtawil** [comment]
@taylorotwell what if I want to add a global scope for a specific case like I don't want to run this global scope for users who had an admin role?

**Pull request closed without merging**
