### PR TITLE
[6.x] Added a new helper function for DB::listen method

### PR DESCRIPTION
**Pull request by thezahedi**
This is helpful for testing.

This helper function replace the question mark with actual binding and dump the executed queries.

### CODE REVIEW

**Comment by thezahedi** [comment]
Can you please tell me the reason of thumbs down?

**Comment by mfn** [comment]
Because it's (afaik) unwritten but basically agreed that we want to get rid of global functions rather to add new ones.

Also your `vsnprintf` might work for your case (MySQL?) but doesn't give useful/correct SQL back for others (pgsql).

**Comment by GrahamCampbell** [comment]
The main problem with this is that illuminate/support does not depend on illuminate/database.

**Comment by GrahamCampbell** [comment]
If this were to go into the framework, it would be into the foundation functions.php, and not support. If you still want to peruse this, please create an issue on the ideas repo.

**Pull request closed without merging**
