### PR TITLE
[5.7] Detect connection errors also

### PR DESCRIPTION
**Pull request by ollielowson**
I've had an issue where a project has dropped a database connection and thrown a `FatalThrowableError`. Looking at the `createTransaction()` function in `https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Concerns/ManagesTransactions.php` and `src/Illuminate/Database/DetectsLostConnections.php`, this only detects instances of the `Exception` class.

I was able to resolve this issue in my project by changing the functions concerned to accept an instance of `Throwable` instead of `Exception`, so this is a Pull Request implementing those changes.

It's my first PR on a big project though, so I would appreciate any feedback :)

### CODE REVIEW

**Comment by ollielowson** [comment]
Following a discussion on larachat.slack.com (with @36864), I am planning to implement a test for this, but I will need to do some careful thinking about how to do it. Essentially, I will need to null the PDO object at the point of being about to beginTransaction() on it...

**Comment by GrahamCampbell** [comment]
5.6 is probably a better target for this?

**Comment by taylorotwell** [comment]
Please re-send to 5.6 branch.

**Comment by ollielowson** [comment]
Sorry for the delay - now re-sent to 5.6 in #22948

**Pull request closed without merging**
