### PR TITLE
[5.4] Add try-catch blade directives

### PR DESCRIPTION
**Pull request by jakebathman**
Other templating systems include a way to catch exceptions in views (see [Perl's try-catch](http://www.template-toolkit.org/docs/manual/Directives.html#section_TRY_THROW_CATCH_FINAL) and the [Ruby on Rails `try` method](http://api.rubyonrails.org/classes/Object.html#method-i-try)). This pull request would add try-catch ability to Blade templates.

Added are: 
- `@try`
- `@catch()`
- `@finally`
- `@endtry`

Here's two examples in a Blade view. Note that `@catch` takes an argument, identical to the native PHP behavior:

image

image

Also included are tests covering these new directives.

Let me know if there are questions or suggestions. Thanks!

### CODE REVIEW

**Comment by browner12** [comment]
hmm.... i don't think we should be using try/catch blocks in our view.

**Comment by jakebathman** [comment]
I've had instances where I could use a ternary statement, but want the failure to be logged or reported. Might not happen often, but it's similar to other directives we use in Blade already (like [`@switch`](https://github.com/laravel/framework/pull/19758)) but with added abilities.

**Comment by browner12** [comment]
couldn't the try/catch happen in the `getName` method then? and do your logging/reporting there?

plus if you move it higher up the chain, then you're doing it in one spot, rather than littering your views with extra blade directives.  then `getName` *always* returns a string, and you handle the other stuff behind the scenes.

I feel like the view should be more ignorant of this stuff.

**Comment by jakebathman** [comment]
I definitely see what you're saying, and generally I agree: try-catch logic should usually be done higher up.

If `$foo` isn't an instance of the class/model though, then `getName()` won't be defined and the method call will fail.

Hopefully errors _will_ be caught higher up, but this might help in catching some last-minute issues when rendering a view (or something like generating an email view, where you're less able to just redirect a user to a 500 page).

**Comment by joshmanders** [comment]
Are we coming full circle here and building original php in blade?

**Comment by deleugpn** [comment]
I know we should had drawn the line a while back, but try catch is too much.
I don't think this should be supported/encouraged. If you really want to do this, add your own blade directive and/or use `@php`

**Comment by jakebathman** [comment]
Agree with all comments. But, in the instances where a last-mile exception catch might be very useful.

The Blade docs section has a snippet that I think fits this nicely: "While Blade provides this feature, using it frequently may be a signal that you have too much logic embedded within your template."

Having try-catch directives doesn't inherently direct the programmer to use them in every blade; they're simply a tool for certain situations, much like `@isset`, `@inject`, and `@switch` are small bits of last-mile conditionals to help build a view.

Thanks for the feedback, all. I really do appreciate it.

**Comment by deleugpn** [comment]
`inject` is also over the line.

**Comment by DanielCoulbourne** [comment]
I don't think this PR is getting a fair shake.
No, you probably don't want to be in a situation where you are checking for exceptions in your views. Yes, there are better places in your app to do this. But if you are reaching for `@try` and `@catch` in a blade template, chances are something is preventing you from being on the "golden path" where other, nicer architecture is possible.

I think the same can be said of `@switch` as @jakebathman said. If you have a switch case in your template, chances are there is a better place that logic could have lived. That said, we give people tools because sometimes apps are hairy and its good to have a semi-supported way to deal with it.

I don't see anything wrong with this directly, and I don't think shaming people for being in the situation where they need this is a particularly good reason not to support it. If we only support Blade directives for logic that **should** live in the view, there's a lot to rip out.

**Comment by taylorotwell** [comment]
Send to 5.5.

**Comment by jakebathman** [comment]
Will do shortly.

**Comment by devcircus** [comment]
Feels like the current "helper craze" is  just muddying the core. Many are just repeating solutions that are already dead simple.

**Pull request closed without merging**
