### PR TITLE
[5.6] Switch to new random API

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👍

**Comment by kamui545** [comment]
I am wondering, is `srand($seed)` still relevant after this change?

**Comment by kamui545** [comment]
Yeah, looks like I was right and this PR breaks the seed feature.
I just tried, we cannot reproduce random numbers.

ping @taylorotwell

**Comment by keradus** [comment]
wow, no tests for that ? :D

**Pull request merged**
