### PR TITLE
[5.3] Add test to see if onConnection is respected

### PR DESCRIPTION
**Pull request by segadora**
This tests indicates that it is not possible to dispatch a single job to a specific connection as documented on 'https://laravel.com/docs/5.3/queues' at **Dispatching To A Particular Connection**

The test is trying to set a null driver as a queue driver and because of that, the job should be discarded.

I wish to have a second look on if this is the correct way to do it.

### CODE REVIEW

**Comment by jacobemcken** [comment]
From the [documentation](https://laravel.com/docs/5.3/queues#introduction):

> A null queue driver is also included which simply discards queued jobs.

This is what the test case proves isn't true, if I understand it correctly.

**Comment by taylorotwell** [comment]
We welcome fixes as PRs.

**Comment by segadora** [comment]
@taylorotwell so am I right, there is a bug or not?

**Comment by segadora** [comment]
I figured out the problem was that I was missing `Illuminate\Contracts\Queue\ShouldQueue` interface, 

https://laravel.com/docs/5.3/queues#creating-jobs

**Pull request closed without merging**
