### PR TITLE
[5.5] make Collection::where independent on error reporting

### PR DESCRIPTION
**Pull request by themsaid**
In reference to https://github.com/laravel/framework/issues/22106

This change removes the try...catch wrapping so that it's not dependent on the level of error reporting you chose for your project.

```
if (count(array_filter([$retrieved, $value], 'is_object')) == 1)
```

Ensures that both variables are objects or non is an object.

### CODE REVIEW

**Comment by mbardelmeijer** [comment]
This broke my code unfortunately. Code to reproduce:

Runs `1` with the old code-base, returns `0` with the new code-base
```
$user = new \stdClass;
$user->created_at = Carbon::now();
 collect([$user])->where('created_at', '!=', null)->count()
```

**Comment by themsaid** [comment]
@mbardelmeijer fixed that here https://github.com/laravel/framework/pull/22256

thanks for the heads up :)

**Comment by mbardelmeijer** [comment]
@themsaid thank you!

**Comment by valorin** [comment]
@themsaid this breaks the case where you're trying to compare a object that can be converted to a string against a raw string.

Consider this code:
```
collect([['value' => new \Illuminate\Support\HtmlString('hello')]])
    ->where('value', 'hello');
```

Prior to this change, the result of `where()` would include the record, since the string values match. 

After this change, the result of `where()` is empty.

I would consider this a major breaking change, because it's incredibly subtle and can cause unexpected behaviour in code (such as in our case).

**Comment by themsaid** [comment]
@valorin here's a fix: https://github.com/laravel/framework/pull/22295

**Comment by valorin** [comment]
Awesome, thanks @themsaid :grin:

**Pull request merged**
