### PR TITLE
[6.x] Alpha ordered imports

### PR DESCRIPTION
**Pull request by driesvints**
giphy-downsized-large

### CODE REVIEW

**Comment by antonkomarev** [comment]
Finally!

**Comment by GrahamCampbell** [comment]
I kinda liked the ordered imports in Laravel, even though I alpha order my own code. :P

**Comment by browner12** [comment]
I'm with Graham. I don't see any valuable reason to change.

**Comment by antonkomarev** [comment]
I cold see one valuable reason for a future: alpha ordered imports could be easily groupped.

Instead:
```php
use Illuminate\Contracts\Auth\Authenticatable as UserContract;
use Illuminate\Contracts\Auth\UserProvider;
use Illuminate\Contracts\Hashing\Hasher as HasherContract;
```
You could have:
```php
use Illuminate\Contracts\{
    Auth\Authenticatable as UserContract,
    Auth\UserProvider,
    Hashing\Hasher as HasherContract
}
```

**Comment by browner12** [comment]
why is the grouping valuable?

**Comment by driesvints** [comment]
I'm not a fan of grouping myself 😅

**Comment by antonkomarev** [comment]
Me too, but its an example what you can easily do with alpha ordered imports and what will require much more changes with length ordered imports.
In fact - I don't like to make changes in framework and check if my IDE isn't reordered imports before pushing the changes. Is there at least one benefit to have length ordered imports? For me it's much clear to have them ordered by name and to see all the imports from similar namespace near to each other and not to track down all the list to find what I want.

**Comment by driesvints** [comment]
> Is there at least one benefit to have length ordered imports?

More consistency with the rest of the PHP open source community.

**Comment by antonkomarev** [comment]
@driesvints length ordered imports? really? I always meant that alpha ordered imports is standard for PHP.

**Comment by driesvints** [comment]
@antonkomarev ah sorry, I meant alpha ordered.

**Comment by browner12** [comment]
The IDEs are gonna be pissed we hounded them for so long about making length ordering an option for auto-formatting, and now we go and just switch anyway. 😅

**Comment by devcircus** [comment]
Strange move, as this exact change received so much push-back for years. Then suddenly, without explanation the change is made. To me, this was one of the many things that made the codebase a joy to peruse.

**Comment by HDVinnie** [comment]
worst PR ever.... length ordered imports is so much cleaner looking.

**Comment by antonkomarev** [comment]
And now they are easier to perceive. What better, pretty look or better readability?

**Comment by devcircus** [comment]
If you have a decent ide, you never have to perceive anything. They just sit at the top of your classes. Before laravel I would have never sorted by length but after years of doing it that way, I’ve grown to love it.

**Comment by driesvints** [comment]
Ordering alphabetically gives you a directory-like view of the imports which imo is a better 1-on-1 mapping when you browse a file directory. Ordering by length doesn't has any real benefit.

**Pull request merged**
