### PR TITLE
[5.5] [WIP] Double down on exception self rendering

### PR DESCRIPTION
**Pull request by laurencei**
So in `5.5` Taylor has announced that Exceptions can provide rendering information to the Exception Handler.

This PR is a WIP for a refactor of the Exception Hander, to take advantage of the new feature, and extract the specific exception rules and place them into their respective classes.

This makes the exception handler a more "generic" class and no longer needs to know about specific exceptions (for example - it no longer needs to contain validation exception logic etc)

Meanwhile - we move that logic back to the exception itself - which is probably a better place for it to be.

The main issue I can see for people upgrading to 5.5 is the overriding of the login path for an unauthorized attempt. I think this can be solved fairly easily with just a config option. But people are still able to intercept this exception in their own app exceptions `render()` function and continue to override it with their custom implementation.

@taylorotwell - if you like this concept - I've got a whole bunch of test cases I want to write for the entire exception class handler (currently there are none?) if this is to get merged. But I did not want to spend too much time if you are not interested.

### CODE REVIEW

**Comment by sisve** [comment]
Moving the functionality to per-Exception implementations of prepareException/response does not provide the  same functionality; I can no longer [easily] write a custom handling of an exception thrown in a third party library - I now have to write my own handler to get the same behavior. 

How would a package target both 5.4 and 5.5 with these changes? Imagine that I have my own sisve\HandlerShazaam (reused by all by Laravel projects); can I write code that works in both 5.4 and 5.5, or do I need to keep two separate codebases?

**Comment by laurencei** [comment]
@sisve - maybe I'm not following what you've written - but in your scenario there is no change in behavior? The logic in the exceptions is *optional* - if nothing is there the app would continue on with the previous behavior.

i.e. In your `app\Exceptions\Handler.php` you would just write

```
    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $exception
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $exception)
    {
        if ($exception instanceof \sisve\HandlerShazaam) {
            // do custom logic
        }
        return parent::render($request, $exception);
    }
```

That would run before you encounter and of the revised code.

And there is no difference between 5.4 or 5.5 in that scenario either AFAIK.

**Comment by sisve** [comment]
I'm saying that you're breaking all existing customized handlers with no obvious gain for the developers. What does the developer get out of rewriting the handlers to this new format? Is there any new functionality at all?

I'm also against the idea of moving out handling of the exceptions onto the exception classes themselves, I believe this clearly breaks separation of concern.

**Comment by laurencei** [comment]
> I'm saying that you're breaking all existing customized handlers with no obvious gain for the developers. What does the developer get out of rewriting the handlers to this new format? Is there any new functionality at all?

What functionality is broken? You dont _have_ to use the new way - the old way will continue to work without changes (except for AuthorizationException - so maybe we leave that as it was)?

> I'm also against the idea of moving out handling of the exceptions onto the exception classes themselves, I believe this clearly breaks separation of concern.

This feature is already in 5.5 - this PR is not adding it. We are just taking advantage of it.

Should the Exception handler know about all the different exceptions it may use? Some might say that is a separation of concern as well. And all the exception class is doing is holding a recommended way to have itself handled. This is alreay

**Comment by sisve** [comment]
Every existing handler that today that has overridden prepareException or convertValidationExceptionToResponse will no longer work, instead they will silently stop working since no one calls those methods anymore. 

There's no gain for the end-user, the developer, by removing these methods. Removing them will only cause additional instructions and time spent upgrading to 5.5, and without any obvious gain. 

Why can't the these method stay, and perhaps they call out themselves to the exception objects? That way there wouldn't be a any bc break, developers that has overridden these methods would still have working code after an upgrade.

**Comment by laurencei** [comment]
The benefit/gain is a cleaner long term solution to handling all types of customising of exceptions without having to touch the core exception handler in the first place.

We *could* keep `prepareException` and it called as an empty function, and that way if someone was overriding it, the behavior would remain. But you could also just move that code in the app parent render function and get the desired behavior - so seems like a simple change.

Would many people be realistically overriding `convertValidationExceptionToResponse`? I would think it would likely only be a few - and you can easily capture that in your own app with 2-3 lines. Doesnt seem like a big deal for the 5.5 upgrade.

I think the fact we are even having this discussion is proof of why it needs to change. Having people overriding such deep functions on a framework class to get basic customization is a sign of it not being optimal. This PR means that moving forward other changes could be made to the core exception handler, without having to worry about strange overrides in the app classes because someone want a different validation error message.

I'll wait to see what Taylor and others think of the concept I'll happy to do more work on it and add some tests etc.

**Comment by taylorotwell** [comment]
This isn't a tenable solution because they can't be easily customized.

**Comment by taylorotwell** [comment]
I'm just going to keep these things as they are for now.

**Comment by laurencei** [comment]
@taylorotwell - ok fair enough.

But just to confirm - the ability to customize is no different and is still fairly easy?

In `app\Exceptions\Handler.php`:
```
public function render($request, Exception $exception)
{
    if ($exception instanceof \use Illuminate\Validation\ValidationException) {
        // do custom logic
    }

    return parent::render($request, $exception);
}
```

That means you can handle any/all exceptions in your app anyway way you like - otherwise you let it enter the core handler and get handled in a default way?

Would possibly be better than overriding protected core exception functions everywhere?

Leave it with you.

**Comment by sisve** [comment]
My argumentation in this issue isn't that it has removed the capability for people to write code that does whatever they want; it is that it breaks existing code that already does what the developer wants.

**Pull request closed without merging**
