### PR TITLE
[5.5] Fix for recent Carbon update (1.24.0)

### PR DESCRIPTION
**Pull request by RyanThompson**
Caused by: https://github.com/briannesbitt/Carbon/commit/a05bed23de4c00040fe33cc6820c7e6be8d00c04#diff-c060a4f07dfb6bce7015fa79a21b6963L3853

### CODE REVIEW

**Comment by RyanThompson** [comment]
Ayaya.. they just reverted their CS change: https://github.com/briannesbitt/Carbon/commit/ef12cbd8ba5ce624f0a6a95e0850c4cc13e71e41

image

**Comment by kylekatarnls** [comment]
Please report us the bug on Carbon before such work-around.

**Comment by deleugpn** [comment]
@kylekatarnls according to the OP link, it was reported, but you replied saying it was Laravel's job to abide by Carbon's breaking change on a minor release.

**Comment by kylekatarnls** [comment]
No, I did not say it was the Laravel's job, I meant Laravel no longer needs __set_state override at all.

But I missed this change, and it's a breaking change, I should not have put it in the release and as Laravel is not the only library that extends Carbon, revert the change was the right thing to do by our side.

I hope you understand my position.

**Pull request merged**
