### PR TITLE
[5.0] Multiline arrays should have trailing commas

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Most of our multiline arrays do this, but some don't.

### CODE REVIEW

**Comment by taiyaei** [comment]
:+1: Nice. Almost too many cleanup PRs in the past couple days

**Comment by GrahamCampbell** [comment]
@taiyaei lol, maybe. I'm preparing for the big cs change in May, applying some minor stuff now.

**Comment by Sladewill** [comment]
Another thing with the arrays is the use of the square bracket arrays in some areas vs the traditional array().

**Comment by GrahamCampbell** [comment]
@Sladewill I know. We're not changing that on 5.0. We'll be totally enforing it in May on the master branch.

**Pull request merged**
