### PR TITLE
[5.6] Changed `==` to `===` in a few places.

### PR DESCRIPTION
**Pull request by TBlindaruk**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
All these look safe to me, but please don't send any more PRs that change the equals comparison type. PRs of that nature typically don't add much value and leed to bugs if not reviewed very carefuly.

**Comment by TBlindaruk** [comment]
@GrahamCampbell ,ok. I will not do it anymore ;)

But I have changed ` equals comparison type` only in places where I sure, that it will not lead to bugs.

**Comment by browner12** [comment]
very much against this PR on 5.6. Even though I agree strong equivalency is usually better, these edits **change behavior**.  While they *probably* won't break things, they definitely have the *potential* to.

If we want to push these changes to 5.7, I'm all for that.

**Comment by TBlindaruk** [comment]
@browner12 , 
I have changed only comparing with:
 - not an empty string;
 - count function
 - func_num_args() function 
------
I have not changed the comparing between 2 vars

**Comment by browner12** [comment]
while the `count`s are probably fine, any of the string comparisons are an definitely issue.

`var_dump(true == 'string')`  //returns true
`var_dump(true === 'string')` //returns false

not saying these are likely scenarios, but if it's possibly we've seen it happen before.

my personal opinion, send these all the 5.7, where we're allowed to break code.

**Comment by TBlindaruk** [comment]
I have created a PR to master brunch for 5.7 version.

**Pull request closed without merging**
