### PR TITLE
Adds feature to allow auto-managing datetime fields when storing and when displaying the value

### PR DESCRIPTION
**Pull request by MikeAlhayek**
Managing datetime field can be easily done by adding Accessor and Mutator into eloquent model. However, if you have multiple datetime fields it can lead more work. Or if you're new to Laravel, Accessor and Mutator may not be the first thing to think off.

Managing datetime field is now easier than ever. You can do so by listing the property names that you want Eloquent to manage for you like so
```
   /**
     * Datetime attributes that should be auto formatted.
     *
     * @var array
     */
    protected $formattedDates = ['approved_at','uploaded_at'];

```

Moreover, you can even change the display format for only one field like so

   /**
     * Datetime attributes that should be auto formatted.
     *
     * @var array
     */
    protected $formattedDates = [
                                                    'approved_at',
                                                     [
                                                           'key' => 'uploaded_at',
                                                           'out_format' => 'H:i A'
                                                     ]
                                                   ];

The default format can easily be set in the config/app.php file using the following config
```
    /*
    |--------------------------------------------------------------------------
    | Application Fallback In Datetime Format
    |--------------------------------------------------------------------------
    |
    | The fallback in datetime format determines the default format to use when
    | storing a datetime auto-formatted field value in the databases.
    |
    */

    'fallback_in_format' => 'Y-m-d H:i:s',

    /*
    |--------------------------------------------------------------------------
    | Application Fallback Out Datetime Format
    |--------------------------------------------------------------------------
    |
    | The fallback out datetime format determines the default format to use when 
    | displaying a datetime value from the database.
    | You may override this format for each field using the $formattedDates
    | in eloquent model model.
    |
    */

    'fallback_out_format' => 'm/d/Y H:i A',
```

### CODE REVIEW

**Review by MikeAlhayek — COMMENTED** [review]
PSR2 styled

**Comment by CrestApps** [comment]
I just pushed a new commit that should resolve the code's style issue. I am not sure how to fix this pull request. If approved, the code from this commit should be used https://github.com/laravel/framework/pull/18491/commits/7ed8e6ec48679f4f268f0c2cdabb045ff564a755

**Comment by deleugpn** [comment]
If you make a commit and push to the same branch you used in the pull request, it will automatically be picked up.

**Comment by taylorotwell** [comment]
No plans on adding this to the core.

**Comment by CrestApps** [comment]
Any idea on why not @taylorotwell?

**Pull request closed without merging**
