### PR TITLE
[5.9] Revert "[5.9] Removed the md extension from LICENSE"

### PR DESCRIPTION
**Pull request by driesvints**
Reverts laravel/framework#29041

It doesn't matter if it's Markdown. Markdown is a plain-text format. This is the same across all the other repos. Markdown will also neatly render in Github. This is also pretty much the standard across other popular open source libraries (Spatie, Zend, Beyond Code, ...)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1: The convention is, however, not use use the `md` extension. In particular, software that automatically checks licenses may only look for `LICENSE`.

**Comment by antonkomarev** [comment]
I suppose Spatie & Beyond Code are using `.md` extension because Laravel used it when they were deciding how to name a file.

**Comment by driesvints** [comment]
We're already using a Markdown extension across all other Laravel libraries. It's a plain-text file. I really don't see the need to change this.

**Comment by BrandonSurowiec** [comment]
For what it is worth, the 5.8 branch (with .md) shows a nice license summary at the top of the page on Github, but the extension-less one does not. I vote to revert.

- With Summary: https://github.com/laravel/framework/blob/5.8/LICENSE.md
- Without: https://github.com/laravel/framework/blob/master/LICENSE

**Comment by antonkomarev** [comment]
That's strange because in all my packages license summary displays for files without extension without any issues: https://github.com/cybercog/laravel-love/blob/master/LICENSE

**Comment by BrandonSurowiec** [comment]
@antonkomarev Guess I'm wrong then :)

**Comment by antonkomarev** [comment]
Maybe github will switch license parser to new naming only after next release... who knows...

**Comment by GrahamCampbell** [comment]
GitHub only renders licenses determined by the default branch of a repo, which is 5.8 for us.

**Comment by staudenmeir** [comment]
An argument against the `md` extension: GitHub adds a `LICENSE` file when you create a new repository and select a license.

**Comment by taylorotwell** [comment]
I'm fine with reverting it until we can get all of the repositories done across the ecosystem. I don't have a strong preference either way.

**Pull request merged**
