### PR TITLE
[9.x] Sub select render only if necessary

### PR DESCRIPTION
**Pull request by cbl**
Duplicated https://github.com/laravel/framework/pull/37195 into `9.x`

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm curious why this is applied to Eloquent builder instead of the base query builder? Was there a reason for that?

**Comment by cbl** [comment]
You are right, I will move the functionality to the base query builder.

**Comment by cbl** [comment]
When a base query builder object is cloned the subselect will also be cloned. This is necessary because the subselect needs the correct instance of the parent query builder so the bindings can be added when rendering.

**Comment by taylorotwell** [comment]
Just not sure this is worthwhile to merge at the time being. Still fear unnecessary breakage of applications in the future and it seems like the problem is pretty easy to work around by not adding the sub select until you are done building up the query.

**Comment by cbl** [comment]
Understandable. The work around is possible where else it sometimes might be more difficult to solve. But negligible in view of the fact that there is a risk of break existing application.

**Pull request closed without merging**
