### PR TITLE
[10.x] Add Transactional attribute

### PR DESCRIPTION
**Pull request by mateusjatenee**
Spring has a very interesting [@Transactional](https://docs.spring.io/spring-framework/reference/data-access/transaction/declarative/annotations.html) annotation. I know Laravel doesn't use a lot of attributes, but I found this to be pretty interesting. Pretty handy when you know you want your entire controller method to run within a transaction.

My 1st implementation allowed for anything that's handled by the container to be transactional, but I simplified it to just things the Router handles.

Example:
```php
<?php

class PostController
{
  #[Transactional]
  public function store(CheckoutRequest $request)
  {
    $post = auth()->user()->createPost($request->validated());
    
    foreach ($request->tags() as $tag) {
      $post->addTag($tag);
    }
    
    return response()->noContent();
  }
}
```

In this scenario the entire method would run inside a transaction, instead of having to wrap the entire thing in a closure.

### CODE REVIEW

**Comment by timacdonald** [comment]
I've wanted this kind of thing on Commands as well. Pretty cool.

**Comment by mateusjatenee** [comment]
@timacdonald Yeah I think this would be pretty handy for commands too, and considering they're the equivalent of routes for the Console kernel it makes sense IMO. 

I'm still not sure whether I think it's good to have this available for everything that's resolvable by the container, but I'm sure we can figure that out if this gets the green light 👍

**Comment by mateusjatenee** [comment]
IMO putting it into a middleware makes it less explicit and easier to misuse without realizing it. 
I find the attribute very clear and visible, even though it might be uncommon.

**Comment by chu121su12** [comment]
How to tell (maybe, make it explicit) when the middleware queries (2 crucial ones I think are auth & substitute bindings) run?

**Comment by taylorotwell** [comment]
I think this idea could be fleshed out a bit more and be something compelling. I'm not sure I'm totally sold on its current form, mainly because: 

1) The middleware question I raised. If this is an attribute, why not `#[Authenticate]` and `#[Authorize]` and pretty much every other middleware style thing we do in Laravel now. Feels like we're opening floodgates to all of those being submitted as attributes, and I'm not sure I'm ready to go down that road.

2) I think a transactional route / controller thing *probably* (maybe?) needs to consider `lockForUpdate` and `sharedLock` support on `SubstituteBindings` as mentioned to be fully robust.

**Pull request closed without merging**
