### PR TITLE
[5.4] add tap to query builder

### PR DESCRIPTION
**Pull request by BrandonShar**
I've run into a few situations lately (mainly parsing filters from query strings) where I ended up using when(1, $callback).

To make this a bit cleaner, I added a tap method to query builder to mimic the behavior found in collections.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Interesting, what were you using this for?

**Comment by BrandonShar** [comment]
I've been parsing filters out of the query string on api endpoints.  A simplified example of code looks like this:

```
return User::when(true, function ($query) use ($request) {  
    foreach ($request->except('sort', 'page') as $param => $value) { 
        $query->where($param, $value); 
    } 
})->get();
```

**Comment by BrandonShar** [comment]
I'd love a cleaner way to filter by query params, but it would definitely require some discussion since the solution would likely be pretty opinionated.

**Comment by taylorotwell** [comment]
Gotcha.

**Comment by JosephSilber** [comment]
@BrandonShar BTW, you can pass an array directly to `where`:

```php
return User::where($request->except('sort', 'page'))->get();
```

**Comment by BrandonShar** [comment]
@JosephSilber thanks for the advice, I'll keep that in mind. In this case though, I simplified my example a good bit. In my real use case, I check for things like * to indicate wild card and whether scopes exist for certain filters.

**Pull request merged**
