### PR TITLE
Postgres - insert default values

### PR DESCRIPTION
**Pull request by pun-ky**
without this fix postgres driver does not allow to create a row without specifying values / using only default values. in postgresql there is special syntax for doing such stuff. for instance:

"insert into $table ($columns) values $parameters" (syntax error because of $parameters equal to "()", however on mysql it works properly)
"insert into $table default values" (works properly on postgres)

see:
http://www.postgresql.org/docs/9.4/static/dml-insert.html
"INSERT INTO products DEFAULT VALUES;"

https://github.com/laravel/framework/issues/10394

### CODE REVIEW

**Comment by taylorotwell** [comment]
Need at least a full paragraph of description please.

**Comment by GrahamCampbell** [comment]
Why is this needed?

**Comment by GrahamCampbell** [comment]
Postgres already supports this without this change?

**Comment by pun-ky** [comment]
without this fix postgres driver does not allow to create a row without specifying values / using only default values. in postgresql there is special syntax for doing such stuff. I described it here:

https://github.com/laravel/framework/issues/10394

**Comment by GrahamCampbell** [comment]
You need to actually put default values in the migration.

**Comment by pun-ky** [comment]
It is not possible because table consists of auto generated column / id only. And yes it is currently expected behavior.

**Pull request closed without merging**
