### PR TITLE
[5.4] Ability to pass data to the view when rendering a paginator

### PR DESCRIPTION
**Pull request by ockle**
When rendering pagination with a custom view:
```php
{!! $users->links('custom-view') !!}
```
this pull request adds the ability to send data to the view:
```php
{!! $users->links('custom-view', ['foo' => 'bar']) !!}
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What's the use case for this please. Why not use view composers?

**Comment by ockle** [comment]
@GrahamCampbell Because view composers don't contain any relation to the context the view is being rendered in.
As I see it, rendering the pagination is akin to [including sub-views](https://laravel.com/docs/5.3/blade#including-sub-views). They allow extra data to be passed in so that you can e.g. conditionally show HTML/data/etc.
This functionality would be useful in the pagination view so one could e.g. change the arrow character used for the paginaiton next/previous links in different parts of your application. If you currently want to be able to do this, you have to have two almost identical pagination views that are only different by two characters. This is a significant amount of code repetition.
There is also a suggestion of a convention in the framework that when you specify a view name, the next parameter is data to be passed to the view, so to me, this functionality is one of those rare times in Laravel where you expect something to work the way you are used to but doesn't, so this PR increases consistency in that regard.

**Comment by Francismori7** [comment]
Also might find usage for this by using `['minimalist' => true]` which could, in your custom template, prevent some stuff from being outputted.

**Comment by tillkruss** [comment]
Can you add this to the docs, please?

**Pull request merged**
