### PR TITLE
Allow optional Render method in Blade Components

### PR DESCRIPTION
**Pull request by ahinkle**
This PR allows the `render` method to be optional on Blade Components. This will allow for cleaner blade components - Livewire 2.0 allows this and would clear up any developer mistakes between Laravel Components and Livewire Components. By default, it will resolve to the created blade component location. `(components.*)`

Example:
```
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Alert extends Component
{
    //
}
```

Will automatically render the view: `components.alert`

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by morrislaptop** [comment]
@ahinkle releasing as a package?

**Comment by ahinkle** [comment]
I don't think so; could be a simple trait I guess. 

I don't think Taylor liked the implementation so if you think of a cleaner way feel free to suggest or open a PR. 🙂

**Comment by ahinkle** [comment]
I've found this to become an annoyance in our organization between Laravel and Livewire components so I created a simple package for anyone who may find it useful.

https://github.com/ahinkle/auto-resolvable-blade-components

**Pull request closed without merging**
