### PR TITLE
[5.8] Extract method refactor

### PR DESCRIPTION
**Pull request by imanghafoori1**
I just saw that there is a little duplicated code which can be improved a little.
The `isCallableWithAtSign` method is replaced with the new `isStrContaining`.

### CODE REVIEW

**Comment by roberto-aguilar** [comment]
The `illuminate/container` package already depends on `illuminate/support` so maybe we can use `Illuminate\Support\Str::contains` method?

**Comment by imanghafoori1** [comment]
If you mean using it instead of the isStrContaining() method, That does not do exactly what we want.
so any way we have to check for ‌is_str()

**Comment by roberto-aguilar** [comment]
You're right, sorry for the misunderstanding, i was referring to the `strpos` function. Maybe it could improve readability a little bit.

**Comment by imanghafoori1** [comment]
I think it's enough.
I don't want to make more nested calls since it gets slower.

**Comment by taylorotwell** [comment]
No plans on changing right now since no bugs.

**Pull request closed without merging**
