### PR TITLE
:children_crossing: Optimize Boolean verification

### PR DESCRIPTION
**Pull request by frowhy**
Optimize can not verify boolean "true" and "false".

### CODE REVIEW

**Comment by frowhy** [comment]
I think this is not good.
Sorry, my English is poor.
These are the screenshots I'm using.
image
image

**Comment by Dylan-DPC** [comment]
This is a breaking :boom: change. Better to target it to master.

**Comment by frowhy** [comment]
@Dylan-DPC Thanks, I will resubmit pull request.

**Comment by Modelizer** [comment]
@frowhy you should use 0 or 1 in the url.

**Pull request closed without merging**
