### PR TITLE
[5.2] Allow both Symfony 2.8 and 3.0

### PR DESCRIPTION
**Pull request by barryvdh**
As discussed in #9652, Symfony 2.8 should be compatible with Symfony 3.0

/cc @stof

### CODE REVIEW

**Comment by crynobone** [comment]
@barryvdh all the components need to be updated too right?

**Comment by barryvdh** [comment]
Oh indeed

**Comment by barryvdh** [comment]
Updated the components also.

**Comment by GrahamCampbell** [comment]
:-1: from me.

**Comment by GrahamCampbell** [comment]
I'm pretty sure this breaks the exception handler too.

**Comment by GrahamCampbell** [comment]
Since Laravel uses classes marked as internal in symfony...

**Comment by stof** [comment]
> Since Laravel uses classes marked as internal in symfony

where does it do such thing ?

**Comment by GrahamCampbell** [comment]
In laravel's exception handler in the "foundation".

**Comment by GrahamCampbell** [comment]
We had to make major changes to it from 2.7 -> 3.0.

**Comment by stof** [comment]
@GrahamCampbell this is because one of the methods of the exceptionHandler got deprecated. But 2.8 has the new API too, not only 3.0

**Comment by GrahamCampbell** [comment]
We're not using the public API though. We're messing with stuff marked as internal.

**Comment by taylorotwell** [comment]
Where are we at with this? Does it break the exception handler or not?

**Comment by crynobone** [comment]
Don't see how any of this would broke the exception handler.

https://github.com/laravel/framework/compare/5.1...master#diff-83b217cbccc861e712759d541d9547aa

**Comment by taylorotwell** [comment]
We'll give it a shot and see if we have any problems.

**Pull request merged**
