### PR TITLE
Make compatible with higher version of phpunit

### PR DESCRIPTION
**Pull request by webmake**
https://github.com/laravel/framework/issues/24269

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Laravel 5.5 LTS only officially supports PHPUnit 6. Adding these to the code is a breaking change, and 5.5 LTS is in maintenance only now anyway, and PHPUnit 7 support would be a new feature.

**Comment by webmake** [comment]
This pr has no BC, as laravel itself supports php 7.0, more over I didn't lift phpunit version.Where was BC?

**Comment by deleugpn** [comment]
Changing method signature is a breaking change as somebody might have overridden these methods and is now not returning the declared type.

**Comment by webmake** [comment]
Yes, sadly but valid argument :+1:

**Pull request closed without merging**
