### PR TITLE
[5.5] Inherited Controller Parameters are not Instantiable

### PR DESCRIPTION
**Pull request by byfoz**
tl;dr:
Fixes `Argument N passed to XController::show() must be an instance of Y, none given` for parameters that inherit from each other.

Issue:
When injecting controller parameters and one of them inherits from a parameter that occurs earlier in the method interface, the parameter is passed as 'none' where it should be instantiated from the container.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Please provide a much fuller description with full code examples and explanation.

**Comment by CImrie** [comment]
@taylorotwell sure, can do - however before I try to write that up, can you have a look at the test file included?

It boils down to the following not working when you expect dependencies to be automatically injected into controller methods:

(this is taken from the test case)

```php
class TestController extends Controller{
    public function example($id, Bar $bar, Foo $foo){}
}

class Foo {}
class Bar extends Foo {} 
```

If you try to fire an HTTP request to the controller you get this error:
`TypeError: Argument 3 passed to Illuminate\Tests\Routing\TestController::example() must be an instance of Illuminate\Tests\Routing\Foo, none given`

This is because the method `alreadyInParameters` in `Illuminate\Routing\RouteDependencyResolverTrait` (line 95) contains: 

```php
    /**
     * Determine if an object of the given class is in a list of parameters.
     *
     * @param  string $class
     * @param  array $parameters
     *
     * @return bool
     */
    protected function alreadyInParameters($class, array $parameters)
    {
        return ! is_null(Arr::first($parameters, function ($value) use ($class) {
            return $value instanceof $class;
         });
    }
```

the `return $value instanceof $class` returns true if a parameter inherits from a type that is also a parameter.

In hindsight the commented out lines containing a real call to the controller highlights this error better. Happy to uncomment those changes and re-supply.

**Comment by devcircus** [comment]
The following works as expected on 5.5.1

```php
Route::get('/testing/{value}', 'HomeController@testing');
```
```php
// HomeController.php
public function testing($value, Testing $t, TestingA $a)
{
    var_dump('value: ', $value);
    var_dump($t);
    var_dump($a);
}

class Testing {}
class TestingA extends Testing {}
```

**Comment by sisve** [comment]
The code looks really weird; it went from comparing object types into comparing string values. What happens if the parameter list already has a string with a valid class name, and you then try to inject a model of that type?

    $parameters = [ 'class' => Foo::class ];

... with ...

    public function myAction(string $class, Foo $foo);

... and `Foo $foo` will not be resolved.

**Comment by CImrie** [comment]
@devcircus my example is with those parameters reversed. I.e. The extending class coming before the parent. So $a,$t ... not $t,$a as before. 

@sisve I would need to check that example later. If correct then yeah I guess we would need to change the check so it's a little more elaborate and handles both cases.

**Comment by taylorotwell** [comment]
I dunno, I feel like this needs to be thought through more.

**Pull request closed without merging**
