### PR TITLE
[5.6] allow children classes with a parent that has a primitive constructor…

### PR DESCRIPTION
**Pull request by samuraiseoul**
When contextually binding a primitive value to a parent class' constructor, instantiating the child through dependency injection does not find the parent class' bound value.

```
class ParentTestClass {
    public function __construct(int $testVal){
    }
}

class ChildTestClass extends ParentTestClass{
}

app()->when(ParentTestClass::class)->needs('$testVal')->give('28');

$child = app()->make(ChildTestClass::class);
```
 results in 
```
Unresolvable dependency resolving [Parameter #1 [ &lt;required&gt; integer $textVal ]] in class ParentTestClass
```

### CODE REVIEW

**Comment by laurencei** [comment]
This only works for one level though right?

What about

```
class GrandParentA {
    public function __construct(int $testVal){
    }
}

class Parent extends GrandParent{
}

class ChildTestClass extends Parent{
}

app()->when(GrandParent::class)->needs('$testVal')->give('28');

$child = app()->make(ChildTestClass::class);
```

**Comment by samuraiseoul** [comment]
That's a great question! I'll check tomorrow when I get back to my work machine. :D

 I think it will work though as the reflection parameter gets in there from the correct constructor. The problem is that the incorrect classname gets put onto the buildStack for the container.

 I couldn't figure out a better place to add it than here, though I'm sure one of the more senior contributors, or the man @taylorotwell himself will know if there's somewhere better to add this.

**Comment by samuraiseoul** [comment]
Either way, I'll add a test case for grandparents as well.

**Comment by samuraiseoul** [comment]
So when I tried 
```
class Parent
{
    public function __construct(int $injectable){}
}

class Child extends Parent 
{
    public function __construct(int $injectable)
    {
        parent::__construct($injectable);
    }
}
app()->when(Parent::class)->needs('$injectable')->give(28);
app()->make(Child::class);
```
it doesn't work. That said I'm not 100% that it should or would be desired behavior so I figured I'd ask before I go down that rabbit hole.

**Comment by taylorotwell** [comment]
Honestly rather than complicate the container more I would rather people just declare the binding for the child class as well.

**Comment by samuraiseoul** [comment]
@taylorotwell I disagree, though I would imagine there's a cleaner way to do it than I did. This is an inconsistent API and if nothing else it should be documented that this is the case. However, consistency is more important in an API and I would argue that either the functionality should be added, or the entire functionality of DI for primitives should be removed.

**Pull request closed without merging**
