### PR TITLE
[5.4] Allow configuration of Faker locale through config

### PR DESCRIPTION
**Pull request by dwightwatson**
As a followup to #17887, this grabs an adjustment to the Faker locale through the configuration. I went with `env` the first time as I thought it wouldn't matter much in development/test environments.

Here I'm using `app.faker_locale` as I'm not sure if any of the other standard configuration files are a better fit for this setting. Let me know if you would prefer a different name/location.

I'm happy to make the PR to `laravel/laravel` if this gets merged and you want it in the app boilerplate.

### CODE REVIEW

**Comment by vlsoprun** [comment]
But why create a new config, if you can do it yourself? [example](https://gist.github.com/vlsoprun/fee993a90b70c3bc0ec4195678536504)

**Comment by dwightwatson** [comment]
Because it's easier than making people override the singleton registration themselves, and as per the internals discussion there's at least a bit of interest in it.

**Comment by vlsoprun** [comment]
Well, overall, I like the idea.
Accounted for each project to add the registration of a provider.

**Comment by garygreen** [comment]
Thanks for this @dwightwatson @taylorotwell , makes it much more convenient! May even encourage people to use faker with seeders more, as I have started doing 😄

**Pull request merged**
