### PR TITLE
Adding UUID to Str class

### PR DESCRIPTION
**Pull request by pilot911**
http://stackoverflow.com/a/23016381/673617 - we really need it

### CODE REVIEW

**Comment by shabushabu** [comment]
There's a great package here:
https://github.com/ramsey/uuid

**Comment by pilot911** [comment]
nice package, but UUID is a core for a lot of projects.. so i hope those functions will be included

**Comment by shabushabu** [comment]
That's why we have composer, so we don't have to reinvent the wheel over and over again.

**Comment by pilot911** [comment]
hmm...ok

**Comment by GrahamCampbell** [comment]
Adding this would be a misuse of the str class. It is for manipulating strings only.

**Pull request closed without merging**
