### PR TITLE
[5.8] Move Collection::add()

### PR DESCRIPTION
**Pull request by staudenmeir**
We can move the `add()` method up to the base collection.

### CODE REVIEW

**Comment by fulopattila122** [comment]
What was the reason behind this move?

**Comment by staudenmeir** [comment]
The `add()` method is not specific to Eloquent, it makes more sense in the base collection.

**Comment by rellect** [comment]
Is this method even necessary? Isn't it the same as the `push()` method?

**Comment by staudenmeir** [comment]
It is the same, but removing it would be an unnecessary breaking change.

**Comment by rellect** [comment]
It can be marked deprecated at least.
I mean, I don't see how moving it makes it better.

**Comment by devcircus** [comment]
It's not that it makes it better, it's just where the generic collection methods belong. It does seem like it could be deprecated in master.

**Pull request merged**
