### PR TITLE
[5.7] Add comment for MySQL tables

### PR DESCRIPTION
**Pull request by kilya11**
Implementing the [idea](https://github.com/laravel/ideas/issues/897).

Currently there is no way to add a comment for the entire table using Schema Builder. Users want it, see e.g. the [question](https://laracasts.com/discuss/channels/eloquent/how-do-i-add-a-table-comment-using-eloquent-schema-builder).
To add such a comment, a developer should append after the creation of a table an additional _raw_ query to the migration:

`DB::statement("ALTER TABLE users COMMENT = 'Only active users please'");`

This PR implements the _php artisan_'s way of adding a table comment:

`$table->comment = "It's a true way!";`

The `comment` is a new table option, like existing ones: `engine`, `charset`, `collation`.

### CODE REVIEW

**Comment by morloderex** [comment]
What about comments on single columns?

**Comment by kilya11** [comment]
It is already [possible](https://laravel.com/docs/5.7/migrations#column-modifiers). Just use the modifier `comment`:

`$table->string('column1')->comment('my comment');`

**Comment by taylorotwell** [comment]
No plans on adding this atm.

**Comment by vincentkedison** [comment]
Any reason for "No plans on adding this atm."? Thanks

**Comment by maxflex** [comment]
There's no need for this. 
+1 Taylor

**Comment by uonick** [comment]
> Any reason for "No plans on adding this atm."? Thanks
Jus use this package
https://github.com/diplodocker/comments-loader

**Pull request closed without merging**
