### PR TITLE
[6.x] Fixed breaking compatability with multi-schema postgres

### PR DESCRIPTION
**Pull request by raymondtri**
This extends #30555 with added suggestions from Taylor Otwell regarding handling strings or arrays, while persisting the old method signature to make it non-breaking.

### CODE REVIEW

**Comment by mfn** [comment]
### TODO
- [ ] If PR gets merged, add the new configuration option to https://github.com/laravel/laravel/blob/master/config/database.php

**Comment by driesvints** [comment]
@mfn think this one can just be documented? Don't feel it's necessary to add every single config option to the config file?

**Comment by driesvints** [comment]
Or it can be. I'm a bit indifferent tbh.

**Comment by mfn** [comment]
😄 

IMHO it's _most easily_ discovered when it's already parts of the blueprint configuration 🤷‍♀️

**Pull request merged**
