### PR TITLE
[5.2] Contract : add missing methods to the Job contract.

### PR DESCRIPTION
**Pull request by lucasmichot**
Add 4 missing methods to the Job contract.

---
- \Illuminate\Contracts\Queue\Job::isDeletedOrReleased:
  - \Illuminate\Events\CallQueuedHandler::call
- \Illuminate\Contracts\Queue\Job::isDeleted
  - \Illuminate\Queue\Worker::process
- \Illuminate\Contracts\Queue\Job::getRawBody
  - \Illuminate\Queue\SyncQueue::raiseFailedJobEvent
  - \Illuminate\Queue\Worker::logFailedJob
  - \Illuminate\Queue\Worker::raiseAfterJobEvent
  - \Illuminate\Queue\Worker::raiseFailedJobEvent
  - \Illuminate\Queue\Jobs\BeanstalkdJob::fire
  - \Illuminate\Queue\Jobs\RedisJob::fire
  - \Illuminate\Queue\Jobs\SqsJob::fire
- \Illuminate\Contracts\Queue\Job::failed
  - \Illuminate\Queue\SyncQueue::handleFailedJob
  - \Illuminate\Queue\Worker::logFailedJob

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please send to 5.3 since this is breaking.

**Comment by GrahamCampbell** [comment]
Meh, will re-open for Taylor to decide. It's up to him to decide if we can slip these in without people noticing, lol.

**Comment by lucasmichot** [comment]
I've wondered the same before PR against 5.2... LOL

**Comment by lucasmichot** [comment]
Slipped in @GrahamCampbell

**Comment by taylorotwell** [comment]
Mainly slipped this in because if we're already calling these methods in
the core, any custom implementation of Job will be broken anyway if it
doesn't include these methods.

**Comment by lucasmichot** [comment]
Indeed @taylorotwell

**Comment by GrahamCampbell** [comment]
Yeh, I totally agree. That's why I quickly re-opened it. ;)

**Pull request merged**
