### PR TITLE
[5.3] Collection chunk added param: $preserve_keys

### PR DESCRIPTION
**Pull request by hocza**
I bumped into this tonight. We should be able to decide if we want to preserve the keys or not.

I made it backward compatible by keeping it true by default.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. Please change the variable to use camelCase, or preferably, just make it shorter so we don't need two words.

**Comment by hocza** [comment]
done

**Comment by JosephSilber** [comment]
We do not use such boolean parameters anywhere. We always preserve the keys, and if you wish to reset them, you call `values()` on the result:

```php
@foreach ($users->chunk(4) as $chunk)
    @foreach ($chunk->values() as $index => $usersChunk)
        // $index will now be 0 based
    @endforeach
@endforeach
```

**Comment by taylorotwell** [comment]
Joseph is correct. You should call values on each chunk... In 5.4 will be much easier even using the higher order methods ... $chunks->each->values();

**Comment by hocza** [comment]
@JosephSilber @taylorotwell If we always preserve the keys why is it false [by default](http://php.net/manual/en/function.array-chunk.php)?

```php
array array_chunk ( array $array , int $size [, bool $preserve_keys = false ] )
```

It could come handy If I just could chunk(2,false) instead of toArray() then call the array_chunk.

Well I guess I could have choose another way to shuffle and populate my Tournament's brackets, but it seemed quicker than any. :)

```php
        $chunks = array_chunk($this->teams()->wherePaid(1)->get()->shuffle()->toArray(),2);
        $index = 1;
        foreach($chunks as $teams) {
            $team_id = $teams[0]['id'];
            if(isset($teams[1])) $opponent_id = $teams[1]['id'];
            else $opponent_id = 0;
            $this->matchups()->create([
                'team_id' => $team_id,
                'opponent_id' => $opponent_id,
                'index' => $index++
            ]);
        }
```

And by not looking at my example, it seems a waste of resource to make another call to make it zero, when we just could set the $preserveKeys back to false (as it supposed to be)

**Pull request closed without merging**
