### PR TITLE
[5.4] Method to return array of namespace hints.

### PR DESCRIPTION
**Pull request by grinry**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Remove the change to gitignore file please.

**Comment by kiberzauras** [comment]
Done. But what is the reason you dont want to ignore idea settings?

**Comment by taylorotwell** [comment]
You should add that to your Git global ignores.

**Comment by tillkruss** [comment]
@kiberzauras: What does this do?

**Comment by kiberzauras** [comment]
@tillkruss packages can have translations, and translations of these packages should have hints, for example if we use `trans('vendor::validation.required');` it will try to get translation of package named vendor.

Now in this commits i just added method, which retrieves array of already registered hints, since they was protected. This will be great help for translation manager packages.

**Pull request merged**
