### PR TITLE
[11.x] Introduce whereRelationIn in eloquent builder

### PR DESCRIPTION
**Pull request by shaheenfawzy**
# Introduce `whereRelationIn()` method to eloquent models

## Description

This pull request introduces a new method called `whereRelationIn($relation, $column, $values)` to eloquent models which is more readable and easier to filter models based on related models values using a where in statement, instead of having to use more verbose approaches such as these
```php
Model::whereHas($relation, fn($query) => $query->whereIn($column, $values));
Model::whereRelation($relation, fn($query) => $query->whereIn($column, $values));
```

## Example usage
```php
Author::whereRelationIn('posts', 'id', [1, 2, 3]);
```

## Notes
which do you think is better adding the `whereRelationIn` method, or using the same whereRelation method but modifying the behaviour to handle the case when the $operator variable is 'in' and the $value is an array like this 
```php
Model::whereRelation($relation, $column, 'in', [...$values])
```

I also opened a pr in the larave/docs repo to document this method here laravel/docs#10021

### CODE REVIEW

**Comment by decadence** [comment]
https://github.com/laravel/framework/pull/52276
https://github.com/laravel/framework/pull/48850
https://github.com/laravel/framework/pull/48111

**Comment by shaheenfawzy** [comment]
@decadence so do you think taylor will also won't accept this pr?

**Comment by decadence** [comment]
Most likely

**Comment by shaheenfawzy** [comment]
@decadence I think I'll take my chances :sweat_smile:

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

**Pull request closed without merging**
