### PR TITLE
[5.7] Add tests for the way JsonResource handles numeric keys

### PR DESCRIPTION
**Pull request by SjorsO**
(https://github.com/laravel/framework/pull/25226 retargeted to 5.7)

`JsonResource` seems to strip all array keys if any of them are numeric or a numeric string. I couldn't find any tests that assert this behavior, so this PR adds some.

Because of this behavior, doing this will give you an array of names, without any ids:
```php
public function index()
{
    $data = User::pluck('name', 'id');

    return JsonResource::make($data);
}
```

I'm not sure if this is a bug or a feature, but having tests for behavior like this is important.

### CODE REVIEW

**Comment by staudenmeir** [comment]
I and others would call this a bug that should be fixed (#24339, #23595, #24302). At least, the unused `removeMissingValues()` parameter should be fixed.

**Comment by taylorotwell** [comment]
It's not a bug.

**Comment by deleugpn** [comment]
I can see how this would be treated as not-a-bug because the Resource API layer is only interested in giving back a collection of objects or a single object and in either case the key is no longer in the Eloquent's power as it's a whole other software layer. I usually include `'id' => $this->resource->id` in my Resource Objects, allowing frontend to `pluck` the same way we do with Collections. I guess I'm neutral on this one as I can see it working both ways.

**Comment by staudenmeir** [comment]
I mainly consider it a bug because #23414 unintentionally changed the behavior in a minor release.

You can argue about whether numeric keys make sense in JSON responses. But by allowing them, you at least give people the choice. You don't have to use them.

**Pull request merged**
