### PR TITLE
[11.x] Use command string instead of array on `Concurrency\ProcessDriver`

### PR DESCRIPTION
**Pull request by rodrigopedra**
This is a follow-up to PR #52807

This PR:

- Builds a command string to call the `invoke-serialized-closure` artisan command, instead of using an array of commands parts
- Changes the `phpBinary` and `artisanBinary` methods to use the same implementation as `Illuminate\Console\Application`, which already includes escaping of these binary paths
  
  https://github.com/laravel/framework/blob/79fbf4a983c147c3bdef0045fa93aa4d8594c151/src/Illuminate/Console/Application.php#L85-L88
  
  https://github.com/laravel/framework/blob/79fbf4a983c147c3bdef0045fa93aa4d8594c151/src/Illuminate/Console/Application.php#L95-L98

  
### Notes

The issue with using the command as an array, is that Symfony's Process Component will quote each part when escaping the command, thus not allowing to send a process to the background by using `2>&1 &`

Previous PR fixed issue #52790, but kept the calling process alive, as noted in comment https://github.com/laravel/framework/pull/52807#issuecomment-2353201474

This approach allows the command to be truly sent in the background without holding up an FPM worker until the deferred commands are executed

### Post Script

I noted the `Concurrency` component's `composer.json` file is missing `illuminate/support` in its `require` section. Also, the namespace on the PSR-4 autoload section is wrong.

https://github.com/laravel/framework/blob/79fbf4a983c147c3bdef0045fa93aa4d8594c151/src/Illuminate/Concurrency/composer.json#L16-L25

Instead of modifying it in this PR, or sending it as a new PR, I made comments to PR #52801 which is refactoring some related classes.

### CODE REVIEW

**Comment by rodrigopedra** [comment]
I tested with this modified code from issue #52790 

```php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Concurrency;
use Illuminate\Support\Sleep;

Artisan::command('testing', function (): void {
    Concurrency::defer(function () {
        Sleep::for(3)->seconds();
        info('a');
    });

    $this->info('b');
});
```

And it works perfectly. 

The calling artisan command ends, returns to the prompt, and then 10 seconds later the deferred process writes to the log, as originally expected.

**Comment by hafezdivandari** [comment]
You may use `Illuminate\Console\Application::formatCommandString()`

https://github.com/laravel/framework/blob/79fbf4a983c147c3bdef0045fa93aa4d8594c151/src/Illuminate/Console/Application.php#L100-L109

**Comment by rodrigopedra** [comment]
Also tested with this route:

```php
<?php

use Illuminate\Support\Facades\Concurrency;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Sleep;

Route::get('/', function () {
    Concurrency::defer(function () {
        Sleep::for(3)->seconds();
        \info('a');
    });

    return 'b';
});
```

On a nginx/PHP-FPM process, and it also executes as expected.

**Comment by rodrigopedra** [comment]
@hafezdivandari I thought on using it, but I feared adding a new dependency to the `Concurrency` component's `composer.json`.

Although IMO, we could centralize all these calls somewhere, maybe on the `Support` component which already has a `ProcessUtils` class.

**Comment by hafezdivandari** [comment]
@rodrigopedra https://github.com/laravel/framework/pull/52744#issuecomment-2344978337

**Comment by rodrigopedra** [comment]
@hafezdivandari done!

Thanks for reviewing it =)

**Pull request merged**
