### PR TITLE
[5.1] Security Related Improvements

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by franzliedke** [comment]
Can you explain these a bit more, since they're security related?

**Comment by GrahamCampbell** [comment]
Sure. Give me a sec to write this up. :)

**Comment by GrahamCampbell** [comment]
Ok, first of all, Taylor and I have decided that symfony's random bytes function isn't so secure because it falls back to a less secure implementation if openssl isn't available, so all I've done here is simply abstract our random bytes implementation from our random function, which is basically identical to symfony's, only without the less secure fallback.

The second change here is to copy over symfony's timing-safe equals function, and remove their check for "does mb_strlen exist", since its already a dependency, so we know it does. This allows us to not depend on symfony's security package anymore. This is useful because it was relatively large for what it actually did for us, especially considering we were forcing lumen users into requiring it. I will always be keeping an eye on symfony's timing-safe comparison implementation, so if it changes, we'll update.

There is one final advantage to ditching symfony's security component, is that it allows us to make security fixes to our implementations in the future where this was not possible with symfony. Take for example we find an issue with timing-safe in 3 year's time, and we want to patch all laravel versions from 5.1 upwards, if we don't make this change, we can't, because we'd be using an unsupported version of symfony 5.2 and 5.3, etc, so they'll never be making the security fix, but we, however, are free to do so.

**Comment by franzliedke** [comment]
Okay, cool, thank you!

**Pull request merged**
