### PR TITLE
[9.x] Add SQL Parentheses for whereRaw in order to use SoftDelete safely

### PR DESCRIPTION
**Pull request by cocoeyes02**
refs: [#2384](https://github.com/laravel/ideas/issues/2384)

### CODE REVIEW

**Comment by mfn** [comment]
So the idea of your problem with operator precedence ("or" vs "and") is to always wrap the where in parenthesis?

Might be a stretch, but maybe people rely on this. You're effectively changing the _literal_ raw query the user provided, which does not sound like a good idea.

---
I can see your problem though, it's absolutely clear that there an existing where condition applied with interferes with your expectation of operator precedence. But OTOH, it has to be clear that there are additional where conditions, otherwise the trait wouldn't make sense.

Personally, if others agree there's something to fix, it should be done only in this context. But I think the proper "fix" is to maybe improve the docs.

IMHO 😄

**Comment by cocoeyes02** [comment]
IMO, people don't always read document. So if possible, I want enable people to use SoftDelete safely if people don't read document.

But OTOH, I think I don't wanna make destructive change. If it affects another feature, I'll close this PR and I'll improve the docs.

**Comment by taylorotwell** [comment]
I dunno if I feel comfortable modifying the raw query.

**Comment by cocoeyes02** [comment]
ok, I'll improve the docs.

**Pull request closed without merging**
