### PR TITLE
[9.x] Allow Eloquent `Builder@withCount` to apply constraints on Relation

### PR DESCRIPTION
**Pull request by cosmastech**
https://github.com/laravel/framework/issues/46633

Not sure if this is a breaking change, but targeting 9.x as I believe it's a bug.

Say that SomeModel has a BelongsToMany relationship. Previously, if you passed a constrained relationship to withCount(), it would always pass an Eloquent\Builder instance as the first parameter to the closure. With this change, it should pass the Relation (HasMany, HasOne, MorphTo) instead.

```php
SomeModel::query()->withCount([
    'related_model' => fn (BelongsToMany $query) => $query->wherePivotNull('some_pivot_column'),
])->get();
```

Previously, this would've thrown an exception for the closure expecting `BelongsToMany`. Assuming you did not add a type hint, the Builder instance would've handled the constraint like `$query->where('pivot_null', 'some_pivot_column')`.

### CODE REVIEW

**Comment by cosmastech** [comment]
It looks like the pipelines are failing because of a docker connection issue.

Is there anything I should do as a contributor when this happens? It doesn't look like I can manually trigger them, so the only other thing would be a force push.

**Comment by driesvints** [comment]
@cosmastech I retriggered the build for you.

Also want to thank you for recent PRs you made 👍

**Comment by cosmastech** [comment]
> @cosmastech I retriggered the build for you.
> 
> Also want to thank you for recent PRs you made 👍

It does bring me pleasure to imagine the eye roll you and Taylor give when you see another PR submitted by me. 😆 

Thank you all for maintaining this framework and associated packages.

**Comment by cosmastech** [comment]
It looks like [the docs indicate that the closure should expect a Builder](https://github.com/laravel/docs/blob/10.x/eloquent-relationships.md?plain=1#L1449) instance as the first parameter.

I personally think there's benefit to giving access to the Relation rather than a Builder instance, so maybe this could target 11.x?

**Comment by Mastacow** [comment]
Don't forget to send an invoice to Tyler for doing work on this framework. As it is sponsored and makes money. You deserve to be paid for your work.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
