### PR TITLE
[5.9] Config option to allow caching of null values

### PR DESCRIPTION
**Pull request by cvsouth**

### CODE REVIEW

**Comment by laurencei** [comment]
@cvsouth - you need to put a detailed explanation of what this PR actually does (beyond the title in your PR), and the reasons why you think this belongs in the Laravel core.

Otherwise it is unlikely to be accepted by Taylor when he sees this, and your PR will be closed.

**Comment by halaei** [comment]
It is a limitation of Laravel cache that you are not supposed to cache null at all. IMO that is fine, because you can wrap a nullable value in an array or do something similar:
```php
Cache::forever('test', [$nullable]);
Cache::forever('test', $nullable ?? false);
```

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by driesvints** [comment]
Laravel's cache implementation conforms to PSR-16. `null` values can already be stored right now with Laravel's cache implementation. The fact that you always get back false for `null` values is due to the following:

> The null value (although it will not be distinguishable from a cache miss when reading it back out).

See https://www.php-fig.org/psr/psr-16/#14-data

**Comment by cvsouth** [comment]
Hi @taylorotwell, @driesvints, @halaei and @laurencei.

I've read over PSR-16 and see that it does indeed say for a null value to be indistinguishable from a cache miss. I created the package `cvsouth/cache-null` which enables support for caching null values.

https://github.com/cvsouth/cache-null 

Without the package we can wrap the nullable value in an array or convert it to false but while that is annoying I think the issue is broader as developers that make the mistake of thinking they can cache null values may not get any type of Exception or unexpected behaviour. Methods like `remember` and `rememberForever` simply recalculate the value every time null was previously stored instead.

**Pull request closed without merging**
