### PR TITLE
[5.6] soft delete $joins issue fixed for PHP7.2

### LINKED ISSUE #22162: SoftDelete trait throws PHP error with PHP7.2
- Laravel Version: 5.1.46
- PHP Version: 7.2.0RC6
- Database Driver & Version: pgsql

### Description:

Using the SoftDelete trait on a model when using PHP 7.2 throws an internal error because of the usage of `count` in the `SoftDeletingScope` on line 75. The property `joins` isn't always an array and results in a call of `count(null)`.

Updating line 92 of `Illuminate/Database/Query/Builder.php` to

```php
    /**
     * The table joins for the query.
     *
     * @var array
     */
    public $joins = [];
```

is enough to stop the error from happening, although it looks like there are multiple other properties in the class that should be updated in a similar way to prevent this error from happening elsewhere.

### Steps To Reproduce:

* Install a version of PHP 7.2
* Create a model that implements `SoftDeletes`
* Attempt to delete an instance of the model
* Notice the error `count(): Parameter must be an array or an object that implements Countable`

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Fixes #22162

### CODE REVIEW

**Comment by paulofreitas** [comment]
@Dylan-DPC See https://github.com/laravel/framework/issues/22162#issuecomment-346275696. 😉

**Comment by Dylan-DPC** [comment]
Damn. Wouldn't this be a better way of fixing it rather than typecasting it to array everywhere else?

**Comment by Dylan-DPC** [comment]
Closing since this has already been fixed

**Comment by paulofreitas** [comment]
> Damn. Wouldn't this be a better way of fixing it rather than typecasting it to array everywhere else?

Maybe this would be desirable, but it would require more changes - this single line change was breaking 5 tests. There are also other attributes in this class that would require the same refactoring. We've found here that there's at least a room for improvement in the docblocks of these attributes. 😄

**Comment by Dylan-DPC** [comment]
> but it would require more changes 

How?

**Comment by paulofreitas** [comment]
@Dylan-DPC This single change was changing the expected SQL code in a weird way: https://travis-ci.org/laravel/framework/jobs/305658674 Look that there's an extra space in the generated SQL code in every failed test.

Those files/lines were being affected:

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php#L108
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Query/Grammars/SqlServerGrammar.php#L312
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Query/Grammars/Grammar.php#L723

**Comment by Dylan-DPC** [comment]
Oh yes true. We could change the `isset()` to empty check or something similar. But still way better than remembering to typecast all counts right?

**Comment by paulofreitas** [comment]
@Dylan-DPC Yep, there's a room for non-breaking improvements in all those attributes that are always handled as arrays. 👍  😉

**Pull request closed without merging**
