### PR TITLE
[5.2] Elixir helper should be wrapped in Blade comments

### PR DESCRIPTION
**Pull request by hiendv**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This was intebtionally changed, but I agree the change was wrong.

**Comment by hiendv** [comment]
The change can result in an error like
```
ErrorException in helpers.php line 294:
file_get_contents(../public/build/rev-manifest.json): failed to open stream: No such file or directory
```
Blade comment or none of these two lines, I think.

**Comment by GrahamCampbell** [comment]
Yeh, I know. That's why I'm agreeing with you. ;)

**Comment by GrahamCampbell** [comment]
Thank you very much for the contribution. :snowman:

**Comment by hiendv** [comment]
Despite the fact that I only changed a couple of characters, I'm very exicted to be one of the contributors of Laravel !

**Pull request merged**
