### PR TITLE
[8.x] Fix getDirty method when using `AsArrayObject` / `AsCollection`

### PR DESCRIPTION
**Pull request by gdebrauwer**
A less impactful version of #38774.

I updated the `originalIsEquivalent` method to make a custom comparison when the attribute uses `AsArrayObject` or `AsCollection` cast. This way, Eloquent will not think there is a difference if there are just some extra spaces in the original json string.

```php
// If you try to save this in a MySQL json column:
// {"foo":"bar"}
// Then MySQL will save it like this:
// {"foo": "bar"}

// This means that Eloquent currently thinks that a json value is changed
// because there is an extra space in the original value.
'{"foo": "bar"}' !== '{"foo":"bar"}'
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
@gdebrauwer can you revert all of those unrelated "$value" changes in the other cast files?

**Comment by gdebrauwer** [comment]
Those changes are necessary, otherwise, the wrong value will be cast. The castable class will just be casting the model's current value instead of the provided value

**Comment by taylorotwell** [comment]
@gdebrauwer In what situations would `$value` and `$attributes[$key]` be different values?

**Comment by gdebrauwer** [comment]
When you try to cast the original value, instead of the updated value

**Comment by taylorotwell** [comment]
@gdebrauwer is there a way to do this without recasting? Like just `json_encode(json_decode($foo))` so they are normalized? I still find it odd to pass the original attribute and the *current* attribute array in the same cast call.

**Comment by gdebrauwer** [comment]
Yeah that would work. I'll have a look tomorrow and update the PR 👌 

(regarding the attributes-array, honestly, I don't really know why that fourth parameter exists 😅)

**Comment by gdebrauwer** [comment]
@taylorotwell It now uses the existing `fromJson` method to cast the values to arrays so those arrays can be compared

**Comment by taylorotwell** [comment]
@gdebrauwer 

Are the `$value` changes in the cast files now able to be reverted?

**Comment by gdebrauwer** [comment]
Forgot about those 😅 I reverted those changes.

**Comment by taylorotwell** [comment]
Do you know if these changes work with `AsEncryptedArrayObject` and `AsEncryptedCollection`?

**Comment by gdebrauwer** [comment]
Those do not have the same issue, as the encrypted value will be saved in a string column instead of json column

**Comment by SachinAgarwal1337** [comment]
@taylorotwell @gdebrauwer 

This is breaking the default attributes logic. 
I have my default attributes set like this

```
protected $attributes = [
        'settings' => [
            'is_public' => true,
            'footer' => true,
        ],
    ];
```

and casting like this

```
 /**
     * @var array
     */
    protected $casts = [
        'settings' => AsArrayObject::class,
    ];
```

Before this update everything was working fine.
After update my tests start to break. Giving the following error
Screenshot 2021-10-01 at 17 23 37

**Comment by gdebrauwer** [comment]
I think you have to provide a json-encoded string as default value:

```php
protected $attributes = [
    'settings' => '{"is_public":true,"footer":true}'
];
```

The error is not caused by this change, because if you use the 'object' cast on that attribute for example, then you will have the same issue.

```php
protected $attributes = [
    'settings' => [
        'is_public' => true,
        'footer' => true,
    ],
];

protected $casts = [
    'settings' => 'object'
];

// this setup will also cause the json_decode error
```

The `$attributes` array should contain database-like values, which arrays are not.

**Comment by SachinAgarwal1337** [comment]
@gdebrauwer hmm... Interesting. 
But I can assure you it's working that way befor I updated to the version this change got released.
(I tested by downgrading the version)

I can update it to that json string.
But isn't this a breaking change?

Also I think the way it was working earlier seems right to me. 
It was applying the casting on default values defined in `$attributes`
Something to think about maybe?

**Comment by SachinAgarwal1337** [comment]
Also as you can see that column name is `settings` so its highly possible there may be like 10-15 keys there for settings. It wont be ideal to add the default value as json string. That will make it more difficult to maintain.
Again something to think about maybe?

**Comment by SachinAgarwal1337** [comment]
@taylorotwell hey, what do think about my comments? Any thoughts?

**Pull request merged**
