### PR TITLE
[10.x] ConstantAccessor (Trait)

### PR DESCRIPTION
**Pull request by rmunate**
Hi Engineer Taylor 👋,

I hope this message finds you well! 🌟 I wanted to bring a feature to your attention that I believe could enhance the overall experience.

## Introduction

The `ConstantAccessor` trait simplifies access to class constants in Laravel models, or any class for that matter. It has been seamlessly integrated into the abstract "Model" class, serving as the foundation for all model extensions. This integration simplifies direct access to constants in your models without requiring additional configuration, **especially when it is required to recover a constant dynamically**.

### Outside a Model

```php
$value = YourModel::constant('YOUR_CONSTANT_NAME');
```

### With any classes

```php
//import the use of Illuminate\Support\Traits\ConstantAccessor.

$constantName = 'CONSTANT_NAME';

$value = ClassName::constant($constantName);
```

This allows for consistent access to constants, both within and outside the model, providing a clean and unified approach.
Additionally, it remains a feature that can be used in any other class, controller, service, enum, etc. I think it would help a lot, **especially when it is required to recover a constant dynamically**.

### CODE REVIEW

**Comment by rmunate** [comment]
If the method name would potentially create conflicts due to the same name being used in a class method, we have aliases at our disposal for extreme cases.

```php
use \Illuminate\Support\Traits\ConstantAccessor {
    constant as getConstant;
}
```

In this situation, if there's ambiguity with the method name in the class, aliases provide a workaround. The provided PHP code demonstrates the use of an alias (`getConstant`) for the `constant` method from the `ConstantAccessor` trait.

**Comment by alejandrodiazpinilla** [comment]
Hello everyone,

I've recently been exploring the implementation of ConstantAccessor, and I believe it could be a valuable addition to Laravel. This feature significantly simplifies access to class constants, providing a more direct approach without additional configurations.

Currently, in Laravel, accessing class constants requires using the full syntax with the class name and constant, which can become cumbersome in some situations, especially when dynamically retrieving constants.

The integration of ConstantAccessor into the abstract class "Model" would be particularly beneficial. Not only would this streamline direct access to constants, but it would also align with Laravel's philosophy of making development faster and cleaner.

I would appreciate it if this could be implemented soon 👍 

Thank you!

**Comment by rmunate** [comment]
Other example:

#### MathConstants Class

```php
// MathConstants.php

class MathConstants
{
    use \Illuminate\Support\Traits\ConstantAccessor;

    const PI = 3.14159;
    const EULER_NUMBER = 2.71828;
    const GOLDEN_RATIO = 1.61803;
    const SQUARE_ROOT_2 = 1.41421;
}
```

Now, you can dynamically access constants from `MathConstants` using a loop without a try-catch block:

```php
// Dynamic usage of ConstantAccessor in a loop

$constantsToRetrieve = ['PI', 'EULER_NUMBER', 'GOLDEN_RATIO', 'SQUARE_ROOT_2'];

foreach ($constantsToRetrieve as $constantName) {
    $constantValue = MathConstants::constant($constantName);
    echo "$constantName: $constantValue\n";
}
```

This example dynamically retrieves constants from the `MathConstants` class using a loop.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by rmunate** [comment]
@taylorotwell . Surely the fact of having included it in the 'Model' class could have caused him doubts, however this is something really useful and very convenient, before deleting the branch and forgetting this PR I would like to contemplate leaving it as a feature for use at the discretion of the developer.

**Comment by alejandrodiazpinilla** [comment]
Hi @taylorotwell 

I understand the importance of maintaining the integrity of the framework. I would like to present some additional arguments regarding the relevance and benefits of the proposed functionality:

**Uniqueness and Simplicity:**

The functionality provided by the ConstantAccessor trait addresses a specific need and offers a simple and elegant solution. Introducing an additional package might be unnecessary and could increase complexity for users.

**Consistency with the Framework:**

The trait has been designed to seamlessly integrate with the Laravel architecture, providing direct access. This aligns with Laravel's philosophy of making development more accessible and consistent.

**Community Benefit:**

By including this functionality in the core of Laravel, the entire community would benefit. Removing the need for an external package simplifies development for users and maintains cohesion within the Laravel ecosystem.

Thank you for your time and consideration!

**Comment by rmunate** [comment]
> Thanks for your pull request to Laravel!
> 
> Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include.
> 
> If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions!
> 
> If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

@taylorotwell . Surely the fact of having included it in the 'Model' class could have caused him doubts, however this is something really useful and very convenient, before deleting the branch and forgetting this PR I would like to contemplate leaving it as a feature for use at the discretion of the developer. Leaving it alone as a trait and removing it from the abstract class 'Model'

Before
```php
$class = new ReflectionClass(ClassName::class);
$constantValue = constant("$class->getShortName()::$constantName");
```
Now
```php
$constantValue =  ClassName::constant($constantName);
```

**Pull request closed without merging**
