### PR TITLE
[5.7] Added alkhachatryan/encryptable package to Laravel framework composer.json

### PR DESCRIPTION
**Pull request by alkhachatryan**
Hi. I developed a small trait, which will help us to encrypt the database and have the records there in encrypted way, using this class: Illuminate\Support\Facades\Crypt.

I have two methods in trait: first for encrypt and the second one for decrypt.

To encrypt the column in the model, developer should add the column name in the model property $encryptable

`
$this->encryptable = ['name', 'email'];
`

I tested this package on Laravel 5.4, 5.5, 5.6, and 5.7. If I did something wrong, let me know, please.

### CODE REVIEW

**Comment by koenhoeijmakers** [comment]
Packages are not to be merged into the core framework, or did you mean to make this available to the framework?

**Comment by alkhachatryan** [comment]
> Packages are not to be merged into the core framework, or did you mean to make this available to the framework?

Yes. Actually this is my first pull request to the Laravel core. In one word, I want that Laravel have this package for 5.8 and newer versions. Like a particle of a Laravel core. If I did something wrong, let me know please.

**Comment by pavinthan** [comment]
@alkhachatryan why do you use third party ( `alkhachatryan/encryptable ` ) package to use Laravel build in feature

**Comment by alkhachatryan** [comment]
> @alkhachatryan why do you use third party ( `alkhachatryan/encryptable` ) package to use Laravel build in feature?
> 
> You could use `alkhachatryan/encryptable` package using composer instance of adding into `Illuminate`
> 
> `NULL` values throw exception in your `Encryptable` trait

I got you. As I mentioned above, this is my first pull request to some core. 

Any way thank you for your suggestion and reaction. I'll do a commit now.

**Comment by alkhachatryan** [comment]
I removed the files from the core dir and added in the composer.json as you advised.
Also added condition for checking for NULL value in each set and get methods.

**Comment by alkhachatryan** [comment]
@taylorotwell can you let me know, please, what I did wrong? I'm not sure is everything ok?

**Comment by driesvints** [comment]
Hey @alkhachatryan. You can use this package in your own app if you like.

**Comment by shreyanshpanchal** [comment]
@alkhachatryan You've implemented this feature "encryptable database". 
If you want this feature to be useful in any Laravel application. 
You can follow this guide [Laravel Package Developement](https://laravel.com/docs/5.7/packages.)

It includes:
- Creating a new github repo for your package
- Adding it to packagist

Now, anyone can install your package into their laravel application by running `composer install alkhachatryan/encryptable`.

You need not to send PR into this repository, As this is an additional feature, It does not need to be a part of core ecosystem. Now why is that? (Because let's assume that this feature is not common enough that everyone will want to use it in their application & therefore shouldn't be part of core.) 

You can also take a look at wide array of packages developed by [Spatie](https://github.com/search?q=spatie), Which are not part of core but they're installed & used ever so frequently.

Please close this issue if i was of some help.
Have a great day.

**Pull request closed without merging**
