### PR TITLE
[5.4] Add @dump() blade directive

### PR DESCRIPTION
**Pull request by calebporzio**
I have a personal custom blade directive called @dump()

I think it would be handy in the core. Similar to $browser->dump() and things like that.

I originally called it @dd, but decided to go with @dump - I'm personally fine with either.

### CODE REVIEW

**Comment by a-komarev** [comment]
If it's `@dump` why it's calling `dd()`? :}

**Comment by browner12** [comment]
isn't it just as quick to write `{{ dd($var) }}`?

**Comment by decadence** [comment]
Better to use dump than dd. And it was rejected already before.

**Comment by decadence** [comment]
And directive is called `dump` but calls `dd` behind the scenes. A little inconsistent.

**Comment by calebporzio** [comment]
aaah k, couldn't find any previous PRs for this at first glance.

I don't like `{{ dd() }}` because I would never write `echo dd()` -> it feels off to me.

I'm not sure I can verbalize why I went with @dump - but it reads better to me. Like: dd() is the helper function we all know about and "dump" is when you want to achieve a similar effect in a different context.

**Comment by taylorotwell** [comment]
You can just echo it :smile:

**Pull request closed without merging**
