### PR TITLE
__isset must return true in Request.php

### PR DESCRIPTION
**Pull request by shatilov**
The __get method does not return an exception so any property can be obtained

### CODE REVIEW

**Comment by mpyw** [comment]
Undefined parameters seems to be handled as `null` without triggering errors or exceptions. It's for our convenience. 

...BTW, do you know PHP's native `isset()` returns `false` not only for undefined values but also for existing `null` value?

**Comment by shatilov** [comment]
in twig: {{ request.var }} - generate exception (because twig check it) if var not defined in parameters. and I have to handle this.
And for our convenience i want to __ isset has return true anywhere - In my opinion its fast way for render

**Comment by ntzm** [comment]
But it's not set. Just check if it's defined before echoing it out?

**Comment by shatilov** [comment]
I do not insist, it just seemed to me more convenient.
-- just check? - It's easier to create custom request class with defined vars and getters.

thanks.

**Comment by mpyw** [comment]
Why don't you use modern Blade instead of legacy Twig?

**Comment by shatilov** [comment]
because my project on symfony )

**Pull request closed without merging**
