### PR TITLE
[5.2] Fixed phpdoc and condensed logic

### PR DESCRIPTION
**Pull request by GrahamCampbell**
The logic condensing was done by first replacing the two unneededly different exists checks, then using distributivity and de morgan laws to condense it.

### CODE REVIEW

**Comment by donnysim** [comment]
Isset would have one problem, if you add a test:

```
$array = ['products' => ['desk' => null]];
$value = Arr::get($array, 'products.desk', false);
$this->assertNull($value);
```

the test would fail with `isset` because the result would be `false` yet the key exists with the value of `null`.

**Comment by GrahamCampbell** [comment]
We already have that issue everywhere then?

**Comment by donnysim** [comment]
If we take it then yes, there's quite some places where it would fail such test, like `data_get` helper etc.. Though I guess the need for null value is almost none. 

And I noticed `has` should be updated in the same way `get` was :\

**Comment by taylorotwell** [comment]
Kind of looks like change in behavior to me.

**Comment by vlakoff** [comment]
Indeed, `Arr::has()` should be made consistent with `Arr::get()`.

**Pull request closed without merging**
