### PR TITLE
[5.7] A cache key that can be used to identify a model

### PR DESCRIPTION
**Pull request by paulredmond**
Based on [ActiveRecord](https://github.com/rails/rails/blob/15ef55efb591e5379486ccf53dd3e13f416564f6/activerecord/lib/active_record/integration.rb#L64), adds a `Model::cacheKey()` method that gets a stable cache key used to identify a model.

This can be used to build model cache that gets invalidated:

```php
class Article extends Model
{
    public function getCachedCommentsCountAttribute()
    {
        return Cache::rememberForever($this->cacheKey() . ':comments_count', function () {
            return $this->comments->count();
        });
    }
}
```

The `cacheKey()` method would produce the following if the model had the `updated_at` date attribute:

```
articles/1-1515693922
```

Models without an `updated_at`:

```
articles/1
```

New models:

```
articles/new
```

For more info, I [wrote about it](https://laravel-news.com/laravel-model-caching) using `Model::touch()` to invalidate cache on a model.

### CODE REVIEW

**Comment by dwightwatson** [comment]
Just read your post this morning - I enjoyed the Rails influence. However I feel that caching models that haven't been persisted yet as just `new` could be problematic - it would be far too easy to clash. Would it be fair to throw an exception if you request a cache key for a model that isn't persisted? I suspect returning an empty string or `null` is ripe for confusion as well.

**Comment by sisve** [comment]
If this is just a new method without any actual integration in the framework ... why should it be part of the framework and not your own base model class?

**Comment by paulredmond** [comment]
@dwightwatson thanks, you can think of `new` as similar to `noop` as caching a new model is something you would never want to do. The method doesn't prohibit the user from calling `cacheKey()` on a new model though, as that would make the code overly complicated IMHO.

**Comment by GrahamCampbell** [comment]
5.6 is probably a better target for this PR than master. :)

**Comment by paulredmond** [comment]
> 5.6 is probably a better target for this PR than master. :)

Thanks @GrahamCampbell, I will get it moved over.

**Comment by taylorotwell** [comment]
Yes, please submit to 5.6.

**Pull request closed without merging**
