### PR TITLE
[5.5] Fix task scheduler quarterly() method

### PR DESCRIPTION
**Pull request by m1guelpf**
Fix https://github.com/laravel/framework/issues/19532 using [@dragonmantank's suggestion](https://github.com/laravel/framework/issues/19532#issuecomment-308488946).

### CODE REVIEW

**Comment by themsaid** [comment]
Just want to share that this is a breaking change, some people might consider the current behaviour as correct and changing it now would break their apps so I suggest that we submit this to 5.5 and in your own app you can use the `cron()` method to pass the expression suggested here until you upgrade to 5.5 upon release.

**Comment by m1guelpf** [comment]
@themsaid Moved to master

**Comment by decadence** [comment]
Then it's worth waiting for fix in original library and don't change anything in Laravel.

**Comment by decadence** [comment]
By the way I don't see how it's breaking change if it fixes a bug. Of course it triggers behaviour change.

**Comment by themsaid** [comment]
> behaviour change

This might cause people to complain that their jobs are running in un-expected time, although it's the correct time but that's not how it was since 5.2. That's why it might be considered a breaking change.

**Comment by taylorotwell** [comment]
To me this isn't really a "fix" because it is not defined anywhere what "quarterly" means in this context. Some people will want it the old way and some people will want it this suggested way.

**Comment by taylorotwell** [comment]
After reading the issue, I do agree this is probably the more expected behavior of quarterly.

**Comment by decadence** [comment]
Thanks. I'm glad my investigation was not in vain.

**Comment by m1guelpf** [comment]
@taylorotwell 
> After reading the issue, I do agree this is probably the more expected behavior of quarterly.

Then, is this still considered breaking, or can I do another PR to the 5.4 branch?

**Pull request merged**
