### PR TITLE
[5.3] Move base64 decoding to the config component

### PR DESCRIPTION
**Pull request by GrahamCampbell**
I've included the commits from #13291 first, to get this to pass.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I don't think we want to add this check to every single configuration retrieval? :/

**Comment by GrahamCampbell** [comment]
I think it's ok?

**Comment by GrahamCampbell** [comment]
Alternatively, I have got another idea...

**Comment by taylorotwell** [comment]
Will wait on other idea heh

**Comment by GrahamCampbell** [comment]
kk ;)

**Pull request closed without merging**
