### PR TITLE
[5.8] Backport PHP 7.4 Support

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmm, well Symfony 4.2 just isn't ever going to be patched for PHP 7.4 I don't think...

**Comment by driesvints** [comment]
I don't think we should touch the versions for 5.8 and that we should only test 7.4snapshot on the latest releases, not the lowest ones.

**Comment by GrahamCampbell** [comment]
Yeh, I agree.

**Comment by GrahamCampbell** [comment]
Right. Give me a minute. :P

**Pull request merged**
