### PR TITLE
[5.7] Unzip serialized attribute

### PR DESCRIPTION
**Pull request by meteguerlek**
```php 
$model =  new Model([
     'foo' => 'bar',
     'data' => serialize(['bar' => 'foo'])
]);
```

screenshot_1

```php 
$model->unzip('data');
```

screenshot_2

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I think unzip is the wrong word perhapse. Makes me think of:

```hs
unzip :: [(a,b)] -> ([a],[b])
```

**Comment by meteguerlek** [comment]
@GrahamCampbell Maybe unlara :). unserializeAttribute..

**Comment by laurencei** [comment]
Wouldnt this make more sense as a `cast`?

i.e. we can already cast to `array` - so why not also cast to `serialize`?

But that then begs the question of what `serialize` gives over `array` for storing in a database, and if we need it at all?

**Comment by meteguerlek** [comment]
First add some test attributes...
```php
$model =  new Model([
     'foo' => 'bar',
     'data' => serialize(['bar' => 'foo'])
]);
```
fill

Unzip
```php
$model->unzip('data');
```
unzip

Unzip here
```php
$model->unzip('data', true);
```
unzip here

Unzip to
```php
$model->unzip('data', false, 'serialized');
```
unzip to

**Pull request closed without merging**
