### PR TITLE
[9.x] Use PSR container interface instead of Laravel contract

### PR DESCRIPTION
**Pull request by BafS**
We are using the Laravel contract but we could use a more precise (Interface segregation principle) and flexible interface (PSR is widely used).

(https://github.com/laravel/framework/pull/35013 but target for master)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Doesn't get return null on failure? Do we need to check for that now?

**Comment by BafS** [comment]
That's the logic in the container, it does throw an exception, the difference is that it will throw `EntryNotFoundException` if the service is not found.

```php
    public function get($id)
    {
        try {
            return $this->resolve($id);
        } catch (Exception $e) {
            if ($this->has($id)) {
                throw $e;
            }

            throw new EntryNotFoundException($id, $e->getCode(), $e);
        }
    }
```

To compare, `make` is just calling `resolve`.

```php
    public function make($abstract, array $parameters = [])
    {
        return $this->resolve($abstract, $parameters);
    }
```

**Comment by GrahamCampbell** [comment]
Ah, thanks for explaining. Looks like no changes are required, then. :)

**Comment by rodrigopedra** [comment]
Isn't the container contract used on other parts of the framework?

From a quick search I found that `Illuminate\Auth\Access\Gate` uses a container just to instantiate a policy.

https://github.com/laravel/framework/blob/9ed06e87690c624ed64660d2a17bf3ecafcf8790/src/Illuminate/Auth/Access/Gate.php#L627-L638

Maybe this PR should review all usages within the framework to see if its worth the change?

I guess it could beneficial for components that can be used outside of the framework. In other words, don't mind checking the usage within the `Illuminate\Foundation` folder.

**Comment by taylorotwell** [comment]
Zero benefit to end users.

**Comment by BafS** [comment]
@taylorotwell I use this component with another container, yes zero benefit for Laravel fullstack users but also zero drawbacks for them. Why not considering this PR ?

**Comment by selcukcukur** [comment]
@BafS I guess some factors are the reason you didn't want to switch to this order. 
- Laravel ContainerInterface allows us to both create and control with "make()".
- However, PSR Container does not allow this to be provided. It requires a separate effort.

When this is the case, it is not beneficial to apply it in this way.

**Comment by BafS** [comment]
@selcukcukur I'm sorry but what you are saying doesn't make sense. I'm not saying we should replace the container with a "PSR only" one, but we should use the most specific interface when possible. Like Taylor said, there is no benefit on the fullstack part but it's a good practice and it help to decouple the code which make it easier to use it as a component.

> no client should be forced to depend on methods it does not use
https://en.wikipedia.org/wiki/Interface_segregation_principle

Unfortunately I don't understand what is the rational not to decouple components when there is no impacts for framework users.

**Comment by BafS** [comment]
Still waiting for potential rationals behind this choice. I wanted to use Illuminate's Event system without Laravel containers.

**Pull request closed without merging**
