### PR TITLE
[10.x] Add job timeout occurred event

### PR DESCRIPTION
**Pull request by saeedhosseiinii**
No event is dispatched when timeout occurss, so there is no way for external packages to know about it. With this pr, this is possible

### CODE REVIEW

**Comment by nunomaduro** [comment]
Thanks for your contribution to Laravel! Would you be willing to include some tests in this pull request?

**Comment by saeedhosseiinii** [comment]
> Thanks for your contribution to Laravel! Would you be willing to include some tests in this pull request?

To test when the timeout occurred, the process is killed, so the assertion cannot be checked.
To prevent the process from being killed if the kill method of the Worker class is overridden, the Job Processed event is dispatched , but this event is not dispatched in the real scenario.
Is there another way to test?

**Comment by nunomaduro** [comment]
@saeedhosseiinii No problem. Testing something as simple as this could be complicated and not worth the hassle. Therefore, let's have Taylor reviewing the pull request without tests.

**Review by nunomaduro — APPROVED** [review]

**Comment by taylorotwell** [comment]
You can register an exception handler (ExceptionHandler::reportable method) to handle the new `TimeoutExceededException` exception. You can do this from your package's service provider.

**Comment by saeedhosseiinii** [comment]
> You can register an exception handler (ExceptionHandler::reportable method) to handle the new `TimeoutExceededException` exception. You can do this from your package's service provider.

This exception only occurs in the JobFailed event and when the job fails.
Consider that I set 5 attempts to the job and timeout occurred on the first attempt. After that the worker is killed and there is no way to know the timeout exception occured!

**Pull request merged**
