### PR TITLE
[5.6] add withSum to framework

### PR DESCRIPTION
**Pull request by spyp**
check it out. in the past people try to add withSum withAvg and ...
and they try to extends the withCount method but i think this methods should be separate because in these methods we play with specific column but in withCount * is enough for that 
i test it if you see this is useful add withAvg and etc because im not pro to do that. withSum is useful in 
analyze funds and ...

### CODE REVIEW

**Comment by deleugpn** [comment]
Missing tests, but it's indeed one of the features I miss the most in the framework.

**Comment by spyp** [comment]
mm simple test
`Operators::withSum('internet','amount')->get()`:
for simple and with conditions
`Operators::withSum(['internet'=>function($query){
....
}]
,'amount')->get()`:
hope this feature added to laravel for now its working and my problem solved but of course . you should check it .

**Comment by decadence** [comment]
Not a chance it will be merged without tests.

**Comment by deleugpn** [comment]
@decadence Agreed, but if there's a positive feedback, I can pick this up, write the tests and re-propose if the author can't write it.

@spyp I was talking about automation tests. Inside the framework there's a folder [tests](https://github.com/laravel/framework/tree/5.6/tests) containing automation tests for every feature the framework offers. A feature like this requires test-code for quality purposes and to avoid other people from proposing changes that break it's functionality.

**Comment by spyp** [comment]
@deleugpn 
i can write test but im not sure i create good coding . so if other peoples like this you test it and check my code its complicated and maybe i have mistake on that.
thanks

**Comment by decadence** [comment]
@deleugpn as far as I remember there was positive feedback on these PRs but they all missed proper tests which satisfy @taylorotwell. Anyway this is needed and would be cool if you can write them.

Ref:
https://github.com/laravel/framework/pull/16815
https://github.com/laravel/framework/pull/18303
https://github.com/laravel/framework/pull/19363

**Comment by spyp** [comment]
i will added and update here :)

**Comment by deleugpn** [comment]
Hey spyp, it's better if you add integration tests (tests/integration) instead of unit tests for this kind of feature.
It's good to have an automation process that checks if the code works against a real database because it's possible that the assertion passes but the query is incorrect. 
They are pretty easy to write as well and you get to make assertion on real values.

**Comment by spyp** [comment]
ok i'll add real database too.

**Comment by taylorotwell** [comment]
I don't see a big point in adding functions like getRelationshipSumQuery. It feels like it should be generalized to handle all aggregates. Not just sum.

**Comment by spyp** [comment]
you are right. i will  try to add other aggregates  too .

**Pull request closed without merging**
