### PR TITLE
[5.6] Add @hidden Blade directive

### PR DESCRIPTION
**Pull request by dodyagung**
`@hidden('foo', 'bar')` will be translated into `<input type="hidden" name="foo" value="bar">`

### CODE REVIEW

**Comment by m1guelpf** [comment]
I'd say no to this. Some blade helpers like @csrf or @method are useful, but if we have a blade directive for every HTML tag then we're back to the old Form helpers, and they were removed for a good reason. You'll probably find a package that already offers this, or you can create a new one.

**Comment by browner12** [comment]
I am personally in the anti-blade helpers camp, and think even `@csrf` and `@method` are overkill, so I'm definitely not for this one either.

learn to love your Live Templates / Snippets / etc

**Comment by devcircus** [comment]
I used to be against all of these blade helpers that save a few keystrokes but there's so many in the core now, I've given up. If it gets merged, I'm sure I'll end up using it eventually.

**Comment by decadence** [comment]
Reinventing Html/Form package

**Comment by dpde** [comment]
I don't think this is a good idea.
If you really need this, have a look at https://laravelcollective.com/docs/master/html

**Comment by browner12** [comment]
BTW @dodyagung we don't mean to pile on you.  Thanks for submitting the PR and trying to better the FW

**Pull request closed without merging**
