### PR TITLE
[9.x] Remove DocBlocks from Facades

### PR DESCRIPTION
**Pull request by driesvints**
This removes all DocBlocks on Facades in favor of using a package like Laravel IDE Helper Generator: https://github.com/barryvdh/laravel-ide-helper

Goes along with https://github.com/laravel/laravel/pull/5562

### CODE REVIEW

**Comment by barryvdh** [comment]
Hmm, I'm not 100% sure about this. What is the reasoning to remove them? The maintenance burden of keeping them updated? Wouldn't it still help people NOT using the IDE helper?

**Comment by driesvints** [comment]
Yes the maintenance burden and all the PRs we get about them. There's perfectly valid packages like yours that can generate these. We're also considering bringing it into the skeleton so people still have them out of the box: https://github.com/laravel/laravel/pull/5562

**Comment by SjorsO** [comment]
Aren't these docblocks necessary even when using IDE helpers? I use the IDE helpers and facade methods that aren't in the docblock aren't autocompleted by PHPStorm (else I wouldn't have made PR https://github.com/laravel/framework/pull/36366, for example)

**Comment by driesvints** [comment]
@SjorsO no they're not

**Comment by SjorsO** [comment]
> @SjorsO no they're not

image
image

Are you sure? Doesn't seem to work for me when I remove the phpdoc from the facade

**Comment by driesvints** [comment]
@SjorsO seems like a bug in ide-helper to me? @barryvdh

**Comment by netpok** [comment]
It needs to be turned on in the config by setting `include_class_docblocks` to `true`

**Comment by netpok** [comment]
It needs to be turned on in the config by setting `include_class_docblocks` to `true`

**Comment by SjorsO** [comment]
> It needs to be turned on in the config by setting `include_class_docblocks` to `true`

Just tried, this works. Big config file though...

**Comment by foremtehan** [comment]
Dont do this man! i dont want to install this package! I'm fine with facades without this pacakges in phpstorm!

**Comment by netpok** [comment]
It is a dependency in the application itself so you can remove it any time from your already tracked composer file.

**Comment by mfn** [comment]
👍 for ide-helper (the _other_ PR)

👎 for removing phpdoc on the Facades

- not every uses / wants to use ide-helper
- projects using the illuminate/* packages directly might have a hard time getting ide-helper run, if at all
- whilst it's a chore to maintain them (but hey, there's a community doing that anyway), it creates a great experience for any IDE out of the box
- also because of this, mentioned by @foremtehan 
  > Also it creates multiple unwanted classes for each models and when you click on one of the models it asks every time which definition you want to go...

**Comment by driesvints** [comment]
> projects using the illuminate/* packages directly might have a hard time getting ide-helper run, if at all

That's not really an argument I think because you wouldn't be using Facades without the framework anyway?

For all the rest: I definitely understand the concerns but you have to keep in mind that "whilst it's a chore to maintain them" still requires us to put in time into these no matter how much the community helps out. We're just looking for a way that everyone can benefit.

**Comment by foremtehan** [comment]
Last from me, If for any reason you want to merge this PR dont remove `@see` meta tag it might helps IDEs to look into another class to fetch data for auto completion (i dont know why `@see` it's not enough for phpstorm)

**Comment by mfn** [comment]
> That's not really an argument I think because you wouldn't be using Facades without the framework anyway?

I'm using `\Illuminate\Support\Facades\Date` via `illuminate/support` in a project without issues; maybe just a lucky coincident, but it works (but, yes, I'm using `illuminate/container` too)

**Comment by taylorotwell** [comment]
If we leave these doc-blocks (sounds like we are going to need to based on feedback so far), does the IDE helper file cause IDEs like PHPStorm to show two entries for every method in the facade?

**Comment by SjorsO** [comment]
> If we leave these doc-blocks (sounds like we are going to need to based on feedback so far), does the IDE helper file cause IDEs like PHPStorm to show two entries for every method in the facade?

No, with docblocks it only shows each method once. Keeping the docblocks has better results than removing them, see the screenshots below.

---

With docblocks, with ide helpers (`include_class_docblocks` true/false give the same results)
image
image

---

Without docblocks, with ide helpers (default config, `include_class_docblocks` = false)
image
image

---

Without docblocks, with ide helpers (`include_class_docblocks` = true)
image
image

**Comment by taylorotwell** [comment]
OK. I guess we will table this for now.

**Comment by tractorcow** [comment]
Rather than moving the facade generation to a generated _ide_helper.php file, why not generate them automatically against the facade classes? If the concern is that contributors forget to add these to the facades, we could run the same generation during github checks, and error in case of diffs. :)

If we run this in framework, and keep these files up to date, developers don't need to check out any extra dependencies just to maintain day to day quality of life.

**Pull request closed without merging**
