### PR TITLE
[5.1] Missing public methods from Events\Dispatcher to Contracts\Events\Dispatcher

### PR DESCRIPTION
**Pull request by guiwoda**
As with the `Router` / `Registrar`, I've added all missing methods.
Let me know if there's any changes needed, happy to help!

Cheers

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Again, please don't add ALL the methods.

**Comment by GrahamCampbell** [comment]
I think the first 3 methods are all that should be added to the contract.

**Comment by guiwoda** [comment]
I'll make a new PR, but same as with https://github.com/laravel/framework/pull/9131 this should be considered a bug and should be fixed.

**Comment by GrahamCampbell** [comment]
Please ONLY methods that are not getters/setters, methods that are not type hinted to return or accept something that's not in our contracts, and methods that are not deprecated.

**Comment by guiwoda** [comment]
@GrahamCampbell Anything regarding methods that hint throwing Symfony exceptions?

**Comment by GrahamCampbell** [comment]
Well, technically that stuff shouldn't be allowed in the contract. Maybe just omit that stuff from the contract and keep it in the implementation.

**Pull request closed without merging**
