### PR TITLE
11.x Adds “Storage Linked” to the artisan about command

### PR DESCRIPTION
**Pull request by adampatterson**
I've added a "Storage linked" item to the Environment section of the about command.

While helping some developers to debug why their media isn't displaying correctly, it is often a result of the storage folder not being linked.

I thought adding simple item to the about command would be a helpful addition.

Running `php artisan about` will show an item labeled "Storage Linked" with a value of **LINKED** or **NOT LINKED**.

### CODE REVIEW

**Comment by ahinkle** [comment]
Cool idea but the storage location can be configured in the `filesystems` configuration file and can contain multiple symbolic links. 

This PR is suggesting that we are trusting that it's not changed from the default configuration.

**Comment by adampatterson** [comment]
@ahinkle  I could check to see if the default is `local` and then confirm that all paths exist.

**Comment by taylorotwell** [comment]
See above. 👍 Not sure what best solution would be here... maybe a list of links - not really sure.

**Comment by adampatterson** [comment]
Thanks @taylorotwell, I'm working on an all paths if the file driver is local, then I'll show a new section and the status of each link.

**Pull request closed without merging**
