### PR TITLE
[5.0] Use environment file configured in the application to replace the app key

### PR DESCRIPTION
**Pull request by hannesvdvreken**
So you can do `php artisan key:generate` and it will always change the key in the env file you've setup in the bootstrap files, wether that's `.env` or `.env.behat` or whatever.

### CODE REVIEW

**Comment by lucasmichot** [comment]
:+1:

**Comment by TheShiftExchange** [comment]
I dont understand. You'll only be using `.env.behat` through a behat test - why do you need to generate a new key for it?

**Comment by TheShiftExchange** [comment]
I've made a new PR that would fix this issue (along with other ones) - https://github.com/laravel/framework/pull/7033

**Comment by taylorotwell** [comment]
@TheShiftExchange makes a good point.

**Comment by taylorotwell** [comment]
I'm just going to add a `--show` option and you can do whatever you want with the key. :smile:

**Pull request closed without merging**
