### PR TITLE
[5.6] Add air, sugar and water to $uncountable

### PR DESCRIPTION
**Pull request by PrismPrince**
This might be helpful for cooking sites. 😸

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Sugar is countable. eg How many sugars in you tea?

**Comment by abdumu** [comment]
@GrahamCampbell or emojis 🌿

**Comment by PrismPrince** [comment]
you can't say "3 sugars for your tea" but "3 sugar cubes" or "3 spoons of sugar", same as "2 glasses of water" not "2 waters"... get my idea? :)

**Comment by joshmanders** [comment]
what are you talking about, I take 3 sugars and 2 airs in my waters.

**Comment by devcircus** [comment]
Depends on context. When referring to types of sugar, sugars is the plural.

**Comment by PrismPrince** [comment]
i agree @devcircus , i think this ends here.. lol 😄👍

**Pull request closed without merging**
