### PR TITLE
[5.4] Test predis and phpredis

### PR DESCRIPTION
**Pull request by halaei**
Reopen and conflict resolve for https://github.com/laravel/framework/pull/17481

### CODE REVIEW

**Comment by halaei** [comment]
I think tests fails because we need to merge https://github.com/laravel/framework/pull/17485 first :(

**Comment by halaei** [comment]
The failure of time related tests shows that phpredis is slower that predis.
@tillkruss

**Comment by halaei** [comment]
@tillkruss Take that back. This does not mean phpredis is slower. The phpredis tests are done after predis!

**Comment by taylorotwell** [comment]
I don't really merge broken tests by themselves into the framework.

**Comment by halaei** [comment]
:D You really are mad at me. I will fix the situation ;)

**Comment by tillkruss** [comment]
@halaei: Just make sure all CI tests are green, otherwise PR's won't get merged.

**Comment by halaei** [comment]
I hope you know that the reason the tests failed is because there is a bug
somewhere else with or without this PR! And it is not my fault at all.

**Comment by halaei** [comment]
Think of this PR as a bug report

**Comment by tillkruss** [comment]
Okay, try opening a new PR that explains the bug, how to reproduce it and how your PR fixes the bug.

**Comment by halaei** [comment]
I try to free some time for that. But things are going too slow. All the
mess could have been cleared in half an hour of one person work. I also did
not expect a release today :(.

**Pull request closed without merging**
