### PR TITLE
[5.3] Make properties in the mailable class public 

### PR DESCRIPTION
**Pull request by sileence**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Breaking change?

**Comment by null9beta** [comment]
Like @GrahamCampbell mentioned this is breaking change but was introduced with a bugfix version. 

It actually cost me some time of my live now, thanks to our QA that error did not make it into production but was at lease giving us some hard time on staging :)

Actually it appeared between 5.3.28 and 5.3.29.

I guess it would be great if those changes in the future would be announced with a proper version jump.

Don´t get that wrong. I love Laravel but there is some serious businesses build behind it and those rely on that fact that bugfix and minor version shall not introduce BC´s.

**Comment by sileence** [comment]
@null9beta probably not the best place to talk about this, but can you tell more about the bug? Maybe there is something I can help with. You can also send me a message to sileence in Larachat.

**Comment by Jono20201** [comment]
This was also a breaking change for us.

**Pull request merged**
