### PR TITLE
[5.4] Added ability to use custom classes for pivot models

### PR DESCRIPTION
**Pull request by pstephan1187**
Move PR over from the 5.2 branch: https://github.com/laravel/framework/pull/13304

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This should probably go to 5.3 rather than 5.4?

**Comment by pstephan1187** [comment]
When will new PRs be closed for 5.3?

**Comment by GrahamCampbell** [comment]
Once 5.3.0 is very close to being tagged, breaking changes will no longer be accepted (in general).

**Comment by GrahamCampbell** [comment]
As a rough guess, I'd say there's still around 10 days to get breaking changes into 5.3 before it's cutting it a bit fine,

**Pull request closed without merging**
