### PR TITLE
[11.x] Adds `Enums` folder to `make:enum` command

### PR DESCRIPTION
**Pull request by milwad-dev**
It is better to create enum classes in the Enums folder, like `Models`

### CODE REVIEW

**Review by driesvints — APPROVED** [review]
Would love to see this change as well 👍

**Comment by laser-hybiz** [comment]
Why is this different than regular class?, isn't it possible to specify the namespace when executing the command?

**Comment by driesvints** [comment]
Because a regular class isn't a type of object.

**Comment by taylorotwell** [comment]
Would rather keep this flexible by default like classes and traits. I personally would tend to group these close to the thing they are attached to.

**Pull request closed without merging**
