### PR TITLE
[10.x] Removes duplicate builds using PHPUnit 9

### PR DESCRIPTION
**Pull request by nunomaduro**
This pull request removes duplicate builds using PHPUnit 9, and effectively ensures our framework is only being tested by PHPUnit 10.

### CODE REVIEW

**Review by driesvints — APPROVED** [review]

**Comment by crynobone** [comment]
Can we have phpunit 9 run only on tags or `workflow_dispatch`. This can allow us to troubleshoot if anything stop working on phpunit 9.

**Comment by driesvints** [comment]
@crynobone we'd have to add the majority of code of this PR again this way. Maybe we can, for now, set up a separate GitHub Action yml file that runs once a week on a schedule?

**Comment by crynobone** [comment]
That's another option too, it not something that we forsee would break but would be nice not to break any existing code on app still running phpunit 9.

**Comment by driesvints** [comment]
Yeah, main reason I want to get rid of the PHPUnit 9 builds here is to not have so many builds running for every PR/commit push.

**Pull request merged**
