### PR TITLE
[5.0] fixed global scope case where eager loading inside scope causes 'is null'

### PR DESCRIPTION
**Pull request by austenc**
See https://github.com/laravel/framework/pull/7898.

Any input / advice / test help appreciated.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please provide tests.

**Comment by austenc** [comment]
@GrahamCampbell I'm not sure how to write tests for this. Any guidance or examples of similar tests would be pretty helpful and I'll give it a shot.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/5.0/tests/Database/DatabaseEloquentRelationTest.php.

**Comment by GrahamCampbell** [comment]
We also have integration tests at https://github.com/laravel/framework/blob/5.0/tests/Database/DatabaseEloquentIntegrationTest.php.

**Pull request merged**
