### PR TITLE
[5.6] Add a array of shared data to the environment.

### PR DESCRIPTION
**Pull request by SOSTheBlack**
This commit prevents the developer having to keep calling the instance every time it will give a view share. this is beautiful!

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Can you provide some description?

**Comment by sisve** [comment]
Where are the tests?

Do we really want to introduce more helpers into the global scope?

**Review by vitorleonel — APPROVED** [review]

**Comment by SOSTheBlack** [comment]
@sisve heler are never too much when they are helpers ;)
@Dylan-DPC go to php docblock

**Comment by devcircus** [comment]
👎🏻 In 5 years of Laravel, I've used "share" maybe once. Seems to be another unnecessary global.

**Pull request closed without merging**
