### PR TITLE
[5.6] Added translations to default Password Reset notification

### PR DESCRIPTION
**Pull request by LasseRafn**
I made the default ResetPassword notification translatable, so that developers won't have to create their own to change the text.

Related: https://github.com/laravel/laravel/pull/4666 (the actual translations)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎 The `trans` function is defined in the foundation package, so this breaks someone requiring the auth package by itself.

**Comment by taylorotwell** [comment]
I suggest using the `__` helper and using JSON translations. Then we don't have to invent new keys, etc.

**Comment by LasseRafn** [comment]
Okay, I agree. Instead, how about including a default Mail class for this instead? For when creating a new Laravel instance?

I just feel that many people would want to translate this.

**Comment by LasseRafn** [comment]
Makes sense, Taylor. I’ll submit a new PR when I’m home.

**Pull request closed without merging**
