### PR TITLE
[5.3] Allow using string-'number' as times argument in factory helper

### PR DESCRIPTION
**Pull request by Kyslik**
Factory helper can be used with times argument that is "numeric" in PHP realm.

example:

```
factory(App\User::class, '100')->make();
```

before fix this would throw Exception:

```
[InvalidArgumentException]
  Unable to locate factory with name [100] [App\User].
```

### CODE REVIEW

**Comment by JosephSilber** [comment]
Wouldn't it be better to pass an actual number? You can easily cast a string if you need it.

**Comment by Kyslik** [comment]
Please see is_number() php doc. You can use all those formats (that includes "actual number" - integer type) as times parameter.

**Comment by Kyslik** [comment]
>I really don't need it myself, just thought that `is_numeric` is better check than `is_string`.

Please see [`is_number()`](http://php.net/manual/en/function.is-numeric.php) php doc. You can use all those formats (that includes "actual number" - integer type) as times argument.

Some possible values that now work: `"100"`, `'100'`, `100`

**Comment by GrahamCampbell** [comment]
This now allows '4.2' which is wrong.

**Comment by Kyslik** [comment]
@GrahamCampbell it works exactly as before.

You could use `factory(App\User::class, 4.2)->make();` which makes 5 objects.

**Comment by tpraxl** [comment]
I appreciate the change in general. I'm working with behat and encountered the following situation:
```
/**
* @Given I have :numberOf customers
*/
public function iHaveCustomers($numberOf)
{
   $customers = factory(Customer::class, $numberOf)->create();
}
```
That caused the following Exception to be thrown:
```
Unable to locate factory with name [2] [App\Customer]. (InvalidArgumentException)
```

In order to fix that, I needed to cast `$numberOf` to a number. 
If I get the PR right, then this would not have been necessary.

**Comment by Kyslik** [comment]
@tpraxl yes you got PR right. 

Thanks for showing that usecase.

**Comment by taylorotwell** [comment]
Just pass a number to begin with.

**Pull request closed without merging**
