### PR TITLE
[6.x] BelongsToMany withSoftDeletes

### PR DESCRIPTION
**Pull request by ddzobov**
# BelongsToMany withSoftDeletes

When using withSoftDeletes() after removal pivot entry will not physically disappear from database.
Standard and custom pivot model - both supported.

This PR based on https://github.com/ddzobov/laravel-pivot-softdeletes
Previous PR: #31210 (published it too early)

## Basic usage

```php
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withSoftDeletes();
    }
}

class Tag extends Model
{
    public function posts()
    {
        return $this->belongsToMany(Post::class)->withSoftDeletes();
    }
}
```

### Custom pivot model:

```php
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Pivot;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    public function tags()
    {
        return $this->belongsToMany(Tag::class)->using(PostTag::class)->withSoftDeletes();
    }
}

class Tag extends Model
{
    public function posts()
    {
        return $this->belongsToMany(Post::class)->using(PostTag::class)->withSoftDeletes();
    }
}

class PostTag extends Pivot
{
    use SoftDeletes;
}
```

### Custom deleted_at field:

```php
$this->belongsToMany(Post::class)->withSoftDeletes('custom_deleted_at');
```

### Show exists & trashed:
```php
WIP
```

### Show only trashed:
```php
WIP
```

### Restore pivot recods:
```php
WIP
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
Don't submit it unless it's actually done and fully featured.

**Comment by skaiblinger** [comment]
@ddzobov I implemented the missing features in #31070 but only for custom pivot models. I hope you don't mind if i just take some of the things you implemented and try to merge together both feature-sets.

**Comment by ddzobov** [comment]
> @ddzobov I implemented the missing features in #31070 but only for custom pivot models. I hope you don't mind if i just take some of the things you implemented and try to merge together both feature-sets.

Now i’m implemented missing methods except forceDelete(). Will do it tomorrow and publish new PR.

After that we can see if we can merge our code bases for better result 😉

**Comment by skaiblinger** [comment]
> Now i’m implemented missing methods except forceDelete(). Will do it tomorrow and publish new PR.
> 
> After that we can see if we can merge our code bases for better result 😉
Yeah sure. Let's get the best of both worlds. 

Maybe you got the cleaner approach on all the deletes, reactivates and whatnot. And you already got that working with and without custom pivot models.
Maybe we can take my part with the pivot-query object, joinSub and applying the scopes, because this opens up some additional features like custom implementation of the SoftDeletes trait (like boolean values instead of pit / null) and configurability of the underlying query.

I would love to have all these things supported by the framework.

**Pull request closed without merging**
