### PR TITLE
[10.x] Handle Validator strings with regex exploding safely fixes pterodactyl/panel#4360 and pterodactyl/panel#1960

### PR DESCRIPTION
**Pull request by gailingmic**
Hello everyone :)

i noticed that Validator Strings with regexes that use the OR operator are not correctly handled.
This should fix and handle edgecases correctly as im walking the string and exploding it manually.

Im obviously open for feedback as my PHP got quite rusty.

Sincerely,
Michell

### CODE REVIEW

**Comment by gailingmic** [comment]
I just noticed that Tests are failing now (some because they expect broken behaviour). Ill fix them before this is worth merging :)

**Comment by gailingmic** [comment]
I just fixed the last edgecase and adjusted the tests to be correct again. Im eager to get some feedback from you guys 😄

**Comment by taylorotwell** [comment]
You can just specify your rules in an array instead of a string to avoid this issue:

CleanShot 2023-05-10 at 16 33 44@2x

**Comment by gailingmic** [comment]
Thank you for your feedback but what i am wondering is: is there a way to give the array variant in a stringified version? Because if there is no way this would still help out immensly as it is quite a common usecase to provide validators in a stringformat when it comes to dynamic or even userprovided interfaces

**Pull request closed without merging**
