### PR TITLE
[5.4] Add $num optional parameter to Arr::random()

### PR DESCRIPTION
**Pull request by vlakoff**
Follow-up to #19741.

There is a bit of room for improvement. Mainly, the function would fail if requesting more items than available. This can be dealt with later, here I do this PR to quickly alter the method signature while it is fresh.

ping @calebporzio

### CODE REVIEW

**Comment by vlakoff** [comment]
`array_random($array, 1)` behaves as `array_random($array)`, i.e. it directly returns the random item.

Is it ok, or should it be changed to behave as `array_random($array, N)`, i.e. returning an array of one item?

**Comment by vlakoff** [comment]
Indeed that's what `Collection::random()` does. `random()` directly returns the item, `random(1)` returns an array of one item. Do you agree `Arr::random()` should do the same?

**Comment by calebporzio** [comment]
I think so, it more closely matches array_rand as well - I will submit a PR as soon as I get the chance.

**Comment by vlakoff** [comment]
I'm already on it :) Also, refs #16865.

**Comment by calebporzio** [comment]
Cool 👍

**Pull request merged**
