### PR TITLE
[5.2] change group route namespace merged style

### PR DESCRIPTION
**Pull request by The-Hasanov**

### CODE REVIEW

**Comment by The-Hasanov** [comment]
[https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/Router.php#L662](Router.php controller namespace solution)

**Comment by GrahamCampbell** [comment]
Isn't this a breaking change?

**Comment by GrahamCampbell** [comment]
Also, please add some tests.

**Comment by taylorotwell** [comment]
Please resubmit with full description and tests.

**Comment by vlakoff** [comment]
May I suggest the following?

```php
    protected static function formatUsesPrefix($new, $old)
    {
        if (! isset($new['namespace']) && ! isset($old['namespace'])) {
            return null;
        }
        
        if (! isset($new['namespace'])) {
            return $old['namespace'];
        }
        
        if (! isset($old['namespace'])) {
            return rtrim($new['namespace'], '\\');
        }       
        
        return strpos($new['namespace'], '\\') === 0
            ? trim($new['namespace'], '\\')
            : trim($old['namespace'], '\\') . '\\' . trim($new['namespace'], '\\');
    }
```

**Pull request closed without merging**
