### PR TITLE
[7.x] Add baseUrl for IDE helper

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by taylorotwell** [comment]
It's not in alphabetical order.

**Comment by GrahamCampbell** [comment]
Easily fixed.

**Comment by GrahamCampbell** [comment]
PR author has disallowed maintainers to update the branch, so not so easily fixed. Please fix this and submit a new PR.

**Comment by lloricode** [comment]
> It's not in alphabetical order.

sorry, this cause of fixing conflict, but didn't notice that sort is not follow

**Pull request closed without merging**
