### PR TITLE
[11.x] `Stringable` is also an interface of symfony

### PR DESCRIPTION
**Pull request by lava83**
`Stringable` is also an interface of symfony and is implemented on models. So if we check a model if a model is filled it except an error: Call to undefined method App\\Model::trim(). So we use now explicit Illuminate\Support\Stringable

### CODE REVIEW

**Comment by Jacobs63** [comment]
You've added an unused `Illuminate\Support\Stringable` import.. what exactly does this solve?

The interface is not used in the helpers file, it is only referenced via PHPDoc, so this only adds an unused duplicate of that.

**Comment by lava83** [comment]
> You've added an unused `Illuminate\Support\Stringable` import.. what exactly does this solve?
> 
> The interface is not used in the helpers file, it is only referenced via PHPDoc, so this only adds an unused duplicate of that.

No: `src/Illuminate/Support/Stringable.php` - used the global interface as BaseStringable

image

And if I check in the `blank` function the value is an instance of (Base)Stringable, `filled($model)` dont work because `Model` didnt have a methode `trim`.

**Comment by Jacobs63** [comment]
> > You've added an unused `Illuminate\Support\Stringable` import.. what exactly does this solve?
> > The interface is not used in the helpers file, it is only referenced via PHPDoc, so this only adds an unused duplicate of that.
> 
> No: `src/Illuminate/Support/Stringable.php` - used the global interface as BaseStringable
> 
> image
> 
> And if I check in the `blank` function the value is an instance of (Base)Stringable, `filled($model)` dont work because `Model` didnt have a methode `trim`.

Ah.. so this fixes your previous PR https://github.com/laravel/framework/pull/51300

That's the difference, I see, sounds good!

**Comment by Jacobs63** [comment]
I believe updating the `blank` helper with this:
```php
        if ($value instanceof Stringable) {
            return trim((string) $value) === '';
        }
```
Instead of this:
```php
        if ($value instanceof Illuminate\Support\Stringable) {
            return $value->trim()->toString() === '';
        }
```

Is both faster and solves more use-cases - @taylorotwell thoughts?

**Comment by lava83** [comment]
> I believe updating the `blank` helper with this:
> 
> ```
>         if ($value instanceof Stringable) {
>             return trim((string) $value) === '';
>         }
> ```
> 
> Instead of this:
> 
> ```
>         if ($value instanceof \Illuminate\Support\Stringable) {
>             return $value->trim()->toString() === '';
>         }
> ```
> 
> Is both faster and solves more use-cases - @taylorotwell thoughts?

But you're not going to hit strings alà '   '. Thats it why I've added `$value->trim()`

**Comment by lava83** [comment]
> I believe updating the `blank` helper with this:
> 
> ```
>         if ($value instanceof Stringable) {
>             return trim((string) $value) === '';
>         }
> ```
> 
> Instead of this:
> 
> ```
>         if ($value instanceof \Illuminate\Support\Stringable) {
>             return $value->trim()->toString() === '';
>         }
> ```
> 
> Is both faster and solves more use-cases - @taylorotwell thoughts?

Okay I've seen, native `trim` can trim this:

```php
$value = '    '; //more than one spaces

trim($value) === ''; //true
```

I will change it to native php function. Thx @Jacobs63

**Pull request merged**
