### PR TITLE
[5.1] Encrypter Fixes

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by ibrasho** [comment]
:+1:

How do you enable the mcrypt encrypter?

**Comment by GrahamCampbell** [comment]
> How do you enable the mcrypt encrypter?

You don't. It's there for testing only. We're removing it in 5.2.

**Comment by taylorotwell** [comment]
You don't really. It's only purpose is for our unit testing during this release cycle. We will remove it in 5.2 was things stabilize.

**Comment by GrahamCampbell** [comment]
If you really want it, you can override the ioc binding I guess, though we don't officially recommend this. :)

**Comment by ibrasho** [comment]
BC? If I used RIJNDEAL_256 before, I'll not be able to decrypt my data in 5.1.

**Comment by GrahamCampbell** [comment]
Yes you will.

**Comment by GrahamCampbell** [comment]
Anyone using a 32 byte key in 5.0 was actually using the 256 cipher anyway, even if they thought they were using 128.

**Comment by ibrasho** [comment]
Not really. AES-256 is not equivalent to MCRYPT_RIJNDEAL_256. It's RIJNDEAL_128 with a 32-byte key.

**Comment by taylorotwell** [comment]
I get the following error when trying to decrypt 5.0 RIJNDAEL_256 on 5.1:

openssl_decrypt(): IV passed is 32 bytes long which is longer than the 16 expected by selected cipher, truncating

**Comment by ibrasho** [comment]
Because the IV length of all AES algorithms should be 16 bytes.

**Comment by ibrasho** [comment]
This why AES-256 != MCRYPT_RIJNDEAL_256.

**Comment by taylorotwell** [comment]
So it sounds like we have no way to support decrypting RIJNDAEL_256 in 5.1 without keeping around a copy of the McryptEncrypter?

**Comment by ibrasho** [comment]
Yes. If we want BC, we must allow people to choose the encrypter that want.

**Comment by ibrasho** [comment]
I believe making the encrypter choice a hidden configuration, mentioned in the upgrade guide should be enough. The default should be OpenSSL.

**Comment by GrahamCampbell** [comment]
> a hidden configuration,

I don't think we should have config baked in. Should be up to the user to hacky override this if they want unsupported ciphers IMO.

**Comment by ibrasho** [comment]
I'm just aiming at an easier upgrade path. :-)

**Comment by taylorotwell** [comment]
We can just use the Mcrypt encrypter if we see they provided us an mcrypt cipher in the cipher config option. Otherwise, we'll use the new OpenSSL encrypter. We can include note in upgrade guide about how to migrate to the new one if / when people want to re-encrypt their data.

**Comment by ibrasho** [comment]
This also possible. Should I create the PR?

**Comment by taylorotwell** [comment]
Graham will update this one.

**Comment by ibrasho** [comment]
I believe we should rename the `Encrypter` class to `OpenSslEncrypter`. This will help us distinguishing between the two implementations later on.

**Comment by taylorotwell** [comment]
Does the blockSize need to be 32 in the OpenSSL encrypter when the cipher is AES-256-CBC?

**Comment by ibrasho** [comment]
Block size is always 128 bits (16 bytes) in AES.

**Comment by tinpont** [comment]
Maybe projects built with laravel below 5.1 could not upgrade in future time?

**Comment by GrahamCampbell** [comment]
@tinpont This PR was manually merged, and will be present for the 5.1.0 release.

Laravel 5.1 is an LTS release and so will support all encryption used from Laravel 4.0+. It is likely that this support will eventually be dropped, though likely not in 5.x as far as I can see. My point is that even if we did drop this in 5.2, it wouldn't be the end of the world, users have 2 (or even 3) years from now to upgrade their encryption and re-encrypt their data with the new, more secure ciphers.

**Comment by tinpont** [comment]
@GrahamCampbell Thanks for your explain. Does 5.1 document will give some way to help people upgrade their cookie encryption to the new one ?

**Comment by GrahamCampbell** [comment]
Yeh, we've documented the upgrading process. You can technically stay with mcrypt in 5.1 if you want by using the same mcrypt cipher in your config.

**Pull request closed without merging**
