### PR TITLE
[5.1] Added message typical of lost connection on MariaDB

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by REBELinBLUE** [comment]
Ah, thanks I shall test it this afternoon

**Comment by GrahamCampbell** [comment]
:)

**Comment by REBELinBLUE** [comment]
To answer your question from https://github.com/laravel/framework/issues/10604#issuecomment-148334017 that is the only additional error message I've spotted. I've asked the person who reported it to me and he said the same thing.

**Comment by GrahamCampbell** [comment]
So, typically, `Error while sending `.

**Comment by REBELinBLUE** [comment]
Seems to be working :) Thanks

**Comment by GrahamCampbell** [comment]
:)

**Comment by chrisbjr** [comment]
I was going to port this fix to 4.2 - but is Taylor still accepting pull requests for 4.2?

**Comment by GrahamCampbell** [comment]
No. Only bug fixes to 5.1, and only security fixes to 5.0 and lower.

**Pull request merged**
