### PR TITLE
Update Mailer.php

### PR DESCRIPTION
**Pull request by parfumix**
before builduing we have to be sure this in not empty string set up.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This would cause a php fatal error if the element at that index is not set.

**Comment by lukasgeiter** [comment]
@GrahamCampbell Not true. http://php.net/manual/en/function.empty.php

> `empty()` does not generate a warning if the variable does not exist.

**Comment by GrahamCampbell** [comment]
Ooops! http://3v4l.org/IdYjg

**Comment by parfumix** [comment]
http://3v4l.org/j5ahm - you have to use array insead of [] (it's has been itroduced in 5.4.x)

**Comment by GrahamCampbell** [comment]
@parfumix What? I was showing it as an example of it working. We don't care about php 5.3.

**Pull request merged**
