### PR TITLE
[5.1] Phpdoc return full class namespace

### PR DESCRIPTION
**Pull request by kasparsklavins**
Changed `@return $this` to `@return \Full\Class\Namespace` for auto-completion in IDE's.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This isn't right.

**Comment by GrahamCampbell** [comment]
We really do mean `$this`.

**Comment by kasparsklavins** [comment]
There's some inconsistencies, ex., https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Builder.php#L716

**Comment by GrahamCampbell** [comment]
That's not inconsistent though, because that time it's not returning `$this`...

**Pull request closed without merging**
