### PR TITLE
[5.5] Preserve parameter order in BoundMethod::call()

### LINKED ISSUE #22687: BoundMethod::call() sends parameters in wrong order
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7 / PDO

### Description:

BoundMethod::call() will send parameters to the function in wrong order in some cases. If a function parameter has a default value set and one precedes it with no default value, the default value from the second parameter will be applied to the first parameter.

### Steps To Reproduce:
```php
//... some class ...

public function list(string $url, string $type = 'all'): void
{
    var_dump($url);
    var_dump($type);
}

//... some container ...
$this->app->call("SomeClass@list", ['testparam']);
```

This will result in output:
```php
string 'all' (length=3)
string 'testparam' (length=24)
```

So the default value for $type was sent to $url parameter instead.

### Explanation:

This is because in BoundMethod on line 119
```php
      return array_merge($dependencies, $parameters);
```
the results from depedency resolution are merged with no order at all. The dependencies are resolved first and after that the parameters so no order is taken into account.

### How to fix:

In function addDepdencyForCallParameter take given parameters into account and fill dependecies in such a way that the order is preserved.

### PR DESCRIPTION
**Pull request by tssge**
This pull request fixes #22687 

We will first resolve the dependencies normal way, but in this commit we
will keep track on the order of the parameters.

Then we will loop through given parameters if all were not consumed and consume these if
we have some unfilled parameters left in our function call.

This way we prevent the default value of some parameter being applied to
the wrong position.

We will need to loop the parameters outside of
addDependencyForCallParameter, because calls to this function check for
parameter count of the function and send the ReflectionParameter as
argument. Because of according to test
ContainerTest::testCallWithCallableArary we must give parameters to
function even if the function parameter count mismatches, we cannot
perform this inside of addDependencyCallParameter.

### CODE REVIEW

**Comment by taylorotwell** [comment]
With your change I still do not get the proper results exactly:

screen shot 2018-01-09 at 9 31 12 am

screen shot 2018-01-09 at 9 31 17 am

**Comment by tssge** [comment]
The results are proper, as I decided to keep the old behavior. As seen in test
```php
    public function testCallWithCallableArray()
    {
        $container = new Container;
        $stub = new ContainerTestCallStub;
        $result = $container->call([$stub, 'work'], ['foo', 'bar']);
        $this->assertEquals(['foo', 'bar'], $result);
    }
//...
    public function work()
    {
        return func_get_args();
    }
```
the arguments that go over the function argument count should be passed to the function nevertheless according to this test.

As in your example, the function is given 3 arguments: 2 chosen by the user and 1 default. These 3 are passed as was done previously by Laravel.

I necessarily do not agree with this behavior myself, but I decided to preserve it due to backwards compatibility.

If you are saying that it is wrong to pass the default value and then the given one, this was done previously as well by BoundMethod::getMethodDependencies:
```php
    protected static function getMethodDependencies($container, $callback, array $parameters = [])
    {
        $dependencies = [];

        foreach (static::getCallReflector($callback)->getParameters() as $parameter) {
            static::addDependencyForCallParameter($container, $parameter, $parameters, $dependencies);
        }

        return array_merge($dependencies, $parameters);
    }
```
after resolving the dependencies (this will resolve default values as well) it will simply merge the resolved dependencies and given parameters having the same end result as in your test.

Running your test without my patch results in the following result
```php
array(3) {
  [0] =>
  string(7) "default"
  [1] =>
  string(3) "foo"
  [2] =>
  string(7) "default"
}
```
which is the same, but the argument order is wrong. And that is what my patch fixes.

**Comment by taylorotwell** [comment]
I guess I don't see the point of passing 3 arguments to a method that only expects 2?

**Comment by tssge** [comment]
Me neither and I'd rather check the argument count and only send the correct amount of arguments. But I did not want to change the existing test, because someone might depend on this behavior, as it has been previously outlined in test that arguments are sent to the function regardless of how many arguments it actually accepts.

Also, I think we should send BindingResolutionException if we are unable to resolve a dependency. Currently BoundMethod just blindly calls the function even if it were unable to resolve all dependencies. I would see that throwing in this case would be consistent with the behavior of Container.

How do you think I should proceed?

**Comment by taylorotwell** [comment]
Looking at the existing code I don't think it was ever intended to be called in the way you are describing. It is meant to be called like this:

screen shot 2018-01-09 at 11 38 21 am

**Comment by tssge** [comment]
I believe you are mistaken. Please see test testCallWithCallableArray in Container.
```php
    public function testCallWithCallableArray()
    {
        $container = new Container;
        $stub = new ContainerTestCallStub;
        $result = $container->call([$stub, 'work'], ['foo', 'bar']);
        $this->assertEquals(['foo', 'bar'], $result);
    }
```
https://github.com/laravel/framework/blob/5.5/tests/Container/ContainerTest.php#L525

This test particularly enforces that this is intended behavior.

**Pull request closed without merging**
