### PR TITLE
[8.x] Allow nullable columns for AsArrayObject/AsCollection casts

### PR DESCRIPTION
**Pull request by tomirons**
When using either of these casts and allowing the column to be `null` it throws an undefined error whenever you access the attribute.

This fixes that issue.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Is it possible they should just return `null`? What do the typical `array` and `collection` casts do?

**Comment by tomirons** [comment]
The typical ones will just return the value if it's null. So your suggestion to just return null makes sense.

**Comment by PhiloNL** [comment]
Hi @tomirons and @taylorotwell 🙌  
I just updated one of my apps and this is a breaking change for me.
I have a user table with JSON settings column which is null by default:

Usage like this is no longer working:
```php
auth()->user()->settings->get('mode', false);
auth()->user()->settings->put('hide_price', $state);
```

This now results in:
```
Call to a member function get() on null
Call to a member function put() on null
```

I think I can fix it by making the default column value `{}`. But again this might break applications who expected to always get a collection by default.

**Comment by tomirons** [comment]
@PhiloNL this PR allows you to have null for these casts. It's up to you how the data is structured.

**Pull request merged**
