### PR TITLE
[5.3] Removed deprecated lists functions

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Though, actually, given the collection changes are going into 5.3, maybe we should just remove them at that point too?

**Comment by JosephSilber** [comment]
I'm :-1: on this.

Like I said in [the original PR](https://github.com/laravel/framework/pull/10888), deprecating it in 5.2 does *not* mean that we have to remove this in 5.3.

`lists` is a function people use a lot. For now, it's just an alias. Removing it doesn't give us much of anything. I understand wanting to unify the codebase, but I believe keeping `lists` around for another cycle will do us more good than harm.

**Comment by GrahamCampbell** [comment]
I'm :+1: since we're already breaking everything with the collection changes in 5.3.

**Comment by vlakoff** [comment]
+1, aliases just add confusion.

No opinion on the name though, but as `pluck` clearly seems to be the choosen one... deal.

**Comment by taylorotwell** [comment]
Rebase?

**Comment by GrahamCampbell** [comment]
Rebased.

**Pull request merged**
