### PR TITLE
[5.4] Extract blade tests verbatim

### PR DESCRIPTION
**Pull request by alexbowers**
These tests have been extracted verbatim to their own classes in order to be more descriptive, and assist in readability by lessening the size of each individual test file.

### CODE REVIEW

**Comment by alexbowers** [comment]
This is a stepping stone. I would like to do further refactors to the way that blade is tested, however this would be inappropriate in this PR due to the substance of the changes made. To keep things easier, this change has been made first, and further changes will follow.

**Comment by GrahamCampbell** [comment]
Would be nice to keep these inside the View folder though.

**Comment by alexbowers** [comment]
I was trying to keep them separate, because blade processing and view processing are different. 

Perhaps subfolders within View would make sense?

**Comment by GrahamCampbell** [comment]
Our tests are supposed to exactly match our src structure though, because we plan to potentially namespace them later.

> Perhaps subfolders within View would make sense?

Yes.

**Pull request merged**
