### PR TITLE
[5.8] Sort auto discovered packages

### PR DESCRIPTION
**Pull request by kapalla**
Service providers of auto discovered packages are registered in order of the declaration in vendor/composer/installed.json. This is in alphabetical order.

I am currently working at a project where it is necessary to register the service providers in the order they are declared in composer.json resp. the composer.json file of metapackages.

To preserve compatibility it should be sorted optionally by an extra key in the root composer.json file.

```json
"extra": {
    "laravel": {
        "dont-discover": [],
        "sort-dependencies": true
    }
}
```

### CODE REVIEW

**Comment by sisve** [comment]
Wouldn't this break if someone reorders your composer.json file? I don't think the order of composer.json entries are supposed to matter, and there's a setting for composer to automatically order them. I wouldn't expect such a thing to also break my application...

**Comment by devcircus** [comment]
Seems like a case where you'd want to disable auto discovery to get more fine-grained control

**Comment by kapalla** [comment]
If you set composers sort-packages flag it would have still the same behavior like it is right now, in alphabetically order.

My intention was to control the order of packages in the composer.json files of metapackages. And this is for me the perfect place. I describe in one file which packages should be loaded and also in which order.

With the default Laravel´s composer.json there is no different behavior. But you can enable this functionality by setting the sort-dependencies flag in the extra:laravel section.

**Comment by kapalla** [comment]
> Seems like a case where you'd want to disable auto discovery to get more fine-grained control

In my case disabling auto discovery is not a good solution. I'm developing a web interface for several network devices. All of them have the same basic interface and i extending it with their custom packages.

With this implementation, i can clone my project and generate a specific web interface when I integrate the metapackage with `composer require company/wifidevice-bundle`.

This bundle requires company/core, company/autobackup etc.

Another device bundle requires company/core, company/sd-card etc.

And here is the problem: company/core needs always be the first registered service provider.
If i disable auto discovery, i need to tell Laravel manually which service providers should be loaded.
But I don't know which packages are implemented, because the root project is the base for every device bundle.

**Comment by sisve** [comment]
The PackageManifest::build() method is already parsing vendor/composer/installed.json to find all declared service providers. This file contains all the dependencies of the application, and we should be able to use this to sort the providers according to dependency order instead of alphabetical order. I believe this would work with your use-case assuming all the packages have their dependencies properly declared.

**Comment by kapalla** [comment]
This is exactly what this PR is doing.
The PackageManifest::build() method checks if sort-dependencies is set to true and if so, it takes the already parsed packages from installed.json and sort it by dependencies instead of alphabetical order.

**Comment by kapalla** [comment]
Ah, ok. Now i know what you mean.

I will change this.

**Comment by kapalla** [comment]
I have also changed the composer key from sort-packages to sort-providers.

**Comment by taylorotwell** [comment]
You should never depend on the registration order of service providers. They should be able to be registered in any order.

**Pull request closed without merging**
