### PR TITLE
Add 'Lego' as an uncountable word

### PR DESCRIPTION
**Pull request by michaeldyrynda**
Source - https://twitter.com/lego_group/status/823016222975557632

### CODE REVIEW

**Comment by reganjohnson** [comment]
Judging by how the past 25 or so releases have gone, I would say this deserves a minor version release.

**Comment by taylorotwell** [comment]
Lol I dunno I legit fear people will complain about this since its pretty common to say "i have a lot of legos", etc. 😆

**Comment by JonoB** [comment]
I am disappoint :(

**Comment by QWp6t** [comment]
This is just a silly legal thing. Apple also doesn't want you to say "iPhones" but instead "iPhone [mobile digital devices](https://www.apple.com/legal/intellectual-property/trademark/appletmlist.html)," but nobody cares about that. For whatever reason, the "Legos" thing triggers people. You don't need to worry about protecting their trademarks. They have lawyers and lobbyists for that.

**Comment by mbicknese** [comment]
What!? I'm disappointed in you Taylor!

(Now go on about your day and keep building cool stuff)

**Comment by timacdonald** [comment]
LGTM

**Pull request closed without merging**
