### PR TITLE
[8.x] Add a queue:prune-failed command

### PR DESCRIPTION
**Pull request by themsaid**
This command removes stale records from the failed_jobs database table. You can pass an `--hours` option with the number of hours to retain jobs data

### CODE REVIEW

**Comment by netpok** [comment]
Shouldn't be better to show an error message and exit with a non-zero return code if the provider does not support pruning instead of silently failing?

**Comment by wouter2203** [comment]
May I ask what the difference is with the `queue:flush` command? Except for the limit parameter, which is only available in 9.X.

But that would mean, as far as I can tell, that from 9.X onwards there are 2 commands which will do identical things.

**Comment by themsaid** [comment]
@wouter2203 flush removes everything while prune keeps the latest records.

**Comment by wouter2203** [comment]
@themsaid Ah, my bad, didn't notice the default of 24 hours to keep!

**Comment by bryceandy** [comment]
> 2 commands which will do identical things

There was a PR before this where `flush` uses an age option:

```
php artisan queue:flush --age=30
// Failed jobs older than 30 days

php artisan queue:prune-failed --hours=30
// Failed jobs older than 30 hours
```

**Pull request merged**
