### PR TITLE
[5.7] Add historical female figure quotes to Inspire

### PR DESCRIPTION
**Pull request by mallardduck**
Provides more diversity in inspiration sources by adding 5 new items.

### CODE REVIEW

**Comment by jycr753** [comment]
Why is this required? I see no point for this PR.

**Comment by mallardduck** [comment]
@jycr753 I don't think it's required, but I also don't think the Inspire command is required to begin with either. As you can see from the mention in this PR's stream it was an idea brought up in laravel/ideas and I liked it so decided to make it happen.

**Comment by mattstauffer** [comment]
Fwiw, I’d wait on the conversation in ideas; talking about it there gives the benefit of discussing the theoretical idea without having to go into more detail about the Specific quotes (e.g. why Malala twice)

**Comment by jycr753** [comment]
The idea is really bad, there is not need to bring identity politics into software development and more when it comes to a command that exist for fun and testing

**Pull request closed without merging**
