### PR TITLE
[11.x] Added a total() method to the Paginator interface

### PR DESCRIPTION
**Pull request by ghost**
This PR adds a `total()` method to the Paginator interface and implementation. This allows developers to retrieve the total number of records available before pagination, which can be useful for displaying record totals, determining last page numbers, and calculating if more pages are available.

**Usage examples:**

```php
// In view
{{ $paginator->total() }} Total Records 

// In controller
$total = $paginator->total();

// In paginator
if ($this->currentPage() < ceil($this->total() / $this->perPage)) {
  // Has more pages
}
```

### CODE REVIEW

**Comment by rojtjo** [comment]
The `total()` method is already available on the `LengthAwarePaginator`. Is there a specific reason you're not using that?

https://github.com/laravel/framework/blob/10.x/src/Illuminate/Contracts/Pagination/LengthAwarePaginator.php
https://github.com/laravel/framework/blob/10.x/src/Illuminate/Pagination/LengthAwarePaginator.php

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
This looks incorrect. Not all paginators have a total, and total is meant to refer to all items in scope, not just on the current page. Only a length aware paginator has a total.

**Comment by GrahamCampbell** [comment]
⚠️  Note also the branch you actually targeted was 10.x, but the title says 11.x

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
