### PR TITLE
[5.2] Remove execution permissions from files that don't need them

### PR DESCRIPTION
**Pull request by guiwoda**
Only executable files I found were on the `/build` directory. Other php files don't need to be executable.

Tests pass, no test added (should I? kinda don't see the point.)

### CODE REVIEW

**Comment by guiwoda** [comment]
Yeah, I just saw #10775... I don't mind if you close this one too, but are we 100% sure it's not a security issue? I don't like having files with o=x everywhere...

**Comment by GrahamCampbell** [comment]
Sorry, we don't process PRs that make mass changes like this. Thanks though.

**Comment by GrahamCampbell** [comment]
If you install using dist mode, the file permissions from github are discarded anyway.

**Comment by guiwoda** [comment]
Good tip, @GrahamCampbell.
Regarding the size of the PR... yeah, I figured. But then, it'd be great if someone with push permissions could fix this once and be done with it.

**Comment by j4m3s** [comment]
@GrahamCampbell do you have a view on how these incorrect executable permissions are making their way into the repository?  

We use various great illuminate modules outside laravel (via composer), where the "install using dist mode" or "only runs from the public directory" protections mentioned in the various tickets relating to the incorrect permissions don't apply.  `illuminate/database` has a significant proportion of its php files executable.  (But it's not consistent so at least some files have the correct mode  set  :) ).

**Pull request closed without merging**
