### PR TITLE
[5.6] Fix docs in trait InteractsWithInput, method input

### PR DESCRIPTION
**Pull request by rolandsusans**
- fix docs

### CODE REVIEW

**Comment by sisve** [comment]
What is this actually fixing? It's not obvious from the online diff that this is a fix at all. It looks like you're changing what the method can accept.

**Comment by rolandsusans** [comment]
- I'm not changing what method can accept, i'm changing docs only
 - you can allways ensure & check docs 
 of https://github.com/laravel/framework/blob/5.6/src/Illuminate/Support/helpers.php#L443-L451

**Comment by rolandsusans** [comment]
@taylorotwell why did you close pull request ?

**Comment by sisve** [comment]
> I'm not changing what method can accept, I'm changing docs only

If I change the docs to say "this parameter must be a boolean", doesn't that mean that you're changing what the function is documented to accept? Thus you're technically also changing the method signature and the behavior of all derived classes.

This documentation change also changes the method from accepting "string, array or null" into "mixed". Mixed means anything, including integers and classes, which was previously not accepted according to the previous documentation.

**Pull request closed without merging**
