### PR TITLE
[5.7] Replace list() with symmetric array destructuring

### PR DESCRIPTION
**Pull request by staudenmeir**
PHP 7.1 introduced  [symmetric array destructuring](http://php.net/manual/en/migration71.new-features.php#migration71.new-features.symmetric-array-destructuring) as the short version of `list()`.

### CODE REVIEW

**Review by carusogabriel — CHANGES_REQUESTED** [review]
We should also include the `list_syntax` option into the StyleCI to ensure the long syntax `list()` or the short one (as proposed here) for new codes.

**Comment by devcircus** [comment]
Seems superfluous.

**Comment by sisve** [comment]
The existing code works, right? So why change a syntax everyone has known for ages with something new? And yes, I still use `array(...)` over `[ ... ]`.

**Comment by taylorotwell** [comment]
Yeah I really just don't like making these mass changes for little reason. Sorry 😦

**Comment by mastef** [comment]
Looks like this has been implemented in #25966 which makes Laravel support libraries incompatible now with hhvm. Just ran into this when trying to use a different project that had laravel framework as a composer dependency.

**Pull request closed without merging**
