### PR TITLE
[5.0] Make Collection::keys() return an instance of Collection

### PR DESCRIPTION
**Pull request by ibrasho**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Breaks the tests. Also, I don't see the point in this?

**Comment by ibrasho** [comment]
Fixed the test and the docblock

**Comment by ibrasho** [comment]
The only point I see is consistency with `values()` in return types.

**Comment by stygiansabyss** [comment]
The point would be to allow the keys() and values() method calls to return the same expectation, a collection instead of one returning an array and one returning a collection.

**Comment by ibrasho** [comment]
I even suggest that `values()` returns a new `Collection` and the current functionality of `values()`, reseting keys, to be in an explicit function `reset()`.

What do you think?

**Pull request merged**
