### PR TITLE
[5.0] Support Every Flysystem Adapter

### PR DESCRIPTION
**Pull request by GrahamCampbell**
We now fully support every flysystem driver with tests.

### CODE REVIEW

**Comment by barryvdh** [comment]
So how would you add custom filesystems to the FilesystemManager now? Would it be possible to define a closure as config (or as a config key)?

    'ftp' => function(){
        return new Filesystem(new FtpAdapter([
                'host' => 'ftp.example.com',
                'username' => 'username',
                'password' => 'password',
            ]
        ));
    },

That would make it more flexible, for example for adding plugins, caching or custom config.

Or a method to add a disk:
`app('filesystem')->addDisk('ftp', $filesystem)`

(And perhaps check if the instance is a Flysystem instance so it adapts it, or a Illuminate filesystem directly.)

**Comment by garygreen** [comment]
@taylorotwell 

> I prefer not to support them all. I don't think all of them are
realistically used by web developers for most projects.

I wanted to use FTP but are you suggesting it's not that popular? So rackspace and S3 are more common than FTP? Not sure about that logic.

Graham, thanks for this looks like you put a lot of effort into it shame Taylor doesn't use ftp or other adapters so doesn't want them merged :unamused: Kinda gives mixed impressions when Flysystem is a 'universal file system' and by default Laravel only promotes usage of two

**Comment by taylorotwell** [comment]
It is possible to use the manager ->extend method to support any driver you want now. You just need to return an instance of `FilesystemInterface`. So that's already possible.

Up for discussion is just a matter of what to support "out of the box".

**Comment by GrahamCampbell** [comment]
People can use my flysystem package if they want all the things. That's exactly what packages are good for, so the core doesn't get bloated with a load of stuff few people will use.

**Comment by garygreen** [comment]
Cheers taylor! Looks simple enough to do, I'm definitely +1 for FTP and Dropbox support out of the box. I think they are pretty common imo.

**Comment by garygreen** [comment]
Btw if anyone else stumbles upon this -- this is how I added FTP adapter support, pretty simple really. In my `AppServiceProvider.php` boot method:

```php
$this->app['filesystem']->extend('ftp', function($app, $config) {
    return new \League\Flysystem\Adapter\Ftp($config);
});
```

Then in your `config/filesystems.php` add one for ftp:

```php
'ftp' => [
			'driver' => 'ftp',
			'host' => 'ftp.blah.com',
			'username' => 'user',
			'password' => 'password',
			'root' => '/public_html',
		],
```

**Comment by taylorotwell** [comment]
Gary, if you'd like to make a PR to add support for it go ahead.

**Comment by phanan** [comment]
Actually I'd only +1 for (S)FTP. I believe @taylorotwell wanted Laravel to be slim and right to the core, hence the removal for html/form, and Whoops partly. All other features, if not essential to the framework, should only be availabe as packages, just like @GrahamCampbell said. Developers themselves must be in charge of what they need and what they don't. Dropbox? S3? Nah.

**Comment by GrahamCampbell** [comment]
> Developers themselves must be in charge of what they need and what they don't

Exactly. That's why we have packages.

**Pull request closed without merging**
