### PR TITLE
[5.5] Add `replace` method to the Collection class 

### PR DESCRIPTION
**Pull request by ThibaudDauce**
Simple implementation of a `replace` method which replace all occurrences of an item to another.

### Other possible features to add to the PR if requested

I kept this implementation really simple because I wanted to know it's a feature wanted by the framework. But we could add more sugar:

#### Strict mode

```php
collect([1, '1', 2])->replace(1, 3, true);

// [3, '1', 2]
```

#### Callbacks

```php
collect([1, 2, 3, 4])->replace(function($value) {
   return ($value % 2) == 0;
}, function($value) {
    return $value * 2;
});

// [1, 4, 3, 8]
```

```php
collect([
    collect([1, 2, 3]),
    collect([2, 1, 2]),
])->replace(function($collection) {
   return $collection->contains(3);
}, collect());

// [ [], [2, 1, 2] ]
```

### CODE REVIEW

**Comment by lucasmichot** [comment]
Really nice @ThibaudDauce , what about adding an extra `$strict = true` parameter ?

**Comment by ThibaudDauce** [comment]
@lucasmichot because I didn't want to add complexity to the PR and I didn't find a clever solution to avoid the additional condition ^^

```php
if ($strict) {
    return $item === $search ? $replace : $item;
}

return $item == $search ? $replace : $item;
```

We could need a new helper:

```php
function is_equals($a, $b, $strict)
{
    // if ($a instanceof Model AND $b instanceof Model) {
    //     return $a->is($b);
    // }

    if ($strict) {
        return $a === $b;
    }

    return $a == $b;
}
```

**Comment by fernandobandeira** [comment]
```php

$operator = $strict ? '===' : '==';

return eval("$a $operator $b');
```

I'd prefer to stick with the conditional though, not sure it's worth the performance boost.

**Comment by lucasmichot** [comment]
Up to @taylorotwell on that

BTW, `eval()` is hell 😈

**Comment by morloderex** [comment]
@ThibaudDauce Any reason for leaving out nested collections? :)

**Comment by ThibaudDauce** [comment]
@morloderex what behaviour do you expect from nested collections?

```
collect([
    collect([1, 2, 1]),
    collect([2, 1, 2]),
])->replace(1, 3);

// [ [3, 2, 3], [2, 3, 2] ]
```

**Comment by taylorotwell** [comment]
I would just use map directly in your own code.

**Pull request closed without merging**
