### PR TITLE
[5.5] Refactoring & Code Cleanup

### PR DESCRIPTION
**Pull request by joaorobertopb**
- Use ternary operator
- Early return
- Remove unnecessary else statement

### CODE REVIEW

**Comment by ntzm** [comment]
Personally, I find the ternary operator to make this more confusing. I do like the early returns and removing the unnecessary `else` statements however.

**Comment by ludo237** [comment]
Sometimes "less code" is not better. Readability should be a thing.

For instance [this patch](https://github.com/laravel/framework/pull/21554/files?diff=split#diff-828954f72fa14c48217530801632b772R50) does not add anything in concrete. Why remove the `else if` there but not [here](https://github.com/laravel/framework/pull/21554/files#diff-9ffa9921c8542da8cb0059fcbc3ad48aR142)? It doesn't make sense.

Those are just two examples, there are many of them.

**Comment by deleugpn** [comment]
https://github.com/laravel/framework/pull/21526#issuecomment-334296244

**Comment by ConnorVG** [comment]
https://github.com/laravel/framework/pull/21554/files#diff-e526262c4637fb5e17fbe8f3788b97a9R114 This worries me; a lot of readability is lost with ternary and null-coalesce pairing.

I agree with a *lot* of the "dropping `else` in favour of early returns", though I feel it makes more sense to guard in most of these instances (such is `if fail -> throw exception` instead of `if success else throw exception` like here https://github.com/laravel/framework/pull/21554/files#diff-e265ae7dcca1de383f991786a8da27f4R20).

We could probably actually tidy up code in a few of these areas though, for instance https://github.com/laravel/framework/pull/21554/files#diff-df089e9b38d0b0f9f95fd3b2275744afR70 could easily just be `return "$rootNamespace\Feature"`

**Pull request closed without merging**
