### PR TITLE
[5.0] Made process column listing function more readable

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Not only is this way easier to read, but it'll make moving to psr2 in 5.1 safer in the respect that less has to change now, so the diff to migrate will be easier to read, so if anything goes wrong, it'll be easier to identify.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Maybe better to extract your code to a Trait to avoid duplicate and keep code DRY?

**Comment by GrahamCampbell** [comment]
@RomainLanz No. All these methods are not the same.

**Comment by taylorotwell** [comment]
Tests fail.

**Comment by GrahamCampbell** [comment]
Travis is green now. :)

**Pull request merged**
