### PR TITLE
[5.4] Cleanup html output app.stub

### PR DESCRIPTION
**Pull request by Quezler**
### Right now

```
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
```

Outputs:

```
<script>
        window.Laravel = {"csrfToken":"mkH0ewvqg7k1oJVCsH2sZH5ZZfoLcjcm6pfx2xP0"}    </script>
```
### Merge request

```
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>

    </script>
```

Outputs:

```
    <script>
        window.Laravel = {"csrfToken":"mkH0ewvqg7k1oJVCsH2sZH5ZZfoLcjcm6pfx2xP0"}
    </script>
```

### CODE REVIEW

**Comment by Quezler** [comment]
Alternatively, since this is a blade template:

```
    <script>
        window.Laravel = {!! json_encode(['csrfToken' => csrf_token()]) !!}
    </script>
```

(I do wonder why regular php tags where used instead of blade)

**Comment by fragkp** [comment]
See here: https://github.com/laravel/framework/pull/15384

**Comment by Quezler** [comment]
Thanks for the link, it does make sense.

Regardless, this pull request is just for the new line, so we're still good to go 🚗

**Comment by taylorotwell** [comment]
Just noticed this was to master. Should have been to 5.3.

**Comment by Quezler** [comment]
Should i make a new pull request for 5.3?

**Comment by tillkruss** [comment]
I'm not going to mention PR like this in release notes.

**Pull request merged**
