### PR TITLE
[9.x] Add inspiring quote by Walt Disney

### PR DESCRIPTION
**Pull request by hosseinhezami**
Add inspiring quote by Walt Disney

### CODE REVIEW

**Comment by ankurk91** [comment]
This is a nice way to badges on your Github profile

**Comment by hosseinhezami** [comment]
@ankurk91 What's a problem?

**Comment by hosseinhezami** [comment]
@ankurk91 
https://github.com/laravel/framework/pull/23849
Just a comma ( , )
How many do you want me to mention?

**Comment by eduance** [comment]
> @ankurk91 What's a problem?

Stop spamming the repository with small pull requests adding single quotes; add something valuable instead.

**Comment by hosseinhezami** [comment]
> > @ankurk91 What's a problem?
> 
> Stop spamming the repository with small pull requests adding single quotes; add something valuable instead.

Hello spam hunter,
Support [#43243](https://github.com/laravel/framework/pull/43243) PR if you think is valuable.
@eduance

**Pull request closed without merging**
