### PR TITLE
[8.x] Container - Detect circular dependencies

### PR DESCRIPTION
**Pull request by ahmedash95**
Hello, 

This PR adds support to detect circular dependencies when the container resolves a dependency. 

The case is, during the development, if we have classes A, B, and C. and:
- **ClassA** constructor has ClassB
- ClassB constructor has ClassC
- ClassC constructor has **ClassA**

The error you would see before this PR is:
```
Maximum function nesting level of '256' reached, aborting!
```

and it's really hard to know which piece of code is causing this error. in this PR the error would be like:
```
Circular dependency when initiating [App\Http\Controllers\ClassA]
```

This way it's much easier to detect and tell the user which class is causing this error.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This exception needs to be added to the throws doc of both the interface and the implementation.

**Comment by taylorotwell** [comment]
Merged. Thanks.

**Comment by GrahamCampbell** [comment]
This is broken. If the container fails to resolve A for whatever reason, then the next time someone tries to resolve A, we have the cyclic dependency exception. This is probably due to the stack not being properly managed.

**Comment by taylorotwell** [comment]
Reverted for now.

**Comment by ahmedash95** [comment]
> This is broken. If the container fails to resolve A for whatever reason, then the next time someone tries to resolve A, we have the cyclic dependency exception. This is probably due to the stack not being properly managed.

Hey @GrahamCampbell , thanks for the heads up. can you please guide me on how to reproduce it and what is the expected behaviour ?

**Comment by ncou** [comment]
hi,

I think the problem is in this try/catch :

https://github.com/illuminate/container/blob/master/Container.php#L910

You should remove the 2 array_pop($this->buildStack); and add it in a finaly{} section becaus the bluidstack is cleaned only if the exception is a BindingResolutionException but this will not always be the case.

Hope this help.

**Comment by macropay-solutions** [comment]
We were bitten by this also and we found a [fix](https://github.com/macropay-solutions/maravel-framework/pull/35) to detect these situations.

**Pull request closed without merging**
