### PR TITLE
[5.5] Add tests

### PR DESCRIPTION
**Pull request by edenreich**
This Pull Request refers to #20990

### CODE REVIEW

**Comment by themsaid** [comment]
@edenreich please explain the changes in this PR

**Comment by taylorotwell** [comment]
Sorry, we don't merge things without descriptions. Please re-submit with one.

**Comment by edenreich** [comment]
my bad...was just about to explain it nvm

**Comment by GrahamCampbell** [comment]
Please add your description to the OP. :)

**Comment by taylorotwell** [comment]
I still can't really tell what we're going for here and the code isn't super obvious.

**Pull request closed without merging**
