### PR TITLE
[5.8] Move env helper to foundation

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by xuanquynh** [comment]
@GrahamCampbell I think the related tests have to be moved to foundation.

**Comment by taylorotwell** [comment]
Hmm, what dependencies does it have that make you think it belongs in foundation and not support?

**Comment by GrahamCampbell** [comment]
It depends on phpdotenv, which is not available in support.

**Comment by GrahamCampbell** [comment]
Anyway, Laravel's env system is kinda specialised to the framework. Is anyone really using this outside the framework, especially in 5.8?

**Comment by GrahamCampbell** [comment]
Hmm, maybe we should just add phpdotenv as a suggest?

**Comment by xuanquynh** [comment]
I agree with Graham Campbell. The `vlucas/phpdotenv` package isn't a dependency of Support component. We should add it to composer suggestion.

**Pull request closed without merging**
