### PR TITLE
[5.4] Low-hanging optimizations in Eloquent models

### PR DESCRIPTION
**Pull request by vlakoff**
Re-submit of #16500.
The changes are quite simple and bring a noteworthy performance improvement.

props @silwerclaw
also ping @fernandobandeira :)

### CODE REVIEW

**Comment by browner12** [comment]
I believe the problem here exists if the attribute value is `null`.  In that case, the behavior will not be the same.

```php
$test['key'] = null;

var_dump(array_key_exists('key', $test));   //returns true
var_dump(isset($test['key']));              //returns false
```

According to the docs:

[isset](http://php.net/manual/en/function.isset.php)

Returns TRUE if var exists and has value other than NULL. FALSE otherwise.

[array_key_exists](http://php.net/manual/en/function.array-key-exists.php)

Returns TRUE on success or FALSE on failure.

**Comment by vlakoff** [comment]
I'm aware of this, thanks.

**Comment by vlakoff** [comment]
I'm tired of reading "isset() is different blah blah". If you don't actually read the code, please at least read the below explanation.

```php
function foo() {
    $data = ['key' => null];
    if (array_key_exists('key', $data)) {
        // return $data['key'], which is null
    }
}

function bar() {
    $data = ['key' => null];
    if (isset('foo', $data)) {
        // not reached
    }
    // return implicit null
}
```

As for casts values, `null` is simply not an expected value.

**Comment by crynobone** [comment]
> As for casts values, `null` is simply not an expected value.

Changing behaviour in a patch release should be avoided regardless.

**Comment by vlakoff** [comment]
Just pick the first change if you want a 100% identical behavior, even for the weirdest, beyond imagination use cases.

**Comment by fernandobandeira** [comment]
👍  ``` getAttributeFromArray ``` is 100% compatible, and we shouldn't have any issues with the ``` hasCast ```...

From the docs:

> The supported cast types are: integer, real, float, double, string, boolean, object, array, collection,  date, datetime, and timestamp.

This method receives only strings, so it seems safe...

**Comment by taylorotwell** [comment]
Please update this PR to be 100% backwards compatible with 5.4.

**Comment by taylorotwell** [comment]
Feel free to re-submit something that is fully BC.

**Pull request closed without merging**
