### PR TITLE
[5.1] Validate that an attribute exists when another attribute(s) passed rules

### PR DESCRIPTION
**Pull request by Davitig**
It can be useful in some situations

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You broke the build.

**Comment by GrahamCampbell** [comment]
Please provide tests too.

**Comment by phroggyy** [comment]
I'd love to see an example of when this would be useful. I mean, if you see an error on the dependency, it's not too relevant if the dependent passes the test or not (unless you'd want to use this for customising error messages, which I'm pretty certain could be done without this too).

**Comment by TheGIBSON** [comment]
@phroggyy, i agree, it's not too relevant, but it's worth to have it.

**Comment by GrahamCampbell** [comment]
Ping @TheGIBSON.

**Comment by GrahamCampbell** [comment]
We can't continue with the build failing and no tests.

**Pull request closed without merging**
