### PR TITLE
[5.4] Added the ability to filter directly on the count method

### PR DESCRIPTION
**Pull request by nathankoop**
Add ability to pass a filter callback to the count method.

This will perform the filter then do the count.

This is similar to the count function in .NET's linq library.

### CODE REVIEW

**Comment by nathankoop** [comment]
I'd argue that it improves the method as it provides a consistent method signature with many of the other methods such as `First`, `Last`, `Min`, `Max`, `Sort`.

**Comment by taylorotwell** [comment]
See Graham's comment.

**Comment by nathankoop** [comment]
I'm confused, this PR clearly improves consistency between the methods in the collection.

Graham's comment does not address the fact that you already use this pattern in several of your existing methods on the Collection class.

**Comment by warriorkitty** [comment]
I was just showing to my work colleague today and we agreed that this is a nice feature. +2 from us!

**Comment by warriorkitty** [comment]
I was just showing this to my coworker and we agreed that this is a nice feature. +2 from us!

**Comment by kt81** [comment]
:+1:

**Pull request closed without merging**
