### PR TITLE
Add ContainsOne function

### PR DESCRIPTION
**Pull request by souri84**
This function allow to verify if one of multiple strings are present in $haystack

### CODE REVIEW

**Comment by jmarcher** [comment]
Can you please add some tests?

**Comment by ryangjchandler** [comment]
The current `Str::contains()` method accepts an array of needles already.

**Comment by bert-w** [comment]
The `$ignoreCase` is not part of any of the `Str` functions yet so this breaks expected usage. And, like already mentioned, the `Str::contains()` already allows you to pass an array as the `$needles`, returning true if at least one of them matches. Originally I thought that the `containsOne` referred to "one and only one" match in the needles array but this is not the case in your code.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
