### PR TITLE
Enhance `throw` Method to Use Typed `Closure` in `Response`

### PR DESCRIPTION
**Pull request by al1r374**
This PR refines the throw method in the ClassName class by typing the $callback parameter as ?Closure and leveraging func_get_args() for backward compatibility. This change enhances the method’s type safety while maintaining flexibility.

- **Previous Implementation:** The original throw method used func_get_args() to handle callback arguments flexibly but included redundant checks for callability and argument presence.
- **New Implementation:** The updated method directly uses a ?Closure type hint for the $callback parameter and removes the extra is_callable() check. This results in cleaner and more readable code.

### Changes Made:

1. **Parameter Typing:** The $callback parameter is now explicitly typed as ?Closure. This type hinting ensures that the parameter is either a Closure or null.
2. **Simplified Callback Handling:** Removed the redundant check for callability, as the type hint ensures the argument is either a valid closure or null.

### Benefits:

1. **Improved Clarity:** Explicitly typing $callback as ?Closure simplifies the code by making the intended use clear and removing redundant checks.
2. **Enhanced Readability:** The code is cleaner and more readable without the extra callability checks.

### CODE REVIEW

**Comment by timacdonald** [comment]
This should probably target 12.x, as it is a potentially breaking change.

No doubt that is why the `func_get_args` technique was used in the first place: to not be a breaking change.

**Comment by henzeb** [comment]
It is indeed a breaking change. An invokable class for example is not a Closure, but is callable and can be called in this  manner.

**Comment by alirezadp10** [comment]
[timacdonald](https://github.com/timacdonald)
[henzeb](https://github.com/henzeb)

Thanks for your thorough explanation. I see your points. Since this change is a breaking change, I'll close this pull request.

**Comment by rodrigopedra** [comment]
You can send it to master and use the `?callable` type hint to accommodate invokable objects.

As @timacdonald said, the `func_get_args()` usage was most due to allow the method to take a parameter without adding a breaking change when it was introduced.

But I see no problems to improving that on a next major version.

**Comment by alirezadp10** [comment]
> You can send it to master and use the `?callable` type hint to accommodate invokable objects.
> 
> As @timacdonald said, the `func_get_args()` usage was most due to allow the method to take a parameter without adding a breaking change when it was introduced.
> 
> But I see no problems to improving that on a next major version.

Should I send a pull request to master branch?

**Comment by rodrigopedra** [comment]
I think so. As a heads-up, you just reopened this one.

**Pull request closed without merging**
