### PR TITLE
[5.1] Time limit for queue listener

### PR DESCRIPTION
**Pull request by kuczmaja**

### CODE REVIEW

**Comment by taylorotwell** [comment]
We already have a timeout option.

**Comment by kuczmaja** [comment]
--timeout limits each job

I proposed time limit for queue:listen process.

$php artisan queue:listen --runtimelimit=300
stops listening after 5 minutes just after finishing current job.

Till now I had to use $timeout 300 php artisan queue:listen
But sometimes it kills process while job is running.

Can you reconsider?

**Comment by marcvdm** [comment]
@kuczmaja Why would you want to set a timeout on a queue:listen?

If you want to process only one job you can do ``php artisan queue:work``

**Comment by kuczmaja** [comment]
I know. I just need to run listener for particular time, not for only one job.
I use ```timeout``` command, but this way I cannot avoid killing listener while processing jobs.

**Pull request closed without merging**
