### PR TITLE
[5.4] Add support for an array of fields.

### PR DESCRIPTION
**Pull request by jorenvh**
Added an if statement to support an array of fields for the field to compare with.

### CODE REVIEW

**Comment by themsaid** [comment]
We have a rule `in_array` that checks if the value of the given field exists in another array field.

```
'email' => 'in_array:emails'
```

I understand that you're trying to achieve the opposite, if so then I prefer if you make it in a different rule rather than adjusting the `different` rule.

ex:

```
'email' => 'not_in_array:emails'
```

**Comment by jorenvh** [comment]
@themsaid I will create a new rule for it. Thanks for the feedback! Expected this weekend.

**Comment by themsaid** [comment]
Alright, closing this then :)

**Comment by themsaid** [comment]
Also please remember to include tests with your PR

**Comment by jorenvh** [comment]
Thanks for the reminder ;)

**Pull request closed without merging**
