### PR TITLE
[5.3] View - Avoid call_user_func

### PR DESCRIPTION
**Pull request by KennedyTedesco**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I don't think we need all these small PRs to 5.3. A larger one to 5.4 would make much more sense, instead of risky spam.

**Comment by KennedyTedesco** [comment]
@GrahamCampbell This option looks reasonable.

I'm gonna hold this for Taylor to decide. But I will stop sending this kind of PR's to 5.3, then.

**Comment by taylorotwell** [comment]
Yeah, I would agree. But, in general, I don't tend to like these types of PRs because it is **very** easy to mess up one small thing or miss one small thing and break something. 😬

**Comment by KennedyTedesco** [comment]
That's true. Let's be cautious. 😊

**Pull request closed without merging**
