### PR TITLE
[5.9] Only use PHPUnit 8

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by driesvints** [comment]
I actually thought of allowing 7 as well at least until 9 is out since 7 is only EOL next February 2019.

**Comment by GrahamCampbell** [comment]
This is only a dev-dependency of the framework. This won't affect Laravel apps.

**Comment by driesvints** [comment]
Yes but with the "lowest" depencies on the Travis build it would still be tested.

**Comment by GrahamCampbell** [comment]
Yes, assuming we have tests that test the phpunit stuff. I'm not familiar of that area of the codebase. :P

**Comment by driesvints** [comment]
Just a couple of tests at the moment.

**Pull request closed without merging**
