### PR TITLE
[5.8] Extract tagging trait

### PR DESCRIPTION
**Pull request by imanghafoori1**
Since the container's file has grown quite considerable.
Maybe we extract out some it's leaf functionality into meaningful traits as concerns.

I tried to extract a class with static methods but it had some side effects on edge cases.

### CODE REVIEW

**Comment by driesvints** [comment]
This isn't needed imo. The functionality is only used in one place.

**Comment by driesvints** [comment]
Cleaner code is a matter of perspective here. Not that I want to come across harsh but imo this is less cleaner because you're unnecessarily separating concerns.

**Comment by imanghafoori1** [comment]
I don't know.
Feel free to close it out.

**Comment by mfn** [comment]
> The functionality is only used in one place.

I was about to give the same feedback 😅 but the remembered the `HasAttributes` trait and it's the same: only used once. I'm not a fan of traits and usually only use this for tests to avoid repeated code and less for production but `HasAttributes` I would like to think is simply a nice way of "having it all in one place" 🤷‍♀️

**Comment by imanghafoori1** [comment]
There is always an other way, but seemingly Taylor is not interested in any refactors or code clean ups at all.
So I stop right here.

**Pull request closed without merging**
