### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by hannesvdvreken**

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
Ugh, need to take out the other commit first.

**Comment by GrahamCampbell** [comment]
Yeh,

**Comment by GrahamCampbell** [comment]
I've sorted it anyway now.

**Comment by hannesvdvreken** [comment]
`Yeh` but pr closed? :p I'm confused

**Comment by GrahamCampbell** [comment]
Your PR contained extra changes so I just made the tiny fix myself to the readme.

**Comment by hannesvdvreken** [comment]
K

**Pull request closed without merging**
