### PR TITLE
[5.1] Easier to register a custom mail driver

### PR DESCRIPTION
**Pull request by nauxliu**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You can't really register a binding by resolving the same thing.

**Comment by GrahamCampbell** [comment]
You just need to override the 'swift.transport' binding. :)

**Comment by NauxLiu** [comment]
But the MailServiceProvider is deferred. so when I using  `mailer` the  MailServiceProvider will override the `swift.transport` again.

**Comment by GrahamCampbell** [comment]
Just use the resolving method.

**Pull request closed without merging**
