### PR TITLE
[5.3] Rename preg_replace_sub() to preg_replace_array() and remove passing by reference

### PR DESCRIPTION
**Pull request by vlakoff**
Please see #12495 for the full details.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Is `preg_replace_sub` actually used in the core?

**Comment by GrahamCampbell** [comment]
If not, I'd say we should just remove it.

**Comment by vlakoff** [comment]
At least with this PR it is consistent with `str_replace_array()` (which might be more useful in practice).

I'm not against removing it, I agree it may be better to not clutter with an infinite amount of short helpers.
Your pick. Just don't leave it as it is :-)

**Comment by vlakoff** [comment]
TBH, I'd vote for removing these `str_replace_array()` and `preg_replace_array()` helpers. I think they are quite specific and therefore add more confusion than usefulness. Still, users could easily add them in their app if desired so.

The former is used only once in the framework (#12259) and could be inlined, the latter isn't used at all (#12495).

I'm pretty sure @GrahamCampbell will agree. @taylorotwell, what's your stance on this?

**Pull request merged**
