### PR TITLE
[5.2] Better PHP 7 Support

### PR DESCRIPTION
**Pull request by GrahamCampbell**
These changes are breaking, but needed for Laravel to work well on PHP 7.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I've also ensured we catch `Throwable` where it makes sense to. This is really useful for ensuring database transactions are actually dealt with correctly and that failed queue jobs are correctly processed for example.

**Comment by GrahamCampbell** [comment]
We can remove the catch Exception parts from these try catch places when ever laravel drops php 5 in the future.

**Comment by GrahamCampbell** [comment]
NB, catching throwable is a breaking change IMO, so I really think we shouldn't move any of this at all to 5.1.

**Comment by taylorotwell** [comment]
The way you are changing exceptions to catch throwable is basically making that code PHP 7 only because the exceptions are no longer going to be caught at all on PHP 5.x code-bases. You should remove all of those and change them back to exceptions so the code essentially would function as it did on PHP 5.x. If you want to do something like what you did, you would need multiple catch blocks, one for throwable and one for base exception to maintain compatibility with PHP 5.x

**Comment by GrahamCampbell** [comment]
Taylor, you're wrong. Look closer. I haven't CHANGED them to only be throwable. I've ADDED throwable and kept the exception catch blocks there too so this works on php 5 and php 7.

**Comment by taylorotwell** [comment]
Sorry missed that on GitHub.

**Comment by GrahamCampbell** [comment]
No problem. :)

**Comment by rationalthinker1** [comment]
Can you please push this for other versions other than 5.2? I am using 5.0 and trying to upgrade to 5.1.

**Comment by a-komarev** [comment]
Take a note please [about `Throwable` block position](https://github.com/laravel/framework/commit/0e7e4830e6a780699a5143dbf717a07eb1fb358b#commitcomment-16675395).

**Comment by GrahamCampbell** [comment]
> Can you please push this for other versions other than 5.2? I am using 5.0 and trying to upgrade to 5.1.

No, sorry. We did backport this to 5.1 after testing it on 5.2, but it will never be backported to 5.0. Please upgrade to either Laravel 5.1 LTS, or Laravel 5.2.

**Pull request merged**
