### PR TITLE
[6.x] Limited properties returned by morph type

### PR DESCRIPTION
**Pull request by ioan-cristea**
This is a functionality to allow a query like "morphWith" but named "morphProperties" to limit the properties of morph by type.

### CODE REVIEW

**Comment by driesvints** [comment]
Tests still aren't running. This is bizar..

**Comment by ioan-cristea** [comment]
I also adapted the modifications to pass the styleci.

**Comment by ioan-cristea** [comment]
I made this changes on my laravel installation because I need it, and I assumed it will be nice to share this. I made only a few changes, please check them and make the improvements they need.

**Comment by ioan-cristea** [comment]
```
$recommendations = Recommendation::with(['recommendable' => function (MorphTo $morphTo) {
    // This eager load some relationships for morph type
    $morphTo->morphWith([
        User::class => [],
        UserVacantion::class => ['user:id,username'],
    ]);

    // This limit the properties showed for morph type. Please insert here also the columns of the relationships requested in $morphTo->morphWith (ex. above I eagler load the "User" relationship and below I requested user_id to be selected in query)
    $morphTo->morphProperties([
        User::class => ['id', 'username'],
        UserVacantion::class => ['id', 'user_id'],
    ]);
}])->get();
```

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Comment by ioan-cristea** [comment]
The idea is to make something like this code but with polymorphic relationships.
```
$query = Team::where('company_id', '=', $company_id)->with(['leader' => function ($query) {
      $query->select(['id', 'username']);
}]);
```
We can select what properties of morphTo model to be returned in a single query, based on it's class.

What you don't understand? because it's a simple modification.

Case: I have 'Photo' model which morphTo User and Album models. When I request all Photos I want to recevie for User only 'id, username', and for Album only 'id, name'

```
$photos = Recommendation::with(['photographable' => function (MorphTo $morphTo) {
    $morphTo->morphProperties([
        User::class => ['id', 'username'],
        Album::class => ['id', 'name'],
    ]);
}])->get();
```

**Comment by irakan** [comment]
Any news about this? I had a case that needs this functionality

**Comment by ioan-cristea** [comment]
> Any news about this? I had a case that needs this functionality

I don't think they had understand the feature, but this commit resolve it.

**Comment by rajan-parmar** [comment]
@ioan-cristea this changes for fetch selected columns of morph type model right?

Current Scenario:
My Query:
image

Result may be:
```
"stock_adjustment_item" => array:12 [
    "id" => 1
    "stock_adjustment_id" => 1
    "product_id" => 1
    "location_id" => 1
    "location_type" => "STORE"
    "quantity" => "5.00"
    "unit_of_measure_derivative_id" => null
    "derivative_ratio" => null
    "input_quantity" => "5.00"
    "created_at" => "2023-08-28T05:44:12.000000Z"
    "updated_at" => "2023-08-28T05:44:12.000000Z"
    "stock_adjustment" => array:3 [
        "id" => 1
        "type_id" => 1
        "reason" => "just testing"
    ]
]
```
here we would expect like this:
```

"stock_adjustment_item" => array:3 [
    "id" => 1
    "stock_adjustment_id" => 1
    "stock_adjustment" => array:3 [
        "id" => 1
        "type_id" => 1
        "reason" => "just testing"
    ]
]
```

**Comment by ioan-cristea** [comment]
Yes, you can limit the columns that are selected for for the morph type model.
You need to use like this
`
$morphTo->morphProperties([
        StockAdjustmentItem::class => ['id', 'stock_adjustment_id'],
        AnotherStockAdjustmentItem::class => ['id', 'stock_adjustment_id'],
        SpecialStockAdjustmentItem::class => ['id', 'stock_adjustment_id', 'a_special_column_for_this_type'],
]);
`

**Comment by rajan-parmar** [comment]
> Yes, you can limit the columns that are selected for for the morph type model. You need to use like this
> 
> ```
> $morphTo->morphProperties([
>         StockAdjustmentItem::class => ['id', 'stock_adjustment_id'],
>         AnotherStockAdjustmentItem::class => ['id', 'stock_adjustment_id'],
>         SpecialStockAdjustmentItem::class => ['id', 'stock_adjustment_id', 'a_special_column_for_this_type'],
> ]);
> ```

Sorry for the late reply. it's not working. 
below relation I need to load with selected columns:
StockAdjustmentItem::class => ['id', 'stock_adjustment_id'], // this load all columns instead of  selected columns.
StockAdjustment::class => ['id', 'type'],

**Comment by GhostvOne** [comment]
It was a very nice feature @ioan-cristea 
How @taylorotwell didn't understand that.

**Comment by GhostvOne** [comment]
I confirm constraint works well https://laravel.com/docs/10.x/eloquent-relationships#constraining-eager-loading-of-morph-to-relationships

**Pull request closed without merging**
