### PR TITLE
[5.8] Add leave to uncountable nouns

### PR DESCRIPTION
**Pull request by lkmadushan**
https://github.com/laravel/framework/pull/27716

### CODE REVIEW

**Comment by driesvints** [comment]
Just realized this: this seems like a verb and not something you want to put in with the rest of this list?

**Comment by devcircus** [comment]
It has sort of become a noun in the UK in recent months....

**Comment by lkmadushan** [comment]
hmm.. what about leave of absence

**Comment by driesvints** [comment]
@lkmadushan hmm good point.

**Comment by rs-sliske** [comment]
doesnt a tree have multiple leaves?

**Comment by lkmadushan** [comment]
@rs-sliske 
leaf -> leaves
leave -> leave (leave of absence)

**Comment by rs-sliske** [comment]
ye i realised my mustake :p

**Comment by devcircus** [comment]
"I've took several leaves of absence from work last year." 

Seems legitimate.

**Comment by lkmadushan** [comment]
@driesvints 
https://english.stackexchange.com/questions/384589/is-leave-of-absence-a-countable-noun

**Comment by lkmadushan** [comment]
@taylorotwell is there any reason not to merge this? Leave is considered as Mass Noun. 
https://en.oxforddictionaries.com/definition/leave#h70274832713400

**Comment by driesvints** [comment]
@lkmadushan your stackexchange link above says the opposite that it is countable?

**Comment by lkmadushan** [comment]
@driesvints `leave of absence` as a statement it's countable but `leave` is uncountable..

We don't say Annual Leaves, Paid Leaves.. Isn't it?

**Pull request closed without merging**
