### PR TITLE
Fulltext search for sql server

### PR DESCRIPTION
**Pull request by otilor**
As @driesvints suggested, this is a SQL Server implementation fo full-text search.

### CODE REVIEW

**Comment by driesvints** [comment]
@tpetry can you help review this? :)

**Comment by tpetry** [comment]
1. Can you add unit tests? Just copy and change the current ones for MySQL and PostgreSQL
2. MsSQL also supports the `FREETEXT` fulltext search. Can you make an options switch (`mode`) to switch between them?
3. Can you support the language parameter for the index? How to use it for `whereFulltext`?

**Comment by humaneguy** [comment]
@tpetry Great. I'd work on that

**Comment by driesvints** [comment]
@tpetry does this look good to you? If so I'll merge it into my own PR.

**Comment by tpetry** [comment]
Haven't run it, can't say whether it is really working. From a bird's-eye view it is looking correctly.

**Comment by driesvints** [comment]
@humaneguy can you also add an integration test in the same fashion as the PostgreSQL and MySQL implementations?

**Comment by humaneguy** [comment]
Hi @taylorotwell I plan on merging this PR to @driesvints's. I just added integration tests which are failing and I shall rectify.

**Comment by driesvints** [comment]
@humaneguy GitHub automatically closed this PR when we merged mine. Can you send this to 8.x?

**Comment by humaneguy** [comment]
Ok great.

**Pull request closed without merging**
