### PR TITLE
[7.x] Fix PresenceVerifier contract

### PR DESCRIPTION
**Pull request by nmokkenstorm**
Hey all,

I included `illuminate/validation` in a project that uses several Laravel components, including `illuminate/database`, which is set up to use the 'Capsule' approach, as recommended in the Readme.md of said package.

During implementation of the validation stuff for this nonstandard approach to things I ran into an issue with the PresenceVerifier, because of a missing method definition on the contract, this PR aims to fix that.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Where is setConnection called on this? Probably we want to make adjustments there instead. Not every implementation of presence verifier contract may have any notion of connections, etc...

**Comment by nmokkenstorm** [comment]
I honestly had the same thought, but opted to go for a more minimal PR first. I have another small set of changes lined up, I can just put them into this PR if you want. At the moment PresenceVerifier as a whole is coupled to database bound, even if the comments make mention of using stuff like Redis.

The only places I found where setConnection is called is in ` Illuminate/Validation/Concerns/ValidatesAttributes.php`, and if you wrap that call in a null check you can do without setConnection. The use case according to the documentation is optionally passing the connection to use, so that should still work as intended, tests also still pass if you do.

**Comment by taylorotwell** [comment]
A super quick fix would maybe be to put a method_exists check around that `setConnection`. The "proper" fix I guess would possibly be an additional interface like `ConnectionAware` or something.

**Comment by nmokkenstorm** [comment]
> A super quick fix would maybe be to put a method_exists check around that `setConnection`. The "proper" fix I guess would possibly be an additional interface like `ConnectionAware` or something.

I extended the contract and did a check on that, which achieves the same result and feels slightly less of a quickfix to me than a method_exists check.

This means that we could theoretically support for example an Array or File driver without messing around with connections.

**Pull request merged**
