### PR TITLE
[8.x] Added test to show an issue with multiple rate limits

### PR DESCRIPTION
**Pull request by mantas-done**
.

### CODE REVIEW

**Review by mantas-done — COMMENTED** [review]
This test adds multiple rate limits (2 in total). And now the rate limit is reached sooner than expected.
https://github.com/laravel/framework/issues/35844

**Comment by driesvints** [comment]
@mantas-done please add a thorough explanation to your PR description at what this fixes.

It seems that the test already fails for the first attempt while it should only fail at the second one? https://github.com/laravel/framework/runs/1683430480#step:8:138

**Comment by mantas-done** [comment]
This test is a copy of an old test with added multiple rate limits. It shouldn't fail at all.
Probably it can be simplified a lot because it checks the same things like an old test.

Basically, the problem is that when adding multiple rate limiters, they each count as one page hit. You can see in the error message that it is expecting that X-RateLimit-Remaining: 1 should be left, but it shows 0.

I am quite new to unit tests, so would appreciate if somebody more skilled would correct the unit test.

**Comment by driesvints** [comment]
Can you try naming your limiter to something else? Like "test2" or something?

**Comment by taylorotwell** [comment]
This has come up on another PR before. Use the `by` method to assign different "buckets" to your rate limits.

**Comment by taylorotwell** [comment]
Can we discuss the real scenario in your application that you are trying to solve? I may be able to suggest a solution that doesn't require any changes at all.

**Comment by mantas-done** [comment]
> Can we discuss the real scenario in your application that you are trying to solve? I may be able to suggest a solution that doesn't require any changes at all.

image

We have a page where there are jobs. The first user who reserves the job gets it. The goal is to prevent auto-refreshing bots from checking the website too often (the load, and also users unhappy that the bots reserve jobs as soon as they appear).

image

I have also checked an example from the documentation, it seems that it also reduces  X-RateLimit-Remaining not by 1 (by the number of rate limiters).

Thank you for looking into this :)


> Can you try naming your limiter to something else? Like "test2" or something?

I have also tried naming it "login" like in documentation. But the result is the same.

**Comment by taylorotwell** [comment]
I would try something like this:

```php
return [
    Limit::perMinute(20)->by('work-per-minute'),
    Limit::perMinute(200)->by('work-per-hour'),
    Limit::perMinute(600)->by('work-per-day'),
];
```

This essentially assigns them each to an arbitrary "segment" where the counts will not affect each other.

**Comment by driesvints** [comment]
@mantas-done does that answer from Taylor work for you? Can this be closed then?

**Comment by mantas-done** [comment]
> @mantas-done does that answer from Taylor work for you? Can this be closed then?

Yes.

Somehow I didn't understand that I needed ->by() so that counts wouldn't affect each other.

Thank you both for the answers :)

**Comment by taylorotwell** [comment]
@mantas-done I don't think we do a great job of demonstrating how I just used `by` in the docs.

**Pull request closed without merging**
