### PR TITLE
[4.2] Test Route Dispatching With Request Params

### PR DESCRIPTION
**Pull request by antonioribeiro**
Currently , if you create a request with parameters and dispatch it to a router, the new request will have none of those paremeters set:

```
Route::get('test', function() 
{
    $params = ['method' => 'POST', 'user_id' => '2'];

    $request = Request::create('/api', strtoupper($params['method']), $params);

    Route::dispatch($request)->getContent();
});

Route::post('api', function() 
{
    dd(Request::instance()->query->all());
});
```

Discovered it from a SO question I was trying to answer: http://stackoverflow.com/questions/26084628/laravel-requestinstance-returns-original-instance#26084628

### CODE REVIEW

**Comment by lyhoanglong** [comment]
I have similar problem in Laravel 5.
I have route like that $oldRequest
```
url: /test1
method: post
data: {json1}
```

In controller handled this request I call I call Route::dispatch($newRequest) (I wish I can call it in middleware)

Problem is that
```
public function dispatchToRoute(Request $request)
```

is calling 
```
protected function runRouteWithinStack(Route $route, Request $request)
    {
        $shouldSkipMiddleware = $this->container->bound('middleware.disable') &&
                                $this->container->make('middleware.disable') === true;

        $middleware = $shouldSkipMiddleware ? [] : $this->gatherRouteMiddlewares($route);

        return (new Pipeline($this->container))
                        ->send($request)
                        ->through($middleware)
                        ->then(function ($request) use ($route) {
                            return $this->prepareResponse(
                                $request,
                                $route->run($request)
                            );
                        });
    }
```
and in run method in class Route is call method
```
protected function runController(Request $request)
    {
        list($class, $method) = explode('@', $this->action['uses']);

        $parameters = $this->resolveClassMethodDependencies(
            $this->parametersWithoutNulls(), $class, $method
        );

        if (! method_exists($instance = $this->container->make($class), $method)) {
            throw new NotFoundHttpException;
        }

        return call_user_func_array([$instance, $method], $parameters);
    }
```

In controller handled the $newRequest, I log and got $oldRequest and I dont know how to resolve this problem. Any idea about this problem?

**Comment by DracotMolver** [comment]
@taylorotwell About using `handle`. This will refresh any request keeping this one forever. Example
(I'm forced to do this in a project)
```php 
$req = Request::create('api/perfilamientos/usuario/7471913', 'GET');
$res = app()->handle($req)->getData();
````
if I do this, I face some issues (maybe it's not the right word). First, Everything will be redirect using the port 80, even if you are using the port 8000. Then, If you move from one page to other and you wanna get the url ( `Request::url()` ), you will get the url make by `Request::create()`, which was pass to `app()->handle()`. So, how can I handle this?

**Comment by aleemb** [comment]
Dingo offers `API::get`, `API::put` type facades which make it very handy to make those calls and handle them as well. The reason I like it is because the API layer can raise it's own exceptions and this gives implicit testability since the API is being called throughout.

It also makes splitting out any web components and decoupling the app that much easier for a more service oriented architecture or even microservices.

**Comment by hayjay** [comment]
> @taylorotwell About using `handle`. This will refresh any request keeping this one forever. Example
> (I'm forced to do this in a project)
> 
> ```
> $req = Request::create('api/perfilamientos/usuario/7471913', 'GET');
> $res = app()->handle($req)->getData();
> ```
> 
> if I do this, I face some issues (maybe it's not the right word). First, Everything will be redirect using the port 80, even if you are using the port 8000. Then, If you move from one page to other and you wanna get the url ( `Request::url()` ), you will get the url make by `Request::create()`, which was pass to `app()->handle()`. So, how can I handle this?

Hi @DracotMolver , were you able to solve this issue?

**Pull request closed without merging**
