### PR TITLE
[5.5] Add Route::default

### PR DESCRIPTION
**Pull request by sileence**
Useful to build SPAs or simply add a default route.

Before:

```
Route::get('{any}', function () {
    return view('welcome');
})->where('any', '.*');
```

After:

```
Route::fallback(function () {
    return view('welcome');
});
```

I got this idea during the Evan You talk in Laracon EU :)

### CODE REVIEW

**Comment by m1guelpf** [comment]
@duilio Why limiting to GET and HEAD? This can be used with all methods!

**Comment by sileence** [comment]
My idea is that the method is used when building SPAs, I don't know if post/put/delete would be useful in that case. I'll leave it to Taylor or others to decide.

**Comment by m1guelpf** [comment]
@sileence How about an optional parameter with an array of methods to use?

**Comment by sileence** [comment]
@m1guelpf then it wouldn't be clean anymore. The idea is to have a clean way to set a fallback route when no other route is matched.

**Comment by mnabialek** [comment]
I think this is good idea. I have at least few times situation when I needed to create "catch-all" route and had to always remind myself to set this `.*` constraint manually and now it could be done out of the box (and I'm not talking about SPAs).

**Comment by decadence** [comment]
I think intercepting all POSTs is bad idea, GET and HEAD is enough. Though it can be optional.

**Comment by joshmanders** [comment]
Agree on only `GET` and `HEAD` anything else, you should just use the `addRoute` method yourself. Otherwise you're reimplementing it with a new name.

**Comment by paulofreitas** [comment]
I'm not sure if the "fallback" name would be clear to everyone but anyway this is indeed a cool idea! 😃

**Comment by sileence** [comment]
@paulofreitas how would you name the method? `Route::default` maybe?

**Comment by paulofreitas** [comment]
@sileence That was the name I was thinking, I din't suggested at first because generally I'm not good at picking names, but I think this one would be more concise/intuitive. 😄

**Comment by taylorotwell** [comment]
`default` is a decent name.

**Comment by deleugpn** [comment]
The recommendation would be to declare this after all routes, correct?

Given`Route::get('posts/{post}', ...)`, when accessing `/posts/9999999` (any non-existing id) Route Implicit Binding will still throw a 404 which means a different behavior than `/postz/9999999` which would get handled by `default`, correct?

**Comment by sileence** [comment]
@deleugpn exactly, unless I find a way to register the fallback/default route always at the bottom. :| I'd need to see how.

**Comment by deleugpn** [comment]
Another question. Given `Route::post('posts/{post}/comments', ...);` when accessing `GET /posts/1/comments` the default route will have precedence over `MethodNotAllowedException`, correct?

**Comment by deleugpn** [comment]
Actually the Router will match the URL first, which means it will find `Route::post('posts/{post}/comments', ...);` first. I think we will still get `MethodNotAllowedException` for those cases, which begs the question of which behavior we would want.

**Comment by sileence** [comment]
@deleugpn thank you for pointing this potential issue out, I'll have a look into that probably tomorrow.

**Comment by sileence** [comment]
@deleugpn I tested the potential issue and it seems to not be an issue at all. Please have a look.

**Comment by sileence** [comment]
Forcing this route to be added at the end would take several methods / conditionals, I don't need if that's worth it as these kind of routes are usually registered at the end anyway.

**Comment by deleugpn** [comment]
Yeah, I just checked and the URI is matched before the verb. So my first assumption was actually right: registering `default` will prevent you from ever getting `MethodNotAllowedException` on a `GET` request.

I also agree with you on keeping the `default` method simple. Those _points_ that I raised are just more about how to document this. If accepted, let's include it in the documentation these 2 extra pieces of information. (Will prevent MethodNotAllowed and must be registered as the last route).

**Comment by taylorotwell** [comment]
Honestly I think I will hold off on this for now. It's easy to define manually for now.

**Comment by JosephSilber** [comment]
Just to add: when doing a catch-all like that, you usually want to exclude a certain sub-path. For example, when building SPAs, it's common to put all JSON endpoints under an `api` prefix. If you don't, using the wrong route in your AJAX requests will return HTML with a 200 instead of a JSON 404. Good luck debugging that!

Here's what I actually use in my apps:

```php
$router->get('/{all?}', 'HomeController@index')->where('all', '^(?!api).*');
```

This way it's only a catch-all for routes that _don't_ start with `api`. Any non-existent routes under `api` properly return a 404.

**Comment by decadence** [comment]
Wouldn't it be a better idea to make real fallback route that Laravel enables once it can't find any matching instead of emulate this by catch all route?

**Comment by yaronuliel** [comment]
I think that makung it so that `fallback` must be defined last is problamatic - and is too similar to the current solutions.
The whole idea is to have a route that you can define everywhere (e.g. in package), and you don't need to worry about the side effect that it'll cause to other properly defined routes (excluding multiple `fallback` definitions - which will have to follow some precedence rule). This is something that AFAIK cannot be achieved currently with `{any}` route

Moreover, I think that it is necessary to have a way to make the `fallback` method stop execution and return to the regular laravel path (to support 404 and MethodNotAllowed without extra work) - I'd suggest doing that by returning `false` from the callback function

**Comment by devcircus** [comment]
From a SPA perspective using a frontend router, this PR works flawlessly, not sure of other use-cases.

**Pull request closed without merging**
