### PR TITLE
Don't join table if already joined

### PR DESCRIPTION
**Pull request by Whyounes**
`1066 Not unique table/alias` if the table is already joined.

### CODE REVIEW

**Comment by ConnorVG** [comment]
Wouldn't it make more sense to use an alias? Joins can have unique clauses and selects, simply filtering based on the table being joined is quite destructive.

**Comment by Dylan-DPC** [comment]
This is a breaking change.

**Comment by Whyounes** [comment]
@ConnorVG If it supports creating aliases, it would make sense to test over the alias instead of the table. But in this case (which happened to me), I had an SQL error because it joined twice, and I had to use this method before joining.

**Comment by Whyounes** [comment]
@Dylan-DPC I can move it to next version. I just need to know if it suitable to be managed in the builder class automatically. Does it make sense to join two tables twice, like this `select * from "users" left join "photos" on "users"."id" = ? inner join "photos" on "users"."id" = ?`?

**Comment by ConnorVG** [comment]
@Whyounes sure it does. Say you have two morphable types you want to join from one table to two others, the middle table is going to be the same in both instances.

Sure, this would make more sense to be done with eager loading but I'm only using it as an example due to your example having the same bypass.

**Comment by Whyounes** [comment]
I think it can be done with one join where to support both targets. However, I think that aliases should be introduced in this case! Should I close this one?

**Comment by ConnorVG** [comment]
@Whyounes it would need two if the morphables are separate relations with the same morph type, that's the reason of my (terrible) example.

That said, the framework doing this sort of magic on queries would be very bizarre and unexpected; I think it would make more sense for the user to alias or something…

**Pull request closed without merging**
