### PR TITLE
[5.7] Add the option to pass an options array to Storage::url($path, $options)

### PR DESCRIPTION
**Pull request by donkfather**
Some services have the option to receive some modifiers when retrieving the url. For example Cloudinary which I am struggling with now has the option to generate a url with transformations. 

I tried to find a better way but couldn't find one. I am even opened to overwrite FilesystemAdapter locally but i didn't find a way.

### CODE REVIEW

**Comment by driesvints** [comment]
This is a breaking change to the contract. Please send this to master.

**Comment by Donkfather** [comment]
@driesvints I've changed the base to master.

**Comment by driesvints** [comment]
Please don't use branch changing on Github. There's currently a bug in Github that sometimes causes commits to not appear in the history log of a PR. Please send in a new PR.

**Comment by devcircus** [comment]
I just finished creating my own TransformationGenerator and UrlGenerator for use with Cloudinary.  Something like this would be nice if it is fleshed out and tested.

**Comment by Donkfather** [comment]
@driesvints i didn't know. will do it now :smile:

**Pull request closed without merging**
