### PR TITLE
when run php artisan make:model,we wish it can be placed in app/Models

### PR DESCRIPTION
**Pull request by wanyuan**
when run php artisan make:model,we wish it can be placed in app/Models

### CODE REVIEW

**Comment by lukasgeiter** [comment]
This is totally not needed. Just call the command like this:

    php artisan make:model Models\User

**Comment by RomainLanz** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
> we wish it can be placed in app/Models

No we don't. Out of the box, that structure is not used.

**Comment by wanyuan** [comment]
why? i think it placed together in a box is beautiful

**Comment by franzliedke** [comment]
Laravel doesn't enforce any conventions in this regard (just make the class PSR-4 loadable), which is even more beautiful. ;)

**Pull request closed without merging**
