### PR TITLE
[5.1] Add force parameter to language has function

### PR DESCRIPTION
**Pull request by bobbybouwmann**
Add force parameter to language has function so we can truely check if the translation exists

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The interface will need updating on 5.2 too.

**Comment by GrahamCampbell** [comment]
Maybe `fallback` as a boolean would be better?

**Comment by bobbybouwmann** [comment]
You mean `$fallback` instead of `$forceLocal` and then set it default to true? 

I will update it in one go, so I wait with changing for your answer ;)

**Comment by GrahamCampbell** [comment]
> There is no interface on the Translator class which implements the has or get function?

Ok then. :)

> You mean $fallback instead of $forceLocal and then set it default to true?

Yeh. :)

**Comment by bobbybouwmann** [comment]
@GrahamCampbell Done ;)

**Comment by taylorotwell** [comment]
How does this change the behavior? Isn't it just doing exactly what it did before this PR?

**Comment by zlatevbg** [comment]
The issue is first described here: https://github.com/laravel/framework/issues/10718

**Comment by taylorotwell** [comment]
I know that but what I'm saying is how does your PR change any behavior? You added a new default param which is "true" but when it's true it just does the behavior it did before.

**Comment by taylorotwell** [comment]
I also don't like that the user would have to pass `false` here. It's not expressive as to what's happening.

**Comment by taylorotwell** [comment]
Added new method `hasForLocale`.

**Comment by bobbybouwmann** [comment]
Thanks Taylor! You indeed have a better solution

**Pull request merged**
