### PR TITLE
[5.5] Improved mysql drop all tables

### PR DESCRIPTION
**Pull request by lkmadushan**
- Reduce the sql queries when dropping all mysql tables

### CODE REVIEW

**Comment by srmklive** [comment]
I think this needs to replicated for PostgreSQL, SQLServer & possibly Sqlite as well.

**Comment by lkmadushan** [comment]
@srmklive it's already done :)

**Comment by taylorotwell** [comment]
It already works though and there is no description of how this improves things with examples of the queries.

**Comment by lkmadushan** [comment]
@taylorotwell Current implementation run N queries when database has N number of tables. This PR only run 2 queries to drop all tables.

Queries:

```
SHOW FULL TABLES WHERE table_type = 'BASE TABLE
DROP TABLE alpha,beta,gamma
```

**Pull request closed without merging**
