### PR TITLE
[8.x] Add `updateOrFail` method to `Model`

### PR DESCRIPTION
**Pull request by caugner**
The `updateOrFail()` method makes it more convenient to handle update errors in update actions, as it is less verbose than checking the return value of `update()`.

### CODE REVIEW

**Comment by crissi** [comment]
sql drivers always throw an exception? what driver are you using?

**Comment by caugner** [comment]
@crissi I'm using the MySQL driver, but what is the difference between `save()` and `saveOrFail()` if both throw an Exception?

**Comment by crissi** [comment]
I see... did not know saveOrFail or existed.

**Comment by caugner** [comment]
The PHPDoc confirms my assumption that `saveOrFail()` throws, while `update()` doesn't:

https://github.com/laravel/framework/blob/6de01746680d7bc7e239b20ec5cdfe70ce586235/src/Illuminate/Database/Eloquent/Model.php#L864-L871

https://github.com/laravel/framework/blob/6de01746680d7bc7e239b20ec5cdfe70ce586235/src/Illuminate/Database/Eloquent/Model.php#L986-L994

**Comment by caugner** [comment]
Note: `saveOrFail()` was added in #11202.

**Comment by willrowe** [comment]
I just went down the rabbit hole trying to use `saveOrFail` to replace something like this:
```php
if (!$model->save()) {
    throw new ModelNotSavedException();
}
```
with something like this:
```php
$model->saveOrFail();
```

I expected `saveOrFail` to function just like most of the other `*OrFail` methods (`findOrFail`, `firstOrFail`, `getOrFail`, etc.), which do some sort of check and then throw an exception if the expected condition is not met.
However, after diving into the code and finding the [original PR](https://github.com/laravel/framework/pull/11202), it appears that was never the intended functionality of the `saveOrFail` method. It actually just wraps the `save` call itself in a transaction, but does not "fail" on any conditions, just rolls back all queries if something else "fails".

I found this PR when looking at the `updateOrFail` and `deleteOrFail` methods that were added after `saveOrFail` and based on the description of this PR especially, it seems that both `updateOrFail` and `deleteOrFail` were added with the same assumption that I had about what the `saveOrFail` method would do:
> as it is less verbose than checking the return value of update().

@caugner can you confirm whether you intended for the `updateOrFail` and `deleteOrFail` methods to actually throw exceptions if `false` was returned from the call or just wrap the underlying calls in transactions?

**Pull request merged**
