### PR TITLE
[6.x] PHPUnit 9 support

### PR DESCRIPTION
**Pull request by GrahamCampbell**
### Why Laravel 6 and not 7?

It is highly likely that PHPUnit 8 won't work in at least one of PHP 8.0, 8.1, 8.2, or 8.3. Since Laravel 6.0 is LTS, it is likely that we will want to continue to support newer versions of PHP, and so we need to be able to run on the latest PHPUnit.

### Why use `graham-campbell/testbench-core`?

PHPUnit 8 deprecated `assertArraySubset` and Laravel ported the code over, but in PHPUnit 9, this port no longer works. Much more work is needed for PHPUnit 9, and moreover, the code for PHPUnit 9 won't work in PHPUnit 8 due to difference interfaces. Luckily, we can use my testbench core package, which handles this mess.

NB There does exist another package that backports `assertArraySubset`, but it appears to be abandoned already, and doesn't work on PHPUnit 9.

### Why the branching code in `src/Illuminate/Foundation/Testing/Assert.php`?

In order to maintain BC, if people are using PHPUnit 8, we use Laravel's existing code. There are 3 cases to consider:

1. If `graham-campbell/testbench-core` is installed, always use its implementation.
2. If not installed and we are on PHPUnit 8, use Laravel's existing backport.
3. If not installed and we are on PHPUnit 9, then we throw an exception whenever someone tries to use the method.

### What to do in Laravel 7?

Perhaps we should remove Laravel's internal backport entirely, and depend on my testbench core package? This PR doesn't deal with that.

### CODE REVIEW

**Comment by mfn** [comment]
Just wanted to voice that I praise the forward thinking to support "at some point older Laravel version with newer dependencies", especially for PHPUnit.

I've experienced this myself that sometimes the Laravel upgrade can't be performed in a timely manner (big project, big dependencies, inferior test suite, etc.) but it's still nice to be able to use newer versions of the dependent libraries, if it's only to already _prepare as much as possible_ before the actual upgrade.

So, thanks 👍

**Comment by driesvints** [comment]
Can't we just require `graham-campbell/testbench-core` in the "require" dependencies and remove the if statement?

**Comment by GrahamCampbell** [comment]
> Can't we just require graham-campbell/testbench-core in the "require" dependencies and remove the if statement?

I was planning on adding this to the default laravel/laravel require-dev in 7.x.

**Comment by GrahamCampbell** [comment]
> Can't we just require graham-campbell/testbench-core in the "require" dependencies and remove the if statement?

The other problem with doing this is that people end up with testbench-core when they didn't want dev deps.

**Comment by driesvints** [comment]
@GrahamCampbell but your package has 0 dependencies and just a handful of classes? I can't see how that would be a bad thing.

**Comment by GrahamCampbell** [comment]
My package does actually depend on phpunit. It just isn't listed as an explicit dependency, to account for people possibly wanting phpunit as a phar. I wouldn't recommend loading my package without phpunit, otherwise autoloading some of the classes will crash the interpreter.

**Comment by GrahamCampbell** [comment]
In particular, I'd expect it to cause problems with preloading.

**Comment by GrahamCampbell** [comment]
TBH, I think it's fine not to require it. Like, we don't require mockery or phpunit within the framework. :)

**Comment by bakerkretzmar** [comment]
@GrahamCampbell just to clarify, does this change mean that with PHPUnit 9 we should always import `Illuminate\Foundation\Testing\Assert` and call `Assert::assertArraySubset`?

I upgraded to PHPUnit 9 and installed `graham-campbell/testbench-core` and that works, but `$this->assertArraySubset()`, `self::assertArraySubset()`, and `static::assertArraySubset()` don't.

Thanks!

**Comment by GrahamCampbell** [comment]
No, you don't need to install my testbench package anymore.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/pull/30989 and https://github.com/laravel/framework/pull/31113 were subsequently merged.

**Comment by GrahamCampbell** [comment]
> $this->assertArraySubset(), self::assertArraySubset(), and static::assertArraySubset() don't.

Yes, they were never intended to work. 

> @GrahamCampbell just to clarify, does this change mean that with PHPUnit 9 we should always import Illuminate\Foundation\Testing\Assert and call Assert::assertArraySubset?

Actually, no. Laravel has included this code actually just for its own internal use. It is intended that you change your own tests to not use this deprecated PHPUnit functionality, or stay on PHPUnit 8 if you don't want to change your code.

**Comment by GrahamCampbell** [comment]
So, just to be clear, the laravel Assert class is internal. It should not be called by your tests directly.

**Comment by GrahamCampbell** [comment]
This is why this change has not been mentioned in the docs. It is strictly an internal change to allow laravel's testing internals to call this code that is no longer in phpunit.

**Comment by GrahamCampbell** [comment]
If you want to call it in your own code, you can use my testbench package, actually. My package is designed for your use case.

**Comment by GrahamCampbell** [comment]
Directly pull in my package's trait.

**Comment by bakerkretzmar** [comment]
@GrahamCampbell sounds good, thanks a lot!

**Pull request merged**
