### PR TITLE
[5.8] Remove Arr::wrap

### PR DESCRIPTION
**Pull request by imanghafoori1**
Since the concrete is not going to an object, native type casting of the language will do the job.
No need to import anything.

### CODE REVIEW

**Comment by driesvints** [comment]
You seem to have two unwanted commits on your branch. Please branch off from an updated 5.8 branch and try to submit again.

**Comment by imanghafoori1** [comment]
No they are merge commits

And they are excluded by github when it counts ontribution commits. 

They are there because I have synchronized my fork with laravel updates

**Comment by driesvints** [comment]
@imanghafoori1 if you branch off from 5.8 instead you get a clean history on your pr. This way unnecessary commits are merged onto the main branch.

**Comment by imanghafoori1** [comment]
image

I have actually branched off,
I know what you mean, but this commits are not of those you have in mind.

Merge commits happen because I have update my fork by creating a pull request from laravel to my fork every now and then. And they do not show up in the commit history of laravel.

**Comment by imanghafoori1** [comment]
@driesvints I have branched of from an older commit before the merge commits
but inevitably those merge commits will appear in future.

image

please consider the verified badge

**Comment by mfn** [comment]
I'm with @driesvints , it's distracting and shouldn't be necessary for just a few lines of changes.

**Comment by imanghafoori1** [comment]
They are inevitable, normal process of git. (for those who create PR from their forks and do not have direct access to the repo)
Git they are auto-ignored by git.
No way to avoid them.

**Comment by imanghafoori1** [comment]
Technically the only way to avoid them is not delete my fork repository after each and every accepted PR and create a new fork. which is not standard.

**Comment by driesvints** [comment]
It's only noise for us to review. Plus these commits get merged into the base branch and are only noise in the commit history of the project. A PR with just the commits that are meant to be merged in is easier for us to process. What you want to do is:

1. fork this repo
2. clone fork locally
3. add this repo as an extra remote
4. branch off from the 5.8 branch of **this** repo
5. do changes and add commits
6. push the new branch to your fork
7. submit the pr to this repo
8. pr gets accepted: delete branch locally and on your fork

New pr: start again from step 4.

**Comment by imanghafoori1** [comment]
@driesvints This is right, I always do these steps exactly.
But as the step 9
I have to create a PR from laravel/framework to imanghafoori1/framework to synchronize my fork with the latest update of laravel/framework branch 5.8

these extra `Merge pull request #23 from laravel/5.8 ` are the result of step 9.

And do not worry they do NOT show up in your history.
for example this PR : https://github.com/laravel/framework/pull/27762/commits
includes a merge commit mith message `sbgs` .

Is there any commit with `sbgs`  message in your history ?!

**Comment by driesvints** [comment]
> Is there any commit with sbgs message in your history ?!

Yes there is:

screen shot 2019-03-05 at 13 04 16

screen shot 2019-03-05 at 13 03 46

These commits are only noise in the project's history. 

I think you're confused about how to pull in the latest changes from the origin repo. I've added an extra step above to clarify. Hope that's more clear.

**Comment by imanghafoori1** [comment]
Thanks for your reply. 
I search to find a remedy.

**Comment by imanghafoori1** [comment]
I alway delete the merged branches immediately .  It does not work

**Comment by mfn** [comment]
>  I have to manually create a PR from `laravel/framework` to `imanghafoori1/framework` and accpet it, in order to synchronize my fork with the latest update of laravel/framework branch 5.8

You just use your favorite local `git` tool and sync it changes from laravels repo into yours via the `origin`, there's really no need to use GH for that; as you said yourself, it's just standard git.

Your local branch referencing the laravel origin and the framework should _never_ have the need for merge commits, only fast forwards: you should never write to it except in your branches.

**Comment by imanghafoori1** [comment]
@mfn

I think your solution should work
Thank you very much Markus
I will try it.

**Pull request closed without merging**
