### PR TITLE
[11.x] MySQL transaction isolation level fix

### LINKED ISSUE #50688: Using transaction isolation level breaks the whole database connection
### Laravel Version

11.0.7

### PHP Version

8.3.3

### Database Driver & Version

MySQL 8.0+

### Description

Since merging https://github.com/laravel/framework/pull/50044, it's no longer possible to specify the transaction isolation level for a (MySQL) connection. The code now bundles all the "SET" statements, but that causes wrong syntax:

```
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED, NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci', SESSION sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
```

Which causes the following exception:
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci', SESSION sql_mode='ONLY_FULL_GROU' at line 1`

The transaction isolation level must apparently be set in a separate statement to actually work.

### Steps To Reproduce

Configure a (MySQL) database with isolation level, like:

```
      'replica' => [
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'database' => env('DB_DATABASE', 'forge'),
            'driver' => 'mysql',
            'engine' => 'innodb',
            'host' => env('DB_REPLICA_HOST', env('DB_HOST', '127.0.0.1')),

            // This currently does not work
            'isolation_level' => 'READ UNCOMMITTED',

            'password' => env('DB_PASSWORD', ''),
            'port' => env('DB_PORT', '3306'),
            'prefix' => '',
            'prefix_indexes' => true,
            'sslmode' => env('DB_SSLMODE', 'require'),
            'strict' => true,
            'unix_socket' => env('DB_SOCKET', ''),
            'username' => env('DB_USERNAME', 'forge'),
        ],
```

and run any command using that connection, like `User::connection('replica')->all()`.

### PR DESCRIPTION
**Pull request by mwikberg-virta**
Should fix #50688

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Or even the tests show this running `SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ, NAMES 'utf8' COLLATE 'utf8_unicode_ci';`.

**Comment by GrahamCampbell** [comment]
What version of mysql are you using?

**Comment by GrahamCampbell** [comment]
Oh man, it does seem the transaction isolation level is a special beast. I'm going to propose a different fix.

**Comment by mwikberg-virta** [comment]
8.3. The current code concatenates all the "SET" statement into a single statement, which does not work for the isolation level.

`SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED, NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci', SESSION sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';`

This results in a SQL error: 
`[2024-03-20 15:50:14] [42000][1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci', SESSION sql_mode='ONLY_FULL_GROUP_' at line 1`

**Comment by mwikberg-virta** [comment]
Setting only the `NAMES` and `sql_mode` works just fine in a single statement

**Comment by mwikberg-virta** [comment]
Anyhow, any fix that works fine is appreciated. Just bumped into this while checking the requirements to upgrade a project to 11.x and this at least made the tests pass

**Review by GrahamCampbell — APPROVED** [review]
I agree this looks correct, after digging around. It seems MySQL implemented transaction isolation level differently to everything else, it's the one thing I didn't manually test, and its rarely used which is why we managed to get this far with nobody noticing.

**Review by GrahamCampbell — APPROVED** [review]

**Comment by mwikberg-virta** [comment]
Assumed that it's not a widely used scenario, and it's mostly only used while running tests in our case (where we kindof need to see the uncommitted data, as all tests run in a transaction)

**Comment by GrahamCampbell** [comment]
> and it's mostly only used while running tests in our case (where we kindof need to see the uncommitted data, as all tests run in a transaction)

You run multiple php processes that both need the same data? Transactions can read their own writes without changing the isolation level. Moreover, the uncommitted isolation level makes it possible for transactions to not actually be able to read their own writes in some situations.

**Comment by mwikberg-virta** [comment]
Let's just say "it's complicated". There are several systems involved and some of the tests are more if the integration test kind, where a different component in a separate thread/container/whatever expects the data to be in the DB (which it will not be, as the original transaction is not committed). Then again, setting the default DB value to `READ UNCOMMITTED` would break other tests, which again rely in the transactional behavior being "as expected".

**Pull request merged**
