### PR TITLE
[9.x] Allow disabling checks for expired views

### PR DESCRIPTION
**Pull request by browner12**
One of the changes @nunomaduro made in #44487 reminded me of a similar PR (#31206) I'd done about 2 years ago that was merged and then reverted due to a reported edge case bug.

The reported bug was that the `view:cache` was not correctly caching registered vendor views. I wish I'd have looked closer 2 years ago, because I've been testing all day, and everything seems to be working well to me, and I can't find any noticeable change in the framework that would've changed this behavior.

With that said, this is a resubmission of that original PR (#31206), with essentially no changes.  This change takes Nuno's optimization on compiled views a step further. The root of the problem is the `$this->compiler->isExpired($path)` method is a relatively expensive call, and it can get called a **large** number of times if:

1. you have a large number of views/components necessary for the page rendering
2. you render the same view/components multiple times on the page 

So the goal is to avoid unnecessary calls to `isExpired()`. Nuno's change in #44487 solves scenario 2 by building up a local cache of file paths already compiled, and then checking for the path value in the array on subsequent calls.  The changes in this PR actually solve both scenarios because you can now explicitly tell the `CompilerEngine` to never check if the path is expired and to assume the file is compiled validly.  This is intended to be a ***production only*** feature, and will only work if you run `php artisan view:cache` as part of your deployment.

So to start, could I first get a little confirmation from others that vendor registered views are being compiling with `artisan view:cache`. After that the PR should be good to review.

Check out the previous PR for the performance improvement data.

### CODE REVIEW

**Comment by taylorotwell** [comment]
How does this address the issues we had with the original PR?

**Review by milwad-dev — COMMENTED** [review]
👍

**Comment by browner12** [comment]
Temporarily converting to draft while I figure out the best course forward for the edge cases.

**Comment by driesvints** [comment]
Hi there. We fixed the failing tests on 9.x which are causing this PR to fail as well. Can you please rebase your PR with 9.x? Thanks

**Comment by driesvints** [comment]
@browner12 feel free to resend this once you've figured out a way forward here. Thanks.

**Pull request closed without merging**
