### PR TITLE
[6.x] Add ability to change notification type

### PR DESCRIPTION
**Pull request by osbre**
## This allows you to set your own type in the type column.

**Why is it better?**

Namespaces can change, for example, when moving files, and then working with these types in database, may not work properly, and with their own types - there will be no problems.

It is motivating to looks like [custom-polymorphic-types](https://laravel.com/docs/6.0/eloquent-relationships#custom-polymorphic-types)

Note: This is my first pull-request, thanks for any review or reply.

### CODE REVIEW

**Comment by mfn** [comment]
IMHO if customization is needed you should create your own channel and use that (I believe in your case it can even extend the built-in one and add the type you need).

👎 on the PR

**Comment by taylorotwell** [comment]
See above comment.

**Comment by mrcat323** [comment]
# Good Job :ok_hand:

**Comment by osbre** [comment]
If someone needs this functionality, use your own channel:

https://gist.github.com/osbre/aee72ff8ce64d3daaec0f35c7dd445f6

**Pull request closed without merging**
