### PR TITLE
[5.5] Add "strict" option for numeric validation rule

### PR DESCRIPTION
**Pull request by pschmidt88**
The `numeric` validates successful for values like `NAN` and `INF`. Although these are valid numeric values by specification, i think it's more intuitive when the validator fails for these values.

This PR adds an optional "strict" option to the `numeric` rule.

```php
Validator::make(['value' => 'numeric:strict']);
```

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
This is a breaking change.

**Comment by paulofreitas** [comment]
This would be really nice to have. 👍 

Note that as Dylan noted this should go to the `master` branch just because it changes the method signature. You can change the base branch yourself by editing the pull request. 😄

**Comment by pschmidt88** [comment]
Ok, did not think about that, but you are right.
I will need to open a new PR for that.

**Comment by jmarcher** [comment]
You need to rebase your branch to avoid that extra commits.

**Comment by sisve** [comment]
How does the name "strict" make sense at all? The INF and NAN are valid numeric values in php, how can any definition of "stricter comparison" point away from the existing language rules?

    var_dump(is_numeric(INF)); // true
    var_dump(is_numeric(NAN)); // true

The described functionality validates that the value is a [real number](https://en.wikipedia.org/wiki/Real_number), not any kind of numerical/comparison strictness.

**Comment by taylorotwell** [comment]
this seems to have a lot more changes than what you described.

**Comment by deleugpn** [comment]
Fork the master branch and apply your changes straight there.

**Pull request closed without merging**
