### PR TITLE
#8629 - Add symofny/var-dumper dependency to composer

### PR DESCRIPTION
**Pull request by Douglasdc3**
Fix for https://github.com/laravel/framework/issues/8629

### CODE REVIEW

**Comment by taylorotwell** [comment]
We don't require it since it's just use for 1 single function.

**Comment by underparnv** [comment]
Would you be opposed to at least listing a note next to the dd documentation that if you are utilizing illuminate/support outside of Laravel you should include this package should you want to utilize this function?

**Comment by GrahamCampbell** [comment]
This needs to go in the composer suggest block.

**Comment by GrahamCampbell** [comment]
You should always refer to the list of suggested packages composer gives you on install over any documentation.

**Comment by Douglasdc3** [comment]
@GrahamCampbell do you want a PR to add this to the suggested block?

**Comment by brendo** [comment]
I'm here from #8707 

> @brendo Please actually read the list of suggested packages gives to you on install...

@GrahamCampbell That was exactly my point, the `symfony/var-dumper` is _not_ mentioned in the composer.json file at all. It's not in the `require` section, nor is it in the `suggested` section, it's totally omitted from both [`illuminate/support`](https://github.com/illuminate/support/blob/master/composer.json) and [`illuminate/database`](https://github.com/illuminate/database/blob/master/composer.json).

@taylorotwell has said it won't be added to `require` since it's only required for a single function, and that's fair enough, but shouldn't it be at least added to the `suggested` block or documented somewhere?

**Comment by GrahamCampbell** [comment]
> That was exactly my point, the symfony/var-dumper is not mentioned in the composer.json file at all.

Ohh, ooops. It should be in the illuminate/support suggest block. Thank you for catching this guys. :)

**Comment by brendo** [comment]
No worries, thanks!

**Pull request closed without merging**
