### PR TITLE
[5.2] Command::hasOption

### PR DESCRIPTION
**Pull request by CupOfTea696**
Checks if the option flag with a key has been passed to the command, regardless of any value that may or may not be set of the option. This can be used the distinguish between `command`, `command --option` and `command --option=value`.

This is an implementation of the issue raised in symfony/symfony#12773.
If the PR mentioned above is merged this could easily be modified to make use of the native symfony/symfony method.

Usage:

``` php
if ($this->hasOption('github') {
   $repo = $this->option('github') ?: $this->argument('name');

   // Create repo named $repo through github API
}
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by CupOfTea696** [comment]
@GrahamCampbell care to explain why?

**Comment by GrahamCampbell** [comment]
As you pointed out, there's a symfony issue here. We don't want to create a conflicting implementation. Just fix it on symfony, then laravel will inherit the change.

**Comment by CupOfTea696** [comment]
It's still a shortcut to do this directly from the command rather than having to get the `InputInterface` first. In the same way `Command::option` exists. But fair enough.

**Comment by GrahamCampbell** [comment]
Thanks for the suggestion anyway. :christmas_tree:

**Pull request closed without merging**
