### PR TITLE
[5.3] Apply global to email addres to CC and BCC

### PR DESCRIPTION
**Pull request by MrAtiebatie**
As I was testing I noticed that the emails I was sending with Laravel were sent to the BCC address I provided. Unfortunately this wasn't the global "to email address" I set in the `config/mail.php`

I have created this pull request to fix this issue. I hope this will be merged because that's the way how I interpreted "global to address" and I think I'm not the only one. Correct me if I'm wrong!

### CODE REVIEW

**Comment by taylorotwell** [comment]
Makes sense to me.

**Comment by juukie** [comment]
So, if you have 
~~~
'to' => ['address' => 'foo@example.com', 'name' => ''],
~~~
in your `config/mail.php`, previously added recipients will be overridden? Seems strange to me.

@MrAtiebatie you said the mail was sent to the BCC address you had provided. But you wanted it to be send only to `foo@example.com`? I can only imagine it's handy when you want to make sure mail won't be sent to other addresses, when testing for example. Otherwise I wouldn't know why you would override recipients that might have been added before.

For example; when I'm having a form to request a testproduct, I often add the 'from' address as a BCC to the _Thanks for your _request_ message that would be sent to the visitor.
In local env I test this with Mailcatcher to make sure the message is send to both the visitor and the 'from' address. 
With the 'to' address set I would only see one message sent to that address?

**Comment by devcircus** [comment]
that is indeed the purpose of the 'Universal To' address. To have a single email address to send all mail to in development. If you'll be sending mail to users in production, do not utilize the 'Universal To'.
[Laravel Mail Docs](https://laravel.com/docs/5.3/mail#mail-and-local-development)

**Comment by Gibbs** [comment]
Is there a way to disable this in an application? The mail service I'm using (SendGrid) doesn't allow duplicate emails.

**Comment by ArtbyArjan** [comment]
@devcircus 
> that is indeed the purpose of the 'Universal To' address. To have a single email address to send all mail to in development. If you'll be sending mail to users in production, do not utilize the 'Universal To'.
[Laravel Mail Docs](https://laravel.com/docs/5.3/mail#mail-and-local-development)

It would probably couldn't hurt to add this to the Mail Docs, because it's not clear right now.
I came here because I was using the 'Universal To' and noticed that I every email sent, also had a CC with the same address. 

Could it be a bug that an e-mail has a 'To' and a 'CC' when using 'Universal To' in `config/mail.php?`

**Comment by quiquegarcia** [comment]
This is coffusing even in documentation, many of our team it was thinking that

Something like this enables Universal To:
```php
Mail::cc('hello2@example.com')
    ->send(new Mailable($data);
```

And this by pass Universal To:
```php
Mail::to('hello@example.com')
    ->cc('hello2@example.com')
    ->send(new Mailable($data);
```

**Pull request merged**
