### PR TITLE
[5.1] Update "artisan serve" to optionally open site in browser

### PR DESCRIPTION
**Pull request by davestewart**
I usually have small .bat file I copy from project to project which does a PHP -S and opens the browser, but since discovering "php artisan serve" I missed automatically opening the site.

This PR adds that functionality for Windows and Mac. Unfortunately I don't know the command for linux, but that can be easily added to the array.

A bit less faffing when just wanting to run tutorials or test stuff quickly :)

### CODE REVIEW

**Comment by davestewart** [comment]
Ah. Sorry that failed. Unfortunately I don't know enough amending PRs to know what to do next.

**Comment by rkgrep** [comment]
:-1: Laravel is not only for browser apps.

**Comment by GrahamCampbell** [comment]
:-1: from me too.

**Comment by GrahamCampbell** [comment]
Also, please fix the CS as highlighted by StyleCI.

**Comment by davestewart** [comment]
Any reason for the close?

**Pull request closed without merging**
