### PR TITLE
Added test-segments to DatabasePostgresSchemaGrammarTest and DatabaseMySqlSchemaGrammarTest to test for issue #7484.

### PR DESCRIPTION
**Pull request by shehi**
Added test-segments to DatabasePostgresSchemaGrammarTest and DatabaseMySqlSchemaGrammarTest to test for issue #7484.

Rephrase of the bug, since the original issue was closed:

> Following Schema Builder code line, written for primarily MySQL:
> $table->mediumInteger('id', true, true);
> doesn't behave as expected when Db-driver is changed to PgSQL. Instead of creating a Not-Nullable PRIMARY INTEGER column, it just creates simple Not-Nullable INTEGER column which is not PRIMARY. Could this bug be fixed in upcoming dev-master release?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Tests failing.

**Comment by shehi** [comment]
So, from changed lines, you can see that I added two checks to ```testAddingMediumInteger()``` methods of both tests. MySQL one actually passes OK, however, as expected, PgSQL one fails the test: it adds the column as a regular integer field/column. 

I will add more lines for other integer-types. Will be referring to http://en.wikibooks.org/wiki/Converting_MySQL_to_PostgreSQL#Data_Types for type relations.

**Comment by shehi** [comment]
Of course they are @GrahamCampbell . The purpose of this pull request is to replicate the bug.

**Comment by GrahamCampbell** [comment]
Yeh, I realized this after commenting, and added the bug label as you can see. :)

**Comment by shehi** [comment]
So, with this latest commit, I added similar tests for tinyInt, smallInt and bigInt types.

Postgres has ```smallserial``` type, ranging between 0-65k, so I used it for tinyInt type. Again, MySQL counterparts are OK. Only Postgres side of things fail.

**Comment by GrahamCampbell** [comment]
Ok, thanks. Taylor will get to this probably within a week.

**Comment by shehi** [comment]
I attempted to fix the issue :) So far tests pass in my side. Let's see what Travis says. Please review my fix and merge if appropriate. I really need this issue fixed asap for my own project.

**Pull request merged**
