### PR TITLE
[5.0] Allow constructorless commands

### PR DESCRIPTION
**Pull request by antonioribeiro**
If we don't have anything else to do in a command constructor than set the object properties, we could just write

```
class PurchasePodcast extends Command implements SelfHandling {

    public $user, $podcast;

    /**
     * Execute the command.
     *
     * @return void
     */
    public function handle()
    {
        // Handle the logic to purchase the podcast...

        event(new PodcastWasPurchased($this->user, $this->podcast));
    }

}
```

Instead of 

```
class PurchasePodcast extends Command implements SelfHandling {

    protected $user, $podcast;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct(User $user, Podcast $podcast)
    {
        $this->user = $user;
        $this->podcast = $podcast;
    }

    /**
     * Execute the command.
     *
     * @return void
     */
    public function handle()
    {
        // Handle the logic to purchase the podcast...

        event(new PodcastWasPurchased($this->user, $this->podcast));
    }

}
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
Too magic for me :)

**Comment by antonioribeiro** [comment]
I understand, but Dispatcher is not exactly magic free, Laravel itself is far from being magic free. :P

The real difference between the current dispatcher code and the new one is only:

```
$instance = $reflection->newInstanceWithoutConstructor();

foreach($reflection->getProperties(ReflectionProperty::IS_PUBLIC) as $parameter)
{
    $instance->{$parameter->name} = $this->getParameterValueForCommand($command, $source, $parameter, $extras);
}
```

The problem is that we repeating, over and over, the same "useless" code on Commands, on big forms things are ugly and waste of resources:

```
<?php

namespace ConsultorioDigital\Services\Events\Commands;

use PragmaRX\Sdk\Core\Bus\Commands\SelfHandlingCommand;
use ConsultorioDigital\Services\Events\Data\Repositories\Event as EventRepository;

class UpdateEventCommand extends SelfHandlingCommand {

	public $id, $user, $client_id, $office_room_id, $title, $description, $start,
			$end, $updated_start, $updated_end, $full, $color;

	function __construct($client_id, $description, $end, $id, $office_room_id, $start,
							$title, $updated_end, $updated_start, $user, $full = false,
							$color)
	{
		$this->client_id = $client_id;
		$this->description = $description;
		$this->end = $end;
		$this->id = $id;
		$this->office_room_id = $office_room_id;
		$this->start = $start;
		$this->title = $title;
		$this->updated_end = $updated_end;
		$this->updated_start = $updated_start;
		$this->user = $user;
		$this->full = $full;
		$this->color = $color;
	}

	public function handle(EventRepository $repository)
	{
		return $repository->updateEvent($this->getPublicProperties());
	}

}
```

Which could be reduced to:

```
<?php

namespace ConsultorioDigital\Services\Events\Commands;

use PragmaRX\Sdk\Core\Bus\Commands\SelfHandlingCommand;
use ConsultorioDigital\Services\Events\Data\Repositories\Event as EventRepository;

class UpdateEventCommand extends SelfHandlingCommand {

	public $id, $user, $client_id, $office_room_id, $title, $description, $start,
			$end, $updated_start, $updated_end, $full, $color;

	public function handle(EventRepository $repository)
	{
		return $repository->updateEvent($this->getPublicProperties());
	}

}
```

**Comment by kirkbushell** [comment]
How is it determining what the properties mean and what they equate to?

I can see that in the example you'er expecting them to be a User and Podcast object - what makes them so?

I agree with @taylorotwell this is a little bit too much magic, and imho breaking what is otherwise a readable and understandable pattern.

Anyone writing commands currently on Laravel 5 will know what they're doing or at least figure it out if they haven't seen a command pattern before. What you're advocating removes that intuitive process completely.

**Comment by antonioribeiro** [comment]
I'm not removing the process, I'm adding functionality to it. It first checks if the constructor is present and uses it, but falls back to the class public properties in case the coder has decided to not create a constructor.

Properties are set by name, if your request and command have the very same input/property name, that command property will receive the value of the input. It is already like that, the difference is that currently it uses the constructor parameters names, instead of the properties directly.

**Comment by Addvilz** [comment]
I am sorry, but you are adding one more "paths" on how to do things, this improves nothing.

1. These properties should not be public, as they are not part of the public API;
2. This is magic (does the property exists?);
3. How do you enforce type?;
4. How do you determine state of the object - initialized with dependencies or what...?;

Last, but not least, you example seems weird by itself - why all those variables, not single Entity container for that particular entity type? If I understand your example correctly, you are trying to solve a problem that is not there.

**Comment by JesseObrien** [comment]
-1 Too much reflection magic. This is not behaviour anyone would expect.

**Pull request closed without merging**
