### PR TITLE
[9.x] serialize selected model attributes on the queue job

### PR DESCRIPTION
**Pull request by mohamed-samir907**
This PR adds support to respect selected columns in the model when serialize/unserialize in the queue.

Problem:
We have tables that have JSON columns that store huge data. and when we want to get any row we just pick the fields we want and send the model to the queue
```php
$store = Store::select('id','domain')->find(1);
FetchStoreProducts::dispatch($store);
```

the problem is when Queue unserialize that it will do the query as `select * from stores ...` instead of `select id, domain from stores ...`

So this PR would fix it to do queries as expected.

### CODE REVIEW

**Comment by themsaid** [comment]
My only concern with this is that it'll increase the payload size since all model attributes names has to be stored inside the payload. 

I think most apps load all model attributes. This means for all those apps, the job payload size will increase for no good reason.

For your specific use case, you can simply pass the model identifier to the job, instead of the model instance, and then load the model from the DB inside the `handle()` method manually with the attributes you need.

**Comment by ionutantohi** [comment]
I guess most apps expect that the model has all attributes from the database inside the job. If for some reason the model was fetched with fewer attributes before is dispatched, those jobs will fail. 

Also is the time concern. If a job is picked up by a worker after some time, the job will run with old/cached data and not fresh from database.

**Comment by driesvints** [comment]
I also agree with @themsaid. I think it's best that for your edge case that you use a different way to serialize these models like @themsaid indicated. Doesn't seems reasonable to first hydrate the model like this: `$model = $value->first();`. The impact across apps who use thousands and thousands of these queued jobs will be gigantic.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
