### PR TITLE
[7.x] Make `StorageLinkCommand` dynamic

### PR DESCRIPTION
**Pull request by browner12**
This PR gives the programmer the ability to define all the links they would like created in their application programmatically. Links and their targets are defined in the `config/filesystems.php` file.

```php
'links' => [
    public_path('storage') => storage_path('app/public'),
    public_path('images') => storage_path('app/images'),
],
```

If this PR is accepted I will make necessary changes in `laravel/laravel`.

### CODE REVIEW

**Comment by shadoWalker89** [comment]
You already submitted this before and was rejected https://github.com/laravel/framework/pull/26194

**Comment by browner12** [comment]
oh really? thanks

**Comment by taylorotwell** [comment]
I think the configuration should have a default value of the current storage link to make upgrading easier since it would be optional for people to add it to their configuration.

**Comment by browner12** [comment]
Sure thing, one sec.

**Comment by shadoWalker89** [comment]
@browner12 @taylorotwell How about instead of adding this new config `links`, each local disk would have a new config option called `public_path` or something like that. and the command would scan the configuration for any local drivers and link them ?

**Comment by taylorotwell** [comment]
@shadoWalker89 not a big fan of that idea.

**Pull request merged**
