### PR TITLE
[5.2] Added updateAll method

### PR DESCRIPTION
**Pull request by acasar**
As requested here: https://github.com/laravel/framework/pull/12083

### CODE REVIEW

**Comment by taylorotwell** [comment]
I wonder if we should somehow take mutated values into account for this?

**Comment by acasar** [comment]
@taylorotwell Done :)

**Comment by taylorotwell** [comment]
So I also thought that people might have static values defined in `$attributes` that are always set on new models when they are instantiated:

```
class User extends Eloquent
{
     protected $attributes = [
          'something' => 'default'
    ]
}
```

We wouldn't necessarily want to include those in the update.

**Comment by acasar** [comment]
Done and squashed to one commit.

**Comment by JosephSilber** [comment]
I just **have** to say this here: I am extremely opposed to this! We should *remove* the current possibility of doing bulk actions, not augment them.

It makes absolutely no sense for an ORM to allow bulk updates/deletion. It leads to accidentally deleting/updating multiple records, and no events will fire - which can cause a lot of pain (even though it's mentioned in the docs).

I truly believe `(new User)->update([...])` should throw an exception, as well as deleting many records. This for example should also throw an error: `User::where('foo', 'bar')->delete()`.

If you want to do bulk DB operations, you should explicitely descend into the query builder:

```php
User::where('foo', 'bar')->toBase()->delete();
```

**Comment by rkgrep** [comment]
@JosephSilber :+1:

**Comment by acasar** [comment]
@JosephSilber I generally agree but if we throw an exception that would be a major breaking change.... :/

I think that bulk updates and deletes are just some syntactic sugar over query builder methods. And it's no harm when they're named explicitly. I mainly see use cases for tests and factories, not for production code.

**Comment by taylorotwell** [comment]
Yeah I don't really have a big problem with bulk operations from Eloquent.

**Comment by taylorotwell** [comment]
I guess I'll just hold off on this for now.

**Comment by JosephSilber** [comment]
I'm just gonna leave these 2 links here:

- http://laravel.io/bin/xK6yK
- https://twitter.com/JanisGitendorfs/status/699583278165200896

**Pull request closed without merging**
