### PR TITLE
[6.0] Fix plural categories in message selector

### PR DESCRIPTION
**Pull request by bonzai**
## Explanation

Currently, the message selector used in Laravel has many issues:

**1. It doesn't support every locale**

Uncommon locales like `bm` (Bambara) aren't supported.

**2. It doesn't support decimal numbers**

You can only use integers so sometimes the result can be invalid:

```php
Lang::choice('singular|plural', '1.0', [], 'en')
```

This code should return `plural` but in the current version it returns `singular`. It's possible to bypass pluralization by specifying number ranges but *ain't nobody got time for that*.

**3. It doesn't support all the plural categories**

Because the message selector doesn't support decimal numbers, a few locales like `pl` (Polish) has missing support for some [plural categories](http://cldr.unicode.org/index/cldr-spec/plural-rules) and return wrong results.

**4. Some locales have wrong pluralization rules**

AFAIR there are locales like `pt_PT` (Portuguese (Portugal)) and `cy` (Welsh) that returns wrong results for some cases (even when using integer numbers).

## Implementation

I decided to completely rewrite the `getPluralIndex` method based on [Language Plural Rules](https://www.unicode.org/cldr/charts/35/supplemental/language_plural_rules.html) from Unicode Consortium ([here](https://github.com/unicode-org/cldr/blob/master/common/supplemental/plurals.xml) you can find the more programmer-friendly list). After this PR the message selector:

- will properly  support decimal numbers
- will support every locale (and every plural category)

This is a breaking change for locales like `cs` (Czech) and `sk` (Slovak), because they will now support `many` category:

- one
- few
- **many** (new category between)
- other

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm confused. Why would your code example return plural? You passed 1.0.

**Comment by bonzai** [comment]
If you look at [English plural rules](https://www.unicode.org/cldr/charts/35/supplemental/language_plural_rules.html#en) you will see that `one` category (singular) is used when the following rules are true - `i = 1 and v = 0`.

- `i` - integer digits of `n`
- `v` - number of visible fraction digits in `n`, with trailing zeros

So the number:

- `1` is singular (`one`)
- `1.0` is plural (`other`) because `v != 0` (it's equal to 1)

[Here](http://unicode.org/reports/tr35/tr35-numbers.html#Operands) you can find more information about plural operands.

Also, there is a [Wikipedia article](https://en.wikipedia.org/wiki/English_plurals#Decimals_are_always_plural) about English plurals with the following information:

> **Any quantity that includes decimal precision is plural**. This includes 1 followed by any number of zeros. It is normal to say 1.0 gallons per flush, for instance, 0.6 units, or 3.3 children per couple, not *1.0 gallon, *0.6 unit, or *3.3 child per couple.

**Comment by taylorotwell** [comment]
No plans to change this. I think 99% of people would expect 1.0 to be singular.

**Comment by bonzai** [comment]
So... you're closing my PR only because you don't like the fact that `1.0` is plural? What about other languages that don't work correctly?

**Comment by bonzai** [comment]
@driesvints: Can you check my PR and confirm those bugs?

**Comment by driesvints** [comment]
@bonzai sorry man. If Taylor closed your pr then I don't think we'll change this any time soon.

**Pull request closed without merging**
