### PR TITLE
Use helpers instead of facades

### PR DESCRIPTION
**Pull request by JosephSilber**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why? I think the helpers are even worse than the facades, and laravel doesn't let you mock the helpers.

**Comment by GrahamCampbell** [comment]
Well, doesn't provide the same easy way the facades do anyway...

**Comment by Anahkiasen** [comment]
:-1: for me too, I much prefer having the facades that I can swap and mock than a function I can't override or do anything with

**Comment by crynobone** [comment]
> and laravel doesn't let you mock the helpers.

From experience, you still can use `Auth::shouldReceive()` and it would work the same, because it always going to refer back to `auth` SL for either helper or facade.

**Comment by GrahamCampbell** [comment]
If it ain't broke, don't fix it.

**Pull request closed without merging**
