### PR TITLE
[7.x] Performance improvements

### PR DESCRIPTION
**Pull request by halaei**
This PR improve asymptotic algorithmic complexity of validation, the speed-up is more than a constant number and it depends on the input size.

Validation tests are passed in my system. I don't know if they break anything. It should be backported to LTS versions. I don't regard this as a breaking change, but you may decide to choose portion of it for version 7, 6, and 5.5.
The performance may still be poor in some cases. But other improvements may require breaking changes or bigger changes.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Missing doc blocks... also, "I don't know if this breaks anything" doesn't inspire confidence.

**Comment by staudenmeir** [comment]
There's a reason for removing duplicate keys: #4126

**Comment by halaei** [comment]
I added some phpdocs. 
It is not easy to reverse engineer and understand the code. It took me 2 days so far.  I think my changes are good. No guarantee because it is complicated.

**Comment by halaei** [comment]
@staudenmeir I remove my changes on Relation. That has nothing to do with validation after all. Maybe Collection::unique() can be improved later. It takes O(n^2) time because the call to in_array inside reject().

**Comment by GrahamCampbell** [comment]
> 5.5.

5.5 is no longer maintained. LTS support for it already ended.

**Comment by taylorotwell** [comment]
There are changes here that appear breaking and I can't risk that on a point release. If you are concerned about people overwhelming your application check the size of the array before sending it to the validator.

**Comment by halaei** [comment]
So maybe Laravel 8

**Pull request closed without merging**
