### PR TITLE
Fix Builder - support camelCase attributes

### PR DESCRIPTION
**Pull request by Xakki**
Use global Model::snakeAttributes for where conditions

I'm not sure how to fix this problem properly because this fix affects all models in the project.

### CODE REVIEW

**Comment by marius-mcp** [comment]
cammelCased attributes are supported if your db supports them from what I know.
All you need to do is put public static $snakeAttributes = false in the model that has cammelCased attributes.

Please elaborate your problem.

**Comment by Xakki** [comment]
Of couse i use $snakeAttributes=false, but this fix for dynamic where, like
->whereUserId(1) 
translate to
->where('userId', '=', 1)

**Comment by taylorotwell** [comment]
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

**Comment by marius-mcp** [comment]
@Xakki you should open an issue for this case then.

**Pull request closed without merging**
