### PR TITLE
[5.3] Added HasOne Through and BelongsTo Through

### PR DESCRIPTION
**Pull request by pdscopes**
I have created a `HasOneThrough` and `BelongsToThrough` Eloquent relationships.

This is fix from https://github.com/laravel/framework/pull/16599 where I actually created a BelongsToThrough rather than a HasOneThrough. I renamed the original class to BelongsToThrough and created a new class called HasOneThrough.

Linked to https://github.com/laravel/framework/issues/8721

### CODE REVIEW

**Comment by srmklive** [comment]
Wouldn't it be better to have it in 5.4?

**Comment by GrahamCampbell** [comment]
Yes, probably.

**Comment by JosephSilber** [comment]
I would frankly only write integration tests for these. All those mocks make the tests harder to read, and doesn't even end up testing it thoroughly.

There are a lot of Eloquent tests like this, and they're all brittle and illegible.

For new stuff, we should go directly for integration tests.

**Comment by pdscopes** [comment]
@srmklive, I'm afraid I'm not up to speed on the release cycle so I couldn't say.

@JosephSilber, I just followed what was already done for other relationships. Do you propose I scrap my unit tests in favour of integration tests? i.e. create a small schema of three database tables and Models to suite?

**Comment by taylorotwell** [comment]
Yes I would send this to master branch and only write integration tests. The mocked unit tests are basically pointless IMO.

**Pull request closed without merging**
