### PR TITLE
[6.x] Query Builder whereIn shortcut

### PR DESCRIPTION
**Pull request by ddzobov**
# Query Builder whereIn shortcut

### Before:

```php
$builder->select('*')->from('users')->where('foo', '<', 1)->whereIn('bar', [2, 3]);

$builder->select('*')->from('users')->where('foo', '=', 1)->whereIn('bar', [2, 3]);
```

### After:

```php
$builder->select('*')->from('users')->where([
    ['foo', '<', 1],
    ['bar', [2, 3]]
]);

$builder->select('*')->from('users')->where([
    'foo' => 1,
    'bar' => [2, 3]
]);
```

### CODE REVIEW

**Comment by decadence** [comment]
Was already proposed and declined unfortunately 😔

**Comment by ddzobov** [comment]
> Was already proposed and declined unfortunately 😔

can you attach your PR here?

**Comment by decadence** [comment]
This is not my PR but here it is https://github.com/laravel/framework/pull/19126

**Comment by taylorotwell** [comment]
Just use the `whereIn` method. This method is already large 😄

**Pull request closed without merging**
