### PR TITLE
Reproduction of JSON array casting bug with Eloquent

### PR DESCRIPTION
**Pull request by alexbowers**
I have ran into an issue where using `assertDatabaseHas` with JSON array casting is not matching the records properly. I have not managed to find the root cause of this yet, but this PR shows the bug in place.

Any assistance in tracking this bug down would be appreciated :)

### CODE REVIEW

**Comment by crynobone** [comment]
Hi there, 

This can be fixed by utilise `castAsJson()` available from the same trait.

**Comment by alexbowers** [comment]
Should the casting not be done automatically based on the model casts?

**Comment by crynobone** [comment]
@alexbowers feel free to submit PR to handle that.

**Comment by stevebauman** [comment]
@alexbowers In our application had to write out own `toJson` method in our base `TestCase` to properly cast values to their JSON value that would appropriately be matched in MySQL and SQLite. Maybe it could be helpful to you:

```php
/**
 * Cast a JSON string to a database compatible type.
 *
 * Compatible with SQLite and MySQL.
 *
 * @return \Illuminate\Database\Query\Expression|string
 */
protected function toJson(mixed $value): mixed
{
    $isSQLite = DB::connection() instanceof SQLiteConnection;

    if (is_string($value)) {
        return $isSQLite ? json_encode($value) : $value;
    }

    if (is_numeric($value)) {
        return $isSQLite ? json_encode((string) $value) : json_encode($value);
    }

    if (is_bool($value)) {
        return $isSQLite ? var_export($value, true) : DB::raw(var_export($value, true));
    }

    // If we're not using SQLite, we must utilize the
    // database driver cast non-scalar values so
    // that the SQL query is properly formed.
    if (! $isSQLite) {
        return $this->castAsJson($value);
    }

    if ($value instanceof Jsonable) {
        $value = $value->toJson();
    } elseif (is_array($value) || is_object($value)) {
        $value = json_encode($value);
    }

    return $value;
}
```

**Comment by taylorotwell** [comment]
Hey there! We usually don't act on PRs that only have failing tests (even if valid bugs). We can only take action on PRs with fixes. Thanks!

**Comment by alexbowers** [comment]
@taylorotwell can this be reopened? I have pushed a fix to the PR so this is now a code change, not just a broken test

**Comment by alexbowers** [comment]
Nvm, just reopened as https://github.com/laravel/framework/pull/49174

**Pull request closed without merging**
