### PR TITLE
[9.x] Adds `to_route` helper

### PR DESCRIPTION
**Pull request by nunomaduro**
This pull request proposes the addition of the `to_route` helper exactly as described here: https://github.com/laravel/framework/pull/38145.

### CODE REVIEW

**Comment by SjorsO** [comment]
sneaky 👀

**Comment by foremtehan** [comment]
I need [str() helper](https://github.com/laravel/framework/pull/31707) more than a helper that redirects.

Look at this:

image

I imported Str class in more than 40 files

**Comment by Jubeki** [comment]
@foremtehan take a look at: https://github.com/laravel/framework/pull/40520

Also you can always define your own helper function.

**Comment by foremtehan** [comment]
@Jubeki that's was fast tbh 😅

**Pull request merged**
