### PR TITLE
[5.2] Update Container and ContainerTest.php

### PR DESCRIPTION
**Pull request by erhankr**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the report. This will need fixing, and the test case put into 5.1. (Not saying you have to fix it btw, just saying it needs fixing in general, lol)

**Comment by taylorotwell** [comment]
I'm having a hard time following what is happening in this PR anymore with these changes and array `+` operations.

**Comment by erhankr** [comment]
`func_get_args()` returns a copy of the passed arguments only, <b>and does not account for default (non-passed) arguments.</b>
```php
$result = call_user_func(function ($foo = 'default') {
          return func_get_args();
});
```
The `$result` is `array()` now. This is wrong <b>for tests</b> because `$foo = 'default'` and real arguments must be `array('default')`

So `ContainerTest.php` doesnt handle default arguments properly because of `func_get_args()`

But tests not fail because of `Container.php` has a bug.

follow `$dependencies` in the `Container.php` 
```php
protected function addDependencyForCallParameter(ReflectionParameter $parameter, 
array &$parameters, &$dependencies)
{
   ...
    elseif ($parameter->isDefaultValueAvailable()) {
        $dependencies[] = $parameter->getDefaultValue();
    }
}
```

```php
protected function getMethodDependencies($callback, array $parameters = [])
{
    ...
        $this->addDependencyForCallParameter($parameter, $parameters, $dependencies);
    ...

    return array_merge($dependencies, $parameters);
}
```

```php
public function call($callback, array $parameters = [], $defaultMethod = null)
{
    `...`
    $dependencies = $this->getMethodDependencies($callback, $parameters);
    return call_user_func_array($callback, $dependencies);
}
```
So there is problem in `Container.php` and `ContainerTest.php`

This test is show the bug in my first commit.
```php
public function testCallWithDefaultValueAndParameters()
{
         $container = new Container;
         $result = $container->call(function ($foo, $bar = []) {
             return func_get_args();
         }, ['foo','bar']);
 
         $this->assertEquals([ 'foo', 'bar'], $result);     // false
         $this->assertEquals([ [], 'foo', 'bar'], $result); // true
}
```
Or without `func_get_args()`
```php
public function testCallWithDefaultValueAndParameters()
{
         $container = new Container;
         $result = $container->call(function ($foo, $bar = []) {
             return [$foo, $bar];
         }, ['foo','bar']);
 
         $this->assertEquals(['foo','bar'], $result); // false
         $this->assertEquals([ [], 'foo'], $result);    // true
}
```
About array `+` operations.
```php
function testCalback1($foo, $bar = 'default') {
    return func_get_args();
}

function testCalback2($foo, $bar = 'default') {
    return [$foo, $bar];
}

function testCalback3($foo, $bar = 'default') {
    return [$foo, $bar] + func_get_args();
}
```
```php
call_user_func_array('testCalback1', ['foo']); // ['foo'] wrong
call_user_func_array('testCalback1', ['foo','bar']); // ['foo','bar']
call_user_func_array('testCalback1', ['foo','bar','baz']); // ['foo','bar','baz']

call_user_func_array('testCalback2', ['foo']); // ['foo','default']
call_user_func_array('testCalback2', ['foo','bar']); // ['foo','bar']
call_user_func_array('testCalback2', ['foo','bar','baz']); // ['foo','bar'] wrong

call_user_func_array('testCalback3', ['foo']); // ['foo','default']
call_user_func_array('testCalback3', ['foo','bar']); // ['foo','bar']
call_user_func_array('testCalback3', ['foo','bar','baz']); // ['foo','bar','baz']
```
So if you dont need arguments not in the parameters, no need `func_get_args()`
if you need all arguments and parameters with correct order, array `+` operation works good.

**Comment by erhankr** [comment]
I changed few times because of The StyleCI analysis has failed.

**Pull request closed without merging**
