### PR TITLE
[5.2] Make password reset url a link

### PR DESCRIPTION
**Pull request by vool**
Small change to format the auth password reset url as a hyper-link

This has the same result as https://github.com/laravel/framework/pull/11741 but without with the dependency issue. ( Sorry couldn't see how to reopen that PR )

Keith

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We should really avoid code duplication. Just assign the link to a variable inline.

**Comment by GrahamCampbell** [comment]
```
Click here to reset your password: <a href="{{ $link = url('password/reset', $token).'?email='.urlencode($user->getEmailForPasswordReset()) }}"> {{ $link }} </a>
```

**Comment by vool** [comment]
your right, 

not too sure what the best way to edit this, but have push an commit with variable as suggested

**Comment by EliasZ** [comment]
@vool https://www.atlassian.com/git/tutorials/rewriting-history/git-commit--amend/

Amending a commit does rewrite history but seeing as you submit a PR and nobody uses your forked repo, you can simply force-push (git push --force) to your fork's branch. Github will automatically pick up on the changed commits and fix the PR for you.

Hope this helps.

**Comment by vool** [comment]
Thanks @EliasZ,l I was thinking that but wasn't too sure

**Pull request closed without merging**
