### PR TITLE
[5.7] Build http queries with RFC3986

### LINKED ISSUE #24044: Inconsistent handling of space character in URL generation
- Laravel Version: 7.5.40
- PHP Version: 7.0.27
- Database Driver & Version: N/A

### Description:

For the most part Laravel tries to use the newer **RFC3986** for URL encoding e.g. [here](https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Routing/RouteUrlGenerator.php#L96) and [here](https://github.com/laravel/framework/blob/30d2f7f350e1e5bfa742e18e993deedefec2e953/src/Illuminate/Routing/UrlGenerator.php#L189). And judging from #11747 this seems to be the accepted way to do it. But there are multiple places where **RFC1738** is used indirectly just because it's the default encoding for the `http_build_query` function. The main difference between the two according to the [docs](http://php.net/manual/en/function.http-build-query.php) is related to the handling of the space character. The former encodes it as `%20` and the later as `+`. To achieve consistency in the URL generation all calls to the `http_build_query` should have `PHP_QUERY_RFC3986` as it's fourth parameter. [Here](https://github.com/laravel/framework/search?utf8=%E2%9C%93&q=http_build_query&type=) we can see the use of that function in the code.

### Steps To Reproduce:

Create a simple named route and then generate a link to it using the route helper like this.

```php
route('myroute', ['key' => 'value with spaces'])
```

### Expected result

`/myroute?key=value%20with%20spaces`

### Actual result

`/myroute?key=value+with+spaces`

### PR DESCRIPTION
**Pull request by carragom**
First stab at #24044. Let me know what you think.

Fixes #24044

### CODE REVIEW

**Comment by ntzm** [comment]
Where you're passing `null` to the `numeric_prefix` parameter, it's meant to be a string. I think it would be better to pass `''` instead

**Comment by ntzm** [comment]
There's also a lot of duplication here. Maybe it's worth extracting the logic to the `Arr` class, something like `Arr::buildQuery($data)`? Just a thought

**Comment by taylorotwell** [comment]
Please provide description in this PR how this is beneficial to users.

**Comment by carragom** [comment]
I think the main advantage of this change is the consistency in query parameter handling. Let's say you receive an API call like `/articles/search=my title`. And let's suppose you want to generate a `self` link as it's often done in APIs, you would reuse the query parameters you got to generate that `self` link but the result       of calling `route('articles.index', ['search' => $req->query('search')])` would be something like `/articles/search=my+title`. The browser(RFC3986)  and Laravel(RFC1738) are using different encoding mechanics for URLs and you might end up with different results without realizing it. More information can be found [here](https://en.wikipedia.org/wiki/Percent-encoding). I hope this explains why this change is important. If I missed something let me know.

**Comment by taylorotwell** [comment]
DRY'd this up into an `Arr::query` helper.

**Pull request merged**
