### PR TITLE
[5.7] Add uncountable word "Corn"

### PR DESCRIPTION
**Pull request by elynnaie**

### CODE REVIEW

**Comment by ntzm** [comment]
Corn can be pluralised, see https://en.wiktionary.org/wiki/corn#Noun

**Comment by denaje** [comment]
Can be, but usually isn't except in rare circumstances. In the example linked, the countable corn refers to

> A grain or seed, especially of a cereal crop.

Even in a corn-centric ag company, we have never referred to corn as "corns".

**Comment by ntzm** [comment]
Also corn can to refer to

> A type of callus, usually on the feet or hands.

which is pluralised

**Comment by denaje** [comment]
There is already precedent in the list of uncountable words for words that can be both countable and uncountable but are usually uncountable. E.g., https://en.wiktionary.org/wiki/fish#Noun

**Comment by 36864** [comment]
That is a poor example. The countable form of "corn", meaning a type of callus, is separate from the usually uncountable "corn", meaning maize. There is no equivalent for "fish".

**Comment by denaje** [comment]
I stand by my argument. A user of Laravel may want to pluralize `fish` as `fish` or `fishes`, but the most common (by far) is `fish`. Same with `corn`.

.....aand it's closed. @taylorotwell Can you give an explanation for the rationale behind which words are considered uncountable in Laravel?

**Comment by denaje** [comment]
For anyone who finds this in the future and wishes to customize the list of uncountable words, I found an easy way to do it. Because the Pluralizer's `$uncountable` array is public, you can modify it. I stuck this in my `AppServiceProvider` and it worked like a charm.

```php
Pluralizer::$uncountable[] = 'corn';
```

As for _removing_ a word from being uncountable, it's quite difficult because you not only have to remove it from `Pluralizer::$uncountable` but also deal with it in `Doctrine\Common\Inflector\Inflector` if it exists there as well. (Why Laravel maintains its own list that doesn't match Doctrine's, who can say.)

**Pull request closed without merging**
