### PR TITLE
[11.x] Add methods to the HTTP kernel to append middleware relative to other middleware

### PR DESCRIPTION
**Pull request by ollieread**
This PR allows for the programmatic insertion of middleware into the priority, relative to existing prioritised middleware.

## Reasoning

My thought behind this is that third-party package developers can now register the priority of their middleware without requiring the user to mess with it themselves. I am currently developing a package where the priority of middleware will depend on several factors, so mostly, I need this. XD

### `Kernel::addToMiddlewarePriorityRelative()`

This method adds middleware to the `Kernel::$middlewarePriority` property relative to other middleware. This method is protected and exists for the other two methods.

## `Kernel::addToMiddlewarePriorityAfter()`

This method adds middleware to the `Kernel::$middlewarePriority` property after existing middleware.

```php
$kernel->addToMiddlewarePriorityAfter(
    \Illuminate\Routing\Middleware\ValidateSignature::class,
    [
        \Illuminate\Cookie\Middleware\EncryptCookies::class,
        \Illuminate\Contracts\Auth\Middleware\AuthenticatesRequests::class,
    ],
);
```

The above adds the `ValidateSignature` middleware to the priority list after the two provided pieces of middleware, ensuring that it will run after them.

This method also accepts a string and not just an array, so you can insert after a single piece of middleware.

### `Kernel::addToMiddlewarePriorityBefore()`

This method adds middleware to the `Kernel::$middlewarePriority` property before existing middleware.

```php
$kernel->addToMiddlewarePriorityBefore(
    \Illuminate\Routing\Middleware\ValidateSignature::class,
    [
        \Illuminate\Cookie\Middleware\EncryptCookies::class,
        \Illuminate\Contracts\Auth\Middleware\AuthenticatesRequests::class,
    ],
);
```

The above adds the `ValidateSignature` middleware to the priority list before the two provided pieces of middleware, ensuring that it will run before them.

This method also accepts a string and not just an array, so you can insert before a single piece of middleware.

### CODE REVIEW

**Comment by leewillis77** [comment]
Just adding a +1 here that I'd definitely find these methods useful!

**Comment by jnoordsij** [comment]
Thanks for this! This is a great replacement for some similar manual hacking that I did within my application to achieve such a thing.

Just curious: is there any intention of adding this to [the `Middleware` configurator class](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Configuration/Middleware.php) as well? If not then I'll probably take that up at some point, as this MR was the last bit that I needed to replace my custom `Kernel` implementation with using just the configurators, so would gladly then update the configurator so I can bundle everything there.

**Comment by ollieread** [comment]
> Thanks for this! This is a great replacement for some similar manual hacking that I did within my application to achieve such a thing.
> 
> 
> 
> Just curious: is there any intention of adding this to [the `Middleware` configurator class](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Configuration/Middleware.php) as well? If not then I'll probably take that up at some point, as this MR was the last bit that I needed to replace my custom `Kernel` implementation with using just the configurators, so would gladly then update the configurator so I can bundle everything there.

Thanks 😊

I did actually plan to do that, but I've been super busy until quite recently. If I start it before you ill link it to this PR so you should get notified!

**Comment by ollieread** [comment]
> Thanks for this! This is a great replacement for some similar manual hacking that I did within my application to achieve such a thing.
> 
> Just curious: is there any intention of adding this to [the `Middleware` configurator class](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Configuration/Middleware.php?rgh-link-date=2024-10-24T16%3A44%3A44Z) as well? If not then I'll probably take that up at some point, as this MR was the last bit that I needed to replace my custom `Kernel` implementation with using just the configurators, so would gladly then update the configurator so I can bundle everything there.

I've created a PR for this here: #53326

**Pull request merged**
