### PR TITLE
[9.x] Added package to add DTO support

### PR DESCRIPTION
**Pull request by WendellAdriel**
I know this is a real shot in the dark, but I wanted to make this happen so I'm going to describe the reasons:

## Why Data Transfer Objects

**Data Transfer Objects** are a great way to **improve** the **code quality** of a codebase by improving the **maintainability**, **decoupling** and **organization** of the code. Also, I've seen that lately this pattern is being applied in a lot of **Laravel** applications. From small and simple to large and complex applications, this pattern can improve the quality of the code and also the DX for developers and having this **out-of-the-box** in the framework would be awesome!

## Why THIS Package

I know that there are a lot of other packages that add **DTO** support to **Laravel**, even more well-known packages than the one I created, but I have some points why this would be a great choice:

1. It's an **abstraction layer** built **on top of Laravel standards and common knowledge**, making it pretty **straightforward** for **Laravel** developers to use. You can check the docs in the **[README](https://github.com/WendellAdriel/laravel-validated-dto#readme)** and check that it's really simple to use and integrate in a Laravel application.
2. The validation of the data is made the same way that you validate a **Request** object, so there's no learning for it, you can apply the knowledge that developers already have.
3. It integrates with **core Laravel features** like **Validation**, **HTTP Requests**, **Eloquent Models** and **Artisan Commands**.

## Observations

- If you see that this could work but the package is missing anything, I would be happy to work on anything needed to make this happen.
- If this could be a possibility for `10.x` instead of `9.x` I would happily create a new PR.
- If this should be added to `laravel/laravel` instead of `laravel/framework` I would happily create a new PR.
- If to add this, any other work is needed on any other repository like docs, etc I would happily work on all changes needed.

### CODE REVIEW

**Comment by WendellAdriel** [comment]
A check failed but I think that it's not related to my PR, how can I check and run those again?

**Comment by ankurk91** [comment]
Nice way to advertise your package

**Comment by huangdijia** [comment]
1. Are you sure everyone needs this package?
2. Why not contribute directly?

**Comment by WendellAdriel** [comment]
@ankurk91 seems a nice package as well, but it's not for DTOs, it can be any other DTO package if they feel like this could be useful, I just mentioned mine because it's a really simple and straightforward one.

@huangdijia 
1. No, that's why I said it's a shot in the dark. The Core Team will decide if that's a nice addition, but most probably it's not going to be integrated into the Framework and I'm all good with that xD
2. I already contributed with some small changes to the Framework, but I added this because I already created this package and it doesn't make sense to recreate it directly in the framework being something that is not even sure they want this in there.

**Comment by WendellAdriel** [comment]
I just remembered that I’ve should created a thread in the discussions first to talk about this and also because of the feedback the PR has so far I don’t think it’s something that people want to see in the framework so I’m going to close it!

Either way, thanks for everyone that spent some time checking on this! All feedback is welcome! :wink:

**Pull request closed without merging**
