### PR TITLE
Sending to a Specified Address

### PR DESCRIPTION
**Pull request by clemblanco**
Sometimes you want to avoid email real customers. The two solutions given by Laravel as per as the official documentation are:
- Using "pretend" to log the emails into the log file.
- Using something like http://mailtrap.io.

Like with [Symfony2](http://symfony.com/doc/current/cookbook/email/dev_environment.html#sending-to-a-specified-address), here we also give the ability to the developer to specify one email address which will receive every single email from his application. Could be very useful on a staging environment where you don't want to email real customers and where the actual tester wouldn't have access to the log files or wouldn't be able to use mailtrap.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Merge conflicts?

**Comment by GrahamCampbell** [comment]
Please send to 5.1.

**Comment by Claymm** [comment]
Sorry what do you mean?

**Comment by GrahamCampbell** [comment]
> Merge conflicts?

We can't merge this as it because there are "merge conflicts".

> Please send to 5.1.

Even if we could merge it, I'd like you to target it at Laravel 5.1 instead of Laravel 5.0. Currently, 5.1 is our master branch, though the master will become 5.2 in the near future.

**Comment by Claymm** [comment]
Ok my bad. Just did it again against master but I still have a merge conflict. Not sure why.

**Pull request closed without merging**
