### PR TITLE
[5.3] Extending blade looping functionality for @foreach

### PR DESCRIPTION
**Pull request by themsaid**
Rebased version of https://github.com/laravel/framework/pull/12867

### CODE REVIEW

**Comment by taylorotwell** [comment]
One thing I'm curious about is if we really need "parent", "depth", "size", and "reverseIndex"...

It seems like the main practical use cases are "index", 'IsFirst", and "isLast"?

**Comment by taylorotwell** [comment]
Renamed isFirst and isLast to just first and last. Renamed reverseIndex to "remaining".

**Comment by taylorotwell** [comment]
Renamed "size" to "count"

**Comment by Yannik** [comment]
@taylorotwell Please keep `parent`! I really need this. I agree that `remaining` is much more expressive than `reverseIndex` (even though reverseIndex is used by all other templating systems, so this is probably an argument for `reverseIndex` too).

**Comment by jackfruh** [comment]
What about a `$loop->more` value for the following scenario:
```
// $speakers = ["Taylor", "Matt", "Jeffrey"];

@foreach($speakers as $speaker) 
    {{$speaker->FirstName}} 

    @if($loop->more)
        joined by
    @endif

@endforeach
```
to output:
```
Taylor joined by Matt joined by Jeffrey
```

**Comment by themsaid** [comment]
@jackfruh you can achieve the same effect with `$loop->last` or `$loop->remaining`

Remaining will return an integer of how many items remaining until the end of the loop, the last item will be 0.

**Comment by jackfruh** [comment]
Thanks @themsaid ! 
I think `$loop->remaining` is perfect!

Will this work with forelse as well?

```
@forelse($speakers as $speaker) 
    @if($loop->first)
       Welcome  
    @endif  
    
    {{$speaker->FirstName}} 

    @if($loop->remaining)
        and
    @endif

    @if($loop->last)
        to this years convention!
    @endif

@empty
    Our speaker lineup isn't posted yet, check back soon.
@endforelse
```

**Comment by themsaid** [comment]
@jackfruh Currently no, I'll PR the feature into 5.3 soon :)

**Comment by Yannik** [comment]
@themsaid Please do, so this can make it into 5.3 before its release :)

**Comment by themsaid** [comment]
@jackfruh @Yannik done https://github.com/laravel/framework/pull/13945

**Comment by jackfruh** [comment]
@themsaid Thanks! You're awesome! 👍

**Comment by themsaid** [comment]
@jackfruh ❤️

**Pull request merged**
