### PR TITLE
Fix juggling equation, performance is_null() -> null checks etc

### PR DESCRIPTION
**Pull request by arthurkushman**
- juggling equation
- performance is_null -> null check
- logical operations precedence
- passed `null` the same as the default parameter

### CODE REVIEW

**Comment by arthurkushman** [comment]
Is there any explanation on why this pull request should be closed?
There are strong technical reasons with what was fixed.

**Comment by browner12** [comment]
you're trying to do too much in this PR.  The smaller it is, the easier it is for the reviewer to comprehend, and more likely to get merged.  I might start with something smaller like switching all the `is_null` checks to `=== null`, and provide a thorough explanation of what it fixes or why it is better.

from my 2 minute google search, the performance difference seems to be negligible, so my guess is it won't be merged, but you can still try.

**Comment by devcircus** [comment]
This [comment on php.net](http://php.net/manual/en/function.is-null.php#117344) lends to the idea that as of php 7, ```is_null``` is actually marginally faster than ```===null```. So, if anything, maybe move a subset of you other changes out to a smaller PR.

**Comment by arthurkushman** [comment]
Ok, presume changing logical operations precedence and removing extra param passed to function would be better - will make a new pr, thx.

**Pull request closed without merging**
