### PR TITLE
[11.x] Non-default schema names

### PR DESCRIPTION
**Pull request by hafezdivandari**
This PR adds tests for all schema operations with prefixed table and with custom schema name. Some schema methods were not working properly in these cases that are fixed on this PR:

### Prefixed table
- Renaming a column on a prefixed table is fixed on SQL Server
- Renaming an index on a prefixed table is fixed on SQL Server
- Specifying a starting value for auto-incrementing column on prefixed table is fixed on PostgreSQL

### Non-default Schema name
- Dropping a primary key on non-default schema is fixed on PostgreSQL
- Renaming a table on non-default schema is fixed on SQL Server
- Renaming a column of a table on non-default schema is fixed on SQL Server
- Renaming an index of a table on non-default schema is fixed on SQL Server

### Prefixed table on non-default schema
Most of schema operations wasn't working on this case, that is fixed now. Grammar was always prefixing the first segment of passed values, that causes a problem when passing a table as `schema.table` and being wrapped as `prefix_schema.table`, this conditions is fixed by separating the logic for wrapping columns/values from wrapping tables after this PR:
- `table.column` being wrapped to `prefix_table.column` using `Grammar::wrap()` as before.
- `schema.table` being wrapped as `schema.prefix_table` using `Grammar::wrapTable()` as expected.

P.S: This is just a fix and adds support for prefixed table and using non-default schema on all cases, it's not changing behavior so we don't need to add anything to upgrade guide.

### Summary of tested and fixed cases
<table>
    <thead>
        <tr>
            <th>DB</th><th>PostgreSQL</th><th>SQL Server</th><th>PostgreSQL</th><th>SQL Server</th><th>PostgreSQL</th><th>SQL Server</th>
        <tr></tr>
<th>Feature </th><th colspan="2">Schema Name</th><th colspan="2">Prefix</th><th colspan="2">Schema Name + Prefix</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Create Table</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Rename Table</td><td>✓</td><td>✓ (fixed)</td><td>✓</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Drop Table</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Has Table</td><td>✓</td><td>✓ (#49965)</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (#49965)</td>
        </tr><tr>
            <td>Table w/ Comment</td><td>✓</td><td>n/a</td><td>✓</td><td>n/a</td><td>✓ (fixed)</td><td>n/a</td>
        </tr><tr>
            <td>Add Column</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Rename Column</td><td>✓ (#45258)</td><td>✓ (fixed)</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Modify Column</td><td>✓ (#45487)</td><td>✓ (#45487)</td><td>✓</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Drop Column</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Column w/ Default</td><td>✓</td><td>✓ (#49965)</td><td>✓</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Column w/ Comment</td><td>✓</td><td>n/a</td><td>✓</td><td>n/a</td><td>✓ (fixed)</td><td>n/a</td>
        </tr><tr>
            <td>Column w/ Starting Value</td><td>✓</td><td>n/a</td><td>✓ (fixed)</td><td>n/a</td><td>✓ (fixed)</td><td>n/a</td>
        </tr><tr>
            <td>Get Columns</td><td>✓</td><td>✓ (#49965)</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (#49965)</td>
        </tr><tr>
            <td>Has Column(s)</td><td>✓</td><td>✓ (#49965)</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (#49965)</td>
        </tr><tr>
            <td>Get Column Type</td><td>✓</td><td>✓ (#49965)</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (#49965)</td>
        </tr><tr>
            <td>Add Index</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Rename Index</td><td>✓</td><td>✓ (fixed)</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Drop Primary</td><td>✓ (fixed)</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Drop Unique</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Drop Index</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Get Indexes</td><td>✓</td><td>✓ (#49965)</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (#49965)</td>
        </tr><tr>
            <td>Has Index</td><td>✓</td><td>✓ (#49965)</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (#49965)</td>
        </tr><tr>
            <td>Add Foreign Key</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Drop Foreign Key</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (fixed)</td><td>✓ (fixed)</td>
        </tr><tr>
            <td>Get Foreign Keys</td><td>✓</td><td>✓ (#49965)</td><td>✓</td><td>✓</td><td>✓</td><td>✓ (#49965)</td>
        </tr><tr>
            <td>Has View</td><td>✓ (#49965)</td><td>✓ (#49965)</td><td>✓</td><td>✓</td><td>✓ (#49965)</td><td>✓ (#49965)</td>
        </tr>
    </tbody>
</table>

### CODE REVIEW

**Comment by taylorotwell** [comment]
Any breaking changes that will need to be documented here?

**Comment by hafezdivandari** [comment]
@taylorotwell no, it's just a fix.

**Comment by taylorotwell** [comment]
Thanks!

**Comment by arjenvanoostrum** [comment]
Hi @hafezdivandari Thanks for your effort to now fully support schema names in `SQLserver`! Brings the database component to an even higher level.

**Pull request merged**
