### PR TITLE
[5.6] Added support for MySQL's "sounds like" operator

### PR DESCRIPTION
**Pull request by mgrinspan**

### CODE REVIEW

**Comment by sisve** [comment]
You've forgot to attach any tests to this PR.

**Comment by mike-grinspan** [comment]
Better? I'm new to TDD.

**Comment by GrahamCampbell** [comment]
> Better? I'm new to TDD.

Adding tests is not TDD. :)

**Comment by chandrasbt** [comment]
Awesome addition!

**Pull request merged**
