### PR TITLE
[5.5] Add factory model creation on different connections

### PR DESCRIPTION
**Pull request by casperboone**
This PR allows for the creation of 'factory models' on other connections than the default.

Example usage:
```php
factory(User::class)->connection('ext-02')->create();
```

Currently, for the same behavior, you would have to `make()` the model, then use `setConnection()` and manually `save()` it.

### CODE REVIEW

**Comment by ntzm** [comment]
Isn't that what the `$connection` property on the models is for? What's the use case for this?

**Comment by themsaid** [comment]
@ntzm so you can create a factory model on a different connection.

**Comment by taylorotwell** [comment]
@casperboone it seems there could be some unexpected behavior if you do:

factory()->connection()->make()...

The model will not have the connection you specified set. That might be unexpected since it works for create.

**Comment by casperboone** [comment]
@taylorotwell Good catch! Will look into it :)

**Comment by casperboone** [comment]
Done 😃 .

The changes involved moving
```
$instance->setConnection($instance->newQueryWithoutScopes()->getConnection()->getName());
```
to the makeInstance() method. I believe this will not change any behavior (and tested this quickly), but please correct me if I'm wrong.

**Comment by themsaid** [comment]
@casperboone  the side effect to your change is that now `factory()->make()` will generate models that have the connection property set, before your change the resulted model will have the connection property = null, since it's not persisted yet I believe the connection should remain null.

**Comment by taylorotwell** [comment]
Yeah I think you can keep current behavior if connection is not explicitly set.

**Comment by casperboone** [comment]
@themsaid Good point! Changed the code. Didn't like having to add two conditionals for this, but seems like the simplest way to keep the current behavior (and support the new 😄).

**Pull request merged**
