### PR TITLE
fix the return error of value's type

### PR DESCRIPTION
**Pull request by ganxiangdong**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This function may return either an integer or a float as described in the phpdoc.

**Comment by ganxiangdong** [comment]
those functions return type is string now

**Comment by GrahamCampbell** [comment]
Oh, do they! That looks like a mistake.

**Comment by GrahamCampbell** [comment]
The aggregate function is marked as only floats and integers, so I guess we need a proper fix there.

**Comment by GrahamCampbell** [comment]
Ok, I've provided a fix: https://github.com/laravel/framework/pull/14781.

**Comment by GrahamCampbell** [comment]
This has been reverted. These functions support max dates which are strings. Our doc is just wrong.

**Pull request closed without merging**
