### PR TITLE
[5.5] Protects class PackageManifest attributes

### PR DESCRIPTION
**Pull request by nunomaduro**
This PR Addresses the attributes of class PackageManifest. In order to make them protected.

There is no reason to them to be public.

### CODE REVIEW

**Comment by tillkruss** [comment]
Out of curiosity, is there a reason for them to be protected?

**Comment by nunomaduro** [comment]
@tillkruss A good rule of thumb is: make everything as private as possible. This makes your class more encapsulated, and allows for changing the internals of the class without affecting the code using your class.

**Comment by taylorotwell** [comment]
I prefer to keep things public.

**Comment by nunomaduro** [comment]
@taylorotwell Sorry to disturb. But why do you prefer keep the things public? 😕

**Comment by m1guelpf** [comment]
@nunomaduro So developers can make changes in their own code, I guess...

**Comment by nunomaduro** [comment]
@m1guelpf @taylorotwell On that case we could have setters or even the strategy pattern.

**Pull request closed without merging**
