### PR TITLE
[5.4] Tests for commands

### PR DESCRIPTION
**Pull request by KKSzymanowski**
I noticed there are no tests for generator commands, so I decided to try writing some.

What do you think? Is this a right approach?

### CODE REVIEW

**Comment by KKSzymanowski** [comment]
This
```php
$this->filesystem->willCheckFile($this->path, false);
```
isn't really obvious that the file should not exist. Maybe it should be changed to
```php
$this->filesystem->willCheckFile($this->path)->andReceive(false);
```

That way if we don't care for the file existance we can just leave the `willCheckFile` call, but when we do, we can specify what should be returned.

Also, `$this->filesystem->willCheckFile()` doesn't feel right. The command checks for file existance, not the filesystem. 
Maybe there should be a command wrapper which generates necessary dependency mocks and instantiates the command with them instead of just a filesystem wrapper.
That way checking for eg. `make:migration` call would look like:
```php
$command->willCall('make:migration')->with([
    'name' => 'FooController',
    '--resource' => false,
])->once();
```
And then whole test would look like:
```php
$this->command->willCheckFile($this->path)->once()->andReceive(false)
              ->willCheckDirectory(dirname($this->path))->once()->andReceive(true)
              ->willNotMakeAnyDirectory()
              ->willGetFile('/stubs\/model\.stub/')->once()->andReceive('DummyNamespace;DummyClass')
              ->willPutFile($this->path, 'App;Foo')->once()
              ->willCall('make:migration')->once()->with([
                  'name'     => 'create_foos_table',
                  '--create' => 'foos',
              ]);
        
$output = $this->command->run();

$this->assertContains('Model created successfully', $output);
```

I think that's a lot better.

**Comment by taylorotwell** [comment]
Personally I don't have a large interest in writing many tests for these commands. They are quite simple to just test manually and see the correct files were generated and they rarely change once they are written.

**Comment by KKSzymanowski** [comment]
I understand. Thanks for explaining.

**Comment by KKSzymanowski** [comment]
I understand. Thanks for explaining.

**Pull request closed without merging**
