### PR TITLE
[5.1] Yet another another attempt to fix Swift Mailer related SSL failures (Issue #4573)

### PR DESCRIPTION
**Pull request by YOzaz**
Hi, updated way of doing transport reset.

### CODE REVIEW

**Comment by YOzaz** [comment]
Right... tests need to be updated.

**Comment by taylorotwell** [comment]
Mailgun transport for example has no "reset" method?

**Comment by YOzaz** [comment]
Update from my side: it's working correctly for half of the year already.

**Comment by taylorotwell** [comment]
@YOzaz you're not addressing the problem. Not all drivers even have a reset method to call.

**Comment by YOzaz** [comment]
@taylorotwell you're absolutely right, and I'm not complaining. Just saying that with SwiftMailer it works - therefore I had something like this implemented in my project when I was testing:
```php
if ( ! is_a( $transport, '\Swift_Transport_AbstractSmtpTransport' ) )
```
... or we can even check if there's a "transport" at all.
But don't want to patch this PR further until you'll make a decision it's required. In either case, current reset (present in Laravel core) doesn't work.

**Comment by taylorotwell** [comment]
You may want to check if `method_exists($transport, 'reset')`

**Comment by YOzaz** [comment]
@taylorotwell done: https://github.com/laravel/framework/pull/13609/commits/4048a640cce99bba7f2432e0e2a3ac8b47d2d896

**Comment by YOzaz** [comment]
But still, travis is failing, and I'm not sure how to fix it.

**Pull request closed without merging**
