### PR TITLE
[5.2] Refactor MocksApplicationServices

### PR DESCRIPTION
**Pull request by sebdesign**
Add `doesntExpectEvents` method and refactor trait to share code with `expectsEvents` method.

Addresses #11386.

### CODE REVIEW

**Comment by sebdesign** [comment]
@taylorotwell @GrahamCampbell any idea why I am getting red on PHP7? Thanks!

**Comment by krzystof** [comment]
Looks like php 7.0.0 passes but [7.0.2](http://php.net/ChangeLog-7.php) fails. Can't see why yet.

**Comment by GrahamCampbell** [comment]
> Looks like php 7.0.0 passes but 7.0.2 fails. Can't see why yet.

**Comment by GrahamCampbell** [comment]
> Looks like php 7.0.0 passes but 7.0.2 fails. Can't see why yet.

That's not related to this PR.

**Comment by taylorotwell** [comment]
So does this allow both methods to be called in one test?

**Comment by GrahamCampbell** [comment]
Please rebase.

**Comment by sebdesign** [comment]
@GrahamCampbell I will rebase when I get back home.

@taylorotwell  yes, I did write some tests on my machine:

```php
    public function testEvents()
    {
        $this->expectsEvents(Foo::class);
        $this->doesntExpectEvents(Bar::class);
        
        event(Foo::class);
    }

    public function testException()
    {
        $this->doesntExpectEvents(Bar::class);
        
        event(Bar::class);

        $this->setExpectedException(Exception::class);
    }
```

**Comment by sebdesign** [comment]
@taylorotwell Should I add the `doesntExpectEvents` method to the documentation?

Also I was thinking, would some assertions on top of these methods be helpful also? Like `assertEventsAreFired()` and `assertEventsDontFire()`?

**Comment by taylorotwell** [comment]
Sure send a docs PR. I don't see a big need for the assert methods.

**Pull request merged**
