### PR TITLE
[5.8] Write the dotenv to stderr rather than stdout

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Is this the same as fwrite(STDERR, $string)?

**Comment by GrahamCampbell** [comment]
Yes. `$output->writeln` is basically the same number of characters as `fwrite(STDERR`. :P

**Comment by GrahamCampbell** [comment]
Technically, it also does a flush to ensure the write buffers have flushed, but apart from that, it's identical. `doWrite` gets called by `writeLn` in https://github.com/symfony/console/blob/v4.1.9/Output/StreamOutput.php.

**Comment by GrahamCampbell** [comment]
Meh, we have symfony, and it's very convenient, so I used it. 🚀

**Pull request merged**
