### PR TITLE
[5.2] password validation override in ResetsPasswords

### PR DESCRIPTION
**Pull request by JamesGuthrie**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but the tests are failing.

**Comment by JamesGuthrie** [comment]
From the build log:
```
$ phpenv global 7.0
rbenv: version `7.0' not installed
The command "phpenv global 7.0" failed and exited with 1 during .
```

Seems as though it's not the tests but something in the build process that failed.

**Comment by taylorotwell** [comment]
What are you wanting to customize about the validation?

**Comment by JamesGuthrie** [comment]
The validation sets the minimum password length to 6 characters. I would like to be able to override this to 8 chars. The alternative solution is:

```php
class PasswordController extends Controller
{
    use ResetsPasswords {
        reset as parentReset;
    }

    public function reset(Request $request)
    {
        $this->validate($request, [
            'token' => 'required',
            'email' => 'required|email',
            'password' => 'required|confirmed|min:8',
        ]);
        return $this->parentReset($request);
    }

}
```

With this change I can do:

```php
class PasswordController extends Controller
{
    use ResetsPasswords;

    $this->passwordValidation = [
        'password' => 'required|confirmed|min:8',
    ];
}
```

**Pull request merged**
