### PR TITLE
[5.5] Fix missing table prefix in SQLiteGrammar compileDropColumn()

### LINKED ISSUE #22741: SQLiteGrammar compileDropColumn() ignores connection table prefix
- Laravel Version: 5.5.28
- PHP Version: 7.1.8
- Database Driver & Version: Doctrine DBAL 2.6.3

### Description:
SQLiteGrammar ignores table prefixes when ordered to compile a `dropColumn` statement. 
This exception is thrown when SQLiteGrammar queries for existing columns in `compileDropColumn` resulting in a similar exception:

`Doctrine\DBAL\Schema\SchemaException : There is no column with name 'col_name' on table 'table_name_without_prefix'.`

This happens when using SQLite driver with a table prefix configured in the connection.

### Steps To Reproduce:

1. Configure a (memory stored) SQLite connection with a table prefix.  
2. Create a migration that creates a column. 
3. Create a migration that drops the same column. 

### Notes

There is currently no test for SQLite grammar `compileDropColumn()` and prefixes are tested neither. It seems to me that creating the former would require me to mock many objects (right?). I've fixed the latter by adding a prefix to the grammar in `DatabaseSQLiteSchemaGrammarTest` though.

### PR DESCRIPTION
**Pull request by tomlankhorst**
Fixes #22741

### CODE REVIEW

**Comment by taylorotwell** [comment]
Don't change so many tests for this. Just write one new test with a new grammar for this functionality.

**Comment by sisve** [comment]
Also; this is a change in behavior and should probably target the 5.6 release and be part of the list of upgrade notes.

**Comment by tomlankhorst** [comment]
Yet this prefix issue might affect any single compile instruction as they are individually responsible for calling `$this->wrapTable($blueprint)` to correctly prefix the table. 
I've created a testDropColumn() test for SQLite but is required me to mock some quite specific parts of the Doctrine DBAL. Would like to hear your feedback. 
@sisve I agree on the different behavior, yet it seems like a deviation from expected and intended behavior.

**Comment by sisve** [comment]
Absolutely, the prefix should be used in this case. However, existing migrations are already written with workarounds where people have hardcoded the prefix. I think it's too much to ask to have people go back and change their existing migrations in the middle of the 5.5 release. It would be easier to ask that in the 5.6 upgrade guide.

**Comment by taylorotwell** [comment]
Sorry to go around about the tests but really I would just write a Integration test that creates a :memory: sqlite table and creates a table with a prefix and verifies it was created with the prefix.

**Comment by tomlankhorst** [comment]
@sisve Well, to me it seems that `dropColumn()` is not working in **any** situation when SQLite with table prefixes are used. So any currently working situation would either:

1. Use no table prefixes
2. Use prefixes and use manual queries
3. Not work because `$tableDiff` and `$tableDiff->removedColumns[]` are using wholly different table names.  

So, in these situations

1. The fix does not alter behavior
2. The fix does not alter behavior
3. The fix alters undocumented and potentially dangerous behavior

Image a situation in which one uses a main database without prefix and a test database that is prefixed with 'test_'. `dropColumn()` would mix up the databases which may have very unexpected results. 

Please current me if I'm wrong!

**Comment by tomlankhorst** [comment]
@taylorotwell I've rewritten the test to use an actual `:memory:` database.

**Comment by victorlap** [comment]
How is this test testing anything? I don't see any `assert*` functions being Calles?

**Comment by tomlankhorst** [comment]
@victorlap 
The SQLite driver will throw an exception when the prefixes are not set properly.
Their absence marks the success of the test. 
It might be good to additionally assert that `hasColumn('name')` is false.

**Pull request merged**
