### PR TITLE
[5.2] Add two methods to the ConnectionInterface

### PR DESCRIPTION
**Pull request by franzliedke**
These two are pretty helpful when integrating just the database component into another application... in my case, Flarum.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please fix the cs issues. ;)

**Comment by GrahamCampbell** [comment]
Doesn't Laravel normally not put getter methods on interfaces by design? // cc @taylorotwell

**Comment by taylorotwell** [comment]
Is there a reason you don't just depend on the concrete Connection instance?

**Comment by franzliedke** [comment]
Decoupling, I guess? ;)

**Comment by franzliedke** [comment]
Since we have an interface...

**Comment by taylorotwell** [comment]
I'm just thinking that interfaces are kind of meant to have a slim interface and not necessarily include every public method of convenience that the concrete implementation has. I would suggest just using the concrete if you need these things.

**Comment by franzliedke** [comment]
Okay, I was hoping that these could be merged since they're obviously of some use in the context of this interface. I guess I'll have to depend on the class then.

Thanks for considering!

**Pull request closed without merging**
