### PR TITLE
[11.x ] feat(helper): `with` supports more callbacks

### PR DESCRIPTION
**Pull request by flc1125**
```php
<?php

$value = chain(10);
// output: 10

$value = chain(5, function ($five) {
    return $five + 5;
}, function ($ten) {
    return $ten * 2;
}, new class {
    public function __invoke($twenty): int
    {
        return $twenty * 3;
    }
}, fn ($sixty) => $sixty / 6);
// output: 10
```

### CODE REVIEW

**Comment by henzeb** [comment]
what's different compared to using the Pipeline?

**Comment by flc1125** [comment]
> what's different compared to using the Pipeline?

I later realized that Chain is actually similar to `with`, so I made some adjustments to make `with` support multiple callbacks.

**Comment by driesvints** [comment]
Tests fail here. Please make them pass and mark as ready.

**Comment by flc1125** [comment]
> Tests fail here. Please make them pass and mark as ready.

When I executed it under the 11.x branch, I found that the same error also occurred.

**Comment by flc1125** [comment]
image

What happend?

**Comment by flc1125** [comment]
https://github.com/laravel/framework/blob/08acc925f1ec8e1c41a54774a36720f506c5b5a8/types/Support/Helpers.php#L15-L43

I think this part might need adjustments in order to pass the unit tests. Please confirm if it can be modified. @henzeb @driesvints

**Comment by henzeb** [comment]
What adjustments? adjustments can be breaking changes, and i think that any changes here would be one. That being said, I still think this is too similar to laravel's Pipeline.

**Pull request closed without merging**
