### PR TITLE
[5.5] Add PHP 7.2 to travis

### PR DESCRIPTION
**Pull request by fernandobandeira**
This PR adds PHP 7.2 as an allowed failure to travis, we need to fix some things for 5.5 to work with 7.2.

Ps: current test is failing due to #20252

### CODE REVIEW

**Comment by deleugpn** [comment]
Are you going to work on fixing the failed tests? I feel like a lot of people might jump into it

**Comment by fernandobandeira** [comment]
Yes, I'll work on it and send a separate PR fixing those tests, it's a simple fix 😄

**Comment by GrahamCampbell** [comment]
Probably a good idea to get this onto 5.4 too?

**Comment by fernandobandeira** [comment]
@GrahamCampbell Sure, sent another PR #20258 for 5.4.

**Comment by taylorotwell** [comment]
Can we just do this on 5.4 and merge it forwards?

**Pull request closed without merging**
