### PR TITLE
[6.0] Add subquery support for from() and table() - OPTION 1

### PR DESCRIPTION
**Pull request by reinink**
Currently the only way to use a subquery in a `from` query clause is to use the `fromSub($query, $as)` method. For example:

```php
$query->select('name')
    ->fromSub(function ($query) {
        $query->something();
    }, 'users')
    ->get();
```

However, if you're using the query builder via the `DB` facade, you don't have access to this functionality, since there is no `DB::fromSub()` method. So, even though `fromSub()` exists, it's really only available once you already have a query builder instance.

Further, in general, I think it's more intuitive to add subquery support to the query builder methods we use everyday, instead of having to reach for methods like `fromSub()`. See #29567 (selects) and  #29563 (orders).

This PR adds the ability to use a subquery in the `from()` query builder method, and subsequently via the `DB::table()` method. To do this I am using the same format as the proposed selects syntax (see #29567), which is a keyed array: `[$as => $query]`.

```php
$query->select('name')
    ->from(['users' => function ($query) {
        $query->something();
    }])
    ->get();

DB::table(['users' => function ($query) {
    $query->something();
}])->get();
```

-------

> **An alternate approach can be found here:** #29602

### CODE REVIEW

**Review by oliverquynh — APPROVED** [review]

**Comment by staudenmeir** [comment]
I think an associative array is not ideal in this case since we only allow a single entry.

A possible alternative: We add a second `$as = null` parameter to `from()` and `table()`.

This way, we could support subqueries *and* make table aliases more accessible:
`DB::table('users as u')` →`DB::table('users', 'u')`

**Comment by reinink** [comment]
Yeah, I considered that. For me this was about consistency. For example, I think we can use the keyed array format in `join()` (and other join methods) as well. With the joins, adding another argument really isn't an option.

To me I like the idea of sticking to this format:

1. If it's a subquery specific method (`selectSub`, `fromSub`, `joinSub`, etc.), then we use an argument for the alias (`$as`). This is existing behaviour.
2. If it's a situation where you normally give a stringed name (`select`, `addSelect`, `from`, `join`), then I think the keyed array format is better.

And I get that it's somewhat unnecessary to use an array, when you're only using the first value, but that's really the nicest syntax. Plus there is precedence for this in the framework. Think of `mapWithKeys()` in the collection class:

https://github.com/laravel/framework/blob/87148965b26af23bf38d503e33439263c1705d10/src/Illuminate/Support/Collection.php#L1192-L1205

**Comment by staudenmeir** [comment]
The array could give users the impression that they can provide multiple subqueries.

**Comment by reinink** [comment]
> The array could give users the impression that they can provide multiple subqueries.

Yep, it could. If they provide multiple, it will only use the first.

**Comment by reinink** [comment]
I've added a second PR for this, with the alternative approach that @staudenmeir suggested. See that here: #29602.

**Pull request closed without merging**
