### PR TITLE
[11.x] Authorization using Ability Objects

### PR DESCRIPTION
**Pull request by remipelhate**
Ever since Gates and Policies were introduced in Laravel, they've been essential for every application I've worked on. Gates in particular have proven extremely useful whenever I wanted to keep authorization logic for each possible ability separate from each other (using invokable classes) to avoid large and complex policies. The only "downside" of Gates compared to Policies (which have auto-discovery) is the need to explicitly define them (and the risk of forgetting to do so). We can use inline authorization using `Gate::allowIf` and `Gate::denyIf` to eliminate the need of manually defining gates, but then before and after authorization hooks don't get executed.

This is something I also "struggled" with with custom validation rules before [Rule Objects](https://laravel.com/docs/11.x/validation#using-rule-objects) were introduced, which led me to wonder if this could be solved in a similar fashion: authorization using Ability Objects.

I originally implemented this concept in a codebase as a before authorization hook (which has been working great), but felt like it might be a nice addition to the framework and decided to try and translate this into the core. I presume this PR may not cover everything yet or may require some extra test coverage, but I'm not really familiar with these internals. So any guidance is welcome.

# Proposal

Ability objects are plain php classes that provide a `granted` method, e.g.:
```php
class ViewDashboardAbility
{
    public function granted(User $user): bool
    {
        // Some authorization logic...
        return false;
    }
}
```

There is no interface to implement, as gates can be used to authorise different types of resources, not only users/authenticatables.

They can be passed as an instance to the `Gate`, which can then evaluate the ability without the need if it being explicitly defined:
```php
use Illuminate\Auth\Access\Gate;

Gate::allows(new ViewDashboardAbility());
```

## Benefits

Ability objects allow developers to isolate authorization of individual abilities into separate classes without having to define them explicitly in the `Gate`. They can therefore be evaluated "on the fly":
```php
use Illuminate\Auth\Access\Gate;

Gate::allows(new ViewDashboard());

// vs

Gate::define('view-dashboard', function (User $user): bool {
    // Some authorization logic...
});
Gate::allows('view-dashboard');
```

Additionally, they also eliminate the need to lookup the ability to determine the expected arguments, as arguments can be provided to the ability's constructor rather than through `Gate` methods:
```php
use Illuminate\Auth\Access\Gate;

Gate::allows(new ViewCompanyInfoAbility($company));

// vs

Gate::allows('view-company-info', $company);
```

### Artisan generator command

This PR includes a new `make:ability` Artisan command with similar behaviour compared to the `make:policy` command.

### Support in Authorization middleware

Ability objects can be used in middleware as follow:
```php
use Illuminate\Auth\Middleware\Authorize;

Route::put('/post/{post}', function (Post $post) {
    // The current user may update the post...
})->middleware(Authorize::using(ViewPostAbility::class, 'post'));
```

### Support in Blade directives

Ability objects can be used in Blade's authorization directives the same way they can be used through `Gate` directly:
```blade
@can(new ViewDashboard)
@cannot(new ViewCompanyInfo($company))
// ... and so on
```

## Backwards compatibility

In order to try not breaking current behaviour, I implemented resolving auth callbacks for ability objects as the last possible use case. `Gate` will always first look for policies, string callbacks and explicitly defined ability callbacks before attempting to resolve ability objects.

The additional benefit of this sequence is that developers can still explicitly define a `Gate` callback for an ability class name, which is useful to fake checking abilities when running tests:
```php
// Arrange
Gate::define(ViewDashboardAbility::class, fn (): bool => false);

// Act
$subject->performActionRequiringAuthorization();

// Assert
$this->assertBasedOnFakedAbility();
```

## Questions

- My current implementation will evaluate `Gate::has(new ViewDashboardAbility)` as false as ability objects are not explicitly defined. Would this be considered the correct outcome? Or is the purpose of `Gate::has()` to be able to determine whether an ability can be resolved?
- When providing an object instance without a `granted()` method, this implementation would currently throw a `Call to undefined method granted()` error. Should it perhaps throw a custom exception instead?

### CODE REVIEW

**Comment by shaedrich** [comment]
> There is no interface to implement, as gates can be used to authorise different types of resources, not only users/authenticatables.

However, this sounds to me like it needs an interface:

> When providing an object instance without a `granted()` method, this implementation would currently throw a `Call to undefined method granted()` error. Should it perhaps throw a custom exception instead?

**Comment by remipelhate** [comment]
The original implementation I made in a codebase indeed relied on an interface. But in that specific case, we were always using the user, so the interface made perfect sense. 

If there is any interest in adding this to Laravel, I leave it up to @taylorotwell to decide what the appropriate Laravel approach would be.

**Comment by devfrey** [comment]
I've been wanting to separate my model policies into smaller 'invokable' abilities for a while. Turns out it's actually already possible to do something close to what you suggest. It requires the ability to be defined (in a service provider), and it only works if the ability accepts an (optional) user argument:

```php
Gate::define(ViewDashboard::class, ViewDashboard::class);
```

```php
class ViewDashboard
{
    public function __invoke(User $user): bool
    {
        return true;
    }
}
```

```php
Gate::allows(ViewDashboard::class); // true
```

Laravel resolves the ability class from the container and calls the `__invoke` method on it.

There's even test coverage for these callables:
https://github.com/laravel/framework/blob/11.x/tests/Auth/AuthAccessGateTest.php#L485-L492

I think it would be slightly more beneficial to try and improve the DX around this existing functionality. For example, by introducing auto-discovery for these ability classes, or by making it easier to define them in a way that doesn't require the class name to be passed twice.

Let me know your thoughts!

**Comment by shaedrich** [comment]
> The original implementation I made in a codebase indeed relied on an interface. But in that specific case, we were always using the user, so the interface made perfect sense.

Just because you use an interface, that interface doesn't have to be tied to a user. I don't see where you make this connection.

> Turns out it's actually already possible to do something close to what you suggest. […] I think it would be slightly more beneficial to try and improve the DX around this existing functionality.

Sounds good 👍🏻

**Comment by remipelhate** [comment]
> I think it would be slightly more beneficial to try and improve the DX around this existing functionality. For example, by introducing auto-discovery for these ability classes, or by making it easier to define them in a way that doesn't require the class name to be passed twice.
> 
> 
> 
> Let me know your thoughts!

I know we can already work with invokable classes when you explicitly define them in the gate. It's actually how I've been using gates for quite a while now. Haven't thought about improving the current functionality, though, so that sure is interesting. 

However, what I personally wanted to achieve with this is to avoid passing arguments through gate methods. I like how with the setup I had in mind, we would be able to provide arguments clearly through the ability's constructor (your IDE would even suggest what types should be provided). It's basically how we work with Rule Objects as well.

If there's an option to update the current invokable class implementation this way, I'm all for it. But depending on how developers are using the current implementation, changing that with the setup I have in mind would be a breaking change.

Does that make sense?

**Comment by remipelhate** [comment]
> Just because you use an interface, that interface doesn't have to be tied to a user. I don't see where you make this connection.

Correct, introducing an interface would not require it to be tied to a user. That's not what I meant. But if an interface would be used, the argument of the `granted()` should get a generic type definition like `mixed` or `object` in order to allow the required flexibility. Or another interface would have to be introduced to be implemented by any resource that should be authorizable through ability objects.

It's all possible and to be fair, I would also prefer to work with an interface here. That's how I originally conceptualised it. But looking across the framework, I feel like there is a tendancy not to provide interfaces for such use-cases (thinking of `middleware()` for queued jobs, commands which should have a `handle()` or `__invoke()` method, ...). But if this an incorrect assumption, by all means, I'm more than happy to comply🙂

**Comment by remipelhate** [comment]
@devfrey Support in middleware is handled in this PR and does work the same way as when handled directly by Gate (see the section on support in middleware in the PR description). The way it works is that when an ability object is provided using it's classname, the Gate will automatically construct the anility with the provided arguments. So the argument will not be passed to the `granted()` method.

But I haven't looked at `AuthorizesRequest` indeed. So that would have to be added.

**Comment by remipelhate** [comment]
Just for reference, this is how I originally implemented this in one of my codebases:
```php
<?php

declare(strict_types=1);

final readonly class AuthoriseUsingAbilityObject
{
    public function __construct(
        private Gate $gate,
    ) {}

    public function __invoke(?User $user, mixed $ability): ?bool
    {
        if (! $ability instanceof Ability) {
            return null;
        }

        // If the ability class is explicitly defined in the gate, we should handle
        // the ability using the resolver defined in the gate. This allows us
        // to define a resolver to fake ability results in tests...
        if ($this->gate->has($ability::class)) {
            return $this->gate->forUser($user)->allows($ability::class, $ability);
        }

        // When the ability class in not defined in the gate, we should resolve it on the fly...
        return $ability->granted($user);
    }
}

final class ServiceProvider extends IlluminateServiceProvider
{
    public function boot(): void
    {
        Gate::before(new AuthoriseUsingAbilityObject($gate));
    }
}
```

Very simple, but it obviously gets a bit more complex when trying to integrate it into the framework.

**Comment by remipelhate** [comment]
On second thought, letting the Gate automatically resolve object abilities provided using their classname may not be a great solution. I did so to enable ability objects to be used in middleware like so:
```php
use Illuminate\Auth\Middleware\Authorize;

Route::put('/post/{post}', function (Post $post) {
    // The current user may update the post...
})->middleware(Authorize::using(ViewPostAbility::class, 'post'));

// Which does the following under the hood...
Gate::authorize(ViewPostAbility::class, $this->getGateArguments($request, $models));
```
However, when before or after hooks are defined, they will receive the ability classname (a string) as their second argument, whereas I would expect the ability object to be passed instead: 
```php
Gate::before(function (User $user, mixed $ability): void {
    //
});

// When invoked using the instance, the ViewDashboardAbility instance will be used to
// resolve authorization and be provided as the $ability argument for the hook...
Gate::allows(new ViewDashboardAbility);

// When invoked using the classname, an instance of ViewDashboardAbility will be used to resolve
// authorization, but the classname would be provided as the $ability argument for hooks...
Gate::allows(ViewDashboardAbility::class);
```
That’s some rather inconsistent behaviour. So perhaps it would be better to initialise the ability object in the middleware before passing it to the Gate. That way, before and after hooks would always receive an instance of the ability object and there would be no need for the Gate to automatically resolve ability classes to instances when provided using their classname.

**Comment by taylorotwell** [comment]
I personally don't think we need to introduce another authorization "concept".

**Comment by remipelhate** [comment]
All good! Thanks for taking the time to have a look at it @taylorotwell.

**Pull request closed without merging**
