### PR TITLE
[8.x] Add dd() and dump() to the Eloquent Model

### PR DESCRIPTION
**Pull request by sebdesign**
This PR adds `dd()` and `dump()` to the Eloquent Model.

```php
$user = User::first();

// Before
dump($user);
dd($user);

// After
$user->dump();
$user->dd();
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎 here, actually. I don't like it.

**Comment by JohnKlein1991** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️ Models in Active record are already God objects, no need to add extra functionality to them.

**Comment by sebdesign** [comment]
@JohnKlein1991 it's not about the need to add functionality, but it's syntactic sugar, e.g. when we want to debug chaining methods that intercept with models.

Another example, Taylor recently implemented the `HasBroadcastChannel` for the model, that adds convenience methods for broadcasting, which doesn't have anything to do with Active Record, but can still be valuable.

**Comment by JohnKlein1991** [comment]
It's sad. Anyway, I think the adding new responsibility to models is wrong way. And doesn't matter is it "new functionality" or "syntax sugar"

**Comment by sebdesign** [comment]
No it's not sad. I can't imagine using models without `$user->notify(new InvoicePaid($invoice))` or `$user->can('update', $post)`. That's what makes Laravel so enjoyable.

I get that the `dump` and `dd` methods are redundant, but let's not stick to the god object dogma. [Methods are affordances, not abilities.](https://adamwathan.me/2017/01/24/methods-are-affordances-not-abilities/)

**Comment by JoshSalway** [comment]
> 👎 here, actually. I don't like it.

Why?

**Comment by GrahamCampbell** [comment]
> Why?

Because:

> Models in Active record are already God objects, no need to add extra functionality to them.

This also adds an implicit dependency on the symfony dump package to our database package.

**Comment by sebdesign** [comment]
@GrahamCampbell The query builder also has dump and dd methods, so the implicit dependency already exists.

**Comment by taylorotwell** [comment]
Don't think I'll merge this for now. Also don't appreciate your comments @JohnKlein1991 😄

**Pull request closed without merging**
