### PR TITLE
[5.4] Feature/self handling queues are optional

### PR DESCRIPTION
**Pull request by daylerees**
This pull request allows for commands and handlers (whether in a queue, or command bus) to be separate as an alternative to self-handling jobs.

I have explained the purpose of this fix (and discussed it in detail) with Taylor, but I'll explain it here for the benefit of those reviewing.

Having the separation between commands and handlers makes the most sense in 'multi-app' environments that use a single queue consumer project. Consider the following:

```
APP1     APP2      APP3

    all fire queued jobs to:

          APP4
  (running queue:listen)
```

Consider the following job:

``` php
<?php

use Some\Other\Package\FooService;

class DoSomething
{
    protected $someId;

    public function __construct($someId)
    {
        $this->someId = $id;
    }

    public function handle(FooService $foo)
    {
        // Do something with foo service.
    }
}
```

Apps 1-3 might wish to fire this job, but to do so they will need to import the package for `FooService` using composer, even though it's never used from those projects.

By separating the command and handler (splitting into two classes, one a value object, the other with a handle method) and allowing the user to map commands to handlers we can fire the jobs from APP1-3 without the FooService requirement.

Mapping commands looks like the following:

``` php
Bus::map(CommandClassHere::class, HandlerClassHere::class);
```

Firing jobs should use the 'command':

``` php
$this->dispatch(CommandClassHere::class)
```

Stand alone handlers should inject their dependencies through the constructor, where existing self-handling jobs will inject their dependencies through the handle method.

This change should be backwards compatible, and still allow for self-handling jobs to function as before.

Thanks for reading!

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Didn't this get ripped out of the core on purpose in 5.2?

**Comment by daylerees** [comment]
@GrahamCampbell the jobs were originally split, and didn't offer self-handling. This patch will allow both to function.

**Comment by taylorotwell** [comment]
This brings the option of handled jobs without the complexity of `SelfHandling` interface, etc.

**Comment by GrahamCampbell** [comment]
Interesting. One small problem is that resolveName on the queue job still gives the handle method as if it were self handling.

**Comment by daylerees** [comment]
@GrahamCampbell I'll take a look at this, thanks mate!

**Comment by GrahamCampbell** [comment]
:)

**Comment by taylorotwell** [comment]
Can you send this to 5.3. I tried to do it using the new GitHub feature but it just crapped a lot of stuff up.

**Comment by GrahamCampbell** [comment]
Yeh, the github feature is only good for going forward versions rather than backwards.

**Pull request closed without merging**
