### PR TITLE
E-mail Validation Regex Update

### PR DESCRIPTION
**Pull request by akbansa**
Email Validation of Laravel 5.4 failed #19724

### CODE REVIEW

**Comment by sileence** [comment]
I kind of feel more comfortable with the PHP default validation rule, maybe adding the domain check on top of that instead of replacing the whole rule?.

**Comment by akbansa** [comment]
@sileence Can you please explain the domain check meaning here?
I am not checking that mx records are available or not, just checking that can it be a valid domain address or not!

**Comment by sileence** [comment]
Maybe checking first with the default PHP rule and if it passes then simple adding an extra check to see if the domain name is valid as well.

**Comment by devcircus** [comment]
Really seems outside the scope of framework level email validation.

**Comment by tillkruss** [comment]
That's a breaking change.

https://fightingforalostcause.net/content/misc/2006/compare-email-regex.php

**Comment by akbansa** [comment]
@sileence I agree with your part but applying extra check for domain validity again will be overhead

@tillkruss The PHP regex and JavaScript given on your link are different as one is passing **a@co.a** while one not

**Comment by tillkruss** [comment]
@akbansa: Yeah, but it's a breaking change an existing email validations will fail. Target 5.5.

**Pull request closed without merging**
