### PR TITLE
[10.x] CacheTTL helper

### PR DESCRIPTION
**Pull request by WendellAdriel**
## Changes

This PR adds a Enum CacheTTL that provides some values for cache TTL as well as some helper methods for defining TTL for cache keys in a more friendly way for developers.

## Why

This will help developers to avoid using arbitrary "magic numbers" in the code like:

```php
Cache::store('redis')->put('bar', 'baz', 600); // 10 Minutes
```

To something more friendly and self-explanatory:

```php
Cache::store('redis')->put('bar', 'baz', CacheTTL::minutes(10));
```

The goal is to improve the DX for developers providing an easy and friendly way to set TTL for the cache.

### CODE REVIEW

**Comment by huangdijia** [comment]
You can add another until method

**Comment by ju5t** [comment]
For me, `now()->addMinutes(10)` is clean enough DX already.

**Comment by taylorotwell** [comment]
I think you can already just do `->put('foo', 'bar', now()->addMinutes(10))`

**Comment by WendellAdriel** [comment]
@taylorotwell but using `now()` will instantiate a date object, this way it doesn't need to instantiate anything

**Comment by WendellAdriel** [comment]
If someone still wants to use this (because some devs reached me saying that they liked it) I decided to wrap this into a really simple and small package so you can use it if you want to:

https://github.com/WendellAdriel/cache-ttl-helper

**Pull request closed without merging**
