### PR TITLE
[5.2] Added ability to Extend Illuminate\Database\Schema\Blueprint

### PR DESCRIPTION
**Pull request by tzsk**
Added ability to Extend Blueprint by Binding it with Container in a Custom Service Provider. It will come pretty handy if someone uses their custom Blueprint in their projects.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Sorry, but we cannot couple our database component like that.

**Comment by kazi-mainuddin-ahmed** [comment]
But why? There is already a Same implementation on ResourceRegistrar Class. There seem to be no problem why here?

**Comment by GrahamCampbell** [comment]
No we don't?

**Comment by kazi-mainuddin-ahmed** [comment]
Yes... There is... Illuminate\Routing\Router.php... Line 351. Method: resource();
```
public function resource($name, $controller, array $options = [])
    {
        if ($this->container && $this->container->bound('Illuminate\Routing\ResourceRegistrar')) {
            $registrar = $this->container->make('Illuminate\Routing\ResourceRegistrar');
        } else {
            $registrar = new ResourceRegistrar($this);
        }

        $registrar->register($name, $controller, $options);
    }
```

Look there is the same implementation for the Route::resource() Methods.

**Comment by GrahamCampbell** [comment]
You said ResourceRegistrar, so I looked there, and there was nothing.

Anyway, this is different, since the router should be coupled to the container. The database should not.

**Comment by kazi-mainuddin-ahmed** [comment]
Oh... Yes... Now I understand why... Database can me used outside of Laravel... In that case there won't be any Container. So that will be an Issue. But I think Illuminate/Database is managed separately.

**Pull request closed without merging**
