### PR TITLE
[5.2] Collapse ThrottleRequests middlewares

### PR DESCRIPTION
**Pull request by Propaganistas**
Suppose the following route definition:

``` php
// In app/Http/Kernel.php
$middlewareGroups = [
    'api' => [ 'throttle:10', 'otherMiddleware', 'someOtherMiddleware' ]
];

// In routes.php
Route::group(['middleware' => 'api'], function() {
   Route::get('foo', 'SomeController@method');
   Route::get('bar', ['middleware' => 'throttle:5', 'uses' => 'SomeController@otherMethod']);
});
```

Route `foo` will behave as expected: 10 requests are allowed before being throttled.
Route `bar` to the contrary is already throttled after 3 times instead of the requested 5 times. This happens because the route is in a throttled group and as such the `RateLimiter` is hit twice.

This seems rather unwanted behavior to me. In my opinion only the closest defined throttler should be honored.

This PR filters throttle middlewares to only the very last defined.

### CODE REVIEW

**Comment by morloderex** [comment]
:-1: that may be unwanted behavior but as I see it if you wanted to limit the bar request you would just set it outside of the group entirely. It is strange to me that you are using the middleware this way.

**Comment by Propaganistas** [comment]
@morloderex I've clarified my use case by using middleware groups.

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Who's to say that's the name of the middleware used.

**Comment by Propaganistas** [comment]
I have suggested another approach here (#11500), which is actually superior to this one.

**Pull request closed without merging**
