### PR TITLE
Make return type of Policies booleans

### PR DESCRIPTION
**Pull request by DrowningElysium**
Mixed doesn't make sense as it is yes or no (true or false)

### CODE REVIEW

**Comment by browner12** [comment]
i think common convention is 

```php
@return bool
```

**Comment by DrowningElysium** [comment]
@browner12 Thanks, I wasn't sure. So if one of the team could confirm it I will change it directly

**Comment by browner12** [comment]
if you look at any other file, you'll see `bool`, so pretty safe to go with that.

**Comment by DrowningElysium** [comment]
@browner12 Thanks, changed it

**Comment by taylorotwell** [comment]
You actually can return authorization responses. You don't have to return booleans.

**Comment by DrowningElysium** [comment]
@taylorotwell Could you maybe edit the docs to also contain this information? https://laravel.com/docs/5.4/authorization#writing-policies I am missing that here

**Pull request closed without merging**
