### PR TITLE
[9.x] Improve `JsonResource::class` values

### PR DESCRIPTION
**Pull request by dinhquochan**
This PR improves the value of the `JsonResource::class`.

### Resource:

```php
return JsonResource::make([
  'array' => [1, 2, 3],
  'object' => (object) ['a' => 'b'],
  'arrayable' => $arrayableObject,
  'htmlString' => $htmlStringObject,
  'stringable' => $stringableObject,
]);
```

### Before

image

### After

image

Thanks.

### CODE REVIEW

**Comment by axlon** [comment]
This introduces a problem; because filtering happens before serialization `Arrayable` and `Stringable` will now take precedence over `JsonSerializable`.

For example:

```php
class Foo implements Arrayable, JsonSerializable
{
    public function toArray()
    {
        return ['bar'];
    }

    public function jsonSerialize()
    {
        return ['baz'];
    }
}
```

Before:

```json
["baz"]
```

After:

```json
["bar"]
```

This could be fixed by also including `JsonSerializable` and `Jsonable` in the filter method, but personally I think only jsonserializable data should be returned by a resource. If you want an arrayable object to be represented as an array, either make it jsonserializable or call `toArray()` on it manually.

**Comment by ankurk91** [comment]
This can be a breaking change for many.

**Comment by dinhquochan** [comment]
Yes @axlon, you're right. I wait for @taylorotwell's opinion.

**Comment by dinhquochan** [comment]
Extra issue, when I add casting `HtmlString::class` instance to a property of Model. It's still empty `{}` when encoding. I think it causes by `json_encode` in `Model` don't know a property is stringable.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
