### PR TITLE
☁️

### PR DESCRIPTION
**Pull request by taylorotwell**

### CODE REVIEW

**Comment by jhm-ciberman** [comment]
> what is this?

https://cloud.laravel.com/
https://www.youtube.com/watch?v=olaSFcQZQWQ

**Comment by binaryfire** [comment]
Not sure how I feel about SaaS-related code being added to the framework to be honest. Shouldn't this be in a package?

**Comment by jhm-ciberman** [comment]
@binaryfire Taylor created Laravel for free, so adding just 22 lines in a huge framework that contains thousands and thousands of lines of code it's not a big deal. 

After all, Laravel already contains hundred of lines of code for compatibility with other SaaS products (AWS, Mailgun, Algolia, etc) and no one is complaining.

**Comment by binaryfire** [comment]
@jhm-ciberman I’m not making light of Taylor’s contributions at all.

The concern is opening the door to going down the same road that Vercel has with Next. Next users are heavily locked into their ecosystem now. A bunch of features only work properly on their platform. And it happened gradually over time.

I think it’s a reasonable concern.

**Pull request merged**
