### PR TITLE
[Bug] urlencoded slashes in routing parameters

### PR DESCRIPTION
**Pull request by Artistan**
# Routing

Current routes do not allow for urlencoded slashes in the paths. This is problematic when trying to create ecommerce solutions with partnumbers in the routes since many part numbers have slashes in them.  There are also quite a few manufacturers with slashes in their names and or brands.  This commit provides the functionality to allow an uri to have encoded slashes, and other characters, in the [routes](http://laravel.com/docs/routing) and also to [create routes with those parameters](http://laravel.com/docs/routing#route-parameters). An example url may be...

https://stage.test.com/part/Cisco%20Systems%2C%20Inc/CISCO2851-SRST%2FK9

thank you!

### CODE REVIEW

**Comment by pilot911** [comment]
Strange solution Taylor. We need for autoencoding router parameters.

**Comment by Artistan** [comment]
Agreed pilot!
We have been using my package to override the routing of laravel to allow for this more robust routing option.  Not sure why it was unencoding the url before exploding the parameters, but this package makes it work I assumed it would...

(artistan/urlencode) [https://github.com/Artistan/Urlencode] [https://packagist.org/packages/artistan/urlencode]

Basically all it overrides in routing is to explode the url before unencoding the parameters.

**Comment by ameenross** [comment]
The regex Symfony uses for parts of a path is `[^/]+`. I don't think it does urldecode before that either. Laravel actually violates the RFC, as the HEX variants of reserved characters (`/` is a reserved char) do NOT mean the same as their unencoded variant.

**Comment by panzer-planet** [comment]
This is still broken and makes passing base64 encoded data in the URL impossible in Laravel. For the 80% use case indeed.

**Comment by Artistan** [comment]
@taylorotwell stated "Just don't use slashes in the URLs. " -- LMAO.
[artistan/urlencode] (https://github.com/Artistan/Urlencode) -- this package worked for me.

**Comment by Artistan** [comment]
basically it decodes the path BEFORE splitting it into parameters and that is why encoded slashes affect the parameters.

**Comment by csga5000** [comment]
@panzer-planet While I'd really like to see this fixed, why wouldn't base64 work?  URL encoding uses % and base 64 doesn't?  So there's no way a base64 string would produce a %2F.

If I'm missing something, let me know and I'll update the issue I just created.  Might as well spam them with another issue since they're ignoring this one.  Cause this is literally retarded.  There is NO reason laravel should be urldecoding the URL before you do routing.

**Comment by csga5000** [comment]
@ameenross Oh, right, I figured I was missing something.  Thanks

**Comment by ameenross** [comment]
You're welcome.

Also of interest: alternative base64 encoding, [A-Za-z0-9-_] more suited for URLs: https://tools.ietf.org/html/rfc4648#page-7

**Comment by alcaitiff** [comment]
@csga5000 and @Artistan I changed the (Artistan/Urlencode)[https://github.com/Artistan/Urlencode] to work on Laravel 5.

You can get it here [https://github.com/alcaitiff/laravel-urlencode]

**Pull request closed without merging**
