### PR TITLE
[5.2] Added RouteFound event

### PR DESCRIPTION
**Pull request by acasar**
Fixes https://github.com/laravel/framework/issues/11496

Basically I added a `RouteFound` event, so that we can inject Controller namespace based on the HTTP api-version header before implicit bindings are resolved (`RouteMatched` is fired too late).

``` php
Route::found(function(RouteFoundEvent $event) {
    // modify $event->route as needed
});
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Just had a thought. What if we implemented the parameter substitution via an event listener for that event?

**Comment by bgarrison25** [comment]
By "parameter substitution" are you talking about what I was doing in my middleware or the parameter substitution that happens in implicit model binding?

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. That would be so awesome. It would be cool if I could stop extending the router to stop the parameter substitution happening.

NB My use case is I perform non-read request locking on a per user basis, then, after a lock has been established, at that point, I do the param substitution, so I know the data is fresh.

NB The middleware that does the binding is here if anyone thinks that's a cool idea: https://github.com/AltThree/Locker/blob/master/src/Http/Middleware/LockingMiddleware.php.

**Comment by GrahamCampbell** [comment]
Yeh, my use case is all bindings.

**Comment by taylorotwell** [comment]
Yeah can y'all give code examples of these use cases?

**Comment by bgarrison25** [comment]
Excuse me if this isn't what your looking for....im pretty new to core development. I have a middleware that replaces a placeholder in the "uses" with the api version namespace from the header. This is the handle method of the middleware:

```php
public function handle($request, Closure $next)
	{
		$route = $request->route(); 
		$actions = $route->getAction();

		$requestedApiVersion = ApiVersion::get($request);
		if (!ApiVersion::isValid($requestedApiVersion)) {
			throw new ApiVersionException('Invalid API Version');
		}

		$apiNamespace = ApiVersion::getNamespace($requestedApiVersion);

		$actions['uses'] = str_replace('{api-namespace}', $apiNamespace, $actions['uses']);

		$route->setAction($actions);

		return $next($request);
	}
```

**Comment by GrahamCampbell** [comment]
Currently, I extend the router:

image

Then I have a middleware that runs it:

image

Then, the middleware applied is looking something like this:

```php
            LockingMiddleware::class,
            SubstituteBindings::class,
```

**Comment by GrahamCampbell** [comment]
So, at this point I've already started the session, authenticated the user, acquired a lock, then only then do I subsisute the bindings. This also reminds me of that issue we had previously were some people were concerned about ddos attacks regarding this binding, specifically targetting the database.

**Comment by GrahamCampbell** [comment]
> Excuse me if this isn't what your looking for....im pretty new to core development.

No worries at all. Your middleware and use case looks pretty similar at the end of the day to mine. You, ultimately, one to have some sort of guard before then doing the bindings.

**Comment by acasar** [comment]
@GrahamCampbell Did you have something like that in mind?

**Comment by taylorotwell** [comment]
**Copying my thoughts from Slack**

what is the difference between routeFound and routeMatched

​[5:03] 
those sound the same to me

​[5:03] 
in fact RouteMatched is fired just a few lines later

​[5:04] 
i dont really see why you need a separate event for this

​[5:04] 
instead of just substituting bindings in the route matched event

​[5:04] 
i also worry about attaching multiple listeners on this event in a unit testing scenario if the app is maintained across unit tetts

**Comment by GrahamCampbell** [comment]
Taylor, the important difference is that it's before we query the database, so we can bail out first if we need to.

**Comment by GrahamCampbell** [comment]
I'm not entirely sure that I really like this fix though.

**Comment by GrahamCampbell** [comment]
Maybe this event isn't the way to go.

**Comment by acasar** [comment]
I'd much prefer to just fire a single event too.

**Comment by acasar** [comment]
I deleted the last commit that moved substituteBindings in an event. At least until we find a better solution.

**Comment by GrahamCampbell** [comment]
Yhe event should not extend the other event.

**Comment by acasar** [comment]
@GrahamCampbell  Fixed.

**Comment by bgarrison25** [comment]
@GrahamCampbell I understand if this isn't the fix you want but I would be interested in how you would solve my problem without it. 

I require a header on calls to my API called 'api-version' and CURRENTLY a middleware that pulls that api-version and determines if its valid (according to my white list) and then, using a mapping, determines the namespace of this version. It then injects this version into a placeholder that I have on my routes. Ex: `Route::get('member/{id}', '/whatever/{api-namespace}/MembersController@show');`

With implicit model binding the `'/whatever/{api-namespace}/MembersController@show'` triest to get reflected and fails miserably because the implicit model binding gets run before middleware (as expected). Someone here decided it would be a good idea to listen to the `routeMatched` event and do my manipulation of the route there. However this event fires AFTER the implicit model binding and there are no events fired before. 

All this I say as a "quick" description of what brought us to this point. If you have another solution for custom placeholder manipulation inside of the route "uses" attribute that doesn't cause implicit model binding to explode i am all ears. Or even if you have a better way of Api versioning that fits along the same lines but doesn't mess with the route?

**Comment by bgarrison25** [comment]
So is this going to be pulled into 5.2 or should I just hack a workaround?

**Comment by taylorotwell** [comment]
I still don't understand why you can't just move substituteBindings into a RouteMatched event. Why add a second event?

**Comment by bgarrison25** [comment]
We can't do that because of this line ` $parameters = (new ReflectionMethod($class, $method))->getParameters();` which happens on line 263 in Route.php in the method "signatureParameters". It happens BEFORE the RouteMatched event is called and tries to call a reflection of a string that would have custom bindings in it which fails miserably.

**Comment by bgarrison25** [comment]
@taylorotwell am i not clarifying well enough? Do you have any more questions?

**Comment by bgarrison25** [comment]
@acasar As it seems this won't be getting merged do you have any suggestions on how i might implement api versioning / namespacing using a header in the request?

**Comment by acasar** [comment]
@bgarrison25 Can't you just provide a valid namespace for a class (e.g. v1 by default) and then substitute it in the ``RouteMatched`` event if needed?

**Comment by acasar** [comment]
On the side note: In my experience, whenever I needed API versioning I always put the version in the URL. Sure it may not be a "best practice", but it's very flexible, easy to implement and many big companies are also using that approach... (Twitter, Facebook, etc.).

**Comment by bgarrison25** [comment]
@acasar I would prefer to keep the version in the header. I have sort of built around it. Also, the issue with your proposed fix above is that I want the version of the api that they send in to determine the namespace of the controller. So if its v3 it will be App\Http\Controllers\v3\....This is why all my routes had the {api-namespace} tag in them. The problem is I can't use custom tags anymore because when implicit model binding occurs it checks to see what the parameters of App\Http\Controllers\{api-namespace}\FooController@Bar are. It tries to do a reflection call on that and obviously fails. This is why I was pushing for an event BEFORE implicit model binding....or even having the existing event happen before....whatever works best....but since that doesn't seem to be happening im not sure where to go....

**Comment by acasar** [comment]
@bgarrison25 To be honest, (after sleeping on it) I think that adding a new event would be confusing and is also quite a "hacky" way to achieve routing based on headers.

If you want to stick with header routing, then I'm afraid you'll need to develop some workaround. Maybe you could use a global middleware or App:before() filter? In this case you will of course need to inject the correct namespace into all of your API routes, since the current route is not resolved yet at that point.

Maybe in the future, we'll have some way of generically dealing with this problem. I imagine it could look something like this:

```php
Route::group(['header' => 'Version:3'], function() {
    Route::get('...');
});
```

But of course someone would need to develop that.

**Comment by EliasZ** [comment]
In my opinion routing based on headers is a smell. That's (according to the spec) not what headers are for (unless you interpret "request modifer" as such).

**Pull request closed without merging**
