### PR TITLE
[5.1] Update type hint in concrete class of Illuminate\Contracts\View\Factory interface

### PR DESCRIPTION
**Pull request by nguyentienlong**
update variable type hint and return type hint - should be abstract or interface (L and D principle in SOLID principles)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please update the implementation with the same typehints.

**Comment by nguyentienlong** [comment]
@GrahamCampbell ah ok, I will update it soon

**Comment by nguyentienlong** [comment]
@GrahamCampbell  this is not `FactoryContract` interface. What did you mean ?

**Comment by GrahamCampbell** [comment]
Please update the contract to match the implementation then. ;)

**Comment by GrahamCampbell** [comment]
If both are already totally in sync, please let me know. I've not checked, but that was my only concern.

**Comment by nguyentienlong** [comment]
I did check the contract https://github.com/illuminate/contracts/blob/5.1/View/Factory.php . Its sync

**Pull request merged**
