### PR TITLE
[5.5] Fix for empty Collection

### PR DESCRIPTION
**Pull request by decadence**
https://github.com/laravel/framework/pull/19616

### CODE REVIEW

**Comment by tillkruss** [comment]
Why was this merged into `master` and not `5.4`?

**Comment by decadence** [comment]
It's already done
https://github.com/laravel/framework/pull/19671

**Comment by tillkruss** [comment]
Ah, thanks!

**Comment by decadence** [comment]
Initially I made it for master because wrongly thought this method is for 5.5 only (maybe because it was merged in master by that moment).

**Pull request merged**
