### PR TITLE
[7.x]Fixes the issue when using cache:clear with PhpRedis and a clustered

### PR DESCRIPTION
**Pull request by JasonXup6**
This is simply a replication of the fix by @willbrowningme in MR #36281 which was already merged to the 8.x release branch, 

@J5Dev in MR #36665 which was already merged to the 6.x release branch.

but it's still unfixed in the 7.x release, so this PR is a simple replication of previously above mentioned.

I have tested that as with the other branch, these changes not only work, but also have no adverse affects.

### CODE REVIEW

**Comment by driesvints** [comment]
Laravel 7 isn't maintained anymore, sorry.

**Comment by JasonXup6** [comment]
I want to know why 6.x can merged which  MR #36665, but 7.x can't ?
Or have any solution for this issue whithin 7.x , whihout upgrade to 8.x.

**Comment by driesvints** [comment]
Laravel 6 is LTS

**Comment by JasonXup6** [comment]
OK, I understand, thanks for quick reply.

**Pull request closed without merging**
