### PR TITLE
[9.x] Added support for notification based events

### PR DESCRIPTION
**Pull request by tkaratug**
This PR adds support for executing any kind of action while sending a notification or after a notification is sent. And those actions are defined in notifications.

This can be done already using notification events but those events are dispatched for all notifications in the project. With this PR it will be possible to execute any kind of action only for a specific notification.

1- Actions that need to be executed while sending a notification can be added in `onSending()` method of the notification.
```php
public function onSending($channel): void
{
    logger('The notification is being sent via '.$channel);
}
```

2- Actions that need to be executed after a notification is sent can be added in `onSent()` method of the notification.
```php
public function onSent($channel): void
{
    logger('The notification has been sent via '.$channel);
}
```

The final notification will be like following:
```php
class FooNotification extends Notification
{
    public function __construct()
    {
        //
    }

    public function via($notifiable): array
    {
        return ['database', 'mail'];
    }

    public function toMail(mixed $notifiable): MailMessage
    {
        return (new MailMessage)
            ->subject('foo')
            ->markdown('emails.foo_notification');
    }

    public function toDatabase(mixed $notifiable): array
    {
        return [
            'message' => 'Lorem ipsum dolor sit amet',
        ];
    }

    public function onSent($channel): void
    {
        logger($this::class.' has been sent via '.$channel);
    }

    public function onSending($channel): void
    {
        logger($this::class.' is being sent via '.$channel);
    }
}
```

### CODE REVIEW

**Comment by bert-w** [comment]
How about https://laravel.com/docs/9.x/notifications#notification-events

**Comment by tkaratug** [comment]
> How about https://laravel.com/docs/9.x/notifications#notification-events

Yes, you may be right but notification events are dispatched for all notifications in the project. My point is to execute any kind of action only for a specific notification.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by tkaratug** [comment]
Hi,

I have released a package for the need mentioned in this PR. Hope it will be useful for the community.
https://github.com/tkaratug/laravel-notification-event-subscriber

**Pull request closed without merging**
