### PR TITLE
[5.2] Invoke sendLogoutResponse method when logout

### PR DESCRIPTION
**Pull request by ElfSundae**
Give app a chance to return custom response.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Surely you should just override the `logout()` method?

**Comment by ElfSundae** [comment]
Just like `AuthenticatesUsers::handleUserWasAuthenticated`, maybe the controller wants to return a JSON response in this `sendLogoutResponse` method, or flash data.
Of cause we can overwrite or override the `logout()` method, but when the Laravel framework updates, we may should modify the overwritten method again if there are new features in the `logout()` method.

**Comment by ElfSundae** [comment]
Ref. #13818

**Comment by taylorotwell** [comment]
Just override the logout method. That is the intention.

**Pull request closed without merging**
