### PR TITLE
Single Action Responsibility Controller

### PR DESCRIPTION
**Pull request by FelipeeDev**
Here's a solution proposal for the Single Action Responsibility Controller.

After that we can create such a Routes i.e.:

`Route::get('foo', ['uses' => 'FooClass']);`

and declare controller class with `handle` method that is responsible for the action. So we don't need to use `__invoke` magic method.

### CODE REVIEW

**Comment by browner12** [comment]
is this just for naming consistency? so we can name our method `handle` instead of `__invoke`?

**Comment by browner12** [comment]
@taylorotwell he just wants to be able to name the method `handle` or `__invoke`, which does not currently work.

doesn't change any functionality, but stays in line with listener and other namings, and we don't have to hijack the magic method.

personally i could take it or leave it.

**Comment by FelipeeDev** [comment]
@taylorotwell I know that Laravel supports this: `Route::get('foo', 'FooController');`. What I want to get is to stay straight with the new web convetion ( which is head by Laravel) and have a possibility to declare class as like other system components (Listeners, Comands, Jobs etc.).

So I think that my proposal is more than justified.

**Comment by sisve** [comment]
> ... stay straight with the new web convetion ( which is head by Laravel)

What new web convention are you talking about? Have you found someones private blog where they overract to the single-responsibility-principle? You have no links in this issue that explains this new convention. And how can it be headed by Laravel if it isn't already in Laravel?

Give some links, explain this new convention, and explain how this implementation is better than the things we already support.

**Comment by sisve** [comment]
Also, may I suggest that you do not suddenly provide a PR with "a solution proposal for the Single Action Responsibility Controller", but instead start a discussion in https://github.com/laravel/internals?

**Comment by FelipeeDev** [comment]
@sisve in fact this isn't new convention in Laravel. It already exists in Laravel (as I metioned before). SARC also occurs in the Framework (as Taylor mentioned) but in other way (by a `__invoke` magic method). My intetion was to show a small improvment (with a PR) and maybe start a discussion about. Well - the word 'new' is a shortcut of some trands that are held.

When developing big project (but not only) - Application design on the basis of individual object liability is commonplace.

I am not going to force this convention but to fine-tune it as an alternative. It works graet with CQRS as well as with MVC.

If you realy need a link here is one:
https://jenssegers.com/85/goodbye-controllers-hello-request-handlers
But it only describs the solution that is already in Laravel.

But as I said before - I do not want to force it so much - when we designe application we should fin d a balnace between conventions.

**Comment by sisve** [comment]
My thoughts is that you're using a term (Single Action Responsibility Controller) which isn't used by the link. That term isn't used on the web at all, according to Google. . I believe that a proper implementation of _request handlers_ are much larger than this PR, we need to discuss the name, consider documentation, write tests, compare the features to other frameworks to make sure we don't make up something that is totally weird, etc.

The next step would be to discuss it on https://github.com/laravel/internals

**Comment by FelipeeDev** [comment]
@sisve 
OK, here is the proposal:

https://github.com/laravel/internals/issues/926

Is it what You expected?

**Pull request closed without merging**
