### PR TITLE
Added @mix and @asset blade directives

### PR DESCRIPTION
**Pull request by OwenMelbz**
This is a simple PR that provides access to a `@asset()` and `@mix()` blade directive to allow a more short hand access to the helpers, recently many directives such as `@json` `@dump` etc this continues that.

```html
<link href="{{ mix('css/app.css') }}" rel="stylesheet">
<!-- vs -->
<link href="@mix('css/app.css')" rel="stylesheet">

<img src="{{ asset('img/logo.svg') }}" alt="Laravel logo">
<!-- vs -->
<img src="@asset('img/logo.svg')" alt="Laravel logo">
```

### CODE REVIEW

**Comment by robclancy** [comment]
That makes like no difference.

**Comment by OwenMelbz** [comment]
@dump made it in and various others.

If it doesn’t negatively impact anything, yet allows users more choice - what’s the downside?

**Comment by robclancy** [comment]
`@dump` sounds like an even worse idea

**Comment by OwenMelbz** [comment]
Bit awkward 
https://github.com/laravel/framework/blob/5.6/src/Illuminate/View/Compilers/Concerns/CompilesHelpers.php#L34 👀

**Comment by robclancy** [comment]
Seeing @dd there too seem worse again haha. Both providing an easy way for people to accidently leave debug data in and making people think it is okay to dump in a template as a way to debug instead of using real tools :thinking:

**Comment by devcircus** [comment]
Never been a fan of global helpers that save a couple of keystrokes, but many in the community seem to think highly of them. So 🤷🏼‍♂️

**Comment by taylorotwell** [comment]
I'm torn on this one I think. To me, it would feel more appealing maybe if I didn't have to even do the link or script tags or whatever. Otherwise I'm not sure it feels like much of a win to me. Thanks for the PR!

**Pull request closed without merging**
