### PR TITLE
[5.8] Add db:wipe Artisan command

### PR DESCRIPTION
**Pull request by antonkomarev**
This PR adds `db:wipe {--database=} {--drop-views} {--drop-types} {--force}` Artisan command.

While developing automated migration & backup restoration process I found very useful to have a quick way to drop all the tables, views and types. It prevents database corruption because of foreign keys and allows to implement full backup restoration on application level.

You could say that there is a `migrate:reset` command. Yes it is, but it's very slow on many migrations amount because it iterates thru the `migrations` table and executes `down` method for each migration. But more important thing that `down` method could be missing if migrations designed to go only up or there is no dropping foreign keys in them. Reset progress will be broken and database became corrupted. You wouldn't be able to run `migrate:reset` again and you will be forced to drop all tables, views & types directly in database.

### CODE REVIEW

**Comment by antonkomarev** [comment]
I've made `migrate:fresh` command simpler. Now it just calls `db:wipe` and then `migrate`.

**Comment by bonzai** [comment]
#15281

**Comment by antonkomarev** [comment]
@bonzai thanks for linking related PR! I hope Taylor will reconsider his decision. It doesn't add additional complexity and simplifies `migrate:fresh` command.

**Comment by staudenmeir** [comment]
The removal of methods makes this a breaking change. Please target the `6.0` branch.

**Comment by antonkomarev** [comment]
@staudenmeir you are right. I forgot that these methods are protected, not private. Changed target = to `master` branch.

**Comment by antonkomarev** [comment]
Resubmitted as #29620

**Pull request closed without merging**
