### PR TITLE
[5.2] Handle InnoDB Deadlocks By Re-Attempting Transactions

### LINKED ISSUE #5380: [5.0] Handle InnoDB Deadlocks By Re-Attempting Transactions
I think Laravel should have built-in support for re-attempting transactions when they fail due to a deadlock. I noticed there was a recent update to re-attempt queries when the connection has "gone away" so I guess this is similar.

The exact error MySQL gives is:
````
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
````

The MySQL docs (http://dev.mysql.com/doc/refman/5.0/en/innodb-deadlocks.html) state:
> Normally, you must write your applications so that they are always prepared to re-issue a transaction if it gets rolled back because of a deadlock.

and

> Always be prepared to re-issue a transaction if it fails due to deadlock. Deadlocks are not dangerous. Just try again.

I think this would help make the framework more "stable" (or accommodating) than it is now, handling somewhat expected cases such as InnoDB locking.

Cheers

### PR DESCRIPTION
**Pull request by agustinprod**
On MySQL galera cluster, deadlocks happens very often. Fixes #5380

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This needs to go to 5.1.

**Comment by killgt** [comment]
Should I do another pull request at 5.1 branch?

**Comment by InstanceOfMichael** [comment]
Correct me if I'm wrong, but just to clarify, I'm pretty sure this retries the MySQL connection, not the actual transaction in deadlock.

**Comment by davidsivocha** [comment]
@InstanceOfMichael is right! This doesn't solve the problem at all, it just tries to call reconnect, which still makes deadlocks fail because you can't reconnect when there is an open transaction in MySQL waiting to be finished. In now way does this fix #5380 at all. If anything it just compounds the problem!

**Comment by killgt** [comment]
I cannot actually test the patch, the deadlocks happen on a 4.2 app. But correct me if i'm wrong, this error happens even if you are not using transactions (atleast on Galera cluster) and in that case, this should work.

There is any way to trigger this deadlock on a single instance mariaDB? I'll be happy to provide a full patch to fix this issue.

**Comment by davidsivocha** [comment]
Yes, it solves the issue in a single use case. But that's not the cause in the issue it pupports to fix (#5380).

When a deadlock happens in normal use cases, this added line will cause your DB to reconnect and to re-try to query that was deadlocked, which is fine!

The problem is that if you have started a `DB::transaction()` this method causes your transaction to fail because if you deadlock, it tries to reconnect, which you cannot do while mid transaction which triggers another PDO error, instead of handling the deadlock correctly (either initiating a rollback, or attempting to retry the transaction).

`DB::transaction()` `DB::commit()` and `DB::rollback()` cannot ever let you reconnect your PDO instance.

**Comment by InstanceOfMichael** [comment]
> this error happens even if you are not using transactions (atleast on Galera cluster) and in that case, this should work.

Yes, the pull request is definitely important and a bugfix, but the description of the bugfix is misleading (or blatantly wrong).

If anyone actually wants automatic retries, they'll need to write their own fancy ``DB::transaction(function(){ ... })`` replacement checking things like ``DB::transactionLevel()``

**Comment by davidsivocha** [comment]
For me, automatic retries aren't even a problem. The problem lies in the fact that the framework tries to force a reconnect regardless of the nature of the query being run. If a `DB::transaction()` has started, PDO should never attempt a reconnect.

**Comment by InstanceOfMichael** [comment]
``DB::transaction()`` definitely needs an upgrade, I've thought about some fluent builder things like:

```
Transaction::make(function(){
    [...]
})
->retries(3)
->exec();
```

But I've never written anything.

**Comment by davidsivocha** [comment]
The other issue at play here is that you are also treating a Deadlock as a Disconnect, which is also not the case. A deadlock and a disconnect are two completely separate things. 

In a nutshell, a Deadlock needs to either retry or discard (and rollback if you are in a transaction), not force a reconnect because a Deadlock is **not** a disconnect

@InstanceOfMichael That would actually make a lot of sense. A decent transaction builder would be lovely to have in here, especially if you can specify a retry count before discard and rollback.

**Comment by taylorotwell** [comment]
Should this be reverted. Could someone with some more knowledge make a PR?

**Comment by GrahamCampbell** [comment]
NB If it is reverted, or simply repaired, this will need to happen on 5.1.

**Comment by InstanceOfMichael** [comment]
> Should this be reverted? Could someone with some more knowledge make a PR?

Probably, I have an exception where I attempt to ``DB::rollback()`` an unexpected open transaction from a previous queue job (so ``DB::transactionLevel()`` returns 1) and ``PDOException``: ``There is no active transaction`` is thrown. One or more of these need to happen:

- ``Illuminate\Database\Connection`` needs to set ``->transactions = 0`` on reconnect.
- ``Illuminate\Database\Connection`` needs to be deconstructed and fresh re-instanciated.
- need a way to tell a single queue worker (not all of them) to restart.

**Pull request merged**
