### PR TITLE
[5.4] [WIP] Namespacing tests

### PR DESCRIPTION
**Pull request by themsaid**
Started with Auth tests, I basically moved the test classes under namespaces that match the structure of the core classes they test.

### CODE REVIEW

**Comment by morloderex** [comment]
Curious why namespace the framework tests?

**Comment by GrahamCampbell** [comment]
Not sure how useful this is tbh. Will only cause merge conflicts.

**Comment by taylorotwell** [comment]
This is an experiment to see if it's nicer.

**Comment by JosephSilber** [comment]
Love this :+1: 

Shouldn't we have separate folders for unit/integration tests?

**Comment by themsaid** [comment]
@JosephSilber yes it's part of the plan if it works, trying to tidy up tests a bit so that we have some sort of guidelines on where to put tests related to specific part, etc...

**Comment by GrahamCampbell** [comment]
> This is an experiment to see if it's nicer.

I do like namespaced tests, but at what cost?

**Comment by taylorotwell** [comment]
Closing this for now so I can get it out of list until we are ready to revisit this for real. Will re-open then. Thanks

**Pull request closed without merging**
