### PR TITLE
[5.4] Include the password hash in auth session

### PR DESCRIPTION
**Pull request by themsaid**
This PR uses the following format for the auth session `id||password_hash`, while attempting to bring the user from the session we'll compare the password hash with the current one in the DB and fail in case no match were found.

So now if the password hash changes all logged in instances of the user will be logged out, this includes the user who changed the password as well, to prevent kicking that user out the developer needs to use `Auth::refresh()` after changing the password.

```
auth()->user()->update([
    'password' => bcrypt('caro')
]);

Auth::refresh();
```

### CODE REVIEW

**Comment by caiquecastro** [comment]
I think it should be done in a more flexible way. Like facebook that let you keep logged even if you change your password.

**Comment by themsaid** [comment]
@caiquecastro you may use `Auth::refresh()` after password reset to keep yourself logged in.

**Comment by taylorotwell** [comment]
We would probably want to keep people logged in by default.

**Comment by srmklive** [comment]
@taylorotwell Would it make sense to automatically login in the user again in case all logged in sessions are cleared?

**Comment by caiquecastro** [comment]
Where is the implementation for the Auth::refresh? I didn't find this method in any classes referenced on the Auth facade.

But related to the PR, this is a good thing that can be mentioned on the docs. I can submit a PR there.

**Comment by caiquecastro** [comment]
I didn't see the method refresh is implemented on this PR. Sorry!

**Comment by themsaid** [comment]
The issue here is that we need to refresh the session after the password change, so we need to listen to that change event, but the Authenticable model can be any Model actually so it's a bit confusing to me how we can detect the password change event for all authenticable models. 
Ideas?

**Comment by srmklive** [comment]
@themsaid Wouldn't it be better if the password hash changes, all the sessions associated with the current user in the database are logged out, but the user is automatically logged in after the password hash was changed?

**Comment by themsaid** [comment]
> after the password hash was changed

That event is what I'm trying to catch but not sure how.

**Comment by srmklive** [comment]
@themsaid How about storing the previous hash in a session? This way, whenever user updates the password it will also update the hash. When that occurs, you can compare the new hash with the old hash value. This will tell us that all active sessions associated with previous hash should be cleared, and the user should be immediately logged in based on new password hash.

**Comment by taylorotwell** [comment]
@srmklive there is no way for us to really hook into this without the user adding code on their application.

**Comment by srmklive** [comment]
@taylorotwell yes i agree, that is something that needs to be done on the user end.

**Pull request closed without merging**
