### PR TITLE
[8.x] Add Route::missing()

### PR DESCRIPTION
**Pull request by hotmeteor**
This PR introduces a new `->missing()` method to `Route`.

Here's the intention...

Let's say you have a route that's using implicit route-model binding (in this case, bound to a particular attribute):
```php
Route::get('/locations/{location:slug}', [LocationsController::class, 'show'])
    ->name('locations.view');
```
Now, if that record doesn't exist, or has been removed, it'll throw a 404 if someone tries to access it. Currently to mitigate that you'd need to customize the controller method to check for it's existence and then handle it accordingly.

Instead, it would be great if there was an `->missing()` method that accepted a callback and handled the situation, ie:
```php
Route::get('/locations/{location:slug}', [LocationsController::class, 'show'])
    ->name('locations.view')
    ->missing(fn($request) => Redirect::route('locations.index', null, 301));
```

To do this we'd now be catching a `ModelNotFoundException` in the `SubstituteBindings` middleware, but this seems acceptable since it'll only be doing this if it detects an `missing` fallback.

Open to suggestions!

### CODE REVIEW

**Comment by reinink** [comment]
A couple ideas here Adam.

One, would `missing` be a better name than `else`?

It might be smart to also accept a callback here, instead of providing the response straight up. That would allow you to lazily create the response, and potentially even get access to the request.

Something like this:

```php
Route::get('/locations/{location:slug}', [LocationsController::class, 'show'])
    ->name('locations.view')
    ->missing(fn () => Redirect::route('locations.index', null, 301));
```

**Comment by GrahamCampbell** [comment]
Missing, fallback, default?

**Comment by hotmeteor** [comment]
@reinink @GrahamCampbell 

Thanks. Updated method to be called `missing()`, and it now accepts a callback.

**Comment by taylorotwell** [comment]
@hotmeteor did you test this with Route caching? Is your "missing" attribute persisted in that case? If so, how so when it is using a Closure?

**Comment by hotmeteor** [comment]
@taylorotwell 

Thanks for pointing that out, I hadn't. I've updated this to handle caching, and tested it.

As part of this modified the `SubstituteBindings` middleware instead of the `Router`, which I felt made it a clearer entrypoint for handling this but possibly less backwards compatible (?) Happy to take suggestions here.

**Comment by browner12** [comment]
This reminds me of my "Internal Redirects" PR from a year ago.

https://github.com/laravel/framework/pull/30806

I still think it would be great if we could handle this through internal routing, rather than making a separate HTTP request.

**Comment by hotmeteor** [comment]
@browner12 My intent with this was that there specifically _would_ be a separate HTTP request, because I want to report to Google that a page is no longer available.

**Comment by browner12** [comment]
My original intent with the PR is that you could return a 404 status with a customized view that is still run through a controller.

If you're sending a 404 a search engine should pick that up as a dead page, doesn't need to be a 3xx.

**Comment by GrahamCampbell** [comment]
You could just serve a 404 page with js that redirects the user. Then you get the correct status code and good UX. ;)

**Comment by browner12** [comment]
Just so I'm understanding correctly, you are suggesting that as a way to solve OP's need with my internal routing solution, correct?

**Comment by adampatterson** [comment]
It would be nice if this could work with a route group.

I have a route group prefixed with a `username` and then a number of routes under that like `username/blog`. I was hoping that this would help clean up some validation.

**Comment by lucagrandicelli** [comment]
How about handling this method on resource controllers (rc)?
It seems that when routing with rc /w route-model binding, if the model is not found (i.e bad ID in the URL), the Exception Handler class takes over any possible try/catch in the code, so basically there ain't no way to return specific response on a 'ModelNotFoundException' or 'NotFoundHttpException' in the controller code. Especially when dealing with API.

**Comment by hotmeteor** [comment]
@lucagrandicelli Look in `ResourceRegistrar`, you'll need to catch an exception in there when trying to resolve the resource method.

**Comment by smarano** [comment]
Maybe is too late, but what about if you have a route with more than one implict-binded model ?`
ex:  '/locations/{location:slug}/{sublocation:slug}'

**Comment by sakihl** [comment]
Coming late to this I have just started using missing() and finding it very useful and would like to echo the comment by @smarano that it would be even nicer if you could know which model was missing where there is more than one in the route.

**Comment by mehdismekouar** [comment]
Nevermind, i found the solution...

```php
Route::get('/tags/{tag}', [TagController::class, 'show'])->missing(function (Request $request) {
    return response()->view('error');
});
```

**Pull request merged**
