### PR TITLE
[5.8] Fix DELETE queries with alias on SQLite

### LINKED ISSUE #29141: Generated query for SQLite is incorrect when deleting records with JOIN and table aliases
- Laravel Version: 5.8.28
- PHP Version: 7.2.10
- Database Driver & Version: SQLite 3.20.1

### Description:

When using Query Builder to generate a delete query with JOINs and table aliases for a SQLite database results in a incorrect SQL query that on execution throws an exception. When the database was switched from SQLite to MySQL the generated query was executed successfully.

From what I understood this line in `Illuminate/Database/Query/Grammars/SQLiteGrammar.php` ([L194](https://github.com/laravel/framework/blob/c6c6434e2c1c14f1c66cd91184e33beed488bee7/src/Illuminate/Database/Query/Grammars/SQLiteGrammar.php#L194)) is responsible for the malformed queries. 

This issue has some similarities to #18098, though its seems to require a different solution, since `DELETE a FROM table_a AS a` appears to execute fine on MySQL, but not on SQLite.

Generated query:
```
delete from "table_a" as "a" where "rowid" in (select "table_a" as "a.rowid" from "table_a" as "a" inner join "table_b" as "b" on "a"."id" = "b"."table_a_id")
```

Exception:
`SQLSTATE[HY000]: General error: 1 near "as": syntax error (SQL: delete from "table_a" as "a" where "rowid" in (select "table_a" as "a.rowid" from "table_a" as "a" inner join "table_b" as "b" on "a"."id" = "b"."table_a_id"))`

### Steps To Reproduce:

**Setup project to use SQLite database and create the following tables:**

```
Schema::create('table_a', function (Blueprint $table) {
    $table->increments('id');
});

Schema::create('table_b', function (Blueprint $table) {
    $table->increments('id');
    $table->unsignedInteger('table_a_id');
});
```

**Run following query builder code:**

```
DB::table('table_a as a')
    ->join('table_b AS b', 'a.id', '=', 'b.table_a_id')
    ->delete();
```

### Workaround:

Disclaimer: this workaround wasn't thoroughly tested so it might not work in all scenarios.

Code:
```
DB::table('table_a')
    ->join('table_b AS b', 'table_a.id', '=', 'b.table_a_id')
    ->delete();
```

Generated query:
```
delete from "table_a" where "rowid" in (select "table_a"."rowid" from "table_a" inner join "table_b" as "b" on "table_a"."id" = "b"."table_a_id")
```

### PR DESCRIPTION
**Pull request by staudenmeir**
`DELETE` queries with an alias don't work on SQLite:

```php
DB::table('users as u')->join('posts', 'posts.user_id', '=', 'u.id')->delete();

// expected
delete from "users" as "u" where "rowid" in (
  select "u"."rowid" from "users" as "u"
  inner join "posts" on "posts"."user_id" = "u"."id"
)

// actual
delete from "users" as "u" where "rowid" in (
  select "users" as "u.rowid" from "users" as "u"
         ^^^^^^^^^^^^^^^^^^^^
  inner join "posts" on "posts"."user_id" = "u"."id"
)
```

Fixes #29141.

### CODE REVIEW

**Comment by driesvints** [comment]
@staudenmeir thanks!

**Comment by taylorotwell** [comment]
Conflicts here.

**Comment by staudenmeir** [comment]
@taylorotwell Resolved.

**Comment by driesvints** [comment]
@staudenmeir small tip: if you rebase your branch instead of merging you prevent the extra merge commit from being added. This keeps the commit history a little cleaner.

**Pull request merged**
