### PR TITLE
Use array_has() instead of hack.

### PR DESCRIPTION
**Pull request by franzliedke**
If we already have a method, why not use that?

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is not correct. It doesn't actually do the same thing.

**Comment by franzliedke** [comment]
Please explain.

**Comment by GrahamCampbell** [comment]
The current way we're still checking it's not the same as microtime(true) even if it is set.

**Comment by franzliedke** [comment]
Yeah, but that's just a hack, abusing the fact that it's highly unlikely a config value will return that value.

**Comment by franzliedke** [comment]
@GrahamCampbell Can you reopen this? I don't understand your argument. =)

**Comment by JoostK** [comment]
This is as correct as it gets.

**Pull request merged**
