### PR TITLE
feat: Add Number::pairs

### PR DESCRIPTION
**Pull request by hotmeteor**
The `Number::pairs()` method provides the ability to "split" a number into pairs of min/max values. It's sort of like `sliding`, except the method will determine the values for you.

The method can create pairs of integers or floats.

Examples:

```php
$output = Number::pairs(25, 10);

// [[1, 10], [11, 20], [21, 25]]

$output = Number::pairs(25, 10, 0);

// [[0, 10], [10, 20], [20, 25]]

$output = Number::pairs(10, 2.5, 0)

// [[0, 2.5], [2.5, 5.0], [5.0, 7.5], [7.5, 10.0]]
```

Thanks!

### CODE REVIEW

**Comment by ermesonqueiroz** [comment]
Hi @hotmeteor. Thank you for your pull request. I appreciate the effort. However, I believe it would be more consistent with programming language standards to set the default value of the third parameter to 0. What do you think?

**Comment by hotmeteor** [comment]
Sure, if you think so. I'm not sure what standards to compare it to though? I think from a UX perspective I'd expect it to behave as I have it. But again, if the preference is to start with zero that's fine by me.

**Review by ermesonqueiroz — COMMENTED** [review]
LGTM

**Comment by hotmeteor** [comment]
@ahinkle Generating values for batches, similar to what's in the docs: https://laravel.com/docs/11.x/queues#dispatching-batches

**Comment by christophrumpel** [comment]
Nice one 👍 What is the reason to call the first argument `$to`? @hotmeteor

**Comment by hotmeteor** [comment]
It represents the number you're pairing up to, though I'm sure there's other names it could have been given. 

I guess I thought like:

Pair "by" 5s, up "to" 100, "offset" by 1.

Changes I could see:
- using a zero-based offset as a default (as suggested elsewhere) to match other method behaviors
- using better argument names

**Comment by christophrumpel** [comment]
Thanks, I'm not complaining just wanted to know more about the decision before I make a video about the feature since it wasn't that clear to me. But I get your points 👍

**Comment by hotmeteor** [comment]
🙇 Oh cool! Ya, naming is hard and Laravel naming is always top-notch so I just want to make sure it's up to standards 😅

**Pull request merged**
