### PR TITLE
[5.1] Replaced count() with empty() - in some cases a huge performance benefit

### PR DESCRIPTION
**Pull request by ghost**
There where a lot of cases where count() has been used just to check if a value is given or not.

If count() is being used, all iterations have to complete... this is not necessary if actions need to be performed even if one iteration passes.

In most of the cases the arrays would be small, but in some situations it is a huge performance difference.

count() is not very effective just to check if an array is empty, this pull request replaces this method with empty().

http://stackoverflow.com/questions/2216110/checking-for-empty-arrays-count-vs-empty

### CODE REVIEW

**Comment by DanielStuttgart** [comment]
Two sources for a count() vs. empty() benchmark:

http://webjawns.com/2014/04/php-benchmark-count-vs-empty/

http://maettig.com/code/php/php-performance-benchmarks.php

**Comment by taylorotwell** [comment]
We don't typically except these types of big multi-file PRs to fix something that isn't really broken. That benchmark is calling `count` literally 1 million times. Something we aren't even close to doing.

**Comment by DanielStuttgart** [comment]
Well, very simple changes were made.

This pull request is an improvement not a fix, it does cut off a few ms in some Laravel benchmarks ;-)

**Comment by kfirba** [comment]
Interesting PR tbh.

**Comment by DanielStuttgart** [comment]
The rejection reasion is way more interesting :D

**Comment by kfirba** [comment]
@DanielStuttgart I think that in order to justify this PR we will need to see some real benefits. Make some benchmarks based on Laravel and see what the difference is.

**Comment by DanielStuttgart** [comment]
To setup a benchmark for these timeframes is very hard, the impact of other proccesses on the cpu and ram result in useless results.

Let’s forget the benchmarks, sorry that I mentioned them. It actually takes the spotlight to the wrong place. Benchmarks are absolutely not needed to say that the wrong functions are being used here or that count() is slower.

Let’s take for example the following if-statement from `src/Illuminate/Database/Migrations/Migrator.php` on line 100:

```php
if (count($migrations) == 0) {
```

And now let’s assume 30 migrations are given...

The following will happen: It will iterate through **ALL** the migrations (30 times) and then compare that to the value zero. And now it gets extremely stupid: If counting has finished, then the rest of the code will fire - without the need to know if there are 30, 50 or 100 migrations. **Why did they get counted then?!**

But with the use of empty() here the following will happen: It will check if [0] is set and compare that to null. And then it already fires the rest of the code! Whoa… in an ant world that has to be a huge performance benefit does it? And from a good programmer that has to be the most efficient and correct way to do it?

Just tell me with a basic programming logic mind if the use of empty() is way faster and better here? Keep in mind that this incorrect use of count() is called a lot of times - will they all together affect times in a very small dimension? (Hint: yes, 20-30 times)

While the above example won’t effect the framework at all when finally running, an example for the querybuilder `src/Illuminate/Database/Query/Builder.php` on line 637 would do:

```php
if (count($query->wheres)) {
```

If someone has like 10 where clauses then they all get counted **for no reason at all**.


Ok now that you should be aware of the correct use of functions here let’s get back to the benchmarks:

In a real world example the times we are talking about here are very very low. But within that dimension of times the change from count() to empty() will be huge! It still is far away from the decimal on the right side, but not enough to get usefull benchmarks for these low number of iterations. Fact is it is faster, like the sources above say 20 to 30 times!

Whatever, the main point here is definitely to make use of the correct functions for the the job. Iterating through all these variables for no reason at all is absolutely insane, no matter if it affects real world times (what it does, but like I said in a very small and very hard measurable dimension).

If you wanted to satisfy Steve Jobs then this change would be no discussion at all. Don’t just be passionate about DocBlocks, do it with these things too! ;)

**Comment by DanielStuttgart** [comment]
phanan has the solution: https://github.com/laravel/framework/issues/9738#issuecomment-124970326

**Comment by patrickcarlohickman** [comment]
@DanielStuttgart While I prefer the use of `empty()`, `count()` is a O(1) operation. It does not iterate the array to determine the count. The underlying structure of a PHP array has a property that keeps the count of the array, so the `count()` method just returns the value of this property.

**Comment by DanielStuttgart** [comment]
@patrickcarlohickman Thanks for the information, that is interesting! And actually a valid reason to reject this PR compared to Taylor's anwser.

Good that we're not using PHP 4, these were the O(n) times... they seem to have learned their lessons (or to protect the people's use cases where count() shouldn't be used).

How come that all these count() benchmarks are slower if it's only a function call without iteration? Is it because of the function's overhead?

**Comment by patrickcarlohickman** [comment]
@DanielStuttgart My guess would be that it is because `count()` is a PHP function, whereas `empty()` is actually a language construct.

**Pull request closed without merging**
