### PR TITLE
[9.x] Add `whereBetweenDate()` , `whereNotBetweenDate()` ,`whereTimestampBetweenDate()` and `whereNotTimestampBetweenDate()`

### PR DESCRIPTION
**Pull request by Haythamasalama**
📌 Same PR #42194 but with the usual approach.

PR: Add whereBetweenDate() and whereNotBetweenDate() to filter two dates with a different formats.

The use-case to use the `whereBetweenDate()`  and `whereNotBetweenDate()` : 

- If you have a column type is DateTime or Timestamp `YYYY-MM-DD hh:mm:ss` and the values you searching on it have a different format as date `YYYY-MM-DD`.

Using `whereBetween()` or  `whereNotBetween()` on previous use-case will return not the exact data we searching on it because SQL will match with a different format to solve this we need to **cast** the column to data format using `date` function 

SQL :
```sql 
-- Before
select * from checklists where created_at between '2022-04-17' and '2022-04-18';   
select * from checklists where created_at not between '2022-04-17' and '2022-04-18';   
-- After 
select * from checklists where date(created_at) between '2022-04-17' and '2022-04-18';   
select * from checklists where date(created_at) not between '2022-04-17' and '2022-04-18';   
```

# Example

### Using `whereBetween()` or `whereNotBetween()`
```php
// Query Builder 
 DB::table('checklists')->whereBetween('created_at', ['2022-04-17','2022-04-18'])->get();
 DB::table('checklists')->whereNotBetween('created_at', ['2022-04-17','2022-04-18'])->get();
// Eloquent 
Checklist::whereBetween('created_at', ['2022-04-17','2022-04-18'])->get();
Checklist::whereNotBetween('created_at', ['2022-04-17','2022-04-18'])->get();
```

Output for using `whereBetween()` from '2022-04-17' to '2022-04-18': 

image

### Using `whereBetweenDate()` or `whereNotBetweenDate()`
```php
// Query Builder 
 DB::table('checklists')->whereBetweenDate('created_at', ['2022-04-17','2022-04-18'])->get();
 DB::table('checklists')->whereNotBetweenDate('created_at', ['2022-04-17','2022-04-18'])->get();
// Eloquent 
Checklist::whereBetweenDate('created_at', ['2022-04-17','2022-04-18'])->get();
Checklist::whereNotBetweenDate('created_at', ['2022-04-17','2022-04-18'])->get();
```

Output for using `whereBetweenDate()` from '2022-04-17' to '2022-04-18': 

image

### CODE REVIEW

**Comment by HaythamaSalama** [comment]
Using `whereBetween()` with `DB::raw('DATE(colum_name)')` to get the exact reuslt 
**Before**
```php 

// Query Builder 
 DB::table('checklists')->whereBetween(DB::raw('DATE(created_at)'), ['2022-04-17','2022-04-18'])->get();
 DB::table('checklists')->whereNotBetween(DB::raw('DATE(created_at)'), ['2022-04-17','2022-04-18'])->get();
// Eloquent 
Checklist::whereBetween(DB::raw('DATE(created_at)'), ['2022-04-17','2022-04-18'])->get();
Checklist::whereNotBetween(DB::raw('DATE(created_at)'), ['2022-04-17','2022-04-18'])->get();

```
Using `whereBetweenDate()` 
**After**
```php 

// Query Builder 
 DB::table('checklists')->whereBetweenDate('created_at', ['2022-04-17','2022-04-18'])->get();
 DB::table('checklists')->whereNotBetweenDate('created_at', ['2022-04-17','2022-04-18'])->get();
// Eloquent 
Checklist::whereBetweenDate('created_at', ['2022-04-17','2022-04-18'])->get();
Checklist::whereNotBetweenDate('created_at', ['2022-04-17','2022-04-18'])->get();

```

**Comment by tpetry** [comment]
I am against that change. The generated SQL statement will prevent the usage of an index on the `created_at ` column. Instead of changing the query in this case, you should change the logic adding the condition to include the time part.

The SQL statement is not unindexable, you can always add a [function-based index](https://sqlfordevs.io/function-based-index). But I believe most developers will be puzzled that this query builder function will render their existing indexes useless when just using `2022-04-17 00:00:00`and `2022-04-18 23:59:59` would have worked perfectly with an index.

**Comment by HaythamaSalama** [comment]
> I am against that change. The generated SQL statement will prevent the usage of an index on the `created_at ` column. Instead of changing the query in this case, you should change the logic adding the condition to include the time part.
> 
> The SQL statement is not unindexable, you can always add a [function-based index](https://sqlfordevs.io/function-based-index). But I believe most developers will be puzzled that this query builder function will render their existing indexes useless when just using `2022-04-17 00:00:00`and `2022-04-18 23:59:59` would have worked perfectly with an index.

I am agreed with you 👌, using this way `2022-04-17 00:00:00` and `2022-04-18 23:59:59`  it's efficient than `date` functions because SQL it's not using the index as you mentioned, and _**this will be clear**_  if you have more thousands of Records.
so I **_will update  the PR_** to use way `2022-04-17 00:00:00`and `2022-04-18 23:59:59` 


**Using  `2022-04-17 00:00:00`and `2022-04-18 23:59:59`**  : 

image

 **Using `date()` function sql** : 

 image

**Comment by HaythamaSalama** [comment]
Now I updated the logic using this way `2022-04-17 00:00:00` to `2022-04-18 23:59:59` because it's more efficient than casting using SQL `date()` function.

The use-case if the column is DateTime and values we searching for Date

Before: 

```php

//  it return the exact data  and does not use the index
DB::table('checklists')->whereBetween(DB::raw('DATE(created_at)'), ['2022-04-17','2022-04-18'])->get(); 
DB::table('checklists')->whereBetween(DB::raw('DATE(created_at)'), ['2022-04-17','2022-04-18'])->get(); 
//it returns not the exact data
DB::table('checklists')->whereNotBetween(created_at, ['2022-04-17','2022-04-18'])->get();
DB::table('checklists')->whereNotBetween(created_at, ['2022-04-17','2022-04-18'])->get();

```
After: 

```php
DB::table('checklists')->whereBetweenDate(created_at, ['2022-04-17','2022-04-18'])->get();
DB::table('checklists')->whereNotBetweenDate(created_at, ['2022-04-17','2022-04-18'])->get();
```

**Comment by tpetry** [comment]
I do believe that this idea has fundamental problems and shouldn‘t be included. I don‘t have any time today, will write more tomorrow.

**Comment by HaythamaSalama** [comment]
> I do believe that this idea has fundamental problems and shouldn‘t be included. I don‘t have any time today, will write more tomorrow.

can you mention what is fundamental problems? however, I make different checks and make a test for all cases 

I check if the values are not dateTime and are not Expression which means the string of the accepted value like this '2022-05-5' to format it but anyone who inputs values like number will have an Exception to make its DateTime

**Comment by HaythamaSalama** [comment]
I think using  `date()` function SQL  it's a more general solution it's like `whereDate()` if you have DateTime column and searching date.
and I think if you are worried about performance you can use normal `whereBetween()` and specify your values `2022-04-17 00:00:00` to `2022-04-18 23:59:59`.

**Comment by HaythamaSalama** [comment]
📌 Update the Logic for `whereBetweenDate()` and `whereNotBetweenDate()`  by using `date` function to cast the column dateTime 

Supported : 
- MySQL 
- Postgres
-  SQL Server
- SQLite

```php
DB::table('checklists')->whereBetweenDate(created_at, ['2022-04-17','2022-04-18'])->get();
DB::table('checklists')->whereBetweenDate(created_at, ['2022-04-17',now()])->get();
DB::table('checklists')->whereNotBetweenDate(created_at, ['2022-04-17','2022-04-18'])->get();
```

**Comment by tpetry** [comment]
My intention was that you are misusing the naming. A filter like `whereBetweenDate(created_at, ...)` is, by its naming, filtering on a date column. But you are not doing date operations on the column, your query is using timestamps in a condition for a function which states to use dates, but you are executing on a timestamp column. So basically, you've built `whereTimestampBetweenDate`, not `whereBetweenDate `.

And your PostgreSQL code again will prevent an index being used because you are casing the column to a date column, which means an index on the timestamp column will not be used. I've tested that PostgreSQL is intelligent enough to not need the cast and use the index (https://dbfiddle.uk/?rdbms=postgres_14&fiddle=7ec796f279c8d0dfd51831dbabdeaa40). But I am uncertain if all the other databases will behave the same. 

You are creating a new filter, with (1) uncertain performance implications and (2) ambigous naming indicating a completely different operation to execute on the database. And all this effort just because `whereBetween('2022-04-17 00:00:00', '2022-04-18 23:59:59') is too much effort to type for you. But `whereBetween` is perfectly handling all date and numeric data types with correct indexing support because it doesn't change any of the column's meanings.

**Comment by HaythamaSalama** [comment]
> My intention was that you are misusing the naming. A filter like `whereBetweenDate(created_at, ...)` is, by its naming, filtering on a date column. But you are not doing date operations on the column, your query is using timestamps in a condition for a function which states to use dates, but you are executing on a timestamp column. So basically, you've built `whereTimestampBetweenDate`, not `whereBetweenDate `.
> 
> And your PostgreSQL code again will prevent an index being used because you are casing the column to a date column, which means an index on the timestamp column will not be used. I've tested that PostgreSQL is intelligent enough to not need the cast and use the index (https://dbfiddle.uk/?rdbms=postgres_14&fiddle=21312df697a4e0b79e9f794b06d19857). But I am uncertain if all the other databases will behave the same.
> 
> You are creating a new filter, with (1) uncertain performance implications and (2) ambigous naming indicating a completely different operation to execute on the database. And all this effort just because `whereBetween('2022-04-17 00:00:00', '2022-04-18 23:59:59')` is too much effort to type for you. But `whereBetween` is perfectly handling all date and numeric data types with correct indexing support because it doesn't change any of the column's meanings.

Ok now `whereBettenDate()`  and `whereBettenDate()` it's casting the column to date format to get the result it works on MySQL, Postgres , SQL Server, SQLite it's like `whereDate()` however I will add another function for more performance with name is: `whereTimestampBetweenDate()` and `whereTimestampBetweenDate()`  as you mention because it works only if the column is a timestamp ...etc

**Comment by HaythamaSalama** [comment]
### 📌  `whereBetweenDate()` and `whereNotBetweenDate()`  caste the column to `date`

Supported : 
- MySQL 
- Postgres
-  SQL Server
- SQLite

```php
DB::table('checklists')->whereBetweenDate(created_at, ['2022-04-17','2022-04-18'])->get();
DB::table('checklists')->whereBetweenDate(created_at, ['2022-04-17',now()])->get();
DB::table('checklists')->whereNotBetweenDate(created_at, ['2022-04-17','2022-04-18'])->get();
```
<hr/>

### 📌 Add `whereTimestampBetweenDate()` and `whereNotTimestampBetweenDate()`

- These two functions it's used where between two dates and the column is `Timestamp ` and values is `Date` the function will format the values `Y-m-d 00:00:00` to `Y-m-d 23:59:59` to get the exact result.



```php
DB::table('checklists')->whereBetweenDate(created_at, ['2022-04-17','2022-04-18'])->get();
DB::table('checklists')->whereBetweenDate(created_at, ['2022-04-17',now()])->get();
DB::table('checklists')->whereNotTimestampBetweenDate(created_at, ['2022-04-17','2022-04-18'])->get();
DB::table('checklists')->whereNotTimestampBetweenDate(created_at, ['2022-04-17',now()])->get();
```

**Comment by HaythamaSalama** [comment]
> The cast is again adding the possibility that an index will not be used correctly because the index has been created for a different data type. I'll stop commenting from now on, I've said everything I wanted to add.

I will attach all formats that function `whereBetween()` can handle it and I will answer why really convinced with this function ?

**Comment by HaythamaSalama** [comment]
I choose common formats however we have a lot of formats for DateTime and timestamps. 
We have values dates with this format  `YYYY-MM-DD`  and we are searching on the table with the following formats :  
| Format | Example values |  `whereBetween()` | `whereBetweenDate()` | 
| ----------- | ----------- | ---------- | ----------- | 
| YYYY-MM-DD      | 2022-05-12  | get the exact results | get the exact results **but** `whereBetween()` is fast |
| YYYY-MM-DD hh:mm | 2022-05-12 00:00 to 2022-05-12 23:59 | ! get the results **but** not the exact data | get the exact results
| YYYY-MM-DD hh:mm:ss | 2022-05-12 00:00:00 to 2022-05-12 23:59:59 | ! get the results **but** not the exact data | get the exact results **but** `whereTimestampBetweenDate()` is fast 
| YYYY-MM-DD hh:mm:ss.sss     |   2022-05-12 00:00:00.000000 to 2022-05-12 23:59:59.999999 | ! get the results **but** not the exact data | get the exact results
| YYYY-MM-DDTHH:mm:ss.SSSZ  |  2022-05-12T09:07:21.205-07:00 to ....| ! get the results **but** not the exact data | get the exact results

So if  you have any format DateTime or timestamp and you are searching on date format `YYYY-MM-DD` the casting is a general solution but if you are worried about the performance you can use `whereBetween()` and formating the values with the range DateTime format for the column, for example, you have a column with this format `YYYY-MM-DD hh:mm:ss.sss `  and the values you searching on it like this `2022-05-12` you need to format the values like this `2022-05-12 00:00:00.000000 to 2022-05-12 23:59:59.999999` to get the exact results.

You have a lot of formats it's not easy to make a function that handles a lot of formats without casting to keep the index working! what if the developer did not make index the column? what if you have a complex query and the index is not used with this complex query? in my opinion, you can find functions that can get the same result you want but in a different way but one of them can get the result fast than one so you are decided what you need to use.

Finally 

This PR handles the general solution for any format DateTime or timestamp with  casting column `whereBetweenDate()` `whereNotBetweenDate()`  and the common format `YYYY-MM-DD hh:mm:ss` with keeping index work `whereTimestampBetweenDate()` , `whereNotTimestampBetweenDate()`


[MySql formats](https://dev.mysql.com/doc/refman/8.0/en/datetime.html#:~:text=MySQL%20retrieves%20and%20displays%20DATETIME,both%20date%20and%20time%20parts)
[Sqlite formats](https://www.postgresql.org/docs/current/functions-formatting.html)
[SQL Server formats](https://docs.microsoft.com/en-us/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql?view=sql-server-ver15)
[postgresql formats](https://www.techonthenet.com/sqlite/functions/datetime.php#:~:text=The%20SQLite%20datetime%20function%20is,HH%3AMM%3ASS)

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by HaythamaSalama** [comment]
@taylorotwell Thank you for your response.

If you want to make a query where between two dates and the values you are searching like this format `YYYY-MM-DD`  and the database has any format of DateTime or timestamp. If using `whereBetween()` it does not return the exact data.

So this PR I made 4 functions ` whereBetweenDate()`  , ` whereNotBetweenDate()` that cast the column on database to get the exact data.

```sql
-- before
select * from checklists where created_at between '2022-04-17' and '2022-04-18';   
-- after
select * from checklists where date(created_at) between '2022-04-17' and '2022-04-18';   
```

And  ` whereNotTimestampBetweenDate()`  , ` whereNotTimestampBetweenDate()`  that handel where between without casting the column on datatabes  if the format is `YYYY-MM-DD hh:mm:ss` .

```sql
-- before
select * from checklists where created_at between '2022-04-17' and '2022-04-18';   
-- after
select * from checklists where created_at between '2022-04-17 00:00:00' and '2022-04-18 23:59:59';   
```

**Comment by HaythamaSalama** [comment]
Hi @taylorotwell 
I followed the Laravel approach. and I think it's a good addition.
I used where between two dates a lot of with project's dashboard if any notes or ideas about the codeI will change.

**Comment by HaythamaSalama** [comment]
@taylorotwell 
place take a look at this comment on another [PR ](https://github.com/laravel/framework/pull/42081#issuecomment-1106810335)for one person that suggests about make function whereBetweenDate 

and I think that will be worthwhile with this PR #42081 we will have functions that handle a lot of ideas about where the date

**Pull request closed without merging**
