### PR TITLE
[8.x] Allow adding multiple columns after a column

### PR DESCRIPTION
**Pull request by themsaid**
This PR allows:

```php
Schema::table('users', function (Blueprint $table) {
    $table->after('remember_token', function ($table){
        $table->string('card_brand')->nullable();
        $table->string('card_last_four', 4)->nullable();
    });
});
```

The order of the columns will be:

- remember_token
- card_brand
- card_last_four

### CODE REVIEW

**Comment by taylorotwell** [comment]
Merged.

**Comment by ronssij** [comment]
`Schema::table('users', function (Blueprint $table) {
    $table->nullable(function ($table){
        $table->after('remember_token', function ($table){
            $table->string('card_brand');
            $table->string('card_last_four', 4);
        });
    });
});`


What about this one too ?

**Comment by ronssij** [comment]
Schema::table('users', function (Blueprint $table) {
    $table->after('remember_token', function ($table){
        $table->string('card_brand')->nullable();
        $table->string('card_last_four', 4)->nullable();
    });
});

**Comment by ronssij** [comment]
This is a nice example implementing like this one for assigning multiple nullable columns.

```
Schema::table('users', function (Blueprint $table) {
   $table->nullable(function ($table){
      $table->after('remember_token', function ($table){
          $table->string('card_brand');
          $table->string('card_last_four', 4);
      });
    });
});
```

**Pull request closed without merging**
