### PR TITLE
[5.5] [proposal] Add interactions to the Eloquent models

### PR DESCRIPTION
**Pull request by sileence**
This proposal adds a simple concept of interactions to Eloquent (I took the name from Spark).

The usage is simple. You define method => class pairs in an interactions array in your eloquent models, like this:

```
<?php

class User extend Eloquent {

    protected $interactions = [
        'createPost' => CreatePost::class,
    ];

    //...
}
```

Then you create the classes (in my example: CreatePost) anywhere in the app, for example:

```
<?php

namespace App\Interactions;

use App\{Post, User};

class CreatePost
{
    public function handle(User $user, Post $post)
    {
        $user->posts()->save($post);
    }
}
```

And now you'll be able to call the `createPost` method in any user model, like this:

`$user->createPost($post)`

The classes are simple PHP classes but they will be instantiated through the container (so you can pass any dependencies to the constructor). 

The handle method will receive the model as the first argument and then any other argument after that.

It's possible to have an interaction that support multiple methods:

```
<?php

class User extend Eloquent {

    protected $interactions = [
        'createPost' => CreatePost::class,
        'createFeaturePost' => CreatePost::class,
    ];

    //...
}
```

```
<?php

class CreatePost
{
    public function createPost(User $user, Post $post) { /**/ }

    public function createFeaturePost(User $user, Post $post) { /**/ }
}
```

Of course my example is very simple but the idea is to use this feature when more complex interactions are required, while keeping the same simple call (like `$user->createPost($post)`) in the controller or anywhere in the app.

I think having separate classes can also be useful not only to load dependencies but to potentially implement interfaces like "ProcessUsingTransaction".

If this idea is approved I will add tests etc. later.

### CODE REVIEW

**Review by KKSzymanowski — APPROVED** [review]

**Comment by joshmanders** [comment]
Okay, so I've been thinking about this and I just can't quite figure out what makes this useful outside of your simple examples...

Why have another class that can be achieved by just having a `createPost` method on the model that does that for you? I mean, these don't sound very reusable for other classes and if they are, why not just use a trait?

**Comment by KKSzymanowski** [comment]
@joshmanders I think the most useful thing about this is the dependency injection. I sometimes find myself in need of a transaction in model methods and this way:
1. The code is more compact
2. You wouldn't need to do these silly tricks to get autocompletion
```php
/** @var DatabaseManager $db **/
$db = app(DatabaseManager::class);
```

**Comment by sileence** [comment]
@joshmanders I've actually tried traits and at some point you might end up including 12+ different traits in one model. 

Using traits also do not provide dependency injection (unless you use the `app()` helper or similar).

And also when using traits you need to be careful of not overriding methods in other traits or in the model itself.

I find that having smaller / dedicated classes are a good thing but I want to keep the simplicity of interacting with the model directly (I mean `$user->createPost($post)` looks better than `app(CreatePost::class)->handle($user, $post)`).

**Comment by joshmanders** [comment]
Great explaination @KKSzymanowski and @sileence I just couldn't think of ways that this is beneficial.

**Comment by taylorotwell** [comment]
Honestly I would just suggest defining regular methods on your model that use the container to call some other class as needed. I'm not sure we need some special construct for this.

**Pull request closed without merging**
