### PR TITLE
[5.6] Revert "allow 0 block time"

### PR DESCRIPTION
**Pull request by halaei**
This reverts commit dbad05599b2d2059e45c480fac8817d1135d5da1.

### CODE REVIEW

**Comment by jmarcher** [comment]
Well, you need to explain a bit why...

**Comment by halaei** [comment]
@tillkruss I am resubmitting the exact same PR as the one closed #23105 and tests are now passing. Closing a PR just because a test that randomly fails happen to fail in a totally unrelated PR has no point.

**Comment by halaei** [comment]
@jmarcher exactly. And now I should re-write the exact same comments.

**Comment by halaei** [comment]
This reverts commit dbad055.
Reasons to revert:

    blocking for ever is in contradiction with job timeout and maybe Redis read_write_timeout.
    It causes problems for deployment/updating code. It makes restarting the workers harder for horizon or other control systems.
    In horizon currently the default timeout is set to zero. Which now means forever, but it used to mean no timeout at all. https://github.com/laravel/horizon/blob/1.0/src/Connectors/RedisConnector.php
    Other implementations like SQS does not allow for long-polling/blocking for more than 30 seconds. They might have other good reasons for the restriction.

**Comment by tillkruss** [comment]
@halaei: Please resubmit with test, so we don't run into the same issue in the future.

**Comment by halaei** [comment]
I will not.

**Comment by ryanwinchester** [comment]
Is the profile pic intentionally ironic?

**Comment by halaei** [comment]
@ryanwinchester my pic 😁 is for a couple of years ago. I didn't tested my code, they give me a sign "test first don't let the bugs in"

**Pull request closed without merging**
