### PR TITLE
[7.x] Auth routes

### PR DESCRIPTION
**Pull request by browner12**
the luxury of these causes more issues than it is worth (IMO)

- force specific paths
- force specific route names
- force specific Controller and methods names
- can result in issues like #30382

being explicit allows easier debugging than having implicit routes.

we can easily include these routes in the default `routes/web.php` file, and/or include them in the documentation for easy copy and pasting.

### CODE REVIEW

**Comment by dwightwatson** [comment]
I'm not sure about this - I quite like being able to set/forget the auth routes and it works well for most use-cases. If you do need to customise anything then you've still got the flexibility to do so.

**Comment by crynobone** [comment]
Instead of deleting the helper methods I would probably prefer **opt-in** instead of the current **opt-out** style. So if in future we adding new Controller users need to follow the upgrading guide and **opt-in** to it instead of facing sudden error when Laravel can't find the new Controller.

**Comment by browner12** [comment]
@dwightwatson yah, there's a fine line between a framework solving hard problems and a framework solving easy problems. IMO this is an easy problem that doesn't require a FW solution, but I understand that's subjective. I personally never use them *because* I find them too implicit but that's my preference.

@crynobone to your point we could also begin to separate them out if that makes more sense, which is still essentially **opt-in** as long as each set only references one Controller.

```php
Auth::login();
Auth::register();
Auth::reset();
Auth::confirm();
Auth::verify();
```

**Comment by crynobone** [comment]
@browner12 I like it but something similar with Laravel Passport routes registration could also be useful:

```php
Route::auth()
    ->withLogin()
    ->withResetPassword()
    ->withConfirmation()
    ->withVerify();
```

https://github.com/laravel/passport/blob/7.0/src/RouteRegistrar.php

**Comment by taylorotwell** [comment]
Nobody is forcing you to use them.

**Comment by sumonkhan60** [comment]
Can i see where the default auth routes is defined in laravel latest version?

**Comment by devcircus** [comment]
They're in the [laravel/ui](https://github.com/laravel/ui/blob/2.x/src/AuthRouteMethods.php) package.

**Pull request closed without merging**
