### PR TITLE
[5.3] Fix incorrect Eloquent models serialization

### LINKED ISSUE #14579: [5.3] Incorrect Eloquent serialization when sending emails with queued
Here a code that works normal in laravel 5.2

```
$user = \App\Models\User::find(1);
$data = [
    'previewMessage' => 'Your account have been successfully created',
    'user'           => $user,
];


\Mail::queue('emails.new_employee', $data, function ($message) use ($user) {
    $message
        ->subject('Registration completed')
        ->to($user->email);
});
```

in emails/new_employee.blade.php in 5.2 you will get an Eloquent model, but in 5.3 you will get an array with attributes.

Is it normal behaviour? Or I shouldn't to pass eloquent model to email view?

### PR DESCRIPTION
**Pull request by spyric**
Fixes #14579 

Not sure that I have rewrite tests correctly. If I'm wrong - can you tell me how test should be writen?

### CODE REVIEW

**Comment by taylorotwell** [comment]
So how is the callback serialized going into the queue? I only see you unserializing it?

**Comment by taylorotwell** [comment]
I also don't think this will solve any problem? The SerializesModels isn't going to serialize models that are buried in the `$data` array.

**Comment by spyric** [comment]
Yes. I have tested it. Here is a sample how it store job in database:

```
{"job":"Illuminate\\Queue\\CallQueuedHandler@call","data":{"commandName":"Illuminate\\Mail\\SendQueuedMail@handle","command":"O:30:\"Illuminate\\Mail\\SendQueuedMail\":3:{s:7:\"\u0000*\u0000view\";s:19:\"emails.new_employee\";s:7:\"\u0000*\u0000data\";a:2:{s:14:\"previewMessage\";s:43:\"Your account have been successfully created\";s:4:\"user\";O:19:\"App\\Models\\Employee\":23:{s:8:\"\u0000*\u0000table\";s:5:\"users\";s:11:\"\u0000*\u0000fillable\";a:8:{i:0;s:10:\"first_name\";i:1;s:11:\"middle_name\";i:2;s:9:\"last_name\";i:3;s:8:\"nickname\";i:4;s:5:\"email\";i:5;s:5:\"phone\";i:6;s:4:\"duty\";i:7;s:7:\"role_id\";}s:9:\"\u0000*\u0000hidden\";a:2:{i:0;s:8:\"password\";i:1;s:14:\"remember_token\";}s:13:\"\u0000*\u0000connection\";N;s:13:\"\u0000*\u0000primaryKey\";s:2:\"id\";s:10:\"\u0000*\u0000keyType\";s:3:\"int\";s:10:\"\u0000*\u0000perPage\";i:15;s:12:\"incrementing\";b:1;s:10:\"timestamps\";b:1;s:13:\"\u0000*\u0000attributes\";a:16:{s:2:\"id\";i:1;s:10:\"first_name\";s:7:\"Giovani\";s:9:\"last_name\";s:9:\"VonRueden\";s:11:\"middle_name\";s:1:\"A\";s:5:\"phone\";s:15:\"+1-981-570-8804\";s:5:\"email\";s:27:\"macejkovic.lexi@example.com\";s:8:\"nickname\";s:7:\"commodi\";s:4:\"hash\";N;s:4:\"duty\";N;s:8:\"password\";s:60:\"$2y$10$nCa7DDpvRbFDrpi1DfW8xO\/4uB79MRum.G2v84KzrRfPXktA47j6q\";s:9:\"api_token\";N;s:4:\"type\";s:8:\"employee\";s:14:\"remember_token\";s:10:\"V3xK7MmDSH\";s:10:\"created_at\";s:19:\"2016-08-04 20:08:32\";s:10:\"updated_at\";s:19:\"2016-08-04 20:08:32\";s:7:\"role_id\";N;}s:11:\"\u0000*\u0000original\";a:16:{s:2:\"id\";i:1;s:10:\"first_name\";s:7:\"Giovani\";s:9:\"last_name\";s:9:\"VonRueden\";s:11:\"middle_name\";s:1:\"A\";s:5:\"phone\";s:15:\"+1-981-570-8804\";s:5:\"email\";s:27:\"macejkovic.lexi@example.com\";s:8:\"nickname\";s:7:\"commodi\";s:4:\"hash\";N;s:4:\"duty\";N;s:8:\"password\";s:60:\"$2y$10$nCa7DDpvRbFDrpi1DfW8xO\/4uB79MRum.G2v84KzrRfPXktA47j6q\";s:9:\"api_token\";N;s:4:\"type\";s:8:\"employee\";s:14:\"remember_token\";s:10:\"V3xK7MmDSH\";s:10:\"created_at\";s:19:\"2016-08-04 20:08:32\";s:10:\"updated_at\";s:19:\"2016-08-04 20:08:32\";s:7:\"role_id\";N;}s:12:\"\u0000*\u0000relations\";a:0:{}s:10:\"\u0000*\u0000visible\";a:0:{}s:10:\"\u0000*\u0000appends\";a:0:{}s:10:\"\u0000*\u0000guarded\";a:1:{i:0;s:1:\"*\";}s:8:\"\u0000*\u0000dates\";a:0:{}s:13:\"\u0000*\u0000dateFormat\";N;s:8:\"\u0000*\u0000casts\";a:0:{}s:10:\"\u0000*\u0000touches\";a:0:{}s:14:\"\u0000*\u0000observables\";a:0:{}s:7:\"\u0000*\u0000with\";a:0:{}s:6:\"exists\";b:1;s:18:\"wasRecentlyCreated\";b:0;}}s:11:\"\u0000*\u0000callback\";s:2121:\"C:32:\"SuperClosure\\SerializableClosure\":2074:{a:5:{s:4:\"code\";s:102:\"function ($message) use($user) {\n    $message->subject('Registration completed')->to($user->email);\n};\";s:7:\"context\";a:1:{s:4:\"user\";O:19:\"App\\Models\\Employee\":23:{s:8:\"\u0000*\u0000table\";s:5:\"users\";s:11:\"\u0000*\u0000fillable\";a:8:{i:0;s:10:\"first_name\";i:1;s:11:\"middle_name\";i:2;s:9:\"last_name\";i:3;s:8:\"nickname\";i:4;s:5:\"email\";i:5;s:5:\"phone\";i:6;s:4:\"duty\";i:7;s:7:\"role_id\";}s:9:\"\u0000*\u0000hidden\";a:2:{i:0;s:8:\"password\";i:1;s:14:\"remember_token\";}s:13:\"\u0000*\u0000connection\";N;s:13:\"\u0000*\u0000primaryKey\";s:2:\"id\";s:10:\"\u0000*\u0000keyType\";s:3:\"int\";s:10:\"\u0000*\u0000perPage\";i:15;s:12:\"incrementing\";b:1;s:10:\"timestamps\";b:1;s:13:\"\u0000*\u0000attributes\";a:16:{s:2:\"id\";i:1;s:10:\"first_name\";s:7:\"Giovani\";s:9:\"last_name\";s:9:\"VonRueden\";s:11:\"middle_name\";s:1:\"A\";s:5:\"phone\";s:15:\"+1-981-570-8804\";s:5:\"email\";s:27:\"macejkovic.lexi@example.com\";s:8:\"nickname\";s:7:\"commodi\";s:4:\"hash\";N;s:4:\"duty\";N;s:8:\"password\";s:60:\"$2y$10$nCa7DDpvRbFDrpi1DfW8xO\/4uB79MRum.G2v84KzrRfPXktA47j6q\";s:9:\"api_token\";N;s:4:\"type\";s:8:\"employee\";s:14:\"remember_token\";s:10:\"V3xK7MmDSH\";s:10:\"created_at\";s:19:\"2016-08-04 20:08:32\";s:10:\"updated_at\";s:19:\"2016-08-04 20:08:32\";s:7:\"role_id\";N;}s:11:\"\u0000*\u0000original\";a:16:{s:2:\"id\";i:1;s:10:\"first_name\";s:7:\"Giovani\";s:9:\"last_name\";s:9:\"VonRueden\";s:11:\"middle_name\";s:1:\"A\";s:5:\"phone\";s:15:\"+1-981-570-8804\";s:5:\"email\";s:27:\"macejkovic.lexi@example.com\";s:8:\"nickname\";s:7:\"commodi\";s:4:\"hash\";N;s:4:\"duty\";N;s:8:\"password\";s:60:\"$2y$10$nCa7DDpvRbFDrpi1DfW8xO\/4uB79MRum.G2v84KzrRfPXktA47j6q\";s:9:\"api_token\";N;s:4:\"type\";s:8:\"employee\";s:14:\"remember_token\";s:10:\"V3xK7MmDSH\";s:10:\"created_at\";s:19:\"2016-08-04 20:08:32\";s:10:\"updated_at\";s:19:\"2016-08-04 20:08:32\";s:7:\"role_id\";N;}s:12:\"\u0000*\u0000relations\";a:0:{}s:10:\"\u0000*\u0000visible\";a:0:{}s:10:\"\u0000*\u0000appends\";a:0:{}s:10:\"\u0000*\u0000guarded\";a:1:{i:0;s:1:\"*\";}s:8:\"\u0000*\u0000dates\";a:0:{}s:13:\"\u0000*\u0000dateFormat\";N;s:8:\"\u0000*\u0000casts\";a:0:{}s:10:\"\u0000*\u0000touches\";a:0:{}s:14:\"\u0000*\u0000observables\";a:0:{}s:7:\"\u0000*\u0000with\";a:0:{}s:6:\"exists\";b:1;s:18:\"wasRecentlyCreated\";b:0;}}s:7:\"binding\";N;s:5:\"scope\";s:34:\"App\\Providers\\RouteServiceProvider\";s:8:\"isStatic\";b:0;}}\";}"}}
```

**Comment by taylorotwell** [comment]
But that doesn't seem correct. SerializesModels is having no effect as I said because it doesn't know any models exist in that `$data` array. Your sample you posted just has the models serialized. They weren't converted to ModelIdentifier instances.

**Comment by taylorotwell** [comment]
Fixed.

**Pull request closed without merging**
