### PR TITLE
[8.x] Fix Logger docblocks

### PR DESCRIPTION
**Pull request by iamgergo**
When calling `Log::info()` for example, we can pass an array or a `Jsonable` object as well, not only `string` values. The formatter will take care of them.

### CODE REVIEW

**Comment by driesvints** [comment]
Are those the only other two options? Otherwise we should just document those?

**Comment by iamgergo** [comment]
I handled the `formatMessage` method as a reference, and its docblock was already `mixed` for the `$message`.

But as I see, it can be any scalar, `array`, `Arrayable` and `Jsonable`. So maybe the `mixed` is a good choice here.

**Comment by GrahamCampbell** [comment]
This is wrong, because it violates the PSR log interface.

**Comment by iamgergo** [comment]
Yes, that's true, the PSR log interface marks the $message as `string` in its docs, but we see clearly, in case of Laravel that is not valid. You can pass other values as well, not only a string.

**Pull request merged**
