### PR TITLE
[5.0] Migrate To Stringy

### PR DESCRIPTION
**Pull request by GrahamCampbell**
#### This is #4204 retargeted at Laravel ~~4.3~~ 5.0.

In #3643, you said you wanted to move to a smaller library for generating urls, and there was significant interest in moving to Stringy in #3748. I've written an implementation here.

---

Related to #3748, #3643 and #4204.

### CODE REVIEW

**Comment by barryvdh** [comment]
Would it be interesting to migrate some of our own implementations to Stringy also (slugify, snakecase etc)

**Comment by GrahamCampbell** [comment]
What about even extending the stringy class?

**Comment by barryvdh** [comment]
Would probably be a bit confusing as all the functions are differently named, right? And would make it more difficult to swap to a different library later on, if we might need to.

**Comment by GrahamCampbell** [comment]
Yeh. I think we're probably good as we are. If people want to use stringy functions, then use stringy directly I guess.

**Comment by vlakoff** [comment]
No offense to the Stringy project which looks promising, but is it mature enough to use in Laravel?

Just as quick examples, about `toAscii()`:
* Patchwork UTF-8 replaces non-breaking spaces with regular spaces, whereas Stringy *removes* them.
* I just [added missing characters](https://github.com/danielstjules/Stringy/pull/61) to improve consistency, and there should be more...

In general, Stringy supports a hand-made, not widely reviewed set of characters, and just cut out the rest. Whereas Patchwork may be a bit heavy, but offers so better handling.

**Comment by GrahamCampbell** [comment]
Hmmm. Maybe we should just ditch stringy and patchwork, and just lift the code we need out of patchwork, and provide a link back in the method we take.

**Comment by taylorotwell** [comment]
If Stringy isn't mature then make it mature :)... if the ASCII method has
some problems let's offer some pull requests.

**Comment by ibrasho** [comment]
@taylorotwell :+1:

**Comment by nicolas-grekas** [comment]
By removing patchork/utf8, you also removed the automatic input normalization... (UTF8+NFC)
You also removed the mbstring+iconv+intl fallbacks and replaced it by a require on ext-mbstring, which potentially reduces the possibility to install Laravel everywhere. But you may be fine with this.
I see no mention of this in the discussion, but this these are important aspects of patchwork/utf8 that went away without a word. This goes beyong slugifying.

**Comment by barryvdh** [comment]
I think requiring ext-mbstring in favor of patchwork was a deliberate decision, not just about slugifying.

**Comment by vlakoff** [comment]
A few extra notes:
* Laravel wasn't invoking `initAll()` but only `initMbstring()`.
    * Related: #6891 (cc @nicolas-grekas)
* Stringy doesn't even handle composite characters…

**Comment by GrahamCampbell** [comment]
@vlakoff #6891 has already been fixed.

**Comment by GrahamCampbell** [comment]
> Stringy doesn't even handle composite characters…

We're not using stingy to replace patchwork? We're using the php extension.

**Pull request merged**
