### PR TITLE
[4.2] Log Failed Jobs Exceptions

### PR DESCRIPTION
**Pull request by milesj**
This fixes issue #6203.

Recreated since this pull got foobar-ed. https://github.com/laravel/framework/pull/6466

### CODE REVIEW

**Comment by elijan** [comment]
Sorry commenting this late, but I haven't see this change in neither 5.* branches nor 4.* .

Basically, feature is still missing. Exceptions are not logged in the failed jobs table. I am correct in thsi assumption?? Cheers

**Comment by paulovitorjp** [comment]
Hi, I am not seeing the exceptions being logged either (5.1). I am experiencing an erratic behavior, sometimes a job runs as it is supposed to but after finishing it goes to the failed_jobs database table. Other times a job with the same payload fails before the handle() function.. this is killing me since I can't see what exception is being thrown...

**Comment by milesj** [comment]
Hahahaha, 2 years later and he still hasn't added/fixed this? For shame.

**Comment by xiatian** [comment]
has not fixed yet?

**Pull request closed without merging**
