### PR TITLE
[8.x] Switch to phpdotenv v5

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Does this have any breaking changes for applications?

**Comment by GrahamCampbell** [comment]
No. :)

**Comment by yu-ichiro** [comment]
For anyone stumbling on the same problem and ended up here:
This PR introduced a silent BC where `$_SERVER` supersedes `$_ENV` where before it was the opposite.

This causes breaks on applications where overwriting $_ENV is not working anymore.
One of the instances is where one is using Laravel with PHPUnit and using `<env force="true">` like in this issue (https://github.com/sebastianbergmann/phpunit/issues/4540) 
The breakage is so subtle that it is hard to tell the cause, and there might be other projects having the same issue.

phpdotenv (which is used under the hood) favors $_SERVER than $_ENV in the default setting:
https://github.com/vlucas/phpdotenv/blob/master/src/Repository/RepositoryBuilder.php#L25-L28
but Laravel originally had an explicit definition of order and overrode this in the other way, which was deleted in this commit. 
https://github.com/laravel/framework/pull/33139/files#diff-c12b490b8b24d347e34234aa0d278fc4566fcdbb0772e6b95125517b10b224dfL57-R55

**Comment by GrahamCampbell** [comment]
We're open to PRs to the upgrading docs. `$_SERVER` is the proper place to go read and write environment variables in PHP . `$_ENV` has issues and `getenv` and `putenv` are not thread-safe, causing bugs in the best, and security problems at worst, running on php-fpm, with things leaking between apps on the same server.

**Comment by GrahamCampbell** [comment]
Sorry about this oversight on the order changing.

**Pull request merged**
