### PR TITLE
[5.0] Fix Querying self relationship

### PR DESCRIPTION
**Pull request by codelight89**
Fix issue  #6190

### CODE REVIEW

**Comment by taiyaei** [comment]
> GrahamCampbell changed the title from [5.0[ Fix Querying self relationship - has to [5.0[ Fix Querying self relationship an hour ago

[5.0[ ? :p

**Comment by taylorotwell** [comment]
Needs explanation of what was broken and how this fixes it.

**Comment by codelight89** [comment]
If table refers itself we would use model with the description of these relationships like:

    class Category extends Model
    {
        public function parent()
        {
            return $this->belongsTo('Category', 'par_cat');
        }

        public function children()
        {
            return $this->hasMany('Category', 'par_cat', 'id');
        }
    }

When I use simple eager loading:

$cat = Category::with('children', 'parent')->get();

everything works fine and i get correct collection,

but if we want to use has(),

$cat = Category::has('children')->get();

$cat = Category::has('parent')->get();

application would generate incorrect sql query:

select * from `categories` where (select count(*) from `categories` where `categories`.`par_cat` = `categories`.`id`) >= 1;

and we get an empty collection.

So I added getRelationCountQueryForSelfRelation() function to fix this issue, that is called when table querying self relationship and appends alias to sql query

to get query like below:

select * from `categories` where (select count(*) from `categories` as `some_alias` where `some_alias`.`id` = `categories`.`par_cat`) >= 1

Also i fixed fallen test.

**Comment by RSully** [comment]
Is there any chance this might see a back-port to 4.2?

**Comment by GrahamCampbell** [comment]
No.

**Comment by RSully** [comment]
This applies cleanly to 4.2. I just tested on my app and it works as expected. I'd really love to see it merged so I am not forced to maintain a fork for some legacy websites.

**Comment by RomainLanz** [comment]
4.2 is not supported anymore. So it will not be back-ported.

**Pull request merged**
