### PR TITLE
[5.3] Removed deprecated view expression class

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by rkgrep** [comment]
Need to remove tests.

**Comment by rkgrep** [comment]
Or refactor them to use `HtmlString`

**Comment by GrahamCampbell** [comment]
> Or refactor them to use HtmlString

Yeh, they should have been changed on 5.2.

**Comment by GrahamCampbell** [comment]
Fixed, and rebased.

**Pull request merged**
