### PR TITLE
[5.5] Use Arr::wrap when calling seeders

### PR DESCRIPTION
**Pull request by carusogabriel**

### CODE REVIEW

**Comment by sisve** [comment]
Hey, didn't this change the logic? The previous logic allowed anything to be cast into an array, now that anything will be an element _in_ the array.

**Comment by paulofreitas** [comment]
@sisve The `Arr::wrap()` method has the same logic that was simplified here. 👍

**Comment by sisve** [comment]
@paulofreitas No, it does not. The previous logic casted the value to an array, while Arr::wrap creates an array with the value _in_ it. Here's an example on the difference in a scenario where I load the list of seeders from a json file. https://3v4l.org/rar1K

**Comment by paulofreitas** [comment]
@sisve Indeed, but it should be noted that this behavior was an unexpected side-effect, the method's docstring says it should expect an array or a string. 😃

**Pull request merged**
