### PR TITLE
[5.3] confirm creating file on make:auth

### LINKED ISSUE #15652: Not confirm creating file on make:auth
- Laravel Version: <=5.3

Run the make:auth artisan command and creating "HomeController" and view files. But if already exist the files, not confirm question.

We have another file with the same name is overwrite without confirmation.

### PR DESCRIPTION
**Pull request by om3rcitak**
Run the make:auth artisan command and creating "HomeController" and view files. But if already exist the files, not confirm question.

We have another file with the same name is overwrite without confirmation.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I suggest not running the command twice. I don't like to do all these checks.

**Comment by sdogruyol** [comment]
@taylorotwell lol. I suggest that you should be aware of something called 'Human Mistake'.

**Comment by omeripek** [comment]
@Om3rCitak you have to say to @taylorotwell "you're the best" for merge your commit bro!

**Comment by eserozvataf** [comment]
@Om3rCitak Why are you losing your time someone else's php framework in open source community? Taylor authors and manages everything here. I suggest finding something owned by a community not a single guy.

**Pull request closed without merging**
