### PR TITLE
[8.x] Add `pre()` method

### PR DESCRIPTION
**Pull request by kartiksprajapati**
Added `pre()` method to format the data in the global helpers

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I don't feel this is needed in the core.

**Comment by GrahamCampbell** [comment]
And echoing like that is gonna be a bad idea, usually.

**Comment by kartik3112** [comment]
can you suggest some debug methods...

**Comment by selcukcukur** [comment]
Why do you think this is needed?

**Comment by driesvints** [comment]
Your previous PR was closed. Please stop sending this in.

**Comment by rodrigopedra** [comment]
@kartik3112 , use these:

https://laravel.com/docs/8.x/helpers#method-dump

https://laravel.com/docs/8.x/helpers#method-dd

**Pull request closed without merging**
