### PR TITLE
[8.x] Fix transaction attempts counter for sqlsrv

### PR DESCRIPTION
**Pull request by krasucki**
This brings back transactions attempts for sqlsrv driver

### CODE REVIEW

**Comment by taylorotwell** [comment]
When was it removed and why?

**Comment by krasucki** [comment]
First introduced in #1883 (well not precisely, because at that time there wasn't $attempts implemented yet, but that was the initial version of this sqlsrv condition) , then during some bug fixing in f4588f8851aab1129f77d87b7dc1097c842390db, for some reason the $attempts was omitted. For me it look like mistake, because there is no reason not to re-run transactions for (pdo) sqlsrv driver.

This is interesting because during all that time nobody noticed this (I must admit that driver is not as popular, but still..) 
 
maybe  @GrahamCampbell can help here?

**Comment by GrahamCampbell** [comment]
The commit you reference does not remove the parameter, but it's possible that not adding it at that point was a mistake.

**Comment by GrahamCampbell** [comment]
I think we could go-ahead and merge this, and see if anyone complains.

**Pull request merged**
