### PR TITLE
[5.3] Closure commands initialize logic moved to bootstrap function

### PR DESCRIPTION
**Pull request by dan-har**

### CODE REVIEW

**Comment by taylorotwell** [comment]
Your PR has no description of why this change was made. From what I remember the code used to be like this and it causes problems. /cc @themsaid

**Comment by dan-har** [comment]
The problems you had are probably because the closure commands were not registered to the application so the application failed when you called one of these commands.

The initialize code that register the closures commands is now moved to the "right" place which is the bootstrap function and all other function that rely on the kernel bootstrap function will have the closure commands registered the same as it is with the command classes.

**Comment by themsaid** [comment]
What problems are you facing currently that this change should solve?

**Comment by dan-har** [comment]
I'm not facing any problem. This removes code duplication and places it in the correct place.

**Pull request closed without merging**
