### PR TITLE
[5.5] Collection : add frequency function.

### PR DESCRIPTION
**Pull request by lucasmichot**
Add frequency function.

### CODE REVIEW

**Comment by m1guelpf** [comment]
Test

**Comment by lucasmichot** [comment]
??



On 11 April 2017 at 11:42:21, Miguel Piedrafita (notifications@github.com)
wrote:

Test

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/laravel/framework/pull/18771#issuecomment-293206322>,
or mute the thread

**Comment by taylorotwell** [comment]
I would just suggest: `collection->where()->count()` :smile:

**Comment by morloderex** [comment]
You can always just macro it 👍

**Pull request closed without merging**
