### PR TITLE
Added Pint Command

### PR DESCRIPTION
**Pull request by prof-usman**
I have added `php artisan pint` command to utilize pint feature so that user don't have to memorize `./vendor/bin/pint`

### CODE REVIEW

**Comment by hmingv** [comment]
Does ./vendor/bin/pint always exist in Laravel projects?

**Comment by GrahamCampbell** [comment]
I don't agree that it's a good idea to add this. `./vendor/bin/` is pretty standard, and you'll get used to it - every tool in PHP goes there.

**Comment by devajmeireles** [comment]
This doesn't make any sense.

**Comment by davidbirkin** [comment]
Small things like this belong in your project and not the framework. Not everyone will use Pint. You could easily make an npm command 

`npm pint`: ./vendor/bin/pint 

Then you solve your issue.

**Pull request closed without merging**
