### PR TITLE
[5.0] Create view composer contract

### PR DESCRIPTION
**Pull request by martinbean**
Created an interface to be applied to view composer classes to enforce the required method name and signature.

### CODE REVIEW

**Comment by JosephSilber** [comment]
That's not right. It defaults to `handle` but [you can use whatever you want](https://github.com/laravel/framework/blob/5.0/src/Illuminate/View/Factory.php#L497).

**Comment by martinbean** [comment]
@JosephSilber Not according to the documentation: http://laravel.com/docs/5.0/views#view-composers

> Now that we have registered the composer, the ProfileComposer@compose method will be executed each time the profile view is being rendered.

And…

> Just before the view is rendered, the composer's compose method is called with the Illuminate\Contracts\View\View instance. You may use the with method to bind data to the view.

**Comment by JosephSilber** [comment]
Again, that's the default. You can still specify which ever method you want.

See here: https://github.com/laravel/framework/blob/5.0/src/Illuminate/View/Factory.php#L497

**Comment by martinbean** [comment]
@JosephSilber The interface is opt-in for users’ view composer classes.

**Comment by GrahamCampbell** [comment]
This sort of thing has been rejected in the past.

**Comment by martinbean** [comment]
@GrahamCampbell Apologies.

**Pull request closed without merging**
