### PR TITLE
[5.5] Use array short syntax while compiling Blade

### PR DESCRIPTION
**Pull request by carusogabriel**

### CODE REVIEW

**Comment by sisve** [comment]
Are there any secret coding guidelines you are following or why are you just going through the code and change things that aren't broken?

**Comment by carusogabriel** [comment]
@sisve I searched in the code if there was any occurrence of `array()` syntax, and there were the last one. But I can close it if is going to trigger a discussion again :disappointed:

**Comment by lagbox** [comment]
I will close if it is going to trigger a discussion again ... so you want to make PRs and have no one comment on them and just have them merged right?

**Comment by ryanwinchester** [comment]
search for `else` too, just in case

**Comment by sisve** [comment]
@carusogabriel Why were you searching the code for array() to begin with? They aren't evil. There are no coding guidelines (at all...) that forbids their use. They were accepted at the time of merging. Why should they be removed now?

There's always open issues and people asking for help in support channels if you have some free time and nothing to do...

**Comment by browner12** [comment]
he's referencing the discussion about making code changes that are only semantic changes rather that functional.

I'm all for coding consistency, and honestly don't care one way or the other. It seems like the short array syntax is much more prevalent.  But we just need a top down decision and go with that.

**Comment by Dylan-DPC** [comment]
I can't find the link but I remember `[]` being marginally faster than `array()`. Also `[]` is being used almost everywhere so I don't see a reason to use the old method.

**Comment by sisve** [comment]
So, how about we add some coding guidelines that points out that short array syntax should be used? Something like styleci or phpcbf could do the conversion automatically without manual pull requests.

**Comment by GrahamCampbell** [comment]
> I can't find the link but I remember [] being marginally faster than array().

I doubt it. Ignoring the speed of the parser, I can 100% guarantee you that it makes zero difference to execution speed. The AST nodes are identical.

> So, how about we add some coding guidelines that points out that short array syntax should be used? 

It doesn't matter what compiled output looks like.

**Pull request closed without merging**
