### PR TITLE
[5.2] Update vlucas/phpdotenv to ~2.0

### PR DESCRIPTION
**Pull request by lucasmichot**
Update `vlucas/phpdotenv` to `~2.0`

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I tried this before. Taylor said no, lol.

**Comment by lucasmichot** [comment]
Why?

**Comment by GrahamCampbell** [comment]
He said there was no point.

**Comment by GrahamCampbell** [comment]
Which is fair play tbh. 1.x works just fine.

**Comment by taylorotwell** [comment]
What are the new features in 2.0?

**Comment by vinkla** [comment]
This is what is new in version 2.0 https://github.com/vlucas/phpdotenv/pull/87

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
