### PR TITLE
Fixed unsafe groupKey parameter

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by sisve** [comment]
What does this fix? Can you add some tests?

**Comment by Piterden** [comment]
Sorry I was hurrying
This is where error had been caught https://github.com/pyrocms/pyrocms/issues/4625

**Comment by Piterden** [comment]
There is also, one idea:
```php
$groupKey = is_string($groupKey)
    ? $groupKey
    : is_object($groupKey)
        ? (int) boolval($groupKey) // or even `count(get_class_methods($groupKey))`
        : (int) $groupKey;
```

**Comment by taylorotwell** [comment]
Would need tests and description.

**Pull request closed without merging**
