### PR TITLE
[5.5] Resolved php artisan down error message

### PR DESCRIPTION
**Pull request by rakshitbharat**
Please at least accept this change and pull to master because your below link this not working:
https://laravel.com/docs/5.5/configuration#maintenance-mode
php artisan down --message="Upgrading Database" --retry=60

Note:
if you don't want my changes then please fix it by your own because your team do not accept changes from poor people like me.

### CODE REVIEW

**Comment by devcircus** [comment]
Can't you just publish the error views and then customize 503 however you wish?

**Comment by rakshitbharat** [comment]
so this should not be fixed ?

btw currently i have made 503 file because this is even not gets published from core to main resources folder.

however problem is solved for me but when documentation says following:
php artisan down --message="Upgrading Database" --retry=60
then it should be fixed in main 5.5 branch because person like me who thinks he is new in PHP after 7yrs will be taught for them.

**Comment by driesvints** [comment]
You can publish this view and adjust it as you see fit: https://laravel.com/docs/5.5/errors#custom-http-error-pages

**Comment by rakshitbharat** [comment]
no problem i will do it my own but also update the documentation which says that you can write messages with following command because this will never run if they don't publish and write code like me or customise it :
php artisan down --message="Upgrading Database" --retry=60 will never work without publishing and customising own.

note:
for me issue is not fixed permanently in LTS branch.

don't worry i will not recreat this issue again.

**Comment by rakshitbharat** [comment]
really don't know why my changes just came from latest 5.8 branch are not getting accepted in 5.4 LTS branch.

note for open source community:
this issue is fixed in 5.8latest branch but in 5.5 branch not fixed which is still under support.

**Comment by driesvints** [comment]
@rakshitbharat we only accept bug fixes for 5.5 and this isn't a bug fix. It's a cosmetic change.

**Comment by rakshitbharat** [comment]
please add this note to documentation that says that console command will not change text in view 503 file please modify on your needs.

In my opinion this is bug and will be bug because sometimes maintanence messages are really important for clients which are using our web app so that they get a proper idea of what happening for when will be fixed, for example I want to place a message that says "please come after 20m we are upgrading database" from this message user will get an idea.

at last I hope above reason was the reason which fixed this cosmetic looking change in 5.8 branch.

**Comment by driesvints** [comment]
@rakshitbharat you are absolutely right and I completely mis-read this. This indeed need is a bug which needs to be fixed. Sorry for mis-interpreting.

**Comment by devcircus** [comment]
Seems like a documentation update would suffice here. Stubs are just to get you started in a very generic way. It is documented that you [can access the exception message in your error views](https://laravel.com/docs/5.8/errors#custom-http-error-pages) already. Maybe just a reminder note here that says if you want to pass a custom message, you'll need to update your view.

**Comment by driesvints** [comment]
@devcircus this is an actual bug right now. You should be able to pass a custom message with the maintenance mode : https://laravel.com/docs/5.5/configuration#maintenance-mode

**Comment by taylorotwell** [comment]
Why did you change the default message?

**Comment by devcircus** [comment]
Yeah I get what's going on. 🤷🏻‍♂️

**Comment by ankurk91** [comment]
OP is just following this PR
https://github.com/laravel/framework/pull/27893

It has the message -
`Service Unavailable`

**Comment by rakshitbharat** [comment]
superb , finally fixed.
thanks community

**Pull request merged**
