### PR TITLE
[10.x] Add tests for nested error messages

### PR DESCRIPTION
**Pull request by samuelwei**
Refering to #47030

This PR adds tests to ensure the localisation of nested error messages is working properly.
It reveals the following bugs:
- Placing the localisation string is a different order result in a different output

Currently this PR is WIP and does not fix the issue

### CODE REVIEW

**Comment by SamuelWei** [comment]
@nunomaduro Are these tests showing a real bug in the current implementation (ignoring the bug I reported in #https://github.com/laravel/framework/issues/47030) or am I missing something in the docs ?
If so, could you fix this first, before I try to come up with a solution for https://github.com/laravel/framework/issues/47030 !?

**Comment by nunomaduro** [comment]
@SamuelWei Is it possible to adjust your tests so it focuses only on the bug you are trying to address? Thanks!

**Comment by nunomaduro** [comment]
To enhance the likelihood of this pull request being merged, it is recommended to concentrate solely on addressing the bug described in https://github.com/laravel/framework/issues/47030. This will enable Taylor to evaluate the issue more effectively. While there is no guarantee that the pull request will be merged, if you can provide a straightforward fix that solely targets the aforementioned issue, it will increase our confidence in merging it.

**Comment by SamuelWei** [comment]
@nunomaduro  To consider both problems separately I have opened a new PR (#47051), this one can then be closed.

**Pull request closed without merging**
