### PR TITLE
[5.2] Intersect Method for Illuminate Request

### PR DESCRIPTION
**Pull request by AdenFraser**

### CODE REVIEW

**Comment by JosephSilber** [comment]
Given that `array_only` works this way, wouldn't it make more sense to simply change the way `$request->only()` works in 5.3?

**Comment by GrahamCampbell** [comment]
@JosephSilber #13162 exists too. ;)

**Comment by JosephSilber** [comment]
I don't get what you are saying.

That PR adds an intersect method, just like this one. Only the implementation is different.

What I am talking about is changing what the only method does.

**Comment by AdenFraser** [comment]
@JosephSilber I agree, the `Arr::only()` / `array_only` method is the same as my proposed `::intersect`, so really the `Request::only()` would make more sense to match as you say.

**Pull request merged**
