### PR TITLE
[5.8] Casting of null values

### PR DESCRIPTION
**Pull request by browner12**
### Problem

Currently if I cast a Model attribute as a 'collection' it is possible to get back either a `Collection` object or `null`. This makes it a little more difficult to work with because now you need to constantly check if you have an object before you can call methods on it.

```php
class Show extends Model
{
    protected $casts = [
        'tags' => 'collection',
    ];
}
```

| id | name | tags |
|---|---|---|
| 1 | Donnie Darko | ['suspense', 'thriller', 'teen'] |
| 2 | The Fifth Element | null |
| 3 | Avatar the Last Airbender | ['animation', 'fantasy'] |

If the database contains a valid JSON object, I will get back a `Collection`.  If the database contains `null`, I will get back `null`.

```php
$show1 = (Show::find(1))->tags;
$show2 = (Show::find(2))->tags;
```

`$show1` will return a `Collection` to me with the elements 'suspense', 'thriller', and 'teen'.

`$show2` will return null to me.

Because of this different return type I can't go straight to a `Collection` method without possibly getting an error.

```php
$show2 = (Show::find(2))->tags->contains('suspense');  //results in error
```

This happens because of the greediness of this line:

https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L472

### Solution

I am proposing an argument that can be passed to our castings, similar to how an argument is passed to the 'decimal' cast.

```php
class Show extends Model
{
    protected $casts = [
        'tags' => 'collection:always',
    ];
}
```

By using `collection:always` instead of `collection`, we will **always** receive a `Collection` object from the casting.  If the field is null, we will get an empty `Collection`.

### CODE REVIEW

**Comment by staudenmeir** [comment]
Replacing `$this->getCastType($key)` with `$this->getCasts()[$key]` breaks casts with uppercase characters or untrimmed spaces:

```php
protected $casts = ['foo' => 'Collection '];
```

**Comment by taylorotwell** [comment]
Hmm, not sure how I feel about introducing an argument to do this. Whenever I've had collection casts I just always make sure the database columns contain an actually valid empty JSON array when they are empty, and never contain null. Can you just take that approach?

**Comment by browner12** [comment]
The difficulty with that is you are not allowed to have default values for fields of type `json`.  For those only using the `text` or `longtext` type, this would probably work.

We could allow certain casts to skip over the null check, but I think this would need to go to 5.9 since we're changing behavior.

```php
if (is_null($value) && !in_array($type, ['collection', 'object', '...'])) {
    return $value;
}
```

**Comment by ludo237** [comment]
You could use a Model observer to automatically fill the JSON column if empty

**Comment by browner12** [comment]
that would work, but it feels like overkill.

It would be great to get consistent return types, and maybe that would be an improvement for 5.9.

I just came across the `$attributes` property on a model, which can be used to set default values.

```php
protected $attributes = [
    'tags' => [],
];
```

originally I thought I could do this, and assign it to an empty array.  However, these values are not mutated, so it actually needs to be set to a string.

```php
protected $attributes = [
    'tags' => '[]',
];
```

**Comment by derekmd** [comment]
> You could use a Model observer to automatically fill the JSON column if empty

An attribute get mutator can also guarantee a `Collection` object when a JSON value isn't present.

```php
class Show extends Model
{
    // ...

    public function getTagsAttribute($tags)
    {
        return collect()->wrap($tags);
    }
```

Or handle missing JSON values with `optional()`:

```php
optional(Show::find(2)->tags)->contains('suspense')
```

**Comment by browner12** [comment]
Casts are essentially just commonly used built in Accessors, so I would prefer to improve the cast rather than writing a custom accessor.

I agree with you guys, there are ways to work around this, but we still need to solve the root issue.

I can also use the null coalesce or ternary operator everywhere to get around this.

```php
$show = Show::find(1);

echo $show->tags ? $show->tags->contains('suspense') : null;
echo $show->tags ?? 'No Shows'

foreach($show->tags ?? [] as $tag) {
    echo $tag;
}
```

But I think having a consistent return type, especially when getting back objects or array is an improvement.

**Comment by taylorotwell** [comment]
I'm still pretty torn on this. We certainly don't want that explode and array_pad at the top of castAttribute so that it runs for every attribute accessor no matter the type I don't think. For now I think I'm going to leave the behavior as is. The mutator solution presented by @derekmd isn't too bad really.

**Comment by browner12** [comment]
FYI, MySQL 8.0.13 now allows JSON fields to have default values.

https://dev.mysql.com/doc/refman/8.0/en/json.html

**Pull request closed without merging**
