### PR TITLE
[5.5] Remove un-used parameter

### PR DESCRIPTION
**Pull request by ahmedash95**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Is this safe to remove?

**Comment by GrahamCampbell** [comment]
Surely this was there on purpose, because this class is abstract, and is extended and overwritten.

**Comment by GrahamCampbell** [comment]
Even if it is safe to remove, 👎 to remove, because of the lack of clarity. The API should remain consistent.

**Comment by ahmedash95** [comment]
@GrahamCampbell you are right man! .. I didn't notice this
Thanks a lot for your clarification

**Pull request closed without merging**
