### PR TITLE
[5.8] Add whereHasMorph()

### PR DESCRIPTION
**Pull request by staudenmeir**
Due to the nature of polymorphism, `whereHas()` doesn't work with `MorphTo` relationships (#5429, #18523).

As a solution, @timacdonald and I are proposing `whereHasMorph()` and the corresponding methods:

```php
Comment::whereHasMorph('commentable', [Post::class, Video::class], function ($query) {
    $query->where('title', 'foo');
})->get();
```
```sql
select * from "comments"
where (
  (
    "commentable_type" = 'App\Post' and exists (
      select * from "posts" where "comments"."commentable_id" = "posts"."id" and "title" = 'foo'
    )
  ) or (
    "commentable_type" = 'App\Video' and exists (
      select * from "videos" where "comments"."commentable_id" = "videos"."id" and "title" = 'foo'
    )
  )
)
```

By creating a temporary `BelongsTo` relationship for each type and allowing relationship instances as the first argument of `has()`, we can reuse most of the existing code.

~~If the user has registered custom aliases in the `morphMap`, they need to provide them instead of class names:~~

To simplify queries with different constraints, we pass the type as the second parameter:

```php
Comment::whereHasMorph('commentable', [Post::class, Video::class], function ($query, $type) {
    if ($type === Post::class) {
        // $query->
    }

    if ($type === Video::class) {
        // $query->
    }
});
```

You can also provide a wildcard and let Laravel get the possible types from the database:

```php
Comment::whereHasMorph('commentable', '*', function ($query) {
    $query->where('title', 'foo');
})->get();
```

The downside here is the additional query that should be mentioned in the docs.

Theoretically, you could use `*` as an alias, but we think it's a better choice than something like `null `.

### CODE REVIEW

**Comment by phroggyy** [comment]
Is there a reason we can't do a morphMap lookup to allow always passing classes? Seems a bit flawed to have to change things in multiple places, unless I'm missing something.

**Comment by timacdonald** [comment]
I might be miss understanding what you mean, but as it stands you can pass:

- Only class types i.e. fqcn
- Only morph map values
- A mixture of morph and class types

i.e. all of the following work...

```php
Relation::morphMap(['posts' => Post::class, 'videos' => Video::class]);

// only classes
Comment::whereHasMorph('commentable', [Post::class, Video::class], function ($query) {
    //
})->etc(...);

// only morph values
Comment::whereHasMorph('commentable', ['posts', 'videos'], function ($query) {
    //
})->etc(...);

// a mixture of both
Comment::whereHasMorph('commentable', ['posts', Video::class], function ($query) {
    //
})->etc(...);
```

We have to create an on-the-fly relationship - hence passing the `$belongsTo` relation instance to the `has` method.

Here is where the morph map lookup is happening: 

https://github.com/laravel/framework/blob/8fe3f1fa25a8b8e4177f8021b1103723569a7d77/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php#L233-L246

@phroggyy let us know if that addresses your concern or if I'm way off base with what you mean 🙂
---

Another nice thing about this is that you have access to the scopes on the models as well. So if `Video` and `Post` all share a `wherePublished()` scope you can access it...

```php
Comment::whereHasMorph('commentable', [Post::class, Video::class], function ($query) {
    $query->wherePublished();
})->etc(...);
```

**Comment by phroggyy** [comment]
Ah, gotcha. In that case, the phrasing of the PR is wrong:

>If the user has registered custom aliases in the `morphMap`, they need to provide them instead of class names:

As per your explanation, this is not true. The user may pass a class name or morph value, but whether the morph map is used doesn't matter.

**Comment by timacdonald** [comment]
Sorry, I actually misspoke. What @staudenmeir said how this implementation works. I've edited my comment just so no one reads it and thinks that is how it currently works.

**Comment by timacdonald** [comment]
I've just [created a PR](https://github.com/staudenmeir/framework/pull/4) to @staudenmeir branch that does the reverse lookup and allows classes even when a morph value has been specified - which matches what I said in my earlier comment.

We might just need to consider if there are any implications to this. Thoughts?

**Comment by staudenmeir** [comment]
I don't think it's a good idea to allow both class names and aliases.

What if we only work with class names? This way, users wouldn't have to adjust the queries when they add a `morphMap`.

**Comment by timacdonald** [comment]
I don't personally use a morph map, so not sure how valuable my opinion on this specific part is, but that sounds like a good way to go about it. 

Either way, I've just [created a PR](https://github.com/staudenmeir/framework/pull/5) for this behaviour as well.

**Comment by staudenmeir** [comment]
`whereHasMorph()` now only allows class names and handles aliases itself:

```php
Relation::morphMap(['posts' => Post::class]);

Comment::whereHasMorph('commentable', [Post::class, Video::class], function ($query) {
    $query->where('title', 'foo');
})->get();
```

**Comment by taylorotwell** [comment]
Nice one!

**Comment by denitsa-cm** [comment]
I just opened this issue related to this PR. Not sure if I'm doing something wrong but can't seem to get the `doesntHaveMorph` to work :) 

https://github.com/laravel/framework/issues/29138

**Comment by mikkopursuittechnology** [comment]
With this improvement can you do nested relationship on morphed classes?

`Comment::whereHasMorph('commentable', [Post::class, Video::class], function ($query) {
    $query->has('author');
})->get();`

In the example above. I'm trying to look for Comments from Posts and Videos that has an author.

**Comment by denitsa-cm** [comment]
@mikkopursuittechnology Have you tried doing that and it didn't work?

**Comment by pelmered** [comment]
This is a great addition, but I can't get it to work with a `morphToMany`-relation. It does not query `*_id` and `*_type` in the intermediate table. 
I guess we need a `whereHasMorphMany` as well?

**Comment by staudenmeir** [comment]
@mikkopursuittechnology Yes, you can.

@pelmered `whereHasMorph()` is only for `MorphTo` relationships. Use `whereHas()` for all other relationships.

**Comment by pelmered** [comment]
@staudenmeir Ok, but `whereHas()` doesn't work with `MorphToMany()`. When I use `whereHas()` I get a RuntimeException with message: `Please use whereHasMorph() for MorphTo relationships.`

And with `whereHasMorph()` it queries the wrong table. 

Conclusion: we need a `whereHasMorphMany()` as well for morphToMany-relations.

**Comment by staudenmeir** [comment]
@pelmered How is your relationship defined? This exception is only thrown for `MorphTo` relationships.

**Comment by pelmered** [comment]
@staudenmeir Yes, you where right. Where was an error in the inverse of the relationship. Sorry about that. `whereHas()` works fine.

**Comment by usamamuneerchaudhary** [comment]
and how to implement the inverse of the relationship?

**Comment by hazemwehbi** [comment]
Hello all,
Can I find in anyone of you any piece of code which apply or use whereHasMorph() ?
Thx in advance

**Comment by staudenmeir** [comment]
@hazemwehbi https://laravel.com/docs/eloquent-relationships#querying-polymorphic-relationships

**Comment by hazemwehbi** [comment]
Thx a lot, I already saw the laravel documentation and followed it but I don't know why it's not working to me.
It show me this error.
"Maximum function nesting level of '250' reached, aborting!"

**Comment by Atiladanvi** [comment]
That would be a dream
```php
$this->query->whereHasMorph('pessoa.pessoavel', '*' , function($s) use ($filterText){
    $s->where('name', 'like', $filterText);
})->get();
```
There's a way to do this ?
```php
$this->query->whereHas('pessoa' , function($q) use ($filterText){
    $q->whereHasMorph('pessoavel', [PessoaFisica::class] , function($s) use ($filterText){
        $s->where('cpf', 'like', $filterText);
    });
})->get();
```
```
SQLSTATE[42P01]: Undefined table: 7 ERROR: missing FROM-clause entry for table "pessoas" LINE 1: select "pessoas"."nome" from "contribuintes" where exists (s... ^ (SQL: select "pessoas"."nome" from "contribuintes" where exists (select * from "pessoas" where "contribuintes"."pessoa_id" = "pessoas"."id" and (("pessoas"."model_type" = Modules\Pessoa\Entities\PessoaFisica and exists (select * from "pessoas_fisicas" where "pessoas"."model_id" = "pessoas_fisicas"."id" and "cpf"::text like %014834587%)))))
```

**Pull request merged**
