### PR TITLE
[8.x] Added ignorable functionality to migration files

### PR DESCRIPTION
**Pull request by binarygeotech**
### Description
This PR adds the ability to ignore migration files either by setting the `ignore` property to true or returning a truthy evaluation in the `ignore()` method of the migration file.

### Purpose
This will enable developers to ignore migration files that are not ready/needed to be migrated yet at the time of running the migrate command. There are some occasions that we needed to ignore some files from been migrated but had to move the files out of the migrations directory.

### CODE REVIEW

**Comment by emmanuelizzy** [comment]
+1

**Comment by LastDragon-ru** [comment]
> There are some occasions that we needed to ignore some files from been migrated but had to move the files out of the migrations directory.

You can redefine Migrator in service provider and implement any logic to skip migrations, please see as example https://github.com/LastDragon-ru/lara-asp/blob/febb6bb3f5cc524b0bec4694349553a1c33fc961/packages/migrator/src/Extenders/SmartMigrator.php#L29

**Comment by binarygeotech** [comment]
@LastDragon-ru, I think it's best for non-advanced users to be able to ignore some migrations files without going the advanced way of extending the `Migrator` class. Moreover, ignoring migration files might be on temporary basis, providing an out-of-the-box simpler method is good approach.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by LastDragon-ru** [comment]
@binarygeotech from my point of view non-advanced users should not ignore migrations because it makes app code more complicated eg you never know exists a table or not, etc.

Another possible solution - move migrations into a separate package. After that, they can be ignored in the provider based on the conditions. Probably you can check how Telescope does it.

**Pull request closed without merging**
