### PR TITLE
[7.x] Allow URL-encoded special characters in basic auth part of URLs

### PR DESCRIPTION
**Pull request by cweiske**
Special characters in HTTP Basic Auth passwords in an URL need to be url-encoded.
Example: foo@bar becomes foo%40bar, in an URL: http://user:foo%40bar@example.org

The UrlValidator did not allow percent signs in username and password, and this is changed now.

Related bugreport and fix for symfony:
- https://github.com/symfony/symfony/issues/36285
- https://github.com/symfony/symfony/pull/36286

### CODE REVIEW

**Comment by taylorotwell** [comment]
We will wait to see what Symfony does. For now you could `urldecode` the value being sending it to the validator.

**Comment by cweiske** [comment]
urldecoding does not help, because that decodes the special characters in the password, which could be an `@`, which breaks validation because `http://user:foo@bar@example.org` is invalid.

**Comment by cweiske** [comment]
Symfony merged the patch and today released 3 versions that contain the patch:
- 3.3.40 (https://github.com/symfony/symfony/pull/36612)
- 4.4.8 (https://github.com/symfony/symfony/pull/36614)
- 5.0.8 (https://github.com/symfony/symfony/pull/36615)

**Comment by driesvints** [comment]
I'll re-open this so Taylor can have another look.

**Comment by driesvints** [comment]
Loosk like there are some merge conflicts by now. @cweiske can you send in a new pr?

**Comment by driesvints** [comment]
Best that you send this to 6.x

**Pull request closed without merging**
