### PR TITLE
Allow manual salt of hash

### PR DESCRIPTION
**Pull request by rtconner**
Allow developer to specify the salt if they wish to.

### CODE REVIEW

**Comment by taylorotwell** [comment]
What would be the use case of wanting to specify your own salt?

**Comment by rtconner** [comment]
Databases don't have hash_equals method, so you can't query on a hash. You need a predictable hash if you ever want to query a database on a hashed string. Obviously it's a horrible idea to salt your own hashes if security is a concern.

I'll get this fixed for php 5.4.

**Comment by taylorotwell** [comment]
I don't think we even want to make this an option.

**Comment by rtconner** [comment]
Allowing developers flexibility?

**Comment by taylorotwell** [comment]
You would have to be doing something pretty bad to even *want* to query a
bcrypt hash. Wouldn't make sense.

**Comment by richwalkup** [comment]
In the scenario where you might need to uniquely identify an individual by a field which you do not want to store because of security purposes (i.e. an SSN) but you want to have the ability to identify a duplicate entry prior to storing the data, this has significant merit. By allowing a static salt option for hashing an item, you can check the hash against existing data and never have to store potentially sensitive data in the database for the unique constraint. Since the hash can't be "decrypted" it's secure even if it's predictable. In some scenarios, security does not necessarily mean unpredictable. 

@rtconner you should more clearly define your use case when suggesting the changes to fully support your argument. @taylorotwell might want to consider being less closed minded about said implementations, especially when the default implementation still maintains strict security. I vote for this implementation because I literally had to do the same type of code change by overriding the BcryptHasher for my use case described above.

**Comment by taylorotwell** [comment]
There are other hash algorithms available. Use one of those if you need to.

**Pull request closed without merging**
