### PR TITLE
Updated for compatibility with MongoDB id

### PR DESCRIPTION
**Pull request by arogozin**
Fixes the following problem when using MongoDB:

ErrorException in Model.php line 2877: Object of class MongoId could not be converted to int

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Don't cast it to an integer then?

**Comment by arogozin** [comment]
No, it actually fails right away. This will give it a chance to cast it as a string, just in case.

**Comment by GrahamCampbell** [comment]
That's because we autocast in 5.2. You need to manually override this if you more custom setups.

**Comment by arogozin** [comment]
I am using 5.2 with jenssegers/mongodb 2.2.4. After creating a user, I kept receiving the error above.

**Comment by GrahamCampbell** [comment]
That's an issue with that package.

**Comment by arogozin** [comment]
Yeah, I reviewed that.. Makes sense! I'll submit fix to the package.

**Pull request closed without merging**
