### PR TITLE
[5.3] Factory registration in service provider.

### PR DESCRIPTION
**Pull request by ghost**
Proposal: https://github.com/laravel/internals/issues/311

### CODE REVIEW

**Comment by JosephSilber** [comment]
Why can't you stick this directly in your service provider:

```php
$this->app->make(EloquentFactory::class)->load(__DIR__.'/../factories');
```

Why does it have to be in the base class?

**Comment by timacdonald** [comment]
Doesnt need to be anywhere, just a suggestion to help make things easier for new devs to get going. :)

**Comment by crynobone** [comment]
> Doesnt need to be anywhere, just a suggestion to help make things easier for new devs to get going. :)

But it's also shouldn't be loaded everywhere, when you can simply load it just for running phpunit, by adding it to `Illuminate\Foundation\Testing\TestCase` or if they're using `orchestra/testbench`, they can use the `TestCase::withFactories()` helpers.

**Comment by timacdonald** [comment]
To easy, perhaps my purpose for it is unique to my project. I'll close this bad boi down, thanks for the feedback!

**Pull request closed without merging**
