### PR TITLE
[6.x] Make a function call instead of nested if statement use it in inherited controllers

### PR DESCRIPTION
**Pull request by ahmedofali**
Make a function call instead of nested if statement use it in inherited controllers

### CODE REVIEW

**Comment by browner12** [comment]
What is the benefit of this?

The `if` statement is not nested? It's only 1 level deep.

**Comment by ahmedofali** [comment]
The if statement contains two conditions I moved them to a function to use it any where when I try to use this trait it's simple and handy to use a function rather than duplication code.

**Comment by GrahamCampbell** [comment]
Under what conditions is it needed to overwrite that method?

**Comment by ahmedofali** [comment]
What the pull request is doing is moving the if condition to a function and call it.

**Comment by browner12** [comment]
We understand **what** you did, we're trying to understand **why** it helps.

I think I might get it, he's not trying to *overwrite* the method, but he's making it a public function so he can use it in other parts of his code.  Is that right?

Can you provide an example of where else you would use this method?

**Comment by ahmedofali** [comment]
I see it much cleaner code so I wrote if you find it will slow the code do not merge it but may I know how you tested it will slow the code or best practices for faster code to apply it in the future.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
