### PR TITLE
[5.1] Change the exception the gate throws

### PR DESCRIPTION
**Pull request by georgecoca**
I've updated this file in order to throw the correct Exception which is UnauthorizedException on createGateUnauthorizedException method. Also this is useful in order to render a different response here: app/Exceptions/Handler.php

### CODE REVIEW

**Comment by taylorotwell** [comment]
This is updated in 5.2.

**Comment by taylorotwell** [comment]
To give more more info, it would be a breaking change to make this change on 5.1.

**Comment by JosephSilber** [comment]
@geodeveloper See here: [AuthorizesRequests.php#L16](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Auth/Access/AuthorizesRequests.php#L16)

**Comment by geodeveloper** [comment]
Ok, great. It's good to know it has been fixed. Thank you.

**Pull request closed without merging**
