### PR TITLE
Added convenient methods for subclasses to hook into the model's events

### PR DESCRIPTION
**Pull request by HolgerW1**
Model subclasses currently have no convenient way to internally hook into the creation, insertion, update, saving and deletion of the model.

App wide event handlers are not appropriate for situations where you want to make your models re-usable for several apps and where you actually perform internal operations only relevant to the model itself and not to the app or any app specific implementations.
The boot method of the model's subclasses can't and shouldn't be used to hook into the model's global events due to the unit testing problem (multiple include issue).

So this extension gives subclasses a chance to perform operations which are independent to app specific implementations and doesn't force developers to put their model only related code into app wide event handlers.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We have events for this.

**Comment by HolgerW1** [comment]
So how do you create a re-usable model class which is not specific to a single app and without forcing developers to paste the same app independant code into the "EventServiceProvider" boot method over and over again?

**Comment by HolgerW1** [comment]
To refine my question: how does a model class add an event handler for its own events inside its class file?
The use case is that code belonging to the model should remain in the class file and not have to be maintained outside the model class.

Maybe I'm wrong but what I've read so far is that you shouldn't use the `boot` method of the class for this and it would lead to errors in phpunit unit tests.

**Comment by TheShiftExchange** [comment]
You just override the model boot method and overload its own events.

**Comment by HolgerW1** [comment]
@TheShiftExchange if I understood you right then according to #1181 that's sth. you shouldn't do and will result in problems with phpunit.

**Comment by TheShiftExchange** [comment]
@HolgerW1 - in that thread is multiple solutions on how to make PHPunit tests work with models that have their own events. There are also multiple forum threads on the topic.

**Pull request closed without merging**
