### PR TITLE
[5.3] Changed the way after/before queue job events work

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This ensures the after event is always fired, and for consistency, since we can't catch exceptions from the after event if we want to fire them in this way, I've changed the exception catching to only catch those thrown by actually executing the job.

**Comment by taylorotwell** [comment]
I can't decide if we really want to fire "after" if an exception occurred. That's kind of a change in behavior. Previously, "after" meant that the job ran successfully.

**Comment by GrahamCampbell** [comment]
Hmmm, maybe. I just see after, and think "after trying to process a job, whatever the outcome". Maybe we need another event that does actually mean that?

**Comment by GrahamCampbell** [comment]
aw ;(

**Pull request closed without merging**
