### PR TITLE
[5.2] add shuffleAssociative to Collection

### PR DESCRIPTION
**Pull request by mattvb91**
Shuffle an associative collection while maintaining the keys

### CODE REVIEW

**Comment by lucasmichot** [comment]
Tests?

**Comment by mattvb91** [comment]
I didn't see any tests for the existing shuffle functionality. Any recommendations as to how to approach it?

**Comment by gibtang** [comment]
Since the result is a random collection. Maybe a simple test is to make sure the result of the collection is not the same as the input collection. There could be a very small off chance that the shuffle actually generates the same result as the initial collection, but that is infinitesimal

**Comment by GrahamCampbell** [comment]
> but that is infinitesimal

Not really, depending on the input size. For a size of 3, it's quite likely tbh.

**Comment by GrahamCampbell** [comment]
For a size of 2, it's 1/2.

**Comment by mattvb91** [comment]
yea because it is random there is the chance that tests fail because the off chance exists that it could return the same input.

I was assuming thats why there was no tests for the current shuffle function.

How is this data set size to test on?
```
        $c = new Collection([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
```

**Comment by lucasmichot** [comment]
> Since the result is a random collection. Maybe a simple test is to make sure the result of the collection is not the same as the input collection. There could be a very small off chance that the shuffle actually generates the same result as the initial collection, but that is infinitesimal

I would also test that the value for a specific key is the same in the input and in the result.

**Comment by mattvb91** [comment]
@lucasmichot array_diff should cover that part:

```
  
    public function testShuffleAssociative()
    {
        $c = new Collection([
            0 => 'zero',
            1 => 'one',
            2 => 'two',
            3 => 'three',
            4 => 'four',
            5 => 'five',
            6 => 'six',
            7 => 'seven',
            8 => 'eight',
            9 => 'nine'
        ]);

        $s = $c->shuffleAssociative();
        $this->assertEmpty(array_diff($c->toArray(), $s->toArray()));
        $this->assertNotEquals(array_keys($c->toArray()), array_keys($s->toArray()));
    }

```

@gibtang do you think using array_keys is sufficient to test the order is different? @GrahamCampbell is that set size large enough to not cause issues?

**Comment by taylorotwell** [comment]
Going to hold off on this. You can define it in your own project if needed.

**Comment by mattvb91** [comment]
@taylorotwell any feedback? Would you prefer an associative array be handled by a separate class altogether?

**Comment by GrahamCampbell** [comment]
No.

> You can define it in your own project if needed.

**Pull request closed without merging**
