### PR TITLE
[10.x] Add forbid, forbid_if and forbid_unless helpers

### PR DESCRIPTION
**Pull request by karkowg**
Small nicety on top of `abort`, `abort_if` and `abort_unless` but dedicated to throwing unauthorized exceptions (403).

`forbid('You shall not pass!');`

### CODE REVIEW

**Comment by milwad-dev** [comment]
I don't agree

**Comment by morloderex** [comment]
@karkowg wouldn't it be better to use `throw_if` and `throw_unless` for this, and then just throw the `Illuminate\Auth\Access\AuthorizationException`?

My reasoning is that `Illuminate\Auth\Access\AuthorizationException` underlying response could have been modified and just by using the abort_if and abort_unless helpers respectively we are by-passing this customisation?

**Comment by taylorotwell** [comment]
I honestly don't mind this method but fear it opens the door to a PR for every single status code imaginable. 😅

**Comment by taylorotwell** [comment]
Feel free to define in your own project. 👍

**Pull request closed without merging**
