### PR TITLE
[8.x] Use "sync" queue in Bus::dispatchNow()

### LINKED ISSUE #29917: [6.0] Job middleware not respected with `dispatchNow()`
- Laravel Version: 6.0.1
- PHP Version: 7.3.8

### Description:
In Laravel 6.0 job middleware was introduced. This works perfectly, except for when jobs are dispatched to be executed immediately using `dispatch_now()` or `Job::dispatchNow()`. Job specific middleware is never applied, as the `\Illuminate\Bus\Dispatcher::dispatchNow()` method never resolves the command specific middleware as the `\Illuminate\Queue\CallQueuedHandler::dispatchThroughMiddleware()` does.

### Steps To Reproduce:
```php
class MyJobWithMiddleware implements ShouldQueue
{
    public function middleware()
    {
        return [new MyMiddleware()];
    }

    public function handle()
    {
         //
    }
}

class MyMiddleware
{
	public function handle($command, $next)
    {
        dd('call me');
    }
}

dispatch_now(new MyJobWithMiddleware());
//

dispatch(new MyJobWithMiddleware());
// "call me"
```

### PR DESCRIPTION
**Pull request by taylorotwell**
This PR fixes two issues. First, it fixes an issue where job middleware are not run when doing something like `ProcessPodcast::dispatchNow()`. This can be fixed by dispatching this job through the `sync` queue instead of invoking it directly from the command bus.

The second problem it fixes is currently any jobs dispatched using `dispatchNow` do not have have access to the `$this->job` property, even though they use `InteractsWithQueue`. The `$this->job` variable will just be `null`. This is awkward because you may have a job that is sometimes dispatched using the normal `dispatch` method and sometimes using `dispatchNow` and the `$this->job` variable is only going to be available when dispatched using `dispatch`. So, you would have to put `null` checks within your job to work around this. This PR solves this by setting a `SyncJob` on the job if one is not already set.

Added a new `dispatchDirectly` method to execute a job directly within the command bus without using the sync queue or job middleware (basically the old `dispatchNow` behavior).

**Alternative:**

One alternative to this is to leave `dispatchNow` as it is and add a new `dispatchSync` method (or some similar name) that dispatches the job using the `sync` queue.

### CODE REVIEW

**Comment by Muffinman** [comment]
I've run into this myself with a project recently. Looks like a good change! 👍

**Comment by driesvints** [comment]
I think updating the behavior here for dispatchNow definitely makes sense. At the moment, I can't see any way it'd break an app.

**Comment by winkbrace** [comment]
I know it's just semantics, but maybe a little more difference in method naming? So instead of `dispatchDirectly` you could emphasize the difference in behaviour more with for example `dispatchRaw` or `dispatchOnly`?

**Comment by taylorotwell** [comment]
Decided to take a less breaking approach using a new `dispatchSync` method.

**Comment by rodrigopedra** [comment]
Hi @taylorotwell , great addition solves a problem I have in a app right now.

One question: as the dispacthNow will attach a SyncJob instance to the command, will the `failed` method be called when an exception is thrown inside the command?

That would simplify/unify a lot of jobs error handling strategies I current have between sync and queued jobs.

Thanks in advance.

**Pull request merged**
