### PR TITLE
Add console command for create a blade view file

### PR DESCRIPTION
**Pull request by IgorDePaula**
Sometimes I need to create many blade files. A command would make it much easier than clicking with the mouse several times. Of all the resources that can be created by the command line, I think this missing.

### CODE REVIEW

**Comment by 36864** [comment]
There have been several PRs like this before and all have been closed: https://github.com/laravel/framework/pulls?q=is%3Apr+make%3Aview+is%3Aclosed

There are plenty of packages out there that add generators as artisan commands, including generators for views. This doesn't need to be in the core.

**Comment by IgorDePaula** [comment]
It is not interesting complete the artisan command list?

**Comment by IgorDePaula** [comment]
Taylor always said: "holding this", but why? Holding without motivation?

**Comment by 36864** [comment]
Pretty much all the `make` commands take care of a fair bit of boilerplate (class definitions, imports, etc.), but usually they default to the least amount of boilerplate necessary for the component to work.

View files have the least amount of boilerplate necessary to be valid. An empty file is a valid view file. Creating an empty file is simple enough on any system without resorting to artisan.

Editor snippets should be sufficient to quickly get your views up. Most modern editors also have functions that enable quick and easy file creation.

If you really want a make:view command, that's fine. As I said before, there are plenty of packages out there with generators for literally everything. But we don't need all of them to be in the core.

**Comment by IgorDePaula** [comment]
Sorry, I not understand what you want say. Why the core not need?

**Comment by 36864** [comment]
Typically you would ask the reverse question when adding something to the core: Why does the core need this?

Personally I don't see the need for a command that just makes a file and pastes 3 lines of codes in it. I can create a stub and use it to make new view files easily without resorting to artisan, for example by simply entering `more stub > resources/views/newview.blade.php`. I can do it even more easily by using a shortcut in my text editor.

The `make` commands are useful when there's quite a bit of boilerplate involved, such as when creating a resource controller. Views usually have either very little in common with other views (as in your implementation, where the new file basically has 3 lines in it), or very much in common, such as when you're adding similar views to handle similar resources in which case it's easier to just duplicate a file and replace variable names (say, `users/index.blade.php` and `posts/index.blade.php` could be very similar, and you'd only have to replace `$user` with `$post` and adjust specific column names to have a functional view).

The only case where I've felt the need for a command that generates views is when I have a few resources that I want to have basic CRUD for, and want to make the same index/show/edit views for. In those cases, I can easily import a generator package that creates all the basic view files for as many resources as I need, and then uninstall it once I'm done.

**Comment by ahinkle** [comment]
Please add tests

**Comment by IgorDePaula** [comment]
I understand now, I will close the PR for agree with you.

**Pull request closed without merging**
