### PR TITLE
[9.x] Use arrow function

### PR DESCRIPTION
**Pull request by hosseinhezami**
Change with arrow function.

### CODE REVIEW

**Comment by driesvints** [comment]
The previous version is more readable imo.

**Comment by hosseinhezami** [comment]
@driesvints :-/
https://github.com/laravel/framework/pull/42838

**Comment by hosseinhezami** [comment]
@taylorotwell 🤔

**Comment by hosseinhezami** [comment]
Hello @driesvints ,
So why this PR https://github.com/laravel/framework/pull/42838 merged?
@taylorotwell

**Comment by driesvints** [comment]
@hosseinhezami please stop spamming our tracker

**Comment by hosseinhezami** [comment]
Spam? it's a question!

**Comment by driesvints** [comment]
@hosseinhezami we don't always merge these: https://github.com/laravel/framework/pull/43233

**Pull request closed without merging**
