### PR TITLE
[5.5] Add allowed ips to Maintenance Mode

### PR DESCRIPTION
**Pull request by marcoocram**
With this change we can set one or more ip addresses that it will be allowed to use the app while it will be on maintenance for the rest of the world.

### CODE REVIEW

**Comment by marcoocram** [comment]
To allow some ip addresses set this env variable in your .env file:

MAINTENANCE_ALLOWED_IPS=127.0.0.1,0.0.0.0,...

**Comment by sisve** [comment]
You should not read environment variables outside of your configuration files. A cached configuration (`php artisan config:cache`) will no longer parse the .env file, so`getenv('MAINTENANCE_ALLOWED_IPS')` will end up returning null. The proper way would be to have a configuration file read the value, and then in turn read from the configuration file using the `config(...)` helper.

**Comment by AdrianKuriata** [comment]
Hope it will be added!

**Comment by browner12** [comment]
this seems like a harmless addition, but i'm kind of against this. Can you explain your use case for this?

First off, ideally your site should be in maintenance mode for a **very** short duration, possibly just during a deployment if you're not doing a zero-down-time deployment.

Second, if you are a designated user, shouldn't you just be using your local version of the site?

Also, @sisve 's suggestions need to be implemented for this to be considered.

If you could explain your use case, it would help.  Thanks.

**Comment by marcoocram** [comment]
Hi!

Thanks for your comments, move to a config could be a nice solution.

My use case for this is sometimes to put an app in production before his launch and check (for the clients and our team) that all works as expected.

I know that this process is better in pre-production area or something else, however sometimes we have not this possibility...

If more people need this i can pass this env variable to config file.

Thanks!

**Comment by AdrianKuriata** [comment]
Sometimes something working on local, but not in production server, this is
good solution for situations like that.

15.11.2017 8:48 PM "Marco Bellido" <notifications@github.com> napisał(a):

**Comment by browner12** [comment]
hmm... i guess I'm 👎  on this. It's a problem that has many other solutions, one such solution being a staging server.

If that is not an option for you, there is another simple solution that would effectively mimic 'maintenance' mode.  simply create a custom service provider that gets applied to all routes, and sends all requests that are not from your whitelist IPs to a Maintenance page.

**Comment by marcoocram** [comment]
I've commited the change to config var if someone is interested to use as custom middleware in their projects.

I close the pull request then.

Thanks!

**Pull request closed without merging**
