### PR TITLE
[5.1] Fix for chunk()

### LINKED ISSUE #9649: Issue using chunk with limit
I am trying to design an endpoint that has a streamed response for returning large JSON results. I am wanting to add a limit query paramater. But it appears to have no effect when used with `chunk()`

For example this doesn't work. The limit simply has no effect:
```php
$users = Users::select();
$users->skip(0);
$users->take(1);

$users->chunk(1, function($u) {
    print_r($u);
});
```

But this does:

```php
$users = Users::select();
$users->skip(0);
$users->take(1);
print_r($users->get())
```

Please any help would be massively appreciated.

### PR DESCRIPTION
**Pull request by arrilot**
Closes #9649

This one is relatively hard to review. Sorry about that.

As you can see in the issue limits and offsets are completely ignored if `chunk()` is used instead of `get()`.
This happens because chunk overrides those properties internally.

Although it's a rare usecase, in my opinion it's a bug and should be fixed in 5.1 therefore.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Chunk is *meant* to override limits and offsets. The original issue you posted shouldn't even be using chunk.

**Comment by Arrilot** [comment]
Why throwing away limits and offset is better than actually handling them like `get()` does?
Are you sure noone will ever want to do smth like `Model::skip(100000)->take(50000)->chunk(100, ...)`?

**Comment by smaxwellstewart** [comment]
Why is 'chunk is meant to override limits and offsets'?

I can't see any reason why there is the necessity for an intentional overwrite.

**Comment by Shkeats** [comment]
@taylorotwell I also can't see any reason why chunk shouldn't internally respect a limit and offset that has already been set. It's not clear that chunk is *meant* to override limits and offsets. It seems to me that rather it *happens* to override limits and offsets because of how it's implemented. I think it's a valid usecase to want to chunk through a limited or offset number of records. 

Say I want to do some processing on 40,000 records with 4 worker threads for jobs and I want them to do 10,000 records each in batches of 500, currently you need to calculate the limits and offsets yourself, set up a loop and call the queries incrementing the skip() and take() as you go.

Chunk could handle this easily if I could run the following on each worker.

-1 Model::take(10000)->chunk(500,..)
-2 Model::skip(10000)->take(10000)->chunk(500,..)
-3 Model::skip(20000)->take(10000)->chunk(500,..)
-4 Model::skip(30000)->take(10000)->chunk(500,..)

I think the above lines are conceptually sound and very readable. 
"With this model, skip the first 10,000 rows, take the next 10,000 in batches of 500 passing them to this closure."

**Comment by smaxwellstewart** [comment]
^ +1

**Comment by WillMac29** [comment]
Model::skip(10000)->take(10000)->chunk(500,..)
I actually just wrote this code intuitively hoping it would do what is indicated above. 
It wasn't working so I decided to do some searching and I came across this pull request. I think its a great idea. Maybe another method or optional override parameter of the default behavior of chunk would be nice.

**Comment by ammont** [comment]
^ +1

**Comment by hhsadiq** [comment]
Any workaround for this?

**Comment by NicksonYap** [comment]
+1

we need this!

**Comment by NicksonYap** [comment]
Work around it to just count the number of loops

```
$skip_amount = 100
$done_amount = 0

DB::table('users')->orderBy('id')->chunk(100, function ($users) use($skip_amount, &$done_amount ) {
    foreach ($users as $user) {
        $done_amount += 1;
         if($done_amount >=  $skip_amount){
             //
         }
    }
});
```

**Comment by egyptik** [comment]
Here's an Eloquent workaround:

```php
Model::skip(100)->take(100)->get()->chunk(10)->each(function ($chunk) {
    // chunk
});
```

**Comment by chriscalip** [comment]
> Here's an Eloquent workaround:
> 
> ```
> Model::skip(100)->take(100)->get()->chunk(10)->each(function ($chunk) {
>     // chunk
> });
> ```
> 
> This will not chunk the Queries, but it does allow you to chunk the results.

A more pragmatic way would be first to get an array of `model Ids` then generate an array of `batch Sets` based on the array chunk of those model Ids. For each subset do a Model find by Ids.
```php
$idModels = [..];
$throughput = N;
$batchSets = array_chunk($idModels, $throughput);
unset($idGroups);
$idModels = $batchSets[0];
$models = Model::find($idModels);
```

**Comment by Stevemoretz** [comment]
Just was reading this, for future readers : none of the above workarounds are good, don't use them, they all have performance issues, if you want to do something like that just re-implement the chunk yourself with `limit`, `skip` and a simple loop based on the total count.

**Comment by DrDynamic** [comment]
> @taylorotwell Model::skip(10000)->take(10000)->chunk(500,..) I actually just wrote this code intuitively hoping it would do what is indicated above. It wasn't working so I decided to do some searching and I came across this pull request. Maybe another method or optional override parameter of the default behavior of chunk would be nice.
> 
> ^ +1

The same happened to me right now. I'd really love to have this.

**Pull request closed without merging**
