### PR TITLE
[8.x] Bumped minimum symfony

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Moves the minimum version of Symfony to 5.1.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Looks like we need to add another component to make tests pass.

**Comment by GrahamCampbell** [comment]
Hmmm, let me investigate. Maybe we have an implicit dependency we should probably add into 6.x and 7.x too.

**Comment by GrahamCampbell** [comment]
Seems to have been caused by https://github.com/symfony/http-foundation/commit/63f42630839c6e2b097ae4a183ca9d3992ccd80a.

**Comment by GrahamCampbell** [comment]
I am going to recommend that they revert their change, as it is a BC break. It will actually break Laravel 7.x too, once Symfony 5.1.0 is out. https://github.com/symfony/symfony/pull/35807

**Comment by GrahamCampbell** [comment]
Let's see what they say to my comments. If they don't want to revert and merge my PR, then we should add the mime dependency to the laravel/framework 7.x branch.

**Comment by nicolas-grekas** [comment]
BTW, thank you for testing with unreleased versions, helping spot issues as early as possible!

**Comment by GrahamCampbell** [comment]
Ok, rebased. Now let's see if the tests pass.

**Comment by GrahamCampbell** [comment]
Passing. 🎉

**Pull request merged**
