### PR TITLE
Adds a bunch of nth item helpers

### PR DESCRIPTION
**Pull request by davedevelopment**
I was surprised to find there wasn't a `Collection::second()` method, so thought I'd add one. 

Then I got kind of excited. My understanding is that many of the Laravel Artisans take inspiration from @DHH, and I've been told I have to ask myself ["What Would DHH Do?"](https://twitter.com/adamwathan/status/636118002199465984). Thankfully, I've a decent amount of experience with Rails and I knew **exactly** What DHH [Would](https://github.com/rails/rails/commit/22af62cf486721ee2e45bb720c42ac2f4121faf4) [Do](https://github.com/rails/rails/commit/e50530ca3ab5db53ebc74314c54b62b91b932389#diff-e3d63442dcd5dc00aa09c82c7daa4934) 😎

``` php
Collection::times(100)->second(); // int(2)
Collection::times(100)->third(); // int(3)
Collection::times(100)->fourth(); // int(4)
Collection::times(100)->fifth(); // int(5)
Collection::times(100)->fortyTwo(); // int(42)
Collection::times(100)->secondToLast(); // int(99)
Collection::times(100)->thirdToLast(); // int(98)
```

```

### CODE REVIEW

**Comment by garygreen** [comment]
```php
/**
 * Return the reddit element in an array passing a given truth test.
 *
 * @param  array  $array
 * @param  callable|null  $callback
 * @param  mixed  $default
 * @return mixed
 */
public static function fortyTwo($array, callable $callback = null, $default = null)
{
```

This is a joke from reddit, right? If this get's merged I'm giving up all hope on humanity. 😄 

Discussion about it's inclusion in Rails was pretty controversial and with good reason. One comment in particular stands out to me:

> 10 useless methods, another 10 useless methods, another 10 useless methods ……

Meh.

**Comment by devcircus** [comment]
Proposed before in #20500

**Comment by davedevelopment** [comment]
> Proposed before in #20500

No way! Spent ages on this 😂

**Comment by devcircus** [comment]
You never know. Taylor changes his mind sometimes after some time has passed.

**Comment by taylorotwell** [comment]
Closed just when I was about to merge. Shame.

**Pull request closed without merging**
