### PR TITLE
[5.1] Memcached persistent connections, SASL authentication, and custom options

### PR DESCRIPTION
**Pull request by tomcastleman**

### CODE REVIEW

**Comment by tomcastleman** [comment]
Proposed additions to cache configuration file `config/cache.php`.

This PR makes the following extra configuration items are available for use with a memcached store:

* `persistent_id` - [`Memcached::__construct`] (http://php.net/manual/en/memcached.construct.php)
explains how this is used
* `sasl` - used by [`Memcached::setSaslAuthData`](http://php.net/manual/en/memcached.setsaslauthdata.php)
* `options` - see [`Memcached::setOptions`](http://php.net/manual/en/memcached.setoptions.php)

These may be used in a store config like so:

```
'stores' => [
    'memcachedstorefoo' => [
        'driver'  => 'memcached',
        'persistent_id' => 'laravel',
        'sasl'       => [
            env('MEMCACHIER_USERNAME'),
            env('MEMCACHIER_PASSWORD')
        ],
        'options'    => [
            'OPT_NO_BLOCK'         => true,
            'OPT_AUTO_EJECT_HOSTS' => true,
            'OPT_CONNECT_TIMEOUT'  => 2000,
            'OPT_POLL_TIMEOUT'     => 2000,
            'OPT_RETRY_TIMEOUT'    => 2,
        ],
        'servers' => [
            [
                'host' => '127.0.0.1', 'port' => 11211, 'weight' => 100
            ],
        ],
    ],
],
```

When defining `options` you should set the config key to the `Memcached` constant name as a string.
This avoids any issues with local environments missing ext-memcached and throwing a warning about
undefined constants. The config keys are automatically resolved into `Memcached` constants by the
`MemcachedPlus\MemcachedConnector` which throws a `RuntimeException` if the constant is invalid.

**Comment by tomcastleman** [comment]
The tests are going to need some tweaking. I can take a look but I'm not so familiar with this.

**Comment by taylorotwell** [comment]
Closing until tests are updated.

**Comment by tomcastleman** [comment]
Submitted new PR #13359 with tests

**Pull request closed without merging**
