### PR TITLE
[5.2] Fix blob type for doctrine columns (binary to blob).

### PR DESCRIPTION
**Pull request by j3j5**
Resubmitted for 5.2 #12044

### CODE REVIEW

**Comment by vlakoff** [comment]
This should be backported to 5.1, I suppose.

**Comment by j3j5** [comment]
I mentioned it on the original issue ( #12043 ) and I did not receive any response (and the issue was closed). I have a branch ready to submit a PR if it's going to be merged.

**Comment by GrahamCampbell** [comment]
Should have been sent to 5.1 in the first place rather than backported.

**Comment by GrahamCampbell** [comment]
I can cherry-pick and backport though I guess. Will just check with Taylor if he's ok with this.

**Comment by j3j5** [comment]
Where can I find the best way to proceed for this kind of issues that affect both, LTS and current versions? Because I did what I understood you say [here](https://laravel.com/docs/5.2/contributions#bug-reports). This is a _minor bug, fully backwards compatible_ and I sent it to the _latest stable branch_ (5.2, if we ignore my mistake of sending it to master first, sorry about that)).

Did I misunderstand it?

**Comment by vlakoff** [comment]
I thought in cases like this, the way to go was to PR to master (5.2) then if suitable, it would manually be backported to LTS (5.1). Isn't it?

**Comment by j3j5** [comment]
Not to _master_ but to the _latest stable branch_. `master` is 5.3 at the moment and that was my first mistake but that's clearly stated on the docs.

> Bug fixes should never be sent to the `master` branch unless they fix features that exist only in the upcoming release.

**Comment by GrahamCampbell** [comment]
> I thought in cases like this, the way to go was to PR to master latest stable (5.2) then if suitable, it would manually be backported to LTS (5.1). Isn't it?

No. Contributors should PR to the correct branch. We don't like to backport. We merge to lowest, then recursively merge upwards.

> This is a minor bug, fully backwards compatible and I sent it to the latest stable branch (5.2, if we ignore my mistake of sending it to master first, sorry about that)).

Our contribution guide says they need to be sent to the LTS branch, which is currently 5.1.

**Comment by j3j5** [comment]
Alright, so I misunderstood _latest stable branch_ with latest _LTS branch_, maybe that's something to be better specified on the contribution guide, because to me, the latest stable is not the same as the latest LTS.

**Comment by GrahamCampbell** [comment]
> Alright, so I misunderstood latest stable branch with latest LTS branch

Looks like our docs are actually incorrect. They should say the LTS branch if they are present in there, otherwise the latest stable.

**Pull request merged**
