### PR TITLE
[5.7] Update the design of the list of commands in Artisan

### PR DESCRIPTION
**Pull request by nunomaduro**
Hey 👋

This proposal addresses **modifications on the output of the artisan list command**.

> This proposal was already discussed in [https://github.com/laravel/ideas/issues/1148](https://github.com/laravel/ideas/issues/1148).

Currently, if you type `php artisan` the terminal will output this:

screenshot 2018-05-01 18 20 40

**Proposal**: Perform minor modifications on the point 1 and point 2. Remove entirely the point 3 and remove subtitles ( the yellow text) from the point 4.

The end result will be:

example-2

You can install the package [Laravel Console Summary](https://github.com/nunomaduro/laravel-console-summary) to see the end result locally in your machine. But I thought to perform a PR to the core with this exact same code instead of proposing the addition of a package.

**Tests**: I don't believe that we need tests on this PR.

### CODE REVIEW

**Comment by mpociot** [comment]
I personally prefer the ability to see all available options. Especially things like verbosity are helpful for people that maybe aren’t used to the artisan commands.

**Comment by abdumu** [comment]
Subtitles are important because they show what Usage suggests. In your version, the list is not clear whether listing commands or options.

I think this change should be for only "list" command, since it's meant to be listing only commands, not anything else.

**Comment by browner12** [comment]
agreed, too subjective.  i do like bringing point 2 onto 1 line, though. removing line breaks where not needed is helpful since this list gets longer and longer all the time.

**Comment by DojoGeekRA** [comment]
This change only affects the `php artisan list` command so the rest of the commands will still display its options.

The beauty of this is that it looks clean and it's unlikely that you will need to pass options like `-quiet` or `-verbose` to this command specifically, so there is no need to display them.

**Comment by taylorotwell** [comment]
Personally I would prefer not to maintain our own list command.

**Comment by taylorotwell** [comment]
It feels like this is something better addressed on the Symfony level.

**Pull request closed without merging**
