### PR TITLE
[5.1] Throttle dynamic parameters

### PR DESCRIPTION
**Pull request by sileence**
Allow developers to change the throttle limit, time and message without copy pasting the trait's methods

This version uses methods and property_exists

Also I considered a good idea to move the throttle message to another method, so users can replace that too, for example if they decide to throttle for 24 hours the could implement the logic so the message says: "you can't login for 3 hours" (instead of seconds, etc.)

### CODE REVIEW

**Comment by martinbean** [comment]
@sileence You beat me to it! I was about to open a Pull Request with throttle limit made configurable. I see you’ve gone one step further though! :smile:

**Comment by sileence** [comment]
@martinbean well the most important thing is that we can finally configure these values :) 

This is my first pull request to the framework, I hope to collaborate more in the future :)

**Comment by JesseLeite** [comment]
:D

**Comment by JesseLeite** [comment]
Thanks @taylorotwell @sileence!

**Pull request merged**
