### PR TITLE
[5.1] Add some common files to the compile config

### PR DESCRIPTION
**Pull request by vlakoff**
These files are loaded on each HTTP request on a fresh installation.
- Authorization Gate
- Symfony Finder: filename filter by glob (since #6781)
- Dotenv
- Carbon (was removed in #9446, but is called in [StartSession](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Session/Middleware/StartSession.php))

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You don't need to add things like carbon here. Class preloader will load any dependencies of other files here for us already.

**Comment by GrahamCampbell** [comment]
:-1: for this as is.

**Comment by vlakoff** [comment]
Carbon is currently missing from the compiled.php, probably because it is generated from the CLI.

**Comment by GrahamCampbell** [comment]
Hmmm, ok. :+1: I guess. ;)

**Comment by vlakoff** [comment]
Yes, there are (incredibly very few) cases that ClassPreloader doesn't catch.

Already soooo close to fully autonomous working. We'll still need human programmers for just a few more years.

**Pull request merged**
