### PR TITLE
[10.x] Revival of the reverted changes in 10.25.0: `firstOrCreate` `updateOrCreate` improvement through `createOrFirst` + additional query tests 

### PR DESCRIPTION
**Pull request by mpyw**
## Prior Discussion

- #48567

## What Changes?

This PR unreverts #48531 and revives `firstOrCreate` `updateOrCreate` enhancement under `createOrFirst`. They were unreliable in previous versions. In high-load applications, unique key constraint errors would occur even when checking for the existence of a record beforehand. The purpose of refactoring with `createOrFirst` internally is to catch this and retry automatically.

### Actual Implementation Changes

- [Revert "[10.x] Revert from using createOrFirst in other *OrCreate methods"](https://github.com/laravel/framework/pull/48531)
  - Reinstate previously reverted changes.
- **[refactor: 💡 use createOrFirst in firstOrCreate](https://github.com/laravel/framework/pull/48637/commits/15e8999f91b1ea7d1a34f04014a21676c0d20d1a)**
  - **Fixed `HasManyThrough::firstOrCreate` to use `createOrFirst`. <ins>This was a previously overlooked point.</ins>**

### Coverages

- [x] `Builder::createOrFirst` by @mpyw
- [x] `Builder::firstOrCreate` by @mpyw
- [x] `Builder::updateOrCreate` by @mpyw
- [x] `HasMany::createOrFirst` by @mpyw
- [x] `HasMany::firstOrCreate` by @mpyw
- [x] `HasMany::updateOrCreate` by @mpyw
- [x] `HasManyThrough::createOrFirst` by @fuwasegu + @mpyw
- [x] `HasManyThrough::firstOrCreate` by @fuwasegu + @mpyw
- [x] `HasManyThrough::updateOrCreate` by @fuwasegu + @mpyw
- [x] `BelongsToMany::createOrFirst` by @mpyw 
- [x] `BelongsToMany::firstOrCreate` by @mpyw
- [x] `BelongsToMany::updateOrCreate` by @mpyw

## Notes

Some `FIXME` comments are remaining. 

```php
$model->getConnection()
    ->expects('select')
    // FIXME: duplicate conditions
    ->with('select * from "table" where ("attr" = ?) and ("attr" = ?) limit 1', ['foo', 'foo'], false)
    ->andReturn([[
        'id' => 123,
        'attr' => 'foo',
        'val' => 'bar',
        'created_at' => '2023-01-01 00:00:00',
        'updated_at' => '2023-01-01 00:00:00',
    ]]);
```

These indicate a problem with duplicate and useless conditions being given when retrying the `SELECT`, but do not significantly bother with the operation. Attempting to fix this using `clone` may yield some unexpected effects due to the `Builder` mutableness. Therefore, we'd like to recognize this as a known issue and leave it out of the scope of this PR.

@tonysm If you think you can fix this problem, could you please submit another PR? Thank you in advance.

### CODE REVIEW

**Comment by driesvints** [comment]
I honestly suggest to just leave things be. I also don't know what this is fixing again?

**Comment by mpyw** [comment]
@driesvints If you have any comments, please see #48567. I personally emailed @taylorotwell and asked him about the policy and he agreed that as long as we add a test it should be fine.

**Comment by mpyw** [comment]
@taylorotwell @crynobone @driesvints @tonysm @ralphjsmit @ryanldy @trevorgehman @SakiTakamachi @fuwasegu Please review the changes. Thank you in advance.

**Comment by morloderex** [comment]
@mpyw if we rely on a unique constraint and my attributes doesn't not include the primary key of the table. And the attributes used let's call it `name` in this example. Doesn't have a unique constraint on the table wouldn't this new behaviour of relying on a unique constraint violation not be a major breaking change, since the unique constraint would never actually occur?

**Comment by mpyw** [comment]
@morloderex This is not a breaking change. It works as follows.

- Before
  - `firstOrCreate()` tries to retrieve through `first()` and calls `create()` if there is no result
  - `updateOrCreate()` tries to retrieve through `first()` and calls `create()` if there is no result, `update()` if there is a result.
- After
  - `firstOrCreate()` tries to retrieve through `first()` and calls **`createOrFirst()`** if there is no result
  - `updateOrCreate()` tries to retrieve through `first()` and calls **`createOrFirst()`** if there is no result, `update()` if there is a result.

The `create()` is just changed to `createOrFirst()`, not that `firstOrCreate()` `updateOrCreate()` will not work without unique constraints in the future. It only means that `firstOrCreate()` and `updateOrCreate()` will work more reliably with unique constraints.

**Comment by trevorgehman** [comment]
> Doesn't have a unique constraint on the table wouldn't this new behaviour of relying on a unique constraint violation not be a major breaking change, since the unique constraint would never actually occur from the database provider?

Without a unique constraint on the table `firstOrCreate()` will work the same way as it does now.

**Comment by trevorgehman** [comment]
> I also don't know what this is fixing again?

@driesvints Essentially it solves race conditions. In high concurrency environments we can't rely on `firstOrCreate()` in its current form because between the `first()` and the `create()` calls, another process may have already created the record. So the `create()` call will throw a `UniqueConstraintException` in that case.

We have for a long time implemented a workaround like this by extending the Builder:

```
public function firstOrCreate(array $attributes = [], array $values = [])
    {
        try {
            return parent::firstOrCreate($attributes, $values);
        } catch (UniqueConstraintViolationException $e) {
            return parent::first($attributes) ?? throw $e;
        }
    }
```

**Comment by deleugpn** [comment]
I don't envy Taylor on this PR at all :sweat_smile: 

[✗] This is a significant change to one of Laravel's most important modules (Eloquent).
[✔️] But it seems like this was only reverted because Eloquent already had existing bugs that were somewhat "invisible". So in the long run the introduction of this change made Eloquent better.
[✔️] It is a convenient addition to the framework .
[✔️] There are many tests added which covers a large set of functionailty. It may be some duplicate tests, but having extra tests often have no downsides.
[✗] But ultimately as an end-user, if you need this, how hard is it to search/replace `firstOrCreate()` with `createOrFirst()` on your codebase?

**Comment by SakiTakamachi** [comment]
@deleugpn 

> But ultimately as an end-user, if you need this, how hard is it to search/replace firstOrCreate() with createOrFirst() on your codebase?

I don't understand why it needs to be replaced.

**Comment by mpyw** [comment]
@deleugpn You do not need to replace them.

1. Many existing usages of `firstOrCreate` in Laravel likely occur in scenarios where occasionally something is not created, but most are already created. It operates by `SELECT` from a replica and then `INSERT` into the primary if it doesn’t exist. The only additional behavior is re-`SELECT` from the primary if there’s a collision' afterward. In prescribed situations, continuing to use `firstOrCreate` is entirely acceptable.
2. Conversely, `createOrFirst` operates very efficiently in cases where most are not created, but some are. If you use this in scenario 1, **not only does the attempt to `INSERT` unnecessarily burden the database, but it also negatively consumes the auto-increment number space**.

Generally, continuing to use `firstOrCreate` should pose no issues. Therefore, you rarely need to – and likely should not – rewrite something previously written with `firstOrCreate` to use `createOrFirst` instead.

**Comment by trevorgehman** [comment]
> [✗] But ultimately as an end-user, if you need this, how hard is it to search/replace `firstOrCreate()` with `createOrFirst()` on your codebase?

They have different use-cases. If 95% of the time the record already exists, then `firstOrCreate()` makes more sense and will be more performant.

**Comment by mpyw** [comment]
@trevorgehman Exactly the same opinion with you 😄

**Comment by mpyw** [comment]
We also hope that this change will be covered in Laravel News. It is not a BC, but I think it is significant to let people know.

**Comment by mpyw** [comment]
Some of `afterCommit`-related tests are fixed, so we included the latest `10.x` branch just in case.

**Comment by akr4m** [comment]
Impressive refinement of firstOrCreate and updateOrCreate to handle high-load scenarios. Extensive testing bolsters confidence. Great work @mpyw! 👍

**Comment by taylorotwell** [comment]
Thanks - this is probably our last attempt at this. 😬

**Comment by tonysm** [comment]
Great work on this @mpyw and @fuwasegu. It's looking good!

**Comment by nunomaduro** [comment]
@mpyw Can you check this bug report? https://github.com/laravel/framework/issues/49514.

**Pull request merged**
