### PR TITLE
Add  relation column average query

### PR DESCRIPTION
**Pull request by amrfayad**
Query Builder Get Average from many relationship

### CODE REVIEW

**Comment by TBlindaruk** [comment]
@amrfayad , please target 5.7

**Comment by TBlindaruk** [comment]
@amrfayad , please close this PR ;)

**Comment by amrfayad** [comment]
@TBlindaruk  done

**Comment by TBlindaruk** [comment]
@amrfayad 5.6 accepts only security fixes.

**Comment by taylorotwell** [comment]
Release this as a package first.

**Pull request closed without merging**
