### PR TITLE
[10.x] Fix Http global middleware for queue, octane, and dependecy injection

### LINKED ISSUE #47738: Global HTTP client middleware being forgotten after every queue job
### Laravel Version

10.15.0

### PHP Version

8.1.19

### Database Driver & Version

MySQL 8.0.33

### Description

All Facades are reset after each queue job, https://github.com/laravel/framework/blob/3cd9bcb25dbfb4e70c9b96dd5b9c2ce109583217/src/Illuminate/Queue/QueueServiceProvider.php#L214.

This causes a global HTTP client middleware, applied in my app's ServiceProvider, not to be applied anymore when using `Http::get()` etc.

### Steps To Reproduce

`app/Providers/AppServiceProvider::boot()`

```php
public function boot()
{
    Http::globalRequestMiddleware(fn ($request) => $request->withHeader(
        'User-Agent', 'Example Application/1.0'
    ));
}
```

`app/Jobs/DoStuff::handle()`

```php
public function handle() {
    Http::get('https://example.com/1');
}
```

### PR DESCRIPTION
**Pull request by timacdonald**
fixes #47738

We added the ability to add global middleware to the Http client.

```php
Http::globalRequestMiddleware(fn ($request) => $request->withHeader(
    'User-Agent', 'Example Application/1.0'
));
```

Because Facades are cached for the duration of a request, this works as expected for each Http request.

On the queue / in octane however, these middleware are not applied.

This is because the underlying `Factory` is not a singleton, so the `Factory` instance is refreshed on each job execution / octane request. The `Factory` instance is where the middleware is stored.

This PR binds the `Factory` as a singleton. Excluding testing infrastructure, the only state the `Factory` maintains is the global middleware and the event service provider. As the event service provider is also a singleton, we shouldn't need to refresh it manually for Octane.

In addition to the queue and Octane fixes, this fix also means that the requests made by the `NotPwnedVerifier` will now pass through the global middleware, which I believe is the expected behaviour.

This is because the `NotPwnedVerifier` injects the `Factory` via the constructor, rather than accessing the Facade.

This also applies to any user-land code that is injecting the `Factory` class, which I also believe is the expected behaviour.

### CODE REVIEW

**Comment by bernardwiesner** [comment]
Just found this bug today... was about to open an issue. Thanks for the fix!

**Comment by timacdonald** [comment]
No troubles!

**Comment by StSarc** [comment]
This breaks the testing infrastructure though!

I am faking an http response of an URL in a test. This fake is written in a base test class. This is used by multiple other test cases. Some of these test cases implement another fake http response of the same URL.
Calling the fake method second time in these test cases does not work. It gives the response set by the first fake method. It does not overwrite the response with the new fake data. The first fake call is always taking the precedence.

Simplified code to reproduce:

```php
<?php

use Illuminate\Support\Facades\Http;

Route::get('/', function (){
  Http::fake([
    'https://laravel.com' => Http::response('OK', 200)
  ]);

  dump(Http::get('https://laravel.com')->body());

  Http::fake([
    'https://laravel.com' => Http::response('Internal Server Error', 500)
  ]);

  dump(Http::get('https://laravel.com')->body());
});
```

On the Laravel Playground: https://laravelplayground.com/#/snippets/0f8268bf-57d5-4709-ac54-e24965ec4c22

The same issue is being faced by others as well: https://laracasts.com/discuss/channels/laravel/overwrite-fake-response-in-http-client?page=1&replyId=762080

The solution suggested (swap) - it used to work until this PR got merged. That solution broke with this PR.

**Comment by timacdonald** [comment]
Responded in https://github.com/laravel/framework/issues/49398

**Pull request merged**
