### PR TITLE
[5.0] Change "stirng" to "string"

### PR DESCRIPTION
**Pull request by mortenhauberg**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This needs updating on any implementations of this contract too. :)

**Comment by mortenhauberg** [comment]
Of course. I think i got them both :)

**Comment by GrahamCampbell** [comment]
Please squash to one commit, then Taylor will review this soon. :)

**Comment by mortenhauberg** [comment]
Okay, i am lost. Could you help me out?

**Comment by GrahamCampbell** [comment]
Just given travis a kick. :)

**Pull request merged**
