### PR TITLE
[5.7] Pop the argument stack when unresolvable optional dependencies are found

### PR DESCRIPTION
**Pull request by twistor**
The technical explanation is that when an unresolved dependency is found in the container, a `BindingResolutionException` is thrown. Higher up in the code, if that dependency was optional, the default value is returned. But, that exception skips the code where the `with` (argument) stack would normally get popped. So, when the next dependency with arguments gets resolved, it has the wrong entry in the stack, and claims that the argument is missing.

This is a difficult bug to explain, it's easier with an example.

Paraphrasing some real code:
```php
// Somewhere in a test we set this in the conatiner.

app()->bind(ViesSoapClient::class, ViesSoapClientMock::class)

class ViesSoapClient
{
    public function __construct($wsdl) {}
}

class ViesSoapClientMock extends ViesSoapClient
{
    public function __construct() {}
}

class TaxService
{
    private $client;

    // Adding the optional constructor dependency here triggers the error.

    public function __construct(ViesSoapClient $client = null)
    {
        $this->client = $client ?: new ViesSoapClient('https://foo');
    }
}

class CartProcessor
{
    public function __construct(TaxService $t, $argument) {}
}

class CartFactory
{
    private $app;

    public function __construct(Application $app)
    {
        $this->app = $app;
    }

    public function buildCartProcessor()
    {
        // The error appears here. This code hasn't changed.
        // I stared at this for a long time scratching my head.
        // I checked the spelling of `argument`. Finally, looking at my diff
        // I was able to guess what change actually caused the error.

        // Illuminate\Contracts\Container\BindingResolutionException:
        // Unresolvable dependency resolving [Parameter #1 [ <required> $argument ]]
        // in class CartProcessor

        return $this->app->make(CartProcessor::class, ['argument' => 'foo']);
    }
}
```

> What does this change actually do?

This code catches the `BindingResolutionException`, cleans up the stack, and re-throws it.

> I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

This code has tests. I admit that they're not great at this point. I would appreciate some discussion as to how to make them acceptable once a consensus has been reached.

As far as I can tell this does not break BC. In most cases, `BindingResolutionException` propagates and this doesn't matter. I'm assuming the current behavior is not desired. If BC wasn't an issue, I would probably remove support for optional dependencies altogether, but that's not an option.

> Feel free to re-submit your change with a thorough explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

This is a bug fix. That's the best explanation I can provide. Integration tests don't really make sense in this case. 
The benefit to end users is that Laravel doesn't tell them that perfectly fine code is broken in an unrelated place.

### CODE REVIEW

**Comment by deleugpn** [comment]
If I understood this correctly, you're not really fixing the problem, but just moving it one step away. What if I don't have just 1 optional dependency but actually 2? `array_pop` will only take one element out of the context and now it will fail on the second, right?

**Comment by twistor** [comment]
@GrahamCampbell That's fine. I wouldn't consider it a big change. And, I would definitely consider the misleading error message a bug. But, fixing it in 5.7 first makes more sense anyway.

@deleugpn That is incorrect. The `with` stack is an array of arrays. Each entry is an array of all the arguments. The real code that I paraphrased above actually uses 3 arguments in the factory and this fix works fine.

I think it would help if we looked at the code in its entirety:

```php
    protected function resolve($abstract, $parameters = [])
    {
        $abstract = $this->getAlias($abstract);
        $needsContextualBuild = ! empty($parameters) || ! is_null(
            $this->getContextualConcrete($abstract)
        );

        if (isset($this->instances[$abstract]) && ! $needsContextualBuild) {
            return $this->instances[$abstract];
        }

         // We push on the stack here.
        $this->with[] = $parameters;
        $concrete = $this->getConcrete($abstract);

        // Here is where the exception happens and we skip the cleanup below.
        if ($this->isBuildable($concrete, $abstract)) {
            $object = $this->build($concrete);
        } else {
            $object = $this->make($concrete);
        }

        foreach ($this->getExtenders($abstract) as $extender) {
            $object = $extender($object, $this);
        }

        if ($this->isShared($abstract) && ! $needsContextualBuild) {
            $this->instances[$abstract] = $object;
        }
        $this->fireResolvingCallbacks($abstract, $object);

        $this->resolved[$abstract] = true;

        // This is where the stack is normally cleaned up.
        array_pop($this->with);
        return $object;
    }
```

**Comment by twistor** [comment]
The deeper issue is using `BindingResolutionException` as control flow for an expected case. Refactoring that is a bigger task.

**Comment by taylorotwell** [comment]
I don't plan to change the container behavior at the moment.

**Pull request closed without merging**
