### PR TITLE
[10.x] Remove deprecated interface Rule implementation with ValidationRule in Password rule validation

### PR DESCRIPTION
**Pull request by MSR2012**
This PR intended for removing deprecated `Rule` interface with `ValidationRule` interface in `Password` rule class.

### CODE REVIEW

**Comment by driesvints** [comment]
This is a breaking change unfortunately. Please attempt master, thanks.

**Comment by driesvints** [comment]
yes

**Comment by MSR2012** [comment]
@driesvints How about changing other rule class as well like Can, Enum etc? Should I add those as well?

**Comment by driesvints** [comment]
@MSR2012 currently I don't know if this PR will get accepted by Taylor. I suggest to first try this one, then proceed with other ones.

**Comment by MSR2012** [comment]
ok, thanks for your suggestions

**Pull request closed without merging**
