### PR TITLE
[5.4] Remove asset helper from mix() helper

### PR DESCRIPTION
**Pull request by it-can**
Fix for issue #20164

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm getting really weary of all these mix changes.

**Comment by taylorotwell** [comment]
Actually reverted. I'm not accepting any Mix changes from anyone accept @JeffreyWay for at least a month.

**Comment by it-can** [comment]
Sounds like a good idea

**Comment by devcircus** [comment]
Works perfectly as-is.

**Pull request merged**
