### PR TITLE
[8.x] Add ability to delete pending and/or delayed jobs

### PR DESCRIPTION
**Pull request by paras-malhotra**
This PR adds the ability to delete a pending job from a queue. Right now, if a user has to delete a pending job, the implementation would depend on the queue driver and there's no easy way to do so with the framework. 

I think if the framework directly supports this in the various drivers, it would be easier for packages like Horizon to delete pending jobs from the dashboard and also make it very convenient for Laravel users to do so in development / specific production environment cases.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Is there a great use case for this? How do you access the job ID?

**Comment by paras-malhotra** [comment]
> Is there a great use case for this? How do you access the job ID?

Some use cases are:

1. Forgetting pending jobs from the Horizon dashboard. Horizon saves the job ID in its own sorted sets, so its easy to access. 
2. An example use case could be giving the flexibility to your app's users to "un-queue" long-running jobs (say ETL or analytics jobs). The IDs of the jobs could be stored in DB/cache for these cases while pushing the jobs to the queue (push and pushRaw return the job IDs)
3. Another case could be delayed jobs - say cart abandonment emails scheduled after 2 hours of the abandonment but say the user comes back before the expiry of 2 hours - then you'll probably want to cancel the cart abandonment email. I haven't yet added support to cancel delayed jobs but I can update the PR to do so, as I now realise cancelling delayed jobs might be very useful

**Comment by paras-malhotra** [comment]
I've updated the PR to add support to delete delayed jobs. Both DB and Redis drivers are supported.

**Comment by taylorotwell** [comment]
How do I get the ID of the job if I do `Job::dispatch()->delay(now()->addHours(2))`?

**Comment by taylorotwell** [comment]
Also how would you know if the job is still pending and is cancellable? I think in your cart abandoned example the delayed job itself can check if it still needs to execute and delete itself if it doesn't.

Same with the analytics example. The user cancelling could store a record in the database that the queued job checks at the beginning of its handle method, etc.

All of these situations feel solvable without the complexity and questions around this PR.

**Comment by paras-malhotra** [comment]
> How do I get the ID of the job if I do `Job::dispatch()->delay(now()->addHours(2))`?
I guess you can't do it with a PendingDispatch but you could do this with `Queue::later()`. We could also implement an after callback on PendingDispatch if required.

> Also how would you know if the job is still pending and is cancellable?
I think you could call `deletePending` and if it returns true, it's cancelled. Most of these use cases would probably be "cancel it if already not dispatched" such as the cart abandonment example (don't send the email unless already sent).

> The delayed job itself can check if it still needs to execute and delete itself if it doesn't
Yes, you could do that but I guess it might be more efficient or more clean this way for certain use cases. For instance, if there's a 10% chance of cancellation, it's probably best to cancel it when that 10% event happens rather than check on every job.

Ping me if you change your mind on this. I'd be happy to make any changes if needed.

**Pull request closed without merging**
