### PR TITLE
[4.2] Add support for PHP7 throwables

### PR DESCRIPTION
**Pull request by themsaid**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Pretty sure there are a lot more cases than this to fix. I implemented this on 5.1 and hit more files than this, and had to make some other changes. Unfortunately, it's not contained within one PR.

**Comment by themsaid** [comment]
Have anything in particular in mind? I went throw all the `catch (\Exception $e)` instances and altered the cases where I felt it needs to be altered, but I'm not completely sure if that's enough since there's no way to check.

**Comment by taylorotwell** [comment]
Does the exception handler type hint the base Exception class? I feel like that is where I have ran into problems with this?

**Comment by GrahamCampbell** [comment]
Yes, it does.

**Comment by taylorotwell** [comment]
Yeah I think that is the thing that has given me trouble in the past.

**Comment by bweston92** [comment]
@themsaid `\Illuminate\Exception` needs updating. Just caught me out.

https://github.com/laravel/framework/blob/4.2/src/Illuminate/Exception/ExceptionDisplayerInterface.php#L12

**Comment by GrahamCampbell** [comment]
No, it doesn't. It wasn;t updated on laravel 5.1 and that works just fine. Changing that would be a massive bc break.

**Comment by bweston92** [comment]
Ok well to support PHP 7 `\Throwable` like `TypeError` it can't just catch `\Exception`.

**Comment by GrahamCampbell** [comment]
We just need to be sure we convert errors to exceptions before hitting that code.

**Comment by bweston92** [comment]
@themsaid mind updating, or want me to send PR?

**Comment by izzyp** [comment]
@themsaid 
The L4.2 required package "filp/whoops 1.1.*" doesn't yet support php7. 

Throwing error:

`Type error: Argument 1 passed to Whoops\Exception\Inspector::__construct() must be an instance of Exception, instance of TypeError given, called in /home/vagrant/Code/vendor/filp/whoops/src/Whoops/Exception/Inspector.php on line 80`

Any way around this? Or am i missing something..?

**Pull request merged**
