### PR TITLE
[5.4] Remove unnecessary comment

### PR DESCRIPTION
**Pull request by alexbowers**

### CODE REVIEW

**Comment by taylorotwell** [comment]
We use these throughout the framework.

**Comment by GrahamCampbell** [comment]
They're also pretty useful to distinguish between return void, and not documented yet.

**Comment by sisve** [comment]
Yes... but on a __construct?

**Comment by GrahamCampbell** [comment]
Yes, connect.

**Comment by GrahamCampbell** [comment]
https://3v4l.org/IGGs3

**Comment by alexbowers** [comment]
@GrahamCampbell A constructor should never return anything other than an instance of a class though. Is there anywhere in the framework we directly call `__construct()`, because that seems wrong

**Comment by GrahamCampbell** [comment]
>  A constructor should never return anything other than an instance of a class though.

Wrong, as I proved in that link. It returns nothing.

**Pull request closed without merging**
