### PR TITLE
[8.x] Refactor component attribute bag

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
When using [components](https://laravel.com/docs/7.x/blade#components), I realized that we can only merge attributes with the array
```php
<div {{$attributes->merge(['class' => 'alert alert-'.$type])}}>
```
we cannot pass a collection
```php
<div {{$attributes->merge(collection(['class' => 'alert alert-'.$type]))}}>
```
This PR is a refactoring of `ComponentAttributeBag`

### CODE REVIEW

**Comment by driesvints** [comment]
Can you fix the conflicts?

**Comment by ricardogobbosouza** [comment]
@driesvints fixed

**Comment by taylorotwell** [comment]
I don't really except blanket "refactoring" PRs. What are you improving specifically?

**Comment by ricardogobbosouza** [comment]
@taylorotwell  
With this refactoring we can enjoy many benefits of the collection, not to mention that there is no duplication of code

**Comment by ricardogobbosouza** [comment]
```php
// component.php
class Component extends \Illuminate\View\Component
{
    public function render()
    {
        // works
        $myAttrs = [];

        // not works
        $myAttrs = collection();

        return View::make('component', compact('myAttrs'));
    }
}

// component.blade.php
<span {!! $attributes->merge($myAttrs) !!}></span>
```

**Comment by ricardogobbosouza** [comment]
With this refactoring, how two implementations above would work.

**Pull request closed without merging**
