### PR TITLE
[7.x] New method withSum for sum one or more columns for the relations

### PR DESCRIPTION
**Pull request by Alexmg86**
### Summing Related Models columns
If you want to summarize the columns of results from a relationship without actually loading them and by one request to the database you may use the `withSum` method, which will place a {relation}_{column}_sum column on your resulting models. For example:
```php
$invoices = Invoice::withSum('items:price,price2')->get();
```
You may add the "sum" for multiple relations as well as add constraints to the queries:
```php
use Illuminate\Database\Eloquent\Builder;

$invoices = Invoice::withSum(['items:price', 'goods:price,price2' => function (Builder $query) {
    $query->where('price','>',6);
}])->get();

echo $invoices[0]->items_price_sum;
echo $invoices[0]->goods_price_sum;
echo $invoices[0]->goods_price2_sum;
```
If you're combining `withSum` with a `select` statement, ensure that you call `withSum` after the `select` method:
```php
$invoices = Invoice::select(['id'])->withSum('items:price')->get();

echo $invoices[0]->id;
echo $invoices[0]->items_price_sum;
```
In addition, using the `loadSum` method, you may load a relationship sum columns after the parent model has already been retrieved:
```php
$invoice = Invoice::first();
$invoice->loadSum('items:price');
```
If you need to set additional query constraints on the eager loading query, you may pass an array keyed by the relationships you wish to load. The array values should be Closure instances which receive the query builder instance:
```php
$invoice = Invoice::first();
$invoice->loadSum(['items:price' => function ($query) {
    $query->where('price', '>', 5);
}]);
```
And of course it is all compatible with scopes in models.

---
### Why is this method needed?
Now, when trying to summarize a column in a related model, we get 2 queries in the database. With this method, it all turns into 1 query to the database and there is no need to load extra data.
I often use this in my work and I hope it will be useful to you!

### CODE REVIEW

**Comment by tobyokeke** [comment]
I think this is relevant. I'd like to use it in my work too. @Alexmg86

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by Alexmg86** [comment]
@taylorotwell thank you very much for your reply!
Yes, I checked the method, it works fine, as it is made by analogy with your withCount method. I also wrote tests to test the performance :)
+ I agreed on the database queries with the sql professional for its quality

**Comment by Alexmg86** [comment]
@tobyokeke hi, i created package, you can [try it](https://github.com/Alexmg86/laravel-sub-query) )))

**Pull request closed without merging**
