### PR TITLE
[5.8] Provide a path of the view in compiled view 

### LINKED ISSUE #1480: Provide a way to retrieve blade/generated php paths mappings
To provide Blade debugging in PhpStorm (please see details in the issue https://youtrack.jetbrains.com/issue/WI-26476 ) it's required to have mappings from blade template path to the path of generated PHP file based on given blade template as well as backward mapping.

As far as I can see, there is no such opportunity now. Please correct me if I'm mistaken.

After a little research I've found two possible small changes in illuminate/view repo that resolve our forward/backward mappings problem:

1) Add an option which forces a compiler to provide a path to blade template (or just a name of blade template) in the generated PHP file - it allows us easily retrieve mappings.

2) Generate a name of generated PHP file based on absolute path or just name of blade template (changes in Compiler#getCompiledPath) -
Now filename generation is based on some not standardized path, that can be absolute or relative (like /path/to/template or ../../template or path/../../to/template etc) depending on user choice in the settings, so it's hard for external tooling like PhpStorm realized what path is used for sha1 filename generation and restore mappings.

I didn't see any security reason to obfuscate path mappings, so I decided to file this feature request and ask you for help. Thank you in advance!

### PR DESCRIPTION
**Pull request by bzixilu**
This PR fixes [laravel/ideas#1480](https://github.com/laravel/ideas/issues/1480) by adding the path of the view at the first line of compiled view in order to provide a possibility of Blade debugging in PhpStorm. 

This pull-request is a simplified version of the pull-request filed before with fixed shortcomings: https://github.com/laravel/framework/pull/27412 , @taylorotwell please take a look.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks!

**Comment by mfn** [comment]
@bzixilu this broke templates using declare(strict_types=1), please see https://github.com/laravel/framework/issues/27704

**Comment by bzixilu** [comment]
@mfn oh, I didn't take strict types declaration into account, sorry for that. I'll take a look ASAP, thank you for reporting!

**Comment by screenager** [comment]
Having upgraded to the latest stable PhpStorm, this functionality only works if the path is added on top of the compiled view. It currently appends it to the bottom.

**Comment by bzixilu** [comment]
@screenager just to be sure, whether it was tested with 2019.1 Release or not? 
If so could you please provide the minimized reproducible test case, I'll file the issue for investigation?

**Comment by screenager** [comment]
Tested with 2019.1 indeed
Cache path set to <myproject>/storage/framework/views
Laravel 5.8.8, PHP 7.2.9
Did a "php artisan view:cache" on beforehand
Xdebug 2.6.1

Let me know if you need anything more

**Pull request merged**
