### PR TITLE
[5.0] Return files from Request array

### PR DESCRIPTION
**Pull request by mattmcdev**
Alternative solution for #8137

### CODE REVIEW

**Comment by taylorotwell** [comment]
So what I don't understand is $this->input() already includes files, so why was it not working in the first place?

**Comment by mattmcdonald-uk** [comment]
Because $this->input() doesn't include files.

Although - if it's supposed to, then a simpler fix would just be:

    $input = $this->getInputSource()->all() + $this->query->all() + $this->file();

**Comment by taylorotwell** [comment]
Ah right I looked at it wrong. Nvm.

**Comment by taylorotwell** [comment]
Made a few tweaks and merged. Added tests. :heart:

**Comment by mattmcdonald-uk** [comment]
Lovely :) And best of all, I now understand a tiny bit more about what's actually going on in that scary /vendor folder!

**Comment by GrahamCampbell** [comment]
:)

**Pull request merged**
