### PR TITLE
[7.x] Add where pivot null methods

### PR DESCRIPTION
**Pull request by DougSisk**
Just some basic is/is not null builder methods for pivot columns on BelongsToMany relations.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm not sure this is going to compile correctly? It seems like it's going to compile to a query that checks if a column contains the string "null".

**Comment by DougSisk** [comment]
I switched over to using `whereNull`. I wasn't sure at first it would work with the pivot naming convention, but a quick test on a project shows it as working.

**Comment by DougSisk** [comment]
Unit tests added 👍

**Comment by taylorotwell** [comment]
I think this is still missing some things. Notice in the wherePivot methods we keep track of them and then use them later for other things.

**Pull request merged**
