### PR TITLE
[5.4] Reset format character added to date format validation

### LINKED ISSUE #17642: [5.4] Validation Rule: date_format bug
As the title says, I may be missing something. The scenario is provided below.

# Versions used
> Laravel Version: 5.4.3
> PHP Version: 7.0.15
> Database Driver & Version: MariaDB 10.1.20

# Problem
> The Laravel 'date_format' validation rule on Requests fail on the date '2017-02'. It fails on non leap years when using the month '02' (February).

# Test Data
**Working on the following dates [Validation is successful]**
> 2016-01
> 2016-02
> 2020-02
> 2024-02

**Not working on the following dates [Validation does not match the format Y-m]**
> 2013-02
> 2017-02
> 2021-02

# Steps to Reproduce

**Create a request with the following rule**
> `return ['testDate' => ['bail', required, 'date_format:Y-m']];`

**Next steps**
> Create a sample input form, route, and controller that uses the request created.
> Input the test data provided above.
> Input test data '2017-02'. Expected: Validation Passed, Actual: Does not match the format Y-m

# Other notes
> The validation rule 'date' works properly even on non leap years when using the month '02' (February).
> Tested on Laravel 5.3, same error.

### PR DESCRIPTION
**Pull request by arjasco**
This tiny addition should fix #17642

### CODE REVIEW

**Comment by ntzm** [comment]
Nice one, probably worth adding some tests to demonstrate the problem?

**Comment by themsaid** [comment]
@arjasco can you explain it more?

**Comment by arjasco** [comment]
If the ! is removed the added test will fail. 

There is a problem in DateTime where when formatting by the month it could overflow and give the incorrect month. Adding the ! will reset to the current and then parse the value, which in term produces the correct.

In the PHP docs someone left a comment about 4 years ago describing the same thing.

**Comment by taylorotwell** [comment]
Then just add it to your own date format when you pass it to the validator.

**Comment by arjasco** [comment]
@taylorotwell Appreciate this isn't the most elegant solution and most would probably question why a '!' is prepended in the source unless it's commented. However, adding this to your format won't work because the same format is being used for the comparison: 

```php
return $date && $date->format($parameters[0]) == $value;
```

Therefore when the format is performed if the '!' is there it will reset the date time to your system current and return false.

Check the issue thread again. (#17642) I posted about how now it's February the issue has disappeared. Problem is whenever we fall into a month that doesn't contain 31 days we get an incorrect result. 

Understand this is such a tiny thing, just means you can't do this: 

```php
$this->validate(request(), [
    'date' => 'date_format:Y-m'
]);
```

Without having to change the format to 'Y-m-d' and doing a request merge to change the date input to append '-01' (adding the first day of the month is a work around also)


Also doesn't seem like a widely known issue, so when it happens it's pretty confusing.

**Pull request closed without merging**
