### PR TITLE
[5.5] Better validation response assertions

### PR DESCRIPTION
**Pull request by devinfd**
Not my intention to sound rude but the new assertJsonValidationErrors method has issues.
1. It only asserts against JSON responses.
2. It is not actually doing ```Assert that the response has the given JSON validation errors for the given keys.```

All the test is asserting is that provided keys are in the JSON response. It's possible that the ```errors``` array contains more than just the validation errors. ie: a developer may be adding there own data into the response.

This PR adds the following assertions ```assertHasValidationError, assertHttpValidationError, assertJsonValidationError, assertValidationErrorMissing, assertHttpValidationErrorMissing, assertJsonValidationErrorMissing```.

These tests more closely assert that Laravel is responding with validation errors and allows the user to assert the validation message.

Example
```php
$this->post('/posts')->assertHttpValidationError('body.required', 'The body field is required.');
$this->json('post', '/posts')->assertJsonValidationError('body.required', 'The body field is required.');

$this->post('/posts', ['body' => 'lorem'])->assertHttpValidationErrorMissing('body.required');
$this->json('post', '/posts', ['body' => 'lorem'])->assertJsonValidationErrorMissing('body.required');
```

```assertHasValidationError``` and ```assertValidationErrorMissing``` will determine if the response is HTTP or not and delegate to the appropriate method.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I think the current method does make some sense though? Assert that a given key is in the JSON response error key. I don't think that is only asserts against JSON responses is confusing since JSON is in the method name?

**Comment by devinfd** [comment]
I think the original assertion (which remains in this PR by the way) is fine if you just want to check for the existence of a key in the error array. But like I said it only asserts against json and it’s possible there may be more than just validation errors in there. 

The biggest issue to me is that if I wanted to assert that (for example) something is required in my request, just using the assertJsonValidationErrors doesn’t guarantee me that the actual error I’m getting back is a “field required” validation error. 

Where as, assertHasValidationError($key, $message) will assert that the key exists in the error array, the message associated to that key exists (telling me that me field is required) and Laravel is responding back with a status code appropriate to my request. 

- Devin Dombrowski

**Comment by taylorotwell** [comment]
No plans to merge this in right now. Feel free to Macro into TestResponse.

**Comment by devinfd** [comment]
That’s what I’ve done on my projects. Thanks anyway.

-Devin

**Pull request closed without merging**
