### PR TITLE
[5.1] Register PSR-7 response.

### PR DESCRIPTION
**Pull request by simensen**
The intent is to allow controllers and middleware to typehint against Response and having one injected.

### CODE REVIEW

**Comment by simensen** [comment]
I spent an hour or so trying to figure out how to write a test for this and I wasn't able to figure out how to get an application, register just this one provider to it, create a request, dispatch it, and have get to the point that the controller was being triggered. If there is an example of how to wire up a service provider and make requests against the application/dispatcher after the fact, I'd be happy to add a test for this.

**Comment by GrahamCampbell** [comment]
Hmm, this doesn't look quite right. Surely all our transformer code needs to be updated?

**Comment by barryvdh** [comment]
@GrahamCampbell What would need to be updated? This isn't for transforming anything, but just to be able to typehint a empty response, to use as basis to prepare the actual response, right?

The transorming of the Response already happens here: https://github.com/laravel/framework/blob/36d50ba04f268fda5ed648320ecbf8f5b4f654de/src/Illuminate/Routing/Router.php#L1222-L1223 
But that doesn't care how the Response is created.

**Comment by simensen** [comment]
I was just coming to write a response when I see @barryvdh said exactly what I was going to. Unless I misunderstand @GrahamCampbell's concern/question, I would agree that this is for the purpose of satisfying dependencies for controllers or middleware that expect to receive a Response instance. This will be a good step to making it easier to integrate some of the other PSR-7 controller/middleware variants out there that include a response in the method signature.

**Comment by GrahamCampbell** [comment]
I'm saying we should be creating the response in the same way in both places.

**Comment by barryvdh** [comment]
So you want to use [HttpMessageFactoryInterface](https://github.com/symfony/psr-http-message-bridge/blob/master/HttpMessageFactoryInterface.php) to create a new (empty) PSR-7 Response?

    protected function registerPsrResponse()
    {
        $this->app->bind('Psr\Http\Message\ResponseInterface', function ($app) {
            return (new DiactorosFactory)->createResponse(new Response);
        });
    }

Which would have pretty much the same, but probably be a bit slower?

I would agree that it would make more sense if we would bind any Factory, but right now it's just Diactoros anyways, so would it matter?

**Comment by simensen** [comment]
Yes, I would not think we would want to do it that way, either.

Also, people would be able to bind to another factory if they wanted to, right? That is, if they wanted to use another PSR-7 Response implementation, they could override this? (I'm still a bit new to the Container stuff and Laravel in general, so I could be way wrong on my assumption here)

I also just noticed that neither the bridge nor diactoros are actually required anywhere in either the root composer.json or routing's composer.json. is that to be expected?

If it is acceptable to register these things w/o having them actually be there with the understanding that projects will have to opt-in to requiring them on their own, I'm fine w/ that. If that was an oversight I can send another PR to get those required (or maybe even just suggested?).

**Comment by barryvdh** [comment]
I think it was omitted on purpose. I asked @taylorotwell to add it, because the transforming of the PSR Response to Symfony Response wasn't easily possible without being added to the core like it is now.

The resolving of the Request (and Response) could be in a package, but was provided to make it simpler. I guess Response resolving wasn't added because we just didn't have an actual use case. But if you do have a valid one, I'm +1 for adding this :) 

And the diactoros/bridge is probably not added to keep it a bit more 'light' as PSR-7 isn't yet really much used yet. Same goes for doctrine/guzzle/aws/pusher/ironIO, that are available but you need to manually pull it in. (It would be good to add this in the suggest section though..)
See the http://laravel.com/docs/5.1/requests#psr7-requests section where it's explicitly mentioned that you need to require those packages.

**Comment by barryvdh** [comment]
And yes, people could just register their own bindings for `Psr\Http\Message\ResponseInterface`/`ResponseInterface` to override the Diactoros factory and use their own.

**Comment by franzliedke** [comment]
@simensen :+1: for this pull request.

Fun to see you here, too. :)

**Pull request merged**
