### PR TITLE
[5.2] Fix invalid() and valid() methods. (issue #14646)

### PR DESCRIPTION
**Pull request by carloscarucce**
`invalid()` and `valid()` methods where returning empty arrays when validating multi-dimensional data array

### CODE REVIEW

**Comment by taylorotwell** [comment]
@themsaid can you look at this? I can't follow what this is doing.

**Comment by themsaid** [comment]
Look at this test @taylorotwell 

```php
    public function testInvalidMethod()
    {
        $trans = $this->getRealTranslator();

        $v = new Validator($trans,
            [
                ['name' => 'John'],
                ['name' => null],
                ['name' => '']
            ],
            [
                '*.name' => 'required',
            ]);

        $this->assertEquals($v->invalid(), [
            1 => ['name' => null],
            2 => ['name' => '']
        ]);
    }
```

The problem is with implicit attributes with values, currently to get the invalid attributes we do:

```
return array_diff_key($this->data, $this->messages()->toArray());
```

But in that case the data would look like:

```
[
    0 => ['name' => 'John'],
    1 => ['name' => null],
    2 => ['name' => '']
]
```

While the messages array:

```
[
    '1.name' => [...],
    '2.name' => [...],
]
```

This will lead to no intersection between keys, resulting an empty array.

In the PR he's checking the key that comes before the first dot (`0.name`, `persons.3.name`, etc...) and check for intersection based on that first key since it's the one the $data array knows about.

**Comment by xxnoobmanxx** [comment]
Exactly :)

**Comment by themsaid** [comment]
Maybe you need to add this test @xxnoobmanxx and provide something similar for `valid()` as well.

```
    public function testInvalidMethod()
    {
        $trans = $this->getRealTranslator();

        $v = new Validator($trans,
            [
                ['name' => 'John'],
                ['name' => null],
                ['name' => '']
            ],
            [
                '*.name' => 'required',
            ]);

        $this->assertEquals($v->invalid(), [
            1 => ['name' => null],
            2 => ['name' => '']
        ]);

        $v = new Validator($trans,
            [
                'persons' => [
                    ['first' => 'jon'],
                    ['first' => ''],
                ],
            ],
            [
                'persons.*.first' => 'required',
            ]);

        $this->assertEquals($v->invalid(), [
            'persons' => [
                ['first' => 'jon'],
                ['first' => ''],
            ]
        ]);

        $v = new Validator($trans,
            [
                'name' => ''
            ],
            [
                'name' => 'required',
            ]);

        $this->assertEquals($v->invalid(), [
            'name' => ''
        ]);
    }
```

**Comment by xxnoobmanxx** [comment]
@themsaid Done.

**Pull request merged**
