### PR TITLE
[5.0] Update config.php

### PR DESCRIPTION
**Pull request by stevendesu**
Moved FilterIterator.php above MultiplePcrefilterIterator to fix a fatal error in PHP

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What php version are you using, because I can't replicate this. Have you configured autoloading correctly, because classpreloader should be able to autoload classes as it needs them?

**Comment by stevendesu** [comment]
I'm using PHP version 5.4.36

I'm not certain what configuring there is to do for autoloading. I simply followed the instruction to install laravel directly from their documentation:

 1. Spin up a new server on DigitalOcean or similar VPS hosting with PHP, MySQL, etc. (all dependencies)
 2. Install composer:
    `curl -sS https://getcomposer.org/installer | php`
 3. Convert composer to a global installation:
    `mv composer.phar ~/bin/composer`
    `export PATH=$PATH:~/bin`
 4. Install laravel:
    `composer global require "laravel/installer=~1.1"`
    `export PATH=$PATH:~/.composer/vendor/bin`
 5. Create a new app:
    `laravel new blog`
 6. Attempt to access your new app:
    http://yourserver.com/blog/

Following the steps above (I've tried using a DigitalOcean server and a DreamHost server) I get the following error in the browser:

```
Fatal error: Cannot redeclare class Symfony\Component\Finder\Iterator\FilterIterator in /home/stevendesu/reedsmetals.stevendesu.com/storage/framework/compiled.php on line 15251
```

I did not do anything special to configure autoloading.

To diagnose the issue I started with `grep "class FilterIterator" * -r` and found that the class is only declared in two places: `compiled.php` and a vendor file.

I put a `debug_print_backtrace()` in the vendor file to figure out how it was getting called before `compiled.php` and got the following:

```

#0  include() called at [/home/stevendesu/reedsmetals.stevendesu.com/vendor/composer/ClassLoader.php:412]
#1  Composer\Autoload\includeFile(/home/stevendesu/reedsmetals.stevendesu.com/vendor/symfony/finder/Symfony/Component/Finder/Iterator/FilterIterator.php) called at [/home/stevendesu/reedsmetals.stevendesu.com/vendor/composer/ClassLoader.php:301]
#2  Composer\Autoload\ClassLoader->loadClass(Symfony\Component\Finder\Iterator\FilterIterator)
#3  spl_autoload_call(Symfony\Component\Finder\Iterator\FilterIterator) called at [/home/stevendesu/reedsmetals.stevendesu.com/storage/framework/compiled.php:15124]
#4  require(/home/stevendesu/reedsmetals.stevendesu.com/storage/framework/compiled.php) called at [/home/stevendesu/reedsmetals.stevendesu.com/bootstrap/autoload.php:34]
#5  require(/home/stevendesu/reedsmetals.stevendesu.com/bootstrap/autoload.php) called at [/home/stevendesu/reedsmetals.stevendesu.com/public/index.php:21]
```

Seeing the class was loaded on line 15124 (before 15251) I took a look at this line in `compiled.php`:

```
abstract class MultiplePcreFilterIterator extends FilterIterator
{
```

We were extending the class before declaring it. That led me to hunt for the reason the order was wrong and I wound up in config.php

**Comment by crynobone** [comment]
While I haven't seen this exact errors, but I can confirm that in certain environment (can remember whether locally or production) if A extends B, when you planning to put both under compiles you need to add B above A.

**Comment by GrahamCampbell** [comment]
@crynobone You shouldn't need to. I wrote tests for class preloader a few months ago that show that it'll autoload classes: https://github.com/ClassPreloader/ClassPreloader/blob/master/tests/ClassLoaderTest.php.

**Comment by stevendesu** [comment]
>it'll autoload classes

I think this is the cause of the issue. It autoloaded the `FilterIterator` class then, a few lines later, attempted to declare the `FilterIterator` class.

An alternate solution to moving the `FilterIterator` declaration up, as I did, would be to simply remote it altogether. This way the only declaration is the automatic one and we never redeclare it. However since the purpose of `compiled.php` was to manually declare our classes to take work off of the autoloader and improve performance, I felt like forcing the autoloader to work *within compiled.php* was counterintuitive.

**Pull request merged**
