### PR TITLE
[8.x] Add the password reset URL to the toMailCallback

### PR DESCRIPTION
**Pull request by NilLlisterri**
It is useful to receive the generated reset URL in the callback, because if we want to only change the mail template texts (`ResetPassword::toMailUsing(function($user, $token) {}`) we have to generate it ourselves.

Backwards compatibility is kept, as it is a new parameter.

### CODE REVIEW

**Comment by SquareBeard** [comment]
FYI this is not backwards compatible.
My code broke because I have no `password.reset` route.
It was not an issue before because I was using the toMailCallback.
The fix is easy tho.

**Comment by driesvints** [comment]
@SquareBeard can you send in a pr?

**Comment by SquareBeard** [comment]
I meant "Adapting my code to this change was easy."
Sorry I wasn't clear enough.

**Comment by mpoma** [comment]
Laravel NOVA is not compatible. Please alert to David

**Comment by driesvints** [comment]
I've sent in a PR to revert this: https://github.com/laravel/framework/pull/38711

**Pull request merged**
