### PR TITLE
[php84] Update dependencies

### PR DESCRIPTION
**Pull request by Jubeki**
WIP.

Seems like I missed some constraints for PHPunit 10. I will also update the composer.json files afterwards.

I don't think that `nesbot/carbon:^2` will support PHP 8.4 based on the releases.
(If I remember correctly the Plan is to drop carbon v2 in Laravel 12 right?)

Pull Requests on other repositories:
- https://github.com/pheanstalk/pheanstalk/pull/270
- https://github.com/aws/aws-sdk-php/pull/2995
- https://github.com/jmespath/jmespath.php/pull/84

### CODE REVIEW

**Comment by Jubeki** [comment]
After this PR:

Phpunit 10 - lowest: Errors: 10, Failures: 8, Deprecations: 134
Phpunit 10 - stable: Errors: 9, Failures: 8, Deprecations: 68
Phpunit 11 - lowest: Errors: 10, Failures: 8, Deprecations: 134
Phpunit 11 - stable: Errors: 9, Failures: 8, Deprecations: 68

I assume many errors to be with the lower bounds of some other libraries.

**Comment by taylorotwell** [comment]
Am I supposed to merge this? Just mark as ready for review if so. 👍

**Comment by Jubeki** [comment]
Should be okay to be merged, you can also leave the decision to @driesvints for further review. The final PR #52633 with the PHP8.4 build is still WIP.

**Comment by driesvints** [comment]
Thanks @Jubeki

**Pull request merged**
