### PR TITLE
 Add batch update

### PR DESCRIPTION
**Pull request by mavinoo**
Add batch update feature to laravel core (laravel do not have it by default) with best possible query performance .

### CODE REVIEW

**Review by mavinoo — COMMENTED** [review]
change StyleCI

**Review by mavinoo — COMMENTED** [review]
update StyleCI

**Comment by ludo237** [comment]
What is batch update ? 😕

**Comment by mavinoo** [comment]
@ludo237 how do you update multiple rows with different values at the same time with single query in laravel !? (without using for each loop to update one by one)

**Comment by ludo237** [comment]
@mavinoo certainly not by including a third party package, with no tests at all, inside the core of laravel

**Comment by ludo237** [comment]
Also Laravel provides [mass update](https://laravel.com/docs/5.3/eloquent#updates), you can tweak it for your purposes...

**Comment by mavinoo** [comment]
i wrote it as a package before, but i want to others test it and if it was okay may be it can be added to laravel elequent by default.

in laravel mass update you can only check 1 condition for where statement to do the update but in my package you can check for multiple conditions in where statement and update with different values in  single query.

package example 
https://github.com/mavinoo/updateBatch#example-2

**Comment by ludo237** [comment]
First mass update doesn't have any constraint, you can setup as many where clause as you want and update as many field as you prefer.

Second you source code does not respect the coding style of Laravel, nor pass the basic tests.

Third you cannot pretend to include a third party package inside Laravel without unit tests at all.

Fourth your `updateBatch` method has some weird logic in it, it's too big and it does too much things

**Comment by Dylan-DPC** [comment]
This is a breaking change.

**Comment by masterwto** [comment]
I don't think laravel needs this.
Do not introduce DIRTY code.

**Pull request closed without merging**
