### PR TITLE
[10.x] Custom messages for `Password` validation rule

### PR DESCRIPTION
**Pull request by skauk**
As described in #48866 `Password` validation rule did not support custom messages provided through the validator and had validation messages in code.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Your PR will break applications that have not added the password translation lines to their validation language file.

**Comment by rcknr** [comment]
@taylorotwell This shouldn't be a problem since default translations are provided with the framework in `src/Illuminate/Translation/lang/en/validation.php`.

**Comment by driesvints** [comment]
@rcknr draft PRs aren't reviewed. Please mark this as ready for review if you need one.

**Comment by driesvints** [comment]
@rcknr Press the "ready for review" button 😉

**Comment by rcknr** [comment]
@driesvints Done. To address @taylorotwell's point: validation messages for passwords are part of the framework. One potential problem I see is when somebody has already used a validation message itself as a translation key (not as slug key e.g. `password.letters`). This could be addressed by translating the message before it's processed by the validator. In any case I doubt it was good idea to put these messages into the rule in the first place.

**Comment by ax-gli** [comment]
could someone tell me where the translation happens? Thank you! I have test cases like these, but they no longer work, should I just change it to the error type? laravel will take care of the translation? Thank you! 
image

**Comment by hatchetaustralia** [comment]
> @taylorotwell This shouldn't be a problem since default translations are provided with the framework in `src/Illuminate/Translation/lang/en/validation.php`.

It broke my tests. All g though, easy fix.

**Comment by bradietilley** [comment]
> @taylorotwell This shouldn't be a problem since default translations are provided with the framework in `src/Illuminate/Translation/lang/en/validation.php`.

It broke my tests. All g though, easy fix.

**Pull request merged**
