### PR TITLE
[5.6] composer sort packages

### PR DESCRIPTION
**Pull request by mnabialek**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks.

**Comment by browner12** [comment]
i know we have this in our `composer.json` does that only when you run a `composer require`?

**Comment by mnabialek** [comment]
@browner12 It was introduced when manually changed package name in https://github.com/laravel/framework/pull/21637 - when you manually change `composer.json` packages won't be auto sorted

**Comment by browner12** [comment]
gotcha, thanks @mnabialek

**Pull request merged**
