### PR TITLE
[5.3] Improve the Colletion of operatorForWhere

### PR DESCRIPTION
**Pull request by mark86092**
To avoid firing the switch in a callback every time it is called

### CODE REVIEW

**Comment by JosephSilber** [comment]
I'm not sure the verbosity is worth it, but at the very least you should inline that `data_get` call (and squash your commits).

**Comment by mark86092** [comment]
Yes, nice suggestion. I'll fix it.

After viewing the other function call, I'm not sure the verbosity is worth or not.

**Comment by vlakoff** [comment]
Maybe, this could be lighter if the `$retrieved` intermediary variable was removed.

**Comment by vlakoff** [comment]
How about:
```
$operator = '>=';

return eval("return data_get(\$item, \$key) $operator \$value;");
```
Code quality assessment: :poop:

**Comment by GrahamCampbell** [comment]
> How about:

No way, lol.

**Comment by squigg** [comment]
Some quick tests show that using functions is around 15% faster than hitting the switch every time (1000 iterations on an array of 1000 items).

Using `!=` with the switch seems to be about 8% slower than using `=`, due to it appearing at the end.

If we are sticking with what we have then maybe we should move those ones up the tree, as I think more people would use `!=` and `!==` than `>` `<` etc.

**Comment by vlakoff** [comment]
With the code of this PR, order of operators shouldn't have performance impact, as the switch is executed only once per `where` call.

However, I agree it would be better to put `!=` above `<` etc.

**Comment by squigg** [comment]
Correct, however I was just noting the performance of the switch statement in the current implementation in the master branch, as the only reason this PR might get merged would be for performance improvements.

The powers that be (Taylor) may prefer to slightly optimise the existing switch statement instead :)

**Comment by vlakoff** [comment]
Order of preference:
1) This PR proposal (with operators reordered as discussed above)
2) Current code
2^99) some `eval()` proposal above

**Comment by vlakoff** [comment]
Also maybe `<` and `>` above `<=` and `>=` ?

`<` `>` `<=` `>=`

**Comment by mark86092** [comment]
I change the position of !== and != .

@viqtor, for the `eval` function, the $operator can do evil. I suggest the white list in switch.

**Comment by vlakoff** [comment]
* How about `<` and `>` above `<=` and `>=` ? (`<` `>` `<=` `>=`)
* The `eval()` wasn't serious. (looks like 2^99 wasn't enough to make it clear)

**Comment by taylorotwell** [comment]
Can someone explain the purpose of this?

**Comment by mark86092** [comment]
@taylorotwell, In the original code, the switch is inside the callback, so the `$this-filter` will loop calling the callback, and the switch of operators runs again and again.

So, I  think it is better to move the switch outside the callback, making callback more specific and clean. And gain some performance by reducing loop.

**Comment by vlakoff** [comment]
I'm running some benches.

**Comment by vlakoff** [comment]
Ran some benches, PHP 5.5.
On 1,000,000 iterations I measured skipping the switch saves 0.5 sec.
Basically, the switch itself is pretty fast, and shouldn't be a bottleneck, the `data_get` being quite slower.

**Comment by JosephSilber** [comment]
We really need proper PHP closures!

```php
switch ($operator) {
    default:
    case '=':
    case '==':  return $item ~> data_get($item, $key) == $value;
    case '===': return $item ~> data_get($item, $key) === $value;
    case '<=':  return $item ~> data_get($item, $key) <= $value;
    case '>=':  return $item ~> data_get($item, $key) >= $value;
    case '<':   return $item ~> data_get($item, $key) < $value;
    case '>':   return $item ~> data_get($item, $key) > $value;
    case '<>':
    case '!=':  return $item ~> data_get($item, $key) != $value;
    case '!==': return $item ~> data_get($item, $key) !== $value;
}
```

**Comment by GrahamCampbell** [comment]
HackLang has this. :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: :trollface:

**Comment by mark86092** [comment]
@JosephSilber this is great. JS has arrow function like this

**Comment by GrahamCampbell** [comment]
> JS has arrow function like this

:crying_cat_face:

**Comment by JosephSilber** [comment]
The powers that be just hate us. It's been shot down [again](https://wiki.php.net/rfc/arrow_functions) and [again](https://wiki.php.net/rfc/short_closures).

I sometimes feel like the PHP internals group doesn't even actively use the language :disappointed_relieved:

**Comment by GrahamCampbell** [comment]
Well, https://wiki.php.net/rfc/arrow_functions, isn't shot down yet. The author just never finished writing the RFC.

**Comment by taylorotwell** [comment]
Going to hold off on this for now.

**Pull request closed without merging**
