### PR TITLE
[11.x] Add Guard Parameter Support to Authentication Redirection Logic 

### PR DESCRIPTION
**Pull request by itxshakil**
This PR enhances the `RedirectIfAuthenticated` and `Authenticate` middleware by introducing support for guard parameters in the redirection logic.

These additions allow for more granular control over the redirection process based on the guard used during authentication. It modifies the handle method to accept variable guard(s) parameters and adjusts the `redirectTo` method to utilize these guards when determining the appropriate redirect path.

This feature is handy in applications with multiple guards, enabling distinct redirection paths for different types of authenticated or unauthenticated users.

**Key Changes:**
- Modified the handle method to accept various guard parameters and process them accordingly.
- Updated the `redirectTo` method to include an optional guard parameter, allowing for guard-specific redirection logic.
- Modified the `unauthenticated` method in `Authenticate` to pass the guards array to the `redirectTo` method, ensuring that redirection logic can be customized based on the guards involved in the authentication attempt
- 
**Benefits:**
- Increased flexibility in handling post-authentication redirects for applications using multiple guards.
- Allows for customized redirection paths based on the type of authenticated user, improving the user experience.
- Provides a more dynamic and context-sensitive redirection strategy for unauthenticated users, improving the overall user experience.
- Enhances the middleware's capability to support applications with complex authentication requirements, including those using multiple guards.
- Allows developers to implement guard-specific redirection logic, offering a higher degree of customization for application routing.

### CODE REVIEW

**Comment by itxshakil** [comment]
Additional Discussion on PR: 
https://github.com/laravel/framework/pull/52055
https://github.com/laravel/framework/pull/52058

**Comment by driesvints** [comment]
As said before we cannot make this change on 11.x because of the severe breaking change on the `redirectTo` method. Quite a bit of apps are probably overwriting this one. 

cc @taylorotwell

**Comment by driesvints** [comment]
@itxshakil think we're gonna let this one go for now. Thanks for your efforts 👍

**Comment by itxshakil** [comment]
Thank you for reviewing my PR and for the feedback. I understand the concern about the potential breaking changes.

I appreciate the consideration given to the proposal and the constructive feedback provided.

**Pull request closed without merging**
