### PR TITLE
Show Falsy values in table output for Laravel artisan commands

### PR DESCRIPTION
**Pull request by akiyamaSM**
This PR suggest to users to show the falsy values instead of blank results.

`$this->table($headers, $rows, $style, $columnStyles**, true**);`

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by lk77** [comment]
I think you should handle falsy values before calling ->table method

**Comment by akiyamaSM** [comment]
@lk77 I really don't think so. I normally expect to see false/null without looping over the rows.

**Comment by lk77** [comment]
Well, false/null values will never be displayed, like with `php -r "echo false;echo null;"`

it's the correct behaviour from table. It's an implementation detail that should be handled by the developer when calling ->call method.

**Pull request closed without merging**
