### PR TITLE
Make tests compatible with phpunit 10 and add some minor refactors

### PR DESCRIPTION
**Pull request by MortezaPoussaneh**
Make tests compatible to phpunit 10
Base on phpunit document [setMethods](https://github.com/sebastianbergmann/phpunit/pull/3687) and [at](https://github.com/sebastianbergmann/phpunit/issues/4297) will be removed. I removed these methods so it can be easily possible to use phpunit 10.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please send to 6.x.

**Comment by MortezaPoussaneh** [comment]
It is not working on 6.x because the methods i used are not available on phpuit < 8

**Comment by MortezaPoussaneh** [comment]
Hey @GrahamCampbell can you tell me why this should go to 6.x? I didn't understand why! I had some other improvement base on this one.

**Comment by driesvints** [comment]
@mortenhauberg

**Comment by driesvints** [comment]
@MortezaPoussaneh we'll indeed only be able to provide support for PHPUnit 10 from 8.x and onwards. I saw there were some conflicts on the PR by now. Can you maybe resent this in to 8.x? Thank you for your work 👍

**Comment by MortezaPoussaneh** [comment]
> @MortezaPoussaneh we'll indeed only be able to provide support for PHPUnit 10 from 8.x and onwards. I saw there were some conflicts on the PR by now. Can you maybe resent this in to 8.x? Thank you for your work

Fixed in here https://github.com/laravel/framework/pull/34700

**Pull request closed without merging**
