### PR TITLE
[5.0] Implementation Of ExistanceAwareTrait In Sessions

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/laravel/framework/pull/6243

### CODE REVIEW

**Comment by ibrasho** [comment]
Squash to one commit? : )

**Comment by bisai-oo** [comment]
can you please tell me how to do that?

**Comment by ibrasho** [comment]
`git rebase -i HEAD~6`

Then change the last 5 `pick`s into `squash`s, save.

Force push the changes: `git push -f`

For a more details guide: http://davidwalsh.name/squash-commits-git or https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by bisai-oo** [comment]
i tried this, but i don't think it worked

**Comment by GrahamCampbell** [comment]
Also, you probably shouldn't add an interface, and if you do, it needs to be put in the contracts package.

**Comment by taylorotwell** [comment]
Going to hold off on this for now.

**Pull request closed without merging**
