### PR TITLE
Delete window.Laravel.csrfToken for Laravel#4260

### PR DESCRIPTION
**Pull request by DrowningElysium**
If PR https://github.com/laravel/laravel/pull/4260 is accepted we will no longer need window.Laravel

### CODE REVIEW

**Review by arcanedev-maroc — COMMENTED** [review]
You need to replace it with:

```blade
<meta name="csrf-token" content="{{ csrf_token() }}">
```

**UPDATE:** See the comment below

**Comment by fernandobandeira** [comment]
@arcanedev-maroc Actually the meta is already there so he only need to remove it.

**Comment by arcanedev-maroc** [comment]
You're right @fernandobandeira, i didn't view the whole file 😄

**Comment by devcircus** [comment]
The entire layout file is just boilerplate to help you get started. This snippet was very useful as I use it in practically every app I work on. I always need to add a few more items. 

Seems much easier to delete it you don't want it than to add it...

**Comment by DrowningElysium** [comment]
@devcircus It seemed to me like it was added with not really a good reason behind it, also the docs are telling us to add it as meta but doesn't tell us to add that script part, so why not just make the script take it from the meta tag directly instead?

**Comment by devcircus** [comment]
It makes sense, and I've wondered why it was added as well.

Laravel Spark actually uses window.Spark for the csrf token instead of the meta tag:
```
// from spark-bootstrap.js

window.axios.defaults.headers.common = {
    'X-Requested-With': 'XMLHttpRequest',
    'X-CSRF-TOKEN': Spark.csrfToken
};
```
And ever since I started using Spark, I find myself using a ```window.MyProject``` in everything I build and so the snippet came in very handy.

It's nothing a sublime snippet can't handle though. :)

**Comment by OwenMelbz** [comment]
I also see this being a pain, lots of javascript libraries pull from this namespace, and it provides a convenient place to tack on other data which can be used by JS.

Personally 🔥 this PR :D

**Pull request merged**
