### PR TITLE
[10.x] Allows specifying the name of the stubs to be published

### PR DESCRIPTION
**Pull request by lukeraymonddowning**
Hey all,

This is a small PR that allows you to limit the stubs that are published when running `php artisan stub:publish`.

## Usage

If you only want to publish stubs for migrations, execute `php artisan stub:publish --only=migration`. Any stubs that start with `migration` will be published.

If you omit the name, all stubs will be published as before. If no stubs match the given name, an error will be displayed to the user.

I contributed this because I'm often interested in editing just one stub, and don't want to have to delete all of the stubs that get published into the application. Thought is was a nice little DX improvement.

As always, thank you for your hard work.

Kind Regards,
Luke

### CODE REVIEW

**Comment by devajmeireles** [comment]
Very nice addition! I noticed the command uses `--` for other things, so wouldn't it be better to use `--name`? 

Or even better: `... --only=migration`

**Comment by lukeraymonddowning** [comment]
@devajmeireles I like the `--only` option a lot. Updated 👌

**Comment by utsavsomaiya** [comment]
May be After merging this #49698.

Please update the test case!

**Comment by devajmeireles** [comment]
> May be After merging this #49698.
> 
> Please update the test case!

This pull request was sent before of your. The correct is to do the inverse. Waiting for the merge of this to improve your pull request. I suggest you change your pull request to draft and mark this pull request.

**Comment by utsavsomaiya** [comment]
> > May be After merging this #49698.
> 
> > 
> 
> > Please update the test case!
> 
> 
> 
> This pull request was sent before of your. The correct is to do the inverse. Waiting for the merge of this to improve your pull request. I suggest you change your pull request to draft and mark this pull request.

Okay! I will take care of it.

**Pull request closed without merging**
