### PR TITLE
[5.2] Allow transform a collection within Paginator

### PR DESCRIPTION
**Pull request by jansenfelipe**
Not sure if it's the best way .. But the idea is allow transform a collection within a paging.

``` php
//Currently
$paginator = $taskModel
    ->orderBy($column, $direction)
    ->paginate($limit);

$tasksTransformed = $paginator->getCollection()->transform(function(Task $task)
{
    return [
       'id' => $task->id,
       'name' => $task->name,
       'username' => $task->user->name,
    ];
});

return new LengthAwarePaginator($tasksTransformed, $paginator->total(), $paginator->perPage(), $paginator->currentPage());
```

``` php
//Proposal
return $taskModel
    ->orderBy($column, $direction)
    ->paginate($limit)
    ->transform(function(Task $task)
    {
        return [
            'id' => $task->id,
            'name' => $task->name,
            'username' => $task->user->name,
        ];
    });
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Didn't we call functions like this `pipe` @taylorotwell?

**Comment by JosephSilber** [comment]
See this note in the docs:

> **Note**: Unlike most other collection methods, `transform` modifies the collection itself. If you wish to create a new collection instead, use the `map` method.

So this already works:

```php
$paginator = $taskModel->orderBy($column, $direction)->paginate($limit);

$paginator->getCollection()->transform(function (Task $task) {
    // return transformed item
});

return $paginator;
```

**Comment by taylorotwell** [comment]
Since it can be done using getCollection for now let's stick with that. I fear going down this road will lead to us redefining all of the collection methods on the paginator.

**Comment by jansenfelipe** [comment]
@JosephSilber 

That way, `$paginator` will not contain paging information (total, current, next url ..). 
Will return only the transformed collection.

**Comment by JosephSilber** [comment]
Why would the paginator lose all that information?

**Pull request closed without merging**
