### PR TITLE
[10.x] Stop adding constraints twice on *Many to *One relationships via one()

### PR DESCRIPTION
**Pull request by cosmastech**
@siarheipashkevich reported that constraints are duplicated when being converted from HasMany/HasManyThrough/MorphMany to HasOne/HasOneThrough/MorphOne

This PR will stop adding those constraints twice by employing the `Relation::noConstraint()` method (which was a TIL moment and I must say, is 🔥)

### CODE REVIEW

**Comment by siarheipashkevich** [comment]
@cosmastech will it save additional conditions?

`$this->shifts()->one()->opened()` . `opened` is a scope.

**Comment by cosmastech** [comment]
> @cosmastech will it save additional conditions?
> 
> `$this->shifts()->one()->opened()` . `opened` is a scope.

@siarheipashkevich It should just ignore the constraints. Was the `opened()` scope not applying previously?

**Comment by cosmastech** [comment]
> @cosmastech will it save additional conditions?
> 
> `$this->shifts()->one()->opened()` . `opened` is a scope.

@siarheipashkevich It should just ignore the constraints. Was the `opened()` scope not applying previously?

**Comment by siarheipashkevich** [comment]
@cosmastech please take a look at my comment and log
https://github.com/laravel/framework/pull/46443#issuecomment-1482670858

we can see that the scope has been applied and it's ok

**Comment by cosmastech** [comment]
> @cosmastech please take a look at my comment and log
> 
> https://github.com/laravel/framework/pull/46443#issuecomment-1482670858
> 
> 
> 
> we can see that the scope has been applied and it's ok

The scope is applied after the fact so it should not be a problem.

**Pull request merged**
