### PR TITLE
[10.x] Add getTable in migration stubs 

### PR DESCRIPTION
**Pull request by danieletulone**
During development, it sometimes happens that you change the name of a table,making the mistake of only updating the up method.

I simply added a getTable method.

### CODE REVIEW

**Comment by rojtjo** [comment]
I often create multiple tables in a single migration at the start of a project, this change would require me to either publish & edit the migration stubs or to clean it up by hand.

**Comment by danieletulone** [comment]
@rojtjo Not really.

Actually, if you create a migration using `php artisan make:migration create_products_table` it will create migration file using migration.create.stub.

If you create a single migration file so you can do it using `php artisna make:migration single_migration` and it will use migration.stub that hasn't any Schema template

**Comment by rojtjo** [comment]
Then it might need some tweaking in the `TableGuesser` (which is probably out of the scope of this PR) as it does use the create stub when I call `artisan make:migration create_order_tables`.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
