### PR TITLE
[5.2] Avoid using with()

### PR DESCRIPTION
**Pull request by lucasmichot**
Follows #12220

### CODE REVIEW

**Comment by vlakoff** [comment]
Now that PHP 5.4 is a must, maybe this function should be deprecated?

**Comment by codbox** [comment]
Will this work? 
{code}
  with($instance = new static)->setRawAttributes($attributes);
{code}
when there is an assignment, i think it might not work. 
am having a doubt. 

when i ran the code on php 5.5 
am getting.
{code}
FatalErrorException in Model.php line 3105:
syntax error, unexpected '->' (T_OBJECT_OPERATOR)
{code}

**Comment by codbox** [comment]
When there is an assignment, i think we will still need to use `with`

**Comment by GrahamCampbell** [comment]
> maybe this function should be deprecated?

We could probably just remove it in 5.3.

**Pull request merged**
