### PR TITLE
Adds support for merging multi-dimensional config arrays

### PR DESCRIPTION
**Pull request by gwendolynrose24**
Adds support for merging multi-dimensional config arrays using Laravel array helper functions
@taylorotwell 

Our agency uses this approach in our own service providers to merge per-install variations of module package configurations for our custom, Laravel-powered content management system.

*** P.S.: I've never contributed to anything before, so I apologize in advance if I did anything incorrectly ***

### CODE REVIEW

**Comment by jakethompson-dev** [comment]
@36864 - Sure! 

We have several modules/plugins for our CMS that function as individual packages and include configuration blocks for defining settings such as the nomenclature used for the module throughout the CMS, the icon that appears in the menu, the user capabilities supported, what policies to register for its models, etc. 

We then take each module's config file and merge it into a single "modules" config to facilitate various functions that need to access available modules (without having to explicitly define config keys for each).

One scenario that occurs often, especially with our church clients, is that they refer to a given module by another name. For example, one church may use the term "Messages" or "Media" instead of "Sermons". This label is part of the configuration block for the Sermons module.

So right now, if a client needs that label changed to something else, we have to recreate the entire configuration block for sermons in the app's "config/modules.php" config file. And any time an update is pushed out for the Sermons module that involves a configuration change, we have to apply that change to each app's "sermons" config block, which leaves a lot of room for error.

Having the ability to merge a multi-dimensional configuration block allows us to limit the config values we have to define in each client's app config to only those values that are different than the default values used by the module package itself.

Sorry for the long-winded explanation, but hopefully that makes sense.

**Comment by brunogaspar** [comment]
I believe this was proposed a couple of times (if i remember correctly) and it was proven to cause issues and it is the intended behaviour.
You can do search here, on GitHub, for `mergeConfigFrom` and it will show some of the closed issues and pull requests with the reasons on why it was not a good idea and the issues it was causing.

Furthermore, considering that this is a breaking change, it should target master (5.7) and not 5.6.

**Comment by taylorotwell** [comment]
See above comment.

**Comment by jakethompson-dev** [comment]
@brunogaspar Makes sense, thanks for the feedback!

**Comment by jakethompson-dev** [comment]
Also, @taylorotwell, your framework is awesome. I can't tell you how much it has made life easier for me and my dev team. Thanks for all your hard work!

**Pull request closed without merging**
