### PR TITLE
Passing 404 to view() method

### PR DESCRIPTION
**Pull request by rajankarthiks**
When We pass 404 as the third arugument to the view function, the view is not being rendered.I think that causes problem to render the custom 404 page in the laravel 5 application. Would like to Discuss.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmmm. This pull is wrong as it stands.

**Comment by GrahamCampbell** [comment]
We can't return 200 OK for an error page. This looks like you've missconfigured your server.

**Comment by rajankarthiks** [comment]
Even If We pass 404 as the third arugument from anywhere else in the application or just return a response()->view('users.login',[],404) anywhere the same default 404 page is displayed.

**Comment by GrahamCampbell** [comment]
I can't replicate this.

**Comment by crynobone** [comment]
screen shot 2015-02-18 at 8 49 01 pm

Current code is working as expected.

**Comment by franzliedke** [comment]
@rajankarthiks What exactly do you see? An empty page or the browser's default 404 page? If I remember correctly, some browsers show their default 404 page if the output sent from the server is shorter than a certain threshold. Maybe that's the problem?

**Comment by rajankarthiks** [comment]
I am really sorry guys.. I think it was my server problem.  When I tested it in forge it is working fine. I don't know why it didn't work even though I used homestead.

**Pull request closed without merging**
