### PR TITLE
[7.x] Fix Http::withCookies()

### LINKED ISSUE #31750: Problem with HTTP facade and withCookies() function
Hi,

I have a problem during passing array to withCookies() function of HTTP client facade - Laravel throw an exception:

`InvalidArgumentException {#365
  #message: "cookies must be an instance of GuzzleHttp\Cookie\CookieJarInterface"
  #code: 0
  #file: "D:\Laravel\api\vendor\guzzlehttp\guzzle\src\Middleware.php"
  #line: 31
  trace: { ... }
`

After changing parameter type from array to CookieJarInterface in PendingRequest class:

`public function withCookies(CookieJarInterface $cookies)`

and the CookieJar object is passed, the problem does not occur and everything works fine. Do you know it is Laravel problem or maybe I do something wrong?

### PR DESCRIPTION
**Pull request by SjorsO**
Currently, `Http::withCookies()` has an array typehint. If you give this method an array, it will throw this error: `cookies must be an instance of GuzzleHttp\Cookie\CookieJarInterface`

For reference, [Zttp's withCookies method](https://github.com/kitetail/zttp/blob/master/src/Zttp.php#L115) doesn't have a typehint.

Fixes https://github.com/laravel/framework/issues/31750

### CODE REVIEW

**Comment by SjorsO** [comment]
The CI fails because `--prefer-lowest` installs Guzzle 6.3.0, which contains a bug that was fixed in 6.3.1: https://github.com/guzzle/guzzle/pull/1999

**Comment by driesvints** [comment]
@SjorsO it only fails with this PR so we'd have to update the minimum version in this pr.

**Comment by SjorsO** [comment]
> @SjorsO it only fails with this PR so we'd have to update the minimum version in this pr.

I'm not very familiar with version constraints, would changing `"guzzlehttp/guzzle": "^6.3|^7.0",` to `"guzzlehttp/guzzle": "^6.3.1|^7.0",` fix it?

**Comment by GrahamCampbell** [comment]
> I'm not very familiar with version constraints, would changing "guzzlehttp/guzzle": "^6.3|^7.0", to "guzzlehttp/guzzle": "^6.3.1|^7.0", fix it?

Yes.

**Comment by GrahamCampbell** [comment]
Please update the suggest phpdoc too.

**Comment by SjorsO** [comment]
> Please update the suggest blocks too (in all composer.json files).

I haven't updated the `Console` and `Mail` suggest blocks, because technically they would work with ^6.3.0. Should I update them to ^6.3.1 too?

**Comment by GrahamCampbell** [comment]
Please update all the suggest blocks, so the framework suggests the same version, across all the components.

**Comment by SjorsO** [comment]
> Please update all the suggest blocks, so the framework suggests the same version, across all the components.

I've bumped all the ones I could find. Thanks for your help!

**Review by GrahamCampbell — APPROVED** [review]
Looks good now. 👍

**Comment by taylorotwell** [comment]
Uh, I don't want people to have to use a "CookieJar" - I just want to be able to pass an array.

**Comment by SjorsO** [comment]
@taylorotwell If you give this method an array Guzzle will throw an exception. Which means that with the current type-hint, this method is unusable.

ZTTP uses this method to [re-use cookies between requests](https://github.com/kitetail/zttp/blob/9de93496597a30e0efd8642ff1a9c9c6c1bc7fcf/tests/ZttpTest.php#L509). `$response->cookies()` returns a `CookieJar`.

**Comment by gocanto** [comment]
@SjorsO you might want to accept the `array` as an argument and build the `jar` within the given method. :) 

ref: https://github.com/guzzle/guzzle/blob/master/src/Cookie/CookieJar.php#L25

**Comment by SjorsO** [comment]
> @SjorsO you might want to accept the `array` as an argument and build the `jar` within the given method. :)
> 
> ref: https://github.com/guzzle/guzzle/blob/master/src/Cookie/CookieJar.php#L25

I thought about using `CookieJar::fromArray($array, $domain)`, but you don't have the `$domain` when this method is called, so it gets kind of tricky.

**Comment by driesvints** [comment]
Taylor pushed a new commit for this: https://github.com/laravel/framework/commit/36d783ce8dbd8736e694ff60ae66e542c62411c3

**Pull request closed without merging**
