### PR TITLE
[5.6] Phpdoc small fix in Auth/Access/Response 🙃

### PR DESCRIPTION
**Pull request by sevastyanovio**
Phpdoc small fix in Auth/Access/Response.

### CODE REVIEW

**Comment by sisve** [comment]
This is obviously wrong.

> The __toString() method allows a class to decide how it will react when it is treated like a string. For example, what echo $obj; will print. This method must return a string, as otherwise a fatal E_RECOVERABLE_ERROR level error is emitted.

Source: https://secure.php.net/manual/en/language.oop5.magic.php

The __toString method will _never_ return null.

https://3v4l.org/q1vMQ

**Comment by a-komarev** [comment]
Completely agree with @sisve. `__toString` method must return empty string instead of null.

**Comment by sevastyanovio** [comment]
@sisve  I this case better to set `string|exception`, because $this->message can be `null`

**Comment by a-komarev** [comment]
Exception is not a return type.

**Comment by sevastyanovio** [comment]
Why not? Exception is class name and it's valid to set it as return type. https://docs.phpdoc.org/references/phpdoc/types.html

**Comment by a-komarev** [comment]
Because it's not returning in this case, it should be in `@throws` tag.

**Comment by a-komarev** [comment]
I've found one more thing about Exceptions:

>  You cannot throw an exception from within a __toString() method. Doing so will result in a fatal error. 

Source: https://secure.php.net/manual/en/language.oop5.magic.php#object.tostring

**Comment by devcircus** [comment]
It was correct in its original form. __toString can't throw an exception. It will result in a fatal error according to php.net. The method returns a string or emits a fatal error.

**Pull request merged**
