### PR TITLE
[6.x] Add support for configuring redis sentinel

### PR DESCRIPTION
**Pull request by ganeshkarki**
As requested in https://github.com/laravel/ideas/issues/395 added redis sentinel configuration support.

Now user can configure the redis sentinel by updating`database.php` like below:
```
    'redis' => [
       ...
        'sentinel' => [
            'options' => [
                'replication' => 'sentinel',
            ],

            'connection_name1' => [
                [
                    'scheme' => 'tcp',
                    'host' => '127.0.0.1',
                    'port' => '26379',
                    'timeout' => 0.6,
                    'read_write_timeout' => 2,
                    'throw_errors' => true
                ],
                [
                     'scheme' => 'tcp',
                    'host' => '127.0.0.1',
                    'port' => '26379',
                    'timeout' => 0.6,
                    'read_write_timeout' => 2,
                    'throw_errors' => true
                ],
                [
                    'scheme' => 'tcp',
                    'host' => '127.0.0.1',
                    'port' => '26379',
                    'timeout' => 0.6,
                    'read_write_timeout' => 2,
                    'throw_errors' => true
                ],

                'options' => [
                    'service' => 'app',
                    'replication' => 'sentinel',

                    'parameters' => [
                        'password' => ''
                        'database' => 0,
                    ],
                ],
            ],
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
Doesn't support PHPRedis? There are no changes to that connector?

**Comment by ganeshkarki** [comment]
No currently this PR, doesn't support PHPRedis. 

Honestly, I am not familiar with PHPRedis much so can't contribute more.
Based on this https://github.com/phpredis/phpredis/pull/851 it looks soon they will have support then, we can integrate similar to this PR.

So this PR, kind of only support predis configuration support.

**Comment by driesvints** [comment]
@ganeshkarki Predis isn't maintained anymore so I don't know if it still makes much sense to add support for this. Predis atm doesn't supports Redis 5 fully for example.

Also: the pr you link to has been open for over 3 years already. Maybe we should wait with all this until they've merged support for it.

There's also https://github.com/laravel/framework/pull/30723 which I'm working on but I'm not sure if it has Sentinel support.

**Comment by taylorotwell** [comment]
I agree it doesn't make sense to do this on Predis since it is unmaintained at the moment.

**Pull request closed without merging**
