### PR TITLE
[11.x] Enhancing redirect logic in `RedirectIfAuthenticated` middleware by passing the `$guard`

### PR DESCRIPTION
**Pull request by maartenpaauw**
> [!CAUTION]
> There's a possibility that this enhancement could lead to breaking changes for projects where developers have extended the `RedirectIfAuthenticated` middleware and overwritten the `redirectTo` method, as it's protected. However, the likelihood of this breaking change affecting existing projects is low.

## Summary

This pull request introduces a significant enhancement to the `RedirectIfAuthenticated` middleware in Laravel 11, offering more flexibility and customization in redirecting logged-in users based on their authentication guard. The current implementation limits redirection based on the `Request $request`, but with this enhancement, developers can tailor redirection based on specific guards, empowering them to create more dynamic and context-aware applications.

## Implementation Details

With this pull request, the `RedirectIfAuthenticated` middleware will now accept a callback function with `?string $guard` as the second parameter, allowing developers to define custom redirection logic based on the authenticated guard. Here's how it works:

```php
$middleware->redirectUsersTo(static function (Request $request, ?string $guard): string {
    return match ($guard) {
        'admins' => Dashboard::getUrl(panel: 'administrator'),
        'market_vendors' => Dashboard::getUrl(panel: 'market-vendor'),
        default => '/dashboard',
    };
});
```

In this example, the callback receives the current request and the guard name. Developers can then use a `match` expression to determine the appropriate redirect URL based on the guard. This enhancement enables more granular control over user redirection, facilitating better user experiences and application flows.

### CODE REVIEW

**Comment by maartenpaauw** [comment]
@taylorotwell Would you be open to reopening this pull request and merging it to `master` rather than `11.x`? I firmly believe that this code adds considerable value. Even if the feature must wait for the next major release.

**Comment by axlon** [comment]
@maartenpaauw Fairly certain your comment won't be read as the PR has been closed. FWIW I 100% agree that this should be added.

My current workaround is keeping a custom `Handler` class in our app (10.x style) and binding it in the container, its workable but really would prefer if the new application style allowed for the same functionality 🙂

**Comment by maartenpaauw** [comment]
Hi @driesvints, I'm unsure if it's appreciated to tag other core maintainers in PRs, but both myself and others are curious if this feature could be considered for inclusion in the next major release? I believe this code adds significant value.

**Comment by AndrewMast** [comment]
This would have been really helpful. Don't get why the `$guard` isn't passed. `Auth::guard()` won't work as it directly grabs `Auth::getDefaultDriver()`, which pulls directly from the config. It may be a "breaking change", but as this ~feature~ change to `RedirectIfAuthenticated` is recent, I feel like this should be added.

**Pull request closed without merging**
