### PR TITLE
[5.7] Make use of a test listener

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Use a test listener instead of `m::close()` in every test

### CODE REVIEW

**Comment by svenluijten** [comment]
Wasn't this already shot down in #25972?

**Comment by MichaelDeBoey** [comment]
@svenluijten It was because the PR was doing to much (and got too big), so I split it up into multiple parts

**Comment by mfn** [comment]
👎  the implicitness is confusing.

The next developer comes around and tries to add them in addition to the listener because "he doesn't see where it's called" (although it works).

I think a single-top level `tearDown` would be more clear instead of all the ones but I assume there's reason we don't have this?

**Comment by MichaelDeBoey** [comment]
I could create a new parent TestClass for all tests too if that solution seems the better way

**Comment by taylorotwell** [comment]
The tests are fine.

**Pull request closed without merging**
