### PR TITLE
Add hydrateWith to hydrate models and their relations

### PR DESCRIPTION
**Pull request by dariusj18**
Create method to assist in hydrating models and their relations.

laravel/ideas#1032

New PR based off master.

### CODE REVIEW

**Comment by dariusj18** [comment]
I think it would be nice if there was some ability to pass in a function similar to the `with` method to allow for custom login.  This would also help with any custom relation types, but I am not sure the best way to accomplish this.  A feature that would assist this and many other use cases would be if relations has some way to declare if they return single or multiple records.  Then we wouldn't need to sniff for the Relation type, we could perform the logic based on the relation's exposed properties.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by dariusj18** [comment]
Are there points in the framework to make it easy to add this functionality to the Eloquent Builder?

Currently the only way I know how to do it is to override the `newEloquentBuilder` method of a root Model class (one that is extended by every other model that is related to another model) and create ones own Builder class with the `hydrateWith` function extending the Eloquent Builder.  This isn't too much but it certainly limits the ability for multiple packages to coexist.

**Comment by IgorGaming** [comment]
> Are there points in the framework to make it easy to add this functionality to the Eloquent Builder?
> 
> Currently the only way I know how to do it is to override the `newEloquentBuilder` method of a root Model class (one that is extended by every other model that is related to another model) and create ones own Builder class with the `hydrateWith` function extending the Eloquent Builder. This isn't too much but it certainly limits the ability for multiple packages to coexist.

Yes, use `macro()`. It is a method in [Illuminate/Support/Traits/Macroable](https://laravel.com/api/master/Illuminate/Support/Traits/Macroable.html) trait.
Something like that:
```
// App\Providers\AppServiceProvider.php
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;

public function register() {
 EloquentBuilder::macro("hydrateWith", function(array $items, array $with = []) {
 // your code
 });
}
```

**Comment by dariusj18** [comment]
Ok, I see now that it doesn't have the trait but it does have the methods to do macros.

**Comment by kobeyy** [comment]
I've developed a similar macro that does the same without needing to specify the relations.

```
Builder::macro('hydrateWithRelations', function (array $items): Model|Collection {
    /** @var Builder $this */
    $instance = $this->newModelInstance();
    if (array_is_list($items)) {
        $hasManyModels = [];
        foreach ($items as $modelAttributes) {
            $hasManyModels[] = $instance::class::hydrateWithRelations($modelAttributes);
        }
        $instance = $instance->newCollection($hasManyModels);
    } else {
        foreach ($items as $field => $value) {
            if ($instance->isRelation($field)) {
                /** @var Model $relationClass */
                $relationClass = $instance->{$field}()->getRelated()::class;
                $relation = $relationClass::hydrateWithRelations($value);
                $instance->setRelation($field, $relation);
            } else {
                $instance->forceFill([$field => $value]);
            }
        }
    }
    return $instance;
});
 ```
        
use case:
```
$userWithPosts = User::with(['posts'])->find(1);
$json = $userWithPosts->toJson();

$hydratedUser = User::hydrateWithRelations(json_decode($json));

```

Could be a nice addition to laravel but not sure if it is PR worthy.

**Comment by kbzone** [comment]
I was working all morning trying to solve this problem with personal methods, until I found your script by chance. I tried it and it worked like a charm.

Kudos for @kobeyy , thank you so much!!

**Pull request closed without merging**
