### PR TITLE
[10.x] Replace paths with proper namespaces when autoloading commands & events

### LINKED ISSUE #47377: Console commands aren't loaded #47327
### Laravel Version

10.13.2

### PHP Version

8.1.17

### Database Driver & Version

_No response_

### Description

after update to laravel 10.13.2 my console commands are not loaded

### Steps To Reproduce

my composer.json
```
"autoload": {
        "psr-4": {
            "App\\": "app/App/",
            "Domain\\": "app/Domain/",
           .....
```
due to PR #47327 now Kernel load is trying to load App\App\Console\Commands\MyCommand.php that is a wrong namespace

MyCommand.php file is in app/App/Console/Commands folder and in the App\Console\Commands namespace

### PR DESCRIPTION
**Pull request by calebdw**
Hello!

Fixes #47377, command autoloading now uses the composer autoload classmap to resolve the class instead of parsing the filename and trying to make assumptions that work for everyone.

Thanks!

### CODE REVIEW

**Comment by taylorotwell** [comment]
What if they aren't class mapped? Wouldn't every class be mapped only if you run `dump-autoload --optimize`?

**Comment by CalebDW** [comment]
Ah, I didn't think of that (I have optimize turned on by default). I updated to a solution similar to the original but replace the paths with the actual namespace definitions from `composer.json`

I also updated the event autoloading to be consistent.

**Comment by CalebDW** [comment]
Any idea why the Windoze virus is failing with an empty array? The test works fine on Linux

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
