### PR TITLE
Fixing phpdoc across several files

### PR DESCRIPTION
**Pull request by joaumg**
Fixing spacing between param in all phpdocs.

Used some regex: 

``` php
   @param\s\S|@param\s{3,}|@param\s{2}\S*\s\S|@param\s{2}\S*\s{3,}
```

Which can be useful.
Explanation:

``` shell
@param\s\S # fetch params that have only one space between @param and the param type.
@param\s{3,} # fetch all that have more than two spaces between @param and the param type.
@param\s{2}\S*\s\S # fetch all that have only one space after the param type.
@param\s{2}\S*\s{3,} # fetch all that have more than two spaces after the param type.
```

It still fetches `* @param mixed\n`, in 6 files:
[src/Illuminate/Contracts/Cookie/QueueingFactory.php#L10](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Contracts/Cookie/QueueingFactory.php#L10)
[src/Illuminate/Contracts/Foundation/Application.php#L26](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Contracts/Foundation/Application.php#L26)
[src/Illuminate/Cookie/CookieJar.php#L108](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Cookie/CookieJar.php#L108)
[src/Illuminate/Foundation/Application.php#L434](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Application.php#L434)
[src/Illuminate/Support/Facades/Facade.php#L41](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Support/Facades/Facade.php#L41)
[src/Illuminate/Support/helpers.php#L443](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Support/helpers.php#L443)

Maybe the regex can be bettered ignoring variadic functions and be added into the build process.

Anyway, what called my attention was the lack of return type here: [src/Illuminate/Database/Eloquent/Relations/MorphTo.php#L150](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Relations/MorphTo.php#L150)

Thanks for the awesome framework. John.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Dupicate.

**Comment by GrahamCampbell** [comment]
It's impossible for us to do a branch merge 5.1->5.2 after merging this.

**Comment by GrahamCampbell** [comment]
I will at somepoint be actually fixing the phpdoc though, once I write the code on StyleCI.

**Comment by GrahamCampbell** [comment]
Your PR already conflicted with 5.1 atm anyway, which is a bit ironic. ;)

**Comment by joaumg** [comment]
I was amused that simple changing the phpdoc could make a conflict...
So I went into the bash:
```shell
joaumg :: ~ » git clone https://github.com/laravel/framework.git laravel_framework
Cloning into 'laravel_framework'...
remote: Counting objects: 81160, done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 81160 (delta 38), reused 0 (delta 0), pack-reused 81072
Receiving objects: 100% (81160/81160), 19.05 MiB | 1.16 MiB/s, done.
Resolving deltas: 100% (52081/52081), done.
Checking connectivity... done.
joaumg :: ~ » cd laravel_framework 
joaumg :: ~/laravel_framework  on 5.1» composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing paragonie/random_compat (1.1.0)
    Loading from cache

  - Installing nikic/php-parser (dev-master 3360288)
    Cloning 33602889c1dbf9087d6b715aa90e95e2a3fc058e

  - Installing classpreloader/classpreloader (dev-master 4257542)
    Cloning 4257542255b04ea4a7d844c61453987ba313daf6

  - Installing danielstjules/stringy (1.x-dev 4749c20)
    Cloning 4749c205db47ee5b32e8d1adf6d9aff8db6caf3b

  - Installing doctrine/inflector (dev-master 90b2128)
    Cloning 90b2128806bfde671b6952ab8bea493942c1fdae

  - Installing jeremeamia/superclosure (dev-master e0cd6ad)
    Cloning e0cd6ada6f3135598fbabaae9edf25777700ea61

  - Installing league/flysystem (dev-master 5e77b62)
    Cloning 5e77b62a894b4c8f1b3bd550447292482ed8b50f

  - Installing psr/log (dev-master 9e45edc)
    Cloning 9e45edca52cc9c954680072c93e621f8b71fab26

  - Installing monolog/monolog (dev-master 7d20351)
    Cloning 7d20351afc85aa23c5795309c9984a1e93d81c27

  - Installing mtdowling/cron-expression (v1.0.4)
    Loading from cache

  - Installing symfony/translation (2.7.x-dev e4ecb9c)
    Cloning e4ecb9c3ba1304eaf24de15c2d7a428101c1982f

  - Installing nesbot/carbon (1.21.0)
    Loading from cache

  - Installing jakub-onderka/php-console-color (0.1)
    Loading from cache

  - Installing jakub-onderka/php-console-highlighter (v0.3.2)
    Loading from cache

  - Installing dnoegel/php-xdg-base-dir (0.1)
    Loading from cache

  - Installing symfony/var-dumper (2.7.x-dev 72bcb27)
    Cloning 72bcb27411780eaee9469729aace73c0d46fb2b8

  - Installing symfony/console (2.7.x-dev 16bb1cb)
    Cloning 16bb1cb86df43c90931df65f529e7ebd79636750

  - Installing psy/psysh (v0.6.1)
    Loading from cache

  - Installing swiftmailer/swiftmailer (5.x-dev 6522539)
    Cloning 6522539daf0a7bdada1cc2dccb7ec37dc0712136

  - Installing symfony/css-selector (2.7.x-dev abb4771)
    Cloning abb47717fb88aebd9437da2fc8bb01a50a36679f

  - Installing symfony/dom-crawler (2.7.x-dev b33593c)
    Cloning b33593cbfe1d81b50d48353f338aca76a08658d8

  - Installing symfony/finder (2.7.x-dev a06a0c0)
    Cloning a06a0c0ff7db3736a50d530c908cca547bf13da9

  - Installing symfony/event-dispatcher (2.8.x-dev a5eb815)
    Cloning a5eb815363c0388e83247e7e9853e5dbc14999cc

  - Installing symfony/http-foundation (2.7.x-dev 3136140)
    Cloning 31361409b4aa6a1694fc376b790d98b0f14e0281

  - Installing symfony/debug (2.7.x-dev 0dbc119)
    Cloning 0dbc119596f4afc82d9b2eb2a7e6a4af1ee763fa

  - Installing symfony/http-kernel (2.7.x-dev 469d250)
    Cloning 469d250b5f1021cb02d13c344f6318eeab2722a0

  - Installing symfony/process (2.7.x-dev f629098)
    Cloning f6290983c8725d0afa29bdc3e5295879de3e58f5

  - Installing symfony/routing (2.7.x-dev 7450f61)
    Cloning 7450f6196711b124fb8b04a12286d01a0401ddfe

  - Installing vlucas/phpdotenv (1.1.x-dev 0cac554)
    Cloning 0cac554ce06277e33ddf9f0b7ade4b8bbf2af3fa

  - Installing mtdowling/jmespath.php (2.2.0)
    Loading from cache

  - Installing guzzlehttp/promises (dev-master b1e1c0d)
    Cloning b1e1c0d55f8083c71eda2c28c12a228d708294ea

  - Installing psr/http-message (dev-master 85d6369)
    Cloning 85d63699f0dbedb190bbd4b0d2b9dc707ea4c298

  - Installing guzzlehttp/psr7 (1.2.1)
    Loading from cache

  - Installing guzzlehttp/guzzle (dev-master a21d3cc)
    Cloning a21d3ccb7ea39a5256079adaa7f0901fde02a5b0

  - Installing aws/aws-sdk-php (3.10.1)
    Loading from cache

  - Installing iron-io/iron_core (1.0.0)
    Loading from cache

  - Installing iron-io/iron_mq (4.x-dev 3302ad9)
    Cloning 3302ad9be1a532ed2e413a082e251ed128816f37

  - Installing hamcrest/hamcrest-php (v1.2.2)
    Loading from cache

  - Installing mockery/mockery (0.9.4)
    Loading from cache

  - Installing pda/pheanstalk (dev-master ba8c8b1)
    Cloning ba8c8b1c3265d4a925864bfffe04c806c3364803

  - Installing doctrine/instantiator (dev-master 8e884e7)
    Cloning 8e884e78f9f0eb1329e445619e04456e64d8051d

  - Installing sebastian/recursion-context (dev-master 994d4a8)
    Cloning 994d4a811bafe801fb06dccbee797863ba2792ba

  - Installing sebastian/exporter (dev-master f88f893)
    Cloning f88f8936517d54ae6d589166810877fb2015d0a2

  - Installing sebastian/diff (dev-master 6899b3e)
    Cloning 6899b3e33bfbd386d88b5eea5f65f563e8793051

  - Installing sebastian/comparator (dev-master 937efb2)
    Cloning 937efb279bd37a375bcadf584dec0726f84dbf22

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Loading from cache

  - Installing phpspec/prophecy (dev-master 4f9b1ea)
    Cloning 4f9b1eaf0a7da77c362f8d91cbc68ab1f4718d62

  - Installing sebastian/environment (dev-master 6324c90)
    Cloning 6324c907ce7a52478eeeaede764f48733ef5ae44

  - Installing phpunit/php-text-template (1.2.1)
    Loading from cache

  - Installing phpunit/php-timer (dev-master 3e82f4e)
    Cloning 3e82f4e9fc92665fafd9157568e4dcb01d014e5b

  - Installing sebastian/version (1.0.6)
    Loading from cache

  - Installing sebastian/global-state (1.1.1)
    Loading from cache

  - Installing symfony/yaml (dev-master e594d90)
    Cloning e594d90fba4e4cddc146bdd3907126b1d74d7316

  - Installing phpunit/phpunit-mock-objects (2.3.x-dev ac8e7a3)
    Cloning ac8e7a3db35738d56ee9a76e78a4e03d97628983

  - Installing phpunit/php-token-stream (dev-master cab6c6f)
    Cloning cab6c6fefee93d7b7c3a01292a0fe0884ea66644

  - Installing phpunit/php-file-iterator (dev-master 6150bf2)
    Cloning 6150bf2c35d3fc379e50c7602b75caceaa39dbf0

  - Installing phpunit/php-code-coverage (2.2.x-dev eabf68b)
    Cloning eabf68b476ac7d0f73793aada060f1c1a9bf8979

  - Installing phpunit/phpunit (4.8.x-dev d82e69c)
    Cloning d82e69c1b34337eae1628c5e2e3b01d2082c4aa9

  - Installing predis/predis (dev-master 6bc1a38)
    Cloning 6bc1a38123f61efde92d8b4a73adabf168e09442

paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-copy (Allows you to use Copy.com storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing videlalvaro/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
symfony/translation suggests installing symfony/config ()
symfony/var-dumper suggests installing ext-symfony_debug ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
aws/aws-sdk-php suggests installing doctrine/cache (To use the DoctrineCacheAdapter)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
predis/predis suggests installing ext-phpiredis (Allows faster serialization and deserialization of the Redis protocol)
Writing lock file
Generating autoload files
joaumg :: ~/laravel_framework  on 5.1» phpunit 
PHPUnit 4.7.3 by Sebastian Bergmann and contributors.

Runtime:	PHP 5.6.15-1+deb.sury.org~trusty+1
Configuration:	/home/joaumg/laravel_framework/phpunit.xml

.............................................................   61 / 1693 (  3%)
.............................................................  122 / 1693 (  7%)
.............................................................  183 / 1693 ( 10%)
.............................................................  244 / 1693 ( 14%)
.............................................................  305 / 1693 ( 18%)
.............................................................  366 / 1693 ( 21%)
.............................................................  427 / 1693 ( 25%)
.............................................................  488 / 1693 ( 28%)
.............................................................  549 / 1693 ( 32%)
.............................................................  610 / 1693 ( 36%)
.............................................................  671 / 1693 ( 39%)
.............................................................  732 / 1693 ( 43%)
.............................................................  793 / 1693 ( 46%)
.............................................................  854 / 1693 ( 50%)
.........................................................E...  915 / 1693 ( 54%)
.............................................................  976 / 1693 ( 57%)
............................................................. 1037 / 1693 ( 61%)
............................................................. 1098 / 1693 ( 64%)
............................................................. 1159 / 1693 ( 68%)
............................................................. 1220 / 1693 ( 72%)
............................................................. 1281 / 1693 ( 75%)
............................................................. 1342 / 1693 ( 79%)
............................................................. 1403 / 1693 ( 82%)
............................................................. 1464 / 1693 ( 86%)
............................................................. 1525 / 1693 ( 90%)
............................................................. 1586 / 1693 ( 93%)
............................................................. 1647 / 1693 ( 97%)
..............................................

Time: 8.49 seconds, Memory: 66.50Mb

There was 1 error:

1) EncrypterTest::testOpenSslEncrypterCanDecryptMcryptedData
Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128'

/home/joaumg/laravel_framework/src/Illuminate/Encryption/McryptEncrypter.php:36
/home/joaumg/laravel_framework/tests/Encryption/EncrypterTest.php:86

FAILURES!
Tests: 1693, Assertions: 3868, Errors: 1.
joaumg :: ~/laravel_framework  on 5.1» php -v                                                                                                                              2 ↵
PHP 5.6.15-1+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

```

What I'm missing ?

**Pull request closed without merging**
