### PR TITLE
[9.x] Back porting #47838

### PR DESCRIPTION
**Pull request by timacdonald**

### CODE REVIEW

**Comment by realtebo** [comment]
Please, merge into v9, not only into v10 ASAP.

**Review by driesvints — APPROVED** [review]

**Comment by ian-nisbet** [comment]
Will this be tagged soon, so that we can remove the temp workaround from composer.json ?

"symfony/http-foundation": "6.2",

**Comment by GrahamCampbell** [comment]
> "symfony/http-foundation": "6.2",

This is not a good work around. I would highly recommend not using 6.2.0. Indeed, this foundation package is not really related to this issue. You should instead pin `symfony/psr-http-message-bridge` to 2.2.0.

**Comment by driesvints** [comment]
I'll make sure we get this out today.

**Pull request merged**
