### PR TITLE
[5.3] Add DispatchesEvents trait.

### PR DESCRIPTION
**Pull request by gabrielkoerich**
Just like the DispatchesJobs trait.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Wasn't the dispatches jobs trait removed in faviour of just calling dispatch?

**Comment by gabrielkoerich** [comment]
Oh, didn't know about that.

**Comment by taylorotwell** [comment]
I would just use the `event` helper personally. It solves the same problem.

**Comment by GrahamCampbell** [comment]
> I would just use the event helper personally. It solves the same problem.

Yes, totally. That's what i was getting at when I mentioned the dispatch method.

**Pull request closed without merging**
