### PR TITLE
Add support for FTP adapter in filesystem

### PR DESCRIPTION
**Pull request by garygreen**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You forgot to add this to the composer suggest blocks.

**Comment by franzliedke** [comment]
Also, @garygreen, can you send a PR changing [this line](https://github.com/franzliedke/laravel/blob/c822db1f5bee1f8cb48d3ff2fd459a51159b00a5/config/filesystems.php#L14) in the laravel/laravel repo?

**Comment by Anahkiasen** [comment]
@GrahamCampbell Doesn't the FTP adapter come with Flysystem itself?

**Comment by GrahamCampbell** [comment]
@Anahkiasen Maybe. If it does, ignore me. ;)

**Comment by garygreen** [comment]
Yeah i was going to do a PR for the Laravel config stuff. FTP is part of Flysystem already but just not supported by Laravel's filesytem wrapper. Now you can do like `Storage::disk('ftp')->has('somefile.txt')`

**Pull request merged**
