### PR TITLE
[10.x] Add an option to specify the default path to the models directory for `php artisan model:prune`

### PR DESCRIPTION
**Pull request by dbhynds**
When running `php artisan model:prune`, the `PruneCommand` hard codes the model directory to be `app_path('Models')`. Our app uses a different naming convention. As a result, our models are kept in a different directory. We recently upgraded from php 8.1 to 8.3 and when we did, this command started throwing an `Symfony\Component\Finder\Exception\DirectoryNotFoundException` every time we run `php artisan model:prune`. We could use the `--model` option to specify an individual model, but that gets unwieldy if we're using this on more than one model.

We put a temporary workaround in place that extends this command and modifies the `getDefaultPath()` method to return the one we need, but it seemed to me like Laravel shouldn't assume that all apps would use a `Models` directory.

This PR adds a `--path` option to the command which allows users to specify which app path they would like to use. The option value defaults to `Models` to maintain backwards compatibility.

Usage example:

```
php artisan model:prune --path="CustomModelPath"
```

I eyeballed the existing automated tests to try to add one here, but I wasn't sure how exactly to do that. I'd be happy to write some if I could get some guidance.

### CODE REVIEW

**Comment by devajmeireles** [comment]
Why not `--path`?

**Comment by dbhynds** [comment]
Great point. I'll update that tomorrow.

**Comment by taylorotwell** [comment]
1. Not sure it should be relative to app path if provided, should just be an absolute path.
2. Should probably allow an array of paths like we allow an array of models.

**Comment by dbhynds** [comment]
Manually tested the following:
```php
Artisan::call('model:prune', ['--path' => [ 'app/Models', 'app/Domains' ]]);
Artisan::call('model:prune', ['--path' => 'app']);
Artisan::call('model:prune', ['--path' => 'vendor/some-random-lib']);
```

**Comment by chWagnr** [comment]
Models are filtered out if they are not in the `App` namespace. Is that intentional? 

The `str_replace` in the `map` callback returns something like this `App\\var\www\html\foo\Models\Bar` when calling `artisan model:prune --path=foo/Models/`

**Pull request merged**
