### PR TITLE
[5.5] Return 201 in case of a Model just created.

### PR DESCRIPTION
**Pull request by mathieutu**
Allow to do : 
```php
class UserController extends Controller
{
    public function store(UserStoreRequest $request)
    {
        return User::create($request->only(['email', 'password']));
    }

    // ...
```

### CODE REVIEW

**Comment by themsaid** [comment]
I think this is a breaking change since people will start getting 201 instead of 200, some tests might fail and client might start complaining.

**Comment by mathieutu** [comment]
Hum, you're right, I can understand that...
Actually I made that because I thought it was already like that, and when I tried it didn't works ^^".

Do you really think some people are returning a just created user with a 200 in a api ? 😱

**Comment by themsaid** [comment]
the answer is YES :D I do . don't really care about the response code in many cases.

**Comment by edsamonte** [comment]
This PR actually makes sense. Though @themsaid is actually right, this is a breaking change. 

Additional feedback is to extend this concern to Resources. There should be a consistency between the two - when returning a model and when returning a resource.

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Http/Resources/Json/ResourceResponse.php#L113

**Comment by taylorotwell** [comment]
I do like this change but yeah would prefer it on 5.6.

**Comment by mathieutu** [comment]
Should I reopen it on master?

**Comment by mathieutu** [comment]
Ok I'll reopen it on master.

**Pull request closed without merging**
