### PR TITLE
[5.5] Ability to create view name aliases

### PR DESCRIPTION
**Pull request by joshralph93**
This gives the ability to use aliases within views and blade directives.

For example adding
```php
View::addAlias('@panel', 'admin.layout.components.panel');
```

means we could use the following syntax within blade

```blade
@component('@panel')
...
@endcomponent
```

Aliases do not have to start with an `@` - but prefixing with a symbol could be a good way to differentiate between an alias and a top level view.

### CODE REVIEW

**Comment by browner12** [comment]
so if I'm following this correctly, the difference is we can write

```php
@component('@panel')
```

instead of 

```php
@component('admin.layout.components.panel')
```

is that correct?

**Comment by joshralph93** [comment]
correct, cleans the template up a fair bit if using a number of components

**Comment by browner12** [comment]
alright, then I'm personally 👎  on this. I don't see enough of a benefit to justify adding this extra feature/code.

**Comment by ConnorVG** [comment]
It does also add the ability to do `view('@panel')`, though (alike @browner12) I am against this. It's just bizarre.

**Comment by taylorotwell** [comment]
No plans to add.

**Pull request closed without merging**
