### PR TITLE
[5.8] delete ForeignKeyDefinition class

### PR DESCRIPTION
**Pull request by TBlindaruk**
- the main difference between ForeignKeyDefinition and ColumnDefinition,
that ColumnDefinition is actually created https://github.com/laravel/framework/pull/24444/files#diff-0a0682dbb89567dbcd7c4f50d4d1ece5R1260

So, as for me it is not ok, that we will have return type, which never will be returned.

UPD: reverted https://github.com/laravel/framework/pull/28387

### CODE REVIEW

**Comment by deleugpn** [comment]
The whole point of docblock is to provide helpful information. Hope the class stays this time.

**Comment by staudenmeir** [comment]
I strongly disagree. The class is highly useful and doesn't cause any harm.

**Comment by driesvints** [comment]
You basically have two sides on this I guess. I'm with @TBlindaruk as the class is dead code basically and only beneficial for IDE's.

**Comment by staudenmeir** [comment]
> only beneficial for IDE's

I assume/hope that most people use IDEs (and foreign keys), so this helps *a lot* of users.

**Comment by TBlindaruk** [comment]
> I assume/hope that most people use IDEs (and foreign keys), so this helps _a lot_ of users.

yes, and IDE will say that `foreign` method will return the `ForeignKeyDefinition` class... but it does not true. It will never return the ForeignKeyDefinition

**Comment by TullariS** [comment]
Sorry @TBlindaruk i replied on my PR and should've done it here.

https://github.com/laravel/framework/pull/28387#issuecomment-489801247

**Comment by TullariS** [comment]
New PR that actually uses ForeignKeyDefinition: #28435

**Comment by TBlindaruk** [comment]
@TullariS , Thanks!) I will close my PR

**Comment by TullariS** [comment]
@TBlindaruk you're welcome. Thank you for the feedback.

**Comment by deleugpn** [comment]
I think Taylor's comment summarise it perfectly (https://github.com/laravel/framework/pull/28435#issuecomment-490063207)

> If it works with PHPDoc only why do we need a code change?

**Pull request closed without merging**
