### PR TITLE
[9.x] Add ```sum``` directive in blade

### PR DESCRIPTION
**Pull request by milwad-dev**
I think is better to add array php methods in blade.
This directive help to sum array in blade like this;
```php
@sum([1, 2, 3, 4]) // 10
OR
@sum(1, 2, 3, 4) // 10
```

### CODE REVIEW

**Comment by dennisprudlo** [comment]
It's a very specific directive you could easily add to your own project (https://laravel.com/docs/9.x/blade#extending-blade). Otherwise we will see a lot of PRs wanting to add `@sub`, `@mul` and the list goes on. Also this only handles array literals, `@sum($someVariable)` won't work.

**Comment by milwad-dev** [comment]
@dennisprudlo 
This directive is for initializing array methods in PHP. Another method will be added in the future.

**Comment by ankurk91** [comment]
BIG no.

If this PR gets merged, Laravel team will see a flood of such PR.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
