### PR TITLE
[6.x] Format docblock spaces

### PR DESCRIPTION
**Pull request by iamgergo**
This PR sets the spacing to the correct format in the docblocks.

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks man! Great job 👍

**Comment by iamgergo** [comment]
Thanks, happy to help!

**Comment by IlyaVorozhbit** [comment]
need more commits!

**Comment by GrahamCampbell** [comment]
Odd this wasn't squash merged @driesvints?

**Comment by driesvints** [comment]
@GrahamCampbell I forgot to squash merge but it's fine.

**Pull request merged**
