### PR TITLE
[8.x] Fix misordered assertEquals arguments

### PR DESCRIPTION
**Pull request by antonkomarev**
This PR fixes `assertEquals` arguments order in tests. It looks like `assertSame` doesn't have this issues.

### CODE REVIEW

**Comment by antonkomarev** [comment]
I don't think we should fix it in 6.x or 7.x, not so important change, just to keep all the things right.

**Comment by GrahamCampbell** [comment]
I am only happy with this if it won't cause merge conflicts with 6.x in the future. Otherwise, no need to change this.

**Comment by antonkomarev** [comment]
But it is wrong now. First argument must be expected value. It will produce incorrect exception on fail.

**Comment by antonkomarev** [comment]
Should I make this changes in 6.x then?

**Comment by antonkomarev** [comment]
Replaced by #34665 targeted to 6.x

@GrahamCampbell I've checked. It is available to merge to 6.x, 7.x and 8.x without any issues.

**Pull request closed without merging**
