### PR TITLE
[8.x] `firstOrCreate` and `firstOrNew` should merge attributes correctly

### PR DESCRIPTION
**Pull request by JayBizzle**
Not sure if this is a bug, but at the same time, it seems like it doesn't work as you'd expect, so thought I'd create this PR for some feedback.

I guess you could argue this is not the correct use case for the `firstOrNew()` method, e.g. why check for an existing value, then change that value to something new. Either way, it was still unexpected.

Consider the following example...

```php
$company = Company::firstOrNew(
	['name' => 'Does not exist'],
	['name' => 'New Company'],
);

dd($company);

```

### Current Output
```
=> App\Models\Company {
    name: "Does not exist",
}
```

### Expected Output?
```
=> App\Models\Company {
    name: "New Company",
}
```

Same "bug" exists with `firstOrCreate()`

More details here https://github.com/laravel/framework/discussions/38303

// ping @Sirfrummel

### CODE REVIEW

**Comment by devcircus** [comment]
Seems like there should be a check in place that doesn't even allow this. The name "firstOr" has no meaning when doing it this way. 

The first parameter not only defines what you're looking for, but also, any additional attributes in the first argument should be used in creating the model if one wasn't found. Any duplicate attributes with different values in the second argument are ignored. 

I'd argue there should be a check for duplicate attributes in each argument, with different values, and if found, throw an exception, because it's no longer a "firstOr" situation at that point. 🤷🏻‍♂️

**Comment by Sirfrummel** [comment]
Thank you for opening the PR.  I disagree it's a mis use of the method though.  Think of the example code I gave in the discussion:
`$project = Project::firstOrCreate([ 'uuid' => $request->uuid ], [ 'uuid' => Str::uuid() ] );`
The gist here is that there are completely valid reasons why you want to do a lookup based on provided user input, _however_ you should be able to override that *if you want* in the CREATE parameters.

What I had to do in my program was an uglier implementation:
```
 $project = Project::firstOrNew(
        ['uuid' => $request->uuid],
        [
          'name' => $request->name
        ]
      );
      if (!$project->id) {
        $project->uuid = Str::uuid();
        $project->save();
      }
```
but it would have been super slick if I could just do:
`$project = Project::firstOrCreate([ 'uuid' => $request->uuid ], [ 'uuid' => Str::uuid() , 'name' => $request->name] );`
for example.
The fact is, there may be some parameters you use to FIND , but you don't actually want to trust them for CREATE (or in this example, have the ability to override).

**Comment by JayBizzle** [comment]
@Sirfrummel You could have written that code like this...

```php

if(! Project::where('uuid', $request->uuid)->exists()) {
	Project::create([
		'uuid' => Str::uuid(),
        'name' => $request->name,
    ]);
}
```

The question is, was the `firstOr*()` method the correct tool to choose for this task? I can see why you expected it to work thought, hence the discussion in this PR 👍

**Comment by JayBizzle** [comment]
t

> If this is accepted (to 9.x?), the same methods of classes `HasOneOrMany` and `BelongsToMany` ([9.x](https://github.com/laravel/framework/pull/37337)) should also be updated.

Thanks, will look into that once we have some definitive feedback on this 'issue' 👍

**Comment by JayBizzle** [comment]
@taylorotwell should I target this at 9.0?

**Comment by taylorotwell** [comment]
@JayBizzle I'm not sure if that's necessary. As far as I can tell, the method is not following its documented behavior, which would make this a bug fix.

**Comment by JayBizzle** [comment]
Okay, will keep the target as 8.0

**Comment by taylorotwell** [comment]
OK - marking this as draft until other locations are updated. Please mark as ready for review when done.

**Comment by JayBizzle** [comment]
I have updated the `firstOr*()` methods on the `HasOneOrMany` relationship.

Just looking at the `firstOr*()` methods on the `BelongsToMany` relationship and it seems to me that those methods don't currently behave like their base Model, or `HasOneOrMany` counterparts. There is no option to pass a seconds array of values that you want to use to create a new instance or persist to the database.

https://github.com/laravel/framework/blob/a0021ab5f05a4c34a02ccec526827024932fbc5f/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L599-L606

https://github.com/laravel/framework/blob/a0021ab5f05a4c34a02ccec526827024932fbc5f/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L616-L623

I guess my question is...is it worth updating these methods when the bug doesn't exists and those methods are not functionally the same as the ones found in `Builder` and `HasOneOrMany`?

I think if we want those methods to be functionally equivalent, then that is a separate issue.

Unless I am missing something? 😕 

Thoughts?

Ping @derekmd @taylorotwell

**Comment by JayBizzle** [comment]
Ah yes, sorry @derekmd I totally.missed the link to that PR. It make sense now. Will do some more work on this tomorrow, thanks 👍

**Comment by JayBizzle** [comment]
Done the `BelongsToMany` relation changes in a PR targeting `9.0` here - #38367

**Comment by Sirfrummel** [comment]
Thank you @JayBizzle for seeing this through!

**Comment by ginnerpeace** [comment]
What's the point?
Why force all developers to accept his habits?
Your feature caused thousands of BUG to projects in the production environment.

**Pull request merged**
