### PR TITLE
[5.2] Add reset form to auth scaffold

### PR DESCRIPTION
**Pull request by danielway**
The "artisan make:auth" scaffold lacked a GET route for the password/email page, to request a reset link email. The view for this operation already exists and is installed by the scaffold.

I simply added this route to the scaffold so the view and the password reset functionality is usable.

### CODE REVIEW

**Comment by taylorotwell** [comment]
There is no bug. I just walked through the entire process on my end.

**Comment by GrahamCampbell** [comment]
showLinkRequestForm is never used then?

**Comment by danielway** [comment]
And the view to enter the email to send the link to is never displayed? The "Forgot my password" link in the included login page 404s.

**Comment by taylorotwell** [comment]
Not for me. Works fine?

**Comment by taylorotwell** [comment]
I just went through the whole process on a fresh 5.2 installation.

**Comment by danielway** [comment]
Alright. Where is the scaffold including the GET route for password/email? Before my commit it only includes the post to send the email.

**Comment by taylorotwell** [comment]
there is no GET password/email... that isn't used anymore in 5.2. it uses
GET password/reset.

**Comment by danielway** [comment]
Oh gotcha, sorry for the confusion.

**Pull request closed without merging**
