### PR TITLE
[9.x] Add a new function `withSoftDeletes` in routes

### PR DESCRIPTION
**Pull request by michaelnabil230**
Laravel allows models to have soft delete to not remove from the row form database. to add the date the resource is deleted.
This contribution allows a developer to create a resource route that supports soft delete routes.

For ex:
```php
Route::resource('users', UserController::class)->withSoftDeletes();
```

### CODE REVIEW

**Comment by siarheipashkevich** [comment]
Please check https://laravel.com/docs/9.x/routing#implicit-soft-deleted-models

**Comment by michaelnabil230** [comment]
@siarheipashkevich 

‎‏In fact it doesn’t look like that feature. In short, it creates the links you want to restore or trashed in your data.

**Comment by ankurk91** [comment]
https://laravel-code.tips/you-can-call-withtrashed-on-a-route-to-accept-soft-deleted-models/
Can you rename this method to `withTrashed()` ?

**Comment by michaelnabil230** [comment]
@ankurk91
But there will be problems in the freamwork. And also my PR creates its own urls trashed and restore.

**Pull request closed without merging**
