### PR TITLE
[6.0] Autoload providers and facades

### PR DESCRIPTION
**Pull request by driesvints**
This PR leverages the autoloading support from Laravel to autoload all service providers and facades which Laravel provides. These were before defined in the `app.php` config file. It cleans up the `app.php` config file and makes the skeleton more cleaner. 

This behavior can still be overridden to the old one by opting out [as described in the docs](https://laravel.com/docs/5.8/packages#package-discovery):

```json
"extra": {
    "laravel": {
        "dont-discover": [
            "laravel/framework"
        ]
    }
},
```

The companion PR for the skeleton here: https://github.com/laravel/laravel/pull/5076

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I still find that the alises registering themselves to be an anti-pattern, just like the situation with global functions.

**Comment by GrahamCampbell** [comment]
Registering providers is one thing, but the alias registration just seems wrong to me.

**Comment by driesvints** [comment]
@GrahamCampbell we haven't had problems with it so far and it's an easy opt-out (see my comment).

**Comment by GrahamCampbell** [comment]
It's not easy to opt out of only the alias registration though.

**Comment by driesvints** [comment]
Maybe we could implement something for that with a new syntax. Something like the below? 🤔

```json
"extra": {
    "laravel": {
        "dont-discover": [
            "laravel/framework@aliases"
        ]
    }
},
```

**Comment by GrahamCampbell** [comment]
I just don't understand why anyone would want aliases to be auto-registered. I often just delete every alias out of the app structure when I make a new app, or keep only a couple of them.

**Comment by driesvints** [comment]
@GrahamCampbell okay but then we're discussing registering Facades in the first place. They've been autoloaded since the beginning of the framework. I don't see why we should change that behavior now. This discussion is also a bit besides the point of this PR.

**Comment by brunogaspar** [comment]
I'm with @GrahamCampbell 

Though, i haven't used this discovery feature that much, but what about disabling a few providers and disabling a few aliases from Laravel itself?

Is that still possible? Or i need to copy everything from one place to the other and remove what i don't want?

**Comment by crynobone** [comment]
This makes it much harder for package developers to say extends `illuminate/auth` and suggest someone to change `Illuminate\Auth\AuthServiceProvider` to `Foo\Bar\AuthServiceProvider` in the `app.php` config (current behaviour).

Moving forward with this, people that want to replace the service provider would needs to re-add all the service providers back to `app.php` (I assume it would be removed since that just going to create duplicates).

**Comment by driesvints** [comment]
> Though, i haven't used this discovery feature that much, but what about disabling a few providers and disabling a few aliases from Laravel itself?

I'm not sure if it's a good idea to disable some providers. The `laravel/framework` comes with all of the components and for me I'd expect all of them to be initialized because I explicitly required them as so.

> Is that still possible? Or i need to copy everything from one place to the other and remove what i don't want?

You'll have to copy them. But I don't think many would want to do this. I haven't ran into any situation myself where I needed to disable some service providers. I think it's best that we look at how we can override bindings in this case.

> This makes it much harder for package developers to say extends illuminate/auth and suggest someone to change Illuminate\Auth\AuthServiceProvider to Foo\Bar\AuthServiceProvider in the app.php config (current behaviour).

Wouldn't it be better if we looked at how you can extend in another way than overriding the service provider? Do you have specific examples when you actually need to override the provider?

> Moving forward with this, people that want to replace the service provider would needs to re-add all the service providers back to app.php (I assume it would be removed since that just going to create duplicates).

This would indeed be the case but like I said I think that that's rather the exception then the rule in most apps. I haven't found myself wanting to do this. I think it's best that we look at better ways on how to extend from the framework or replace internals instead of having to resort to override service providers. 

I added a companion PR above where I indeed removed the core aliases and providers from the skeleton.

**Comment by crynobone** [comment]
> I haven't found myself wanting to do this.

I have the need to have this. Which is why I put up the example.

---

Other than above issue, this would also cause issue for any packages that still depends on the default services to be registered first. Laravel prevent this issue by ensuring the services from `app.providers` will registers anything that prefixed with `Illuminate\` name to be loaded first, see <https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Application.php#L574-L585>

**Comment by GrahamCampbell** [comment]
> I have the need to have this. Which is why I put up the example.

I also have the need for this. I replace the bus service provider entirely.

**Comment by driesvints** [comment]
> I have the need to have this. Which is why I put up the example.

Okay but can you show some code then? Like: actually show an example why you would need to do this.

> this would also cause issue for any packages that still depends on the default services to be registered first.

There shouldn't be a need for ordering service providers. The container should resolve dependencies properly.

>  Laravel prevent this issue by ensuring the services from app.providers will registers anything that prefixed with Illuminate\ name to be loaded first

Ah, thanks for making me aware. I think we may actually remove that part now.

> I also have the need for this. I replace the bus service provider entirely.

Can you tell why you needed to do that? Is there any reason why you can't leverage the container/contracts for this?

Btw: definitely not trying to play hard ball here guys. I genuinely want to look into your use cases to help understand them better and figure out the best solution for this 👍

**Comment by crynobone** [comment]
> There shouldn't be a need for ordering service providers. The container should resolve dependencies properly.

If `laravel/passport` service providers got loaded first before `laravel/framework` you don't see that it's going to cause an issue right now? The container can't resolve services that yet to be registered.

**Comment by GrahamCampbell** [comment]
> The container can't resolve services that yet to be registered.

That shouldn't be a problem, since nobody should be resolving things in the register method? Only from within callbacks that should never get run until boot, or later?

**Comment by GrahamCampbell** [comment]
> There shouldn't be a need for ordering service providers.

The use case I have is for registering error handling as quick as possible. For example, Bugsnag has to be manually added, to ensure it can capture as much as the bootstrap process as possible.

**Comment by crynobone** [comment]
> That shouldn't be a problem, since nobody should be resolving things in the register method? Only from within callbacks that should never get run until boot, or later?

https://github.com/laravel/passport/blob/7.0/src/PassportServiceProvider.php#L251-L258

Passport uses `Auth::extend()` on `register()`. This explicitly require `Illuminate\Auth\AuthServiceProvider` to be resolved first. I did make a PR to 5.7 to avoid this #26824 but passport still support Laravel 5.6

**Comment by taylorotwell** [comment]
I'll just hold off on this since I can tell it will be pretty contentious and is basically a cosmetic change 😅

**Comment by driesvints** [comment]
Okay no problem. I guess for now its indeed a cosmetic chance but if we ever want to use the components separately then we should definitely revise this.

**Pull request closed without merging**
