### PR TITLE
[10.x] Add tests for nested error messages

### PR DESCRIPTION
**Pull request by samuelwei**
Refering to https://github.com/laravel/framework/issues/47030

This PR adds tests to ensure the localisation of nested error messages is working properly.

It reveals the following bug: Fully nested, partially nested and fully flat json translation files behaive differently.

In other areas of Laravel, the "degree of nesting" is irrelevant, so this should also be the case for translating validation errors from a consistency perspective.

It is possible to fix this problem of the framework in the laravel application itself, but according to the clean code principles (https://clean-code-developer.com/grades/grade-1-red/#Root_Cause_Analysis) it would be better to fix the root problem.

Currently this PR is WIP and does not fix the issue

--
Replaces: #47034

### CODE REVIEW

**Comment by SamuelWei** [comment]
@nunomaduro Before investing in fixing this bug, does the Laravel core team think it is a bug that should be fixed?

**Comment by nunomaduro** [comment]
@taylorotwell Can you let us know, if you think this is a bug that should be fixed? If yes, simply set the pull request back to draft, so we can work on a solution that makes these tests pass.

**Comment by nunomaduro** [comment]
@taylorotwell Can you let us know, if you think this is a bug that should be fixed? If yes, simply set the pull request back to draft, so we can work on a solution that makes these tests pass.

**Comment by taylorotwell** [comment]
I don't merge failing tests, only fixes.

**Comment by taylorotwell** [comment]
Unsure if it should be fixed. We never document this as a capability of Laravel.

**Pull request closed without merging**
