### PR TITLE
[5.0] Minor CS Fixes, And Micro-Optimizations

### PR DESCRIPTION
**Pull request by GrahamCampbell**
In foreach loops, php will actually evaluate what we're iterating over for every iteration. Because of this, we should not be casting inside the foreach loop.

### CODE REVIEW

**Comment by ibrasho** [comment]
I think you missed on in `Illuminate\Database\Eloquent\SoftDeletingScope` @ line 39.

**Comment by GrahamCampbell** [comment]
No, that was intentional. :)

**Comment by ibrasho** [comment]
Just to know, why is it different?

**Comment by GrahamCampbell** [comment]
We need to evaluate it each time since we are modifying it during each iteration. I don't want to change the behaviour of anything in this pull.

**Comment by ibrasho** [comment]
I think the casting was there since `Builder::$wheres` default value is null, am I right?

[I can't see the difference between using casting and not using it.](http://3v4l.org/TtEnt)

Am I missing something?

**Comment by GrahamCampbell** [comment]
Yes, this case is not the same as what you had there.

**Pull request closed without merging**
