### PR TITLE
[5.2] Populate the email field from the password reset email

### PR DESCRIPTION
**Pull request by dwightwatson**
This change will append the URL encoded email address of the user to the reset password link that is emailed to them. This is used to pre-populate the email field on the reset password form. This makes it easier for legitimate users who are trying to reset their password while continuing to make it difficult to brute-force a reset token.

### CODE REVIEW

**Comment by CurosMJ** [comment]
the token and email should better be sent as parameters instead of url path.

**Comment by dwightwatson** [comment]
Yeah, I thought I'd get some feedback first before changing the structure of the path too much. My other thought was to leave the token as is and then pass the email as a query parameter instead.

**Comment by CurosMJ** [comment]
your other thought is better

**Comment by taylorotwell** [comment]
To me the e-mail should be more like a query string or something so you don't have to mess with the controller method signature.

**Pull request merged**
