### PR TITLE
[7.x] Change custom pivot model when used in updated event

### LINKED ISSUE #29636: [5.8] Pivot Model Events - originals are not set
- Laravel Version: 5.8.32
- PHP Version: 7.3.1
- Database Driver & Version: PostgreSQL 10.6

### Description:

I have a pivot table with some additional attributes. I also defined a custom intermediate model for this pivot to be able to observe relation changes.

#### Tables example

|consultants|
|---|
id
...

|consultancies|
|---|
id
...

|consultancy_constultant|
|---|
consultancy_id
consultant_id
from
till
job_title

In ConsultancyConsultantObserver `updated` gets fired and executed. I want to store in history log all changes user made. So I simply call `$model->getChanges()` to get changed attributes. It works on regular eloquent models, but on pivot models I receive an object, that only has relation ids (in my case consultancy_id and consultant_id) as original attributes stored. So it is not possible to fetch old attribute values at this point.

I tried to debug it, but I could not catch the point, where it happens - I gave up after 2 hours of trying... 

@ralphschindler you seem to be a relevant contributor to the pivot models stuff. May be you can help me

**UPDATE**: forget to mention. I update pivot values via sync array. Here is a snipped from code

```php
$consultant->consultancies()->sync([
    3 => [
        'from'      => Arr::get($consultancyInput, 'from', null),
        'till'      => Arr::get($consultancyInput, 'till', null),
        'job_title' => Arr::get($consultancyInput, 'job_title', null),
    ]
]);
```

### LINKED ISSUE #29678: Can't get pivot model's id prop on updated event
- Laravel Version: 5.8.*
- PHP Version: 7.2.13
- Database Driver & Version: MariaDB 10.3.4 

### Description:
The pivot model's id attribute is not accessible inside of the updated() method. It is only accessible in the created method.

### Steps To Reproduce:

ModelA class:

```
public function modelB()
{
    return $this->belongsToMany(ModelB::class, 'model_a_model_b', 'model_a_id', 'model_b_id')
        ->using(PivotModel::class)
        ->withPivot('id', 'prop_1', 'prop_2');
}
```
ModelB class:

```
public function modelA()
{
    return $this->belongsToMany(ModelA::class, 'model_a_model_b', 'model_b_id', 'model_a_id')
        ->using(PivotModel::class)
        ->withPivot('id', 'prop_1', 'prop_2');
}
```

PivotModel:

```
use Illuminate\Database\Eloquent\Relations\Pivot;

class PivotModel extends Pivot
{
    public $incrementing = true;

    public static function boot() {

        parent::boot();

        static::created(function ($model) {
            dump($model->id); // Accessible
            dump($model->toArray()); // The id prop is in the array
        });

        static::updated(function ($model) {
            dump($model->id); // Not accessible
            dump($model->toArray()); // The id prop is not in the array
        });
    }
}
```

Pivot table migration file

```
Schema::create('model_a_model_b', function (Blueprint $table) {
    $table->increments('id');
    $table->unsignedInteger('model_a_id');
    $table->unsignedInteger('model_b_id');
    $table->string('prop_1');
    $table->string('prop_2');

    $table->unique(['model_a_id', 'model_b_id'], 'model_a_id_model_b_id');

    $table->foreign('model_a_id')
        ->references('id')->on('model_a')
        ->onDelete('cascade')
        ;

    $table->foreign('model_b_id')
        ->references('id')->on('model_b')
        ->onDelete('cascade')
        ;

    $table->timestamps();
});
```

You can check [my question](https://stackoverflow.com/questions/57562783/cant-access-pivot-models-id-attribute-inside-of-the-staticsaved-method-in) on the SO for more details

### PR DESCRIPTION
**Pull request by ebrigham1**
Re-pulling #29720 against 6.0 

/cc @ralphschindler for feedback

Text from original pull request below

---
This PR fixes #29678 and may possibly fix #29636 

## Problem
Custom pivot classes were missing attributes as well as information on what was changed/dirty when used with a custom updated event. This is happening because in `updateExistingPivotUsingCustomClass()` `save()` is called on a newly generated pivot model rather than the existing attached pivot model. Because of this the "new" pivot model is passed into the updating event and it is lacking any other attributes that weren't passed to be updated aside from the keys necessary to perform the update.

When attempting to fix this problem I also ran into another problem which is that  `getCurrentlyAttachedPivots()` was generating a pivot object that was missing some information (table, connection, timestamps).

## Solution
Instead of generating a new pivot object to run save on it is run on the pivot returned from `getCurrentlyAttachedPivots()`, this should retain all the additional attributes that weren't specifically updated in this call.

In `getCurrentlyAttachedPivots()` I've essentially copied the instantiation style of `newPivot()` so that the object generated will not just have the attributes from the database but also get the proper table name and connection information.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Ping @ralphschindler

**Comment by ralphschindler** [comment]
I'm still looking at this (with 2-3 other pivot related issues in the tracker), just dropping a line to say I'm on it still.

**Comment by ebrigham1** [comment]
FYI the problem #29970 fixes (Correctly modify updated_at on custom pivot model) also seems to be fixed by this branch without the additional line of code added `$pivot->timestamps = in_array($this->updatedAt(), $this->pivotColumns);`. This is due to to the fact that the fix to `getCurrentlyAttachedPivots()` allows the existing `$pivot` object to have all the existing attributes, not just those passed in. This allows it to correctly detect whether it has timestamps without the additional line of code.

Tested by manually pulling in @mpyw's test from #29970 locally. I can rebase and pull in the test and the line, deleting the line, but don't want to mess with this pull request at this point unless requested to do so.

**Comment by ebrigham1** [comment]
I ended up removing the line mentioned above from #29970 as there were merge conflicts that needed to be resolved from merging it into master branch. As you can see the test added still passes with the line removed.

**Comment by ralphschindler** [comment]
@ebrigham1 I am not entirely sure this needs a new CustomTest class, can the use case be worked into the existing Test class?

I will run through it tonight.

**Comment by ebrigham1** [comment]
Thank you for reviewing @ralphschindler. I've moved the tests, but I did have to slightly modify the classes used by the existing tests. I'm unsure if this would be considered modifying an existing test or not so I left this in a separate commit and can easily undo it if it is not desired.

**Comment by taylorotwell** [comment]
So what is the status here? Is this ready to merge?

**Comment by ebrigham1** [comment]
As far as I'm concerned its ready to go, but I don't think @ralphschindler has fully reviewed it yet, I did make the one change he initially requested.

**Comment by ce-brex** [comment]
Will this be merged into the 6.x branch?

**Comment by GrahamCampbell** [comment]
@ce-brex No. This is being treated as a breaking change, rather than a bug fix. A bug fix is a breaking change that is changing something to how it was always intended to work. Other breaking changes are changing some behaviour to be better, and are not considered "bug fixes", and so must go to master to avoid breaking people's code.

**Comment by GrahamCampbell** [comment]
> A bug fix is a breaking change that is changing something to how it was always intended to work

This PR is not a bug fix, because it was not changing something to how it was **obviously intended to work**.

**Pull request merged**
