### PR TITLE
[5.5] load missing closure issue fixed

### LINKED ISSUE #22134: loadMissing returns an error when passing a closure
- Laravel Version: 5.5.21
- PHP Version: 7.1.9
- Database Driver & Version: mySQL

### Description:
I use `loadMissing` and it works properly, however when I call it with a Closure:

    public function getProductsAttribute(){
        $this->loadMissing(['shop.product'=> function ($query) {
         ....
        }]);
        ...
    }

returns error `"array_key_exists(): The first argument should be either a string or an integer"` on:

    public function relationLoaded($key){
        return array_key_exists($key, $this->relations);
    }

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
Fixes #22134

### CODE REVIEW

**Comment by sisve** [comment]
Did someone forget the tests? ;)

**Comment by Dylan-DPC** [comment]
Yeah "someone" missed them. I wanted to include them but searched a lot and couldn't find tests for `load` or `loadMissing`.

**Comment by sisve** [comment]
There never was any tests in the original PR https://github.com/laravel/framework/pull/20630 either. That's what makes this so fun, you get to be the first to write them! To boldly write what no one has written before!

**Comment by Dylan-DPC** [comment]
Yeah I know. I thought it is something better for a separate PR?

**Comment by taylorotwell** [comment]
Is there really a need to create these two variables?

**Comment by taylorotwell** [comment]
Please resubmit with tests.

**Pull request closed without merging**
