### PR TITLE
Download files with non-ascii characters v2

### PR DESCRIPTION
**Pull request by ejoseca**
We can't set the ContentDisposition 'attachment' in the constructor.
If the filename contains non-ascii characters, the constructor will throw an exception.
In this revision, if you don't specify a name, it is taken from the filename (this is what Symphony does if you don't provide a name, but here we can convert the filename to an ascii string so it won't throw any exception).

### CODE REVIEW

**Comment by jee7** [comment]
Would also like that to be fixed. Nowadays it shouldn't be any problem if there are non-ASCII characters in the file name. Why is this even checked?

**Comment by gwilgen** [comment]
Thanks @ejoseca for such a complete response.

I changed mi code not to use **Response::download()**, because it doesn't work (with files with non ascii chracters). I directly use your proposition for the download code directly in my Controllers.

Hope it wil be added to Laravel soon!

**Comment by ejoseca** [comment]
If it is useful for someone:

In Laravel 5, you can extend the _\Illuminate\Routing\ResponseFactory_ class and override the _download()_ method. Then, in a ServiceProvider, register your custom _ResponseFactory_ as the default one:

<pre>
// We extends \Illuminate\Routing\ResponseFactory class, that implements Illuminate\Contracts\Routing\ResponseFactory

$this->app->singleton('Illuminate\Contracts\Routing\ResponseFactory', function ($app) {
    return new MyCustomResponseFactoryExtendedFromResponseFactory($app['Illuminate\Contracts\View\Factory'], $app['redirect']);
});
</pre>

Doing this, you can use the default methods (_Response::json()_, _respose()->view()_, etc) and your custom methods in the same way: _Response::download()_, _response()->download

**Comment by victorortizmx** [comment]
:+1:

**Comment by jakjr** [comment]
+1

**Comment by localdisk** [comment]
:+1:

**Comment by mmochetti** [comment]
We faced the same issue. So far we decided to implement our own Response facade and Response service provider extending and overriding Laravels ones to fix this issue.
Would be nice that @taylorotwell or @GrahamCampbell, or any one else in charge of Laravel maintenance, takes a look at this as so many people faced the same issue. And also because @ejoseca put some good effort fixing it and explaining what was going on. Thanks!

**Comment by Rattone** [comment]
Hi! Was this fixed in Laravel 6, 7, 8...?

**Pull request closed without merging**
