### PR TITLE
[6.x] Adds lcfirst helper in Str class

### PR DESCRIPTION
**Pull request by aocneanu**
Adds a `lcfirst` helper in `Str` class that mirrors the existing `ucfirst`.

Adds a `testLcfirst` test for the helper.

The helper makes a string first character lowercase.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Won't this just have the effect of making the code twice as slow?

**Comment by aocneanu** [comment]
I guess it would be the same level of "slowness" as for `Str::ucfirst()`

**Comment by taylorotwell** [comment]
Feel free to macro this into your own project if you require it.

**Comment by aocneanu** [comment]
Roger.

One small request if I may, please help me understand why it is not inconsistent to have`Str::ucfirst()` without having `Str::lcfirst()`, because I'm clearly missing a point here.

Thank you in advance for the clarification.

**Pull request closed without merging**
