### PR TITLE
[5.7] Fix typos

### PR DESCRIPTION
**Pull request by Rowayda-Khayri**
This PR is to fix typos in MigrationCreator.php

### CODE REVIEW

**Comment by JayBizzle** [comment]
Uh oh

https://laravel-news.com/neurotic-laravel

😆

**Comment by Rowayda-Khayri** [comment]
I've worked as possible to make it follow the multi-line comments style.

**Comment by jmarcher** [comment]
This breaks the comment styling, can you fix that and keep the sense in the comments?

**Comment by taylorotwell** [comment]
No plans on merging right now.

**Pull request closed without merging**
