### PR TITLE
[5.2] Preserve keys in collection reverse

### LINKED ISSUE #9948: Collection: allow $preserve_keys option on reverse()
Is there a reason the `Collection`'s reverse method doesn't have a `$preserve_keys` option (see [PHP Docs for array_reverse](http://php.net/manual/en/function.array-reverse.php))? Is it simply a PHP version issue?

I ended up having to use `collect(array_reverse($points->all(), true))` instead of what I hoped would just be `$points->reverse(true)`.

### PR DESCRIPTION
**Pull request by arrilot**
Closes #9948

Sent to master because method signature is changed.

### CODE REVIEW

**Comment by ibrasho** [comment]
Why not to 5.1?
This doesn't change current behaviour..

**Comment by GrahamCampbell** [comment]
It is a breaking change though because it changes the method signature.

**Comment by JosephSilber** [comment]
I would have it preserve keys in 5.2, and be done with it. No need for the flag.

If you want to reset the keys, call `values()` on the result.

**Comment by arrilot** [comment]
Yeah, that makes sense, but it's a bigger bc break on the other hand.

@taylorotwell Any thoughts?

**Comment by taylorotwell** [comment]
I agree with @JosephSilber. I don't like adding all these flags for preserving keys. We should preserve keys where possible and, as he said, use ->values if you don't want keys.

**Comment by arrilot** [comment]
Okay, gonna change it in a couple of hours then.

**Comment by taylorotwell** [comment]
Went ahead and fixed it for you.

**Pull request merged**
