### PR TITLE
Fix "getQueueableIds" method in Collection

### PR DESCRIPTION
**Pull request by miladr**

### CODE REVIEW

**Comment by jmarcher** [comment]
Are you aware that $model->getQueueableId() is just an alias for $model->getKey() ?

Your PR is just repeating code.

**Comment by miladr** [comment]
I know, but in my case i'm overriding "getQueueableId" in my models to include tenant id with models when they are serialized.

**Comment by miladr** [comment]
It seems to me obvious that "getQueueableIds" function off Collection should call getQueueableId off all items.
As Str::EMPTY is an alias for '' but it's not worthless. [(4165d9c)](https://github.com/jmarcher/framework/commit/4165d9cf4d1f5c3ec23eb1d12683ee6c154b5d9a)

**Comment by Dylan-DPC** [comment]
Your title says it all. You can't "change" a function in a point release. Better to target this to master.

**Comment by taylorotwell** [comment]
No description given.

**Comment by miladr** [comment]
Sorry. "getQueueableIds" function of Collection is using "getKeys" function of its Models. I think it's better to it use "getQueueableId" of Models.
@taylorotwell

**Pull request closed without merging**
