### PR TITLE
Localize responses

### PR DESCRIPTION
**Pull request by dmcbrn**
Will propose another file change  to `/resources/lang/en/auth.php`. See here: https://github.com/laravel/laravel/compare/master...dmcbrn:patch-1

---details---

When creating an API I'm getting untranslated responses. This PR (in combination with the one mentioned above) will extract the 'Unauthenticated' text to language files making it easy to translate it.

### CODE REVIEW

**Comment by jmarcher** [comment]
:-1:

No need to localize Exception messages.

And your __() approach is wrong in this case.

**Comment by dmcbrn** [comment]
Hey, I'm still learning here and trying to contribute where I can. So I'd appreciate some constructive criticism. Obviously some checks failed and I'm doing something wrong, but I'm not sure what was it as the PR is as simple as it could be.

My scenario is that I have the API that returns the 'Unauthorized' reply. I'd like to keep my translations in one place so that I don't have to translate in front-end. Since the Laravel is returning the text next to the error number I don't see a reason why it couldn't be localized as well.

Thanks!

**Comment by jmarcher** [comment]
You should never return an exception, handle them and show an error message.

**Comment by dmcbrn** [comment]
I'm not returning an exception.

**Pull request closed without merging**
