### PR TITLE
[5.4] Use translations for auth:make

### PR DESCRIPTION
**Pull request by HendrikGrobler**
This change makes Laravel's auth:make command friendlier for non-english websites and makes it easier to added more supported languages out of the box in future.

It also fits in with the existing use of translation files in a clean Laravel install.

The auth:make command now also exports a labels translation file that contains translations for all the generated views. The locale can be specified as an option, but defaults to the locale set in the config.

Suggestions are welcome, especially around the keys and ways the translations are structured.

### CODE REVIEW

**Comment by taylorotwell** [comment]
No plans on this.

**Comment by HendrikGrobler** [comment]
The irony: “One thing that has been bothering me is I have seen a few people say they don’t contribute to Laravel because it seems like PRs get closed or shot down without much explanation. It’s hard to tell how many people are actually experiencing this issue. However, even a few cases is something that really bothers me and I want to improve.”

**Comment by taylorotwell** [comment]
That doesn't mean I must accept all pull requests. The reason for closing this one is it's easily translatable to any language after the fact. The languages could also be published as a package that others can easily download, etc.

**Comment by taylorotwell** [comment]
Another thing I would suggest is pinging and asking about the feature in Slack #internals before PRing it. That way people can talk about the issue before anyone spends time implementing anything.

**Comment by HendrikGrobler** [comment]
I appreciate the reply, I never expected that you simply need to approve every PR. I realize that not everything belongs in the framework, however, your comment was literally the issue described in the Reddit thread. It was short with very little explanation. 

I am happy enough with the reason presented, my reasoning was simply that the framework might be easier to adopt for non-english speakers if it had better more languages baked in. 

I am on Larachat and internals tends to be rather dead. However I will try pitching my idea there in future first.

I don't mind spending time, I learn more about how the framework works etc. But dismissively dealing with PR's is toxic to the community.

Thanks Taylor, I know it's not the easiest thing to manage.

**Comment by kamui545** [comment]
@HendrikGrobler In addition to slack there is also https://github.com/laravel/internals, cheers!

**Comment by HendrikGrobler** [comment]
Thanks @kamui545 I'll give that a go as well :)

**Pull request closed without merging**
