### PR TITLE
[5.1] Add HHVM >= 3.8.0 support in the artisan serve command

### PR DESCRIPTION
**Pull request by tortuetorche**
With the help of the [Proxygen Web Server](https://code.facebook.com/posts/1503205539947302/introducing-proxygen-facebook-s-c-http-framework/).

Now we can run Laravel development server with [HHVM](http://hhvm.com), like this:
`hhvm artisan serve`

### CODE REVIEW

**Comment by taylorotwell** [comment]
Does comparing versions like that work?

**Comment by GrahamCampbell** [comment]
@taylorotwell Yep: http://3v4l.org/FSQVX.

**Comment by tortuetorche** [comment]
I think this feature can be easily backported for older versions of Laravel.

**Comment by GrahamCampbell** [comment]
> I think this feature can be easily backported for older versions of Laravel.

No need. We only intend to fix bugs on the 5.1 branch.

**Comment by GrahamCampbell** [comment]
Don't we need to error if we're using a version of HHVM less than 3.8.0?

**Comment by GrahamCampbell** [comment]
Since serve doesn't work at all.

**Comment by tortuetorche** [comment]
@GrahamCampbell OK.
So for older versions of Laravel you can put this `hhvm_serve` file in the root of your application:
```sh
#!/bin/sh

hhvm -m server -v Server.Type=proxygen -v Server.SourceRoot="$(pwd)" -v Server.IP=localhost -v Server.Port=8000 -v Server.DefaultDocument=server.php -v Server.ErrorDocument404=server.php
```

**Comment by tortuetorche** [comment]
> Don't we need to error if we're using a version of HHVM less than 3.8.0?

Why not.

**Comment by tortuetorche** [comment]
@GrahamCampbell Should I need to update this pull request to add a artisan error message?

**Comment by GrahamCampbell** [comment]
> Should I need to update this pull request to add a artisan error message?

Just throwing an exception would be fine tbh.

**Comment by tortuetorche** [comment]
:sunglasses:

**Pull request merged**
