### PR TITLE
[5.2] Wrap "has" callback in where closure

### PR DESCRIPTION
**Pull request by wleona3**
So that "orWheres" on the has condition don't have to ALSO be nested in another where closure.

### CODE REVIEW

**Comment by acasar** [comment]
Hmm... Can you give some code example where this is needed?

**Comment by taylorotwell** [comment]
Closing based on above comment.

**Comment by wleona3** [comment]
Code such as this:
```
Model::whereHas('relation', function ($query) {
    $query->where('foo', 'bar');
    $query->orWhere('foo', 'baz');
});
```

Results in an exists condition like this:
`exists (relation.id = model.relation_id and relation.foo = 'bar' or relation.foo = 'baz')`

The issue here is that the 'or' statement now always applies. I'd hope that it'd generate something similar to 

`exists (relation.id = model.relation_id and (relation.foo = 'bar' or relation.foo = 'baz'))`

**Comment by acasar** [comment]
@wleona3 Thanks for the example. Your fix doesn't work in some cases as mentioned above, but we could implement it more like this: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Builder.php#L1187

**Pull request closed without merging**
