### PR TITLE
Log Facade methods

### PR DESCRIPTION
**Pull request by Artistan**
docblock definition for the static facade methods

### CODE REVIEW

**Comment by jmarcher** [comment]
Why? @see \Illuminate\Log\Writer is enough

**Comment by Artistan** [comment]
@jmarcher the `@see` declaration does not define it as a statically accessible set of methods. You could argue that it does based on it being a Laravel Facade... but I would be assuming everyone that looks at the code knows this and has used Laravel.  Adding these increases readability for newcomers and improves IDE support.

**Comment by taylorotwell** [comment]
Need to think more on if I want to do this for every single facade.

**Comment by jmarcher** [comment]
I personally do not like when things are added only to make life simpler for an IDE.
And this means that the comments need to be maintained along with the Writer class.

If your IDE needs help you can install the laravel-ide-helper package, and for API Reference, Laravel offers https://laravel.com/api/5.5/ that is way better than looking into the code for newcomers.

**Pull request closed without merging**
