### PR TITLE
[9.x] Add support for native enum to enum column : `$table->enum('status', OrderStatus::cases())`

### PR DESCRIPTION
**Pull request by MarienMupenda**

### CODE REVIEW

**Comment by driesvints** [comment]
See many previous attempts why this is a bad idea.

**Comment by MarienMupenda** [comment]
@driesvints thank you !

**Comment by MarienMupenda** [comment]
Is there any link to those previous attempts ?

**Comment by X-Coder264** [comment]
@MarienMupenda https://github.com/laravel/framework/pull/39854 https://github.com/laravel/framework/pull/40662 https://github.com/laravel/framework/pull/41026 https://github.com/laravel/framework/pull/41827 https://github.com/laravel/framework/pull/43483

**Pull request closed without merging**
