### PR TITLE
[5.5] Add cascade deletes to Model

### PR DESCRIPTION
**Pull request by diegosm**
With these changes we could use cascade deletes when fill the protected $cascadeDeletes = [ 'eager.loadings.accepted' ];

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
Why not just leave it to the database to cascade delete for you?

**Comment by diegosm** [comment]
Because the database onDelete(cascade) doesn't work with soft deletes

**Comment by imbrish** [comment]
One could also want to run some callback for "delete" events on related models.

**Comment by sisve** [comment]
I'm looking at the call to delete and wonder, does it actually load the model and fire any model events as @imbrish thinks, or does it just mildly abuse the fact that the callback that can be used to filter relations is a query Builder and can also be used to delete things?

And @diegosm says this should work with soft deletable items, but I don't see how. That would require a call to `$model->performDeleteOnModel()` but I see no such calls in the code. (Which also goes back to the previous question, are the models loaded at all?)

There's some unclear things;
1. Are we or are we not loading the actual models and firing the related events (deleting and deleted) on them?
2. Does this work with soft deletable models?
3. What's the data type of $item? The docblock is missing it.
4. Does performCascadeDeletes and performDeleteOnRelation return bool or void? Which is it? (Once again, the docblock looks weird.)
5. Does this work with recursive relations? Can I delete a node in a tree and all child nodes and children's child nodes are also deleted?
6. Where are the tests?

**Comment by diegosm** [comment]
1. No, the I founded two solutions to this, first go through each item in relationship and delete it, it maybe fire these events, but if had a lot of records maybe won't be a good idea, the code show the update for each relation recursively:
```

$this->load([ $item => function ( $q ) {
$q->delete();
}]);

```

This produces these SQL's

```

update users set deleted_at = ?, updated_at = ? where users.team_id in (?) and users.deleted_at is null 

update teams set deleted_at = ?, updated_at = ? where id = ?

```

In relation teams.users, but it isn't firing the events.

2. It is more for soft deletes

3 and 4. The dockblocks are wrong, it was automatically generated.

5. In first example is a cascade example 'teams.users'

6. I didn't make tests in these solution =/ Sorry

**Comment by taylorotwell** [comment]
Not necessary. Can be done at database level.

**Comment by diegosm** [comment]
To do this in database you need to have a lot of triggers for relations when using soft deletes, but ok..

**Comment by timacdonald** [comment]
@diegosm you might be interested in this package: https://github.com/michaeldyrynda/laravel-cascade-soft-deletes

**Pull request closed without merging**
