### PR TITLE
[9.x] Add `pipe` helper

### PR DESCRIPTION
**Pull request by michael-rubel**
### Inspiration
This helper was inspired by the combination of `tap()` and `collect()->pipe()`. Sometimes it's handy if you can pipe something without creating a collection, the same manner we can go with `tap()`.

### Example
```php
return pipe(static::$tooLongObjectName, function ($shortened) {
    if ($shortened->someMethodIsTrue()) {
        return false;
    }

    if (! $shortened->anotherMethodIsFalse()) {
        return false;
    }

    return true;
});
```

### CODE REVIEW

**Comment by crynobone** [comment]
You can already use `with()` or `transform()` at the moment.

**Comment by DarkGhostHunter** [comment]
```php
return with(static::$tooLongObjectName, function ($shortened) {
    if ($shortened->someMethodIsTrue()) {
        return false;
    }

    if (! $shortened->anotherMethodIsFalse()) {
        return false;
    }

    return true;
});
```

**Comment by michael-rubel** [comment]
@DarkGhostHunter Thanks, but it's more about consistency with the method available in the collection. I think it's not only me who may look for this method after using it in collections. Let's see what @taylorotwell says.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
