### PR TITLE
runAsynBackground to run all the tasks concurrently(#15720)

### PR DESCRIPTION
**Pull request by uppinggoer**
As for v5.1, when I need some callbacks, I must use runCommandInForeground which runs all my commands serially. If one command need too much time, in that way, all my command will has no chances to run. So I must use runCommandInBackground. However, no callbacks, I can't get any feedback.

On the other hand, if some command run too more time than expected, I want to be alerted by eamils.

In my project, I don't need runCommandInForeground. But the runAsyncBackground is necessary.

Maybe, I didn't get the correct methods.

### CODE REVIEW

**Comment by uppinggoer** [comment]
[more info](https://github.com/laravel/framework/pull/15829)

**Comment by srmklive** [comment]
@uppinggoer This is a breaking change in my opinion. I doubt that it will be included in 5.3. Also you haven't written any tests for this.

**Comment by taylorotwell** [comment]
This would make the after callbacks run before the command is even finished?

**Comment by uppinggoer** [comment]
```
    public function tryCleanUp(Container $container)
    {
        if (! $this->runAsynBackground) {
            return true;
        }

        // timeout alarm
        if (0 < $this->expiredTime && time() >= $this->expiredTime) {
            // alert
            $this->alarmTimeout($container);

            return true;
        }

        // is running
        if (file_exists($this->mutexPath())) {
            return false;
        }

        $this->callAfterCallbacks($container);

        return true;
    }
```

As I said in [#15829](https://github.com/laravel/framework/pull/15829), tryCleanUp just try to clean up. The following code will return false if then event hasn't finished
```
        if (file_exists($this->mutexPath())) {
            return false;
        }
```

**Comment by uppinggoer** [comment]
[more info](https://github.com/laravel/framework/pull/15829)  you can get the examples

**Pull request closed without merging**
