### PR TITLE
[5.8] Add the `dd` method to the query builder

### PR DESCRIPTION
**Pull request by alexbowers**
Adds the `dd` helper to the query builder so that you can debug queries inline.

```php
Post::first()->comments()->dd();
Post::where('a', 'b')->where('g', 'd')->dd();
```

Will show you the query and bindings.

### CODE REVIEW

**Comment by alexbowers** [comment]
The benefit of this is you can put the die dump at any point in the query build process (similar to how you can in a Collection chain).

Normally you would have to assign it to a temporary variable (which isn't necessarily easy to do, depending on how complex your query is), and then run the `toSql()` and `getBindings()` methods on the temp variable.

This allows you to not have to change your code, just put `->dd()` at any point in the query building process.

**Comment by taylorotwell** [comment]
I would just add it to the underlying query builder class instead of making a trait.

**Comment by alexbowers** [comment]
I'll be honest, I did that originally, then thought I had to add it to all of the individual relationships. When it turned out I didn't have to do that, I forgot to revert my changes. I'll make that change now.

**Comment by alexbowers** [comment]
Done.

**Comment by staudenmeir** [comment]
I think we should name the method `dump()` to be consistent with similar methods in Laravel and Dusk.

**Comment by alexbowers** [comment]
On Collections, the method is also called `dd`. Having `dd` is consistent with Laravel

**Comment by alexbowers** [comment]
A `dd` is the same as a `dump`, except that it kills the page as well.

**Review by akiyamaSM — APPROVED** [review]

**Comment by staudenmeir** [comment]
`Collection` contains both methods, but `TestResponse` and Dusk's `Browser` only have a `dump()` method that calls `dd()` internally. Maybe we should add both `dump()` and `dd()` to the query builder.

**Comment by taylorotwell** [comment]
Should this be on the Eloquent builder or the query builder?

**Comment by staudenmeir** [comment]
Please move the method to the query builder. This way, it is also available on the Eloquent builder.

**Comment by alexbowers** [comment]
I'll move it to the Query builder so that both have it.

@taylorotwell Any thoughts on `dump` vs `dd`? Should I change it, keep it, or provide both? A dump that doesn't die seems useless, and a dump that does die seems misnamed. so unsure how I should handle that.

**Comment by alexbowers** [comment]
Ok, thats changed. Now the Query Builder and Eloquent have both debug methods on them.

**Pull request merged**
