### PR TITLE
[8.x] Add custom date casting format to carbon object

### PR DESCRIPTION
**Pull request by brianrlewis**
The purposes of this PR is to make eloquent respect the custom date formats that are defined in `protected $casts = []` in cases where a single attribute is accessed. Currently the custom date formatting is only applied when date attributes are converted to strings in `addCastAttributesToArray`.

Obviously this is because eloquent is designed to return a Carbon date object when a single date attribute is accessed. However we can still tell that Carbon object which format to use when it is converted to a string.

For example with how things are now it works like this:

```
use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    protected $casts = [
        'transaction_date' => 'date:m/d/Y',
    ];
}

$invoice = new Invoice;
$invoice->transaction_date = '2020-11-25';

(string)$invoice->transaction_date // 2020-11-25 00:00:00
```

With this change in place you instead get this:
```
(string)$invoice->transaction_date // 11/25/2020
```

Current implementations may be designed around the expectation that the default format will be used when the Carbon object is converted to a string, so this could be included as a low or medium impact change for v8.

Having something like this in place will reduce the amount of additional code that needs to be written in order to convert dates to the desired format and makes the date casting feature more idiomatic.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Surely this is meant to be implemented by you overriding the toDateTime method?

**Comment by driesvints** [comment]
@kylekatarnls if you have a sec could you give this a review? Thanks!

**Comment by kylekatarnls** [comment]
Hum, it may be expected intuitively to get this format for the cast in string via the `casts` option but according to the doc:

> When using the date or datetime cast type, you may specify the date's format. This format will be used when the model is serialized to an array or JSON

`->casts` is only for array/JSON, not for string casts, if it's merged it need to be documented as breaking change as users may have `echo $user->custom_date_formatted` that currently use the default string cast and will fall to this new format if there is a custom cast format set.

If you're trying to customize the format for SQL saving, let me recommend instead:

```php
<?php
// app/Database/Query/Grammars/MySqlGrammar.php

namespace App\Database\Query\Grammars;

class MySqlGrammar extends \Illuminate\Database\Query\Grammars\MySqlGrammar
{
    public function getDateFormat()
    {
        return 'Y-m-d H:i:s.u';
    }
}
```

with:

```php
<?php
// app/Providers/AppServiceProvider.php

namespace App\Providers;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    // ...

    /**
    * Bootstrap any application services.
    *
    * @return void
    */
    public function boot()
    {
        DB::connection()->setQueryGrammar(new \App\Database\Query\Grammars\MySqlGrammar);
    }
```

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
