### PR TITLE
[5.1] Keep colums content if yet setted

### PR DESCRIPTION
**Pull request by ghost**
Hi,

If i have this code : 

``` php
    public function scopeWithMoviePoster($query)
    {
        return $query->leftJoin('art as poster', function ($join) {
                       $join->on('poster.media_id', '=', 'movie.idMovie')
                            ->where('poster.media_type', '=', 'movie')
                            ->where('poster.type', '=', 'poster');})
                     ->addSelect('poster.url as poster');
    }
```

Then I use : 

``` php
            $items = Movie::withMoviePoster()   // Remplace avantageusement une relation has_one
                           ->with('writers', 'directors', 'actors', 'countries', 'genres', 'studios')
                           ->find($id);
```

The find method don't keep the previous selection of fields i have made before.

The two modified files seem to solved this issue.

Hope this helps.

Regards

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please fix your CS issues

**Comment by tamplan** [comment]
Sorry, new using theses tools...

**Comment by tamplan** [comment]
Did someone can help me indicating why the step 'continuous-integration/travis-ci/pr' fails ?

Thanks by advance.

Regards

**Comment by tamplan** [comment]
I delete it because i have some issues.

**Pull request closed without merging**
