### PR TITLE
[10.x] Uses PHP Native type declarations in Auth middleware

### PR DESCRIPTION
**Pull request by rnambaale**
Adds native type declarations to public methods in Auth middleware.

### CODE REVIEW

**Comment by crynobone** [comment]
This introduce a breaking change to any Laravel application extending those method, no?

**Comment by rnambaale** [comment]
@crynobone You are right.

But I had assumed that it would be safer, or more predictable if all applications consuming this sent through the exact same type of `$request`. 

Thoughts?

**Comment by crynobone** [comment]
absolutely no breaking change on patch releases.

**Comment by rnambaale** [comment]
@crynobone I will close this one; and open it on the 11.x branch

Thanks.

**Pull request closed without merging**
