### PR TITLE
[11.x] Adds overwrite empty string helper

### PR DESCRIPTION
**Pull request by Lakshan-Madushanka**
Nullable or empty string fields in a database table are common occurrences. However, we typically don't want to display those empty spaces in our Blade templates.

Consider a User table with a nullable field last_name. If this field is empty, when we display it in Blade as `{{$user->last_name}}` the expected result is:

**first name: lakshan
last name:**

But ideally, we want something like this:

**first name: lakshan
last name: N/A**

This situation is common in many projects. While there are multiple solutions, using a ternary operator like` {{$user->last_name ?: 'N/A'}} `can be cumbersome. Additionally, if our  value contains only empty spaces or new lines ...etc., we probably don't want to display them to the user. In such cases, we would need to use more complex logic in our Blade files.

To solve this issue more efficiently, the following feature comes in handy:

last name: `{{Str::overwriteEmpty($user->last_name)}}`

Although the default value is a hyphen, you can use any desired symbol like so:

last name: `{{Str::overwriteEmpty($user->last_name, 'N/A')}}`  

This would result in:

**last name: N/A**

### CODE REVIEW

**Comment by henzeb** [comment]
I'd suggest a shorter name. Like 'default' or `value`. overwriteEmpty is not a good name imho. And you could use the [filled](https://laravel.com/docs/11.x/helpers#method-filled) or [blank](https://laravel.com/docs/11.x/helpers#method-blank) helpers instead to determine if the value is empty.

**Comment by johanrosenson** [comment]
> if our empty value contains empty spaces or new lines

Then the value isn't empty, I don't think we should redefine what commonly accepted terms mean.

It's better IMO to make sure values are trimmed when inserted into the model (or when accessed if that works better for your use case), then it's very easy to just rely on `?:` or `??` (i usually prefer the latter).

**Comment by Lakshan-Madushanka** [comment]
@henzeb  I think  filled() or blank() methods do not check for characters like \n or \r. It's important to note that these methods are not solely for checking emptiness, as described.

**Comment by Lakshan-Madushanka** [comment]
@johanrosenson, of course, you can use ternary or null coalesce operators. However, ternary operators may throw an error if the value is empty, and null coalesce operators only check if the value is empty. If the value is an empty space (' '), it will still be displayed.

**Comment by Lakshan-Madushanka** [comment]
@johanrosenson sorry for the misunderstanding description updated. Ternary throw error  for null values but null coalesce works with the trim middleware but I think it's little more  convenient with this helper (that's what helpers do)

**Comment by Lakshan-Madushanka** [comment]
@henzeb I also think name must be more fancier

**Comment by Rizky92** [comment]
What I would do in this situation is to use the model's attribute. I have total control about what value should be overwritten and what not.

In your case, it could be like this:
```php
public function lastName(): Attribute
{
    return Attribute::get(fn (array $attributes) => empty($attributes['last_name'] ? 'N/A' : $attributes['last_name');
}

**Comment by Lakshan-Madushanka** [comment]
@Rizky92 Even though I didn't mention it in the description, as I said, there are different ways to address this, including using model attributes. However, none of them seem ideal to me, so I've made this pull request.

For instance, if you have a model with five nullable fields, would you implement five different mutators for that? This would likely make your model messy and hard to maintain. In my opinion, mutators are meant to handle more advanced tasks, and they may not apply when returning data for an API.

Even though this may seem like a small issue, in my personal experience, it can escalate into a bigger mess."

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
