### PR TITLE
[5.7][FIX] Pagination calls into the collection

### PR DESCRIPTION
**Pull request by BSN4**
When calling collection methods from pagination instance it doesn't apply on the pagination items  . it's only return a collection . I made a horrible helper methods just to help me achieve this . This an old issue by the way. We don't need to ignore it anymore

### CODE REVIEW

**Comment by if4lcon** [comment]
I need to make some changes 4 tests failed sorry 🤓

**Comment by driesvints** [comment]
There are several breaking changes in this PR and there aren't any tests for this. Please send this to master with tests if you still want it to get merged in with a thorough explanation why this is needed (perhaps with some example code).

**Comment by if4lcon** [comment]
@driesvints OK here a real world example ... if you want to paginate and use sortBy you probably want to do this:

```php
Articles::paginate(20)->sortBy(function($item, $key) {
       return $item->isLiked ? 0 : $key;
});
```

but that won't apply it to the pagination it will only return your collection and leave you frustrated ....  and  after you give up you will do it like this

```php
 $perPage = 20
$pagianted_articles = Articles::paginate($perPage);

$articles = $pagianted_articles->sortBy(function($item, $key) {
       return $item->isLiked ? 0 : $key;
});

$articles = new LengthAwarePaginator($articles, $pagianted_articles->total(), $pagianted_articles->perPage());
```

this is just bad we already have a pagination instance but because we can't edit our items we have to make a new pagination instance  ... so my pull request will help artisans to do it the natural way like the first example 👍

```php
Articles::paginate(20)->sortBy(function($item, $key) {
       return $item->isLiked ? 0 : $key;
});
```

**Comment by if4lcon** [comment]
@driesvints do I need to make a new PR with tests ?? I'm not sure how to test it I need your help with this PR please .

**Pull request closed without merging**
