### PR TITLE
[11.x] feature/add_coalesce_function 

### PR DESCRIPTION
**Pull request by rmunate**
Hello devs,

I propose adding the `COALESCE` function to Laravel, which would be an excellent addition. `COALESCE` is a standard SQL tool widely used across different databases like Oracle, MySQL, and others. By integrating it into Laravel, it helps maintain clean and understandable code for developers familiar with standard SQL. Adding `COALESCE` to Laravel would enhance the development experience by adhering to recognized standards and simplifying the handling of null data in our queries.

```php
$value = coalesce($var1, $var2, $var3, ....);
```

### CODE REVIEW

**Comment by henzeb** [comment]
Interesting, I suggest support for callbacks using value() helper.

**Comment by PerryvanderMeer** [comment]
Why would I use this instead of `$var1 ?? $var2 ?? $var3`?

**Comment by rmunate** [comment]
> What are the benefits of this above `$var1 ?? $var2 ?? $var3`?

Hi Perry,

I hope you're doing well. Regarding your question, it primarily comes down to readability and the use of standard concepts. Just as we use standard terms in SQL, applying the same naming conventions and understanding their usage fosters standardization. Similarly, the ?? operator is perfectly fine for achieving an equivalent result.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

**Pull request closed without merging**
