### PR TITLE
[5.8] Replace global helper with container call in Exception Handler

### PR DESCRIPTION
**Pull request by antonkomarev**
As @crynobone noted in #29564 we could use container instead of global helper method.

### CODE REVIEW

**Review by driesvints — APPROVED** [review]

**Comment by taylorotwell** [comment]
Doesn't matter either way. This is within the foundation component.

**Comment by antonkomarev** [comment]
That seems strange to me, because we already have container instantiated, why should we reinstantiate it using global helper?

**Comment by deleugpn** [comment]
The container is a singleton and does not get reinstantiated with the global helper?

**Comment by antonkomarev** [comment]
Yes, but if it's already assigned in class field, why shouldn't we use it instead?

**Pull request closed without merging**
