### PR TITLE
[5.1] Add method_field() Helper Function

### PR DESCRIPTION
**Pull request by RomainLanz**
Hi,

This is just a simple helper to generate the special hidden field `_method` in a form.

I have literally no idea where are tests for helper functions, if someone tell me I'll create some.

### CODE REVIEW

**Comment by brunogaspar** [comment]
This method is already present https://github.com/RomainLanz/framework/blob/add_method_field/src/Illuminate/Foundation/helpers.php#L427-L438

**Comment by brunogaspar** [comment]
PR https://github.com/laravel/framework/pull/9477

**Comment by RomainLanz** [comment]
Your right, thanks.

**Comment by brunogaspar** [comment]
:+1:

**Pull request closed without merging**
