### PR TITLE
[6.x] Sorts listeners for output on the event:list command

### PR DESCRIPTION
**Pull request by arenowebdev**
As a developer I like to see the output of this command sort the event listener classes in alphabetical order so that they are easier to scan.

### CODE REVIEW

**Review by koenhoeijmakers — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
:-1: Very against this. The order they are displayed in is the order they are executed in. I think that is very important to know (say, if one crashes, you know what ran and what did not).

**Comment by netpok** [comment]
That's a good point, how about an option for it?
`php artisan event:list --sort`

**Comment by GrahamCampbell** [comment]
Hmm, I don't really see the point. One could just pipe the output into some unix tools to get it sorted.

**Comment by netpok** [comment]
Not really because event:list displays a table and events are only displayed for the first listener, otherwise its empty.

**Pull request closed without merging**
