### PR TITLE
[9.x] Add view data assertions to `TestView`

### PR DESCRIPTION
**Pull request by browner12**
- `assertViewHas()`
- `assertViewHasAll()`
- `assertViewMissing()`

these methods are all available on the `TestResponse`, but not currently `TestView`.  These assertions can be more helpful to test the workings of the component, and not reliant on how the data actually gets displayed on the view side of things.

### CODE REVIEW

**Comment by taylorotwell** [comment]
If this is a test view object, is it a bit redundant to say `assertViewHas` instead of just `assertHas`?

**Comment by jasonmccreary** [comment]
Tiny, tiny papercut, but if this is new code, I'd love to be able to check a piece of view data is explicitly `null` (as you can't in the current assertions since `null` is the default value and ignored).

**Comment by browner12** [comment]
this just got deployed today, so unfortunately can't change it now.

I'm trying to think how this would work, and AFAIK in PHP you can't tell if an argument is passed, or if it's using the default value.  I feel like we'd have to separate out a separate method for checking simply if the variable is passed, and one for if the variable has a specific value.

**Comment by jasonmccreary** [comment]
Yeah, no worries. Just something in the rare times I've actually passed in `null` as view data I thought could be improved.

I've seen other languages use a constant in this case. For example, Objective-C uses a `NOT_FOUND` constant when searching strings. Mimicing that, there could something like a `TestView::IGNORE_VALUE` which is the default - allowing `null` to be passed in separately.

**Comment by browner12** [comment]
very interesting.... I feel like this could be super beneficial in numerous places on the framework.

how do you check for the constant? aren't you still comparing by value? what value do you assign the constant?

**Comment by jasonmccreary** [comment]
Yes, its actual value could be a bit tricky as a simple value could pose the same problem. I suppose that's the benefit of a language constant.

Nonetheless, something random would have a lower hit rate than `null`. For example, `LARAVEL_CONSTANT_256`. 😂

**Pull request merged**
