### PR TITLE
[5.5] Added "software" as an uncountable word

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by BrandonShar** [comment]
This may be a nit-picky distinction, but should these be considered breaking changes? A few have been added lately, maybe it's time to think about a way to add these on a per-app basis?

**Comment by browner12** [comment]
does the break occur on things like guessing table names in models?

**Comment by BrandonShar** [comment]
Yes, it looks to me that it will. `Model@getTable` calls `Str::plural` which calls `Pluralizer::plural`.

**Comment by browner12** [comment]
i would agree then, yes technically these changes should go to master

**Comment by edmandiesamonte** [comment]
Assuming we have a model called `Software`, this is what we do since _software_'s plural form is still _software_
```
class Software extends Model {
    
    protected $table = 'software';
```

With this new change, the code above would still work. Unless otherwise, _softwares_ (with the 's') have already been used (i.e. in migrations), then it is really a breaking change.

Just my two cents.

Disclaimer: I authored a same PR for _firmware_ https://github.com/laravel/framework/pull/21306

**Comment by BrandonShar** [comment]
Sure, if you specify the table it's going to be fine, but I would guess most people don't do that. If you've been using a softwares table, it will break next time you update. 

As a followup, the `$uncountable` array in `Pluralizer` is already public, so there's no code change needed to modify it in a service provider on a per app basis.

**Pull request merged**
