### PR TITLE
[9.x] Added All Missing Facades Methods in Docblocks

### PR DESCRIPTION
**Pull request by foremtehan**
I managed to get/sort all the missing methods for facades ([script](https://gist.github.com/foremtehan/7640672bf3afe813efb725e98b9884d3)), Enjoy!

### CODE REVIEW

**Comment by driesvints** [comment]
This is going to be way too much for Taylor to review. I'm also not sure all of these are correct?

**Comment by foremtehan** [comment]
Lets taylor see this, I work on this for hours and you closed this in 2 minutes.

**Comment by marvin-wtt** [comment]
Maybe break it down into smaller PRs

**Comment by foremtehan** [comment]
@marvin-wtt i tried https://github.com/laravel/framework/pull/42970, But it misunderstood, i re-sorted them taylor taught i removed them i will try again.

**Pull request closed without merging**
