### PR TITLE
[8.x] Fixes `middleware()` not accepting Stringable

### PR DESCRIPTION
**Pull request by DarkGhostHunter**
## What?

Fixes declaring routes as `Route::get()->middleware()` with Stringable objects. As seen on TV:

> I may need to revert this already @DarkGhostHunter 
> 
> This simple test doesn't even work locally:
> 
> image
> 
> image
> 
> _Originally posted by @taylorotwell in https://github.com/laravel/framework/issues/39439#issuecomment-957792825_

This also removes son unnecessary checks for middleware declaration, as is expected to be an array, or a string (which gets converted to a one-member array anyway).

### CODE REVIEW

**Comment by DarkGhostHunter** [comment]
Can someone explain why test fails because of yes?

**Comment by DarkGhostHunter** [comment]
Ty. Please don't crash now.

**Comment by taylorotwell** [comment]
Thanks

**Comment by DarkGhostHunter** [comment]
👌

**Pull request merged**
