### PR TITLE
[5.5] remove the last few '\Illuminate\...' codes

### PR DESCRIPTION
**Pull request by johnlui**
This PR replaced the last few '\Illuminate\...' codes with \Illuminate\...Controller::class with all tests passed.

### CODE REVIEW

**Comment by bloggervista** [comment]
looks good. Ide friendly

**Comment by taylorotwell** [comment]
This is even longer than before?

**Comment by browner12** [comment]
> Length isn't all that matters!

🤣  never thought I'd see that in a PR.

**Comment by rs-sliske** [comment]
>This is even longer than before?

i always thought those emails were spam :o

**Comment by bloggervista** [comment]
Yeah I don't know if shorter is preferred or IDE friendly is preferred for such cases.

**Comment by deleugpn** [comment]
Import the class into the namespace to shorten it throughout the code.

**Pull request closed without merging**
