### PR TITLE
[5.5] Support composite primary key in Eloquent

### PR DESCRIPTION
**Pull request by matze-berg**
Allowed saving for multi column primary keys

### CODE REVIEW

**Comment by jmarcher** [comment]
The formatting does not match the rest of the framework.

Please provide tests for this new feature.

Better point this change to master

**Comment by mxframe** [comment]
Sorry, i am new to git and the commit stuff. I don't know how to provide tests.
But this code will work. It's just like the old one, the only difference is, that multiple primary keys (in an array) will be fetched and assigned now.

I can point it to the master, but the guidlines said, it should be pointed to the currrent version, because at th moment laravel is only working with a single primary key.

**Comment by jmarcher** [comment]
I mean you should provide some unit tests for the new feature, check inside the Illuminate\Tests\Database namespace for a guideline

What I meant with the master branch is that this PR makes big changes in the functionality.

**Comment by themsaid** [comment]
Please check this thread discussing your exact proposal, it contains some information that explains why this wasn't added to Eloquent: https://github.com/laravel/framework/issues/5355

Also a change like this requires tests to make sure it works.

**Comment by jlsjonas** [comment]
@themsaid I just came looking for related issues after seeing #5355 was locked **without** explaining why.

The only information in that issue is that it doesn't make sense to be excluded by default.

There are more than enough valid use-cases to support it, and it's also not that hard to implement it seeing certain comments.

It would be good if we could at least get a valid explanation why instead of "doubt it will ever happen" (even though a lot of people were/are willing to work on it)

Developers don't always pick the RDBMS they're working with. Should be supported at the very least for reading imho

**Comment by jlsjonas** [comment]
@taylorotwell @themsaid can you guys please give proper reasoning why this is rejected? composite keys are a **requirement** when dealing with real-world situations. Especially when having a system that works across countries/companies that need data from other systems. you keep pointing to #5355 which explains nothing at all. Seriously...

**Comment by reganjohnson** [comment]
+1 For what it's worth.
Would like to see this feature added to the framework.

**Comment by Chris25602** [comment]
+1 bump on this. I find it strange that both symfony & zend support this...and also the resistance by the main contributors is a little bewildering.

**Comment by mrsolarius** [comment]
Hey, It's possible to update your comit to laravel 6.2.
I know this is not officialy implement, but I use it in larael 5.5 and in new version they have issue with attributesToArray() function

**Pull request closed without merging**
