### PR TITLE
[8.x] The `isHtml()` method has been added

### PR DESCRIPTION
**Pull request by selcukcukur**
This seems to be the best way to check this right now.

### CODE REVIEW

**Comment by s-patompong** [comment]
It would return true only if I give it a string that starts with `<html` which basically is the HTML file itself, right?

Can we make it able to check other HTML tags as well? like <div, <p, etc.?

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
Thanks, but I feel this is neither robust nor necessary.

**Comment by selcukcukur** [comment]
> It would return true only if I give it a string that starts with `<html` which basically is the HTML file itself, right?
> 
> Can we make it able to check other HTML tags as well? like <div, <p, etc.?

You can use "strip_tags()" for this, it allows you to parse all html and php tags.

@GrahamCampbell I agree, too just tried my luck

**Comment by selcukcukur** [comment]
@GrahamCampbell Actually, there is one more way. I'm applying it soon...

**Comment by selcukcukur** [comment]
@GrahamCampbell 

See : https://www.php.net/manual/tr/class.tidynode.php

It is possible to take advantage of this basic plugin, but it is necessary to create a new class, so it is best to use it this way or not include it in the project at all.

**Comment by GrahamCampbell** [comment]
I am still 👎 on the concept. An HTML string is supposed to contain only HTML. Why is this method needed?

**Comment by selcukcukur** [comment]
> I am still 👎 on the concept. An HTML string is supposed to contain only HTML. Why is this method needed?

- When sending an email or sending an email string, we may want to check the type.
- Or if we are using a theme system, we can check if there is a valid html for it.
- Or if we are converting a markdown file to html, we can use it to check if it is html correctly.

But for very detailed controls, more additions are needed. I don't think it's a very good idea either. That's why this tiny method works.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
