### PR TITLE
[5.6] Adds --api flag to make:controller

### PR DESCRIPTION
**Pull request by OzairP**
👋 

## Synopsis
This PR allows developers to add the `--api` flag when running the `make:controller --resource` command in Artisan. This is useful for creating API resource routes via `Route::apiResource(...)`.

## Reasoning
Currently the `--resource` flag adds CRUD methods plus two additional methods for viewing forms for creating and updating. The `--api` flag along with the `--resource` flag will remove the two additional methods which are not needed for REST end points.

This is a QoL PR so developers won't have to create resource controllers, find and open the file, then find the appropriate methods to remove.

## Breaking Changes
**This PR introduces no breaking changes**. This will only affect future code generations should the invoker decide to opt in with the `--api` flag.

## Testing
This PR also includes tests for
* `make:controller` (plain)
* `make:controller --resource`
* `make:controller --resource --parent=...`
* `make:controller --resource --api`
* `make:controller --resource --api --parent=...`

I believe this is the firsts suite of tests to test Artisans code generation, so this somewhat sets a standard on how they should be tested. If anyone have any suggestions on how to improve the assertions please let me know 😄 .

(Extends from https://github.com/laravel/framework/pull/22920)

### CODE REVIEW

**Comment by stefanoruth** [comment]
How about using the --api without --resource can that be done too?

**Comment by taylorotwell** [comment]
Can you remove all of those assertions files and such. It just looks like a bunch of duplicated stuff - I'm not sure how valuable that actually is.

**Comment by OzairP** [comment]
@stefanoruth @36864 I agree, I would prefer to have done `--resource=api`, but I suppose I was following the current track of how flags are being added, like --parent.

@taylorotwell I agree that the assertion files are code duplication. You did ask for me to add some tests from my last PR so this is the only way I saw of writing the integration test cleanly. Would you like me to remove all the tests or figure out a different way of testing it?

**Comment by taylorotwell** [comment]
Just remove all the tests and I'll work on it.

**Comment by OzairP** [comment]
I'm looking forward to see your strategy on testing this.

**Pull request merged**
