### PR TITLE
[7.x] Stop returning void

### PR DESCRIPTION
**Pull request by lucasmichot**
We should clearly differentiate `null` from `void` results.
This PR ensures that we stop returning `void`.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Meh, this really doesn't matter. Both a void and null function actually evaluate to null when you call them and look at the result.

**Comment by GrahamCampbell** [comment]
The only thing this PR does is risk breaking code that depended on an incorrectly documented void return?

**Comment by lucasmichot** [comment]
> The only thing this PR does is risk breaking code that depended on an incorrectly documented void return?

??
not at all

Not a single docblock has been modified...

**Comment by GrahamCampbell** [comment]
> Not a single docblock has been modified...

**Comment by GrahamCampbell** [comment]
> Not a single docblock has been modified...

I know. I am saying that if our existing phpdoc has any errors, then your PR will break something, and it's not that unlikely that there are errors, so this is risky.

**Pull request closed without merging**
