### PR TITLE
Proposal: elixir helper should return a full url.

### PR DESCRIPTION
**Pull request by vluzrmos**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is BC break.

**Comment by franzliedke** [comment]
How is this breaking? It fixes a bug for some people, I believe.

**Comment by ibrasho** [comment]
@franzliedke Someone might be depending on the current behaviour.

If `elixir()` is not generating the correct url, you can always use `url(elixir())`.

**Comment by lukasgeiter** [comment]
@vluzrmos Just send the PR to `master` and it should have a better chance of getting merged.

**Comment by franzliedke** [comment]
@ibrasho You mean manually prepending the base URL?

**Comment by vluzrmos** [comment]
I think that is uggly, my PR just prepend de base url inside elixir helper.

**Comment by phanan** [comment]
@ibrasho @franzliedke This change won't break if the developer is using `url(elixir())`, since `url()` is smart enough to not mess with a full URL. If will, though, if he is manually prepending the base URL.

**Pull request closed without merging**
