### PR TITLE
[5.5] Revert dynamic eval call

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Since Laravel 5.5 is PHP 7.0+, then functions of this name are fine.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Isn't the __call still needed to fallback to ->command()?

**Comment by GrahamCampbell** [comment]
Hmm, well, I just directly reverted the two commits.

**Comment by GrahamCampbell** [comment]
Actually, no, that method is not required, because the __call method is already defined on the parent class. I'll update the 5.4 implementation to call the parent method to avoid this confusion.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/pull/17366

**Pull request merged**
