### PR TITLE
[5.1] [Should be 5.0] Let a collection get keyed by a closure

### PR DESCRIPTION
**Pull request by lucasmichot**

### CODE REVIEW

**Comment by JosephSilber** [comment]
I think this would be cleaner:

```php
public function keyBy($keyBy)
{
	if ( ! $keyBy instanceof Closure)
	{
		return $this->keyBy(function($item) use ($keyBy)
		{
			return data_get($item, $keyBy);
		});
	}

	$results = [];

	foreach ($this->items as $item)
	{
		$results[$keyBy($item)] = $item;
	}

	return new static($results);
}
```

**Comment by lucasmichot** [comment]
Indeed @JosephSilber

**Comment by GrahamCampbell** [comment]
Please squash to one commit.

**Comment by djtarazona** [comment]
:+1:

**Comment by JosephSilber** [comment]
@lucasmichot Actually, we already have the `valueRetriever`.

Use that instead:
```php
public function keyBy($keyBy)
{
    if ( ! $keyBy instanceof Closure)
    {
        return $this->keyBy($this->valueRetriever($keyBy));
    }

    $results = [];

    foreach ($this->items as $item)
    {
        $results[$keyBy($item)] = $item;
    }

    return new static($results);
}
```

**Comment by JosephSilber** [comment]
@taylorotwell will this make it into 5.0?

**Pull request merged**
