### PR TITLE
[5.3] PDO::ATTR_CASE / pagination (#15668)

### PR DESCRIPTION
**Pull request by TWITConsulting**
Pagination fix: If PDO::ATTR_CASE is used as db-option respect this setting when retrieving aggregate for pagination

### CODE REVIEW

**Comment by taylorotwell** [comment]
Lower case is the convention in Laravel.

**Comment by GrahamCampbell** [comment]
@taylorotwell The problem is the oracle database doesn't allow lowercase here I think?

**Comment by TWITConsulting** [comment]
Might be - but if you set the PDO:ATTR_CASE to upper case in the database connections options for some reasons the current code won't work, as the "aggregate" field in the result object is transformed to an upper case named field.

Specifying the PDO:ATTR_CASE seems to be a valid option within the database connection set up in the database.php / .env.

For example at our company we are using the upper case setting as we are doing this in all projects (not only Laravel/Lumen based ones)

**Comment by GrahamCampbell** [comment]
Ok, so what Taylor is saying is Laravel is intentionally being opinionated so you can't do that.

**Comment by TWITConsulting** [comment]
...means using a valid PDO-option should break the paging?

**Comment by taylorotwell** [comment]
We can document that we don't support that option.

**Comment by egoisticalgoat** [comment]
We needed to use that option because our testing environment used a MySQL database, which returned the attributes in uppercase, but the production environment used a Oracle database, which returned them in lowercase by default. Not using that option would mean changing 1000+ lines of code just for switching between environments.

**Comment by TWITConsulting** [comment]
@taylorotwell This seems for me the worst option available: Instead of fixing a bug (breaking up a functionality by using a correct configuration is for me a bug, clearly) changing the documentation.

But if you change the documentation you must also change the current code - the return statement of the function must be changed to ensure code consistency:

`return (int) array_change_key_case((array) $item)['aggregate'];`

This return statement will be used if the result from the aggregate-select is returned as array. This return statement means also: If the column names in the result are not lower cased  array_change_key_case() will rename the columns to lower case. So for me that means in context of the current code:

- If the database driver returns columns as lower case the function/pagination works as expected
- If the database driver returns column names as natural string (as they appear within the database) or as upper case but the whole result is an array it works as the array_change_key_case() within the return-statement will convert those names
- If the database driver returns column names as natural string (as they appear within the database) or as upper case but the whole result is an object it won't work as the function in the current implementation assumes the column names are lower cased.

Logical consequences might be (regarding code consistency):

- The function will convert the column names to lower case names in every of those cases so the function will work with every configuration regarding the case of the names
- The function won't convert the column names in any case (so also when an array is returned the function should not transform column names)

Doing A in some cases and B in other cases seems not be an good option as a framework should be flexible and not require a very specific configuration (assuming that in object mode the column names must be lower cased and in array mode the column naming does not matter is a specific configuration requirement)

**Pull request closed without merging**
