### PR TITLE
[4.2] Improved The "exists" Function

### PR DESCRIPTION
**Pull request by irfanevrens**
adding a limit(1) is usefull for control of existence and can be find it 1 step in db.

### CODE REVIEW

**Comment by JosephSilber** [comment]
@irfanevrens I'm not sure I understand the motivation behind this change.

Is it to somehow optimize the query?

If so, I don't see how it does. Adding a `limit` clause to a `count()` query *does not* limit the results counted.

You can try it yourself on any database you have:

```sql
select count(*) from users limit 1
```

The result will be the full count of the number of users found in the database. The `limit` clause only affects the total number of records returned, not the amount being counted.

**Comment by lol768** [comment]
I guess this could be achieved with a nested select instead?

```sql
SELECT COUNT(*) FROM (SELECT * FROM `users` LIMIT 1);
```

Not sure this is going to be any faster than counting them all, though.

**Comment by JosephSilber** [comment]
No need to count:

```sql
select * from (select 1 from users limit 1)
```

**Comment by JosephSilber** [comment]
Or you could use a real `EXISTS`

**Comment by lol768** [comment]
> No need to count:
```sql
select * from (select 1 from users limit 1)
```

That's neat, didn't think about doing it like that.

> Or you could use a real SELECT EXISTS (SELECT ...)

Seems to work pretty well with MySQL - is that universally possible though? Can I do it in SQLite or SQL server?

**Comment by jaketoolson** [comment]
Related : https://github.com/laravel/framework/pull/9627

**Pull request merged**
