### PR TITLE
[11.x] Read XSRF-TOKEN Directly from Cookie

### PR DESCRIPTION
**Pull request by kostamilorava**
### Description:

I propose enhancing the XSRF token retrieval process to also read the XSRF-TOKEN directly from the cookie if the input or header does not contain the token.

### Rationale:

There are numerous cases where users encounter errors related to missing XSRF tokens because they don't understand the current mechanism. Even if the header is set, the cookie contains the same data. By reading the XSRF-TOKEN directly from the cookie, we simplify the process and reduce potential errors.

### Benefits:

- Improved Reliability: Ensures the token is always retrieved, reducing the chance of missing token errors.
- Simplicity: Cookies are already decrypted at this point, eliminating the need to pass the token through a decryptor (as it's done for header).
- Tested Solution: I have tested this approach on two projects, and it works seamlessly.

### CODE REVIEW

**Comment by rodrigopedra** [comment]
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#storing-the-csrf-token-value-in-the-dom

> A CSRF token can be included in the <meta> tag as shown below. All subsequent calls in the page can extract the CSRF token from this <meta> tag. It can also be stored in a JavaScript variable or anywhere on the DOM. ***However, it is not recommended to store the CSFR token in cookies or browser local storage.***

**Comment by kostamilorava** [comment]
Yes, but Laravel already stores it inside cookies. It's not about storing, it's about reading it from the cookie. If we follow that link, Laravel should remove the csrf-cookie endpoint, that sets cookie with the name XSRF-TOKEN.

I think Laravel comply this OWASP recommendation by encrypting CSRF token and storing it encrypted in cookies.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by Krisell** [comment]
> Yes, but Laravel already stores it inside cookies. It's not about storing, it's about reading it from the cookie. If we follow that link, Laravel should remove the `/csrf-cookie` endpoint, that sets cookie with the name XSRF-TOKEN.

The CSRF token must be submitted to the server in another way than via a cookie, as its purpose is to show that the request is first-party, and not initiated from a third party (which may still carry cookies depending on settings). See the OWASP page for more information about the kind of attacks the CSRF token prevents.

The XSRF Laravel cookie is simply a convenience feature, and is only used in the direction from the server to the client. It is used because client libraries like `axios` automatically pick up the cookie value and send is as request headers (an example of "another way", as post data is also valid).

**Pull request closed without merging**
