### PR TITLE
[5.3] Make collection generator command

### PR DESCRIPTION
**Pull request by browner12**
because collections are awesome.

### CODE REVIEW

**Comment by browner12** [comment]
not sure if i did this right. i never know if i'm syncing my fork to the upstream correctly. any suggestions would be appreciated if i didn't.

**Comment by browner12** [comment]
do we care if it passes on 7.1 yet?

**Comment by GrahamCampbell** [comment]
PHP 7.1 is segfaulting. We need to contact the release manager at some point to let them know.

**Comment by taylorotwell** [comment]
Probably will hold off on this PR. I'm not totally sure it's a use case that happens often enough to warrant a generator at this point. Thanks.

**Comment by browner12** [comment]
thanks for considering it. One thing I think would be cool with it is similar to how we can `php artisan make:model --migration`, we could append on `php artisan make:model --migration --collection`.  maybe this is more of an interesting use case.

**Pull request closed without merging**
