### PR TITLE
[5.4] Add isSoftDeleting() method

### PR DESCRIPTION
**Pull request by Propaganistas**
As requested in https://github.com/laravel/framework/pull/17189#issuecomment-272025780

### CODE REVIEW

**Comment by taylorotwell** [comment]
I guess I don't totally understand. Why would isSoftDeleting return `true` if I'm not actively deleting the model. I guess I don't see the use case for this?

**Comment by Propaganistas** [comment]
I'm suggesting a method to check in a safe way if a model soft deletes. Currently you'd have to do something like `method_exists($this, 'bootSoftDeletes')` or check trait implementation using `class_uses()`. Since there's already a safeguard method for `forceDelete()`, I thought it could be beneficial to also allow checking of existence of the SoftDeletes trait as well. I actually encountered the code case mentioned below quite some times.

Guess it'll probably need a rename to `softDeletes()`?

```php
trait SomeTrait {

    // This trait inherently doesn't know if its implementing model uses SoftDeletes in advance.
    protected function bootSomeTrait()
    {
        if (method_exists(static::class, 'bootSoftDeletes')) {
            static::restored(function() { // });
        }
    }
}
```
vs
```php
trait SomeTrait {

    // This trait inherently doesn't know if its implementing model uses SoftDeletes in advance.
    protected function bootSomeTrait()
    {
        if (static::softDeletes()) {
            static::restored(function() { // });
        }
    }
}
```

**Comment by Propaganistas** [comment]
Oops, sorry for closing accidentally.

**Comment by GrahamCampbell** [comment]
Probably needs to go to 5.5.

**Comment by Shkeats** [comment]
@Propaganistas Would suggest that you call the method isSoftDeletable(). isSoftDeleting sounds like you are checking if the model is currently being deleted.

**Comment by taylorotwell** [comment]
No plans on this right now.

**Comment by Propaganistas** [comment]
@Shkeats I don't tend to agree. You would at least need `class_uses_recursive()` to accommodate to all use cases. And in that regard the following is more performant:

```php
return method_exists(static::class, 'bootSoftDeletes');
```

Anyhow, this PR is closed.

**Pull request closed without merging**
