### PR TITLE
[9.x] Added a superior & inferior clauses to the query builder

### PR DESCRIPTION
**Pull request by Julian-Louis**
Hello,
In the course of my work, I had to implement multiples times numeric comparison between values in where clauses.
I thought it might be useful to others and I would love to contribute to the Laravel community.
Have a great day!

### CODE REVIEW

**Comment by dennisprudlo** [comment]
Maybe a macro would be better for this case?

If this gets merged (I would suggest to rename the functions to `whereGreaterThan` and `whereLessThan`) there will be PRs for every other case like what about those:
- `orWhereGreaterThan` (`or column > value`)
- `orWhereLessThan` (`or column < value`)
- `whereGreaterThanOrEquals` (`and column >= value`)
- `whereLessThanOrEquals` (`and column <= value`)
- `orWhereGreaterThanOrEquals` (`or column >= value`)
- `orWhereLessThanOrEquals` (`or column <= value`)

**Comment by Julian-Louis** [comment]
Thank you for your macro tip.
I agree with whereGreaterThan but regarding whereLessThan, how about whereLowerThan instead ?
Let's see what the community feels about it !

**Comment by dennisprudlo** [comment]
> how about whereLowerThan instead?

I would still use "less" in that case, since it is the name for the `<` comparison in mathematics and is widely adopted in programming (See the MySQL docs for reference: https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html)

**Comment by Julian-Louis** [comment]
Okay, sorry, you're right

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
