### PR TITLE
[5.4] Use ::class notation

### PR DESCRIPTION
**Pull request by lucasmichot**
Use `::class` notation.

---

**Notes:**

- This PR only apply to `/src` code.
- Some FQN were let as it on purpose.
- This PR should probably be passed just before `5.4` first release.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Not sure it makes sense to make this change for little merit.

**Comment by lucasmichot** [comment]
Well, it's more about consistency, as for #17148. Not sure this PR will be merged though
I let it open and WIP to include some other commits if necessary, up to Taylor to merge it just before 5.4 release if he feels so

**Comment by alexbowers** [comment]
@GrahamCampbell Just my 2¢; but the ability to click through on an IDE to a class (which ::class allows but, but a string doesn't), is quite useful.

I'd very much like it to be a standard part going forward if possible.

**Comment by TommyC81** [comment]
What @alexbowers said, anything that lets us take advantage of external functionality is helpful.

**Pull request merged**
