### PR TITLE
Save the types in enum and then give an error if you enter the wrong type

### PR DESCRIPTION
**Pull request by DevNull-IR**
Save the types in enum and then give an error if you enter the wrong type

### CODE REVIEW

**Comment by milwad-dev** [comment]
Is that support for php 8.0?

**Comment by DevNull-IR** [comment]
> 8.0?

No, 8.1 PHP [Documentation](https://www.php.net/manual/en/language.enumerations.overview.php)

**Comment by milwad-dev** [comment]
Laravel support php 8.0. 
You can add this commit for Laravel [10.x].

https://github.com/laravel/framework/blob/9.x/composer.json#L18

**Comment by DevNull-IR** [comment]
> Laravel support php 8.0. You can add this commit for Laravel [10.x].
> 
> https://github.com/laravel/framework/blob/9.x/composer.json#L18

Oh! Yes thankyou!.

**Comment by DevNull-IR** [comment]
> Laravel support php 8.0. You can add this commit for Laravel [10.x].
> 
> https://github.com/laravel/framework/blob/9.x/composer.json#L18

Oh! Yes thankyou!.

**Pull request closed without merging**
