### PR TITLE
[5.6] Improvements

### PR DESCRIPTION
**Pull request by carusogabriel**
Together with PHPStorm and https://github.com/kalessil/phpinspectionsea, here are some improvements that we can make to Laravel, such as unnecessaries parentheses, casts; plus equal operator usage; stripos instead of strpos + strtolower, etc

### CODE REVIEW

**Comment by 36864** [comment]
Are there any benchmarks that show `stripos()` is actually faster than `strpos(strtolower())?

**Comment by raul3k** [comment]
@browner12 removing some casts seems like an improvement because casting something we are sure that is already in the type we want is redundant, like: $array = (array) array_map(), or casting (int) to an int. That can make the code more concise, more readable and simpler.
Thats IMO.

**Comment by taylorotwell** [comment]
I try to avoid big PRs like this without clear, measurable benefit.

**Comment by browner12** [comment]
i'll try and run some benchmarks on the `stripos` changes next week. Intuitively, that one **should** be an improvement.

**Comment by X-Coder264** [comment]
How is this a "big" PR? 😕

**Comment by devcircus** [comment]
Even though the changes may seem small, it touches a lot of files, which in turn, could affect a lot of different areas of the framework:

photo jul 06 4 36 27 pm

**Comment by X-Coder264** [comment]
95% of the changes in the PR are just removing unnecessary brackets and casts (which cannot affect anything). The only "bigger" change (which in itself is also a really small change) is the `strpos(strtolower()` to `stripos`.

**Comment by antonkomarev** [comment]
I think be best way will be write benchmarks to compare `strpos(strtolower()` and `stripos`. This is the most important part of this PR. Then if benchmark will show any speed improvements it could be pushed as new PR.

**Comment by EdgarSedov** [comment]
Actually, all of changes make code much cleaner, simplier and more readable. The onlyarguable parts is `stripos`. removing unnecessary casts will definitely not make perfomance worse

**Comment by deleugpn** [comment]
@EdgarSedov

> Actually, all of changes make code much cleaner [...]

To whom?

**Comment by EdgarSedov** [comment]
@deleugpn 

> To whom?
To everyone. Pointless type casting and useless parentheses cannot add readability a priori

**Comment by browner12** [comment]
> 95% of the changes in the PR are just removing unnecessary brackets and casts (which cannot affect anything).

famous last words of a programmer... 😆

**Pull request closed without merging**
