### PR TITLE
fix for single line @php statements but also for multi-line @php with parentheses and @endphp

### PR DESCRIPTION
**Pull request by rikvdh**
I've changed the regex to work a bit different. At first we had a negative lookahead on the parentheses. But as seen in #45388, people actually use parentheses which makes it look like a single-line statement instead, but then include the `@endphp`. Since the  regex was greedy and ate other `@php`-statements in the process of searching for full blocks it didn't work.

I've added another test and change the regex to be omitting possible other `@php`-blocks making only the `@php/@endphp` pairs really working.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Tests failing.

**Comment by rikvdh** [comment]
Sorry I noticed. I need to continue breaking my head some more on that regex..

**Comment by donnysim** [comment]
To be fair I think https://github.com/laravel/framework/issues/45388 uses the `@php` incorrectly, if you put brackets you don't put `@endphp`

```blade
@php (
    $classes = [
        'admin-font-mono', // Font weight
    ])
@endphp
```
should be 
```blade
@php
    $classes = [
        'admin-font-mono', // Font weight
    ]
@endphp
```
with his version even the IDE complains that something is wrong and it's missing an opening statement because of how it perceives the usages

**Comment by rikvdh** [comment]
@donnysim I agree, but it breaks past behavior and this makes all cases work. If you put `@endphp` or not.

**Comment by donnysim** [comment]
But is it worth fixing framework for someones bad code? Maybe this could be moved to 10.x as a breaking change?

**Comment by rikvdh** [comment]
@donnysim I leave that up to maintainers to decide. I would like a fix in 9.x as well since I've now faced my earlier issue a couple of times. The past behaviour of `@php(..)` was a bit buggy depending on its surroundings.

**Comment by donnysim** [comment]
@rikvdh I'm kind of confused here, I just tried
```blade
@php(
    $hello = 'Hello World'
)
@endphp

{{ $hello }}
```

and got 
```
Illuminate\View\ViewException : Undefined variable $hello (View: F:\Laragon\boilerplate\resources\views\render.blade.php)
```

how is his code working then? 🤔 if I use that variant without echo it prints me the php code instead of a blank string as it should

**Comment by rikvdh** [comment]
> @rikvdh I'm kind of confused here, I just tried
> 
> ```
> @php(
>     $hello = 'Hello World'
> )
> @endphp
> 
> {{ $hello }}
> ```
> 
> and got
> 
> ```
> Illuminate\View\ViewException : Undefined variable $hello (View: F:\Laragon\boilerplate\resources\views\render.blade.php)
> ```
> 
> how is his code working then? 🤔 if I use that variant without echo it prints me the php code instead of a blank string as it should

Woah.. I was going to say: 'I dont know'. But if you put a space before the opening parenthesis ot works. ;-)

Apparently there is a difference between
```php
<?php (
    $hello = 'Hello World'
)
?>

<?php echo e($hello); ?>

and 
```php
<?php(
    $hello = 'Hello World'
)
?>

<?php echo e($hello); ?>
```

probably some weird PHP scoping thing. I've not bothered to investigate any further, but with the parenthesis adjacent it seems that the variables are scoped. This is also current behavior without my fix.

**Comment by donnysim** [comment]
Yeah, the space makes it a full php opening and closing match 😅 so the whole statement got confusing. IDE also doesn't recognize it as a separate case which got me more confused that it should. Kind of seems like a gnarly case to crack using regex.

**Comment by rodrigopedra** [comment]
If you always keep a space after the PHP opening tag, it should work.

```php
return $this->storeRawBlock("<?php {$matches[1]} ?>");
```

*added a space before the closing tag for symmetry only*

**Comment by rikvdh** [comment]
@taylorotwell Why did you mark it as a draft? imo this is done.

**Comment by taylorotwell** [comment]
Honestly I don't have any appetite to change this and make the regex more complicated and potentially have another breaking change. The issue isn't that important to me nor is it a pressing issue in the Laravel community.

**Comment by rikvdh** [comment]
@taylorotwell I don't see how this is breaking in its current form. imo the current behavior is buggy and needs fixing.

**Comment by caendesilva** [comment]
Just chiming in here that I also think this feels like a bug. It's rather unexpected to me that you can't use both single-line and multi-line directives. Maybe a note should be added to the docs. I'd be happy to do it if it's desired.

**Pull request closed without merging**
