### PR TITLE
[5.6] Changing Auth stubs for Bootstrap v4

### PR DESCRIPTION
**Pull request by rsm23**
Changing Auth stubs for Bootstrap v4

### CODE REVIEW

**Comment by devcircus** [comment]
Is there a particular reason for removing the id attributes on the inputs?

**Comment by Dylan-DPC** [comment]
This is a breaking change and it could break a user's layout. Better to target 5.6

**Comment by dwightwatson** [comment]
This was handled by #22494

**Comment by GrahamCampbell** [comment]
Thanks for the contribution @rsm23, but it seems this change has already been made on master, in preparation for the Laravel 5.6.0 release.

**Pull request closed without merging**
