### PR TITLE
[10.x] Add createIfNotExist Method to Schema Facade

### PR DESCRIPTION
**Pull request by tgozo19**
This pull request introduces a new method, `createIfNotExist`, to the Schema Facade. 

The existing `create` method in the Schema Facade allows us to create tables using the following syntax:

```php
Schema::create('users', function (Blueprint $table) {});
```

However, if we attempt to run another migration to create a table that already exists, it results in a failure. 

To address this issue, the `createIfNotExist` method has been added. This method first checks if the table already exists before attempting to run the migration. If the table exists, it does not throw an error. Instead, it informs the user that the table already exists, exits the current migration, and continues to run any subsequent migrations.

This enhancement improves the robustness of database migrations and provides better feedback to the user during the migration process.

### CODE REVIEW

**Comment by hafezdivandari** [comment]
No need a new Schema method for this, it can be done much easier with a new `Blueprint` fluent command, just like we already do with `$blueprint->temporary()`:

https://github.com/laravel/framework/blob/5e444ac8b9f2e39ded13248cc2e91c82ee162691/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L126

Something like this:

```php
Schema::create('users', function (Blueprint $table) {
    $table->ifNotExists();

    $table->id();
    $table->string('name');
});
```

**Comment by tgozo19** [comment]
Thanks for the contribution @hafezdivandari. Does this actually exist?

```php
Schema::create('users', function (Blueprint $table) {
    $table->ifNotExists();

    $table->id();
    $table->string('name');
});
```

**Comment by hafezdivandari** [comment]
@tgozo19 MySQL, SQLite and PostgreSQL support this syntax:

```sql
CREATE TABLE foo IF NOT EXISTS ...
```

It's easy to implement this on Laravel.

**Comment by tgozo19** [comment]
Now I have added a 3rd parameter to Schema::create(). the parameter is optional and should either be true or false. It's default value is false. If set to true then we will check if the table already exists before attempting to run the migration. If the table exists, it does not throw an error. Instead, it informs the user that the table already exists, exits the current migration, and continues to run any subsequent migrations.

For it to work as intended it should be used like this

```php
Schema::create('posts', function (Blueprint $table) {}, true);
```

**Pull request closed without merging**
