### PR TITLE
[5.3] [WIP] Add InteractsWithMail trait

### PR DESCRIPTION
**Pull request by sileence**
Usage (working so far):

```
        $this->seeMail(function (Mail $m) {
            $m->to('admin@styde.net')
              ->subject('Please confirm your email');
        });
```

You can assert the body of the mail contains a link in HTML:

```
        $this->seeMail(function (Mail $with) use ($url) {
            $with->htmlLink($url);
        });
```

Type hinting the variable in the closure gives you IDE auto completion.

---

I really like this, but I'd like some feedback as well.

### CODE REVIEW

**Comment by CristianLlanos** [comment]
I really like your approach. Would you be so kind as to add some DocDlocks for InteractsWithMail and Mail classes, please?

**Comment by sileence** [comment]
@CristianLlanos yes, of course, once this is approved I'll add all the docs, etc. And many more methods.

**Comment by taylorotwell** [comment]
Can you not use the Mailable spys?

**Comment by sileence** [comment]
@taylorotwell yes, however (and please correct me if I'm wrong) but that fake doesn't test that the view was generated or other characteristics like the from address or the subject, and it doesn't work outside of the mailable interface. While this catches the swift message just before it is sent and let you test things in more detail.

**Comment by taylorotwell** [comment]
Personally I wouldn't test it this way. I would just create a new mailable instance, call the ->build() method and then inspect the mailable to see that the proper data is set on the instance.

**Comment by sileence** [comment]
Well I'm using this method (and the other one I PR) in this test:

```
        // ...
        $token = $this->seeAndGetInDatabase('tokens', [
            'email' => 'admin@styde.net'
        ]);

        $tokenUrl = route('token', $token);

        $this->seeMail(function (Mail $with) use ($tokenUrl) {
            $with->to('admin@styde.net')
                ->htmlLink($tokenUrl);
        });

        // ...
```

I'm testing that I generate a token and that the token URL is sent to the user's email.

With the fake I can test that I'm triggering the mailable, and I can then unit test the mailable, but I don't see a way to describe the full feature that the token needs to be sent to the user's email. Because I could forget to send the URL or send a wrong one, etc. 

Anyway, I'm just PR something I find useful for my projects, but it's your call.

**Comment by taylorotwell** [comment]
I would rather not take this approach. I would rather try to have test helpers around Mailables that after you call the `build` method you can inspect the view / data / subject, etc. and verify it is all correct.

**Pull request closed without merging**
