### PR TITLE
[5.4] Some refactoring on Eloquent builder

### PR DESCRIPTION
**Pull request by themsaid**
Extracted a new method that'll create a new model instance and set the connection to the same connection of the Builder instance:

```
public function newModelInstance($attributes = [])
{
    return $this->model->newInstance($attributes)->setConnection(
        $this->query->getConnection()->getName()
    );
}
```

Refactored the areas where this logic used to happen to call the method instead.

+ some minor docblock fixes.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks

**Comment by gabrielkoerich** [comment]
@themsaid This commit introduced something a bug in my tests, if I create a model just using `new Model()` and `save()`, the connection is null, so all my comparisons using `$model->is(...)` doens't work anymore. Maybe we should use this new method in save() too? I don't know.

**Comment by themsaid** [comment]
@gabrielkoerich I don't think this commit made a change to the code, we just extracted part of the code in a method.

**Comment by gabrielkoerich** [comment]
@themsaid Yeap, that's weird. It was something between 5.4.18 and 5.4.19, and the only commit that changed something with connections was this one... Do you know what else could it be? Thanks.

**Comment by gabrielkoerich** [comment]
@themsaid I end up calling `fresh()` after creating the model and it's working.

**Pull request merged**
