### PR TITLE
Update Model.php $exists

### PR DESCRIPTION
**Pull request by mavsan**
Anyone from outside the model can change the property of $exists. I have to be sure that the record exists in the database.
~~~
$model = new User();
$model->exists = true;
function someMethod($model)
{
      if($model->exists)
      {
      // wrong!
      }
}
~~~

### CODE REVIEW

**Comment by browner12** [comment]
while I personally don't think this change is necessary, at a minimum you should probably make the property `protected` instead of `private` so your child models have access to this property.

**Comment by themsaid** [comment]
@mavsan tests fail

**Comment by bobbybouwmann** [comment]
`isExists()` doesn't seem to be a nice name for the method. Why not use `exists()`?

**Comment by fernandobandeira** [comment]
Most of the tests are failing because they can't check for exists anymore, you need to change them to ``` isExists() or exists() ```, however there's also another issue, check the following line:

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Model.php#L493

You'll need to address this one properly...

**Comment by shadoWalker89** [comment]
How about making `exists` property `protected` and add an accessor. 
This way People will be able to keep using `$model->exists` in their code

**Comment by taylorotwell** [comment]
No plans to change this on a minor release especially. I personally am not too keen on that kind of "protection" as a programming philosophy in general either. I could still change exists, it's just harder.

**Pull request closed without merging**
