### PR TITLE
[7.x] Adds notification stub from project stubs

### PR DESCRIPTION
**Pull request by peterfox**
Allows for custom stubs to be added to a project for Notifications. My projects, like I'm sure a few peoples will, uses custom logic in notifications which becomes a part of the boiler plate each time so it would be really useful to have the ability to customise per project.

I've not added the stub to the `stubs:publish` command but am happy to do so if required.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. Why do this for the notifications, but not the others?

**Comment by peterfox** [comment]
@GrahamCampbell I'm happy to go and make this work for all others but realistically wasn't sure if there was a reason for only some being included in the first place.

The main reason I think notifications should be added is because I often find I need to extend the MailMessage class in projects so using that extended class in a stub would be good but also I often find myself implementing the channel methods or rewriting the `via` method to have some bespoke logic for switching channels in and out on a per project basic. Having a stub customised for this in a project would be far more useful to me than any of the others so far so I was surprised when it wasn't available to override.

That said if you want me to through and do the other stubs that are yet to be added I don't mind as long as I know it's a wanted feature that'll get merged?

**Comment by taylorotwell** [comment]
Place holders weren't updated to match other stubs.

**Comment by peterfox** [comment]
@taylorotwell sorry, I'm not quite sure what you mean by that?

**Pull request closed without merging**
