### PR TITLE
[8.x] Accept callable and listener class names as batch handler functions

### PR DESCRIPTION
**Pull request by halaei**
Batch is using closures for then, catch, finally handlers. Because I was afraid serializing closures might have some limitations, I thought it is not a bad idea to allow to users the feature without closure serializations.
This PR is trying to let users to use php-serializable callables  as well as listener classes for handlers:

```php

Bus::batch([
    new ProcessPodcast(Podcast::find(1)),
    new ProcessPodcast(Podcast::find(2)),
    new ProcessPodcast(Podcast::find(3)),
])->then(SomeListener::class)
->catch([SomeClass::class, 'staticFunction'])
->finally('someFunctionName')
->dispatch();

class SomeListener
{
    function __construct(Batch $batch) {
        //...
    }
    function handle() {
        //...
    }
}
class SomeClass {
    static function staticFunction(Batch $batch, Throwable $e) {
        //
    }
}
someFunctionName(Batch $batch, Thrwoable $e = null) {
    //...
}

```

Let me know if you agree with this.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I think that's probably fine. Do you know why tests are failing?

**Comment by halaei** [comment]
No. But I will take a look at it soon.

**Comment by halaei** [comment]
This invoke also works:
```php
    protected function invoke($handler, Batch $batch, \Throwable $e = null)
    {
        if (is_callable($handler)) {
            call_user_func($handler, $batch, $e);

            return;
        }
        dispatch(new $handler($batch, $e));
    }
```

**Comment by driesvints** [comment]
Hey @halaei. Can you pay attention to our coding standards with the next prs? We use FQN, extra spaces in DocBlocks and white lines after `if` statements. I've fixed these for you now.

**Comment by halaei** [comment]
@driesvints Sure thanks.

**Comment by mfn** [comment]
> We use FQN, extra spaces in DocBlocks and white lines after `if` statements.

FTR, there is https://laravel.com/docs/7.x/contributions#coding-style but except showing how code "looks", it doesn't "describe" it.

I think especially the FQN is easy to miss as this is, compared to a lot of OSS PHP code I read, rather the exception as most are using imports.

Just wanted to mention it 😄

**Comment by driesvints** [comment]
@mfn I think if you scan the rest of the code in a file it's pretty obvious tbh. But feel free to PR something to the docs if you feel anything could be clarified 👍

**Pull request merged**
