### PR TITLE
[5.2] Laravel libsodium Encryption Library

### PR DESCRIPTION
**Pull request by scrothers**
First implementation of adding libsodium support to Laravel as an alternative encryption method.

https://paragonie.com/book/pecl-libsodium

### CODE REVIEW

**Comment by scrothers** [comment]
Researching how to add libsodium to Travis.

**Comment by scrothers** [comment]
I could probably use a little help getting Travis to play nice :(

**Comment by GrahamCampbell** [comment]
:-1: for adding anything else. The only reason we have two encrypters, is for BC with laravel 4.

**Comment by scrothers** [comment]
@GrahamCampbell This PR should be closed for the same reason as #10199 

I'll package both up as separate packages to be released for optional use :)

**Comment by taylorotwell** [comment]
Would you mind boxing this up with your hashing sodium package. Then we can have 1 convenient package to pull in if users want to use sodium for hashing / encryption.

**Comment by scrothers** [comment]
Absolutely, already on it.

**Comment by scrothers** [comment]
I have gone ahead and turned this into a package located here in case anyone wants it:
https://github.com/scrothers/libsodium-laravel

**Comment by paragonie-scott** [comment]
Sidenote: If anyone wants a simpler interface, I've been developing [Halite](https://github.com/paragonie/halite) (available on Composer as `paragonie/halite`) as a developer-friendly libsodium wrapper.

It's not Laravel-specific, it's more meant for wide PHP usage.

It hasn't been sufficiently peer reviewed, but in the future it may be of interest to Laravel developers.

**Pull request closed without merging**
