### PR TITLE
[11.x] Optimize container by caching reflection data

### PR DESCRIPTION
**Pull request by sarven**
It's another slight improvement for large applications with many dependencies. In Laravel we can define services with interfaces as scoped or singleton to force single creation. But for services without an interface (or those declared by using the bind method), there is no need to use scoped or singleton, so every time the service is needed a new instance needs to be created, and in the case of complex applications it could be quite slow. As the first improvement, we can cache data retrieved by using reflection to make those new instances a little bit faster. For a small number of services, it isn't a big optimization, but for a larger number of services, it could mean a few milliseconds per request, which could be a nice optimization. 

**Benchmarks**

It was tested on the example application with a few nested dependencies similar to the following structure: 
.Service1
..Service11
....ServiceA
....ServiceB
....ServiceC
....ServiceD
..Service12
....ServiceA
....ServiceB
....ServiceC
....ServiceD
..Service13
....ServiceA
....ServiceB
....ServiceC
....ServiceD
..Service14
....ServiceA
....ServiceB
....ServiceC
....ServiceD
..Service15
....ServiceA
....ServiceB
....ServiceC
....ServiceD

**BEFORE**
```
ab -n 1000 -c 1 http://127.0.0.1:8080/
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:        nginx/1.25.5
Server Hostname:        127.0.0.1
Server Port:            8080

Document Path:          /
Document Length:        2 bytes

Concurrency Level:      1
Time taken for tests:   44.335 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      1128000 bytes
HTML transferred:       2000 bytes
Requests per second:    22.56 [#/sec] (mean)
Time per request:       44.335 [ms] (mean)
Time per request:       44.335 [ms] (mean, across all concurrent requests)
Transfer rate:          24.85 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.3      0       8
Processing:    34   44   9.8     41     133
Waiting:       34   44   9.8     41     133
Total:         35   44   9.8     41     133

Percentage of the requests served within a certain time (ms)
  50%     41
  66%     43
  75%     45
  80%     47
  90%     55
  95%     65
  98%     73
  99%     81
 100%    133 (longest request)
```
Screenshot 2024-06-13 at 15 40 06

**AFTER**

```
ab -n 1000 -c 1 http://127.0.0.1:8080/
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:        nginx/1.25.5
Server Hostname:        127.0.0.1
Server Port:            8080

Document Path:          /
Document Length:        2 bytes

Concurrency Level:      1
Time taken for tests:   35.608 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      1128000 bytes
HTML transferred:       2000 bytes
Requests per second:    28.08 [#/sec] (mean)
Time per request:       35.608 [ms] (mean)
Time per request:       35.608 [ms] (mean, across all concurrent requests)
Transfer rate:          30.94 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       4
Processing:    29   35   7.9     33     110
Waiting:       29   35   7.9     33     110
Total:         29   35   7.9     33     110

Percentage of the requests served within a certain time (ms)
  50%     33
  66%     34
  75%     36
  80%     37
  90%     41
  95%     51
  98%     59
  99%     72
 100%    110 (longest request)
```

Screenshot 2024-06-13 at 15 40 16

### CODE REVIEW

**Comment by NickSdot** [comment]
Above results as diff.

image

**Comment by devajmeireles** [comment]
Clearly this is not going to go forward, a waste of time.

**Comment by rojtjo** [comment]
This looks very promising!
Did you run these benchmarks with OPcache enabled? If not, could you post the results with it enabled?

**Comment by sarven** [comment]
@rojtjo It was tested with enabled Opcache. Here is the screenshot from Blackfire:
Screenshot 2024-06-14 at 08 29 43

**Comment by taylorotwell** [comment]
Can we maybe get some real world benchmarks on apps that would simulate a bit more "typical" Laravel application in production with a couple of database queries?

**Comment by Tofandel** [comment]
I agree, I could give it a try, but right now all my apps are in 10.x, I didn't yet migrate to 11.x, and I'm wondering if the performance might be due to just the change to properties rather than methods in the reflection, because from my previous testing I noticed that php already caches the result of `new ReflectionClass()` because the first call always takes ~20 times more time than subsequent calls

**Comment by sarven** [comment]
@taylorotwell It doesn't make any sense to create an app with SQL queries, because this change doesn't impact queries, it only impacts the container. I know that it is an imagined example, but I was motivated by seeing something like this in one of the apps that I maintain:
Screenshot 2024-06-21 at 14 57 51

@Tofandel I've created the repository with a comparison. You can check it here: https://github.com/sarven/laravel-optimization-test

**Before**
```
Time: 19.366332292557ms
Memory: 20.48 KB
```

**After**
```
Time: 15.390226840973ms
Memory: 10.24 KB
```

It's counterintuitive, but seems like in the cached version memory usage is even lower. I don't know how PHP works under the hood, so can't explain that.

I'm thinking if the possibility to flush this cache is required or not. 

BTW I would want to improve the whole container, so this is the first of a few smaller changes. I would want to introduce something like a compilation of the container before deploying the application. It should improve the situation when in large monolithic apps you can see a profile like this:

Screenshot 2024-06-21 at 15 04 45

where the whole request time is 500ms (Blackfire time, not the real one)

**Comment by taylorotwell** [comment]
Going to hold off on this one for now, but may revisit it in the future.

**Comment by Sophist-UK** [comment]
> Results diff

Looking at these results a reduction from 44.35s to 35.608s is a 19.7% improvement in performance which (even if this is a synthetic benchmark focussing only on this small part of a typical overall response) is non-trivial.

@taylorotwell Is it time to revisit this?

**Comment by Tofandel** [comment]
@sarven 

This is not how you test memory footprint in php

```php
for ($i = 0; $i < $count; $i++) {
    $app = require __DIR__.'/bootstrap/app.php';
    $app->make(Kernel::class)->bootstrap();

    $start = microtime(true);
    $startMemory = memory_get_usage(true);
    $service = $app->make(RootService::class);
    $service = $app->make(RootService::class);
    $service = $app->make(RootService2::class);
    $service = $app->make(RootService2::class);
    $end = microtime(true);
    $endMemory = memory_get_usage(true);

    $data[] = [
        'time' => ($end - $start) * 1000,
        'memory' => $endMemory - $startMemory,
    ];

}
```

You have no guarantee about when the garbage collector runs, so first you need to run it yourself before the calls to get the memory usage.

You are also testing the memory footprint of a statically cached definition in a loop. This will give you meaningless data because there will be no increase after the first loop. In the real world you would take the memory of one loop and multiply it by the number of loops because php is bootstrapped from scratch every time (unless running on octane)

I would also suggest checking the peak memory as this is what will matter in high request density scenario instead of the memory after garbage collection.

**Pull request closed without merging**
