### PR TITLE
Add orderByRandom() function in query builder 

### PR DESCRIPTION
**Pull request by vlakoff**
Refs #5223

### CODE REVIEW

**Comment by vlakoff** [comment]
I'm thinking about renaming `getRandomFunction()` to `randomFunction()`, some opinion on this?

**Comment by vinicius73** [comment]
+1

**Comment by vs0uz4** [comment]
+1

**Comment by vluzrmos** [comment]
:+1:
I think is better `getRandomStatement()`.

**Comment by vluzrmos** [comment]
I made a trait with that feature to be used on models.

https://gist.github.com/vluzrmos/8046e20769a595a4b0d0

**Comment by vlakoff** [comment]
This scope approach is great :)

However I try to avoid the "oh hey it has so many layers, this looks so Professional" fashion, so here's mine: https://gist.github.com/vlakoff/8c8a9c8ee9437d3c1a94

**Pull request closed without merging**
