### PR TITLE
[5.8][FR] Multiple mail drivers.

### PR DESCRIPTION
**Pull request by dkulyk**
Sometimes need to send different mails to different SMTP servers. For example multidomain site with different configurations.  

Work in progress.
Related https://github.com/laravel/ideas/issues/1455

Config need to be looks like https://gist.github.com/dkulyk/3e251cd95269526db49c0c8c8641331b

### CODE REVIEW

**Comment by taylorotwell** [comment]
I honestly don't think this is a common enough case to warrant a breaking change?

**Comment by anik786** [comment]
Can we please consider allowing multiple mail servers like we do databases. Common use case is a multi-tenant application.

**Comment by Megachill** [comment]
This feature is very important in multi tenant apps, especially when dealing with Vendor Level apps where multiple mail configurations / domains might apply.

**Comment by driesvints** [comment]
@Megachill good news. It's coming in Laravel 7: https://github.com/laravel/framework/pull/31073

**Comment by Megachill** [comment]
@driesvints yes just saw that too, awesome. Good feature imho

**Pull request closed without merging**
