### PR TITLE
[5.3] Update policy.stub

### PR DESCRIPTION
**Pull request by cracki**
fix doc block for namespaced model

### CODE REVIEW

**Comment by taylorotwell** [comment]
This PR doesn't describe what is broken. So I have no idea what to verify.

**Comment by cracki** [comment]
when using console command to generate policy, if model get name spaced (Ex. Model\Post) , generated doc block must use same name spaced path

**Comment by taylorotwell** [comment]
Please give me an exact Artisan command I can paste in my terminal to recreate the issue.

**Comment by cracki** [comment]
php artisan make:model Models\Mymodel
Model created successfully.

php artisan make:policy MymodelPolicy --model=Models\Mymodel
Policy created successfully.
-------------------
generated doc  block:
    /**
     * Determine whether the user can view the mymodel.
     *
     * @param  \App\User  $user
     * @param  \App\Mymodel  $mymodel
     * @return mixed
     */
this is correct:
* @param  \App\Models\Mymodel  $mymodel

**Pull request merged**
