### PR TITLE
[7.x] Nested Eager Load Columns Usage

### PR DESCRIPTION
**Pull request by wandersonwhcr**
I am using eager load to select dependencies.

I select _books_ and require only `id` column. After, I select _chapters_ from _books_ and require only `id` and `book_id` columns.

```php
$builder
    ->with('books:id')
    ->with('books.chapters:id,book_id');
```

If I analyze database queries, it will generate:

```sql
SELECT * FROM `books`;
SELECT `id`, `book_id` FROM `chapters`;
```

Note that `*` from _books_ was used instead of `id`.

I created a simple test to simulate the problem.

That was caused because `Illuminate\Database\Eloquent\Builder::with` method use `array_merge` to join eager loads: if we call _books_ twice, second call (without columns) will be used.

But, the question is: how to fix that? Or, it _must_ be fixed?

### CODE REVIEW

**Comment by wandersonwhcr** [comment]
If I invert `array_merge` parameters, it works. But, later definitions will be ignored. Example:

```php
$builder
    ->with('books:id')
    ->with('books.chapters:id,book_id')
    ->with('books:id,name');
```

Only `id` from _books_ table will be selected.

**Comment by wandersonwhcr** [comment]
If I use `with` in reverse order, it works.

```php
$builder
    ->with('books.chapters:id,book_id')
    ->with('books:id');
```

**Comment by wandersonwhcr** [comment]
Just to explain: I know my tests are failing and they are the proof of current behavior.

**Comment by wandersonwhcr** [comment]
Gotcha!

But I will create more tests.

**Comment by wandersonwhcr** [comment]
I configured this PR to `7.x` branch because this change can break softwares where programmers think it was working.

**Comment by wandersonwhcr** [comment]
Another problem this PR will fix: undefined columns.

```php
$builder
    ->with('books:id,unknown_column_foobar')
    ->with('books.chapters:id,book_id');
```

If you remove last `with` method call, it will break if `unknown_column_foobar` column doesn't exist. But, before this PR, it will select all columns, ignoring configuration... So, it "works".

**Comment by taylorotwell** [comment]
No plans to change / fix this right now.

**Comment by wandersonwhcr** [comment]
Why?

**Pull request closed without merging**
