### PR TITLE
Add @logged to BladeEngine

### PR DESCRIPTION
**Pull request by ghost**
Check if current user is logged with this snippet of code

```
@logged 
// do something for authenticated users
@endlogged
```
instead of

```
@if (\Auth::user())
// do something for authenticated users
@endif
```

### CODE REVIEW

**Comment by tillkruss** [comment]
`@logged` seems vague, how about `@loggedIn`?

**Comment by mg-freelancer** [comment]
@tillkruss do u mean to change `@logged` to `@loggedIn`

**Comment by tillkruss** [comment]
Yes, and maybe it makes sense to add `@guest` or `@loggedOut` directive as well?

**Comment by mg-freelancer** [comment]
@tillkruss very interesting, I will check other feedback

**Comment by tillkruss** [comment]
It would probably make sense to support different guards as well, like `@loggedIn('guard-name')`.

**Comment by mg-freelancer** [comment]
sorry, please clarify that

**Comment by tillkruss** [comment]
https://laravel.com/docs/master/authentication

**Comment by taylorotwell** [comment]
Don't really like this syntax.

**Comment by mg-freelancer** [comment]
@taylorotwell great, Don't like @logged as syntax only or the whole idea of checking current logged user ?

**Pull request closed without merging**
