### PR TITLE
Revert "[6.x] Add 'setRawAttribute' method"

### PR DESCRIPTION
**Pull request by taylorotwell**
Reverts laravel/framework#30853

### CODE REVIEW

**Comment by Lloople** [comment]
In case someone wants more information about this 👉 #30884

**Comment by mfn** [comment]
The latest release of illuminate/database unfortunately is 6.8.0 which does not yet contain the fix => can a new release for the components please be cut? Thanks 🙏

**Comment by driesvints** [comment]
@mfn we can't tag the components anymore unfortunately because it's been too long since we did the 6.9.0 release. We'll need to wait until next week for the 6.10.0 release.

**Comment by mfn** [comment]
Thanks for the heads up! 👍

**Pull request merged**
