### PR TITLE
[9.x] Stringable exactly not match with other Stringable variable

### PR DESCRIPTION
**Pull request by medeiroz**
- Laravel Version: 9.5.1
- PHP Version: 8.1
- Database Driver & Version: N/A

### Description:
When need compare two Stringable variables with exactly method. Then false is returned

### Steps To Reproduce:

```php
<?php

$first = \Str::of('name');
$second = \Str::of('name');
$first->exactly($second);
//  => false

// true is expected but false is returned

```

image

## Solution

- Cast argument to string when argument is Stringable

### CODE REVIEW

**Comment by SjorsO** [comment]
Doesn't make a lot of sense to have a method called `exactly` that does a loose comparison.

Might be a better idea to do this instead:
```php
if ($value instanceof Stringable) {
    $value = $value->toString();
}

return $this->value === $value;
```

**Comment by driesvints** [comment]
The method dockblock clearly indicates you can only pass a string.

**Comment by imanghafoori1** [comment]
```php
if (is_object($value) && method_exists('__toString', $value)) {
    $value = (string) $value;
}
```

So that there is no loose comparison will happen.

**Comment by dennisprudlo** [comment]
@imanghafoori1 I'm not sure any object that has a `__toString()` should be a valid parameter.
```php
$model = new \App\Models\SomeModel;
str('[]')->exactly($model); // true
```

The type in the docblock says only `string` can be passed, so maybe just add `Stringable` (the class not the global interface) to the docblock and check like @SjorsO did.

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
👎 You are incorrectly calling this function if you do not pass a string.

**Comment by GrahamCampbell** [comment]
If you want this function to support stringable objects, then we would have to widen its param type.

**Comment by driesvints** [comment]
@GrahamCampbell that's what this PR tries to do 😅  I also misjudged this PR at first for wrong usage but I can see the use case here.

**Comment by pedroaff** [comment]
The two itens has the exact values, so it should not return false.
It's makes sense when we need to compare two itens w/ the same value.

**Pull request merged**
