### PR TITLE
[5.0] Add Pluralize Helper

### PR DESCRIPTION
**Pull request by RomainLanz**
Hi everyone,

I know that we already have a `str_plural()` method but I think that this helper is more readable.
I also add some tests and correct the `Pluralizer` to handle a count of 0.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Not correct behaviour.

**Comment by RomainLanz** [comment]
And why?

**Comment by RomainLanz** [comment]
Think that we have a member counter:

````php
 {!! pluralize('member', $memberCount) !!} registered
````

**Comment by GrahamCampbell** [comment]
That's the way str_plural already works. Also, you should be using escaped tags there.

**Pull request closed without merging**
