### PR TITLE
tooManyAttempts method of RateLimiter class parameter fix

### PR DESCRIPTION
**Pull request by khanrn**
`$decayMinutes = 1` parameter has no usage inside the method. So we better remove it.

### CODE REVIEW

**Comment by jmarcher** [comment]
This should be pointing to master

**Comment by rnaby** [comment]
@jmarcher Pointed to `master` branch. Changed from `5.5`. What about #22190 and #22191 ?

**Comment by jmarcher** [comment]
Those are fine in this case you are modifying the public API that's why.

And btw, you need to rebase your branch

**Comment by sisve** [comment]
What problem does this change actually fix?

**Comment by taylorotwell** [comment]
Has a bunch of other commits in the history. Please resubmit fresh to master.

**Comment by rnaby** [comment]
@jmarcher Thanks for clarifying the API thing. And I just changed the pointing branch in *GitHub* web UI form `5.5` to `master`. That's why this rebase issue occurred.

@sisve This `$decayMinutes = 1` parameter has no usage inside the method. Why should we put a parameter there which has no usage in the method ? BTW, my new submission is #22202. We can continue this discussion there.

@taylorotwell My new submission is #22202 . Please have a look when you get time.

**Pull request closed without merging**
