### PR TITLE
Fix some typos in "Auth" directory root files.

### PR DESCRIPTION
**Pull request by GinoPane**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Sorry, but most of these changes are wrong.

**Comment by GrahamCampbell** [comment]
Infact, all of them are wrong.

**Comment by GinoPane** [comment]
Hmm, any arguments? "Their" to "his" should be right, fixes for articles seem to be right to, hyphens - here's the link for the rule: http://www.oxforddictionaries.com/words/hyphen. So all of them seem to be right.

**Comment by GrahamCampbell** [comment]
The user may not be male, so "his" is totally wrong.

**Comment by GinoPane** [comment]
It's really controversial, cause a noun "user" is masculine noun and there's no difference who the real user is. And even without this change all other changes seem to be grammatically correct. So I'm afraid you cannot assert that "all of them are wrong":)

**Comment by GrahamCampbell** [comment]
In English, nouns don't have a gender.

**Comment by GinoPane** [comment]
I've already told that it's controversial:) Everything differs in the context (http://www.native-english.ru/grammar/english-nouns-gender). Nevertheless, I think, it is completely wrong to use plural pronoun "their" for singular "user".

**Comment by phanan** [comment]
> Nevertheless, I think, it is completely wrong to use plural pronoun "their" for singular "user".

It's completely right. You may want to check your source.

**Comment by GrahamCampbell** [comment]
>  think, it is completely wrong to use plural pronoun "their"

It is NOT the JUST plural pronoun. It is used in both contexts.

**Comment by GrahamCampbell** [comment]
Locking this because this is going nowhere.

**Pull request closed without merging**
