### PR TITLE
getRelation docs updated

### PR DESCRIPTION
**Pull request by pavinthan**
For editors / IDEs suggestion

### CODE REVIEW

**Comment by ConnorVG** [comment]
This is incorrect, it would need to be something like:
`@return \Illuminate\Database\Eloquent\Model|Illuminate\Database\Eloquent\Collection|null`

This is clearly massive, `mixed` is nicer.

**Comment by ConnorVG** [comment]
You still have the wrong collection class.

**Comment by pavinthan** [comment]
But it's bit clear and for painless development, otherwise no comment.

**Comment by pavinthan** [comment]
Thank you Guys

**Pull request closed without merging**
