### PR TITLE
broadcast notifications with custom type

### PR DESCRIPTION
**Pull request by aram810**

### CODE REVIEW

**Comment by taylorotwell** [comment]
No description provided with PR with examples, etc.

**Comment by aram810** [comment]
@taylorotwell  Will this functionality be available in the next release ?

**Comment by Dylan-DPC** [comment]
@aram810 submit a new PR to master with description and examples of what your PR is trying to achieve.

**Comment by aram810** [comment]
@Dylan-DPC thanks

**Pull request closed without merging**
