### PR TITLE
[7.x] Allow including a closure in a queued chain

### PR DESCRIPTION
**Pull request by themsaid**
This PR allows including a closure in a chain.

```php
Download::withChain([
    new RunTests(),
    new Deploy(),
    function(){
        Deployment::update(....);
    }
])
```

Also I've removed the serialization and deserialization of chained jobs since it'll be serialized deserialized along with the main job being dispatched anyway.

### CODE REVIEW

**Comment by SjorsO** [comment]
@themsaid Not related to this PR, but could you maybe take a look at queuing closures using the `Queue` facade?

```php
// This works
dispatch(function () {
    //
});

// This currently gives a cryptic error
Queue::push(function () {
    //
});
```

**Comment by taylorotwell** [comment]
I feel fairly confident there was a reason those serialize / unserialize were in place and I remember dealing with it when I wrote this. Do we have to remove them?

**Comment by themsaid** [comment]
@taylorotwell I've put them back, not sure why we need that but just in case :)

**Comment by ryangjchandler** [comment]
> @themsaid Not related to this PR, but could you maybe take a look at queuing closures using the `Queue` facade?
> 
> ```
> // This works
> dispatch(function () {
>     //
> });
> 
> // This currently gives a cryptic error
> Queue::push(function () {
>     //
> });
> ```

I've just made a PR to fix this here #31644 .

**Pull request merged**
