### PR TITLE
[8.x] Solve the inconsistency of the with-and-without middleware

### PR DESCRIPTION
**Pull request by khalilst**
This PR solved the inconsistency of the `withMiddleware` and `withoutMiddleware` in the following of this issue #24680 .

The first problem was related to running one or two middlewares (e.g. `withMiddleware(['foo', 'bar'])`) after disabling them using `withMiddleware()` [without parameter]. It was not working.

The second problem was related to enabling all middlewares using `withMiddleware()` [without parameter] after disabling them explicitly (e.g. `withoutMiddleware(['foo', 'bar'])`).  This one was not working, also.

For more clarification:
```php
//1. All middlewares disabled here.
$this->withoutMiddleware();

//2. Only include the foo & bar middlewares. This was NOT working before this PR.
$this->withMiddleware(['foo', 'bar']);

//3. Disable the bar middleware. It was OK.
$this->withoutMiddleware('bar');

//4. Enable all middlewares including bar middleware. Before this PR, the bar middleware was NOT included.
$this->withMiddleware();
```

Also, the test for above example included in the second commit.

### CODE REVIEW

**Comment by taylorotwell** [comment]
What is a signed middleware?

**Comment by khalilst** [comment]
@taylorotwell , It is just a name I have used for signed/flagged middleware using `withMiddleware` & `withoutMiddleware`.

```php
    $sign === true  // Used for middleware passed to withMiddleware
    $sign === false // Used for middleware passed to withoutMiddleware
```
Also, it may be extended to use for dynamic add/remove middlewares.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by Minhyme** [comment]
@khalilst did you ever package this? I agree the laravel functionality is confusing behavior but I also agree with the comments on this PR that your code changes are not the easiest to follow as the naming is quite confusing.

**Comment by khalilst** [comment]
No, I didn't package it, but I like to give it a try.
Do you have any recommendations for the naming? We can open the PR if you
or Taylor agree with that.

**Comment by hcbaxiom** [comment]
@taylorotwell

**Pull request closed without merging**
