### PR TITLE
[5.6] Allow component slots to be arrays

### PR DESCRIPTION
**Pull request by AndrewMast**
I wanted to be able to use the component for tables or lists, but that wasn't really possible so I came up with this solution:

If the name of the slot ends with "[]" or "[key]", the slot is overridden with an array and the new element is appended to the array.

Example Code:
```
@slot('array[]', 'value')
@slot('array[key]', 'value')
```
Example Output: (from inside of the view)
```
$array = [
    0 => "value",
    "key" => "value"
];
```

Of course, if you previously set the slot 'array' to the value of 'string' (`@slot('array', 'string')`) and then added the code above, it would be overridden with the array and vice versa.

### CODE REVIEW

**Comment by browner12** [comment]
```php
@slot('array', ['value'])
@slot('array', ['key' => 'value'])
```

**Comment by Dylan-DPC** [comment]
This is a breaking change.

**Comment by AndrewMast** [comment]
I forgot to mention it, but the main reason I made this is because it works like this:
```
@slot('array[]')
    value
@endslot
```

**Comment by AndrewMast** [comment]
@browner12 Please elaborate on what you said.

@Dylan-DPC Can you explain why it is a breaking change?

**Comment by taylorotwell** [comment]
No plans on adding this.

**Comment by taylorotwell** [comment]
@Dylan-DPC i appreciate your comments but it would be helpful if you explained why when you make them.

**Comment by Dylan-DPC** [comment]
@taylorotwell Sure.

**Comment by browner12** [comment]
sure. slots could always be array. just used the syntax I showed you to accomplish the same result.

**Comment by AndrewMast** [comment]
@browner12 I know, but my point of making it was so that embedded html can be the value of the array

**Pull request closed without merging**
