### PR TITLE
[11.x] Verified & Unverified, Blade Directives

### PR DESCRIPTION
**Pull request by devajmeireles**
This PR introduces two new Blade directives that aim to check the email status of the authenticated user:

The `verified` directive:

```blade
@verified
    Your email address is already verified, thank you!
@endverified
```

The `unverified` directive:

```blade
@unverified
    Your email address is not verified. Click here to receive a new email to confirm your email address.
@endunverified
```

Both of them act related to `hasVerifiedEmail` method of the `MustVerifyEmail` interface.

### CODE REVIEW

**Comment by insathroof** [comment]
This is the kind of thing I wonder why it doesn't exist in Laravel yet...

**Comment by martinbean** [comment]
The value of `auth()->guard{$guard}->user()` is not guaranteed to have a `hasVerifiedEmail` method as it’s just type-hinted as `Illuminate\Contracts\Auth\Authenticatable`. This will fail if the developer is using something other than the default `User` model.

**Comment by dinhquochan** [comment]
Disagree, because the MustVerifyEmail interface/trait is optional. Just using custom if directives or using @if directly is much clearer.

**Comment by devajmeireles** [comment]
> The value of `auth()->guard{$guard}->user()` is not guaranteed to have a `hasVerifiedEmail` method as it’s just type-hinted as `Illuminate\Contracts\Auth\Authenticatable`. This will fail if the developer is using something other than the default `User` model.



> Disagree, because the `MustVerifyEmail` interface/trait is optional. Just using custom if directives or using `@if` directly is much clearer.

The use of these directives depends on `MustVerifyEmail` being in use. If `MustVerifyEmail` is not in use, then you don't need to use these directives.

**Comment by taylorotwell** [comment]
Since this seems to be getting some early push back I'll just leave it up to the end-developer to use `Blade::if` to easily add this if you want.

**Pull request closed without merging**
