### PR TITLE
[6.x] Allow model serialization for typed properties

### LINKED ISSUE #30494: [6.x] [PHP 7.4] Using Typed properties classes on SerializesModels causes error due Illuminate\Contracts\Database\ModelIdentifier
- Laravel Version: 6.4.1
- PHP Version: 7.4.0RC4
- PHP RFC: https://wiki.php.net/rfc/typed_properties_v2

Using this class definition:

```php
<?php declare(strict_types=1);

namespace App\Mails\User;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use App\Models;

class Confirm extends Mailable
{
    use Queueable, SerializesModels;

    /**
     * @var \App\Models\User
     */
    public Models\User $user;

    /**
     * @param \App\Models\User $user
     *
     * @return self
     */
    public function __construct(Models\User $user)
    {
        $this->user = $user;
    }
}
```

Queue can not serialize properties due Typed property `App\Mails\User\Confirm::$user`.

Error:

```
[2019-11-01 12:10:31] local.ERROR: Typed property App\Mails\User\Confirm::$user must be an instance of App\Models\User, Illuminate\Contracts\Database\ModelIdentifier used {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Typed property App\\Mails\\User\\Confirm::$user must be an instance of App\\Models\\User, Illuminate\\Contracts\\Database\\ModelIdentifier used at /vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php:23)
[stacktrace]
#0 /vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(23): ReflectionProperty->setValue()
#1 [internal function]: App\\Mails\\MailAbstract->__sleep()
#2 /vendor/laravel/framework/src/Illuminate/Queue/Queue.php(139): serialize()
#3 /vendor/laravel/framework/src/Illuminate/Queue/Queue.php(110): Illuminate\\Queue\\Queue->createObjectPayload()
#4 /vendor/laravel/framework/src/Illuminate/Queue/Queue.php(88): Illuminate\\Queue\\Queue->createPayloadArray()
#5 /vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(37): Illuminate\\Queue\\Queue->createPayload()
#6 /vendor/laravel/framework/src/Illuminate/Queue/Queue.php(44): Illuminate\\Queue\\SyncQueue->push()
#7 /vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(180): Illuminate\\Queue\\Queue->pushOn()
#8 /vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(388): Illuminate\\Mail\\Mailable->queue()
#9 /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(239): Illuminate\\Mail\\Mailer->queue()
#10 /app/Services/Mail/Mailer.php(53): Illuminate\\Support\\Facades\\Facade::__callStatic()
#11 /app/Services/Mail/Mailer.php(19): App\\Services\\Mail\\Mailer::queue()
#12 /app/Services/User/Confirm.php(53): App\\Services\\Mail\\Mailer::userConfirm()
#13 /app/Http/Controllers/Api/UserSignup.php(39): App\\Services\\User\\Confirm::start()
#14 [internal function]: App\\Http\\Controllers\\Api\\UserSignup->confirmStart()
#15 /vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#16 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#17 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#18 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#19 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#20 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#21 /app/Http/Middlewares/LoggerRequest.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middlewares\\LoggerRequest->handle()
#23 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then()
#25 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack()
#26 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute()
#27 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute()
#28 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#29 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#30 /app/Http/Middlewares/Language.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middlewares\\Language->handle()
#32 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#34 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#36 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#37 /public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#38 {main}
```

### PR DESCRIPTION
**Pull request by driesvints**
At the moment it's not possible to use model serialization on jobs with typed properties (which is coming to PHP 7.4). The reason for this is that the property values get replaced with a `ModelIdentifier` instance which contains all the info to unserialize the model or collection later on.

This new implementation takes the approach of saving those ModelIdentifiers on a separate `$identifiers` property and replaces the original property values with empty instances of those models or collections. This way, type safety is preserved and we can use typed properties on queueable jobs.

This is technically a breaking change because if you expect the properties to contain the `ModelIdentifier` you'll now get an empty model or collection after serialization. But this is also only happening if you're doing anything with the model after serialization and before sending it to the queue, which seems unlikely.

Fixes https://github.com/laravel/framework/issues/30494 

Small side note: one small other thing that I thought of was if people would be overriding a model constructor with different arguments other than the default that this wouldn't work but I found out that in the current unserialization process the same approach is taken and thus that wouldn't work anyway at the moment. It's also my personal opinion that people shouldn't override a collection or model's constructor but best use named constructors in these cases.

### CODE REVIEW

**Comment by driesvints** [comment]
It seems StyleCI is failing because it doesn't supports typed properties yet. 

cc @GrahamCampbell

**Comment by driesvints** [comment]
I've ignored the file in StyleCI for now.

**Comment by dkulyk** [comment]
I think need to use __serialize/__unserialize for this. This also added on PHP 7.4

**Comment by driesvints** [comment]
@dkulyk that would change the entire narrative of this functionality. The idea behind the current approach is that a fresh instance is retrieved while if we'd serialize everything then that would mean the exact object as is would be serialized.

**Comment by driesvints** [comment]
@dkulyk also: we'll probably only be able to support that when PHP 7.4 is the new minimum version which won't be before September 2021.

**Comment by dkulyk** [comment]
For PHP 7.3 and below will work old behavior. for 7.4+ new. 
Also 
```php
class A{
    public $a = 2;
    protected $b = "ss";
    private $c = false;

    public function __serialize()
    {
        return [
            'a' => $this->a,
            '*b' => $this->b, 
            'Ac' => $this->c 
        ];
    }
serialize(new A) -> unserialized on 7.3 and below:
O:1:"A":3:{s:1:"a";i:1;s:4:"*b";s:1:"s";s:4:"Ac";b:1;} //PHP 7.3
O:1:"A":3:{s:1:"a";i:1;s:4:"*b";s:1:"s";s:4:"Ac";b:1;} //PHP 7.4
```

**Comment by GrahamCampbell** [comment]
@driesvints Yes, StyleCI parses files as PHP 7.3 right now. Support for PHP 7.4 is likely to land Q1 2020. We haven't decided on a launch date yet for that.

**Pull request merged**
