### PR TITLE
[7.x] Add Str::between method

### PR DESCRIPTION
**Pull request by osbre**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. Could you update https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Stringable.php too please.

**Comment by danilopinotti** [comment]
The tests aren't covering empty strings passed as argument in `$before` or `$after`

**Comment by taylorotwell** [comment]
@osbre I think @danilopinotti has a good suggestion.

**Comment by SjorsO** [comment]
Some tests for strings that contain the `$before` and `$after` twice or more would also be a good idea.

For example:
```php
$string = Str::between('[1] bla bla [2]', '[', ']');

// $string === '1] bla bla [2'
```

Testing this behavior could help prevent unexpected breaking changes in the future.

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
Please make the prescribed changes.

**Comment by osbre** [comment]
@GrahamCampbell, sorry for the long response. I updated my code.

Thanks to everyone!

**Comment by SjorsO** [comment]
This PR might inspire some more helpers in the future:
```php
Str::between() // '[1] bla bla [2]' => '1] bla bla [2'
Str::betweenFirst() // '[1] bla bla [2]' => '1'
Str::betweenLast() // '[1] bla bla [2]' => '2'
Str::betweenAll() // '[1] bla bla [2]' => ['1', '2']
```

**Comment by adelf** [comment]
@SjorsO I think better to make it in another PR

**Comment by taylorotwell** [comment]
Can you describe where in your application you found yourself needing this?

**Comment by SjorsO** [comment]
I know the question wasn't directed at me, but I could use this PR for something I'm working on right now: I'm writing a password reset test using Laravel Dusk. I'm intercepting the email that contains the reset link, and now I want Dusk to visit that link. I could use `Str::between($email->body, 'href="', '"')` to grab the link.

The current implementation of `Str::between()` would only work for this if the email body only contains 1 link. As soon as it would contain multiple i would get a useless result.

**Comment by adelf** [comment]
Maybe `findBetween` is better name for this method...

**Comment by osbre** [comment]
@taylorotwell I felt the need for this when analyzing my Envoy's log output, for example lines:

```
[127.0.0.1]: Status%%Updating exercise
[127.0.0.1]: Container%%c784a56f3f40
```

To parse current key (it's may been "Status", "Container", or something other) i need:

```php
Str::between($buffer, ':', '%%'); // Status or Container
```
Part inside my app: https://github.com/code-co-ua/code.co.ua/blob/exercises-webide/app/Domain/Exercise/Jobs/LaunchExerciseJob.php#L39

**Pull request merged**
