### PR TITLE
[5.1] Change redis ref keys to avoid breaking upgrades

### PR DESCRIPTION
**Pull request by HughNoble**
To go up alongside https://github.com/laravel/framework/pull/12733 to prevent breaking upgrades as per discussion at https://github.com/laravel/framework/issues/13675

### CODE REVIEW

**Comment by taylorotwell** [comment]
With this it wouldn't break but we should still recommend a cache flush right?

**Comment by HughNoble** [comment]
Yes, a flush is recommended but not required.

**Comment by taylorotwell** [comment]
Both merged.

**Comment by mstephens** [comment]
Great! I would like to revisit the tests next week just to improve what's there currently from 5.1 (noted when doing the commits). Although the mock tests won't pickup runtime errors. Perhaps a simulation?

**Comment by GrahamCampbell** [comment]
@mstephens Did you get a chance to look at this please. We'd be massively grateful if you could fit it in, whenever. :)

**Pull request merged**
