### PR TITLE
[5.1] Remove redundant function call

### PR DESCRIPTION
**Pull request by apollopy**
The `login` function will call `updateSession` function which will excute

``` php
$this->session->set($this->getName(), $id);
```

https://github.com/laravel/framework/blob/5.1/src/Illuminate/Auth/Guard.php#L432

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
What does this do please?

**Comment by apollopy** [comment]
@GrahamCampbell 
the explanation updated.

**Comment by taylorotwell** [comment]
If it's not broken don't fix it. Had too many broken PRs lately.

**Comment by vlakoff** [comment]
This is a leftover from the [first implementation](https://github.com/laravel/framework/commit/e7074a78848457e8c025f8f71db1259ee73a8d11) which wasn't making any sense:

	public function loginUsingId($id, $remember = false)
	{
		$this->session->put($this->getName(), $id);

		return $this->login($this->user(), $remember);
	}

Then it was fixed five months later in #1712, see how this `retrieveById` is welcome:

	public function loginUsingId($id, $remember = false)
	{
		$this->session->put($this->getName(), $id);

		return $this->login($this->provider->retrieveById($id), $remember);
	}

(Then, it was again modified #2871 to return the user as stated in the phpdoc.)

So, it's not a redundant function call but rather a leftover from the first implementation which was entirely wrong.

**Comment by apollopy** [comment]
The corresponding test cases are not understood

https://github.com/laravel/framework/blob/5.1/tests/Auth/AuthGuardTest.php#L245

**Comment by vlakoff** [comment]
Just an overlook I suppose, doesn't impact the test as the return value is not used actually.

More importantly:
* If no user is found for the given id, bad things happen. We should check `retrieveById` gave an user before continuing, otherwise throw a proper error.
* As `login()` is mocked in the test, we aren't testing much. We should either:
    * test the whole thing, as in the tests above,
    * or simply test we are logging with the expected user and returning it (basically what is done currently).

**Comment by vlakoff** [comment]
@taylorotwell What should be the behavior when `Guard::loginUsingId` (Laravel 5.1) or `SessionGuard::loginUsingId` (Laravel 5.2) is called with an invalid id? (throw exception, return false...) Current behavior: `login` is then called with `null` and errors happen.

**Comment by vlakoff** [comment]
Thoughts?

I'm ready to submit code for this, but I have to know what should be thrown if ever `SessionGuard::loginUsingId` were to be called with an invalid id.

**Pull request closed without merging**
