### PR TITLE
[5.3] Added console command contract.

### PR DESCRIPTION
**Pull request by Modelizer**
Sometimes we need to pass console command into a class and also we want to add a layer only to inject console command. This contract will help us to do it.

I have a project where I need to solve it.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I don't see the point in this?

**Comment by Modelizer** [comment]
I'm passing console class as an argument to a concrete class. but I don't want to hardcode class name rather I'll go with an interface. This way I can swap console class when I needed. Make sense?

**Comment by sisve** [comment]
Why should this interface be added to laravel/framework instead of kept within your own codebase?

**Comment by Modelizer** [comment]
Yup, I gave a thought for it. But after rethinking; why don't we add an interface in the core to handle it rather I need to implement it on every single file I created.

This is not a breaking change thou and it will also help others to do it easily if they encounter similar situation like me :)

**Comment by GrahamCampbell** [comment]
> I'm passing console class as an argument to a concrete class. but I don't want to hardcode class name rather I'll go with an interface. This way I can swap console class when I needed. Make sense?

Your interface is empty though, so no point.

**Pull request closed without merging**
