### PR TITLE
[5.1] Return Collection From Query Builder

### PR DESCRIPTION
**Pull request by GrahamCampbell**
> This is a really nice feature. The collection class is one of the best things in Laravel! It is also a boon for consistency.
> 
> This one does not touch the getModels method, or anything that has to do with relations or eager loading. In fact, it doesn't touch anything Eloquent related, so it's much safer.
> 
> We also now have the integration tests, which really helps.

Replaces #7213.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Conflicts?

**Comment by JosephSilber** [comment]
@taylorotwell rebased.

**Comment by GrahamCampbell** [comment]
Looks pretty nice. :+1:

**Comment by JosephSilber** [comment]
@GrahamCampbell out of curiosity: how did you originally move this PR that was targeted at 5.0 to master?

**Comment by RomainLanz** [comment]
He just create a new PR with your branch across all fork and target master.

**Comment by GrahamCampbell** [comment]
Yeh, anyone can create a pull to and from any repo on github. They don't need any special permissions. :)

**Comment by taylorotwell** [comment]
Want to hold off on this as I want to minimize breaking changes in 5.1 and it is rather trivial to just `collect` your DB results if you want a collection of them.

**Comment by GrahamCampbell** [comment]
:(

**Pull request closed without merging**
