### PR TITLE
[5.1] Return nested collection from groupBy

### PR DESCRIPTION
**Pull request by JosephSilber**
The collection's `groupBy` method should return a collection of collections, similar to the `chunk` method.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We'll have to make sure we document this change. I fairly recently had to write some code specific to the way this used to work in the laravel auto presenter package that will be broken by this.

NB I'm fine with this change, I'd just like to make sure we document it. :)

**Comment by JosephSilber** [comment]
@GrahamCampbell Are you sure it will break your package? Calling `Collection::make` on an existing collection will still return a normal collection. Same goes for `new Collection($collection)`.

And yes, I agree we should document it :)

**Comment by GrahamCampbell** [comment]
> Are you sure it will break your package?

I'm not all that sure. It wasn't all that recent. I was just providing it as an example. :)

**Comment by JosephSilber** [comment]
@GrahamCampbell the database tag is wrong.

**Comment by GrahamCampbell** [comment]
Oh crap, yeh. lol - I'm just used to using this method in the context of eloquent collections. :)

**Comment by JosephSilber** [comment]
@GrahamCampbell I guess you auto presenter uses the builder's `groupBy` then?

:grinning:

**Comment by GrahamCampbell** [comment]
Not quite, we just have some tests that use it to make sure we're dealing with the result of that function correctly. :)

**Comment by taylorotwell** [comment]
Conflicts.

**Pull request merged**
