### PR TITLE
[6.x] Optimize next available job in database queue

### PR DESCRIPTION
**Pull request by jasonlav**
Current getNextAvailableJob queue selects all columns in the jobs database. This can cause database performance issues if the jobs table has many rows and the payload column is large. Added subquery to find the next available job prior to selecting all columns in the database. Fully backwards compatible.

### CODE REVIEW

**Comment by taylorotwell** [comment]
@jasonlav you were able to test this on your large job database and confirm it actually does solve your issues?

**Comment by jasonlav** [comment]
In testing, updated query has improved response time 20x against large job database.

**Comment by taylorotwell** [comment]
I'm curious if interior query not having any lock means lots of database workers will receive deadlocks?

**Comment by taylorotwell** [comment]
So, one thing I'm noticing locally is that if I start 10 database workers and load 5000 jobs into the queue the total time to process all the jobs takes 10 seconds. However, with the old query (without the subquery) it takes only 4 seconds. Seems like we are taking a big step backwards in performance here?

**Comment by rodrigopedra** [comment]
Well the premise for this PR is:

> Current getNextAvailableJob queue selects all columns in the jobs database. This can cause database performance issues...

But all the columns are still retrieved (* more on this later):

https://github.com/laravel/framework/blob/55ed697839a14da94a4c15f6f683644b6969853e/src/Illuminate/Queue/DatabaseQueue.php#L212-L230

As such I don't see any benefits of running a subquery instead of a query with `LIMIT 1` as before.

Also as the ORDER BY uses only the primary key, the query optimizer will most likely use the primary key index to sort before fetching all the data. And the limit clause will make the execution halt after the first record is retrieved.

(*) I mean retrieved from the DB to PHP. Note that before and after this PR just one record's columns is sent over the wire.

Lastly, I tried running both queries to see their execution plan. For the suggested query by this PR, I tried this:

~~~sql
SELECT *
FROM `jobs`
WHERE
    `id` IN (
        SELECT `id`
        FROM `jobs`
        WHERE
            `queue` = 'default'
            AND (
                (`reserved_at` IS NULL AND `available_at` <= CURRENT_TIMESTAMP)
                OR (`reserved_at` <= CURRENT_TIMESTAMP - 5000)
            )
        ORDER BY `id`
        LIMIT 1
    )
~~~

MySQL errored with this message:

> [42000][1235] This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'

I am using MySQL version 8. Please apologize me if the query I come up from reading the code is wrong.

For the current query, I tested this SQL query:

~~~sql
EXPLAIN SELECT *
FROM `jobs`
WHERE
    `queue` = 'default'
    AND (
        (`reserved_at` IS NULL AND `available_at` <= CURRENT_TIMESTAMP)
        OR (`reserved_at` <= CURRENT_TIMESTAMP - 5000)
    )
ORDER BY `id`
LIMIT 1;
~~~

| id | select\_type | table | partitions | type | possible\_keys | key | key\_len | ref | rows | filtered | Extra |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1 | SIMPLE | jobs | NULL | index | jobs\_queue\_index | PRIMARY | 8 | NULL | 1 | 35.55 | Using where |

As you can see current query is already very optimized (at least for MySQL).

For reference my jobs table had 4,827 records when I was testing it out.

**Comment by paras-malhotra** [comment]
Original query:
```sql
select * from `jobs`
where `queue` = 'default' and 
((`reserved_at` is null and `available_at` <= CURRENT_TIMESTAMP) or `reserved_at` <= CURRENT_TIMESTAMP - 3600)
order by `id` asc limit 1;
```

New query (with this PR):
```sql
select * from `jobs`
where `id` = 
   (select `id` from `jobs` where `queue` = 'default' and
   ((`reserved_at` is null and `available_at` <= CURRENT_TIMESTAMP) or `reserved_at` <= CURRENT_TIMESTAMP - 3600)
   order by `id` asc limit 1)
limit 1;
```

Explains are as follows:
**Original Query**

| id | select_type | table | partitions | type | possible_keys    | key              | key_len | ref   | rows | filtered | Extra                              ________________________________________________________________________________________________________________________
|  1 | SIMPLE      | jobs  | NULL       | ref  | jobs_queue_index | jobs_queue_index | 1022    | const |    1 |   100.00 | Using index condition; Using where |

**New Query**

| id | select_type | table | partitions | type | possible_keys    | key              | key_len | ref   | rows | filtered | Extra                              ________________________________________________________________________________________________________________________
|  1 | PRIMARY     | NULL  | NULL       | NULL | NULL             | NULL             | NULL    | NULL  | NULL |     NULL | no matching row in const table     |
|  2 | SUBQUERY    | jobs  | NULL       | ref  | jobs_queue_index | jobs_queue_index | 1022    | const |    1 |   100.00 | Using index condition; Using where |


Based on the explains, it doesn't seem the new query is faster.

**Comment by taylorotwell** [comment]
I'm going to hold off on this for now because the queue processing time more than doubles on my machine with this PR.

**Comment by rodrigopedra** [comment]
Thanks @paras-malhotra for the heads up on the query.

Somehow I missed it was a `where id = (...)` instead of a `where in`.

But nevertheless it seems we got to similar conclusions

**Pull request closed without merging**
