### PR TITLE
add `destroyOrFail` to the `Model`

### PR DESCRIPTION
**Pull request by mahmoudmohamedramadan**

### CODE REVIEW

**Comment by mahmoudmohamedramadan** [comment]
@taylorotwell Sir can you see this PR, please

**Comment by inxilpro** [comment]
It seems like this could be implemented as:

```php
return (new static)->getConnection()->transaction(function() use ($ids) {
    if (!$destroyed = static::destroy($ids)) {
      throw new RuntimeException('No records were destroyed.');
    }
    return $destroyed;
});
```

But in the end I'm not sure that `destroyOrFail()` describes this behavior, because `Model::destroy()` will also throw an exception if any of the `$model->delete()` calls fail.  It's more like `destroyInTransaction()` or something similar…

**Comment by taylorotwell** [comment]
Feels unfortunate we have to duplicate so much code here. Maybe there is a better way?

**Comment by mahmoudmohamedramadan** [comment]
@taylorotwell Thanks for your sweet words in the PR rejection and, I wished ONLY to make Laravel easier because I love this framework so much

**Pull request closed without merging**
