### PR TITLE
[5.1] Adds --times param to migrate:reset and migrate

### LINKED ISSUE #9019: Proposal: ability to specify the number of migrations to apply/rollback
I've just created two models with ``php artisan make:model``, migrations were created also.
I have written the code for the first model and wanted to see if it fails. So I'd like to run only first migration as it is the only one that is ready. But when I ran ``php artisan migrate``, it applies all the new files that it finds within the ``--path`` option. And there's no option to run only first n migrations or to rollback only n of them.

I propose to implement the ``--num`` option which will be able to control how many migration files will be applied/rolled back now.

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes #9019 :smile:

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please update the tests. :)

**Comment by jbrooksuk** [comment]
I did buddy :)

**Comment by jbrooksuk** [comment]
Oh, just missing one.

**Comment by jbrooksuk** [comment]
WTF... I swear these were working.

**Comment by jbrooksuk** [comment]
Fixed :)

**Comment by lukasgeiter** [comment]
I'd suggest calling it differently though. `--times` kind of reads like, *migrate the database n times*.
Maybe something like `--take` would be better?

**Comment by taylorotwell** [comment]
No intention of supporting this.

**Pull request closed without merging**
