### PR TITLE
[8.x] Schema Dump

### PR DESCRIPTION
**Pull request by taylorotwell**
This PR adds support for a new `php artisan schema:dump` command which uses `mysqldump` or `pgdump` to dump the current state of your schema to a `database/schema/{connection}-schema.mysql` file. 

When this file exists and `php artisan migrate` or `php artisan migrate:fresh` is run AND no migrations have run against the database yet (`migrations` table is empty), this schema file will be loaded into the database first and then any outstanding migrations will be run. This means that effectively this schema file would typically only ever be used during local development or during CI testing. In production, you would typically already have migrations that have run in the past so this schema file would never be triggered.

Once the schema file is created, any or all of your existing migrations my be deleted as long as they have already run against your production environment. They are no longer needed during local development since the schema file exists. For convenience, a `--prune` flag has been added to the `schema:dump` command to delete your existing migrations after dumping the schema.

This new feature solves two problems. First, it relieves developers from having a huge migrations directory full of files they no longer need. Second, loading a single schema file is quicker than running hundreds of migrations for each test class in your applications, so your tests can run much faster when using a schema.

### CODE REVIEW

**Comment by alexbowers** [comment]
I haven't had a chance to play with this yet, but i've found mysqldump to have issues with MySQL generated columns in the past, i'll try it out at the weekend if i get the chance, but something worth noting if you haven't come across those problems before

**Comment by alexbowers** [comment]
Also, worth noting, how does this interact with migrations from packages?

**Comment by schrapel** [comment]
This is really cool. One project some junior developers have made changes to production databases manually without migration files and I've been wanting to get migration files in sync with the production database and this seems like it will solve that problem. Thanks!

**Comment by devmsh** [comment]
Love it, but I can't imagine the best workflow to use it, I think the only safe way to use it is to run the command against the production server because its the only place that will exactly know what's migrated. Them I need to push these changes from the server to me git repo! Otherwise a conflict will happen at the next deploy?

**Comment by taylorotwell** [comment]
@devmsh - no that's not how you should use it. I detail how to use it in my original comment.

**Comment by mnabialek** [comment]
Cool idea. I also merge migrations into single dump and use my package https://github.com/mnabialek/laravel-quick-migrations to speed up Dusk tests (when you cannot use DatabaseTransactions) so I can confirm merging migrations into single database dump makes difference in tests speed.

**Comment by sonnygauran** [comment]
wondering how this will affect package migrations

**Comment by tabacitu** [comment]
> wondering how this will affect package migrations

Package migrations should be fine. AFAIK it's standard practice for packages to first publish the migrations to ```database/migrations```, _then_ run them. That way they'll also be run when moving to production. Or when someone else installs the project.

**Comment by alexbowers** [comment]
@tabacitu It isn't necessarily standard practice to do that, since it is possible for packages to provide their own migrations folders via Service Providers and Laravel will execute those migrations also.

**Comment by narwy** [comment]
@taylorotwell Option to migrate from dump also maybe? (speeds)

**Comment by emielmolenaar** [comment]
This is nice. How would we deal with data that is migrated though? For example, when the schema changes, you might want to move data around. Or you might want to create a migration to insert new roles or permissions.

**Comment by kohlerdominik** [comment]
We have the same issue as @emielmolenaar . As Seeders are not versioned, it's hard to add with them in a production environment.

Let's say we have predefined roles in a role table. Now i released a new Feature, let's say a  `FlightsList`, and i need to add permissions for this to existing Admin-role. So i run this in the migration:


```php
public function up() 
{
    Role::firstWhere('name', 'Admin')
        ->permission()
        ->attach(Permission->firstWhere('name', 'flights.list'));
}
```

@taylorotwell maybe it would make sense to provide a `DataInsertationInterface` with `abstract public function insert()` to it? So we could keep these migrations with `$migration instanceOf DataInsertationInterface`. `php artisan migrate` would run all migrations first, and then run migrations with DataInsertation?

**Comment by driesvints** [comment]
It's always best to extract data changes from your migrations. Your migrations generally don't run twice in your production environment and in your tests you don't want to migrate data every time your migrations are changed.

**Comment by emielmolenaar** [comment]
@driesvints How can we accomplish that? I think migrations are generally a fine way to add or modify data; however if there any other ways to do this thus making this new feature even more useful I am open to suggestions.

**Comment by driesvints** [comment]
@emielmolenaar just remove the data modification lines from your migrations when you've run them in production.

**Comment by hubertnnn** [comment]
How will this affect database compatibility?
Eg. if I want production to run on MySQL but Unit Tests and some of the local envs to use SQLite

**Comment by GautierDele** [comment]
> How will this affect database compatibility?
> Eg. if I want production to run on MySQL but Unit Tests and some of the local envs to use SQLite

You can choose the database connection
php artisan schema:dump --database=mysql

**Comment by hubertnnn** [comment]
I don't think that will help either if the driver in that connection will change eg.
```
 'connections' => [
        'main' => [
            'url' => env('DATABASE_URL'),
        ],
        'legacy' => [
            'url' => env('LEGACY_DATABASE_URL'),
        ],
        'test' => [
            'url' => env('UNIT_TEST_DATABASE_URL'),
        ],
]
```
and following .env:
```
// On production
DATABASE_URL=mysql://root:password@127.0.0.1/forge?charset=UTF-8
UNIT_TEST_DATABASE_URL=sqlite://localhost/storage/database_unittest.sqlite

// On local
DATABASE_URL=sqlite://localhost/storage/database.sqlite
UNIT_TEST_DATABASE_URL=sqlite://localhost/storage/database_unittest.sqlite
```

As you can see the connection did not change (is still "main") but the driver did.

My question is if in this case the database dump will be stored in some platform agnostic format and will it work, or will it cause an error.

**Comment by alexbowers** [comment]
It isn't in an agnostic format, its in the same format as the platform you export in, supporting only mysql and postgres (based on mysqldump or postgresdump being used).

**Comment by isclopezm** [comment]
I have been doing this "by hand" just to have a better control of the migration files, I never thought about how this may help on tests. Thanks for always be one step ahead!!

**Comment by jonathanpmartins** [comment]
I just saw this new feature and it really amused me, very nice! It will help a lot of people and save a lot of time. If you have a lot of migrations you can significantly reduce the time to migrate them all. 
This otherwise, does not resolve my problem. The number of migrations of the project is pretty close to 1 migration per table. No need to optimize anything here.

**My question: - It is possible to decrease even more the migration time?**

I explain It here: https://stackoverflow.com/questions/63855888/faster-laravel-migration-for-projects-with-a-lot-of-tables

**Comment by mfn** [comment]
Another way I use is:
1. run all tests in transactions (using PgSQL though, not sure about MySQL)
2. only re-run the migrations when they actually change
  A cheap hash function over all the migration files and if that hash changed, I re-run the migrations. Which in practice is only on branch switch.

The 1) guarantees the DB is always in the same state after tests.

Saved me a lot of time when I too had the need to only run singular tests.

**Comment by milewski** [comment]
I think this feature is pretty nice, however, It seems that won't work at all for those who don't run tests using the same database as the one used in production e.g `sqlite:memory` vs `mysql`, as soon as I make the dump a new file called `mysql-schema.sql` is created ... but that's it.. when running the tests all migrations are gone (pruned) and all tests fail as the `mysql-schema.sql` won't be loaded as due during tests it uses SQLite .. so I would assume it would be trying to find a file called `sqlite-schema.sql` instead but as there's one.. it doesn't work...

**Comment by driesvints** [comment]
@milewski you can choose to dump the file and keep the migrations by not using the `--prune` flag.

**Comment by lk77** [comment]
Hello,

is it recommended to prune migrations during a major release ? can we consider that users should have run all existing migrations before updating to the new version that remove those migrations ?

they can always go back to the previous version to run the migrations and then update again.

**Comment by driesvints** [comment]
I personally don't recommend this approach for packages but if you follow semver then yes you'll have to do it in a major release and note about it in a changelog/upgrade guide.

**Comment by Bouhnosaure** [comment]
Hi, i'm running in the same issue, like @milewski explains, if we prune all migrations we can't setup any other database that are different than the one we use to generate the SQL dump ( and it's logical ) .

However, it is possible to make an export for an sqlite or any other database, but we need to setup this one before and dump it after.

I've tried this and got and sqlite-schema.sql and it's the one that is used when the tests runs migrations ( with a sqlite:memory database ) 

But what i've got is `The command "sqlite3 $LARAVEL_LOAD_DATABASE < $LARAVEL_LOAD_PATH" failed.` but in my opinion it's an issue on my side.

So, it could be interesting to dig how we can improve the workflow to dump ( and prune ) when we have a different database for testing.

**Comment by driesvints** [comment]
@Bouhnosaure since sqlite support has been merged my solution from above won't work anymore. I'll send in a note to the docs to try to explain that this cannot be used in combination with an in memory database.

**Comment by Bouhnosaure** [comment]
Alright @driesvints, indeed i was a bit sceptical when i've began my upgrade to 8.x for this reason, thanks for your quick answer !

**Comment by sdjrppl** [comment]
Hi 
I'm currently having a problem with migrate:refresh command using previous dump file, mysql .
I'm testing brand new project install. This project already have a **php artisan migrate:dump --purge** file.
When I do **php artisan migrate:refresh --seed** , first time is ok. Second time It throws error that table A already exists on database. Which means. My schema dump, have migrations previously created, but using **--purge** , they not exists on migrations folder, like supposed. What I'm missing here ? 
Thanks

**Comment by sdjrppl** [comment]
Well I've edited my .dump file with drop if exists statement before create table. Idk if it's supposed to do this. Using php artisan schema:dump --prune maybe should have this as default behaviour no ? thanks

**Comment by emielmolenaar** [comment]
Try php artisan migrate:fresh --seed. This will drop all tables first.

**Comment by sdjrppl** [comment]
@emielmolenaar Dam I've mistaken php artisan migrate:refresh --seed with migrate:fresh --seed . You are right of course , wtf .

**Comment by sdjrppl** [comment]
nevermind my comment :confused:

**Pull request merged**
