### PR TITLE
[5.9] Add the option to pass an options array to Storage::url($path, $options) 

### PR DESCRIPTION
**Pull request by donkfather**
Some services have the option to receive some modifiers when retrieving the url. For example Cloudinary which I am struggling with now has the option to generate a url with transformations.

I tried to find a better way but couldn't find one. I am even opened to overwrite FilesystemAdapter locally but i didn't find a way.

If necessary i will write tests but first i want to know if you approve the idea.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Which Flysystem driver are you going to be using this with? Can you provide a link to it?

**Comment by taylorotwell** [comment]
Ping.

**Comment by GrahamCampbell** [comment]
Seems like a bit of a bypass of the idea if flysystem to know what driver you're using, and pass driver specifics, beyond "is it cloud or local"?

**Comment by olivernybroe** [comment]
I think he might refer to this https://github.com/enl/flysystem-cloudinary driver.
When using `getUrl` with this driver, you can for example pass in the `width` and `height` through the options.

https://github.com/enl/flysystem-cloudinary/blob/407fa71a88f631898e37671325c82f22aec2328f/tests/Plugin/GetUrlTest.php#L11-L19

**Comment by Donkfather** [comment]
@taylorotwell  sorry for the late response. I used [this one](https://github.com/carlosocarvalho/flysystem-cloudinary) in my current implementation. 
I managed to make it work by extending the Storage like this:
`
Storage::extend('cloudinary', function ($app, $config) {
    return new App\FilesystemAdapter(new Filesystem(new CloudinaryAdapter($config)));
});
` 

I created a custom FilesystemAdapter that extends the Illuminate\Filesystem\FilesystemAdapter and overwrites the `url` method by adding another parameter `$options = [ ]`.

**Comment by taylorotwell** [comment]
OK. Will hold off on this for now. I do basically agree with Graham it's a bit of a leaky abstraction at that point and you may be better off just using the storage system's API directly.

**Pull request closed without merging**
