### PR TITLE
[6.x] Null type check consistency

### PR DESCRIPTION
**Pull request by fazed**
This PR aligns `null` checks with comparable type checks like `true` and `false`. Though this might not improve performance by any means, it makes a lot more sense to me than using the `is_null` function (opinions will differ).

My other motivation was the amount of calls to the `is_null` function in our call graph. Using the primitive check should reduce the amount of calls (went from 2600+ to not even showing up). Whether this interests anybody I don't know, but it reduced the amount of clutter on our call graph so we're happy.

PR also contains removal of redundant regex escapes and minor step count optimisations.

### CODE REVIEW

**Comment by driesvints** [comment]
I'm not a fan of Yoda style comparisons tbh. I feel they don't read well.

**Comment by fazed** [comment]
> I'm not a fan of Yoda style comparisons tbh. I feel they don't read well.
Cool, I can live with that. Removing Yoda style might also be more consistent with existing code. I'll flip the statements for consistency.

**Comment by antonkomarev** [comment]
> PR also contains removal of redundant regex escapes and minor step count optimisations.

This better do as a separate PR to make it easier to review and if this PR will be rejected - then other ones could be accepted.

**Comment by browner12** [comment]
I agree, since this PR covers so many files, separate them out so each PR only does 1 thing.

There is some discussion in the PHP docs that in v7, `is_null()` is actually slightly more performant than `=== null`.  Do we have a way of verifying there is no performance drop with this change?

**Comment by GrahamCampbell** [comment]
We should be very careful that the semantics has not accidentally been changed with these sorts of refactoring.

**Comment by fazed** [comment]
> You'd better do it as a separate PR to make it easier to review and if this PR will be rejected - then other ones could be accepted.

Will do; reverted the regex changes will open a new PR.

>There is some discussion in the PHP docs that in v7, is_null() is actually slightly more performant than === null. Do we have a way of verifying there is no performance drop with this change?

Apparently the performance difference is zero to none, 1-5 nanoseconds either way depending on the test/benchmark used. Ever since the standardisation of OPcache in PHP 7 the performance might swing either way. Prior to PHP 7 each subsequent call would cause (minor) performance hits.

>We should be very careful that the semantics has not accidentally been changed with these sorts of refactoring.

I Agree. I've been careful with each of the changes; even though changes should be double checked.

**Pull request closed without merging**
