### PR TITLE
[8.x] Don't overwrite minute and hour when specifying a time with twiceMonthly()

### LINKED ISSUE #35429: Console schedule twiceMonthly at a given time
- Laravel Version: 8.x
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description:
twiceMonthly at a given time is not working ok

image

dailyAt($time) is set the minute and hour, then in function return set minute and hour to 0 again.

### Steps To Reproduce:
```
$schedule->command('test:test')
                ->twiceMonthly(1, 16, '1:30');
```

### Fixed:
```
public function twiceMonthly($first = 1, $second = 16, $time = '0:0')
    {
        $daysOfMonth = $first.','.$second;

        $this->dailyAt($time);

        return $this->spliceIntoPosition(3, $daysOfMonth);
    }
```

### PR DESCRIPTION
**Pull request by JayBizzle**
Fixes https://github.com/laravel/framework/issues/35429

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Is this bug present in 6.x?

**Comment by driesvints** [comment]
@GrahamCampbell it seems it is. @JayBizzle can you send this to 6.x as well?

**Comment by JayBizzle** [comment]
Will do this evening unless someone beats me to it 👍🏻

**Comment by JayBizzle** [comment]
@driesvints This bug is not present on the `6.x` branch. The extra `$time` parameter was added in `7.x`

See here https://github.com/laravel/framework/pull/33274

**Pull request merged**
