### PR TITLE
[9.x] Throw exceptions when migration methods are missing

### PR DESCRIPTION
**Pull request by Kolyunya**
Current migrator logic is broken. It does not report any errors when migrations having no `up()` or `down()` methods get applied or rolled back. It just silently pretends like there's no problem, when this is an obvious problem. When we want to *apply* the migration it *must* have the `up()` method. When we want to roll it back it *must* have the `down()` method.

Current logic leads the application to a broken state: migration is registered as `migrated` or `rolled back` and we *assume* that its changes are applied or rolled back when in reality the developer just forgot to implement the corresponding method.

This is kind of a breaking change, so I suppose it should be targeted to the `master` branch.

### CODE REVIEW

**Comment by taylorotwell** [comment]
It is intended that you can forego having `down` methods. They aren't 100% necessary.

**Comment by Kolyunya** [comment]
@taylorotwell 

1. Is the `up()` method not 100% necessary by design as well? Because currently it is not. What is the point of having a migration which does nothing?
2. `down()` methods are indeed optional *but* when they are missing it automatically means that the migration can not be reverted.
3. Current design brings the application to a broken state when a migration without the `down()` method was reverted but it can not be applied *again* because for example the table already exists.

**Comment by paras-malhotra** [comment]
Down or up methods need not be mandatory. I know of so many experienced Laravel devs that simply dont write downs. You're in control of your own app, what's wrong with that?

You assume simply by writing down methods, migrations are reversible. Unfortunately the real world doesn't operate the same way.

**Comment by Kolyunya** [comment]
@paras-malhotra I personally *never* write downs. This is not my point. My point is that the migration having no `down()` **can not be reverted** by definition. As well as migration having no `up()` **can not be applied** by definition.

Again, I don't propose to make those methods mandatory I'm just saying that an exception must be thrown when **only** a missing method is being called.

It's perfectly fine to have a project convention to not write downs. No problem with that. `artisan migrate` will work fine. But `artisan migrate:rollback` must throw when it can not find corresponding methods.

**Pull request closed without merging**
