### PR TITLE
[10.x] Extended View contract with fragments methods

### PR DESCRIPTION
**Pull request by BrunoMollo**
Hi, when  using Blade fragment my LSP throws the following error:

image

I fixed it by adding the four corresponding methods in the View interface.

### CODE REVIEW

**Review by mateusjunges — COMMENTED** [review]
I believe that changing/adding new methods to a contract is a breaking change accordingly to [SemVer](https://semver.org/)

**Comment by dammy001** [comment]
Yeah, you are right @mateusjunges

**Comment by pelmered** [comment]
Yea, this looks like a very large impact change that might not be worth it. Maybe it could be a trait instead? Or maybe it could be added to IDE helper if it is not there already?

**Comment by BrunoMollo** [comment]
Thanks for your response. I managed to remove the error by using phpdoc as show in the following snippet:

```php
        /** @var \Illuminate\View\View */
        $view = view("category.index", ["category_list" => $category_list]);
        return $view->fragment("category-list");
```
Surely it is not the more type-safe solution nor the more ergonomic one, but works without modifying the framework.

However, I would like to know why adding new methods to an interface might result in breaking changes. I understand that modifying existing methods is a breaking change, but adding new ones sounds like a minor update to me. On the other hand, i might be quite wrong due to my lack of experience, i would love to learn.

**Comment by driesvints** [comment]
We can't add these methods on a patch release sorry.

**Comment by pelmered** [comment]
> However, I would like to know why adding new methods to an interface might result in breaking changes. I understand that modifying existing methods is a breaking change, but adding new ones sounds like a minor update to me. On the other hand, i might be quite wrong due to my lack of experience, i would love to learn.

Adding new methods to an interface/contract means that any class that implements that contract needs to implement those methods. For a normal class that you can extend it would not be a breaking change, but for an interface it is.

**Comment by BrunoMollo** [comment]
Thanks @pelmered for the explanation. Now it seem more clear to me. By running some grep commands i verified that only `/Illuminate/View/View.php` implemented this interface (class that already has this method). But this contract might be used by an external package.

Really, thanks for your time, i really appreciate it.

**Pull request closed without merging**
