### PR TITLE
[5.4] Force reconnect

### PR DESCRIPTION
**Pull request by halaei**
To fix https://github.com/laravel/framework/issues/15865

### CODE REVIEW

**Comment by themsaid** [comment]
I'm not sure I understand the test you wrote, don't think it's testing anything!

Also how would you use this new parameter to force reconnecting?

**Comment by halaei** [comment]
Yes the test is dummy: it checks that exception is not raised as opposed to `testTransactionsDecrementedOnTransactionException()`

**Comment by halaei** [comment]
I have my example of how the new parameter is used here: https://github.com/laravel/framework/issues/15865#issuecomment-253294969

**Comment by taylorotwell** [comment]
This feels really strange and like we're avoiding some other problem. Why would we want to have a "force" parameter on a `disconnect` method. We already told it to "disconnect". What does "force" even mean semantically here? We already told it to do something. Now we're telling it to "no, seriously, disconnect" in even stronger terms? I don't know. The whole concept feels weird.

**Comment by halaei** [comment]
Currently when we tell disconnect, it means "disconnect if and only if not
in the middle of a transaction". Maybe this is wrong in the first place. If
it is for the sake of English language, I am not a native speaker. My
concern was to keep BC and not to introduce another function to do
"disconnect even if within transaction". Don't know if it is the best way
but I feel something needs change, doesn't it?

**Comment by halaei** [comment]
Another option, that may be more appropriate is let disconnect() do
"disconnect no matter what" and then those parts of code that need to
disconnect iff not in a transaction do "if not in transaction then
disconnect else throw exeption". That may be a new function if many
duplicates?

**Comment by taylorotwell** [comment]
I would be curious to know why we are checking if we are already in a transaction and throwing that exception in the first place.

**Comment by halaei** [comment]
Not sure, but sounds like it relates to the idea of automatically retrying
queries if they failed because of lost connection. Then a safegaurd is
added for not retrying if in the middle of a transaction, because when
connection is lost, the transaction is also lost, hence retrying is partial
and terrible. But the implementation of the check seems to be in a wrong
place.

**Pull request closed without merging**
