### PR TITLE
[5.1] Namespace the global serialization functions.

### PR DESCRIPTION
**Pull request by chrishalbert**

### CODE REVIEW

**Comment by taylorotwell** [comment]
I'm curious why you are even seeing this issue?

**Comment by JosephSilber** [comment]
I have a feeling this has something to do with this blogpost: [Optimizing PHP performance by using fully-qualified function calls](http://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/).

**Comment by GrahamCampbell** [comment]
No, it's to fix partial serialization bugs. Nothing to do with performance.

**Comment by taylorotwell** [comment]
Yeah but what I'm asking is why would this fix a partial serialization bug?

**Comment by chrishalbert** [comment]
I'm honestly not sure why this was throwing the error. AWS seems to have their own flavors of servers/services, so it could have something to do with their php build. I'll see if I can get some more diagnostics.

**Comment by taylorotwell** [comment]
Can you re-open this once we have more info? This should make no difference in terms of the results.

**Comment by lintaba** [comment]
hotfix:
```
<?php
namespace Illuminate\Cache
{
    function unserialize($arg){
        return \unserialize($arg);
    }

    function serialize(string $arg){
        return \serialize($arg);
    }
}
```

**Comment by lintaba** [comment]
For us it was because of php5/php7 migration, with invalid references in the database. 
If you encounter this issue, try to flush the cache, or check the entries whether they have valid classes.

**Comment by chrishalbert** [comment]
@lintaba That is correct. It was an error occurring with how the classes were being serialized in redis. Once I did the swap to php7, or vice-versa, if there were lingering cached objects that were attempted to be consumed by the newly swapped php version, I'd encounter this error. Ensuring the cache was clear fixed the problem.

**Pull request closed without merging**
