### PR TITLE
[5.1] Remove useless else

### PR DESCRIPTION
**Pull request by lucasmichot**
Remove useless else

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You tried this before, and before, and it was rejcted because there's no point.

**Comment by lucasmichot** [comment]
No. There was a failing test.

**Comment by GrahamCampbell** [comment]
Last time, yes, but the time before, no. ;)

**Comment by lucasmichot** [comment]
Probably
https://github.com/laravel/framework/pull/6334

**Pull request closed without merging**
