### PR TITLE
[5.7] Output schedule task run time just like queue job

### PR DESCRIPTION
**Pull request by leo108**
The current output of `schedule:run` is like

```
Running scheduled command: '/usr/bin/php7.1' 'artisan' task1-name > '/dev/null' 2>&1
No scheduled commands are ready to run.
No scheduled commands are ready to run.
No scheduled commands are ready to run.
No scheduled commands are ready to run.
Running scheduled command: '/usr/bin/php7.1' 'artisan' task2-name > '/dev/null' 2>&1
No scheduled commands are ready to run.
No scheduled commands are ready to run.
```

We don't know the exact time of task running.

This PR adds a DateTime string at the beginning of the output:

```
[2018-08-19 23:00:00]Running scheduled command: '/usr/bin/php7.1' 'artisan' task2-name > '/dev/null' 2>&1
[2018-08-19 23:01:00]No scheduled commands are ready to run.
[2018-08-19 23:02:00]No scheduled commands are ready to run.
```

like what queue worker does.

So that we can know that task2 was triggered at 2018-08-19 23:00:00, it makes debugging schedule-related problems easier.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Shouldn't there maybe be a space between the date and the word or something?

**Comment by leo108** [comment]
@taylorotwell Fixed

**Comment by laurencei** [comment]
Actually this is using the wrong output.

The `runAt` timestamp you have created is the "current time" - but that is not the time of the evalation of what scheduled tasks to run.

If the purpose is for debugging etc - you should put the `$this->startedAt` time - which is already stored and used as the evaluated time.

Otherwise you will get strange timestamps for tasks that did not run, when the evaluated timestamp is different to the current timestamp (i.e. if you have longer running sync jobs etc).

**Comment by mfn** [comment]
I'm not fond of this approach, it seems to be something like logging should handle (yes, I'm aware no logging is involved here, so…).

At least make the method `protected` so that it can be overriden at developers convenience. Not everyone might agree with your choice of date format (I, for one, despise formats not containing the timezone).

**Pull request closed without merging**
