### PR TITLE
Remove deprecated password validation rule

### PR DESCRIPTION
**Pull request by netpok**
In #37650 the `password` rule was renamed to `current_password` with the intention of removing the old rule in the next major version. This PR removes it.

The original reasoning behind this was that later `password` could be used as an alias for the new `Password::defaults()` while I'm still supporting the idea I'm not sure whether it should be done in the next version or in a later one.

The problem with implementing it right away is that it can pass for the provided password even if it's not valid for developers who does not follow the upgrade guide. By waiting a few minor or even a major version we could prevent security issues because it would simply throw an exception.

If it should be included in this version I'm willing to create a pull request for it.

### CODE REVIEW

**Comment by driesvints** [comment]
Feel free to ignore the failing PHP 8.1 tests for now.

Btw, shouldn't we update the tests to use the current_password rule instead?

**Comment by netpok** [comment]
The current_password rule already have the same tests at [line 749](https://github.com/laravel/framework/blob/3e2ef3207e2a3e103893614a0ea1718360a5c558/tests/Validation/ValidationValidatorTest.php#L749)

**Comment by Jubeki** [comment]
I would support aliasing the new Password::defaults() rule to password in Laravel 9.

What about adding an validation config where you can configure the Password rule?

**Comment by driesvints** [comment]
@netpok if you rebase with master test should pass now

**Comment by netpok** [comment]
Rebased it
---
@Jubeki what do you mean by adding a validation config?

1. If you mean to support the old or the new behavior I'm against that, developers should just simply migrate.
2. If you mean to configure the default password rule you can already do that by using `Password::default`, adding a new config option (and file) is out of the scope for this PR.

**Pull request merged**
