### PR TITLE
Add creation and update datetime columns

### PR DESCRIPTION
**Pull request by Jim-Webfox**
Add datetimes function to create "created_at" and "updated_at" columns using "datetime" columns instead off "timestamps" columns to add further future proofing.

### CODE REVIEW

**Comment by ziming** [comment]
I'm curious, how does it future proof compared to timestamps?

**Comment by Jim-Webfox** [comment]
timestamps currently has a maximum date time of 03:14:08 on 19 January 2038. datetime can go to 9999-12-31 23:59:59. Even knowing its 15ish years away thought it'd be good to implement an alternative.

**Comment by taylorotwell** [comment]
This should go to 9.x or 10.x branch. Master is technically Laravel 11 (2024 release).

**Comment by Jim-Webfox** [comment]
My bad, thank you.

**Pull request closed without merging**
