### PR TITLE
[5.4] Stop using asset helper function inside mix helper function

### PR DESCRIPTION
**Pull request by themsaid**

### CODE REVIEW

**Comment by it-can** [comment]
Thanks

**Comment by bram1028** [comment]
@themsaid Can I ask why this change was made? This is a breaking change, if you serve your app from a sub-folder. Will have to use `{{ asset(mix(...)) }}` now.

**Comment by dwightwatson** [comment]
The breaking change was actually introduced in #19968, this reverts back to how it was working beforehand. You can see my comment in that thread about a use-case where assets aren't served from the same domain as the app. For most people serving assets from their root-level domain application it's not going to matter, but it gives people with slightly different requirements (yourself included) a little more flexibility.

**Comment by bram1028** [comment]
Ah, I see. Thanks @dwightwatson

**Pull request merged**
