### PR TITLE
[5.7] Fix postgres bool support

### PR DESCRIPTION
**Pull request by Ridzhi**
Add boolean support for pgsql driver.

### CODE REVIEW

**Comment by Ridzhi** [comment]
> I understand the code, but what problem does it fix?
> 
> Question may sound stupid but I'm using Laravel with PostgreSQL for years and have LOTS of booleans => never had an issue.

When I try insert boolean value to boolean column, value convert to int and I catch exception, for example `SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "assigned" is of type boolean but expression is of type integer`

**Comment by mfn** [comment]
FTR, I can't replicate this. What version of PostgreSQL are you using?

With Laravel 5.7 and PgSQL 9.6, everything is working fine.

**Comment by coraxster** [comment]
@mfn @taylorotwell 
hey guys
I also got this problem.
You can reproduce it when the PDO::ATTR_EMULATE_PREPARES attribute is true.
I made a little test. Please feel free to try.
https://github.com/coraxster/laravel-pg-bool-test

So could you please re-open the PR?
Thank you! 
Also @Ridzhi thank you for your fix!

**Comment by mfn** [comment]
So I guess the answer to me comment https://github.com/laravel/framework/pull/26259#issuecomment-433542489 is this ?
>  You can reproduce it when the PDO::ATTR_EMULATE_PREPARES attribute is true.

But why would you do that? Isn't this unsafe and basically, if the dev decides to do that, you're on your own?

The frameworks code works as intended to me and breaks when people tinker around with that PDO attribute…

**Comment by coraxster** [comment]
> But why would you do that?
In some cases you have to do that. For example while using Postgres cluster with a front-end balancer.
https://pgbouncer.github.io/faq.html#how-to-use-prepared-statements-with-transaction-pooling

btw. its pretty wired to convert bools to int when Postgres has the true bool type instead mysql's tinyInts. strange that it works in basic cases.

**Comment by mfn** [comment]
> In some cases you have to do that. For example while using Postgres cluster with pgbouncer as a front-end.
> https://pgbouncer.github.io/faq.html#how-to-use-prepared-statements-with-transaction-pooling

I am in fact using pgbouncer. That addition to the infrastructure outside of Laravel had 0 effect on any kind of application behaviour, lest about boolean/int conversion stuff.

Although I don't get explicit replies to that, I now believe it's due to change of `PDO::ATTR_EMULATE_PREPARES`, isn't it?

**Comment by mfn** [comment]
> Looks like you don't use transaction-pooling mode in pgbouncer. Thats the difference.

Thanks, you're right; I'm using `session`, good point 👍

**Comment by Ridzhi** [comment]
@coraxster Thank you for explanation, I was lazy. @mfn So, PR will be reopen/accepted ?

**Comment by mfn** [comment]
This PRs implementation would force an extra conversion call for all users, whether they're using this modification or not; I'm not really a fan of the implementation.

Also, no one explained _why_ use `PDO::ATTR_EMULATE_PREPARES => true`, what's the purpose? I also not sure what the connection actually is between pgbouncers configuration.

**Comment by coraxster** [comment]
found another solution.
just deleting optional `data_type` attribute here
https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Connection.php#L576

then all bindings will be used as PDO::PARAM_STR
got no problems with `INT` and `BOOL` with `ATTR_EMULATE_PREPARES ` works fine now

what do you think?

**Pull request closed without merging**
