### PR TITLE
[11.x] Add MSSQL 2017 and PGSQL 10 builds

### PR DESCRIPTION
**Pull request by driesvints**
Test the low end supported databases.

Would love to get help getting the tests to pass.

### CODE REVIEW

**Comment by Jubeki** [comment]
It seems like generated columns only exist as of PostegreSQL 12:
https://www.postgresql.org/docs/12/ddl-generated-columns.html

This Documentation (5.3 Generated Columns) does not exist on v11 or v10:
https://www.postgresql.org/docs/10/ddl.html

**Comment by Jubeki** [comment]
websearch_ts_query exists only as of PostgreSQL v11: https://www.postgresql.org/docs/release/11.0/

**Comment by Jubeki** [comment]
Primary key and foreign key on partitioned tables only exists as of PostgreSQL v11:
https://www.postgresql.org/docs/release/11.0/

**Comment by driesvints** [comment]
Thanks @Jubeki. We should be able to skip these tests then somehow.

**Comment by Jubeki** [comment]
```php
version_compare(Schema::getConnection()->getServerVersion(), '12.0', '<')
```
This should probably work.

**Comment by driesvints** [comment]
Was thinking more like a Phpunit annotation but I guess Phpunit doesn't uses those anymore? 🤔

**Comment by Jubeki** [comment]
There is already a check for the used type of database, so I don't think there is an Attribute for that:
https://github.com/laravel/framework/blob/13d28862ce18cfc6609080fcb02cd649b3eede82/tests/Integration/Database/SchemaBuilderTest.php#L342-L344

**Comment by Jubeki** [comment]
Maybe @crynobone has an idea about the Attributes.

**Comment by crynobone** [comment]
You need to write one to hook with Testbench, something like:

```php
<?php

namespace Illuminate\Tests\Testbench\Attributes;

use Attribute;
use Closure;
use Illuminate\Support\Facades\DB;
use Orchestra\Testbench\Contracts\Attributes\Actionable as ActionableContract;

#[Attribute(Attribute::TARGET_CLASS | Attribute::TARGET_METHOD | Attribute::IS_REPEATABLE)]
class RequiresDatabase implements ActionableContract
{
    /**
     * Construct a new attribute.
     *
     * @param  string  $driver
     * @param  string  $versionRequirement
     */
    public function __construct(public string $driver, public string $versionRequirement)
    {
        //
    }

    /**
     * Handle the attribute.
     *
     * @param  \Illuminate\Foundation\Application  $app
     * @param  \Closure(string, array<int, mixed>):void  $action
     * @return void
     */
    public function handle($app, Closure $action): void
    {
        $connection = DB::connection($this->driver);

        if (
            preg_match('/(?P<operator>[<>=!]{0,2})\s*(?P<version>[\d\.-]+(dev|(RC|alpha|beta)[\d\.])?)[ \t]*\r?$/m', $this->versionRequirement, $matches)
        ) {
            if (empty($matches['operator'])) {
                $matches['operator'] = '>=';
            }

            if (! version_compare($connection->getServerVersion(), $matches['version'], $matches['operator'])) {
                call_user_func($action, 'markTestSkipped', [sprintf("Requires %s:%s", $connection->getName(), $this->versionRequirement)]);
            }
        }
    }
}
```

**Comment by driesvints** [comment]
It's okay. Fine to leave the current skips. Just need to fix the postgres types failure and then this one is ready to go,.

**Comment by driesvints** [comment]
Nice, thanks @Jubeki

**Pull request merged**
