### PR TITLE
[5.2] Collection union function

### PR DESCRIPTION
**Pull request by john-main-croud**
Quick function to provide a true union of two collections

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please squash to one commit.

**Comment by john-main-croud** [comment]
Done :)

**Comment by GrahamCampbell** [comment]
Please fix the failing tests.

**Comment by mark86092** [comment]
@GrahamCampbell Something wrong with travis-ci.

**Comment by JosephSilber** [comment]
I'm just gonna link to this here: https://github.com/laravel/framework/pull/12223

**Comment by john-main-croud** [comment]
Fixed! Sorry about that - Travis seems to be having a headache generally but tests passed on PHP7

**Comment by GrahamCampbell** [comment]
Travis seems to be up and down today. I've just given it another kick.

**Comment by GrahamCampbell** [comment]
Please rebase and force push, and that'll fix travis.

**Comment by taylorotwell** [comment]
Union sounds better than concat and the PHP docs to refer to the + operator on arrays as a "union".

**Comment by salarmehr** [comment]
@john-main-croud `@return void` is incorrect at the phpdoc blcok

**Pull request merged**
