### PR TITLE
Fix whoops version

### PR DESCRIPTION
**Pull request by themsaid**

### CODE REVIEW

**Comment by deleugpn** [comment]
What's the difference?

**Comment by patrickbrouwers** [comment]
Isn't that the same as `^2.1.4` (https://getcomposer.org/doc/articles/versions.md#caret-version-range-)?

**Comment by themsaid** [comment]
@patrickbrouwers thanks :)

**Comment by themsaid** [comment]
@deleugpn it won't work if it's less than 2.1.4

**Pull request merged**
