### PR TITLE
[6.x] Add DocBlock for common Eloquent Builder methods

### PR DESCRIPTION
**Pull request by andriichuk**
Hi there. Laravel has a lot of magic and we have some problems with IDE code inspection. 
Now to solve this problem we are adding this DocBlock for a specific model:

image

Or document the query:

image

So please merge this PR to improve IDE code inspection

image

### CODE REVIEW

**Comment by gocanto** [comment]
you can always get away using 

```php
Foo::query()->first();
``` 

nevertheless, this would be nice to have as well.

**Comment by andriichuk** [comment]
@gocanto Yes, but I want to call the methods that are specified in the documentation without IDE inspection issues

**Comment by driesvints** [comment]
Please see previous attempts.

**Comment by mfn** [comment]
@andriichuk the problem with is PR is that it's not complete enough.

Yes, you can autocomplete `findOrFail` but now _all_ your models (i.e. `User::findOrFail()`) return `Model` => this is not correct and thus not useful.

I'd say https://github.com/barryvdh/laravel-ide-helper still solves this in the best pragmatic way.

**Comment by andriichuk** [comment]
@mfn Yes, I see the problem... autocomplete does not work for methods defined in the child model.
But how about this change?

```php
* @method static \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection findOrFail(mixed $ids, array $columns = ['*'])
```
->

```php
* @method static static|\Illuminate\Database\Eloquent\Collection findOrFail(mixed $ids, array $columns = ['*'])
```

Now `findOrFail` return the correct model.

**Comment by mfn** [comment]
Please take a look at ide-helper first, you'll find some inspiration there, e.g.
```php
            /**
             * Find a model by its primary key or throw an exception.
             *
             * @param mixed $id
             * @param array $columns
             * @return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection|static|static[] 
             * @throws \Illuminate\Database\Eloquent\ModelNotFoundException
             * @static 
             */ 
            public static function findOrFail($id, $columns = [])
```

**Pull request closed without merging**
