### PR TITLE
[6.x] Dismiss check with session data if viaRemember

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by voyula** [comment]
Already, remember_me cookie provide cached password_hash value.
Not needed recache password_hash value for comparison cached password_value and actual password value with session data.

**Comment by taylorotwell** [comment]
Define "huge loss of performance" for your services.

**Comment by voyula** [comment]
I tested with Apache Benchmark for Now;
sudo /usr/bin/ab -n 1000 -c 10 -C URL

Without This PR:
Document Path:          /page
Document Length:        7511 bytes

Concurrency Level:      10
Time taken for tests:   51.508 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      8778000 bytes
HTML transferred:       7511000 bytes
Requests per second:    19.41 [#/sec] (mean)
Time per request:       515.078 [ms] (mean)
Time per request:       51.508 [ms] (mean, across all concurrent requests)
Transfer rate:          166.43 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       15   86  94.7     45     503
Processing:   103  425 823.4    343   10977
Waiting:      103  424 823.3    343   10977
Total:        127  511 832.5    430   11051

Percentage of the requests served within a certain time (ms)
  50%    430
  66%    545
  75%    616
  80%    649
  90%    760
  95%    909
  98%   1084
  99%   1823
 100%  11051 (longest request)

With this PR:

Document Path:          /page
Document Length:        7511 bytes

Concurrency Level:      10
Time taken for tests:   40.494 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      8778000 bytes
HTML transferred:       7511000 bytes
Requests per second:    24.69 [#/sec] (mean)
Time per request:       404.941 [ms] (mean)
Time per request:       40.494 [ms] (mean, across all concurrent requests)
Transfer rate:          211.69 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       15   85  94.4     46     550
Processing:   103  317 171.1    304    1017
Waiting:      103  316 170.7    302    1017
Total:        127  402 183.3    404    1140

Percentage of the requests served within a certain time (ms)
  50%    404
  66%    487
  75%    531
  80%    561
  90%    634
  95%    713
  98%    792
  99%    926
 100%   1140 (longest request)

**Comment by voyula** [comment]
I don't think necessary recache password_hash on session data if viaRemember.
Because already have a cache on remember_me cookie.

**Comment by taylorotwell** [comment]
I'm not changing this security related feature on an LTS sorry. Please do not submit this PR again.

**Comment by voyula** [comment]
For 8.x too?

**Comment by voyula** [comment]
I don't think this a feature, maybe bug fix.

**Pull request closed without merging**
