### PR TITLE
[5.4] Create a mapToGroups method

### PR DESCRIPTION
**Pull request by JosephSilber**
```php
$users->mapToGroups(function ($user) {
    return [$user->country => $user->id];
});

/*
    [
        'canada' => [23, 1],
        'france' => [34, 3],
        'germany' => [9],
        'us' => [4, 7, 2],
    ]
*/
```

### CODE REVIEW

**Comment by thecrypticace** [comment]
Seems neat. I have, on occasion, needed to use `->map` after a groupBy so this could be a neat addition. I'm not 100% on the name `mapToGroups` though. Doesn't feel right but I can't think of a better one.

Also, the above example with Higher Order Messages can be written as:
```php
$users->groupBy("country")->map->pluck("id");
```

Want to see something even crazier? Add a groupBy proxy and you can write it like this:
**Warning: Please don't actually do this. Code readability and intent are important**
```php
$users->groupBy->country->map->map->map->id;
```

Aside: `keyBy` and `groupBy` both would benefit from being in the default proxy list. Not sure why they weren't included. I know you can add them with `Collection::proxy` but it still seems like a sensible default.

**Comment by JosephSilber** [comment]
> the above example with Higher Order Messages can be written as

I intentionally created a simple example. But if you do more complex stuff, you may end up with two closures.

Additionally, if the value you're mapping to requires the original key, you're out of luck without this `mapToGroups`. You'd have to resort back to an ugly `foreach`.

**Comment by thecrypticace** [comment]
> I intentionally created a simple example. But if you do more complex stuff, you may end up with two closures.

Yeah, I figured as much. Was just pointing it out.

> you're out of luck without this `mapToGroups`

Yeah. What I usually try to do is map first and include an extra entry for grouping if needed. But I always felt that it was a bit of a hack. Just depends on use case.

**Comment by ConnorVG** [comment]
I feel like this should follow the naming of `flatMap` and be named `groupMap`.

**Comment by JosephSilber** [comment]
@ConnorVG to me, `groupMap` means something else. I'd expect `groupMap` to work like this:

```php
$collection = collect([
    'a' => [2, 5],
    'b' => [8, 9],
]);

$collection->groupMap(function ($number) {
    return $number * 2;
});

/*
    [
        'a' => [4, 10],
        'b' => [16, 18],
    ]
*/
```

...which would also maybe be a useful method, but this `mapToGroups` is something else.

**Comment by ConnorVG** [comment]
Eh? That's just a map map.

**Comment by fernandobandeira** [comment]
I think we could add another test for numeric keys:

```php
$users->mapToGroups(function ($user) {
    return [$user->age => $user->id];
});

/*
    [
        17 => [23, 1],
        23 => [34, 3],
        31 => [9],
        44 => [4, 7, 2],
    ]
*/
```
So we assert that it won't reindex the array in the future...

**Pull request merged**
