### PR TITLE
[5.3] Adding unicode support

### PR DESCRIPTION
**Pull request by mohamedsabil83**
Adding line (type => 'unicode') to support Unicode message for non Latin character

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Tests fail.

**Comment by mohamedsabil83** [comment]
How, I try it and receive an Arabic text correctly instead of (?) or which test you mean?

**Comment by themsaid** [comment]
@mohamedsabil83 Travis tests fail after your change: https://travis-ci.org/laravel/framework/builds/179628887

**Comment by mohamedsabil83** [comment]
Can you do it as right way ? Note when I add this line, sms notification support unicode normally

**Pull request merged**
