### PR TITLE
Add "resolution" order to route:list command

### PR DESCRIPTION
**Pull request by antonioribeiro**
This can be handy when debugging resolution problems, as we can see routes in the exact order they will be resolved.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Is this the same as just not passing a sort at all?

**Comment by antonioribeiro** [comment]
Not the same, because the default is sort by `uri`:

``` php
[
    'sort', null, InputOption::VALUE_OPTIONAL, 
    'The column (resolution, domain, method, uri, name, action, middleware) to sort by', 
    'uri' <= DEFAULT
],
```

**Comment by Synchro** [comment]
@antonioribeiro if you are trying to figure out exactly which route is being used for a URL and/or domains, take a look at [my fork](https://github.com/Synchro/framework/tree/route-list-url) that does that much more accurately by actually resolving the routes rather than leaving you to match route patterns yourself.

**Comment by antonioribeiro** [comment]
So you are advertising your Laravel fork on the actual Laravel framework repository, @Synchro? 🤷‍♂️
Thanks, but no thanks!

**Comment by Synchro** [comment]
Only because I thought it might be useful for what it sounded like you were trying to do, and my PR for it was rejected. There's no reasonable way for me to turn it into an extension, so it's otherwise dead code.

**Pull request merged**
