### PR TITLE
Laravel pagination limit number of pages to show

### PR DESCRIPTION
**Pull request by xyxu**
Laravel pagination limit number of pages to show

### CODE REVIEW

**Comment by deleugpn** [comment]
What is this doing? What's the goal? Can you provide some description and a test-case for it?

**Comment by xyxu** [comment]
limited page number to settled result count:
$model->limit(1000)->paginate(50);

**Comment by d1urno** [comment]
Hi, I stumbled upon this today and I believe this is a basic feature. We are trying to build a multiple ranking system in wich we need to take the first 500 or 1000 items on different categories, so these limits need to be aswell paginated to be correctly shown.

**Comment by Grzegozr** [comment]
I have the same bug in laravel 7 ;(

**Comment by SUXUMI** [comment]
The best solution what I've found:

1. Create service provider
````
class ExtendCollectionServiceProvider extends ServiceProvider
{
    public function boot()
    {
        Collection::macro('paginate', function ($perPage, $total = null, $page = null, $pageName = 'page') {
            $page = $page ?: LengthAwarePaginator::resolveCurrentPage($pageName);

            return new LengthAwarePaginator($this->forPage($page, $perPage), $total ?: $this->count(), $perPage, $page, [
                'path' => LengthAwarePaginator::resolveCurrentPath(),
                'pageName' => $pageName,
            ]);
        });
    }
}
````

2. Register it in `config/app.php`  (https://laravel.com/docs/8.x/providers#registering-providers)
3. Use pagination through the collection

```
$users = User::latest()->limit(300)->get();
$users->paginate(30);
```

Source: https://laracasts.com/discuss/channels/laravel/how-to-limit-in-pagination-in-laravel?reply=650651
Author: [MichalOravec](https://laracasts.com/@MichalOravec)

**Pull request closed without merging**
