### PR TITLE
[5.5] Limit number of pages to show in pagination

### PR DESCRIPTION
**Pull request by xyxu**
Limit number of pages to show in pagination
#4629

### CODE REVIEW

**Comment by taylorotwell** [comment]
No plans on adding.

**Comment by JoelGross** [comment]
I am building an app that allows companies to post a certain number of job listings for recruiting. Companies can potentially post thousands of job listings, so I use paginate(50) to show them. However, companies pay for each listing, so if they are on a plan paying for 30 job listings, but have 50 total listings, I need to limit their results. When I try to do $jobs->take($countOfJobs)->paginate(50); this returns all results and ignore take. How should this be handled?

**Comment by xyxu** [comment]
$jobs->limit($countOfJobs)->paginate(50);

**Comment by ingGhost** [comment]
s

> just change take to limit
> $jobs->limit($countOfJobs)->paginate(50);

its doestn work, how possible for work? i hv same problem

**Pull request closed without merging**
