### PR TITLE
[5.4] Add helper function 'me()' as an alias for 'auth()->user()'

### PR DESCRIPTION
**Pull request by calebporzio**
I'm taking a queue from the common API endpoint: `/user/me`

I think `me()` is an appropriate metaphor for the concept of `auth()->user()`

I think people would love to start using this.

Thanks for taking a peek!
- Caleb

### CODE REVIEW

**Comment by decadence** [comment]
I used this helper but with name `user` :)

**Comment by devcircus** [comment]
It seems that 'me' makes sense in the context of an endpoint, as the end user will be interacting with it. A core 'me' helper seems to lose its meaning though.

**Comment by BrandonShar** [comment]
This seems pretty easy to define in any project where you want it, especially since there's already an example in the comments of someone who did the same thing but preferred a different name.

**Comment by KKSzymanowski** [comment]
I feel like `signedIn` or `loggedIn` would be a better name, because it makes more sense to reason about the code from the point of view of the interpreter, not the end-user. For example:
```php
if(signedIn()->subscriptionExpired()) {
    signedIn()->notify(new SubscriptionExpired);
}
```
It makes more sense to say:
> If the signed-in user's subscription has expired, notify him of that.

instead of

> If my subscription is expired, notify me.

Nevertheless, I like this idea.

**Comment by Kyslik** [comment]
I myself had this dilemma, I use `current` all over the place.

This is not going to be merged, cheers.

**Comment by taylorotwell** [comment]
I dunno this is pretty ballsy, lol. If anything I would prefer `user`.

**Comment by Kyslik** [comment]
@taylorotwell yea, `user` would be best with an exception that if you list multiple `users` you "want" to reserve `user`... `foreach users as user`.

**Pull request closed without merging**
