### PR TITLE
[8.x] Improve phpdoc types for column names and allow count() to accept an array of column names like get() does

### PR DESCRIPTION
**Pull request by williamdes**
- Improve phpdoc types for column names
- Allow count() to accept an array of column names like get() does

Fixes: #40337

### CODE REVIEW

**Comment by taylorotwell** [comment]
Couldn't there be Expression instances in some of these cases?

**Comment by williamdes** [comment]
> Couldn't there be Expression instances in some of these cases?

Probably, I will check this
Why was my pull request closed?

**Comment by driesvints** [comment]
@williamdes probably because Taylor thought this PR was incomplete. It's best that you send in a new PR when you've made any necessary adjustments.

**Comment by williamdes** [comment]
> @williamdes probably because Taylor thought this PR was incomplete. It's best that you send in a new PR when you've made any necessary adjustments.

This is terrible, hopefully I am not first time contributor, please guys use templates (github saved replies) for your replies if needed but say to the contributor about why it was closed. If I was a first time contributor I would probably go cry and think open source is not for me.
Just my two cents ;)

**Comment by driesvints** [comment]
But he gave a reason? Okay, it's debatable on how it was formed but he said he thought this was incomplete and therefor closed it?

**Comment by williamdes** [comment]
> But he gave a reason? Okay, it's debatable on how it was formed but he said he thought this was incomplete and therefor closed it?

Well I agree there was a question sent but I did not see a link between the comment and the closing :/. May I suggest that you first put back the PR in a draft state so the contributor can understand there is work to be done ?

**Comment by driesvints** [comment]
@williamdes it's just the way Taylor likes to work to not have too many PR's open lingering. He manages dozens of repositories and it's hard to get an overview if all those PR's are left open. This has been the way we work for many years now and I don't think we'll change that soon, sorry. You can attempt a new PR if you like.

**Comment by williamdes** [comment]
> @williamdes it's just the way Taylor likes to work to not have too many PR's open lingering. He manages dozens of repositories and it's hard to get an overview if all those PR's are left open. This has been the way we work for many years now and I don't think we'll change that soon, sorry. You can attempt a new PR if you like.

Sure, I do understand this too
I will open a new one soon

**Comment by williamdes** [comment]
> Couldn't there be Expression instances in some of these cases?

Hi @taylorotwell 
Can I make a first PR that includes my work and wait for me to have some time to finish the full support in another PR ?

Should I still target 8.x ?

**Comment by driesvints** [comment]
8.x isn’t maintained anymore. Best that you send it to 9.x

**Pull request closed without merging**
