### PR TITLE
[9.x] Remove view component from routing dependency

### PR DESCRIPTION
**Pull request by vladysta**
Relates to https://github.com/laravel/framework/issues/31781 and https://github.com/laravel/ideas/issues/2112

The only thing, I don't know how to test when there is no view (`Illuminate\Contracts\View\Factory`).
Can you please help me recreate `Illuminate\Contracts\Routing\ResponseFactory` without view dependency?

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now.

**Comment by vladyslavstartsev** [comment]
@taylorotwell when can I submit this PR again?

**Comment by driesvints** [comment]
@vladyslavstartsev probably not for a while. I think in general this is something we won't do any time soon, sorry.

**Comment by vladyslavstartsev** [comment]
@driesvints any explanation of this? I think it is worth doing for general quality of product.

**Comment by driesvints** [comment]
We just don't want to do these changes.

**Pull request closed without merging**
