### PR TITLE
Change the HTML lang attribute of the Laravel exception page to automatically detect the region

### PR DESCRIPTION
**Pull request by xushulang**
Change the HTML lang attribute of the Laravel exception page to automatically detect the region

### CODE REVIEW

**Comment by driesvints** [comment]
Exception messages aren't translated afaik so I don't see this being necessary? You can change this in your own app by publishing the views.

**Comment by xushulang** [comment]
> Exception messages aren't translated afaik so I don't see this being necessary? You can change this in your own app by publishing the views.

If not modified, the browser language translation prompt will pop up. Although this is a small detail, we hope that Laravel will become more and more perfect.

**Comment by crynobone** [comment]
> If not modified, the browser language translation prompt will pop up. Although this is a small detail, we hope that Laravel will become more and more perfect.

Wouldn't this make it more imperfect, the text is in English but the HTML attribute state that it is using the locale language. https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang

**Comment by driesvints** [comment]
Feel free to do this in your own app. Thanks

**Pull request closed without merging**
