### PR TITLE
[5.1] Fix undefined response exception in CrawlerTrait

### PR DESCRIPTION
**Pull request by joecohens**
There was 1 error:

1) ExampleTest::testBasicExample
ErrorException: Undefined property: Symfony\Component\HttpFoundation\Response::$exception

### CODE REVIEW

**Comment by taylorotwell** [comment]
Eh, it isn't quite right either. You want to pass the exception that actually occurred during the HTTP request lifecycle. What test did you write to cause this problem?

**Comment by joecohens** [comment]
@taylorotwell Sorry. It was totally my fault, I've upgraded a Laravel 5 app and override some of the app exception handler methods like the render method that now is being converted `toIlluminateResponse`. That might be good warning on the upgrade to 5.1 guide. Sorry again and thanks for the response.

**Comment by geocine** [comment]
@joecohens  I wonder how you resolved this issue. I am experiencing this error when running the sample tests on a fresh lumen install

**Comment by joecohens** [comment]
@geocine The problem was in the Exceptions/Handler.php when I stopped the app for returning me a illuminate response, I was throwing my own. You need to be sure you are returning a `toIlluminateResponse` https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Exceptions/Handler.php#L106

Let me know if that worked for you :)

**Comment by geocine** [comment]
@joecohens , thank you. I am not sure if this is the same case with **lumen**. I haven't done any modifications to `Exceptions/Handler.php` . Here is the issue I opened at https://github.com/laravel/lumen-framework/issues/226 .

**Pull request closed without merging**
