### PR TITLE
Use composer cache + dist installs

### PR DESCRIPTION
**Pull request by barryvdh**
Should speed up installs, especially since API limits on archives have been removed (see https://github.com/composer/composer/issues/4884#issuecomment-195229989 )

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Caching the .composer folder can be a bad ideas since composer's cache has quite a few bugs regarding branch aliases on packages not being updated without a cache flush, and package retags not being updated.

**Comment by GrahamCampbell** [comment]
It's best for us to test that the current uncached install works.

**Comment by barryvdh** [comment]
Are those still open Composer issues? Which one, I can look into it.

And whatabout just removing --prefer-source, as the zips are usually faster?

**Comment by barryvdh** [comment]
@GrahamCampbell Could you elaborate on the issues with caching? If it really does create problems, it can probably be fixed. (Regardless if Laravel uses it or not)

**Comment by barryvdh** [comment]
Also, if caching does cause problems, either caused by Composer or by vendor packages using incorrect syntax errors etc, it should be looked into, because when people deploy stuff, they will also cache their dependencies..

**Comment by GrahamCampbell** [comment]
Deploying stuff is no issue, because a lock file exists. The bugs relate to incorrect dependency resolving.

**Comment by barryvdh** [comment]
Do you have a link / issue reference / example travis build I can look into?

**Comment by GrahamCampbell** [comment]
Take a look at the composer.lock file from cachet. See how it keeps switching between broken auto-presenter tags. This is because one of us has a dodgie composer cache.

https://github.com/CachetHQ/Cachet

**Comment by GrahamCampbell** [comment]
This is the same effect we'd observe on travis if we didn't delete the cache.

**Pull request closed without merging**
