### PR TITLE
[6.x] Fix null in PHP7.4 version treated as an array

### PR DESCRIPTION
**Pull request by houseme**
fix 'Trying to access array offset on value of type null'  

https://github.com/laravel/framework/issues/30737

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmmm. Why was this ever null. I think we should crash the app with a better error message, telling users they must provide a path.

**Comment by houseme** [comment]
> Hmmm. Why was this ever null. I think we should crash the app with a better error message, telling users they must provide a path.

at Application->Laravel\Lumen\Concerns\{closure}(8, 'Trying to access array offset on value of type null', '/Users/housene/Documents/lanrenkeji/huhu-push/vendor/illuminate/support/ServiceProvider.php', 84, array('path' => '/Users/housene/Documents/lanrenkeji/huhu-push/vendor/illuminate/pagination/resources/views', 'namespace' => 'pagination'))
in ServiceProvider.php line 84

**Comment by driesvints** [comment]
Please provide some code and a test.

**Comment by GrahamCampbell** [comment]
> array('path' => '/Users/housene/Documents/lanrenkeji/huhu-push/vendor/illuminate/pagination/resources/views', 'namespace' => 'pagination'))

Because your code says path instead of paths.

**Comment by houseme** [comment]
> 

Trying to access array offset on value of type null

**Comment by driesvints** [comment]
Let's first try to figure out a bit if there's an issue at all. Feel free to respond in the linked issue with some code.

**Pull request closed without merging**
