### PR TITLE
[5.7] Start to test against PHP 7.3

### PR DESCRIPTION
**Pull request by carusogabriel**

### CODE REVIEW

**Comment by carusogabriel** [comment]
@Kyslik Nops. PHP 7.3 has reached "Release Candidates" already, so any new feature ou BC will come up. I'll fix the failure :)

**Comment by GrahamCampbell** [comment]
Could we fix the failing test and remove php 7.3 from allow failures? Also, perhaps we should test 5.5 and 5.6 on PHP 7.3 too?

**Comment by taylorotwell** [comment]
I don't totally like allowing failures especially on recent Laravel versions as I would rather just make sure the problems are fixed.

**Comment by carusogabriel** [comment]
> Could we fix the failing test and remove php 7.3 from allow failures?

(At least) Laravel 5.7 is ready for PHP 7.3 Our problem is with a dependency of a dependency: https://github.com/aws/aws-sdk-php/pull/1647. As soon as that PR gets merged, I'll bump our dependency here and we can deliver this PR.

> Also, perhaps we should test 5.5 and 5.6 on PHP 7.3 too?

This is up to the maintainers. Let me know what version should I target and prepare the patch :)

**Comment by taylorotwell** [comment]
I would just target 5.7. So we're still waiting on something upstream?

**Comment by carusogabriel** [comment]
> I would just target 5.7

:+1: 

> So we're still waiting on something upstream?

We're just waiting for https://github.com/aws/aws-sdk-php/pull/1647. As soon as that PR gets merged, I'll bump our dependency here and we can deliver this PR.

**Comment by laurencei** [comment]
Related issue: https://github.com/laravel/framework/issues/26204

**Comment by fititnt** [comment]
Seems to be not really a bug with laravel, but if using PHP 7.0.0 stable and module Xdebug 2.7.0beta1 (it is the latest as this date) the user can experience:

- "Arr::flatten produces error "Unsupported operand types" (As listed on #26204)
- On NGinx, error logs show "recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1,..."
- "Segmentation fault (core dumped)" if use `php artisan serve`

One way to mitigate this issue is temporary uninstall Xdebug instead of downgrade to PHP 7.2. On debian based distros, can try this:

`sudo apt remove php-xdebug`

**Comment by mfn** [comment]
> "Segmentation fault (core dumped)"

For anyone who can reproduce this and wants to help upstream (xdebug?) and you're on Ubuntu, you can:
- look in `/var/crash/` if you've a core dump
- install PHP with debug symbols
- unpack and run gdb with the PHP version against the core file
- get a backtrace
- report it upstream 😄 

(it's a bit more involved if you've never done this, but anyone interested can google this together)

**Comment by fititnt** [comment]
@mfn  Humm, I think I will open a new issue just for this, as is more complicated, and someone already opened one issue on https://bugs.xdebug.org/view.php?id=1600

**Comment by mfn** [comment]
>  I'm not 100% sure about if the file at /var/crash are the most recent

Note: I'm not an expert, but from my experience: they are not. Once a crash is recorded, the file seems to have some TTL before being (discard|overwritten?).

> Segmentation fault (core dumped)

At this point you should be able to get a backtrace with `bt` and, given you've debug symbols, should see a human readable backtrace.

**Comment by fititnt** [comment]
@mfn I opened a specific case to discuss this case. From there I think will be easier to go deeper on next days/weeks.

**Pull request closed without merging**
