### PR TITLE
[10.x] Add "Server has gone away" to DetectsLostConnection

### PR DESCRIPTION
**Pull request by Jubeki**
Closes https://github.com/laravel/framework/issues/51229

### CODE REVIEW

**Review by driesvints — APPROVED** [review]

**Comment by dennisprudlo** [comment]
@Jubeki out of curiosity, is case sensitivity necessary here? Would lowercasing the message also be an option or is it better to be explicit in case the same message in a different case means something completely different for some reason?

**Comment by driesvints** [comment]
Yes casing is important here. See the linked issue.

**Comment by dennisprudlo** [comment]
@driesvints yes, what I meant was that the fix was necessary because the error message is being transformed to "uppercase the first character" by an sql engine or a hosting provider. If another provider returns the message in say title case or the same provider uses this logic for other messages as well, another update will be necessary.

Can't this be simplified by lowercasing the strings before checking (this would require redundant messages)? Or is this too risky?

**Comment by driesvints** [comment]
@dennisprudlo I'm not sure myself. Your idea sounds good to me tbh. We could maybe try it out.

**Pull request merged**
