### PR TITLE
[5.8] added policy option in model make command

### PR DESCRIPTION
**Pull request by yamenarahman**
This pull request added the option of creating a policy for a model created by artisan console.

### CODE REVIEW

**Comment by ahinkle** [comment]
https://github.com/laravel/framework/pull/25787#issuecomment-424719124

**Comment by taylorotwell** [comment]
You can't change the shortcut for pivot on a patch release.

**Comment by taylorotwell** [comment]
Feel free to resubmit without that breaking change.

**Comment by yamenarahman** [comment]
@taylorotwell Thank you, what do you suggest shortcuts to be for pivot and policy options?

**Pull request closed without merging**
