### PR TITLE
[6.x] Alternative API for registering mutators and accessors

### PR DESCRIPTION
**Pull request by inxilpro**
Currently, the only way to define mutators and accessors is via the `getFooAttribute()` and `setFooAttribute()` naming convention. This means that it's impossible to dynamically register a mutator and it makes it more cumbersome to re-use logic. There are often times when it would be helpful to use the same mutation logic in different classes—for example, when working with UUIDs that are stored as binary in the database, or monetary values.

### A concrete example of the problem this solves:

We always store monetary values in the database as the currency’s smallest unit. For example, an event may have a registration fee stored as `registration_fee_cents`. We re-use this pattern in many places—a `cents` column on our billing plan, or on a billing transaction record.

Because of this, we **nearly always** have to do `$cents / 100` and `$dollars * 100` calculations, as most people want to see dollars. This results in `getRegistrationFeeDollars()` and `getPlanDollars()` and `getTransactionAmountDollars()` methods peppered throughout the code base that all do exactly the same thing.

### How this addresses the problem:

This PR introduces two new `Model` methods:

 - `public static function registerAccessor($attribute, Closure $accessor)`
 - `public static function registerMutator($attribute, Closure $mutator)`

This allows for dynamically defining mutators and accessors, and reusing mutation code. For example:

```php
trait MutatesCents
{
    protected static function registerCentMutator($cent_attribute, $dollar_attribute)
    {
        static::registerAccessor($dollar_attribute, function() use ($cent_attribute) {
            return $this->getAttribute($cent_attribute) / 100;
        });

        static::registerMutator($dollar_attribute, function($value) use ($cent_attribute) {
            $this->attributes[$cent_attribute] = $value * 100;
        });
    }
}

class MeetupEvent extends Model
{
    use MutatesCents;
    
    protected static function boot()
    {
        parent::boot();
        
        static::registerCentMutator('registration_fee_cents', 'registration_fee_dollars');
        static::registerCentMutator('admin_fee_cents', 'admin_fee_dollars');
    }
}

$event = new MeetupEvent([
    'registration_fee_cents' => 10000,
]);

assert($event->registration_fee_dollars === 100.00);

$event->registration_fee_dollars = 99.99;
assert($event->registration_fee_cents === 9999);
```

### CODE REVIEW

**Comment by rs-sliske** [comment]
been thinking of making something like this as a package but if it makes it into core that would be better i guess :)

only thing i can think is calling the variables accessors and mutators rather than get/setMutators.

**Comment by inxilpro** [comment]
I tried to keep the changes as minimal as possible, so I’m only using the term “accessor” in the public API. If this gets merged, there are some naming changes that might be appropriate for the `7.x` branch, but since the framework internally uses the terms “get mutator” and “set mutator” I thought it would be better to stick that that terminology internally.

**Comment by inxilpro** [comment]
But, I definitely went back-and-forth on the naming, so I’m certainly open to changing it.

**Comment by taylorotwell** [comment]
Why would you note just define a trait that contains the mutators you want to reuse and then attach that trait to the models you want them on? This feels like a hacked together way of accomplishing that exact same thing? We already have mechanisms in PHP for code re-use.

**Comment by inxilpro** [comment]
@taylorotwell that would require that you have a trait for each possible attribute name.

**Comment by lk77** [comment]
hello,

i think this can be really usefull.
It's not only about code re-use, traits works well for that, but it's mostly to allow dynamic accessor and mutator, and it can be really usefull.

**Pull request closed without merging**
