### PR TITLE
[5.6] Remove timeout alarm while the job finished

### PR DESCRIPTION
**Pull request by youmingdot**
This PR fixes the bug described below.

Queue work using POSIX alarm to walk timeout method when the job run timeout.
While, the alarm do not be remove when the job finished success.
So that, the alarm signal will be send while the job finished success.

As a result, when we use redis queue with blocking pop, after process blocked, the alarm will walk the timeout method and kill the queue worker.

```php
// Error logic.
while (true) {
    if (! $this->daemonShouldRun($options, $connectionName, $queue)) {
        $this->pauseWorker($options, $lastRestart);

        continue;
    }

    $job = $this->getNextJob(
        $this->manager->connection($connectionName), $queue
    );

    if ($this->supportsAsyncSignals()) {
        // Register the timeout handler using alarm signal.
        $this->registerTimeoutHandler($job, $options);
    }

    if ($job) {
        $this->runJob($job, $connectionName, $options);
    } else {
        $this->sleep($options->sleep);
    }

    // The alarm is still clocking at this moment.

    $this->stopIfNecessary($options, $lastRestart);
}
```

```php
'connections' => [
    'default' => [
        'driver'      => 'redis',
        'connection'  => 'default',
        'queue'       => 'default',
        'retry_after' => 60,
        'block_for'   => 5,
    ],
],
```

### CODE REVIEW

**Comment by sisve** [comment]
Renaming the `registerTimeoutHandler` method is a breaking change. Either keep the old name or target the master (5.7) branch.

**Comment by youmingdot** [comment]
@sisve This is a bug fix PR, so I think it must be merge to branch 5.6, and then, pick it to master branch.

**Comment by youmingdot** [comment]
@sisve I have reset the name of this method, just fix the bugs.

**Comment by taylorotwell** [comment]
These changes cause several Horizon tests to break. I would be curious to know why and it makes me hesitant to merge this as-is right now. Can you try your changes while running the Horizon tests and then re-open when you know what is causing that breakage?

**Pull request closed without merging**
