### PR TITLE
[10.x] Introduce new `Arr::take()` helper

### PR DESCRIPTION
**Pull request by ryangjchandler**
I reached for this today and could have sworn that it existed, but turns out that it's only a `Collection` method. I think it makes sense as an `Arr` helper too, since it reads a lot nicer than the underlying `array_slice()` syntax.

### CODE REVIEW

**Comment by ryangjchandler** [comment]
Ah, yeah not `limit()`, `take()` is the correct method name.

**Comment by taylorotwell** [comment]
Yeah I think that would be good.

**Comment by ryangjchandler** [comment]
@taylorotwell All done :^)

**Comment by taylorotwell** [comment]
Thanks!

**Comment by decadence** [comment]
Note: this doesn't preserve array keys while `Collection::take` does

**Pull request merged**
