### PR TITLE
[5.1] Allow Arr::get from objects that implements ArrayAccess

### PR DESCRIPTION
**Pull request by donnysim**
Allow to use Arr::get method on objects that implement ArrayAccess. It's something that I stumbled upon and is really useful.

### CODE REVIEW

**Comment by donnysim** [comment]
Looking at it again, it probably needs an additional check after the instanceof.

**Comment by taylorotwell** [comment]
Yeah it has no key check after instanceof check. Also needs unit tests.

**Comment by donnysim** [comment]
Will adjust it and write some tests once I have a free moment.

**Comment by GrahamCampbell** [comment]
Please send new features to 5.2. 5.1 is open for bug fixes only at this point.

**Pull request closed without merging**
