### PR TITLE
[5.2]Replace is_null instead

### PR DESCRIPTION
**Pull request by lianguan**

### CODE REVIEW

**Comment by ArjanSchouten** [comment]
Lol https://github.com/laravel/framework/issues/11111

**Comment by phecho** [comment]
@ArjanSchouten 
GrahamCampbell given the answer. Because we can. :laughing:

**Comment by ArjanSchouten** [comment]
Doesn't really matter in my opinion. Funny to reference that :smile:

**Comment by phecho** [comment]
Even if it's not a good style, they must be consistent.

**Comment by marktopper** [comment]
:-1: http://stackoverflow.com/a/8229005/2807030

**Comment by GrahamCampbell** [comment]
We have no official code style rule on null comparison.

**Pull request closed without merging**
