### PR TITLE
[5.5] Add console events

### PR DESCRIPTION
**Pull request by lucasmichot**
Add console events - Reboot of https://github.com/laravel/framework/pull/16355 (originally targeting 5.3)

---

Related to https://github.com/laravel/framework/pull/15613

### CODE REVIEW

**Comment by taylorotwell** [comment]
I would name it CommandFinished maybe instead of CommandTerminating.

**Comment by taylorotwell** [comment]
Ping.

**Comment by lucasmichot** [comment]
Renamed `CommandTerminating` to `CommandFinished`

**Comment by taylorotwell** [comment]
I'm curious why you did not pass the output interface as well?

**Comment by lucasmichot** [comment]
I've added this change : https://github.com/laravel/framework/pull/20298/commits/545c30d9158fd79126b3d336a97f4c7a07739fac
`OutputInterface` added to `CommandFinished`

Not sure it really makes sense to add it to `ArtisanStarting` too

**Comment by taylorotwell** [comment]
I would add it to both. I can't think of why we wouldn't.

**Comment by lucasmichot** [comment]
Added

**Comment by ctf0** [comment]
@lucasmichot can u update the docs about this as well ?

**Pull request merged**
