### PR TITLE
[6.x] Prevent error on key:generate command

### PR DESCRIPTION
**Pull request by zogxray**
Prevent fatal error on key:generate command and show error messsage "You must create .env file before set the application key".

### CODE REVIEW

**Review by tobiasthaden — CHANGES_REQUESTED** [review]
Instead of the empty `return`, you may return the error line.

**Comment by GrahamCampbell** [comment]
The current code is fine, if not better.

**Comment by zogxray** [comment]
@tobiasthaden that method annotated as "@return void", not string.

**Comment by GrahamCampbell** [comment]
Historically, Laravel has treated void as "don't use the return value of this method", rather than the more strict approach of "this method never returns anything", which explains why there is code in the core that returns within methods marked as having void return type.

**Comment by tobiasthaden** [comment]
There is already a `return` on line 39. So I think `string|null` is fine.

**Comment by zogxray** [comment]
@tobiasthaden +

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Pull request closed without merging**
