### PR TITLE
[10.x] Add database driver cache cleanup event

### PR DESCRIPTION
**Pull request by m-derakhshi**
Add cache driver database event to delete expired data

### CODE REVIEW

**Comment by ankurk91** [comment]
Does it work on all database engines?

**Comment by m-derakhshi** [comment]
this event works for MySQL database

for other databases, if you work, you can add events using these guides

sqlite: https://stackoverflow.com/questions/63219862/does-sqlite3-has-something-like-create-event-if-not-exists-event-name-on-sche

pgsql:https://www.postgresql.org/docs/current/event-trigger-example.html

sqlsrv: https://learn.microsoft.com/en-us/sql/t-sql/language-elements/waitfor-transact-sql?redirectedfrom=MSDN&view=sql-server-ver16

**Comment by johanrosenson** [comment]
`NOW()` and `UNIX_TIMESTAMP()` does not follow the timezone set in `config/app.php` so this cleanup would act differently than any cleanups done in PHP.

Cache cleanups done in code are usually using a lottery to make sure it doesn't run on every page load, take a look at `DatabaseLock` which have a `2/100` chance to run the cleanup, maybe the `DatabaseStore` should do something similar, but my guess is that it's not done for performance reasons (to avoid table locking for instance).

**Comment by m-derakhshi** [comment]
@johanrosenson
I did tests with several time zones
The expiration date field is stored UTC

**Comment by driesvints** [comment]
Feel free to add this to your own app, thanks.

**Pull request closed without merging**
