### PR TITLE
[5.1] Moved max and min functions into general collections

### LINKED ISSUE #9144: [proposal] Collection::min and Collection::max
@taylorotwell closed https://github.com/laravel/framework/issues/2155 after saying they'll be added to `4.*`, however they are not present currently in `5.*` either.

To clarify, this is [`Support\Collection`](https://github.com/illuminate/support/blob/master/Collection.php), not [`Eloquent\Collection`](https://github.com/illuminate/database/blob/master/Eloquent/Collection.php#L92) (which does have the max/min methods).

My proposal: shift the current max-min methods to `Support\Collection` as `Eloquent\Collection` extends from the support collection.

The reason being, sometimes I create collections without querying the DB.

### PR DESCRIPTION
**Pull request by tonglil**
Closes #9144 (and #2155 actually).

I put the functions in alphabetical order around the nearest functions, not sure what the order was otherwise.

### CODE REVIEW

**Comment by lucasmichot** [comment]
Already rejected https://github.com/laravel/framework/pull/5257#issuecomment-54912067

**Comment by GrahamCampbell** [comment]
It would be good if this could be considered again. We're over a year later now. :)

**Comment by lucasmichot** [comment]
Min and max tests should be moved too BTW @tonglil

**Comment by GrahamCampbell** [comment]
That's true. :)

**Comment by GrahamCampbell** [comment]
Though technically the test should be copied and the originals left too otherwise this would be known as a "refuckter".

**Comment by lucasmichot** [comment]
:-D

**Comment by taylorotwell** [comment]
Can someone show me the use case for this?

**Comment by lucasmichot** [comment]
@taylorotwell , We want to return a reponse :
a collection of items, and we want to set the Last-Modified header of the response, using the maximum date field of the items of this collection.

**Comment by taylorotwell** [comment]
It just seems a little odd... like if I have:

```
$collection = collect([1, 2, 3, 4, 5]);
```

How do I get the maximum value in the collection. I can't just call `max`?

**Comment by tonglil** [comment]
@taylorotwell The use case is that sometimes we create collections without querying. I'll work on a refactor that allows the optional key parameter for collections that won't use the key option.

@lucasmichot Sure I can copy the tests and add some more cases.

**Comment by taylorotwell** [comment]
Going to close this for now as it doesn't make sense for collections of primitives.

**Comment by tonglil** [comment]
@taylorotwell do I submit a new PR if I add a solution for primitives, eg: `->max()`?

**Comment by taylorotwell** [comment]
Yes.

**Pull request closed without merging**
