### PR TITLE
[5.3] Use blade syntax

### PR DESCRIPTION
**Pull request by idecardo**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I think this was intentionally avoided so non-blade files can be used.

**Comment by idecardo** [comment]
@GrahamCampbell Thank you. I'm a newbie and didn't know about that.

**Comment by GrahamCampbell** [comment]
Actually, that said, this file already has other blade syntax in it, so this PR is probably fine. :)

**Comment by taylorotwell** [comment]
Current version is fine.

**Pull request closed without merging**
