### PR TITLE
[5.5] Added domain helper to route

### PR DESCRIPTION
**Pull request by m1guelpf**
Originally sent by @robinvdvleuten to 5.4 branch in https://github.com/laravel/framework/pull/19243, submitting to 5.5 branch

### CODE REVIEW

**Comment by robinvdvleuten** [comment]
Nice! Thanks @m1guelpf!

**Comment by deleugpn** [comment]
@m1guelpf I opened a PR on your fork (https://github.com/m1guelpf/framework/pull/1) to add a specific test for this. The test fails on current master branch but passes on your master (with these changes).
I noticed that this PR corrects some of the tests that would be broken, but currently it doesn't really have a test for this specific added feature. I think if you merge the PR the commit should show up here automatically.

**Comment by m1guelpf** [comment]
@deleugpn Done!

**Comment by deleugpn** [comment]
PR

**Comment by ntzm** [comment]
I'd rather transitioning from 5.4 to 5.5 to be as simple as possible, but changing things like this will make it more difficult. I'm not saying I disagree with the feature, I'd just rather it not change the current behaviour to be honest.

**Comment by m1guelpf** [comment]
Maybe it would be better to keep current domain() functionality, but use the new functionality when passing a parameter, like:
``` php
domain()
```
would act as it does now, but
``` php
domain($domain)
```
would do new behaviour

**Comment by deleugpn** [comment]
I think it would be quite weird to have a method that return either a string or a Route object.

**Comment by robinvdvleuten** [comment]
I tried to stay as close to the Laravel API as possible; if you would like to add a prefix you call `prefix('/api')` but if you want to get the prefix of the route you'll call `getPrefix()`.

**Comment by decadence** [comment]
AFAIK now you can define domain only on route group. Does this PR bring opportunity to define domain for every single Route? Or I misunderstood something?

**Comment by deleugpn** [comment]
@decadence I would infer that it does since the test I wrote for this does exactly that.

**Comment by taylorotwell** [comment]
@m1guelpf yes you should make the existing domain method function as both a getter and setter depending on if an argument is passed. We do that in other parts of the framework occasionally.

**Comment by taylorotwell** [comment]
Eh, nevermind, I guess we have other get* methods on this class.

**Comment by joshmanders** [comment]
Excellent PR!

**Pull request merged**
