### PR TITLE
[5.0] Remove duplicate call to StringUtils::equals

### PR DESCRIPTION
**Pull request by JosephSilber**

### CODE REVIEW

**Comment by barryvdh** [comment]
Should you check if the header is set first? Now you could be decrypting an empty value, right?

**Comment by JosephSilber** [comment]
@barryvdh What would be the problem with that?

**Comment by barryvdh** [comment]
Won't that throw a `Illuminate\Encryption\DecryptException`? Why not just check the header value first? Something like this:

    $token = $request->input('_token');

    if ( ! $token && $header = $request->header('X-XSRF-TOKEN'))
    {
        $token = $this->encrypter->decrypt($header);
    }
    
    return StringUtils::equals($request->session()->token(), $token);

**Comment by JosephSilber** [comment]
@barryvdh Oh yeah. Thanks. Updated.

**Comment by GrahamCampbell** [comment]
?

**Comment by JosephSilber** [comment]
@taylorotwell why was this closed?

**Comment by JosephSilber** [comment]
@taylorotwell why was this closed? This code runs on every post request and should be optimized as much as possible.

**Comment by crynobone** [comment]
#7528

**Comment by JosephSilber** [comment]
@crynobone what am I supposed to see there?

**Comment by crynobone** [comment]
That PR has been merged, no?

**Comment by JosephSilber** [comment]
@crynobone I see. Interesting that that one was accepted after this one was closed.

Also, that one checks the `header` twice for some odd reason and looks broken to me.

If the `X-CSRF-TOKEN` header is present, [this conditional](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L59) will never run - since `$token` will be truthy - and the header will never be decrypted.

**Pull request closed without merging**
