### PR TITLE
[5.2] Fix SoftDeletes forceDelete return

### PR DESCRIPTION
**Pull request by jn-jairo**
The function forceDelete did not return the result.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is intended, as indicated by the return phpdoc.

**Comment by jn-jairo** [comment]
But in Model class the function forceDelete() return bool|null and the funtion delete() return bool|null, why the SoftDeletes change this to return always null?

**Comment by GrahamCampbell** [comment]
Meh, I don't mind I guess. You can't have it as `bool|void` though. `void` cannot be mixed since it means garbage, not null.

**Comment by jn-jairo** [comment]
I understand, my mistake, I forgot to change void to null. I change to bool|null is this correct now?

**Pull request merged**
