### PR TITLE
Laracasts now has over 1200 video tutorials

### PR DESCRIPTION
**Pull request by ahinkle**
https://laracasts.com/stats

### CODE REVIEW

**Comment by browner12** [comment]
can we just change to "contains many video tutorials" and be done with it?

**Comment by concept-core** [comment]
@ahinkle 1215.

**Comment by decadence** [comment]
Maybe @JeffreyWay will make API for getting this number? :)

**Comment by m1guelpf** [comment]
Maybe change it to `more than three days`?

**Comment by GuidoHendriks** [comment]
There isn't really an issue in changing this every now and then? It's not like it's ever wrong, 1215 is still "over 1100". The time we've all spend discussing this issue, would be enough time to change it manually for the next 5 years. 🙈

@m1guelpf What's the point of that? That's like changing it to "over 400"... It's well over 8 days of tutorials.

**Pull request closed without merging**
