### PR TITLE
[5.5] Autoload Package Providers

### PR DESCRIPTION
**Pull request by driesvints**
> Note for anyone who comes across this PR: the final implementation differs from the proposal below. Please check in the docs how auto-discovery works when 5.5 is released.

This PR adds autoloading functionality for packages. Package maintainers can define their providers through the `extra` key in their `composer.json` file and they will be automatically loaded by the framework, eliminating the need for developers to manually register them.

Example:

```json
{
    "extra": {
        "providers": "MyPackage\\MyServiceProvider"
    }
}
```

Or define multiple providers:

```json
{
    "extra": {
        "providers": [
            "MyPackage\\MyFirstServiceProvider",
            "MyPackage\\MySecondServiceProvider",
        ]
    }
}
```

### Benefits

- Finally development related packages with service providers don't need to be registered anymore in the `require` list. They may simple be added in `require-dev` and when deploying to production, they won't be loaded into the app anymore
- Installation for packages are done automatically, eliminating the need for developers to manually set things up

### Some Notes

- Functionality is on by default but can be opted out through a new config option
- Package providers need to be known up front so they're cached in a new `packages.php` file in `bootstrap/cache`
- The new `PackageAssetLoader` accepts any given key so you can still use it for other keys than just `providers`

### CODE REVIEW

**Comment by RamonSmit** [comment]
I like this idea :+1:

**Comment by m1guelpf** [comment]
@driesvints Can't 👍 enough!
Also, would this work with the existing cache artisan commands? (I mean, if I cache everything on deployment, this would still work...)

**Comment by driesvints** [comment]
@m1guelpf yeah, this falls outside the caching commands. It'll create a new `packages.php` file in `bootstrap/cache` that's being handled the same way as the `services.php` file.

**Comment by m1guelpf** [comment]
@driesvints And wouldn't this broke everything if a non-existent provider is provided? Is there some thind of check for this?

**Comment by driesvints** [comment]
@m1guelpf I added a new commit where we'll check first to see if the class exists before registering.

**Comment by m1guelpf** [comment]
@driesvints What will happen to the providers on the config/app.php file?

**Comment by driesvints** [comment]
@m1guelpf nothing. They'll continue to work as expected. That part remains untouched.

**Comment by Lloople** [comment]
This looks amazing, I'm wondering why it's not been done before

**Comment by bloggervista** [comment]
Yes this is great idea. Even if a single package have multiple providers which usually don't happen can it work?
And I also would like after installing package it prompts for vendor publish like interface :)
I like this idea and hope it gets merged in Laravel 5.5

**Comment by driesvints** [comment]
@bloggervista this indeed also works for multiple providers

**Comment by garygreen** [comment]
Few problems I have with this:

* What about certain packages that you would like to register based on a certain environment?
* You can't change the order your own providers or packages are registered in - personally I think package should be registered first, so your own providers can overwrite anything if required, i.e. your own providers should have the final say.
* What if packages have an `extra` field with `providers` in but it doesn't actually have anything to do with Laravel? It may break the whole process, just a consideration.
* This looks like it doesn't work for deferred service providers.

Personally, I would prefer to see some kind of `package:install` command and some 'plugin' based system for Laravel where developers can better and more easily integrate/install their application more easily. I know there is stuff like `->loadMigrationsFrom` and `->publishes` blah but I think that's all a bit clunky as well, the whole plugin system needs a bit of tweaking.

**Comment by driesvints** [comment]
@garygreen 

> What about certain packages that you would like to register based on a certain environment?

You can still turn off this behavior and use your own providers to have these checks. You can add a package to `require-dev` as well and not have it installed on production.

> You can't change the order your own providers or packages are registered in - personally I think package should be registered first, so your own providers can overwrite anything if required, i.e. your own providers should have the final say.

You can turn off this behaviour through the config option and register the providers manually in `app.php` if you like just like before. Nothing changes to the current behavior.

> What if packages have an extra field with providers in but it doesn't actually have anything to do with Laravel? It may break the whole process, just a consideration.

I thought of this and considered having an `laravel_providers` key instead but I'm not sure if we should do that. I think very few packages are using a key like that atm. It'll only break for very specific use cases. So I'd still go for just the `providers` key.

> This looks like it doesn't work for deferred service providers.

This is true & we're checking in on that. 

> Personally, I would prefer to see some kind of package:install command and some 'plugin' based system for Laravel where developers can better and more easily integrate/install their application more easily. I know there is stuff like `->loadMigrationsFrom` and `->publishes` blah but I think that's all a bit clunky as well, the whole plugin system needs a bit of tweaking.

This is a different discussion I believe :)

**Comment by taylorotwell** [comment]
@garygreen I have rewritten some things to address all of those concerns.

**Comment by garygreen** [comment]
Nice, look forward to seeing it. It would be nice if the `config:cache` command gets rid of the `packages` manifest file and instead puts all the the providers in the app stuff - that way it won't need to bootstrap an extra class and additional file on every request in production.

**Comment by taylorotwell** [comment]
It would be opcached in production anyways.

**Comment by a-komarev** [comment]
The only one thing  about this way to loading service providers. What if I want to use package but extend service provider with my own one? Is it possible?

**Comment by driesvints** [comment]
@a-komarev yes, there's a config option to turn off the behavior.

**Comment by driesvints** [comment]
@a-komarev and you'll be able to not auto-discover individual packages.

**Comment by taylorotwell** [comment]
All of the concerns expressed so far have been addressed. I am about to push the code.

**Comment by raftalks** [comment]
This is nice feature, however the order of loading them might need further discussion, for instance I tried using laravel passport and it seems to fail the concept as it expects to have auth class defined in the container, where as that doesn't seem to exists.

**Comment by driesvints** [comment]
@raftalks I think it's best that you open an issue on the passport repo for that

**Comment by bloggervista** [comment]
@driesvints  What what order will the plugin will be auto loaded ? I mean is it like adding service provider at last ?

**Comment by driesvints** [comment]
@bloggervista behavior was recently changed: https://github.com/laravel/framework/pull/19646

**Comment by bloggervista** [comment]
Thanks for info i was worried about it :)

**Comment by vesper8** [comment]
@driesvints what is the new config option to disable auto-discovery altogether ?

I am using the latest 5.5-dev and auto-discovery is enabled and working. But I can't seem to find any new option in any of the config files that have something to do with package discovery

**Comment by brunogaspar** [comment]
@vesper8 Try defining `'autoload_package_providers' => false,` on your `config/app.php` file and see if it works.

At least that's what's being used on this PR.

**Comment by driesvints** [comment]
@vesper8 you can use this:

```
"extra": {
    "laravel": {
        "dont-discover": [
            "*"
        ]
    }
},
```

Here are the docs: https://laravel.com/docs/master/packages#package-discovery

@brunogaspar Note the quote in the first comment: the implementation here has been greatly refactored.

**Comment by vesper8** [comment]
is there a way to list all the service providers and aliases that have been discovered ?

`php artisan package:discover` only lists the packages that contain service providers and/or aliases but since some packages can list multiple, or as I have now begun adding them myself for packages that are not adding it, it would be very useful to see what is actually being loaded

something like
`php artisan package:discovered-aliases` and `php artisan package:discovered-providers`
or `php artisan package:discover --detailed`

I know they are listed in /bootstrap/cache/packages.php but think it would be nice to have them listed in the console

**Pull request merged**
