### PR TITLE
[5.7] Add withAggregate

### PR DESCRIPTION
**Pull request by spyp**

### CODE REVIEW

**Comment by spyp** [comment]
https://github.com/laravel/framework/pull/25290

**Comment by jmarcher** [comment]
Can you check why do your tests fail?

**Comment by spyp** [comment]
Hi. can you tell me what error you got because i test them before PR . by the way as i mentioned i think my tests specially migrations and seed tables is hard for test . and i don't have idea that how can i create proper test against database.anyway if you can tell me you have syntax error or fail assertion.

**Comment by spyp** [comment]
you are right i didn't travis. i will try to fix tests

**Comment by taylorotwell** [comment]
Since last time we tried this it caused a lot of problems, I want to this vetted as a package first. Both the builder and relation class are Macroable, so you should be able to macro these methods into the classes. If that package works without issue for people I will merge this into the core.

**Comment by arxeiss** [comment]
This would be really nice feature. Hope it will get merged one day.

But for now, I found little workaround, which works in Laravel 5.7. Not probably the best solution, but it does the work
```php
User::withCount(['terms as term_sum' => function($query){
    $query->select(DB::raw('SUM(id)'));
}])
```

**Comment by dwightwatson** [comment]
I actually ended up breaking this out into a [package: `watson/aggregate`](https://github.com/dwightwatson/aggregate) - wasn't sure if @spyp was interested in doing it and hope it's alright with him - to use until it's reconsidered for the core.

**Comment by deleugpn** [comment]
@arxeiss mindblowing hacking. That workaround is amazing.

**Comment by cryoten** [comment]
@dwightwatson absolute life saver. I needed `withAvg` and decided to give myself a headache by doing some crazy `selectRaw` as I needed to support polymorphic relations. I decided to search as I couldn't be the only person to think about needing a method like this and here I am. Good work, I hope it will make it's way into core at some point in the future.

**Pull request closed without merging**
