### PR TITLE
[5.6] Simplify pagination

### PR DESCRIPTION
**Pull request by kawax**
I tried 5.6-dev and bootstrap 3. 
bootstrap3 + bootstrap-4.blade.php : No problem.
image
bootstrap-4.blade.php -> default.blade.php
simple-bootstrap-4.blade.php -> simple-default.blade.php

Even if you use custom pagination, there is no breaking change.
`views/vendor/pagination/default.blade.php`

### CODE REVIEW

**Comment by browner12** [comment]
Can you please more thoroughly explain what changes you have made, and why this is better?

**Comment by 36864** [comment]
How is this not a breaking change? You're adding classes where there weren't any. Bootstrap 3 didn't use any of those classes, so it's possible that someone using it also has custom classes with those names, which would likely break pagination after this change.

It's not a huge deal since this is going to 5.6, but it should be noted as a breaking change.

**Comment by kawax** [comment]
### 5.6 + bootstrap3
This setting is necessary in AppServiceProvider@boot if it remains as bootstrap-4.

```php
Paginator::defaultView('pagination::default');
Paginator::defaultSimpleView('pagination::simple-default');
```

People who want to use the strict bootstrap 3 will be asked to use custom pagination.
Or, add bootstrap-3.blade.php.

### 5.6 + custom pagination
I mainly want to solve this.
It seems likely to affect many projects using custom pagination.

```php
Paginator::defaultView('vendor.pagination.default');
```

This is not necessary if you keep `default`

**Comment by taylorotwell** [comment]
I still have no idea what you are saying. Yes, people will need to add two lines to service provider in 5.6 to continue using Bootstrap 3 views since Bootstrap 3 is the default.

**Comment by taylorotwell** [comment]
I added a `Paginator::useBootstrapThree()` method for convenience.

**Pull request closed without merging**
