### PR TITLE
[5.3] php-serialized value object attributes for Eloquent Model

### PR DESCRIPTION
**Pull request by halaei**
...(implementing with casts) **supporting inheritance**
### Sample usecase: chat states for Telegram Bots

``` php
class Chat extends Model {
    protected $casts = ['state' => State::class];
    ...
}
abstract class State {
    abstract public function handleTelegramUpdate($update, Chat $chat);
}
class DefaultState extends State {
    public function handleTelegramUpdate($update, Chat $chat)
    {
        if(/*the $update means a menu item is selected*/) {
            $chat->state = new SubMenuState(/*the selected menu item*/);
            //send the sub-menu to the chat.
        }
    }
}
class SubMenuState extends State {
    ...
}
```

The pseudo code of main Telegram update handler function does the following:

``` php
    $update = getTelegramUpdate();
    if ($update is a chat) {
        $chat = $chatRepository->findOrCreate($update->chat_id);
       ...
       if($chat->state === null) {
           (new DefaultState)->handleTelegramUpdate($update, $chat);
       } else {
          $chat->state->handleTelegramUpdate($update, $chat);
       }
       $chat->save();
    }
```

What do you think?

### CODE REVIEW

**Comment by halaei** [comment]
It is possible to do the same thing with accessors and mutators by the way!

**Comment by themsaid** [comment]
I think that's the same as https://github.com/laravel/framework/pull/13315

**Comment by halaei** [comment]
Sounds like  #13315 has more! By the way, have you seen this test? Someone might think it is not OK!
```php
    public function testModelDateAttributesAreImmutable()
    {
        $model = new EloquentModelCastingStub();
        $model->setDateFormat('Y-m-d H:i:s');

        $model->dateAttribute = '2016-01-03 10:11:12';
        $this->assertNotSame($model->dateAttribute, $model->dateAttribute);
        $model->dateAttribute->second = 0;
        $this->assertEquals(12, $model->dateAttribute->second);

        $model['dateAttribute'] = '2016-01-03 10:11:12';
        $this->assertNotSame($model['dateAttribute'], $model['dateAttribute']);
        $model['dateAttribute']->second = 0;
        $this->assertEquals(12, $model['dateAttribute']->second);
    }
```

**Comment by halaei** [comment]
This PR is based on php serialization and support inheritance as well! I guess it is not 100% similar to #13315

**Comment by taylorotwell** [comment]
Going to hold off on this in the core.

**Pull request closed without merging**
