### PR TITLE
[5.1] Revert iron changes

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by robclancy** [comment]
Because of this the documentation needs to be updated. Firstly the version it says is `~2.0|~4.0`. Which will put you on 4.0 which simply doesn't work because of #10828. Secondly I can't even find the documentation on how to use their old API on their site or anywhere so far. Which means with Laravel 5.1 you can't use iron.io if you start a new project in iron.io now.

**Comment by GrahamCampbell** [comment]
Thanks @robclancy. We'd accept a PR to the docs to point out that the laravel collective package can be used for newer versions, and L5.1 won't ship with support, and L5.2 has had all support dropped.

NB That's assuming laravel collective have actually dealt with that stuff as was the pan.

**Comment by robclancy** [comment]
Laravel 5.1 is LTS. You can't just have something stop working and say "nope we don't have that issue in the next version".

**Comment by robclancy** [comment]
Not to mention that https://github.com/LaravelCollective/iron-queue has this exact issue so upgrading to 5.2 isn't even an option (wasn't doing it anyway, I am on LTS for a reason).

It needs to be fixed in both places, why was the original fix removed?

**Comment by GrahamCampbell** [comment]
The original fix was removed because it was a mess and was broken, mainly due to the terrible versioning system and backwards structure of the ironmq php library.

**Comment by robclancy** [comment]
Is this also the reason support was dropped? Do you have an issue where the issues you had are explained? I need to recreate this fix properly.

**Comment by GrahamCampbell** [comment]
Unfortunately, it's scattered about a bit, sorry.

**Comment by GrahamCampbell** [comment]
Maybe just talk to Taylor on slack about this?

**Comment by robclancy** [comment]
Are the people at LaravelCollective very active? Best solution is it being fixed there and 5.1 docs updated to explain what happened and to use the package instead.

**Comment by GrahamCampbell** [comment]
> Are the people at LaravelCollective very active?

I can't really comment, lol.

> Best solution is it being fixed there and 5.1 docs updated to explain what happened and to use the package instead.

As I said, you'll have to convince Taylor, not me. ;)

**Comment by taylorotwell** [comment]
I think they are fairly active over there.

**Pull request merged**
