### PR TITLE
[5.5] Add clear method to collection

### PR DESCRIPTION
**Pull request by lucasmichot**
Add `clear` method to `\Illuminate\Support\Collection`

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why not just make a new collection?

**Comment by lucasmichot** [comment]
You could, this method is just a way to do it fluently

**Comment by morloderex** [comment]
Why not `return new self([])` instead of modifing the existing collection?

**Comment by taylorotwell** [comment]
Think I'll hold off on this.

**Pull request closed without merging**
