### PR TITLE
[5.3] Added setUnixMode and getUnixMode to Filesystem

### PR DESCRIPTION
**Pull request by verwer**
Added the possibility to set and get the Unix file permissions in Filesystem.

### CODE REVIEW

**Comment by sisve** [comment]
Could you show an example how this method will be called? This would only work if you first asserted that the filesystem wrapper you use is the locale filesystem, right? Anyone using S3 or Rackspace will get php errors about missing methods?

**Comment by GrahamCampbell** [comment]
@sisve This component is not to be confused with flysytem.

**Comment by GrahamCampbell** [comment]
totally different class, not even same interface: https://github.com/laravel/framework/blob/5.3/src/Illuminate/Filesystem/FilesystemAdapter.php

**Comment by taylorotwell** [comment]
Why not just call the method `chmod` to avoid confusion?

**Comment by beverio** [comment]
@taylorotwell And then with two separate methods (setChmod and getChmod)? Or just one method that accepts two arguments? If only the first is filled, it's a getter, else a setter?

**Comment by taylorotwell** [comment]
I would just have one method.

**Comment by marktopper** [comment]
```
$filesystem->chmod('file.txt'); // returns the chmod
$filesystem->chmod('file.txt', 777); // chmod 777 file.txt
```

Am I right @taylorotwell?

**Comment by beverio** [comment]
@taylorotwell @marktopper I just combined the two methods into one and renamed it to `chmod`.

@marktopper According to the PHP documentation you'll have to pass an octal value, so it would be:
```
$filesystem->chmod('file.txt', 0777);
```

**Pull request merged**
