### PR TITLE
[9.x] Protect against ambiguous columns

### PR DESCRIPTION
**Pull request by BenWalters**
Resolving https://github.com/laravel/framework/issues/43274

### CODE REVIEW

**Comment by driesvints** [comment]
Tests are failing here.

**Comment by driesvints** [comment]
Actually can you send this to 8.x since this is a bug fix?

**Comment by BenWalters** [comment]
@driesvints  sure, I can make the change on 8.x and recreate a PR. Any suggestions on the failing tests? On initial review it seems wrong that the `AuthEloquentUserProviderTest` should be using a stdClass to test retrieval of an Eloquent User?

**Comment by driesvints** [comment]
@BenWalters I don't have too much time to deep dive into this. I guess you'll need to add a mock reference for the new method call.

**Pull request closed without merging**
