### PR TITLE
[5.5] Add try-catch blade directives

### PR DESCRIPTION
**Pull request by jakebathman**
Applying changes noted in PR #20678 to 5.5

### CODE REVIEW

**Comment by jmarcher** [comment]
I don't think we should be catching exceptions inside views.
Either way I see no Win on this kind of helpers it is just exactly the same code written in blade directives.

```
@try
  // Something
@catch(\Exception $e)
  // Do another thing
@finally
  // Finally thing
@endtry
```
99 Characters


```
try{
  // Something
}catch(\Exception $e){
  // Do another thing
}finally{
  // Finally thing
}
```
95 Characters

**Comment by jakebathman** [comment]
The Blade directives allow for HTML printing straight in the template though, as with other Blade conditionals, such as with:

```
@try
  {{ $foo->bar() }}
@catch(\Throwable $e)
  <p>Some DOM</p>
@endtry
```

These are simplistic examples, but maybe you have a lot of PHP or complex checks inside the `@try`, which could be caught and have an HTML-only element printed when something is thrown.

**Comment by jmarcher** [comment]
But what I mean in the first instance is that exceptions are thrown by "logic" parts of your code, that means they should not be inside a view.

**Comment by devcircus** [comment]
I can see cases where it could come in handy, however it's quite simple to do already.

**Comment by sebastiandedeyne** [comment]
I wouldn't mind this without catching an exception object. Would be a nice alternative to checking for nested things.

Dealing with exception types and `finally` wouldn't make too much sense in views imo, but this syntax looks pretty clean to me:

```
@isset($foo->bar->baz)
  <p>{{ $foo->bar->baz }}</p>
@else
  <p>Nothing</p>
@endisset

@try
  <p>{{ $foo->bar->baz }}</p>
@catch
  <p>Nothing</p>
@endtry
```

**Comment by jakebathman** [comment]
Allowing the parameter in `@catch` to be optional would be an interesting change, so without a param it would just render to the highest level of possible error, like `<?php } catch(\Throwable $e) { ?>`. Might cause issues in PHP 5.6, with the split between Errors and Exceptions.

Dunno when `@finally` would be useful, but didn't want to leave it out since it's part of the PHP try-catch spec.

**Comment by joshmanders** [comment]
@jakebathman 5.5 requires php 7 so I don't think it'll have issues.

**Comment by jakebathman** [comment]
Forgot that until after I posted the comment, so it would definitely work to make the `@catch()` param optional and use a catch on `\Throwable` as the default.

**Comment by taylorotwell** [comment]
I didn't particularly have a problem with this to be honest but it seems the masses do. 🤷‍♂️

**Comment by jakebathman** [comment]
Thanks, all.

**Pull request closed without merging**
