### PR TITLE
[5.2] Allow table-qualified columns in pluck operations

### PR DESCRIPTION
**Pull request by JosephSilber**
Would allow you to do this:

``` php
User::join('posts', 'users.id', '=', 'posts.user_id')->pluck('users.name', 'posts.id');
```

### CODE REVIEW

**Comment by jchamberlain** [comment]
:+1: Previously discussed at #1069, and attempted in #4738 and #6663.

**Comment by rkgrep** [comment]
I think, aliases handling might be another very useful feature.

````php
User::join('others', 'users.id', '=', 'others.user_id')
    ->pluck('users.name', 'others.name as other_name');
````

Because currently I have to pluck such values out of resulting collection.

**Comment by JosephSilber** [comment]
I think adding aliases is taking it a bit too far.

If you need aliases, you *should* pluck the values out of the results:

```php
User::join('others', 'users.id', '=', 'others.user_id')
    ->get(['users.name', 'others.name as other_name'])
    ->pluck('name', 'other_name');
```

**Comment by JosephSilber** [comment]
@rkgrep Added.

**Comment by JosephSilber** [comment]
@GrahamCampbell what's going on with Travis and PHP 7?

**Comment by jchamberlain** [comment]
:+1: This is turning out really nice. I love the addition of aliases!

**Comment by rkgrep** [comment]
:+1: Nice!

**Pull request merged**
