### PR TITLE
[5.7] Added functions randomStates & randomState

### PR DESCRIPTION
**Pull request by gushh**
When using factories you can set the states to be random.

__Usage:__
`factory(App\Post::class, 10)->states(['unpublished', 'published'])->randomState()->create();`

__Or:__
`factory(App\Post::class, 10)->randomStates(['unpublished', 'published'])->create();`

### CODE REVIEW

**Comment by browner12** [comment]
Can you explain the use case here a little more? I feel like the common use here would be to make both published and unpublished `Post`s to check both states, where as with the randomness it's possible you could end up with only 'published' or only 'unpublished'.

```php
factory(App\Post::class, 10)->state(['published'])->create();
factory(App\Post::class, 10)->state(['unpublished'])->create();
```

If this feature were to be added, I feel like you're making the API a little confusing by allowing the 2 ways to enable this.  Why not just do away with the `randomState()` method and force everything through `randomStates()`?

Finally, before this is merged you will need to add some tests.

Thanks!

**Comment by sisve** [comment]
Introducing randomness into something people use for testing has some use-cases, but it requires a repeatable seeding process so that a test failure can be reproduced. I would expect test failures to output a seed, and some way to use this seed when executing phpunit to reproduce those "random" values again.

**Comment by deleugpn** [comment]
Looks like it brings more complexity than actually helps.

**Comment by taylorotwell** [comment]
You could build a helper in your own test cases to do this pretty easily.

**Pull request closed without merging**
