### PR TITLE
[4.2] Added More Filesystem Tests

### PR DESCRIPTION
**Pull request by manan-jadhav**

### CODE REVIEW

**Comment by CurosMJ** [comment]
How can I keep it from being complex? Guide me please. @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Just litteraly delete the things you know might be there. Don't try and scan for everything.

**Comment by CurosMJ** [comment]
Can I get a reason why this is closed ?

**Comment by GrahamCampbell** [comment]
I assume because it was a mess. If you can clean it up, then send it again.

**Comment by CurosMJ** [comment]
Cleaned it up, sent it again.

**Pull request closed without merging**
