### PR TITLE
[10.x] Feat: Add color_hex validation rule

### PR DESCRIPTION
**Pull request by nikopeikrishvili**
This PR adds a hex color validation rule to check that an attribute is a valid HEX color.
There are a couple of rules for HEX color to be valid:

**Standard 6-Digit Hex Codes:**
**Format: #RRGGBB**
Each pair of characters (RR, GG, BB) represents the intensity of red, green, and blue colors, respectively.
Each pair is written in hexadecimal format, ranging from 00 to FF.
Example: #FF0000 represents pure red, with maximum intensity of red and no green or blue.

**Short 3-Digit Hex Codes:**
**Format: #RGB**
A shorthand version where each character represents red, green, and blue, but with less precision.
Each character is in hexadecimal, ranging from 0 to F.
Example: #F00 is equivalent to #FF0000, both representing pure red.

Error message in case of error:
Screenshot 2023-11-20 at 21 30 06

### CODE REVIEW

**Comment by apih** [comment]
@nikopeikrishvili @taylorotwell Can this be extended to cover alpha channel? I have the same name of rule defined in my apps, and currently this built-in version will fail the input from my users, since the values will contain alpha channel as well.

Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color

**Comment by ahinkle** [comment]
Hey @apih,

I had a similar case -- which this PR will eliminate my custom rule. I contributed alpha channel support which was recently merged:

https://github.com/laravel/framework/pull/49069

**Comment by apih** [comment]
Hey @ahinkle, thanks for your PR. I noticed that your PR allowed 5 digits value to pass, which is not valid, so I opened a PR myself to fix that.

#49070

**Comment by ahinkle** [comment]
Hey thanks! Good catch.

**Comment by siarheipashkevich** [comment]
@nikopeikrishvili is it possible to set one of the formats for validation? For example I need to accept only:
Standard 6-Digit Hex Codes:
Format: #RRGGBB

**Comment by ahinkle** [comment]
You may have to write a custom rule for that. Laravel validation doesn't generally accept PRs of argument exclusions.

**Pull request merged**
