### PR TITLE
[8.x] Introducing Job Encryption

### PR DESCRIPTION
**Pull request by themsaid**
This PR adds a `UsesEncryption` interface. When the interface is used, laravel will encrypt the `command` inside the payload and decrypt it while running `CallQueuedHandler`.

Encrypting the command payload hides the job class properties which may hold sensitive information (API keys, passwords, personal information, etc...).

### CODE REVIEW

**Comment by crnkovic** [comment]
Is there any downside to using this all the time?

**Comment by themsaid** [comment]
@crnkovic The overhead of encryption/decryption plus the extra payload size might not be necessary for most jobs.

**Comment by crnkovic** [comment]
@themsaid With the implementation of AES operations directly into most modern CPUs' instruction set, OpenSSL encryption/decryption (which Laravel uses) runs very, very fast. There is no overhead. 2 MB of data gets encrypted and decrypted in 0.050s with OpenSSL using AES-256-CBC as cipher. But I (relatively) agree with the payload size though, especially when using in-memory store like redis (or SQS which has the payload limit) since the payload size will double when encrypted.

**Comment by taylorotwell** [comment]
@themsaid can we put an integration test on this?

**Comment by themsaid** [comment]
@taylorotwell done

**Pull request merged**
