### PR TITLE
[9.x] Improve output for some Artisan commands

### PR DESCRIPTION
**Pull request by sarukomine**
This PR is for #43543, to add the additional space after the output.

Before

Screenshot 2022-08-04 at 4 30 11 PM

After

Screenshot 2022-08-04 at 4 35 58 PM

Screenshot 2022-08-04 at 4 36 07 PM

### CODE REVIEW

**Comment by nunomaduro** [comment]
Remember this being an issue, when running different artisan commands, such as "migrate:fresh", "migrate:refresh", using different options such as "--seed", etc. Do you mind of testing all the possible combinations together?

**Comment by sarukomine** [comment]
> Remember this being an issue, when running different artisan commands, such as "migrate:fresh", "migrate:refresh", using different options such as "--seed", etc. Do you mind of testing all the possible combinations together?

@nunomaduro sure

**Comment by driesvints** [comment]
Tests need to be fixed here as well.

**Comment by sarukomine** [comment]
@nunomaduro I have improved `migrate:fresh` command, and I checked other commands look good, please let me know if I still missed some~

@driesvints Fixed tests, now passed all tests

**Pull request merged**
